# Broken plurals

## Introduction

In the previous chapter we introduced sound plurals, which are formed by appending suffixes to the singular noun. The singular noun in these plurals remains, more or less, intact when forming these plurals. The sound plurals correspond to English regular plurals which are formed by appending "s" to the singular noun. However, English has some plurals that are not formed by adding the plural ending "s". Here are some examples,

| Singular | Plural |
|:-----------|:-----------|
| man        | men        |
| woman      | women      |
| child      | children   |
| mouse      | mice       |

In these plurals, the singular noun is altered to form the plural.

Arabic also forms such plurals. They are called _broken_ plurals because the singular noun is not kept intact but its structure is, in most cases, altered, or "broken-up" when forming the plural.

While English only forms such plurals for a handful of nouns, Arabic forms broken plurals for many nouns.

## Review of word patterns and semi-flexible nouns

Before we begin our discussion about broken plurals, we will do a quick review of word patterns and semi-flexible nouns. This will, if [#allAh]{.trn2} wills, facilitate the explanation of broken plurals.

Most words in Arabic are formed from three letter roots. We use the paradigm root [فعل]{.arroot} to show word patterns. For example, the noun [رَجُل]{.ar} [rajul]{.trn} "a man" is formed from the root [رجل]{.arroot} on the pattern [فَعُل]{.ar} [faeul]{.trn}.

Most nouns in Arabic are _fully-flexible_. This means that, when indefinite, they take [n]{.trn}-marks and the i-state is shown by an [in]{.trn}-mark [◌ٍ]{.ar} at the end of the noun. For example, [رَجُل]{.ar} [rajul]{.trn} "a man" and [بَيْت]{.ar} [bayt]{.trn} "a house" are fully-flexible nouns. So, you can see, below, that they take [n]{.trn}-marks, and the indefinite i-state is indicated by an [in]{.trn}-mark [◌ٍ]{.ar}:

[ذَهَبَ رَجُلٌ إِلَىٰ بَيْتٍ.]{.ar}  
[pahaba rajulun EilA bayt.]{.trn}  
"A man went to a house."

Some nouns are _semi-flexible_. This means that they don't take [n]{.trn} marks, and also, the indefinite i-state is indicated by an [a]{.trn} mark [◌َ]{.ar}. Examples of such nouns are:

+ [غَضْبَىٰ^2^]{.ar} [gaDbA^2^]{.trn} _adj._ (fem.) "a very angry one~f~" from the root [غضب]{.arroot}
+ [صَحْرَاء^2^]{.ar} [SaHrAE^2^]{.trn} (fem.) "a desert~f~" from the root [صحر]{.arroot}

[ذَهَبَتْ جَارِيَةٌ غَضْبَىٰ إِلَىٰ صَحْرَاءَ.]{.ar}  
[pahabat jAriyatun gaDbA EilA SaHrAE.]{.trn}  
"A very angry girl went to a desert."

When definite, semi-flexible nouns are identical to fully-flexible nouns:

[ذَهَبَتِ ٱلْجَارِيَةُ ٱلْغَضْبَىٰ إِلَى ٱلصَّحْرَاءِ.]{.ar}  
[pahabati -ljAriyatu -lgaDbA Eila -SSaHrAE.]{.trn}  
"The very angry girl went to the desert."

All nouns that have the endings [اء]{.ar} and [ىٰ]{.ar}, that are extrinsic to the word's root, are semi-flexible.
[اء]{.ar} and [ىٰ]{.ar} are also feminine markers for singular nouns, just like [ة]{.ar}. (Except that [ة]{.ar} does not, in general, make a noun semi-flexible.) 

It is important to note that [ة]{.ar}, [اء]{.ar}, and [ىٰ]{.ar} are only feminine markers for singular nouns. We will see that they are also endings for broken plural nouns and, in that case, they are not feminine markers. However, 
[اء]{.ar} and [ىٰ]{.ar}, when endings for broken plural nouns, will make the broken plural nouns semi-flexible, just as they do for singular nouns.

Nouns that are of the patterns [فَفَافِف]{.ar} and [فَفَافِيف]{.ar} are also semi-flexible nouns. Here each letter [ف]{.ar} could be any letter of the alphabet. 
These are patterns for broken plurals, as we will see very soon. 
We had mentioned this in section\ \@ref(fafafif-diptote).

This concludes our short review of word patterns and semi-flexible nouns. We will use these concepts in our discussion of broken plurals.

## Patterns of the broken plural

Broken plurals occur in specific patterns, which we will show using the paradigm [فعل]{.arroot} for three-letter roots. Ararbic also has (comparatively fewer) four-letter roots and we will show patterns for broken plurals of four-letter roots using the paradigm root [فعلل]{.ar}. We will also use the letter [ف]{.ar}, when needed, to indicate any letter of the alphabet.

We now give all but the rarest broken plural patterns below. The singular and plural and given together separated by a colon character ":", the singular on the right, and its plural on the left.

1.  **[فُعَل]{.ar} [fueal]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[صُورَة: صُوَر]{.ar}  |a picture|[دَوْلَة: دُوَل]{.ar} |a dynasty/state
    |[أُمَّة: أُمَم]{.ar}   |a nation |[رُكْبَة: رُكَب]{.ar} |a knee

2.  **[فُعْل]{.ar} [fuel]{.trn}**. Examples:

    ||
    |---:|:-|---:|:-
    |[أَحْمَر^2^، حَمْرَاء^2^: حُمْر]{.ar}  |red    |[أَعْمَىٰ^2^، عَمْيَاء^2^: عُمْي]{.ar}  |blind
    |[أَصْفَر^2^، صَفْرَاء^2^: صُفْر]{.ar}  |yellow |[أَصَمّ^2^، صَمّاء^2^: صُمّ]{.ar}     |deaf
    |[أَسْوَد^2^، سَوْدَاء^2^: سُود]{.ar}  |black  |[أَبْكَم^2^، بَكْمَاء^2^: بُكْم]{.ar}  |mute
    |[أَبْيَض^2^، بَيْضَاء^2^: بِيض]{.ar}  |white  |[نَاقَة: نُوق]{.ar}               |a camel~f~

3.  **[فُعُل]{.ar} [fueul]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[كِتَاب: كُتُب]{.ar}  |a book|[رَسُول: رُسُل]{.ar}  |a messenger
    |[جِدَار: جُدُر]{.ar}  |a wall|[سَفِينَة: سُفُن]{.ar} |a ship
 
4.  **[فِعَل]{.ar} [fieal]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[قِطْعَة: قِطَع]{.ar}  |a piece|[سِيرَة: سِيَر]{.ar}  |a course of life

5.  **[فِعَال]{.ar} [fieAl]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[رَجُل: رِجَال]{.ar} |a man         |[ٱِمْرَأَة: نِسَاء]{.ar}   |a woman
    |[عَبْد: عِبَاد]{.ar} |a slave~m~    |[أَمَة: إِمَاء]{.ar}     |a slave~f~
    |[جَبَل: جِبَال]{.ar} |a mountain    |[أُنْثَىٰ^2^: إِنَاث]{.ar} |a female
    |[كَلْب: كِلَاب]{.ar} |a dog         |[صَغِير: صِغَار]{.ar}    |small/little
    |[حَسَن: حِسَان]{.ar} |good/handsome |[كَبِير: كِبَار]{.ar}    |big
    |[صَعْب: صِعَاب]{.ar} |difficult     |[كِرَام: كَرِيم]{.ar}    |noble

6.  **[فُعُول]{.ar} [fueUl]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[أَمْر: أُمُور]{.ar} |a matter         |[جَيْش: جُيُوش]{.ar} |an army
    |[بَيْت: بُيُوت]{.ar} |a house          |[قَلْب: قُلُوب]{.ar} |a heart
    |[حَقّ: حُقُوق]{.ar}  |a truth, a right |[رَأْس: رُؤُوس]{.ar} |a head
    |[مَلِك: مُلُوك]{.ar} |a king           |[شَهْر: شُهُور]{.ar} |a month
    |[سَيْف: سُيُوف]{.ar} |a sword          |[نَفْس: نُفُوس]{.ar} |a self
    |[شَيْخ: شُيُوخ]{.ar} |an old man       |[عَيْن: عُيُون]{.ar} |a (water) spring
    |[شَاهِد: شُهُود]{.ar}|a witness        ||

7.  **[فُعَّل]{.ar} [fueeal]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[رَاكِع، راكعَة: رُكَّع]{.ar} |a matter         |[غَائِب: غُيَّب]{.ar} |absent

8.  **[فُعَّال]{.ar} [fueeAl]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[قَارِئ: قُرَّاء]{.ar}  |a reader~m~       |[كَافِر: كُفَّار]{.ar}    |a disbeliever~m~
    |[تَاجِر: تُجَّار]{.ar}  |a trader~m~       |[جَاهِل: جُهَّال]{.ar}    |an ignorant one~m~
    |[عَامِل: عُمَّال]{.ar}  |a worker~m~       ||

9.  **[فَعَلَة]{.ar} [faealah]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[سَاحِر: سَحَرَة]{.ar}  |a magician~m~     |[قَاتِل: قَتَلَة]{.ar}   |a killer~m~
    |[عَامِل: عَمَلَة]{.ar}  |a labourer~m~     |[سَيِّد: سَادَة]{.ar}    |a chief~m~

10. **[فُعَلَة]{.ar} [fuealah]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[قَاضٍ: قُضَاة]{.ar}  |a judge~m~     |[رَاوٍ: رُوَاة]{.ar}   |a narrator~m~

11. **[فِعَلَة]{.ar} [fiealah]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[دُبّ: دِبَبَة]{.ar}  |a bear     |[قِرْد: قِرَدَة]{.ar}   |a monkey
    |[هِرّ: هِرَرَة]{.ar}  |a cat~m~   ||

12. **[فِعْلَة]{.ar} [fielah]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[أَخ: إِخْوَة]{.ar}  |a brother     |[فَتًى: فِتْيَة]{.ar}   |a young man

13. **[أَفْعُل]{.ar} [Eafeul]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[رِجْل: أَرْجُل]{.ar}  |a leg         |[شَهْر: أَشْهُر]{.ar}   |a month
    |[نَفْس: أَنْفُس]{.ar}  |a self        |[عَيْن: أَعْيُن]{.ar}   |an eye

14. **[أَفْعَال]{.ar} [EafeAl]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[بَاب: أَبْوَاب]{.ar}  |a door        |[مَيِّت: أَمْوَات]{.ar}    |dead
    |[قَلَم: أَقْلَام]{.ar}  |a pen         |[شَيْء: أَشْيَاء^2^]{.ar} |a thing
    |[قَدَم: أَقْدَام]{.ar}  |a foot        |[ٱِسْم: أَسْمَاء]{.ar}    |a name
    |[صَاحِب: أَصْحَاب]{.ar} |a companion~m~|[يَوْم: أَيَّام]{.ar}     |a day
    |[شَرِيف: أَشْرَاف]{.ar} |noble         |[عَدُوّ: أَعْدَاء]{.ar}    |an enemy
    |[عَيْن: أَعْيَان]{.ar}  |an eminent person ||

15. **[أَفْعِلَة]{.ar} [Eafeilah]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[لِسَان: أَلْسِنَة]{.ar}  |a tongue      |[طَعَام: أَطْعِمَة]{.ar} |a food
    |[إِمَام: أَئِمَّة]{.ar}   |a leader~m~   |[إِلَـٰه: آلِهَة]{.ar}  |a god

16. **[فَوَاعِل^2^]{.ar} [fawAeil^2^]{.trn}**. (Semi-flexible because of [فَفَافِف^2^]{.ar} pattern.) Examples:

    ||
    |---:|:---|---:|:---
    |[صَاحِبَة: صَوَاحِب^2^]{.ar} |a companion~f~      |[عَامِل: عَوَامِل^2^]{.ar} |a factor
    |[جَارِيَة: جَوَارٍ^2^]{.ar}  |a girl              |[شَاهِد: شَوَاهِد^2^]{.ar} |a corroborating evidence
    |[أَمْر: أَوَامِر^2^]{.ar}   |a command           |[خَاتَم: خَوَاتِم^2^]{.ar} |a ring (jewelry)
    |[نَادِرَة: نَوَادِر^2^]{.ar} |a joke, a witticism |[فَارِس: فَوَارِس^2^]{.ar} |a horseman

17. **[فَعَائِل^2^]{.ar} [faeAEil^2^]{.trn}**. (Semi-flexible because of [فَفَافِف^2^]{.ar} pattern.) Examples:

    ||
    |---:|:---|---:|:---
    |[حُرَة: حَرَائِر^2^]{.ar}      |a free woman|[جَزِيرَة: جَزَائِر^2^]{.ar} |an island
    |[ضَرّة: ضَرَائِر^2^]{.ar}      |a co-wife   |[رِسَالَة: رَسَائل^2^]{.ar} |a message
    |[حَدِيقَة: حَدَائِق^2^]{.ar}    |a garden    |[حَاجَة: حَوَائِج^2^]{.ar}  |a need
    |[حَقِيبَة: حَقَائِب^2^]{.ar}    |a bag       |[دَلِيل: دَلَائِل^2^]{.ar}  |an evidence
    |[كَبِيرَة: كَبَائِر^2^]{.ar}    |a major sin |[خَلِيفَة: خَلَائِف^2^]{.ar} |a successor

18. **[فِعْلَان]{.ar} [fielAn]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[غُلَام: غِلْمَان]{.ar}  |a boy     |[ثَوْر: ثِيرَان]{.ar}   |a bull
    |[جَار: جِيرَان]{.ar}   |a neighbor|[غُرَاب: غِرْبَان]{.ar}  |a crow
    |[أَخ: إِخْوَان]{.ar}    |a brother |[فَأْر: فِئْرَان]{.ar}   |a mouse
    
19. **[فُعْلَان]{.ar} [fuelAn]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[بَلَد: بُلْدَان]{.ar}  |a country     |[شُجَاع: شُجْعَان]{.ar} |a brave one
    |[جِدَار: جُدْرَان]{.ar} |a wall        |[شَابّ: شُبَّان]{.ar}   |a young man

20. **[فُعَلَاء]{.ar} [fuealAE]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[أَمِير: أُمَرَاء]{.ar} |a commander~m~ |[خَلِيفَة: خُلَفَاء]{.ar} |a caliph
    |[فَقِير: فُقَرَاء]{.ar} |a poor one~m~  |[عَالِم: عُلَمَاء]{.ar}  |a scholar~m~
    |[بَخِيل: بُخَلَاء]{.ar} |a miser~m~     |[شَاعِر: شُعَرَاء]{.ar}  |a poet~m~

21. **[أَفْعِلَاء]{.ar} [EafeilAE]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[نَبِيّ: أَنْبِيَاء]{.ar} |a prophet~m~  |[شَدِيد: أَشِدَّاء]{.ar} |a forceful one~m~
    |[صَدِيق: أَصْدِقَاء]{.ar}|a friend~m~   |[قَوِيّ: أَقْوِيَاء]{.ar} |a strong one~m~
    |[غَنِيّ: أُغْنِيَاء]{.ar} |a rich one~m~ |[شَقِيّ: أَشْقِيَاء]{.ar} |a wretched one~m~

22. **[فَعْلَىٰ]{.ar} [faelA]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[مَرِيض: مَرْضَىٰ]{.ar} |a sick one~m~  |[جَرِيح: جَرْحَىٰ]{.ar} |a wounded person
    |[أَسِير: أَسْرَىٰ]{.ar} |a captive      ||

23. **[فَعَالِي^2^]{.ar} [faeAlI^2^]{.trn}**. (Semi-flexible because of [فَفَافِف^2^]{.ar} pattern.) Examples:

    ||
    |---:|:---|---:|:---
    |[لَيْلَة: لَيَالٍ^2^]{.ar}|a night  |[أَرْض: أَرَاضٍ^2^]{.ar} |a land, an earth
    |[أَهْل: أَهَالٍ^2^]{.ar} |a family ||

24. **[فَعَالَىٰ^2^]{.ar} [faeAlA^2^]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[صَحْرَاء^2^: صَحَارَىٰ^2^]{.ar}|a desert  |[فَتْوَىٰ^2^: فَتَاوَىٰ^2^]{.ar} |a formal legal opinion
    |[يَتِيم: يَتَامَىٰ^2^]{.ar}|an orphan     |[هَدِيَّة: هَدَايَا^2^]{.ar}    |a gift

25. **[فَعِيل]{.ar} [faeIl]{.trn}** (rare). Examples:

    ||
    |---:|:---|---:|:---
    |[عَبْد: عَبِيد]{.ar}|a slave~m~  |[حِمَار: حَمِير]{.ar} |a donkey~m~

26. **[فُعُولَة]{.ar} [fueUlah]{.trn}** (rare). Examples:

    ||
    |---:|:---|---:|:---
    |[بَعْل: بُعُولَة]{.ar}|a husband  ||

27. **[فِعَالَة]{.ar} [fieAlah]{.trn}** (rare). Examples:

    ||
    |---:|:---|---:|:---
    |[حَجَر: حِجَارَة]{.ar}|a stone  ||

28. **[فَعَل]{.ar} [faeal]{.trn}** (rare). Examples:

    ||
    |---:|:---|---:|:---
    |[حَلْقَة: حَلَق]{.ar}|a circular ring  ||

29. **[فَعْل]{.ar} [fael]{.trn}** (very rare). Examples:

    ||
    |---:|:---|---:|:---
    |[صَاحِب: صَحْب]{.ar}|a companion  ||

30. **[فَفَافِف^2^]{.ar} [fafAfif^2^]{.trn}**. Includes the sub-patterns:

    + **[فَعَالِل^2^]{.ar} [faeAlil^2^]{.trn}**
    + **[أَفَاعِل^2^]{.ar} [EafAeil^2^]{.trn}**
    + **[تَفَاعِل^2^]{.ar} [tafAeil^2^]{.trn}**
    + **[مَفَاعِل^2^]{.ar} [mafAeil^2^]{.trn}**

    Examples:

    ||
    |---:|:---|---:|:---
    |[ثَعْلَب: ثَعَالِب^2^]{.ar}  |a fox         |[تَجْرِبَة: تَجَارِب^2^]{.ar} |an experience
    |[عَنْكَبُوت: عَنَاكِب^2^]{.ar}|a spider      |[مَسْجِد: مَسَاجِد^2^]{.ar}  |a mosque      
    |[دِرْهَم: دَرَاهِم^2^]{.ar}  |a dirham      |[مَعَانٍ: مَعْنًى^2^]{.ar}   |a meaning     
    |[جَوْهَر: جَوَاهِر^2^]{.ar}  |a gem         |[مَحَالّ: مَحَلَّة^2^]{.ar}   |a locality
    |[إِصْبَع: أَصَابِع^2^]{.ar}  |a finger      |[مَعِيشَة: مَعَاىِش^2^]{.ar} |a means of subsistence      
    |[أَنْمُلَة: أَنَامِل^2^]{.ar} |a finger tip  ||

31. **[فَفَافِيف^2^]{.ar} [fafAfIf^2^]{.trn}**. Includes the sub-patterns:

    + **[فَعَالِيل^2^]{.ar} [faeAlIl^2^]{.trn}**
    + **[أَفَاعِيل^2^]{.ar} [EafAeIl^2^]{.trn}**
    + **[تَفَاعِيل^2^]{.ar} [tafAeIl^2^]{.trn}**
    + **[مَفَاعِيل^2^]{.ar} [mafAeIl^2^]{.trn}**
    + **[يَفَاعِيل^2^]{.ar} [yafAeIl^2^]{.trn}**
    + **[فَوَاعِيل^2^]{.ar} [fawAeIl^2^]{.trn}**

    Examples:

    ||
    |---:|:---|---:|:---
    |[سُلْطَان: سَلَاطِين^2^]{.ar}  |a sultan         |[إِعْصَار: أَعَاصِير^2^]{.ar}  |a whirlwind
    |[شَيْطَان: شَيَاطِين^2^]{.ar}  |a devil          |[تَأْرِيخ: تَوَارِيخ^2^]{.ar}  |a history
    |[سِكِّين: سَكَاكِين^2^]{.ar}   |a knife          |[تَصْوِير: تَصَاوِير^2^]{.ar}  |a picture
    |[دِينَار: دَنَانِير^2^]{.ar}  |a [dInAr]{.trn2} |[مِفْتَاح: مَفَاتِيح^2^]{.ar}  |a key       
    |[مِسْكِين: مَسَاكِين^2^]{.ar}  |a needy person   |[مَلْعُون: مَلَاعِين^2^]{.ar}  |an accursed one~m~
    |[كُرْسِيّ: كَرَاسِيّ^2^]{.ar}    |a chair          |[يُنْبُوع: يَنَابِيع^2^]{.ar}  |a (water) spring
    |[أُمْنِيَّة: أَمَانِيّ^2^]{.ar}   |a wish           |[جَامُوس: جَوَامِيس^2^]{.ar}  |a buffalo

32. **[فَعَالِلَة]{.ar} [faeAlilah]{.trn}**. Examples:

    ||
    |---:|:---|---:|:---
    |[أُسْتَاذ: أَسَاتِذَة]{.ar}  |a professor  |[مَلَك: مَلَائِكَة]{.ar}  |an angel
    |[فَيْلَسُوف: فَلَاسِفَة]{.ar} |a philosopher|[جَبَّار: جَبَابِرَة]{.ar} |a tyrant

Note the following from the above broken plural patterns and examples:

+ Both common nouns and adjectival nouns form broken plurals.

+ There are comparatively fewer broken plurals for female intelligent beings than for male intelligent beings. We will expand on this in a subsequent section.

+ Some patterns of the broken plural are also patterns singular nouns. For example, the pattern [فِعَال]{.ar} [fieAl]{.trn} has both singular nouns, like [كِتَاب]{.ar} [kitAb]{.trn} "a book" and broken plurals, like [رِجَال]{.ar} [rijAl]{.trn} "men"

+ The broken plural patterns [فِعْلَان]{.ar} [fielAn]{.trn} and [فُعْلَان]{.ar} [fuelAn]{.trn} are fully-flexible nouns. Although they end with the [ان]{.ar} ending which is extrinsic to the root, they are not semi-flexible nouns. Only singular adjectival nouns that end with an extrinsic [ان]{.ar} on the pattern [فَعْلَان]{.ar}, and that also fulfil the other conitions listed in section\ \@ref(adjectival-noun-an-diptote), are semi-flexible.

+ There is often a correlation between the pattern of a singular noun and the pattern of its plural.

  Sometimes this correlation is very strong:

  + All singular nouns of the patterns [أَفْل^2^]{.ar} [Eafeal^2^]{.trn} and [فَعْلَاء^2^]{.ar} [faelAE]{.trn} that denote colors and physical characteristics, have broken plurals on the pattern [فُعْل]{.ar} [fuel]{.trn}. Example:

    |Singular | Plural|
    |:---|:---|
    |[أَحْمَر^2^، حَمْرَاء^2^]{.ar}  "red"  |[حُمْر]{.ar} |
    |[أَبْكَم^2^، بَكْمَاء^2^]{.ar}  "mute" |[بُكْم]{.ar} |

  + Singular nouns that have four or more consonant letters (excluding [ة]{.ar}) regularly form their broken plurals on the patterns [فَفَافِف^2^]{.ar} and [فَفَافِيف^2^]{.ar}. The pattern [فَفَافِيف^2^]{.ar} is used when there is an intermendiate long vowel between the consonants. Examples:

    |Singular | Plural|
    |:---|:---|
    |[إِصْبَع]{.ar} "a finger" |[أَصَابِع^2^]{.ar} |  
    |[مِفْتَاح]{.ar}  "a key"  |[مَفَاتِيح^2^]{.ar}|

  + Singular nouns of the patterns [فِعْلَة]{.ar} [fielah]{.trn} and [فُعْلَة]{.ar} [fuelah]{.trn} regularly form their broken plurals on the pattern [فِعَل]{.ar} [fieal]{.trn} and [فُعَل]{.ar} [fueal]{.trn} respectively. Examples:
    
    |Singular | Plural|
    |:---|:---|
    |[قِطْعَة]{.ar}  "a piece"|[قِطَع]{.ar} |
    |[رُكْبَة]{.ar}  "a knee" |[رُكَب]{.ar} |

  Other times, this correlation is more like a tendency:

  + Singular nouns on the pattern [فَعِيلَة]{.ar} [faeIlah]{.trn} tend to form broken plurals on the pattern [فَعَائِل^2^]{.ar} [faeAEil^2^]{.trn}. Examples:

    |Singular | Plural|
    |:---|:---|
    |[حَدِيقَة]{.ar}     "a garden"|[حَدَائِق^2^]{.ar} |
    |[حَقِيبَة]{.ar}     "a bag"   |[حَقَائِب^2^]{.ar} |

  + Singular nouns on the pattern [فَاعِل]{.ar} [fAeil]{.trn}, that denote male intelligent beings, tend to form broken plurals on the pattern [فُعَّل]{.ar} [fueeal]{.trn}, [فُعَّال]{.ar} [fueeAl]{.trn}, and [فَعَلَة]{.ar} [faealah]{.trn}. Examples:

    |Singular | Plural|
    |:---|:---|
    |[غَائِب]{.ar}  "absent"     |[غُيَّب]{.ar}  |
    |[قَارِئ]{.ar}  "a reader~m~"|[قُرَّاء]{.ar} |
    |[قَاتِل]{.ar}  "a killer~m~"|[قَتَلَة]{.ar} |

  + Singular nouns on the pattern [فَاعِل]{.ar} [fAeil]{.trn} and [فَاعِلَة]{.ar} [fAeilah]{.trn}, that don't denote male intelligent beings, tend to form broken plurals on the pattern [فَوَاعِل]{.ar} [fawAeil]{.trn}. Examples:

    |Singular | Plural|
    |:---|:---|
    |[صَاحِبَة]{.ar}  "a companion~f~"|[صَوَاحِب^2^]{.ar} |
    |[عَامِل]{.ar}   "a factor"      |[عَوَامِل^2^]{.ar} |

    [فَارِس]{.ar} [fAris]{.trn} "a horseman" with the plural [فَوَارِس^2^]{.ar} is one of a number of exceptions.

+ Some words have roots that have the same letter repeated in the root. These are called _doubled_ roots. 

  + For example:
  
    |Root | Word | Pattern
    |:----|:--|:--
    |[دبّ]{.arroot}|[دُبّ]{.ar}   "a bear"            | [فُعْل]{.ar}
    |[حلّ]{.arroot}|[مَحَلَّة]{.ar} "a locality"        | [مَفْعَلَة]{.ar}
    |[أمّ]{.arroot}|[إِمَام]{.ar} "a leader"          | [فِعَال]{.ar}
    |[حقّ]{.arroot}|[حَقّ]{.ar}   "a truth, a right"  | [فَعْل]{.ar}
    |[هرّ]{.arroot}|[هِرّ]{.ar}   "a cat~m~"          | [فِعْل]{.ar}

  We will discuss doubled roots in detail in chapter\ \@ref(doubled-roots). For now we will mention the following:

  + The repeated letter in the word root may get doubled or separated in the word's pattern. Frequently, the repeated letter may be doubled in the singular, and separated in the plural. Examples:

    |Singular | Plural|
    |:---|:---|
    |[حَقّ]{.ar}   "a truth, a right"|[حُقُوق]{.ar} |
    |[دُبّ]{.ar}   "a bear"          |[دِبَبَة]{.ar} |
    |[هِرّ]{.ar}   "a cat~m~"        |[هِرَرَة]{.ar} |

    The reverse also occurs, where the repeated letter may be separated in the singular, and doubled in the plural. Examples:

    |Singular | Plural|
    |:---|:---|
    |[إِمَام]{.ar}    "a leader~m~"|[أَئِمَّة]{.ar} |

  + The doubled letter may modify the basic word pattern somewhat. For example:

    |Root | Word pattern | Expected word | Actual word
    |:-|:--|:--|:--
    |[شدّ]{.arroot} |[أَفْعِلَاء^2^]{.ar} |$\times$\ [أَشْدِدَاء^2^]{.ar} |[أَشِدَّاء^2^]{.ar}
    |[حلّ]{.arroot} |[مَفَاعِل^2^]{.ar}  |$\times$\ [مَحَالِل^2^]{.ar}  |[مَحَالّ^2^]{.ar} 
    |[صمّ]{.arroot} |[أَفْعَل^2^]{.ar}  |$\times$\ [أَصْمَم^2^]{.ar}  |[أَصَمّ^2^]{.ar} 

+ We have previously learned that the endings [ة]{.ar}, [اء]{.ar}, and [ىٰ]{.ar} that are extrinsic to the word's root are feminine markers for singular nouns. These extrinsic endings also occur for broken plurals but there, they are _not_ feminine markers.

  In fact, in a sort of role reversal, the endings [ة]{.ar} in a broken plural tends to indicate that the singular is a masculine noun. And the [اء]{.ar} ending is only for broken plurals of male intelligent beings.  Examples:

  |Singular | Plural|
  |:---|:---|
  |[لِسَان]{.ar} "a tongue"      |[أَلْسِنَة]{.ar} |
  |[هِرّ]{.ar}   "a cat~m~"      |[هِرَرَة]{.ar}  |
  |[أَمِير]{.ar} "a commander~m~"|[أُمَرَاء]{.ar} |
  |[صَدِيق]{.ar} "a friend~m~"   |[أَصْدِقَاء]{.ar}|

+ There often exist multiple broken plurals for the same singular noun. Many times, in fact, a singular noun may have a sound plural in addition to one or more broken plurals. Examples:

  |Singular | Plural
  |:---|---:
  |[شَهْر]{.ar} |[أَشْهُر، شُهُور]{.ar}
  |[عَيْن]{.ar} |[أَعْيُن، عُيُون، أَعْيَان]{.ar}
  |[عَامِل]{.ar}|[عَامِلُونَ، عَوَامِل^2^، عَمَلَة، عُمَّال]{.ar}

  We will discuss how to manage these multiple plurals in a subsequent section.

+ Occasionally, multiple singular nouns will share the same broken plural. Examples:

  |Singular | Plural
  |:---|---:
  |[مَكْتَب]{.ar} "an office" |[مَكَاتِب^2^]{.ar}
  |[مَكْتَبَة]{.ar} "a library"|[مَكَاتِب^2^]{.ar}

  Context will then tell us which of two meanings is intended.

+ The letters [ء]{.ar}, [ا]{.ar}, [و]{.ar}, and [ي]{.ar} are considered _weak_ letters. Words that one or more these weak letters in their roots are called _defective_ words. We will discuss defective words more completely in later chapters, if [#allAh]{.trn2} wills. For now, we will note the following:

  + Weak letters often get interchanged with one another when going from a singular to a plural. Examples:

    |Root |Singular | Plural|
    |:--|:---|:---|
    |[أرخ]{.arroot} | [تَأْرِيخ]{.ar} | [تَوَارِيخ^2^]{.ar}
    |[نوق]{.arroot} | [نَاقَة]{.ar}  | [نُوق]{.ar}
    |[ثور]{.arroot} | [ثَوْر]{.ar}   | [ثِيرَان]{.ar}

  + Weak letters can affect surrounding vowels. For example:

    |Root | Word pattern | Expected word | Actual word
    |:-|:--|:--|:--
    |[بيض]{.arroot} |[فُعْل]{.ar} |$\times$\ [بُيْض]{.ar} |[بِيض]{.ar}

  + The weak letter [ي]{.ar}, when followed by the [ىٰ]{.ar} ending, usually modifies (in writing) it to an [ِEalif]{.trn} instead. The pronunciation is the same. For example:

    |Root | Word pattern | Expected word | Actual word
    |:-|:--|:--|:--
    |[هدي]{.arroot} |[فَعَالَىٰ^2^]{.ar} |$\times$\ [هَدَايَىٰ^2^]{.ar} |[هَدَايَا^2^]{.ar}

  + A [ي]{.ar} at the end of a word, in some states, gets ommitted  and replaced by an [in]{.trn}-mark [◌ٍ]{.ar} on the preceding letter. This happens even when the [ي]{.ar} is extrinsic to the root, and even if the word is semi-flexible (and thus would not normally accept an [n]{.trn} mark). Examples:

    |Root | Word pattern | Expected word  | Actual word 
    |:-|:--|:--|:--
    |[قضي]{.arroot} |[فَاعِل]{.ar} |$\times$\ [قَاضِي]{.ar} |[قَاضٍ]{.ar}
    |[جري]{.arroot} |[فَوَاعِل^2^]{.ar} |$\times$\ [جَوَارِي^2^]{.ar} |[جَوَارٍ^2^]{.ar}
    |[ليل]{.arroot} |[فَعَالِي^2^]{.ar} |$\times$\ [لَيَالِي^2^]{.ar} |[لَيَالٍ^2^]{.ar}

+ If there are more than four consonant letters in a word, then only four of them are selected to form the broken plural. For example:

  |Singular | Plural
  |:---|---:
  |[عَنْكَبُوت]{.ar} "a spider" |[عَنَاكِب^2^]{.ar}

+ Some words have individual irrgularities as well and we will discuss them below:

  + The word [ٱِمْرَأَة]{.ar} and its plural [نِسَاء]{.ar} are both irregular and we will discuss them separately in chapter\ \@ref(irregular-nouns).

  + The broken plural [أَشْيَاء^2^]{.ar} [EacyAE]{.trn} (of the singular noun [شَيْء]{.ar} [cayE]{.trn} "a thing") is irregular in that it is semi-flexible. Otherwise its pattern [أَفْعَال]{.ar} [EafeAl]{.trn} is regularly fully-flexible.

  + The broken plural of the singular noun [مَلَك]{.ar} [malak]{.trn} "an angel" is [مَلَائِكَة]{.ar} [malAEikah]{.trn}. It is on the pattern [فَعَالِلَة]{.ar} [faeAlilah]{.trn}. But it is unusual in that the plural has an extra letter [ء]{.ar} that is missing in the singular. This is because the singular has a lesser-used variant: [مَلْأَك]{.ar} [malEak]{.trn} that is used to form the plural.

  + The broken plural of the singular noun [دِينَار]{.ar} "a [dInAr]{.trn2}" is [دَنَانِير^2^]{.ar}. It is on the pattern [فَعَالِيل^2^]{.ar}. It is irregular in that there are two [ن]{.ar}'s in the plural whereas the singular only has one.

  There are other words as well with similar irregularities.

## Co-existence of multiple broken plurals

We noted that there are often multiple broken plurals for the same singular noun. Many singular nouns even have a sound plural in addition to one or more broken plurals. Here are some examples.

  |Singular | Meanings | Plural
  |:---|:---|---:
  |[جِدَار]{.ar}|a wall              |[جُدُر، جُدْرَان]{.ar}
  |[شَهْر]{.ar} |a month             |[أَشْهُر، شُهُور]{.ar}
  |[أَمْر]{.ar} |a matter; a command |[أُمُور، أَوَامِر^2^]{.ar}
  |[عَيْن]{.ar} |an eye; a (water) spring; an eminent person |[أَعْيُن، عُيُون، أَعْيَان]{.ar}
  |[عَامِل]{.ar}|a worker; a labourer; a factor              |[عَامِلُونَ، عَوَامِل^2^، عَمَلَة، عُمَّال]{.ar}

We will deal with the co-existence of sound and broken plurals in the next section. In this section, we will explain the existence of multiple broken plurals, and when one of them is preferred or required to be used over the other. Basically, there could be a few things going on:

1. Sometimes it is more or less optional which of the multiple broken plurals to use. For example, the singular noun [جِدَار]{.ar} has two broken plurals:
[جُدُر، جُدْرَان]{.ar}
Either could be used, more or less, interchangeably.

2. Other times, the singular has multiple distinct meanings, and each of these distinct meanings is associated with its own broken plural(s). Here are some examples:

   + The word [أَمْر]{.ar} [Eamr]{.trn} has two distinct meanings, each with it's own plural:

     i. "a matter". This has the broken plural [أُمُور]{.ar} [EumUr]{.trn}.
     ii. "a command". This has the broken plural [أَوَامِر^2^]{.ar} [EawAmir^2^]{.trn}.

   + The word [عَيْن]{.ar} [Eayn]{.trn} has multiple distinct meanings. There are three main meanings, and they share the broken plural with each other in the following way:

     i. "an eye". This meaning primarily uses the plural [أَعْيُن]{.ar} [Eaeyun]{.trn} but it may also use the plural [عُيُون]{.ar} [euyUn]{.trn}, and rarely also the plural [أَعْيَان]{.ar} [EaeyAn]{.trn}.
     ii. "a (water) spring". This meaning primarily uses the plural [عُيُون]{.ar} [euyUn]{.trn} but it may also use the plural [أَعْيُن]{.ar} [Eaeyun]{.trn}, and rarely also the plural [أَعْيَان]{.ar} [EaeyAn]{.trn}.
     iii. "an eminent person". This meaning only uses the plural [أَعْيَان]{.ar} [EaeyAn]{.trn}.

   + The word [عَامِل]{.ar} [eAmil]{.trn} has the following meanings and plurals:
     
     i. "a worker~m~". Generally, this has the plural [عُمَّال]{.ar} [eummAl]{.trn}.
     ii. "a labourer~m~". This uses the plural [عَمَلَة]{.ar} [eamalah]{.trn}.
     iii. "a factor". This uses the plural [عَوَامِل^2^]{.ar} [eawAmil^2^]{.trn}.

3. Arabic has what are known as _plurals of fewness_. These are specific patterns that may (sometimes, but not always) be used when the persons or things denoted by the plural are only a few (ten or less) and not many. These patterns are:

   i. [فِعْلَة]{.ar} [fielah]{.trn}
   ii. [أَفْعُل]{.ar} [Eafeul]{.trn}
   iii. [أَفْعَال]{.ar} [EafeAl]{.trn}
   iv. [أَفْعِلَة]{.ar} [Eafeilah]{.trn}

   For example:
   
   i. [شَهْر]{.ar} [cahr]{.trn} "a month", plurals: [أَشْهُر، شُهُور]{.ar}. The plural [أَشْهُر]{.ar} could be used when the number of months are only a few (ten or less), and the plural [شُهُور]{.ar} could be used when the number of months are large.
   ii. The plurals [أَعْيُن]{.ar} and [عُيُون]{.ar} of the word [عَيْن]{.ar} could also possibly be used similarly in this manner for the meanings of "an eye" and "a (water) spring".

   Of course, this distinction only applies when the singular noun has additional plurals, not just one from the above four patterns. If a noun has only one of the about four plural patterns then it may be used indiscriminately and will not indicate any limitation in number.

## Co-existence of sound and broken plurals

Some nouns have both sound and broken plurals for more or less the same meaning. Here are some examples:

|Singular | Meaning | Sound plural |Broken plural
|:---|:---|:---|:---
|[قَاتِل]{.ar}  | a killer       |[قَاتِلُونَ]{.ar} |[قَتَلَة]{.ar}
|[كَافِر]{.ar}  | a disbeliever  |[كَافِرُونَ]{.ar} |[كُفَّار]{.ar}
|[كَبِير]{.ar}  | a big one~m~   |[كَبِيرُونَ]{.ar} |[كِبَار]{.ar}
|[صَغِير]{.ar}  | a small one~m~ |[صَغِيرُونَ]{.ar} |[صِغَار]{.ar}
|[رَاكِع]{.ar}  | one who bows~m~|[رَاكِعُونَ]{.ar} |[رُكَّع]{.ar}
|[رَاكِعَة]{.ar} | one who bows~f~|[رَاكِعَات]{.ar} |[رُكَّع]{.ar}
|[صَاحِبَة]{.ar} | a companion~f~ |[صَاحِبَات]{.ar} |[صَوَاحِب^2^]{.ar}
|[جَارِيَة]{.ar} | a girl         |[جَارِيَات]{.ar} |[جَوَارٍ^2^]{.ar}

We will treat the [Un]{.trn} and [At]{.trn} sound plurals separately.

### [Un]{.trn} plurals and broken plurals

Remember from chapter\ \@ref(sound-plurals) that [Un]{.trn} plurals are, with very few exceptions, only used for male intelligent beings.

If a singular noun has both an [Un]{.trn} sound plural and one or more broken plurals


## The broken plural and patterns

Remember that Arabic nouns are derived from roots which are usually three, but sometimes four or more, letters. Also that three-letter roots and word patterns are exemplified using the template root [فعل]{.arroot}. And that four-letter roots are exemplified using the template root [فعلل]{.arroot}. For example, the word [رَجُلٌ]{.ar} [rajulun]{.trn} has the root [رجل]{.arroot} and is of the pattern [فَعُلٌ]{.ar} [faeulun]{.trn}. 

Arabic broken plurals fall into patterns. The plural of [رَجُلٌ]{.ar} [rajulun]{.trn} is [رِجَالٌ]{.ar} [rijAlun]{.trn}. The pattern of this plural is [فِعَالٌ]{.ar} [fieAlun]{.trn}, which is a common plural pattern. Another broken plural with this pattern is [جِبَالٌ]{.ar} [jibAlun]{.trn} "mountains" plural of [جَبَلٌ]{.ar} [jabalun]{.trn} "a mountain".

Note that, plurals of the pattern [فِعَالٌ]{.ar} [fieAlun]{.trn} are fully-changing so they have an [n]{.trn}-mark when indefinite, which will depend on the state of the plural. Here is an example sentence:

[صَعَدَ رِجَالٌ جًبَالًا]{.ar}  
[Saeada -rrijAlu jibAlan.]{.trn}  
"The men went up the mountain."

There are other plural patterns which are non-fully-changing, for example, [أَغْنِيَاءُ]{.ar} [EagniyAEu]{.trn}, plural of [غَنِيٌ]{.ar} [ganiyyun]{.trn} "rich", of the pattern [أَفْعِلَاءُ]{.ar} [EafeilAEu]{.trn}.  Note that this plural pattern ends with [اء]{.ar} which is external to the root [فعل]{.arroot}. [اء]{.ar}, [ة]{.ar}, and [ىٰ]{.ar}, when external to the root, are feminine markers for singular nouns, but not for plural nouns.  However, just like for singular nouns, when a broken plural ends with [اء]{.ar} or [ىٰ]{.ar} which is external to its root, the broken plural will be non-fully-changing.

Unfortunately, there is usually not much relation between the pattern of the singular and the pattern of the plural. So you should memorize the plural of a noun with its singular.

## Common patterns for the broken plural

Here are some of the more common broken plural patterns:

Pattern | Example
:-------------|:---------------------------------
[أَفْعَالٌ]{.ar} [EafeAlun]{.trn} | [أَعْمَالٌ]{.ar} [EaemAlun]{.trn} "deeds" plural of [عَمَلٌ]{.ar} [eamalun]{.trn} "a deed"
[فُعُولٌ]{.ar} [fueUlun]{.trn}   | [قُلُوبٌ]{.ar} [qulUbun]{.trn} "hearts" plural of [قَلْبٌ]{.ar} [qalbun]{.trn} "a heart"
[فِعَالٌ]{.ar} [fieAlun]{.trn}   | [رِجَالٌ]{.ar} [rijAlun]{.trn} "men" plural of [رَجُلٌ]{.ar} [rajulun]{.trn} "a man"
[فُعُلٌ]{.ar} [fueulun]{.trn}    | [كُتُبٌ]{.ar} [kutubun]{.trn} "books" plural of [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book"
[فَعْلَىٰ]{.ar} [faelA]{.trn} (non-fully-changing)    | [أَسْرَىٰ]{.ar} [EasrA]{.trn} "captives" plural of [أَسِيرٌ]{.ar} [EasIrun]{.trn} "a captive"
[فُعَلَاءُ]{.ar} [fueAlAEu]{.trn} (non-fully-changing) | [عُلَمَاءُ]{.ar} [eulAmAEu]{.trn} "(male) scholars" plural of [عَالِمٌ]{.ar} [eAlimun]{.trn} "a (male) scholar"
[أَفْعِلَاءُ]{.ar} [EafeilAEu]{.trn} (non-fully-changing) | [أَغْنِيَاءُ]{.ar} [EagniyAEu]{.trn} "rich"
[فُعْلَانٌ]{.ar} [fuelAnun]{.trn} | [بُلْدَانٌ]{.ar} [buldAnun]{.trn} "countries" plural of [بَلَدٌ]{.ar} [baladun]{.trn} "a country"
[فِعْلَانٌ]{.ar} [fielAnun]{.trn} | [غِلْمَان]{.ar} [gilmAn]{.trn} "boys" plural of [غُلَام]{.ar} [gulAm]{.trn} "boy"
[فَعَالِلُ]{.ar} [faeAlilu]{.trn} | a

Note the following:

+ Some broken plurals end with [ة]{.ar}, and [اء]{.ar} and [ىٰ]{.ar} which are external to the word's root. These are feminine markers for singular nouns but not for plural nouns.
+ [اء]{.ar} and [ىٰ]{.ar} that external to the word's root cause broken plurals to be non-fully-changing.
+ There are other non-fully-changing patterns for broken plurals: [mafAeilu]{.trn}, etc.
+ The broken plural patterns [فُعْلَان]{.ar} and [فِعْلَان]{.ar} are fully-changing, even though they end with an [ان]{.ar} which is external to the word's root. This ending only makes a noun non-fully-changing if it is a proper noun, or a singular qualitative noun, along with other conditions, that we listed, which must also be satisfied.
<!-- should mafAeilu be separate from faeAlilu? -->


## Existence of broken plurals for types of nouns

The use of broken plurals is a little complicated, and their use in poetry and rhetorical style can be somewhat different from normal usage. Here we will describe whether they are found, and how to use them for the different noun categories according to normal usage.

1. Designative nouns:
   a. Male rational beings: Very commonly found. Examples:
      + [غِلْمَانٌ]{.ar} [gilmAnun]{.trn} "boys", plural of [غُلَامٌ]{.ar} [gulAmun]{.trn} "a boy".
      + [عُلَمَاءُ]{.ar} [eulamAEu]{.trn} "(male) scholars", plural of [عَالِمٌ]{.ar} [eAlimun]{.trn} "a (male) scholar".
   b. Female rational beings: Uncommon but not unfound. Examples:
      + [نِسَاءٌ]{.ar} [nisAEun]{.trn} "women", plural of [ٱِمْرَأَةٌ]{.ar} [EimraEatun]{.trn} "a woman". This is the most commonly used broken plural for female rational beings. Yet it is irregular in the sense that the singular and plural are formed from different roots ([مرء]{.arroot} and [نسو]{.arroot} respectively.)
      + [إِمَاءٌ]{.ar} [EimAEun]{.trn} "slave-women", plural of [أَمَةٌ]{.ar} [Eamatun]{.trn} "a slave-woman"
      + [حَرَائِرُ]{.ar} [HarAEiru]{.trn} "free-women", plural of [حُرَّةٌ]{.ar} [Hurratun]{.trn} "a free-woman".

      Typically, though, female rational beings will use the [At]{.trn} sound plural, for example [عَالِمَاتٌ]{.ar} [eAlimAtun]{.trn}, plural of [عَالِمَةٌ]{.ar} [eAlimatun]{.trn} "a (female) scholar".
   c. Non-rational beings (both masculine and feminine): very common. Examples:
      + [هِرَرٌ]{.ar} [hirarun]{.trn} "cats", plural of [هِرَّةٌ]{.ar} [hirratun]{.trn} "a cat".
      + [سُيُوفٌ]{.ar} [suyUfun]{.trn} "swords", plural of [سَيْفٌ]{.ar} [sayfun]{.trn} "a sword".
2. Qualitative nouns:
   a. Male rational beings: Very common. Examples:
      + [أَغْنِيَاءُ]{.ar} [EagniyAEu]{.trn}, plural of [غَنِيٌ]{.ar} [ganiyyun]{.trn} "rich (masc.)".
      + [كِرَامٌ]{.ar} [kirAmun]{.trn}, plural of [كَرِيمٌ]{.ar} [karImun]{.trn} "noble, generous (masc.)".
      + [ٱَلرِّجَالُ ٱلْأَغْنِيَاءُ كِرَامٌ.]{.ar}  
        [EarrijAlu -lEagniyAEu kirAmun.]{.trn}  
        "The rich men are generous."
   b. Female rational beings: Apart from a few exceptions, this is almost unused in normal usage. The [At]{.trn} plural is used instead, for example [ عَالِمَاتٌ كَرِيمَاتٌ]{.ar} [eAlimAtun karImAtun]{.trn} "noble (female) scholars".
   c. Non-rational beings: also unused in normal usage. The [At]{.trn} plural is used instead, as we'll see soon, if Allah wills. REMOVE: The feminine singular is used for describers in a noun-phrase or for descrptive nouns in the information of a sentence. The [At]{.trn} plural is used otherwise. Example:  
      [ٱَلْكُتُبُ ٱلْكَبِيرَةُ ثَقِيلَةٌ وَٱلصَّغِيرَاتُ خَفِيفَةٌ.]{.ar}  
      [Ealkutubu -lkabIratu vaqIlatun wa-SSagIrAtu xafIfatun.]{.trn}  
      "The big books are heavy and the small ones are light."

## Existence of more than one broken plural for a noun

Some nouns have multiple broken plurals that can be used, more or less, interchangeably. For example:

+ [طُلَّابٌ]{.ar} [TullAbun]{.trn} and [طَلَبَةٌ]{.ar} [Talabatun]{.trn} plurals of [طَلِبٌ]{.ar} [Talibun]{.trn} "a (male) student".
+ [شُهُورٌ]{.ar} [cuhUrun]{.trn} and [أَشْهُرٌ]{.ar} [Eachurun]{.trn} plurals of [شَهْرٌ]{.ar} [cahrun]{.trn} "a month".

In some cases one of these plurals may be used to indicate a larger quantity and the other a smaller quantity, but this rule is not worth worrying about much for now.

Other nouns have multple broken plurals too but here each broken plural is used for a different meaning. For example:

+ [أَمْرٌ]{.ar} [Eamrun]{.trn} can mean both :
  1. "a matter, an affair", pluralized as [أُمُورٌ]{.ar} [EumUrun]{.trn} "matters, affairs"
  2. "a command, an order", pluralized as [أَوَامِرُ]{.ar} [EawAmiru]{.trn} (non-fully-changing) "commands, orders".  

## Co-existence of sound and broken plurals for the same noun

There are many nouns which can be pluralized with both sound plurals and broken plurals. For example,

+ [عَالِمٌ]{.ar} [eAlimun]{.trn} "a (male) scholar" can be pluralized using the sound [Un]{.trn} plural as [عَالِمُونَ]{.ar} [eAlimUna]{.trn} as well as with the broken plural [عُلَمَاءُ]{.ar} [eulamAEu]{.trn}.
+ [كَافِرٌ]{.ar} [kAfirun]{.trn} "a (male) disbeliever" can be pluralized using the sound [Un]{.trn} plural as [كَافِرُونَ]{.ar} [kAfirUna]{.trn} as well as with the broken plurals [كُفَّارٌ]{.ar} [kuffArun]{.trn} and [كَفَرَةٌ]{.ar} [kafaratun]{.trn}.

It is also possible to use both sound [Un]{.trn} and broken plurals in the same phrase and sentence. For example,

[ٱَلرِّجَالُ ٱلْأَغْنِيَاءُ كَرِيمُونَ]{.ar}  
[EarrijAlu -lEagniyAEu karImUna.]{.trn}  
"The rich men are generous."

For now, we recommend that you prefer to use the broken plural when possible, even if a word can form the sound [Un]{.trn} plural. Although more difficult for the beginner, this is more common in normal usage. In the vocabulary lists that we provide, we will typically not provide sound [Un]{.trn} plurals, even if they are technically possible, unless they are commonly used.

## Using plural in place of a dual with dual attached pronoun

For saying 
[وجوهكما]{.ar}

instead of 

[وجهاكما]{.ar}

for "Your~2~ faces"

See [إن تَتُوبَا إِلَى ٱللَّهِ فَقَدْ صَغَتْ قُلُوبُكُمَا) التحريم: 4]{.ar} in Ibn Ashoor

## Using verbs and pronouns with plurals

### Plurals of rational beings

In the previous chapter we gave the rule of using doer-modifications with verbs for sound plurals of rational being doers. The rule is similar for broken plurals of rational being doers:

1. If the broken plural doer is placed before the verb or is not mentioned, then the plural doer-modification corresponding to the gender of the singular doer is employed. For example, [ٱَلرِّجَالُ ذَهَبُوا.]{.ar} "The men went.", [ٱَلنِّسَاءُ ذَهَبْنَ.]{.ar} "The women went.", [ذَهَبُوا.]{.ar} "They~masc.~ went."
2. If the broken plural doer is placed after the verb, then the singular doer-modification corresponding to the gender of the singular doer is employed. For example, [ذَهَبَ الرِّجَالُ]{.ar} "The men went.", [ذَهَبَتِ ٱلنِّسَاءُ]{.ar} "The women went."

This is the most common usage. However, another possibility is allowed which is uncommon and usually only found in older works. That is the usage of the feminine singular verb doer modification for broken plurals that refer to both male and female rational being doers. So we can have [ذَهَبَتِ ٱلرِّجَالُ.]{.ar} and [ٱَلرِّجَالُ ذَهَبَتْ.]{.ar} and [ذَهَبَتِ ٱلنِّسَاءُ.]{.ar} and [ٱلنِّسَاءُ ذَهَبَتْ.]{.ar}.

For now, we recommend that you stick to the more common usage in your own sentences.

Note that this rule is only for the verb doer-modifications. Detached and attached pronouns for rational beings generally match the noun they refer to in number and gender. For example,

[ذَهَبَ ٱلرًّجَالُ إِلَىٰ بُيُوتِهِمْ وَذَهَبَتِ ٱَلنِّسَاءُ إِلَىٰ بُيُوتِهِنَّ.]{.ar}  
"The men went to their houses and then women went to their houses."

[هُمْ رِجَالٌ وَهُنَّ نِسَاءٌ.]{.ar}  
[hum rijAlun wahunna nisAEun.]{.trn}  
"They~pl.\ masc.~ are men and they~pl.\ fem.~ are women."

### Plurals of non-rational beings

The usage of pronouns and verb doer-modifications for plural non-rational beings is somewhat complicated and depends on the type of the plural and the quantity of doers intended by the plural. 

The most general rule, however, is that it is preferred to treat plurals of non-rational beings as feminine singular. So the feminine singular pronouns [هِيَ]{.ar} [hiya]{.trn}/[ـهَا]{.ar} [-hA]{.trn} and feminine singular verb doer modification [فَعَلَتْ]{.ar} [faealat]{.trn} are used. It doesn't matter if the singular of the plural noun is masculine or feminine or if the plural doer comes before or after the verb. This general rule applies to both sound plurals and broken plurals of non-rational beings. For example,

[ٱلشَّجَرَاتُ سَقَطَتْ وَٱلْحَيَوَانَاتُ أَكَلَتْ مِنْ ثَمَرِهَا.]{.ar}  
"The trees fell and the animals ate from their fruit."

[ظَهَرَتِ ٱلنُّجُومُ فِي ٱلسَّمَاءِ وَلَمَعَتْ وَنَظَرَ إِلَيْهَا ٱلْغُلَامُ.]{.ar}  
"The stars appeared in the sky and shone and the boy looked at them."

This general rule has the following exception:

If a broken plural is used for non-rational beings and either a small quantity (typically ten or fewer) is intended, or the items are treated as individually distinct then it is preferred to use the feminine plural pronouns [هُنَّ]{.ar} [hunna]{.trn}/[ـهُنَّ]{.ar} [-hunna]{.trn} instead of the feminine singular pronouns [هِيَ]{.ar} [hiya]{.trn}/[ـهَا]{.ar} [-hA]{.trn}. Similarly, the feminine plural doer modification [فَعَلْنَ]{.ar} [faealna]{.trn} is preferred, but only if the doer does not occur after the verb. If the doer occurs after the verb then the feminine singular doer modification [فَعَلَتْ]{.ar} is used. For example,

[وَضَعْتُ قَلَمًا أَحْمَرَ وَقَلَمًا أَزْرَقَ وَقَلَمًا أَسْوَدَ عَلَى ٱلْمَكْتَبِ. سَقَطَتِ ٱلْأَقْلَامُ عَلَى ٱلْأَرْضِ وَذَهَبْنَ تَحْتَ ٱلْمَكْتَبِ وَخَرَجَ حِبْرُهُنَّ.]{.ar}  
"I put a red pen and a blue pen and a black pen on the desk. The pens fell on the ground and went under the desk and their ink came out."

Here the pens are few in number and are considered individually distinct. Therefore, the feminine plural pronouns and verb doer modification are used.

In the example before the previous example which has the broken plural [ٱَلنُّجُومُ]{.ar} "stars", the quantity of stars in the sky is large and they are treated as one homogenous body instead of treating them as individually distinct items. This favors usage of the feminine singular pronoun ([إِلَيْهَا]{.ar}) and feminine singular verb doer modification ([ظَهَرَتْ، لَمَعَتْ]{.ar}). <!-- Simone Bettega, Rethinking Agreement in Spoken Arabic: The Question of Gender-->

<!--This exception can also be used to indicate plurality especially if there is no other indicator. For example, if you wish to say the sentence "They fell." where "they" refers to any non-rational beings, you may choose to say [سَقَطْنَ.]{.ar} instead of [سَقَطَتْ.]{.ar} because the former makes it clear that there are multiple doers.-->

If you're unsure whether to apply the feminine singular or feminine plural pronouns or verb doer modifications in a particular case, you may safely use the feminine singular as it is the more commonly used.

### Using verbs with individually mentioned non-rational doers

Sometimes there are multiple non-rational doers for a verb that are individually mentioned. In this case, if the verb occurs before the doers then it will be singular and match the gender of the first mentioned doer. For example,

[سَقَطَ قَلَمٌ وَكِتَابٌ وَحَقِيبَةٌ عَلَى ٱلْأَرْضِ.]{.ar}  
"A pen and a book and a bag fell on the ground."

[سَقَطَتْ حَقِيبَةٌ وَكِتَابٌ وَقَلَمٌ عَلَى ٱلْأَرْضِ.]{.ar}  
"A bag and a book and a pen fell on the ground."

If the verb occurs after the doers then it may be either feminine singular or feminine plural. For example,

[ٱلْحَقِيبَةُ وَٱلْكِتَابُ وَٱلْقَلَمُ سَقَطَتْ عَلَى ٱلْأَرْضِ.]{.ar}  
[ٱلْحَقِيبَةُ وَٱلْكِتَابُ وَٱلْقَلَمُ سَقَطْنَ عَلَى ٱلْأَرْضِ.]{.ar}  
"The bag and the book and the pen fell on the ground."

## Remove

[هِيَ كُتُبٌ ثَقِيلَةٌ.]{.ar}  
"They are heavy books."

If the non-rational plural doer is not mentioned in a sentence, or if the plural is for a small number of non-rational beings then the feminine plural pronouns [هُنَّ]{.ar} [hunna]{.trn}/[ـهُنَّ]{.ar} [-hunna]{.trn} and feminine plural verb doer modification [ـنَ]{.ar} [-na]{.trn} is used. Again, it doesn't matter if the singular of the plural noun is masculine or feminine. However, the feminine plural verb doer modification is used only if the doer is not mentioned or if it comes before the verb. If the doer comes after the verb then the feminine singular verb doer modification is used. Here are some examples:

[وَجَدَ ٱلرَّجُلُ فِي ٱلْحَقِيبَةِ أَقْلَامًا. حَمَلَ ٱلْحَقيبَةَ فَخَرَجْنَ مِنْهَا وَسَقَطْنَ. فَرَفَعَهُنَّ.]{.ar}  
"The man found pens in the bag. He carried the bag and they came out of it and fell down. So he picked them up."


## Usage of plurals of qualitative nouns with non-rational beings

The usage of qualitative nouns with non-rational plurals is also somewhat complicated. Here we will explain the more normal usage and then also the uncomman usage for completeness.

### Normal usage

Consider the following noun phrase:

[ٱَلسِّنُونَ ٱلصَّعْبَةُ]{.ar}  
[EassinUna -SSaebatu]{.trn}  
"the difficult years"

The describee is a plural [ٱَلسِّنُونَ]{.ar}. But the describer is singular feminine [ٱَلصَّعْبَةُ]{.ar}, not plural [ٱَلصَّعْبَاتُ]{.ar}. This is because for plural non-rational beings, Arabic typically uses the feminine singular qualitative noun instead of the plural qualitative noun. Even if the describee is masculine, yet the describer will be feminine singular. For example,

[حَيَوَانَاتٌ وَحْشَةٌ]{.ar}  
[HayawAnatun waHcatun]{.trn}  
"wild animals"

This usage of the feminine singular qualitative noun for non-rational beings occurs in two scenarios:

i. When the qualitative noun is describing plural non-rational beings as the describer in a noun-phrase. This was the case for the two examples above.
ii. When the qualitative noun is describing plural non-rational beings as the information of a sentence. For example:

[ٱَلْحَيَوَانَاتُ كَبِيرَةٌ.]{.ar}  
[EalHayawAnAtu kabIratun]{.trn}  
"The animals are big."

This rule applies even when the qualitative noun in the information is definite. For example:

[ٱَلسِّنُونَ ٱلصَّعْبَةُ هِيَ ٱلطَّوِيلَةُ.]{.ar}  
[AssinUna -SSaebatu hiya -TTawIlatu]{.trn}  
"The difficult years were the long ones."

Note that in the above sentence, it is not just the qualitative nouns [ٱلصَّعْبَةُ]{.ar} and [ٱلطَّوِيلَةُ]{.ar} which are feminine singular. So too is the pronoun [هِيَ]{.ar}. We have already learned the rule for pronouns in the previous section.

Note however that this rule is applied only when the qualitative noun is the describer in a noun-phrase, or in the information of a sentence. If the qualitative noun is describing plural non-rational beings as the subject of a sentence then it will be pluralized. For example:

[ٱَلْحَيَوَانَاتُ كَبِيرَةٌ وَصَغِيرَةٌ. ٱَلْكَبِيرَاتُ قَوِيَّةٌ.]{.ar}  
[EalHayawAnatu kabIratun wa SagIratun. EalkabIrAtu qawiyyatun]{.trn}  
"The animals are big and small. The big ones are strong."

In the example above, in the first sentence the qualitative nouns [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} "big" and [صَغِيرَةٌ]{.ar} [SagIratun]{.trn} "small" are in the feminine singular because they are the information of the sentence and are describing the non-rational plural [ٱَلْحَيَوَانَاتُ]{.ar} [EalHayawAnAtu]{.trn} "the animals".

But in the second sentence, the qualitative noun 
[ٱَلْكَبِيرَاتُ]{.ar} [EalkabIrAtu]{.trn} "the big ones"
is the subject of the sentence. So it is pluralized.

Finally, it is worth mentioning that this usage of the feminine singular qualitative noun for non-rational beings only occurs with the plural, not the dual. Qualitative nouns for dual non-rational beings are dualized as we have seen in the previous chapter.

### Uncommon usage

Using the feminine singular qualitative noun for plural non-rational beings, as we've explained above, is the more normal usage. However, it is allowed, and sometimes you may find, the plural of a qualitative noun beings used for non-rational beings even when it is a describer in a noun-phrase or in the information of a sentence. Thus you may see:

[ٱَلْحَيَوَانَاتُ ٱلْكَبِيرَاتُ ثَقِيلَاتٌ.]{.ar}  
[EalHayawAnAtu -lkabIrAtu vaqIlAtun.]{.trn}  
"The big animals are heavy."

instead of the normal usage:

[ٱَلْحَيَوَنَاتُ ٱلْكَبِيرَةُ ثَقِيلَةٌ.]{.ar}  
[EalHayawAnAtu -lkabIratu vaqIlatun.]{.trn}  
"The big animals are heavy."

and

[كُتُبٌ ثِقَالٌ]{.ar}  
[kutubun viqAlun]{.trn}  
"heavy books"

instead of the more normal:

[كُتُبٌ ثَقِيلَةٌ]{.ar}  
[kutubun vaqIlatun]{.trn}  
"heavy books"

Conversely, we may also find, in rare usage, the feminine singular qualitative noun being used for rational female beings when it is a describer in a noun-phrase or in the information of a sentence. For example,

[جَارِيَاتٌ حَسَنَةٌ]{.ar}  
[jAriyAtun Hasanatun]{.trn}  
"good girls"

instead of the normal usage:

[جَارِيَاتٌ حَسَنَاتٌ]{.ar}  
[jAriyAtun HasanAtun]{.trn}  
"good girls"

For the beginner we recommend that you stick to the normal usage, instead of these rarer usages.

## The qualitative nouns "many" and "few"

### The qualitative noun "many"

The qualitative noun [كَثِيرٌ]{.ar} [kavIrun]{.trn} is used to mean "a lot" when it is describing an uncountable quantity. For example,

[مَاءٌ كَثِيرٌ]{.ar}  
[mAEun kavIrun]{.trn}  
"a lot of water"

[ذَهَبٌ كَثِيرَةٌ]{.ar}  
[pahabun kavIrun]{.trn}  
"a lot of gold"

When used with plural countable nouns the same qualitative noun [كَثِيرٌ]{.ar} [kavIrun]{.trn} is used to mean "many".  With plural non-rational nouns, we will typically use the feminine singular [كَثِيرَةٌ]{.ar} [kavIratun]{.trn} consistent with what we have learned so far. Example:

[حَيَوَانَاتٌ كَثِيرَةٌ]{.ar}  
[HayawAnAtun kavIratun]{.trn}  
"many animals"

However, its usage with plural rational beings can be somewhat different from what we have learned so far.
[كَثِيرٌ]{.ar} [kavIrun]{.trn} has the sound plurals [كَثِيرُونَ]{.ar} [kavIrUna]{.trn} and [كَثِيرَاتٌ]{.ar} [kavIrAtun]{.trn}. And these can be used, as expected, with rational male and female beings respectively. It also has the broken plural [كِثَارٌ]{.ar} [kivArun]{.trn}.
However, instead of using these plurals, [كَثِيرٌ]{.ar} [kavIrun]{.trn} is often used in the masculine singular when used as a qualitative noun for rational beings.

So we often see, for example,

[مُعَلِّمُونَ كَثِيرٌ]{.ar}  
[mueallimUna kavIrun]{.trn}  
"many (male) teachers"

instead of

[مُعَلِّمُونَ كَثِيرُونَ]{.ar}  
[mueallimUna kavIrUna]{.trn}  
"many (male) teachers"

although the latter is also permissible.

Similarly,

[أَنْتُمْ كَثِيرٌ.]{.ar}  
[Eantum kavIrun.]{.trn}  
"You are many (in number)."

The masculine singular [كَثِيرٌ]{.ar} [kavIrun]{.trn} is also often used with plural female rational beings. For example,

[ٱلْمُعًلِّمَاتُ كَثِيرٌ.]{.ar}  
[EalmueallimAtu kavIrun.]{.trn}  
"The (female) teachers are many."

although, in this case, it is probably more common to use the [At]{.trn} plural:

[ٱلْمُعًلِّمَاتُ كَثِيرَاتٌ.]{.ar}  
[EalmueallimAtu kavIrAtun.]{.trn}  
"The (female) teachers are many."

### The qualitative noun "few"

The above discussion also applies to the opposite of [كَثِيرٌ]{.ar} [kavIrun]{.trn}: [قَلِيلٌ]{.ar} [qalIlun]{.trn}. Here are some examples:

[طَعَامٌ قَلِيلٌ]{.ar}  
[TaeAmun qalIlun]{.trn}  
"a little food"

[كُتُبٌ قَلِيلَةٌ]{.ar}  
[kutubun qalIlatun]{.trn}
"a few books"

[ٱلرِّجَالُ قَلِيلٌ.]{.ar}  
[EarrijAlu qalIlun.]{.trn}  
and  
[ٱلرِّجَالُ قَلِيلُونَ.]{.ar}  
[EarrijAlu qalIlUna.]{.trn}  
"The men are few."

[ٱلطَّالِبَاتُ قَلِيلٌ.]{.ar}
[EaTTAlibAtu qalIlun]{.trn}  
and  
[ٱلطَّالِبَاتُ قَلِيلَاتٌ.]{.ar}
[EaTTAlibAtu qalIlAtun]{.trn}  
"The (female) students are few."

### "Many people" and "few people"

The qualitative nouns [كَثِيرٌ]{.ar} [kavIrun]{.trn} and [قَلِيلٌ]{.ar} [qalIlun]{.trn} can be used with the preposition [مِنْ]{.ar} [min]{.trn} to express "a large quantity of" and "a small quantity of" respectively. For example,

[رَجَعَ كَثِيرٌ مِنَ ٱلرِّجَالِ إِلَىٰ بُيُوتِهِمْ.]{.ar}  
[rajaea kavIrun mina -rrijAli EilA buyUtihim]{.trn}  
"A large quantity of the men returned to their homes." = "Many men returned to their homes."

Within context the qualitative nouns [كَثِيرٌ]{.ar} [kavIrun]{.trn} and [قَلِيلٌ]{.ar} [qalIlun]{.trn} can also be used by themselves to mean "a large number of people", and "a few people" respectively. Example:

[ذَهَبَ إِلَىٰ ٱلسُّوقِ كَثِيرٌ وَرَجَعَ قَلِيلٌ]{.ar}  
[pahaba Eila -ssUqi kavIrun warajaea qalIlun.]{.trn}  
"A large number [of people] went to the market and a few [people] returned."

The definite [ٱَلْكَثِيرُ]{.ar} [EalkavIru]{.trn} can be used too in this sense to mean "the many [people]". 
And the definite [ٱَلْقَلِيلُ]{.ar} [EalqalIlu]{.trn} can be used to mean "the few [people]". Example:


[عَمِلَ ٱلْقَلِيلُ وَلَعِبَ ٱلْكَثِيرُ.]{.ar}  
[eamila -lqalIlu walaeiba -lkavIru.]{.trn}  
"The few worked and the many played." 

## Vocabulary

### List

### Notes

nisaa2 plural of imra2ah
FIXME: show imra2ah-nisaa2 at the end as an exception, imra2-qawm, insaan-naas?
ashyaa2a is a diptote, despite being on pattern af3aalun
exception: colors and physical characteristics use broken plural for fem. rat. and also for non-rat.

