# Adjectival nouns

## Introduction

So far we have studied common nouns like [رَجُل]{.ar} [rajul]{.trn} "a man" and  [بَيْت]{.ar} [bayt]{.trn} "a house". 
<!--These are called designative nouns because the noun designates a specific object or entity.-->

In this chapter we will study *adjectival-nouns*. Adjectival-nouns are a class of nouns that don't denote objects. Rather they describe some quality of an object.

## Adjectives in English

In English we usually use adjectives to describe nouns. For example, the word "big" is an adjective. It can be used in a couple of different ways:

1. It can be used to describe a noun in an adjectival-noun-phrase. For example:

   "a big car"

2. The adjective "big" can also be used as the information of a sentence, describing the subject noun. For example:

   "The car is big."

But the adjective "big" cannot be used by itself as a noun, for example, as the subject of a sentence. So we can't say:

$\times$ "The big is fast."

We would have to say something like:

"The big car is fast."

instead.

## Terminology: the _describer_ and the _describee_

We take this opportunity to introduce some grammatical terminology. The adjectival-noun-phrase "a big car" consists of two parts:

i. The adjective "big". It is describing the car. We will call it the _describer_ in the noun-phrase.
ii. The common noun "a car": It is being described by the describer. We will call it the _describee_.

We will reserve this terminology of _describer_ and _describee_ only for the noun and adjective in an adjectival-noun-phrase. So we won't use this terminology for the sentence: "The car is big."

Instead, here we will continue to use the existing terminology of _subject_ and _information_. The definite noun "the car" is the subject of this sentence, and the adjective "big" is the information.

## Adjectival-nouns in English

Consider the English word "antique". It is what we will call a _adjectival-noun_. 
<!--It describes some quality of the object it refers to.-->

It can be used just like an adjective to describe a noun as part of a noun-phrase. For example:

"The antique table is expensive."

In the above sentence the adjective "antique" is a describer and is describing the noun "table".

It can also be used as the information of a sentence, just like an adjective. For example:

"The table is antique."

But what makes it different from an normal adjective is that it can also be used by itself as a noun. For example:

"The antique is expensive."

Here "the antique" could refer to any entity that can be described by the quality of being old and valuable. The adjectival-noun does not require any other noun in this sentence and can stand on its own as the subject of the sentence.

Adjectival-nouns are rare in English. Instead, adjectives are usually used when we want to describe a noun.

## Adjectival-nouns in Arabic and genderizability

<!--In Arabic, however, the situation is reversed. -->
Arabic does not have adjectives. It only has adjectival-nouns.

The word [صَغِير]{.ar} [SagIr]{.trn} is an example of an indefinite adjectival-noun in Arabic. It describes the quality of being "small" or "little". It can be used to denote any person, animal, or things that can be described as being small. Technically we could translate it as "a little one~m~" or "a small one~m~".

Being a noun [صَغِير]{.ar} [SagIr]{.trn}, like all other nouns in Arabic, will have a grammatical gender. Since it does not end with a feminine marker like [ة]{.ar}, we can state that 
[صَغِير]{.ar} [SagIr]{.trn} is a masculine noun.

Adjectival-nouns are genderizable. This means that we can feminize 
[صَغِير]{.ar} [SagIr]{.trn} (masc.) to get the feminine noun.
We will feminize 
[صَغِير]{.ar} [SagIr]{.trn} (masc.) with the feminine marker [ة]{.ar} to get the feminine adjectival noun
[صَغِيرَة]{.ar} [SagIrah]{.trn} (fem.) "a little one~f~".

Generally, the dictionary will typically only supply the masculine adjectival-noun.
And we are expected to know how to feminize it to get the feminine adjectival noun.

As opposed to adjectival-nouns, common nouns are not genderizable. So, for example, if we know that the noun
[غُلَام]{.ar} [gulAm]{.trn} "a boy" exists, we cannot assume that we can feminize it, by using the feminine marker [ة]{.ar}, for example, getting: $\times$ [غُلَامَة]{.ar} [gulAmah]{.trn}. This would be a misguided attempt to obtain the meaning for "a girl". Instead, we have to look up the Arabic word for "a girl" in the dictionary separately, and we find that it is [جَارِيَة]{.ar} [jAriyah]{.trn}.

Many times times, a masculine/feminine common noun pair will exist, that differ only by the feminine marker [ة]{.ar}. For example: 

+ [ٱِبْن]{.ar} [Eibn]{.trn} "a son" and [ٱِبْنَة]{.ar} [Eibnah]{.trn} "a daughter".
+ [مُعَلِّم]{.ar} [mueallim]{.trn} "a teacher~m~" and [مُعَلِّمَة]{.ar} [mueallimah]{.trn} "a teacher~f~"

This does not indicate that the common noun is genderizable. Rather, when the common noun masc./fem. pair has a meaning that is derived from a verb or an adjective (like
[مُعَلِّم]{.ar}/[مُعَلِّمَة]{.ar}),
then the masculine/feminine pair are co-derived as separate non-genderizable words. We will discuss this in more detail in later chapters, if [#allAh]{.trn2} wills.

And when the common noun masc./fem. pair has a primitive (non-verbal and non-adjectival) meaning, (like
[ٱِبْن]{.ar}/[ٱِبْنَة]{.ar}),
then this is only a coincidence. We alluded to this in section\ \@ref(related-nouns-for-male-and-female-animate-beings).

### Examples of Arabic adjectival-nouns

Here are some examples of Arabic adjectival-nouns that we will use in this chapter.

Arabic adjectival-noun    | Meaning
:------------------|:------------
[كَبِير]{.ar}    [kabIr]{.trn}  | a big one~m~
[صَغِير]{.ar}    [SagIr]{.trn}  | a small one~m~
[طَيِّب]{.ar}     [Tayyib]{.trn}  | a good one~m~
[سَيِّئ]{.ar}     [sayyiE]{.trn} | a bad one~m~
[قَدِيم]{.ar}    [qadIm]{.trn}  | an old one~m~
[جَدِيد]{.ar}    [jadId]{.trn}  | a new one~m~
[سَهْل]{.ar}     [sahl]{.trn}   | an easy one~m~
[صَعْب]{.ar}     [Saeb]{.trn}   | a difficult one~m~
[طَوِيل]{.ar}    [TawIl]{.trn}  | a long/tall one~m~
[قَصِير]{.ar}    [qaSIr]{.trn}  | a short one~m~
[ثَقِيل]{.ar}    [vaqIl]{.trn}  | a heavy one~m~
[خَفِيف]{.ar}    [xafIf]{.trn}  | a light one~m~
[وَاسِع]{.ar}    [wAsie]{.trn}  | a wide one~m~
[ضَيِّق]{.ar}     [Dayyiq]{.trn} | a narrow one~m~
[سَرِيع]{.ar}    [sarIe]{.trn}  | a fast one~m~
[بَطِيء]{.ar}    [baTIE]{.trn}  | a slow one~m~
[قَوِيّ]{.ar}     [qawiyy]{.trn} | a strong one~m~
[ضَعِيف]{.ar}    [DaeIf]{.trn}  | a weak one~m~

## Adjectival-noun-phrases

### The describer and the describee

Let's learn how adjectival-noun-phrases are formed in Arabic.

We learned in section\ \@ref(terminology-the-describer-and-the-describee)
above that adjectival-noun-phrases consist of a describer and a describee. 

In English adjectival-noun-phrases, like "the small house", the adjective describer ("small") comes before the describee ("house"). Also, only one definite article ("the") is used before the entire noun-phrase.

Here is the equivalent Arabic adjectival-noun-phrase:

[ٱَلْبَيْتُ ٱلصَّغِيرُ]{.ar}  
[Ealbaytu -SSagIru]{.trn}  
"the house, the small one" = "the small house"

Note the following:

+ The adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" comes after the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house".
+ Both the adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" and the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" get the definite article [ٱَلْ]{.ar} "the".
+ The adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" is genderized to match the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" in gender.
+ The adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" matches the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" in state. In this example, they were both in the u-state but we will see examples in the other states as well.
+ The essential translation of the above adjectival-noun-phrase is "the house, the small one" but we will usually give the more natural translation: "the small house"

Let's try another example: let's try to translate the sentence: "The little girl took a new book from the good mother."

Here is the sentence in Arabic:

[أَخَذَتِ ٱلْجَارِيَةُ ٱلصَّغِيرَةُ كِتَابًا جَدِيدًا مِنْ ٱلْأُمِّ ٱلطَّيِّبَةِ.]{.ar}  
[Eaxapati -ljAriyatu -SSagIratu kitaban jadIdan mina -lEummi -TTayyibah.]{.trn}  
"The little girl took a new book from the good mother."

This sentence has three adjectival noun phrases. We will analyze each one individually:

i. [ٱَلْجَارِيَةُ ٱلصَّغِيرَةُ]{.ar}  
   [EaljAriyatu -SSagIratu]{.trn}  
   "the little girl"

   In this phrase the definite feminine noun [ٱلْجَارِيَةُ]{.ar} [EaljAriyatu]{.trn} is the doer of the verb [أَخَذَ]{.ar} [Eaxapa]{.trn} "took". Therefore it is in the u-state. It is also the describee in the adjectival-noun-phrase. Its describer [ٱَلصَّغِيرَةُ]{.ar} [EaSSagIratu]{.trn} follows the describee and is made to match the describee in state (u-state), gender (feminine), and definiteness (definite).

ii. [كِتَابًا جَدِيدًا]{.ar}  
    [kitAban jadIdan]{.trn}  
    "a new book"

    In this phrase the indefinite masculine noun [كِتَابًا]{.ar} [kitAban]{.trn} is the doee of the verb [أَخَذَ]{.ar} [Eaxapa]{.trn} "took". Therefore it is in the a-state. It is also the describee in the adjectival-noun-phrase. Its describer [جَدِيدًا]{.ar} [jadIdan]{.trn} follows the describee and is made to match the describee in state (a-state), gender (masculine), and definiteness (indefinite).

iii. [ٱَلْأُمِّ ٱلطَّيِّبَةِ]{.ar}  
     [EalEummi -TTayyibati]{.trn}  
     "the good mother"

      In this phrase the definite feminine noun [ٱلْأُمِّ]{.ar} [EalEummi]{.trn} is following the preposition [مِنْ]{.ar} [min]{.trn} "from". Therefore it is in the i-state. It is also the describee in the adjectival-noun-phrase. Its describer [ٱَلطَيِّبَةِ]{.ar} [EaTTayyibati]{.trn} follows the describee and is made to match the describee in state (i-state), gender (feminine), and definiteness (definite). 

      Note carefully that the describer matches the describee in gender, not necessarily in having the same [ة]{.ar} ending. The feminine adjectival-noun describer [ٱَلطَيِّبَة]{.ar} [EaTTayyibah]{.trn} is still formed using the feminine marker [ة]{.ar}, despite the feminine describee [ٱَلْأُمّ]{.ar} not having the [ة]{.ar} feminine marker.

<!--
[حَمَلَتِ ٱلْأُمُّ ٱلطَّيِّبُ جَارِيَةً صَغِيرَةً بِيَدٍ قَوِيَّةٍ.]{.ar}  
-->

"The tall strong mother took an old and heavy book from the little girl."

## Adjectival-nouns as the information of a sentence

Let's see how to use Arabic adjectival-nouns as the subject or information of a sentence.

[ٱَلْبَيْتُ صَغِيرٌ.]{.ar}  
[Ealbaytu SagIr.]{.trn}  
"The house is a small one." = "The house is small."

In the above sentence, the indefinite adjectival noun 
[صَغِير]{.ar} [SagIr]{.trn} "a small one"
is used as the information of a sentence. Its indefiniteness and u-state is indicated by the [un]{.trn}-mark [◌ٌ]{.ar} on its end.

When an adjectival noun is the information of a sentence, then it shall be genderized to match the gender of the subject noun. The subject noun in this case ([ٱَلْبَيْت]{.ar}) is masculine. Therefore, the masculine adjectival-noun ([صَغِير]{.ar}) is chosen.

Technically, the translation of this sentence is "The house is a small one."
However, because Arabic has only adjectival-nouns and not adjectives, it is how we can express the English sentence "The house is small." Therefore we can also translate it into English as such.

Now let's try a sentence with a feminine subject:

[ٱَلْجَارِيَةُ صَغِيرَة.]{.ar}  
[EaljAriyatu SagIrah]{.trn}  
"The girl is a little one~f~." = "The girl is little."

In the above example the subject ([ٱَلْجَارِيَة]{.ar} "the girl") was feminine. Therefore, we feminized the masculine adjectival-noun [صَغِير]{.ar} [SagIr]{.trn} with the feminine marker [ة]{.ar} to get the feminine adjectival noun
[صَغِيرَة]{.ar} [SagIrah]{.trn} "a little one~f~"
and used the feminine adjectival-noun in the sentence.

## Adjectival-noun-phrases

We learned in section\ \@ref(terminology-the-describer-and-the-describee)
above that adjectival-noun-phrases consist of a describer and a describee. 

In English adjectival-noun-phrases, like "the small house", the adjective describer ("small") comes before the describee ("house"). Also, only one definite article ("the") is used before the entire noun-phrase.

Here is the equivalent Arabic adjectival-noun-phrase:

[ٱَلْبَيْتُ ٱلصَّغِيرُ]{.ar}  
[Ealbaytu -SSagIru]{.trn}  
"the house, the small one" = "the small house"

Note the following:

+ The adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" comes after the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house".
+ Both the adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" and the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" get the definite article [ٱَلْ]{.ar} "the".
+ The adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" is genderized to match the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" in gender.
+ The adjectival-noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" matches the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" in state. In this example, they were both in the u-state but we will see examples in the other states as well.
+ The essential translation of the above adjectival-noun-phrase is "the house, the small one" but we will usually give the more natural translation: "the small house"

--

Now, let's try using an adjectival-noun as the subject of a sentence.

which describes the quality of being small or little. Because it is a noun, and not an adjective, it technically means "a little one" or "a small one", where "one" can refer to any entity, e.g., a person, an animal, an object, etc, that is small or little. But this translation "a little/small one" may be a little awkward in English in some sentences, so we will often translate it  in English with the adjective "little" or "small".
For example, [صَغِير]{.ar} [SagIrun]{.trn} is a adjectival-noun which describes the quality of being small or little. Because it is a noun, and not an adjective, it technically means "a little one" or "a small one", where "one" can refer to any entity, e.g., a person, an animal, an object, etc, that is small or little. But this translation "a little/small one" may be a little awkward in English in some sentences, so we will often translate it  in English with the adjective "little" or "small".

Notice that [صَغِيرٌ]{.ar} [SagIrun]{.trn} has an [n]{.trn}-mark. This means it is indefinite and it is why we translated it as "_a_ little one". Instead of an [n]{.trn}-mark, it can be preceded by [ٱَلْ]{.ar} in order to give [ٱَلصَغِيرُ]{.ar} [aSSagIru]{.trn}  in which case it will be definite and mean "_the_ little/small one".

We can use this adjectival-noun as a noun in a sentence. For example:

[حَمَلَتِ ٱلْأُمُّ ٱلصَّغِيرَ.]{.ar}  
[Hamalati -lEummu -SSagIra.]{.trn}  
"The mother carried the little one."

Here we may infer that "the little one" refers to a child.

In addition to having the indefnite and definite property of nouns, adjectival-nouns also have gender: they may be masculine or feminine. 

The masculine [صَغِيرٌ]{.ar} [SagIrun]{.trn} is used when the noun described by the adjectival-noun is masculine, like [بَيْتٌ]{.ar} [baytun]{.trn} "a house".

The feminine of most adjectival-nouns is formed by adding the feminine marker [ة]{.ar}. Some adjectival-nouns take other feminine markers, as we will see in later chapters, if [#allAh]{.trn2} wills.

So in order to form the feminine of [صَغِيرٌ]{.ar} [SagIrun]{.trn}, we add [ة]{.ar} to it and it becomes [صَغِيرَةٌ]{.ar} [SagIratun]{.trn}.
The feminine [صَغِيرَةٌ]{.ar} [SagIratun]{.trn} is used when the noun described by the adjectival-noun is feminine, like [شَجَرَةٌ]{.ar} [cajaratun]{.trn} "a tree".

##  Describers in a noun-phrase

### A adjectival-noun as the describer

The expression "a small house" is an example of a noun-phrase. It consists of a _describer_ and a _describee_. The adjective "small" is the describer and the noun "a house" is the describee.

In an English noun-phrase, the describer comes before the describee.

In an Arabic noun-phrase, a adjectival-noun is used as the describer to give the meaning of the adjective. The describee comes first and the describer comes after the describee. Furthermore, the describer matches the describee in state, definiteness, and gender.

So in Arabic, in order to express "a small house", we put the [describee]{.syn} [بَيْتٌ]{.ar} [baytun]{.trn} "a house" first, and place the adjectival-noun [صَغِيرٌ]{.ar} [SagIrun]{.trn} "a small one" after it as the [describer]{.syn}. Then the adjectival-noun [صَغِيرٌ]{.ar} [SagIrun]{.trn} gives the meaning of the adjective "small":

[بَيْتٌ صَغِيرٌ]{.ar}  
[baytun SagIrun]{.trn}  
"a house, a small one" = "a small house"

Here the [describee]{.syn} [بَيْتٌ]{.ar} [baytun]{.trn} "a house" is masculine, indefinite, and in the u-state. Therefore, the [describer]{.syn} [صَغِيرٌ]{.ar} [SagIrun]{.trn} "a small one" is also is also masculine, indefinite, and in the u-state. 
Similarly, for "the small tree" we say:

[ٱَلشَّجَرَةُ ٱلصَّغِيرَةُ]{.ar}  
[accajaratu -SSagIratu]{.trn}  
"the tree, the big one" = "the small tree"

Here too the [describer]{.syn} [ٱلصَّغِيرَةُ]{.ar} [aSSagIratu]{.trn} "the small one" matches the [describee]{.syn} [ٱَلشَّجَرَةُ]{.ar} [accajaratu]{.trn} "the tree" in being feminine, definite, and in the u-state.

Here are examples of noun-phrases with adjectival-nouns used in sentences:

[ذَهَبَ إِلَىٰ بَيْتٍ صَغِيرٍ.]{.ar}  
[pahaba EilA baytin SagIrin.]{.trn}  
"He went to a small house."

[ٱَلْجَارِيَةُ ٱلصَّغِيرَةُ فِي ٱلْمَدْرَسَةِ.]{.ar}  
[EaljAriyatu -SSagIratu fi -lmadrasati.]{.trn}  
"The little girl is at school."

[حَمَلَتِ ٱلْمَرْأَةُ ٱلْغُلَامَ ٱلصَّغِيرَ.]{.ar}  
[Hamalati -lmarEatu -lgulAma -SSagIra.]{.trn}  
"The woman carried the little boy."

### Multiple describers

If there are multiple describers to be used in a noun phrases, they may follow one another sequentially, with, or without the word [وَ]{.ar} [wa]{.trn} "and", just as in English. For example, the adjectival-noun [جَمِيلٌ]{.ar} [jamIlun]{.trn} means "a beautiful one". We can combine it with [صَغِيرٌ]{.ar} [SagIrun]{.trn} "a small one" thus:

[لِلرَّجُلِ بَيْتٌ جَمِيلٌ صَغِيرٌ.]{.ar}  
[lirrajuli baytun jamIlun SagIrun.]{.trn}  
"The man has a beautiful small house."

[لِلرَّجُلِ بَيْتٌ صَغِيرٌ وَجَمِيلٌ.]{.ar}  
[lirrajuli baytun SagIrun wajamIlun.]{.trn}  
"The man has a small and beautiful house."

فلان أديب عربي مشهور
famous arab literate

reverse order


### A prepositional phrase as the describer

Consider the phrase:

[كِتَابٌ مِنَ ٱلْمَكْتَبَةِ]{.ar}  
[kitAbun mina -lmaktabati]{.trn}  
"a book from the library"

The prepositional phrase [مِنَ ٱلْمَكْتَبَةِ]{.ar} [mina -lmaktabati]{.trn} "from the library" is not a adjectival-noun. Yet it still acts as a describer for the noun [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book", in that it is describing a quality of the book.

If we want to add a adjectival-noun as an additional describer, we may add it either before or after the prepositional phrase describer. Here are both examples as complete sentences:

[قَرَأَ كِتَابًا صَغِيرًا مِنَ ٱلْمَكْتَبَةِ.]{.ar}  
[qaraEa kitAban SagIran mina -lmaktabati.]{.trn}  
AND  
[قَرَأَ كِتَابًا مِنَ ٱلْمَكْتَبَةِ صَغِيرًا.]{.ar}  
[qaraEa kitAban mina -lmaktabati SagIran.]{.trn}  
"a small book from the library"

The first option is usually chosen as a matter of preference but the second option is legitimate too.

## Adjectival-nouns as the information in a sentence

### Indefinite adjectival-nouns as the [information]{.syn}

We have just studied [بَيْتٌ صَغِيرٌ]{.ar} [baytun SagIrun]{.trn} "a small man" as an example of a noun-phrase. Now let's take a look at the sentence:

"The house is small."

This is a [subject-information]{.syn} sentence. The noun "the house" is the [subject]{.syn} and the adjective "small" is the [information]{.syn}.

In order to express this sentence in Arabic, we again remember that Arabic does not have adjectives and uses adjectival-nouns instead. When an indefinite adjectival-noun is used as the [information]{.syn} of a sentence, it gives the meaning of the adjective. So in order to express this sentence in Arabic, we will say:

[ٱَلْبَيْتُ صَغِيرٌ]{.ar}  
[Ealbaytu SagIrun]{.trn}  
"The house is a small one." = "The house is small."

The indefinite adjectival-noun [صَغِيرٌ]{.ar} [SagIrun]{.trn} is the [information]{.syn} of the sentence. Therefore, it gives the meaning of the adjective "small".

### Definite adjectival-nouns as the [information]{.syn}

We can also use a definite adjectival-noun as the [information]{.syn} too.

[ٱلْبَيْتُ ٱلصًّغِيرُ هُوَ ٱلْجَمِيلُ.]{.ar}  
[Ealbaytu -SSagIru huwa -ljamIlu.]{.trn}  
"The small house is the beautiful one."

[ٱَلْجَمِيلُ]{.ar} [EaljamIlu]{.trn} is the definite adjectival-noun in the information of the sentence. Here it won't be translated as the adjective "beautiful". Instead it will be translated as a noun "the beautiful one".

## Vocabulary

Arabic word |Transcription| Meaning
:-----------|:------------|:------------
[كَبِيرٌ]{.ar}   | [kabIrun]{.trn}  | big
[صَغِيرٌ]{.ar}   | [SagIrun]{.trn}  | small
[حَسَنٌ]{.ar}    | [Hasanun]{.trn}  | good
[سَيِّئٌ]{.ar}    | [sayyiEun]{.trn} | bad
[قَدِيمٌ]{.ar}   | [qadImun]{.trn}  | old
[جَدِيدٌ]{.ar}   | [jadIdun]{.trn}  | new
[سَهْلٌ]{.ar}    | [sahlun]{.trn}   | easy
[صَعْبٌ]{.ar}    | [Saebun]{.trn}   | difficult
[طَوِيلٌ]{.ar}   | [TawIlun]{.trn}  | long
[قَصِيرٌ]{.ar}   | [qaSIrun]{.trn}  | short
[ثَقِيلٌ]{.ar}   | [vaqIlun]{.trn}  | heavy
[خَفِيفٌ]{.ar}   | [xafIfun]{.trn}  | light
[وَاسِعٌ]{.ar}   | [wAsieun]{.trn}  | wide
[ضَيِّقٌ]{.ar}    | [Dayyiqun]{.trn} | narrow
[سَرِيعٌ]{.ar}   | [sarIeun]{.trn}  | fast
[بَطِيءٌ]{.ar}   | [baTIEun]{.trn}  | slow
[قَوِيٌّ]{.ar}    | [qawiyyun]{.trn} | strong
[ضَعِيفٌ]{.ar}   | [DaeIfun]{.trn}  | weak
[كَثِيرٌ]{.ar}   | [kavIrun]{.trn}  | much/a lot
[قَلِيلٌ]{.ar}   | [qalIlun]{.trn}  | a little

## Exercises

The cat is a small animal.
"The heavy book is difficult."

[مَاءٌ قَلِيلٌ]{.ar}  
