# Semi-flexible nouns

## Introduction

Nouns are of two main categories of nouns, with regard to their endings in the different noun states:

1. Rigid nouns.
2. Flexible nouns. These are further sub-divided into:
   i. Fully-flexible nouns.
   ii. Semi-flexible nouns.

So far we have been mostly studying fully-flexible nouns. In this chapter we will learn about semi-flexible nouns.

Here is an example of the kind of nouns we have learned so far:

State  | Indefinite | Definite
:------|:-----------|:---------
u-state| [رَجُلٌ]{.ar} | [ٱَلرَّجُلُ]{.ar}
a-state| [رَجُلًا]{.ar}| [ٱَلرَّجُلَ]{.ar}
i-state| [رَجُلٍ]{.ar} | [ٱَلرَّجُلِ]{.ar}

As you can see, the noun has [n]{.trn}-marks when it is indefinite, and also, the vowel mark on the last letter changes for each state that the noun is in. These kinds of nouns are called _fully-flexible_ nouns. They are by far the most common type of noun.

There are some nouns, however, that are _semi-flexible_. 
Here is an example of a semi-flexible noun, [صَحْرَاء]{.ar} [SaHrAE]{.trn} "a desert":

State  | Indefinite | Definite
:------|:-----------|:---------
u-state| [صَحْرَاءُ]{.ar} | [ٱَلصَّحْرَاءُ]{.ar}
a-state| [صَحْرَاءَ]{.ar} | [ٱَلصَّحْرَاءَ]{.ar}
i-state| [صَحْرَاءَ]{.ar} | [ٱَلصَّحْرَاءِ]{.ar}

As you can see, when [صَحْرَاء]{.ar} [SaHrAE]{.trn} is indefinite, it does not have an [n]{.trn}-mark. Also, when it is indefinite and in the i-state, the vowel mark on its final letter is not [◌ِ]{.ar}, as you might expect but [◌َ]{.ar} . And so the noun looks identical in the a-state and i-state when it is indefinite.

When it is definite, however, it looks just like fully-flexible nouns.

So there are two differences between fully-flexible and semi-flexible nouns:

1. When indefinite, a semi-flexible noun does not have an [n]{.trn}-mark.
2. When indefinite and in the i-state, a semi-flexible noun's final letter does not have an [i]{.trn}-mark. Instead it shall have an [a]{.trn}-mark, just like when it is in the a-state.

The other category of nouns are _rigid_ nouns. Rigid nouns don't change their endings due to their state. They are much fewer in number compared to flexible nouns. Pronouns are an example of rigid nouns.

## Feminine markers

Before we discuss semi-flexible nouns in more detail, we will discuss feminine markers. We already know of one feminine marker: the looped-[tAE]{.trn} [ة]{.ar}. When a singular noun ends with [ة]{.ar}, then that is an indication, with very few exceptions, that it is a feminine noun. Examples are:

Root | Feminine noun | Masculine noun from same root (if any)
:-|:-------|:-------
[جري]{.arroot} | [جَارِيَة]{.ar}  "a girl~f~"             | --
[علم]{.arroot} | [عَالِمَة]{.ar}  "a scholar~f~"          | [عَالِم]{.ar}  "a scholar~m~"
[كلب]{.arroot} | [كَلْبَة]{.ar}  "a dog~f~"               | [كَلْب]{.ar}  "a dog~m~"
[شجر]{.arroot} | [شَجَرَة]{.ar}  "a tree"                 | --
[صغر]{.arroot} | [صَغِيرَة]{.ar}  _adj._ "small~f~"   | [صَغِير]{.ar}  _adj._ "small~m~"

As you can see, the feminine marker [ة]{.ar} is never part of the noun's root. It is thus considered _extrinsic_ to the root. Also, sometimes, but not always, the feminine noun is formed by adding the feminine marker [ة]{.ar} to the end of a masculine noun.

It is also important to note that [ة]{.ar} is only a feminine marker for singular nouns. When we learn plurals, if [#allAh]{.trn2} wills, we will see that [ة]{.ar} is used frequently with masculine plurals.

Now we will learn of two more feminine markers: [اء]{.ar} and [ىٰ]{.ar}. 

Here are some examples of nouns that end with these two feminine markers:

Root | Feminine noun | Masculine noun (if any)
:-|:-------|:-------
[صحر]{.arroot} | [صَحْرَاء]{.ar}  "a desert"               | --
[حمر]{.arroot} | [حَمْرَاء]{.ar}  _adj._ "red~f~"      | [أَحْمَر]{.ar}  _adj._ "red~m~"
[ذكر]{.arroot} | [ذِكْرَىٰ]{.ar}  "a memory"                 | --
[غضب]{.arroot} | [غَضْبَىٰ]{.ar}  _adj._ "very angry~f~" | [غَضْبَان]{.ar}  _adj._ "very angry~m~"

When extrinsic to the word's root, [اء]{.ar} and [ىٰ]{.ar} are feminine markers, just like [ة]{.ar}. However, one important difference from [ة]{.ar} is that sometimes
[اء]{.ar} and [ىٰ]{.ar} may not be extrinsic to the word's root. In this case, they will not be feminine markers, and the noun will regularly be a masculine noun. Examples:

Root | Noun | Pattern using paradigm [فعل]{.arroot}
:--|:----------|:----
[هدي]{.arroot} | [ٱلْهُدَىٰ]{.ar}  (masc.) "the guidance" | [ٱَلْفُعَل]{.ar}
[برء]{.arroot} | [إِبْرَاء]{.ar}  (masc.) "an acquittal" | [إِفْعَال]{.ar}

These cases will become more clear, if [#allAh]{.trn2} wills, when we study weak roots (roots that contain a weak letter like [ء، و، ي]{.ar}).

Otherwise, 
when extrinsic to the word's root, [اء]{.ar}, and [ىٰ]{.ar} are consistently feminine markers, just like [ة]{.ar}. 

Also, just like [ة]{.ar}, [اء]{.ar}, and [ىٰ]{.ar} are only feminine markers for singular nouns. We will see, if [#allAh]{.trn2} wills, that they are used frequently with masculine plurals.

By the way, another difference from [ة]{.ar} is that when 
[اء]{.ar}, and [ىٰ]{.ar} are feminine markers, and a masculine counterpart exists, then the feminine noun is not formed by simply adding the feminine marker to the end of the masculine noun. The masculine and feminine nouns are different internally as well. For example, the feminine noun
[حَمْرَاء]{.ar}  _adj._ "red~f~"
is not formed simply by adding the feminine marker [اء]{.ar} to the end of the masculine noun
[أَحْمَر]{.ar}  _adj._ "red~m~".

We will discuss this in more detail below.

## Categories of semi-flexible nouns

We now return to our discussion of semi-flexible nouns. Semi-flexible nouns, in terms of their formation, fall under different categories. We will discuss them below.

### Nouns that end with an external [اء]{.ar}

If a noun ends with an [اء]{.ar}, which is external to the word's root, then it shall be a semi-flexible noun.

We have already seen an example of such a noun above: [صَحْرَاءُ]{.ar} [SaHrAEu]{.trn} "a desert". The root of this noun is [صحر]{.arroot}. You can see that the ending [اء]{.ar} is not part of the root. Therefore it is a semi-flexible noun.

Furthermore, this [اء]{.ar} which is external to the word's root is a feminine marker for singular nouns, just like [ة]{.ar}, except that [ة]{.ar} does not generally make a noun semi-flexible.

Here is an example sentence with this noun:

[ذَهَبَ ٱلرَّجُلُ إِلَىٰ صَحْرَاءَ وَاسِعَةٍ.]{.ar}  
[pahaba -rrajulu EilA SaHrAEa wAsieatin]{.trn}  
"The man went to a wide desert."

Note that [صَحْرَاءَ]{.ar} [SaHrAEa]{.trn} is  in the i-state because it is preceded by the preposition [إِلَىٰ]{.ar} [EilA]{.trn} "to". It is also a describee, whose describer is [وَاسِعَةٍ]{.ar} [wAsieatin]{.trn} "wide". The final vowel mark [◌َ]{.ar} on the describee [صَحْرَاءَ]{.ar} [SaHrAEa]{.trn} has no effect on the final vowel mark on the describer [وَاسِعَةٍ]{.ar} [wAsieatin]{.trn} "wide". All that matters int this regard is the state of the describee. 

Beware that there are some words where [اء]{.ar} may be part of the word's root, e.g. [ٱِبْتِدَاءٌ]{.ar} [ibtidAEun]{.trn} "a beginning" whose root is [بدء]{.arroot} and which is on the pattern [ٱِفْتِعَالٌ]{.ar} [iftieAlun]{.trn}. Because here the [ء]{.ar} in [ٱبْتِدَاءٌ]{.ar} is part of the word's root, therefore it shall not be a semi-flexible noun. That is why you can see that it has an [n]{.trn} mark when it is indefinite. Also, for the same reason, [اء]{.ar} in this word is not a feminine marker, and the word is masculine.

### Nouns that end with an external [ىٰ]{.ar}

If a noun ends with an [ىٰ]{.ar} which is external to the word's root, then it shall be a semi-flexible noun.

An example of such a words is [ذِكْرَىٰ]{.ar} [pikrA]{.trn} "a remembrance". The root of this word is [ذكر]{.arroot} and it is on the pattern [فِعْلَىٰ]{.ar}.

Similar to [اء]{.ar}, this [ىٰ]{.ar} which is external to the word's root is a feminine marker for singular nouns.

Since [ذِكْرَىٰ]{.ar} [pikrA]{.trn} already ends with a vowel, the last letter won't have any additional vowel markers and therefore the word will appear the same in all states:

  State  | Indefinite | Definite
  :------|:-----------|:---------
  u-state| [ذِكْرَىٰ]{.ar} | [ٱَلذِّكْرَىٰ]{.ar}
  a-state| [ذِكْرَىٰ]{.ar} | [ٱَلذِّكْرَىٰ]{.ar}
  i-state| [ذِكْرَىٰ]{.ar} | [ٱَلذِّكْرَىٰ]{.ar}

Here is an example of this word in a sentence:

[ٱَلْكِتَابُ ذِكْرَىٰ جَمِيلةٌ.]{.ar}  
[EalkitAbu pikrA jamIlatun]{.trn}  
"The book is a beautiful remembrance."

Note how the describers in both examples above are feminine because the describee nouns are feminine.

Beware also that, just like in the case of [اء]{.ar}, there are some words where [ىٰ]{.ar} may be part of the word's root, e.g. [ٱَلْهُدَىٰ]{.ar} [EalhudA]{.trn} "the guidance" whose root is [هدي]{.arroot}. Because here the [ىٰ]{.ar} in [ٱلْهُدَىٰ]{.ar} is part of the word's root, therefore it shall not be a semi-flexible noun. So, when it is indefinite, it will have an [n]{.trn}-mark when it is indefinite: [هُدًى]{.ar} [hudan]{.trn} "a guidance". Also, for the same reason, [ىٰ]{.ar} in this word is not a feminine marker, and the word is masculine.

### Nouns on the pattern [أَفْعَل]{.ar}

If a noun is on the pattern [أَفْعَل]{.ar} then it shall be a semi-flexible noun. 

Most colors and many physical characteristics fall into this pattern. Colors and physical characteristics are qualitative nouns. The masculine qualitative noun is on the pattern [أَفْعَلُ]{.ar}. And the feminine qualitative noun is on the pattern [فَعْلَاءُ]{.ar} [faelAEu]{.trn} (which is itself a semi-flexible noun pattern). Here are some examples of such qualitative nouns:

Root | Masc. Noun | Fem. noun | Meaning
:----|:-----------|:-------------|:------------
[حمر]{.arroot} | [أَحْمَرُ]{.ar}  | [حَمْرَاءُ]{.ar}  | red
[سود]{.arroot} | [أَسْوَدُ]{.ar}  | [سَوْدَاءُ]{.ar}  | black
[بيض]{.arroot} | [أَبْيَضُ]{.ar}  | [بَيْضَاءُ]{.ar}  | white
[عرج]{.arroot} | [أَعْرَجُ]{.ar}  | [عَرْجَاءُ]{.ar}  | lame
[حور]{.arroot} | [أَحْوَرُ]{.ar}  | [حَوْرَاءُ]{.ar}  | beautiful eyed
[بكم]{.arroot} | [أَبْكَمُ]{.ar}  | [بَكْمَاءُ]{.ar}  | mute

### Qualitative nouns that end with an external [ان]{.ar}

This category is more complicated than the previous ones. The following conditions must be satisfied for a word that ends with [ان]{.ar} to be a semi-flexible noun:

1. It must be a qualitative noun, not a designative noun. So the designative noun [قُرْءَانٌ]{.ar} [qurEAnun]{.trn} "a [#qurEan]{.trn2}" of the root [قرء]{.arroot} is not a semi-flexible noun.
2. The [ان]{.ar} must be external to the word's root. So [جَبَانٌ]{.ar} [jabAnun]{.trn} "a coward" of the root [جبن]{.arroot} is not a semi-flexible noun.
3. The feminine of the qualitative noun shall not be formed by adding [ة]{.ar} to it. So [نَدْمَانٌ]{.ar} [nadmAnun]{.trn} "regretful" of the root [ندم]{.arroot}, whose feminine is [نَدْمَانَةٌ]{.ar} [nadmAnatun]{.trn} is not a semi-flexible noun.

It is rare that this last condition fails. Most qualitative nouns that end with an external [ان]{.ar} are of the pattern [فَعْلَانُ]{.ar} [faelAnu]{.trn} and their feminine is of the pattern [فَعْلَىٰ]{.ar} [faelA]{.trn} (which is itself a semi-flexible noun pattern). The following are examples of semi-flexible nouns that fall into this category:

Root | Masc. Noun | Fem. noun | Meaning
:----|:-----------|:-------------|:------------
[غضب]{.arroot} | [غَضْبَانُ]{.ar} | [غَضْبَىٰ]{.ar}   | very angry
[عطش]{.arroot} | [عَطْشَانُ]{.ar} | [عَطْشَىٰ]{.ar}   | very thirsty
[جوع]{.arroot} | [جَوْعَانُ]{.ar} | [جَوْعَىٰ]{.ar}   | very hungry

### Other categories

There are a couple more categories of semi-flexible nouns. Some have to do with proper nouns, which we will cover later in this chapter, and others are plural nouns which we will learn in a later chapter, if [#allAh]{.trn2} wills.

