# Gender of nouns

## Introduction

All nouns in Arabic are either masculine or feminine in gender. Sometimes the nouns designate animate beings like "a man", "a woman", "a dog", "a cow", "a teacher", etc.

Other nouns designate inanimate objects like "a book", "a house", "a hand", "a tree", "a city", "a food". In Arabic these nouns too will be grammatically either masculine or feminine.

## Nouns that designate animate beings.

In terms of their form, nouns that designate animate beings are in three categories:

1. The nouns for male and female animate beings match each other.
2. The nouns for male and female animate beings are unrelated.
3. The same noun is used for both sexes.

### Matching nouns for male and female animate beings

In Arabic sometimes for nouns that designate animate beings, the nouns for both sexes match each other. Here are some examples:

Arabic word | Transcription|Gender | Definition
:-----------|:-----------|:---|:----------------
[ٱِمْرَأٌ]{.ar} |[imraEun]{.trn}     |masc.|a man
[ٱِمْرَأَةٌ]{.ar}|[imraEatun]{.trn}   |fem. |a woman
[مُعَلِّمٌ]{.ar} |[mueallimun]{.trn}  |masc.|a male teacher
[مُعَلِّمَةٌ]{.ar}|[mueallimatun]{.trn}|fem. |a female teacher
[كَلْبٌ]{.ar}  |[kalb]{.trn}        |masc.|a male dog
[كَلْبَةٌ]{.ar} |[kalbatun]{.trn}    |fem. |a female dog
[هِرٌّ]{.ar}   |[hirrun]{.trn}      |masc.|a male cat
[هِرَّةٌ]{.ar}  |[hirratun]{.trn}    |fem. |a female cat

In each of the words in the table above, the feminine noun is formed by adding a looped [tAE]{.trn} [ة]{.ar} to the masculine noun. For example, [ٱِمْرَأٌ]{.ar} [imraEun]{.trn} is "a man" and [ٱِمْرَأَةٌ]{.ar} [imraEatun]{.trn} is "a woman".

The looped [tAE]{.trn} [ة]{.ar} is thus a feminine marker for singular nouns. There are a couple of other feminine markers besides looped [tAE]{.trn} but they are not as common and we will learn them later if Allah wills.
 
Note that when we add looped [tAE]{.trn} [ة]{.ar} to a masculine noun to make it a feminine noun, the final letter of the masculine noun gets an [a]{.trn}-mark and the [n]{.trn}-mark gets transferred to the looped [tAE]{.trn} [ة]{.ar}. For example, in the case of [كَلْبٌ]{.ar} [kalb]{.trn} "a male dog", in order to get the feminine noun [كَلْبَةٌ]{.ar} [kalbatun]{.trn} "a female dog", [ب]{.ar} gets an [a]{.trn}-mark and [ة]{.ar} gets the [n]{.trn}-mark.

#### Remove

Note also that we have provided a new word for "a man": [ٱِمْرَأٌ]{.ar} [imraEun]{.trn}.
But we have already learned the word for "a man": [رَجُلٌ]{.ar} [rajulun]{.trn}. So what is difference between [رَجُلٌ]{.ar} [rajulun]{.trn} and [ٱِمْرَأٌ]{.ar} [imraEun]{.trn}?
There is some degree of overlap but the noun [رَجُلٌ]{.ar} [rajulun]{.trn} is used more commonly when talking about male human beings.
[ٱِمْرَأٌ]{.ar} [imraEun]{.trn} is used generally when speaking about "man" generically, for example, in sentences like "Man is a social animal." and "A man should always be honest." It is also often used to mean "a person".

the [n]{.trn}-mark is transferred to the looped [tAE]{.trn} and the previous letter gets an [a]{.trn}-mark. In the case of [ٱِمْرَأَةٌ]{.ar} [imraEatun]{.trn} the previous letter is a [hamza]{.trn} that was seated on a [wAw]{.trn} in [ٱِمْرَوٌ]{.ar} [imraEun]{.trn} and we have to change its seat to [alif]{.trn} when we replace the [un]{.trn}-mark with an [a]{.trn}-mark.

Also, we have already learned another word for "a man": [رَجُلٌ]{.ar} [rajulun]{.trn}. So what is difference between [رَجُلٌ]{.ar} [rajulun]{.trn} and [ٱِمْرَؤٌ]{.ar} [imraEun]{.trn}.
The noun [رَجُلٌ]{.ar} [rajulun]{.trn} is used more commonly when talking about specific male human beings.
[ٱِمْرَؤٌ]{.ar} [imraEun]{.trn} is used generally when speaking about "man" generically, for example, in sentences like "Man is a social animal.", and "A man should always be honest."

### Unrelated nouns for male and female animate beings

For other nouns that designate animate beings, the nouns for the male and female sexes are completely unrelated. Here are some examples:

Arabic word | Transcription|Gender | Definition
:-----------|:-----------|:---|:----------------
[أَبٌ]{.ar}   |[Eabun]{.trn}     |masc.|a father
[أُمٌّ]{.ar}   |[Eummun]{.trn}    |fem. |a mother
[غُلَامٌ]{.ar} |[gulAmun]{.trn}   |masc.|a boy
[جَارِيَةٌ]{.ar}|[jAriyatun]{.trn} |fem. |a girl
[أَسَدٌ]{.ar}  |[Easadun]{.trn}   |masc.|a lion
[لَبْوَةٌ]{.ar} |[labwatun]{.trn}  |fem. |a lioness
[ثَوْرٌ]{.ar}  |[vawrun]{.trn}    |masc.|a bull
[بَقَرَةٌ]{.ar} |[baqaratun]{.trn} |fem. |a cow

Even in these nouns you can see that the feminine noun usually ends with a looped [tAE]{.trn} [ة]{.ar} feminine marker. There are only a few commonly used feminine nouns that don't end with a feminine marker like looped [tAE]{.trn}. [أُمٌّ]{.ar} [Eummun]{.trn} "a mother" is one of these exceptions.

### Using the same noun for both sexes

There are other words for animate beings where the same word is used for both sexes. The word itself will still be either grammatically masculine or feminine. Here are some examples:

Arabic word | Transcription|Gender | Definition
:-----------|:-----------|:---|:----------------
[إِنْسَانٌ]{.ar}|[EinsAnun]{.trn}  |masc.|a human
[شَخْصٌ]{.ar}  |[caxSun]{.trn}    |masc.|a person
[نَفْسٌ]{.ar}  |[nafsun]{.trn}    |fem. |a self
[حَيَوَانٌ]{.ar}|[HayawAnun]{.trn} |masc.|an animal
[طَائِرٌ]{.ar} |[TAEirun]{.trn}   |masc.|a bird
[قِرْدٌ]{.ar}  |[qirdun]{.trn}    |masc.|a monkey
[حَمَامَةٌ]{.ar}|[HamAmatun]{.trn} |fem. |a pigeon

So for example [قِرْدٌ]{.ar} [qirdun]{.trn} "a monkey" is grammatically masculine but it can be used for both a male and a female monkey.

By the way, even when the male and female animal have different words, sometimes one of them is used commonly for animals of both sexes, especially when the animal's sex is not obvious or relevant. For example 
[كَلْبٌ]{.ar} [kalb]{.trn} (masc.) is used commonly for "a dog" and [هِرَّةٌ]{.ar} [hirratun]{.trn} (fem.) is used commonly for "a cat".

Similarly [إِنْسَانٌ]{.ar} [EinsAnun]{.trn} "a human" is grammatically masculine but it can be used for both male and female human beings.

//It can be a little tricky using a masculine noun for a female animate being, and vice versa. So, if Allah wills, we will learn how to deal with these nouns in detail.

Note also that [نَفْسٌ]{.ar} [nafsun]{.trn} "a self" is a feminine noun but it does not end in a looped [tAE]{.trn} [ة]{.ar}. It is one of the small number of feminine nouns that don't have a female marker, like [أُمٌّ]{.ar} [Eummun]{.trn} (fem.) "a mother"

## Nouns that designate inanimate objects

Nouns that designate inanimate objects also have a fixed grammatical gender. There is usually no discernable reason why some are assigned a masculine gender while others are assigned a feminine gender.

Arabic word | Transcription|Gender | Definition
:-----------|:-----------|:---|:----------------
[كِتَابٌ]{.ar} |[kitAbun]{.trn}   |masc.|a book
[بَيْتٌ]{.ar}  |[baytun]{.trn}    |masc.|a house
[قَلَمٌ]{.ar}  |[qalamun]{.trn}   |masc.|a pen
[طَعَامٌ]{.ar} |[TaeAmun]{.trn}   |masc.|a food
[مَاءٌ]{.ar}  |[mAEun]{.trn}     |masc.|a water
[مَدْرَسَةٌ]{.ar}|[madrasatun]{.trn}|fem. |a school
[مَدِينَةٌ]{.ar}|[madInatun]{.trn} |fem. |a city
[غُرْفَةٌ]{.ar} |[gurfatun]{.trn}  |fem. |a room
[شَجَرَةٌ]{.ar} |[cajaratun]{.trn} |fem. |a tree
[شَمْسٌ]{.ar}  |[camsun]{.trn}    |fem. |a sun
[قَمَرٌ]{.ar}  |[qamarun]{.trn}   |masc.|a moon
[عِلْمٌ]{.ar}  |[eilmun]{.trn}    |masc.|a knowledge
[قُوَّةٌ]{.ar}  |[quwwatun]{.trn}  |fem. |a strength
[حَيَاةٌ]{.ar} |[HayAtun]{.trn}   |fem. |a life
[مَوْتٌ]{.ar}  |[mawtun]{.trn}    |masc.|a death

In these nouns as well we note that feminine nouns usually end with the feminine marker looped [tAE]{.trn} [ة]{.ar}. 
But here too, we find another exception:
[شَمْسٌ]{.ar} [camsun]{.trn} "a sun" which is feminine but does not end with a feminine marker.
These exceptions are not very many and if Allah wills we will not find it hard to memorize them.

## Vocabulary

### List

### Notes

[ٱِمْرَأٌ]{.ar} and [امرأة] behave a little bit differently than most nouns.

1. when definite article is added
2. when declined in the 3 states, penultimate letter may get declined too.
