# Rules for writing hamzah {#hamzarules}

## Seats of hamzah

Hamzah is written in four different ways:

1. Seated on an [Ealif]{.trn2}: [أ]{.tradar} or [إ]{.tradar}
2. Seated on an [wAw]{.trn2}: [ؤ]{.tradar}
3. Seated on an [yAE]{.trn2}: [ئ]{.tradar}
4. Unseated: [ء]{.tradar}

Here are some of notes about writing hamzah in the above four methods:

+ When unseated hamzah comes between two letters that are joined, then it is written above the line that joins them, for example: [خَطِيءَة]{.tradar} [xaTIEah]{.trn}. In this word, the [yAE]{.trn2} [ي]{.tradar} joins to the [tAE marbUTah]{.trn} [ة]{.tradar}.
  
  As a special case, when unseated hamza comes between joined [lAm]{.trn2} and [Ealif]{.trn2} ([لا]{.tradar}), then it is positioned between them thus: [لءا]{.tradar}. (In most cases, this is replaced with [لآ]{.tradar} as we will explain in the next point below.) And this is different from hamzah on the [Ealif]{.trn2} following the [lAm]{.trn2}: [لأ]{.tradar}.

+ When unseated hamzah is followed by an [Ealif]{.trn2}: [ءا]{.tradar},  the combination of hamzah and [Ealif]{.trn2} is usually written as [آ]{.tradar} as a convention. Examples: [آمَنَ]{.tradar} [EAmana]{.trn}, [ظَمْآن]{.tradar} [PamEAn]{.trn}, [شَنَآن]{.tradar} [canaEAn]{.trn}. However, when the [Ealif]{.trn2} is a suffix or part of a suffix, or the hamzah is doubled, or there is an [Ealif]{.trn2} before the hamzah then we will write [ءا]{.tradar}, not [آ]{.tradar}. Examples: [شَيْءَانِ]{.tradar} [cayEAni]{.trn}, [سَءَّال]{.tradar} [saEEAl]{.trn}, [قِرَاءَات]{.tradar} [qirAEAt]{.trn}. 

+ When hamzah is seated on [Ealif]{.trn2}, if it has an [i]{.trn}-mark, it is written below the [Ealif]{.trn2}: [إِ]{.tradar}. Otherwise, it is written above the [Ealif]{.trn2}: [أَ]{.tradar}, [أُ]{.tradar}, [أْ]{.tradar}.

+ When hamzah is seated on [yAE]{.trn2} [ئ]{.tradar} the dots of the [yAE]{.trn2} are no longer written. Here's how it will appear in different positions:

  Isolated | End | Middle | Beginnning
  :--------|:----|:-------|:----------
  [ئ]{.tradar}| [ـئ]{.tradar}| [ـئـ]{.tradar}| [ئـ]{.tradar}

  Note that hamzah is seated on [yAE]{.trn2} in the middle position [ـئـ]{.tradar} is different from unseated hamzah between two joining letters [ـءـ]{.tradar}.

So how do we know when to write hamzah unseated and when seated? And how do we choose between its three different seats? There are a set of rules that we need to follow in order to correctly write hamzah.

## Rules for determining the seat of hamzah

### Without prefixes and suffixes

We will first learn how to determine the seat of hamzah for a word
without any prefix or suffix.

Hamzah can occur in three positions in a word:

1. At the beginning of the word
1. In the middle of the word
1. At the end of the word

We will treat each of these positions below.

####  At the beginning of the word

When hamzah occurs in the beginning of a word, then:

a. If the hamzah carries a long-[A]{.trn} vowel, it is written unseated followed by an [Ealif]{.trn2} and written as [آ]{.tradar}, for example [آمَنَ]{.tradar} [EAmana]{.trn}.
b. If the hamzah carries any other vowel, it is written seated on an [Ealif]{.trn2}, and is marked with the appropriated vowel mark, for example [أَسْلَمَ]{.tradar} [Easlama]{.trn}, [أُرِيدُ]{.tradar} [EurIdu]{.trn}, [إِسْلَام]{.tradar} [EislAm]{.trn}, [إِيمَان]{.tradar} [EImAn]{.trn}, [أُوخِذَ]{.tradar} [EUxipa]{.trn}. 

#### In the middle of the word

The most general case is when hamzah is in the middle of a word. 

Arabic has three short vowels, three long vowels, two semi-vowels, and a zero-vowel indicated by a [0]{.txt}-mark [◌ْ]{.tradar}. Each of these has an order of precedence and a hamzah seat, that we have shown in the table below:

Precedence | Vowel | Seated hamzah
:--|:------|:-----
1. | [I]{.trn}/[ay]{.trn} | [ء]{.tradar}
2. | [i]{.trn}            | [ئ]{.tradar}
3. | [U]{.trn}/[aw]{.trn} | [ء]{.tradar}
4. | [u]{.trn}            | [ؤ]{.tradar}
5. | [A]{.trn}            | [ء]{.tradar}
6. | [a]{.trn}            | [أ]{.tradar}
7. | [◌ْ]{.tradar}         | [ء]{.tradar}

**Main rule:** Disregard any doubling mark [◌ّ]{.tradar}. Consider the vowel on the consonant before the hamzah and the _shortened_ vowel on the hamzah itself. Determine which of the two vowels wins by being higher in precedence in the above table. The winning vowel's seat will be the seat of the hamzah.

**Sub-rule:** If the main rule determines that hamzah is to be seated on [Ealif]{.trn2}, and there is a long [A]{.trn} vowel on the hamzah using an [Ealif]{.trn2}, then hamzah shall be unseated. And the combination of [ءَا]{.tradar} will usually be written as [آ]{.tradar}.

Examples:

| Word | Vowel on consonant before hamzah | Shortened vowel on hamzah | Winning vowel | Seated hamzah |
|:-----|:-|:-|:-|:------|
|\vphantom{\huge J} [هَيْءَة]{.tradar} [hayEah]{.trn}     | [ay]{.trn} | [a]{.trn}  | [ay]{.trn} | [ء]{.tradar} |
|\vphantom{\huge J} [خَطِيءَة]{.tradar} [xaTIEah]{.trn}   | [I]{.trn}  | [a]{.trn}  | [I]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [اسْتِيءَاس]{.tradar} [EistIEAs]{.trn}| [I]{.trn}  | [a]{.trn}  | [I]{.trn}  | [ء]{.tradar} (Exception: [ءَا]{.tradar} is not written as [آ]{.tradar} when the preceding vowel is [I]{.trn}.)|
|\vphantom{\huge J} [تَوْءَم]{.tradar} [tawEam]{.trn}     | [aw]{.trn} | [a]{.trn}  | [aw]{.trn} | [ء]{.tradar} |
|\vphantom{\huge J} [سَائِل]{.tradar} [sAEil]{.trn}      | [A]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [تَسَاؤُل]{.tradar} [tasAEul]{.trn}   | [A]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [تَسَاءَلَ]{.tradar} [tasAEala]{.trn}  | [A]{.trn}  | [a]{.trn}  | [A]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [قِرَاءَات]{.tradar} [qirAEAt]{.trn}  | [A]{.trn}  | [a]{.trn}  | [A]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [نُوآنٌ]{.tradar} [nUEAnun]{.trn}    | [U]{.trn}  | [a]{.trn} | [U]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [مَسْؤُول]{.tradar} [masEUl]{.trn}    | [◌ْ]{.tradar}   | [u]{.trn}  | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [تَرْئِيس]{.tradar} [tarEIs]{.trn}    | [◌ْ]{.tradar}   | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [مِرْآة]{.tradar} [mirEAh]{.trn}     | [◌ْ]{.tradar}   | [a]{.trn}  | [a]{.trn}  | [ء]{.tradar} (Using sub-rule.)|
|\vphantom{\huge J} [ظَمْآن]{.tradar} [PamEAn]{.trn}     | [◌ْ]{.tradar}   | [a]{.trn}  | [a]{.trn}  | [ء]{.tradar} (Using sub-rule.)|
|\vphantom{\huge J} [مَسْأَلَة]{.tradar} [masEalah]{.trn}  | [◌ْ]{.tradar}   | [a]{.trn}  | [a]{.trn}  | [أ]{.tradar} |
|\vphantom{\huge J} [الْمَرْأَة]{.tradar} [almarEah]{.trn} | [◌ْ]{.tradar}   | [a]{.trn}  | [a]{.trn}  | [أ]{.tradar} |
|\vphantom{\huge J} [بِئْسَ]{.tradar} [biEsa]{.trn}       | [i]{.trn}  | [◌ْ]{.tradar}   | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [سُؤْل]{.tradar} [suEl]{.trn}        | [u]{.trn}  | [◌ْ]{.tradar}   | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [كَأْس]{.tradar} [kaEs]{.trn}        | [a]{.trn}  | [◌ْ]{.tradar}   | [a]{.trn}  | [أ]{.tradar} |
|\vphantom{\huge J} [سُئِلَ]{.tradar} [suEila]{.trn}      | [u]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [يَئِسَ]{.tradar} [yaEisa]{.trn}      | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [رَئِيس]{.tradar} [raEIs]{.trn}      | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [سُؤَال]{.tradar} [suEAl]{.trn}      | [u]{.trn}  | [a]{.trn}  | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [رُؤُوس]{.tradar} [ruEUs]{.trn}      | [u]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [لُؤَيّ]{.tradar} [luEayy]{.trn}      | [u]{.trn}  | [a]{.trn}  | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [شَنَآن]{.tradar} [canaEAn]{.trn}    | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [ء]{.tradar} (Using sub-rule.)|
|\vphantom{\huge J} [سَأَلَ]{.tradar} [saEala]{.trn}      | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.tradar} |
|\vphantom{\huge J} [رَأَىٰ]{.tradar} [raEA]{.trn}        | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.tradar} (Sub-rule doesn't apply because [A]{.trn} vowel at end represented by [ىٰ]{.tradar}, not [Ealif]{.trn2}.)|
|\vphantom{\huge J} [رَأَّسَ]{.tradar} [raEEasa]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.tradar} |
|\vphantom{\huge J} [يُرَئِّسُ]{.tradar} [yuraEEisu]{.trn}  | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [رُئِّسَ]{.tradar} [ruEEisa]{.trn}     | [u]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [تَفَؤُّل]{.tradar} [tafaEEul]{.trn}   | [a]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [سَءَّال]{.tradar} [saEEAl]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [ء]{.tradar} (Using sub-rule.)|
|\vphantom{\huge J} [لَءَّال]{.tradar} [laEEAl]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [ء]{.tradar} (Using sub-rule.)|

#### At the end of the word

When hamzah occurs at the end of a word, disregard the vowel on hamzah itself, and consider only the vowel on preceding consonant.
Plug it into the precedence table as above to determine the seat of hamzah.

| Word | Vowel on consonant before hamzah | Seated hamzah |
|:-----|:-|:------|
|\vphantom{\huge J} [دُعَاءُ]{.tradar} [dueAEu]{.trn}     | [A]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [سُوءُ]{.tradar} [sUEu]{.trn}        | [U]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [جِيءَ]{.tradar} [jIEa]{.trn}        | [I]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [ضَوْءَ]{.tradar} [DawEa]{.trn}       | [aw]{.trn} | [ء]{.tradar} |
|\vphantom{\huge J} [شَيْءَ]{.tradar} [cayEa]{.trn}       | [ay]{.trn} | [ء]{.tradar} |
|\vphantom{\huge J} [بُطْءُ]{.tradar} [buTEu]{.trn}       | [◌ْ]{.tradar}   | [ء]{.tradar} |
|\vphantom{\huge J} [عِبْءُ]{.tradar} [eibEu]{.trn}       | [◌ْ]{.tradar}   | [ء]{.tradar} |
|\vphantom{\huge J} [شَطْءُ]{.tradar} [caTEu]{.trn}       | [◌ْ]{.tradar}   | [ء]{.tradar} |
|\vphantom{\huge J} [يُهَدِّئُ]{.tradar} [yuhaddiEu]{.trn}  | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [سَيِّئُ]{.tradar} [sayyiEu]{.trn}     | [i]{.trn}  | [ئ]{.tradar} |
|\vphantom{\huge J} [بَطُؤَ]{.tradar} [baTuEa]{.trn}      | [u]{.trn}  | [ؤ]{.tradar} |
|\vphantom{\huge J} [يَهْدَأُ]{.tradar} [yahdaEu]{.trn}    | [a]{.trn}  | [أ]{.tradar} |
|\vphantom{\huge J} [مُبْتَدَإِ]{.tradar} [mubtadaEi]{.trn} | [a]{.trn}  | [إ]{.tradar} |

The exception to this rule is when the previous letter is a doubled [wAw]{.trn2} with an [u]{.trn}-mark.
In this case the hamzah will again be unseated. Example [تَبَوُّءُ]{.tradar} [tabawwuEu]{.trn}.

Note also that [مُبْتَدَإِ]{.tradar} [mubtadaEi]{.trn} can be written with the hamzah below the [Ealif]{.trn2} because of the [i]{.trn}-mark on the hamzah.
But it is also common to write it as [مُبْتَدَأ]{.tradar} [mubtadaE]{.trn}, especially when the hamzah is unvoweled.

### With prefixes and suffixes

#### Prefixes

If hamzah is in the beginning of a word, adding a prefix to the word will not alter the writing of the hamzah.
Hamzah will continue to be seated on an [Ealif]{.trn2}.
Here are some examples of words with beginning hamzahs and prefixes.

|Word without prefix | Prefix | Word with prefix
|:---|:-|:---
| \vphantom{\huge J} [أُسْتَاذِ]{.tradar} | [لِ]{.tradar}  | [لِأُسْتَاذِ]{.tradar}
| \vphantom{\huge J} [آخِرَة]{.tradar}  | [الْ]{.tradar} | [الْآخِرَة]{.tradar}

#### Suffixes

If hamzah is at the end of a word, adding a suffix to the word can, in general, alter the writing of the hamzah. 
Hamzah is now, generally, treated as if it is in the middle of the word, and the rules for hamzah in the middle of a word apply.
Examples:  

| Word | Vowel on consonant before hamzah | Shortened vowel on hamzah | Winning vowel | Seated hamzah |
|:-----|:-|:-|:-|:------|
|\vphantom{\huge J} [بَرِيءُونَ]{.tradar} [barIEUna]{.trn}     | [I]{.trn}  | [u]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [بَرِيءَانِ]{.tradar} [barIEAni]{.trn}     | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [بَرِيءِينَ]{.tradar} [barIEIna]{.trn}     | [I]{.trn}  | [i]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [بَرِيءَيْنِ]{.tradar} [barIEayni]{.trn}    | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [شَيْءُهُ]{.tradar} [cayEuhu]{.trn}        | [ay]{.trn} | [u]{.trn} | [ay]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [شَيْءَهُ]{.tradar} [cayEahu]{.trn}        | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [شَيْءِهِ]{.tradar} [cayEihi]{.trn}        | [ay]{.trn} | [i]{.trn} | [ay]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [شَيْءَانِ]{.tradar} [cayEAni]{.trn}       | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [شَيْءَيْنِ]{.tradar} [cayEayni]{.trn}      | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [مَجِيءُهُ]{.tradar} [majIEuhu]{.trn}      | [I]{.trn}  | [u]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [مَجِيءَهُ]{.tradar} [majIEahu]{.trn}      | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [مَجِيءِهِ]{.tradar} [majIEihi]{.trn}      | [I]{.trn}  | [i]{.trn} | [I]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [سُوئِهِ]{.tradar} [sUEihi]{.trn}         | [U]{.trn}  | [i]{.trn} | [i]{.trn}   | [ئ]{.tradar} |
|\vphantom{\huge J} [ضَوْئِهِ]{.tradar} [DawEihi]{.trn}        | [aw]{.trn} | [i]{.trn} | [i]{.trn}   | [ئ]{.tradar} |
|\vphantom{\huge J} [سُوءُهُ]{.tradar} [sUEuhu]{.trn}         | [U]{.trn}  | [u]{.trn} | [U]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [سُوءَهُ]{.tradar} [sUEahu]{.trn}         | [U]{.trn}  | [a]{.trn} | [U]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [سُوءَانِ]{.tradar} [sUEAni]{.trn}        | [U]{.trn}  | [a]{.trn} | [U]{.trn}   | [ء]{.tradar} |
|\vphantom{\huge J} [ضَوْءَهُ]{.tradar} [DawEahu]{.trn}        | [aw]{.trn} | [a]{.trn} | [aw]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [ضَوْءَانِ]{.tradar} [DawEAni]{.trn}       | [aw]{.trn} | [a]{.trn} | [aw]{.trn}  | [ء]{.tradar} |
|\vphantom{\huge J} [مُتَّكِئِينَ]{.tradar} [muttakiEIna]{.trn}  | [i]{.trn}  | [i]{.trn} | [i]{.trn}   | [ئ]{.tradar} |
|\vphantom{\huge J} [يُبَرِّئُونَ]{.tradar} [yubarriEUna]{.trn}  | [i]{.trn}  | [u]{.trn} | [i]{.trn}   | [ئ]{.tradar} |
|\vphantom{\huge J} [يُبَرَّؤُونَ]{.tradar} [yubarraEUna]{.trn}  | [a]{.trn}  | [u]{.trn} | [u]{.trn}   | [ؤ]{.tradar} |

There are some exceptions:

+ If the letter before the hamzah has a [0]{.txt}-mark and is not [wAw]{.trn2} or [yAE]{.trn2},
then the hamzah will be written unseated. Examples:

  + \vphantom{\huge J}  [جُزْءَانِ]{.tradar} [juzEAni]{.trn}  
  + \vphantom{\huge J}  [عِبْءَانِ]{.tradar} [eibEAni]{.trn}  
  + \vphantom{\huge J}  [عِبْءَيْنِ]{.tradar} [eibEayni]{.trn}  
  + \vphantom{\huge J}  [بُطْءَهُ]{.tradar} [buTEahu]{.trn}  
  + \vphantom{\huge J}  [بُطْءُهُ]{.tradar} [buTEuhu]{.trn}  
  + \vphantom{\huge J}  [بُطْءِهِ]{.tradar} [buTEihi]{.trn}

+ If the hamzah is after a long-[U]{.trn} vowel or an [aw]{.trn} semi-vowel, and the hamzah does not have an [i]{.trn}-mark, then it is written unseated. Example:

  + \vphantom{\huge J} [يَسُوءُونَ]{.tradar} [yasUEUna]{.trn}

  This is actually an acceptable variant in the general case, as will discuss below in section\ \@ref(hamza-variants)

([انِ]{.tradar}, [يْنِ]{.tradar}, [هُ]{.tradar}, and [هِ]{.tradar} are suffixes.)
Note that the combination [ءا]{.ar} is not written as [آ]{.ar} when the [Ealif]{.trn2} is part of the suffix.

### [n]{.trn}-marks on final hamzah

[n]{.trn}-marks on a final hamzah do not affect the writing of the hamzah except in the case of [an]{.trn}-mark. When writing [an]{.trn}-mark on a hamzah at the end of a word:

1. If there is an [Ealif]{.trn2} before a unseated hamzah [اء]{.tradar}, then we don't add a silent [Ealif]{.trn2} when writing [an]{.trn}-mark. For example [دَاء]{.tradar} becomes [دَاءً]{.tradar} [dAEan]{.trn}, not [دَاءًا]{.tradar}.

2. Otherwise, we add the silent [Ealif]{.trn2} after the hamzah so that the hamzah is now in the middle of the word with a suffix [Ealif]{.trn2} after it. We now pretend that the hamzah has an [a]{.trn}-mark and that the [Ealif]{.trn2} after it is a long-[A]{.trn} vowel. Then we go through the rules for writing hamzah in the middle of a word (given above) to determine how hamzah will be written. We then write the [an]{.trn}-mark on the hamzah. Examples:

+ \vphantom{\huge J} [مُبْتَدَأ]{.tradar} becomes [مُبْتَدَأٌ، مُبْتَدَءًا، مُبْتَدَإٍ]{.tradar} 
+ \vphantom{\huge J} [مَلْجَأ]{.tradar} becomes [مَلْجَأٌ، مَلْجَءًا، مَلْجَإٍ]{.tradar}
+ \vphantom{\huge J} [جُزْء]{.tradar} becomes [جُزْءٌ، جُزْءًا، جُزْءٍ]{.tradar}
+ \vphantom{\huge J} [شَيْء]{.tradar} becomes [شَيْءٌ، شَيْءًا، شَيْءٍ]{.tradar}
+ \vphantom{\huge J} [سَيِّئ]{.tradar} becomes [سَيِّئٌ, سَيِّئًا, سَيِّئٍ]{.tradar}

### Variants {#hamza-variants}

There are some historical and regional variants to the above rules. The main one is when the letter before hamzah has a [0]{.txt}-mark, the hamzah is generally written unseated. So with this variant, we write:

+ \vphantom{\huge J} [مَسْءُول]{.tradar} instead of [مَسْؤُول]{.tradar}
+ \vphantom{\huge J} [أَسْءِلَة]{.tradar} instead of [أَسْئِلَة]{.tradar}
+ \vphantom{\huge J} [مَسْءَلَة]{.tradar} instead of [مَسْأَلَة]{.tradar}

However, this rule appears to be not consistently followed. For example, [nacEah]{.trn} is generally always written [نَشْأَة]{.tradar} never [نَشْءَة]{.tradar}.

A second variant is to avoid the repetition of vowel letters like [و]{.tradar} and [ي]{.tradar}. So they write:

+ \vphantom{\huge J} [رُءُوس]{.tradar} instead of [رُؤُوس]{.tradar}.
+ \vphantom{\huge J} [رَءِيس]{.tradar} instead of [رَئِيس]{.tradar}.

## Why so complicated?

Hamzah was originally not pronounced everywhere in some Classical Arabic dialects. 
So, for many words, speakers of these dialects would typically only pronounce hamzah in the beginning of a word.
When hamzah would occur in the middle of a word, they would replace it with an [a]{.trn}, [u]{.trn}, or [i]{.trn} vowel.
So they would adjust their pronunciation as follows:

|Proununciation with hamzah | Proununciation without hamzah
|:--|:--
|\vphantom{\huge J}[هَيْءَة]{.tradar} [hayEah]{.trn}   | [هَيَّة]{.tradar} [hayyah]{.trn}     
|\vphantom{\huge J}[خَطِيءَة]{.tradar} [xaTIEah]{.trn} | [خَطِيَّة]{.tradar} [xaTiyyah]{.trn}   
|\vphantom{\huge J}[تَوْءَم]{.tradar} [tawEam]{.trn}   | [تَوَّم]{.tradar} [tawwam]{.trn}
|\vphantom{\huge J}[تَسَاؤُل]{.tradar} [tasAEul]{.trn} | [تَسَاوُل]{.tradar} [tasAwul]{.trn}
|\vphantom{\huge J}[بِئْسَ]{.tradar} [biEsa]{.trn}     | [بِيسَ]{.tradar} [bIsa]{.trn}
|\vphantom{\huge J}[سُؤْل]{.tradar} [suEl]{.trn}      | [سُول]{.tradar} [sUl]{.trn}
|\vphantom{\huge J}[كَأْس]{.tradar} [kaEs]{.trn}      | [كَاس]{.tradar} [kAs]{.trn}

When the Classical Standard Arabic variety emerged,
then, for reasons that are beyond the scope of this text,
the pronunciation _with_ hamzah 
and the consonantal spelling _without_ hamzah became standardized.
So [ء]{.tradar} is now added as a pronunciation mark on top of the various _seats_ that would instead have been dialectally pronounced without hamzah.

## Typographical limitations

Unfortunately, most digital fonts do not currently allow for correctly typing an unseated hamzah between two joined letters 
([ـءـ]{.tradar}), 
as in 
[خَطِيءَة]{.tradar} [xaTIEah]{.trn}.
In most fonts, the hamzah character (Unicode [u+0621]{.texttt}) will break the joining between the two letters surrounding it, and the output will be rendered incorrectly: 
[خَطِيءَة]{.ar} [xaTIEah]{.trn}.

Two typefaces which allow for the correct typesetting are 

+ Amiri from Alif Type ([amirifont.org](https://www.amirifont.org/))
+ Naskh™ from DecoType ([decotype.com](https://www.decotype.com/))

We have used the Amiri font for typesetting this appendix chapter.

For most other fonts, 
an unseated hamzah between two joined letters 
would have to be approximated
in one of two ways:

1. Hamzah superscript on a [kacIdah]{.trn2} character: [ـٔ]{.ar}. Example: [خَطِيـَٔة]{.ar}. The Unicode input sequence is:

   [u+0640]{.texttt} [arabic tatweel]{.smallcaps}  
   [u+0654]{.texttt} [arabic hamza above]{.smallcaps}

   This is a more accurate approximation, but some fonts may not position the hamzah correctly on the [kacIdah]{.trn2}, or position vowel marks on the superscript hamzah correctly.

2. Hamzah seated on [yAE]{.trn2}: [ئ]{.ar}. Example: [خَطِيئَة]{.ar}. This is a more coarse, yet more prevalent, and better supported, approximation.

Beware, though, that neither of these approximations would allow for the correct rendering of a complex (but thankfully rare) word like 
[لَءَّال]{.tradar} [laEEAl]{.trn} "pearl seller", where the hamzah is not allowed to disturb the [lAm-Ealif]{.trn2} ligature [لا]{.tradar}.

