# [إِنَّ]{.ar} and its sisters

## Introduction

In the basic subject-information sentence, both the subject and the information are in the u-state. For example:

```{r,echo=FALSE,engine='tikz', engine.opts = list(template = "srctex/tikz2pdf-lua.tex")}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text=.\txarb{مُعَلِّمٌ} \txarb{ٱَلرَّجُلُ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace}, decorate] 
   (word-1.north west) -- (word-1.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize information};

\draw [decoration={brace}, decorate] 
   (word-2.north west) -- (word-2.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize subject};

\path (0,0) node [midway, below=4.5ex, right=0ex, align=left] {``The man is a teacher.'')};

\end{tikzpicture}
```

In the above sentence both the subject [ٱَلرَّجُلَ]{.ar} "the man", and the information [مُعَلِّمٌ]{.ar} "a teacher" are in the u-state. In this chapter we will study a family of particles, called
[إِنَّ]{.ar} and its sisters,
that modify the subject-information sentence by placing the subject in the a-state instead of the u-state. For example,

[إِنَّ ٱلرَّجُلَ مُعَلِّمٌ.]{.ar}  
[Einna -rrajula mueallimun.]{.trn}  
"Indeed the man is a teacher."

Note how, in the above example, the subject [ٱَلرَّجُلَ]{.ar} "the man" is now in the a-state. The information [مُعَلِّمٌ]{.ar} "a teacher" remains in the u-state. 

The particles constituting the family of 
[إِنَّ]{.ar} and its sisters
are:

1. [إِنَّ]{.ar}  [Einna]{.trn}
1. [أَنَّ]{.ar}  [Eanna]{.trn}
1. [كَأَنَّ]{.ar}  [kaEanna]{.trn}
1. [لَـٰكِنَّ]{.ar}  [lAkinna]{.trn}
1. [لَيْتَ]{.ar}  [layta]{.trn}
1. [لَعَلَّ]{.ar}  [laealla]{.trn}

We shall now study each of these particles.

## [إِنَّ]{.ar} [Einna]{.trn}

[إِنَّ]{.ar} [Einna]{.trn} is used to begin independent sentences. It has an emphatic meaning, as if the speaker is asserting the information about the subject. It is often translated into English as "indeed" or "verily", but it is also often left untranslated.

[إِنَّ]{.ar} [Einna]{.trn} is only used to begin subject-information sentences. Verbal sentences cannot be introduced by [إِنَّ]{.ar} [Einna]{.trn} directly. (Later, in section\ \@ref(damiir-al-shan), we shall see how to overcome this restriction.). For example,

[إِنَّ ٱلدِّينَ عِنْدَ ٱللَّـٰهِ ٱلْإِسْلَامُ.]{.ar}  
[Einna -ddIna einda -llAhi -lEislAmu.]{.trn}  
"Indeed, the religion in the sight of [#allAh]{.trn2} is [#islAm]{.trn2}." ([#qurEAn]{.trn2}\ 3:19, trans. Saheeh International)

[إِنَّ]{.ar} [Einna]{.trn} 
may be preceded by other particles like [وَ]{.ar} "and", [فَ]{.ar} "so", and [ثُمَّ]{.ar} "then". For example,

[ٱُطْلُبِ ٱلْعِلْمَ ٱلنَّافِعَ. فَإِنَّ طَلَبَ ٱلْعِلْمَ ٱلنَّافِعَ عَمَلٌ صَالِحٌ. وَإِنَّ تَرْكَهُ غَفْلَةٌ.]{.ar}
"Seek the useful knowledge. For indeed the seeking of the useful knowledge is a good deed. And indeed leaving it is a negligence."

The subject of
[إِنَّ]{.ar} [Einna]{.trn} 
may be a noun phrase, in which case, any describers or replacements of the subject are also in the a-state. Examples:

[إِنَّ هَـٰؤُلَاءِ ٱلرِّجَالَ ٱلْكِرَامَ أَصْدِقَائِي.]{.ar}  
"Indeed these noble men are my friends."

[إِنَّ]{.ar} [Einna]{.trn} may have multiple subjects, each in the a-state, separated by [وَ]{.ar}. Example,

[إِنَّ ٱلْمُسْلِمِينَ وَٱلْمُسْلِمَاتِ يَبُدُونَ ٱللَّـٰهَ.]{.ar}  
"Indeed the Muslim men and Muslim women worship [#allAh]{.trn2}."

[إِنَّ]{.ar} [Einna]{.trn} may be used to begin sentences with an indefinite subject. For example,

[إِنَّ مَلِكٍا مِنَ ٱلْهِنْدِ كَتَبَ إِلَىٰ أَحَدِ وُزَرَائِهِ.]{.ar}  
"Indeed a king from India wrote to one of his ministers."

Note that in all the above examples that
[إِنَّ]{.ar} [Einna]{.trn} is only used to begin subject-information sentences. Verbal sentences cannot be introduced by [إِنَّ]{.ar} [Einna]{.trn} directly. (Later, in section\ \@ref(damiir-al-shan), we shall see how to overcome this restriction.).
By default, the subject of [إِنَّ]{.ar} [Einna]{.trn} must directly follow it with no intervening words or particles. The only exception is when the information consists of a prepositional or adverbial phrase, it is then allowed to precede the subject. The subject, in any case, shall be in the a-state. For example,

[إِنَّ فِي ٱلْبَيْتِ رَجُلًا.]{.ar}  
"Indeed, in the house, is a man."

[إِنَّ تَحْتَ ٱلشَّجَرَةِ كَنْزًا ثَمِينًا.]{.ar}  
"Indeed, under the tree, is a precious treasure."

This reverse order is permitted even when the subject is definite. For example,

[إِنَّ مَعَكَ صَاحِبَكَ.]{.ar}  
"Indeed, with you, is _your companion_."

This puts the logical accent on the subject [صَاحِبَكَ]{.ar} "your companion". If the subject is placed first then this puts the logical accent on the information:

[إِنَّ صَاحِبَكَ مَعَكَ.]{.ar}  
"Indeed your companion is _with_ you."

If the subject contains a pronoun that refers to a noun in the information then the information must precede the subject. For example,

[إِنَّ فِِي ٱلْمَصْنَعِ عُمَّالَهُ.]{.ar}  
"Indeed, in the factory, are its workers."

[إِنَّ أَمَامَ ٱلدَّارِ حَارِسَهَا.]{.ar}  
"Indeed, in front of the door, is its guard."

### Pronoun subjects

<!--In the examples above, the subject of [إِنَّ]{.ar} has been a noun. -->
The subject of [إِنَّ]{.ar} may be a pronoun instead of a noun. For this the attached pronouns are used. For example,

[لَا تَقْطَعْ تِلْكَ ٱلشَّجَرَةَ فَإِنَّهَا ظَلِيلَةٌ.]{.ar}  
"Don't cut that tree, for it is shady."

[إِنَّكُمَا صَدِيقَايَ.]{.ar}  
"You~2~ are my friends."

The speaker pronouns, both singular and plural, may optionally keep or drop their [ن]{.ar}. 
So for the singular speaker pronoun both [إِنَّنِي]{.ar} [EinnanI]{.trn} and [إِنِّي]{.ar} [EinnI]{.trn} may be used.
And for the plural speaker pronoun both [إِنَّنَا]{.ar} [EinnanA]{.trn} and [إِنَّا]{.ar} [EinnA]{.trn} may be used.
Examples:

[إِنِّي مُسْلِمٌ.]{.ar} or [إِنَّنِي مُسْلِمٌ.]{.ar}  
"Indeed I am a Muslim."

[إِنَّنَا كَاتِبُو هَـٰذَا ٱلْكِتَابَ.]{.ar} or [إِنَّا كَاتِبُو هَـٰذَا ٱلْكِتَابَ.]{.ar}  
"Indeed we are the writers of this book."

[إِنَّ]{.ar} with the speaker pronouns are often used with doer verbal nouns to signify that the speaker intends to to the action of the verb. For example,

[إِنِّي ذَاهِبٌ إِلَىٰ ٱلْمَسْجِدِ.]{.ar}  
"I'm going to the mosque."

We also mentioned this point in section\ \@ref(doer-verbal-noun-for-intended-future-action).
