# Irregular nouns

## Introduction

There are some nouns in Arabic which are _irregular_ and behave a little differently than other _regular_ nouns. In this chapter we will study these irregular nouns.

## The five nouns

There are five nouns in Arabic which are irregular in the same basic way. Collectively, they are called "the five nouns".
They behave a little differently from regular nouns in how they display their state.

We have learned that regular nouns have three states: the u-state, a-state, and i-state. For singular nouns, the u-state is marked by the [u]{.trn}-mark [◌ُ]{.ar}, the a-state is marked by the [a]{.trn}-mark [◌َ]{.ar}, and the i-state is marked by the [i]{.trn}-mark [◌ِ]{.ar}. The [n]{.trn}-marks [◌ٌ]{.ar}, [◌ً]{.ar} and [◌ٍ]{.ar} are only but extensions of [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar} respectively.

We now present the five irregular nouns that behave differently.

### [أَبٌ]{.ar} [Eab]{.trn}, [أَخٌ]{.ar} [Eax]{.trn}, and [حَمٌ]{.ar} [Ham]{.trn}

The first three nouns that we will talk about are:

i. [أَب]{.ar} [Eab]{.trn} "a father"        (root: [أبو]{.arroot}) 
i. [أَخ]{.ar} [Eax]{.trn} "a brother"       (root: [أخو]{.arroot}) 
i. [حَم]{.ar} [Ham]{.trn} "a father-in-law" (root: [حمو]{.arroot}) 

The final root letter of all three of these nouns is [و]{.ar}. However, irregularly, it is omitted in most formations of the word. It does resurface in some cases as we will describe below.

Without the final root letter [و]{.ar}, these nouns display their state like regular nouns. Here are some examples:

[لِلْجَارِيَةِ أَبٌ كَبِيرٌ وَأَخٌ صَغِيرٌ.]{.ar}  
[liljAriyati Eabun kabIrun waEaxun SagIr]{.trn}  
"The girl has an old father and a young brother."

[ضَرَبَ ٱلْغُلَامُ أَخًا لَهُ.]{.ar}  
[Daraba -lgulAmu Eaxan lahu.]{.trn}  
"The boy beat a brother of his."

[ٱَلْحَمُ وَٱلْأَبُ فِي بَيْتِ ٱلْأَخِ.]{.ar}  
[EalHamu walEabu fI bayti -lEax.]{.trn}  
"The father-in-law and the father are in the brother's house."

Where the nouns behave irregularly is when they are an annexe noun in an annexation. Then instead of displaying their state with [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar}, they display their state using the long vowels [و]{.ar} [U]{.trn}, [ا]{.ar} [A]{.trn}, and [ي]{.ar} [I]{.trn} instead. Here are some examples:

[هُوَ أَخُو ٱلْجَارِيَةِ.]{.ar}  
[huwa Eaxu -ljAriyah]{.trn}  
"He is the girl's brother."
<!--
[زَيدٌ أَخُو عَمْرٍو.]{.ar}  
[zaydun EaxU eamrin.]{.trn}  
"Zayd is [e#amr]{.trn2}'s brother."
-->

[سَأَلْتُ أَبَا صَدِيقِي عَنْ أَمْرٍ.]{.ar}  
[saEaltu EabA SadIqI ean Eamr.]{.trn}  
"I asked my friend's father about a matter."

<!--
[شَكَرْتُ لِحَمِي زَيْدٍ.]{.ar}  
[cakartu liHamI zaydin.]{.trn}  
"I thanked Zayd's father-in-law."
-->

[ذَهَبْتُ إِلَىٰ بَيْتِ حَمِي ٱلرَّجُلِ.]{.ar}  
[pahabtu EilA bayti Hami -rrajul.]{.trn}  
"I went to the man's father-in-law's house."

When these nouns are annexed to attached pronouns, then in most cases they will behave as above. So, for example,

[أَبُوهُ]{.ar}  
[EabUhu]{.trn}  
"his father" (u-state).

[أَخَانَا]{.ar}  
[EaxAnA]{.trn}  
"our brother" (a-state).

However, if the attached pronoun is [ي]{.ar} (for the singular speaker participant), then in that case, the attached pronoun [ي]{.ar} attaches to the annexe noun directly, without any intervening long vowel:

<!--
Even when the base noun in the noun-chain is an attached pronoun, these nouns behave in this irregular way, except if the attached pronoun is for the speaking person [ي]{.ar}. In that case, the attached pronoun [ي]{.ar} attaches to the annexe noun directly, without any intervening long vowel. Examples:
-->

[أَخِي]{.ar}  
[EaxI]{.trn}  
"my brother" (u-state, a-state, and i-state).

[أَبِي]{.ar}  
[EabI]{.trn}  
"my father" (u-state, a-state, and i-state).

[حَمِي]{.ar}  
[HamI]{.trn}  
"my father-in-law" (u-state, a-state, and i-state).

Here are some more examples in sentences:

[أَخُوهُ طَوِيلٌ وَأَخُوهَا قَصِيرٌ وَأَخِي كَبِيرٌ.]{.ar}  
[EaxUhu TawIlun waEaxUhA qaSIrun waEaxI kabIr.]{.trn}  
[His brother is tall and her brother is short and my brother is big."

[سَأَلَ أَخَاهُمْ وَأَخَانَا.]{.ar}  
[saEaltu EaxAhum waEaxAnA.]{.trn}  
"I asked their~m,3+~ brother and our brother."

[شَكَرَ أَخِي أَبِي.]{.ar}  
[cakara EaxI EabI.]{.trn}  
"My brother thanked my father."

[ذَهَبْتُ إِلَىٰ بَيْتِ أَخِيهِنَّ.]{.ar}  
[pahabtu EilA bayti EaxIhinn.]{.trn}  
"I went to their~f,3+~ brother's house."

The above irregular behavior of these three nouns is only when they are annexe nouns. When they happen to be base nouns in annexations, then they again they behave like regular nouns and their state is displayed by the short vowel marks [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar}, when definite, and by the [n]{.trn}-marks 
[◌ٌ]{.ar}, 
[◌ً]{.ar}, and
[◌ٍ]{.ar}, when indefinite.
. Examples:

[بَيْتُ ٱلْأَخِ كَبِيرٌ.]{.ar}  
[baytu -lEaxi kabIr.]{.trn}  
"The brother's house is big."

[ذَهَبْتُ إِلَىٰ بَيْتِ أَخٍ.]{.ar}  
[pahabtu EilA bayti Eax.]{.trn}  
"I went to a brother's house."

When these nouns form their duals and plurals, then the final root letter [و]{.ar} is resurfaces.
In forming the broken plural, the final root letter [و]{.ar}, being a weak letter, sometimes converts to a [ء]{.ar}.
The following table shows their duals and plurals.

|Word | Dual (u-state) | Dual (a-state and i-state)|Plural|
|:-|:--|:---|:---|
|[أَب]{.ar} [Eab]{.trn}|[أَبَوَانِ]{.ar} [EabawAni]{.trn}|[أَبَوَيْنِ]{.ar} [Eabawayni]{.trn}|[آبَاء]{.ar} [EAbAE]{.trn}|
|[أَخ]{.ar} [Eax]{.trn}|[أَخَوَانِ]{.ar} [EaxawAni]{.trn}|[أَخَوَيْنِ]{.ar} [Eaxawayni]{.trn}|[إِخْوَة]{.ar} [Eixwah]{.trn}, [إِخْوَان]{.ar} [EixwAn]{.trn}|
|[حَم]{.ar} [Ham]{.trn}|[حَمَوَانِ]{.ar} [HamawAni]{.trn}|[حَمَوَيْنِ]{.ar} [Hamawayni]{.trn}|[أَحْمَاء]{.ar} [EaHmAE]{.trn}|

One special note regarding the dual [أَبَوَانِ]{.ar}/[أَبَوَيْنِ]{.ar}: in addition to meaning "two fathers", they can also mean "both parents", i.e., "a father and a mother". Here are examples of these words in sentences:

[ذَهَبَ ٱلْأَخَوَانِ إِلَى ٱلْمَسْجِدِ.]{.ar}  
[pahaba -lEaxawAni fi -lmasjidi.]{.trn}  
"The brothers~2~ went to the mosque."

[سَأَلْتُ أَخَوَيَّ عَنْ أَمْرٍ]{.ar}  
[saEaltu Eaxawayya ean Eamrin.]{.trn}  
"I asked my brothers~2~ about a matter."

[شَكَرْتُ لِأَبَوَيْهِ]{.ar}  
[cakartu liEabawayhi.]{.trn}  
"I thanked his parents."

### [ذُو]{.ar} [pU]{.trn} and [ذَات]{.ar} [pAt]{.trn}

The fourth irregular noun from "the five nouns" is the masculine noun [ذُو]{.ar} [pU]{.trn} and its feminine counterpart [ذَات]{.ar} and [pAt]{.trn}. The words [ذُو]{.ar} [pU]{.trn} and [ذَات]{.ar} [pAt]{.trn} mean "owner of" or "possessor of". 

So, for example, [ذُو ٱلْمَالِ]{.ar} [pu -lmAli]{.trn} means "possessor~m~ of wealth" or "wealthy person~m~". The singular, dual, and plural of [ذُو]{.ar} [pU]{.trn} in all three states is shown in the table below:

|State|Singular|Dual|Plural|
|:--|:---|:---|:---|
|u-state|[ذُو]{.ar} [pU]{.trn} |[ذَوَا]{.ar} [pawA]{.trn}|[ذَوُو]{.ar} [pawU]{.trn}|
|a-state|[ذَا]{.ar} [pA]{.trn} |[ذَوَيْ]{.ar} [paway]{.trn}|[ذَوِي]{.ar} [pawI]{.trn}|
|i-state|[ذِي]{.ar} [pI]{.trn} |same as a-state|same as a-state|

The noun [ذُو]{.ar} [pU]{.trn} and its duals and plurals are only ever used as annexe nouns in annexations. Furthermore, they may not be annexed to pronouns.

[هَـٰذِهِ ٱلشَّجَرَةُ ذَاتُ ثَمَرٍ كَثِيرٍ.]{.ar}  
[hApihi -ccajaratu pAtu vamarin kavIrin.]{.trn}  
"This tree is the possessor of much fruit." = "This tree is very fruitful."

The word [ذَاتٌ]{.ar} is the feminine of [ذُو]{.ar}. When used as the first noun in a noun chain, its states, duals, and plurals are as in the table below:

|State|Singular|Dual|Plural|
|:--|:---|:---|:---|
|u-state|[ذَاتُ]{.ar} [pAtu]{.trn} |[ذَوَاتَا]{.ar} [pawAtA]{.trn} |[ذَوَاتُ]{.ar} [pawAtu]{.trn}|
|a-state|[ذَاتَ]{.ar} [pAta]{.trn} |[ذَوَاتَيْ]{.ar} [pawAtay]{.trn}|[ذَوَاتِ]{.ar} [pawAti]{.trn}|
|i-state|[ذَاتِ]{.ar} [pAti]{.trn} |same as a-state|same as a-state|


Examples:

As opposed to [ذُو]{.ar} which is only used in noun-chains, [ذَاتٌ]{.ar} may be used a noun in its own right. In this case it means "personality" or "essence". This usage is often found in theological or philosophical works. And, as such, unlike [ذُو]{.ar} which can't have attached pronouns, [ذَاتٌ]{.ar} can be used with attached pronouns. Examples:

### [فُو]{.ar} [fU]{.trn}

The fifth noun in this discussion is [فُو]{.ar} [fU]{.trn}. It is the most irregular noun so far in that it is derived from [فَمٌ]{.ar} [famun]{.trn} "mouth". 

The word [فَمٌ]{.ar} [famun]{.trn} (plural [أَفْواهٌ]{.ar} [EafwAhun]{.trn}) may be used regularly in forming duals, attaching pronouns to it, etc. Examples:

[فَمَا ٱلنَّهْرَيْنِ كَبِيرَانِ.]{.ar}  
[fama -nnahrayni kabIrAni.]{.trn}  
"The mouths~2~ of the rivers~2~ are big."

[فَمِي مَفْتُوحٌ.]{.ar}  
[famI maftUhun.]{.trn}  
"My mouth is open."

[فَمُهَا جَمِيلٌ.]{.ar}  
[famuhA jamIlun.]{.trn}  
"Her mouth is beautiful."

[فَتَحَ فَمَهُ.]{.ar}  
[fataHa famahu.]{.trn}  
"He opened his mouth."

[جَعَلَتِ ٱلْأُمُّ لُقْمَةَ طَعَامٍ فِي فَمِ ٱبْنَتِهَا.]{.ar}  
[jaealati -lEummu luqmata TaeAmin fI fami -bnatihA.]{.trn}  
"The mother put a morself of food in her daughter's mouth."

In addition to the above regular behavior of [فَمٌ]{.ar} [famun]{.trn} "mouth", when the word is singular and is the first noun in a noun-chain, it is common to replace it with [فُو]{.ar} [fU]{.trn}. This is also done when the second noun in the noun-chain is a pronoun. 

The three states of the singular [فُو]{.ar} [fU]{.trn} are shown in the table below:

|u-state|a-state|i-state|
|:---|:---|:---|
|[فُو]{.ar} [fU]{.trn} |[فَا]{.ar} [fA]{.trn} |[فِي]{.ar} [fI]{.trn}|

Examples of usage:

[فُو ٱلنَّهْرِ كَبِيرٌ.]{.ar}  
[fu -nnahri kabIrun.]{.trn}  
"The mouth of the river is big."

[فُوهَا جَمِيلٌ.]{.ar}  
[fUhA jamIlun.]{.trn}  
"Her mouth is beautiful."

[فَتَحَ فَاهُ.]{.ar}  
[fataHa fAhu.]{.trn}  
"He opened his mouth."

[جَعَلَتِ ٱلْأُمُّ لُقْمَةَ طَعَامٍ فِي فِي ٱبْنَتِهَا.]{.ar}  
[jaealati -lEummu luqmata TaeAmin fI fi -bnatihA.]{.trn}  
"The mother put a morself of food in her daughter's mouth."

When the attached pronoun for the speaking person [ي]{.ar} is attached to [فُو]{.ar} [fU]{.trn}, [فَا]{.ar} [fA]{.trn}, or [فِي]{.ar} [fI]{.trn} the combination is always [فِيَّ]{.ar} [fiyya]{.trn} in all three states. Examples:

[فِيَّ مَفْتُوحٌ.]{.ar}  
[fiyya maftUhun.]{.trn}  
"My mouth is open."

[فَتَحْتُ فِيَّ.]{.ar}  
[fataHtu fiyya.]{.trn}  
"I opened my mouth."

[أَكَلْتُ بِفِيَّ.]{.ar}  
[Eakaltu bifiyya.]{.trn}  
"I ate with my mouth."

As mentioned above, [فُو]{.ar} [fU]{.trn} typically only replaces [فَمٌ]{.ar} [famun]{.trn} "mouth", when the word is singular and is the first noun in a noun-chain. Otherwise, [فَمٌ]{.ar} [famun]{.trn} continues to be used.

## Other irregular nouns

There are more nouns that have irregularity in their own ways. We will discuss them below.

[سنة ، سنون، سنين، سنوات]{.ar}

[أم، أمهاتة]{.ar}

[أولون]{.ar} no singular, mostly used as annexe noun
[ماء مياه]{.ar}
[شفة شفاه]{.ar}
[إنسان أناس الناس ناس]{.ar}

Nouns starting with connecting hamza: ابن است ...

### The nouns [ابن]{.ar} and [ابنة]{.ar}

<!--
## Nouns that begin with connecting [hamzah]{.trn}

When the definite article [ٱَلْ]{.ar} [Eal]{.trn} is prefixed to a noun which begins with a connecting [hamzah]{.trn}, the [hamzah]{.trn} is not pronounced. Instead the [lAm]{.trn} in [ٱَلْ]{.ar} will take an [i]{.trn}-mark. For example, [ٱِبْنٌ]{.ar} [Eibnun]{.trn} "a son" becomes [ٱَلِٱبْنُ]{.ar} [Ealibnu]{.trn} "the son".
-->

### The nouns [ٱِمْرَأ]{.ar} and [ٱِمْرَأَة]{.ar}

There are two nouns which are irregular in their definiteness and indefniteness that we will now discuss:

Besides [رَجُلٌ]{.ar} [rajulun]{.trn} "a man", Arabic has another word for "a man": [ٱِمْرَأٌ]{.ar} [EimraEun]{.trn} (u-state). In the a-state and i-state, this word would regularly become [ٱِمْرَءًا]{.ar} [EimraEan]{.trn} and [ٱِمْرَإٍ]{.ar} [EimraEin]{.trn} respectively. However, as a very common variant, it appears with the [n]{.trn}-marks as shown in the table below:

State         | Regular indefinite | Irregular indefinite
:-------------|:-----------------|:--------------
u-state       |[ٱِمْرَأٌ]{.ar} [EimraEun]{.trn} |[ٱِمْرُؤٌ]{.ar} [EimruEun]{.trn}
a-state       |[ٱِمْرَءًا]{.ar} [EimraEan]{.trn}|[ٱِمْرَءًا]{.ar} [EimraEan]{.trn}
i-state       |[ٱِمْرَإٍ]{.ar} [EimraEin]{.trn} |[ٱِمْرِئٍ]{.ar} [EimriEin]{.trn}

As you can see, the state of the noun affects the vowel not only on the final letter but also on the letter before it. This irregularity is only commonly found with this noun.

Also irregularly, when making this noun definite by prefixing [ٱَلْ]{.ar}, the noun loses its connecting [hamzah]{.trn} altogether and is further modified somewhat from the indefinite. It must be noted that this is the only form allowed for the definite.

State         | Definite
:-------------|:-----------------
u-state       |[ٱَلْمَرْءُ]{.ar} [EalmarEu]{.trn}
a-state       |[ٱَلْمَرْءَ]{.ar} [EalmarEa]{.trn}
i-state       |[ٱَلْمَرْءِ]{.ar} [EalmarEi]{.trn}

The counterpart of this noun [ٱِمْرَأَةٌ]{.ar} [EimraEatun]{.trn} "a woman" is also irregular but only in forming the definite noun:

State         | Indefinite                    | Definite
:-------------|:-----------------|:-----------------
u-state       |[ٱِمْرَأَةٌ]{.ar} [EimraEatun]{.trn}|[ٱَلْمَرْأَةُ]{.ar} [EalmarEatu]{.trn}
a-state       |[ٱِمْرَأَةً]{.ar} [EimraEatan]{.trn}|[ٱَلْمَرْأَةَ]{.ar} [EalmarEata]{.trn}
i-state       |[ٱِمْرَأَةٍ]{.ar} [EimraEatin]{.trn}|[ٱَلْمَرْأَةِ]{.ar} [EalmarEati]{.trn}

By the way, what is difference between [رَجُلٌ]{.ar} [rajulun]{.trn} and [ٱِمْرَأٌ]{.ar} [imraEun]{.trn}?
There is some degree of overlap but the noun [رَجُلٌ]{.ar} [rajulun]{.trn} is used more commonly when talking about male human beings.
[ٱِمْرَأٌ]{.ar} [imraEun]{.trn} is used generally when speaking about "man" generically, for example, in sentences like "Man is a social animal." and "A man should always be honest." It is also often used to mean "a person".


