# The verb [كَانَ]{.ar} {#the-verb-kaana}

## Introduction

We have learned that a verb must have a doer in the u-state and can have a direct doee in the a-state.
In this chapter, we will learn about a new type of verb, whose doer is called its subject, and whose direct doee is called its information.

The principal verb of this type is [كَانَ]{.ar} which is used to mean "was". There are other verbs which behave in a similar manner and they are called the _sisters_ of [كَانَ]{.ar}.

## [كَانَ]{.ar}, its subject, and its information

Consider the sentence:

[ٱلرَّجُلُ مُعَلِّمٌ.]{.ar}  
"The man is a teacher."

This is a subject-information sentence. 
[ٱلرَّجُلُ]{.ar} is the subject in the u-state, and
[مُعَلِّمٌ]{.ar} is the information, also in the u-state.
Arabic does not, in this case, express any word for "is".

Consider now the following sentence:

<!--
[كَانَ ٱلرَّجُلُ مُعَلِّمًا.]{.ar}  
"The man was a teacher."
-->


```{r,echo=FALSE,engine='tikz', fig.ext='pdf', engine.opts = list(template = if (knitr::is_html_output()) "srctex/tikz2pdf-lua-html.tex" else "srctex/tikz2pdf-lua.tex")}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=2.0ex}]
\path [decoration={text effects along path, 
  text=.\txarb{مُعَلِّمًا} \txarb{ٱَلرَّجُلُ} \txarb{كَانَ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, rotate=90, anchor=south, left=0ex, align=left] {\scriptsize direct doee/\\\scriptsize information};

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, rotate=90, anchor=south, left=0ex, align=left] {\scriptsize doer/\\\scriptsize subject};

%\path (0,0) node [midway, below=4.5ex, right=0ex, align=left] {``The man was a teacher.''};

\end{tikzpicture}
```

Now, as you can see, Arabic does express a word for "was". It is the past verb [كَانَ]{.ar} [kAna]{.trn}.
[كَانَ]{.ar} is a hollow verb from the root [كون]{.arroot}. 
It's resembling verb is [يَكُونُ]{.ar} [yakUnu]{.trn}.
The complete table for this verb for all doer pronouns is given below:

|Doer pronoun|past verb|resembling verb|
|:----|:----|:----|
| he        | [كَانَ]{.ar}   | [يَكُونُ]{.ar}   |
| she       | [كَانَتْ]{.ar}  | [تَكُونُ]{.ar}   |
| you~1m~   | [كُنْتَ]{.ar}   | [تَكُونُ]{.ar}   |
| you~1f~   | [كُنْتِ]{.ar}   | [تَكُونِينَ]{.ar} |
| I         | [كُنْتُ]{.ar}   | [أَكُونُ]{.ar}   |
| they~2m~  | [كَانَا]{.ar}  | [يَكُونَانِ]{.ar} |
| they~2f~  | [كَانَتَا]{.ar} | [تَكُونَانِ]{.ar} |
| you~2~    | [كُنْتُمَا]{.ar} | [تَكُونَانِ]{.ar} |
| they~3m~  | [كَانُوا]{.ar} | [يَكُونُونَ]{.ar} |
| they~3f~  | [كُنَّ]{.ar}    | [يَكُنَّ]{.ar}    |
| you~3m~   | [كُنْتُمْ]{.ar}  | [تَكُونُونَ]{.ar} |
| you~3f~   | [كُنْتُنَّ]{.ar}  | [تَكُنَّ]{.ar}    |
| we        | [كُنَّا]{.ar}   | [نَكُونُ]{.ar}   |

Like, for other verbs, 
the doer of [كَانَ]{.ar},
[ٱلرَّجُلُ]{.ar}, is in the u-state, and
and its direct doee, [مُعَلِّمًا]{.ar}, is in the a-state.

However, unlike most other verbs,
the doer of [كَانَ]{.ar},
[ٱلرَّجُلُ]{.ar}, is also called its subject
and its direct doee, [مُعَلِّمًا]{.ar}, is also called its information.

So a sentence with [كَانَ]{.ar} used in this way is a subject-information sentence.
If it begins with [كَانَ]{.ar} then it is also a verbal sentence at the same time.

This property also applies to the sisters of [كَانَ]{.ar} that we will learn later in this chapter. 
Together, these verbs are also called _deficient_ verbs, because, besides their doer/subject, they also need an information to complete the meaning of the sentence.
That is, without the information, the sentence is deficient.

"Is" subject-information sentences can be converted to "was" subject-information sentences using the verb [كَانَ]{.ar}. Here are some examples:

| "is" | "was" |
|:-|:-|
| [زَيْنَبُ جَائِعَةٌ.]{.ar}  |[كَانَتْ زَيْنَبُ جَائِعَةً.]{.ar}  |
| "Zaynab is hungry." |"Zaynab was hungry."     |
| [ٱَلْغُلَامُ زَيْدٌ.]{.ar}  |[كَانَ ٱلْغُلَامُ زَيْدًا.]{.ar} |
| "The boy is Zayd."  |"The boy was Zayd."     |
| [ٱَلنِّسَاءُ فِي بُيُوتِهِنَّ.]{.ar}         |[كَانَتْ ٱلنِّسَاءُ فِي بُيُوتِهِنَّ.]{.ar}     |
| "The women are in their houses." |"The women were in their houses." |
| [هُمْ مَسْرُورُونَ وَفَرِحُونَ.]{.ar}            | [كَانُوا مَسْرُورِينَ وَفَرِحِينَ.]{.ar}     |
| "They~3m~ are happy and rejoicing."  | "They~3m~ were happy and rejoicing." |
| [أَنَا نَائِمَةٌ.]{.ar}                | [كُنْتُ نَائِمَةً.]{.ar}       |
| "I~1f~ am sleeping."             | "I~1f~ was sleeping."|
| [أَنْتَ لِي أَخٌ.]{.ar}               | [كُنْتَ لِي أَخًا.]{.ar}            |
| "You~1m~ are a brother to me.   | "You~1m~ were a brother to me.|

### Sequence of [كَانَ]{.ar}, its subject, and its information

In sentence word order, the natural sequence is 
<!--[كَانَ]{.ar}, its subject, and its information, as -->
verb, subject, information.

[كَانَ زَيْدٌ قَائِمًا.]{.ar}  
"Zayd was standing."

but we may also, for the same meaning, apply the sequence verb, information, subject:

[كَانَ قَائِمًا زَيْدٌ.]{.ar}  
"Zayd was standing."

and also the sequence information, verb, subject:

[قَائِمًا كَانَ زَيْدٌ.]{.ar}  
"Zayd was standing."

This last order is common in questions and alternative sentence sentences. For example:

[أَقَائِمًا كَانَ زَيْدٌ.]{.ar}  
"Was Zayd standing?"

[ٱُدْعُ زَيْدًا قَائِمًا كَانَ أَوْ جَالِسًا!]{.ar}  
"Call Zayd, be he standing or sitting!"

<!--See Wright vol. ii. Section 41 Rem a, p. 100B -->

Sometimes, however, this inversion is impossible because of an indistinguishable state of the two nouns.

For example, in order to express "My brother was my companion," we must say:

[كَانَ أَخِي رَفِيقِي.]{.ar}  
"My brother was my companion."

This is because, if we invert it, it would naturally mean:

[كَانَ رَفِيقِي أَخِي.]{.ar}  
"My companion was my brother."

The following apparent sequence is also possible:

[زَيْدٌ كَانَ قَائِمًا.]{.ar}  
"Zayd: he was standing."

But this is actually a topic-comment sentence.
[زَيْدٌ]{.ar} is the topic.
And the comment is [كَانَ قَائِمًا]{.ar}, which is itself a [كَانَ]{.ar} subject-information sentence in the sequence verb, subject, information.
The subject is the hidden pronoun "he" and the information is [قَائِمًا]{.ar}.

### Plurals of non-rational beings with [كَانَ]{.ar}

Because [كَانَ]{.ar} sentences are subject-information being sentences, 
many of the rules that we have learned for subject-information sentences also apply to [كَانَ]{.ar} sentences.
One such rule is that when the subject of a sentence is a plural of non-rational beings, and the information is a adjectival noun, then the feminine singular adjectival noun is often used. (See section\ \@ref(usage-of-plurals-of-non-intelligent-beings).)
For example:

[كَانَتِ ٱلْبُيُوتُ صَغِيرَةً.]{.ar} (typical)  
"The houses were small."  

Also allowed, but not as common:  
[كَانَتِ ٱلْبُيُوتُ صَغِيرَاتٍ.]{.ar}  
[كَانَتِ ٱلْبُيُوتُ صِغَارًا.]{.ar}  

[ٱلثِّيرَانُ كَانَتْ ضَخْمَةً.]{.ar} (typical)  
"The bulls were large."

Also allowed, but not as common:  
[ٱلثِّيرَانُ كَانَتْ ضِخَامًا.]{.ar}  
[ٱلثِّيرَانُ كُنَّ ضَخْمَاتٍ.]{.ar}  

### [كَانَ]{.ar} with a separating pronoun

Another rule that applies to subject-information sentences, and that carries over to 
[كَانَ]{.ar} sentences, is that
when the subject and information are both definite, 
then a separating pronoun, which is a detached pronoun that matches the subject, can be inserted between them.
For example,

[كَانَ ٱلْمُؤْمِنُونَ هُمُ ٱلْفَائِزِينَ.]{.ar}  
"The believers were the winners."

<!--
[ٱَلْمُؤْمِنُونَ هُمُ ٱلْفَائِزُونَ.]{.ar}  
"The believers are the winners."
-->

The separating pronoun [هُمْ]{.ar} does not, in this case, serve to disambiguate the information [ٱلْفَائزِينَ]{.ar} "the winners", from being a describer, as it did in sentences without [كَانَ]{.ar} (see section\ \@ref(subject-information-sentences-separating-pronoun)).
This is because the a-state of [ٱلْفَائزِينَ]{.ar} already tells us that it is the information of [كَانَ]{.ar}. 
If [ٱلْفَائزِينَ]{.ar} were a describer of the u-state subject [ٱَلْمُوْمِنُونَ]{.ar}, then it too would be in the u-state, not the a-state.
So the separating pronoun serves more, here, to emphasize the subject.

Most of the time, separating pronouns are used in [كَانَ]{.ar} sentences when the subject of [كَانَ]{.ar} is itself a pronoun. Examples:

[وَكُنَّا نَحْنُ ٱلْوَارِثِينَ]{.ar}  
"And it is We who were the inheritors" [al-[#qurEAn]{.trn2} 28:58, translation by Saheeh International]

[كُنْتَ أَنْتَ ٱلرَّقِيبَ عَلَيْهِمْ]{.ar}  
"You were the Observer over them" [al-[#qurEAn]{.trn2} 5:117, translation by Saheeh International]

Sometimes a pronoun may appear to be a separating pronoun, but actually is not one. Consider, for example, the following sentence:

[كَانَ ٱلْمُؤْمِنُونَ هُمُ ٱلْفَائِزُونَ.]{.ar}  
"The believers were the winners."

Note that [ٱَلْفَائِزُونَ]{.ar} is in the u-state, so it is not, by itself, the information of [كَانَ]{.ar}.
So this is, in fact, a topic-comment sentence.
[ٱَلْمُوْمِنُونَ]{.ar} is the topic and the subject of [كَانَ]{.ar}.
The information of [كَانَ]{.ar} is the comment [هُمُ ٱلفَائِزُونَ]{.ar}, which is itself a subject-information sentence with a u-state subject ([هُمْ]{.ar}) and a u-state information ([ٱلْفَائزُونَ]{.ar}).

### Negating [كَانَ]{.ar}

Like other past verbs,
the verb [كَانَ]{.ar}
may be negated by preceding it with the particle [مَا]{.ar}. For example:

[مَا كَانَ إِبْرَٰهِيمُ يَهُودِيًّۭا وَلَا نَصْرَانِيًّۭا وَلَـٰكِن كَانَ حَنِيفًۭا مُّسْلِمًۭا وَمَا كَانَ مِنَ ٱلْمُشْرِكِينَ]{.ar}  
"Abraham was neither a Jew nor a Christian, but he was one inclining toward truth, a Muslim [submitting to Allāh]. And he was not of the polytheists."
([al-#qurEAn]{.trn2} 3:67, translation Saheeh International)

A similar meaning may be obtained with the particle [لَمْ]{.ar} followed by the
[0]{.txt}-state
resembling verb
[يَكُنْ]{.ar}.
This is dealt with in section\ \@ref(lam-yakun) below.

## The resembling verb of [كَانَ]{.ar}

### The u-state resembling verb [يَكُونُ]{.ar}

We have already mentioned that Arabic does not usually express any word for "is".
So when, then, is the u-state resembling verb [يَكُونُ]{.ar} used?
There are actually a few uses of this verb. We will explain them below:

#### [يَكُونُ]{.ar} used for habitual "is"

Consider the sentence, "The mother cooks the food." 
The verb "cooks" implies that the action is habitually done, not necessarily that it is being done at present. 
If we wished to say that the action is being done at present, we might instead say, "The mother _is cooking_ the food."
English maintains this distinction between the present and the habitual for most verbs.
But it does not for ther verb "is".
So if we say, "The sky is blue," then it can mean both 
(i) that the sky is blue at present, or 
(ii) that it is habitually blue, not necessarily that it is blue at present.

In Arabic the situation is somewhat different.
Arabic does not usually have a distinction between the present and the habitual for most verbs. So [تَطْبُخُ الْأُمُّ الطَّعَامَ.]{.ar}  may mean both
(i) that the mother is cooking the food at present, or
(ii) that she habitually does.

<!--However, interestingly, Arabic does have the distinction between the present and the habitual for the verb "is".
As you know, Arabic does not usually express a word for the present "is".-->
But for the verb "is", Arabic can distinguish between the present and the habitual.
So if we say [السَّمَاءُ زَرْقَاءُ]{.ar}, then this can, in general, mean both
(i) that the sky is blue at present, and
(ii) that it is habitually blue.
If we wish to emphasize the habitual meaning, we may use the resembling verb [يَكُونُ]{.ar}, thus:

[تَكُونُ السَّمَاءُ زَرْقَاءَ.]{.ar}  
"The sky is [habitually] blue."

While we call this the 
habitual [يَكُونُ]{.ar},
it can include a range of meanings, including
continually, recurringly, regularly, typically, generally, often, sometimes, can, may, etc.
Habitual [يَكُونُ]{.ar} is negated using [مَا]{.ar} or [لَا]{.ar}, just like other u-state resembling verbs.

Here are some examples:

[قَالَ وَمَا الْبِتْعُ وَالْمِزْرُ؟ قُلْتُ شَرَابٌ يَكُونُ مِنَ الْعَسَلِ وَالْمِزْرُ يَكُونُ مِنَ الشَّعِيرِ]{.ar}  
"He said: 'What is mead and beer?' I said: 'A drink [made] from honey, and beer is [made] from barley.'  
<!--(From [سنن النسائي]{.ar}:5604)-->
(Part of [HadIv]{.trn2} 5604 from [#sunan al-#nisAEI]{.trn2})

<!--
[إِنَّ أَحَدَكُمْ لَيَعْمَلُ بِعَمَلِ أَهْلِ الْجَنَّةِ حَتَّى مَا يَكُونُ بَيْنَهُ وَبَيْنَهَا إِلاَّ ذِرَاعٌ]{.ar}  
"One of you will do deeds of the people of Paradise, until there is between him and it but a forearm span"  
(Part of [HadIv]{.trn2} 2137 from [#jAmie al-#tirmipI]{.trn2})
From [جامع الترمذي]{.ar}:2137)-->

[يَكُونُ اللِّحَافُ وِسَادَةً وَلَا تَكُونُ الْوِسَادَةُ لِحَافًا.]{.ar}  
"The blanket can be a pillow but the pillow cannot be a blanket."

[مَا يَكُونُ الرَّجُلُ صَدِيقَكَ حَتّى يَصْدُقَكَ.]{.ar}  
"A man is not your friend until he is truthful to you."

##### [قَدْ يَكُونُ]{.ar} for "may be"

When the meaning "may be" is desired, the 
the resembling verb
[يَكُونُ]{.ar}
may be preceded by the particle [قَدْ]{.ar}. For example,

[قَدْ يَكُونُ الاسْتِهْزَاءُ كُفْرًا.]{.ar}  
"Mocking may be a disbelief."

#### [يَكُونُ]{.ar} used for future "will be"

Another usage of the resembling verb
[يَكُونُ]{.ar}
is for the future tense to mean "will be".
In this case, it is often preceded by [سَ]{.ar} or [سَوْفَ]{.ar}.
[سَ]{.ar} and [سَوْفَ]{.ar} are optional and are commonly dropped, especially when the context indicates the future.
Future [يَكُونُ]{.ar}
is negated by [لَا]{.ar}.
Here are some examples:

[فَقَدْ كَذَّبْتُمْ فَسَوْفَ يَكُونُ لِزَامًا]{.ar}  
"For you [disbelievers] have denied, so it [i.e., your denial] is going to be adherent."  
([al-#qurEAn]{.trn2} 25:77, translation Saheeh International)

[لا يَكونُ اللَّعَّانُونَ شُفَعَاءَ وَلَا شُهَدَاءَ يَومَ القِيَامَةِ]{.ar}  
"The frequent cursers will be neither intercessors nor witnesses [on] the day of resurrection."  
([#hadIv]{.trn2} 1553 from [#riyAD al-#SAliHIn]{.trn2}, [يَوْمَ]{.ar} is in the a-state because it is an adverb of time, see chapter\ \@ref(adverb-of-time).)

[يَوْمَ يَكُونُ ٱلنَّاسُ كَٱلْفَرَاشِ ٱلْمَبْثُوثِ]{.ar}  
"It is the Day when people will be like moths, dispersed,"  
([al-#qurEAn]{.trn2} 101:4, translation Saheeh International)

### The a-state resembling verb [يَكُونَ]{.ar}

Like a-state resembling verbs in general, [يَكُونَ]{.ar} "be" expresses the meaning of purpose, wish, or expectation. It occurs after the particles
[أَنْ]{.ar},
[لَنْ]{.ar},
[لِ]{.ar},
[كَيْ]{.ar},
[حَتَّىٰ]{.ar}, and
[إِذَنْ]{.ar}.
All this is consistent with what we have learned about a-state resembling verbs in chapter\ \@ref(a-state-incomplete-action-verbs).
Here are some examples:

[نَزَلَ بِهِ ٱلرُّوحُ ٱلْأَمِينُ. عَلَىٰ قَلْبِكَ لِتَكُونَ مِنَ ٱلْمُنذِرِينَ]{.ar}  
"The Trustworthy Spirit [i.e., Gabriel] has brought it down. Upon your heart, [O Muḥammad] - that you may be of the warners -"  
([al-#qurEAn]{.trn2} 26:193--194, translation Saheeh International)

[لَّن يَسْتَنكِفَ ٱلْمَسِيحُ أَن يَكُونَ عَبْدًۭا لِّلَّهِ وَلَا ٱلْمَلَـٰٓئِكَةُ ٱلْمُقَرَّبُونَ]{.ar}  
"Never would the Messiah disdain to be a servant of Allāh, nor would the angels near [to Him]"  
(From [al-#qurEAn]{.trn2} 4:172, translation Saheeh International)

[أَفَأَنتَ تُكْرِهُ ٱلنَّاسَ حَتَّىٰ يَكُونُوا۟ مُؤْمِنِينَ]{.ar}  
"Then, [O Muḥammad], would you compel the people in order that they become believers?"  
([al-#qurEAn]{.trn2} 10:99, translation Saheeh International)

### The [0]{.txt}-state resembling verb [يَكُنْ]{.ar} {#lam-yakun}




