# [كَانَ]{.ar} and its sisters

## Introduction

We have learned that a verb must have a doer in the u-state and can have a direct doee in the a-state.
In this chapter, we will learn about a new type of verb, whose doer is called its subject, and whose direct doee is called its information.

The principal verb of this type is [كَانَ]{.ar} which is used to mean "was". There are other verbs which behave in a similar manner and they are called the _sisters_ of [كَانَ]{.ar}.

## [كَانَ]{.ar}, its subject, and its information

Consider the sentence:

[ٱلرَّجُلُ مُعَلِّمٌ.]{.ar}  
"The man is a teacher."

This is a subject-information sentence. 
[ٱلرَّجُلُ]{.ar} is the subject in the u-state, and
[مُعَلِّمٌ]{.ar} is the information, also in the u-state.
Arabic does not, in this case, express any word for "is".

Consider now the following sentence:

<!--
[كَانَ ٱلرَّجُلُ مُعَلِّمًا.]{.ar}  
"The man was a teacher."
-->


```{r,echo=FALSE,engine='tikz', fig.ext='pdf', engine.opts = list(template = if (knitr::is_html_output()) "srctex/tikz2pdf-lua-html.tex" else "srctex/tikz2pdf-lua.tex")}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=2.0ex}]
\path [decoration={text effects along path, 
  text=.\txarb{مُعَلِّمًا} \txarb{ٱَلرَّجُلُ} \txarb{كَانَ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, rotate=90, anchor=south, left=0ex, align=left] {\scriptsize direct doee/\\\scriptsize information};

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, rotate=90, anchor=south, left=0ex, align=left] {\scriptsize doer/\\\scriptsize subject};

%\path (0,0) node [midway, below=4.5ex, right=0ex, align=left] {``The man was a teacher.''};

\end{tikzpicture}
```

Now, as you can see, Arabic does express a word for "was". It is the past verb [كَانَ]{.ar} [kAna]{.trn}.
[كَانَ]{.ar} is a hollow verb from the root [كون]{.arroot}. 
It's resembling verb is [يَكُونُ]{.ar} [yakUnu]{.trn}.
The complete table for this verb for all doer pronouns is given below:

|Doer pronoun|past verb|resembling verb|
|:----|:----|:----|
| he        | [كَانَ]{.ar}   | [يَكُونُ]{.ar}   |
| she       | [كَانَتْ]{.ar}  | [تَكُونُ]{.ar}   |
| you~1m~   | [كُنْتَ]{.ar}   | [تَكُونُ]{.ar}   |
| you~1f~   | [كُنْتِ]{.ar}   | [تَكُونِينَ]{.ar} |
| I         | [كُنْتُ]{.ar}   | [أَكُونُ]{.ar}   |
| they~2m~  | [كَانَا]{.ar}  | [يَكُونَانِ]{.ar} |
| they~2f~  | [كَانَتَا]{.ar} | [تَكُونَانِ]{.ar} |
| you~2~    | [كُنْتُمَا]{.ar} | [تَكُونَانِ]{.ar} |
| they~3m~  | [كَانُوا]{.ar} | [يَكُونُونَ]{.ar} |
| they~3f~  | [كُنَّ]{.ar}    | [يَكُنَّ]{.ar}    |
| you~3m~   | [كُنْتُمْ]{.ar}  | [تَكُونُونَ]{.ar} |
| you~3f~   | [كُنْتُنَّ]{.ar}  | [تَكُنَّ]{.ar}    |
| we        | [كُنَّا]{.ar}   | [نَكُونُ]{.ar}   |

Like, for other verbs, 
the doer of [كَانَ]{.ar},
[ٱلرَّجُلُ]{.ar}, is in the u-state, and
and its direct doee, [مُعَلِّمًا]{.ar}, is in the a-state.

However, unlike most other verbs,
the doer of [كَانَ]{.ar},
[ٱلرَّجُلُ]{.ar}, is also called its subject
and its direct doee, [مُعَلِّمًا]{.ar}, is also called its information.

So a sentence with [كَانَ]{.ar} used in this way is a subject-information sentence.
If it begins with [كَانَ]{.ar} then it is also a verbal sentence at the same time.

This property also applies to the sisters of [كَانَ]{.ar} that we will learn later in this chapter. 
Together, these verbs are also called _deficient_ verbs, because, besides their doer/subject, they also need an information to complete the meaning of the sentence.
That is, without the information, the sentence is deficient.

"Is" subject-information sentences can be converted to "was" subject-information sentences using the verb [كَانَ]{.ar}. Here are some examples:

| "is" | "was" |
|:-|:-|
| [زَيْنَبُ جَائِعَةٌ.]{.ar}  |[كَانَتْ زَيْنَبُ جَائِعَةً.]{.ar}  |
| "Zaynab is hungry." |"Zaynab was hungry."     |
| [ٱَلْغُلَامُ زَيْدٌ.]{.ar}  |[كَانَ ٱلْغُلَامُ زَيْدًا.]{.ar} |
| "The boy is Zayd."  |"The boy was Zayd."     |
| [ٱَلنِّسَاءُ فِي بُيُوتِهِنَّ.]{.ar}         |[كَانَتْ ٱلنِّسَاءُ فِي بُيُوتِهِنَّ.]{.ar}     |
| "The women are in their houses." |"The women were in their houses." |
| [هُمْ مَسْرُورُونَ وَفَرِحُونَ.]{.ar}            | [كَانُوا مَسْرُورِينَ وَفَرِحِينَ.]{.ar}     |
| "They~3m~ are happy and rejoicing."  | "They~3m~ were happy and rejoicing." |
| [أَنَا نَائِمَةٌ.]{.ar}                | [كُنْتُ نَائِمَةً.]{.ar}       |
| "I~1f~ am sleeping."             | "I~1f~ was sleeping."|
| [أَنْتَ لِي أَخٌ.]{.ar}               | [كُنْتَ لِي أَخًا.]{.ar}            |
| "You~1m~ are a brother to me.   | "You~1m~ were a brother to me.|

## Sequence of [كَانَ]{.ar}, its subject, and its information

In sentence word order, the natural sequence is 
[كَانَ]{.ar}, its subject, and its information, as 

[كَانَ زَيْدٌ قَائِمًا.]{.ar}  
"Zayd was standing."

but we may also say, for the same meaning:

[كَانَ قَائِمًا زَيْدٌ.]{.ar}  
"Zayd was standing."

and also:

[قَائِمًا كَانَ زَيْدٌ.]{.ar}  
"Zayd was standing."

This last order is common in questions and alternative sentence sentences. For example:

[أَقَائِمًا كَانَ زَيْدٌ.]{.ar}  
"Was Zayd standing?"

[ٱُدْعُ زَيْدًا قَائِمًا كَانَ أَوْ جَالِسًا!]{.ar}  
"Call Zayd, be he standing or sitting!"

<!--See Wright vol. ii. Section 41 Rem a, p. 100B -->

Sometimes, however, this inversion is impossible because of an indistinguishable state of the two nouns.

For example, in order to express "My brother was my companion," we must say:

[كَانَ أَخِي رَفِيقِي.]{.ar}
"My brother was my companion."

This is because, if we invert it, it would naturally mean:

[كَانَ رَفِيقِي أَخِي.]{.ar}
"My companion was my brother."


## With non-rational beings as the subject

Because [كَانَ]{.ar} sentences are subject-information being sentences, 
many of the rules that we have learned for subject-information sentences also apply to [كَانَ]{.ar} sentences.
One such rule is that when the subject of a sentence is a plural of non-rational beings, and the information is a adjectival noun, then the feminine singular adjectival noun is often used. (See section\ \@ref(usage-of-plurals-of-non-intelligent-beings).)
For example:

[كَانَتِ ٱلْبُيُوتُ صَغِيرَةً.]{.ar} (typical)  
"The houses were small."  

Also allowed, but not as common:  
[كَانَتِ ٱلْبُيُوتُ صَغِيرَاتٍ.]{.ar}  
[كَانَتِ ٱلْبُيُوتُ صِغَارًا.]{.ar}  

[ٱلثِّيرَانُ كَانَتْ ضَخْمَةً.]{.ar} (typical)  
"The bulls were large."

Also allowed, but not as common:  
[ٱلثِّيرَانُ كَانَتْ ضِخَامًا.]{.ar}  
[ٱلثِّيرَانُ كُنَّ ضَخْمَاتٍ.]{.ar}  



## Subject-information verbs

As we've already mentioned Arabic does not normally express the word "is". For example,

[ٱَلْبِنَاءُ مَدْرَسَةٌ.]{.ar}  
[EalbinAEu madrasatun.]{.trn}  
"The building is a school."

However, it does express the word "was". The word "was" is a completed-action verb:

| Arabic verb | Transcription | Meaning     |
|:------------|:--------------|:------------|
| [كَانَ]{.ar}  | [kAna]{.trn}  | [He] was    |
| [كَانَتْ]{.ar} | [kAnat]{.trn} | [She] was   |

[كَانَ]{.ar} [kAna]{.trn} behaves like any other verb in that its doer is in the u-state and its doee is in the a-state. Examples:

[كَانَ ٱلْبِنَاءُ مَدْرَسَةً.]{.ar}  
[kAna -lbinAEu madrasatan]{.trn}  
"The building was a school."

[كَانَتِ ٱلْمَرْأَةُ أُمًّا.]{.ar}  
[kAnati -lmarEatu Eumman]{.trn}  
"The woman was a mother."

However, this verb is special and a little different from other verbs. Usually for verbs, the doer and doee represent separate entities. For example,

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrujulu kitAban.]{.trn}  
"The man wrote a book."

In the above sentence "the man" and "a book" refer to separate entities. Compare this to the following sentence:

[كَانَ ٱلْبِنَاءُ مَدْرَسَةً.]{.ar}  
[kAna -lbinAEu madrasatan]{.trn}  
"The building was a school."

Here, "the building" and "a school" refer to the same entity. That is why this verb is considered special. It is classified from a group of verbs called *subject-information verbs*. The doer of the verb "the building" is also the subject of the sentence, and the verb's doee "a school" is also the information of the sentence.

## TODO

The [doer]{.syn} is not really doing any action. In fact, in meaning it is the [subject]{.syn} of a sentence and the [object]{.syn} of the verb is the [information]{.syn} about the [subject]{.syn}.
However, this verb is special and a little different from other verbs. The [doer]{.syn} is not really doing any action. In fact, in meaning it is the [subject]{.syn} of a sentence and the [object]{.syn} of the verb is the [information]{.syn} about the [subject]{.syn}.

[كَانَ]{.ar} [kAna]{.trn} is an example of "[subject-information]{.syn} verbs".  Sentences that start with [subject-information]{.syn} verbs are both [subject]{.syn}-[information]{.syn} sentences and verbal sentences.

There are a few other verbs like [كَانَ]{.ar}, for example:

| Arabic verb | Transcription | Meaning     |
|:------------|:--------------|:------------|
| [صَارَ]{.ar}  | [SAra]{.trn}  | [He] became |
| [صَارَتْ]{.ar} | [SArat]{.trn} | [She] became|

#### Indefinite qualitative nouns with [subject-information]{.syn} verbs

Remember from the previous chapter that there are some verbs classified as [subject-information]{.syn} verbs. The [doer]{.syn} of such a verb is also the [subject]{.syn} of the sentence, and the verb's [object]{.syn} is also the [information]{.syn} of the sentence.

[كَانَ]{.ar} [kAna]{.trn} "[he] was" is such a verb. For example,

[كَانَ ٱلْبِنَاءُ مَدْرَسَةً.]{.ar}  
[kAna -lbinAEu madrasatan]{.trn}  
"The building was a school."

In this sentence, [ٱَلْبِنَاءُ]{.ar} [EalbinAEu]{.trn} "the building" is both the [doer]{.syn} of the verb [كَانَ]{.ar} [kAna]{.trn} and also the [subject]{.syn} of the sentence. And [مَدْرَسَةً]{.ar} [madrasatan]{.trn} "a school" is both the [object]{.syn} of the verb and also the [information]{.syn} of the sentence.

Now in the preceding section, we have learned a rule that if an indefinite qualitative noun is used as the [information]{.syn} of a sentence, then it gives the meaning of an adjective. This rule also applies to sentences with [subject-information]{.syn} verbs: If an indefinite qualitative noun is used as the [information]{.syn} of a [subject-information]{.syn} verb, there here too it will give the meaning of an adjective. For example,

[كَانَ ٱلْبِنَاءُ كَبِيرًا.]{.ar}  
[kAna -lbinAEu kabIran]{.trn}  
"The building was a big one." = "The building was big."

The indefinite qualitative noun [كَبِيرًا]{.ar} [kabIran]{.trn} is the [information]{.syn} of the sentence, therefore it gives the meaning of the adjective "big".

### kaana for tenses

كان بفعل
كان قد فعل

