# Completed-action verbs

## Introduction

Verbs are action words. Verbs can be either _completed-action_ verbs where the action of the verb has been completed, e.g., "The boy went." or _incomplete-action_ verbs where the action of the verb is on-going or not yet completed, e.g., "The boy goes." In this chapter we will study _completed-action_ verbs.

## Arabic word roots

We take this opportunity to learn about Arabic roots. 
Native Arabic words, both nouns and verbs, are generally derived from roots. Most roots are comprised of three letters. A smaller number are comprised of four or more letters. 

Words are derived from their roots according to patterns. In traditional Arabic grammar studies, the root [فعل]{.arroot} is used as a paradigm for three-letter roots to showcase word and meaning patterns. 

So for example, the word [بَيْت]{.ar} [bayt]{.trn} "a house" is derived from the root [بيت]{.arroot}. Using the paradigm root [فعل]{.arroot}, we can see that the pattern of the word [بَيْت]{.ar} [bayt]{.trn} is [فَعْل]{.ar} [fael]{.trn}.
The [أَمْر]{.ar} [Eamr]{.trn} "a matter" is derived from the root [ءمر]{.arroot}. Its pattern is also [فَعْل]{.ar} [fael]{.trn}.

Similarly, the word [مَكْتَب]{.ar} [maktab]{.trn} "a library" is derived from the root [كتب]{.arroot}. And [مَلْعَب]{.ar} [maleab]{.trn} "a playground" is derived from the root [لعب]{.arroot}. Using the paradigm root [فعل]{.arroot}, we can see that the pattern of both these words is [مَفْعَل]{.ar} [mafeal]{.trn}. Here, the letter [م]{.ar} [m]{.trn} is an extraneous letter added to form the words and is not part of their roots.

Not only nouns, but verbs, too, are derived from roots. All verbs are derived from their roots in a fixed set of patterns called _forms_ which are numbered 1 onward. For example, the completed-action form 2 verb pattern is [فَعَّلَ]{.ar} [faeeala]{.trn} and the completed-action form 3 verb pattern is [فَاعَلَ]{.ar} [fAeala]{.trn}. There are approximately 9-10 forms that are in common usage. In addition, there are a few higher order forms (11 onward) that are less common. In this chapter will study the completed-action form 1 verb only.

## The form 1 completed-action verb

Here are some examples of completed-action form 1 verbs in Arabic:

Root | Completed-action form 1 verb| Meaning
:----|:----|:----
[فعل]{.arroot} |[فَعَلَ]{.ar} [faeala]{.trn} |"did"
[ذهب]{.arroot} |[ذَهَبَ]{.ar} [pahaba]{.trn} |"went"
[كتب]{.arroot} |[كَتَبَ]{.ar} [kataba]{.trn} |"wrote"
[قرء]{.arroot} |[قَرَأَ]{.ar} [qaraEa]{.trn} |"read"
[جلس]{.arroot} |[جَلَسَ]{.ar} [jalasa]{.trn} |"sat"
[سءل]{.arroot} |[سَأَلَ]{.ar} [saEala]{.trn} |"questioned"
[سكت]{.arroot} |[سَكَتَ]{.ar} [sakata]{.trn} |"became quiet"
[جعل]{.arroot} |[جَعَلَ]{.ar} [jaeala]{.trn} |"made"
[علم]{.arroot} |[عَلِمَ]{.ar} [ealima]{.trn} |"knew"
[عمل]{.arroot} |[عَمِلَ]{.ar} [eamila]{.trn} |"worked"
[كبر]{.arroot} |[كَبُرَ]{.ar} [kabura]{.trn} |"grew"

Note that [فعل]{.arroot}, in addition to being used as a paradigm root, also has a verb in its own right: [فَعَلَ]{.ar} [faeala]{.trn} "did".

Note, also, that the completed-action form 1 verb consists only of the three letters of the root. The first and the final letter always have an [a]{.trn}-mark while the middle letter's vowel is variable. It may have an [a]{.trn}-mark, [i]{.trn}-mark, or an [u]{.trn}-mark, depending on the verb. Using the paradigm root [فعل]{.arroot}, we can say that the form 1 verb occurs in the patterns [فَعَلَ]{.ar}, [فَعِلَ]{.ar}, and [فَعُلَ]{.ar}. 

A good dictionary will tell us the middle vowel mark of a particular verb. However, as a trend, the [a]{.trn}-mark is the most common for the middle vowel mark, followed by the [i]{.trn}-mark, while the [u]{.trn}-mark is the least common.

Interestingly, there can exist multiple verbs from the same root, each with its own distinct meaning, that differ only in the vowel mark on the middle letter. An example of two such verbs is:

+ [حَسَبَ]{.ar} [Hasaba]{.trn} "calculated"
+ [حَسِبَ]{.ar} [Hasiba]{.trn} "deemed"

You can see above how the verb [كَتَبَ]{.ar} [kataba]{.trn} "wrote" is derived from the root [كتب]{.arroot}. We have already, by the way, learned another word derived from this root: the noun [كِتَاب]{.ar} [kitAb]{.trn} "a book", which is on the pattern [فِعَال]{.ar} [fieAl]{.trn}. Note how both the verb and the noun derived from this root have a meaning that is common and has to do with writing or of something written. 
In a similar manner, you will often see that words derived from the same root generally share some common meaning, although this common meaning may not always be obvious or straightforward.

## Verbal sentences

We have already learned of subject-information sentences. Here we will learn of a new type of sentence called a _verbal sentence_. A verbal sentence is one that begins with a verb.

When a verb is in a sentence, it requires a doer. The doer is a noun which represents the person who does the action of the verb. For example, in the sentence "The boy went.", the noun "the boy" is the doer of the verb.

### Verbs with a masculine doer noun

Consider the sentence:

"The boy went." 

In order to express this sentence in Arabic, we will say:

[ذَهَبَ ٱلْغُلَامُ.]{.ar}  
[pahaba -lgulAm.]{.trn}  
"The boy went." 

[ذَهَبَ]{.ar} [pahaba]{.trn} "went" is the verb and [ٱلْغُلَامُ]{.ar} [algulAmu]{.trn} "the boy" is the doer. Note how the doer is in the u-state. Also note that in English the doer comes before the verb whereas in Arabic the doer comes after the verb in sentence word order. We can state this as a rule of Arabic grammar: 

**In Arabic, every verb in a sentence shall have a doer noun. The doer noun shall be in the u-state and shall come after the verb in sentence word order.**

<!--In Arabic, a doer noun shall always be in the u-state and shall come after the verb in word order.

The basic form of the verb [ذَهَبَ]{.ar} [pahaba]{.trn} is specifically for masculine doers. We shall see in the next section how the verb is modified for feminine doers. 

The doer may be definite, indefinite, a common noun, or a proper noun. Examples:

A boy went.

Muhammad went.

The time went.
-->

In the above example the doer noun was definite, but a doer may be indefinite too. Example:

[ذَهَبَ رَجُلٌ إِلَىَ ٱلسُّوقِ.]{.ar}  
[pahaba rajulun Eila -ssUq.]{.trn}  
"A man went to the market."

In the above sentence, the doer noun [رَجُلٌ]{.ar} [rajulun]{.trn} is indfinite.

### Verbs with a feminine doer noun

Now consider the sentence:

"A girl went." 

In order to express this sentence in Arabic, we will say:

[ذَهَبَتْ جَارِيَةٌ.]{.ar}  
[pahabat jAriyah.]{.trn}  
"A girl went." 

Note that we have modified the verb by adding on the letter [تْ]{.ar} at the end. This [تْ]{.ar} is used when the doer is ia feminine noun. It is called the [تْ]{.ar} of femininity. 

If the word following the noun begins with a connecting [hamzah]{.trn} then we add a helper vowel to the [تْ]{.ar} and it becomes [تِ]{.ar}. Examples:

[جَلَسَتِ ٱلْهِرَّةُ عَلَى ٱلْكُرْسِيِّ.]{.ar}  
[jalasati -lhirratu eala -lkursiyyi.]{.trn}  
"A cat~f~ sat on the chair."

[لَعِبَتِ ٱلطِّفْلَةُ فِي ٱلْبَيْتِ.]{.ar}  
[laeibati -TTiflatu fi -lbayt.]{.trn}  
"The child~f~ played in the house."
<!--
[عَلِمَتْ ٱمْرَأَةٌ.]{.ar}  
[pahabati -mraEatun.]{.trn}  
"A woman went."

Note that whether or not we add a helper vowel to [تْ]{.ar}, the letter before it always has an [a]{.trn}-mark.
-->

## Verbs with doees

### Direct doees

Consider the sentence:

"The man wrote a book."

In this sentence, "wrote" is the verb, "the man" is the doer, and "a book" is what we shall call the _doee_. In fact, it is what we shall call a _direct doee_ because it comes directly after the verb without an intermediate preposition. A doee is the noun to whom the action of verb is done. 

In Arabic, we will express the sentence "The man wrote a book." by saying:

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrajulu kitAbA.]{.trn}  
"The man wrote a book."

Note how in Arabic the doee [كِتَابًا]{.ar} [kitAban]{.trn} "a book" is in the a-state. This is because, in Arabic, verbs shall cause a direct doee to be in the a-state. This is true whether the direct doee is definite or indefinite. Here is another example:

<!--[ضَرَبَتِ ٱلْمَرْأَةُ ٱلْجَارِيَةَ.]{.ar}  
[Darabati -lmarEatu -ljAriyata.]{.trn}  
"The woman hit the girl."
-->

[سَأَلَتِ ٱلْأُمُّ ٱلْجَارِيَةَ.]{.ar}  
[saEalati -lEummu -ljAriyah.]{.trn}  
"The mother questioned the girl."

Note again how [ٱلْجَارِيَةَ]{.ar} [aljAriyata]{.trn} "the girl" is in the a-state because it is a direct doee.

### Multiple direct doees

Some verbs can take more than one direct doee. In this case, all direct doees shall be in the a-state. For example,

[جَعَلَ ٱللَّـٰهُ ٱلرَّجُلَ مُسْلِمًا.]{.ar}  
[jaeala -llAhu -rrajula muslimA.]{.trn}  
"[#allAh]{.trn2} made the man a Muslim."

In this sentence both [ٱلرَّجُلَ]{.ar} [arrajula]{.trn} "the man" and [مُسْلِمًا]{.ar} [musliman]{.trn} "a Muslim" are direct doees of the verb [جَعَلَ]{.ar} [jaeala]{.trn} and therefore both are placed in the a-state.

### Indirect doees

Instead of, or in addition to, direct doees, some verbs take an _indirect doee_. An indirect doee is one before which there is a preposition. For example, in English we might say:

"The man looked at the moon."

In this sentence, "the moon" is an indirect doee because it is preceded by the preposition "at". Similarly, in Arabic, we will say:

[نَظَرَ ٱلرَّجُلُ إِلَى ٱلْقَمَرِ.]{.ar}  
[naPara -rrajulu Eila -lqamar.]{.trn}  
"The man looked at the moon."

In this sentence [ٱَلْقَمَرِ]{.ar} [alqamari]{.trn} "the moon" is an indirect doee of the verb [نَظَرَ]{.ar} [naPara]{.trn} "looked" because it is preceded by the preposition [إِلَىٰ]{.ar} [EilA]{.trn} "to". The preposition, as usual, causes the word after it (the indirect doee [ٱَلْقَمَرِ]{.ar} [Ealqamari]{.trn}) to be in the i-state, as opposed to the a-state of the direct doee.

Note also, that the verb "looked" in English used the preposition "at" whereas the Arabic verb [نَظَرَ]{.ar} [naPara]{.trn} used the preopsition [إِلَىٰ]{.ar} [EilA]{.trn} "to" for the same meaning. This is very common and you should not expect Arabic to use exact counterparts of the prepositions used in English. In fact, everytime you learn a new verb, you should also learn the prepositions that go with it.

It is also possible for the same verb to take different prepositions with possibly different meanings. So, for example, we can say:

[نَظَرَ ٱلرَّجُلُ فِي ٱلْأَمْرِ.]{.ar}  
[naPara -rrajulu fi -lEamri.]{.trn}  
"The man looked into the matter."
<!-- « فَنَظَرَ نَظْرَة فِي النُّجُومِ» سورة الصافات(88) -->

It may also be possible for the same verb to take a direct doee. So we could also say:

[نَظَرَ ٱلرَّجُلُ ٱلْمَكْتُوبَ فِي ٱلْكِتَابِ.]{.ar}  
[naPara -rrajulu -lmaktUba fi -lkitAbi.]{.trn}  
"The man viewed what was written in the book."
<!--This example from Lane. Also: « يَوْمَ يَنظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ» سورة النبأ،(40)-->

A good dictionary will tell us which prepositions are used with indirect doees with a given verb and also whether it takes a direct doee.

Some verb take a direct doee and another indirect doee, both at the same time. For example,

[سَأَلَ ٱلْغُلَامُ ٱلْمُعَلِّمَةَ عَنْ أَمْرٍ.]{.ar}  
[saEala -lgulAmu -lmueallimata ean Eamr.]{.trn}  
"The boy asked the teacher~f~ about a matter."

[ٱَلْمُعَلِّمَةَ]{.ar} [Ealmueallimata]{.trn} "the teacher~f~" is the direct doee, and therefore it is in the a-state.
[أَمْرٍ]{.ar} [Eamrin]{.trn} "a matter" is an indirect doee, and so it is in the i-state.
The preposition [عَنْ]{.ar} [ean]{.trn} is translated, here, as "about".

It is also possible that an English verb may take a direct doee, while the corresponding Arabic verb may only take an indirect doee. The reverse is also quite possible. For example,

[غَفَرَ ٱللَّـٰهُ لِلْمُسْلِمِ.]{.ar}  
[gafara -llAhu lilmuslimi.]{.trn}  
"[#allAh]{.trn2} forgave the Muslim."

The verb "forgave" in English takes a direct doee for the person who is forgiven. In Arabic, however, the corresponding verb [غَفَرَ]{.ar} [gafara]{.trn} "forgave" takes the forgiven person as an indirect doee, using the preposition [لِ]{.ar} [li]{.trn}.

## Verbs with doer pronouns

We have learned that a pronoun is a special kind of noun that can be used to replace a definite noun. And we have already learned two category of pronouns in Arabic:

i.  Detached pronouns, like [هُوَ]{.ar}, [هِيَ]{.ar}, etc.
ii. Attached pronouns, like [هُ]{.ar}, [هَا]{.ar}, etc.

Now we would like to replace the doer noun of a verb with a pronoun. For example, instead of saying:

"The man went."

we would like to say:

"He went."

For this we will have to learn a third category of pronoun pronouns called _doer pronouns_ for completed-action verbs.
Doer pronouns are of two types: visible and invisible.

Here we list the singular doer pronouns in Arabic. 

Singular participant | Doer pronoun
:------|:--
Masc. absentee ("he")      | invisible
Fem. absentee ("she")      | invisible
Masc. addressee ("you~1,m~") | [تَ]{.ar} [-ta]{.trn}
Fem. addressee ("you~1,f~")  | [تِ]{.ar} [-ti]{.trn}
Speaker ("I")              | [تُ]{.ar} [-tu]{.trn}

We will now give an explanation of the above doer pronouns.

### Doer pronouns for the singular absentee-participant ("he"/"she")

The doer pronouns of the absentee-participant are the equivalent of "he" and "she". For example, let's try to replace the doer-noun "the man" in the sentence: "The man went."

[ذَهَبَ ٱلرَّجُلُ.]{.ar}  
[pahaba -rrajul.]{.trn}  
"The man went."

When we replace the doer noun [ٱلرَّجُل]{.ar} [Earrujul]{.trn} "the man" with the doer pronoun "he", we get:

[ذَهَبَ.]{.ar}  
[pahab.]{.trn}  
"[He] went."

As you can see, all we did was omit the doer-noun [ٱَلرَّجُل]{.ar} [Earrujul]{.trn}, and we didn't add any word to replace it as the doer pronoun. This is because the doer pronoun for "he" is _invisible_ and automatically comes into place when we omit the doer noun.

The doer pronoun for "she" is similarly invisible.
For example, if we replace the doer noun in the sentence:

[قَرَأَتِ ٱلْجَارِيَةُ كِتَابًا.]{.ar}  
[qaraEati -ljAriyatu kitAbA.]{.trn}  
"The girl read a book."

we get:

[قَرَأَتْ كِتَابًا.]{.ar}  
[qaraEat kitAbA.]{.trn}  
"[She] read a book."

#### Explanation of invisible pronouns

Why do we have to go to all the trouble of saying that the doer-pronouns of the singular masculine absentee-participant "he"/"she" are invisible? Why can't we simply say that there are no doer-pronouns for the singular masculine absentee-participant?

The reason is that making the statement that these pronoun exist but are invisible is useful to us from the perspective of the grammar theory that we are building.

That is: we need to be able to state, as a rule of grammar, that every verb needs to have a doer, whether visible or not. And that doer shall come after the verb in sentence word order.

If we are able to make this a rule, then we will see, if [#allAh]{.trn2} wills, that it will help us later. For example, when we study verbs with plural doers.

### Doer pronouns for the singular addressee ("you~1~") and speaker ("I") participants

It is only the doer pronouns for the singular absentee participant that are invisible for completed-action verbs. The doer pronouns for the singular addressee and speaker participants are visible. When visible, the doer pronouns are attached to the verb.

Here we show how the visible doer pronouns are attached to the verb using the root paradigm [فعل]{.arroot}. The middle root letter ([ع]{.ar}) has an [a]{.trn}-vowel [◌َ]{.ar} here but this vowel will vary for other verbs.

Singular participant | Doer pronoun | Doer pronoun with verb
:------|:--|:--
Addressee "you~1,m~" | [تَ]{.ar} [-ta]{.trn} | [فَعَلْتَ]{.ar} [faealta]{.trn}
Addressee "you~1,f~" | [تِ]{.ar} [-ti]{.trn} | [فَعَلْتِ]{.ar} [faealti]{.trn}
Speaker "I"          | [تُ]{.ar} [-tu]{.trn} | [فَعَلْتُ]{.ar} [faealtu]{.trn}

Note also how the visible singular doer pronouns modify the verb by replacing the [a]{.trn}-mark [◌َ]{.ar} on its final letter by a $\emptyset$-mark [◌ْ]{.ar}.

Furthermore, note how the doer pronoun for the addressed person "you" is differentiated for masculine and feminine doers whereas the doer pronoun for the speaking person "I" is the same for both genders.

Here are some examples of sentences with visible doer pronouns:

[كَتَبْتَ كِتَابًا.]{.ar}  
[katabta kitAbA.]{.trn}  
"You~m~ wrote a book."

[ذَهَبْتُ]{.ar}  
[pahabt.]{.trn}  
"I went."

The above sentence ends with the doer pronoun, so the vowel-mark on the doer pronoun is not pronounced ([pahabt]{.trn}). So, how would be know which doer pronoun it is? That is, does the sentence say "I went." or "You~m~ went." or "You~f~. went."? The answer is that the sentence by itself is ambiguous and context would tell us which of the three options is intended.

Take care to note that the singular doer pronouns modify the final letter of the basic verb, whereas the [تْ]{.ar} of femininity does not. So make sure you see the difference in the following two sentences:

[قَرَأْتِ ٱلْكِتَابَ.]{.ar}  
[qaraEti -lkitAb.]{.trn}  
"You~f~ read the book."

[قَرَأَتِ ٱلْكتَابَ.]{.ar}  
[qaraEati -lkitAb.]{.trn}  
"She read the book."

### Assimilation of the doer pronoun

If the final letter of the root of a verb is [ت]{.ar}, then it gets assimililated with the [ت]{.ar} which is the doer pronoun and only one [ت]{.ar}, representing both, is written. Consider the verb:

[سكت]{.arroot} [سَكَتَ]{.ar} [sakata]{.trn} "became quiet"

When we add a visible doer pronoun to this verb, we get:

[سَكَتُّ]{.ar}  
[sakattu]{.trn}  
"I became quiet"

[سَكَتَّ]{.ar}  
[sakatta]{.trn}  
"You~1,m~ became quiet"

[سَكَتِّ]{.ar}  
[sakatti]{.trn}  
"You~1,f~ became quiet"

Assimilation is treated in more detail in chapter/appendix TODO.

## Verbs with doee pronouns

Just like doer nouns may be replaced with doer pronouns, so, too, may doee nouns be replaced with _doee pronouns_. Doee pronouns are also attached to the end of the verb but they don't modify the vowel on the final letter of the verb. The doee pronouns are the same attached pronouns that are also used with prepositions:

Singular participant | Doee pronoun
:------|:--
Masc. absentee  | [هُ]{.ar} [-hu]{.trn}    "him"   
Fem. absentee   | [هَا]{.ar} [-hA]{.trn}   "her"   
Masc. addressee | [كَ]{.ar} [-ka]{.trn}    "you~1,m~"
Fem. addressee  | [كِ]{.ar} [-ki]{.trn}    "you~1,f~"
Speaker         | [ي]{.ar}                "me"    

Here are some notes regarding their usage:

+ Doee pronouns shall always be attached to the verb. So if there is a doer noun then it shall be placed after the attached doee pronoun. For example:

  [سَأَلَهُ ٱلْغُلَامُ.]{.ar}  
  [saEalahu -lgulAm.]{.trn}  
  "The boy asked him."

+ If however, the doer is also a pronoun, then it shall be attached first to the verb and then the doee pronoun shall be attached to the doer pronoun. For example,

  [سَأَلْتُكِ.]{.ar}  
  [saEaltuk.]{.trn}  
  "I asked you~f~."

+ If the doer pronoun is invisible, then the doee pronoun shall be attached to the verb again directly with only a possible [تْ]{.ar} of femininity intervening. For example:

  [سَأَلَهَا.]{.ar}  
  [saEalahA.]{.trn}  
  "He asked her."

  [سَأَلَتْكَ.]{.ar}  
  [saEalatk.]{.trn}  
  "She asked you~m~."

+ If the doee pronoun [هُ]{.ar} [-hu]{.trn} "him" is preceded by the vowels [i]{.trn}, [I]{.trn}, or [ay]{.trn} then it shall instead become [هِ]{.ar} [hi]{.trn} with no change in meaning. (We've already learned this rule.) For example,

  [سَأَلْتِهِ.]{.ar}  
  [saEaltih]{.trn}  
  "You~f~ asked him."

+ An intervening [ن]{.ar} is always used between the verb and the speaker-participant doee pronoun variants [◌ِي]{.ar} [-I]{.trn} and [◌ِيَ]{.ar} [-iya]{.trn}. Remember that these pronouns force any consonant before it to have a [i]{.trn}-mark [◌ِ]{.ar}. Therefore, the combination will be written as [نِي]{.ar} [-nI]{.trn} and [نِيَ]{.ar} [-niya]{.trn} respectively. For example:

  [سَأَلَنِي رَجُلٌ.]{.ar}  
  [saEalanI rajul.]{.trn}  
  "A man asked me."

  [سَأَلَنِيَ ٱلرَّجُلُ.]{.ar}  
  [saEalaniya -rrajul.]{.trn}  
  "The man asked me."

  <!--The [ن]{.ar} is purely for intervening between the verb and the doee pronoun and has no meaning on its own.-->
  If there is a visible doer pronoun, the intervening [ن]{.ar} shall come after it so that the [ن]{.ar} is always connected to the doee pronoun. For example,

  [سَأَلْتَنِي.]{.ar}  
  [saEaltanI]{.trn}  
  "You~m~ asked me."

  By the way, we have already seen this intervening [ن]{.ar} before when it was used with some prepositions, e.g. [مِنِّي]{.ar} [minnI]{.trn}, [عَنِّي]{.ar} [eannI]{.trn}, and [لَدُنِّي]{.ar} [ladunnI]{.trn}
  <!--So why don't we simply incorporate the [ن]{.ar} with the doee pronoun and say that the doee pronoun for "me" is [نِي]{.ar} [-nI]{.trn} and [نِيَ]{.ar} [-niya]{.trn}? This is because in addition to their use as doee pronouns, these same pronouns are also used in other places as we shall see later, if [#allAh]{.trn2} wills, and in those cases there is often no intervening [ن]{.ar} for the speaking person pronoun. -->

  Even though, the variant [◌ِي]{.ar} [-I]{.trn} is, in general, more commonly used, when the noun following it begins with a connecting [hamzah]{.trn} then the variant [◌ِيَ]{.ar} [-ya]{.trn} is preferred. That is why we used the variant [◌ِيَ]{.ar} [-ya]{.trn} when it was followed by a connecting [hamzah]{.trn} ([سَأَلَنِيَ ٱلرَّجُلُ.]{.ar}), and the variant [◌ِي]{.ar} [-I]{.trn} when it was not followed by a connecting [hamzah]{.trn} ([سَأَلَنِي رَجُلٌ.]{.ar}). 

  This preference is not mandatory. So it is allowed for [◌ِي]{.ar} [-I]{.trn} to be used when followed by a connecting [hamzah]{.trn}. When this happens, the long vowel [-I]{.trn} will be shortened to [-i]{.trn} in connecting it to the next word, although the [◌ِي]{.ar} is retained in writing. For example,

  [سَأَلَنِي ٱلرَّجُلُ.]{.ar}  
  [saEalani -rrajul.]{.trn}  
  "The man asked me."

  <!--However, [يَ]{.ar} [-ya]{.trn} is typically not used as a doee pronoun if not followed by a connecting [hamza]{.trn}. -->

  <!--To summarize, generally speaking, although both are often permissible, [◌ِي]{.ar} [-I]{.trn} is the more commonly used in all circumstances except in specific cases where [◌ِي]{.ar} [-I]{.trn} is impermissible and [يَ]{.ar} [-ya]{.trn} is required. We will mention those cases when we encounter them, if [#allAh]{.trn2} wills.-->

<!--Examples from Quran: لا يَنَالُ عَهْدِي الظَّالِمِينَ).

2- في كلمات أخرى، هي: (مَعِيَ) حيثما وقعت، و(أَجْرِيَ إلاَّ) وهي في تسعة مواضع، و(يَدِيَ إِلَيْكَ) بالمائدة، (وَأُمِّيَ إِلَهَيْنِ) بالمائدة، و(بَيْتِيَ لِلطَّائِفِينَ) بالبقرة والحج، و(بَيْتِيَ مُؤْمِنًا) بنوح، و(وَجْهِيَ للهِ) بآل عمران، و(وَجْهِيَ لِلَّذِي) بالأنعام 

http://www.alfaseeh.com/vb/showthread.php?t=93064A-->

## Multiple verbs for one doer

In this section we will use the verbs:

Root | Completed-action form 1 verb| Meaning
:----|:----|:----
[دخل]{.arroot} |[دَخَلَ]{.ar} [daxala]{.trn} |"entered"
[خرج]{.arroot} |[خَرَجَ]{.ar} [xaraja]{.trn} |"exited"
[ءكل]{.arroot} |[أَكَلَ]{.ar} [Eakala]{.trn} |"ate"
[شرب]{.arroot} |[شَرِبَ]{.ar} [cariba]{.trn} |"drank"

Consider, now, the sentence:

"I entered the room, ate, drank, and exited."

The doer in this sentence is the pronoun "I". This same doer is doing the action of multiple verbs:
"entered", "ate", "drank", and "exited".
When we try to express this sentence in Arabic we must remember that every verb shall have its own doer, and that the doer shall occur after it in sentence word order. So we will say:

[دَخَلْتُ ٱلْغُرْفَةَ فَأَكَلْتُ فَشَرِبْتُ فَخَرَجْتُ.]{.ar}  
[daxaltu -lgurfata faEakaltu facaribtu faxarajt.]{.trn}  
"I entered the room and then I ate and then I drank and then I exited."

Note also, that we need to replace the commas by connecting particles like [وَ]{.ar} [wa-]{.trn} "and", or [فَ]{.ar} [fa-]{.trn} "so"/"and then", etc. We chose
[فَ]{.ar} [fa-]{.trn} which implies consequence or subsequence between the individual events.

Let's now try this sentence with a doer noun instead of a doer pronoun:

"The girl entered the room, ate, drank, and exited."

Here is our translation:

[دَخَلَتِ ٱلْجَارِيَةُ ٱلْغُرْفَةَ فَأَكَلَتْ فَشَرِبَتْ فَخَرَجَتْ.]{.ar}  
[daxalati -ljAriyatu -lgurfata faEakalat facaribat faxarajat.]{.trn}  
"The girl entered the room and then she ate and then she drank and then she exited."

Each verb again has its own doer, which is coming after the verb in sentence word order. The doer of the first verb [دَخَلَ]{.ar} [daxala]{.trn} "entered" is the noun 
[ٱَلْجَارِيَةُ]{.ar} [EaljAriyatu]{.trn} "the girl".
The subsequent verbs all have doers too but they are the invisible doer pronouns for the singular feminine absentee participant. That is why we don't write them. Note also that every verb has the [تْ]{.ar} of femininity attached to it to indicate its singular feminine absentee doer.
<!--
In a sentence that has multiple verbs separated by "and", normally one of them is placed before the doer and the rest after it. For example,

[أَكَلَ ٱلرَّجُلُ وَشَرِبَ.]{.ar}  
[Eakala -rrajulu wacariba.]{.trn}  
"The man ate and drank."

The first verb [أَكَلَ.]{.ar} [Eakala]{.trn} has the doer [ٱلرَّجُلُ]{.ar} [Earrajulu]{.trn}, and the second verb [شَرِبَ]{.ar} [cariba]{.trn} has an invisible doer pronoun "he".
-->

## Order of words in a sentence

### Changing the order of words for emphasis

In Arabic, the doer always follows the verb. So the normal order of a sentence is verb-doer-doee. For example,

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrajulu kitAbA.]{.trn}  
"The man wrote a book."

However, we will often come across sentences like:

[ٱَلرَّجُلُ كَتَبَ كِتَابًا.]{.ar}  
[Earrajulu kataba kitAbA.]{.trn}

It may appear as if [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} is the doer and it is coming before the verb [كَتَبَ]{.ar} [kataba]{.trn}. But actually, this is not the case. As a matter of fact, this sentence is basically a subject-information sentence. 

Here [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} "the man" is the subject of the sentence, and [كَتَبَ كِتَابًا]{.ar} [kataba kitAban]{.trn} "he wrote a book", itself a verbal sentence with an invisible doer pronoun, is the information about the subject. So the translation of the sentence is technically:

"The man, he wrote a book."

However, this is an awkward translation so we will usually translate it as "The man wrote a book." <!--But this is also the translation of:

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrajulu kitAban.]{.trn}  
"The man wrote a book."
-->

The question arises: if both sentences above have the same translation, then would we say [ٱَلرَّجُلُ كَتَبَ كِتَابًا.]{.ar} [Earrajulu kataba kitAban.]{.trn} instead of the more normal [كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar} [kataba -rrajulu kitAban.]{.trn}? The answer is that this change in the sentence's word order is done in order to give more emphasis to the doer, as if to say:

"_The man_ wrote a book."

So in Arabic, the order of words is generally more flexible than in English and this is often used to give emphasis to certain words.

### Verbs pull definite nouns towards them

When a verb has a doer noun and a doee noun, the normal order of words in a sentence is: verb, doer noun, doee noun. For example,

[كَتَبَ ٱلرَّجُلُ ٱلْكِتَابَ.]{.ar}  
[kataba -rrajulu -lkitAba.]{.trn}  
"The man wrote the book."

There is a tendency, in Arabic, for verbs to _pull_ definite nouns towards them. This means that if there are any indefinite nouns, they have a tendency to get pushed father away. So, for example,
if a verb's doer is an indefinite noun and the doee is a definite noun, the doee will often (but not always) precede the doer. For example,

[كَتَبَ ٱلْكِتَابَ رَجُلٌ.]{.ar}  
[kataba -lkitAba rajul.]{.trn}  
"A man wrote the book."

The vowel-marks at the end of the nouns, and context, will tell us which is the doer and which is the doee. In this particular example, it was optional, and not mandatory to make the definite doee precede the doer in sentence word order. So we could have also said, instead:

[كَتَبَ رَجُلٌ ٱلْكِتَابَ.]{.ar}  
[kataba rajuluni -lkitAb.]{.trn}  
"A man wrote the book."

Now let's take a look at sentences with pronouns. Remember that pronouns are a category of nouns, and also (from section\ \@ref(definiteness-of-pronouns)) that they are definite nouns. In fact they are stronger in definiteness than words that are made definite using [ٱَلْ]{.ar}. This because if when we say "The man wrote the book." instead of "A man wrote the book.", we assume that everyone knows which man we are referring to. Now if we replace "the man" with the pronoun "he": "He wrote the book.", then this assumption becomes stronger. "He" is, in a sense, more definite than "the man.".

So now, when the direct doee noun [ٱلْكِتَابَ]{.ar} [EalkitAba]{.trn} "the book" is replaced with the pronoun "it", the doee pronoun must be attached to the verb, and then the doer noun follows the doee pronoun:

[كَتَبَهُ ٱلرَّجُلُ.]{.ar}  
[katabahu -rrajulu.]{.trn}  
"The man wrote it."

This can be seen as a mandatory case of the verb pulling the definite noun toward it.

Now, consider a sentence with an indirect doee. Again, the normal order of words in a sentence is verb, doer noun, preposition, doee noun. For example,

[ذَهَبَ ٱلْغُلَامُ إِلَى ٱلْمَدْرَسَةِ.]{.ar}  
[pahaba -lgulAmu Eila -lmadrasah.]{.trn}  
"The boy went to the school."

Now, if we replace the indirect doee noun [ٱلْمَدْرَسَةِ.]{.ar} [Ealmadrasati]{.trn} "the school" with the pronoun "it", the indirect doee pronoun [هَا]{.ar} [-hA]{.trn} "it" is attached, not to the verb, but to the preposition [إِلَىٰ]{.ar} [EilA]{.trn} thus: [إِلَيْهَا]{.ar} [EilayhA]{.trn} "to it". So it possible to preserve the original order of words in the sentence:

[ذَهَبَ ٱلْغُلَامُ إِلَيْهَا.]{.ar}  
[pahaba -lgulAmu EilayhA.]{.trn}  
"The boy went to it."

While the above sentence is correct, it is in fact more common to place the preposition and doee pronoun [إِلَيْهَا]{.ar} [EilayhA]{.trn} "to it" right after the verb, and before the doer noun, thus:

[ذَهَبَ إِلَيْهَا ٱلْغُلَامُ.]{.ar}  
[pahaba Eilayha -lgulAmu.]{.trn}  
"The boy went to it."

This is because the pronoun [هَا]{.ar} [-hA]{.trn} "it" is stronger in definiteness than [ٱلْغُلَام]{.ar} [EalgulAm]{.trn} "the boy". So the verb has a stronger pull towards it.
<!--This is because if there is a doee pronoun for a verb, whether direct or indirect, the verb has an effect of pulling the doee pronoun toward it. When it is a direct doee pronoun, the doee pronoun is necesarrily attached to the verb. But even when it is an indirect doee pronoun, the effect persists, and it tends to pull the preposition and doee pronoun toward the verb, even before the verb's doer noun.-->

This ordering of words due to the attractive pull of the verb is largely learned by experience. The more you read Arabic, the better feel you will get for it, if [#allAh]{.trn2} wills.

## Negating completed-action verbs

In order to negate a completed-action verb, the particle [مَا]{.ar} [mA]{.trn} is placed before it. This gives the meaning of the action of the verb did not get, or has not got, done. So for example:

[مَا ذَهَبَ ٱلرَّجُلُ.]{.ar}  
[mA pahaba -rrajulu.]{.trn}  
"The man did not go." or,  
"The man has not gone."

## The particle [قَدْ]{.ar} [qad]{.trn}

The particle [قَدْ]{.ar} [qad]{.trn}, when placed before a completed-action verb emphasizes that the action of the verb has already or definitely occured.

[قَدْ ذَهَبَ ٱلرَّجُلُ.]{.ar}  
[qad pahaba -rrajulu.]{.trn}  
"The man has already gone." or,  
"The man did go."

## Separating doee pronouns from the verb

FIXME: move to imperfect verb chapter

We have mentioned that doee pronouns are attached to the verb. Sometimes there is a need to separate the doee pronoun from the verb. When separating the doee pronoun from the verb, it is instead attached to the prefix [إِيَّا]{.ar} [EiyyA]{.trn}. So then we get the following doee pronouns:

Person | Doee pronoun
:------|:--
Absent person (masc.) "him" | [إِيَّاهُ]{.ar} [EiyyAhu]{.trn} 
Absent person (fem.)  "her" | [إِيَّاهَا]{.ar} [EiyyAhA]{.trn}
Addressed person (masc.)  "you~masc.~" | [إِيَّاكَ]{.ar} [EiyyAka]{.trn} 
Addressed person (fem.)  "you~fem.~"   | [إِيَّاكِ]{.ar} [EiyyAki]{.trn} 
Speaking person (masc. and fem.)  "me" | [إِيَّايَ]{.ar} [EiyyAya]{.trn} 

Note that for the speaking person "me", there is no intervening [ن]{.ar} between the prefix [إِيَّا]{.ar} [EiyyA]{.trn} and the doee pronoun. Note also that only [يَ]{.ar} [-ya]{.trn} is allowed to be attached to the prefix [إِيَّا]{.ar} [EiyyA]{.trn}. This is because [◌ِي]{.ar} [-I]{.trn} is not permitted to be used with words that end in a long vowel ([-A]{.trn}, [-I]{.trn}, or [-U]{.trn}) or a semi-vowel ([-ay]{.trn} or [-aw]{.trn}). And the prefix [إِيَّا]{.ar} [EiyyA]{.trn} ends with the long-vowel [A]{.trn}.

But we may ask why is there a need to separate the doee pronoun from the verb? This can occur for a couple of reasons:

i. If there are multiple doee pronouns, only one of them can be attached to the verb. Example,

   [ضَرَبَتْنِي وَإِيَّاهُ.]{.ar}  
   [DarabatnI wa EiyyAhu.]{.trn}  
   "She hit me and him."

ii. If the doee is placed before the verb for emphasis. Example,

    [إِيَّايَ ضَرَبَتْ.]{.ar}  
    [EiyyAya Darabat.]{.trn}  
    "She hit _me_."

## TODO

1. Multiple verb doers: Copy over from sound plurals and rework.
2. [جواز تأنيث الفعل ووجوبه]{.ar}

