# Proper nouns

## Introduction

Proper nouns are also known as names. Here are some examples of Arabic names:

| Men's |names | Women's |names |
|--:|:---|--:|:---|
|[مُحَمَّد]{.ar}         |[#muHammad]{.trn2}      | [عَائِشَة^2^]{.ar}     |[e#AEicah]{.trn2} |
|[سَعِيد]{.ar}         |[#saeId]{.trn2}         | [فَاطِمَة^2^]{.ar}     |[#faTimah]{.trn2} |
|[ٱَلْحَسَن]{.ar}        |[al-#Hasan]{.trn2}      | [حَفْصَة^2^]{.ar}      |[#HafSah]{.trn2} |
|[ٱَلنُّعْمَان]{.ar}      |[al-#nuemAn]{.trn2}     | [سُمَيَّة^2^]{.ar}      |[#sumayyah]{.trn2} |
|[طَلْحَة^2^]{.ar}      |[#TalHah]{.trn2}        | [جَمِيلَة^2^]{.ar}     |[#jamIlah]{.trn2} |
|[أُسَامَة^2^]{.ar}     |[#usAmah]{.trn2}        | [زَيْنَب^2^]{.ar}      |[#zaynab]{.trn2} |
|[عُثْمَان^2^]{.ar}     |[e#uvmAn]{.trn2}        | [مَرْيَم^2^]{.ar}      |[#maryam]{.trn2} |
|[عُمَر^2^]{.ar}       |[e#umar]{.trn2}         | [سُعَاد^2^]{.ar}      |[#sueAd]{.trn2} |
|[إِبْرَاهِيم^2^]{.ar}   |[#ibrAhIm]{.trn2}       | [أَسْمَاء^2^]{.ar}     |[#asmAE]{.trn2} |
|[عَبْد ٱللَّـٰه]{.ar}    |[e#abd #allAh]{.trn2}   | [لَيْلَىٰ^2^]{.ar}      |[#laylA]{.trn2} |
|[أَبُو بَكْر]{.ar}      |[#abU #bakr]{.trn2}     | [أُمّ حَبِيبَة^2^]{.ar}  |[#umm #HabIbah]{.trn2} |

| Place |names | Misc. |names |
|-:|:--|-:|:---|
|[مَكَّة^2^]{.ar}   |Mecca     |[رَمَضَان^2^]{.ar} |[#ramadAn]{.trn2} (a month) |
|[دِمَشْق^2^]{.ar}  |Damascus  |[أُحُد]{.ar}      |[#uHud]{.trn2} (a mountain)    |
|[مِصْر^2^]{.ar}   |Egypt     |[ٱَلنِّيل]{.ar}    |the Nile (a river)             |
|[ٱَلْقَاهِرَة]{.ar}  |Cairo     |[ٱَلْفَاتِحَة]{.ar}  |the [#fAtiHah]{.trn2} (a [sUrah]{.trn2}) |
|[ٱَلْهِنْد]{.ar}    |India     |                |                             |

Note the following points from the list abobe:

+ Although some names begin with [ٱَلْ]{.ar}, most don't.
+ Many names are semi-flexible (indicated by [◌^2^]{.ar}).
+ Some names consist of more than a single word, like [عَبْد ٱللَّـٰه]{.ar}    [e#abd #allAh]{.trn2}

We will explain these and more details regarding proper nouns in this chapter.

## Definiteness of proper nouns

Proper nouns differ from common nouns and adjectival nouns in a couple of important ways:

+ All proper nouns, even if they don't begin with [ٱَلْ]{.ar}, are definite. 
+ A proper noun which does not begin with [ٱَلْ]{.ar}, and which is fully-flexible, shall have an [n]{.trn} mark, despite being definite.

The above points are exemplified in the following sentence:

[ذَهَبْتُ إِلَىٰ بَيْتِ مُحَمَّدٍ ٱلْكَرِيمِ وَزَيْنَبَ ٱلطَّيِّبَةِ.]{.ar}  
[pahabtu EilA bayti muHammadini -lkarImi wazaynaba -TTayyibah.]{.trn}  
"I went to the house of the noble [#muHammad]{.trn2} and the good [#zaynab]{.trn2}."

Note the above from the above example:

+ [مُحَمَّدٍ]{.ar} is fully-flexible so it has an [in]{.trn}-mark [◌ٍ]{.ar} in the i-state.
+ [زَيْنَبَ]{.ar} is semi-flexible so it does not have an [n]{.trn}-mark, and instead has an [a]{.trn} mark [◌َ]{.ar} in the i-state.
+ The proper nouns [مُحَمَّد]{.ar} and [زَيْنَب]{.ar} are describees in descriptive noun phrases.
+ Their describers ([ٱلْكَرِيمِ]{.ar} and [ٱلطَّيِّبَةِ.]{.ar}, respectively) have [ٱَلْ]{.ar} to match the definiteness of the definite proper noun describees. Furthermore, they both end with [◌ِ]{.ar} because they match the i-state of their describees.

## Meanings of names

Many names are re-used from common nouns and adjectival nouns with positive meanings. Examples:

+ [مُحَمَّد]{.ar}         [#muHammad]{.trn2}      "a highly praised one~m~"
+ [سَعِيد]{.ar}         [#saeId]{.trn2}         "a happy (fortunate) one~m~"
+ [ٱَلْحَسَن]{.ar}        [al-#Hasan]{.trn2}      "the good one~m~"
+ [طَلْحَة]{.ar}      [#TalHah]{.trn2}    "an acacia (tree)"
+ [جَمِيلَة]{.ar}     [#jamIlah]{.trn2}   "a beautiful one~f~"

It is possible for these names to sometimes (technically) cause a sentence to have an ambiguous meaning. For example,

[جَلَسَ ٱلْحَسَنُ مَعَ سَعِيدٍ.]{.ar}  
[jalsa -lhasanu maea saeId]{.trn}  
"[al-#Hasan]{.trn2} sat with [#saeId]{.trn2}."  
or  
"The good one~m~ sat with a happy (fortunate) one~m~."  

Context would tell us whether the proper noun or the common/adjectival noun meaning is intended.

Note however the following sentence:

[ذَهَبَتْ جَمِيلَةُ إِلَىٰ ٱلْبَيْتِ.]{.ar}  
[pahabat jamIlatu Eila -lbayt.]{.trn}

This sentence can only be understood to use [جَمِيلَة]{.ar} with its proper noun meaning:

"[#jamIlah]{.trn2} went to the house."

This is because [جَمِيلَة]{.ar} is semi-flexible as a proper noun and fully-flexible as an adjectival/common noun. If [جَمِيلَة]{.ar} were intended to be used with its adjectival/common noun meaning then it would have an [un]{.trn}-mark [◌ٌ]{.ar} and the sentence would be:

[ذَهَبَتْ جَمِيلَةٌ إِلَىٰ ٱلْبَيْتِ.]{.ar}  
[pahabat jamIlatun Eila -lbayt.]{.trn}  
"A beautiful one~f~ went to the house."

We will learn why [جَمِيلَة]{.ar} is semi-flexible as a proper noun in section\ \@ref(proper-nouns-ending-with-looped-ta) below.

## Flexibility of proper nouns

In this section we will discuss the flexibility of proper nouns.
For now, we will deal only with proper nouns that do not begin with [ٱَلْ]{.ar}.
In terms of their flexibility, proper nouns consist of two types:

i. Fully-flexible proper nouns.
i. Semi-flexible proper nouns.

We will treat each of them below.

### Fully-flexible proper nouns

<!--
Fully-flexible proper nouns may or may not begin with [ٱَلْ]{.ar}.

#### Names that begin with [ٱَلْ]{.ar}

If a proper noun begins with [ٱَلْ]{.ar} then the question of its flexibility is pretty much moot. 
This is because noun beginning with with [ٱَلْ]{.ar} display their state fully, regardless of whether or not they are semi-flexible without the [ٱَلْ]{.ar}. Examples:

[ٱَلْحَسَنُ حَفِيدُ رَسُولِ ٱللَّـٰهِ صلى اللّه عليه وسلم.]{.ar}  
"[al-#Hasan]{.trn2} is the grandson of the messenger of [#allAh]{.trn2} (may [#allAh]{.trn2} grant peace and confer blessing upon him)."
(u-state displayed with [◌ُ]{.ar}.)

[سَأَلَ ٱلرَّجُلُ ٱلنُّعْمَانَ عَنْ أَمْرٍ.]{.ar}  
"The man asked [al-#nuemAn]{.trn2} about a matter."  
(a-state displayed with [◌َ]{.ar}.)

[ذَهَبْتُ إِلَى ٱلْقَاهِرَةِ.]{.ar}  
"I went to Cairo."  
(i-state displayed with [◌ِ]{.ar}.)

Examples of names that begin with [ٱَلْ]{.ar} are:

|||||
|--:|:---|--:|:---|
|[ٱَلْحَسَن]{.ar}      |[al-#Hasan]{.trn2}      |[ٱَلْقَاهِرَة]{.ar}    |Cairo
|[ٱَلْحُسَيْن]{.ar}     |[al-#Husayn]{.trn2}     |[ٱَلْهِنْد]{.ar}      |India 
|[ٱَلْعَبَّاس]{.ar}     |[al-e#abbAs]{.trn2}     |[ٱَلصِّين]{.ar}      |China 
|[ٱَلْزُّبَيْر]{.ar}     |[al-#zubayr]{.trn2}     |[ٱَلنِّيل]{.ar}      |the Nile 
|[ٱَلنُّعْمَان]{.ar}    |[al-#nuemAn]{.trn2}     |[ٱَلْفُرَات]{.ar}     |the Euphrates

#### Names that don't begin with [ٱَلْ]{.ar}
-->
For names that don't begin with [ٱَلْ]{.ar}, the default assumption is that they are fully-flexible, unless they fall into one of the categories of semi-flexible nouns (which we will study soon).

Examples of fully-flexible names are:

|||||
|--:|:---|--:|:---|
|[مُحَمَّد]{.ar}         |[#muHammad]{.trn2}  |[مُعَاذ]{.ar}         |[#mueAp]{.trn2}  |
|[نُوح]{.ar}          |[#nUh]{.trn2}       |[سَعْد]{.ar}          |[#saed]{.trn2}   |
|[شُعَيْب]{.ar}         |[#cueayb]{.trn2}    |[عَمَّار]{.ar}         |[e#ammAr]{.trn2} |
|[عَلِيّ]{.ar}          |[e#alI]{.trn2}      |[حَسَّان]{.ar}         |[#HassAn]{.trn2} |
|[زَيْد]{.ar}          |[#zayd]{.trn2}      |[سَعِيد]{.ar}         |[#saeId]{.trn2}  | 
|[أَنَس]{.ar}          |[#anas]{.trn2}      |[أُحُد]{.ar}          |[#uHud]{.trn2} (a mountain) |

These are all masculine names.

Examples of sentences with fully-flexible proper nouns:

[زَيْدٌ غُلَامٌ طَيِّبٌّ.]{.ar}  
[zaydun gulAmun Tayyib]{.trn}  
"Zayd is a good boy."

[شَكَرَ أَنَسٌ عَلِيًّا.]{.ar}  
[cakara Eanasun ealiyyA.]{.trn}  
"Anas thanked [e#alI]{.trn2}."

[لَبِسَ سَعِيدٌ قَمِيصَ نُوحٍ ٱلأَخْضَرَ.]{.ar}  
[labisa saeIdun qamISa nUHini -lEaxDar.]{.trn}  
"[#saeId]{.trn2} wore [#nUH]{.trn2}'s green shirt."

### Semi-flexible proper nouns

The rules for the semi-flexibility of proper nouns are a little different from the rules for the semi-flexibility of common nouns and adjectival nouns that we learned in chapter\ \@ref(semi-flexible-nouns).
Proper nouns shall be semi-flexible if they fall under one of the categories below. Note that the categories are not mutually exclusive. That is: some semi-flexible proper nouns will fall into more than one category.

#### Names ending with [ة]{.ar}

All names ending with [ة]{.ar} shall be semi-flexible. This rule is specific to proper nouns. We have already seen that common nouns and adjectival nouns that end ith [ة]{.ar} are fully-flexible.

Most such proper nouns are feminine names. Examples:

|||||
|--:|:---|--:|:---|
|[خَدِيجَة^2^]{.ar}     |[#xadIjah]{.trn2}   |[مَيْمُونَة^2^]{.ar}    |[#maymUnah ]{.trn2} |
|[فَاطِمَة^2^]{.ar}     |[#faTimah]{.trn2}   |[صَفِيَّة^2^]{.ar}      |[#Safiyyah]{.trn2}  |
|[عَائِشَة^2^]{.ar}     |[e#AEicah]{.trn2}   |[خَوْلَة^2^]{.ar}      |[#xawlah]{.trn2}    |
|[سُمَيَّة^2^]{.ar}      |[#sumayyah]{.trn2}  |[جَمِيلَة^2^]{.ar}     |[#jamIlah]{.trn2}   |
|[حَفْصَة^2^]{.ar}      |[#HafSah]{.trn2}    |[آسِيَة^2^]{.ar}      |[#Asiyah]{.trn2}    |

However, some masculine names may end with [ة]{.ar} too:

|||||
|--:|:---|--:|:---|
|[حَمْزَة^2^]{.ar}     |[#Hamzah]{.trn2}   |[مُعَاوِيَة^2^]{.ar}   |[#mueAwiyah ]{.trn2}|
|[أُسَامَة^2^]{.ar}    |[#usAmah]{.trn2}   |[عِكْرِمَة^2^]{.ar}    |[e#ikrimah ]{.trn2} |
|[طَلْحَة^2^]{.ar}     |[#TalHah]{.trn2}   |[عُبَادَة^2^]{.ar}    |[e#ubAdah]{.trn2}   |

Example:

[طَلْحَةُ ٱلْطَّوِيلُ بَعْلُ جَمِيلَةَ ٱلْكَرِيمَةِ.]{.ar}  
"The tall [#TalHah]{.trn2} is the husband of the generous [#jamIlah]{.trn2}."

#### Names ending with an extrinsic [اء]{.ar} or [ىٰ]{.ar}

Similar to common nouns and adjectival nouns, all names ending with an extrinsic [اء]{.ar} or [ىٰ]{.ar} shall be semi-flexible. These are usually feminine names. Examples:

|||||
|--:|:---|--:|:---|
| [أَسْمَاء^2^]{.ar}     |[#asmAE]{.trn2}  | [لَيْلَىٰ^2^]{.ar}      |[#laylA]{.trn2} |
| [دَرْدَاء^2^]{.ar}     |[#dardAE]{.trn2} | [سَلْمَىٰ^2^]{.ar}      |[#salmA]{.trn2} |

Examples in sentences:

[ذَهَبَتْ سَلْمَىٰ إِلَىٰ بَيْتِ أَسْمَاءَ.]{.ar}  
"[#salmA]{.trn2} went tp [#asmAE]{.trn2}'s house."

Sentence word order is usually pretty flexible. For stylistic reasons, it is permissible for a doee to precede the doer.
For example,

[سَأَلَتْ دَرْدَاءَ أَسْمَاءُ.]{.ar}  
"[#asmAE]{.trn2} asked [#dardAE]{.trn2}"

But because words that end with [ىٰ]{.ar} never display any state, then for these words the sentence word order becomes more rigid. So the following sentence:

[سَأَلَتْ لَيْلَىٰ سَلْمَىٰ.]{.ar}  
would usually only mean
"[#laylA]{.trn2} asked [#salmA]{.trn2}."

#### Names ending with an extrinsic [ان]{.ar}

All names ending with an extrinsic [ان]{.ar} will be semi-flexible. 

This is somewhat different from the rule we learnt for common noun and adjectival nouns in section\ \@ref(adjectival-noun-an-diptote). There only adjectival nouns of the pattern [فَعْلَان]{.ar} and whose feminine was not formed by adding [ة]{.ar} to it were considered semi-flexible nouns.

Examples:

|||||
|--:|:---|--:|:---|
|[عُثْمَان^2^]{.ar}     |[e#uvmAn]{.trn2}  |[رَمَضَان^2^]{.ar}     |[#ramaDAn]{.trn2} |
|[سُفْيَان^2^]{.ar}     |[#sufyAn]{.trn2}  |[شَعْبَان^2^]{.ar}     |[#caebAn]{.trn2}  |

Example:

[جَلَس عُثْمَانُ مَعَ سُفْيَانَ فِي رَمَضَانَ.]{.ar}  
"[e#uvmAn]{.trn2} sat with [#sufyAn]{.trn2} in [#ramaDAn]{.trn2}."

#### Names on the pattern [أَفْعَل]{.ar}

All names on the pattern [أَفْعَل]{.ar} shall be semi-flexible. Examples:

|||||
|--:|:---|--:|:---|
|[أَحْمَد^2^]{.ar}     |[#aHmad]{.trn2}  |[أَسْعَد^2^]{.ar}     |[#asead]{.trn2} |

#### Names of the pattern [فُعَل]{.ar}

Names of the pattern [فُعَل]{.ar} shall be semi-flexible. Examples:

|||||
|--:|:---|--:|:---|
|[عُمَر^2^]{.ar}  |[e#umar]{.trn2} |[مُضَر^2^]{.ar}     |[#muDar]{.trn2} |

Interestingly, the fully-flexible name [e#amr]{.trn2} is written with a silent [و]{.ar} at its end: [عَمْرو]{.ar} when in the u- and i-states in order to distinguish it from the more common name [e#umar]{.trn2}. Otherwise, both names would appear identical when written without vowel marks, thus: [عمر]{.ar}.

Name|u-state|a-state|i-state
:-|:--|:--|:--
[e#amr]{.trn2}|[عَمْرٌو]{.ar} [eamrun]{.trn}| [عَمْرًا]{.ar} [eamran]{.trn}|[عَمْرٍو]{.ar} [eamrin]{.trn}
[e#umar]{.trn2}|[عُمَرُ]{.ar} [eumaru]{.trn}| [عُمَرَ]{.ar} [eumara]{.trn}|[عُمَرَ]{.ar} [eumara]{.trn}

#### Names that are originally verbs

Names that are originally verbs are semi-flexible. Examples:

+ [يَزِيد^2^]{.ar} [#yazId]{.trn2} "He increases"
+ [يَعِيش^2^]{.ar} [#yaeIc]{.trn2} "He lives"

Their origin as verbs will be apparent when we study incomplete-action verbs.

#### Names of foreign origin

Names of foreign origin are generally semi-flexible. These include the names of angels, many of the previous prophets and messengers, and other persons. Examples:

|||||
|--:|:---|--:|:---|
|[جِبْرِيل^2^]{.ar}    |[#jibrIl]{.trn2}  |[زَكَرِيَّا^2^]{.ar}    |[#zakariyyA]{.trn2}|
|[إِبْرَاهِيم^2^]{.ar}  |[#ibrAhIm]{.trn2} |[يَحْيَىٰ^2^]{.ar}     |[#yaHyA]{.trn2}    |
|[إِسْمَاعِيل^2^]{.ar}  |[#ismAeIl]{.trn2} |[هَاجَر^2^]{.ar}     |[#hAjar]{.trn2}    |
|[إِسْحَاق^2^]{.ar}    |[#isHAq]{.trn2}   |[مَرْيَم^2^]{.ar}     |[#maryam]{.trn2}   |
|[يَعْقُوب^2^]{.ar}    |[#yaeqUb]{.trn2}  |[يَأْجُوج^2^]{.ar}    |[#yaEjUj]{.trn2}   |
|[يُوسُف^2^]{.ar}     |[#yUsuf]{.trn2}   |[مَأْجُوج^2^]{.ar}    |[#maEjUj]{.trn2}   |
|[يُونُس^2^]{.ar}     |[#yUnus]{.trn2}   |[إِبْلِيس^2^]{.ar}    |[#iblIs]{.trn2}    |
|[إِدْرِيس^2^]{.ar}    |[#idrIs]{.trn2}   |[فِرْعَون^2^]{.ar}    |Pharoah            |
|[أَيُّوب^2^]{.ar}     |[#ayyUb]{.trn2}   |[هِرْقَل^2^]{.ar}     |Heraclius          |
|[مُوسَىٰ^2^]{.ar}     |[#mUsA]{.trn2}    |[كِسْرَىٰ^2^]{.ar}     |Chosroes           |
|[عِيسَىٰ^2^]{.ar}     |[e#IsA]{.trn2}    |[قَيْصَر^2^]{.ar}     |Caesar             |

Note that 
[فِرْعَون^2^]{.ar} "Pharoah" 
as [قَيْصَر^2^]{.ar}     "Caesar",
despite being titles,
are treated as proper names.

The only exception to this rule is a masculine name of foreign origin that comprises of only three letters, and whose middle letter has an $\emptyset$-mark. Such a name will be fully-flexible. Example:

+ [نُوح]{.ar} [#nUH]{.trn2}

#### Feminine names

All feminine names, regardless of their origin, or their ending, shall be semi-flexible. We have already given examples of semi-flexible feminine names that end with [ة]{.ar}, [اء]{.ar}, and [ىٰ]{.ar}, so we will provide other examples here:

|||||
|--:|:---|--:|:---|
[زَيْنَب^2^]{.ar}      |[#zaynab]{.trn2} |[مَرْيَم^2^]{.ar}      |[#maryam]{.trn2} |
[سُعَاد^2^]{.ar}      |[#sueAd]{.trn2}  |[هَاجَر^2^]{.ar}      |[#hAjar]{.trn2}  |

The only exception to this rule is a feminine name of native Arabic origin, that comprises of only three letters, and whose middle letter has an $\emptyset$-mark. Such a name is permitted to be optionally fully-flexible or semi-flexible. Examples:

+ [هِنْد]{.ar} Hind
+ [دَعْد]{.ar} [#daed]{.trn2}

Example of usage:

[ذَهَبَتْ هِنْدٌ إِلَىٰ بَيْتِ دَعْدٍ.]{.ar}  
or  
[ذَهَبَتْ هِنْدُ إِلَىٰ بَيْتِ دَعْدَ.]{.ar}  
"Hind went to [#daed]{.trn2}'s house.

## The name [فُلَان]{.ar}

The fully-flexible name [فُلَان]{.ar} is used as a place-holder name in casual conversations. It may be translated into English as "so-and-so". For example,

[ظَلَمَ ٱلرَّجُلُ فُلَانًا وَغَدَرَ بِفُلَانٍ.]{.ar}
"The man wronged so-and-so and he acted treacherously with so-and-so."

For females, the name [فُلَانَة^2^]{.ar} is used.

[صَدَقَتْ فُلَانَةُ.]{.ar}  
"So-and-so~f~ told the truth."

## The Replacement

Before we proceed with our discussion on proper nouns, we will take a short digression to discuss a grammatical concept called the _replacement_. We will only give a short preview here and will treat it fully in chapter\ \@ref(the-replacement-chapter).

A _replacement_ is a word that follows another word, the _replacee_, and replaces it from the perspective of the grammar of the sentence. The replacement is put in the same state as the replacee.
Here is an example of a sentence with a replacement and a replacee:

```{r,echo=FALSE,engine='tikz', engine.opts = list(template = "srctex/tikz2pdf-lua.tex")}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text= \txarb{كِتَابًا.} \txarb{شَيْـًٔا} \txarb{ٱلْغُلَامُ} \txarb{أَخَذَ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, below=0.5ex, left=0.2ex, rotate=90] {\scriptsize replacement};

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, below=0.5ex, left=0.2ex, rotate=90] {\scriptsize replacee};

\path [decoration={text effects along path, 
  text={``The boy took something: a book''},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate, below=13ex] (0,0);


\end{tikzpicture}
```

In the above sentence, the word [كِتَابًا]{.ar} "a book" is the replacement of 
[شَيْـًٔا]{.ar} "something". Therefore, it is put in the same a-state.

The replacement is frequently used with proper nouns. For example,

[ذَهَبَ ٱلْغُلَامُ إِلَىٰ بَيْتِ عَمِّهِ عَلِيٍّ.]{.ar}  
"The boy went to his uncle [e#alI]{.trn2}'s house."

In this sentence, the name [عَلِيّ]{.ar} [e#alI]{.trn2} is the replacement of the replacee [عَمّ]{.ar} "uncle". Note, again, that the replacement comes after the replacee and matches it in state. However, the replacement does not need to come directly after the replacee. We can see that there is the pronoun [ه]{.ar} "his" between them.

Here is another example:

[سَأَلَ ٱلطَّالِبُ مُعَاذٌ ٱلْمُعَلِّمَ سَعْدًا.]{.ar}  
"The student [#mueAp]{.trn2} asked the teacher [#saed]{.trn2}."

## Annexed names

So far we have only dealt with proper nouns that are single words. There are some proper nouns that may be formed from two words that are in an annexation. These belong to different categories:

### "Slave of" names

Some names are formed by annexing the noun [عَبْد]{.ar} [eabd]{.trn} "a slave" to one of the names of [#allAh]{.trn2}. The most common of these names are:

+ [عَبْد ٱللَّـٰه]{.ar} [e#abd #allAh]{.trn2} "the Slave of [#allAh]{.trn2}"
+ [عَبْد ٱلرَّحْمَـٰن]{.ar} [e#abd al-#raHmAn]{.trn2} "the Slave of the Most Merciful"

As usual, the base noun shall always be in the i-state. And the state of the annexe noun [عَبْد]{.ar} is variable, depending on it's function in the sentence. Example:

[عَبْدُ ٱللَّـٰهِ هُوَ أَخُو عَبْدِ ٱلرَّحْمَـٰنِ.]{.ar}
"[e#abd #allAh]{.trn2} is the brother of [e#abd al-#raHmAn]{.trn2}."

### "Parent of" names

It is common to call a man, not by his own given name, but rather by calling him the father of one of his children, usually his first born son. For example, if a man named [أَحْمَد]{.ar} "[#aHmad]{.trn2}" had a son named [زَيْد]{.ar} "Zayd", he may be called [أَبُو زَيْد]{.ar} [#abU #zayd]{.trn2} "Zayd's father". Example of usage in a sentence:

[ذَهَبْتُ إِلَىٰ بَيْتِ أَبِي زَيْدٍ.]{.ar}  
"I went to [#abU #zayd]{.trn2}'s house."  
(Note how [زَيْدٍ]{.ar} has an [in]{.trn}-mark [◌ٍ]{.ar} in the i-state because it is fully-flexible.)

While using the name of first-born son is more common, a daughter's name could be used as well. Example,

[سَأَلْتُ أَبَا رُقَيَّةَ سُؤالًا.]{.ar}  
"I asked [#abU #ruqayyah]{.trn2} a question."  
(Note how [رُقَيَّةَ]{.ar} has an [a]{.trn}-mark [◌َ]{.ar} in the i-state because it is semi-flexible.)

Women, too, are similarly called as the mother of one of their children. For example, 
the wife of the Prophet
(may [#allAh]{.trn2} grant peace and confer blessing upon him)
[أُمّ حَبِيبَة^2^]{.ar} [#umm #HabIbah]{.trn2}
was called thus because she had a daughter named
[حَبِيبَة^2^]{.ar}
from a previous marriage.
<!--a woman with a daughter named [حَبِيبَة^2^]{.ar} could be called [أُمّ حَبِيبَة^2^]{.ar} [#umm #HabIbah]{.trn2}.-->

By the way, a person need not literally be a father or a mother to be called in such a way. These names may be applied as nicknames.

For example, the Companion of the Prophet
(may [#allAh]{.trn2} grant peace and confer blessing upon him)
was called
[أَبُو هُرَيرَة^2^]{.ar} 
[#abU #hurayrah]{.trn2}
because it is reported that he used to have a pet kitten ([هُرَيْرَة]{.ar}). Here is an example of this name in a sentence.

[أَبُو هُرَيْرَةَ صَحَابِيٌّ جَلِيلٌ.]{.ar}  
"[#abU #hurayrah]{.trn2} is a great Companion."  
(Note how [هُرَيْرَةَ]{.ar} is now considered a semi-flexible proper noun even though it may originally have been derived from the common noun "a kitten".)

Similarly, the Companion [أَبُو بَكْرٍ]{.ar} [#abU #bakr]{.trn2} is not known to have a son named [بَكْر]{.ar}.

It is often the case that a "parent of" name overtakes the actual given name of person in popularity, and becomes the person's name for all intents and purposes. Such is indeed the case for the Companions 
[أَبُو بَكْرٍ]{.ar} [#abU #bakr]{.trn2}
and
[أَبُو هُرَيرَة^2^]{.ar} 
[#abU #hurayrah]{.trn2}.

### "Son of" names

In a manner similar to "parent of" names, a person may be referred to as the son of his parent. For example, the Companion [عُمَر^2^]{.ar} [e#umar]{.trn2} had a son named 
[عَبْد ٱللَّـٰه]{.ar} [e#abd #allAh]{.trn2}. He is commonly known as [ٱِبْن عُمَر^2^]{.ar} [#ibn e#umar]{.trn2} "[e#umar]{.trn2}'s son".

Attributing a son to his father is most common. But attributing him to a mother or other ancestor is also possible.

Examples:

+ the Companion [عَمَّار]{.ar} was affectionately called [ٱِبْن سُمَيَّة^2^]{.ar} [#ibn #sumayyah]{.trn2} "[#sumayyah]{.trn2}'s son" by the Prophet
(may [#allAh]{.trn2} grant peace and confer blessing upon him). His mother [#sumayyah]{.trn2} was an early martyr in [#islAm]{.trn2}.
+ the famous scholar [ٱِبْن كَثِير]{.ar} [#ibn #kavIr]{.trn2} is referred to by his grandfather's name [كَثِير]{.ar} [#kavIr]{.trn2}.
+ a human being is called [ٱِبْن آدَم^2^]{.ar} based on his being a descendent of the first man, the Prophet [#adam]{.trn2}.

#### Full names

The full name of a person is formed by putting his given name first, and then his "son of" name after it as a replacement. Here is an example of a full name:

[زَيْدُ بْنُ أَحْمَدَ]{.ar}  
Zayd the son of [#aHmad]{.trn2}

Note some peculiarities of the full name:

+ The name [زَيْد]{.ar} "Zayd" has lost its [n]{.trn} mark.
+ The word [بْن]{.ar} "son" is not written with its initial connecting [hamzah]{.trn2} [ٱ]{.ar}.

These peculiarities are only when forming a full name in this manner. Consider for example the following sentence:

[زَيْدٌ ٱبْنُ أَحْمَدَ.]{.ar}  
Zayd is the son of [#aHmad]{.trn2}

In the above example, the name [زَيْدٌ]{.ar} has its [n]{.trn}-mark and [ٱبْن]{.ar} is written with its connecting [hamzah]{.trn2} [ٱ]{.ar}. Therefore this is not an expression of the full name in a replacee-replacement format. Rather, [ٱبْنُ أَحْمَدَ]{.ar} here is the information of the sentence.

For women, the word [بِنْت]{.ar} is used instead of [بْن]{.ar}. 

Example:

[قَرَأَتِ ٱلْمُعَلِّمَةُ كِتَابَ ٱلطَّالِبَةِ زَيْنَبَ بِنْتِ أَحْمَدَ.]{.ar}  
"The teacher read the book of the student Zaynab the daughter of [#aHmad]{.trn2}."

The names of multiple forefathers may be strung together in this way separated by [بْن]{.ar}. For example:

[ٱِسْمُ نَبِيِّنَا مُحَمَّدُ بْنُ عَبْدِ ٱللَّـٰهِ بْنِ عَبْدِ ٱلْمُطَّلِبِ.]{.ar}  
"Our prophet's name is [#muHammad]{.trn2} the son of [e#abd #allAh]{.trn2} the son of [e#abd al-#muTTalib]{.trn2}."  
(Note that the second [بْنِ]{.ar} is in the i-state to match the state of the annexe noun [عَبْدِ]{.ar} in [عَبْدِ ٱللّـٰه]{.ar}.)

We will deal with complete full names in section\ \@ref(complete-full-names) below.

### Other annexed names

Other words besides
[عَبْد]{.ar},
[أَب]{.ar},
[أُمّ]{.ar},
and
[ٱِبْن]{.ar}
may be used in annexed names too. Here are some examples:

+ [ذُو ٱلْقَرْنَينِ]{.ar} [#zu l-Qarnayn]{.trn2} "He of the two horns"
+ [مَدِينَة ٱلنَّبِي]{.ar} [madinatu -nnabiyyi]{.trn} "The City of the Prophet", frequently reduced to simply [ٱَلْمَدِينَة]{.ar} "Medina". 

  Context is used to infer whether by [ٱَلْمَدِينَة]{.ar} is meant "Medina" or "the city".
+ [ٱمْرُؤُ ٱلْقَيْس]{.ar} [#imruE al-#qays]{.trn2} "The man of al-Qays", a pre-[#islAm]{.trn2}ic poet.

## Names beginning with [ٱَلْ]{.ar}

Most names do not begin with [ٱَلْ]{.ar}. Some, however, do begin with [ٱَلْ]{.ar}. Examples:

|||||
|--:|:---|--:|:---|
|[ٱَلْحَسَن]{.ar}      |[al-#Hasan]{.trn2}      |[ٱَلْزُّبَيْر]{.ar}     |[al-#zubayr]{.trn2}|
|[ٱَلْحُسَيْن]{.ar}     |[al-#Husayn]{.trn2}     |[ٱَلنُّعْمَان]{.ar}    |[al-#nuemAn]{.trn2}|
|[ٱَلْعَبَّاس]{.ar}     |[al-e#abbAs]{.trn2}     ||

If a proper noun begins with [ٱَلْ]{.ar} then the question of its flexibility is pretty much moot. 
This is because noun beginning with with [ٱَلْ]{.ar} display their state fully, regardless of whether or not they are semi-flexible without the [ٱَلْ]{.ar}. Examples:

[ٱَلْحَسَنُ حَفِيدُ رَسُولِ ٱللَّـٰهِ صلى اللّه عليه وسلم.]{.ar}  
"[al-#Hasan]{.trn2} is the grandson of the messenger of [#allAh]{.trn2} (may [#allAh]{.trn2} grant peace and confer blessing upon him)."  
(u-state displayed with [◌ُ]{.ar}.)

[سَأَلَ ٱلرَّجُلُ ٱلنُّعْمَانَ عَنْ أَمْرٍ.]{.ar}  
"The man asked [al-#nuemAn]{.trn2} about a matter."  
(a-state displayed with [◌َ]{.ar}.)

[ذَهَبْتُ إِلَى بَيْتِ ٱلنُّعْمَانِ.]{.ar}  
"I went to [al-#nuemAn]{.trn2}'s house."  
(i-state displayed with [◌ِ]{.ar}.)

Names that begin with [ٱَلْ]{.ar} can sometimes lose their initial [ٱَلْ]{.ar}. Sometimes, this is systematic, as we will lear in section\ \@ref(calling-names-with-al).
Other times, it's hard to tell why. 

Conversely, names that don't begin with [ٱَلْ]{.ar} can sometimes gain it.

Examples:

+ The name of the daughter of the Companion [أَبُو ٱلدَّرْدَاء]{.ar} [#abu l-#dardAE]{.trn2} is actually [دَرْدَاء^2^]{.ar} [#dardAE]{.trn2}, not [ٱَلدَّرْدَاء]{.ar}.

+ The son of the uncle of the Prophet
(may [#allAh]{.trn2} grant peace and confer blessing upon him)
[ٱَلْعَبَّاس]{.ar} [al-e#abbAs]{.trn2}
is called
[ٱِبْن عَبَّاس]{.ar} [#ibn eabbAs]{.trn2}, not [ٱِبْن ٱلْعَبَّاس]{.ar}.


However, the son of 
[ٱَلْزُّبَيْر]{.ar}     [al-#zubayr]{.trn2}|
is called
[ٱِبْن ٱلْزُّبَيْر]{.ar}     [#ibn al-#zubayr]{.trn2} with the [ٱَلْ]{.ar}.

## Place names

Place names are generally feminine. Because of their feminine gender, those not beginning with [ٱَلْ]{.ar} will be semi-flexible according to section\ \@ref(feminine-names) above.

Examples of place names are:

|||||
|--:|:---|--:|:---|
|[مَكَّة^2^]{.ar}    |Mecca             |[ٱَلْمَدِينَة]{.ar}   |Medina|
|[دِمَشْق^2^]{.ar}   |Damascus          |[ٱَلْقَاهِرَة]{.ar}   |Cairo |
|[بَغْدَاد^2^]{.ar}  |[#bagdAd]{.trn2}  |[ٱَلْهِنْد]{.ar}     |India |
|[مِصْر^2^]{.ar}    |Egypt             |[ٱَلصِّين]{.ar}     |China |
|[فَارِس^2^]{.ar}   |Persia            |[ٱَلرُّوم]{.ar}     |Rome  |
|[تَبُوك^2^]{.ar}   |[#tabUk]{.trn2}   |[ٱَلْبَصْرَة]{.ar}    |[#baSrah]{.trn2}|

Example of use:

[ذَهَبَ ٱلرَّجُلُ إِلَىٰ مَكَّةَ ٱلْمُكَرَّمَةِ وَٱلْمَدِينَةِ ٱلْمُنَوَّرَةِ.]{.ar}  
"The man went to the ennobled Mecca and the illuminated Medina."

While most place names are feminine, a few are masculine. Among these are:

|||||
|--:|:---|--:|:---|
|[ٱَلْيَمَن]{.ar}  |Yemen  |[ٱَلشَّام]{.ar}  |the Levant |
|[ٱَلْعِرَاق]{.ar} |Iraq   ||

## Names of tribes

Here are examples of names of tribes:

|||||
|--:|:---|--:|:---|
|[قُرَيش]{.ar}           | [#qurayc]{.trn2}      |[ٱَلْأَوْس]{.ar}          | [al-#aws]{.trn2}        |
|[بَنُو تَمِيم]{.ar}       | [#banU #tamIm]{.trn2} |[ٱَلْخَزْرَج]{.ar}         | [al-#xazraj]{.trn2}     |
|[هَوَازِن^2^]{.ar}       | [#hawAzin]{.trn2}     |[بَنُو إِسْرَائِيل^2^]{.ar} | [#banU #isrAEIl]{.trn2} |

Tribes are usually called by the name of their progenitor. For example, [إِسْرَائِيل^2^]{.ar} [#isrAEIl]{.trn2} is a name of the Prophet [يَعْقُوب^2^]{.ar} [#yaeqUb]{.trn2}. 
The [Un]{.trn} sound plural [بَنُونَ]{.ar} "sons/children" is annexed to the name 
[إِسْرَائِيل^2^]{.ar} [#isrAEIl]{.trn2}
to get the name of the tribe
[بَنُو إِسْرَائِيل^2^]{.ar} [#banU #isrAEIl]{.trn2} "the children of [#isrAEIl]{.trn2}". In the a- and i-states, this becomes
[بَنِي إِسْرَائِيل^2^]{.ar} [#banI #isrAEIl]{.trn2}.

Not all tribe names have [بَنُونَ]{.ar} "sons" annexed to them, but many do. And often it is optional to keep or drop the annexed [بَنُونَ]{.ar}. Examples:

+ [قُرَيْش]{.ar} [#qurayc]{.trn2} usually does not have [بَنُونَ]{.ar} annexed to it.
+ [بَنُو تَمِيم]{.ar} [#banU #tamIm]{.trn2} may optionally drop the annexed [بَنُونَ]{.ar} and be called simply [تَمِيم]{.ar} [#tamIm]{.trn2}.

### Flexibility of tribe names

The flexibility of tribe names depends on the name. Here are some examples:

+ [إِسْرَائِيل^2^]{.ar} [#isrAEIl]{.trn2} is a name of foreign origin and is therefore semi-flexible. Example:

  [بَعَثَ ٱللَّـٰهُ مُوسَىٰ إِلَىٰ بَنِي إِسْرَائِيلَ.]{.ar}  
  "[#allAh]{.trn2} sent [#mUsA]{.trn2} to the children of [#isrAEIl]{.trn2}."

+ [قُرَيْش]{.ar}            [#qurayc]{.trn2}     and [تَمِيم]{.ar}        [#tamIm]{.trn2} are native Arabic masculine names and are therefore fully-flexible. Example:

  [قُرَيشٌ وَبَنُو تَمِيمٍ قَبِيلَتَانِ.]{.ar}  
  "[#qurayc]{.trn2}     and [#banU #tamIm]{.trn2} are tribes~2~."

+ [هَوَازِن^2^]{.ar} [#hawAzin]{.trn2} is on the semi-flexible noun pattern [فَفَافِف^2^]{.ar} and is therefore semi-flexible.

### Gender of tribe names

Tribe names are unusual in that they are treated as both singular feminine and plural masculine.
If the tribe name is the doer of a verb then it is usually treated as singular feminine.
Otherwise, for example, if it comes before the verb, then the plural masculine pronouns are used for it.

Example:

[سَكَنَتْ قُرَيْشٌ مَكَّةَ وَعَبَدُوا ٱلْأَصْنَامَ.]{.ar}  
"[#qurayc]{.trn2} dwelled in Mecca and they worshipped idols."

## Titles

Titles are common nouns that denote a rank or position of a person. Titles in English include: Doctor, Mister, and King. For example:

+ King David
+ Mr. Smith
+ Dr. Adams

Here are some examples of titles in Arabic:

|||||
|--:|:---|--:|:---|
|[ٱَلنَّبِيّ]{.ar}   |Prophet    |[ٱَلْإِمَام]{.ar}  |[#imAm]{.trn2} |
|[ٱَلْمَلِك]{.ar}   |King       |[ٱَلشَّيْخ]{.ar}   |[#cayx]{.trn2} |
|[ٱَلْأَمِير]{.ar}  |Commander  |[ٱَلْحَافِظ]{.ar}  |[#HAfiP]{.trn2}|
|[ٱَلْقَاضِي]{.ar}  |Judge      |[ٱَلْأُسْتَاذ]{.ar} |Professor      |

Some Arabic titles are left untranslated in English like

+ [ٱَلْإِمَام]{.ar}  [#imAm]{.trn2} (a leader)
+ [ٱَلشَّيْخ]{.ar}   [#cayx]{.trn2} (a venerable man)
+ [ٱَلْحَافِظ]{.ar}  [#HAfiP]{.trn2} (one who has memorized, and preserved religious texts)

### Titles as replacees

Titles are usually placed in front a proper noun and made definite with [ٱَلْ]{.ar} to match the proper noun. For example,

[سَأَلَ رَجُلٌ ٱلْإِمَامَ مَالِكًا عَنْ أَمْرٍ.]{.ar}  
"A man asked [#imAm #mAlik]{.trn2} about a matter."

In the above sentence, the title [ٱَلْإِمَامَ]{.ar} [#imAm]{.trn2} is a replacee and the name [مَالِكًا]{.ar} [#mAlik]{.trn2} is the replacement.

Some titles are formed from annexations. Examples:

|||||
|--:|:---|--:|:---|
|[خَلِيفَةُ رَسُولِ ٱللَّـٰهِ]{.ar}  | the Successor of the Messenger of [#allAh]{.trn2}  |[سَيْفُ ٱللَّـٰهِ]{.ar}         | the Sword of [#allAh]{.trn2}  |
|[أَمِيرُ ٱلْمُؤْمِنِينَ]{.ar}     | the Commander of the Believers                     |[عِمَادُ ٱلدِّينِ]{.ar}        | the Pillar of the Faith  |
|[أُمُّ ٱلْمُؤْمِنِينَ]{.ar}       | the Mother of the Believers                        |[صَلَاحُ ٱلدِّينِ]{.ar}        | the Righteousness of the Faith  |

Example:

[أُمُّ ٱلْمُؤْمِنِينَ عَائِشَةُ هِيَ ٱِبْنَةُ خَلِيفَةِ رَسُولِ ٱللَّـٰهِ أَبِي بَكْرٍ.]{.ar}  
"The Mother of the Believers [e#AEicah]{.trn2} is the daughter of the Successor of the Messenger of [#allAh]{.trn2} [#abU #bakr]{.trn2}."

### Titles in annexations

Some prominent inanimate objects, like mountains, rivers, and cities, may have titles. For example:

+ Mount Everest
+ the river Nile
+ the city of Damascus

In Arabic, the titles for these objects usually don't occur as replacees as they do for persons. Rather, the title is annexed to the proper noun in an annexation. Examples:

|||||
|--:|:---|--:|:---|
|[جَبَلُ أُحُدٍ]{.ar}      |Mount [#uHud]{.trn2} |[مَدِينَةُ دِمَشْقَ]{.ar}   |the city of Damascus |
|[نَهْرُ ٱلنِّيلِ]{.ar}    |the river Nile      |[شَهْرُ رَمَضَانَ]{.ar}    |the month of [#ramaDAn]{.trn2} |
|[سُورَةُ ٱلْفَاتِحَةِ]{.ar} |the [#sUrah]{.trn2} of [al-#fAtiHah]{.trn2} ||

Example:

[قَرَأَتِ ٱلْجَارِيَةُ سُورَةَ ٱلْفَاتِحَةِ فِي شَهْرِ رَمَضَانَ.]{.ar}  
"The girl read the [#sUrah]{.trn2} of [al-#fAtiHah]{.trn2} in the month of [#ramaDAn]{.trn2}."

## Nicknames

Nicknames are often given to people. They are usually descriptive of some physical quality or character trait of the person. For example, the Companion [#abU #bakr]{.trn2} was given the  nickname [ٱلصِّدِّيق]{.ar} "the steadfast affirmer of the truth".

Nicknames usually come after a person's name as a replacement.

[أَبُو بَكَرٍ ٱلصِّدِّيقُ هُوَ خَلِيفَةُ رَسُولِ ٱللَّـٰهِ.]{.ar}  
"[#abU #bakr]{.trn2} the steadfast affirmer of the truth is the successor of the messenger of [#allAh]{.trn2}."

[قَرَأَ سُلَيْمَانُ ٱلأَعْمَشُ ٱلْقُرْآنَ.]{.ar}  
"[#sulaymAn]{.trn2} the weak-sighted read the [#qurEAn]{.trn2}."

## The affiliate adjectival noun

The affiliate adjectival noun is a kind of adjectival noun that indicates an affiliation.

Here are some examples of affiliate adjectival nouns:

|||||
|--:|:---|--:|:---|
|[عِرَاقِيّ]{.ar}    |an Iraqi            |[قُرَشِيّ]{.ar}     |a [#qurayc]{.trn2}ite |
|[مَكِّي]{.ar}      |a Meccan            |[تَمِيمِيّ]{.ar}    |a [#tamIm]{.trn2}ian  |
|[دِمَشْقِيّ]{.ar}    |a Damascan          |[إِسْرَائِيلِيّ]{.ar} |an [#isrAEIl]{.trn2}ite|
|[شَافِعِيّ]{.ar}    |a [#cAfie]{.trn2}ite |[حَنَفِيّ]{.ar}     |a [#HanafI]{.trn2}    |
|[مَالِكِيّ]{.ar}    |a [#mAlikI]{.trn2}   |[حَنْبَلِيّ]{.ar}    |a [#HanbalI]{.trn2}   |

Note the following about affiliate adjectival nouns:

+ Generally, the ending [◌ِيّ]{.ar} [-iyy]{.trn} is suffixed to a noun to create an affiliate adjectival noun. 
+ The [ة]{.ar} ending is removed before adding the [◌ِيّ]{.ar} [-iyy]{.trn} suffix.
+ Sometimes there are other internal changes to the word before this suffix is added. For example,
  + [قُرَيْش]{.ar} becomes [قُرَشِيّ]{.ar}
+ The affiliate adjectival noun may be formed from any of the names of a person. (Usually, one of the more distinctive names is chosen.) For example:
  + A follower of the school of thought of [ٱَلْإِمَام أَبُو حَنِيفَة]{.ar} [#imAm #abU #HanIfah]{.trn2} is called [حَنَفِيّ]{.ar} "a [#HanafI]{.trn2}".
  + A follower of the school of thought of [ٱَلْإِمَام أَحْمَد بْن حَنْبَل]{.ar} [#imAm #aHmad ibn #Hanbal]{.trn2} is called [حَنْبَلِيّ]{.ar} "a [#HanbalI]{.trn2}".

We will treat adjectival nouns more fully in chapter\ \@ref(the-affiliate-adjective-chapter).

Afflilate adjectival nouns frequently occur with proper nouns. They come after the proper noun as a replacement, and are made definite by [ٱَلْ]{.ar} to match the proper noun in definiteness. Examples:

[ٱِبْن كَثِيرٍ ٱلدِّمَشْقِيُّ مُفَسِّرٌ وَمُؤَرِّخٌ.]{.ar}  
"[#ibn #kavIr]{.trn2} the Damascan is an exegete and a historian."

## Complete full names

We have already studied how a basic full name is formed in section\ \@ref(full-names). Here, we will expand on that topic.

The complete full name of a person is formed by placing some or all of his different names in a particular order. Each name in the order is a replacement of one of the names before it. Generally, the order is:

i. Titles
i. "Father of" name
i. Given name
i. "Son of" names
i. Affiliate names

The nickname's position is variable.

Here are some examples of full names in varying degrees of completeness:

[عَائِشَةُ هِيَ ٱبْنَةُ خَلِيفَةِ رَسُولِ ٱللَّـٰهِ أَبِي بَكْرٍ ٱلصِّدِّيقِ.]{.ar}  
"[e#AEicah]{.trn2} is the daughter of the  Successor of the Messenger of [#allAh]{.trn2}, [#abU #bakr]{.trn2}, the steadfast affirmer of the truth."

[قَتَلَ أَبُو لُؤْلُؤَةَ ٱلْمَجُوسِيُّ أَمِيرَ ٱلْمُؤْمِنِينَ أَبَا حَفْصٍ عُمَرَ بْنَ ٱلْخَطَّابِ.]{.ar}  
"[#abU #luEluEah]{.trn2}, the Magian killed the Commander of the Believers, [#abU #HafS]{.trn2}, [e#umar]{.trn2} the son of [al-#xaTTAb]{.trn2}."

[كَتَبَ ٱلْحَافِظُ ٱلْمُؤَرِّخُ ٱلْمُفَسِّرُ عِمَادُ ٱلدِّينِ أَبُو ٱلْفِدَاءِ إِسْمَاعِيلُ بْنُ عُمَرَ بْنِ كَثِيرٍ ٱلْقُرَشِيُّ ٱلدِّمَشْقِيُّ ٱلشَّافِعِيُّ تَفْسِيرًا.]{.ar}  
"The [#HAfiP]{.trn2}, the historian, the exegete, the Pillar of the Faith, the father of [al-#fidAE]{.trn2}, [#ismAEIl]{.trn2} the son of [e#umar]{.trn2} the son of [#kavIr]{.trn2}, the [#qurayc]{.trn2}ite, the Damascan, the [#cAfie]{.trn2}ite wrote an exegesis."  
(Note how the second [بْنِ]{.ar} is in the i-state because it is a replacement of [عُمَرَ]{.ar} which is in the i-state because it is a base noun of the first [بْنُ]{.ar}.)
  
