# Questions

## Introduction

TODO

## [أَ]{.ar} and [هَلْ]{.ar} questions

TODO

## [مَنْ]{.ar} "Who" questions

In chapter\ \@ref(the-connected-nouns) we have studied the use of [مَنْ]{.ar} [man]{.trn} as a connected noun.
Now, we will study its use as a question noun.
[مَنْ]{.ar} is used to formulate "who" questions.
As with connected-nouns [مَنْ]{.ar} is typically used for intelligent beings. 
(See section\ \@ref(man-and-maa-for-intelligent) for when [مَنْ]{.ar} may be used for non-intelligent beings.)
Except in case that we will note below,
[مَنْ]{.ar}
is usually placed in the beginning of the question sentence.
Being a noun, [مَنْ]{.ar} may be in one of the three states but because it is a rigid noun, its state will not be apparent.
[مَنْ]{.ar} is considered a singular masculine noun but it is used for all numbers and genders.

### [مَنْ]{.ar} in the u-state

Here are some examples of the question noun
[مَنْ]{.ar}
as the subject of a sentence:

[مَنْ زَيْدٌ؟]{.ar}  
"Who is Zayd?"

[مَنْ أَخُوهُ زَيْدٌ؟]{.ar}  
"Whose brother is Zayd?"

[مَنْ أَنْتِ؟]{.ar}  
"Who are you~1f~?"

[مَنِ هَـٰؤُلَاءِ ٱلنِّسَاءُ؟]{.ar}  
"Who are these women?"

[مَنْ ٱلرِّجَالُ ٱلَّذِينَ جَاءُوا؟]{.ar}  
"Who are the men that have come?

In all the above sentences
[مَنْ]{.ar}
is the subject of the sentence, 
and the rest of the sentence constitutes the information.
The noun following 
[مَنْ]{.ar},
even when indefinite,
cannot be considered its describer or replacement.
Therefore, [مَنْ رَجُلٌ؟]{.ar} can only mean "Who is a man?", not "Which man?".

<!--
[مَنْ إِلَٰهٌ غَيْرُ اللَّهِ يَأْتِيكُم بِضِيَاءٍ]{.ar}  
Don't think I can use this. Most English translations say "what/which deity".
Even though i3raab texts say ilaah is a khabar.
-->

When [مَنْ]{.ar} is used to ask about the doer of a verb, the verb is generally used with a singular masculine doer pronoun.
For example:

[مَنْ جَاءَ؟]{.ar}  
"Who came?"

However, occasionally, the verb's doer pronoun can be made to match the gender of the person(s) who are being asked about,
especially if the question is specific to a gender. For example:

[مَنْ كَانَتْ أُمَّكَ؟]{.ar}  
"Who was your mother?"

Note how [كَانَتْ]{.ar} has a feminine doer pronoun to match the gender of [أُمَّكَ]{.ar}.[^man-doer-pronoun]

[^man-doer-pronoun]: Wright states (vol.\ 2, §170, p.\ 313C):

    > As interrogatives, [مَنْ]{.ar} and [مَا]{.ar} are construed with the masculine singular of a verb, but occasionally admit of the feminine when the predicate is of the feminine gender; as [مَنْ كَانَتْ أُمَّكَ]{.ar} who was your mother?

    From [البحر المحيط لأبي حيان]{.ar} for the [tafsIr]{.trn2} of [فَإِن كَانَتَا ٱثۡنَتَیۡنِ]{.ar} [4:176]:

    > [... مَن صُرِّحَ بِها ولَها لَفْظٌ ومَعْنًى. فَمَن أنَّثَ راعى المَعْنى، لِأنَّ التَّقْدِيرَ: أيَّةُ أُمٍّ كانَتْ أُمَّكَ. ومَدْلُولُ الخَبَرِ في هَذا مُخالِفٌ لِمَدْلُولِ الِاسْمِ، بِخِلافِ الآيَةِ، فَإنَّ المَدْلُولَيْنِ واحِدٌ، ولَمْ يُؤَنَّثْ في مَن كانَتْ أُمَّكَ لِتَأْنِيثِ الخَبَرِ، إنَّما أُنِّثَ مُراعاةً لِمَعْنى مَن إذْ أرادَ بِها مُؤَنَّثًا. ألا تَرى أنَّكَ تَقُولُ: مَن قامَتْ فَتُؤَنَّثُ مُراعاةً لِلْمَعْنى إذا أرَدْتَ السُّؤالَ عَنْ مُؤَنَّثٍ، ولا خَبَرَ هُنا فَيُؤَنَّثُ قامَتْ لِأجْلِهِ]{.ar}

    From [البحر المحيط لأبي حيان]{.ar} for the [tafsIr]{.trn2} of [ثُمَّ لَمۡ تَكُن فِتۡنَتُهُمۡ]{.ar} [6:23]:

    > [وأمّا مَن كانَتْ أُمَّكَ، فَإنَّهُ حَمَلَ اسْمَ كانَ عَلى مَعْنى (مَن)؛ لِأنَّ مَن لَها لَفْظٌ مُفْرَدٌ، ولَها مَعْنًى بِحَسَبِ ما تُرِيدُ مِن إفْرادٍ وتَثْنِيَةٍ وجَمْعٍ وتَذْكِيرٍ وتَأْنِيثٍ، ولَيْسَ الحَمْلُ عَلى المَعْنى لِمُراعاةِ الخَبَرِ، ألا تَرى أنَّهُ يَجِيءُ حَيْثُ لا خَبَرَ ؟ نَحْوَ ومِنهم مَن يَسْتَمِعُونَ إلَيْكَ. و(تَكُنْ) مِثْلُ مَن يا ذِئْبُ يَصْطَحِبانِ. ومَن تَقْنُتْ في قِراءَةِ التّاءِ، فَلَيْسَتْ تَأْنِيثُ كانَتْ لِتَأْنِيثِ الخَبَرِ، وإنَّما هو لِلْحَمْلِ عَلى مَعْنى (مَن) حَيْثُ أرَدْتَ بِهِ المُؤَنَّثَ، وكَأنَّكَ قُلْتَ: أيَّةُ امْرَأةٍ كانَتْ أُمَّكَ]{.ar}

If the question is regarding a specific number and gender, then we are more likely to insert the corresponding specific connected noun
([ٱلَّذِي]{.ar}, etc.)
between the question noun [مَن]{.ar} and the verb. 
For example:

[مَنِ اللَّتَانِ تَظَاهَرَتَا عَلَى النَّبِيِّ صلى الله عليه وسلم مِنْ أَزْوَاجِهِ]{.ar}  
"Who are the ones~2f~, from his wives, who aided one another against the Prophet ﷺ ?  
[sunnah.com/bukhari:4913](https://sunnah.com/bukhari:4913)

Note that now the dual feminine doer pronoun in [تَظَاهَرَتَا]{.ar} is the link-back pronoun that matches the connected noun [ٱللَّتَانِ]{.ar}.

## [مَا]{.ar} "What" questions

TODO

## [أَيّ]{.ar} "Which" questions

TODO

## [كَيْفَ]{.ar} "How" questions

TODO

## [أَيْنَ]{.ar} "Where" questions

TODO

## [مَتَىٰ]{.ar} "When" questions

TODO

## Other question words

TODO

## Differentiating question words from their other functions

Many of the question words 
([أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.)
also have other functions.
For example,
in chapter\ \@ref(the-connected-nouns) we learned that [مَنْ]{.ar}, [مَا]{.ar}, and [أَيّ]{.ar} are also connected nouns.
Many of the question nouns can also be used as _conditional nouns_ that we will study in chapter\ \@ref(...), if [#allAh]{.trn2} wills.

In this section, we will discuss briefly how to determine when words like
[أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.
are question words, and when they could have one of their other functions.

The basic principle regarding a question sentence is that it is to be treated as one unit. 
A word from within a question sentence is not, individually, affected by anything outside the question.
Let's try to understand this using an example.

Consider the following sentence:

[ٱِسْأَلْ أَيُّهُمْ قَامَ]{.ar}  
[EisEal Eayyuhum qAm]{.trn}  
"Ask: 'Which of them stood?'"

The speaker is commanding the addressed person to ask a group of people the question: 
"Which of them stood".

The question sentence is
[أَيُّهُمْ قَامَ]{.ar}
[Eayyuhum qAm]{.trn}
"Which of them stood".
This entire sentence is considered the direct doee of the verb of command [ٱسْأَلْ]{.ar} "ask!".
The question noun [أَيُّ]{.ar} [Eayyu]{.trn} is in the u-state because it is the subject of the question sentence.
It does not become [أَيَّ]{.ar} [Eayya]{.trn} in the a-state because it is not, by itself, the direct doee of 
[ٱسْأَلْ]{.ar}.
Rather, as we have just stated, the entire question sentence is the direct doee.
But because the direct doee is a sentence, and not an individual word, it does not indicate its state using, for example, an a-mark [◌َ]{.ar}.

Now, let's modify the example. Consider now this sentence:

[ٱِسْأَلْ أَيَّهُمْ قَامَ]{.ar}  
[EisEal Eayyahum qAm]{.trn}  
Ask the one of them who stood!

Now, the noun [أَيَّ]{.ar} is in the a-state because it (individually) is the direct doee of the verb of command 
[ٱسْأَلْ]{.ar}.
The speaker is now commanding the addressed person to ask (something) of only the person who stood, out of a group of people. The rest of the people are not to be asked.
Because the noun 
[أَيَّ]{.ar}
is individually affected by the preceding verb
[ٱسْأَلْ]{.ar}
it is now not a question noun, and must be one of the other functions that the word
[أَيّ]{.ar} can have.
As a matter of fact, it is here a connected noun, and the sentence following it:
[قَامَ]{.ar} "he stood" is its connector.

The other noteworthy point regarding questions
(besides their being considered one unit)
is that they may only be preceded 
either by a verb of knowledge, (like [عَلِمَ]{.ar}, [دَرىٰ]{.ar}, etc.)
or by an expression indicating that the question is being quoted.
We have already seen an example of the question being quoted in the example:

[ٱِسْأَلْ أَيُّهُمْ قَامَ]{.ar}  
"Ask: 'Which of them stood?'"

An example of a question being preceded by a verb of knowledge is:

[مَا عَلِمْتُ أَذَهَبَ أَمْ مَكَثَ]{.ar}  
I don't know whether he went or stayed.

Here the question sentence is: 
[أَذَهَبَ أَمْ مَكَثَ]{.ar}
"Did he go or did he stay?"

By the way, a question sentence may be part of a bigger question as well. For example:

[أَتَدْرِي أَيُّهُمْ فِي ٱلدَّارِ؟]{.ar}  
[EatadrI Eayyuhum fi -ddAr]{.trn}  
Do you know: which of them is in the house?

Note now the subtle difference in meaning if we change the state of [أَيّ]{.ar} in the above example from the u-state to the a-state:

[أَتَدْرِي أَيَّهُمْ فِي ٱلدَّارِ؟]{.ar}  
[EatadrI Eayyahum fi -ddAr]{.trn}  
Do you know the one of them who is in the house?

When [أَيّ]{.ar} was in the u-state it was a question noun. And the speaker was asking the addressed person if he could figure out who, from among the group of people, was in the house.

When [أَيّ]{.ar} is in the a-state it is now a connected noun.
The connector's link-back pronoun is omitted (as is permissible in this case, see section\ \@ref(...)). With the link-back pronoun restored, the sentence is
[أَتَدْرِي أَيَّهُمْ هُوَ فِي ٱلدَّارِ؟]{.ar}
And the speaker is asking the addressed person if he is familiar with the person who is in the house.
Now he is not asking the addressed person to identify him, but rather if knows him as a person.

This difference is apparent with 
[أَيّ]{.ar} 
because it is a flexible noun whose state is indicated by the vowel mark at its end.
The same occurs in the other question nouns that are also connected nouns:
[مَا]{.ar}, and [مَنْ]{.ar}
but it won't often be as apparent because they are rigid nouns.

As a final note, sometimes, one of the words like 
[أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.
may be preceded by parts of a sentence that are neither quoting, nor a verb of knowledge.
Here we can be sure that the word is not a question word
and
must be one of its other functions. However,
it still may not be easy to figure out what that other function is.
Nevertheless, the meaning of the sentence can still usually be gleaned.
For example:

[فَلْتَدْخُلْ مِنْ أَيِّ أَبْوَابِ الْجَنَّةِ شَاءَتْ]{.ar}  
"then let her enter from whichever of the doors of paradise she wishes."[^question-vs-other-functions]

[^question-vs-other-functions]: Distinguishing question words from their other functions is often not straightforward. Consider the example:

    [أَتَدْرِي أَيَّ كِتَابٍ قَرَأَ؟]{.ar}  
    Do you know which book he read?
    
    [أَيّ]{.ar} is a question noun in the a-state because it is the direct doee of the verb [قَرَأَ]{.ar}. It can't be a connected noun because [أَيَّ كِتَابٍ]{.ar} is indefinite and connected nouns are always considered definite.

    See also these excerpts:

    From the [tafsIr]{.trn2} of [وَإِذَا مَآ أُنزِلَتْ سُورَةٌ فَمِنْهُمْ مَّن يَقُولُ أَيُّكُمْ زَادَتْهُ هَـٰذِهِ إِيمَاناً]{.ar} [9:124] from [تفسير الآلوسي]{.ar}:

    > [وقرأ عبيد بن عمير {أَيُّكُمْ} بالنصب على تقدير فعل يفسره المذكور ويقدر مؤخرًا لأن الاستفهام له الصدر أي أيكم زادت زادته الخ.]{.ar}

    From the [tafsIr]{.trn2} of [ثُمَّ لَنَنزِعَنَّ مِن كُلِّ شِيعَةٍ أَيُّهُمْ أَشَدُّ عَلَى ٱلرَّحْمَـٰنِ عِتِيّاً]{.ar} [9:124] from [بداىع الفوائد لابن القيم]{.ar}:

    > [و ﴿أيُّهم أشَدُّ﴾ للنحاة فيه أقوال:]{.ar}
    >
    > [أحدها: قول الخليل أنه مبتدأ وأشد خبره ولم يعمل لننزعن فيه لأنه محكي والتقدير الذي يقال فيه: ﴿أيُّهم أشَدُّ عَلى الرَّحْمَنِ عِتِيًّا﴾ وعلى هذا فـ (أي) استفهامية.]{.ar}
    >
    > [الثاني: قول يونس أنه رفع على جهة التعليق للفعل السابق كما لو قلت علمت أنه أخوك فعلق الفعل عن الفعل كما تعلق أفعال القلوب.]{.ar}
    >
    > [الثالث: قول سيبويه إن (أي) هنا موصولة مبنية على الضم والمسوغ لبنائها حذف صدر صلتها، وعنده أصل الكلام أيهم هو أشد فلما حذف صدر الصلة بنيت على الضم تشبيها لها بالغايات التي قد حذفت مضافاتها ك قبل وبعد وعلى كل واحد من الأقوال إشكالات نذكرها ثم نبين الصحيح إن شاء الله.]{.ar}
    >
    > [فأما قول الخليل: فقيل يلزمه ستة أمور:]{.ar}
    >
    > [الأول حذف الموصوف.]{.ar}
    >
    > [الثاني: حذف الصلة.]{.ar}
    >
    > [الثالث: حذف العائد لأن تقديره الذي يقال لهم إنهم أشد وهذا لا عهد لنا فيه باللغة.]{.ar}
    >
    > [وأما ما يحذف من القول فإنه إنما يكون قولا مجردا عن كونه صلة لموصول نحو قوله: ﴿والمَلائِكَةُ باسِطُو أيْدِيهِمْ أخْرِجُوا أنْفُسَكُمُ﴾ أي يقولون أو قائلين ومثله: ﴿والَّذِينَ اتَّخَذُوا مِن دُونِهِ أوْلِياءَ ما نَعْبُدُهم إلاّ لِيُقَرِّبُونا إلى اللَّهِ زُلْفى﴾]{.ar}
    >
    > [الرابع: أنه إذا قدر المحذوف هكذا لم يستقم الكلام فإنه يصير ﴿لَنَنْزِعَنَّ مِن كُلِّ شِيعَةٍ﴾ الذين يقال فيهم ﴿أيُّهم أشَدُّ﴾]{.ar}
    >
    > [وهذا فاسد فإن ذلك المنزوع لا يقال فيه: ﴿أيُّهم أشَدُّ﴾ بل هو نفسه أشد أو من أشد الشيعة على الرحمن فلا يقع عليه الاستفهام بعد نزعه فتأمله.]{.ar}
    >
    > [الخامس: أن الاستفهام لا يقع إلا بعد أفعال العلم والقول على الحكاية ولا يقع بعد غيره من الأفعال تقول علمت أزيد عندك أم عمرو ولو قلت ضربت أزيد أم عمرو لم يجز وننزعن ليس من أفعال العلم]{.ar}
    >
    > [فإذا قلت: ضربت أيهم قام. لم تكن إلا موصولة ولا يصح أن يقال ضربت الذي يقال فيه أيهم قام، وإنما توهم مثل ذلك لكون اللفظ صالحا لجهة أخرى مستقيمة فيتوهم متوهم أن حمله على الجهة الأخرى يستقيم والذي يدل عليه أنه لو قدرت موضعه استفهاما صريحا ليس له جهة أخرى لم يجز]{.ar}
    >
    > [فإذا قلت: ضرب أزيد عندك أم عمرو. لم يجز بخلاف ضرب أيهم عندك.]{.ar}
    >
    > [فلو كان أيهم استفهاما لجاز الكلام مع الاستفهام الذي بمعناهما وإنما لم يقع الاستفهام إلا بعد أفعال العلم والقول أما القول فلأنه يحكي به كل جملة خبرية كانت أو إنشائية، وأما أفعال العلم فإنما وقع بعدها الاستفهام لكون الاستفهام مستعلما به فكأنك إذا قلت: أزيد عندك أم عمرو كان معناه أعلمني، وإذا قلت: علمت أزيد عندك أم عمرو.]{.ar}
    >
    > [كان معناه علمت ما يطلب استعلامه فلهذا صح وقوع الاستفهام بعد العلم لأنه استعلام ثم حمل الحسبان والظن عليهما لكونهما من بابه ووجه آخر وهو كثرة استعمال أفعال العلم فجعل شأن ليس لغيرها.]{.ar}
    >
    > [السادس: أن هذا الحذف الذي قدره في الآية حذف لا يدل عليه سياق فهو مجهول الوضع وكل حذف كان بهذه المنزلة كان تقديره من باب علم الغيب وأما قول يونس بن حبيب فإشكاله ظاهر فإن التعليق إنما يكون في أفعال القلوب نحو العلم والظن والحسبان دون غيرها.]{.ar}
    >
    > [ولا يجوز أن تقول ضربت أيهم قام على أن تكون (أيهم) استفهاما وقد علق الفعل عن العمل فيه وأما قول سيبويه فإشكاله أنه بناء خارج عن النظائر ولم يوجد في اللغة شاهد له قال السهيلي ما ذكره سيبويه لو استشهد عليه بشاهد من نظم أو نثر أو وجدنا بعده في كلام فصيح شاهدا له لم نعدل به قولا ولا رأينا لغيره عنه طولا ولكنا لم نجز ما بين لمخالفته غيره لا سيما مثل هذه المخالفة فإنا لا نسلم أنه حذف من الكلام شيء وإن قال: إنه حذف ولا بد والتقدير أيهم هو أخوك فيقال: لم يبنوا في النكرة فيقولون مررت برجل أخوك أو رأيت رجلا أبوك أي هو أخوك وأبوك ولم خصوا أيا هذا دون سائر الأسماء أن يحذف من صلته ثم يبنى للحذف ومتى وجدنا شيئا من الجملة يحذف ثم يبنى الموصوف بالجملة من أجل ذلك الحذف وذلك الحذف لا نجعله متضمنا لمعنى الحرف ولا مضارعا له وهذه علة البناء وقد عدمت في أي قال والمختار قول الخليل ولكنه يحتاج إلى شرح وذلك أنه لم يرد بالحكاية ما يسبق إلى الفهم من تقدير معنى القول ولكنه أراد حكاية لفظ الاستفهام الذي هو أصل في أي كما يحكيه بعد العلم إذا قلت قد علمت من أخوك وأقام زيد أم قعد فقد تركت الكلام على حاله قبل دخول الفعل لبقاء معنى الاختصاص والتعيين في أي الذي كان موجودا فيها وهي استفهام لأن ذلك المعنى هو الذي وضعت له استفهاما كانت أو خبرا كما حكوا لفظ النداء في قولهم اللهم اغفر لي أيها الرجل وارحمنا أيتها العصابة فنحكي لفظ هذا إشعارا بالتعيين والاختصاص الموجود في حال النداء لوجود معنى الاختصاص والتعيين فيه قال وقول يونس: إن الفعل ملغي حق وإن لم يكن من أفعال القلب وعلة إلغائه ما قدمناه من حكاية لفظ الاستفهام للاختصاص فإذا أتممت العلة وقلت ضربت أيهم أخوك. زالت مضارعة الاستفهام وغلب فيه معنى الخبر لوجود الصلة التامة بعده]{.ar}
    >
    > [قال وأما قوله تعالى: ﴿وَسَيَعْلَمُ الَّذِينَ ظَلَمُوا أيَّ مُنْقَلَبٍ يَنْقَلِبُونَ﴾ وإجماعهم على أنها منصوبة بـ ﴿ينقلبون﴾ لا بـ ﴿سيعلم﴾ وقد كان يتصور فيها أن تكون منصوبة بـ سيعلم على جهة الاستفهام ولكن تكون موصولة والجملة صلتها والعائد محذوف ولكن منع من هذا أصل أصلناه ودليل أقمناه على أن الاسم الموصول إذا عني به المصدر ووصل بفعل مشتق من ذلك المصدر لم يجز لعدم الفائدة المطلوبة من الصلة وهي إيضاح الموصول وتبيينه والمصدر لا يوضح فعله المشتق من لفظه لأنه كأنه هو لفظا ومعنى إلا في المختلف الأنواع كما تقدم قال ووجه آخر أقوى من هذا وهو أن أيا لا تكون بمعنى الذي حتى تضاف إلى معرفة فتقول لقيت أيهم في الدار إذ من المحال أن يكون بمعنى الذي وهو نكرة والذي لا ينكر وهذا أصل يبنى عليه في (أي).]{.ar}

    From [معانى القآن للفراء]{.ar} for the [tafsIr]{.trn2} of [2:69]:

    > [فأعملْ في " ما " " وأي " الفعلَ الذي بعدَهما، ولا تُعمِل الذي قبلهما إذا كان مُشتقّاً من العِلْم ؛ كقولك : ما أعلم أَيُّهم قال ذاك، ولا أعلمنّ أَيُّهم قال ذاك، وما أدرِى أَيَّهم ضربت، فهو في العِلِم والإخبار والإنْباء وما أشبهها على ما وصفتُ لك. منه قول الله تبارك وتعالى :﴿ وَما أَدْرَاكَ ماهِيَهْ ﴾ ﴿ وَما أَدْرَاكَ ما يَوْمُ الدَّينِ ﴾ " ما " الثانية رفعٌ، فرفعتَها بيوم ؛ كقولك : ما أدراك أي شيء يومُ الدّين، وكذلك قول الله تبارك وتعالى :﴿ لِنَعْلَمَ أي الْحِزْبَيْنِ أَحْصَى ﴾ رفعتَه بأَحْصَى، وتقول إذا كان الفعل واقعا على أي : ما أدرى أَيَّهم ضربت. وإنما امتنعت من أن تُوقع على أي الفعل الذي قبلها من العلم وأشباهه ؛ لأنك تجِدُ الفعلَ غيرَ واقع على أي في المعنى ؛ ألا ترى أنك إذا قلت : اذْهَبْ فاعلم أيُّهما قام أنك تسأل غيرهما عن حالهما فتجد الفعل واقعا على الذي أعلمك، كما أنك تقول : سل أيُّهُمْ قام، والمعنى : سل الناس أيُّهُمْ قام. ولو أوقعت الفعل على " أي " فقلت : اسأل أيَّهُمْ قام لكنت كأنك تضمر أيّاً مرّة أخرى ؛ لأنك تقول : سل زيدا أيُّهُمْ قام، فإذا أوقعت الفعل على زيد فقد جاءت " أي " بعده. فكذلك " أي " إذا أوقعت عليها الفعل خرجت من معنى الاستفهام، وذلك إن أردته، جائز، تقول : لأضْرِبَنَّ أيَّهُم يقول ذاك ؛ لأنّ الضرب لا يقع على [ اسم ثم يأتي بعد ذلك استفهام، وذلك لأن الضرب لا يقع على ] اثنين، وأنتَ تقول في المسألة : سل عبد الله عن كذا، كأنك قلت : سله عن كذا، ولا يجوز ضربت عبد الله كذا وكذا إلا أن تريد صفة الضرب، فأما الأسماء فلا. وقول الله :﴿ ثُمَّ لَنَنْزِعَنّ مِنْ كُلِّ شِيعةٍ أيُّهُم أشَدُّ على الرّحْمَنِ عِتيّاً ﴾ من نصب أيّاً أوقع عليها النزع وليس باستفهام، كأنه قال : ثم لنستخرجن العاتيَ الذي هو أشد. وفيها وجهان من الرفع ؛ أحدهما أن تجعل الفعل مكتفيا بِمن في الوقوع عليها، كما تقول : قد قتلنا من كل قوم، وأصبنا من كل طعام، ثم تستأنف أيّاً فترفعها بالذي بعدها، كما قال جلّ وعزّ :﴿ يَبْتَغُونَ إلى رَبِّهِمُ الْوَسِيلَةَ أيُّهُمْ أَقْرَبُ ﴾ أي ينظرون أيُّهُم أقرب. ومثله ﴿ يُلْقُونَ أقْلاَمَهُمْ أَيُّهُمْ يَكْفُلُ مَرْيَمَ ﴾. وأما الوجه، الآخر فإن في قوله تعالى :﴿ ثم لَنَنْزِعَنّ مِنْ كلِّ شِيعَةٍ ﴾ لننزعن من الذين تشايعوا على هذا، ينظرون بالتشايع أيهم أشدّ وأخبث، وأيهم أشدّ على الرحمن عِتيّاً، والشيعة ويتشايعون سواء في المعنى. وفيه وجه ثالث من الرفع أن تجعل ﴿ ثُمّ لَننْزِعَنَّ مِنْ كُلِّ شِيعَةٍ ﴾ بالنداء ؛ أي لننادين ﴿ أيُّهُمْ أشدُّ على الرّحْمانِ عِتيّاً ﴾ وليس هذا الوجه يريدون. ومثله مما تعرفه به قوله :﴿ أفَلَمْ يَيْأَسِ الَّذِيِنَ آمنَوُا أَنْ لَوْ يشاء اللَّهُ لهَدَى الناس جَميعاً ﴾ فقال بعض المفسرين ﴿ أَفَلَمْ يَيْأَسِ الَّذِينَ آمَنُوا ﴾ : ألم يعلم، والمعنى - والله أعلم - أفلم ييأسوا علما بأن الله لو شاء لهدى الناس جميعا. وكذلك " لَنَنْزِعَنّ " يقول يريد ننزعهم بالنداء.]{.ar}
 
