# Subject-information sentences

## Introduction

In this chapter we will learn about a class of sentences called _subject-information sentences._ 
Subject-information sentences consist of two parts:

i. The _subject_. This is the topic of the sentence.
ii. The _information_. This gives us some information about the subject.

## Forming subject-information sentences

Here is a subject-information sentence:

"The building is a house."

The subject of the sentence is "the building". This means that the sentence is about "the building". 

The information is "a house". This means that the information that the sentence is giving us about the subject is that it is "a house".

Let's try to form this sentence in Arabic.

First we assemble the individual parts:

i. "The building" in Arabic is [ٱَلْبِنَاء]{.ar} [EalbinAE]{.trn} (masc.).
ii. "A house" is [بَيْت]{.ar} [bayt]{.trn} (masc.).

Next we put them both in the u-state. For subject-information sentences, both the subject and the information shall be in the u-state. Remember that the u-state is formed by putting an [un]{.trn}-mark [◌ٌ]{.ar} at the end of an indefinite noun, and a [u]{.trn}-mark [◌ُ]{.ar} at the end of a definite noun. Here are the two nouns in the u-state:

i. [ٱَلْبِنَاءُ]{.ar} [EalbinAEu]{.trn} (masc.) "the building" (u-state)
ii. [بَيْتٌ]{.ar} [baytun]{.trn} (masc.) "a house" (u-state)

In order to form this sentence in Arabic, we put the subject first and then the information. So we get:

[ٱَلْبِنَاءُ بَيْتٌ.]{.ar}  
[EalbinAEu bayt.]{.trn}  
"The building is a house."

But wait! Where is the Arabic word for "is"? It turns out that Arabic does not usually express any word for "is". Instead, the meaning of this word is implied.

Also, not that the final vowel mark at the end of the sentence is written but not pronounced. So we will write 
[بَيْتٌ]{.ar} but say
[bayt]{.trn}, not
[baytun]{.trn}.
This is in accordance with what we learned in section\ \@ref(pronouncing-the-end-of-a-sentence).

Now let's try reversing this sentence, and try making the sentence:

"The house is a building."

We follow the same procedure by assembling the individual parts of the sentence and putting them in the u-state:

i.  The subject: [ٱَلْبَيْتُ]{.ar} [Ealbaytu]{.trn} (masc.) "the house" (u-state)
ii. The information: [بِنَاءٌ]{.ar} [binAEun]{.trn} (masc.) "a building" (u-state)

And then we put them together, first the subject and then the information:

[ٱَلْبَيْتُ بِنَاءٌ.]{.ar}  
[Ealbaytu binAE.]{.trn}  
"The house is a building."

and there we have our sentence.

## Matching the gender between the subject and the information

In the sentences above, both the subject and the information were masculine nouns. Now let's try forming a sentence where the subject and the information have different genders. Let's try saying:

"The building is a school."

i.   The subject: [ٱَلْبِنَاءُ]{.ar} [EalbinAEu]{.trn} (masc.) "the building" (u-state)
ii.  The information: [مَدْرَسَةٌ]{.ar} [madrasatun]{.trn} (fem.) "a school" (u-state)

In the same manner as before, we form the sentence by first writing the subject and then the information:

[ٱَلْبِنَاءُ مَدْرَسَةٌ.]{.ar}  
[EalbinAEu madrasah.]{.trn}  
"The building is a school."

We can also reverse this sentence:

[ٱَلْمَدْرَسَةُ بِنَاءٌ.]{.ar}  
[Ealmadrasatu binAE.]{.trn}  
"The school is a building ."

So we see that it is quite normal to have a sentence where the gender of the subject does not match the gender of the information. 
<!--And we made no attempt to try change their gender by genderizing one of them to match the gender of the other. This is because both words
[ٱَلْبِنَاء]{.ar} [EalbinAE]{.trn} (masc.) "a building"
and
[مَدْرَسَة]{.ar} [madrasah]{.trn} (fem.) "a school"
are non-genderizable words.

If either the subject or the information is a genderizable noun, the in this case the subject and the information are made to match each other in gender. For example, let's try to form the sentence:
-->
This is because the words we have dealt with so far denote animate objects.
If either the subject or the information denote animate beings, then in this case the subject and the information often do match each other in gender. For example, let's try to form the sentence:

"The mother is a teacher."

Here are the indiviual words that we will use to form the sentence:

i.  The subject: "the mother": [ٱَلْأُمُّ]{.ar} [EalEummu]{.trn} (fem.) (u-state).
ii. The information: "a teacher". We have two words for "a teacher" in Arabic: 

    + [مُعَلِّم]{.ar} [mueallium]{.trn} (masc.) "a (male) teacher"
    + [مُعَلِّمَة]{.ar} [mueallimah]{.trn} (fem.) "a (female) teacher". 

    Obviously, [مُعَلِّمَة]{.ar} [mueallimah]{.trn} would apply here so we put it in the u-state: [مُعَلِّمَةٌ]{.ar} [mueallimatun]{.trn}
(u-state).

Now we can assemble the sentence:

[ٱَلْأُمُّ مُعَلِّمَةٌ.]{.ar}  
[EalEummu mueallimah.]{.trn}  
"The mother is a teacher~f~."

In the reverse sentence "The teacher is a mother.", we again use the feminine noun
[مُعَلِّمَة]{.ar} [mueallimah]{.trn} (fem.) "a (female) teacher",
which is now the subject of the sentence, to match the feminine noun in the information 
[ٱَلْأُمّ]{.ar} [Ealumm]{.trn} (fem.)
"a mother". So we get:

[ٱَلْمُعَلِّمَةُ أُمٌّ.]{.ar}  
[Ealmueallimatu Eumm.]{.trn}  
"The teacher~f~ is a mother."

<!--If the subject and the information apply to animate beings, then even if they are not genderizable, they will usually match each other in gender in order for the sentence to be meaningful. For example:-->
Here is another example:

[ٱَلرَّجُلُ أَبٌ.]{.ar}  
[Earrujulu Eab.]{.trn}  
"The man is a father."

<!--
In the above sentence, both the subject
[ٱَلرَّجُل]{.ar}
[Earrujul]{.trn}
(masc.) "the man"
and the information
[أَب]{.ar}
[Eab]{.trn}
(masc.) "a father" are non-genderizable nouns. But they match each other in gender because that is the only way for the sentence to be meaningful.

But if one of the non-genderizable nouns can be applied to both physical genders then the subject and information may mismatch in gender. For example, the noun [شَخْص]{.ar} [caxS]{.trn} "a person" is a masculine noun that is applied to both male and female persons. So if the person being referred to is a woman, for example, then we can get an apparent mismatch in gender between the grammatical gender of the subject and the grammatical subject of the information. Example:
-->
Now, let's try a sentence where we are still dealing with animate beings but the nouns mismatches in grammatical gender.

[ٱَلْأُمُّ شَخْصٌ.]{.ar}  
[EalEummu caxS.]{.trn}  
"The mother is a person."

[ٱَلشَّخْصُ مُعَلِّمَةٌ.]{.ar}  
[EaccaxSu mueallimah.]{.trn}  
"The person is a (female) teacher."

[ٱَلْمُعَلِّمَةُ شَخْصٌ.]{.ar}  
[Ealmueallimatu caxS.]{.trn}  
"The (female) teacher is a person."

In the above examples, the grammatical genders mismatch between the subject and the information. But this is because we are matching with the physical gender of the person represented by the masculine noun [شَخْص]{.ar} [caxS]{.trn} "a person", not its grammatical gender.

The same effect is seen when using the word [حَيَوان]{.ar} [HayawAn]{.trn} which is a masculine noun meaning "an animal". It can be applied to both male and female animals. So we can say:

[ٱَلْحَيَوَانُ هِرٌّ.]{.ar}  
[EalHayawAnu hirr.]{.trn}  
"The animal is a (male) cat."

and

[ٱَلْحَيَوَانُ هِرَّةٌ.]{.ar}  
[EalHayawAnu hirrah.]{.trn}  
"The animal is a (female) cat."

<!--
We assemble the individual parts of the sentence in the u-state:
and "a building" is [بِنَاءٌ]{.ar} [binAEun]{.trn}. In order to say "The house is a building" we put the [subject]{.syn} first and put its [information]{.syn} after it. Both the [subject]{.syn} and the [information]{.syn} are put in the u-state.

This kind of sentence is called a [subject-information]{.syn} sentence. It consists of two parts:

1. The part before "is": "the house". This is who the sentence is about. We call this the [subject]{.syn} of the sentence.
2. The part after "is": "a building". This is telling us some information about the [subject]{.syn}. We call this the [information]{.syn}.

Arabic does not normally express the word "is". In order to express this sentence in Arabic we put the [subject]{.syn} first and then the [information]{.syn}. For these simple sentences the [subject]{.syn} and the [information]{.syn} will be in the u-state.

"The house" is [ٱَلْبَيْتُ]{.ar} [albaytu]{.trn} and "a building" is [بِنَاءٌ]{.ar} [binAEun]{.trn}. In order to say "The house is a building" we put the [subject]{.syn} first and put its [information]{.syn} after it. Both the [subject]{.syn} and the [information]{.syn} are put in the u-state.

[ٱَلْبَيْتُ بِنَاءٌ.]{.ar}  
[Ealbaytu binAEun.]{.trn}  
"The house is a building."

Now let's try saying "The man is a teacher."

"The man" is [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn}. For "a teacher" we have two words in Arabic: 

+ [مُعَلِّمٌ]{.ar} [mueallimun]{.trn} "a male teacher" 
+ [مُعَلِّمَةٌ]{.ar} [mueallimun]{.trn} "a female teacher" 

Obviously "the man" can only be [مُعَلِّمٌ]{.ar} [mueallimun]{.trn} "a male teacher". So the sentence is:

[ٱَلرَّجُلُ مُعَلِّمٌ.]{.ar}  
[Earrajulu mueallimun.]{.trn}  
"The man is a (male) teacher."

Let's try another example: "The animal is a cat."

"The animal" is [حَيَوَانٌ]{.ar} [HayawAnun]{.trn}. For "a cat" we have two words:

+ [هِرٌّ]{.ar} [hirrun]{.trn} "a male cat"
+ [هِرَّةٌ]{.ar} [hirratun]{.trn} "a female cat"

Usually, in Arabic [هِرَّةٌ]{.ar} [hirratun]{.trn} "a female cat" is used for "a cat" if the animal's gender is not specified, or not important. So putting together the sentence we get:

[ٱَلْحَيَوَانُ هِرَّةٌ.]{.ar}  
[EalHayawAnu hirratun.]{.trn}  
"The animal is a cat."

Note that, in this sentence, the [subject]{.syn} [ٱَلْحَيَوَانُ]{.ar} [alHayawAnu]{.trn} "the animal" is a masculine noun. And the [information]{.syn} 
[هِرَّةٌ]{.ar} [hirratun]{.trn} "a cat" is a feminine noun. So the [subject]{.syn} and the [information]{.syn} do not match in gender. This is perfectly normal. We make the [information]{.syn} match the [subject]{.syn} in gender only if:

1. There are separate words for the masculine and feminine nouns for the [information]{.syn}, and
2. Only one of the two words can be correctly applied to the [subject]{.syn}.

In this case there were separate words for the masculine and feminine nouns for the [information]{.syn}:

+ [هِرٌّ]{.ar} [hirrun]{.trn} "a male cat"
+ [هِرَّةٌ]{.ar} [hirratun]{.trn} "a female cat"

but both of these can be applied to the [subject]{.syn}, because the [subject]{.syn} [ٱَلْحَيَوَانُ]{.ar} [alHayawAnu]{.trn} (masc.) "the animal" is used for both male and female animals. [هِرَّةٌ]{.ar} [hirratun]{.trn} is chosen because it is commonly used for "a cat" as we have already explained.

We have already seen an example of matching the gender of the [information]{.syn} with the [subject]{.syn} in the example:

[ٱَلرَّجُلُ مُعَلِّمٌ.]{.ar}  
[Earrajulu mueallimun.]{.trn}  
"The man is a (male) teacher."
-->

## Detached pronouns

Pronouns, in Arabic, are special nouns that can be used in place of other nouns when it is known who is being referred to. They include words like "he", "she", "it", "you", "I", etc. So you can have a sentence with a noun subject, like:

"The man is a teacher."

Or you can replace the noun "man" with the pronoun "he":

"He is a teacher."

In Arabic there are a few different kinds of pronouns. Here we will learn _detached pronouns_. They are called detached pronouns because they are detached from other words. There are another set of pronouns called _attached pronouns_ that we will learn later, if [#allAh]{.trn2} wills.

When talking about pronouns, it is beneficial to make use of a concept of grammar called _participants_.

In any kind of speech there are there can be up to three types of _participants_ involved. A participant may consist of one individual, or more than one individuals.  The three participants in speech are:

1. The _I/we-participant_. This is the participant who is speaking. When the participant who is speaking refers to himself or herself (or themselves if plural) then he/she/they use the pronouns "I", "me", "we", and "us" in English. We will call this the _I/we-participant_.
2. The _you-participant_. This is the participant whom the speaking-participant is directly speaking to. When the speaking-participant refers to the participant he is speaking to, he uses the "you" pronoun in English. We will call this the _you-participant_.
3. The _they-participant_. This is the participant who is not being directly spoken to. Their only participation in the speech is that they are being referred to. When the speaking-participant refers to them in English, the pronouns used for this participant are "he", "him", "she", "her", "it", "they", and "them". For convenience, we will call this participant the _they-participant_ (even though the participant may be singular).

We will now learn the pronouns for these participants in Arabic, if [#allAh]{.trn2} wills. We will start with the pronouns for the singular participants.

### Detached pronouns for the they-participant

Here are the Arabic detached pronouns for the singular they-participant:

+ They~1m~-participant: [هُوَ]{.ar} [huwa]{.trn} "he".
+ They~1f~-participant: [هِيَ]{.ar} [hiya]{.trn} "she".

Here are some examples of pair of sentences, each first with a noun, and then with a pronoun in place of the noun:

+ [ٱَلرَّجُلُ مُعَلِّمٌ.]{.ar}  
  [Earrajulu mueallim.]{.trn}  
  "The man is a teacher~m~."
  
  [هُوَ مُعَلِّمٌ.]{.ar}  
  [huwa mueallim.]{.trn}  
  "He is a (male) teacher~m~."

+ [ٱَلْجَارِيَةُ طَالِبَةٌ.]{.ar}  
  [EaljAriyatu Talibah.]{.trn}  
  "The girl is a student~f~."

+ [هِيَ طَالِبَةٌ.]{.ar}  
  [hiya Talibah.]{.trn}  
  "She is a student~f~."

+ [ٱَلْبَيْتُ بِنَاءٌ.]{.ar}  
  [Ealbaytu binAE.]{.trn}  
  "The house is a building."

  [هُوَ بِنَاءٌ.]{.ar}  
  [huwa binAE.]{.trn}  
  "It is a building."

  Note that Arabic uses the pronoun [هُوَ]{.ar} [huwa]{.trn} "he" to refer to the inanimate object "the house". This is because, as we know, all nouns in Arabic are either masculine or feminine. In translating the sentence to English we will employ the neutral pronoun "it" to make the sentence sound natural.

+ [ٱَلْبِنَاءُ مَدْرَسَةٌ.]{.ar}  
  [EalbinAEu madrasah.]{.trn}  
  "The building is a school."

  [هُوَ مَدْرَسَةٌ.]{.ar}
  [huwa madrasah.]{.trn}  
  or  
  [هِيَ مَدْرَسَةٌ.]{.ar}
  [hiya madrasah.]{.trn}  
  "It is a school."

  Note that either [هُوَ]{.ar} [huwa]{.trn} "he" or [هِيَ]{.ar} [hiya]{.trn} "she" can be used in the above sentence because the gender of the subject [ٱَلْبِنَاء]{.ar} [EalbinAE]{.trn} (masc.) "the building" mismatches the gender of the information [مَدْرَسَة]{.ar} [madrasah]{.trn} (fem.) "a school.".

  In such cases where the genders of the subject and the information do not match, then, generally speaking, the pronoun for either gender could be employed with the following guideline:

  Prefer to match the gender of the subject pronoun with the gender of the information, unless the noun being replaced with a pronoun is an animate being, in which case prefer to use the gender of the animate being. 

  So in the above sentence we will prefer to use [هِيَ مَدْرَسَةٌ.]{.ar} [hiya madrasah.]{.trn} because the information [مَدْرَسَةٌ]{.ar} [madrasatun]{.trn} "a school" is feminine.

+ Here is an example with an animate being as the subject:

  [ٱَلْجَارِيَةُ إِنْسَانٌ.]{.ar}  
  [EaljAriyatu InsAn.]{.trn}  
  "The girl is a human."

  [هِيَ إِنْسَانٌ.]{.ar}  
  [hiya InsAn.]{.trn}  
  "She is a human."

  Here, if we replace the noun [ٱَلْجَارِيَة]{.ar} [EaljAriyah]{.trn} "the girl" with a pronoun, we will prefer to use [هِيَ]{.ar} [hiya]{.trn} "she", because the girl is an animate being, even though the information [إِنْسَانٌ]{.ar} [EinsAnun]{.trn} "a human" is masculine.

### Detached pronouns for the you-participant and the I/we-participant

Here are the pronouns for the singular you-participant and speaking-participant:

+ You~1m~-participant (masc.): [أَنْتَ]{.ar} [Eanta]{.trn} "you~m~".
+ You~1f~-participant (fem.): [أَنْتِ]{.ar} [Eanti]{.trn} "you~f~".
+ I/we~1~-participant (masc. & fem.): [أَنَا]{.ar} [Eana]{.trn} "I". 

Note that the you-participant pronoun "you" has separate pronouns for the masculine and the feminine while the speaking-participant pronoun "I" has the same pronoun for both genders. Examples with these pronouns:

+ [أَنْتَ مُعَلِّمٌ.]{.ar}  
  [Eanta mueallim.]{.trn}  
  "You~m~ are a teacher~m~."

+ [أَنْتِ مُعَلِّمَةٌ.]{.ar}  
  [Eanti mueallimah.]{.trn}  
  "You~f~ are a teacher~f~."

+ [أَنَا مُعَلِّمٌ.]{.ar}  
  [Eana mueallim.]{.trn}  
  "I am a teacher~m~."

+ [أَنَا مُعَلِّمَة.]{.ar}  
  [Eana mueallimah.]{.trn}  
  "I am a teacher~f~."

## Flexible and rigid nouns

All the nouns that we've come across so far (except the pronouns we just learned about above) are a category of nouns called _flexible_ nouns. They are called flexible, because their ending will change depending on their state. Even though we've only used nouns in the u-state so far, we have learned in section \@ref(state), the state of a noun determines the vowel mark on their final letter. The table of states is reproduced here for convenience.

State         | Indefinite "a book" | Definite "the book"
:-------------|:-----------------|:--------------
u-state       |[كِتَابٌ]{.ar} [kitAbun]{.trn}  |[ٱَلْكِتَابُ]{.ar} [alkitAbu]{.trn} 
a-state       |[كِتَابًا]{.ar} [kitAban]{.trn} |[ٱَلْكِتَابَ]{.ar} [alkitAba]{.trn} 
i-state       |[كِتَابٍ]{.ar} [kitAbin]{.trn}  |[ٱَلْكِتَابِ]{.ar} [alkitAbi]{.trn} 

Because, as we said, their ending changes based on their state, they are called flexible nouns.

As opposed to flexible nouns, there are some nouns whose ending is not determined by their state. They can appear the same no matter if they are in the u-state, a-state, or i-state. We will call them _rigid_ nouns. Pronouns are rigid nouns.

## A definite noun as the information {#chap-smp-sent-sec-def-info}

In all the examples so far, the information has been an indefinite noun: "a building", "a teacher", "a cat", etc. It is also possible for the information to be a definite noun:

[ٱَلرَّجُلُ ٱلْمُعَلِّمُ.]{.ar}  
[Earrajulu -lmueallim.]{.trn}  
"The man is the teacher~m~."

<!-- ضمير الفصل is not a copula. It may even have no i3raab depending on one opinion of the grammarians. -->

The above sentence, although correct, is ambiguous. It can also be interpreted as a noun-phrase, meaning "the teacher-man", instead of the complete sentence "The man is the teacher~m~." Therefore, in order to disambiguate and make it clear that we mean the complete sentence, a _disambiguating pronoun_ is usually (not not always) inserted between the subject and the information.
Disambiguating pronouns are detached pronouns that match the subject of the sentence in gender. With a disambiguating pronoun, the sentence above becomes:

[ٱَلرَّجُلُ هُوَ ٱلْمُعَلِّمُ.]{.ar}  
[Earrajulu  huwa -lmueallim.]{.trn}  
"The man is the teacher~m~."

The disambiguating pronoun here is [هُوَ]{.ar} [huwa]{.trn} and is not translated. Here are some more examples of sentences with definite informations and disambiguating pronouns.

[ٱَلْبَيْتُ هُوَ ٱلْبِنَاءُ.]{.ar}  
[Ealbaytu -lbinAEu.]{.trn}  
"The house is the building."

[ٱَلْحَيَوَانُ هِيَ ٱلْهِرَّةُ.]{.ar}  
[EalHayawAnu hiya -lhirratu.]{.trn}  
"The animal is the cat."

## An indefinite noun as the subject

How about making the subject an indefinite noun? Can we say:

+ A house is a building.
+ A man is the teacher.

It turns out that sentences where the subject is an indefinite noun are not as straightforward to express in Arabic. We will explore some ways of expressing them later if [#allAh]{.trn2} wills.

## The word "and"

Arabic uses [وَ]{.ar} [wa]{.trn} to mean "and". It is written right next to the word after it without any space between it and the next word. 

[وَمَدْرَسَةٌ]{.ar}  
[wa madrasatun]{.trn}  
"and a school"

[وَ]{.ar} [wa]{.trn} meaning "and" does not change the state of the noun following it. Examples:

[ٱَلْبِنَاءُ بَيْتٌ وَمَدْرَسَةٌ.]{.ar}  
[EalbinAEu baytun wa madrasatun]{.trn}  
"The building is a house and a school."

[أَخَذَ ٱلرَّجُلُ كِتَابًا وَقَلَمًا.]{.ar}  
[Eaxapa -rrajulu kitAban waqalaman]{.trn}  
"The man took a book and pen."

[دَخَلَتِ ٱلْمَرْأَةُ وَٱلْجَارِيَةُ ٱلْبَيْتَ.]{.ar}  
[daxalati -lmarEatu wa-ljAriyatu -lbayta]{.trn}  
"The woman and the girl entered the house."

We can also use [وَ]{.ar} to connect sentences:

[ٱلرَّجُلُ إِنْسَانٌ وَٱلْكَلْبُ حَيَوَانٌ]{.ar}  
[Earrujulu EinSAnun wa-lkalbu HayawAnun]{.trn}  
"The man is a human and the dog is an animal."

