# Sound plurals

## Introduction

Arabic uses the plural for nouns in number three and higher. The formation and use of plurals in Arabic can be somewhat complicated. One of these complications is that, in using plurals, Arabic distinguishes between intelligent beings and non-intelligent beings. Intelligent beings are those living beings that are endowed with reason like humans, angels, and jinn. Non-intelligent beings include animals, inanimate objects, abstract concepts, etc.

As a further complication, there is sometimes more than one way to use plurals. In this chapter we will explain the most common usages to keep things as simple as possible.

Arabic has two categories of plurals:

1. The _sound plural:_ 
   English regularly forms the plural by adding the plural ending "s" to the end of a singular noun. For example:
   
   | Singular | Plural |
   |:-----------|:-----------|
   | book       | books      |
   | house      | houses     |
   | boy        | boys       |
   | girl       | girls      |
   
   Arabic also forms some plurals by adding plural endings to to the singular noun. This kind of plural is call a _sound_ plural because the singular noun is kept more or less sound (intact) when adding the plural ending.
   
   Arabic has two types of sound plurals:
   
   i.  The [Un]{.trn} sound plural.
   ii. The [At]{.trn} sound plural.

  We will describe each of these in this chapter.

2. The _broken plural_: When forming this plural the singular noun is not kept intact. We will learn about this plural in the next chapter, if [#allAh]{.trn2} wills.

<!--When translating plurals to English, we may use the subscript "3+" thus "teachers~m,3+~" in order to distinguish it from the dual "teachers~m,2~".-->

## The [Un]{.trn} sound plural

The [Un]{.trn} sound plural is formed by adding the ending [◌ُونَ]{.ar} [-Una]{.trn} to the singular noun when it is in the u-state, and [◌ِينَ]{.ar} [-Ina]{.trn} when the noun is in the a-state or i-state. For convenience, we will call it the "[Un]{.trn} sound plural" instead of the "[-Una]{.trn}/[-Ina]{.trn} plural".

Here is the [Un]{.trn} sound plural of [مُعَلِّم]{.ar} [mueallim]{.trn} "a teacher~m~":

| State | Indefinite [Un]{.trn} plural "teachers~m~"| Definite [Un]{.trn} plural "the teachers~m~"|
|:---------|:-------------|:-------------|
| u-state         | [مُعَلِّمُونَ]{.ar} [mueallimUna]{.trn} |[ٱَلْمُعَلِّمُونَ]{.ar} [EalmueallimUna]{.trn}|
| a- and i-states | [مُعَلِّمِينَ]{.ar} [mueallimIna]{.trn} |[ٱَلْمُعَلِّمِينَ]{.ar} [EalmueallimIna]{.trn}|

Note that, just like for duals, the indefinite [Un]{.trn} sound plural doesn't have [n]{.trn} marks. The only difference between the definite and indefinite [Un]{.trn} sound plural is the definite article [ٱَلْ]{.ar} "the". 

The duals of [مُعَلِّم]{.ar} [mueallim]{.trn} "a teacher~m~" are included here for comparison:

| State | Indefinite [Un]{.trn} sound plural "teachers~m,2~" | Definite [Un]{.trn} sound plural "the teachers~m,2~"|
|:---------|:-------------|:-------------|
| u-state         | [مُعَلِّمَانِ]{.ar} [mueallimAni]{.trn} |[ٱَلْمُعَلِّمَانِ]{.ar} [EalmueallimAni]{.trn}|
| a- and i-states | [مُعَلِّمَيْنِ]{.ar} [mueallimayni]{.trn} |[ٱَلْمُعَلِّمَيْنِ]{.ar} [Ealmueallimayni]{.trn}|

Here are some examples of the [Un]{.trn} sound plural in sentences:

+ u-state:

  [ٱلْمُعَلِّمُونَ فِي ٱلْمَدْرَسَةِ.]{.ar}  
  [EalmueallimUna fi -lmadrasah]{.trn}  
  "The teachers are in the school."

+ a-state:

  [سَأَلَ ٱلْغُلَامُ مُعَلِّمِينَ عَنْ أَمْرٍ.]{.ar}  
  [saEala -lgulAmu mueallimIna fI Eamr.]{.trn}  
  "The boy asked some teachers about a matter."

+ i-state:

  [طَلَبَ ٱلْغُلَامُ مِنَ ٱلْمُعَلِّمِينَ عِلْمًا.]{.ar}  
  [Talaba -lgulAmu mina -lmueallimIna eilmA.]{.trn}  
  "The boy sought some knowledge from the teachers."

### Applicability of the [Un]{.trn} sound plural

Except for very few exceptions, the [Un]{.trn} sound plural is used only for male intelligent beings. We will learn some of these exceptions in chapter\ \@ref(irregular-nouns).

<!--Of these exceptions, the word [سَنَةٌ]{.ar} [sanatun]{.trn} "a year" is the most common. It is pluralized as [سِنُونَ]{.ar} [sinUna]{.trn} in the u-state and [سِنِينَ]{.ar} [sinIna]{.trn} in the a-state and i-state.-->

## The [At]{.trn} sound plural

The [At]{.trn} sound plural is formed by adding the ending [ات]{.ar} [At]{.trn} to the indefinite singular noun. <!-- when it is in the u-state, and [ـَاتٍ]{.ar} [Atin]{.trn} when the noun is in the a-state or i-state.-->

Here is the [At]{.trn} sound plural of [حَيَوَان]{.ar} [HayawAn]{.trn} "an animal":

| State | Indefinite [Un]{.trn} plural "animals"| Definite [Un]{.trn} plural "the animals"|
|:---------|:-------------|:-------------|
| u-state         | [حَيَوَانَاتٌ]{.ar} [HayawAnAtun]{.trn} |[ٱَلْحَيَوَانَاتُ]{.ar} [EalHayawAnAtu]{.trn}|
| a- and i-states | [حَيَوَانَاتٍ]{.ar} [HayawAnAtin]{.trn} |[ٱَلْحَيَوَانَاتِ]{.ar} [EalHayawAnAti]{.trn}|

Note that: <!-- there _are_ [n]{.trn} marks for the [At]{.trn} sound plural. Definite plural nouns are also formed in the same way but they won't have [n]{.trn} marks:-->

+ Unlike the [Un]{.trn} sound plural, the [At]{.trn} sound plural takes [n]{.trn} marks. Also, just like for singular nouns, the final vowel on the plural ending [ات]{.ar} [At]{.trn} indicates the state of the plural.
+ The [At]{.trn} sound plural does not take the [a]{.trn}-mark [◌َ]{.ar} and the [an]{.trn}-mark [◌ً]{.ar}. Instead the [i]{.trn}-mark [◌ِ]{.ar} and the [in]{.trn}-mark [◌ٍ]{.ar}-mark are used to indicate both the a-state and the i-state.

| State | the animal | the animals
|:-----------|:-------------|:-------------|
| u-state | [ٱَلْحَيَوَانُ]{.ar} [EalHayawAnu]{.trn}| [ٱَلْحَيَوَانَاتُ]{.ar} [EalHayawAnAtu]{.trn}|
| a-state | [ٱَلْحَيَوَانَ]{.ar} [EalHayawAna]{.trn}| [ٱَلْحَيَوَانَاتِ]{.ar} [EalHayawAnAti]{.trn}|
| i-state | [ٱَلْحَيَوَانِ]{.ar} [EalHayawAni]{.trn}| [ٱَلْحَيَوَانَاتِ]{.ar} [EalHayawAnAti]{.trn}|

### Nouns ending in [ة]{.ar}

If a noun ends with a looped [tAE]{.trn} [ة]{.ar}, then it is removed before appending the [At]{.trn} sound plural ending. 
Here, for example, is the [At]{.trn} sound plural of [مُعَلِّمَة]{.ar} [mueallimah]{.trn} "a teacher~f~":

| State | Indefinite [Un]{.trn} plural "teachers~f~"| Definite [Un]{.trn} plural "the teachers~f~"|
|:---------|:-------------|:-------------|
| u-state         | [مُعَلِّمَاتٌ]{.ar} [mueallimAtun]{.trn} |[ٱَلْمُعَلِّمَاتُ]{.ar} [EalmueallimAtu]{.trn}|
| a- and i-states | [مُعَلِّمَاتٍ]{.ar} [mueallimAtin]{.trn} |[ٱَلْمُعَلِّمَاتِ]{.ar} [EalmueallimAti]{.trn}|

Here are some examples of the [At]{.trn} sound plural in sentences:

+ u-state:

  [فِي ٱلْمَدْرَسَةِ مُعَلِّمَاتٌ .]{.ar}  
  [fi -lmadrasati mueallimAtun.]{.trn}  
  "In the school are teachers."

+ a-state:

  [نَصَرَ ٱللَّـٰهُ ٱلْمُسْلِمِينَ.]{.ar}  
  [naSara -llAhu -lmuslimIna.]{.trn}  
  "[#allAh]{.trn2} aided the Muslims.

+ i-state:

  [نَظَرَ ٱلْغُلَامُ إِلَى ٱلْحَيَوَانَاتِ.]{.ar}  
  [naPara -lgulAmu Eila -lHayawAnAti.]{.trn}  
  "The boy looked at the animals."

### Nouns ending with [اء]{.ar}, [ىٰ]{.ar}, [ا]{.ar}, and [اة]{.ar} {#at-plural-for-defective-nouns}

As with duals, nouns that end with [اء]{.ar}, [ىٰ]{.ar}, [ا]{.ar}, and [اة]{.ar} are treated specially when forming their [At]{.trn} sound plural. Examples of such nouns are:

+ [سَمَاء]{.ar} [samAE]{.trn} "a sky"
+ [غَضْبَىٰ]{.ar} [gaDbA]{.trn} _adj._ "very angry~f~"
+ [ٱَلْعَصَا]{.ar} [EaleaSA]{.trn} "the staff"
+ [فَتَاة]{.ar} [fatAh]{.trn} "a young woman"

We will learn how to form the [At]{.trn} sound plural of these words in later chapters, if [#allAh]{.trn2} wills.

<!--
### The [At]{.trn} sound plural for words ending with [اء]{.ar}

If a noun ends with an [اء]{.ar} then the [hamzah]{.trn} may either be retained or get converted to a [و]{.ar} when forming the [At]{.trn} sound plural. This is done based on the same rules as for the dual which we explained in the previous chapter.

Thus,

+ REMOVE because plurals of qualitative nouns not yet discussed: [صَفْرَاءُ]{.ar} [SafrAE]{.trn} (root: [صفر]{.arroot}) becomes [صَفْرَاوَاتٌ]{.ar} [SafrAwAtun]{.trn}.
+ [صَحْرَاءُ]{.ar} [SaHrAE]{.trn} (root: [صحر]{.arroot}) becomes [صَحْرَاوَاتٌ]{.ar} [SaHrAwAtun]{.trn}.
+ [إِبْطًاءٌ]{.ar} [EibTAEun]{.trn} (root: [بطء]{.arroot}) becomes [إِبْطَاءَاتٌ]{.ar} [EibTAEAtun]{.trn}.
+ [سَمَاءٌ]{.ar} [samAEun]{.trn} (root: [سمو]{.arroot}) becomes [سَمَاءَاتٌ]{.ar} [samAEAtun]{.trn} or [سَمَاوَاتٌ]{.ar} [samAwAtun]{.trn}.

### The [At]{.trn} sound plural for words ending with [يٰ]{.ar}

If a noun ends with [ىٰ]{.ar}, then whether the [ىٰ]{.ar} is a feminine marker or not, it becomes a [yAE]{.trn} with an [a]{.trn}-mark [يَ]{.ar} when forming the [At]{.trn} sound plural. For example,  

+ [حُبَارَىٰ]{.ar} [HubArA]{.trn} becomes [حُبَارَيَاتٌ]{.ar} [HubArayAtun]{.trn}.

### Designative nouns of the pattern [فَُِعْل]{.ar} and [فَُِعْلَة]{.ar}
-->

### Common nouns of the patterns [فَعْل]{.ar}/[فَعْلَة]{.ar}, [فِعْل]{.ar}/[فِعْلَة]{.ar}, and [فُعْل]{.ar}/[فُعْلَة]{.ar}

Common nouns of the patterns [فَعْل]{.ar}/[فَعْلَة]{.ar}, [فِعْل]{.ar}/[فِعْلَة]{.ar}, and [فُعْل]{.ar}/[فُعْلَة]{.ar} are treated specially when forming their [At]{.trn} sound plural.

If a common noun is of these patterns and the middle root letter is not [و]{.ar} or [ي]{.ar}, and the middle and final root letters are not the same, then the word is modified internally when forming the [At]{.trn} sound plural.

There are two separate rules to consider:

1.  If a common noun is of the pattern [فَعْل]{.ar} [fael]{.trn} or [فَعْلَة]{.ar} [faelah]{.trn}, then the $\emptyset$-mark on the middle letter shall be converted to an [a]{.trn}-mark [◌َ]{.ar} when forming the [At]{.trn} sound plural. For example:

    + [نَحْلَة]{.ar} [naHlah]{.trn} "a bee" becomes [نَحَلَات]{.ar} [naHalAt]{.trn} "bees", not $\times$\ [نَحْلَات]{.ar} [naHlAt]{.trn}.
    + [ضَرْبَة]{.ar} [Darbah]{.trn} "a strike" becomes [ضَرَبَات]{.ar} [DarabAt]{.trn} "strikes", not $\times$\ [ضَرْبَات]{.ar} [DarbAt]{.trn}.

    If the middle root letter is [و]{.ar} or [ي]{.ar}, or the middle and final root letters are the same then this modification is not done. For example,

    + [جَوْزَة]{.ar} [jawzah]{.trn} "a walnut" becomes [جَوْزَات]{.ar} [jawzAt]{.trn}.
    + [حَجَّة]{.ar} [Hajjah]{.trn} "a pilgrimage" becomes [حَجَّات]{.ar} [HajjAt]{.trn}.

2.  If a common noun is of the pattern [فِعْل]{.ar} [fiel]{.trn}, [فِعْلَة]{.ar} [fielah]{.trn}, [فُعْل]{.ar} [fuel]{.trn}, or [فُعْلَة]{.ar} [fuelah]{.trn} then the $\emptyset$-mark on the middle letter can, optionally, either:

    i.   be retained,
    ii.  be converted to an [a]{.trn} mark, or
    iii. be converted to the vowel mark on the first letter.

    For example:

    + [ظُلْمَة]{.ar} [Pulmah]{.trn} "a darkness" can become, optionally, either [ظُلْمَات]{.ar} [PulmAt]{.trn} or [ظُلَمَات]{.ar} [PulamAt]{.trn}, or [ظُلُمَات]{.ar} [PulumAt]{.trn} "darknesses".
    + [كِسْرَة]{.ar} [kisrah]{.trn} "a piece" can become, optionally, either [كِسْرَات]{.ar} [kisrAt]{.trn} or [كِسَرَات]{.ar} [kisarAt]{.trn}, or [كِسِرَات]{.ar} [kisirAt]{.trn} "pieces".

Note that this rule of changing the vowel mark is only true for common nouns. Adjectival-nouns on these patterns will retain the $\emptyset$-mark when forming the [At]{.trn} sound plural. So [صَعْب]{.ar} [Saeb]{.trn} and [صَعْبَة]{.ar} [Saebah]{.trn} "a difficult one" become only [صَعْبَات]{.ar} [SaebAt]{.trn}, not $\times$\ [صَعَبَات]{.ar} [SaeabAt]{.trn}.

### Applicability of the [At]{.trn} sound plural

We had mentioned that the [Un]{.trn} sound plural is used, with very few exceptions, only for male intelligent beings. Conversely, the [At]{.trn} is used for both female intelligent beings, and for non-intelligent beings (both masculine and feminine) like animals, inanimate objects, and abstract concepts. Rarely, it is also used for male intelligent beings.


<!--
Examples:

[ٱَلْمُعَلِّمَاتُ فِي ٱلْمَدْرَسَةِ.]{.ar}  
[EalmueallimAtu fi -lmadrasati.]{.trn}  
"The female teachers are in the school."

[ٱَلْحَيَوَانَاتُ فِي ٱلْغَابَاتِ.]{.ar}  
[EalHayawAnAtu fi -lgAbAti.]{.trn}  
"The animals are in the forests."
-->

## Conditions for forming the sound plural

Many times, a noun can form both an [Un]{.trn} sound plural and an [At]{.trn} sound plural.
<!--However, some nouns form only an [Un]{.trn} sound plural, and not an [At]{.trn} sound plural.
Conversely, some nouns form only an [At]{.trn} sound plural, and not an [Un]{.trn} sound plural.
-->
However, there are many nouns that can form only one of the two sound plurals.
And many nouns don't form either sound plural; they only form broken plurals. (We will learn about broken plurals in the next chapter, if [#allAh]{.trn2} wills.) There are even nouns that can form both sound and broken plurals.

Here we will learn some of the conditions which a noun needs to satisfy in order for it to form the sound plurals.

### Conditions for the [Un]{.trn} sound plural

The [Un]{.trn} sound plural is used, with very few exceptions, only for nouns that denote male intelligent beings. These guidelines will help you determine which nouns form the [Un]{.trn} sound plural. 

We will treat common nouns and adjectival nouns separately.

#### Common nouns

<!--Common nouns will form an [Un]{.trn} sound plural if it is listed in their vocabulary/dictionary definition. 
You can often determine if a common noun will regularly form a sound plural based on the pattern of the noun. But that is an advanced technique that we will learn later, if [#allAh]{.trn2} wills. For now, we will rely on the dictionary/vocabulary definition to tell us whether a noun forms the [Un]{.trn} sound plural.
-->
With very few exceptions, the only common nouns that _may_ be allowed to form [Un]{.trn} sound plurals are those that denote male intelligent beings, and whose feminine is formed by adding a [ة]{.ar} to the masculine noun. So, [غُلَام]{.ar} [gulAm]{.trn} "a boy" is disqualified from forming a [Un]{.trn} sound plural because its feminine counterpart is [جَارِيَة]{.ar} [jAriyah]{.trn} "a girl", not $\times$\ [غُلَامَة]{.ar} [gulAmah]{.trn}. In addition, a further restriction is imposed, which we will explain below:

We learned in section\ \@ref(related-nouns-for-male-and-female-animate-beings) that, in terms of their meaning, nouns that denote animate beings are of two kinds:

i.  Nouns that have a primitive meaning. That is, their meaning is not derived from a verbal or adjectival meaning. Examples (for male intelligent beings whose feminine is formed by adding [ة]{.ar} to the masculine noun):

    Arabic word | Definition
    :----------------|:----------------
    [ٱِبْن]{.ar}    [Eibn]{.trn}      |a son
    [طِفْل]{.ar}    [Tifl]{.trn}      |a child
    [إِنْسَان]{.ar}  [EinsAn]{.trn}    |a human being
    [حُرّ]{.ar}     [Hurr]{.trn}      |a free man

    Such nouns, in general, won't be expected to form [Un]{.trn} sound plurals, unless the [Un]{.trn} sound plural is explicitly allowed in their dictionary definition.

ii. Nouns that have a meaning that is derived from a verbal or adjectival meaning. Examples (for male intelligent beings whose feminine is formed by adding [ة]{.ar} to the masculine noun):

    |Word | Definition | [Un]{.trn} plural|
    |:--------------|:----------------|:------------|
    |[مُعَلِّم]{.ar}  |a  teacher~m~   |[مُعَلِّمُونَ]{.ar}|
    |[مُسْلِم]{.ar}  |a  Muslim~m~ (one who submits)  |[مُسْلِمُونَ]{.ar}|
    |[كَافِر]{.ar}  |a  disbeliever~m~ |[كَافِرُونَ]{.ar}|
    |[لَاعِب]{.ar}  |a  player~m~    |[لَاعِبُونَ]{.ar}|

    Such nouns, in general, can be expected to form [Un]{.trn} sound plurals. 
    
<!--Many of these nouns also, as we will see in the next chapter, if [#allAh]{.trn2} wills, form broken plurals. In general, then, the broken plural is preferred to be used over the sound plural, and the sound plural is only used in specific cases (that we will also see later, if [#allAh]{.trn2} wills).-->

The above condition, as we have explained it, is somewhat imprecise. For example, the word 
    [حُرّ]{.ar}     [Hurr]{.trn}      (masc.) "a free man" seems to have a meaning that is derived from the adjective "free" and it forms its feminine by adding [ة]{.ar} to it thus: 
[حُرَّة]{.ar}    [Hurrah]{.trn}    (fem.) "a free woman".
Yet it is considered a primitve noun, and thus does not form an [Un]{.trn} sound plural.

In later chapters, once we have studied the patterns of the derived nouns, we will try to make this condition more precise, if [#allAh]{.trn2} wills.

The few exceptions of common nouns that denote non-male intelligent beings, yet have an [Un]{.trn} sound plural include:

+ [عَالَم]{.ar} [eAlam]{.trn} "a world" forms the [Un]{.trn} plural [عَالَمُونَ]{.ar} [EAlamUna]{.trn} "worlds".
+ [أَرْض]{.ar} [EarD]{.trn} (fem.) "a land", "an earth" forms the [Un]{.trn} plural [أَرْضُونَ]{.ar} [EarDUna]{.trn} "lands", "earths".
+ [أَهْل]{.ar} [Eahl]{.trn} "a family" forms the [Un]{.trn} plural [أَهْلُونَ]{.ar} [EahlUna]{.trn} "families".

#### Adjectival nouns

If an adjectival noun forms its feminine by adding the feminine marker [ة]{.ar} to the masculine noun, then we may assume that it forms the [Un]{.trn} sound plural. 

Most adjectival nouns satisfy this condition. For example, consider the adjectival noun:

+ [كَبِير]{.ar} [kabIr]{.trn} (masc.) "a big one"

It forms its feminine by adding a [ة]{.ar} to the masculine noun, thus:

+ [كَبِيرَة]{.ar} [kabIrah]{.trn} (fem.) "a big one"

The above condition is satisfied; therefore,
[كَبِير]{.ar} [kabIr]{.trn} (masc.) "a big one" forms the [Un]{.trn} sound plural [كَبِيرُونَ]{.ar} [kabIrUna]{.trn} "big ones".

By the way, it is only the masculine adjectival noun that will form the [Un]{.trn} sound plural. Nouns with a [ة]{.ar} are not allowed to form the [Un]{.trn} sound plural.

We have come across two patterns on adjectival nouns that don't form their feminine by adding [ة]{.ar} to masculine noun. These are:

i.  [فَعْلَان^2^]{.ar} [faelAn^2^]{.trn}, whose feminine is on the pattern [فَعْلَىٰ^2^]{.ar} [faelA^2^]{.trn}. Example: [غَضْبَان^2^]{.ar} [gaDbAn^2^]{.trn} (masc.) "very angry" whose feminine is [غَضْبَىٰ^2^]{.ar} [gaDbA^2^]{.trn}.
ii. [أَفْعَل^2^]{.ar} [Eafeal^2^]{.trn}, whose feminine is on the pattern [فَعْلَاء^2^]{.ar} [faelAE^2^]{.trn}. Example: [أَحْمَر^2^]{.ar} [EaHmar^2^]{.trn} (masc.) "red", whose feminine is [حَمْرَاء^2^]{.ar} [HamrAE^2^]{.trn}.

Because the above two patterns don't form their feminine by adding [ة]{.ar} to the masculine noun, therefore the masculine nouns don't form the [Un]{.trn} sound plural. We will see, if [#allAh]{.trn2} wills, that they form broken plurals instead.

### Conditions for the [At]{.trn} sound plural

Just like the [Un]{.trn} plural, there are conditions that should be fulfilled in order for a noun to form an [At]{.trn} plural.
We provide the following guidelines to help you determine if a noun can form an [At]{.trn} plural.

#### Nouns that end with a feminine marker

With very few exceptions, all nouns that end with a feminine marker like
[ة]{.ar}, [اء]{.ar}, and [ىٰ]{.ar}
are able to form an [At]{.trn} plural. This includes both common nouns and adjectival nouns.

As mentioned in section\ \@ref(at-plural-for-defective-nouns) above, we will learn how to form plurals for nouns that end with 
[اء]{.ar}, and [ىٰ]{.ar}
later, if [#allAh]{.trn2} wills.
So, for now, we will focus on nouns that end with [ة]{.ar}.
Examples are:

+ [حَسَنَة]{.ar} [Hasanah]{.trn} _adj._ "a good one" forms the [At]{.trn} plural [حَسَنَات]{.ar} [HasanAt]{.trn} "good ones".
+ [حَسَنَة]{.ar} [Hasanah]{.trn} (common noun) "a good deed" also forms the same [At]{.trn} plural [حَسَنَات]{.ar} [HasanAt]{.trn} "good deeds".
+ [صَدِيقَة]{.ar} [SadIqah]{.trn} "a friend~f~" forms the [At]{.trn} plural [صَدِيقَات]{.ar} [SadIqAt]{.trn} "friends~f~".

The very few exceptions include:

+ [أُمَّة]{.ar} [Eummah]{.trn} "a nation"
+ [أَمَة]{.ar} [Eamah]{.trn} "a female slave"
+ [شَفَة]{.ar} [cafah]{.trn} "a lip"

These nouns form broken plurals instead.

#### Nouns that don't end with a feminine marker

##### Common nouns {-}

Common nouns that don't end with a feminine marker will form the [At]{.trn} plural only if they don't have a broken plural listed in the dictionary. Furthermore, it is preferred if the noun have five or more letters.

+ [حَيَوَان]{.ar} [HayawAn]{.trn} "an animal" forms the [At]{.trn} plural [حَيَوَانَات]{.ar} [HayawAnAt]{.trn} "animals".
+ [حَمَّام]{.ar} [HammAm]{.trn} forms the [At]{.trn} plural [حَمَّامَات]{.ar} [HammAmAt]{.trn} "bathrooms". (The doubled [م]{.ar} counts as two letters.)

##### Masculine adjectival nouns {-}

Masculine adjectival nouns are permitted to form an [At]{.trn} sound plural, but only when they are applied to non-intelligent beings.

For example, if the masculine adjectival noun [صَعْب]{.ar} [Saeb]{.trn} "a difficult one" is applied to "books", which is the plural of the masculine noun [كِتَاب]{.ar} [kitAb]{.trn} "a book", then the masculine adjectival noun [صَعْب]{.ar} [Saeb]{.trn} is permitted to form the [At]{.trn} plural [صَعْبَات]{.ar} [SaebAt]{.trn} "difficult ones".

By the way, note that both the masculine adjectival noun [صَعْب]{.ar} [Saeb]{.trn}, and its feminine [صَعْبَة]{.ar} [Saebah]{.trn} form the same [At]{.trn} sound plural [صَعْبَات]{.ar} [SaebAt]{.trn}.

<!--
## Usage of plural adjectival nouns

We will defer the discussion on how to use plural adjectival nouns until the next chapter, when we will learn broken plurals, if [#allAh]{.trn2} wills.
-->

<!--
## Plurals of adjectival nouns 

Most adjectival-nouns form sound plurals. For now you can assume, unless told otherwise, that any adjectival noun can form an [Un]{.trn} sound plural applicable to male intelligent beings, and an [At]{.trn} sound plural applicable to female intelligent beings and non-intelligent beings.

In later chapters, we will give a more complete list of conditions that need to be satisfied for a noun to form sound plurals.

So the masculine adjectival-noun [طَيِّب]{.ar} "Tayyib" (masc.) "a good one" will form the following plurals:

+ the [Un]{.trn} sound plural [طَيِّبُونَ]{.ar} [TayyibUna]{.trn} applicable to male intelligent beings, and
+ the [At]{.trn} sound plural [طَيِّبَات]{.ar} [TayyibAt]{.trn} applicable to masculine nouns non-intelligent beings.

And the feminine adjectival noun [طَيِّبَة]{.ar}

It is not just designative nouns that have plurals. Many qualitative nouns may be pluralized with sound plurals as well. For example, [طَيِّبٌ]{.ar} [Tayyibun]{.trn} has the [Un]{.trn} sound plural [طَيِّبُونَ]{.ar} [TayyibUna]{.trn} and the [At]{.trn} sound plural [طَيِّبَاتٌ]{.ar} [TayyibAtun]{.trn}. The complete rules of whether a qualitative noun has a sound plural are somwehat complicated. For now, you may use the following rule of thumb:

Only masculine qualitative nouns that form their feminine by the addition of [ة]{.ar} may be pluralized with the [Un]{.trn} sound plural. And all feminine qualitative noun that ends with [ة]{.ar} may be pluralized with the [At]{.trn} sound plural. But there do exist feminine qualitative nouns that don't end with [ة]{.ar} that form the [At]{.trn} sound plural. For example,

+ [كَبِيرٌ]{.ar} [kabIrun]{.trn} "big (masc.)" forms its feminine with the addition of [ة]{.ar}: [كَبِيرَةٌ]{.ar} [kabIratun]{.trn}. Therefore it can be pluralized with the sound [Un]{.trn} sound plural [كَبِيرُونَ]{.ar}. And [كَبيرَةٌ]{.ar} can be pluralized as [كَبِيرَاتٌ]{.ar}.
+ [غَضْبَانُ]{.ar} [gaDbAnu]{.trn} "very angry (masc.)" forms its feminine without [ة]{.ar}: [غَضْبَىٰ]{.ar} [gaDbA]{.trn}. Therefore it will not form the sound [Un]{.trn} sound plural.

In using plurals of qualitative nouns, Arabic distinguishes between intelligent beings and non-intelligent beings. Here we explain the usage of qualitative noun plurals with intelligent beings. We will explain the usage of qualitative noun plurals with non-intelligent beings in the next chapter, if Allah wills.

When a qualitative noun is describing plural intelligent beings, then the qualitative noun will be pluralized. For example,

[ٱَلْمُعَلِّمُونَ طَيِّبُونَ.]{.ar}  
[EalmueallimUna TayyibUna]{.trn}  
"The male teachers are good."

[كَانَتِ ٱلْجَارِيَاتُ ٱلطَّوِيلَاتُ سَرِيعَاتٍ.]{.ar}  
[kAnati -ljAriyAtu -TTawIlAtu sarIeAtin]{.trn}  
"The tall girls were fast."
-->

## Detached plural pronouns

We have already learned the detached pronouns for singular and dual nouns. They are repeated here:

|Participant|Detached pronoun|
|:---|:-|
|Absentee  sing. masc.    |[هُوَ]{.ar} [huwa]{.trn}   "he"      |
|Absentee  sing. fem.     |[هِيَ]{.ar} [hiya]{.trn}   "she"    |
|Absentee  dual           |[هُمَا]{.ar} [humA]{.trn}      "they~2~" |
|Addressee sing. masc.    |[أَنْتَ]{.ar} [Eanta]{.trn} "you~1,m~"|
|Addressee sing. fem.     |[أَنْتِ]{.ar} [Eanti]{.trn} "you~1,f~"|
|Addressee dual           |[أَنْتُمَا]{.ar} [EantumA]{.trn} "you~2~" |
|Speaker   sing.          |[أَنَا]{.ar} [Eana]{.trn}  "I"      |
|Speaker   dual           | -- |

Now we will learn the detached pronouns for the plural participants:

|Participant|Detached pronoun|
|:---|:-|
|Absentee  pl. masc. |[هُمْ]{.ar} [hum]{.trn}        "they~3,m~" |
|Absentee  pl. fem.  |[هُنَّ]{.ar} [hunna]{.trn}      "they~3,f~" |
|Addressee pl. masc. |[أَنْتُمْ]{.ar} [Eantum]{.trn}   "you~3,m~" |
|Addressee pl. fem.  |[أَنْتُنَّ]{.ar} [Eantunna]{.trn} "you~3,f~" |
|Speaker   pl.       |[نَحْنُ]{.ar} [naHnu]{.trn}     "we" |

Note that the plural detached pronoun for the speaker participant 
[نَحْنُ]{.ar} [naHnu]{.trn}     "we"
are the same for both genders.

Also, remember that there is no detached pronoun for the dual speaker-participant. 
So, if the speaker-pariticipant consists of two individuals then we will use the plural pronoun.

Here are some examples of their use:

[هُمْ مُسْلِمُونَ.]{.ar}  
[hum muslimUn.]{.trn}  
"They~3,m~ are men~3~."

[هُنَّ مُعَلِّمَاتٍ.]{.ar}  
[hum mueallimaAt.]{.trn}  
"They~3,f~ are teachers~f~."

[أَنْتُمْ لَاعِبُونَ.]{.ar}  
[Eantum lAeibUn.]{.trn}  
"You~3,m~ are players~3,m~."

[أَنْتُنَّ صَدِيقَاتٍ.]{.ar}  
[Eantunna SadIqAt.]{.trn}  
"You~3,f~ are friends~3,f~."

[نَحْنُ رَجُلَانِ فَقِيرَانِ.]{.ar}  
[naHnu rajulAni faqIrAn.]{.trn}  
"We~2,m~ are poor men~2~." (Note the plural pronoun subject with a dual noun in the information.)

[نَحْنُ مُسْلِمَاتٍ.]{.ar}  
[naHnu muslimAt.]{.trn}  
"We~3,f~ are Muslims~3,f~."

## Attached plural pronouns

We have also already learned the attached pronouns for the singular and dual participants. They too are repeated here:

|Participant | Attached pronoun|
|:------|:--|
|Absentee   sing. masc.    | [هُ]{.ar} [-hu]{.trn}   "him"       |
|Absentee   sing. fem.     | [هَا]{.ar} [-hA]{.trn}  "her"       |
|Absentee   dual           | [هُمَا]{.ar} [-humA]{.trn}  "them~2~"|
|Addressee  sing. masc.    | [كَ]{.ar} [-ka]{.trn}   "you~m,1~"  |
|Addressee  sing. fem.     | [كِ]{.ar} [-ki]{.trn}   "you~f,1~"  |
|Addressee  dual           | [كُمَا]{.ar} [-kumA]{.trn}  "you~2~" |
|Speaker    sing.          | [ي]{.ar}               "me"        |
|Speaker    dual | -- |

Now we will learn the attached pronouns for the plural participant:

|Participant | Attached pronoun|
|:------|:--|
|Absentee   pl. masc.    | [هُمْ]{.ar} [-hum]{.trn}   "them~3,m~  |
|Absentee   pl. fem.     | [هُنَّ]{.ar} [-hunna]{.trn} "them~3,f~  |
|Addressee  pl. masc.    | [كُمْ]{.ar} [-kum]{.trn}   "you~3,m~"  |
|Addressee  pl. fem.     | [كُنَّ]{.ar} [-kunna]{.trn} "you~3,f~"  |
|Speaker    pl           | [نَا]{.ar} [-nA]{.trn}    "us"        |

Note the following points about them:

+ The plural absentee-participant detached and attached pronouns ("they~3,m~"/"them~3,m~") are the same:
  + masculine: [هُمْ]{.ar} [-hum]{.trn}.
  + feminine: [هُنَّ]{.ar} [-hunna]{.trn}.
+ Just like [هُ]{.ar} [hu]{.trn} "him" and [هُمَا]{.ar} [-humA]{.trn} "them~2~", the plural absentee-participant attached pronouns
[هُمْ]{.ar} [-hum]{.trn}   "them~3,m~" and
[هُنَّ]{.ar} [-hunna]{.trn} "them~3,f~"
become [هِمَا]{.ar} [-himA]{.trn} and [هِنَّ]{.ar} [-hinna]{.trn} respectively, when preceded by the vowels [◌ِ]{.ar} [-i]{.trn}, [◌ِي]{.ar} [-I]{.trn}, or the semi-vowel [◌َيْ]{.ar} [-ay]{.trn}. Examples:
   + [بِهِمْ]{.ar} [bihimA]{.trn} "with them~3,m~"
   + [فِيهِنَّ]{.ar} [fIhinna]{.trn} "in them~3,f~"
   + [إِلَيْهِمْ]{.ar} [Eilayhim]{.trn} "to them~3,m~"
+ The final $\emptyset$-mark on the [مْ]{.ar} in the masculine plural pronouns ([هُمْ]{.ar} [hum]{.trn}, [أَنْتُمْ]{.ar} [Eantum]{.trn}, and [كُمْ]{.ar} [-kum]{.trn}) becomes a [u]{.trn}-mark ([هُمُ]{.ar} [humu]{.trn}, [أَنْتُمُ]{.ar} [Eantumu]{.trn},  and[كُمُ]{.ar} [-kumu]{.trn} respectively) when followed by a connecting [hamzah]{.trn}. Examples:
  + [هُمُ ٱلْمُعَلِّمُونَ.]{.ar}  
    [humu -lmueallimUn.]{.trn}  
    "They~pl.\ masc.~ are the (male) teachers."
  + [ذَهَبَ إِلَيْكُمُ ٱلرَّجُلُ.]{.ar}  
    [pahaba Eilaykumu -rrajul.]{.trn}  
    "The man went to you~3,m~."
  + [أَنْتُمُ ٱلْمُسْلِمُونَ.]{.ar}  
    [Eantumu -lmuslimUn.]{.trn}
    "You~3,m~ are the Muslims~3,m~."
+ When the speaker plural attached pronoun [نَا]{.ar} is attached to a word that ends with a [نْ]{.ar} with a $\emptyset$-mark, there is only one [ن]{.ar} written and it is doubled with a doubling mark [◌ّ]{.ar} on it. So we get:
   + [نَا]{.ar} + [مِنْ]{.ar} = [مِنَّا]{.ar} [minnA]{.trn}
   + [نَا]{.ar} + [عَنْ]{.ar} = [عَنَّا]{.ar} [eannA]{.trn}
   + [نَا]{.ar} + [لَدُنْ]{.ar} = [لَدُنَّا]{.ar} [ladunnA]{.trn}
+ The preposition [لِ]{.ar} [li]{.trn} "for" becomes [لَ]{.ar} [la]{.trn} when followed by the plural attached pronouns:
   + [لَهُمْ]{.ar} [lahum]{.trn} "for them~3,m~"
   + [لَهُنَّ]{.ar} [lahunna]{.trn} "for them~3,f~"
   + [لَكُمْ]{.ar} [lakum]{.trn} "for you~3,m~"
   + [لَكُنَّ]{.ar} [lakunna]{.trn} "for you~3,f~"
   + [لَنَا]{.ar} [lanA]{.trn} "for us"

### Plural doee pronouns

The plural attached pronouns that we have just learned are also used as doee pronouns. 
<!--Again, there is no additional intervening [ن]{.ar} for the speaking participant dual attached pronoun [نَا]{.ar} [-nA]{.trn}. -->
Examples:

[سَأَلَهُمُ ٱلرَّجُلُ.]{.ar}  
[saEalahumu -rrajul.]{.trn}  
"The man asked them~3,m~."

[سَأَلْتُكُمْ.]{.ar}  
[saEaltukum]{.trn}  
"I asked you~3,m~."

[سَأَلَتْكُنَّ.]{.ar}  
[saEalatkunn.]{.trn}  
"She asked you~3,f~."

[سَأَلَانَا.]{.ar}  
[saEalAnA.]{.trn}  
"They~2~ asked us."

## Pronouns for the plural

Here are the detached, attached, and doer pronouns for the plural:

|Person|Detached pronoun|Completed-action verb doer pronoun|Completed-action verb with doer pronoun|Attached pronoun|
|:---|:----|:----|:----|
| they/them~pl.\ masc.~ |[هُمْ]{.ar} [hum]{.trn}        | [◌ُو]{.ar} [-U]{.trn}     |[فَعَلُوا]{.ar} [faealU]{.trn}     |[هُمْ]{.ar} [-hum]{.trn}|
| they/them~pl.\ fem.~  |[هُنَّ]{.ar} [hunna]{.trn}      | [نَ]{.ar} [-na]{.trn}     |[فَعَلْنَ]{.ar} [faealna]{.trn}     |[هُنَّ]{.ar} [-hunna]{.trn}|
| you~pl.\ masc.~       |[أَنْتُمْ]{.ar} [Eantum]{.trn}   | [تُمْ]{.ar} [-tum]{.trn}   |[فَعَلْتُمْ]{.ar} [faealtum]{.trn}   |[كُمْ]{.ar} [-kum]{.trn}|
| you~pl.\ fem.~        |[أَنْتُنَّ]{.ar} [Eantunna]{.trn} | [تُنَّ]{.ar}  [-tunna]{.trn}|[فَعَلْتُنَّ]{.ar} [faealtunna]{.trn} |[كُنَّ]{.ar} [-kunna]{.trn}|
| we/us~pl.\ masc.\ and fem.~ |[نَحْنُ]{.ar} [naHnu]{.trn}     | [نَا]{.ar} [-nA]{.trn}    |[فَعَلْنَا]{.ar} [faealnA]{.trn}    |[نَا]{.ar} [-nA]{.trn}|


Here are some rules for the plural pronouns:

+ The plural attached and detached pronouns for the absent person "they/them~pl.\ masc.~" are pronounced the same: [هُمْ]{.ar} [hum]{.trn}.
+ Similar to the singular and dual,the pronouns for the speaking person (we, us) do not differentiate between the masculine and feminine genders plural either.
+ The speaking person pronouns are the same for the dual and plural: [نَحْنُ]{.ar} [naHnu]{.trn} and [نَا]{.ar} [-nA]{.trn}.
+ Similar to [هُ]{.ar} [-hu]{.trn}, [هُمَا]{.ar} [-humA]{.trn}, the [u]{.trn}-mark on the plural attached pronoun [هُمْ]{.ar} [-hum]{.trn} becomes an [i]{.trn}-mark ([هِمْ]{.ar} [-him]{.trn}) when it is preceded by the vowels [◌ِ]{.ar} [i]{.trn}, [ـِي]{.ar} [I]{.trn}, or the semi-vowel [ـَيْ]{.ar} [ay]{.trn}. Examples: 
  + [عَلَيْهِ]{.ar}, [ealayhi]{.trn} "on him"
  + [فِيهِمْ]{.ar} [fIhim]{.trn} "in them~pl.~"
  + [بِهِمْ]{.ar} [bihim]{.trn} "with them~pl.~".
+ The final $\emptyset$-mark on the [مْ]{.ar} in the masculine plural pronouns ([هُمْ]{.ar} [hum]{.trn}, [هُمْ]{.ar} [-hum]{.trn}, [أَنْتُمْ]{.ar} [Eantum]{.trn}, [تُمْ]{.ar} [-tum]{.trn}, [كُمْ]{.ar} [-kum]{.trn}) becomes a [u]{.trn}-mark ([هُمُ]{.ar} [humu]{.trn}, [هُمُ]{.ar} [-humu]{.trn}, [أَنْتُمُ]{.ar} [Eantumu]{.trn}, [تُمُ]{.ar} [-tumu]{.trn}, [كُمُ]{.ar} [-kumu]{.trn} respectively) when followed by a connecting [hamzah]{.trn}. Examples:
  + [هُمُ ٱلْمُعَلِّمُونَ.]{.ar}  
    [humu -lmueallimUna.]{.trn}  
    "They~pl.\ masc.~ are the (male) teachers."
+ The plural masculine verb doer pronoun for the absent person "they~pl.\ masc.~" [ـُوا]{.ar} [U]{.trn} has a silent [Ealif]{.trn} which is written only and not pronounced. This [Ealif]{.trn} is dropped when a doee pronoun is attached. For example: 
  + [ضَرَبُوا ٱلرَّجُلَ.]{.ar}  
    [Darabu -rrajula.]{.trn}  
    "They hit the man.
  + [ضَرَبُوهُ.]{.ar}  
    [DarabUhu.]{.trn}  
    "They~pl.\ masc.~ hit him."
+ The plural masculine verb doer pronoun for the addressed person "you~pl.\ masc.~" [تُمْ]{.ar} [-tum]{.trn} becomes [تُمُو]{.ar} [tumU]{.trn} when a doee pronoun is attached. For example:
  + [ضَرَبْتُمُ ٱلرَّجُلَ.]{.ar}  
    [Darabtumu -rrajula.]{.trn}  
    "You~pl.\ masc.~ hit the man."
  + [ضَرَبْتُمُوهُ.]{.ar}  
    [DarabtumUhu.]{.trn}  
    "You~pl.\ masc.~ hit him."
+ The [ن]{.ar} in the speaking participant attached pronoun "us" [نَا]{.ar} [-nA]{.trn} is part of the pronoun and is not an intervening [ن]{.ar} as was the case for the singular speaking participant pronouns. So we get:
   + [عَلَيْنَا]{.ar} [ealaynA]{.trn} "on us"
   + [بِنَا]{.ar} [binA]{.trn} "with us"

  However, when attached to a word that ends with a [نْ]{.ar} with a $\emptyset$-mark, there is only one [ن]{.ar} written and it is doubled with a doubling mark [◌ّ]{.ar} on it. So we get:
   + [نَا]{.ar} + [مِنْ]{.ar} = [مِنَّا]{.ar} [minnA]{.trn}
   + [نَا]{.ar} + [عَنْ]{.ar} = [عَنَّا]{.ar} [eannA]{.trn}
   + [نَا]{.ar} + [لَدُنْ]{.ar} = [لَدُنَّا]{.ar} [ladunnA]{.trn}
+ The preposition [لِ]{.ar} [li]{.trn} "for" becomes [لَ]{.ar} [la]{.trn} when followed by the plural attached pronouns:
   + [لَهُمْ]{.ar} [lahum]{.trn} "for them~3+~"
   + [لَكُمْ]{.ar} [lakum]{.trn} "for you~3+~"
   + [لَنَا]{.ar} [lanA]{.trn} "for us"
+ The plural speaking participant doer pronoun [نَا]{.ar} [-nA]{.trn} is the same as the plural speaking participant attached pronoun [نَا]{.ar} [-nA]{.trn}. But you can tell them apart because the doer pronoun, when attached to the verb, causes the final letter of the verb to have a $\emptyset$-mark. Consider the following two sentences:

  [سَأَلْنَا.]{.ar}  
  [saEalnA.]{.trn}  
  "We asked."

  [سَأَلَنَا.]{.ar}  
  [saEalanA.]{.trn}  
  "He asked us."


## Verbs with plural intelligent doers

Remember that in Arabic, a doer, whether a noun or a pronoun, always after a verb. 

[ذَهَبُوا إِلَىٰ بَيْتٍ.]{.ar}  
[pahabU EilA baytin.]{.trn}  
"They~pl.\ masc.~ went to a house."

When the doer is a plural noun then the plural doer pronoun is not employed.

[ذَهَبَ ٱلْمُعَلِّمُونَ إِلَىٰ بَيْتٍ.]{.ar}  
[pahabA -lmueallimUna EilA baytin.]{.trn}  
"The teachers went to a house."

The above verbal sentence can be rearranged to be a subject-information sentence. This gives more emphasis to the subject. In this case, the verb shall follow the subject and will need a doer pronoun after it.

[ٱَلْمُعَلِّمُونَ ذَهَبُوا إِلَىٰ بَيْتٍ.]{.ar}  
[EalmueallimUna pahabU EilA baytin.]{.trn}  
"The teachers, they~pl.\ masc.~ went to a house."

If there are multiple verbs associated with the same doer in a verbal sentence, the doer noun will follow the first verb  and the rest of the verbs will have doer pronouns. For example:

[أَكَلَ ٱلْمُعَلِّمُونَ  وَشَرِبُوا وَذَهَبُوا.]{.ar}  
[Eakala -rrajulAni wacaribU wapahabU.]{.trn}  
"The two men ate and they~pl.\ masc.~ drank and they~pl.\ masc.~ went."  
= "The two men ate and drank and went."

The above verbal sentence can be rearranged to be a subject-information sentence. In that case, all the verbs shall have doer pronouns. The sentence will have the same translation as above, except for an emphasis on the subject of the sentence.

[ٱَلْمُعَلِّمُونَ أَكَلُوا وَشَرِبُوا وَذَهَبُوا.]{.ar}  
[EalmueallimUna EakalU wacaribU wapahabU.]{.trn}  
"The two men, they~pl.\ masc.~ ate and they~pl.\ masc.~ drank and they~pl.\ masc.~ went."  
= "_The two men_ ate and drank and went."

### Verbs with multiple doers mentioned individually

If there are multiple doers of a verb, and each is mentioned individually, then there is often more than one way to handle them. Here we will give the more common usage.

If the verb is followed by multiple doers, only the first is the true doer with respect to  modifying the verb according to its gender and number. Examples:

[ذَهَبَتِ ٱلْأُمُّ وَٱلْغُلَامُ.]{.ar}  
[pahabati -lEummu wa-lgulAmu.]{.trn}  
"The mother and the boy went."

[ذَهَبَ ٱلْغُلَامُ وَٱلْأُمُّ .]{.ar}  
[pahaba -lgulAmu wa -lEummu.]{.trn}  
"The boy and the mother went."

If the doers consist of different persons (speaking person, addressed person, and absent person), then they are placed in order of strength: The speaking person is stronger than the addressed person, who is stronger than the absent person. The verb doer pronoun of the first (true) doer is then used. Example:
  
[ذَهَبْتُ أَنَا وَأَنْتَ وَهُوَ.]{.ar}  
[pahabtu Eana waEanta wahuwa.]{.trn}  
"I, you, and he went."

[أنْتَ وَهُوَ ذَهَبْتُمَا.]{.ar}  
[Eanta wahuwa pahabtumA.]{.trn}  
"You~sing.~ and he, you~dual~ went."

[أَنَا وَمُحَمَّدٌ ذَهَبْنَا.]{.ar}  
[Eana wamuHammadun pahabnA.]{.trn}  
"I and [#muHammad]{.trn2}, we went."

Note how the speaking person detached pronoun [أَنَا]{.ar} [Eana]{.trn} is used in addition to the doer pronoun [تُ]{.ar} [-tu]{.trn} in order to add [وَ]{.ar} [wa]{.trn} "and" to it.

If the verb follows the doers, then it will have the doer pronoun corresponding to number of the doers. Example:

[ٱلْأُمُّ وَٱلْجَارِيَةُ ذَهَبَتَا.]{.ar}  
[EalEummu wa-ljAriyatu pahabatA.]{.trn}  
"The mother and the girl went."

[ٱلْأُمُّ وَٱلْجَارِيَتَانِ ذَهَبْنَ.]{.ar}  
[EalEummu wa-ljAriyatAni pahabna.]{.trn}  
"The mother and the two girls, they~pl.\ fem.~ went."

If the doers consist of both male and female persons, then the verb will have the masculine doer prenoun corresponding to the number of the doers. Example:

[ٱلْأُمُّ وَٱلْجَارِيَةُ وَٱلْغُلَامُ ذَهَبُوا.]{.ar}  
[EalEummu wa-ljAriyatu wa-lgulAmu pahabU.]{.trn}  
"The mother, the girl, and the boy, they~pl.\ masc.~ went."
<!-- Al-Nahw Al Wafy vol. i. p. 268, point 9 -->

