# Usage and style

## "There is a ..." sentences.

In English the plain existence of an indefinite subject is expressed using the word "there". For example:

i.   "There is a gloom in the house"
ii.  "There is a type of anger which is liked and [there is] a type of anger which is disliked.
iii. "There are reasons."
iv.  "There is a god."
v.   "Is there food?"
vi.  "Yes, there is food"

The word "there" in these examples does not indicate a specific place. Rather it signifies the existence of the subject of the sentence. 
This use of "there" is called the _existential_ "there".

<!--As if to say:

i.   "A gloom exists in the house."
ii.  "A type of confidence exists which is good and a type of confidence exists which is bad.
iii. "Reasons exist"
iv.  "A god exists."
-->

Expressing such sentences in Arabic can sometimes be tricky.
There is a modern tendency to use the [Parf makan]{.trn2} [هُنَاكَ]{.ar} and the [majhUl]{.trn2} verb [يُوجَدُ]{.ar}. <!-- as direct equivalents of the English "there" and "exists".-->
So one might find:

i.   [هُنَاكَ حَزَنٌ فِي ٱلْبَيتِ.]{.ar} or  
     [يُوجَدُ حَزَنٌ فِي ٱلْبَيتِ.]{.ar}
ii.  [هناك غضب يستحب وهناك غصب يكره.]{.ar}  or  
     [يوجد غضب يستحب ويوجد غصب يكره.]{.ar}
iii. [هُناك أسباب.]{.ar} or  
     [تُوجَدُ أسباب.]{.ar}  
iv.  [هناك إله.]{.ar} or  
     [يوجد إله.]{.ar}
v.   [هَل هناك طعام؟]{.ar} or  
     [هل يوجد طعام؟]{.ar}
v.   [نَعَمْ هناك طعام.]{.ar} or  
     [نَعَمْ يوجد طعام.]{.ar}

Sometimes in place of [هُنَاكَ]{.ar}, its synonym, [ثَمَّةَ]{.ar} is used.
These usages of [هُنَاكَ]{.ar}, [ثَمَّةَ]{.ar}, and [يُوجَدُ]{.ar} are foreign to Arabic and should generally be avoided.

In Classical Arabic, expressing such sentences falls under the category of sentences with indefinite subjects.
We have discussed this topic in chapter\ \@ref(chap-indef-subjects).

There are various strategies for expressing such sentences:

If, for example, there is a [jArr wa-majrUr]{.trn2}, or other [cibh jumlah]{.trn2} then it can readily be used as a [xabar]{.trn2} that precedes the [mubtadaE]{.trn2}. For example:

[فِي ٱلْبَيتِ حَزَنٌ.]{.ar}  
"In the house is gloom."

Sometimes, a [jArr wa-majrUr]{.trn2}, or other [cibh jumlah]{.trn2} is not original, but can readily be manufactured. 
For example, in the sentence, "There are reasons." the reasons must be for something, and that something can be used as a [xabar]{.trn2}:

[لِلْوَضْعِ أَسْبَابٌ.]{.ar}  
"For the situation, are reasons."

Similarly, a introductory sentence or [cibh jumlah]{.trn2} can be manufactured to pave the way for the main sentence. For example:

[الغَضَبُ غَضَبَانِ: غَضَبٌ مُسْتَحَبٌّ وَغَضَبٌ مَكْرُوهٌ.]{.ar}  
"Anger is (actually) two angers: an anger that is liked, and an anger that is disliked."

[مَنَ ٱلْغَضَبِ مَا يٌسْتَحَبُّ وَمَا يٌكْرَهُ.]{.ar}  
"From anger is that which is liked, that which is disliked."

Sometimes it hard to come up with any of the above solutions, as in the sentence: "There is a god."
Such sentences, if they are able to be converted to an interjection, may be expressed with the subject itself as a one word sentence:

[إِلَـٰهٌ!]{.ar}  
"[There is] a god!"

This solution should only be considered if the sentence makes sense as an interjection, and can not be used as a blanket solution. For example, in the exchange:

"Is there food?"  
"Yes, there is food."

One way to express this in Arabic is:

[هَلْ مِنْ طَعَامٍ؟]{.ar}  
[نَعَمْ، عِنْدَنَا طَعَامٌ.]{.ar}  

English also uses the word "there" with this existential meaning for sentences like:

i.  "There was a king."
ii. "There is no hope."

These sentences can be expressed in Arabuc without indefinite subjects. For example:

i.  [كَانَ مَلِكٌ.]{.ar}  
    This uses the _self-sufficient_ [كَانَ]{.ar}. (See section\ \@ref(self-sufficient-kaana).)

ii. [لَا أَمَلَ.]{.ar}  
    This uses the [nAfiyah lil-jins]{.trn2} [لَا]{.ar}. (See section\ \@ref(la-nafiyah-lil-jins).)

### Legitimate use of [هُنَاكَ]{.ar} and [يُوجَدُ]{.ar}

If, of course, a place is intended by "there" then there is no problem using [هُنَاكَ]{.ar} or its synonyms. For example:

[أَثَمَّ زَيْدٌ؟]{.ar}  
"Is Zayd there?"

Similarly, [يُوجَدُ]{.ar} may be used with no problem if the meaning "is (to be) found" is intended. For example:

[من قتل معاهدا لم يرح رائحة الجنة، وإن ريحها توجد من مسيرة أربعين عاماً]{.ar}

### Technical and scientific use of [يوجَد]{.ar}

Our above directive to avoid the use of [يوجد]{.ar} to mean "there is" holds for normal sentences.
Sometimes, however, a more technical meaning of "exists" is intended, especially in the language of science.
<!--
However, scholars, in developing branches of science, need to define terminology and use it in the precise manner which their science demands.
Historically, scholars have added on scientific meanings to existing words. There is no problem with this if done carefully and discriminately.
-->
In this case, [يوجد]{.ar} and its [ism mafeUl]{.trn2} [موجود]{.ar} may be used when needing to discuss the existence of something in a scientific text.
But such usage should be restricted to its domain, and should not, ideally, spill over to normal sentences, where a simple "there is" is intended.

While this concession can be granted to [يوجد]{.ar}, we find no such justifying circumstance for using [هناك]{.ar} existentially.


