# Verbal nouns

## Introduction

Every verb has a set of _verbal-nouns_ derived from it that, despite being nouns, have a verbal meaning to them. In some cases, a verbal nouns may be used in place of the verb from which it is derived, thereby adding a nuance in meaning.

This set of verbal-nouns is:

1. The doing verbal-noun
2. The doer verbal noun
3. the doee verbal noun

 The doing verbal noun

## Introduction

Consider the following form\ 1 verb:

| Root | Completed-action verb | Incomplete-action verb (u-state)|
|:--|:----|:-----|
|[ذهب]{.arroot} | [ذَهَبَ]{.ar} [pahaba]{.trn} "he went" | [يَذْهَبُ]{.ar} [yaphabu]{.trn} "he goes"|

The doing verbal-noun associated with this verb is [ذَهَابٌ]{.ar} [pahAbun]{.trn}. It denotes "the action of going", or simply "going". In this section we shall learn how this and other verbal-nouns are used.

Before we proceed, we present a new method to present a verb and its meaning in this book. Instead of giving the above table when presenting a verb, we will say:

[ذَهَبَ يَذْهَبُ ذَهَابًا]{.ar}  
[pahaba yaphabu pahAban]{.trn}  
"to go"

The completed-action verb for the singular masculine absent person "he", the corresponding incomplete-action verb, and their doing verbal-noun are given together, in sequence. The doing verbal-noun is given in the a-state, because of a usage that we shall learn in a later chapter, if [#allAh]{.trn2} wills. This is how verb definitions are traditionally found in Arabic dictionaries. And the English meaning is given using the dictionary definition, in this case, the phrase: "to go". 

## Patterns of the doing verbal-noun for form\ 1 verbs

The patterns of the doing verbal-noun for form\ 1 verbs are very variable. It is best to learn the doing verbal-noun when you learn a new verb. Having said that, there are some general trends which may be useful to keep in mind:

1. If the verb takes a direct doee, then the completed-action verb must necessarily be of the pattern [فَعَلَ]{.ar} [faeala]{.trn} or [فَعِلَ]{.ar} [faeila]{.trn} (because completed-action verbs of the pattern [فَعُلَ]{.ar} [faeula]{.trn} never take a direct doee). In this case:
   a. The doing verbal-noun for many verbs, in general, tends to be [فَعْلٌ]{.ar} [faelun]{.trn}. Examples:
      + [فَتَحَ يَفْتَحُ فَتْحًا]{.ar} [fataHa yafTahu fatHan]{.trn} "to open ([هـ]{.ar} s.th.)"
      + [أَخَذَ يَأْخُذُ أَخْذًا]{.ar} [Eaxapa yaExupu Eaxpan]{.trn} "to take ([هـ]{.ar} s.th.)"
      + [حَمِدَ يَحْمَدُ حَمْدًا]{.ar} [Hamida yaHmadu Hamdan]{.trn} "to praise ([ه]{.ar} s.o.)"
2. If the verb does not take a direct doee, then:
   a. If the completed-action verb is of the pattern [فَعِلَ]{.ar} [faeila]{.trn}, then:
      i. If the meaning of the verb does not fall under the cases ii., iii., and iv. (below), then the doing verbal-noun tends to be, in general, of the pattern [فَعَلٌ]{.ar} [faealun]{.trn}. Examples:
         + [تَعِبَ يَتْعَبُ تَعَبًا]{.ar} [taeiba yateabu taeaban]{.trn} "to become tired"
         + [جَزِعَ يَجْزَعُ جَزَعًا]{.ar} [jaziea yajzaeu jazaean]{.trn} "to be impatient"
         + [أَسِفَ يَأْسَفُ أَسَفًا]{.ar} [Easifa yaEsafu Easafan]{.trn} "to be sorrowful"
      ii. If, instead, the meaning of the verb denotes being a color, then the doing verbal-noun is usually of the pattern [فُعْلَةٌ]{.ar} [fuelatun]{.trn}. Examples:
          + [خَضِرَ يَخْضَرُ خُضْرَةً]{.ar} [xaDira yaxDaru xuDratan]{.trn} "to be green"
          + [سَمِرَ يَسْمَرُ سُمْرَةً]{.ar} [xaDira yaxDaru xuDratan]{.trn} "to be brown"
      iii. If, instead, the meaning of the verb denotes some work or effort, then the doing verbal-noun tends to be of the pattern [فُعُولٌ]{.ar} [fueUlun]{.trn}. Example:
           + [قَدِمَ يَقْدَمُ قُدُومًا]{.ar} [qadima yaqdamu qudUman]{.trn} "to arrive"
      iv. If, instead, the meaning of the verb denotes some static quality, then the doing verbal-noun tends to be of the pattern [فُعُولَةٌ]{.ar} [fueUlatun]{.trn}. Example:
          + [يَبِسَ يَيْبَسُ يُبُوسَةٌ]{.ar} [yabisa yaybasu yubUsatun]{.trn} "to be dry"
   a. If the completed-action verb is of the pattern [فَعَلَ]{.ar} [faeala]{.trn}, then:
      i. If the meaning of the verb does not fall under the cases ii., iii., and iv. (below), then the doing verbal-noun tends to be, in general, of the pattern [فُعُولٌ]{.ar} [fueUlun]{.trn}. Examples:
         + [قَعَدَ يَقْعُدُ قُعُودًا]{.ar} [qaeada yaqeudu queUdan]{.trn} "to sit, stay back"
         + [سَجَدَ يَسْجُدُ سُجُودًا]{.ar} [sajada yasjudu sujUdan]{.trn} "to prostrate down"
         + [خَضَعَ يَخْضَعُ خُضُوعًا]{.ar} [xaDaea yaxDaeu xuDUean]{.trn} "to be humble"
      ii. If, instead, the meaning of the verb denotes an ailment, then the doing verbal-noun is usually of the pattern [فُعَالٌ]{.ar} [fueAlun]{.trn}. Examples:
          + [سَعَلَ يَسْعُلُ سُعَالً]{.ar} [saeala yasealu sueAlan]{.trn} "to cough"
      iii. If, instead, the meaning of the verb denotes travelling, then the doing verbal-noun is usually of the pattern [فَعِيلٌ]{.ar} [faeIlun]{.trn}. Examples:
           + [رَحَلَ يَرْحَلُ رَحِيلًا]{.ar} [raHala yarHalu raHIlan]{.trn} "to depart"
      iv. If, instead, the meaning of the verb denotes a sound, then the doing verbal-noun is usually of the pattern [فَعِيلٌ]{.ar} [faeIlun]{.trn} or [فُعَالٌ]{.ar} [fueAlun]{.trn}, or both. Examples:
          + [صَرَخَ يَصْرُخُ صَرِيخًا وَصُرَاخًا]{.ar} [Saraxa yaSruxu SarIxan waSurAxan]{.trn} "to scream"
3. If the verb denotes a craft or a profession or a rank, then the doing verbal-noun is often of the pattern [فِعَالَةٌ]{.ar} [fieAlatun]{.trn}. Examples:
   + [تَجَرَ يَتْجُرُ تِجَارَةً]{.ar} [tajara yatjuru tijAratan]{.trn} "to trade"
   + [أَمِرَ يَأْمَرُ إِمَارَةً]{.ar} [Eamira yaEmaru EimAratan]{.trn} "to be a commander"
4. If the completed-action verb is of the pattern [فَعُلَ]{.ar} [faeula]{.trn}, then the doing verbal noun tends to be of the pattern [فُعُولَةٌ]{.ar} [fueUlatun]{.trn} or [فَعَالَةٌ]{.ar} [faeAlatun]{.trn}. Examples:
   + [صَعُبَ يَصْعُبُ صُعُوبَةً]{.ar} [Saeuba yaSeubu SueUbatan]{.trn} "to be difficult"
   + [شَجُعَ يَشْجُعُ شَجَاعَةً]{.ar} [cajuea yacjueu cajAeatan]{.trn} "to be brave"

As mentioned earlier, these are only general trends and there are many verbs that have doing verbal-nouns which don't fall under the above rules.

## Usage of the doing verbal-noun

### State and definiteness

The doing verbal noun has properties of a noun, like state and definiteness. But it gives the meaning of a verb. For example, consider the verb [أَكَلَ يَأْكُلُ أَكْلًا]{.ar} [Eakala yaEkulu Eaklan]{.trn} "to eat". We can use its doing verbal noun in a sentence like this:

[فَرَغَ زَيْدٌ مِنَ ٱلْأَكْلِ.]{.ar}  
[faraga zaydun mina -lEakli.]{.trn}  
"Zayd got done with eating."

Note how the doing verbal noun [ٱلْأَكْلِ]{.ar} [EalEakli]{.trn} gives the meaning of the action of the verb "eating". But since it is a noun, it obeys the rules for nouns, like being in the i-state when preceded by the preposition [مِنْ]{.ar} [min]{.trn}.

Another point worth noting is that we have made it definite by saying [ٱَلْأَكْلِ]{.ar} [EalEakli]{.trn} instead of saying [أَكْلٍ]{.ar} [Eaklin]{.trn} for the meaning of "eating". This is because, as we explained in section 
\@ref(usage-of-definite-and-indefinite-nouns),
the definite noun is usually used in Arabic to give a general meaning, where in English we would not use "the". This may be a good time to re-read that section.

Having said that, the indefnite doing verbal-noun may be used too, and this will give the meaning of "a certain", or "a specific". For example, with the verb [عَمِلَ يَعْمَلُ عَمَلًا]{.ar} [eamila yaemalu eamalan]{.trn} "to work", we can say:

[فَرَغَ مِنْ عَمَلٍ صَعْبٍ.]{.ar}  
[faraga min eamalin Saebin.]{.trn}  
"He got done with a [certain] difficult work."

### With a doer

A doer may be used with the doing verbal-noun to show who is doing the action. In this case, the doing verbal-noun and the doer are usually placed in a noun-chain. The doing verbal-noun shall be the first noun and the doer shall be in the i-state as the second noun in the noun-chain. For example, consider the verb [قَرَأَ يَقْرَأُ قِرَاءَةً]{.ar} [qaraEa yaqraEu qirAEatan]{.trn} "to read". We can say:

[سَمِعْتُ قِرَاءَةَ زَيْدٍ.]{.ar}  
[samietu qirAEata zaydin.]{.trn}  
"I heard Zayd's reading."

The doer may similarly be a pronoun, in which case, as usual, attached pronouns are used. So we can say:

[سَمِعْتُ قِرَاءَتَهُ.]{.ar}  
[samietu qirAEatahu.]{.trn}  
"I heard his reading."

### With an indirect doee

If a verb uses a particular preposition with indirect doees, and the doing verbal-noun of that verb is to be used with an indirect doee, then that same preposition is used with the doing verbal-noun.

For example the verb [ذَهَبَ يَذْهَبُ ذَهَابًا]{.ar} [pahaba yaphabu pahAban]{.trn} "to go" is used with the preposition [إِلَىٰ]{.ar} [EilA]{.trn} "to" with an indirect doee to give the place to which the doer is going. This same preposition is then used with the doing verbal noun, thus:

[تَعِبْتُ مِنَ ٱلذَّهَابِ إِلَىٰ ٱلْمَدِينَةِ  ٱلْبَعِيدَةِ.]{.ar}  
[taeibtu mina -ppahAbi Eila -lmadInati -lbaeIdati.]{.trn}  
"I became tired from going to the far city."

If a doer is used along with the indirect doee, then the doer shall be placed in a noun chain with the doer verbal-noun, as explained in the previous section. For example,

[حَزِنْتُ مِنْ ذَهَابِ زَيْدٌ إِلَىٰ مَدِينَةٍ بَعِيدَةٍ.]{.ar}  
[Hazintu min pahAbi zaydin EilA madInatin baeIdatin.]{.trn}  
"I became sad from Zayd's going to a far city."

### With a direct doee

If a verb takes a direct doee, and we wish to use the direct doee with the verb's doing verbal noun, then we may deal with it in one of three ways:

#### The direct doee in the i-state in a noun-chain with the doing verbal noun

In the first method, the direct doee is in the i-state as the second noun in a noun-chain with the doing verbal-noun. This method is used when the doer of the verbal noun is not mentioned with the doing verbal-noun, or when there is no other phrase between the doing verbal-noun and the direct doee. For example,

[فَرَغَ زَيْدٌ مِنْ قِرَاءَةِ ٱلْكِتَابِ.]{.ar}  
[faraga zaydun min qirAEati -lkitAbi.]{.trn}  
"Zayd got done with reading the book."

In this sentence, [ٱَلْكِتَبِ]{.ar} [EalkitAbi]{.trn} "the book" is the direct doee of the doing verbal-noun [قِرَاءَةِ]{.ar} [qirAEati]{.trn} "reading". The doer [زَيْدٌ]{.ar} [zaydun]{.trn} "Zayd" is only mentioned in the beginning of the sentence but not again with the doing verbal-noun. Therefore, the direct doee [ٱَلْكِتَبِ]{.ar} [EalkitAbi]{.trn} "the book" is allowed to be put in a noun-chain with the doing verbal noun thus: [قِرَاءَةِ ٱلْكِتَابِ]{.ar}  [qirAEati -lkitAbi]{.trn}  "reading the book".

Instead of a noun, the direct doee may be a pronoun instead. For example,

[قَرَأ زَيْدٌ ٱلْكِتَابَ فَفَرَغَ مِنْ قِرَاءَتِهِ.]{.ar}  
[qaraEa zayduni -lkitAba fafaraga min qirAEatihi]{.trn}  
"Zayd read the book, and then he got done with reading it."

Remember from the previous section, that a doer is handled in the same way with a doing verbal-noun by placing it in a noun-chain with the doing verbal-noun. So how do we know whether the second noun in a noun-chain with a doing verbal-noun is a doer or a doee? Well, for many verbs the meaning of the verbal-noun and the noun is sufficient. For example, in the phrase [قِرَاءَةِ ٱلْكِتَابِ]{.ar} [qirAEati -lkitAbi]{.trn} "reading the book", the meaning of "reading" makes it clear that [ٱَلْكِتَابِ]{.ar} [EalkitAbi]{.trn} can only be a doee, because a book can't be the one doing the reading.

But there are some verbs, however, where the meaning of the verbal-noun itself is not sufficient to tell us whether the noun following it in a noun-chain is a doer or a doee. Consider the verb 
<!--[قَتَلَ يَقْتُلُ قَتْلًا]{.ar} [qatala yaqtulu qatlan]{.trn} "to kill ([ه]{.ar} s.o.)".-->
[ضَرَبَ يَضْرِبُ ضَرْبًا]{.ar} [Daraba yaDribu Darban]{.trn} "to beat ([ه]{.ar} s.o.)". If we form a noun-chain using its doing verbal-noun, thus: [ضَرْبُ زَيْدٍ]{.ar} [Darbu zaydin]{.trn}, we cannot know whether Zayd is the doer (the one doing the beating), or the doee (the one getting beaten). In this case, we will need more context to help us determine whether Zayd is the doer or the doee. Here are a few sentences that may help illustrate this point:

[ضَرَبَ زَيْدٌ عَمْرًا. سَمِعَ ٱلْأَبُ **ضَرْبَ زَيْدٍ** فَغَضِبَ عَلَيْهِ. فَنَدِمَ زَيْدٌ مِنْ **ضَرْبِ عَمْرٍو**.]{.ar}  
[Daraba zaydun eamran. samiea -lEabu Darba zaydin fagaDiba ealayhi. fa nadima zaydun min Darbi eamrin.]{.trn}  
"Zayd beat [e#amr]{.trn2}. The father heard Zayd's beating so he became angry with him. So, Zayd became remorseful of beating [e#amr]{.trn2}."

We can see that the meaning of the sentences help us determine that in the phrase
[ضَرْبَ زَيْدٍ ]{.ar}
[Darba zaydin]{.trn}, Zayd is the doer, and in 
[ضَرْبِ عَمْرٍو]{.ar}
[Darbi eamrin]{.trn}, [e#amr]{.trn2} is the doee.

<!-- The masdar naSr may also be useful here:  نصر الله. نصر العبد-->

#### The direct doee in a-state following the doing verbal-noun

The second way to deal with a direct doee and a doing-verbal noun is to put it in the a-state after the doing verbal-noun. This is usually done when the doer is mentioned with the doing verbal-noun in a noun-chain with it. The direct doee is then placed after the doer in the a-state. For example, we can re-word the previous example:

<!--[سَمِعْتُ ضَرْبَ زَيْدٍ عَمْرًا.]{.ar}  
[samietu Darba zaydin eamran.]{.trn}  
"I heard Zayd's beating [e#amr]{.trn2}."-->

[ضَرَبَ زَيْدٌ عَمْرًا. سَمِعَ ٱلْأَبُ **ضَرْبَ زَيْدٍ عَمْرًا** فَغَضِبَ عَلَيْهِ. فَنَدِمَ زَيْدٌ مِنْ **ضَرْبِهِ عَمْرًا**.]{.ar}  
[Daraba zaydun eamran. samiea -lEabu Darba zaydin eamran fagaDiba ealayhi. fa nadima zaydun min Darbihi eamran.]{.trn}  
"Zayd beat [e#amr]{.trn2}. The father heard Zayd's beating [e#amr]{.trn2} so he became angry with him. So, Zayd became remorseful of his beating [e#amr]{.trn2}."

