# Calling out to someone

## Introduction

When directly addressing soneone in Arabic and calling out to him by name, the particle [يَا]{.ar} [yA]{.trn} is usually prefixed to the person's name. For example,

[ٱَلسَّلَامُ عَلَيْكُمْ يَا زَيْنَبُ.]{.ar}  
[EassalAmu ealaykum yA zaynabu.]{.trn}  
"Peace be upon you, O Zaynab."

There are different rules regarding the state markings of the noun following [يَا]{.ar} [yA]{.trn} and we will describe them in the following sections.

## Calling out to specific persons

### Using single word personal names

When a specific person is called out to, and the name used to call him consists of a single word, then that word shall be in the u-state. The sentence above is an example of this rule where the name [زَينَبُ]{.ar} [zaynabu]{.trn} "Zaynab" is in the u-state.

If the word would have an [n]{.trn}-mark, then the [n]{.trn}-mark is dropped. So, for example, the name [زَيْدٌ]{.ar} [zaydun]{.trn} "Zayd" usually has an [n]{.trn}-mark. But when used for being called out to, the [n]{.trn}-mark is dropped and it becomes:

[ٱَلسَّلَامُ عَلَيْكُمْ يَا زَيْدُ.]{.ar}  
[EassalAmu ealaykum yA zaydu.]{.trn}  
"Peace be upon you, O Zayd."

### Using single word indefinite common nouns

The examples above show the person being called out to using a personal name. Instead of a personal name, a common noun can also be used with the same rule. Examples:

[ٱَلسَّلَامُ عَلَيْكُمْ يَا غُلَامُ.]{.ar}  
[EassalAmu ealaykum yA gulAmu.]{.trn}  
"Peace be upon you, O you boy."

[ٱَلسَّلَامُ عَلَيْكُمْ يَا جَارِيَةُ.]{.ar}  
[EassalAmu ealaykum yA jAriyatu.]{.trn}  
"Peace be upon you, O you girl."

In English, we have shown that a specific person is being called using the word "you", e.g., "O you boy". Duals and plurals are also allowed, again with the same rule:

[يَا رِجَالُ، قَدْ حَدَثَ أَمْرٌ.]{.ar}  
[yA rijAlu qad Hadava Eamrun.]{.trn}  
"O you men, a matter has occurred."

Note how the word [رِجَالُ]{.ar} [rijAlu]{.trn} "men" does not have an [n]{.trn}-mark because the word is used to call out to the specific persons.

Similarly,

[يَا لَاعِبَانِ بَدَأْتُمَا ٱللَّعِبَ وَمَا فَعَلْتُمَا ٱلْعَمَلَ.]{.ar}  
[yA lAeibAni badaEtuma -llaeiba wamA faealtuma -leamal.]{.trn}  
"O you players~2~, you have started playing and you have not done the work."

### Using single word definite common nouns

When using a common noun to call out to a person, especially if the common noun is a title, it is often desired to make the common noun definite with [ٱَلْ]{.ar}. In this case, the particle [يَا]{.ar} [yA]{.trn} is modified to [أَيُّهَا]{.ar} [EayyuhA]{.trn}, or sometimes [يَا أَيُّهَا]{.ar} [yA EayyuhA]{.trn}. Examples:

[يَا أَيُّهَا ٱلْأُسْتَاذُ، قَدْ فَعَلْتُ ٱلْوَاجِبَ.]{.ar}  
[yA Eayyuha -lEustApu, qad faealtu -lwAjiba]{.trn}  
"O you the Professor, I have done the obligatory [work]."

[أَنَا سَقِيمٌ أَيُّهَا ٱلطَّبِيبُ.]{.ar}  
[Eana saqImun, Eayyuha -TTabIbu.]{.trn}  
"I am ill, O you the Doctor."

If the person being called out to is feminine, then [أَيُّهَا]{.ar} [EayyuhA]{.trn} is modified to [أَيَّتُهَا]{.ar} [EayyatuhA]{.trn}. For example:

[أَيَّتُهَا ٱلْمُعَلِّمَةُ، هَـٰذَا كِتَابِي.]{.ar}  
[Eayyatuha -lmueallimatu, hApA kitAbi.]{.trn}  
"O you the teacher~f~, this is my book."


### Using multiple words

The above discussion pertains to calling out to the addressed person with a single word. Often times a person's name may consist of multiple words. For example:

+ [عَبْدُ ٱللَّـٰهِ]{.ar}  
  [eabdu -llAhi]{.trn}  
  "[e#abd #allAh]{.trn2}"

+ [أَبُو بَكْرٍ]{.ar}  
  [EabU bakrin]{.trn}  
  "[#abU #bakr]{.trn2}"

+ [صَلَاحُ ٱلدِّينِ]{.ar}  
  [SalAHu -ddIni]{.trn}  
  "[#salAH ad-#dIn]{.trn2}"

In this case, then instead of the u-state, the word is put into the a-state. Furthermore, the [n]{.trn}-mark, if any, is preserved. Examples:

[مَا عَرَفْتُ ذَ ٰلِكَ ٱلرَّجُلَ، يَا عَبْدَ ٱللَّـٰهِ.]{.ar}  
[mA earaftu pAlika -rrajula, yA eabda -llAhi.]{.trn}  
"I have not recognized that man, O [e#abd #allAh]{.trn2}."

[يَا أَبَا بَكْرٍ، أَنْتَ رَجُلٌ كَرِيمٌ.]{.ar}  
[yA EabA bakrin, Eanta rajulun karImun]{.trn}  
"O [#abU #bakr]{.trn2}, You are a noble man."

[يَا صَلَاحَ ٱلدِّينِ، صَبَرْتَ فَنَصَرَكَ ٱللَّـٰهُ.]{.ar}  
[yA SalAHa -ddIni, Sabarta fanaSaraka -llAhu.]{.trn}  
"O [#salAH ad-#dIn]{.trn2}, you were patient so [#allAh]{.trn2} gave you victory."


If, instead of a personal name, a noun phrase consisting of multiple words is used to call out to a person, then in this case as well, the first noun shall be in the a-state. Examples:

[يَا أَمِيرَ ٱلْمُؤمِنِينَ، قَدْ حَضَرَ ٱلْقَوْمُ.]{.ar}  
[yA EamIra -lmuEminIna, qad HaDara -lqawmu.]{.trn}  
"O Commander of the Believers, the people are present."

[يَا ٱبْنَ أَخِي، قَدْ سَقَطَ قَلَمُكَ عَلَى ٱلْأَرْضِ.]{.ar}  
[ya -bna EaxI, qad saqaTa qalamuka.]{.trn}  
"O my nephew, your pen has fallen on the ground."

[يَا تَلَامِيذَ ٱلْمَدْرَسَةِ، ٱلْعِلْمُ أَمَانَةٌ.]{.ar}  
[yA talAmIpa -lmadrasati, -leilmu EamAnatun.]{.trn}  
"O pupils of the school, knowledge is a trust."

When multiple words are used to call out to a person, the second word in the noun-chain may be a pronoun. Here too, the first noun shall be in the a-state. Examples:

[يَا أَبانا]{.ar}  
[yA EabAnA]{.trn}  
"O our father"

## Calling out to unspecified persons

All the discussion so far has pertained to calling out to specific persons. So for example, when you say,

<!--[يَا ظَالِمُ، عَذَابُ ٱللَّـٰهِ وَاقِعٌ.]{.ar}  -->
[يَا مُسْلِمُ، نَصْرُ ٱللَّـٰهِ قَرِيبٌ.]{.ar}  
[yA muslimu, naSru -llAhi qarIbun.]{.trn}  
"O you Muslim, the victory of [#allAh]{.trn2} is near."

then you are addressing a specific Muslim, who is perhaps in front of you. 

If an unspecified person or persons are being called out, then the word used to call out is put into the a-state. Furthermore, the [n]{.trn}-mark, if any, is preserved. So if you want to address any unspecific Muslim, you will say:

[يَا مُسْلِمًا، نَصْرُ ٱللَّـٰهِ قَرِيبٌ.]{.ar}  
[yA musliman, naSru -llAhi qarIbun.]{.trn}  
"O [any] Muslim, the victory of [#allAh]{.trn2} is near."

If multiple words are used, whether or not the person called out to is specific or unspecified, then too the first noun is put in the a-state.

[يَا لَاعِبِي لُعَبٍ، ٱلْوَقْتُ ثَمِينٌ.]{.ar}  
[yA lAeibI lueabini, -lwaqtu vamInun.]{.trn}  
"O [any] players of games, time is precious."

## Omitting [يَا]{.ar} [yA]{.trn}

When calling out to someone, it is permissible to omit the [يَا]{.ar} [yA]{.trn}, especially when the person being called is very near. So, instead of saying,

[يَا زَيْدُ، سُؤالُكَ جَيِّدٌ.]{.ar}  
[yA zaydu, suEAluka jayyidun.]{.trn}  
"O Zayd, your question is excellent."

it is permissible to say:

[زَيْدُ، سُؤالُكَ جَيِّدٌ.]{.ar}  
[zaydu, suEAluka jayyidun.]{.trn}  
"Zayd, your question is excellent."

Note that even when [يَا]{.ar} [yA]{.trn} is ommitted the name [زَيْدُ]{.ar} [zaydu]{.trn} "Zayd" is in the u-state without any [n]{.trn}-mark.

This usage is especially common when supplicating to [#allAh]{.trn2} with the word [رَبٌّ]{.ar} [rabbun]{.trn} "lord", to emphasize the closeness of [#allAh]{.trn2} to the supplicator. For example,

[رَبَّنا لَكَ ٱلْحَمْدُ.]{.ar}  
[rabbanA laka -lHamdu.]{.trn}  
"Our Lord, for you is [all] praise."

## Shortening the attached pronoun [ي]{.ar} [I]{.trn} "my"

When calling someone with the pronoun "my", for example "O my people", it is common to shorten the attached pronoun [ي]{.ar} [I]{.trn} "my" to an [i]{.trn}-mark [◌ِ]{.ar}. So while the following is permissible,

[يَا قَوْمِي]{.ar}  
[yA qawmI]{.trn}  
"O my people"

it is more common to say:

[يَا قَوْمِ]{.ar}  
[yA qawmi]{.trn}  
"O my people"

This usage is especially common when supplicating to [#allAh]{.trn2} with the phrase [رَبِّ]{.ar} [rabbi]{.trn} "my Lord".

## Calling out to [#allAh]{.trn2} by name

When calling out to [#allAh]{.trn2} by name, it is permissible to prefix the name [#allAh]{.trn2} with [يَا]{.ar}. So we can say:

[يَا أَللَّـٰهُ]{.ar}  
[yA EallAhu]{.trn}
"O [#allAh]{.trn2}"

Note that the word [أَللَّـٰهُ]{.ar} [EallAhu]{.trn} now has a regular [hamzah]{.trn} [أ]{.ar} instead of a connecting [hamzah]{.trn} [ٱ]{.ar}.

However, instead of saying [يَا أَللَّـٰهُ]{.ar} [yA EallAhu]{.trn} for "O [#allAh]{.trn2}", it is in fact more common to use a special word:

[ٱَللَّـٰهُمَّ]{.ar}  
[EallAhumma]{.trn}  
"O [#allAh]{.trn2}"

Examples:

[ٱَللَّـٰهُمَّ أَنْتَ ٱلسَّلَامُ وَمِنْكَ ٱلسَّلَامُ.]{.ar}  
[EallAhumma Eanta -ssalAmu waminka -ssalAmu.]{.trn}  
"O [#allAh]{.trn2}, You are Peace and from You is peace."

[ٱَللَّـٰهُمَّ أَنْتَ ٱلصَّاحِبُ فِي ٱلسَّفَرِ.]{.ar}  
[EallAhumma Eanta -SSAHibu fi -ssafari.]{.trn}  
"O [#allAh]{.trn2}, You are the companion in the journey."

