# Broken plurals

## Introduction

In the previous chapter we introduced sound plurals, which are formed by appending suffixes to the singular noun. The singular noun in these plurals remains, more or less, intact when forming these plurals. The sound plurals correspond to English regular plurals which are formed by appending "s" to the singular noun. However, English has some plurals that are not formed by adding the plural ending "s". Here are some examples,

| Singular | Plural |
|:-----------|:-----------|
| man        | men        |
| woman      | women      |
| child      | children   |
| mouse      | mice       |

In these plurals, the singular noun is altered to form the plural.

Arabic also forms such plurals. They are called _broken_ plurals because the singular noun is not kept intact but its structure is, in most cases, altered, or "broken-up" when forming the plural.

While English only forms such plurals for a handful of nouns, Arabic forms broken plurals for many nouns.

## The broken plural and patterns

Remember that Arabic nouns are derived from roots which are usually three, but sometimes four or more, letters. Also that three-letter roots and word patterns are exemplified using the template root [فعل]{.arroot}. And that four-letter roots are exemplified using the template root [فعلل]{.arroot}. For example, the word [رَجُلٌ]{.ar} [rajulun]{.trn} has the root [رجل]{.arroot} and is of the pattern [فَعُلٌ]{.ar} [faeulun]{.trn}. 

Arabic broken plurals fall into patterns. The plural of [رَجُلٌ]{.ar} [rajulun]{.trn} is [رِجَالٌ]{.ar} [rijAlun]{.trn}. The pattern of this plural is [فِعَالٌ]{.ar} [fieAlun]{.trn}, which is a common plural pattern. Another broken plural with this pattern is [جِبَالٌ]{.ar} [jibAlun]{.trn} "mountains" plural of [جَبَلٌ]{.ar} [jabalun]{.trn} "a mountain".

Note that, plurals of the pattern [فِعَالٌ]{.ar} [fieAlun]{.trn} are fully-changing so they have an [n]{.trn}-mark when indefinite, which will depend on the state of the plural. Here is an example sentence:

[صَعَدَ رِجَالٌ جًبَالًا]{.ar}  
[Saeada -rrijAlu jibAlan.]{.trn}  
"The men went up the mountain."

There are other plural patterns which are non-fully-changing, for example, [أَغْنِيَاءُ]{.ar} [EagniyAEu]{.trn}, plural of [غَنِيٌ]{.ar} [ganiyyun]{.trn} "rich", of the pattern [أَفْعِلَاءُ]{.ar} [EafeilAEu]{.trn}.  Note that this plural pattern ends with [اء]{.ar} which is external to the root [فعل]{.arroot}. [اء]{.ar}, [ة]{.ar}, and [ىٰ]{.ar}, when external to the root, are feminine markers for singular nouns, but not for plural nouns.  However, just like for singular nouns, when a broken plural ends with [اء]{.ar} or [ىٰ]{.ar} which is external to its root, the broken plural will be non-fully-changing.

Unfortunately, there is usually not much relation between the pattern of the singular and the pattern of the plural. So you should memorize the plural of a noun with its singular.

## Common patterns for the broken plural

Here are some of the more common broken plural patterns:

Pattern | Example
:-------------|:---------------------------------
[أَفْعَالٌ]{.ar} [EafeAlun]{.trn} | [أَعْمَالٌ]{.ar} [EaemAlun]{.trn} "deeds" plural of [عَمَلٌ]{.ar} [eamalun]{.trn} "a deed"
[فُعُولٌ]{.ar} [fueUlun]{.trn}   | [قُلُوبٌ]{.ar} [qulUbun]{.trn} "hearts" plural of [قَلْبٌ]{.ar} [qalbun]{.trn} "a heart"
[فِعَالٌ]{.ar} [fieAlun]{.trn}   | [رِجَالٌ]{.ar} [rijAlun]{.trn} "men" plural of [رَجُلٌ]{.ar} [rajulun]{.trn} "a man"
[فُعُلٌ]{.ar} [fueulun]{.trn}    | [كُتُبٌ]{.ar} [kutubun]{.trn} "books" plural of [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book"
[فَعْلَىٰ]{.ar} [faelA]{.trn} (non-fully-changing)    | [أَسْرَىٰ]{.ar} [EasrA]{.trn} "captives" plural of [أَسِيرٌ]{.ar} [EasIrun]{.trn} "a captive"
[فُعَلَاءُ]{.ar} [fueAlAEu]{.trn} (non-fully-changing) | [عُلَمَاءُ]{.ar} [eulAmAEu]{.trn} "(male) scholars" plural of [عَالِمٌ]{.ar} [eAlimun]{.trn} "a (male) scholar"
[أَفْعِلَاءُ]{.ar} [EafeilAEu]{.trn} (non-fully-changing) | [أَغْنِيَاءُ]{.ar} [EagniyAEu]{.trn} "rich"
[فُعْلَانٌ]{.ar} [fuelAnun]{.trn} | [بُلْدَانٌ]{.ar} [buldAnun]{.trn} "countries" plural of [بَلَدٌ]{.ar} [baladun]{.trn} "a country"
[فَعَالِلُ]{.ar} [faeAlilu]{.trn} | a

<!-- should mafAeilu be separate from faeAlilu? -->


## Existence of broken plurals for types of nouns

The use of broken plurals is a little complicated, and their use in poetry and rhetorical style can be somewhat different from normal usage. Here we will describe whether they are found, and how to use them for the different noun categories according to normal usage.

1. Designative nouns:
   a. Male rational beings: Very commonly found. Examples:
      + [غِلْمَانٌ]{.ar} [gilmAnun]{.trn} "boys" plural of [غُلَامٌ]{.ar} [gulAmun]{.trn} "a boy".
      + [عُلَمَاءُ]{.ar} [eulamAEu]{.trn} "(male) scholars" plural of [عَالِمٌ]{.ar} [eAlimun]{.trn} "a (male) scholar".
   b. Female rational beings: Uncommon but not unfound. Examples:
      + [إِمَاءٌ]{.ar} [EimAEun]{.trn} "slave-women" plural of [أَمَةٌ]{.ar} [Eamatun]{.trn} "a slave-woman"
      + [حَرَائِرُ]{.ar} [HarAEiru]{.trn} "free-women" plural of [حُرَّةٌ]{.ar} [Hurratun]{.trn} "a free-woman".

      Typically, though, female rational beings will use the [At]{.trn} sound plural, for example [عَالِمَاتٌ]{.ar} [eAlimAtun]{.trn} plural of [عَالِمَةٌ]{.ar} [eAlimatun]{.trn} "a (female) scholar".
   c. Non-rational beings (both masculine and feminine): very common. Examples:
      + [هِرَرٌ]{.ar} [hirarun]{.trn} "cats" plural of [هِرَّةٌ]{.ar} [hirratun]{.trn} "a cat".
      + [سُيُوفٌ]{.ar} [suyUfun]{.trn} "swords" plural of [سَيْفٌ]{.ar} [sayfun]{.trn} "a sword".
2. Descriptive nouns:
   a. Male rational beings: Very common. Examples:
      + [أَغْنِيَاءُ]{.ar} [EagniyAEu]{.trn}, plural of [غَنِيٌ]{.ar} [ganiyyun]{.trn} "rich (masc.)".
      + [كِرَامٌ]{.ar} [kirAmun]{.trn}, plural of [كَرِيمٌ]{.ar} [karImun]{.trn} "noble, generous (masc.)".
      + [ٱَلرِّجَالُ ٱلْأَغْنِيَاءُ كِرَامٌ.]{.ar}  
        [EarrijAlu -lEagniyAEu kirAmun.]{.trn}  
        "The rich men are generous."
   b. Female rational beings: Apart from a few exceptions, this is almost unused in normal usage. The [At]{.trn} plural is used instead, for example [ عَالِمَاتٌ كَرِيمَاتٌ]{.ar} [eAlimAtun karImAtun]{.trn} "noble (female) scholars".
   c. Non-rational beings: also unused in normal usage. The [At]{.trn} plural is used instead, as we'll see soon, if Allah wills. REMOVE: The feminine singular is used for describers in a noun-phrase or for descrptive nouns in the information of a sentence. The [At]{.trn} plural is used otherwise. Example:  
      [ٱَلْكُتُبُ ٱلْكَبِيرَةُ ثَقِيلَةٌ وَٱلصَّغِيرَاتُ خَفِيفَةٌ.]{.ar}  
      [Ealkutubu -lkabIratu vaqIlatun wa-SSagIrAtu xafIfatun.]{.trn}  
      "The big books are heavy and the small ones are light."

## Existence of more than one broken plural for a noun

Some nouns have multiple broken plurals that can be used, more or less, interchangeably. For example:

+ [طُلَّابٌ]{.ar} [TullAbun]{.trn} and [طَلَبَةٌ]{.ar} [Talabatun]{.trn} plurals of [طَلِبٌ]{.ar} [Talibun]{.trn} "a (male) student".
+ [شُهُورٌ]{.ar} [cuhUrun]{.trn} and [أَشْهُرٌ]{.ar} [Eachurun]{.trn} plurals of [شَهْرٌ]{.ar} [cahrun]{.trn} "a month".

In some cases one of these plurals may be used to indicate a larger quantity and the other a smaller quantity, but this rule is not worth worrying about much for now.

Other nouns have multple broken plurals too but here each broken plural is used for a different meaning. For example:

+ [أَمْرٌ]{.ar} [Eamrun]{.trn} can mean both :
  1. "a matter, an affair", pluralized as [أُمُورٌ]{.ar} [EumUrun]{.trn} "matters, affairs"
  2. "a command, an order", pluralized as [أَوَامِرُ]{.ar} [EawAmiru]{.trn} (non-fully-changing) "commands, orders".  

## Co-existence of sound and broken plurals for the same noun

There are many nouns which can be pluralized with both sound plurals and broken plurals. For example,

+ [عَالِمٌ]{.ar} [eAlimun]{.trn} "a (male) scholar" can be pluralized using the sound [Un]{.trn} plural as [عَالِمُونَ]{.ar} [eAlimUna]{.trn} as well as with the broken plural [عُلَمَاءُ]{.ar} [eulamAEu]{.trn}.
+ [كَافِرٌ]{.ar} [kAfirun]{.trn} "a (male) disbeliever" can be pluralized using the sound [Un]{.trn} plural as [كَافِرُونَ]{.ar} [kAfirUna]{.trn} as well as with the broken plurals [كُفَّارٌ]{.ar} [kuffArun]{.trn} and [كَفَرَةٌ]{.ar} [kafaratun]{.trn}.

In fact, all masculine descriptive nouns  that form their feminine by the addition of [ة]{.ar} may be pluralized with the [Un]{.trn} plural in addition to any broken plurals that they might have. However, this [Un]{.trn} plural may only be used with male rational beings. For example,

+ [كَبِيرٌ]{.ar} [kabIrun]{.trn} "big (masc.)" forms its feminine with the addition of [ة]{.ar}: [كَبِيرَةٌ]{.ar} [kabIratun]{.trn}. Therefore it can be pluralized with the sound [Un]{.trn} plural [كَبِيرُونَ]{.ar} (when referring to male rational beings) as well as its broken plural [كِبَارٌ]{.ar} [kibArun]{.trn}.
+ [غَضْبَانُ]{.ar} [gaDbAnu]{.trn} "very angry (masc.)" forms its feminine without [ة]{.ar}: [غَضْبَىٰ]{.ar} [gaDbA]{.trn}. Therefore it will not form the sound [Un]{.trn} plural and it may have only its broken plural [غِضَابٌ]{.ar} [giDabun]{.trn}.

It is also possible to use both sound [Un]{.trn} and broken plurals in the same phrase and sentence. For example,

[ٱَلرِّجَالُ ٱلْأَغْنِيَاءُ كَرِيمُونَ]{.ar}  
[EarrijAlu -lEagniyAEu karImUna.]{.trn}  
"The rich men are generous."

For now, we recommend that you prefer to use the broken plural when possible, even if a word can form the sound [Un]{.trn} plural. Although more difficult for the beginner, this is more common in normal usage. In the vocabulary lists that we provide, we will typically not provide sound [Un]{.trn} plurals, even if they are technically possible, unless they are commonly used.

## Using verbs and pronouns with plurals

### Plurals of rational beings

In the previous chapter we gave the rule of using doer-modifications with verbs for sound plurals of rational being doers. The rule is similar for broken plurals of rational being doers:

1. If the broken plural doer is placed before the verb or is not mentioned, then the plural doer-modification corresponding to the gender of the singular doer is employed. For example, [ٱَلرِّجَالُ ذَهَبُوا.]{.ar} "The men went.", [ٱَلنِّسَاءُ ذَهَبْنَ.]{.ar} "The women went.", [ذَهَبُوا.]{.ar} "They~masc.~ went."
2. If the broken plural doer is placed after the verb, then the singular doer-modification corresponding to the gender of the singular doer is employed. For example, [ذَهَبَ الرِّجَالُ]{.ar} "The men went.", [ذَهَبَتِ ٱلنِّسَاءُ]{.ar} "The women went."

This is the most common usage. However, another possibility is allowed which is usually only found in older works. That is the usage of the feminine singular verb doer modification for broken plural doers. So we can have [ذَهَبَتِ ٱلرِّجَالُ.]{.ar} and [ٱَلرِّجَالُ ذَهَبَتْ.]{.ar} and [ذَهَبَتِ ٱلنِّسَاءُ.]{.ar} and [ٱلنِّسَاءُ ذَهَبَتْ.]{.ar}.

Note that this rule is only for the verb doer-modifications. Detached and attached pronouns for rational beings always match the noun they refer to in number. For example,

[ذَهَبَ ٱلرًّجَالُ إِلَىٰ بُيُوتِهِمْ وَذَهَبَتِ ٱَلنِّسَاءُ إِلَىٰ بُيُوتِهِنَّ.]{.ar}  
"The men went to their houses and then women went to their houses."

[هُمْ مُعَلِّمُونَ وَهُنَّ مُعَلِّمَاتٌ.]{.ar}  
[hum mueallimUna wahunna mueallimAtun.]{.trn}  
"They~pl.\ masc.~ are male teachers and they~pl.\ fem.~ are female teachers."

### Plurals of non-rational beings

The usage of pronouns and verb doer-modifications for non-rational beings is somewhat complicated and depends on whether the plural is mentioned in the sentence or not and whether a large number or small number is intended by the plural. Here we will explain the more common usage.

If the non-rational plural noun is mentioned in a sentence, or if the plural is for a large number of non-rational beings then the feminine singular pronouns [هِيَ]{.ar} [hiya]{.trn}/[ـهَا]{.ar} [-hA]{.trn} and the feminine singular verb doer-modification [ـَتْ]{.ar} [-at]{.trn} are used. It doesn't matter if the singular of the plural noun is masculine or feminine or if the doer comes before or after the verb. Here are some examples:

[هِيَ كُتُبٌ ثَقِيلَةٌ.]{.ar}  
"They are heavy books."

[أَكَلَتِ ٱلْحَيَوَانَاتُ  طَعَامَهَا وَشَرِبَتْ مَاءَهَا.]{.ar}  
"They animals ate their food and drank their water."

If the non-rational plural doer is not mentioned in a sentence, or if the plural is for a small number of non-rational beings then the feminine plural pronouns [هُنَّ]{.ar} [hunna]{.trn}/[ـهُنَّ]{.ar} [-hunna]{.trn} and feminine plural verb doer modification [ـنَ]{.ar} [-na]{.trn} is used. Again, it doesn't matter if the singular of the plural noun is masculine or feminine. However, the feminine plural verb doer modification is used only if the doer is not mentioned or if it comes before the verb. If the doer comes after the verb then the feminine singular verb doer modification is used. Here are some examples:

[وَجَدَ ٱلرَّجُلُ فِي ٱلْحَقِيبَةِ أَقْلَامًا. حَمَلَ ٱلْحَقيبَةَ فَخَرَجْنَ مِنْهَا وَسَقَطْنَ. فَرَفَعَهُنَّ.]{.ar}  
"The man found pens in the bag. He carried the bag and they came out of it and fell down. So he picked them up."

If you're unsure which of the above two rules apply in a particular case, you may safely use the feminine singular as it is the more commonly used.

## Usage of plurals of descriptive nouns with non-rational beings

The usage of descriptive nouns with non-rational plurals is also somewhat complicated. Here we will explain the more normal usage and then also the uncomman usage for completeness.

### Normal usage

Consider the following noun phrase:

[ٱَلسِّنُونَ ٱلصَّعْبَةُ]{.ar}  
[EassinUna -SSaebatu]{.trn}  
"the difficult years"

The described noun is a plural [ٱَلسِّنُونَ]{.ar}. But the describer is singular feminine [ٱَلصَّعْبَةُ]{.ar}, not plural [ٱَلصَّعْبَاتُ]{.ar}. This is because for plural non-rational beings, Arabic typically uses the feminine singular descriptive noun instead of the plural descriptive noun. Even if the described noun is masculine, yet the describer will be feminine singular. For example,

[حَيَوَانَاتٌ وَحْشَةٌ]{.ar}  
[HayawAnatun waHcatun]{.trn}  
"wild animals"

This usage of the feminine singular descriptive noun for non-rational beings occurs in two scenarios:

i. When the descriptive noun is describing plural non-rational beings as the describer in a noun-phrase. This was the case for the two examples above.
ii. When the descriptive noun is describing plural non-rational beings as the information of a sentence. For example:

[ٱَلْحَيَوَانَاتُ كَبِيرَةٌ.]{.ar}  
[EalHayawAnAtu kabIratun]{.trn}  
"The animals are big."

This rule applies even when the descriptive noun in the information is definite. For example:

[ٱَلسِّنُونَ ٱلصَّعْبَةُ هِيَ ٱلطَّوِيلَةُ.]{.ar}  
[AssinUna -SSaebatu hiya -TTawIlatu]{.trn}  
"The difficult years were the long ones."

Note that in the above sentence, it is not just the descriptive nouns [ٱلصَّعْبَةُ]{.ar} and [ٱلطَّوِيلَةُ]{.ar} which are feminine singular. So too is the pronoun [هِيَ]{.ar}. We have already learned the rule for pronouns in the previous section.

Note however that this rule is applied only when the descriptive noun is the describer in a noun-phrase, or in the information of a sentence. If the descriptive noun is describing plural non-rational beings as the subject of a sentence then it will be pluralized. For example:

[ٱَلْحَيَوَانَاتُ كَبِيرَةٌ وَصَغِيرَةٌ. ٱَلْكَبِيرَاتُ قَوِيَّةٌ.]{.ar}  
[EalHayawAnatu kabIratun wa SagIratun. EalkabIrAtu qawiyyatun]{.trn}  
"The animals are big and small. The big ones are strong."

In the example above, in the first sentence the descriptive nouns [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} "big" and [صَغِيرَةٌ]{.ar} [SagIratun]{.trn} "small" are in the feminine singular because they are the information of the sentence and are describing the non-rational plural [ٱَلْحَيَوَانَاتُ]{.ar} [EalHayawAnAtu]{.trn} "the animals".

But in the second sentence, the descriptive noun 
[ٱَلْكَبِيرَاتُ]{.ar} [EalkabIrAtu]{.trn} "the big ones"
is the subject of the sentence. So it is pluralized.

Finally, it is worth mentioning that this usage of the feminine singular descriptive noun for non-rational beings only occurs with the plural, not the dual. Descriptive nouns for dual non-rational beings are dualized as we have seen in the previous chapter.

### Uncommon usage

Using the feminine singular descriptive noun for plural non-rational beings, as we've explained above, is the more normal usage. However, it is allowed, and sometimes you may find, the plural of a descriptive noun beings used for non-rational beings even when it is a describer in a noun-phrase or in the information of a sentence. Thus you may see:

[ٱَلْحَيَوَانَاتُ ٱلْكَبِيرَاتُ ثَقِيلَاتٌ.]{.ar}  
[EalHayawAnAtu -lkabIrAtu vaqIlAtun.]{.trn}  
"The big animals are heavy."

instead of the normal usage:

[ٱَلْحَيَوَنَاتُ ٱلْكَبِيرَةُ ثَقِيلَةٌ.]{.ar}  
[EalHayawAnAtu -lkabIratu vaqIlatun.]{.trn}  
"The big animals are heavy."

and

[كُتُبٌ ثِقَالٌ]{.ar}  
[kutubun viqAlun]{.trn}  
"heavy books"

instead of the more normal:

[كُتُبٌ ثَقِيلَةٌ]{.ar}  
[kutubun vaqIlatun]{.trn}  
"heavy books"

Conversely, we may also find, in rare usage, the feminine singular descriptive noun being used for rational female beings when it is a describer in a noun-phrase or in the information of a sentence. For example,

[جَارِيَاتٌ حَسَنَةٌ]{.ar}  
[jAriyAtun Hasanatun]{.trn}  
"good girls"

instead of the normal usage:

[جَارِيَاتٌ حَسَنَاتٌ]{.ar}  
[jAriyAtun HasanAtun]{.trn}  
"good girls"

For the beginner we recommend that you stick to the normal usage, instead of these rarer usages.

## The descriptive nouns "many" and "few"

### The descriptive noun "many"

The descriptive noun [كَثِيرٌ]{.ar} [kavIrun]{.trn} is used to mean "a lot" when it is describing an uncountable quantity. For example,

[مَاءٌ كَثِيرٌ]{.ar}  
[mAEun kavIrun]{.trn}  
"a lot of water"

[ذَهَبٌ كَثِيرَةٌ]{.ar}  
[pahabun kavIrun]{.trn}  
"a lot of gold"

When used with plural countable nouns the same descriptive noun [كَثِيرٌ]{.ar} [kavIrun]{.trn} is used to mean "many".  With plural non-rational nouns, we will typically use the feminine singular [كَثِيرَةٌ]{.ar} [kavIratun]{.trn} consistent with what we have learned so far. Example:

[حَيَوَانَاتٌ كَثِيرَةٌ]{.ar}  
[HayawAnAtun kavIratun]{.trn}  
"many animals"

However, its usage with plural rational beings can be somewhat different from what we have learned so far.
[كَثِيرٌ]{.ar} [kavIrun]{.trn} has the sound plurals [كَثِيرُونَ]{.ar} [kavIrUna]{.trn} and [كَثِيرَاتٌ]{.ar} [kavIrAtun]{.trn}. And these can be used, as expected, with rational male and female beings respectively. It also has the broken plural [كِثَارٌ]{.ar} [kivArun]{.trn}.
However, instead of using these plurals, [كَثِيرٌ]{.ar} [kavIrun]{.trn} is often used in the masculine singular when used as a descriptive noun for rational beings.

So we often see, for example,

[مُعَلِّمُونَ كَثِيرٌ]{.ar}  
[mueallimUna kavIrun]{.trn}  
"many (male) teachers"

instead of

[مُعَلِّمُونَ كَثِيرُونَ]{.ar}  
[mueallimUna kavIrUna]{.trn}  
"many (male) teachers"

although the latter is also permissible.

Similarly,

[أَنْتُمْ كَثِيرٌ.]{.ar}  
[Eantum kavIrun.]{.trn}  
"You are many (in number)."

The masculine singular [كَثِيرٌ]{.ar} [kavIrun]{.trn} is also often used with plural female rational beings. For example,

[ٱلْمُعًلِّمَاتُ كَثِيرٌ.]{.ar}  
[EalmueallimAtu kavIrun.]{.trn}  
"The (female) teachers are many."

although, in this case, it is probably more common to use the [At]{.trn} plural:

[ٱلْمُعًلِّمَاتُ كَثِيرَاتٌ.]{.ar}  
[EalmueallimAtu kavIrAtun.]{.trn}  
"The (female) teachers are many."

### The descriptive noun "few"

The above discussion also applies to the opposite of [كَثِيرٌ]{.ar} [kavIrun]{.trn}: [قَلِيلٌ]{.ar} [qalIlun]{.trn}. Here are some examples:

[طَعَامٌ قَلِيلٌ]{.ar}  
[TaeAmun qalIlun]{.trn}  
"a little food"

[كُتُبٌ قَلِيلَةٌ]{.ar}  
[kutubun qalIlatun]{.trn}
"a few books"

[ٱلرِّجَالُ قَلِيلٌ.]{.ar}  
[EarrijAlu qalIlun.]{.trn}  
and  
[ٱلرِّجَالُ قَلِيلُونَ.]{.ar}  
[EarrijAlu qalIlUna.]{.trn}  
"The men are few."

[ٱلطَّالِبَاتُ قَلِيلٌ.]{.ar}
[EaTTAlibAtu qalIlun]{.trn}  
and  
[ٱلطَّالِبَاتُ قَلِيلَاتٌ.]{.ar}
[EaTTAlibAtu qalIlAtun]{.trn}  
"The (female) students are few."

### "Many people" and "few people"

The descriptive nouns [كَثِيرٌ]{.ar} [kavIrun]{.trn} and [قَلِيلٌ]{.ar} [qalIlun]{.trn} can be used with the preposition [مِنْ]{.ar} [min]{.trn} to express "a large quantity of" and "a small quantity of" respectively. For example,

[رَجَعَ كَثِيرٌ مِنَ ٱلرِّجَالِ إِلَىٰ بُيُوتِهِمْ.]{.ar}  
[rajaea kavIrun mina -rrijAli EilA buyUtihim]{.trn}  
"A large quantity of the men returned to their homes." = "Many men returned to their homes."

Within context the descriptive nouns [كَثِيرٌ]{.ar} [kavIrun]{.trn} and [قَلِيلٌ]{.ar} [qalIlun]{.trn} can also be used by themselves to mean "a large number of people", and "a few people" respectively. Example:

[ذَهَبَ إِلَىٰ ٱلسُّوقِ كَثِيرٌ وَرَجَعَ قَلِيلٌ]{.ar}  
[pahaba Eila -ssUqi kavIrun warajaea qalIlun.]{.trn}  
"A large number [of people] went to the market and a few [people] returned."

The definite [ٱَلْكَثِيرُ]{.ar} [EalkavIru]{.trn} can be used too in this sense to mean "the many [people]". 
And the definite [ٱَلْقَلِيلُ]{.ar} [EalqalIlu]{.trn} can be used to mean "the few [people]". Example:


[عَمِلَ ٱلْقَلِيلُ وَلَعِبَ ٱلْكَثِيرُ.]{.ar}  
[eamila -lqalIlu walaeiba -lkavIru.]{.trn}  
"The few worked and the many played." 

## Vocabulary

### List

### Notes

nisaa2 plural of imra2ah
FIXME: show imra2ah-nisaa2 at the end as an exception, imra2-qawm, insaan-naas?
ashyaa2a is a diptote, despite being on pattern af3aalun
exception: colors and physical characteristics use broken plural for fem. rat. and also for non-rat.

