#!/bin/sh
Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook')"
#Rscript -e "bookdown::render_book('index.Rmd','bookdown::epub_book')"
#Rscript -e "bookdown::render_book('index.Rmd','pdf_document')"

