# Comparative nouns

## Introduction

In order to express a comparative relationship between nouns, for example, "The boy is taller than the girl.", Arabic uses descriptive nouns with a distinct form. Here is a table of some common descriptive nouns and their corresponding comparative nouns.

|Root|Descriptive noun | Comparative noun|
|:--|:--|:--|
|[كبر]{.arroot}|[كَبِيرٌ]{.ar}   [kabIrun]{.trn}   "big"       | [أَكْبَرُ]{.ar} [Eakbaru]{.trn} "biger"     |
|[صغر]{.arroot}|[صَغِيرٌ]{.ar}   [SagIrun]{.trn}   "small"     | [أَصْغَرُ]{.ar} [EaSgaru]{.trn} "smaller"   |
|[حسن]{.arroot}|[حَسَنٌ]{.ar}    [Hasanun]{.trn}   "good"      | [أَحْسَنُ]{.ar} [EaHsanu]{.trn} "better"    |
|[سوء]{.arroot}|[سَيِّئٌ]{.ar}    [sayyiEun]{.trn}  "bad"       | [أَسْوَأُ]{.ar} [EaswaEu]{.trn} "worse"     |
|[قدم]{.arroot}|[قَدِيمٌ]{.ar}   [qadImun]{.trn}   "old"       | [أَقْدَمُ]{.ar} [Eaqdamu]{.trn} "older"     |
|[جد]{.arroot}|[جَدِيدٌ]{.ar}    [jadIdun]{.trn}   "new"       | [أَجَدُّ]{.ar}  [Eajaddu]{.trn} "newer"     |
|[سهل]{.arroot}|[سَهْلٌ]{.ar}    [sahlun]{.trn}    "easy"      | [أَسْهَلُ]{.ar} [Eashalu]{.trn} "easier"    |
|[صعب]{.arroot}|[صَعْبٌ]{.ar}    [Saebun]{.trn}    "difficult" | [أَصْعَبُ]{.ar} [EaSeabu]{.trn} "more difficult"|
|[طول]{.arroot}|[طَوِيلٌ]{.ar}   [TawIlun]{.trn}   "long"      | [أَطْوَلُ]{.ar} [EaTwalu]{.trn} "longer"     |
|[قصر]{.arroot}|[قَصِيرٌ]{.ar}   [qaSIrun]{.trn}   "short"     | [أَقْصَرُ]{.ar} [EaqSaru]{.trn} "shorter"    |
|[ثقل]{.arroot}|[ثَقِيلٌ]{.ar}   [vaqIlun]{.trn}   "heavy"     | [أَثْقَلُ]{.ar} [Eavqalu]{.trn} "heavier"    |
|[خف]{.arroot}|[خَفِيفٌ]{.ar}    [xafIfun]{.trn}   "light"     | [أَخَفُّ]{.ar}  [Eaxaffu]{.trn} "lighter"    |
|[وسع]{.arroot}|[وَاسِعٌ]{.ar}   [wAsieun]{.trn}   "wide"      | [أَوْسَعُ]{.ar} [Easwaeu]{.trn} "wider"      |
|[ضيق]{.arroot}|[ضَيِّقٌ]{.ar}    [Dayyiqun]{.trn}  "narrow"    | [أَضْيَقُ]{.ar} [EaDyaqu]{.trn} "narrower"   |
|[سرع]{.arroot}|[سَرِيعٌ]{.ar}   [sarIeun]{.trn}   "fast"      | [أَسْرَعُ]{.ar} [Easraeu]{.trn} "faster"     |
|[بطء]{.arroot}|[بَطِيءٌ]{.ar}   [baTIEun]{.trn}   "slow"      | [أَبْطَأُ]{.ar} [EabtaEu]{.trn} "slower"     |
|[قوي]{.arroot}|[قَوِيٌّ]{.ar}    [qawiyyun]{.trn}  "strong"    | [أَقْوَىٰ]{.ar} [EaqwA  ]{.trn} "stronger"   |
|[ضعف]{.arroot}|[ضَعِيفٌ]{.ar}   [DaeIfun]{.trn}   "weak"      | [أَضْعَفُ]{.ar} [EaDeafu]{.trn} "weaker"     |

Note the following points regarding the comparative form:

+ Comparatives are regularly of the pattern [أَفْعَلُ]{.ar} [Eafealu]{.trn} using the template root [فعل]{.arroot}. 
+ Comparatives are non-fully changing nouns, so they won't have [n]{.trn} marks and the indefinite comparative in the i-state will have an [a]{.trn}-mark on the last letter.
+ If a root's last two letters are the same, it is shown as a two-letter root and the comparative is formed by doubling the last letter. Example: [جد]{.arroot}: [أَجَدُّ]{.ar}  [Eajaddu]{.trn} "newer".
+ If a root's last letter is [و]{.ar} or [ي]{.ar}, then the comparative's last letter will be [ىٰ]{.ar}. Example: [قوي]{.arroot}: [أَقْوَىٰ]{.ar} [EaqwA  ]{.trn} "stronger".

You may remember that the pattern of the identical is identical to the pattern of colors and physical characteristics. For example [أَحْمَرُ]{.ar} [EaHmaru]{.trn} "red". However, this similarity is largely superficial. We will see that comparatives are feminized differently and that they are used with feminine nouns differently as well.

## Usage of comparatives

As we mentioned, comparatives are descriptive nouns. Here is an example sentence using a comparative:

[ٱَلْغُلَامُ أَطْوَلُ مِنَ ٱلْجَارِيَةِ.]{.ar}  
[EalgulAmu EaTwalu mina -ljAriyati.]{.trn}  
"The boy is taller than the girl."

Here you can see that the preposition [مِنْ]{.ar} [min]{.trn} is used to mean "than".

If we wish to say: "The girl is taller than the boy.", we will use the same [أَطْوَل]{.ar} [EaTwalu]{.trn} even though the subject "the girl" is now feminine:

[ٱَلْجَارِيَةِ أَطْوَلُ مِنَ ٱلْغُلَامُ.]{.ar}  
[EaljAriyati EaTwalu mina -lgulAmu.]{.trn}  
"The girl is taller than the boy."

Similarly, is the subject noun to be compared is a plural, whether masculine or feminine, rational or non-rational, the same comparative is used. Examples:

[ٱَلرِّجَالُ أَطْوَلُ مِنَ ٱلنِّسَاءِ]{.ar}  
[EarrijAlu Eatwalu mina -nnisAEi.]{.trn}  
"The men are taller than the women."

[ٱَلْأَقْلَامُ ٱلصُّفْرُأَ طْوَلُ مِنَ ٱلْأَقْلَامِ ٱلْحُمْرِ.]{.ar}  
