# Descriptive nouns

## Introduction

In Arabic there are some nouns called _descriptive nouns_. For example:

Arabic word |Transcription| Gender | meaning
:-----------|:------------|:---|:-----------
[كَبِيرٌ]{.ar}   | [kabIrun]{.trn}   | masc. | anything big
[كَبِيرَةٌ]{.ar}  | [kabIratun]{.trn} | fem.  | anything big

[كَبِيرٌ]{.ar} [kabIrun]{.trn} may be applied to anything that can be described as "big", as long as it is designated by a masculine noun. Remember that all nouns, even those that designate inanimate beings, are either masculine or feminine. For example, [كَبِيرٌ]{.ar} [kabIrun]{.trn} may be applied to "a big man" ([رَجُلٌ]{.ar} [rajulun]{.trn}) or "a big house" ([بَيْتٌ]{.ar} [baytun]{.trn} (masc.)).

Similarly, [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} may be applied to anything that can be described as "big" that is designated by a feminine noun. For example, [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} may be applied to "a big cat" ([هِرَّةٌ]{.ar} [hirratun]{.trn} (fem.)) or "a big tree" ([شَجَرَةٌ]{.ar} [cajaratun]{.trn} (fem.)).

Descriptive nouns generally come in pairs: a masculine descriptive noun, and a feminine descriptive noun. The feminine descriptive noun is usually formed by adding a looped [tAE]{.trn} [ة]{.ar} to the end of a masculine descriptive noun, just like we saw for some common nouns. There are some descriptive nouns that form the feminine by using a different feminine marker. And there are a few descriptive nouns that don't change for feminine nouns. We will learn these later if Allah wills.

Descriptive nouns may seem a little strange because English does not commonly have such nouns. But there are a few that can help understand this concept:

In the sentence "I bought an antique.", the word "antique" can be applied to anything that is old and valuable, like an antique table or an antique car. 

Similarly, the word "dependent" can be used as a for a family member, like a spouse or a child, or for a dependent clause in a sentence, or for anything that depends on another thing.

In Arabic these nouns are very common. But they are a little difficult to translate in English because English does not commonly have these types of nouns. We will translate them using the word "one" like [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} (fem.) "a big one". This translation is a little awkward but it is difficult to come up with a better one.

## Adjectives

English uses  adjectives to describe nouns. For example, we can say "a big man". "Big" is the adjective, and "man" is the _described noun_.

Arabic does not technically have adjectives. In Arabic we use descriptive nouns instead. Fo example, in order to express "a big man", we put the described noun [رَجُلٌ]{.ar} [rajulun]{.trn} "a man" first, and place the descriptive noun [كَبِيرٌ]{.ar} [kabIrun]{.trn} (masc.) "a big one" after it. Then the descriptive noun "a big one" gives the meaning of the adjective "big":

[رَجُلٌ كَبِيرٌ]{.ar}
[rajulun kabIrun]{.trn}
"a big man"

Similarly, for "the big tree" we say:

[ٱَلشَّجَرَةُ ٱلْكَبِيرَةُ]{.ar}  
[accajaratu -lkabIratu]{.trn}  
"the big tree"

Let's note a couple of things about descriptive nouns when they are used as adjectives:

+ The descriptive noun comes after the described noun. [كَبِيرٌ]{.ar} [kabIrun]{.trn} "big" comes after [رَجُلٌ]{.ar} [rajulun]{.trn} "a man".

+ The state of the descriptive noun  will match the state of the described noun. "A big man" is [رَجُلٌ كَبِيرٌ]{.ar} [rajulun kabIrun]{.trn}. The described noun [رَجُلٌ]{.ar} [rajulun]{.trn} "man" is in the u-state. Therefore, the descriptive noun [كَبِيرٌ]{.ar} [kabIrun]{.trn} "big" is also in the u-state. We haven't seen nouns in other states yet but if the described noun were in the a-state [رَجُلًا]{.ar} [rajulan]{.trn} " man", we would put the descriptive noun in the a-state as well [كَبِيرًا]{.ar} [kabIran]{.trn} "big": [رَجُلًا كَيِيرًا]{.ar} [rajulan kabIran]{.trn}.

+ If the described noun is indefinite then the descriptive noun will also be indefinite ([رَجُلٌ كَبِيرٌ]{.ar} [rajulun kabIrun]{.trn} "a big man"). Similarly, if the described noun is definite then the descriptive noun will also be definite ([ٱَلشَّجَرَةُ ٱلْكَبِيرَةُ]{.ar} [accajaratu -lkabIratu]{.trn} "the big tree").

+ If the described noun is masculine then the masculine descriptive noun is used. If the described noun is feminine than the feminine descriptive noun is used.

To summarize, when descriptive nouns are used as adjectives, they follow the described noun and match it in state, definiteness, and gender.

We now give a list of common descriptive nouns. We will give only the masculine descriptive noun. To form the feminine descriptive noun, you can add a looped [tAE]{.trn} [ة]{.ar} to the masculine noun, just like we have already seen for [كَبِيرٌ]{.ar} [kabIrun]{.trn} (masc.) and [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} (fem.). 

We will also generally translate the meaning using an English adjective, like "big", instead of "a big one". This is just for convenience. You must remember that descriptive nouns may be used as adjectives but they are actually nouns. We will see some examples of them being used as nouns later in this chapter if Allah wills.

Arabic word |Transcription| meaning
:-----------|:------------|:------------
[حَسَنٌ]{.ar}    | [Hasanun]{.trn}  | good
[سَيِّئٌ]{.ar}    | [sayyiEun]{.trn} | bad
[كَبِيرٌ]{.ar}   | [kabIrun]{.trn}  | big
[صَغِيرٌ]{.ar}   | [SagIrun]{.trn}  | small
[قَدِيمٌ]{.ar}   | [qadImun]{.trn}  | old
[جَدِيدٌ]{.ar}   | [jadIdun]{.trn}  | new
[سَهْلٌ]{.ar}    | [sahlun]{.trn}   | easy
[صَعْبٌ]{.ar}    | [Saebun]{.trn}   | difficult
[طَوِيلٌ]{.ar}   | [TawIlun]{.trn}  | long
[قَصِيرٌ]{.ar}   | [qaSIrun]{.trn}  | short
[ثَقِيلٌ]{.ar}   | [vaqIlun]{.trn}  | heavy
[خَفِيفٌ]{.ar}   | [xafIfun]{.trn}  | light
[وَاسِعٌ]{.ar}   | [wAsieun]{.trn}  | wide
[ضَيِّقٌ]{.ar}    | [Dayyiqun]{.trn} | narrow
[سَرِيعٌ]{.ar}   | [sarIeun]{.trn}  | fast
[بَطِيءٌ]{.ar}   | [baTIEun]{.trn}  | slow

### Examples

### Exercises

## Descriptive nouns in sentences

We have learned that simple sentences have two parts: a subject, and an information. Both the subject and the information are put in the u-state. Let's see some examples of sentences with descriptive nouns.

### Indefinite descriptive noun as information

Our first example uses an indefinite descriptive noun in the information of a sentence:

[ٱَلرَّجُلُ كَبِيرٌ]{.ar}  
[Earrujulu kabIrun]{.trn}  

In the above sentence, the subject is a common noun [ٱَلرَّجُلُ]{.ar} [arrujulu]{.trn} "the man". The information is a descriptive noun [كَبِيرٌ]{.ar} [kabIrun]{.trn} "a big one". When the information of a sentence is an indefinite descriptive noun (as in this sentence), it is used to give the meaning of the adjective. So instead of saying "The man is a big one." we can translate this sentence as "The man is big."

### Gender of descriptive noun as information

In our next example, we have a feminine subject:

[ٱَلشَّجَرَةُ كَبِيرَةٌ]{.ar}  
[Eaccajaratu kabIratun]{.trn}  
"The tree is big."

Note that since the subject [ٱَلشَّجَرَةُ]{.ar} [accajaratu]{.trn} "the tree" is a feminine noun, we use the feminine descriptive noun [كَبِيرَةٌ]{.ar}  [kabIratun]{.trn} "big" for the information. This is because, when first explaining simple sentences, we said that we make the information match the subject in gender only if:

1. There are separate words for the masculine and feminine nouns for the information, and
2. Only one of the two words can be correctly applied to the subject.

This applies to sentence here because there are separate words for the masculine and feminine descriptive noun: [كَبِيرٌ]{.ar} [kabIrun]{.trn} (masc.) and [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} (fem.). And only one of these two [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} (fem.) can be applied to the subject because the subject is a feminine noun [ٱَلشَّجَرَةُ]{.ar} [accajaratu]{.trn} "the tree".

So, since descriptive nouns generally occur in masculine and feminine pairs, when they are used as the information in a sentence, we will match the gender of the descriptive noun to match the gender of the subject.

### Definite descriptive noun as information

Now let's try using definite descriptive noun as the information

[ٱَلشَّجَرَةُ ٱلْكَبِيرَةُ]{.ar}  
[Eaccajaratu -lkabIratu]{.trn}  
"The tree is the big one."

Since the descriptive noun is definite in the information, we translate it as "the big one" instead of "big". Remember that the translation "big" is only used if the descriptive noun in the information is indefinite.

But wait! There is an issue with this sentence. Didn't we see earlier in this chapter that 
[ٱَلشَّجَرَةُ ٱلْكَبِيرَةُ]{.ar}
[Eaccajaratu -lkabIratu]{.trn}
means "the big tree"?

It turns out that when a definite descriptive noun is used after another definite noun we get two meanings:

1. A phrase with noun and an adjective. For example "the big tree".
2. A complete sentence with a subject and an information. For example "The tree is big."

Usually we are able to tell from context which of the two meanings is intended. And there is also another way to express the sentence to distinguish it from the phrase. We will learn this technique later if Allah wills.

So if we get two meanings from a definite descriptive noun following another definite noun, do we also 
get two meanings from an _indefinite_ descriptive noun following another indefinite noun? For example:

[رَجُلٌ كَبِيرٌ]{.ar}
[rajulun kabIrun]{.trn}

Can this mean both:

+ "a big man"
+ "A man is big"

The answer is "no". This is because, as we've already mentioned, simple sentences can generally only start with a definite noun. So if there is an indefinite noun in the beginning it can only mean the phrase, like "a big man" in this example in this example.

### Descriptive noun as the subject

## Adjectives in sentences

The cat is a small animal.


## Remove:

We use adjectives to describe nouns. For example, we can say "a big man". "Big" is the adjective, and "man" is the _described noun_.

In English the adjective comes before the described noun. But in Arabic, the adjective comes after the described noun. 

For example, [كَبِيرٌ]{.ar} is an adjective that means "big". Here are some examples of how it is used:

| Arabic     | Transcription  |English |
|:-----------------------|:----------------------------|:-----------------|
| [رَجُلٌ كَبِيرٌ]{.ar}        | [rajulun kabIrun]{.trn}     | a big man        |
| [ٱَلرَّجُلُ ٱلْكَبِيرُ]{.ar}    | [arrajulu -lkabIru]{.trn}   | the big man      |
| [فِي بَيْتٍ كَبِيرٍ]{.ar}     | [fI baytin kabIrin]{.trn}   | in a big house   |
| [فِي ٱلْبَيْتِ ٱلْكَبِيرِ]{.ar} | [fi -lbayti -lkabIri]{.trn} | in the big house |


Let's note a couple of things:

+ In Arabic, the adjective comes after the described noun. [كَبِيرٌ]{.ar} [kabIrun]{.trn} comes after [رَجُلٌ]{.ar} [rajulun]{.trn}.

+ The state of the adjective  will match the state of the described noun. "A big man" is [رَجُلٌ كَبِيرٌ]{.ar} [rajulun kabIrun]{.trn}. The described noun [رَجُلٌ]{.ar} [rajulun]{.trn} "man" is in the u-state. Therefore, the adjective [كَبِيرٌ]{.ar} [kabIrun]{.trn} "big" is also in the u-state. Similarly "in a big house" is [فِي بَيْتٍ كَبِيرٍ]{.ar} [fI baytin kabIrin]{.trn}. The described noun [بَيْتٍ]{.ar} [baytin]{.trn} "house" is in the i-state. Therefore, the adjective [كَبِير]{.ar} [kabIrin]{.trn} "big" is also in the i-state. 

+ If the described noun is indefinite then the desriber will also be indefinite ([رَجُلٌ كَبِيرٌ]{.ar} [rajulun kabIrun]{.trn}, [فِي بَيْتٍ كَبِيرٍ]{.ar} [fI baytin kabIrin]{.trn}). Similarly, if the described noun is definite then the desriber will also be definite ([ٱَلرَّجُلُ ٱلْكَبِيرُ]{.ar} [arrajulu -lkabIru]{.trn}, [فِي ٱلْبَيْتِ ٱلْكَبِيرِ]{.ar} [fi -lbayti -lkabIri]{.trn}).

Here are some more Arabic adjectives:

Arabic word |Transcription| meaning
:-----------|:------------|:------------
[كَبِيرٌ]{.ar}   | [kabIrun]{.trn}  | big
[صَغِيرٌ]{.ar}   | [SagIrun]{.trn}  | small
[طَوِيلٌ]{.ar}   | [TawIlun]{.trn}  | long
[قَصِيرٌ]{.ar}   | [qaSIrun]{.trn}  | short
[ثَقِيلٌ]{.ar}   | [vaqIlun]{.trn}  | heavy
[خَفِيفٌ]{.ar}   | [xafIfun]{.trn}  | light
[وَاسِعٌ]{.ar}   | [wAsieun]{.trn}  | wide
[ضَيِّقٌ]{.ar}    | [Dayyiqun]{.trn} | narrow
[قَدِيمٌ]{.ar}   | [qadImun]{.trn}  | old
[جَدِيدٌ]{.ar}   | [jadIdun]{.trn}  | new
[سَرِيعٌ]{.ar}   | [sarIeun]{.trn}  | fast
[بَطِيءٌ]{.ar}   | [baTIEun]{.trn}  | slow

## Nouns with multiple adjectives

## Adjectives can be used as nouns

We learned in the previous chapter that nouns have a state (u-state, a-state, or i-state) and that they can have [ٱَلْ]{.ar} [al]{.trn} to make them definite or an [n]{.trn}-mark to make them indefininte. And we just saw that adjectives also have state and can have either [ٱَلْ]{.ar} [al]{.trn} or an [n]{.trn}-mark. This makes them look very similar to nouns. In fact, adjectives can be used just like regular nouns.

If the word [كَبِيرٌ]{.ar} [kabIrun]{.trn} is used by itself (not following another noun as an adjective) then it is itself a noun meaning "a big one". This noun can be applied to any big thing, like a big person, or a big animal, or a big object. Similarly [ٱَلْكَبِيرُ]{.ar} [alkabIru]{.trn} means "the big one". 

This might seem a little strange but this can occur in English as well, although it is not very common. 

For example, the word "antique" is an adjective that can be used to describe, for example, "an antique vase" or "an antique table". But we can use "antique" by itself too without a described noun. So we can say,

"I bought an antique."

"An antique" here is a noun that could be any item that is old and valuable; it may be a book, or a vase, or a car, for example.

But we can't do this with all adjectives in English. We can't say, for example,

"I bought a big."

In Arabic, on the other hand, all adjectives can be used as nouns. But when we translate them to English we will use the word "one" so that the English translation makes sense. So, as we saw [كَبِيرٌ]{.ar} [kabIrun]{.trn} as a noun means "a big one".

Similarly [فِي ٱلْكَبِيرِ]{.ar} [fi -lkabIri]{.trn} means "in the big one". "The big one" could be any big thing, like a big house. We don't know what the big things is exactly just from the sentence. Just like we don't know what the "antique" actually is from the sentence "I bought an antique."

When an adjective is used as a regular noun we will call it a _descriptive noun_.

### Describing descriptive nouns with adjectives

If an adjective is used as a descriptive noun, can we use describe that descriptive noun with another adjective?

Yes we can. Even in English if we use "antique" as a noun, we can describe it with another adjective. So we can say "a heavy antique". "Heavy" is the adjective, and "antique" is the described noun.

Similarly we can say

[ٱَلْكَبِيرُ ٱلثَّقِيلُ]{.ar}  
[EalkabIru -vvaqIlu]{.trn}  
"the heavy big-one"

[فِي كَبِيرٍ ثَقِيلٍ]{.ar}  
[fI kabIrin vaqIlin]{.trn}  
"in a heavy big-one"

## Description phrases

In addition to describing nouns with adjectives, we may also describe them with a phrase. For example

[رَجُلٌ فِي ٱلْبَيْتِ]{.ar}  
[rajulun fi -lbayti]{.trn}  
"A man in the house"

Here the noun "a man" is being described as being "in the house", which is a phrase. Similarly,

[رَجُلٌ فِي بَيْتٍ]{.ar}  
[rajulun fI baytin]{.trn}  
"A man in a house"

Generally, only indefinite nouns can be described with  phrases. In the next chapter we will see what happene if we replace [رَجُلٌ]{.ar} [rajulun]{.trn} in the examples above with [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn}.

## Move to a later chapter:

There is an exception to only indefinite nouns being described by phrases. Sometimes definite nouns may be described by phrases but only if the meaning of the noun is very general like [ٱَلْعِلْمُ]{.ar} "Knowledge".


I bought a small.

This is not a complete sentence because "small" cannot be used as a noun by itself. It can only be a description. So you have to say something like

I bought a small book.

In Arabic, however, all descrbing words are nouns and can be used by, either by themselves like

I bought an antique

or as descrbing words, like

I bought an antique vase.

So, for example, [كَبِير]{lang=ar dir=rtl} is a noun which mean "a big person or thing". Used by itself, it can refer to anything which fits the descrition of being big, like a big man, or a big dog, or a big book, etc.

But it can also be used as a describing word. This table shows how describing words are used in Arabic.


means "a big house".

lso remember that we said that a description is also a noun and it can be used by itself as a noun.

3aDheemun means someone or something great. It can be used as a description:

_rajulun 3aDheemun_ 

means "a great man".

_3an rajulin 3aDheemin_ 

means "about a great man".

But we can use 3aDheem by itself too. If we say

_3an 3aDheemin_

by itself, it means "about someone or something great". Only context will tell us whether "a great person" is meant or "a great thing".


