# Non-fully-changing nouns and proper nouns

## Introduction

Here is an example of the kind of nouns we have learned so far:

State  | Indefinite | Definite
:------|:-----------|:---------
u-state| [رَجُلٌ]{.ar} | [ٱَلرَّجُلُ]{.ar}
a-state| [رَجُلًا]{.ar}| [ٱَلرَّجُلَ]{.ar}
i-state| [رَجُلٍ]{.ar} | [ٱَلرَّجُلِ]{.ar}

As you can see, the noun has [n]{.trn}-marks when it is indefinite, and also, the vowel mark on the last letter changes for each state that the noun is in. These kinds of nouns are called _fully-changing_ nouns. They are by far the most common type of noun.

There are some nouns, however, that are _non-fully-changing_. There are two differences between fully-changing and non-fully-changing nouns:

1. When indefinite, a non-fully-changing noun does not have an [n]{.trn}-mark.
2. When indefinite and in the i-state, a non-fully-changing noun's final letter shall not have an [i]{.trn}-mark. Instead it shall look identical to its appearance in the a-state.

Here is an example of a non-fully-changing noun, [صَحْرَاءُ]{.ar} [SaHrAEu]{.trn} "a desert":

State  | Indefinite | Definite
:------|:-----------|:---------
u-state| [صَحْرَاءُ]{.ar} | [ٱَلصَّحْرَاءُ]{.ar}
a-state| [صَحْرَاءَ]{.ar} | [ٱَلصَّحْرَاءَ]{.ar}
i-state| [صَحْرَاءَ]{.ar} | [ٱَلصَّحْرَاءِ]{.ar}

As you can see, when [صَحْرَاءُ]{.ar} [SaHrAEu]{.trn} is indefinite, it does not have an [n]{.trn}-mark. Also, when it is indefinite and in the i-state, the vowel mark on its final letter is not [◌ِ]{.ar}, as you might expect but [◌َ]{.ar} . And so the noun looks identical in the a-state and i-state when it is indefinite.

When it is definite, however, it behaves just like fully-changing nouns.

## Categories of non-fully-changing nouns

Non-fully-changing nouns fall under different categories. We will discuss them below.

### Nouns that end with an external [اء]{.ar}

If a noun ends with an [اء]{.ar}, which is external to the word's root, then it shall be a non-fully-changing noun.

We have already seen an example of such a noun above: [صَحْرَاءُ]{.ar} [SaHrAEu]{.trn} "a desert". The root of this noun is [صحر]{.arroot}. You can see that the ending [اء]{.ar} is not part of the root. Therefore it is a non-fully-changing noun.

Furthermore, this [اء]{.ar} which is external to the word's root is a feminine marker for singular nouns, just like [ة]{.ar}, except that [ة]{.ar} does not generally make a noun non-fully-changing.

Here is an example sentence with this noun:

[ذَهَبَ ٱلرَّجُلُ إِلَىٰ صَحْرَاءَ وَاسِعَةٍ.]{.ar}  
[pahaba -rrajulu EilA SaHrAEa wAsieatin]{.trn}  
"The man went to a wide desert."

Note that [صَحْرَاءَ]{.ar} [SaHrAEa]{.trn} is  in the i-state because it is preceded by the preposition [إِلَىٰ]{.ar} [EilA]{.trn} "to". It is also a describee, whose describer is [وَاسِعَةٍ]{.ar} [wAsieatin]{.trn} "wide". The final vowel mark [◌َ]{.ar} on the describee [صَحْرَاءَ]{.ar} [SaHrAEa]{.trn} has no effect on the final vowel mark on the describer [وَاسِعَةٍ]{.ar} [wAsieatin]{.trn} "wide". All that matters int this regard is the state of the describee. 

Beware that there are some words where [اء]{.ar} may be part of the word's root, e.g. [ٱِبْتِدَاءٌ]{.ar} [ibtidAEun]{.trn} "a beginning" whose root is [بدء]{.arroot} and which is on the pattern [ٱِفْتِعَالٌ]{.ar} [iftieAlun]{.trn}. Because here the [ء]{.ar} in [ٱبْتِدَاءٌ]{.ar} is part of the word's root, therefore it shall not be a non-fully-changing noun. That is why you can see that it has an [n]{.trn} mark when it is indefinite. Also, for the same reason, [اء]{.ar} in this word is not a feminine marker, and the word is masculine.

### Nouns that end with an external [ىٰ]{.ar}

If a noun ends with an [ىٰ]{.ar} which is external to the word's root, then it shall be a non-fully-changing noun.

An example of such a words is [ذِكْرَىٰ]{.ar} [pikrA]{.trn} "a remembrance". The root of this word is [ذكر]{.arroot} and it is on the pattern [فِعْلَىٰ]{.ar}.

Similar to [اء]{.ar}, this [ىٰ]{.ar} which is external to the word's root is a feminine marker for singular nouns.

Since [ذِكْرَىٰ]{.ar} [pikrA]{.trn} already ends with a vowel, the last letter won't have any additional vowel markers and therefore the word will appear the same in all states:

  State  | Indefinite | Definite
  :------|:-----------|:---------
  u-state| [ذِكْرَىٰ]{.ar} | [ٱَلذِّكْرَىٰ]{.ar}
  a-state| [ذِكْرَىٰ]{.ar} | [ٱَلذِّكْرَىٰ]{.ar}
  i-state| [ذِكْرَىٰ]{.ar} | [ٱَلذِّكْرَىٰ]{.ar}

Here is an example of this word in a sentence:

[ٱَلْكِتَابُ ذِكْرَىٰ جَمِيلةٌ.]{.ar}  
[EalkitAbu pikrA jamIlatun]{.trn}  
"The book is a beautiful remembrance."

Note how the describers in both examples above are feminine because the describee nouns are feminine.

Beware also that, just like in the case of [اء]{.ar}, there are some words where [ىٰ]{.ar} may be part of the word's root, e.g. [ٱَلْهُدَىٰ]{.ar} [EalhudA]{.trn} "the guidance" whose root is [هدي]{.arroot}. Because here the [ىٰ]{.ar} in [ٱلْهُدَىٰ]{.ar} is part of the word's root, therefore it shall not be a non-fully-changing noun. So, when it is indefinite, it will have an [n]{.trn}-mark when it is indefinite: [هُدًى]{.ar} [hudan]{.trn} "a guidance". Also, for the same reason, [ىٰ]{.ar} in this word is not a feminine marker, and the word is masculine.

### Nouns on the pattern [أَفْعَل]{.ar}

If a noun is on the pattern [أَفْعَل]{.ar} then it shall be a non-fully-changing noun. 

Most colors and many physical characteristics fall into this pattern. Colors and physical characteristics are qualitative nouns. The masculine qualitative noun is on the pattern [أَفْعَلُ]{.ar}. And the feminine qualitative noun is on the pattern [فَعْلَاءُ]{.ar} [faelAEu]{.trn} (which is itself a non-fully-changing noun pattern). Here are some examples of such qualitative nouns:

Root | Masc. Noun | Fem. noun | Meaning
:----|:-----------|:-------------|:------------
[حمر]{.arroot} | [أَحْمَرُ]{.ar}  | [حَمْرَاءُ]{.ar}  | red
[سود]{.arroot} | [أَسْوَدُ]{.ar}  | [سَوْدَاءُ]{.ar}  | black
[بيض]{.arroot} | [أَبْيَضُ]{.ar}  | [بَيْضَاءُ]{.ar}  | white
[عرج]{.arroot} | [أَعْرَجُ]{.ar}  | [عَرْجَاءُ]{.ar}  | lame
[حور]{.arroot} | [أَحْوَرُ]{.ar}  | [حَوْرَاءُ]{.ar}  | beautiful eyed
[بكم]{.arroot} | [أَبْكَمُ]{.ar}  | [بَكْمَاءُ]{.ar}  | mute

### Qualitative nouns that end with an external [ان]{.ar}

This category is more complicated than the previous ones. The following conditions must be satisfied for a word that ends with [ان]{.ar} to be a non-fully-changing noun:

1. It must be a qualitative noun, not a designative noun. So the designative noun [قُرْءَانٌ]{.ar} [qurEAnun]{.trn} "a [#qurEan]{.trn2}" of the root [قرء]{.arroot} is not a non-fully-changing noun.
2. The [ان]{.ar} must be external to the word's root. So [جَبَانٌ]{.ar} [jabAnun]{.trn} "a coward" of the root [جبن]{.arroot} is not a non-fully-changing noun.
3. The feminine of the qualitative noun shall not be formed by adding [ة]{.ar} to it. So [نَدْمَانٌ]{.ar} [nadmAnun]{.trn} "regretful" of the root [ندم]{.arroot}, whose feminine is [نَدْمَانَةٌ]{.ar} [nadmAnatun]{.trn} is not a non-fully-changing noun.

It is rare that this last condition fails. Most qualitative nouns that end with an external [ان]{.ar} are of the pattern [فَعْلَانُ]{.ar} [faelAnu]{.trn} and their feminine is of the pattern [فَعْلَىٰ]{.ar} [faelA]{.trn} (which is itself a non-fully-changing noun pattern). The following are examples of non-fully-changing nouns that fall into this category:

Root | Masc. Noun | Fem. noun | Meaning
:----|:-----------|:-------------|:------------
[غضب]{.arroot} | [غَضْبَانُ]{.ar} | [غَضْبَىٰ]{.ar}   | very angry
[عطش]{.arroot} | [عَطْشَانُ]{.ar} | [عَطْشَىٰ]{.ar}   | very thirsty
[جوع]{.arroot} | [جَوْعَانُ]{.ar} | [جَوْعَىٰ]{.ar}   | very hungry

### Other categories

There are a couple more categories of non-fully-changing nouns. Some have to do with proper nouns, which we will cover later in this chapter, and others are plural nouns which we will learn in a later chapter, if [#allAh]{.trn2} wills.

## Proper nouns

Proper nouns are names of persons and places. Proper nouns are always definite. Despite being definite, they will often not begin with [ٱَلْ]{.ar}.

### Male names

Here are some examples of male names: 

+ [مُحَمَّدٌ]{.ar} [muHammadun]{.trn} [#muHammad]{.trn2}
+ [زَيْدٌ]{.ar} [zaydun]{.trn} [#zayd]{.trn2}
+ [سَعِيدٌ]{.ar} [saeIdun]{.trn} [#saeId]{.trn2}
+ [عَلِيٌّ]{.ar} [ealiyyun]{.trn} [e#alI]{.trn2}
+ [سَعْدٌ]{.ar} [saedun]{.trn} [#saed]{.trn2}
+ [ٱَلْحَسَنُ]{.ar} [Ealhasanu]{.trn} [#al-#Hasan]{.trn2}
+ [أَسْعَدُ]{.ar} [Easeadu]{.trn} [E#asead]{.trn2}
+ [عُثْمَانُ]{.ar} [euvmAnu]{.trn} [e#uvmAn]{.trn2}
+ [طَلْحَةُ]{.ar} [Talhatu]{.trn} [#Talhah]{.trn2}
+ [إِبْرَاهِيمُ]{.ar} [EibrAhImu]{.trn} [E#ibrAhIm]{.trn2}
+ [عُمَرُ]{.ar} [eumaru]{.trn} [e#umar]{.trn2}

You can see that male names often have an [n]{.trn}-mark. This does not mean that they are indefinite. Rather, as we've mentioned above, proper noun are always definite. So, for example, it is possible for a proper noun with an [n]{.trn}-mark to begin a subject-information sentence, because it is definite:

[مُحَمَّدٌ رَجُلٌ كَرِيمٌ.]{.ar}  
[muHammadun rajulun karImun.]{.trn}  
"[#muHammad]{.trn2} is a noble man."

<!-- [جَاءَ مُجَمَّدٌ ٱلْكَبِيرُ]{.ar}  
  [jAEa muHammaduni -lkabIru.]{.trn}  
  "The noble [#muHammad]{.trn2} came."

FIXME: Isn't this a badal instead? Maybe remove this section. -->

Names are also often originally qualitative nouns with a good meaning. For example, [سَعِيدٌ]{.ar} [saeIdun]{.trn} is a qualitative noun meaning "happy".

Sometimes, it is not clear from the sentence itself whether a word is used as a qualitative noun, or as a name. For example:

[جَاءَ سَعِيدٌ]{.ar}  
[jAEa saeIdun]{.trn}  
"A happy (masc.) one came."  
OR  
"[#saeId]{.trn2} came."

Many male names are fully changing but there are some that are non-fully-changing. A male name will be non-fully-changing if it falls under the following categories:

1. The male name ends with an [ان]{.ar} which is external to the word's root. This is regardless of whether or not the word was originally a qualitative noun. A name that falls under this category is [عُثْمَانُ]{.ar} [euvmAnu]{.trn} [e#uvmAn]{.trn2} of the root [عثم]{.arroot}.
2. The male name is on the pattern [أَفْعَل]{.ar}, e.g. [أَسْعَدُ]{.ar} [Easeadu]{.trn} [E#asead]{.trn2} of the root [سعد]{.arroot}.
3. The male name ends with a [ة]{.ar}. We have learned that [ة]{.ar} is a feminine marker for singular nouns. However, it is often found in male names and in this case it is not a feminine marker. When a male name ends with [ة]{.ar} then it will be non-fully-changing. An example of a male name that ends with [ة]{.ar} is [طَلْحَةُ]{.ar} [Talhatu]{.trn} [#Talhah]{.trn2}.
4. The male name is non-Arabic in origin, and comprises of more than three letters. Most of the earlier prophets' names that are found in the [#qurEAn]{.trn2} fall under this category, e.g. [إِبْرَاهِيمُ]{.ar} [EibrAhImu]{.trn} [E#ibrAhIm]{.trn2}.

   However, if the non-Arabic origin name comprises three letters then it shall be fully changing, e.g., [نُوحٌ]{.ar} [nUHun]{.trn} [#nUH]{.trn2}.
5. The male name is of the pattern [فُعَل]{.ar}. The only common name that falls in this category is [عُمَرُ]{.ar} [eumaru]{.trn} [e#umar]{.trn2} of the root [عمر]{.arroot}.

   Interestingly, the fully-changing name [e#amr]{.trn2} is written with a silent [و]{.ar} at its end when in the u- and i-states in order to distinguish it from the more common name [e#umar]{.trn2}. Otherwise, both names would appear identical when written without vowel marks, thus: [عمر]{.ar}.

   Name|u-state|a-state|i-state
   :-|:--|:--|:--
   [e#amr]{.trn2}|[عَمْرٌو]{.ar} [eamrun]{.trn}| [عَمْرًا]{.ar} [eamran]{.trn}|[عَمْرٍو]{.ar} [eamrin]{.trn}
   [e#umar]{.trn2}|[عُمَرُ]{.ar} [eumaru]{.trn}| [عُمَرَ]{.ar} [eumara]{.trn}|[عُمَرَ]{.ar} [eumara]{.trn}

There are other categories of non-fully-changing male names as well but they are rare so we won't worry about them.

### Female names

Here are some examples of female names: 

+ [جَمِيلَةُ]{.ar} [jamIlatu]{.trn} [#jamIlah]{.trn2}
+ [فَاطِمَةُ]{.ar} [faTimatu]{.trn} [#fATimah]{.trn2}
+ [زَيْنَبُ]{.ar} [zaynabu]{.trn} [#zaynab]{.trn2}

Female names often, but not always, end with a feminine marker. They too are definite without [ٱَلْ]{.ar} [Eal]{.trn} but they differ from male names in that they are almost always non-fully-changing nouns. Therefore they don't have [n]{.trn}-marks. 

There are some female names that are fully-changing but they are rare so we won't worry about them.

Even when the name is originally a qualitative noun which is fully-changing, it will become non-fully-changing when used as a name. For example:

[جَاءَتْ جَمِيلَةٌ]{.ar}  
[jAEat jamIlatun]{.trn}  
"A beautiful (fem.) one came."

[جَاءَتْ جَمِيلَةُ]{.ar}  
[jAEat jamIlatu]{.trn}  
"[#jamIlah]{.trn2} came."

### Place names

Place names are usually, but not always, feminine and non-fully-changing. Some place names have [ٱَلْ]{.ar} [Eal]{.trn}. Here are some examples:

+ [مَكَّةُ]{.ar} [makkatu]{.trn} (fem.) Mecca
+ [مِصْرُ]{.ar} [miSru]{.trn} (fem.) Egypt
+ [ٱَلْعِرَاقُ]{.ar} [EaleirAqu]{.trn} (masc.) Iraq

## Writing nouns in this book

Henceforth, when we discuss nouns outside of a sentence, we will generally write them without [n]{.trn}-marks and translate them without any indefinite article, e.g. [جَارِيَة]{.ar} [jAriyah]{.trn} "girl". You may assume that all indefinite fully-changing nouns will have an [n]{.trn}-mark. 

Non-fully-changing nouns will be marked with a superscript ◌^2^ to indicate that the final vowel has at most two variations when indefinite, not three, e.g. [صَحْرَاء^2^]{.ar} [SaHrAE]{.trn}^2^ "desert".

## Vocabulary

### List

### Notes

3amr has waw
