# Duals

## Introduction

For any number greater than one, English uses the plural. For example, the plural of "house" is "houses". So in English we will say:

"two houses"

Arabic, on the other hand, uses the plural only for nouns in number three and higher. For nouns that are two in number Arabic uses the _dual_.

## Forming the dual

The dual is formed by appending dual suffix [◌َانِ]{.ar} [Ani]{.trn} when the noun is in the u-state and [◌َيْنِ]{.ar} [ayni]{.trn} when the noun is in the a-state or i-state. Definite nouns, which have [ٱَلْ]{.ar} in their beginning are dualized the same way. 

For example, when we dualize [بَيْت]{.ar} [bayt]{.trn} "house" in order to say "two houses", we get:

| States | Indefinite | Definite
:----|:-------|:-------
u-state         | [بَيْتَانِ]{.ar} [baytAni]{.trn}  | [ٱَلْبَيْتَانِ]{.ar} [EalbaytAni]{.trn}
a- and i-states | [بَيْتَيْنِ]{.ar} [baytayni]{.trn} | [ٱَلْبَيْتَيْنِ]{.ar} [Ealbaytayni]{.trn}   

Note that indefinite duals don't have [n]{.trn} marks. The only difference between definite and indefinite duals is the prefix [ٱَلْ]{.ar}.

## Duals of nouns that end with feminine markers

### Nouns ending in [ة]{.ar}

If a noun ends with a looped [tAE]{.trn} [ة]{.ar}, then it is converted to an open [tAE]{.trn} [ت]{.ar} before appending the dual suffix. For example, dualizing [شَجَرَة]{.ar} [cajarah]{.trn} "tree", we get "two trees":

| States | Indefinite | Definite
:----|:-------|:-------
u-state         | [شَجَرَتَانِ]{.ar} [cajaratAni]{.trn} | [ٱَلشَّجَرَتَانِ]{.ar} [EaccajaratAni]{.trn}
a- and i-states | [شَجَرَتَيْنِ]{.ar} [cajaratayni]{.trn}| [ٱَلشَّجَرَتَيْنِ]{.ar} [Eaccajaratayni]{.trn}

If a feminine noun does not have a looped [tAE]{.trn} then it will simply be appended with [◌َانِ]{.ar} [Ani]{.trn} and [◌َيْنِ]{.ar} [ayni]{.trn}. For example, dualizing [أُمّ]{.ar} [Eumm]{.trn} "mother" in order to get "two mothers", we get [أُمَّانِ]{.ar} [EummAni]{.trn} in the u-state and [أُمَّيْنِ]{.ar} [Eummayni]{.trn} in the a- and i-states.

### Nouns ending with [اء]{.ar}

If a noun ends with the feminine marker [اء]{.ar} which is external to the word's root then the [ء]{.ar} shall be changed into a [و]{.ar} when appending the dual suffixes [◌َانِ]{.ar} [Ani]{.trn} [◌َيْنِ]{.ar} [ayni]{.trn}. Example:

[صَحْرَاء]{.ar} [SaHrAE]{.trn} (root: [صحر]{.arroot}) becomes [صَحْرَاوَانِ]{.ar} [SaHrAwAni]{.trn} and [صَحْرَاوَيْنِ]{.ar} [SaHrAwayni]{.trn}.

Remember that there are some words where [اء]{.ar} may be part of the word's root, e.g. [ٱِبْتِدَاء]{.ar} [ibtidAE]{.trn} "a beginning" whose root is [بدء]{.arroot}. Because here the [ء]{.ar} in [ٱبْتِدَاء]{.ar} is part of the word's root, therefore the [ء]{.ar} shall not be changed into a [و]{.ar} when appending the dual suffixes. It remains a [ء]{.ar} thus: [ٱِبْتِدَاءانِ]{.ar} [EibtidAEAni]{.trn} and [ٱِبْتِدَاءَيْنِ]{.ar} [EibtidAEayni]{.trn}.

There are other words where [اء]{.ar} is not external to the word's root, but where the [ء]{.ar} has been changed from an original [و]{.ar} or a [ي]{.ar} in the word's root. We will learn how to form duals of these words later, if [#allAh]{.trn2} wills.
<!-- النحو الواضح الثانوية part 2-->

### Nouns ending with [ىٰ]{.ar}

If a noun ends with [ىٰ]{.ar} which is external to the word's root then the [ىٰ]{.ar} shall be changed to a [يَ]{.ar} when adding the dual suffixes. For example,  

[غَضْبَىٰ]{.ar} [gaDbA]{.trn} (root: [غضب]{.arroot}) becomes [غَضْبَيَانِ]{.ar} [gaDbayAni]{.trn} and [غَضْبَيَيْنِ]{.ar} [gaDbayayni]{.trn}.

Beware also that, just like in the case of [اء]{.ar}, there are some words where [ىٰ]{.ar} is not external to the word's root, like [ٱَلْهُدَىٰ]{.ar} [EalhudA]{.trn} "the guidance" whose root is [هدي]{.arroot}. We will learn how to form duals of these words later, if [#allAh]{.trn2} wills.

<!-- Don't discuss duals of defective nouns in detail here. Discuss them in the chapter of defective nouns.-->

## Subject-information sentences with a dual subject

In subject-information sentences, if the subject is a dual, then the information will typically match it in being a dual. For example:

[ٱَلْمَرْأَتَانِ أُمَّانِ]{.ar}  
[EalmarEatAni EummAni]{.trn}  
"The two women are mothers."

Note that both [ٱَلْمَرْأَتَانِ]{.ar} [EalmarEatAni]{.trn} "the two women" and [أُمَّانِ]{.ar}  [EummAni]{.trn}  "two mothers" are in the u-state because, just like for sentences with singulars, the subject and information are put in the u-state.

Sometimes, however, the subject and information may not match in number because of the meaning of the sentence. For example,

[ٱَلْبِنَاءَانِ مَدْرَسَةً]{.ar}  
[EalbinAEAni madrasatan]{.trn}  
"The two buildings are a school"

### Duals of qualitative nouns

Just like common nouns, qualitative nouns can also be duals. When a qualitative noun is used to describe a dual noun, the qualitative noun will also be dual. Examples:

The two women are noble.

The two men are very angry.

The big books are heavy.

The man read two heavy books.

## Detached dual pronouns

We have learned the detached pronouns that are used in place of singular nouns. They are:

|Person|Detached pronoun
|:---|:-
Absent person (masc.) "he"             |[هُوَ]{.ar} [huwa]{.trn} 
Absent person (fem.)  "she"            |[هِيَ]{.ar} [hiya]{.trn} 
Addressed person (masc.) "you~masc.~"  |[أَنْتَ]{.ar} [Eanta]{.trn} 
Addressed person (fem.) "you~fem.~"    |[أَنْتِ]{.ar} [Eanti]{.trn} 
Speaking person (masc. and fem.) "I"   |[أَنَا]{.ar} [Eana]{.trn}

Now we will learn the detached pronouns for the dual persons:

|Person|Detached pronoun
|:---|:-
Absent person (masc. and fem.) "they~dual~"   |[هُمَا]{.ar} [humA]{.trn} 
Addressed person (masc. and fem.) "you~dual~" |[أَنْتُمَا]{.ar} [EantumA]{.trn} 
Speaking person (masc. and fem.) "we"         |[نَحْنُ]{.ar} [naHnu]{.trn}

Note that the dual detached pronouns are the same for both genders.

Here are some examples of their use:

[هُمَا مُعَلِّمَتَانِ كَرِيمَتَانِ.]{.ar}  
[humA mueallimatAni karImatAni.]{.trn}  
"They~dual.\ fem.~ are noble teachers."

## Attached dual pronouns

We have also learned the attached pronouns for the singular persons:

Person | Attached pronoun
:------|:--
Absent person (masc.) "him" | [هُ]{.ar} [-hu]{.trn}
Absent person (fem.)  "her" | [هَا]{.ar} [-hA]{.trn}
Addressed person (masc.)  "you~masc.~" | [كَ]{.ar} [-ka]{.trn}
Addressed person (fem.)  "you~fem.~"   | [كِ]{.ar} [-ki]{.trn}
Speaking person (masc. and fem.)  "me" | [◌ِي]{.ar} [-I]{.trn} and [يَ]{.ar} [-ya]{.trn}

Now we will learn the detached pronouns for the dual persons:

|Person|Attached pronoun
|:---|:-
Absent person (masc. and fem.) "them~dual~"   |[هُمَا]{.ar} [-humA]{.trn} 
Addressed person (masc. and fem.) "you~dual~" |[كُمَا]{.ar} [-kumA]{.trn} 
Speaking person (masc. and fem.) "us"         |[نَا]{.ar} [-nA]{.trn}

Note the following points about them:

+ Like the dual detached pronouns, the dual attached pronouns are the same for both genders.

+ The absent person dual attached pronoun "them~dual~" [هُمَا]{.ar} [-humA]{.trn} is the same as the dual detached pronoun "they~dual~" [هُمَا]{.ar} [humA]{.trn}.

+ Just like the absent person singular attached pronoun "him" [هُ]{.ar} [hu]{.trn}, the absent person dual attached pronoun "them~dual~" [هُمَا]{.ar} [-humA]{.trn} becomes [هِمَا]{.ar} [-himA]{.trn} when preceded by the vowels [◌ِ]{.ar} [i]{.trn}, [ـِي]{.ar} [I]{.trn}, or the semi-vowel [ـَيْ]{.ar} [ay]{.trn}. Examples:
   + [بِهِمَا]{.ar} [bihimA]{.trn} "with them~dual~"
   + [فِيهِمَا]{.ar} [fIhimA]{.trn} "in them~dual~"
   + [إِلَيْهِمَا]{.ar} [EilayhimA]{.trn} "to them~dual~"

+ The [ن]{.ar} in the speaking person attached pronoun "us" [نَا]{.ar} [-nA]{.trn} is part of the pronoun and is not an intervening [ن]{.ar} as was the case for the singular speaking person pronouns. So we get:
   + [عَلَيْنَا]{.ar} [ealaynA]{.trn} "on us"
   + [بِنَا]{.ar} [binA]{.trn} "with us"

  However, when attached to a word that ends with a [نْ]{.ar} with a ∅-mark, there is only one [ن]{.ar} written and it is doubled with a doubling mark [◌ّ]{.ar} on it. So we get:
   + [نَا]{.ar} + [مِنْ]{.ar} = [مِنَّا]{.ar} [minnA]{.trn}
   + [نَا]{.ar} + [عَنْ]{.ar} = [عَنَّا]{.ar} [eannA]{.trn}
   + [نَا]{.ar} + [لَدُنْ]{.ar} = [لَدُنَّا]{.ar} [ladunnA]{.trn}
+ The preposition [لِ]{.ar} [li]{.trn} "for" becomes [لَ]{.ar} [la]{.trn} when followed by the dual attached pronouns:
   + [لَهُمَا]{.ar} [lahumA]{.trn} 
   + [لَكُمَا]{.ar} [lakumA]{.trn} 
   + [لَنَا]{.ar} [lanA]{.trn}
+ As expected, the long [A]{.trn} vowel at the ends of the dual attached pronouns becomes a short [a]{.trn} vowel when followed by a connecting hamzah [ٱ]{.ar}. Example:
  + [ذَهَبَ إِلَيْنَا ٱلرَّجُلُ.]{.ar}  
    [pahaba Eilayna -rrajulu.]{.trn}  
    "The man went toward us."

### Dual doee pronouns

The dual attached pronouns that we have just learned are also used as doee pronouns. Again, there is no additional intervening [ن]{.ar} for the speaking person dual attached pronoun [نَا]{.ar} [-nA]{.trn}. Examples:

[سَأَلَهُمَا ٱلرَّجُلُ.]{.ar}  
[saEalahuma -rrajulu.]{.trn}  
"The man asked them~dual~."

[سَأَلْتُكُمَا.]{.ar}  
[saEaltukumA]{.trn}  
"I asked you~dual~."

[سَأَلَتْنَا.]{.ar}  
[saEalatnA.]{.trn}  
"She asked us."

## Verbal sentences with dual doers

### Dual nouns for the doer

We learned that the completed-action verb for a masculine doer is on the pattern [فَعَلَ]{.ar}. And when the doer is feminine, the [ت]{.ar} of femininity is attached to the verb thus: [فَعَلَتْ]{.ar}. We have used these verbs with singular doer nouns. The doer noun always comes after the verb and shall be in the u-state. Examples:

[ذَهَبَ ٱلْغُلَامُ.]{.ar}  
[pahaba -lgulAmu.]{.trn}  
"The boy went." 

[ذَهَبَتْ جَارِيَةٌ.]{.ar}  
[pahabat jAriyatun]{.trn}  
"A girl went." 

These same verbs are used when the doer noun is a dual. Examples:

[ذَهَبَ ٱلْغُلَامَانِ.]{.ar}  
[pahaba -lgulAmAni.]{.trn}  
"The two boys went." 

[ذَهَبَتْ جَارِيَتَانِ.]{.ar}  
[pahabat jAriyatAni.]{.trn}  
"Two girls went." 

### Dual pronouns for the doer

We have already learned the singular doer pronouns:

Person | Doer pronoun | Doer pronoun with verb
:------|:--|:--
Absent person (masc.) "he"  | _invisible_          | [فَعَلَ]{.ar} [faeala]{.trn}
Absent person (fem.)  "she" | _invisible_          | [فَعَلَتْ]{.ar} [faealat]{.trn}
Addressed person (masc.)  "you~masc.~" | [تَ]{.ar} [-ta]{.trn} | [فَعَلْتَ]{.ar} [faealta]{.trn}
Addressed person (fem.)  "you~fem.~"   | [تِ]{.ar} [-ti]{.trn} | [فَعَلْتِ]{.ar} [faealti]{.trn}
Speaking person (masc. and fem.)  "I"  | [تُ]{.ar} [-tu]{.trn} | [فَعَلْتُ]{.ar} [faealtu]{.trn}

Now we will learn the dual doer pronouns:

Person | Doer pronoun | Doer pronoun with verb
:------|:-|:---
Absent person (masc. and fem.) "they~dual~"  | [◌َا]{.ar} [-A]{.trn} | masc.: [فَعَلَا]{.ar} [faealA]{.trn}, fem: [فَعَلَتَا]{.ar} [faealatA]{.trn}
Addressed person (masc. and fem.)  "you~dual~" | [تُمَا]{.ar} [-tumA]{.trn} | [فَعَلْتُمَا]{.ar} [faealtumA]{.trn} 
Speaking person (masc. and fem.)  "we"  | [نَا]{.ar} [-nA]{.trn} | [فَعَلْنَا]{.ar} [faealnA]{.trn}

Note the following points regarding the dual doer pronouns:

+ The dual doer pronouns are the same for both genders.
+ However, the absent person dual doer pronoun [◌َا]{.ar} [-A]{.trn} "they~dual~", when used for a feminine doer is attached to the verb with an intervening [ت]{.ar} of femininity thus: [فَعَلَتَا]{.ar} [faealatA]{.trn}
+ The dual speaking person doer pronoun [نَا]{.ar} [-nA]{.trn} is the same as the dual speaking person attached pronoun [نَا]{.ar} [-nA]{.trn}. But you can tell them apart because the doer pronoun, when attached to the verb, causes the final letter of the verb to have a ∅-mark. Consider the following two sentences:

  [سَأَلْنَا.]{.ar}  
  [saEalnA.]{.trn}  
  "We asked."

  [سَأَلَنَا.]{.ar}  
  [saEalanA.]{.trn}  
  "He asked us."

Here are some more examples of the dual doer pronouns:

[سَأَلْتُمَانَا]{.ar}  
[saEaltumAnA]{.trn}  
"You~dual~ asked us"

[سَأَلَتَاكُمَا]{.ar}  
[saEalatAkumA]{.trn}  
"They~dual\ fem.~ asked you~dual~"

[سَأَلَاهُمَا]{.ar}  
[saEalAhumA]{.trn}  
"They~dual\ masc.~ asked them~dual~"

## Sentence word order

As we've mentioned, the doer, whether a noun or a pronoun, always comes after the verb. Here are a couple of examples of verbal sentences with dual doers:

[ذَهَبَا إِلَىٰ بَيْتٍ.]{.ar}  
[pahabA EilA baytin.]{.trn}  
"They~dual~ went to a house."

[ذَهَبَ ٱلرَّجُلَانِ إِلَىٰ بَيْتٍ.]{.ar}  
[pahabA -rrujalAni EilA baytin.]{.trn}  
"The two men went to a house."

The above verbal sentence can be rearranged to be a subject-information sentence. This gives more emphasis to the subject. In this case, the verb shall follow the subject and will have a doer pronoun.

[ٱَلرَّجُلَانِ ذَهَبَا إِلَىٰ بَيْتٍ.]{.ar}  
[EarrujalAni pahabA EilA baytin.]{.trn}  
"The two men, they~dual~ went to a house."  
= "_The two men_ went to a house."

If there are multiple verbs associated with the same doer in a verbal sentence, the doer noun will follow the first verb  and the rest of the verbs will have doer pronouns. For example:

[أَكَلَ ٱلرَّجُلَانِ وَشَرِبَا وَذَهَبَا.]{.ar}  
[Eakala -rrajulAni wacaribA wapahabA.]{.trn}  
"The two men ate and they~dual~ drank and they~dual~ went."  
= "The two men ate and drank and went."

The above verbal sentence can be rearranged to be a subject-information sentence. In that case, all the verbs shall have doer pronouns. The sentence will have the same translation as above, except for an emphasis on the subject of the sentence.

[ٱَلرَّجُلَانِ أَكَلَا وَشَرِبَا وَذَهَبَا.]{.ar}  
[EarrajulAni EakalA wacaribA wapahabA.]{.trn}  
"The two men, they~dual~ ate and they~dual~ drank and they~dual~ went."  
= "_The two men_ ate and drank and went."

