# Nouns of superiority

## Introduction

Consider the sentence:

"The book is heavier than the pen."

In this sentence a relationship of superiority is established between the two nouns: "the book" and "the pencil". The book is being described as being superior in heaviness.

By the way, we are using the "superiority" in a technical sense. For example, we can say "The donkey is weaker than the horse." Here the donkey is being described as superior in weakness.

In order to express a superiority relationship between nouns, for example, , Arabic uses descriptive nouns with a distinct form. Here is a table of some common descriptive nouns and their corresponding  nouns of superiority.

|Root|Descriptive noun | Noun of superiority|
|:--|:--|:--|
|[كبر]{.arroot}|[كَبِيرٌ]{.ar}   [kabIrun]{.trn}   "big"       | [أَكْبَرُ]{.ar} [Eakbaru]{.trn} "biger"     |
|[صغر]{.arroot}|[صَغِيرٌ]{.ar}   [SagIrun]{.trn}   "small"     | [أَصْغَرُ]{.ar} [EaSgaru]{.trn} "smaller"   |
|[حسن]{.arroot}|[حَسَنٌ]{.ar}    [Hasanun]{.trn}   "good"      | [أَحْسَنُ]{.ar} [EaHsanu]{.trn} "better"    |
|[سوء]{.arroot}|[سَيِّئٌ]{.ar}    [sayyiEun]{.trn}  "bad"       | [أَسْوَأُ]{.ar} [EaswaEu]{.trn} "worse"     |
|[قدم]{.arroot}|[قَدِيمٌ]{.ar}   [qadImun]{.trn}   "old"       | [أَقْدَمُ]{.ar} [Eaqdamu]{.trn} "older"     |
|[جد]{.arroot}|[جَدِيدٌ]{.ar}    [jadIdun]{.trn}   "new"       | [أَجَدُّ]{.ar}  [Eajaddu]{.trn} "newer"     |
|[سهل]{.arroot}|[سَهْلٌ]{.ar}    [sahlun]{.trn}    "easy"      | [أَسْهَلُ]{.ar} [Eashalu]{.trn} "easier"    |
|[صعب]{.arroot}|[صَعْبٌ]{.ar}    [Saebun]{.trn}    "difficult" | [أَصْعَبُ]{.ar} [EaSeabu]{.trn} "more difficult"|
|[طول]{.arroot}|[طَوِيلٌ]{.ar}   [TawIlun]{.trn}   "long"      | [أَطْوَلُ]{.ar} [EaTwalu]{.trn} "longer"     |
|[قصر]{.arroot}|[قَصِيرٌ]{.ar}   [qaSIrun]{.trn}   "short"     | [أَقْصَرُ]{.ar} [EaqSaru]{.trn} "shorter"    |
|[ثقل]{.arroot}|[ثَقِيلٌ]{.ar}   [vaqIlun]{.trn}   "heavy"     | [أَثْقَلُ]{.ar} [Eavqalu]{.trn} "heavier"    |
|[خف]{.arroot}|[خَفِيفٌ]{.ar}    [xafIfun]{.trn}   "light"     | [أَخَفُّ]{.ar}  [Eaxaffu]{.trn} "lighter"    |
|[وسع]{.arroot}|[وَاسِعٌ]{.ar}   [wAsieun]{.trn}   "wide"      | [أَوْسَعُ]{.ar} [Easwaeu]{.trn} "wider"      |
|[ضيق]{.arroot}|[ضَيِّقٌ]{.ar}    [Dayyiqun]{.trn}  "narrow"    | [أَضْيَقُ]{.ar} [EaDyaqu]{.trn} "narrower"   |
|[سرع]{.arroot}|[سَرِيعٌ]{.ar}   [sarIeun]{.trn}   "fast"      | [أَسْرَعُ]{.ar} [Easraeu]{.trn} "faster"     |
|[بطء]{.arroot}|[بَطِيءٌ]{.ar}   [baTIEun]{.trn}   "slow"      | [أَبْطَأُ]{.ar} [EabtaEu]{.trn} "slower"     |
|[قوي]{.arroot}|[قَوِيٌّ]{.ar}    [qawiyyun]{.trn}  "strong"    | [أَقْوَىٰ]{.ar} [EaqwA]{.trn}   "stronger"   |
|[ضعف]{.arroot}|[ضَعِيفٌ]{.ar}   [DaeIfun]{.trn}   "weak"      | [أَضْعَفُ]{.ar} [EaDeafu]{.trn} "weaker"     |
|[كثر]{.arroot}|[كَثِيرٌ]{.ar}   [kavIrun]{.trn}   "many"      | [أَكْثَرُ]{.ar} [Eakvaru]{.trn} "more"       |
|[قل]{.arroot} |[قَلِيلٌ]{.ar}   [qalIlun]{.trn}   "few/less"  | [أَقَلُّ]{.ar}  [Eaqallu]{.trn} "fewer/lesser"|

Note the following points regarding the form of the noun of superiority:

+ Nouns of superiority are regularly of the pattern [أَفْعَلُ]{.ar} [Eafealu]{.trn} using the template root [فعل]{.arroot}. 
+ Nouns of superiority are non-fully changing nouns, so they won't have [n]{.trn} marks and the indefinite noun in the i-state will have an [a]{.trn}-mark on the last letter.
+ If a root's last two letters are the same, it is shown as a two-letter root and the noun of superiority is formed by doubling the last letter. Example: [جد]{.arroot}: [أَجَدُّ]{.ar}  [Eajaddu]{.trn} "newer".
+ If a root's last letter is [و]{.ar} or [ي]{.ar}, then the noun of superiority's last letter will be [ىٰ]{.ar}. Example: [قوي]{.arroot}: [أَقْوَىٰ]{.ar} [EaqwA  ]{.trn} "stronger".

You may remember that the pattern of the identical is identical to the pattern of colors and physical characteristics. For example [أَحْمَرُ]{.ar} [EaHmaru]{.trn} "red". However, this similarity is largely superficial. We will see that nouns of superiority are feminized differently and sometimes not at all.

## Comparing two nouns

Nouns of superiority can be used to compare a descriptive quality between two nouns. Here is an example sentence:

[ٱَلْغُلَامُ أَطْوَلُ مِنَ ٱلْجَارِيَةِ.]{.ar}  
[EalgulAmu EaTwalu mina -ljAriyati.]{.trn}  
"The boy is taller than the girl."

Here you can see that the preposition [مِنْ]{.ar} [min]{.trn} is used to mean "than".

If we wish to say: "The girl is taller than the boy.", we will use the same [أَطْوَل]{.ar} [EaTwalu]{.trn} even though the subject "the girl" is now feminine:

[ٱَلْجَارِيَةِ أَطْوَلُ مِنَ ٱلْغُلَامُ.]{.ar}  
[EaljAriyati EaTwalu mina -lgulAmu.]{.trn}  
"The girl is taller than the boy."

Similarly, if the subject noun to be compared is a plural, whether masculine or feminine, rational or non-rational, the same noun of superiority is used. Examples:

[ٱَلرِّجَالُ أَطْوَلُ مِنَ ٱلنِّسَاءِ وَهُنَّ أَقْصَرُ مِنْهُمْ.]{.ar}  
[EarrijAlu Eatwalu mina -nnisAEi wa hunna EaqSaru minhum.]{.trn}  
"The men are taller than the women and they~fem.~ are shorter than them~masc.~."

[ٱلْكُتُبُ أَثُقَلُ مِنَ ٱلْأَقْلَامِ.]{.ar}  
[Ealkutubu Eavqalu mina -lEaqlAmi.]{.trn}  
"The books are heavier than the pens."

### Nouns of superiority without a second noun

The above example compared one noun to another. Often, the second noun need not be mentioned. For example,

[ٱلْكُتُبُ أَثْقَلُ.]{.ar}  
[Ealkutubu Eavqalu.]{.trn}  
"The books are heavier."

## Conveying the meaning of the highest degree

The same nouns of superiority are also used in Arabic to convey the meaning of the highest degree of a quality, like "the biggest house", "the weakest link", "the best book", etc. This can be done in a number of ways.

### With indefinite noun-chains

The most common way to express this in Arabic is using a noun-chain with the noun of superiority and an indefinite noun. Here is an example:

[هُوَ أَسْرَعُ غُلَامٍ فِي ٱلْمَدْرَسَةِ.]{.ar}  
[huwa Easraeu gulAmin fi -lmadrasati.]{.trn}  
"He is the fastest boy in the school."

An important point to note is that while in English we used the definite in the translation: "the fastest boy", in Arabic the noun-phrase [أَسْرَعُ غُلَامٍ]{.ar} [Easraeu gulAmin]{.trn} is technically indefinite. It is just hard to find a suitable translation in English where the noun-phrase could be indefinite.

The same noun of superiority is used with feminine and dual/plural nouns. Examples:

[هِيَ أَطْوَلُ ٱمْرَأَةٍ.]{.ar}  
[hiya EaTwalu -mraEatin.]{.trn}  
"She is the tallest woman."

[هُمَا أَطْوَلُ رَجُلَيْنِ.]{.ar}  
[humA EaTwalu rajulayni.]{.trn}  
"They are tallest (two) men."

[هُنَّ أَطْوَلُ نِسَاءٍ.]{.ar}  
[hunna EaTwalu nisAEin.]{.trn}  
"They are the tallest women."

<!-- ^ pretty much from Wright vol. ii., sect. 93, p. 227 -->

### With definite noun-chains

The noun of superiority can also be used in definite noun-chains with a slightly different meaning. However, the second noun of the noun-chain will need to be in the plural. Examples:

[هُوَ أَطْوَلُ ٱلرِّجَالِ.]{.ar}  
[huwa EaTwalu -rrijAli.]{.trn}  
"He is the tallest of the men."

[هُمَا أَطْوَلُ ٱلنِّسَاءِ]{.ar}  
[humA EaTwalu -nnisAEi.]{.trn}  
"They (two) are the tallest of the women."

## As describers

So far we have conveyed the meaning of the highest degree with noun-chains, where the noun of superiority is the first-noun in the noun-chain. We can also place the noun of superiority as a describer in a descriptive noun-phrase. This usage is somewhat more complicated and we will explain it below.

For masculine singular nouns, we use the same form of the noun of superiority as we have been using so far:

[هُوَ ٱلرَّجُلُ ٱلْأَطْوَلُ.]{.ar}  
[huwa -rrajulu -lEaTwalu.]{.trn}  
"He is the tallest man."

For feminine and plural nouns, we will have to learn new forms of the noun of superiority. We will give these forms based on the template root [فعل]{.arroot} in the table below:

|Masc. sing.| masc. dual | masc. sound plur. | masc. broken plural| fem. sing. | fem. dual | fem. sound plur.|fem. broken plur.|
|:--|:--|:--|:--|:--|:--|:--|:--|
|[أَفْعَلُ]{.ar} [Eafealu]{.trn}|[أَفْعَلَانِ]{.ar} [EafealAni]{.trn}|[أَفْعَلُونَ]{.ar} [EafealUna]{.trn}|[أَفَاعِلُ]{.ar} [EafAeilu]{.trn}|[فُعْلَىٰ]{.ar} [fuelA]{.trn}|[فُعْلَيَانِ]{.ar} [fuelayAni]{.trn}|[فُعْلَيَاتٌ]{.ar} [fuelayAtun]{.trn}|[فُعَلٌ]{.ar} [fuealun]{.trn}|

| Number | Masc. | Fem. |
|:--|:--|:--|
|sing.        | [أَفْعَلُ]{.ar} [Eafealu]{.trn}|    [فُعْلَىٰ]{.ar} [fuelA]{.trn}|
|dual         | [أَفْعَلَانِ]{.ar} [EafealAni]{.trn}|[فُعْلَيَانِ]{.ar} [fuelayAni]{.trn}|
|sound plur.  | [أَفْعَلُونَ]{.ar} [EafealUna]{.trn}|[فُعْلَيَاتٌ]{.ar} [fuelayAtun]{.trn}|
|broken plural| [أَفَاعِلُ]{.ar} [EafAeilu]{.trn}|  [فُعَلٌ]{.ar} [fuealun]{.trn}|

Duals/plurals can also be used in noun-chains especially when no other indication of number is present. example.

جاء أكارم الرجال
If the singular were used it might imply that one man came.

https://forum.wordreference.com/threads/%D9%81%D9%8A-%D8%A3%D9%82%D8%B5%D9%89-%D8%B3%D8%A7%D8%AD%D9%84-%D8%A8%D8%AD%D8%B1-%D8%A7%D9%84%D8%B4%D9%85%D8%A7%D9%84.3477546/#post-17650853

hum lilkufri yawma2idhin aqrabu minhum lil 2eemaan ii.,Sect. 48 rem A. p. 133A

khair, sharr
