# The five irregular nouns

There are five nouns in Arabic which are irregular and behave a little different than other nouns in how they show their state.

We have learned that regular nouns have three states: the u-state, a-state, and i-state. For singular nouns, the u-state is marked by the [u]{.trn}-mark [◌ُ]{.ar}, the a-state is marked by the [a]{.trn}-mark [◌َ]{.ar}, and the i-state is marked by the [i]{.trn}-mark [◌ِ]{.ar}. The [n]{.trn}-marks [◌ٌ]{.ar}, [◌ً]{.ar} and [◌ٍ]{.ar} are only but extensions of [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar} respectively.

We now present the five irregular nouns that behave differently.

## [أَبٌ]{.ar} [Eabun]{.trn}, [أَخٌ]{.ar} [Eaxun]{.trn}, and [حَمٌ]{.ar} [Hamun]{.trn}

The first three nouns that we will talk about are 

1.  [أَبٌ]{.ar} [Eabun]{.trn} "father"
2.  [أَخٌ]{.ar} [Eaxun]{.trn} "brother"
3.  [حَمٌ]{.ar} [Hamun]{.trn} "father-in-law"

In many respects, these nouns show their state like regular nouns. Here are some examples:

[حَضَرَ أَخٌ فَسَأَلْتُ ٱلْأَخَ عَنْ أَمْرٍ وَشَكَرْتُ لِلْأَخِ.]{.ar}  
[HaDara Eaxun fasaEaltu -lEaxa ean Eamrin wa cakartu lilEaxi.]{.trn}  
"A brother was present, so I asked  the brother about a matter, and I thanked the brother."

[أَمَرَ ٱلرَّجُلُ أَخًا بِاٱلْعَمَلِ فَعَمِلَ ٱلْأَخُ.]{.ar}  
"The man ordered a brother to work, so the brother worked."

[أَبٌ]{.ar} [Eabun]{.trn} "father" and [حَمٌ]{.ar} [Hamun]{.trn} "father-in-law" behave exactly the same as well.

Where the nouns behave irregularly is when they are the first noun in a noun-chain. Then instead of showing their state with [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar}, they show their state using the long vowels [و]{.ar} [U]{.trn}, [ا]{.ar} [A]{.trn}, and [ي]{.ar} [I]{.trn} instead. Here are some examples:

[زَيدٌ أَخُو عَمْرٍو.]{.ar}  
[zaydun EaxU eamrin.]{.trn}  
"Zayd is [e#amr]{.trn2}'s brother."

[سَأَلْتُ أَبَا غُلَامِ عَنْ أَمْرٍ.]{.ar}  
[saEaltu EabA gulAmin ean Eamrin.]{.trn}  
"I asked a boy's father about a matter."

[شَكَرْتُ لِحَمِي زَيْدٍ.]{.ar}  
[cakartu liHamI zaydin.]{.trn}  
"I thanked Zayd's father-in-law."

Even when the second noun in the noun-chain is an attached pronoun, these nouns behave in this irregular way, except if the attached pronoun is for the speaking person [ي]{.ar}. In that case, the attached pronoun [ي]{.ar} attaches to the noun directly, without any intervening long vowel. Examples:

[أَخُوهُ طَوِيلٌ وَأَخُوهَا قَصِيرٌ وَأَخِي كَبِيرٌ.]{.ar}  
[EaxUhu TawIlun waEaxUhA qaSIrun waEaxI kabIrun.]{.trn}  
[His brother is tall and her brother is short and my brother is big."

[سَأَلَ أَخَاهُمْ وَأَخَانَا.]{.ar}  
[saEaltu EaxAhum waEaxAnA.]{.trn}  
"I asked their~m,3+~ brother and our brother."

[شَكَرَ أَخِي أَبِي.]{.ar}  
[cakara EaxI EabI.]{.trn}  
"My brother thanked my father."

[ذَهَبْتُ إِلَىٰ بَيْتِ أَخِيهِنَّ.]{.ar}  
[pahabtu EilA bayti EaxIhinna.]{.trn}  
"I went to their~f,3+~ brother's house."

The above irregular behavior of these three nouns is only when they are the first noun in a noun-chain. When they happen to be the second noun in a noun-chain, they again they behave like regular nouns and their state is shown by the short vowel marks [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar}. Examples:

[بَيْتُ ٱلْأَخِ كَبِيرٌ.]{.ar}  
[baytu -lEaxi kabIrun.]{.trn}  
"The brother's house is big."

[ذَهَبْتُ إِلَىٰ بَيْتِ أَخٍ.]{.ar}  
[pahabtu EilA bayti Eaxin.]{.trn}  
"I went to a brother's house."

Another irregularity of these three nouns is that when their duals are formed, an extra [و]{.ar} is added before adding the dual suffix. The following table shows this for the three noun in all three states.

|Word | Dual (u-state) | Dual (a-state and i-state)|Plural|
|:-|:--|:---|:---|
|[أَبٌ]{.ar} [Eabun]{.trn}|[أَبَوَانِ]{.ar} [EabawAni]{.trn}|[أَبَوَيْنِ]{.ar} [Eabawayni]{.trn}|[آبَاءٌ]{.ar} [EAbAEun]{.trn}|
|[أَخٌ]{.ar} [Eaxun]{.trn}|[أَخَوَانِ]{.ar} [EaxawAni]{.trn}|[أَخَوَيْنِ]{.ar} [Eaxawayni]{.trn}|[إِخْوَةٌ]{.ar} [Eixwatun]{.trn} and [إِخْوَانٌ]{.ar} [EixwAnun]{.trn}|
|[حَمٌ]{.ar} [Hamun]{.trn}|[حَمَوَانِ]{.ar} [HamawAni]{.trn}|[حَمَوَيْنِ]{.ar} [Hamawayni]{.trn}|[أَحْمَاءٌ]{.ar} [EaHmAEun]{.trn}|

One special note regarding [أَبَوَانِ]{.ar} [EabawAni]{.trn} and [أَبَوَيْنِ]{.ar} [Eabawayni]{.trn}: in addition to meaning "two fathers", they can also mean "both parents", i.e., "a father and a mother". Here are examples of these words in sentences:

[ذَهَبَ ٱلْأَخَوَانِ إِلَى ٱلْمَسْجِدِ.]{.ar}  
[pahaba -lEaxawAni fi -lmasjidi.]{.trn}  
"The brothers~2~ went to the mosque."

[سَأَلْتُ أَخَوَيَّ عَنْ أَمْرٍ]{.ar}  
[saEaltu Eaxawayya ean Eamrin.]{.trn}  
"I asked my brothers~2~ about a matter."

[شَكَرْتُ لِأَبَوَيْهِ]{.ar}  
[cakartu liEabawayhi.]{.trn}  
"I thanked his parents."

All three of these nouns form broken plurals which behave regularly like other broken plurals.

## [ذُو]{.ar} [pU]{.trn} and [ذَاتٌ]{.ar} [pAtun]{.trn}

The fourth irregular noun that we will discuss is the masculine noun [ذُو]{.ar} [pU]{.trn} and its feminine counterpart [ذَاتٌ]{.ar} and [pAtun]{.trn}. The words [ذُو]{.ar} [pU]{.trn} and [ذَاتٌ]{.ar} [pAtun]{.trn} mean "owner of" or "possessor of". 

So, for example, [ذُو ٱلْمَالِ]{.ar} [pu -lmAli]{.trn} means "possessor~m~ of wealth" or "wealthy person~m~". The singular, dual, and plural of [ذُو]{.ar} [pU]{.trn} in all three states is shown in the table below:

|State|Singular|Dual|Plural|
|:--|:---|:---|:---|
|u-state|[ذُو]{.ar} [pU]{.trn} |[ذَوَا]{.ar} [pawA]{.trn}|[ذَوُو]{.ar} [pawU]{.trn}|
|a-state|[ذَا]{.ar} [pA]{.trn} |[ذَوَيْ]{.ar} [paway]{.trn}|[ذَوِي]{.ar} [pawI]{.trn}|
|i-state|[ذِي]{.ar} [pI]{.trn} |same as a-state|same as a-state|

The noun [ذُو]{.ar} [pU]{.trn} and its duals and plurals are only ever used in noun-chains and then too, never as the last noun in the chain. Furthermore, when it is the first noun in a noun chain, the second noun may not be a pronoun.

[هَـٰذِهِ ٱلشَّجَرَةُ ذَاتُ ثَمَرٍ كَثِيرٍ.]{.ar}  
[hApihi -ccajaratu pAtu vamarin kavIrin.]{.trn}  
"This tree is the possessor of much fruit." = "This tree is very fruitful."

The word [ذَاتٌ]{.ar} is the feminine of [ذُو]{.ar}. When used as the first noun in a noun chain, its states, duals, and plurals are as in the table below:

|State|Singular|Dual|Plural|
|:--|:---|:---|:---|
|u-state|[ذَاتُ]{.ar} [pAtu]{.trn} |[ذَوَاتَا]{.ar} [pawAtA]{.trn} |[ذَوَاتُ]{.ar} [pawAtu]{.trn}|
|a-state|[ذَاتَ]{.ar} [pAta]{.trn} |[ذَوَاتَيْ]{.ar} [pawAtay]{.trn}|[ذَوَاتِ]{.ar} [pawAti]{.trn}|
|i-state|[ذَاتِ]{.ar} [pAti]{.trn} |same as a-state|same as a-state|


Examples:

As opposed to [ذُو]{.ar} which is only used in noun-chains, [ذَاتٌ]{.ar} may be used a noun in its own right. In this case it means "personality" or "essence". This usage is often found in theological or philosophical works. And, as such, unlike [ذُو]{.ar} which can't have attached pronouns, [ذَاتٌ]{.ar} can be used with attached pronouns. Examples:

## [فُو]{.ar} [fU]{.trn}

The fifth noun in this discussion is [فُو]{.ar} [fU]{.trn}. It is the most irregular noun so far in that it is derived from [فَمٌ]{.ar} [famun]{.trn} "mouth". 

The word [فَمٌ]{.ar} [famun]{.trn} (plural [أَفْواهٌ]{.ar} [EafwAhun]{.trn}) may be used regularly in forming duals, attaching pronouns to it, etc. Examples:

[فَمَا ٱلنَّهْرَيْنِ كَبِيرَانِ.]{.ar}  
[fama -nnahrayni kabIrAni.]{.trn}  
"The mouths~2~ of the rivers~2~'s are big."

[فَمِي مَفْتُوحٌ.]{.ar}  
[famI maftUhun.]{.trn}  
"My mouth is open."

[فَمُهَا جَمِيلٌ.]{.ar}  
[famuhA jamIlun.]{.trn}  
"Her mouth is beautiful."

[فَتَحَ فَمَهُ.]{.ar}  
[fataHa famahu.]{.trn}  
"He opened his mouth."

[جَعَلَتِ ٱلْأُمُّ لُقْمَةَ طَعَامٍ فِي فَمِ ٱبْنَتِهَا.]{.ar}  
[jaealati -lEummu luqmata TaeAmin fI fami -bnatihA.]{.trn}  
"The mother put a morself of food in her daughter's mouth."

In addition to the above regular behavior of [فَمٌ]{.ar} [famun]{.trn} "mouth", when the word is singular and is the first noun in a noun-chain, it is common to replace it with [فُو]{.ar} [fU]{.trn}. This is also done when the second noun in the noun-chain is a pronoun. 

The three states of the singular [فُو]{.ar} [fU]{.trn} are shown in the table below:

|u-state|a-state|i-state|
|:---|:---|:---|
|[فُو]{.ar} [fU]{.trn} |[فَا]{.ar} [fA]{.trn} |[فِي]{.ar} [fI]{.trn}|

Examples of usage:

[فُو ٱلنَّهْرِ كَبِيرٌ.]{.ar}  
[fu -nnahri kabIrun.]{.trn}  
"The mouth of the river is big."

[فُوهَا جَمِيلٌ.]{.ar}  
[fUhA jamIlun.]{.trn}  
"Her mouth is beautiful."

[فَتَحَ فَاهُ.]{.ar}  
[fataHa fAhu.]{.trn}  
"He opened his mouth."

[جَعَلَتِ ٱلْأُمُّ لُقْمَةَ طَعَامٍ فِي فِي ٱبْنَتِهَا.]{.ar}  
[jaealati -lEummu luqmata TaeAmin fI fi -bnatihA.]{.trn}  
"The mother put a morself of food in her daughter's mouth."

When the attached pronoun for the speaking person [ي]{.ar} is attached to [فُو]{.ar} [fU]{.trn}, [فَا]{.ar} [fA]{.trn}, or [فِي]{.ar} [fI]{.trn} the combination is always [فِيَّ]{.ar} [fiyya]{.trn} in all three states. Examples:

[فِيَّ مَفْتُوحٌ.]{.ar}  
[fiyya maftUhun.]{.trn}  
"My mouth is open."

[فَتَحْتُ فِيَّ.]{.ar}  
[fataHtu fiyya.]{.trn}  
"I opened my mouth."

[أَكَلْتُ بِفِيَّ.]{.ar}  
[Eakaltu bifiyya.]{.trn}  
"I ate with my mouth."

As mentioned above, [فُو]{.ar} [fU]{.trn} typically only replaces [فَمٌ]{.ar} [famun]{.trn} "mouth", when the word is singular and is the first noun in a noun-chain. Otherwise, [فَمٌ]{.ar} [famun]{.trn} continues to be used.

