# Gender

All nouns in Arabic are either masculine or feminine in gender. Sometimes the nouns designate living beings, like "man", "woman", "human", "bull", "cow", "teacher", "student", etc.

Other times, the nouns designate inanimate objects. 

There are other nouns that are more descriptive meaning and are often used as description words, like "a big [person or thing]", "a happy [person]", etc.

To deal with the gender of these different kinds of nouns, we'll classify nouns into:

1. _Fixed-ending_ nouns: In fixed-ending nouns, we generally cannot modify the masculine noun to obtain the feminine noun.
2. _Flexible-ending_ nouns: In flexible-ending nouns, we can generally modify the masculine noun to obtain the feminine noun.

## Fixed-ending nouns

These include:

1. Nouns for living beings that are male and female. The grammatical gender of the noun usually matches the gender of the living being. Here are some examples:

   Arabic word | Transcription|Gender | Definition
   :-----------|:-----------|:---|:----------------
   [رَجُلٌ]{.ar}  |[rajulun]{.trn}   |masc.|a man
   [ٱِمْرَؤٌ]{.ar} |[imraEun]{.trn}   |masc.|a man
   [ٱِمْرَأَةٌ]{.ar}|[imraEatun]{.trn} |fem. |a woman
   [طِفْلٌ]{.ar}  |[Tiflun]{.trn}    |masc.|a male child
   [طِفْلَةٌ]{.ar} |[Tiflatun]{.trn}  |fem. |a female child
   [أَبٌ]{.ar}   |[Eabun]{.trn}     |masc.|a father
   [أُمٌّ]{.ar}   |[Eummun]{.trn}    |fem. |a mother
   [إِنْسَانٌ]{.ar}|[EinsAnun]{.trn}  |masc.|a human
   [شَخْصٌ]{.ar}  |[caxSun]{.trn}    |masc.|a person
   [كَلْبٌ]{.ar}  |[kalb]{.trn}      |masc.|a male dog
   [كَلْبَةٌ]{.ar} |[kalbatun]{.trn}  |fem. |a female dog
   [هِرٌّ]{.ar}   |[hirrun]{.trn}    |masc.|a male cat
   [هِرَّةٌ]{.ar}  |[hirratun]{.trn}  |fem. |a female cat
   [أَسَدٌ]{.ar}  |[Easadun]{.trn}   |masc.|a lion
   [لَبْوَةٌ]{.ar} |[labwatun]{.trn}  |fem. |a lioness
   [ثَوْرٌ]{.ar}  |[vawrun]{.trn}    |masc.|a bull
   [بَقَرَةٌ]{.ar} |[baqaratun]{.trn} |fem. |a cow
   [قِرْدٌ]{.ar}  |[qirdun]{.trn}    |masc.|a monkey
   [حَمَامَةٌ]{.ar}|[HamAmatun]{.trn} |fem. |a pigeon
   [حَيَوَانٌ]{.ar}|[HayawAnun]{.trn} |masc.|an animal
   [طَيْرٌ]{.ar}  |[Tayrun]{.trn}    |masc.|a bird

2. Nouns for inanimate objects that are not physically male or female. However, the nouns will still be either grammatically masculine or feminine.

   Arabic word | Transcription|Gender | Definition
   :-----------|:-----------|:---|:----------------
   [كِتَابٌ]{.ar} |[kitAbun]{.trn}   |masc.|a book
   [بَيْتٌ]{.ar}  |[baytun]{.trn}    |masc.|a house
   [قَلَمٌ]{.ar}  |[qalamun]{.trn}   |masc.|a pen
   [طَعَامٌ]{.ar} |[TaeAmun]{.trn}   |masc.|a food
   [مَاءٌ]{.ar}  |[mAEun]{.trn}     |masc.|a water
   [بَلَدٌ]{.ar}  |[baladun]{.trn}   |masc.|a country
   [شَيْءٌ]{.ar}  |[cayEun]{.trn}    |masc.|a thing
   [مَدْرَسَةٌ]{.ar}|[madrasatun]{.trn}|fem. |a school
   [مَدِينَةٌ]{.ar}|[madInatun]{.trn} |fem. |a city
   [مَكْتَبَةٌ]{.ar}|[maktabatun]{.trn}|fem. |a library
   [غُرْفَةٌ]{.ar} |[gurfatun]{.trn}  |fem. |a room
   [شَجَرَةٌ]{.ar} |[cajaratun]{.trn} |fem. |a tree
   [كَلَامٌ]{.ar} |[kalAmun]{.trn}   |fem. |a speech
   [نَصِيحَةٌ]{.ar}|[naSIHatun]{.trn} |fem. |an advice
   [رَأْسٌ]{.ar}  |[raEsun]{.trn}    |masc.|a head
   [أَنْفٌ]{.ar}  |[Eanfun]{.trn}    |masc.|a nose
   [بَطْنٌ]{.ar}  |[baTnun]{.trn}    |masc.|a belly
   [يَدٌ]{.ar}   |[yadun]{.trn}     |fem. |a hand, an arm
   [رِجْلٌ]{.ar}  |[rijlun]{.trn}    |fem. |a leg
   [عَيْنٌ]{.ar}  |[eaynun]{.trn}    |fem. |an eye, a water spring
   [شَمْسٌ]{.ar}  |[camsun]{.trn}    |fem. |a sun
   [قَمَرٌ]{.ar}  |[qamarun]{.trn}   |masc.|a moon
   [عِلْمٌ]{.ar}  |[eilmun]{.trn}    |masc.|a knowledge
   [قُوَّةٌ]{.ar}  |[quwwatun]{.trn}  |fem. |a strength
   [حَيَاةٌ]{.ar} |[HayAtun]{.trn}   |fem. |a life
   [مَوْتٌ]{.ar}  |[mawtun]{.trn}    |masc.|a death

Let's note a few things:

+ The feminine noun usually ends with a looped [tAE]{.trn} [ة]{.ar}, which is a feminine marker for singular nouns (but not for plural nouns which we'll learn in the next chapter, if Allah wills). This looped [tAE]{.trn} is the most common feminine marker. There are a couple of other feminine markers that are not very common. We will learn those later, if Allah wills.

+ There are a few feminine nouns that don't end with looped [tAE]{.trn}, like [أُمٌّ]{.ar} [Eummun]{.trn} "a mother", [شَمْسٌ]{.ar} [camsun]{.trn} "a sun". Only a few of these are commonly used so they will not be too hard to learn, if Allah wills. Of these are parts of the body that occur in pairs like eyes, hand, and legs. These are mostly feminine, even if they don't have a feminine marker. 

+ The feminine noun is sometimes fomed by adding the looped [tAE]{.trn} to the masculine noun like mar', kalb. Other times, the feminine noun is completely different, like bull, cow. Because of this, we won't assume that we can generally form a feminine to a fixed-ending noun by adding the feminine marker.

+ Animals often have different words for the male animal and the female animal, like [أَسَدٌ]{.ar} [Easadun]{.trn} "a lion", [لَبْوَةٌ]{.ar} [labwatun]{.trn}"a lioness", [ثَوْرٌ]{.ar} [vawrun]{.trn} "a bull", [بَقَرَةٌ]{.ar} [baqaratun]{.trn} "a cow". This is often the case when the make and female animal are visually or agriculturally distinct.

  Other times, the same noun is often used to refer to both the male and female animal, like [قِرْدٌ]{.ar} [qirdun]{.trn} "a monkey", [حَمَامَةٌ]{.ar} [HamAmatun]{.trn} "a pigeon". 
  
+ There are some nouns for living beings that don't have different masculine and feminine nouns. These nouns can be used for both male and female living beings even though the noun is itself only of one grammatical gender. For example, [شَخْصٌ]{.ar} [caxSun]{.trn} is a masculine noun which means "a person". But it can be used to refer to both a man and a woman. 

  Remember that we cannot modify fixed-ending nouns by adding a feminine marker like looped [tAE]{.trn} [ة]{.ar} to it. So when [شَخْصٌ]{.ar} [caxSun]{.trn} is used to refer to a female person, we can't modify it to [شَخْصَةٌ]{.ar} [caxSatun]{.trn} because this word does not exist.

  Similarly [حَيَوَانٌ]{.ar} [HayawAnun]{.trn} is a masculine noun which means "an animal" but it can be used to refer to both male and female animals without modifying it. 

+ Even when there are different words for the male and female living beings, one of them is often commonly used to refer to both the male and female animal. For example, [كَلْبٌ]{.ar} [kalbun]{.trn} is "a male dog" and  [كَلْبَةٌ]{.ar} [kalbatun]{.trn} is "a female dog". But commonly, [كَلْبٌ]{.ar} [kalbun]{.trn} is used to refer to both a male and a female dog. This is done especially when we just want to say "a dog" and we are not concerned wither whether it is a male or female dog.

  Similarly [هِرَّةٌ]{.ar} [hirratun]{.trn} is commonly used to refer to both a female and a male cat, even though the word [هِرٌّ]{.ar} exists. And [طِفْلٌ]{.ar} [Tiflun]{.trn} "a male child" is commonly used to refer to both a male and a female child, even though the word [طِفْلَةٌ]{.ar} [Tiflatun]{.trn} exists. [إِنْسَانٌ]{.ar} [EinsAnun]{.trn} "a human" is also one of these words. (The word [إِنْسَانَةٌ]{.ar} [EinsAnatun]{.trn} "a female human" exists but it is very rarely used.)

  So how do we know when a fixed-ending noun of one gender is commonly used to refer to both male and female living beings, even though the noun exists in both genders? Many nouns that designate animals behave like this. As for nouns that designate humans, there are not very many of these and we have already listed the most common ones. When we come across nouns like these, we will note it in the vocabulary.

+ There are two words for "a man": [رَجُلٌ]{.ar} [rajulun]{.trn} and [ٱِمْرَؤٌ]{.ar} [imraEun]{.trn}.
The noun [رَجُلٌ]{.ar} [rajulun]{.trn} is used more commonly when talking about male human beings.
[ٱِمْرَؤٌ]{.ar} [imraEun]{.trn} is used generally when speaking about "man" generically, for example, in sentences like "Man is a social animal." and "A man should always be honest."

  **MOVE THIS TO NOUNS CHAPTER**

  The word [ٱِمْرَؤٌ]{.ar} [imraEun]{.trn} also behaves a little differently than most other nouns. When we add [ٱَلْ]{.ar} to it to make it definite "the man", instead of becoming [ٱَلِٱمْرَؤُ]{.ar} [alimraEu]{.trn}, it becomes [ٱَلْمَرْءُ]{.ar} [almarEu]{.trn}. Similarly, 
[ٱِمْرَأَةٌ]{.ar} [imraEatun]{.trn} "a woman" becomes
[ٱَلْمَرْأَةُ]{.ar} [almarEatu]{.trn}.

  There is another more strange behavior of the noun [ٱِمْرَؤٌ]{.ar} [imraEun]{.trn}when it does not have [ٱَلْ]{.ar}. Usually if we put it in the a-state and i-state it will become
[ٱِمْرَأً]{.ar} [imruEun]{.trn}
[ٱِمْرَإٍ]{.ar} [imruEun]{.trn}
  
  Sometimes, we find it as [ٱِمْرُؤٌ]{.ar} [imruEun]{.trn} in the u-state. And when it is in the a-state and i-state, it appears as 
[ٱِمْرُؤٌ]{.ar} [imruEun]{.trn}
[ٱِمْرُؤٌ]{.ar} [imruEun]{.trn}

## Flexible-ending nouns

Flexible-ending nouns can refer to living beings as well as inanimate objects. Description words are also nearly always flexible-ending nouns. Flexible-ending nouns can usually be feminized when needed by adding a feminine marker to them. The most common feminine marker for singular nouns, as we've noted already, is looped [tAE]{.trn}.

Here are some examples of flexible-ending nouns:

Arabic word  | Transcription|Gender | Definition
:----------- |:-----------|:---|:----------------
[سَعِيدٌ]{.ar}  | [saeIdun]{.trn}      | masc.| a happy [masc. person]
[سَعِيدَةٌ]{.ar} | [saeIdatun]{.trn}    | fem. | a happy [fem. person]
[مُعَلِّمٌ]{.ar}  | [mueallimun]{.trn}   | masc.| a [masc.] teacher
[مُعَلِّمَةٌ]{.ar} | [mueallimatun]{.trn} | fem. | a [fem.] teacher
[أُسْتَاذٌ]{.ar} | [EustApun]{.trn}     | masc.| a [masc.] professor
[أُسْتَاذَةٌ]{.ar}| [EustApatun]{.trn}   | fem. | a [fem.] professor
[كَبِيرٌ]{.ar}  | [kabIrun]{.trn}      | masc.| a big [masc. person or thing]
[كَبِيرَةٌ]{.ar} | [kabIratun]{.trn}    | fem. | a big [fem. person or thing]
[صَغِيرٌ]{.ar}  | [SagIrun]{.trn}      | masc.| a small [masc. person or thing]
[صَغِيرَةٌ]{.ar} | [SagIratun]{.trn}    | fem. | a small [fem. person or thing]
[وَاسِعٌ]{.ar}  | [wAsieun]{.trn}      | masc.| a wide [masc.thing]
[وَاسِعَةٌ]{.ar} | [wAsieatun]{.trn}    | fem. | a wide [fem. thing]
[ضَيِّقٌ]{.ar}   | [Dayyiqun]{.trn}     | masc.| a narrow [masc.thing]
[ضَيِّقَةٌ]{.ar}  | [Dayyiqatun]{.trn}   | fem. | a narrow [fem. thing]

Let's note a few things:

+ When we add a looped [tAE]{.trn} to a masculine noun the letter before the looped [tAE]{.trn} will always have an [a]{.trn}-mark.

## Feminine flexible-ending nouns as description words

In the previous chapter we noted that a description word has to match the described noun in definiteness and state. For example:

[ٱَلرَّجُلُ السَّعِيدُ فِي بَيْتٍ كَبِيرٍ]{.ar}  
[Earrujulu -ssaeIdu fI baytin kabIrin]{.trn}  
The happy man is in the big house.

[ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} "the man" is definite and in the u-state so its description word [السَّعِيدُ]{.ar} [assaeIdu]{.trn} "a happy [person]" will also be definite and in the u-state.

Similarly, [بَيْتٍ]{.ar} [baytin]{.trn} "the house" is indefinite and in the i-state so its description word [كَبِيرٍ]{.ar} [kabIrin]{.trn} "a big [place]" will also be indefinite and in the i-state.

Now we'll modify this rule: a description word shall match the described noun in gender as well as case and definiteness. Let's try this by making the described nouns feminine:

[ٱَلْمَرْأَةُ السَّعِيدَةُ فِي مَكْتَبَةٍ كَبِيرَةٍ]{.ar}  
[EalmarEatu -ssaeIdatu fI maktabatin kabIratin]{.trn}  
The happy woman is in the big library.

[ٱَلْمَرْأَةُ]{.ar} [almarEatu]{.trn} "the woman" is feminine so its description word [السَّعِيدَةُ]{.ar} [assaeIdatu]{.trn} will also be feminine and also match the described noun it by being definite and in the u-state.

Similarly, [مَكْتَبَةٍ]{.ar} [maktabatin]{.trn} "a library" is feminine so  its description word [كَبِيرَةٍ]{.ar} [kabIratin]{.trn} "a big [place]" will also be feminine and also match the described noun by being indefinite and in the i-state.

As we mentioned, description words are usually flexible-ending nouns so it is easy to make them feminine by adding a feminine marker to them. However, there are a few flexible-ending nouns that are used as description words for feminine described nouns without modifying them by adding a feminine marker. Also, rarely, a fixed-ending noun might be used as a description word. In this case as well, the fixed-ending noun may not be modified by adding a feminine marker to it. We will deal with these cases later, if Allah wills, but for now we will just note that these cases do occur.

## Simple sentences with feminine subjects

### The information about the subject is a flexible-ending noun

In the previous chapter we took a look at some simple sentences that consist of a subject and some information about the subject. So far the subjects have been masculine nouns. Here are some sentences that we used as examples:

[ٱَلرَّجُلُ مُعَلِّمٌ]{.ar}  
[Earrajulu mueallimun]{.trn}  
"The man is a teacher."

[ٱَلرَّجُلُ كَبِيرٌ]{.ar}  
[Earrajulu kabIrun]{.trn}  
"The man is big."

[ٱَلرَّجُلُ ٱلْكَبِيرُ]{.ar}  
[Earrajulu -lkabIru]{.trn}  
"The man is the big [person]."

[ٱَلْكَبِيرُ سَعِيدٌ]{.ar}  
[EalkabIru saeIdun]{.trn}  
"The big [person] is happy."

In these sentences the information about the subject is a flexible-ending noun. If we replace the subject [ٱَلرَّجُلُ]{.ar} [Earrajulu]{.trn} "the man" with a feminine subject
[ٱَلْمَرْأَةُ]{.ar}
[almarEatu]{.trn}
"the woman",
we will also make the subject's information feminine by adding a feminine-marker.

### The information about the subject is a fixed-ending noun

We can also have sentences where the information is a fixed-ending noun. In this case, if we replace the masculine subject with a feminine subject, we check if a corresponding feminine fixed-ending noun exists with the correct meaning. If it does exist we may use it to replace the fixed-ending masculine information. Otherwise we will keep the fixed-ending masculine subject.

[ٱَلْغُلَامُ طِفْلٌ]{.ar}  
[EalgulAmu Tiflun]{.trn}  
"The boy is a child."

[ٱَلْجَارِيَةُ طِفْلَةٌ]{.ar}  
[EaljAriyatu Tiflatun]{.trn}  
"The girl is a child."

[ٱَلْجَارِيَةُ طِفْلٌ]{.ar}  
[EaljAriyatu Tiflun]{.trn}  
"The girl is a child."

Since [طِفْلَةٌ]{.ar} [Tiflatun]{.trn} "a female child" exists as a fixed-ending noun we were able to use it to replace [طِفْلٌ]{.ar} [Tiflun]{.trn} "a child". In the last sentence we kept [طِفْلٌ]{.ar} [Tiflun]{.trn} "a child" even with a feminine subject since it is commonly used to refer to both a male or a female child. Both sentences are correct.

Here is another example:

[ٱَلثَّوْرُ حَيَوَانٌ]{.ar}  
[Ealbaqaratu HayawAnun]{.trn}  
"The bull is an animal."

[ٱَلبَقَرَةُ حَيَوَانٌ]{.ar}  
[Ealbaqaratu HayawAnun]{.trn}  
"The cow is an animal."

Since [حَيَوَانَةٌ]{.ar} [HayawAnatun]{.trn} does not exist as a fixed-ending noun, we can not use it to replace [حَيَوَانٌ]{.ar} [HayawAn]{.trn}.

We can also have a masculine subject with fixed-ending feminine information:

[ٱَلْكَلَامُ نَصِيحَةٌ]{.ar}  
[EalkalAmu naSIHatun]{.trn}
"The speech is an advice."

**Add na3t to above xabars here or in next section**
albaqaratu hayawaanun kabeerun

## Some notes about fixed-ending and flexible-ending nouns

fixed-ending nouns are often primitive, or they are words for concepts.

flexible-ending nouns are usually based on some characteristic of the object.

Description words are usually from flexible-ending nouns.

## In a later chapter:

Some flexible-ending nouns become commonly used as words that designate specific things. 

Sometimes they may be inanimate objects like, e.g. naSIHah advice, muSIbah calamity.

Other times they are persons of only one gender, e.g., jAriyah girl. 

These now behave like fixed-ending nouns in that we can not add or remove the feminine marker.

There are also other flexible-ending nouns used as words that designate persons of both gender like mueallim, mueallimah.

Some fixed-ending nouns can be used as description words like xAm "a raw material".

