# Noun-chains

## Introduction

In Arabic we may chain two or more nouns in a sequence to establish an "of" relationship between them, in order to express, for example,

+ "the mother of the boy", or, equivalently" "the boy's mother".
+ "a house of a man", or, equivalently, "a man's house".
+ "the sword of Zayd", or equivalently, "Zayd's sword".

In English, as you can see there we can express this relationship using the word "of" or using apostrophe-s "'s" between two nouns. In some phrases, using apostrophe-s is more natural than using the word "of".

In Arabic we express these types of phrases by chaining the two nouns together thus:

[أُمُّ ٱلْغُلَامِ]{.ar}  
[Eummu -lgulAmi]{.trn}  
"the mother of the boy", or, equivalently" "the boy's mother"

We can identify noun-chains by noting that the first noun in the chain has neither an [n]{.trn} mark, nor an [ٱَلْ]{.ar}, and the second noun in the chain will be in the i-state. 

The first noun in the chain is the noun before "of" and the second noun in the chain is the noun after "of".

## State of the chained nouns

The second noun in the chain will be in the i-state. The first noun may be in any state, depending on its function in the sentence. For example,

   + [أُمُّ ٱلْغُلَامِ مُعَلِّمَةٌ.]{.ar}  
     [Eummu -lgulAmi mueallimatun.]{.trn}  
     "The mother of the boy is a teacher.", or, equivalently, "The boy's mother is a teacher."
   + [وَجَدَ أُمَّ ٱلْغُلَامِ.]{.ar}  
     [wajada Eumma -lgulAmi.]{.trn}  
     "He found the boy's mother." (Note that [أُمَّ]{.ar} is in the a-state.)
   + [كَتَبَتْ إِلَىٰ أُمِّ ٱلْغُلَامِ.]{.ar}  
     [katabat EilA Eummi -lgulAmi.]{.trn}  
     "She wrote to the boy's mother." (Note that [أُمِّ]{.ar} is in the i-state.)

## Definiteness of the nouns in the chain

As we mentioned above, the first noun in the chain can have neither an [n]{.trn} mark, nor an [ٱَلْ]{.ar}. The definiteness of both nouns is determined by examining the second noun in the chain. If the second noun is definite (either by having [ٱَلْ]{.ar}, or by being a proper noun), then both the nouns in the chain will be definite. And if the second noun is indefinite, then both the nouns in the chain will be indefinite. 

[بَيْتُ مُحَمَّدٍ]{.ar}  
[baytu muHammadin]{.trn}  
"the  house of [#muHammad]{.trn2}"

[بَيْتُ ٱلرَّجُلِ]{.ar}  
[baytu -rrajuli]{.trn}  
"The house of the man"

[بَيْتُ رَجُلٍ]{.ar}  
[baytu rajulin]{.trn}  
"a house of a man"

## Describers for nouns in noun-chains

If the second noun in a chain is to be described using a descriptive noun, then just like we have learned, we will place the descriptive noun after the second noun in the chain and match it definiteness, state, gender, and number (depending on whether it denotes a rational or non-rational being). Examples: 

[بَيْتُ رَجُلٍ كَبِيرٍ]{.ar}  
[baytu rajulin kabIrin]{.trn}  
"a house of an old/big man" = "an old/big man's house"

[بُيُوتُ ٱلرِّجالِ ٱلْكِبَارِ]{.ar}  
[buyUtu -rrijAli -lkibAri]{.trn}  
"houses of the old/big men" = "the old/big men's houses"

If the first noun in a chain is to be described using a descriptive noun, then we will actually place the descriptive noun after the second noun, not the first noun, in the chain. This way we don't break the chain of the two nouns. The describer will match the first noun definiteness, state, gender, and number (depending on whether it denotes a rational or non-rational being). Examples: 

[بَيْتُ رَجُلٍ كَبِيرٌ]{.ar}  
[baytu rajulin kabIrun]{.trn}  
"a big house of a man" = "a man's big house"

[بُيُوتُ  ٱلْمَرْأَةِ ٱلْكَبِيرَةُ]{.ar}  
[buyUtu -lmarEati -lkabIratu]{.trn}  
"the big houses of the woman" = "the woman's big houses"

Consider, however, the sentence:

[ذَهَبَ إِلَىٰ بَيْتِ رَجُلٍ كَبِيرٍ.]{.ar}  
[pahaba EilA bayti rajulin kabIrin.]{.trn}  

In this sentence both the first noun in the chain [بَيْتِ]{.ar} [bayti]{.trn} and second noun [رَجُلٍ]{.ar} [rajulin]{.trn} are indefinite, singular, masculine, and in the i-state. So the describer [كَبِيرٍ]{.ar} [kabirin]{.trn} could be applicable to either. And the meaning of the sentence could be either,

"He went to a man's big house."

or,

"He went to a big/old man's house."

The listener would know from context which of the two meanings is intended. If the speaker wished to explicitly disambiguate the meanings without relying on context, he could use the preposition [لِ]{.ar} instead of using a noun-chain. Here the preposition [لِ]{.ar} gives the meaning of "of", rather than "for".

[ذَهَبَ إِلَىٰ بَيْتٍ كَبِيرٍ لِرَجُلٍ.]{.ar}  
[pahaba EilA baytin kabIrin lirajulin.]{.trn}  
"He went to a big house of a man." = "He went to a man's big house."

and,

[ذَهَبَ إِلَىٰ بَيْتٍ لِرَجُلٍ  كَبِيرٍ.]{.ar}  
[pahaba EilA baytin kabIrin lirajulin.]{.trn}  
"He went to a big/old man's house."

## Duals and plurals in noun chains

### Duals

Remember that duals are expressed by suffixing [ـَانِ]{.ar} [Ani]{.trn} to the noun when it is in the u-state and [ـَيْنِ]{.ar} [ayni]{.trn} when it is in the a-state and i-state.

If a dual is the second noun in a chain, then it is not treated any differently from any other noun. For example,

[بَيْتُ ٱلرَّجُلَيْنِ]{.ar}  
[baytu -rrajulayni]{.trn}  
"the house of the two men"

If a dual is the first noun in a chain, then the [ن]{.ar} in the dual suffix is dropped. For example,

+ [بَيْتَا ٱلرَّجُلِ وَاسِعَانِ.]{.ar}  
  [bayta -rrajuli wAsieAni.]{.trn}  
  "The two houses of the man are spacious."

  Note that [بَيْتَا ٱلرَّجُلِ ]{.ar} [bayta -rrajuli]{.trn} is technically pronounced identically to [بَيْتَ ٱلرَّجُلِ]{.ar} [bayta -rrajuli]{.trn}. The [Ealif]{.trn} in [بَيْتَا]{.ar} is not pronounced because of the connecting [hamzah]{.trn} after it. Some say that extra stress may be placed on the vowel [ta]{.trn} in order to convey that it is the dual: [bay#t#a -rrajuli]{.trn}.

+ [ذَهَبَ إِلَىٰ مَدِنَتَيْ بَلَدٍ.]{.ar}  
  [pahaba EilA madInatay baladin.]{.trn}  
  "He went to two cities of a country."
+ [فَتَحَ بَابَيِ ٱلْبَيْتِ.]{.ar}  
  [fataHa bAbayi -lbayti.]{.trn}  
  "He opened the two doors of the house."

  Note that a helper [i]{.trn} vowel is placed on the [ي]{.ar} in [بَابَيِ]{.ar} [bAbayi]{.trn} instead of the ∅-mark because of the connecting [hamzah]{.trn} after it.

### Plurals

We have learned three kinds of plurals:

1. The sound [Un]{.trn} plural.
2. The sound [At]{.trn} plural.
3. The broken plural.

The sound [Un]{.trn} plural behaves similarly to the dual in that when it is the first noun in a chain, the [ن]{.ar} is dropped. Examples:

+ [مُعَلِّمُو ٱلْغُلَامِ فِي ٱلْمَدْرَسَةِ.]{.ar}  
  [mueallimu -lgulAmi fi -lmadrasati.]{.trn}  
  "The teachers of the boy are in the school."

  Note, again, that [مُعَلِّمُو ٱلْغُلَامِ]{.ar} is technically pronounced identically to [مُعَلِّمُ ٱلْغُلَامِ]{.ar} [mueallimu -lgulAmi]{.trn}, except some say that extra stress may be placed on the vowel [مُ]{.ar} in the case of the plural [muealli#m#u -lgulAmi]{.trn}. This can serve to differentiate it from the singular when heard orally:

  [مُعَلِّمُ ٱلْغُلَامِ فِي ٱلْمَدْرَسَةِ.]{.ar}  
  [mueallimu -lgulAmi fi -lmadrasati.]{.trn}  
  "The teacher of the boy is in the school."

+ [وَجَدَ مُعَلِّمي غُلَامٍ.]{.ar}  
  [wajada mueallimI gulAmin.]{.trn}  
  "He found teachers of a boy."

+ [ذَهَبَ إِلَىٰ مُعَلِّمِي ٱلْغُلَامِ.]{.ar}  
  [pahaba EilA mueallimi -lgulAmi.]{.trn}  
  "He went to the teachers of the boy."

  Here too, some say to place extra stress on the vowel [مِ]{.ar} [muealli#m#i -lgulAmi]{.trn} in order to differentiate it to the listener from the singular:

+ [ذَهَبَ إِلَىٰ مُعَلِّمِ ٱلْغُلَامِ.]{.ar}  
  [pahaba EilA mueallimi -lgulAmi.]{.trn}  
  "He went to the teacher of the boy."

The other two types of plurals: the sound [At]{.trn} plural and the broken plural are not treated any differently from other nouns when used in chains. Examples:

+ [بُيُوتِ الرَّجُلِ وَاسِعَةٌ.]{.ar}  
  [buyUtu -rrajuli wAsieatun.]{.trn}  
  "The houses of the man are spacious."

+ [ذَهَبَتِ ٱلْمَعَلِّمَةُ إِلَىٰ طَالِبَاتِ ٱلْمَدْرَسَةِ.]{.ar}  
  [pahabati -lmueallimatu EilA TAlibAti -lmadrsati.]{.trn}  
  "The (female) teacher went to the (girl) students of the school."

## Non-fully changing nouns in noun-chains

Remember that a non-fully changing noun without [ٱَلْ]{.ar} does not take an [n]{.trn}-mark and its last letter keeps an [a]{.trn} mark instead of an [i]{.trn} mark when in the i-state. When definite with [ٱَلْ]{.ar}, it is similar to fully-changing nouns.

So when a non-fully changing noun without [ٱَلْ]{.ar} is the second noun in a noun-chain, it will have an [a]{.trn}-mark instead of an [i]{.trn} mark.

For example, [صَحْرَاءُ]{.ar} [SaHrAEu]{.trn} "a desert" is a non-fully-changing noun. "A desert's sky" will be expressed as:

[سَمَاءُ صَحْرَاءَ]{.ar}  
[samAEu SaHrAEa]{.trn}

not:

[سَمَاءُ صَحْرَاءِ]{.ar}  
[samAEu SaHrAEi]{.trn}

Similarly, [جَمِيلَةُ]{.ar} "[#jamIlah]{.trn2}" as a woman's name is a proper noun and is a non-fully-changing noun. "[#jamIlah]{.trn2}'s house" will be expressed as:

[بَيْتُ جَمِيلَةَ]{.ar}  
[baytu jamIlata]{.trn}  

not:

[بَيْتُ جَمِيلَةِ]{.ar}  
[baytu jamIlati]{.trn}  

However, as an exception, when an indefinite non-full-changing noun is the first noun in a noun-chain and is in the i-state, it will actually take an [i]{.trn}-mark on its last letter. For example, [صَحْرَاءُ]{.ar} [SaHrAEu]{.trn} "a desert" is a non-fully-changing noun.

"in the desert of [#makkah]{.trn2}" will be expressed as,

[فِي صَحْرَاءِ مَكَّةَ]{.ar}  
[fI SaHrAEi makkata]{.trn}  

As you can see, [صَحْرَاءِ]{.ar} [SaHrAEi]{.trn} has an [i]{.trn}-mark despite being a non-fully-changing noun, exemplifying the exceptional rule we have just stated. Also note, by the way, that [مَكَّةَ]{.ar} [makkata]{.trn} has an [a]{.trn}-mark on it's last letter in the i-state because it is a non-fully-changing noun without [ٱَلْ]{.ar} as the second noun in a noun-chain.

## Noun chains with more than two nouns

So far we have seen noun-chains with two nouns. Noun-chains can be arbitrarily long, although practically they will usually be less than five nouns long. Here is an example of a noun-chain with more than two nouns:

+ [مِفْتَاحُ بَابِ بَيْتِ ٱلرَّجُلِ]{.ar}  
  [miftAHu bAbi bayti -rrajuli]{.trn}  
  "the key of the door of the man's house"

+ [سَمَاءُ صَحْرَاءِ مَكَّةَ]{.ar}  
  [samAEu SaHrAEi makkata]{.trn}  
  "the sky of the desert of Makkah"

+ [كِتَابَا جَارِيَتَيْ مَدِينَةِ دَمِشْقَ]{.ar}  
  [kitAbA jAriyatay madInati damicqa]{.trn}  
  "the two books of the two girls of the city of Damascus"

+ [مِنْ وَرَقَتَيْ شَجَرَةِ حَدِيقَةٍ صَغِيرَتَيْنِ]{.ar}  
  [min waraqatay cajarati HadIqatin]{.trn}  
  "from two small leaves of a tree of a garden"

Note the following:

+ Only the last noun may have [ٱَلْ]{.ar} or an [n]{.trn} mark. 
+ The definiteness of the last noun determines the definiteness of the rest of the nouns in the chain. 
+ All the nouns except the first must be in the i-state. 
+ The [ن]{.ar} of the dual and the [Un]{.trn} plural is dropped for all nouns except the last.
+ Any non-fully-changing noun in the i-state in any position but the last will take an [i]{.trn}-mark on it's last letter. If a non-fully-changing noun is the last noun in the chain, and it does not have [ٱَلْ]{.ar} then it will take an [a]{.trn}-mark on it's last letter.
+ Describers for any of the nouns in the chain will appear at the end. Practically, only one of the nouns will have a describer.

## Mismatched definiteness in noun-chains

We have learned that if the second noun is definite (either by having [ٱَلْ]{.ar}, or by being a proper noun), then both the nouns in the chain will be definite. And if the second noun is indefinite, then both the nouns in the chain will be indefinite. 

What if we need to express an of-relationship where the two nouns are not both definite or both indefinite? For example, how then do we express phrases like "a house of the man" and "the house of a man"? 
In order to express the former, we can employ the preposition [لِ]{.ar}:

[ذَهَبَ إِلَىٰ بَيْتٍ لِلرَّجُلِ.]{.ar}  
[pahaba EilA baytin lirrajuli]{.trn}  
"He went to a house of the man."

Another way to express this is that we may interpret the phrase "a house of the man" to understand that the man has more than one house and that we are talking about one of them. In this case, we can use the plural to say,

[ذَهَبَ إِلَىٰ بَيْتٍ مِنْ بُيُوتِ ٱلرَّجُلِ]{.ar}  
[pahaba EilA baytin min buyUti -rrajuli.]{.trn}  
"He went to a house from the houses of the man."

This use of the plural, although fairly common, may be more appropriate in some cases than others, depending on the meaning of the sentence. 

The question remains: how to express a phrase of the type "the house of a man", where the first noun in definite and the second noun is indefinite?

In this case we will use the same expression as we did for "a house of a man":

[بَيْتُ رَجُلٍ]{.ar}  
[baytu rajulin]{.trn}  
"a house of a man"

Technically, "house" is indefinite in this expression, but it can still be used idiomatically to translate "the house of a man." It may help to use apostrophe-s in the translation where the definiteness of "house" is not apparent: "a man's house".

## Pronouns in a noun-chain

Consider the noun-chain:

[بَيْتُ ٱلرَّجُلِ]{.ar}  
[baytu -rrajuli]{.trn}  
"the house of the man" = "the man's house"

We can replace the noun "the man" with the attached pronoun [ـهُ]{.ar} [-hu]{.trn} "him" to get:

[بَيْتُهُ]{.ar}  
[baytuhu]{.trn}  
"the house of him" = "his house"

This can be done with all the attached pronouns:

|Arabic|English|
|:---|:----|
|[بَيْتُهُ]{.ar} [baytuhu]{.trn}    |  his house |
|[بَيْتُهَا]{.ar} [baytuhA]{.trn}   |  her house |
|[بَيْتُهُمَا]{.ar} [baytuhumA]{.trn}|  their~dual\ masc.~ house |
|[بَيْتُهُمَا]{.ar} [baytuhumA]{.trn}|  their~dual\ fem.~ house |
|[بَيْتُهُمْ]{.ar} [baytuhum]{.trn}  |  their~pl.\ masc.~ house |
|[بَيْتُهُنَّ]{.ar} [baytuhunna]{.trn}|  their~pl.\ fem.~ house |
|[بَيْتُكَ]{.ar} [baytuka]{.trn}    |  your~sing.\ masc.~ house |
|[بَيْتُكِ]{.ar} [baytuki]{.trn}    |  your~sing.\ fem.~ house |
|[بَيْتُكُمَا]{.ar} [baytukumA]{.trn}|  your~dual~ house |
|[بَيْتُكُمْ]{.ar} [baytukum]{.trn}  |  your~pl.\ masc.~ house |
|[بَيْتُكُنَّ]{.ar} [baytukunna]{.trn}|  your~pl.\ fem.~ house |
|[بَيْتِي]{.ar} [baytI]{.trn}      |  my house |
|[بَيْتُنَا]{.ar} [baytunA]{.trn}   |  our house |

Here are some notes regarding the use of pronouns in noun-chains.

+ An attached pronoun may be only the last noun in a noun-chain. It cannot be the first noun in a noun-chain.
+ A looped [tAE]{.trn} [ة]{.ar} in the first noun becomes an open [tAE]{.trn} [ت]{.ar} when a pronoun is attached as the second noun in the noun-chain. For example [مَدْرَسَةٌ]{.ar} [madrasatun]{.trn} "a school" becomes [مَدْرَسَتُهُ]{.ar} [madrasatuhu]{.trn} "his school".
+ The first noun in the noun-chain, before the attached pronoun, may be in any state. So, for example, we can have:
  + [دَخَلَ بَيْتَهُ.]{.ar} (a-state)  
    [daxala baytahu]{.trn}  
    "He entered his house."
  + [فِي بَيْتِهِ.]{.ar} (i-state)  
    [fI baytihi]{.trn}  
    "in his house"
+ With the pronoun [ـِي]{.ar} [-I]{.trn}, the first noun in the noun-chain will generally appear the same in all states. For example,
  + [بَيْتِي كَبِيرٌ]{.ar} (u-state)  
    [baytI kabIrun.]{.trn}  
    "My house is big."
  + [دَخَلَ بَيْتِي.]{.ar} (a-state)  
    [daxala baytI]{.trn}  
    "He entered my house."
  + [فِي بَيْتِي]{.ar} (i-state)  
    [fI baytI]{.trn}  
    "in my house"
+ We have mentioned that when a dual noun or sound [Un]{.trn} plural noun is first noun in a noun-chain its [ن]{.ar} is dropped. This rule remains valid when the last noun in the noun-chain is an attached pronoun. So we get:
  + [بَيْتَاهُ]{.ar}  
    [baytAhu]{.trn}  
    "his two houses"
  + [إِلَىٰ بَيْتَيْهِمَا]{.ar}  
    [EilA baytayhimA]{.trn}  
    "to their~dual~ two houses"
  + [مُعَلِّمُوكَ]{.ar}  
    [mueallimUka]{.trn}
    "your~sing.\ masc.~ (male) teachers"
  + [مِنْ مُعَلِّمِيهِ]{.ar}  
    [min mueallimIhi]{.trn}  
    "from his (male) teachers"

+ With dual nouns and sound [Un]{.trn} plural nouns, when the last noun in the noun-chain is [ـِي]{.ar} [-I]{.trn} "my", the [ـِي]{.ar} [-I]{.trn} becomes a [يَ]{.ar} [ya]{.trn} when preceded by an unvowelled [ا]{.ar} [Ealif]{.trn} or [ي]{.ar} [yAE]{.trn}. The [يَ]{.ar} gets doubled when preceded by an unvowelled [ي]{.ar}. Examples:
  + [مُعَلِّمَايَ طَيِّبَانِ.]{.ar}  
    [mueallimAya TayyibAni.]{.trn}  
    "My two (male) teachers are good."
  + [مِنْ مُعَلِّمَيَّ]{.ar}  
    [min mueallimayya]{.trn}  
    "from my two (male) teachers"
  + [إِلَىٰ مُعَلِّمِيَّ]{.ar}  
    [EilA mueallimiyya]{.trn}  
    "to my (male) teachers"
<!--There is an example of ya after unvoweled waw: fUya "my mouth" but famI and fiyya are more common so I won't mention this rule since I won't be providing an example-->

+ As a special rule, however, when the sound [Un]{.trn} plural is in the u-state and is the first-noun in a noun-chain followed by [ـِي]{.ar} [-I]{.trn} "my", the ending will not become [ـُويَ]{.ar} [-Uya]{.trn} as we might expect. Instead, it will become identical to the a-state and i-state [ـِيَّ.]{.ar} [-iyya]{.trn}. For example:
  + [مُعَلِّمِيَّ طَيِّبُونَ.]{.ar}  
    [mueallimiyya TayyibUna.]{.trn}  
    "My (male) teachers~pl.~ are good."

+ Pronouns are always definite. So when a pronoun is the last noun in a noun-chain, all preceding nouns will be definite. This is important to know because if a describer is to be used for any of the preceding nouns, it will be definite too and will therefore have [ٱَلْ]{.ar}. Examples:
  + [بَيْتِي ٱلْكَبِيرُ وَاسِعٌ.]{.ar}  
    [bayti -lkabIru wAsieun.]{.trn}  
    "My big house is spacious."
  + [قَرَءَا كِتَابَيْهِمَا ٱلْجَدِيدَيْنِ.]{.ar}  
    [qaraEA kitAbayhima -ljadIdayni.]{.trn}  
    "They~dual~ read their two new books."
  + [مُعَلِّمِيَّ ٱلْكِرَامُ فِي مَدْرَسَتِهِمُ ٱلْقَدِيمَةِ.]{.ar}  
    [mueallimiyya -lkirAmu fI madrasatihimu -lqadImati.]{.trn}  
    "My noble (male) teachers are in their old school."

  By the way, describers will obviously only be for nouns preceding the pronoun and never for the pronoun itself.

## Noun-chains with "and"

### Multiple nouns before "of" and one noun after "of"

In English we can have an expression like "the pen and the book of the boy" = "the boy's pen and book". In this sentence there are two nouns before "of" and one noun after "of".

In order to express this in Arabic, we will say:

[قَلَمُ ٱلْغُلَامِ وَكِتَابُهُ]{.ar}  
[qalamu -lgulAmi wa kitAbuhu]{.trn}  
"the boy's pen and his book" = "the boy's pen and book"

Note that the noun-chain is not broken by the insertion of [وَ]{.ar} [wa]{.trn} "and". Rather a second noun-chain is used and the two are separated by [وَ]{.ar} [wa]{.trn} "and". This is the preferred way of expressing such expressions.

There is another, less preferred way of expressing this. And this is by breaking the first noun-chain and inserting [وَ]{.ar} [wa]{.trn} "and":

[قَلَمُ وَكِتَابُ ٱلْغُلَامِ]{.ar}  
[qalamu wa kitAbu -lgulAmi]{.trn}  
"the boy's pen and book"

This second method is not considered as eloquent. Some even consider it incorrect. So we advise you to use the first method whenever possible.

#### With pronouns

If the second noun in the noun-chain is replaced with a pronoun then only the first method is allowed. For example,

[قَلَمُهُ وَكِتَابُهُ]{.ar}  
[qalamuhu wakitAbuhu]{.trn}  
"his pen and his book"

### One noun before "of" and multiple nouns after "of"

We can also have expressions like "the house of the boy and the girl". In this sentence there is one noun before "of" and two nouns after "of".

To express this in Arabic we will say:

[بَيْتُ ٱلْغُلَامِ وَٱلْجَارِيَةِ]{.ar}  
[baytu -lgulAmi wa-ljAriyati]{.trn}  
"the house of the boy and the girl"

Note that both 
[ٱلْغُلَامِ]{.ar} [EalgulAmi]{.trn} and [ٱَلْجَارِيَةِ]{.ar} [EaljAriyati]{.trn} are in the i-state because they are both second nouns in the noun-chain.

#### With pronouns

If any or both of the second nouns in the noun-chain is replaced with a pronoun then the first noun must be repeated. For example,

[بَيْتُهُ وَبَيْتُ ٱلْجَارِيَةِ]{.ar}  
[baytuhu wabaytu -ljAriyati]{.trn}  
"his house and the girl's house"

[بَيْتُهُ وَبَيْتُهَا]{.ar}  
[baytuhu wabaytuhA]{.trn}  
"his house and her house"

However, it must be said that these expressions are ambiguous because they could be interpreted to mean that there are two houses: one that is "his" and the second that is "her's". One way to remove this ambiguity, when only a single house is intended, is to use the dual pronoun instead:

[بَيْتُهُمَا]{.ar}  
[baytuhumA]{.trn}  
"their~dual~ house"

## Non-possessive noun-chains

piece of bread, man of wealth, rule of law, nahru -lEurdunn

## Exercises

1. [في البيت باب كبير و باب صغير. دخل الرجل من باب البيت الكبير.]{.ar}  

