# Form 1 incomplete-action verbs-- a-state

## Introduction

Incomplete-action verbs in the a-state differ from the u-state only in the verb endings. Incomplete-action verbs in the a-state are used for specific meanings that we will detail in this chapter.

## Verb table with doer pronouns

The following table shows the a-state incomplete action verbs with doer pronouns, alongside their u-state counterparts.

|Person|Incomplete-action verb doer pronoun|Incomplete-action verb with doer pronoun in the u-state|Incomplete-action verb with doer pronoun in the a-state|
|:---|:--|:----|:----|
| he                |_invisible_           |[يَفْعَلُ]{.ar}   [yafealu]{.trn}   |[يَفْعَلَ]{.ar}   [yafeala]{.trn}   
| she               |_invisible_           |[تَفْعَلُ]{.ar}   [tafealu]{.trn}   |[تَفْعَلَ]{.ar}   [tafeala]{.trn}   
| you~sing.\ masc.~ |_invisible_           |[تَفْعَلُ]{.ar}   [tafealu]{.trn}   |[تَفْعَلَ]{.ar}   [tafeala]{.trn}   
| you~sing.\ fem.~  |[ي]{.ar} [-I]{.trn}   |[تَفْعَلِينَ]{.ar} [tafealIna]{.trn} |[تَفْعَلِي]{.ar} [tafealI]{.trn} 
| I                 |_invisible_           |[أَفْعَلُ]{.ar}   [Eafealu]{.trn}   |[أَفْعَلَ]{.ar}   [Eafeala]{.trn}   
| they~dual\ masc.~ |[ا]{.ar} [-A]{.trn}   |[يَفْعَلَانِ]{.ar} [yafealAni]{.trn} |[يَفْعَلَا]{.ar} [yafealA]{.trn} 
| they~dual\ fem.~  |[ا]{.ar} [-A]{.trn}   |[تَفْعَلَانِ]{.ar} [tafealAni]{.trn} |[تَفْعَلَا]{.ar} [tafealA]{.trn} 
| you~dual~         |[ا]{.ar} [-A]{.trn}   |[تَفْعَلَانِ]{.ar} [tafealAni]{.trn} |[تَفْعَلَا]{.ar} [tafealA]{.trn} 
| they~pl.\ masc.~  |[و]{.ar} [-U]{.trn}   |[يَفْعَلُونَ]{.ar} [yafealUna]{.trn} |[يَفْعَلُوا]{.ar} [yafealU]{.trn} 
| they~pl.\ fem.~   |[نَ]{.ar} [-na]{.trn}  |[يَفْعَلْنَ]{.ar}  [yafealna]{.trn}  |[يَفْعَلْنَ]{.ar}  [yafealna]{.trn}  
| you~pl.\ masc.~   |[و]{.ar} [-U]{.trn}   |[تَفْعَلُونَ]{.ar} [tafealUna]{.trn} |[تَفْعَلُوا]{.ar} [tafealU]{.trn} 
| you~pl.\ fem.~    |[نَ]{.ar} [na]{.trn}   |[تَفْعَلْنَ]{.ar}  [tafealna]{.trn}  |[تَفْعَلْنَ]{.ar}  [tafealna]{.trn}  
| we                |_invisible_           |[نَفْعَلُ]{.ar}   [nafealu]{.trn}   |[نَفْعَلَ]{.ar}   [nafeala]{.trn}   

Note that:

+ For verbs where the u-state is indicated by a [u]{.trn}-mark [◌ُ]{.ar} on the final letter of the verb, the a-state is indicated by an [a]{.trn}-mark [◌َ]{.ar}. For example, [يَفْعَلُ]{.ar} [yafealu]{.trn} (u-state) and [يَفْعَلَ]{.ar} [yafeala]{.trn} (a-state).
+ For verbs where the u-state is indicated by a [ن]{.ar} after the doer pronoun, the a-state is indicated by the loss of the [ن]{.ar}. For example, [يَفْعَلَانِ]{.ar} [yafealAni]{.trn} (u-state) and [يَفْعَلَا]{.ar} [yafealA]{.trn} (a-state).
+ For verbs whose doer pronoun is [نَ]{.ar} and for whom the u-state is not indicated, the a-state is similarly not indicated, and the u-state and a-state verbs are identical. For example, [تَفْعَلْنَ]{.ar} [tafealna]{.trn}.
+ The verbs [يَفْعَلُوا]{.ar} [yafealU]{.trn} and [تَفْعَلُوا]{.ar} [tafealU]{.trn} end with a silent [ا]{.ar} [Ealif]{.trn} which is only written and not pronounced. This extra [ا]{.ar} [Ealif]{.trn} is removed when a doee pronoun is attached, for example [يَفْعَلُوهُ]{.ar} [yafealUhu]{.trn}. This is exactly the same as was done for the completed-action verb [فَعَلُوا]{.ar} [faealU]{.trn}.

