# Unfinished-action verbs -- u-state

## Introduction

We had mentioned that there are approximately 10 commonly used verb forms. And we have already studied the completed-action verb for form 1. In this chapter we will study incomplete-action form 1 verbs. Incomplete-action verbs are used when the action of a verb is on-going at present or will occur in the future.

## Pattern for form 1

Using the root paradigm [فعل]{.arroot}, we have already seen that completed-action verbs for form 1 occur in the patterns [فَعَلَ]{.ar} [faeala]{.trn}, [فَعِلَ]{.ar} [faeila]{.trn}, and [فَعُلَ]{.ar} [faeula]{.trn}. The patterns for form 1 incomplete-action verbs are [يَفٌعَلُ]{.ar} [yafealu]{.trn}, [يَفٌعِلُ]{.ar} [yafeilu]{.trn}, and [يَفٌعُلُ]{.ar} [yafeulu]{.trn}.

Note that the incomplete-action verb forms add an extraneous [يَـ]{.ar} [ya-]{.trn} to the beginning of the verb. This extra letter can change, as we will see soon, to the letters [تَـ]{.ar} [ta-]{.trn}, [نَـ]{.ar} [na]{.trn}, or [أَ]{.ar} [Ea-]{.trn} depending on the doer.

## Vowel-mark on the middle root letter

We have seen that vowel on the middle root letter in a completed-action verb can vary depending on the verb. So we can have,

+ [كَتَبَ]{.ar} [kataba]{.trn} "he wrote"
+ [عَمِلَ]{.ar} [eamila]{.trn} "he worked"
+ [كَبُرَ]{.ar} [kabura]{.trn} "he became big"

Similarly, the vowel on the middle letter in an incomplete-action verb can also vary depending on the verb. Generally, this will need to be looked up in a dictionary and memorized. But there are the following rules which limit the variation:

1. If the completed-action verb has an [a]{.trn}-mark on the middle letter, the incomplete-action verb's middle letter can have either an [a]{.trn}-mark, [i]{.trn}-mark, or an [u]{.trn}-mark, depending on the verb. For example,

   + [كَتَبَ يَكْتُبُ]{.ar} [kataba yaktubu]{.trn} "he wrote, he writes"
   + [ذَهَبَ يَذْهَبُ]{.ar} [pahaba yaphabu]{.trn} "he went, he goes"
   + [كَشَفَ يَكْشِفُ]{.ar} [kacafa yakcifu]{.trn} "he uncovered, he uncovers"

2. If the completed-action verb has an [i]{.trn}-mark on the middle letter, the incomplete-action verb's middle letter will usually have an [a]{.trn}-mark. Rarely, for a few verbs, it may be an [i]{.trn}-mark instead. For example,

   + [عَمِلَ يَعْمَلُ]{.ar} [eamila yaemalu]{.trn} "he worked, he works"
   + [حَسِبَ يَحْسِبُ]{.ar} [Hasiba yaHsibu]{.trn} "he deemed, he deems" <!--see Lane root Hsb for more examples. Also here: https://www.alukah.net/literature_language/0/136210/%D8%A7%D9%84%D9%85%D8%AC%D8%B1%D8%AF-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AB%D9%8A/-->

3. If the completed-action verb has an [u]{.trn}-mark on the middle letter, the incomplete-action verb's middle letter shall have a [u]{.trn}-mark. For example,

   + [كَبُرَ يَكْبُرُ]{.ar} [kabura yakburu]{.trn} "he grew big, he grows big"

It is possible for some incomplete-action verbs to have more than option for the vowel mark on the middle letter. Both variants give the same meaning for the verb. For example, the completed-action verb [حَسِبَبُ]{.ar} [Hasiba]{.trn} "he deemed" has as its incomplete-verb both [يَحْسِبُ]{.ar} [yaHsibu]{.trn} and [يَحْسَبُ]{.ar} [yaHsabu]{.trn}.

## Verb state

As you know, nouns in Arabic have a state that is determined by the function of the noun in the sentence. For example, consider the following sentence:

[سَأَلَ ٱلْغُلَامُ ٱلرَّجُلَ عَنْ شَيْءٍ.]{.ar}  
[saEala -lgulAmu -rrajula Ean cayEin.]{.trn}  
"The boy asked the man about something."

In the above sentence, [ٱَلْغُلَامُ]{.ar} [EalgulAmu]{.trn} is the doer of the verb so it is in the u-state and this is indicated by the [u]{.trn}-mark on its final letter.
[ٱَلرَّجُلَ]{.ar} [Earrujala]{.trn} is the direct doee of the verb so it is in the [a]{.trn} state and this is indicated by the [a]{.trn} mark on its final letter.
[شَيْءٍ]{.ar} [cayEin]{.trn} is directly preceded by a preposition so it is in the [i]{.trn} state and this is indicated by the [in]{.trn} mark on its final letter.
The completed-action verb [سَأَلَ]{.ar}'s ending is not determined based on the function of the verb in the sentence, and therefore, it does not have any state. (The ending can change depending on whether a pronoun is attached to it but this is not related to the function of the verb in the sentence and does not represent any state.)

As opposed to completed-action verbs, which don't have any state, incomplete-action verbs do have a state which is determinined by the function of the verb in a sentence. Similar to nouns, the state of an incomplete-action verb is indicated by the vowel mark or suffix at the end of the verb.

Incomplete action verbs have three states, just like nouns. Two of the states are in common with nouns: the u-state and the a-state. The third state is different from nouns and it is called the ∅-state (null-state).

The [u]{.trn}-mark on the final letter of [يَفُعَلُ]{.ar} [yafealu]{.trn} indicates that it is in the u-state. Will will study only the u-state of incomplete-action verbs in this chapter. And we will study the a-state and ∅-state in later chapters if [#allAh]{.trn2} wills.

## With doer nouns

As with completed-action verbs, doer nouns are placed after the verb in sentence word order. However, the gender of the doer noun affects the beginning of the incomplete-action verb. If the doer noun is masculine, then the verb used is [يَفْعَلُ]{.ar} [yafealu]{.trn}. And if the doer noun is feminine, then the verb used is [تَفْعَلُ]{.ar} [tafealu]{.trn}. Examples:

[يَذْهَبُ ٱلْغُلَامُ إِلَى ٱلْمَدْرَسَةِ.]{.ar}  
[yaphabu -lgulAmu Eila -lmadrasati]{.trn}  
"The boy goes to the school."

[يَعْمَلُ ٱلرَّجُلَانِ فِي ٱلْمَدِينَةِ.]{.ar}  
[yaemalu -rrajulAni fi -lmadInati.]{.trn}  
"The men~dual.~ work in the city."

[تَذْهَبُ ٱلْجَارِيَةُ إِلَى ٱلْمَدْرَسَةِ]{.ar}  
[taphabu -ljAriyatu Eila -lmadrasati]{.trn}  
"The girl goes to the school."

[تَعْمَلُ ٱلنِّسَاءُ فِي بُيُوتِهِنَّ.]{.ar}  
[taemalu -nnisAEu fI buyUtihinna.]{.trn}  
"The women work in their houses."

## With doee nouns and pronouns

Doee nouns and pronouns with incomplete-action verbs work exactly as with completed-action verbs.

[يَسْأَلُ ٱلْغُلَامُ ٱلرَّجُلَ سُؤَالًا.]{.ar}  
[yasEalu -lgulAmu -rrajula suEAlan.]{.trn}  
"The boy asks the man a question."

[يَسْأَلُهَا ٱلْغُلَامُ سُؤَالًا.]{.ar}  
[yasEaluha -lgulAmu suEAlan.]{.trn}  
"The boy asks her a question."

## With doer pronouns

When we studied completed-action verbs, we saw that doer pronouns are either visible or invisible. Visible doer pronouns are added to the end of the verb, modifying the end of the verb in the process.

The doer pronouns for incomplete-action verbs are different from the doer pronouns for completed-action verbs.
Incomplete-action verbs' doer pronouns are also added to the end of the verb, but in addition to modifying the end of the verb, they modify the beginning of the verb as well. Futhermore, additional letters may be added after the doer pronoun to indicate the state of the verb. 

We'll show what all this means in the table below of verbs with doer pronouns. Completed-action verbs are included as well so that you can contrast them with their incomplete-action counterparts.

|Person|Completed-action doer pronoun|Completed-action verb with doer pronoun|Incomplete-action verb doer pronoun|Incomplete-action verb with doer pronoun in the u-state|
|:---|:--|:----|:--|:----|
| he                |_invisible_         |[فَعَلَ]{.ar}    [faeala]{.trn}     |_invisible_         |[يَفْعَلُ]{.ar}   [yafealu]{.trn} |
| she               |_invisible_         |[فَعَلَتْ]{.ar}   [faealat]{.trn}    |_invisible_         |[تَفْعَلُ]{.ar}   [tafealu]{.trn} |
| you~sing.\ masc.~ |[تَ]{.ar} [-ta]{.trn}   |[فَعَلْتَ]{.ar}   [faealta]{.trn}    |_invisible_         |[تَفْعَلُ]{.ar}   [tafealu]{.trn} |
| you~sing.\ fem.~  |[تِ]{.ar} [-ti]{.trn}   |[فَعَلْتِ]{.ar}   [faealti]{.trn}    |[ي]{.ar} [-I]{.trn} |[تَفْعَلِينَ]{.ar} [tafealIna]{.trn} |
| I                 |[تُ]{.ar} [tu]{.trn}   |[فَعَلْتُ]{.ar}   [faealtu]{.trn}    |_invisible_         |[أَفْعَلُ]{.ar}   [Eafealu]{.trn} |
| they~dual\ masc.~ |[ا]{.ar} [-A]{.trn}   |[فَعَلَا]{.ar}   [faealA]{.trn}     |[ا]{.ar} [-A]{.trn}   |[يَفْعَلَانِ]{.ar} [yafealAni]{.trn} |
| they~dual\ fem.~  |[ا]{.ar} [-A]{.trn}   |[فَعَلَتَا]{.ar}  [faealatA]{.trn}   |[ا]{.ar} [-A]{.trn}   |[تَفْعَلَانِ]{.ar} [tafealAni]{.trn} |
| you~dual~         |[تُمَا]{.ar} [-tumA]{.trn} |[فَعَلْتُمَا]{.ar} [faealtumA]{.trn}  |[ا]{.ar} [-A]{.trn}   |[تَفْعَلَانِ]{.ar} [tafealAni]{.trn} |
| they~pl.\ masc.~  |[و]{.ar} [-U]{.trn}   |[فَعَلُوا]{.ar}  [faealU]{.trn}     |[و]{.ar} [-U]{.trn}   |[يَفْعَلُونَ]{.ar} [yafealUna]{.trn} |
| they~pl.\ fem.~   |[نَ]{.ar} [-na]{.trn}   |[فَعَلْنَ]{.ar}   [faealna]{.trn}    |[نَ]{.ar} [-na]{.trn}   |[يَفْعَلْنَ]{.ar}  [yafealna]{.trn} |
| you~pl.\ masc.~   |[تُمْ]{.ar} [-tumA]{.trn}  |[فَعَلْتُمْ]{.ar}  [faealtum]{.trn}   |[و]{.ar} [-U]{.trn}   |[تَفْعَلُونَ]{.ar} [tafealUna]{.trn} |
| you~pl.\ fem.~    |[تُنَّ]{.ar} [-tunna]{.trn}  |[فَعَلْتُنَّ]{.ar}  [faealtunna]{.trn} |[نَ]{.ar} [na]{.trn}   |[تَفْعَلْنَ]{.ar} [tafealna]{.trn} |
| we                |[نَا]{.ar} [nA]{.trn}  |[فَعَلْنَا]{.ar}  [faealnA]{.trn}    |_invisible_         |[نَفْعَلُ]{.ar}   [nafealu]{.trn} |

## REMOVE

So far we have learned finished-action verbs with the different doer-modifications. Finished-action verbs are used when an action is finished. For example, [كَتَبَ]{.ar} [kataba]{.trn} "he wrote" indicates that the act of writing has been finished. An unfinished-action verb is used when the action of the verb has not been finished. 

## Unfinished-action verb states

Unfinished-action verbs have states similar to how nouns have states. This is different from finished-action verbs which don't have state. The table below gives the unfinished-action verb counterparts to the finished-action verb [كَتَبَ]{.ar} [kataba]{.trn} "he wrote":

|u-state|a-state|∅-state|
|:----|:----|:----|
|[يَكْتُبُ]{.ar} [yaktubu]{.trn}|[يَكْتُبَ]{.ar} [yaktuba]{.trn}|[يَكْتُبْ]{.ar} [yaktub]{.trn}|

The basic state of verb is the u-state. [يَكْتُبُ]{.ar} [yaktubu]{.trn} means "he writes" or "he is writing". The a-state and ∅-state unfinished-action verbs give different meanings and we will deal with them in later chapters, if [#allAh]{.trn2} wills. In this chapter we will deal with u-state unfinished-action verbs.

## Unfinished-action verb doer-modifications

Finished-action verbs' doer-modifications are suffixes to the verb. In contrast, unfinished-action verbs' doer-modifications affect both the beginning and the end of the basic verb stem. 

Here is a table of the finished-action verb and and the u-state unfinished-action verb for the root [فَعَلَ]{.arroot}:

|Person|Finished-action|Unfinished-action u-state|
|:---|:----|:--|
| he                |[فَعَلَ]{.ar}    [faeala]{.trn}     |[يَفْعَلُ]{.ar}   [yafealu]{.trn} |
| she               |[فَعَلَتْ]{.ar}   [faealat]{.trn}    |[تَفْعَلُ]{.ar}   [tafealu]{.trn} |
| they~dual\ masc.~ |[فَعَلَا]{.ar}   [faealA]{.trn}     |[يَفْعَلَانِ]{.ar} [yafealAni]{.trn} |
| they~dual\ fem.~  |[فَعَلَتَا]{.ar}  [faealatA]{.trn}   |[تَفْعَلَانِ]{.ar} [tafealAni]{.trn} |
| they~pl.\ masc.~  |[فَعَلُوا]{.ar}  [faealU]{.trn}     |[يَفْعَلُونَ]{.ar} [yafealUna]{.trn} |
| they~pl.\ fem.~   |[فَعَلْنَ]{.ar}   [faealna]{.trn}    |[يَفْعَلْنَ]{.ar}  [yafealna]{.trn} |
| you~sing.\ masc.~ |[فَعَلْتَ]{.ar}   [faealta]{.trn}    |[تَفْعَلُ]{.ar}   [tafealu]{.trn} |
| you~sing.\ fem.~  |[فَعَلْتِ]{.ar}   [faealti]{.trn}    |[تَفْعَلِينَ]{.ar} [tafealIna]{.trn} |
| you~dual~         |[فَعَلْتُمَا]{.ar} [faealtumA]{.trn}  |[تَفْعَلَانِ]{.ar} [tafealAni]{.trn} |
| you~pl.\ masc.~   |[فَعَلْتُمْ]{.ar}  [faealtum]{.trn}   |[تَفْعَلُونَ]{.ar} [tafealUna]{.trn} |
| you~pl.\ fem.~    |[فَعَلْتُنَّ]{.ar}  [faealtunna]{.trn} |[تَفْعَلْنَ]{.ar} [tafealna]{.trn} |
| I                 |[فَعَلْتُ]{.ar}   [faealtu]{.trn}    |[أَفْعَلُ]{.ar}   [Eafealu]{.trn} |
| we                |[فَعَلْنَا]{.ar}  [faealnA]{.trn}    |[نَفْعَلُ]{.ar}   [nafealu]{.trn} |

Note:

+ The unfinished-action verb for "she" is the same as that for "you~sing.\ masc.~": [تَفْعَلُ]{.ar} [tafealu]{.trn}
+ The unfinished-action verb for "they~dual\ fem.~" is the same as that for "you~dual.~": [تَفْعَلَانِ]{.ar} [tafealAni]{.trn} 

## Vowels in unfinished-action verbs

We had mentioned that vowel on the middle letter in a finished-action verb can vary depending on the verb. So we can have,

+ [كَتَبَ]{.ar} [kataba]{.trn} "he wrote"
+ [عَمِلَ]{.ar} [eamila]{.trn} "he worked"
+ [كَبُرَ]{.ar} [kabura]{.trn} "he became big"

Similarly, the vowel on the middle letter in an unfinished-action verb can also vary depending on the verb. So generally, this will need to be looked up in a dictionary and memorized. But there are the following rules which limit the variation:

1. If the finished-action verb has an [a]{.trn}-mark on the middle letter, the unfinished-action verb's middle letter can have either an [a]{.trn}-mark, [i]{.trn}-mark, or an [u]{.trn}-mark, depending on the verb. For example,

   + [كَتَبَ يَكْتُبُ]{.ar} [kataba yaktubu]{.trn} "he wrote, he writes"
   + [ذَهَبَ يَذْهَبُ]{.ar} [pahaba yaphabu]{.trn} "he went, he goes"
   + [كَشَفَ يَكْشِفُ]{.ar} [kacafa yakcifu]{.trn} "he uncovered, he uncovers"

2. If the finished-action verb has an [i]{.trn}-mark on the middle letter, the unfinished-action verb's middle letter can have either an [i]{.trn}-mark or an [a]{.trn}-mark, depending on the verb, with [a]{.trn}-mark being more common. For example,

   + [عَمِلَ يَعْمَلُ]{.ar} [eamila yaemalu]{.trn} "he worked, he works"
   + [حَسِبَ يَحْسِبُ]{.ar} [Hasiba yaHsibu]{.trn} "he deemed, he deems" <!--see Lane root Hsb for more examples. Also here: https://www.alukah.net/literature_language/0/136210/%D8%A7%D9%84%D9%85%D8%AC%D8%B1%D8%AF-%D8%A7%D9%84%D8%AB%D9%84%D8%A7%D8%AB%D9%8A/-->

3. If the finished-action verb has an [u]{.trn}-mark on the middle letter, the unfinished-action verb's middle letter shall have a [u]{.trn}-mark. For example,

   + [كَبُرَ يَكْبُرُ]{.ar} [kabura yakburu]{.trn} "he grew big, he grows big"

It is possible for some unfinished-action verbs to have more than option for the vowel mark on the middle letter. Both variants give the same meaning for the verb. For example, the finished-action verb [حَسِبَبُ]{.ar} [Hasiba]{.trn} "he deemed" has as its unfinished-verb both [يَحْسِبُ]{.ar} [yaHsibu]{.trn} and [يَحْسَبُ]{.ar} [yaHsabu]{.trn}.

## Usage of unfinished-action verbs

Here are some examples of sentences with unfinished-action verbs.

Unfinished-action verbs can, in general, give the meaning of both an action which is habitually done, like "He goes to school." or an action which is being done right now "He is going to school." Both of these can be expressed with [يَذْهَبُ ]{.ar}. But depending on the meaning of the verb and the context, placing the doer before the verb can sometimes indicate that the action is taking place right now.

Later, id [#allAh]{.trn2} wills, we will lear additional techniques to indicate that the action is taking place right now.

Sometimes, the English past tense and present tense may not match the Arabic finished-action and unfinished-action respectively. Examples,

## Unfinished-action verbs for future actions

