---
title: "Fundamentals of Standard Arabic"
subtitle:  "A learner's textbook with grammar, vocabulary, and exercises"
author: "Ahmad Sheikh"
documentclass: book
geometry:
# final
#- paperwidth=170mm
#- paperheight=244mm
#- bindingoffset=6mm
#- twoside
# A4 2 pages per sheet draft
- paper=a5paper               # a5: 148.5 by 210mm
- textwidth=114.8mm           # = (170 - 6)*0.7
- textheight=170.8mm          # = 244 * 0.7
- twoside
mainfont: Junicode
fontsize: 10pt
polyglossia-lang:
  name: en
polyglossia-otherlangs:
  - name: arabic
fontfamilies:
  - name: \arabicfont
    font: Vazir-Light
    options: Script=Arabic,Scale=1.0
  - name: \tradarab
    font: Amiri
    options: Script=Arabic,Scale=1.0
csquotes: true
output:
  bookdown::gitbook:
    pandoc_args: ["--lua-filter=trn.lua"]
    keep_md: yes
    css: mystyle.css
    number_sections: true
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: serif
        size: 2
      sharing:
        facebook: yes
        github: no
        twitter: yes
        linkedin: yes
        weibo: no
        instapaper: no
        vk: no
        all: ['facebook', 'twitter', 'linkedin', 'weibo', 'instapaper']
      info: yes
  bookdown::pdf_book:
    number_sections: true
    pandoc_args: ["--lua-filter=trn.lua", "--columns=65"] # for forcing word wrap in pipe tables
    latex_engine: xelatex
    #template: default_latex_template.tex # with Brill font the PDF font is too large and this needs to be uncommented. includes and in_header should then be commented
    includes:
      in_header: "preamble.tex"
    keep_tex: true
---

# Preface {-}

The primary texts of [#islAm]{.trn2} (the [#qurEAn]{.trn2} and the Sunnah) are in Arabic. So is much of its scholarly literature. However, there is a multitude of Muslims for whom Arabic is not a native language, yet who are familiar enough with English to study textbooks written in this language. The goal of this book is to help them learn Arabic at a beginner's level so that, together with a study of the appropriate expositional texts, they are one step closer to understanding the primary texts in their original language. We hope that this will, if [#allAh]{.trn2} wills, make them feel more connected to the primary texts and their teachings. Furthermore, they can be empowered to study the vast body of Arabic [#islAm]{.trn2}ic literature.

This book is a teaching grammar and not a reference grammar. So, in the initial chapters, topics are presented sequentially at only a basic level, without treating them exhaustively, before moving on to the next topic. Furthermore, since this is a beginner's textbook, only the more common usages are explained.

We have also aimed to make this a self-teaching textbook so that diligent students should, if [#allAh]{.trn2} wills, be able to study it without a instructor. In doing this, we have perhaps made the text more verbose than is usual for an instructor-taught textbook. If the reader finds our text too wordy and prefers a more concise style, we recommend *A New Arabic Grammar of the Written Language* by J. A. Haywood and H. M. Nahmad, 2nd edition, published by Lund Humphries.

In our experience, we have also realized that students are turned off by foreign grammatical terminology, whether Latin-based or Arabic. We believe that terminology is necessary for a rigorous non-immersive study of language. So while we employ terminology, we have tried to make it natural in English. To accomplish this, we have sometimes invented terminology. Other times, we have translated the meaning of Arabic grammar terms to English. In places, we have also used established English grammar terminology where we deemed appropriate. The drawback to this non-standard approach, however, is that the student may not be able to immediately relate the terminology he has learned in this book to established terminology in other grammar textbooks. To remedy this to some extent, we provide a glossary in the appendix which maps the grammatical terminology used in this book to other, established, Latin-based and Arabic-based counterparts.

It may also be appropriate to apprise the reader that we teach Arabic grammar only as a tool to reach our goal of helping the reader learn the language. As such, the grammar presented here may not conform completely with the comprehensive and self-consistent theories developed by the Arabic grammarians. We believe that that classical grammar is best suited to be learned by students who are already competent in basic Arabic. That the student may have to unlearn some of what he has learned here (if and when he studies classical grammar), is a cost that is more acceptable to us than getting the beginner bogged down in complex grammatical details at a stage when he is unable to envisage the necessity of their complexity.

[a.z.s.]{.smallcaps}  
[lahore, dec. 2021]{.smallcaps}  

## Test {-}

This is the _preface_. Test trans [Parf makAn ealayhi pcv machad]{.trn} [◌َ  ◌ً  ◌ِ  ◌ٍ  ◌ُ  ◌ٌ  ◌ْ  ◌ّ  ◌ٰ  ◌ٔ  ◌ٕ  ]{.ar}

[شَيْـَٔيْنِ بَرِيـِٔينَ شَيْـًٔا خَطِيـَٔة]{.ar}

[شَيْءَيْنِ بَرِيءِينَ شَيْءًا خَطِيءَة]{.ar}


this is in [small caPs]{.smallcaps}.
