# Preface {.unnumbered}

[بسم الله الرحمن الرحيم]{.aralt}

<!--The following line is needed because Preface is an unnumbered chapter and otherwise fancy header will print the header text for the previous chapter "Contents"-->
<!--\markboth {\textsc{\MakeLowercase{Preface}}}{\textsc{\MakeLowercase{Preface}}}-->

<!--Sunnah are the sayings and actions of the Prophet صلى الله عليه وسلم.
Hadith is the text by which we know the sunnah.-->

<!-- For font size calibration:-->
<!--
§**28.** a) The short vowels _a, i, u_ are sonant. 
They never occur at the beginning of a syllable (§51).
_y_ and _w_ are consonantal vowels. 
They can appear at the beginning and at the end of a syllable.
Sonant and consonantal vowels may combine homogeneously or heterogeneously:
homogeneous contact _iy = i_, _uw = u_, heterogeneous contact _ay, aw_.
The long vowel _a_ is ambiguous in that it can be regarded as a double sonant o as a sonant-consonantal combination:
_nama_ 'sleep' with _a = a-a_.
-->

The primary texts of [#islAm]{.trn2} (the [#qurEAn]{.trn2} and the [#HadIv]{.trn2}) are in Arabic.
So too is much of its scholarly literature.
However, there are many Muslims for whom Arabic is not a native language, yet who are familiar enough with English to study textbooks written in this language.
The goal of this book is to help them learn Arabic at a beginner's level so that, together with a study of the appropriate expositional texts, they are one step closer to understanding the primary texts in their original language.
We hope that this will, if [#allAh]{.trn2} wills, make them feel more connected to the primary texts and their teachings.
Furthermore, they can be empowered to study the vast body of Arabic [#islAm]{.trn2}ic literature.

<!--The Arabic that we attempt to teach in this book is _Standard Classical Arabic_.
We define this term as follows:-->
Regarding the title of this book: 
the Arabic grammarians were describing _an_ Arabic language, drawing upon a corpus that included transmitted texts and the dialectal speech of informants.
We term the language of this corpus to be _Classical Arabic_ because of its considerable volume and its agreed upon significance and eloquence.
In the process of describing the dialectal variation of Classical Arabic, a standard variety emerged
and gained prevalence. 
Thenceforth, virtually all texts that were composed attempted to conform to the grammar of this standard.
And it is the grammar of this _Standard Classical Arabic_ that is the subject of this work.

While the grammar that we cover in this book is of Standard Classical Arabic, the vocabulary includes post-classical words and meanings, which were a legitimate addition to the language.
But we stop short of dealing with Modern Standard Arabic ([msa]{.smallcaps}) 
because the preponderance of its modern vocabulary would detract from the main focus of this book.
And also because Western grammar works which focus on [msa]{.smallcaps} tend to use modern texts as a corpus to re-describe and re-codify its grammar.
Which can put the grammar of this definition of [msa]{.smallcaps} at odds with the grammar of Standard Classical Arabic.

<!--
Having described Classical Arabic (with its dialectal variation), the grammarians would also give their opinions as to what constituted a normative variety.
also venture into prescribing a standard from amongst the variety found in Classical Arabic.
This Standard Classical Arabic gained prevalence as a written register and was thereafter used for composing and transmitting texts.
-->

This book is a learning or teaching grammar, as opposed to being strictly a reference grammar.
Therefore, generally, topics are covered, and examples are given, in a manner that assumes an understanding of only preceding content.
We have, however, generally tried to origanize content coherently for convenient reference during learning.

We have also aimed to make this a self-instruction textbook so that a diligent student should, if [#allAh]{.trn2} wills, be able to study it independently.
The target learner is someone who has not been exposed to grammatical terminology beyond a grade school level.
While terminology is necessary for a rigorous non-immersive learning of language, we have tried to steer away from Latin-based terms like _accusative_ and _jussive_.
Such terms, when first encountered by an uninitiated learner, may deter him from proceeding further.
So we have in some places translated the meaning of Arabic grammar terms to English.
In other places, we have used established English grammar terms where the terms are basic enough.
We have even, in places, invented terms where we deemed appropriate.
We have also used some grammatical terminology from Arabic directly, usually in cases where our target learner may have already been exposed to them from [tajwId]{.trn2}, or where the term is complex enough that creating a term specifically in English wouldn't make it any simpler.
The drawback to this non-standard approach, however, is that the student may not be able to immediately relate the terminology he has learned in this book to established terminology in other grammar textbooks.
To remedy this to some extent, we provide a glossary which maps the grammatical terminology used in this book to other, established, Latin-based and Arabic-based counterparts.

It may also be appropriate to inform the reader that we chose to present a subset, and sometimes a simplified version, of Arabic grammar.
As such, the grammar presented here may not be entirely consistent with the comprehensive and harmonious framework developed by the Arab grammarians.
We chose this approach because we felt that exposing the beginner to complex grammatical details at this stage would be more of a hindrance than a help in learning the language.

This book is a currently work in progress and is produced using the [Quarto](https://quarto.org/) authoring and publishing framework.
The code and text are open-sourced and developed at 
[github.com/adamiturabi/arabic-tutorial-book](https://github.com/adamiturabi/arabic-tutorial-book).
The typeset output is published at 
[adamiturabi.github.io/arabic-tutorial-book/](https://adamiturabi.github.io/arabic-tutorial-book/).

[the authors]{.smallcaps}  

<!--
[a.z.s.]{.smallcaps}  
[lahore, dec.]{.smallcaps} 2021[ce]{.smallcaps}  
[لاهور، جمادى الأولى ١٤٤٣هـ‍]{.ar}

Test:

This is the _preface_.
Test trans [Parf makAn ealayhi pcv machad]{.trn} [◌َ  ◌ً  ◌ِ  ◌ٍ  ◌ُ  ◌ٌ  ◌ْ  ◌ّ  ◌ٰ  ◌ٔ  ◌ٕ  ]{.ar}

[شَيْـَٔيْنِ بَرِيـِٔينَ شَيْـًٔا خَطِيـَٔة]{.ar}

[شَيْءَيْنِ بَرِيءِينَ شَيْءًا خَطِيءَة]{.ar}


this is in [Small Caps]{.smallcaps}.


```{r setup ,echo=FALSE}
options(tinytex.engine = "lualatex")
```
-->
<!--
# Romanization scheme {.unnumbered}

\markboth {\textsc{\MakeLowercase{Romanization scheme}}}{\textsc{\MakeLowercase{Romanization scheme}}}

The following romanization scheme is used in this book for the transcription and transliteration of Arabic sounds and letters into the Latin script.

[consonants]{.smallcaps}

|   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|  [ص]{.ar}  |  [ش]{.ar}  |  [س]{.ar}  |  [ز]{.ar}  |  [ر]{.ar}  |  [ذ]{.ar}  |  [د]{.ar}  |  [خ]{.ar}  |  [ح]{.ar}  |  [ج]{.ar}  |  [ث]{.ar}  |  [ت]{.ar}  |  [ب]{.ar}  |  [ء]{.ar}  |
| [S]{.trn2} | [c]{.trn2} | [s]{.trn2} | [z]{.trn2} | [r]{.trn2} | [p]{.trn2} | [d]{.trn2} | [x]{.trn2} | [H]{.trn2} | [j]{.trn2} | [v]{.trn2} | [t]{.trn2} | [b]{.trn2} | [E]{.trn2} |

|   |   |   |   |   |   |   |   |   |   |   |   |   |   |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|  [ى]{.ar}  |  [و]{.ar}  |  [ه]{.ar}  |  [ن]{.ar}  |  [م]{.ar}  |  [ل]{.ar}  |  [ك]{.ar}  |  [ق]{.ar}  |  [ف]{.ar}  |  [غ]{.ar}  |  [ع]{.ar}  |  [ظ]{.ar}  |  [ط]{.ar}  |  [ض]{.ar}  |
| [y]{.trn2} | [w]{.trn2} | [h]{.trn2} | [n]{.trn2} | [m]{.trn2} | [l]{.trn2} | [k]{.trn2} | [q]{.trn2} | [f]{.trn2} | [g]{.trn2} | [e]{.trn2} | [P]{.trn2} | [T]{.trn2} | [D]{.trn2}  |

[vowels]{.smallcaps}

|   |   |   |   |   |   |   |   |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| [◌َ]{.ar}   | [◌ُ]{.ar}   | [◌ِ]{.ar}   | [◌َا]{.ar}  | [◌ُو]{.ar}  | [◌ِي]{.ar}  | [◌َوْ]{.ar}   | [◌َيْ]{.ar}   |
| [a]{.trn2} | [u]{.trn2} | [i]{.trn2} | [A]{.trn2} | [U]{.trn2} | [I]{.trn2} | [aw]{.trn2} | [ay]{.trn2} |


When transcribing example text,
the _italic_ Latin script is used,
no letters are capitalized,
a non-sentence-initial connecting hamzah is transliterated with a hyphen (-),
and the [lAm]{.trn2} of the definite article is not transliterated for sun letters.

[ة]{.ar} is transcribed as [h]{.trn} at the end of an utterance, and as [t]{.trn} otherwise.

For example:

[ٱِلْتَقَطَتْ أُمُّ طَلْحَةَ وَٱلْحَسَنِ وَرَقَةَ ٱلشَّجَرَةِ.]{.ar}  
[EiltaqaTat Eummu TalHata wa-lHasani waraqata -ccajarah.]{.trn}



When using Arabic words in the English text,
the regular (non-italic) Latin script is used,
words are transcribed in pausal pronunciation,
word-final [◌ِيّ]{.ar} [-iyy]{.trn} is transcribed as "[I]{.trn2}",
the first letter of a proper noun is capitalized,
word-initial hamzah is not transliterated,
the definite article is always transliterated as "al-" with a hyphen following it,
as shown.
[ة]{.ar} is transcribed as "t" in the middle of an annexation, and as "h" otherwise.

Accurate romanizations are preferred unless an established and distinctly separate usage is current in English.
Examples:

"[#ealI]{.trn2} and [#usAmah]{.trn2} revised [#sUrat al-#eankabUt]{.trn2} from the [#qurEAn]{.trn2} in the mosque in the month of [#rabIe al-#vAnI]{.trn2}."

"The caliphate moved from [al-#madInah]{.trn2} to Damascus."
-->

