# Introduction

All praises are due to [#allAh]{.trn2}. We praise Him, seek His help, and ask for His forgiveness. We seek refuge in [#allAh]{.trn2} from the evil in our souls and from our sinful deeds. Whomever [#allAh]{.trn2} guides, no one can mislead. Whomever [#allAh]{.trn2} leads astray, no one can guide. I bear witness that there is no one worthy of worship except [#allAh]{.trn2}. I also bear witness that [#muHammad]{.trn2} is His servant and messenger.

May the peace and blessings of [#allAh]{.trn2} be upon the Prophet [#muHammad]{.trn2}, the other prophets and messengers, all of their families, and the rest of the righteous.

## History of Arabic 

[#allAh]{.trn2}, may He be glorified and exalted, revealed the [#qurEAn]{.trn2} more than 1400 years ago to the Prophet [#muHammad]{.trn2}, may [#allAh]{.trn2} grant peace and confer blessing upon him. The language of the [#qurEAn]{.trn2} is the Arabic language, as it was understood by the Arabs at that time. The sayings and actions of the Prophet, may [#allAh]{.trn2} grant peace and confer blessing upon him, were recorded by his companions also in this Arabic language. This Arabic is called Classical Arabic. The Classical Arabic language consisted of multiple dialects that were spoken by the different tribes and in the different regions of the Arabian peninsula.

All languages evolve over time. For example, the Old English language spoken 1400 years ago would be unintelligible to us today. But when Arabic began to evolve and change from the Classical Arabic of the time of the Prophet, may [#allAh]{.trn2} grant peace and confer blessing upon him, scholars made efforts to preserve the language of [#allAh]{.trn2}'s revelation.

In preserving Classical Arabic, a standard version, extracted from the Classical Arabic dialects, came to be used as a literary and scientific language. A wealth of scholarly literature exists in this "Standard Arabic". As scholars developed new branches of religious and secular sciences, new terms and meanings were added to this Arabic. A few words were also borrowed from foreign languages as needed by the different scientific disciplines. These additions were, by and large, deliberate, done by scholars who were experts in their field and also well versed in Standard Arabic, and validated by subsequent generations of scholarly discourse.

While Standard Arabic was thus preserved from major change and was used for literary purposes, the language that was spoken by Arabs in their day-to-day lives continued to evolve naturally from the classical dialects into the modern colloquial dialects. And so today, there exist two very distinct types of Arabic: the modern colloquial Arabic dialects which Arabs learn as their mother tongue and are primarily only spoken and not written, and Standard Arabic which is taught at schools and is primarily a written language.

In modern times, many new words and meanings have been added to Standard Arabic, often via translation from Western languages, to keep up with technological advancements and modern media. However, it must be said that these additions were often done by translators rather than scholars in the field, and sometimes lacked the deliberation seen in the additions to pre-modern Standard Arabic. This modern development of Standard Arabic is called Modern Standard Arabic. There are also a small amount of words, meanings, and grammatical usages, which existed in Classical Arabic, but which are deemed archaic, and are therefore largely unused, in Modern Standard Arabic.

## Scope of this book

In this book, we will study Standard Arabic. We will focus on the pre-modern language. If [#allAh]{.trn2} wills, this will help you to begin to understand the language of the [#qurEAn]{.trn2}, the [#HadIv]{.trn2}, and [#islAm]{.trn2}ic literature.

If your goal is to learn Modern Standard Arabic, then this book may still be of help because the core language and the grammar are essentially the same. However, you may prefer to study from a resource that focuses on the modern language.

This book does not touch at all upon the modern colloquial dialects that are spoken in the Arab world today.

## How to study from this book

We will start with the Arabic script and present in each chapter a new concept of Arabic grammar. We will also give vocabulary for you to memorize and have chapter exercises. Unfortunately, some of the sentences we present, both as examples and as chapter exercises, because of their construction and subject matter, may seem of dubious usefulness to a learner wanting to learn practical usage. We ask that you overlook this and bear with us as we try to reinforce grammatical concepts. In answering the exercises, we strongly recommend that you memorize the vocabulary in full and write down the answers on paper with a pen. 

We strongly recomment that you **not**:

+ answer the exercises verbally without writing them down,
+ look up the answers before attempting to write the answer yourself,
+ look up words in the vocabulary list without memorizing them,
+ proceed to the next chapter before memorizing the vocabulary and going through the exercises.

Be aware that while Arabic grammar requires effort to master to a sufficient degree, the real barrier to reading and understanding Arabic texts by oneself is vocabulary. Arabic is a very rich language and knowledge of a few thousand words is needed before the student can begin to read texts independently.

You may also find yourself having to go back a few chapters every once in a while and revising the concepts therein. This is very normal and not a cause for any alarm. It may also prove beneficial to re-do the exercises of that chapter when this occurs.

