# Subject-information verbs

As we've already mentioned Arabic does not normally express the word "is". However, it does express the verb "was".

| Arabic verb | Transcription | Meaning     |
|:------------|:--------------|:------------|
| [كَانَ]{.ar}  | [kAna]{.trn}  | [He] was    |
| [كَانَتْ]{.ar} | [kAnat]{.trn} | [She] was   |

[كَانَ]{.ar} [kAna]{.trn} behaves like any other verb in that its [doer]{.syn} is in the u-state and its [object]{.syn} is in the a-state. Examples:

[كَانَ ٱلْبِنَاءُ مَدْرَسَةً.]{.ar}  
[kAna -lbinAEu madrasatan]{.trn}  
"The building was a school."

[كَانَتِ ٱلْمَرْأَةُ أُمًّا.]{.ar}  
[kAnati -lmarEatu Eumman]{.trn}  
"The woman was a mother."

However, this verb is special and a little different from other verbs. The [doer]{.syn} is not really doing any action. In fact, in meaning it is the [subject]{.syn} of a sentence and the [object]{.syn} of the verb is the [information]{.syn} about the [subject]{.syn}.

[كَانَ]{.ar} [kAna]{.trn} is an example of "[subject-information]{.syn} verbs".  Sentences that start with [subject-information]{.syn} verbs are both [subject]{.syn}-[information]{.syn} sentences and verbal sentences.

There are a few other verbs like [كَانَ]{.ar}, for example:

| Arabic verb | Transcription | Meaning     |
|:------------|:--------------|:------------|
| [صَارَ]{.ar}  | [SAra]{.trn}  | [He] became |
| [صَارَتْ]{.ar} | [SArat]{.trn} | [She] became|

#### Indefinite descriptive nouns with [subject-information]{.syn} verbs

Remember from the previous chapter that there are some verbs classified as [subject-information]{.syn} verbs. The [doer]{.syn} of such a verb is also the [subject]{.syn} of the sentence, and the verb's [object]{.syn} is also the [information]{.syn} of the sentence.

[كَانَ]{.ar} [kAna]{.trn} "[he] was" is such a verb. For example,

[كَانَ ٱلْبِنَاءُ مَدْرَسَةً.]{.ar}  
[kAna -lbinAEu madrasatan]{.trn}  
"The building was a school."

In this sentence, [ٱَلْبِنَاءُ]{.ar} [EalbinAEu]{.trn} "the building" is both the [doer]{.syn} of the verb [كَانَ]{.ar} [kAna]{.trn} and also the [subject]{.syn} of the sentence. And [مَدْرَسَةً]{.ar} [madrasatan]{.trn} "a school" is both the [object]{.syn} of the verb and also the [information]{.syn} of the sentence.

Now in the preceding section, we have learned a rule that if an indefinite descriptive noun is used as the [information]{.syn} of a sentence, then it gives the meaning of an adjective. This rule also applies to sentences with [subject-information]{.syn} verbs: If an indefinite descriptive noun is used as the [information]{.syn} of a [subject-information]{.syn} verb, there here too it will give the meaning of an adjective. For example,

[كَانَ ٱلْبِنَاءُ كَبِيرًا.]{.ar}  
[kAna -lbinAEu kabIran]{.trn}  
"The building was a big one." = "The building was big."

The indefinite descriptive noun [كَبِيرًا]{.ar} [kabIran]{.trn} is the [information]{.syn} of the sentence, therefore it gives the meaning of the adjective "big".


