# Nouns

## Introduction

Here are some examples of common nouns in Arabic:

Arabic word | Transcription|Definition
:-----------|:-----------|:----------------
[رَجُلٌ]{.ar}  |[rajulun]{.trn}   |a man
[كِتَابٌ]{.ar} |[kitAbun]{.trn}   |a book
[بَيْتٌ]{.ar}  |[baytun]{.trn}    |a house
[شَجَرَةٌ]{.ar} |[cajaratun]{.trn} |a tree

## Indefinite and definite nouns

"A book" is [كِتَابٌ]{.ar} [kitAbun]{.trn}. If we want to say "the book" we add [ٱَلْ]{.ar} [al]{.trn} to the beginning of the word and we also change the [n]{.trn}-mark at the end of the word [بٌ]{.ar} [un]{.trn} to the short vowel [بُ]{.ar} [u]{.trn}. The prefix [ٱَلْ]{.ar} [al]{.trn} is called the *definite article"*.

[كِتَابٌ]{.ar}  
[kitAbun]{.trn}  
"a book"

[ٱَلْكِتَابُ]{.ar}  
[alkitAbu]{.trn}  
"the book"

Note that [ٱَلْ]{.ar} [al]{.trn} has a connecting [hamzah]{.trn} so the [hamzah]{.trn} will be pronounced only in the beginning of a sentence.

When a noun has an [n]{.trn}-mark like [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book" we will call it an indefinite noun.
When a noun has [ٱَلْ]{.ar} [al]{.trn} and no [n]{.trn}-mark like [ٱَلْكِتَابُ]{.ar} [alkitAbu]{.trn} "the book" we will call it a definite noun.

## Sun letters and moon letters

“A man” in Arabic is [رَجُلٌ]{.ar} [rajulun]{.trn}. To make this definite we add [ٱَلْ]{.ar} [al]{.trn} to the beginning of the word and we also change the [n]{.trn}-mark at the end of the word [لٌ]{.ar} [un]{.trn} to the short vowel [لُ]{.ar} [u]{.trn}. But instead of becoming [ٱَلْرَجُلُ]{.ar} [alrajulu]{.trn} the word becomes [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn}. The [ل]{.ar} in [ٱَلْ]{.ar} becomes silent and the [ر]{.ar} gets doubled. This happens because the first letter [ر]{.ar} in the word [رَجُلٌ]{.ar} [rajulun]{.trn} is from a group of letters called "sun letters". For all nouns beginning with sun letters, when [ٱَلْ]{.ar} [al]{.trn} is put in the beginning, the [ل]{.ar} in [ٱَلْ]{.ar} becomes silent and the sun letter becomes doubled.

The rest of the letters in the alphabet are called "moon letters" and for these letters [ل]{.ar} in [ٱَلْ]{.ar} does not become silent and the moon letter does not become doubled. For example, we have already seen that [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book" becomes [ٱَلْكِتَابُ]{.ar} [alkitAbu]{.trn} "the book".

The sun letters are [ت ث د ذ ر ز س ش ص ض ط ظ ل ن]{.ar}.  
The moon letters are [ء ب ج ح خ ع غ ف ق ك م ه و ي]{.ar}.

The names "sun letters" and "moon letters" were given because of the Arabic words for "sun" and "moon" respectively. "The sun" in Arabic is [ٱَلشَّمْسُ]{.ar} [accamsu]{.trn} which begins with [ش]{.ar} which causes the [ل]{.ar} in [ٱَلْ]{.ar} to be silent. "The moon" is [ٱَلْقَمَرُ]{.ar} [alqamaru]{.trn} which begins with [ق]{.ar} which does not cause the [ل]{.ar} in [ٱَلْ]{.ar} to be silent. Thus [ش]{.ar} represents the sun letters and [ق]{.ar} represents the moon letters.

Here are some examples of words that begin with sun letters:

Indefinite noun | Definite noun
:-----------|:-----------
[رَجُلٌ]{.ar} [rajulun]{.trn} "a man" | [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} "the man"  
[تَاجِرٌ]{.ar} [tAjirun]{.trn} "a trader" | [ٱَلتَّاجِرُ]{.ar} [attAjiru]{.trn} "the trader"  
[لُعْبَةٌ]{.ar} [luebatun]{.trn} "a toy" | [ٱَللُّعْبَةُ]{.ar} [alluebatu]{.trn} "the toy"  

Here are some examples of words that begin with moon letters:

Indefinite noun | Definite noun
:-----------|:-----------
[كِتَابٌ]{.ar} [kitAbun]{.trn} "a book" | [ٱَﻞْكِتَابُ]{.ar} [alkitAbu]{.trn} "the book"  
[بَيْتٌ]{.ar} [baytun]{.trn}  "a house" | [ٱَﻞْبَيْتُ]{.ar} [albaytu]{.trn} "the house"  
[أَمْرٌ]{.ar} [Eamrun]{.trn} "the affair" | [ٱَﻝْأَمْرُ]{.ar} [alEamru]{.trn} "the affair"  

## The state of a noun

In Arabic, most nouns have a visible state that can be seen by looking at the end of the noun. 

When a noun ends with a [◌ٌ]{.ar} [un]{.trn}-mark or [◌ُ]{.ar} [u]{.trn}-mark, then we say that it is in the u-state. The same noun can also end with [◌ً]{.ar} [an]{.trn}-mark or [◌َ]{.ar} [a]{.trn}-mark in which case it will be in the a-state. And it can also end with [◌ٍ]{.ar} [in]{.trn}-mark or [◌ِ]{.ar} [i]{.trn}-mark, in which case it is in the i-state.

Example:

State         | Indefinite "a book" | Definite "the book"
:-------------|:-----------------|:--------------
u-state       |[كِتَابٌ]{.ar} [kitAbun]{.trn}  |[ٱَلْكِتَابُ]{.ar} [alkitAbu]{.trn} 
a-state       |[كِتَابًا]{.ar} [kitAban]{.trn}  |[ٱَلْكِتَابَ]{.ar} [alkitAba]{.trn} 
i-state       |[كِتَابٍ]{.ar} [kitAbin]{.trn}  |[ٱَلْكِتَابِ]{.ar} [alkitAbi]{.trn} 

The default state of a noun is the u-state. But it may occur in the a-state or i-state depending on its role in a sentence. We will learn more about this later, if Allah wills, when we learn how to form sentences.

Here are examples of a couple more nouns:

State         | Indefinite "a tree" | Definite "the tree"
:-------------|:-----------------|:--------------
u-state       |[شَجَرَةٌ]{.ar} [cajaratun]{.trn}  |[ٱَلشَّجَرَةُ]{.ar} [accajaratu]{.trn} 
a-state       |[شَجَرَةً]{.ar} [cajaratan]{.trn}  |[ٱَلشَّجَرَةَ]{.ar} [accajarata]{.trn} 
i-state       |[شَجَرَةٍ]{.ar} [cajaratin]{.trn}  |[ٱَلشَّجَرَةِ]{.ar} [accajarati]{.trn} 

State         | Indefinite "a man" | Definite "the man"
:-------------|:-----------------|:--------------
u-state       |[رَجُلٌ]{.ar} [rajulun]{.trn}  |[ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} 
a-state       |[رَجُلًا]{.ar} [rajulan]{.trn}  |[ٱَلرَّجُلَ]{.ar} [arrajula]{.trn} 
i-state       |[رَجُلٍ]{.ar} [rajulin]{.trn}  |[ٱَلرَّجُلِ]{.ar} [arrajuli]{.trn} 

## Nouns that begin with connecting [hamzah]{.trn}

When the definite article [ٱَلْ]{.ar} [Eal]{.trn} is prefixed to a noun which begins with a connecting [hamzah]{.trn}, the [hamzah]{.trn} is not pronounced. Instead the [lAm]{.trn} in [ٱَلْ]{.ar} will take an [i]{.trn}-mark. For example, [ٱِبْنٌ]{.ar} [Eibnun]{.trn} "a son" becomes [ٱَلِٱبْنُ]{.ar} [Ealibnu]{.trn} "the son".

## Irregular nouns

There are two nouns which are irregular in their definiteness and indefniteness that we will now discuss:

Besides [رَجُلٌ]{.ar} [rajulun]{.trn} "a man", Arabic has another word for "a man": [ٱِمْرَأٌ]{.ar} [EimraEun]{.trn} (u-state). In the a-state and i-state, this word would regularly become [ٱِمْرَءًا]{.ar} [EimraEan]{.trn} and [ٱِمْرَإٍ]{.ar} [EimraEin]{.trn} respectively. However, as a very common variant, it appears with the [n]{.trn}-marks as shown in the table below:

State         | Regular indefinite | Irregular indefinite
:-------------|:-----------------|:--------------
u-state       |[ٱِمْرَأٌ]{.ar} [EimraEun]{.trn} |[ٱِمْرُؤٌ]{.ar} [EimruEun]{.trn}
a-state       |[ٱِمْرَءًا]{.ar} [EimraEan]{.trn}|[ٱِمْرَءًا]{.ar} [EimraEan]{.trn}
i-state       |[ٱِمْرَإٍ]{.ar} [EimraEin]{.trn} |[ٱِمْرِئٍ]{.ar} [EimriEin]{.trn}

As you can see, the state of the noun affects the vowel not only on the final letter but also on the letter before it. This irregularity is only commonly found with this noun.

Also irregularly, when making this noun definite by prefixing [ٱَلْ]{.ar}, the noun loses its connecting [hamzah]{.trn} altogether and is further modified somewhat from the indefinite. It must be noted that this is the only form allowed for the definite.

State         | Definite
:-------------|:-----------------
u-state       |[ٱَلْمَرْءُ]{.ar} [EalmarEu]{.trn}
a-state       |[ٱَلْمَرْءَ]{.ar} [EalmarEa]{.trn}
i-state       |[ٱَلْمَرْءِ]{.ar} [EalmarEi]{.trn}

The counterpart of this noun [ٱِمْرَأَةٌ]{.ar} [EimraEatun]{.trn} "a woman" is also irregular but only in forming the definite noun:

State         | Indefinite                    | Definite
:-------------|:-----------------|:-----------------
u-state       |[ٱِمْرَأَةٌ]{.ar} [EimraEatun]{.trn}|[ٱَلْمَرْأَةُ]{.ar} [EalmarEatu]{.trn}
a-state       |[ٱِمْرَأَةً]{.ar} [EimraEatan]{.trn}|[ٱَلْمَرْأَةَ]{.ar} [EalmarEata]{.trn}
i-state       |[ٱِمْرَأَةٍ]{.ar} [EimraEatin]{.trn}|[ٱَلْمَرْأَةِ]{.ar} [EalmarEati]{.trn}

By the way, what is difference between [رَجُلٌ]{.ar} [rajulun]{.trn} and [ٱِمْرَأٌ]{.ar} [imraEun]{.trn}?
There is some degree of overlap but the noun [رَجُلٌ]{.ar} [rajulun]{.trn} is used more commonly when talking about male human beings.
[ٱِمْرَأٌ]{.ar} [imraEun]{.trn} is used generally when speaking about "man" generically, for example, in sentences like "Man is a social animal." and "A man should always be honest." It is also often used to mean "a person".

## Usage of definite and indefinite nouns

Consider the noun "time". In English we can make this noun definite using the definite article "the", for example, "The time to act is now." In Arabic, this noun will also take the definite article: [ٱَلْوَقْتُ]{.ar} [Ealwaqtu]{.trn} "the time".

We can also make "time" indefinite using indefinite articles like "a" or "some". For example, "There is a time for work and a time for play." and "We have some time before we need to leave." In Arabic we will make the noun indefinite in both these sentences using an [n]{.trn}-mark: [وَقْتٌ]{.ar} [waqtun]{.trn} "a time" or "some time".

Consider now a third scenario: in English we can also use the word "time" without a definite or indefinite article. For example, "Time is money." Here, the word "time" is used with a general meaning. However, in Arabic, a noun must be either definite or indefinite. So we must choose between [ٱَلْوَقْتُ]{.ar} [Ealwaqtu]{.trn} and [وَقْتٌ]{.ar} [waqtun]{.trn}. In Arabic, [وَقْتٌ]{.ar} [waqtun]{.trn} can only mean "a time" or "some time". [ٱَلْوَقْتُ]{.ar} [Ealwaqtu]{.trn} is then used when we wish to say "time" with a general meaning. So in Arabic the definite noun is used in two ways: 

i. When the definite meaning is desired. For example, "We met at the time we had agreed upon." (Use [ٱَلْوَقْتُ]{.ar} [Ealwaqtu]{.trn} "the time".)
ii. When a general meaning is desired. For example, "There is nothing more valuable than time." (Use [ٱَلْوَقْتُ]{.ar} [Ealwaqtu]{.trn} "time".)

Conversely, [n]{.trn}-marks are used only when an indefinite meaning is desired. For example, "We agreed to meet at a certain time."(Use [وَقْتٌ]{.ar} [waqtun]{.trn} "a time".)

Similarly, sometimes a noun like "home" or "school" is used without either "the" or "a". For example, "He goes to school." and "She went home.". In these cases, we will us the definite article [ٱَلْ]{.ar} in Arabic. So we will say [ٱَلْبَيْتُ]{.ar} [Ealbaytu]{.trn} for "home" and [ٱَلْمَدْرَسَةُ]{.ar} [Ealmadrasatu]{.trn} for "school".

But there is an additional complication: note that English often does not use an indefinte article, even when an indefinite meaning is intended. For example, "We have time." meaning "We have some time." So we will use [وَقْتٌ]{.ar} [waqtun]{.trn} here.

This English usage of an indefinite meaning without an indefnite article is especially true with plurals. For example, "There are books in the bag." Here the intended meaning is "There are some books in the bag." Consequently, in Arabic we will use the indefinite noun [كُتُبٌ]{.ar} [kutubun]{.trn} "some books" not [ٱَلْكُتُبُ]{.ar} [Ealkutubu]{.trn}.

However, there are times when English uses a plural without a definite or indefinite article, and a general meaning is intended. For example, "Books contain knowledge." In this case, in Arabic we will use the definite noun [ٱَلْكُتُبُ]{.ar} [Ealkutubu]{.trn}.

This topic may be a little difficult to completely understand right now because we have not yet learned how to form sentences. Later, you may refer back to this section as needed.

