# Completed-action verbs

## Introduction

Verbs are action words. Verbs can be either _completed-action_ verbs where the action of the verb has been completed, e.g., "The boy went." or _incomplete-action_ verbs where the action of the verb is on-going or not yet completed, e.g., "The boy goes." In this chapter we will study _completed-action_ verbs.

## Arabic word roots

We take this opportunity to learn about Arabic roots. 
Native Arabic words, both nouns and verbs, are generally derived from roots. Most roots are comprised of three letters. A smaller number are comprised of four or more letters. 

Words are derived from their roots according to patterns. In traditional Arabic grammar studies, the root [فعل]{.arroot} is used as a paradigm for three-letter roots to showcase word and meaning patterns. 

So for example, the word [بَيْتٌ]{.ar} [baytun]{.trn} "a house" is derived from the root [بيت]{.arroot}. And [أَمْرٌ]{.ar} [Eamrun]{.trn} "an affair" is derived from the root [ءمر]{.arroot}. Using the paradigm root [فعل]{.arroot}, we will say that the pattern of both these words is [فَعْلٌ]{.ar} [faelun]{.trn}.

Similarly, the word [مَكْتَبٌ]{.ar} [maktab]{.trn} "a library" is derived from the root [كتب]{.arroot}. And [مَلْعَبٌ]{.ar} [maleabun]{.trn} "a playground" is derived from the root [لعب]{.arroot}. Using the paradigm root [فعل]{.arroot}, we will say that the pattern of both these words is [مَفْعَلٌ]{.ar} [mafealun]{.trn}. Here the letter [م]{.ar} [m]{.trn} is an extraneous letter added to form the word and is not part of the root.

Verbs, too, are derived from roots. All verbs are derived from their roots in a fixed set of patterns called _forms_ which are numbered 1 onward. For example, the completed-action form 2 verb pattern is [فَعَّلَ]{.ar} [faeeala]{.trn} and the completed-action form 3 verb pattern is [فَاعَلَ]{.ar} [fAeala]{.trn}. There are approximately 9-10 forms that are in common usage. There are a few higher order forms that are less common. In this chapter will study the completed-action form 1 verb only.

## The form 1 completed-action verb

Here are some examples of completed-action form 1 verbs in Arabic:

Root | Completed-action form 1 verb| Meaning
:----|:----|:----
[فعل]{.arroot} |[فَعَلَ]{.ar} [faeala]{.trn} |"did"
[ذهب]{.arroot} |[ذَهَبَ]{.ar} [pahaba]{.trn} |"went"
[كتب]{.arroot} |[كَتَبَ]{.ar} [kataba]{.trn} |"wrote"
[جعل]{.arroot} |[جَعَلَ]{.ar} [jaeala]{.trn} |"made"
[ضرب]{.arroot} |[ضَرَبَ]{.ar} [Daraba]{.trn} |"hit"
[علم]{.arroot} |[عَلِمَ]{.ar} [ealima]{.trn} |"knew"
[عمل]{.arroot} |[عَمِلَ]{.ar} [eamila]{.trn} |"worked"
[كبر]{.arroot} |[كَبُرَ]{.ar} [kabura]{.trn} |"grew"

Note that [فعل]{.arroot}, in addition to being used as a paradigm root, also has a verb in its own right: [فَعَلَ]{.ar} [faeala]{.trn} "did".

Note, also, that the completed-action form 1 verb consists only of the three letters of the root. The first and the final letter always have an [a]{.trn}-mark while the middle letter's vowel is variable. It may have an [a]{.trn}-mark, [i]{.trn}-mark, or an [u]{.trn}-mark, depending on the verb. Using the paradigm root [فعل]{.arroot}, we can say that the form 1 verb occurs in the patterns [فَعَلَ]{.ar}, [فَعِلَ]{.ar}, and [فَعُلَ]{.ar}. 

A good dictionary will tell us the middle vowel mark of a particular verb. However, as a trend, the [a]{.trn}-mark is the most common for the middle vowel mark, followed by the [i]{.trn}-mark, while the [u]{.trn}-mark is the least common.

Interestingly, there can exist multiple verbs from the same root, each with its own distinct meaning, that differ only in the vowel mark on the middle letter. The most common example is:

+ [حَسَبَ]{.ar} [Hasaba]{.trn} "calculated"
+ [حَسِبَ]{.ar} [Hasiba]{.trn} "deemed"

You can see above how the verb [كَتَبَ]{.ar} [kataba]{.trn} "wrote" is derived from the root [كتب]{.arroot}. We have already, by the way, learned another word derived from this root: the noun [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book", which is on the pattern [فِعَالٌ]{.ar} [fieAlun]{.trn}. Note how both the verb and the noun derived from this root have a meaning that is common and has to do with writing or of something written. 
In a similar manner, you will often see that words derived from the same root generally share some common meaning, although this common meaning may not always be obvious or straightforward.

## Verbal sentences

We have already learned of subject-information sentences. Here we will learn of a new type of sentence called a _verbal sentence_. A verbal sentence is one that begins with a verb.

When a verb is in a sentence, it requires a doer. A doer is a noun or a pronoun that does the action of the verb. For example, in the sentence "The boy went.", the noun "the boy" is the doer of the verb.

### Verbs with a masculine doer noun

Consider the sentence:

"The boy went." 

In order to express this sentence in Arabic, we will say:

[ذَهَبَ ٱلْغُلَامُ.]{.ar}  
[pahaba -lgulAmu.]{.trn}  
"The boy went." 

[ذَهَبَ]{.ar} [pahaba]{.trn} "went" is the verb and [ٱلْغُلَامُ]{.ar} [algulAmu]{.trn} "the boy" is the doer. Note how the doer is in the u-state. Also note that in English the doer comes before the verb whereas in Arabic the doer comes after the verb.
In Arabic, a doer noun shall always be in the u-state and shall come after the verb in word order.

The basic form of the verb [ذَهَبَ]{.ar} [pahaba]{.trn} is specifically for masculine doers. We shall see in the next section how the verb is modified for feminine doers. 

The doer may be definite, indefinite, a common noun, or a proper noun. Examples:

A boy went.

Muhammad went.

The time went.

### Verbs with a feminine doer noun

Now consider the sentence:

"A girl went." 

In order to express this sentence in Arabic, we will say:

[ذَهَبَتْ جَارِيَةٌ.]{.ar}  
[pahabat jAriyatun]{.trn}  
"A girl went." 

Note that we have modified the verb by adding on the letter [تْ]{.ar} at the end. This [تْ]{.ar} is to indicate that the doer is feminine and is called the [تْ]{.ar} of femininity. If the word following the noun begins with a connecting [hamzah]{.trn} then we add a helper vowel to the [تْ]{.ar} and it becomes [تِ]{.ar}. Examples:

[ذَهَبَتِ ٱلْبَقَرَةُ.]{.ar}  
[pahabati -lbaqaratu.]{.trn}  
"The cow went."

[ذَهَبَتِ ٱمْرَأَةٌ.]{.ar}  
[pahabati -mraEatun.]{.trn}  
"A woman went."

Note that whether or not we add a helper vowel to [تْ]{.ar}, the letter before it always has an [a]{.trn}-mark.

## Verbs with doees

### Direct doees

Consider the sentence:

"The man wrote a book."

In this sentence, "wrote" is the verb, "the man" is the doer, and "a book" is what we shall call the _doee_. In fact, it is what we shall call a _direct doee_ because it comes directly after the verb without an intermediate preposition. A doee is the noun to whom the action of verb is done. 

In Arabic, we will express the sentence "The man wrote a book." by saying:

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrajulu kitAban.]{.trn}  
"The man wrote a book."

Note how in Arabic the doee [كِتَابًا]{.ar} [kitAban]{.trn} "a book" is in the a-state. This is because, in Arabic, verbs shall cause a direct doee to be in the a-state. This is true whether the direct doee is definite or indefinite. Here is another example:

[ضَرَبَتِ ٱلْمَرْأَةُ ٱلْجَارِيَةَ.]{.ar}  
[Darabati -lmarEatu -ljAriyata.]{.trn}  
"The woman hit the girl."

Note again how [ٱلْجَارِيَةَ]{.ar} [aljAriyata]{.trn} "the girl" is in the a-state because it is a direct doee.

### Multiple direct doees

Some verbs can take more than one direct doee. In this case, all direct doees shall be in the a-state. For example,

[جَعَلَ ٱللَّـٰهُ ٱلرَّجُلَ مُسْلِمًا.]{.ar}  
[jaeala -llAhu -rrajula musliman.]{.trn}  
"[#allAh]{.trn2} made the man a Muslim."

In this sentence both [ٱلرَّجُلَ]{.ar} [arrajula]{.trn} "the man" and [مُسْلِمًا]{.ar} [musliman]{.trn} "a Muslim" are direct doees of the verb [جَعَلَ]{.ar} [jaeala]{.trn} and therefore both are placed in the a-state.

### Indirect doees

Instead of, or in addition to, direct doees, some verbs take an _indirect doee_. An indirect doee is one before which there is a preposition. For example, in English we might say:

"The man looked at the moon."

In this sentence, "the moon" is an indirect doee because it is preceded by the preposition "at". Similarly, in Arabic, we will say:

[نَظَرَ ٱلرَّجُلُ إِلَى ٱلْقَمَرِ.]{.ar}  
[naPara -rrajulu Eila -lqamari.]{.trn}  
"The man looked at the moon."

In this sentence [ٱَلْقَمَرِ]{.ar} [alqamari]{.trn} "the moon" is an indirect doee of the verb [نَظَرَ]{.ar} [naPara]{.trn} "looked" because it is preceded by the preposition [إِلَىٰ]{.ar} [EilA]{.trn} "to". The preposition also causes the indirect doee to be in the i-state, as opposed to the a-state of the direct doee.

Note also, that the verb "looked" in English used the preposition "at" whereas the Arabic verb [نَظَرَ]{.ar} [naPara]{.trn} used the preopsition [إِلَىٰ]{.ar} [EilA]{.trn} "to" for the same meaning. This is very common and you should not expect Arabic to use exact counterparts of the prepositions used in English. In fact, everytime you learn a new verb, you should also learn the prepositions that go with it.

It is also possible for the same verb to take different prepositions with possibly different meanings. So, for example, we can say:

[نَظَرَ ٱلرَّجُلُ فِي ٱلْأَمْرِ.]{.ar}  
[naPara -rrajulu fi -lEamri.]{.trn}  
"The man looked into the matter."
<!-- « فَنَظَرَ نَظْرَة فِي النُّجُومِ» سورة الصافات(88) -->

It may also be possible for the same verb to take a direct doee. So we could also say:

[نَظَرَ ٱلرَّجُلُ ٱلْمَكْتُوبَ فِي ٱلْكِتَابِ.]{.ar}  
[naPara -rrajulu -lmaktUba fi -lkitAbi.]{.trn}  
"The man viewed what was written in the book."
<!--This example from Lane. Also: « يَوْمَ يَنظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ» سورة النبأ،(40)-->

A good dictionary will tell us which prepositions are used with indirect doees with a given verb and also whether it takes a direct doee.

By the way, it is entirely possible that an English verb may take a direct doee, while the corresponding Arabic verb may only take an indirect doee. The reverse is also quite possible. For example,

[غَفَرَ ٱللَّـٰهُ لِلْمُسْلِمِ.]{.ar}  
[gafara -llAhu lilmuslimi.]{.trn}  
"[#allAh]{.trn2} forgave the Muslim."

## Verbs with doer pronouns

A pronoun may replace a noun as the doer of a verb. For example, instead of saying "The man went", you can say "he went", or "you went", etc. 
In Arabic too doer nouns may be replaced with doer pronouns. 
Doer pronouns are attached to the end of the basic form of the verb.

Here we show the singular doer pronouns in Arabic. The root template [فعل]{.arroot} is used to show how the doer pronouns attach the the verb. The middle root letter of [فعل]{.arroot} has an [a]{.trn}-vowel [◌َ]{.ar} here but this vowel will vary for other verbs.

Person | Doer pronoun | Doer pronoun with verb
:------|:--|:--
Absent person (masc.) "he"  | _invisible_          | [فَعَلَ]{.ar} [faeala]{.trn}
Absent person (fem.)  "she" | _invisible_          | [فَعَلَتْ]{.ar} [faealat]{.trn}
Addressed person (masc.)  "you~masc.~" | [تَ]{.ar} [-ta]{.trn} | [فَعَلْتَ]{.ar} [faealta]{.trn}
Addressed person (fem.)  "you~fem.~"   | [تِ]{.ar} [-ti]{.trn} | [فَعَلْتِ]{.ar} [faealti]{.trn}
Speaking person (masc. and fem.)  "I"  | [تُ]{.ar} [-tu]{.trn} | [فَعَلْتُ]{.ar} [faealtu]{.trn}

Note how the doer pronouns for the absent persons "he" and "she" say _invisible_. In Arabic, doer pronouns are either visible or invisible. We shall see what this means with examples.

Note also how the visible singular doer pronouns modify the basic verb by replacing the [a]{.trn}-mark [◌َ]{.ar} on the final letter by a ∅-mark [◌ْ]{.ar}.

Furthermore, note how the doer pronoun for the addressed person "you" is differentiated for masculine and feminine doers whereas the doer pronoun for the speaking person "I" is the same for both genders.

Here are some examples of sentences with visible doer pronouns:

[ذَهَبْتُ]{.ar}  
[pahabtu]{.trn}  
"I went"

[كَتَبْتَ كِتَابًا.]{.ar}  
[katabta kitAban.]{.trn}  
"You~masc.~ wrote a book."

Now we come to the invisible doer pronouns. When we wish to use the doer pronouns for the absent person "he" and "she" we will simply delete the doer noun that the pronoun is replacing without any other changes. The doer pronoun will then be said to exist, because it is required for the meaning of the sentence, but it will be invisible. Here are some examples.

[كَتَبَ كِتَابًا.]{.ar}  
[kataba kitAban.]{.trn}  
"He wrote a book."

[ذَهَبَتْ.]{.ar}  
[pahabat.]{.trn}  
"She went."

Take care to note that the singular doer pronouns modify the final letter of the basic verb, whereas the [تْ]{.ar} of femininity does not. So make sure you see the difference in the following two sentences:

[ضَرَبْتِ ٱلْجَارِيَةَ.]{.ar}  
[Darabti -ljAriyata.]{.trn}  
"You~fem.~ hit the girl."

[ضَرَبَتِ ٱلْجَارِيَةَ.]{.ar}  
[Darabati -ljAriyata.]{.trn}  
"She hit the girl."

## Verbs with doee pronouns

Just like doer nouns may be replaced with doer pronouns, doee nouns may too be replaced with _doee pronouns_. Doee pronouns are also attached to the end of the verb but they don't modify the vowel on the final letter of the verb. The doee pronouns are the same attached pronouns that are also used with prepositions:

Person | Doee pronoun
:------|:--
Absent person (masc.) "him" | [هُ]{.ar} [-hu]{.trn}
Absent person (fem.)  "her" | [هَا]{.ar} [-hA]{.trn}
Addressed person (masc.)  "you~masc.~" | [كَ]{.ar} [-ka]{.trn}
Addressed person (fem.)  "you~fem.~"   | [كِ]{.ar} [-ki]{.trn}
Speaking person (masc. and fem.)  "me" | [◌ِي]{.ar} [-I]{.trn} and [يَ]{.ar} [-ya]{.trn}

Here are some notes regarding their usage:

+ Doee pronouns shall always be attached to the verb. So if there is a doer noun then it shall be placed after the attached doee pronoun. For example:

  [سَأَلَهُ ٱلْغُلَامُ.]{.ar}  
  [saEalahu -lgulAmu.]{.trn}  
  "The boy asked him."

+ If however, the doer is also a pronoun, then it shall be attached first to the verb and then the doee pronoun shall be attached to the doer pronoun. For example,

  [سَأَلْتُكِ.]{.ar}  
  [saEaltuki.]{.trn}  
  "I asked you~fem.~."

+ If the doer pronoun is invisible, then the doee pronoun shall be attached to the verb again directly with only a possible [تْ]{.ar} of femininity intervening. For example:

  [سَأَلَهَا.]{.ar}  
  [saEalahA.]{.trn}  
  "He asked her."

  [سَأَلَتْكَ.]{.ar}  
  [saEalatka.]{.trn}  
  "She asked you~masc.~."

+ If the doee pronoun [هُ]{.ar} [-hu]{.trn} "him" is preceded by the vowels [i]{.trn}, [I]{.trn}, or [ay]{.trn} then it shall instead become [هِ]{.ar} [hi]{.trn} with no change in meaning. For example,

  [سَأَلْتِهِ.]{.ar}  
  [saEaltihi]{.trn}  
  "You~fem.~ asked him."

+ An intervening [ن]{.ar} is always used between the verb and the speaking person doee pronouns [◌ِي]{.ar} [-I]{.trn} and [يَ]{.ar} [-ya]{.trn}. Remember that these pronouns force any consonant before it to have a [i]{.trn}-mark [◌ِ]{.ar}. Therefore, the combination will be written as [نِي]{.ar} [-nI]{.trn} and [نِيَ]{.ar} [-niya]{.trn} respectively. For example:

  [سَأَلَنِي رَجُلٌ.]{.ar}  
  [saEalanI rajulun.]{.trn}  
  "A man asked me."

  [سَأَلَنِيَ ٱلرَّجُلُ.]{.ar}  
  [saEalaniya -rrajulu.]{.trn}  
  "The man asked me."

  <!--The [ن]{.ar} is purely for intervening between the verb and the doee pronoun and has no meaning on its own.-->
  If there is a visible doer pronoun, the intervening [ن]{.ar} shall come after it so that the [ن]{.ar} is always connected to the doee pronoun. For example,

  [سَأَلْتَنِي.]{.ar}  
  [saEaltanI]{.trn}  
  "You~(masc.)~ asked me."

  By the way, we have already seen this intervening [ن]{.ar} before when it was used with some prepositions, e.g. [مِنِّي]{.ar} [minnI]{.trn}, [عَنِّي]{.ar} [eannI]{.trn}, and [لَدُنِّي]{.ar} [ladunnI]{.trn}
  <!--So why don't we simply incorporate the [ن]{.ar} with the doee pronoun and say that the doee pronoun for "me" is [نِي]{.ar} [-nI]{.trn} and [نِيَ]{.ar} [-niya]{.trn}? This is because in addition to their use as doee pronouns, these same pronouns are also used in other places as we shall see later, if [#allAh]{.trn2} wills, and in those cases there is often no intervening [ن]{.ar} for the speaking person pronoun. -->

  Note how we used [يَ]{.ar} [-ya]{.trn} when it was followed by a connecting [hamzah]{.trn} ([سَأَلَنِيَ ٱلرَّجُلُ]{.ar}), and [◌ِي]{.ar} [-I]{.trn} when it was not followed by a connecting [hamzah]{.trn} ([سَأَلَنِي زَيْدٌ]{.ar}). Such is often the case. But it is also quite common for [◌ِي]{.ar} to be used when followed by a connecting [hamzah]{.trn}. When this happens, the vowel will be shortened to [i]{.trn} in pronunciation, although the [◌ِي]{.ar} is retained in writing. For example,

  [سَأَلَنِي ٱلرَّجُلُ.]{.ar}  
  [saEalani -rrajulu.]{.trn}  
  "The man asked me."

  <!--However, [يَ]{.ar} [-ya]{.trn} is typically not used as a doee pronoun if not followed by a connecting [hamza]{.trn}. -->

  To summarize, generally speaking, although both are often permissible, [◌ِي]{.ar} [-I]{.trn} is the more commonly used in all circumstances except in specific cases where [◌ِي]{.ar} [-I]{.trn} is impermissible and [يَ]{.ar} [-ya]{.trn} is required. We will mention those cases when we encounter them, if [#allAh]{.trn2} wills.

<!--Examples from Quran: لا يَنَالُ عَهْدِي الظَّالِمِينَ).

2- في كلمات أخرى، هي: (مَعِيَ) حيثما وقعت، و(أَجْرِيَ إلاَّ) وهي في تسعة مواضع، و(يَدِيَ إِلَيْكَ) بالمائدة، (وَأُمِّيَ إِلَهَيْنِ) بالمائدة، و(بَيْتِيَ لِلطَّائِفِينَ) بالبقرة والحج، و(بَيْتِيَ مُؤْمِنًا) بنوح، و(وَجْهِيَ للهِ) بآل عمران، و(وَجْهِيَ لِلَّذِي) بالأنعام 

http://www.alfaseeh.com/vb/showthread.php?t=93064A-->

## Order of words in a sentence

### Changing the order of words for emphasis

In Arabic, the doer always follows the verb. So the normal order of a sentence is verb-doer-doee. For example,

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrajulu kitAban.]{.trn}  
"The man wrote a book."

However, we will often come across sentences like:

[ٱَلرَّجُلُ كَتَبَ كِتَابًا.]{.ar}  
[Earrajulu kataba kitAban.]{.trn}

It may appear as if [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} is the doer and it is coming before the verb [كَتَبَ]{.ar} [kataba]{.trn}. But actually, this is not the case. As a matter of fact, this sentence is basically a subject-information sentence. 

Here [ٱَلرَّجُلُ]{.ar} [arrajulu]{.trn} "the man" is the subject of the sentence, and [كَتَبَ كِتَابًا]{.ar} [kataba kitAban.]{.trn} "he wrote a book", itself a verbal sentence with an invisible doer pronoun, is the information about the subject. So the translation of the sentence is technically:

"The man, he wrote a book."

However, this is an awkward sentence in English so we will translate it as "The man wrote a book." But this is also the translation of:

[كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar}  
[kataba -rrajulu kitAban.]{.trn}  
"The man wrote a book."

So why then would we say [ٱَلرَّجُلُ كَتَبَ كِتَابًا.]{.ar} [Earrajulu kataba kitAban.]{.trn} instead of the more normal [كَتَبَ ٱلرَّجُلُ كِتَابًا.]{.ar} [kataba -rrajulu kitAban.]{.trn}? The answer is that this change in the sentence's word order is done in order to give more emphasis to the doer, as if to say:

"_The man_ wrote a book."

So in Arabic, the order of words is generally more flexible than in English and this is often used to give emphasis to certain words.

### Indefinite doers

If a verb's doer is an indefinite noun, it is often, but not always, placed at the end of the sentence. This too is for emphasis. For example,

[كَتَبَ ٱلْكِتَابَ رَجُلٌ.]{.ar}  
[kataba -lkitAba rajulun.]{.trn}  
"A man wrote the book."

### Multiple verbs for one doer

In a sentence that has multiple verbs separated by "and", normally one of them is placed before the doer and the rest after it. For example,

[أَكَلَ ٱلرَّجُلُ وَشَرِبَ.]{.ar}  
[Eakala -rrajulu wacariba.]{.trn}  
"The man ate and drank."

## Separating doee pronouns from the verb

We have mentioned that doee pronouns are attached to the verb. Sometimes there is a need to separate the doee pronoun from the verb. When separating the doee pronoun from the verb, it is instead attached to the prefix [إِيَّا]{.ar} [EiyyA]{.trn}. So then we get the following doee pronouns:

Person | Doee pronoun
:------|:--
Absent person (masc.) "him" | [إِيَّاهُ]{.ar} [EiyyAhu]{.trn} 
Absent person (fem.)  "her" | [إِيَّاهَا]{.ar} [EiyyAhA]{.trn}
Addressed person (masc.)  "you~masc.~" | [إِيَّاكَ]{.ar} [EiyyAka]{.trn} 
Addressed person (fem.)  "you~fem.~"   | [إِيَّاكِ]{.ar} [EiyyAki]{.trn} 
Speaking person (masc. and fem.)  "me" | [إِيَّايَ]{.ar} [EiyyAya]{.trn} 

Note that for the speaking person "me", there is no intervening [ن]{.ar} between the prefix [إِيَّا]{.ar} [EiyyA]{.trn} and the doee pronoun. Note also that only [يَ]{.ar} [-ya]{.trn} is allowed to be attached to the prefix [إِيَّا]{.ar} [EiyyA]{.trn}. This is because [◌ِي]{.ar} [-I]{.trn} is not permitted to be used with words that end in a long vowel ([-A]{.trn}, [-I]{.trn}, or [-U]{.trn}) or a semi-vowel ([-ay]{.trn} or [-aw]{.trn}). And the prefix [إِيَّا]{.ar} [EiyyA]{.trn} ends with the long-vowel [A]{.trn}.

But we may ask why is there a need to separate the doee pronoun from the verb? This can occur for a couple of reasons:

i. If there are multiple doee pronouns, only one of them can be attached to the verb. Example,

   [ضَرَبَتْنِي وَإِيَّاهُ.]{.ar}  
   [DarabatnI wa EiyyAhu.]{.trn}  
   "She hit me and him."

ii. If the doee is placed before the verb for emphasis. Example,

    [إِيَّايَ ضَرَبَتْ.]{.ar}  
    [EiyyAya Darabat.]{.trn}  
    "She hit _me_."

## TODO

1. Multiple verb doers: Copy over from sound plurals and rework.
2. [جواز تأنيث الفعل ووجوبه]{.ar}

