# Prepositions

Prepositions are words like "in", "on", "at", etc. 

Prepositions come before a noun and put it in the i-state. For example the preposition [فِي]{.ar} [fI]{.trn} means "in". We can put it before the noun [بَيْتٌ]{.ar} [baytun]{.trn} "a house":

[فِي بَيْتٍ]{.ar}  
[fI baytin]{.trn}  
"in a house"

Note how the noun [بَيْتٍ]{.ar} [baytin]{.trn} "a house" is in the i-state because of the preposition before it, shown by the [in]{.trn}-mark under the [tAE]{.trn} [تٍ]{.ar}.

Arabic has two types of prepositions: _true_ prepositions and _pseudo_-prepositions.

## True prepositions

True prepositions are _particles_ that don't have the properties of nouns. Thus, they cannot be definite or indefinite. They cannot be preceded by [ٱَلْ]{.ar} [al]{.trn} or ended with an [n]{.trn}-mark. And they don't have states (u-state, a-state, and i-state). 

Here is a list of the more common true prepositions:

Preposition | Transcription | Meaning
:-------|:-------|:-------------
[بِ]{.ar}   |[bi]{.trn}   | with, by, next to
[لِ]{.ar}   |[li]{.trn}   | for, to
[فِي]{.ar}  |[fI]{.trn}   | in
[عَلَىٰ]{.ar} |[ealA]{.trn} | on
[إِلَىٰ]{.ar} |[EilA]{.trn} | to, toward
[مِنْ]{.ar}  |[min]{.trn}  | from
[عَنْ]{.ar}  |[ean]{.trn}  | from, about
[كَ]{.ar}   |[ka]{.trn}   | like

Notes:

+ Prepositions that are a single letter (like 
[بِ]{.ar} [bi]{.trn}, [ل]{.ar} [li]{.trn}, [كَ]{.ar} [ka]{.trn}) are joined to the following noun in writing. Example:
  
  [بِقَلَمٍ]{.ar}  
  [biqalamin]{.trn}  
  "with a pen"

  [لِرَجُلٍ]{.ar}  
  [lirajulin]{.trn}  
  "for a man"

  [كَٱمْرَأَةٍ]{.ar}  
  [ka-mraEatin]{.trn}  
  "like a woman"

+ When a single letter preposition comes before a definite noun with [ٱَلْ]{.ar} [al]{.trn}, the preposition is generally joined to the [alif]{.trn} in the [ٱَلْ]{.ar} [al]{.trn}. The [alif]{.trn} is now not pronounced (because as we know it has a connecting [hamzah]{.trn}). Example:

  [بِٱلْقَلَمِ]{.ar}  
  [bi-lqalami]{.trn}  
  "with a pen"

+ The only exception is the preposition [لِ]{.ar} [li]{.trn}. When joined to a definite noun with [ٱَلْ]{.ar} [al]{.trn}, the [alif]{.trn} in [ٱَلْ]{.ar} is dropped and we write two [lAm]{.trn}s together. Example:

  [لِلرَّجُلِ]{.ar}  
  [li-rrajuli]{.trn}  
  "for the man"

  However, if the noun too starts with a [lAm]{.trn}, then we drop the entire [ٱَلْ]{.ar} [al]{.trn}. This is to avoid having three [lAm]{.trn}s joined to each other. Example:

  [ٱَللُّعْبَةُ]{.ar}  
  [Ealluebatu]{.trn}  
  "the toy"

  becomes

  [لِلُّعْبَةِ]{.ar}  
  [li-lluebati]{.trn}  
  "for the toy"

  not 

  [لِللُّعْبَةِ]{.ar}  

+ The prepositions 
[عَلَىٰ]{.ar} [ealA]{.trn} "on" and
[إِلَىٰ]{.ar} [EilA]{.trn} "to" have a long-[A]{.trn} vowel at the end but it is written with a dotless [yAE]{.trn} [ىٰ]{.ar} instead of an [alif]{.trn}. (We have already learned that some words are written this way.)

+ Prepositions that are composed of multiple letters are not joined to the following noun. Example:

  [إِلَىٰ مَدْرَسَةٍ]{.ar}  
  [EilA madrasatin]{.trn}  
  "to a school"

+ If a preposition ends with a long vowel, then (just like other words that end with long vowels), when it is followed by a word which begins with a connecting [hamzah]{.trn}, the ending is pronounced as a short vowel that connects to the following word.. Examples:

  [فِي ٱلْبَيْتِ]{.ar}  
  [fi -lbayti]{.trn}  
  "in the house"

  [إِلَى ٱمْرَأَةٍ]{.ar}  
  [Eila -mraEatin]{.trn}  
  "to a woman"

+ If a preposition ends with a null-vowel mark [◌ْ ]{.ar} and it is followed by a word that begins with a connecting [hamzah]{.trn}, then the null-vowel mark is changed to a short vowel according to the following rules:

  + The ending of the preposition [عَنْ]{.ar} [ean]{.trn} gets an [i]{.trn}-mark and becomes [عَنِ]{.ar} [eani]{.trn}. Examples:
    
    [عَنِ ٱلرَّجُلِ]{.ar}  
    [eani -rrajuli]{.trn}  
    "about the man"

    [عَنِ ٱمْرَأَةٍ]{.ar}  
    [eani -mraEatin]{.trn}  
    "about the woman"

  + The ending of the preposition [مِنْ]{.ar}  [min]{.trn} gets an [a]{.trn}-mark if followed by the [ٱَلْ]{.ar} [al]{.trn} of a definite noun. Otherwise it gets an [i]{.trn}-mark if followed by any other connecting [hamzah]{.trn}. Examples:

    [مِنَ ٱلرَّجُلِ]{.ar}  
    [mina -rrajuli]{.trn}  
    "from the man"

    [مِنِ ٱمْرَأَةٍ]{.ar}  
    [mini -mraEatin]{.trn}  
    "from a woman"

## Pseudo-prepositions

Pseudo-prepositions are actually nouns but they are used as prepositions. The above rules of writing and pronunciation apply to them as well.

Here is a list of some common pseudo-prepositions:

Preposition | Transcription | Meaning
:-------|:-------|:-------------
[عِنْدَ]{.ar} | [einda]{.trn} | at
[لَدَىٰ]{.ar} | [ladA]{.trn}  | at
[لَدُنْ]{.ar} | [ladun]{.trn} | at
[مَعَ]{.ar}  | [maea]{.trn}  | together with

Here are some examples using pseudo-prepositions:

...

The preposition [عِنْدَ]{.ar} [einda]{.trn} "at" can be used with a person to mean  "the place of the person". For example

[عِنْدَ ٱلرَّجُلِ]{.ar}  
[einda -rrajuli]{.trn}  

can be used to mean "at the man's [house, etc]."

bayna repeated

## Prepositions with pronouns

We have already learned detached pronouns like [هُوَ]{.ar}, [هِيَ]{.ar}, [أَنْتَ]{.ar}, [أَنْتِ]{.ar}, and [أَنَا]{.ar}. Here we will learn about _attached pronouns_. These are the singular attached pronouns:

Person | Attached pronoun
:------|:--
Absent person (masc.) "him" | [هُ]{.ar} [-hu]{.trn}
Absent person (fem.)  "her" | [هَا]{.ar} [-hA]{.trn}
Addressed person (masc.)  "you~masc.~" | [كَ]{.ar} [-ka]{.trn}
Addressed person (fem.)  "you~fem.~"   | [كِ]{.ar} [-ki]{.trn}
Speaking person (masc. and fem.)  "me" | [ي]{.ar} [-I]{.trn} and [يَ]{.ar} [-ya]{.trn}

Attached pronouns have many uses and we will see in later chapters, if [#allAh]{.trn2} wills, how they attach to nouns and particles. Here we will learn how they are attach to prepositions. 

Attached pronouns are used with prepositions when we want to replace the noun after a preposition with a pronoun. For example, if instead of saying "from the man" we would like to say "from him", or "from me", etc., we will attach the one of attached pronouns above to the end of the preposition.

Here are some notes regarding the use of attached pronouns: 

1. There are two attached pronouns for the singular person: the long vowel [-I]{.trn}, written as [ي]{.ar}, and [يَ]{.ar} [-ya]{.trn}. 
Generally speaking, they are interchangeable but in normal usage [ي]{.ar} [-I]{.trn} is much more commonly used than [يَ]{.ar} [-ya]{.trn}. 
However, there are certain cases where the long vowel [ي]{.ar} [-I]{.trn} is not permitted and [يَ]{.ar} [-ya]{.trn} is required. 
We will mention those cases below.
2. When using the speaking person attached pronouns [ي]{.ar} [-I]{.trn} and [يَ]{.ar} [-ya]{.trn}, if there is a consonant before either of them it is forced to have a short [i]{.trn}-vowel [◌ِ]{.ar}, if it already doesn't have one. For example:
   + [عِنْدَ]{.ar} [einda]{.trn} followed by [ي]{.ar} [-I]{.trn} becomes [عِنْدِي]{.ar} [eindI]{.trn}.
   + [مَعَ]{.ar} [maea]{.trn} followed by [يَ]{.ar} [-ya]{.trn} becomes [مَعِيَ]{.ar} [maeiya]{.trn}.
1. When the speaking person attached pronoun is attached to prepositions that end with [نْ]{.ar}, like [مِنْ]{.ar} [min]{.trn}, [عَنْ]{.ar} [ean]{.trn}, and [لَدُنْ]{.ar} [ladun]{.trn}, an additional intervening [نِ]{.ar} is added between the preposition and the attached pronoun. In writing, [ن]{.ar} is written only once and is doubled with a doubling mark [◌ّ]{.ar} on it. So we get:
   + [مِنِّي]{.ar} [minnI]{.trn}
   + [عَنِّي]{.ar} [eannI]{.trn}
   + [لَدُنِّي]{.ar} [ladunnI]{.trn}
2. The [ىٰ]{.ar} [A]{.trn} ending of prepositions is forced to become [◌َيْ]{.ar} [ay]{.trn} when attaching an attached pronoun. Examples:
   + [إِلَيْهَا]{.ar} [EilayhA]{.trn} "to her"
   + [عَلَيْكَ]{.ar} [ealayka]{.trn} "on you~masc.~"
3. When attaching the speaking person attached pronoun to any word that ends with a long vowel ([◌َا]{.ar} [-A]{.trn}, [◌َىٰ]{.ar} [-A]{.trn}, [◌ِي]{.ar} [-I]{.trn}, or [◌ُو]{.ar} [-U]{.trn}) or a semi-vowel ([◌َيْ]{.ar} [-ay]{.trn} or [◌َوْ]{.ar} [-aw]{.trn}), the long vowel [ي]{.ar} [-I]{.trn} is not permitted to be used as the speaking person pronoun. Instead, only [يَ]{.ar} [-ya]{.trn} may be used.

   The only long vowels or semi-vowels at the end of prepositions are [◌َىٰ]{.ar} [-A]{.trn} and [◌ِي]{.ar} [-I]{.trn}.
   And remember that the previous rule forces [ىٰ]{.ar} [A]{.trn} in prepositions to become [◌َيْ]{.ar} [ay]{.trn} when attaching a pronoun.

   So when adding the speaking person attached pronoun [يَ]{.ar} [-ya]{.trn} with these prepositions, only one [ي]{.ar} is written and it is doubled thus: [يَّ]{.ar}. Examples:
   + [فِيَّ]{.ar} [fiyya]{.trn} "in me"
   + [إِلَيَّ]{.ar} [Eilayya]{.trn} "to me"
   + [عَلَيَّ]{.ar} [ealayya]{.trn} "on me"
   + [لَدَيَّ]{.ar} [ladayya]{.trn} "at me".

   Note that the letter before the speaking person attached pronoun [يَ]{.ar} [-ya]{.trn} is now not a consonant so it is not forced to have a short [i]{.trn}-vowel [◌ِ]{.ar}.
5. The preposition [لِ]{.ar} [li]{.trn} "for" becomes [لَ]{.ar} [la]{.trn} when followed by an attached pronoun, for all pronouns except the speaking person pronouns [ي]{.ar} [-I]{.trn} and [يَ]{.ar} [ya]{.trn} "me", where it remains [لِ]{.ar} [li]{.trn}:
   + [لَهُ]{.ar} [lahu]{.trn} "for him"
   + [لَهَا]{.ar} [lahA]{.trn} "for her"
   + [لَكَ]{.ar} [laka]{.trn} "for you~masc.~"
   + [لَكِ]{.ar} [laki]{.trn} "for you~fem.~"
   + [لِي]{.ar} [lI]{.trn} and [لِيَ]{.ar} [liya]{.trn} "for me"
6. The pronoun [ـهُ]{.ar} [-hu]{.trn} "him" becomes[هِ]{.ar} [hi]{.trn} when it is preceded by the vowels [◌ِ]{.ar} [i]{.trn}, [ـِي]{.ar} [I]{.trn}, or the semi-vowel [ـَيْ]{.ar} [ay]{.trn}. So we get
   + [بِهِ]{.ar} [bihi]{.trn} "with him"
   + [فِيهِ]{.ar} [fIhi]{.trn} "in him"
   + [إِلَيْهِ]{.ar} [Eilayhi]{.trn} "to him"
7. The preposition [كَ]{.ar} [ka]{.trn} "like" is not used with attached pronouns. So, for example, [كَهُ]{.ar} [kahu]{.trn} is not allowed for "like him."

## Meaning of prepositions and translating them

For each preposition that we have listed above, we have also given its meaning. For example,

+ [فِي]{.ar}[fI]{.trn} "in"
+ [بِ]{.ar} [bi]{.trn} "with", "by", "next to"

These meanings are not always fixed. And there is some degree of overlap in meanings as well. For example, in order to say "in the city" we will usually say
[فِي ٱلْمَدِينَةِ]{.ar}[fi -lmadInati]{.trn} but sometimes we can also say
[بِٱلْمَدِينَةِ]{.ar} [bi -lmadInati]{.trn} with the same meaning. As you keep learning, practicing, and reading Arabic, you will learn how to choose which preposition to use, if Allah wills.

Similarly, sometimes we have two or more prepositions with almost the same meaning. For example,

+ [مِنْ]{.ar}  |[min]{.trn}  | from
+ [عَنْ]{.ar}  |[ean]{.trn}  | from, about

Knowing which one is used where will also take practice.

We will also see that English often uses one preposition to express a meaning, while Arabic will use another preposition to express the same meaning. For example, in English we say "angry _with_".  But Arabic usually uses the preposition [مِنْ]{.ar} [min]{.trn} "from" with [غَاضِبٌ]{.ar} [gADibun]{.trn} "angry" instead of using [بِ]{.ar} [bi]{.trn} "with". So in Arabic we would say [غَاضِبٌ مِنْ]{.ar} [gADibun min]{.trn} but we will still translate it as "angry with". This usage is idiomatic, and as you keep learning you will learn which prepositions to use in which circumstances.

## Sentences and phrases with prepositions

We have seen how a noun can be used after a preposition to get a prepositional phrase, for example:

[ إِلَى ٱلْمَدِينَةِ]{.ar}  
[Eila -lmadInati]{.trn}  
"to the city"

We can put an indefinite noun in front of this structure:

[طَريقٌ إِلَى ٱلْمَدِينَةِ]{.ar}  
[TarIqun Eila -lmadInati]{.trn}  
"a way to the city"  

Note that the preposition has no effect on the state of the noun before it. In this case, it is in the u-state. Only the noun after the preposition is put in the i-state.

We can also put a definite noun in front of the prepositional phrase. Now the resulting structure can, in general, have two meanings: (1) a complete sentence, and (2) an incomplete sentence. For example,

[ٱَلطَّريقُ إِلَى ٱلْمَدِينَةِ]{.ar}  
[EaTTarIqu Eila -lmadInati]{.trn}  
1. "The way is to the city."  
2. "The way to the city"

Usually, it will be clear from the context which of the two meanings is valid. For example, the second meaning, "The way to the city," can be part of a complete sentence:

[ٱَلطَّريقُ إِلَى ٱلْمَدِينَةِ طَوِيلٌ]{.ar}  
[EaTTarIqu Eila -lmadInati TawIlun]{.trn}  
"The way to the city is long."

### A sentence with an indefinite noun and a prepositional phrase

We have seen that if an indefinite noun is placed in front of a prepositional phrase, we get an incomplete sentence. For example,

[رَجُلٌ فِي ٱلْبَيْتِ]{.ar}  
[rajulun fi -lbayti]{.trn}  
"a man in the house"

Now we will see how to make the complete sentence: 

"A man **is** in the house."

We have already stated that sentences with indefinite subjects are not straightforward in Arabic. In order to express this sentence, we put the prepositional phrase first, and place the indefinite subject after it:

[فِي ٱلْبَيْتِ رَجُلٌ]{.ar}  
[fi -lbayti rajulun]{.trn}  
"In the house is a man." = "A man is in the house."

It may sometimes be more convenient to translate this type of sentence in English using "there is":

"There is a man in the house."

In Arabic, however, we will not use the equivalent of "there" and will express this, as we have just explained, by placing the prepositional phrase first, and the indefinite subject after it.

## To have something

English uses the word "have" or "has" to express that someone 
Arabic does not have a word for "have" or "has". In order to express sentences like

"I have a book."  
"The boy has a father."  

Arabic uses prepositions like 

+ [لِ]{.ar} [li]{.trn} "for"
+ [عِنْدَ]{.ar} [einda]{.trn} "at"
+ [لَدَىٰ]{.ar} [ladA]{.trn} "at"
+ [مَعَ]{.ar} [maea]{.trn} "together with"

Here are some examples:

[لِلْغُلَامِ أَبٌ]{.ar}  
[li -lgulAmi Eabun]{.trn}
"The boy has a father." (literally "For the boy is a father.")

[عِنْدَ ٱلرَّجُلِ كِتَابٌ]{.ar}  
[einda -rrajuli kitAbun]{.trn}  
"The man has a book." (literally "At the man is a book.")

[مَعَ ٱلْجَارِيَةِ لُعْبَةٌ]{.ar}  
[maea -ljAriyati luebatun]{.trn}  
"The girl has a toy." (literally "With the girl is a toy.")

Here are some notes that can help you choose which preposition to use to express "has" or "have":

+ [لِ]{.ar} [li]{.trn} "for" is used to express personal relationships, like "I have a friend", "I have a son", etc. It is also used when you wish to imply that you own the object. For example, the sentence

  [لِلرَّجُلِ كِتَابٌ]{.ar}  
  [li -rrajuli kitAbun]{.trn}  

  implies that the man owns a book. But it is possible that he has lent it to someone else so he does not actually have it on his person or at his house, etc.

+ [عِنْدَ]{.ar} [einda]{.trn} "at" is used to express that the person has the object in his possession, but not necessarily that he has it with him right now. For example the sentence

  [عِنْدَ ٱلرَّجُلِ كِتَابٌ]{.ar}  
  [einda -rrajuli kitAbun]{.trn}  

  implies that the man has a book in his possession. But it is possible that it may not be with him right now. It may be at his house or elsewhere.

+ [لَدَىٰ]{.ar} [ladA]{.trn} "at" is used to express that the person has the object in his possession and that he has it with him right now. For example the sentence

  [لَدَى ٱلرَّجُلِ كِتَابٌ]{.ar}  
  [lada -rrajuli kitAbun]{.trn}  

  implies that the man has a book in his possession and that he has it with him right now.

+ [مَعَ]{.ar} [maea]{.trn} "together with" is used to express that the person has the object with him right now. But it doesn't necessarily imply ownership. For example, the sentence 

  [مَعَ ٱلرَّجُلِ كِتَابٌ]{.ar}  
  [maea -rrajuli kitAbun]{.trn}  

  means that the man has a book with him right now. But it is possible that he does not own it and that someone else has lent it to him.

There is some degree of overlap in meaning and you will get a feeling of which preposition is more appropriate in which circumstance as you progress in your learning, if Allah wills. For now, if you find that the object can be used with all of these prepositions, you might go with [عِنْدَ]{.ar} [einda]{.trn} as it is more commonly used.

## Prepositional phrases with describers 

Consider the sentence

[ٱَلرَّجُلُ فِي ٱلْبَيْتِ]{.ar}  
[Earrujulu fi -lbayti]{.trn}  
"The man is in the house."

If we wish to describe the house as, for example, "the big house", we will simply place a suitable describer after the noun "house". The describer shall match the noun in state and definiteness. Since a preposition puts the noun after it in the i-state, the describer too will be in the i-state:

[ٱَلرَّجُلُ فِي ٱلْبَيْتِ ٱلْكَبِيرِ]{.ar}  
[Earrujulu fi -lbayti -lkabIri]{.trn}  
"The man is in the big house."

Consider also the sentence,

[قَرَأَ كِتَابًا مِنَ ٱلْمَكْتَبَةِ]{.ar}  
[qaraEa kitAban mina -lmaktabati]{.trn}  
"He read a book from the library."

The prepositional phrase [مِنَ ٱلْمَكْتَبَةِ]{.ar}  [mina -lmaktabati]{.trn}  "from the library" is describing the book. If we wish to place another describer for the book, like, "good book", we may place it after "book" and before the prepositional phrase:

[قَرَأَ كِتَابًا حَسَنًا مِنَ ٱلْمَكْتَبَةِ]{.ar}  
[qaraEa kitAban Hasanan mina -lmaktabati]{.trn}  
"He read a good book from the library."

However, sometimes you will see that the describer [حَسَنًا]{.ar} [Hasanan]{.trn} "good" is placed after the prepositional phrase:

[قَرَأَ كِتَابًا مِنَ ٱلْمَكْتَبَةِ حَسَنًا]{.ar}  
[qaraEa kitAban mina -lmaktabati Hasanan]{.trn}  
"He read a good book from the library."

This is only suitable in some circumstances. So we recommend that you place describer before the prepositional phrase for your own sentences, but not be surprised to see describers after prepositional phrases. Note also that [حَسَنًا]{.ar} [Hasanan]{.trn} "good" remains indefinite and in the a-state because it is matching [كِتَابًا]{.ar} [kiTaban]{.trn} "a book".

<!-- AZS: I think this is done only when the prepositional phrase is a na3t to the noun and muta3alliq  with "existing", not muta3alliq with, for example, the verb qara'tu -->

