# Pronouns

## Introduction

A pronoun is a word that is used in place of a noun. English has pronouns like "I", "me", "he", "him", "they", "them", etc. So, for example, you can have sentence with a noun:

"Zayd is in the house."

or you can use a pronoun:

"He is in the house."

Note that English has two sets of pronouns:

1. I, he, she, they.
2. Me, him, her, them.

A pronoun is used from these sets depending on the function of the noun it substitutes. For example, the speaker of a sentence can use either "I" or "me":

+ "I went to school."
+ "Zayd hit me."

Arabic also has two sets of pronouns:

1. Detached pronouns
2. Attached pronouns

We use detached and attached pronouns depending on the function of the noun it sustitues in the sentence.

In describing pronouns we will use the following terminology:

1. "The speaker": The is the person speaking. Pronouns used for the speaker are "I", "me", "we", and "us". Traditionally, this is also known as the "first-person".
2. "The addressee": This the person spoken to or being addressed. The pronoun used for the addressee is "you". Traditionally, this is also known as the "second-person".
3. "The absent": This person is not speaking nor being directly addressed. Pronouns used for the absent are "he", "she", "they", and "them". Traditionally, this is also known as the "third-person".

## Detached pronouns

As the name implies, detached pronouns are not attached to another word. The detached pronouns in Arabic are:

Pronouns for the absent:

1. [هُوَ]{.ar} [huwa]{.trn} "he".
2. [هِيَ]{.ar} [hiya]{.trn} "she".
6. [هُمَا]{.ar} [humA]{.trn} "they (dual masc. & fem.)".
8. [هُمْ]{.ar} [hum]{.trn} "they (pl. masc.)".
9. [هُنَّ]{.ar} [hunna]{.trn} "they (pl. fem.)".

Pronouns for the addressee:

1. [أَنْتَ]{.ar} [Eanta]{.trn} "you (sing. masc.)".
4. [أَنْتِ]{.ar} [Eanti]{.trn} "you (sing. fem.)".
7. [أَنْتُمَا]{.ar} [EantumA]{.trn} "you (dual masc. & fem.)".
10. [أَنْتُمْ]{.ar} [Eantum]{.trn} "you (pl. masc.)".
11. [أَنْتُنَّ]{.ar} [Eantunna]{.trn} "you (pl. fem.)".

Pronouns for the speaker:

1. [أَنَا]{.ar} [Eana]{.trn} "I". 
12. [نَحْنُ]{.ar} [naHnu]{.trn} "we (pl. masc. & fem.)"

Notes:

+ In [أَنَا]{.ar} [Eana]{.trn} "I", the [Ealif]{.trn} after the [ن]{.ar} is silent and [ن]{.ar} is pronounced with a short vowel. At the end of a sentence, the vowel maintained and it will continue to be pronounced [Eana]{.trn}, not [an]{.trn}.
+ Addressee pronouns for the dual don't distinguish between the masculine and the feminine. The same pronoun is used for both genders.
+ There is no dual pronoun for the speaker. The plural [نَحْنُ]{.ar} [naHnu]{.trn} is used instead.
+ There is no equivalent for the English neuter gender pronoun "it". This is because all nouns in Arabic, even inanimate beings, are either masculine or feminine.

Remember that Arabic verbs already have a doer pronoun so we don't need to add another. Here are some examples of sentences with detached pronouns:

## Attached pronouns

As the name implies, attached pronouns attach to a word. Attached pronouns are generally the equivalent of {him, her, them, me, us}. They are used in the following cases:

1. Substituting a noun which is the doee of a verb.
2. Substituting a noun which after a preposition.
3. Substituting the second noun of a noun-chain.

The attached pronouns in Arabic are:

Pronouns for the absent:

1. [ـهُ]{.ar} [-hu]{.trn} "him".
2. [ـهَا]{.ar} [-hA]{.trn} "her".
6. [ـهُمَا]{.ar} [-humA]{.trn} "them (dual masc. & fem.)".
8. [ـهُمْ]{.ar} [-hum]{.trn} "them (pl. masc.)".
9. [ـهُنَّ]{.ar} [-hunna]{.trn} "them (pl. fem.)".

Pronouns for the addressee:

1. [ـكَ]{.ar} [-ka]{.trn} "you (sing. masc.)".
2. [ـكِ]{.ar} [-ki]{.trn} "you (sing. fem.)".
3. [ـكُمَا]{.ar} [-kumA]{.trn} "you (dual masc. & fem.)".
4. [ـكُمْ]{.ar} [-kum]{.trn} "you (pl. masc.)".
5. [ـكُنَّ]{.ar} [-kunna]{.trn} "you (pl. fem.)".

Pronouns for the speaker:

1. [ـِي]{.ar} [-I]{.trn} "me". 
2. [نَا]{.ar} [-nA]{.trn} "us (pl. masc. & fem.)"

Here are some examples of sentences with detached pronouns:

