# The Arabic script

## The Arabic alphabet

The Arabic alphabet traditionally has 28 letters, shown in the table below.

No.|Arabic letter|Trans-cription|Name |Description
:--|:--|:--|:---|:---------------------------
 1|[ا]{.ar}|[A]{.trn}| [Ealif]{.trn} |A vowel like in English "man". But after these letters ([خ،ر،ص،ض،غ،ق]{.ar}) it sounds like "awe" in English "awesome".
 2|[ب]{.ar}|[b]{.trn}| [bAE]{.trn} |Like English "b" in "boy".
 3|[ت]{.ar}|[t]{.trn}| [tAE]{.trn} |Like English "t" in "tall" but softer. Touch the tongue against the back of the top front teeth instead of just the gum.
 4|[ث]{.ar}|[v]{.trn}| [vAE]{.trn} |Like English "th" in "think" but softer. Loosely bite the tip of your tongue between your front teeth and then force air out trying to hiss "ssss". Keep your tongue touching the top and bottom teeth and the hiss should come out like a "th" sound.
 5|[ج]{.ar}|[j]{.trn}| [jIm]{.trn} |Like English "j" in "just".
 6|[ح]{.ar}|[H]{.trn}| [HAE]{.trn} |Like English "h" in "hat" but pronounced from the bottom of the throat.
 7|[خ]{.ar}|[x]{.trn}| [xAE]{.trn} |Not found in English. Try saying "kh" but with a scraping sound.
 8|[د]{.ar}|[d]{.trn}| [dAl]{.trn} |Like English "th" in this.
 9|[ذ]{.ar}|[p]{.trn}| [pAl]{.trn} |Place your tongue as in [ث]{.ar} and force air out. But this time instead of trying to hiss "ssss" try to buzz "zzzz" but again keep your tongue touching the top and bottom teeth..
10|[ر]{.ar}|[r]{.trn}| [rAE]{.trn} |Like English "r" in "rat"
11|[ز]{.ar}|[z]{.trn}| [zAE]{.trn} |Like English "z" in "zoo"
12|[س]{.ar}|[s]{.trn}| [sIn]{.trn} |Like English "s" in "see"
13|[ش]{.ar}|[c]{.trn}| [cIn]{.trn} |Like English "sh" in "show"
14|[ص]{.ar}|[S]{.trn}| [SAd]{.trn} |An emphatic [س]{.ar} that will be described later
15|[ض]{.ar}|[D]{.trn}| [DAd]{.trn} |An emphatic [د]{.ar} that will be described later
16|[ط]{.ar}|[T]{.trn}| [TAE]{.trn} |An emphatic [ت]{.ar} that will be described later
17|[ظ]{.ar}|[P]{.trn}| [PAE]{.trn} |An emphatic [ذ]{.ar} that will be described later
18|[ع]{.ar}|[e]{.trn}| [eayn]{.trn} |A very peculiar sound formed in the throat
19|[غ]{.ar}|[g]{.trn}| [gayn]{.trn} |Like between English "g" and a soft "r".
20|[ف]{.ar}|[f]{.trn}| [fA ]{.trn}| Like English "f" in "fox".
21|[ق]{.ar}|[q]{.trn}| [qAf]{.trn}| Like "k" but sounded from the top back of the mouth.
22|[ك]{.ar}|[k]{.trn}| [kAf]{.trn}| Like English "k" in "kite".
23|[ل]{.ar}|[l]{.trn}| [lAm]{.trn}| Like English "l" in "light".
24|[م]{.ar}|[m]{.trn}| [mIm]{.trn}| Like English "m" in "man".
25|[ن]{.ar}|[n]{.trn}| [nUn]{.trn}| Like English "n" in "nut".
26|[ه]{.ar}|[h]{.trn}| [hAE]{.trn}| Like English "h" in "hat". Much softer than [ح]{.ar}
27|[و]{.ar}|[w]{.trn}/[U]{.trn}| [wAw ]{.trn} |Like English "w" in "water". Also used as the vowel "oo" in "moon".
28|[ي]{.ar}|[y]{.trn}/[I]{.trn}| [yAE]{.trn} |Like English "y" in "yellow". Also used as the vowel like "ee" in English "meek".

In addition to the traditional 28 letters, there is also one additional letter called [hamzao]{.trn}, that was originally only sounded and not written. Together with [hamzao]{.trn} there are 29 letters.

No.|Arabic letter|Trans-cription|Name |Description
:--|:--|:--|:---|:---------------------------
 29|[ء]{.ar}|[E]{.trn}| [hamzao]{.trn} | The sound of of the breath stopping between the words "oh-oh" and "a apple".

### Pronunciation notes

Some of the sounds are similar to sounds in English but others are very different. Here we will attempt to describe the sounds but we recommend that you learn the correct pronunciation from an experienced Arabic or [#qurEAn]{.trn2} teacher.

#### [ث]{.ar} [vAE]{.trn}, [ذ]{.ar} [pAl]{.trn}, and [ظ]{.ar} [PAE]{.trn}

Try to pronoun the "th" in "think" but bring your tongue out of your mouth between and barely touching the top and bottom front teeth. Have your lips and cheek in a wide grin. Now force air out and the sound will be somewhere between "th" and "s". This is [ث]{.ar} [vAE]{.trn}.

Now, with the tongue, teeth, and lips in the same position, try to pronounce "z". This is [ذ]{.ar} [pAl]{.trn}.

#### [ص]{.ar} [SAd]{.trn}, [ض]{.ar} [DAd]{.trn}, [ط]{.ar} [TAE]{.trn}, and [ظ]{.ar} [PAE]{.trn}

The letters [س]{.ar} [sIn]{.trn}, [د]{.ar} [dAl]{.trn}, [ت]{.ar} [tAE]{.trn}, and [ذ]{.ar} [pAl]{.trn} are pronounced with the mouth and lips in a wide grin. Now try pronouncing them, in turn, with the lips round forming a small circle. The sounds will be emphatic and will be [ص]{.ar} [SAd]{.trn}, [ض]{.ar} [DAd]{.trn}, [ط]{.ar} [TAE]{.trn}, and [ظ]{.ar} [PAE]{.trn} respectively.

## Writing Arabic words

### Letters in different positions

Arabic is written right-to-left, unlike English and most other languages which are written left-to-right. When writing, the letters in a word are generally joined to each other, except for six out of the 28 letters, which join only to the letter preceding them but not to the letter following them. These six partially-joining letters are [ا، د، ذ، ر، ز، و]{.ar}. 

When joining the letters, letters are modified in order to join to the preceding and following letter. The fully-joining letters can be in four positions:

1. by itself (isolated),
2. in the beginning of a group of joined letters,
3. in the middle of a group of joined letters,
4. in the end of a group of joined letters.

As we just mentioned, six of the letters ([ا، د، ذ، ر، ز، و]{.ar}) don't join to the following letter. So these letters can only occur only in the end of a group of joined letters, or isolated by themselves.

In this book we will show a "Simplified Arabic" writing style where, in each of the four positions, the letter maintains its basic shape and is usually only slightly modified to join to the previous and following letter with horizontal lines. 

To explain the method of modifying the letters when joining them, we will take [ب]{.ar} as an example and start with the isolated form:

Isolated form: [ب]{.ar}

To modify this into the end form, we simply join a horizontal line to the right of the letter:

End form: [ـب]{.ar}. 

To get the middle form, we take the end form [ـب]{.ar} and cut off its tail which is at its left, and replace it with a horizontal line. We also move the dot slightly to get:

Middle form: [ـبـ]{.ar}

And finally, to get the beginning form, we take the middle form [ـبـ]{.ar} and remove the horizontal line at the right:

Beginning form: [بـ]{.ar}

Now most of the letters follow this common technique but a few of them are modified a little further in each form. These, more complicated, letters are [ع، غ، ك، ه، ي]{.ar} and you can study them and the rest of the letters in the table below:

No|Isolated|End|Middle|Beginning
:--|:----|:----|:----|:----
 1|[ا]{.ar}|[ـا]{.ar}|none|none
 2|[ب]{.ar}|[ـب]{.ar}|[ـبـ]{.ar}|[بـ]{.ar}
 3|[ت]{.ar}|[ـت]{.ar}|[ـتـ]{.ar}|[تـ]{.ar}
 4|[ث]{.ar}|[ـث]{.ar}|[ـثـ]{.ar}|[ثـ]{.ar}
 5|[ج]{.ar}|[ـج]{.ar}|[ـجـ]{.ar}|[جـ]{.ar}
 6|[ح]{.ar}|[ـح]{.ar}|[ـحـ]{.ar}|[حـ]{.ar}
 7|[خ]{.ar}|[ـخ]{.ar}|[ـخـ]{.ar}|[خـ]{.ar}
 8|[د]{.ar}|[ـد]{.ar}|none|none
 9|[ذ]{.ar}|[ـذ]{.ar}|none|none
10|[ر]{.ar}|[ـر]{.ar}|none|none
11|[ز]{.ar}|[ـز]{.ar}|none|none
12|[س]{.ar}|[ـس]{.ar}|[ـسـ]{.ar}|[سـ]{.ar}
13|[ش]{.ar}|[ـش]{.ar}|[ـشـ]{.ar}|[شـ]{.ar}
14|[ص]{.ar}|[ـص]{.ar}|[ـصـ]{.ar}|[صـ]{.ar}
15|[ض]{.ar}|[ـض]{.ar}|[ـضـ]{.ar}|[ضـ]{.ar}
16|[ط]{.ar}|[ـط]{.ar}|[ـطـ]{.ar}|[طـ]{.ar}
17|[ظ]{.ar}|[ـظ]{.ar}|[ـظـ]{.ar}|[ظـ]{.ar}
18|[ع]{.ar}|[ـع]{.ar}|[ـعـ]{.ar}|[عـ]{.ar}
19|[غ]{.ar}|[ـغ]{.ar}|[ـغـ]{.ar}|[غـ]{.ar}
20|[ف]{.ar}|[ـف]{.ar}|[ـفـ]{.ar}|[فـ]{.ar}
21|[ق]{.ar}|[ـق]{.ar}|[ـقـ]{.ar}|[قـ]{.ar}
22|[ك]{.ar}|[ـك]{.ar}|[ـكـ]{.ar}|[كـ]{.ar}
23|[ل]{.ar}|[ـل]{.ar}|[ـلـ]{.ar}|[لـ]{.ar}
24|[م]{.ar}|[ـم]{.ar}|[ـمـ]{.ar}|[مـ]{.ar}
25|[ن]{.ar}|[ـن]{.ar}|[ـنـ]{.ar}|[نـ]{.ar}
26|[ه]{.ar}|[ـه]{.ar}|[ـهـ]{.ar}|[هـ]{.ar}
27|[و]{.ar}|[ـو]{.ar}|none|none
28|[ي]{.ar}|[ـي]{.ar}|[ـيـ]{.ar}|[يـ]{.ar}

You can see that each letter maintains a basic shape and is modified for each of the four positions. 

### Joining the different forms to make a word

Notice that when we modified the isolated form to get to the beginning, middle, and end forms, we added a horizontal line to each or both sides. It is this horizontal line which joines to the horizontal line of the neighboring letter.

As an example, we would like to join the following letters (starting from the right): [م-ع-ش-ر]{.ar} into one word. The first letter is [م]{.ar} so we modify it to its beginning form [مـ]{.ar}. The next two letters are converted to their middle forms [ـعـ، ـشـ]{.ar}. And the last letter [ر]{.ar} is converted to its end form [ـر]{.ar}. Then we join the horizontal lines together and get [مــعــشــر]{.ar}. Usually, when we join letters like this we shorten the horizontal lines so you will generally see the word like this [معشر]{.ar}.

In this example, we needed the beginning, middle, and end forms of the letters. Isolated forms are used in a word when there is a partially-joining letter present that won't join to the following letter. The letter after a partially-joining letter will be in its beginning form even though it is in the middle of a word. But if it is the last letter in the word then it will take its isolated form.

Let's take a look at some examples where a group of disjoint letters are joined to form a word:

Disjoint | Joined
:------------|:---------
[ذ-ل-ك]{.ar} | [ذلك]{.ar}
[ا-ح-م-د]{.ar} | [احمد]{.ar}
[ر-س-و-ل]{.ar} | [رسول]{.ar}
[و-ز-ي-ر]{.ar} | [وزير]{.ar}
[ر-ا-ز-ق]{.ar} | [رازق]{.ar}

Notice that in the last example, all the letters were in the isolated form.

#### Simplified and Traditional writing styles

We have just shown how letters join to each other with a horizontal line in the Simplified Arabic writing style. Traditional Arabic writing styles are a little more complex than Simplified Arabic: some letters join almost vertically instead of horizontally. But when you get familiar with the Simplified Arabic writing style, if Allah wills, it will not be too difficult for you to read the Traditional Arabic writing style as well.

Here are some comparisions of letters joining to each other in the Simplified Arabic and Traditional Arabic writing styles.

```{r, eval=knitr::is_html_output(), echo=FALSE}
  knitr::asis_output('
Disjoint | Joined (simplified) | Joined (traditional)
:------------|:---------|:---------
[ت-م-ر]{.ar} | [تمر]{.ar}| [تمر]{lang="ar" dir="rtl" style="font-family: Amiri;"}
[ا-ل-ح-ج-ج]{.ar} | [الحجج]{.ar} | [الحجج]{lang="ar" dir="rtl" style="font-family: Amiri;"}
[ا-ل-م-ا-س]{.ar} | [الماس]{.ar} | [الماس]{lang="ar" dir="rtl" style="font-family: Amiri;"}
[ل-م-ح-ة]{.ar} | [لمحة]{.ar} | [لمحة]{lang="ar" dir="rtl" style="font-family: Amiri;"}
[ب-ح-ر]{.ar} | [بحر]{.ar} | [بحر]{lang="ar" dir="rtl" style="font-family: Amiri;"}
[س-ح-ر]{.ar} | [سحر]{.ar} | [سحر]{lang="ar" dir="rtl" style="font-family: Amiri;"}
')
```

```{=latex}
\begin{longtable}[]{@{}lll@{}}
\toprule
Disjoint & Joined (simplified) & Joined (traditional)\tabularnewline
\midrule
\endhead
\RL{\textarabic{ت-م-ر}} & \RL{\textarabic{تمر}} &
\RL{\tradarab{تمر}}\tabularnewline
\RL{\textarabic{ا-ل-ح-ج-ج}} & \RL{\textarabic{الحجج}} &
\RL{\tradarab{الحجج}}\tabularnewline
\RL{\textarabic{ا-ل-م-ا-س}} & \RL{\textarabic{الماس}} &
\RL{\tradarab{الماس}}\tabularnewline
\RL{\textarabic{ل-م-ح-ة}} & \RL{\textarabic{لمحة}} &
\RL{\tradarab{لمحة}}\tabularnewline
\RL{\textarabic{ب-ح-ر}} & \RL{\textarabic{بحر}} &
\RL{\tradarab{بحر}}\tabularnewline
\RL{\textarabic{س-ح-ر}} & \RL{\textarabic{سحر}} &
\RL{\tradarab{سحر}}\tabularnewline
\bottomrule
\end{longtable}
```

### Looped [tAE]{.trn}

Looped [tAE]{.trn} [ة]{.ar} is a special letter which is merged from two letters of the alphabet. It is a [tAE]{.trn} [ت]{.ar} but it is written a [ه]{.ar} [hAE]{.trn} with two dots above it. We will transcribe it as [o]{.trn}. Looped [tAE]{.trn} [ة]{.ar} is pronounced exactly as a [ت]{.ar} [tAE]{.trn} except if it is at the end of a sentence in which case it is pronounced as a [ه]{.ar} [hAE]{.trn} as we'll explain later, if Allah wills. Looped [tAE]{.trn} occurs only at the end of a word so it has only an end form and an isolated form (used when the letter before it is a partially-joining letter). 

Examples:

+ [فاطمة]{.ar}
+ [شجرة]{.ar}
+ [فتاة]{.ar}

### Writing [hamzao]{.trn}

We have mentioned that [hamzao]{.trn} was a later addition to the Arabic alphabet and originally it was only sounded and not written. [#hamzao]{.trn} can be written in a number of different ways:

1. Above or below a vowel letter. [#hamzao]{.trn} can be written above the vowel letters thus: [أ ؤ ئ]{.ar}. Sometimes, it may also be written under an [Ealif]{.trn} thus: [إ]{.ar}. Examples: [أفعال]{.ar}, [سؤلك]{.ar}, [فئة]{.ar}, [إن]{.ar}.
2. After a letter. This has two sub cases:
   a. Standalone after a partially-joining letter or at the end of a word. Examples: [تساءل]{.ar}, [توءم]{.ar}, [عبء]{.ar}.
   a. Inline in the middle of a word after a fully-joining letter. In this case [hamzao]{.trn} is written above the horizontal line that connects the letters. Examples: [خطيـٔة]{.ar}, [شيـٔا]{.ar}, [بريـٔين]{.ar}.

In all cases it is pronounced the same. There are actually a set of fairly complicated rules that determine which of the above ways to choose when writing [hamzao]{.trn}. We present these rules in Appendix \@ref(hamzarules). We recommend that for now, you memorize the spelling of each word that we present that contains a [hamzao]{.trn}. When you are sufficiently advanced, and curious enough, you may refer to Appendix \@ref(hamzarules) to learn the full set of rules.

## Letters that look similar

Some letters are very similar to each other and only differ in their dots or other slight differences. You should take care to distinguish between these letters. We will describe their similarities and differences here.

The letters [ب]{.ar}, [ت]{.ar}, and [ث]{.ar} differ only in their dots and are otherwise identical in all positions. [ن]{.ar} and [ي]{.ar} are similar in initial and middle positions to [ب]{.ar}, [ت]{.ar}, and [ث]{.ar} but differ from them and from each other in isolated and final positions. Compare all five in the table below:

Isolated | End | Middle | Beginnning
:--------|:----|:-------|:----------
[ب]{.ar}| [ـب]{.ar}| [ـبـ]{.ar}| [بـ]{.ar}
[ت]{.ar}| [ـت]{.ar}| [ـتـ]{.ar}| [تـ]{.ar}
[ث]{.ar}| [ـث]{.ar}| [ـثـ]{.ar}| [ثـ]{.ar}
[ن]{.ar}| [ـن]{.ar}| [ـنـ]{.ar}| [نـ]{.ar}
[ي]{.ar}| [ـي]{.ar}| [ـيـ]{.ar}| [يـ]{.ar}

These groups of letters  differ too, only in their dots:

+ [ج]{.ar}, [ح]{.ar}, and [خ]{.ar}
+ [د]{.ar} and [ذ]{.ar}
+ [ر]{.ar} and [ز]{.ar}
+ [س]{.ar} and [ش]{.ar}
+ [ص]{.ar} and [ض]{.ar}
+ [ط]{.ar} and [ظ]{.ar}
+ [ع]{.ar} and [غ]{.ar}

The letters [ف]{.ar} and [ق]{.ar} are similar in the initial and middle positions except for the dots. But in the isolated and final positions, the tail of [ق]{.ar} goes lower than that of [ف]{.ar}.

Isolated | End | Middle | Beginnning
:--------|:----|:-------|:----------
[ف]{.ar}| [ـف]{.ar}| [ـفـ]{.ar}| [فـ]{.ar}
[ق]{.ar}| [ـق]{.ar}| [ـقـ]{.ar}| [قـ]{.ar}

Be careful also not to confuse [غ]{.ar} and [ف]{.ar} in their middle forms. The loop for [ف]{.ar} is round where it is triangular and flat-topped for [غ]{.ar} (as it is for [ع]{.ar}). Compare their middle forms in the table below:

Isolated | Middle
:--------|:------
[غ]{.ar}| [ـغـ]{.ar}
[ف]{.ar}| [ـفـ]{.ar}

The letters [Ealif]{.trn} [ا]{.ar} and [lAm]{.trn} [ل]{.ar} can be confused for each other. Their forms are shown here again for easy comparison:

Isolated | End | Middle | Beginnning
:--------|:----|:-------|:----------
[ا]{.ar}| [ـا]{.ar}| none | none
[ل]{.ar}| [ـل]{.ar}| [ـلـ]{.ar}| [لـ]{.ar}

## Vowels and pronunciation marks.

### Short Vowels

Arabic has six vowels. There are three short vowels which don't have letters in the alphabet. Instead they are shown with pronunciation marks:

1.  [a]{.trn} like in English “mud”, written with an [a]{.trn}-mark [◌َ]{.ar} which is a small diagonal line above the letter like [مَـ]{.ar} [ma]{.trn}.
1.  [i]{.trn} like in English “bit”, written with an [i]{.trn}-mark [◌ِ]{.ar} which is a small diagonal line under the letter like [بِـ]{.ar} [bi]{.trn}.
1.  [u]{.trn} like in English “put”, written with an [u]{.trn}-mark [◌ُ]{.ar} which is a tiny waw above the letter like [فُـ]{.ar} [fu]{.trn}.

Examples of words with short vowels:

+ [فَتَحَ]{.ar} [fataHa]{.trn}
+ [عَمِلَ]{.ar} [eamila]{.trn}
+ [قُتِلَ]{.ar} [qutila]{.trn}

### Long Vowels

There are also three long vowels which are part of the alphabet:

1.  [A]{.trn} generally written with an unmarked [ا]{.ar} [Ealif]{.trn} and with the preceding letter having an [a]{.trn}-mark. Example [مَا]{.ar} [mA]{.trn}. This vowel is mostly pronounced like the vowel in English “man”. If however, it comes after these letters [خ،ر،ص،ض،ط،ظ،غ،ق]{.ar} it is pronounced like English "awe".
1.  [I]{.trn} like in English “been” written with an unmarked [ي]{.ar} [yAE]{.trn} with the preceding letter having an [i]{.trn}-mark. Example [فِي]{.ar} [fI]{.trn}.
1.  [U]{.trn} like in English “moon” written with an unmarked [و]{.ar} [wAw]{.trn} with the preceding letter having an [u]{.trn}-mark. Example [ذُو]{.ar} [pU]{.trn}.

Examples of words with long and short vowels:

+ [هَارُونُ]{.ar} [hArUnu]{.trn}
+ [كَذَا]{.ar} [kapA]{.trn}
+ [سَرَادِيبَ]{.ar} [sarAdIba]{.trn}

#### [A]{.trn} vowel written with a small [Ealif]{.trn}

Sometimes the [A]{.trn} vowel is written as a small [Ealif]{.trn} [◌ٰ]{.ar}, called a "dagger [Ealif]{.trn}", instead of a regular [Ealif]{.trn} [ا]{.ar}. This is done only for a few commonly used words. Here are some examples:

+ [هَـٰذَا]{.ar} [hApA]{.trn}
+ [ذَ ٰلِكَ]{.ar} [pAlika]{.trn}

#### [A]{.trn} vowel written with a [yAE]{.trn}

In some other words, the [A]{.trn} vowel is written with a [yAE]{.trn} instead of an [Ealif]{.trn} [ا]{.ar}. When this happens, we will write the [yAE]{.trn} without its dots and write a dagger [Ealif]{.trn} [◌ٰ]{.ar} above it, like this [ىٰ]{.ar}. Here are some examples:

+ [عَلَىٰ]{.ar} [ealA]{.trn}
+ [رَمَىٰ]{.ar} [ramA]{.trn}

### Rest-mark

As we have seen above if an Arabic letter has a vowel after it it will take one of the three pronunciation marks: [◌َ]{.ar}, [◌ِ]{.ar}, [◌ُ]{.ar}. If, however, there is no vowel after the letter we will put a "rest-mark" on it [◌ْ]{.ar}. This mark can only occur if there is a short vowel before the letter. Examples:

+ [كَمْ]{.ar} [kam]{.trn}
+ [مُنْذُ]{.ar} [munpu]{.trn}
+ [مِنْهُمْ]{.ar} [minhum]{.trn}
+ [مِنْهَا]{.ar} [minhA]{.trn}

### Semi-vowels

Arabic has two short semi-vowels:

1. [aw]{.trn} like in English “goal”. This is written with a [wAw]{.trn} with a rest-mark on it and a [A]{.trn} vowel before it. Example [لَوْ]{.ar} [law]{.trn}. 
2. [ay]{.trn} like in English “bait”. This is written with a [yAE]{.trn} with a rest-mark on it and a [A]{.trn} vowel before it. Example [كَيْ]{.ar} [kay]{.trn}. 
Examples with short semi-vowels:

+ [وَيْحَكَ]{.ar} [wayHaka]{.trn}
+ [غَيْرُهُ]{.ar} [gayruhu]{.trn}
+ [قَوْلُهُ]{.ar} [qawluhu]{.trn}

It also has two long semi-vowels:

1. [Aw]{.trn} like in English “cow”. This is written with a [wAw]{.trn} with a rest-mark on it and a [A]{.trn} vowel before it. Example [وَاوْ]{.ar} [wAw]{.trn}. 
2. [Ay]{.trn} like in English “bye”. This is written with a [yAE]{.trn} with a rest-mark on it and a [A]{.trn} vowel before it. Example [شَايْ]{.ar} [cAy]{.trn}.

These long semi-vowels are rare and may only occur at the end of a sentence.

### Doubled letters

A word may contain "doubled" letters. This is when the same letter occurs, one after the other; the first letter has a rest-mark, and the second letter has a vowel. For example, in the word [قَتْتَلَ]{.ar} [qattala]{.trn}, the letter [ت]{.ar} is doubled. When this occurs, we actually only write the letter once and put a "doubling mark" [◌ّ]{.ar} on it, like so: [قَتَّلَ]{.ar} [qattala]{.trn}. When pronouncing this word, stop at and stress the doubled letter [qattala]{.trn} and make sure it does not sound like the undoubled letter in [قَتَلَ]{.ar} [qatala]{.trn}. Examples with doubled letters:

+ [كَبَّرَ]{.ar} [kabbara]{.trn}
+ [حَدُّهُ]{.ar} [Hadduhu]{.trn}
+ [فَعَّالَ]{.ar} [faeeAla]{.trn}
+ [سِكِّينُ]{.ar} [sikkInu]{.trn}. Note that the [i]{.trn}-mark is below the doubling mark but above the letter [ك]{.ar}. This is the most common way to write this, although having the [i]{.trn}-mark below the letter is also sometimes done as well. (In this case, the doubling mark will still be above the letter.)
+ [سَفُّودُ]{.ar} [saffUdu]{.trn}
+ [ضَالِّينَ]{.ar} [DAllIna]{.trn}
+ [مُزَّمِّلُ]{.ar} [muzzammilu]{.trn}

## Connecting [hamzao]{.trn}

Some words in arabic begin with a sukoon. When this occurs a connecting [hamzao]{.trn} (written as a tiny صـ on an alif) is put before it. If this word comes in the beginning of the sentence the connecting alif is pronounced as a [hamzao]{.trn}. Example. Otherwise this connecting [hamzao]{.trn} is not pronounced and the word is connected to the final vowel of the previous word in pronunciation. Example. If the previous word does not end with a vowel, then a helper vowel is added. For n-marks, teh helper vowel is i. Example:

In this tutorial we will transcribe the connecting [hamzao]{.trn} with a hyphen - when it is in the middle of a sentence.

Examples
‘alwaladu sa3eedun [ٱَلْوَلَدُ سَعِيدٌ]{.ar}
Daraba -lwaladu ‘aHmada NOT Daraba ‘alwaladu aHmada

When one word ends in a long vowel and the next word begins with a connecting [hamzao]{.trn}, the long vowel becomes a short vowel in pronunciation (but in writing the long vowel’s letter is retained.) For example

‘Ilaa masjidin BUT Dhahaba ‘ila -lmasjidi NOT dhahaba ‘ilaa -lmasjidi NOR ‘ilaa ‘almasjidi
‘Illaa zaydan BUT ‘Illa -lmuSalleena NOT `illaa -lmuSalleena NOR ‘illaa ‘almuSalleena.
Fee baytin BUT Fi -lbayt NOT fee -lbayt NOR fee ‘albayt
Dhoo sa3atin BUT Dhu -lqarnayni NOT dhoo -lqarnayni NOR dhoo ‘alqarnayni 

Sometimes a connecting [hamzao]{.trn} can occurs after an n-mark. In these cases will will pronounce the n-mark and follow it with a short-i:

Zaydani -lkabeeru NOT zaydan ‘alkabeera

## Joining [lAm]{.trn} and [Ealif]{.trn}

When the letter [Ealif]{.trn} follows [lAm]{.trn} we would expect them to be joined like this [ل+ا]{.ar} &rarr; [لـا]{.ar}. But actually, they are joined in a special way 

[ل+ا]{.ar} &rarr; [لا]{.ar}

If we add [hamzao]{.trn} to the [Ealif]{.trn} or add another [lAm]{.trn}, here is how they will be written and pronounced in words:

Disjoint | Joined | Transcription
:--------|:-------|:-------------
[لَ + ا]{.ar}| [لَا]{.ar}| [lA]{.trn}
[ٱَ + لْ + إِ + يمَانُ]{.ar}| [ٱَلْإِيمَانُ]{.ar}| [alEImAnu]{.trn}
[ٱَ + لْ + آ + فَةُ]{.ar}| [ٱَلْآفَةُ]{.ar}| [alEAfatu]{.trn}
[أَ + لَّ + ا]{.ar}| [أَلَّا]{.ar}| [EallA]{.trn}
[لِ + لِ + ٱ + نْتِقَالِ]{.ar}| [لِلِٱنْتِقَالِ]{.ar}| [li li-ntiqAli]{.trn}

## [n]{.trn}-marks

We will now show three new pronunciation marks, collectively called [n]{.trn}-marks.

1. [an]{.trn}-mark [ ً]{.ar}
1. [in]{.trn}-mark [ ٍ]{.ar}
1. [un]{.trn}-mark [ ٌ]{.ar}

These [n]{.trn}-marks may only occur on a letter at the end of a word. They are pronounced as a short vowel ([a]{.trn}, [i]{.trn}, or [u]{.trn}) followed by an [n]{.trn}. For example, [سَالِمٌ]{.ar} [sAlimun]{.trn}, [سَالِمٍ]{.ar} [sAlimin]{.trn}.

As a spelling rule, if a word ends with an [an]{.trn} mark, we will generally add a silent [Ealif]{.trn} after it, for example [سَالِم]{.ar} becomes [سَالِمًا]{.ar} [sAliman]{.trn}. This is done for all words except:

1. If the word ends with a looped [tAE]{.trn} [ة]{.ar}. In this case we don't add the silent [Ealif]{.trn}. For example, [غَاضِبَة]{.ar} becomes [غَاضِبَةً]{.ar} [gADibatan]{.trn}, not [غَاضِبَةًا]{.ar} or [غَاضِبَتًا]{.ar}.

2. If the word ends with a [yAE]{.trn} that represents a long-[A]{.trn} vowel. In this case, the [an]{.trn} mark is put on the letter before the [yAE]{.trn} and the final [yAE]{.trn} becomes silent and is not pronounced. For example, [مُصْطَفَىٰ]{.ar} becomes [مُصْطَفًى]{.ar} [muSTafan]{.trn}.

2. If the word ends with a [hamzao]{.trn}. In this case, we might or might not write a silent [Ealif]{.trn}, depending on the following rules:

   a. If there is an [Ealif]{.trn} before a unseated [hamzao]{.trn} [اء]{.ar}, then we don't add a silent [Ealif]{.trn}. For example [دَاء]{.ar} becomes [دَاءً]{.ar} [dAEan]{.trn}, not [دَاءًا]{.ar}.

   b. Otherwise, we add the silent [Ealif]{.trn} after the [hamzao]{.trn} so that the [hamzao]{.trn} is now in the middle of the word with a suffix [Ealif]{.trn} after it. We now pretend that the [hamzao]{.trn} has an [a]{.trn}-mark and that the [Ealif]{.trn} after it is a long-[A]{.trn} vowel. Then we go through the rules for writing [hamzao]{.trn} in the middle of a word (given above) to determine how [hamzao]{.trn} will be written. We then write the [an]{.trn}-mark on the [hamzao]{.trn}. For example [مُبْتَدَأ]{.ar} becomes [مُبْتَدَءًا]{.ar} [mubtadaEan]{.trn}, [مُبْتَدِئ]{.ar} becomes [مُبْتَدِئًا]{.ar} [mubtadiEan]{.trn}, [بُطْء]{.ar} becomes [بُطْـًٔا]{.ar} [buTEan]{.trn}.

Here are some examples of words with [n]{.trn}-marks:

+ [سَعْدٌ]{.ar}  [saedun]{.trn}
+ [ضَرْبًا]{.ar} [Darban]{.trn}
+ [قَاضٍ]{.ar}  [qADin]{.trn}
+ [سَعَةً]{.ar}  [saeatan]{.trn}
+ [دُعَاءً]{.ar} [dueAEan]{.trn}
+ [ٱِمْرَءًا]{.ar} [imraEan]{.trn}
+ [شَيْـًٔا]{.ar} [cayEan]{.trn}
+ [سُوءًا]{.ar} [sUEan]{.trn}
+ [غَبَنٌ]{.ar} [gabanun]{.trn}

## Pronouncing the end of a sentence

When a word is at the end of a sentence and it does not end with a long vowel, then the final letter's pronunciation mark is pronounced as a null-vowel mark when vocalizing the sentence. If the final letter is a looped [tAE]{.trn} [ة]{.ar} then it is pronounced as a [ه]{.ar} [hAE]{.trn} with a null-vowel mark. 

This change in pronunciation is only vocal, it does not affect how we write the pronunciation mark. Here we give some examples of words pronounced if they were at the end of a sentence:

+ euqbah
+ wAlidAy
+ wAlidayy
+ EabI

If however, the final letter's pronunciation mark is a [an]{.trn} mark then it is pronounced as a long-[A]{.trn} vowel. The only exception is if the final letter were looped [tAE]{.trn} [ةً]{.ar}, in which case it is then pronounced as a [hAE]{.trn} with a null-vowel mark [هْ]{.ar}. Here are examples of words with [an]{.trn} marks pronounced as if they were at the end of a sentence.

Note that the above exception is only for looped [tAE]{.trn}. If a [hamzao]{.trn} with an [an]{.trn} mark occurs at the end of a word, then it too will be pronounced as if it had a long-[A]{.trn} vowel after it. Such is the case, whether or not a silent [Ealif]{.trn} is written after the [hamzao]{.trn}. Examples:

+ [مُبْتَدَءًا]{.ar} is pronounced [mubtadaEA]{.trn}
+ [دُعَاءً]{.ar} is pronounced [dueAEA]{.trn}

Similarly, if the word has a final [yAE]{.trn} that represents the long-[A]{.trn} vowel, and the letter before has an [an]{.trn} mark, it is pronounced with the long-[A]{.trn} vowel at the end of the sentence. For example:

+ [مُصْطَفًى]{.ar} is pronounced [muSTafA]{.trn}

Except in this section, we will usually transcribe Arabic into English letters without modifiying the transcription for the last word in the sentence. This is because the last vowel mark is helpful for us to learn the grammatical function of the word. But when saying the sentence out aloud you should pronounce the ending of the final word as we have just described.

For example, the sentence:  
[ذَهَبَ إِلَى ٱلْبَيْتِ]{.ar}

will be transcribed as:  
[pahaba Eila -lbayti]{.trn}

but should be pronounced as  
[pahaba Eila -lbayt]{.trn}

## Quranic script

In printed Qurans, which are called [muSHaf]{.trn}s, some words will be written a little differently than how they are written in non-Quranic Arabic. The reasons for this are beyond the scope of this tutorial. But here we’ll just give a few examples and note that these differences are only found in [muSHaf]{.trn}s. For standard written Arabic, the writing explained in this chapter is used instead.

mAlik
samAwAt
al-SalAh

