# Sound plurals

## Introduction

Arabic uses the plural for nouns in number three and higher. The formation and use of plurals in Arabic can be somewhat complicated. Furthermore, there is sometimes more than one way to use plurals. In this chapter we will explain the most common usage to keep things as simple as possible.

English regularly forms the plural by adding the plural ending "s" to the end of a singular noun. For example:

| Singular | Plural |
|:-----------|:-----------|
| book       | books      |
| house      | houses     |
| boy        | boys       |
| girl       | girls      |

Arabic also forms some plurals by adding plural endings to to the singular noun. This kind of plural is call a _sound_ plural because the singular noun is kept more or less sound (intact) when adding the plural ending.

Arabic has two sound plurals:

1. The [Un]{.trn} plural.
2. The [At]{.trn} plural.

We will describe each of them in detail.

## The [Un]{.trn} plural

The [Un]{.trn} plural is formed by adding the ending [ـُونَ]{.ar} [Una]{.trn} to the singular noun when it is in the u-state, and [ـِينَ]{.ar} [Ina]{.trn} when the noun is in the a-state or i-state. For convenience, we will call it the "[Un]{.trn} plural" instead of the "[Una]{.trn}/[Ina]{.trn} plural".

| State | a (male) teacher | (male) teachers |
|:-----------|:-------------|:-------------|
| u-state |[مُعَلِّمٌ]{.ar} [mueallimun]{.trn} | [مُعَلِّمُونَ]{.ar} [mueallimUna]{.trn}| 
| a-state |[مُعَلِّمًا]{.ar} [muealliman]{.trn}| [مُعَلِّمِينَ]{.ar} [mueallimIna]{.trn} | 
| i-state |[مُعَلِّمٍ]{.ar} [mueallimin]{.trn} | [مُعَلِّمِينَ]{.ar} [mueallimIna]{.trn} |

Note that there are no [n]{.trn} marks for the [Un]{.trn} plural. Definite plural nouns are also formed in the same way:

| State | the (male) teacher | the (male) teachers |
|:-----------|:-------------|:-------------|
| u-state | [ٱَلْمُعَلِّمُ]{.ar} [Ealmueallimu]{.trn}| [ٱَلْمُعَلِّمُونَ]{.ar} [EalmueallimUna]{.trn}
| a-state | [ٱَلْمُعَلِّمَ]{.ar} [Ealmueallima]{.trn}| [ٱَلْمُعَلِّمِينَ]{.ar} [EalmueallimIna]{.trn}  
| i-state |[ٱَلْمُعَلِّمِ]{.ar} [Ealmueallimi]{.trn} | [ٱَلْمُعَلِّمِينَ]{.ar} [EalmueallimIna]{.trn}

### Applicability of the [Un]{.trn} plural

Except for very few exceptions, the [Un]{.trn} plural is used only for male rational beings (humans, jinn, etc.). Of these exceptions, the word [سَنَةٌ]{.ar} [sanatun]{.trn} "a year" is the most common. It is pluralized as [سِنُونَ]{.ar} [sinUna]{.trn} in the u-state and [سِنِينَ]{.ar} [sinIna]{.trn} in the a-state and i-state.

## The [At]{.trn} plural

The [At]{.trn} plural is formed by adding the ending [ـَاتٌ]{.ar} [Atun]{.trn} to the indefinite singular noun when it is in the u-state, and [ـَاتٍ]{.ar} [Atin]{.trn} when the noun is in the a-state or i-state.

| State | an animal | animals
|:-----------|:-------------|:-------------|
| u-state | [حَيَوَانٌ]{.ar} [HayawAnun]{.trn}  | [حَيَوَانَاتٌ]{.ar} [HayawAnAtun]{.trn}
| a-state | [حَيَوَانًا]{.ar} [HayawAnan]{.trn} | [حَيَوَانَاتٍ]{.ar} [HayawAnAtin]{.trn} 
| i-state |[حَيَوَانٍ]{.ar} [HayawAnin]{.trn}   | [حَيَوَانَاتٍ]{.ar} [HayawAnAtin]{.trn} 

Note that there _are_ [n]{.trn} marks for the [At]{.trn} plural. Definite plural nouns are also formed in the same way but they won't have [n]{.trn} marks:

| State | the animal | the animals
|:-----------|:-------------|:-------------|
| u-state | [ٱَلْحَيَوَانُ]{.ar} [EalHayawAnu]{.trn}| [ٱَلْحَيَوَانَاتُ]{.ar} [EalHayawAnAtu]{.trn}
| a-state | [ٱَلْحَيَوَانَ]{.ar} [EalHayawAna]{.trn}| [ٱَلْحَيَوَانَاتِ]{.ar} [EalHayawAnAti]{.trn}  
| i-state |[ٱَلْحَيَوَانِ]{.ar} [EalHayawAni]{.trn} | [ٱَلْحَيَوَانَاتِ]{.ar} [EalHayawAnAti]{.trn}

If a noun ends with a looped [tAE]{.trn} [ة]{.ar}, then it is removed before appending the [At]{.trn} plural ending:

| State | a (female) teacher | (female) teachers |
|:-----------|:-------------|:-------------|
| u-state | [مُعَلِّمَةٌ]{.ar} [mueallimatun]{.trn}| [مُعَلِّمَاتٌ]{.ar} [mueallimAtun]{.trn}
| a-state | [مُعَلِّمَةً]{.ar} [mueallimatan]{.trn}| [مُعَلِّمَاتٍ]{.ar} [mueallimAtin]{.trn}  
| i-state |[مُعَلِّمَةٍ]{.ar} [mueallimatin]{.trn} | [مُعَلِّمَاتٍ]{.ar} [mueallimAtin]{.trn} 

### The [At]{.trn} plural for words ending with [اء]{.ar}

If a noun ends with an [اء]{.ar} then the [hamzah]{.trn} may either be retained or get converted to a [و]{.ar} when forming the [At]{.trn} plural. This is done based on the same rules as for the dual which we explained in the previous chapter.

Thus,

+ REMOVE because plurals of descriptive nouns not yet discussed: [صَفْرَاءُ]{.ar} [SafrAE]{.trn} (root: [صفر]{.arroot}) becomes [صَفْرَاوَاتٌ]{.ar} [SafrAwAtun]{.trn}.
+ [صَحْرَاءُ]{.ar} [SaHrAE]{.trn} (root: [صحر]{.arroot}) becomes [صَحْرَاوَاتٌ]{.ar} [SaHrAwAtun]{.trn}.
+ [إِبْطًاءٌ]{.ar} [EibTAEun]{.trn} (root: [بطء]{.arroot}) becomes [إِبْطَاءَاتٌ]{.ar} [EibTAEAtun]{.trn}.
+ [سَمَاءٌ]{.ar} [samAEun]{.trn} (root: [سمو]{.arroot}) becomes [سَمَاءَاتٌ]{.ar} [samAEAtun]{.trn} or [سَمَاوَاتٌ]{.ar} [samAwAtun]{.trn}.

### The [At]{.trn} plural for words ending with [يٰ]{.ar}

If a noun ends with [ىٰ]{.ar}, then whether the [ىٰ]{.ar} is a feminine marker or not, it becomes a [yAE]{.trn} with an [a]{.trn}-mark [يَ]{.ar} when forming the [At]{.trn} plural. For example,  

+ [حُبَارَىٰ]{.ar} [HubArA]{.trn} becomes [حُبَارَيَاتٌ]{.ar} [HubArayAtun]{.trn}.

### Designative nouns of the pattern [فَُِعْل]{.ar} and [فَُِعْلَة]{.ar}

If a designative noun is of the pattern [فَعْل]{.ar} [fael]{.trn} or [فَعْلَة]{.ar} [faelah]{.trn}, and the middle letter is not [و]{.ar} or [ي]{.ar}, then the null-vowel mark on the middle letter will be converted to an [a]{.trn}-mark when forming the [At]{.trn} plural. Therefore, 

+ [نَحْلَة]{.ar} [naHlah]{.trn} becomes [نَحَلَات]{.ar} [naHalAt]{.trn}, not [نَحْلَات]{.ar} [naHlAt]{.trn}.

If a designative noun is of the pattern [فِعْل]{.ar} [fiel]{.trn}, [فِعْلَة]{.ar} [fielah]{.trn}, [فُعْل]{.ar} [fuel]{.trn}, or [فُعْلَة]{.ar} [fuelah]{.trn}, and the middle letter is not [و]{.ar} or [ي]{.ar}, then the null-vowel mark on the middle letter can either:

  i.   be retained,
  ii.  be converted to an [a]{.trn} mark, or
  iii. be converted to the vowel mark on the first letter.

Thus,

+ [ظُلْمَة]{.ar} can become either [ظُلْمَات]{.ar} [PulmAt]{.trn} or [ظُلَمَات]{.ar} [PulamAt]{.trn}, or [ظُلُمَات]{.ar} [PulumAt]{.trn}.
+ [كِسْرَة]{.ar} can become either [كِسْرَات]{.ar} [kisrAt]{.trn} or [كِسَرَات]{.ar} [kisarAt]{.trn}, or [كِسِرَات]{.ar} [kisirAt]{.trn}.

Note that this rule of changing the vowel mark is only true for designative nouns. Descriptive nouns will retain the null-vowel mark when forming the [At]{.trn} plural. So [صَعْب]{.ar} [Saeb]{.trn} and [صَعْبَة]{.ar} [Saebah]{.trn} become only [صَعْبَات]{.ar} [SaebAt]{.trn}, not [صَعَبَات]{.ar} [SaeabAt]{.trn}.

### Applicability of the [At]{.trn} plural

We had mentioned that the [Un]{.trn} plural is used, with very few exceptions, only for male rational beings. Conversely, the [At]{.trn} is used for female rational beings as well as for other nouns (both masculine and feminine) like animals, inanimate objects, and abstract concepts. It is rarely also used for male rational beings.

Examples:

[ٱَلْمُعَلِّمَاتُ فِي ٱلْمَدْرَسَةِ.]{.ar}  
[EalmueallimAtu fi -lmadrasati.]{.trn}  
"The female teachers are in the school."

[ٱَلْحَيَوَانَاتُ فِي ٱلْغَابَاتِ.]{.ar}  
[EalHayawAnAtu fi -lgAbAti.]{.trn}  
"The animals are in the forests."

## Usage of sound plurals

It is not just designative nouns that have plurals. Descriptive nouns may be pluralized as well. For example, [طَيِّبٌ]{.ar} [Tayyibun]{.trn} has the [Un]{.trn} plural [طَيِّبُونَ]{.ar} [TayyibUna]{.trn} and the [At]{.trn} plural [طَيِّبَاتٌ]{.ar} [Tayyibaatun]{.trn}. In using plurals of descriptive nouns, however, Arabic distinguishes between rational beings (humans, angels, and jinn) and non-rational beings (animals, inanimate objects, abstract concepts, etc.).

### Usage of sound plurals of descriptive nouns with rational beings

When a descriptive noun is describing a plural noun denoting rational beings, then the descriptive noun will be pluralized. For example,

[ٱَلْمُعَلِّمُونَ طَيِّبُونَ.]{.ar}  
[EalmueallimUna TayyibUna]{.trn}  
"The male teachers are good."

[كَانَتِ ٱلْجَارِيَاتُ ٱلطَّوِيلَاتُ سَرِيعَاتٍ.]{.ar}  
[kAnati -ljAriyAtu -TTawIlAtu sarIeAtin]{.trn}  
"The tall girls were fast."

### Usage of sound plurals of descriptive nouns with non-rational beings

#### Normal usage

When a descriptive noun is describing a plural noun denoting non-rational beings, either as the describer in a noun-phrase, or in the information of a sentence, then the descriptive noun will typically not be pluralized. The feminine singular descriptive noun is used instead, even if the described noun is masculine. For example,

[حَيَوَانَاتٌ وَحْشَةٌ]{.ar}  
[HayawAnatun waHcatun]{.trn}  
"wild animals"

[ٱَلسِّنُونَ ٱلصَّعْبَةُ]{.ar}  
[EassinUna -SSaebatu]{.trn}  
"the difficult years"

[ٱَلْحَيَوَانَاتُ ٱلْوَحْشَةُ كَبِيرَةٌ.]{.ar}  
[EalHayawAnAtu -lwaHcatu kabIratun]{.trn}  
"The wild animals are big."

[كَانَتِ ٱلسِّنُونَ ٱلصَّعْبَةُ طَوِيلَةً.]{.ar}  
[kAnati -ssinUna -SSaebatu TawIlatan]{.trn}  
"The difficult years were long."

This is done even if the desrciptive noun in the information of the sentence is definite. For example,

[كَانَتِ ٱلسِّنُونَ ٱلصَّعْبَةُ ٱلطَّوِيلَةَ.]{.ar}  
[kAnati -ssinUna -SSaebatu -TTawIlata]{.trn}  
"The difficult years were the long ones."

Note, however, that when a descriptive noun denoting plural non-rational beings is not the describer in a noun-phrase, or is not the information of a sentence, then it will be pluralized. But remember that the [Un]{.trn} plural is only used for male human beings. So the [At]{.trn} plural will be used, even if the descriptive noun refers to a masculine object. For example,

[ٱَلْحَيَوَانَاتُ كَبِيرَةٌ وَصَغِيرَةٌ. ٱَلْكَبِيرَاتُ قَوِيَّةٌ.]{.ar}  
[EalHayawAnatu kabIratun wa SagIratun. EalkabIrAtu qawiyyatun]{.trn}  
"The animals are big and small. The big ones are strong."

In the example above, in the first sentence the descriptive nouns [كَبِيرَةٌ]{.ar} [kabIratun]{.trn} "big" and [صَغِيرَةٌ]{.ar} [SagIratun]{.trn} "small" are in the feminine singular because they are the information of the sentence and are describing the non-human plural described noun [ٱَلْحَيَوَانَاتُ]{.ar} [EalHayawAnAtu]{.trn} "the animals".

But in the second sentence, the descriptive noun 
[ٱَلْكَبِيرَاتُ]{.ar} [EalkabIrAtu]{.trn} "the big ones"
is the subject of the sentence. It is used as a regular noun so it is pluralized with the [At]{.trn} plural. 

It is also the described noun for the descriptive noun [قَوِيَّةٌ]{.ar} [qawiyyatun]{.trn} "strong". [قَوِيَّةٌ]{.ar} is feminine singular because it is the information of the sentence and is describing the non-human plural described noun [ٱَلْكَبِيرَاتُ]{.ar} [EalkabIrAtu]{.trn} "the big ones".

#### Uncommon usage

Using the feminine singular descriptive noun for plural non-rational beings, as we've explained above, is the more normal usage. However, it is allowed, and sometimes you may find, the sound [At]{.trn} plural of a descriptive noun beings used for non-rational beings even when it is a describer in a noun-phrase or in the information of a sentence. Thus you may see:

[ٱَلْحَيَوَانَاتُ ٱلْكَبِيرَاتُ ثَقِيلَاتٌ.]{.ar}  
[EalHayawAnAtu -lkabIrAtu vaqIlAtun.]{.trn}  
"The big animals are heavy."

instead of the normal usage:

[ٱَلْحَيَوَنَاتُ ٱلْكَبِيرَةُ ثَقِيلَةٌ.]{.ar}  
[EalHayawAnAtu -lkabIratu vaqIlatun.]{.trn}  
"The big animals are heavy."

Conversely, we may also find, in rare usage, the feminine singular descriptive noun being used for rational female beings when it is a describer in a noun-phrase or in the information of a sentence. For example,

[جَارِيَاتٌ حَسَنَةٌ]{.ar}  
[jAriyAtun Hasanatun]{.trn}  
"good girls"

instead of the normal usage:

[جَارِيَاتٌ حَسَنَاتٌ]{.ar}  
[jAriyAtun HasanAtun]{.trn}  
"good girls"

For the beginner we recommend that you stick to the normal usage, instead of these rarer usages.

## Pronouns for the plural

We have learned detached pronouns, completed-action verb doer-modifications, and attached pronouns for the singular and the dual. Here we will add the corresponding pronouns for the plural. We use the root [فعلل]{.arroot} as a template to show the verb doer-modifications.

|Person|Detached pronoun|Completed-action verb doer-modification|Attached pronoun|
|:---|:----|:----|:----|
| he/him |[هُوَ]{.ar} [huwa]{.trn} |[فَعَلَ]{.ar}  [-a]{.trn}  |[ـهُ]{.ar} [-hu]{.trn}|
| she/her |[هِيَ]{.ar} [hiya]{.trn} |[فَعَلَتْ]{.ar} [-at]{.trn} |[ـهَا]{.ar} [-hA]{.trn}|
| they/them~dual\ masc.~ |[هُمَا]{.ar} [humA]{.trn} |[فَعَلَا]{.ar} [-A]{.trn} |[ـهُمَا]{.ar} [-humA]{.trn}|
| they/them~dual\ fem.~ |[هُمَا]{.ar} [humA]{.trn} |[فَعَلَتَا]{.ar} [-atA]{.trn} |[ـهُمَا]{.ar} [-humA]{.trn}|
| they/them~pl.\ masc.~ |[هُمْ]{.ar} [hum]{.trn} |[فَعَلُوا]{.ar} [-U]{.trn} |[ـهُمْ]{.ar} [-hum]{.trn}|
| they/them~pl.\ fem.~ |[هُنَّ]{.ar} [hunna]{.trn} |[فَعَلْنَ]{.ar} [-na]{.trn} |[ـهُنَّ]{.ar} [-hunna]{.trn}|
| you~sing.\ masc.~ |[أَنْتَ]{.ar} [Eanta]{.trn} |[فَعَلْتَ]{.ar} [-ta]{.trn} |[ـكَ]{.ar} [-ka]{.trn}|
| you~sing.\ fem.~ |[أَنْتِ]{.ar} [Eanti]{.trn} |[فَعَلْتِ]{.ar}  [-ti]{.trn} |[ـكِ]{.ar} [-ki]{.trn}|
| you~dual~ |[أَنْتُمَا]{.ar} [EantumA]{.trn} |[فَعَلْتُمَا]{.ar} [-tumA]{.trn} |[ـكُمَا]{.ar} [-kumA]{.trn}|
| you~pl.\ masc.~ |[أَنْتُمْ]{.ar} [Eantum]{.trn} |[فَعَلْتُمْ]{.ar} [-tum]{.trn} |[ـكُمْ]{.ar} [-kum]{.trn}|
| you~pl.\ fem.~ |[أَنْتُنَّ]{.ar} [Eantunna]{.trn} |[فَعَلْتُنَّ]{.ar}  [-tunna]{.trn} |[ـكُنَّ]{.ar} [-kunna]{.trn}|
| I/me |[أَنَا]{.ar} [Eana]{.trn} |[فَعَلْتُ]{.ar}  [-tu]{.trn} |[ـنِي]{.ar} [-nI]{.trn}/[ـِي]{.ar} [-I]{.trn}|
| we/us~dual~ |[نَحْنُ]{.ar} [naHnu]{.trn} |[فَعَلْنَا]{.ar} [-nA]{.trn} |[ـنَا]{.ar} [-nA]{.trn}|


Here we will re-list some of the rules for the singular and dual pronouns and add rules for the plural pronouns:

+ The dual attached and detached pronouns for the non-participator "they/them~dual\ masc.~" are pronounced the same: [هُمَا]{.ar} [humA]{.trn}.
+ The plural attached and detached pronouns for the non-participator "they/them~pl.\ masc.~" are pronounced the same: [هُمْ]{.ar} [hum]{.trn}.
+ Only the dual verb doer-modification for the non-participator differentiates between the masculine ([ـَا]{.ar} [-A]{.trn}) and feminine ([ـَتَا]{.ar} [-atA]{.trn}). Otherwise, the same pronouns are used in the dual for both genders.
+ Speaker pronouns and verb doer-modifications do not differentiate between the masculine and feminine genders.
+ The singular attached pronoun for the speaker is [ـنِي]{.ar} [nI]{.trn} when a doee pronoun, and [ـِي]{.ar} [I]{.trn} otherwise. This [ـِي]{.ar} [I]{.trn} becomes a [يَ]{.ar} [ya]{.trn} when preceded by an unvoweled [ي]{.ar}. Examples:
  + [لِي]{.ar}  
    [lI]{.trn}  
    "for me"
  + [ضَرَبَنِي.]{.ar}  
    [DarabanI.]{.trn}  
    "He hit me."
  + [فِيَّ]{.ar}  
    [fiyya]{.trn}   
    "in me". 
  + [إِلَيَّ]{.ar}  
    [Eilayya]{.trn}  
    "to me"

    Note that the [ي]{.ar} in [فِي]{.ar} and [إِلَىٰ]{.ar} gets doubled when it joins with the pronoun [يَ]{.ar}.

+ The attached pronoun and verb doer-modification for the dual/plural speaker "we/us" are the same: [نَا]{.ar} [nA]{.trn}.
+ The same pronouns and verb doer-modifications are used for the dual and plural speaker: [نَحْنُ]{.ar} [naHnu]{.trn} and [ـنَا]{.ar} [-nA]{.trn} respectively.
+ The [u]{.trn}-mark on the attached pronouns [ـهُ]{.ar} [-hu]{.trn}, [ـهُمَا]{.ar} [-humA]{.trn}, and [ـهُمْ]{.ar} [-hum]{.trn} becomes an [i]{.trn}-mark ([ـهِ]{.ar} [-hi]{.trn}, [ـهِمَا]{.ar} [-himA]{.trn}, and [ـهِمْ]{.ar} [-him]{.trn} respectively) when they are preceded by the vowels [◌ِ]{.ar} [i]{.trn}, [ـِي]{.ar} [I]{.trn}, or the semi-vowel [ـَيْ]{.ar} [ay]{.trn}. Examples: 
  + [عَلَيْهِ]{.ar}, [ealayhi]{.trn} "on him"
  + [فِيهِمَا]{.ar} [fIhimA]{.trn} "in them~dual~"
  + [بِهِمْ]{.ar} [bihim]{.trn} "with them~pl.~".
+ The final null-vowel mark on the [مْ]{.ar} in the masculine plural pronouns ([هُمْ]{.ar} [hum]{.trn}, [ـهُمْ]{.ar} [-hum]{.trn}, [أَنْتُمْ]{.ar} [Eantum]{.trn}, [ـتُمْ]{.ar} [-tum]{.trn}, [ـكُمْ]{.ar} [-kum]{.trn}) becomes a [u]{.trn}-mark ([هُمُ]{.ar} [humu]{.trn}, [ـهُمُ]{.ar} [-humu]{.trn}, [أَنْتُمُ]{.ar} [Eantumu]{.trn}, [ـتُمُ]{.ar} [-tumu]{.trn}, [ـكُمُ]{.ar} [-kumu]{.trn} respectively) when followed by a connecting [hamzah]{.trn}. Examples:
  + [هُمُ ٱلْمُعَلِّمُونَ.]{.ar}  
    [humu -lmueallimUna.]{.trn}  
    "They~pl.\ masc.~ are the (male) teachers."
+ The plural masculine verb doer-modification for the non-participator "they~pl.\ masc.~" [ـُوا]{.ar} [U]{.trn} has a silent [Ealif]{.trn} which is written only and not pronounced. This [Ealif]{.trn} is dropped when a doee pronoun is attached. For example: 
  + [ضَرَبُوا ٱلرَّجُلَ.]{.ar}  
    [Darabu -rrajula.]{.trn}  
    "They hit the man."
  + [ضَرَبُوهُ.]{.ar}  
    [DarabUhu.]{.trn}  
    "They~pl.\ masc.~ hit him."
+ The plural masculine verb doer-modification for the addressee "you~pl.\ masc.~" [ـتُمْ]{.ar} [-tum]{.trn} becomes [تُمُو]{.ar} [tumU]{.trn} when a doee pronoun is attached. For example:
  + [ضَرَبْتُمُ ٱلرَّجُلَ.]{.ar}  
    [Darabtumu -rrajula.]{.trn}  
    "You~pl.\ masc.~ hit the man."
  + [ضَرَبْتُمُوهُ.]{.ar}  
    [DarabtumUhu.]{.trn}  
    "You~pl.\ masc.~ hit him."

## Verbs with plural rational doers

In section \@ref(chap-duals-sec-verbs-dual-doer) we learned that if a noun has a dual doer, then:

1. If the doer noun is placed before the verb or is not mentioned, then the dual doer-modification is employed.
2. If the doer noun is placed after the verb, then the singular doer-modification corresponding to the gender of the doer is employed.

We had given the following examples:

+ [ذَهَبَا إِلَىٰ بَيْتٍ.]{.ar}  
  [pahabA EilA baytin.]{.trn}  
  "They~dual~ went to a house."
+ [ٱَلرَّجُلَانِ ذَهَبَا إِلَىٰ بَيْتٍ.]{.ar}  
  [EarrujalAni pahabA EilA baytin.]{.trn}  
  "The (two) men went to a house."
+ [ذَهَبَتِ ٱلْمَرْأَتَانِ إِلَىٰ بَيْتٍ.]{.ar}  
  [pahabati -lmarEatAni EilA baytin.]{.trn}  
  "The (two) women went to a house."

Verbs with plural doer nouns also a corresponding rule, using the plural doer-modification only when either the noun is not mentioned, or is mentioned but placed before the verb. However, this rule is only valid for doers which are rational beings. We will deal with non-rational doers in the next chapter.

Examples:

If there are multiple doers of a verb, and each is mentioned individually, then:

1. If the verb precedes the doers, then it will usually have the doer-modification of the first mentioned doer. Examples:
   + [ذَهَبْتُ أَنَا وَأَنْتَ وَهُوَ.]{.ar}  
     [pahabtu Eana waEanta wahuwa.]{.trn}  
     "I, you, and he went."
   + [ذَهَبَتِ ٱلْأُمُّ وَٱلْغُلَامُ.]{.ar}  
     [pahabati -lEummu wa-lgulAmu.]{.trn}  
     "The mother and the boy went."
2. If the verb follows the doers, then it will have the doer-modification corresponding to number of the doers. Example:
   + [ٱلْأُمُّ وَٱلْجَارِيَةُ ذَهَبَتَا.]{.ar}  
     [EalEummu wa-ljAriyatu pahabatA.]{.trn}  
     "The mother and the girl went."
   + [ٱلْأُمُّ وَٱلْجَارِيَتَانِ ذَهَبْنَ.]{.ar}  
     [EalEummu wa-ljAriyatAni pahabna.]{.trn}  
     "The mother and the two girls went."

   If the doers consist of both male and female persons, then the verb will have the masculine doer prefix corresponding to the number of the doers. Example:
   + [ٱلْأُمُّ وَٱلْجَارِيَةُ وَٱلْغُلَامُ ذَهَبُوا.]{.ar}  
     [EalEummu wa-ljAriyatu wa-lgulAmu pahabU.]{.trn}  
     "The mother, the girl, and the boy went."
   
