# Verbs

## Introduction

Here are some English sentences with verbs:

+ He wrote a book.
+ She wrote a book.
+ You wrote a book.
+ I wrote a book.

Each of these sentences has:

1. a pronoun ("he", "she", "you", "I") which is the doer of the verb,
2. the verb itself: "wrote", and
3. the doee of the verb, i.e., the object upon whom the action of the verb is done: "a book".

Notice in each sentence that the verb "wrote" remains the same irrespective of the doer of the verb.

In Arabic the doer pronoun is attached to the verb as a suffix. For example, the verb "wrote" in Arabic is [كَتَبْ]{.ar} [katab]{.trn}. And these are the doer pronoun suffixes:

1. [◌َ]{.ar}  [a]{.trn}  "he"
2. [ـَتْ]{.ar} [at]{.trn} "she"
3. [تَ]{.ar}  [ta]{.trn} "you (sing. masc.)"
4. [تِ]{.ar}  [ti]{.trn} "you (sing. fem.)"
5. [تُ]{.ar}  [tu]{.trn} "I (masc. & fem.)"

Each of these can be attached to the basic verb stem [كَتَبْ]{.ar} [katab]{.trn} "wrote":

1. [◌َ]{.ar}  + [كَتَبْ]{.ar} = [كَتَبَ]{.ar}   [kataba]{.trn} "He wrote."
2. [ـَتْ]{.ar} + [كَتَبْ]{.ar} = [كَتََبَتْ]{.ar}  [katabat]{.trn} "She wrote."
3. [تَ]{.ar}  + [كَتَبْ]{.ar} = [كَتَبْتَ]{.ar}  [katabta]{.trn} "You (sing. masc.) wrote."
4. [تِ]{.ar}  + [كَتَبْ]{.ar} = [كَتَبْتِ]{.ar}  [katabti]{.trn} "You (sing. fem.) wrote."
5. [تُ]{.ar}  + [كَتَبْ]{.ar} = [كَتَبْتُ]{.ar}  [katabtu]{.trn} "I (masc. & fem.) wrote."

The above are complete sentences in and of themselves. However, we can add the doee ("a book") too:

1.  [كَتَبَ كِتَابًا.]{.ar} [kataba kitAban.]{.trn} "He wrote a book."
2. [كَتََبَتْ كِتَابًا.]{.ar} [katabat kitAban.]{.trn} "She wrote a book."
3. [كَتَبْتَ كِتَابًا.]{.ar} [katabta kitAban.]{.trn} "You (sing. masc.) wrote a book."
4. [كَتَبْتِ كِتَابًا.]{.ar} [katabti kitAban.]{.trn} "You (sing. fem.) wrote a book."
5. [كَتَبْتُ كِتَابًا.]{.ar} [katabtu kitAban.]{.trn} "I (masc. & fem.) wrote a book."

Note that the doee [كِتَابًا]{.ar} [kitAban]{.trn} "a book" has an [an]{.trn}-mark and is therefore in the a-state. Direct doees of verbs shall be in the a-state.

The doee may be a definite noun instead of an indefinite noun, in which case it shall lose the [n]{.trn}-mark and be prefixed with [ٱَلْ]{.ar} [Eal]{.trn}. However, it shall still be in the a-state. For example,

[كَتَبَ ٱلْكِتَابَ.]{.ar}  
[kataba -lkitAba.]{.trn}  
"He wrote the book."

### Verbs with noun doers

So far we have seen verbs whose doers were pronouns ("he", "she", "you", "I"). Similar to English, instead of these pronouns, verbs may have nouns as doers. For example,

1. [كَتَبَ ٱلرَّجُلُ كِتَبًا.]{.ar}  
   [kataba -rrajulu kitAban.]{.trn}  
   "The man wrote a book."
2. [كَتَبَتْ جَارِيَةٌ ٱلْكِتَابَ]{.ar}  
   [katabat jAriyatuni -lkitAba.]{.trn}  
   "A girl wrote the book."

Note that:

+ Even when the doer is a noun, the pronoun suffixes for "he" or "she" are still attached to the verb depending on the gender of the doer. However, they are not translated.
+ The doer nouns are in the u-state. Doer nouns shall generally be in the u-state. 
+ The doer noun follows the verb. Sentence word order is somewhat flexible in Arabic but normally a verb's doer comes after the verb. English primarily uses word order to determine who the doer of a verb is and who the doee is. Conversely, Arabic uses the nouns' states to determine the doer and doee. As mentioned, the doer will be in the u-state and the doee will be in the a-state.



