# Glossary of terms

|This book | Arabic | Western | Notes|
|:----|----:|:----|:------|
|a-state | [المَنْصُوبُ]{.ar}, [حَالَةُ النَّصْبِ]{.ar}| accusative case (nouns), subjunctive mood (verbs) |
|i-state | [المَجْرُورُ]{.ar}, [حَالَةُ الجَرِّ]{.ar}| genitive case ||
|absolute doee |[المَفْعُول المُطْلَق]{.ar} | absolute accusative ||
|adjectival noun |[الصِّفَةُ]{.ar} | epithet |
|adverb of time  |[ظَرْفُ الزَّمَانِ]{.ar}, [المَفْعُولُ فِيهِ]{.ar} | ?? ||
|adverb of place |[ظَرْفُ المَكَانِ]{.ar}, [المَفْعُولُ فِيهِ]{.ar} | ?? ||
|[idafa]{.term} |[الإِضَافَة]{.ar} | ?? ||
|[mudaf]{.term} |[المُضَافُ]{.ar} | construct noun ||
|[mudafil]{.term} |[المُضَافُ إِلَيْهِ]{.ar} | ?? ||
|[verb of] command | [الأَمْرُ]{.ar} | imperative ||
|comment |[الخَبَر]{.ar} | predicate, comment ||
|connected noun |[الاسْمُ المَوْصُولُ]{.ar} | relative pronoun ||
|connecting sentence |[الصِِّلَة]{.ar} | ?? ||
|deputy -- |[نَائِبُ --]{.ar}, [نَائِبٌ عَنْ --]{.ar} | ?? ||
|[mafulb]{.term} |[المَفْعُول بِهِ]{.ar} | object ||
|doer |[الفَاعِلُ]{.ar} | subject ||
|particle|[الحَرْفُ]{.ar} | particle ||
|pointing noun|[اسْمُ الإِشَارَةِ]{.ar} | demonstrative pronoun ||
|preposition|[حَرْفُ الجَرِّ]{.ar} | preposition ||
|prohibition|[النَّهْيُ]{.ar} | ?? ||
|pronoun|[الضَّمِيرُ]{.ar} | pronoun ||
|proper noun|[العَلَمُ]{.ar} | ?? ||
|questioning|[الاسْتِفْهَامُ]{.ar} | interrogative ||
|rigid noun|[الاسْمُ المَيْنِيُّ]{.ar} | ?? ||
|semi-flexible noun|[المَمْنُوعُ مِنَ الصَّرْفِ]{.ar} | diptote ||
|state | [الإعْرَابُ]{.ar} | inflection, case (nouns), mood (verbs) |
|subject of ([إِنَّ]{.ar}, [كَانَ]{.ar}, etc.) |[اسْمُ --]{.ar} | ?? ||
|topic |[المُبْتَدَأُ بِهِ]{.ar}, [المُبْتَدَأُ]{.ar} | subject, topic ||
|[tanwIn]{.trn2} |[التَّنْوِين]{.ar} | nunation ||
|u-state | [المَرْفُوعُ]{.ar}, [حَالَةُ الرَّفْعِ]{.ar}| nominative case (nouns), indicative mood (verbs) ||
|0-state | [المَجْزُومُ]{.ar}, [حَالَةُ الجَزْمِ]{.ar}| jussive mood ||
