# The noun as a verb-like governor

## Introduction

There are some nouns that are like verbs.
In that they may have the meaning of a verb (like the ;masdar;),
or they have be derived from a verb (like the ;mushtaqq;s: the ;ism_fail;, the ;ism_maful;, etc.).

In this chapter we will study their ability to govern a ;faa3il; or a ;maful;.

## The ;ism_fail; as a governor

Consider the verb
yaDribu.
For example:

(@) zaydun yaDribu 3amran

The sentence is parsed as follows:
* zaydun is a ;mubtada;
* The ;xabar; of zaydun is the inner sentence yaDribu 3amran
* yaDribu is a ;ustate; verb. It governs its a singular masculine ;mustatir; pronoun in the ;ustate; as its ;faa3il;.
* 3amran is a ;mafulb; governed in the ;astate; by ;yaDribu;.

Let's consider the inner sentence
yaDribu 3amran
It is a complete sentence consisting a two ;3umdah; elements:

 i. The ;muxbar3;: the singular masculine ;faa3il; pronoun of the verb yaDribu
ii. The ;muxbar;: the verb ;yaDribu;

The ;mafulb; is a ;fadlah; element, and the inner sentence will be grammatically complete without it.

The above analysis is our starting point.
Now we come to our discussion regarding the ;ism_fail;.
The ;ism_fail; is technically a noun.
But because of it derivation from the verb, it has some verbal qualities.

Instead of using the verb yaDribu in example () above
we may instead use its ;ism_fail;
DArib, thus:

(@) zaydun DAribun 3amran

Using the ;ism_fail; instead of the verb affects the meaning of the sentence.
Using DArib instead of yaDrib can be seen as asserting the fact that Zayd is beating 3amr.
We wil study the meaning implications of using an ;ism_fail; vs a verb in more detail in section\ (ref) below.
For now, let's focus on the grammar of the new sentence.
If we parse example () we get the following analysis:

* zaydun is a ;mubtada; in the ;ustate;.
* DAribun is the ;xabar; of the ;mubtada; in the ;ustate;.
  It governs its a singular masculine ;mustatir; pronoun in the ;ustate; as its ;faa3il;.
* 3amran is a ;mafulb; governed in the ;astate; by ;yaDribu;.

Note that, just like the verb yaDribu,
;DAribun; now governs a ;faa3il; and the ;mafulb;.

Implicating the ;mustatir; ;faa3il; pronoun is essential for the grammar of the sentence.
And we will get to it in section\ (ref) below.
But before we do that, let's discuss an important difference of the new sentence () zaydun DAribun 3amran from the old sentence () zaydun yaDribu 3amran:

And that is that
Daribun 3amran
is not an inner sentence.
This is because it is not a complete sentence.
The single word DAribun itself is the ;xabar; of ;zaydun;.
The two ;3umdah; elements are:
zayd (the ;muxbar3;), and DAribun (the ;muxbar;).
The ;mustatir; singular masculine ;faa3il; pronoun) does not make an inner sentence with its governor DAribun.
We can understanding this by seeing that we can say 
yaDribu 3amran
as a complete sentence to mean "He beat 3amr."
But we cannot say
DAribun 3amran.
as a complete sentence.
DAribun 3amran
requires Zaydun as a ;mubtada; to form one complete sentence.
Nevertheless,
the ;mustatir; ;faa3il; pronoun is an integral part of the ;ism_faa3il; DArib and is governed by it in the ;ustate;.

## Conditions for using the ;ism_fail; as a verb-like governor

There are X conditions that need to be satisfied for using the ;ism_fail; as a governor:

## Implicating the ;mustatir; ;faa3il; pronoun

The ;mustatir; ;faa3il; pronoun will typically accompany its governing ;ism_fail; in most cases.

gender matching
number matching
drvaniya

When the ;ism_fail; is not a verb-like governor, then the ;mustatir; ;faa3il; pronoun is not implicated.
This is in the following cases:

## Replacing the ;mustatir; ;faa3il; pronoun with an apparent noun


** Important ** : Hidden pronoun requires gender matching of ism_fail to its mufassir


## Meaning implication of using the ;ism_fail; instead of the verb

## Improper annexation (maybe its own chapter)

yaqoom
qaa'im.
