    "albahr-almuheet"
    , cit_text = "[البحر المحيط لأبي حيان]{.ar}"
    , bib_text = "[البحر المحيط لأبي حيان]{.ar}, <https://tafsir.app/albahr-almuheet>"
    "ibn-aashoor"
    , cit_text = "[تفسير التحرير والتنوير لابن عاشور]{.ar}"
    , bib_text = "[تفسير التحرير والتنوير لابن عاشور]{.ar}, <https://tafsir.app/ibn-aashoor>"
    "tabari"
    , cit_text = "[تفسير الطبري]{.ar}"
    , bib_text = "[تفسير الطبري]{.ar}, <https://tafsir.app/tabari>"
    "ibn-katheer"
    , cit_text = "[تفسير ابن كثير]{.ar}"
    , bib_text = "[تفسير ابن كثير]{.ar}, <https://tafsir.app/ibn-katheer>"
    "ibn-alqayyim"
    , cit_text = "[تفسير ابن القيم]{.ar}"
    , bib_text = "[تفسير ابن القيم]{.ar}, <https://tafsir.app/ibn-alqayyim>"
    "ibn-taymiyyah"
    , cit_text = "[تفسير ابن تيمية]{.ar}"
    , bib_text = "[تفسير ابن تيمية]{.ar}, <https://tafsir.app/ibn-taymiyyah>"
    "ibn-uthaymeen"
    , cit_text = "[تفسير ابن عثيمين]{.ar}"
    , bib_text = "[تفسير ابن عثيمين]{.ar}, <https://tafsir.app/ibn-uthaymeen>"
    "qurtubi"
    , cit_text = "[تفسير القرطبي]{.ar}"
    , bib_text = "[تفسير القرطبي]{.ar}, <https://tafsir.app/qurtubi>"

