# Sentence and government theory

## Introduction


## The elements of a sentence

There are two types of sentences in Arabic:

 i. The ;mubtada;-;xabar; sentence.
    It begins with a noun.
    For example:

    (@) [زَيْدٌ رَجُلٌ]{.ar}  
        "Zayd is a man."
<!--
    (@) [زَيْدٌ كَتَبَ]{.ar}  
        "Zayd, he wrote."
-->

ii. The verbal sentence.
    It begins with a verb.
    For example:

    (@) [كَتَبَ زَيْدٌ]{.ar}  
        "Zayd wrote."

Particles like [وَ]{.ar} "and", [مَا]{.ar} are allowed to precede the sentences
(if applicable)
without affecting their being a
;mubtada;-;xabar;
or verbal sentence.
So [وَزَيْدٌ رَجُلٌ]{.ar} is still a 
;mubtada;-;xabar;
sentence.
And 
[مَا كَتَبَ زَيْدٌ]{.ar} "Zayd did not write" is a verbal sentence.

The Arabic sentence,
(whether a
;mubtada;-;xabar; sentence,
or a verbal sentence)
has two basic elements:

 i. The _;musnadi;_
ii. The _;musnad;_

The ;musnadi;
and
the ;musnad;
complement each other.
The ;musnadi; provides support to the ;musnad;.
And the ;musnad; relies upon the ;musnadi;.

In the 
;mubtada;-;xabar;
the ;mubtada; is the ;musnadi;.
And the ;xabar; is the ;musnad;.

And in the verbal sentence,
the ;faa3il; is the ;musnadi;.
And the verb is the ;musnad;.

ADD DIAGRAM

The ;musnadi;
and
the ;musnad;
are the two _;3umdah;_ elements of a sentence, without which the sentence is not complete.
Any other elements that are added are considered _;fadlah;_.

Consider the following example:

(@) [كَتَبَ زَيْدٌ كِتَابًا]{.ar}  
    "Zayd wrote a book."

In the above example, the ;mafulb; [كِتًابًا]{.ar} is considered a ;fadlah; element.
If we remove it from the sentence, the sentence remains grammatically complete.

(@) [كَتَبَ زَيْدٌ]{.ar}  
    "Zayd wrote."

By the way,
even though a ;fadlah; element 
is not necessary to make a sentence grammatically complete,
removing it may affect the meaning drastically.

Consider the following example:

(@government-not-see-zayd) [مَا رَأَيْتُ زَيْدًا]{.ar}  
    "I did not see Zayd."

If we remove the ;mafulb; [زَيْدًا]{.ar}, the sentence is grammatically complete but will have a very different meaning from the original:

(@) [مَا رَأَيْتُ]{.ar}  
    "I did not see."

## The theory of government

We know that nouns and ;mudarie; verbs have a concept called _state_.
When such a _stateful_ element is in a sentence, it will be in a particular state.
But how do we know in which state we should put a stateful element?
To determine this we use the theory of _government_.^[@liheibi_sentence@ 107]

The theory of government states that every stateful element is governed by a _governor_.
(An element may be governed by only one governor. One governor may, however, may govern multiple separate elements.)
And that governor determines what state the stateful element will be in.
The element governed by a governor is called a _governee_.
For example,
the rule for the government of a ;mafulb; is that the
;mafulb; is governed typically by a verb.
And the verb governs the
;mafulb; in the ;astate;.

So when we say (@government-not-see-zayd) [مَا رَأَيْتُ زَيْدًا]{.ar} 
then the verb
[رَأَيْتُ]{.ar} is the governor of the
;mafulb; [زَيْدًا]{.ar} and governs it in the ;astate;.
We can also say that
the ;mafulb; [زَيْدًا]{.ar}
is the governee of the verb
[رَأَيْتُ]{.ar}.

<!--
In a similar manner, other stateful elements like
the ;mubtada;,
the ;xabar;,
the ;faa3il;,
the ;mudafil;,
etc.
will have governors that are discussed in the literature.^[@liheibi_sentence@ chapter\ 4, @owens_foundations_grammar@ chapter\ 2]

In this chapter we will discuss governing the ;mafulb;, the preposition, and the ;mudafil;.
We will not discuss
governing
the ;mubtada;,
the ;xabar;,
and
the ;faa3il;,
because we deem it of less practical value. The interested reader may refer to the above-mentioned resources for them.
And for other stateful elements, like adverbs, we will discuss their government in their respective chapters, ;ia;.


Similarly,
the particle [لَمْ]{.ar} governs a ;mudarie; verb in the ;istate;.
So if we say [لَمْ يَذْهَبْ زَيْدٌ]{.ar},
then th particle [لَمْ]{.ar} is the governor of the ;istate; ;mudarie; verb 
[يَذْهَبْ]{.ar}.

In a similar manner, other stateful elements like
the ;mubtada;,
the ;xabar;,
the ;faa3il;,
the ;mudafil;,
etc.
will have governors that are discussed in the literature.^[See @liheibi_sentence@]

## The government of the preposition

It is not just stateful elements that are governed


## Adding ;fadlah; elements to a sentence: the theory of government

In order to add
_stateful_
;fadlah; elements to a sentence,
Arabic grammatical theory states that their must be
a governor 


```yml
non-essential elements
nested sentences
```

Some fact.^[@liheibi_sentence@ 245]

Sometimes the ;3aamil; is required to be implicit.
For example:

(@) [عَلَىٰ رَجُلٍ مِنَ ٱلْقَرْيَتَيْنِ عَظِيمٍ]{.ar}  
    "on a great existing^from\ the\ two\ cities^ man"

The fundamental structure is "on a great existing man,"
where "great" and "existing" are the ;na3t;s.
Then the ;shibh_jumlah; 
[مِنَ ٱلْقَرْيَتَيْنِ]{.ar}
is added as a ;ma3mul; of the conceptual ;3aamil; "existing."

-->

## The government of the ;mafulb;

## The government of the preposition

### The need for governing the preposition

In the Arabic grammatical model, prepositional phrases are ;fadlah; elements.
In order to bring a ;fadlah; stateful element into a sentence, a suitable element of the original sentence must act as governor of the new ;fadlah; element.
For example, consider the sentence

(@) [جَلَسَ زَيْدٌ]{.ar}  
    "Zayd sat."

We would like to add the prepositional phrase
[عَلَى ٱلْأَرْضِ]{.ar}
"on the ground" to the sentence, thus:

(@sentence-verb-gov-prep-zayd-sat-ground) [جَلَسَ زَيْدٌ عَلَى ٱلْأَرْضِ]{.ar}  
    "Zayd sat on the ground."

In order to do this, a suitable element in the original sentence 
([جَلَسَ زَيْدٌ]{.ar})
must act as the governor for the preposition
[عَلَىٰ]{.ar}.
The verb
[جَلَسَ]{.ar}
is this suitable element.

Now, you may be thinking:
we introduced the concept of government for determining the state of an element.
But prepositions don't have state. So why should they need to be governed, and in what manner may they be governed?

This is a valid objection. 
"Governing" a preposition is definitively problematic.^[@owens_foundations_grammar@ 177]
However, we can work around this problem with the following reasoning:

<!--
The preposition
[عَلَىٰ]{.ar}
is followed by the
[ٱلْأَرْضِ]{.ar}
in the ;istate;.
-->
The noun
[ٱلْأَرْضِ]{.ar}
is governed by the preposition
[عَلَىٰ]{.ar}
and not directly by the verb
[جَلَسَ]{.ar}
This is because it is the preposition which _causes_ the noun following it to be in the ;istate;.
In order to bring the ;fadlah; (stateful) element
[ٱلْأَرْض]{.ar}
in the sentence,
we have to establish an unbroken chain of ;3aamil;-;ma3mul; dependencies that links back to a governing element in the original sentence.
Saying that
[عَلَىٰ]{.ar}
is governed by
[جَلَسَ]{.ar}
allows us to accomplish this.
So
[جَلَسَ]{.ar}
will govern
[عَلَىٰ]{.ar}.
And
[عَلَىٰ]{.ar}
will govern
[ٱلْأَرْض]{.ar}.


ADD DIAGRAM

Another way to look at this is that a prepositional phrase may be parsed (virtually) as a ;mafulb;.^[@kasher_intransitive_verb@ §3.1 124 citing [ابن جني]{.ar}; @nahw_wafi@ 2/439; @owens_foundations_grammar@ 176 citing [المبرد]{.ar}, [ابن جني]{.ar}, [الزجاجي]{.ar}.]
Consider the example:

(@sentence-pass-zayd) [مَرَرْتُ بِزَيْدٍ]{.ar}  
    "I passed by Zayd."

In the above example, the prepositional phrase
[بِزَيْدٍ]{.ar}
may be parsed (virtually) as in the ;astate; as a ;mafulb;.
So much so, that if we wish to add a second ;maful; using a ;3atf; then it may be added in the ;astate;.
For example:

(@) [مَرَرْتُ بِزَيْدٍ وَعَمْرًا]{.ar}
    ^[Not all grammarians permit this. See @ali_hani_ta3alluq@ footnote 34 for details.]  
    "I passed by Zayd and [#eamr]{.trn2}."

Of course the more usual 
[مَرَرْتُ بِزَيْدٍ وَعَمْرٍو]{.ar}
is also permitted.

So we can consider the verb as governing the entire prepositional phrase in the ;astate;.
And within the prepositional phrase, the preposition governs its following noun in the ;istate;.

ADD DIAGRAM



<!--
([جَلَسَ زَيْدٌ]{.ar}).
it has to be by means of its governor
[عَلَىٰ]{.ar}.
So if we say that
[عَلَىٰ]{.ar}
is governed by
[جَلَسَ]{.ar}
then this allows us to establish the necessary link of dependencies

So saying that
[عَلَىٰ]{.ar}
is governed by
[جَلَسَ]{.ar}
allows us to have a (necessarily) unbroken dependency of governorns to add the ;fadlah; (and stateful) element 
[ٱلْأَرْض]{.ar}.
-->

### Prepositions not needing a governor

What we have just said regarding a preposition requiring a governor is true of _essential_ prepositions.
An essential preposition is that which, by its addition, gives a distinctly new meaning to the sentence.
They are also used to connect an indirect ;maful; to its governing verb.
The preposition [ب]{.ar} in (@sentence-pass-zayd) [مَرَرْتُ بِزَيْدٍ]{.ar} is an example of an essential preposition.

There also exist _non-essential_ prepositions.
These merely give emphasis to an existing meaning in the sentence.
Non-essential prepositions do not need a governor.
Here is an example of a non-essential preposition:

(@) [ما جاء من رجلٍ]{.ar}
    [@ali_hani_ta3alluq@]{.citex}  
    "Not a man came."

The preposition [مِنْ]{.ar} only emphasizes the meaning of the sentence.
If we drop if the basic meaning would remain the same:

(@) [ما جاء رجلٌ]{.ar}
    [@ali_hani_ta3alluq@]{.citex}  
    "Not a man came."

By the way,
[مِنْ]{.ar} happens to be a non-essential preposition in the example above.
But it may be an essential preposition in other sentences.
For example:

(@) [خَرَجَ زَيْدٌ مِنَ ٱلْبَيْتِ]{.ar}  
    "Zayd came out from the house."

### Valid governors of the preposition

The verb is the typical governor of the preposition.
We have already given an example of a verb governing a prepostion: (@sentence-verb-gov-prep-zayd-sat-ground) [جَلَسَ زَيْدٌ عَلَى ٱلْأَرْضِ]{.ar}.
Besides the verb, nouns that have the effect of a verb may also govern the preposition.
Such nouns include:

##### The ;masdar; {.unnumbered}

Also included are ;mushtaqq; nouns like:

##### The ;ism_fail; {.unnumbered}

##### The ;ism_maful; {.unnumbered}

##### The ;sifah_mush; {.unnumbered}

##### The ;sighah_mub;s {.unnumbered}

##### The ;af3al; {.unnumbered}

<!--
Even ;mushtaqq; nouns that don't typically govern a ;mafulb; 
(like the ;ism_zaman; and the ;ism_makan;)
are permitted to govern a preposition^[@nahw_wafi@ 2/440 citing @sabban@ 2/443. But [#abU #HayyAn]{.trn2} did not allow this (see ).]:
-->

Grammarians differ regarding whether the 
the ;ism_zaman; and the ;ism_makan;
are permitted to govern a preposition.
Some grammarians allow them to govern prepositions.^[@nahw_wafi@ 2/440 citing @sabban@ 2/443]
Others disagree.^[@ibn_jinni_khasaais@ 2/209]
Here are examples (considering them permissible) as governors:

##### The ;ism_zaman; {.unnumbered}

(@) [انقضى مسعاك لتأييد الحق]{.ar}
    [@nahw_wafi@ 2/440]{.citex}  
    "Your [period of] effort for aiding the truth has ended."

##### The ;ism_makan; {.unnumbered}

(@) [رأيت مدخلك إلى الدار]{.ar}
    [@sabban@ 2/443]{.citex}  
    "I saw your [place of] entrance to the house."


Also permitted as governorns are ;jamid; nouns used with an adjectival meaning.
For example:

### One governor governing multiple prepositions

One governor can govern multiple different prepositions with no problems.
For example:

But if the multiple governees are the same prepositon, then in general they may not be governed by the same governor.^[@nahw_wafi@ 2/444 footnote 3]
So we can't say:

(@) ;x; [مَرَرْتُ بِزَيْدٍ بِعَمْرٍو]{.ar}
    [@tasreeh_hashiyat_yasin@ 1/378]{.citex}  
    "I passed by Zayd by [#eamr]{.trn2}"  
    (although, separting the second preposition with a ;3atf; is of course allowed: [مَرَرْتُ بِزَيْدٍ وَبِعَمْرٍو]{.ar}.)

But if the same preposition is used with different meanings then it is permissible to have them being governed by the same governor.
For example:

(@) [مَرَرْتُ بِزَيْدٍ بِٱلْبَادِيَةِ]{.ar}
    [@tasreeh_hashiyat_yasin@ 1/378]{.citex}  
    "I passed _by_ Zayd _in_ the desert."

If the first preposition restricts the verb, and the second preposition is applied after the verb has been restricted, then too may the multiple same prepositions be used.^[@nahw_wafi@ 2/444 footnote 3]
For example:

(@) [كُلَّمَا رُزِقُوا مِنْهَا مِنْ ثَمَرَةٍ رِّزْقًا]{.ar}
    [@https://quran.com/2/25@]{.citex}  
    (The first [مِنْ]{.ar} restricts the governing verb [رُزِقُوا]{.ar} to [ٱلْجَنًّات]{.ar} "the gardens". And the second [مِنْ]{.ar} is restricted to "from the fruit from the gardens."^[@https://tafsir.app/kashaf/2/25@])

### A meaningful connection between the preposition and its governor

In order for a preposition to be governed by a governor,
there needs to be a meaningful connection between the governor and the governed prepositional phrase.^[@nahw_wafi@ 2/442D--445, @maani_nahw@ 3/131--133]

Consider the following example:

(@) [شَبَّهْتُ خَالِدًا وَهُوَ يَجُودُ بِمَالِهِ بِٱلْبَحْرِ]{.ar}
    [@maani_nahw@ 3/131]{.citex}  
    "I likened [#xAlid]{.trn2}, while he (was) being generous with his wealth, with the sea."  
    (The [و]{.ar} in [وَهُوَ يَجُودُ]{.ar} is translated as "while." See section\ (ref).)

In the above example,
the prepositional phrase
[بِٱلبَحْرِ]{.ar} "with the sea"
is meaningfully connected to the verb
[شَبَّهَ]{.ar} "to liken,"
not with the verb 
[يَجُودُ]{.ar} "to be generous."
Therefore, it is
[شَبَّهَ]{.ar}
that governs
the preposition in
[بِٱلبَحْرِ]{.ar},
not
[يَجُودُ]{.ar}.

Similarly,
the prepositional phrase
[بِمَالِهِ]{.ar} "with his wealth"
is meaningfully connected to the verb
[يَجُودُ]{.ar} "to be generous,"
not with the verb
[شَبَّهَ]{.ar} "to liken."
Therefore, it is
[يَجُودُ]{.ar}
that governs
the preposition in
[بِمَالِهِ]{.ar},
not
[شَبَّهَ]{.ar}.

Here is another example:

(@) [ٱلْيَوْمَ يَئِسَ ٱلَّذِينَ كَفَرُوا مِنْ دِينِكُمْ]{.ar}
    [@https://quran.com/5/3@ cited by @maani_nahw@ 3/131]{.citex}  
    "This day those who disbelieve have despaired of [defeating] your religion;"

In the above example,
the prepositional phrase
[مِنْ دِينِكُمْ]{.ar} "of your religion
is meaningfully connected to the verb
[يَئِسَ]{.ar} "to despair,"
not with the verb 
[كَفَرَ]{.ar} "to disbelieve"
Therefore, it is
[يَئِسَ]{.ar}
that governs
the preposition in
[مِنْ دِينِكُمْ]{.ar}
not
[كَفَرَ]{.ar}.^[@https://tafsir.app/aldur-almasoon/5/3@]

### The combination of verbs with prepostions: the indirect ;maful;

In theory,
prepositions impart their own meanings.^[@kasher_intransitive_verb@ §2.7 124]
And there is no restriction on which prepositions may be used with a given governing verb (or verbal noun),
as long as the prepositional phrase be meaningfully connected with its governor.^[@nahw_wafi@ 2/161]

The following examples show a possible set of prepositions that are meaningfully governed by the verb
[ٱنْصَرَفَ]{.ar} "to turn around, leave":

(@) [ٱنْصَرَفَ إِلَىٰ مَصْنَعِهِ]{.ar}
    [@nahw_wafi@ 2/161]{.citex}  
    "He left to his workplace."

(@) [ٱنْصَرَفَ مِنَ ٱلْمَصْنَعِ إِلَىٰ بَيْتِهِ]{.ar}
    [@nahw_wafi@ 2/161]{.citex}  
    "He left from the workplace to his house."

(@) [ٱنْصَرَفَ ٱلْعَالِمُ عَنِ ٱلْهَزْلِ]{.ar}
    [@nahw_wafi@ 2/161]{.citex}  
    "The scholar left off joking."

(@) [ٱنْصَرَفَ فِي سَيَّارَتِهِ]{.ar}
    [@nahw_wafi@ 2/161]{.citex}  
    "He left in his caravan."

Having said that,
in practice,
certain verbs are more meaningfully connected with certain prepositions, sometimes almost to the exclusion of others.^[@kasher_intransitive_verb@ §3.3]
For example, the verb
[أَقْسَمَ]{.ar} "to swear"
requires the preposition [بِ]{.ar} in order to transit to what is being sworn by.^[@kasher_intransitive_verb@ §3.3 129 citing [ابن الأنباري]{.ar}]
For example,

(@) [أقسم بالله]{.ar}
    [@anbari_asrar@ 203]{.citex}  
    "I swear by [#allAh]{.trn2}"

The combination of a verb and its governed preposition can even acquire a specific meaning.
Consider, for example, the verb
[وَجَدَ]{.ar}.
It's basic meaning is "to find."
It may be used with prepositions like
[بِ]{.ar},
[عَلَىٰ]{.ar},
[فِي]{.ar}
with this basic meaning.
For example:

(@) [وَجَدْتُ ٱلْكِتَابَ بِجَهْدٍ]{.ar}  
    "I found the book with effort."

(@) [وَجَدْتُ ٱلْكِتَابَ فِي ٱلْبَيْتِ]{.ar}  
    "I found the book in the house."

(@) [وَجَدْتُ ٱلْكِتَابَ عَلَى ٱلْخِزَانَةِ]{.ar}  
    "I found the book on the cupboard."

But this verb also has specific meanings when used with these prepositions and certain indirect ;maful;s
(albeit possibly with different ;masdar;s).
For example:

(@) [وَجَدَ عَلَيْهِ]{.ar}
    [Lane: root [وجد]{.ar}]{.citex}  
    "He was angry with him."

(@) [وَجَدَ بِهَا]{.ar}
    [Lane: root [وجد]{.ar}]{.citex}  
    "He loved her."

(@) [قَدْ وَجَدَ فِي نَفْسِهِ عَلَىَّ]{.ar}
    [@https://sunnah.com/muslim:1649b@]{.citex}  
    "he may have some feelings against me"

In such cases, the preposition almost seems to lose some of its independent meaning.
Instead, the meaning of the expression is obtained from the combination of the verb with the prepostion.

### The implication of general beingness

Consider the sentence:

(@sentence-zayd-in-house) [زَيْدٌ فِي ٱلدَّارِ]{.ar}
    [@ibn_aqil_alfiyyah@ 2/211]{.citex}  
    "Zayd is in the house."

We mentioned in section\ (ref) above,
that the governor of a preposition must be a verb, or what has the effect of a verb.
But we find no such word in the sentence above.
So what then is the governor of the preposition [فِي]{.ar}?

In order to remain consistent with the Arabic grammatical model,
we _implicate_ the involvement of an implied governor.
This implied governor has the meaning given by the verb "is" or its verbal noun "being".
We will refer to it as _general beingness_.

In Arabic grammatical terminology,
general beingness is represented by the verb
[ٱسْتَقَرَّ]{.ar}
or its ;ism_fail;
[مُسْتَقِرّ]{.ar},
or by the word
[كَائِن]{.ar},
which is the ;ism_fail; of the verb
[كَانَ]{.ar}.

Using these representations of general beingness,
we can explicate
(one interpretation of)
example (@sentence-zayd-in-house) [زَيْدٌ فِي ٱلدَّارِ]{.ar} as:

(@sentence-zayd-in-house-explicit) [زَيْدٌ [مُسْتَقِرٌّ] فِي ٱلدَّارِ]{.ar}  
    "Zayd is [being] in the house."

The word "being" is not really needed in the translation because the verb "is" conveys the same concept.
But we have added it to explicate the involvement of general beingness in the grammar of the sentence.

Note that
implicating general beingness in a sentence 
as we did in example (@sentence-zayd-in-house-explicit) above
is not same as if the words
[ٱسْتَقَرَّ]{.ar} "to settle",
[مُسْتَقِرّ]{.ar} "settled",
or
[كَائِن]{.ar} "being"
were actually expressed.
When expressed, they impart their own meaning.
For example

(@) [زَيْدٌ مُسْتَقِرٌّ فِي ٱلدَّارِ]{.ar}  
    "Zayd is settled in the house."

When implicating general beingness we only use the words
[ٱسْتَقَرَّ]{.ar},
[مُسْتَقِرّ]{.ar},
and
[كَائِن]{.ar}
terminologically.
In fact, according to the prevalent opinion among the grammarians,
general beingness can only be implied.^[@nahw_wafi@ 1/477]
If one of these (or any other) words is actually expressed,
then it will impart a specific meaning, not the meaning of general beingness.
Having said that, some grammarians did permit general beingness to be expressed.^[@ibn_aqil_alfiyyah@ 2/211 footnote]

### Implied general beingness as the ;xabar; of a sentence

The implication of generall beingness in the sentence
in example (@sentence-zayd-in-house) [زَيْدٌ فِي ٱلدَّارِ]{.ar}
solves another problem for us.
Remember how we said that, in the Arabic grammatical model,
the preposition is a ;fadlah; element.
So if we remove it (and the following ;istate; noun [ٱلدَّار]{.ar}) from the sentence,
we should still be left with a complete sentence.
Let's try doing that:

(@) [زَيْدٌ [مُسْتَقِرٌّ]]{.ar}  
    "Zayd is [being]."

See how the implied general beingness serves as the ;3umdah; ;musnad;: the ;xabar;.
If we were to not implicate general beingness, we would be left with a grammatically incomplete sentence.

We also take this opportunity to explain an apparent inconsistency.
Back in chapter\ (ref),
we had said that a prepositional phrase can be the ;xabar; of a sentence.
We now state that, strictly speaking, it is the (implied) governor of the prepostion which is the ;xabar;.
But because the actual ;xabar; is implied and is not expressed, we can say, loosely speaking,
that the prepositional phrase is the ;xabar;.

This approach of applying a terminological label differently when loosely speaking vs when strictly speaking is common.^[@nahw_wafi@ 1/215, 2/118, 2/442]
We will see other examples of it in sections\ (refs) ;ia;.

### Other implied governors besides general beingness

While general beingness is necessarily implied and never expressed (see section\ (ref) above),
other governors of prepositions too may be optionally suppressed.
This is done on the condition that that the overall meaning or context supplies the meaning of the suppressed governor.^[@nahw_wafi@ 2/447 footnote]
For example:

(@) [ٱلْحُرُّ بٱلْحُرِّ]{.ar}
    [@https://quran.com/2/178@ cited by @nahw_wafi@ 2/447]{.citex}  
    "the free for the free"

In the above example,
the ;xabar; has been analyzed as the implied governor
[يَقْتَصُّ]{.ar} "is retributed against"
or
[يُقْتَلُ]{.ar} "is killed".
So the sentence with the implicated meaning is 
[الحُرُّ يَقْتَصُّ أوْ يُقْتَلُ بِالحُرِّ]{.ar}
"the free is retributed against, or killed, for the free."^[@https://tafsir.app/ibn-aashoor/2/178@]

### The prepositional phrase as a ;na3t;

Consider the sentence

(@sentence-prep-phrase-na3t) [رأيتُ طائرًا على الغصن]{.ar}
    [@ali_hani_ta3alluq@]{.citex}  
    "I saw a bird on the branch."

Now the logical assumption is that the bird was on the branch, not that my act of seeing was done on a branch.
So this means that the preposition [عَلَىٰ]{.ar} is not meaningfully connected with the verb [رَأَىٰ]{.ar}.
Therefore, [رَأَىٰ]{.ar} is not the governor of the preposition [عَلَىٰ]{.ar}.^[@ali_hani_ta3alluq@]
So what then is governing the preposition [عَلَىٰ]{.ar}.

Here again, we implicate the governor of general beingness, as if to say:

(@) [رأيتُ طائرًا [مُسْتَقِرًّا] على الغصن]{.ar}  
    "I saw a bird [being] on the branch."

General beingness
[[مُسْتَقِرًّا]]{.ar}
is implicated as the governor of
the preposition [عَلَىٰ]{.ar}.
The implicated general beingness is also a ;na3t; to the ;mafulb; 
[طَائِرًا]{.ar}.
But because 
the implied general beingness is not expressed, we may say, loosely speaking,
that the prepositional phrase is the ;na3t;.

In order for a prepositional phrase to be a ;na3t;,
its ;manut; will usually be an indefinite noun,
like 
[طَائِرًا]{.ar}
is in example (@sentence-prep-phrase-na3t) above.
In the case where the prepositional phrase occurs after a definite noun,
(like in [رأيتُ ٱلطائر على الغصن]{.ar})
it will typically be analyzed as a ;hal;.
We will discuss this in more detail in chapter\ (ref) section\ (ref) ;ia;.

Here are some more examples of prepositional phrases as ;na3t;s:

<!--
(@) [لَقَدْ جَاءَكُمْ رَسُولٌ مِنْ أَنْفُسِكُمْ]{.ar}
    [@https://quran.com/9/128@]{.citex}  
    "There has certainly come to you a Messenger from among yourselves."  
    ([مِنْ أَنْفُسِكُمْ]{.ar} is analyzed as a ;na3t;^[])
-->

(@) [كَمَثَلِ جَنَّةٍ بِرَبْوَةٍ]{.ar}
    [@https://quran.com/2/265@]{.citex}  
    "like a garden on high ground"  
    ([بِرَبْوَةٍ]{.ar} is analyzed as a ;na3t;.^[@https://tafsir.app/albahr-almuheet/2/265@])

(@) [رَبَّنَا وَٱبْعَثْ فِیهِمْ رَسُولًا مِّنْمْهُ]{.ar}
    [@https://quran.com/2/129@]{.citex}  
    "Our Lord, and send among them a messenger from themselves"  
    ([مِنْهُمْ]{.ar} is analyzed as a ;na3t;.^[@https://tafsir.app/albahr-almuheet/2/129@])

<!--
(@) [وَقَالُوا لَوْلَا نُزِّلَ هَـٰذَا ٱلْقُرْءَانُ عَلَىٰ رَجُلٍ مِنَ ٱلْقَرْيَتَيْنِ عَظِيمٍ]{.ar}
    [@https://quran.com/43/31@]{.citex}  
    And they said, "Why was this Qur’ān not sent down upon a great man from [one of] the two cities?"  
-->


When a prepositional phrase is, loosely speaking, a ;na3t;,
its governor is typically the implicated general beingness.^[@ibn_hisham_awdah_almasaalik@ 2/285, @ibn_aqil_alfiyyah@ 1/213].
<!--
In fact, some grammarians insist that the implied governor can only be general beingness.^[@https://tafsir.app/albahr-almuheet/3/194@ ([مَا وَعَدْتَنَا عَلَىٰ رُسُلِكَ]{.ar})]
-->
However, it is conceivable that the implied governor of the preposition be interpreted, if not formally then at least in meaning, as some other verb (or verbal noun).^[@nahw_wafi@ 2/447 footnote]
For example:

(@sentence-quran-27-12) [فِی تِسْعِ ءَایَاتٍ إِلَىٰ فِرْعَوْنَ وَقَوْمِهِ]{.ar}
    [@https://quran.com/27/12@]{.citex}  
    "[These are] among the nine signs [you will take] to Pharaoh and his people."

In one interpretation of the above [Ayah]{.trn2},
the 
prepositional phrase
[إِلَىٰ فِرْعَوْنَ]{.ar}
"to Pharoah"
has been analyzed as ;na3t; of
[ءَایَاتٍ]{.ar}
"signs".
The meaning with the implicated governor has been explained as
[وَاصِلَةٌ إِلَى فِرْعَوْنَ]{.ar}
"_arriving_ to Pharoah".^[@3akbari_tibyan@ 2/1005. But see also @https://tafsir.app/aldur-almasoon/27/12@ where this interpretation is critiqued.]

Here is another example:

(@sentence-quran-9-125) [فَزَادَتْهُمْ رِجْسًا إِلَىٰ رِجْسِهِمْ]{.ar}
    [@https://quran.com/9/125@]{.citex}  
    "it has [only] increased them in evil [in addition] to their evil"

In the above [Ayah]{.trn2},
the 
prepositional phrase
[إِلَىٰ رِجْسِهِمْ]{.ar}
"to their evil"
has been analyzed as ;na3t; of
[رِجْسًا]{.ar}
"evil".
The meaning with the implicated governor has been explained as
[كُفْرًاً مَضْمُومًا إِلَىٰ كُفْرِهِمْ]{.ar}
"in disbelief _in addition_ to their disbelief."^[@https://tafsir.app/kashaf/9/125@]




<!--
### The order of different ;na3t;s

When a ;manut; is described by more than one ;na3t; and 
@nahw_wafi@ 3/496
-->

### The prepositional phrase in other functions

Besides the ;xabar; and the ;na3t; a prepositional phrase may also occur as a ;hal; and a ;silah;.^[@nahw_wafi@ 2/441--442]
We will cover these two remaining topics in their respective chapters in sections\ (ref) and (ref) respectively.

## The government of the ;mudafil; in an ;idaafah;

As we know, the ;mudafil; of an ;idaafah; is always in the ;istate;.
For example, in the annexation
[كِتَابُ ٱلْغُلَامِ]{.ar},
the ;mudafil;
[ٱلْغُلَامِ]{.ar}
is in the ;istate;.

There is some dispute with regard to what element governs the ;mudafil;.
The obvious contender is the ;mudaf;, ([كِتَاب]{.ar}) since apparently it _causes_ the ;mudafil; to be in the ;istate;.
However, some grammarians disliked the idea of a noun being a governor and so they have provided altenate theories.^[@owens_foundations_grammar@ §9.2.2.2.5 242--243]
But for our purposes, we can ignore those theories and consider the ;mudaf; to govern the ;mudafil;.

## Nested sentences



## Word-order of the governor and its governee

By default, the governor will precede its governee.
For example:

(@sentence-zayd-beat-3amr) [ضَرَبَ زَيْدٌ عَمْرًا]{.ar}  
    "Zayd beat [#eamr]{.trn2}."

In example (@sentence-zayd-beat-3amr) above,
the governing verb
[ضَرَبَ]{.ar}
precedes its governees:
the ;faa3il;
[زَيْدٌ]{.ar},
and the ;mafulb;
[عَمْرًا]{.ar}.

However, this order is often varied in order to convey a desired meaning.
For example:

(@sentence-zayd-beat-3amr-object-first) [عَمْرًا ضَرَبَ زَيْدٌ]{.ar}  
    "Zayd beat _[#eamr]{.trn2}_."

In example (@sentence-zayd-beat-3amr-object-first) above,
the ;mafulb;
[عَمْرًا]{.ar}
has been placed before its governor
[ضَرَبَ]{.ar},
possibly to emphasize it.

This varying of the order of the words of the sentence is subject to certain rules, depending on:

* the type of the governor (whether it is a verb, or a verbal noun, etc.)
* the type of the governee (whether it is a preposition, or an adverb, etc.)
* the desired meaning of the expression.

We will discuss
the word-order rules for some governees here.
For new types of governees, we will discuss their word-order in their respective chapters, ;ia;.
And we will discuss sentence word-order generally in chapter\ (ref) ;ia;.

TODO: move to word order chapter:

(@) [ضرب موسى عيسى]

(@) [اشترى كمثرى موسى]{.ar}

(@) [وضرب ليلى عيسى]{.ar}

@nahw_wafi@ 2/54

### Word order of the ;mudafil; ;ma3mul; and its ;mudaf; ;3aamil;

Must be directly followed

### Word order of the preposition and its governee

Must be directly followed

### Word order of the preposition and its governor

<!--
As a general tendency, a governor will typically precede its governee(s) in sentence word order.
This is rule is more strict for some governor-governee relationships than for others.
-->
A prepositional phrase may freely precede its governor.^[@nahw_wafi@ 2/444A]
This may be done for a number of purposes:

##### To limit and particularize the effect of the governor to the noun following the preposition.^[@maani_nahw@ 3/121] {.unnumbered}

For example:

(@) [وَمِنْهُ تَفَجَّرُ أَنْهَارُ الْجَنَّةِ]{.ar}
    [@https://sunnah.com/bukhari:2790@]{.citex}  
    "and from it originate the rivers of Paradise"

(@) [وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ]{.ar}
    [@https://quran.com/3/122@ cited by @maani_nahw@ 3/121]{.citex}  
    "and upon Allāh the believers should rely."  

##### For drawing attention to the noun following the preposition^[@maani_nahw@ 3/121] {.unnumbered}

(@) [وَٱللَّهُ بِمَا تَعْمَلُونَ خَبِيرٌ]{.ar}
    [@https://quran.com/3/180@ cited by @maani_nahw@ 3/123]{.citex}  
    "And Allāh, of what you do, is [fully] Aware."

(@) [أَلِهَـٰذَا جَمَعْتَنَا]{.ar}
    [@https://sunnah.com/bukhari:4770@]{.citex}  
    "Is it for _this_ (that) you have gathered us?"

(@) [وَبِٱلْأَسْحَارِ هُمْ يَسْتَغْفِرُونَ]{.ar}
    [@https://quran.com/51/18@]{.citex}  
    "And in the hours before dawn they would ask forgiveness"  
    (The prepositional phrase [بِٱلْأَسْحَارِ]{.ar} is placed not just before its governor in the ;xabar; [يَسْتَغْفِرُونَ]{.ar}, but also before the ;mubtada; [هُمْ]{.ar}.)


When governing the preposition (and also the adverbs of time and place (section\ ref)),
the placement of the governee is especially flexible.^[@radiy_kafiyah@ 1/289D--290A]
We will see, in sections\ (refs) ;ia; that the governee, in this case,
are permitted to be placed where other types of governees are not.

TODO: Add content to:

* [إِنَّ]{.ar} and its sisters: ibn_aqil 1/278 fn; 1/349
* [كَانَ]{.ar} and its sisters [كان زيد آكلا طعامك]{.ar}
* [#HijAzi]{.trn2} [مَا]{.ar}:  sharh uthaymeen 22/4 ([مكا بي أنت معينا]{.ar})

<!--
When the prepositional phrase (and adverb of time and place) is governed by the ;xabar;
of a ;mubtada;-;xabar; sentence,
then
the prepositional phrase may even precede the ;mubtada;.
For example,


It is rare, or even impermissible, for other types of governees of the ;xabar; to precede the ;mubtada;.
(See the discussion on (@some-ref) [عمرا زيد ضرب]{.ar} in section\ (ref).)

In fact, when the governor of the prepositional phrase (and adverb of time and place) is the ;xabar;
of [إِنَّ]{.ar} (or its sisters),
or of [كَانَ]{.ar} (or its sisters),
or of the [#HijAzi]{.trn2} [مَا]{.ar},
even
then may the prepositional phrase be placed before the subject.
This latitude is expressly granted only to prepositional phrases and adverbs of time and place,
and not to other types of governees.
Examples:
-->

### Word-order of the ;mafulb; and its governor

Consider example (@sentence-zayd-beat-3amr) again:

(@sentence-zayd-beat-3amr) [ضَرَبَ زَيْدٌ عَمْرًا]{.ar}  
    "Zayd beat [#eamr]{.trn2}."

There are six possible permutations of word-order of the above example.

...

(@) [عمرا زيد ضرب]{.ar}

In examples ... the ;maful; [عمرا]{.ar} precedes its governor [ضرب]{.ar}.
This is generally permitted for stylistic (?) aspects, as we will discuss in chapter (ref).

Lets consider exaple ... in more detail.
This is because the ;maful; is governed by ضرب in the ;xabar;. 
But it precedes, not just its ;3aamil; but also the ;mubtada; of the outer sentence.
This is normal for some types of governees (like the prep).
But for the mafulb some grammarians consider it impermissible.
Others allow it, but consider it rare or weak in its structure.


@peled_sentence_types@ considers this dubious or unattested. Search for OSV in the text. However, others consider it permissible (search sabban, batalyusi for this sentence).

### Word-order of the ;faa3il; and its governor

### Word-order of the ;mubtada; and the ;xabar;

## Notes

### [ما وعدتنا على رسلك]{.ar}

@https://tafsir.app/ibn-aashoor/3/194@

::: {.ar}
ولَمّا سَألُوا المَثُوبَةَ في الدُّنْيا والآخِرَةِ تَرَقَّوْا في السُّؤالِ إلى طَلَبِ تَحْقِيقِ المَثُوبَةِ، فَقالُوا ﴿وآتِنا ما وعَدْتَنا عَلى رُسُلِكَ﴾ .
وتَحْتَمِلُ كَلِمَةُ (عَلى) أنْ تَكُونَ لِتَعْدِيَةِ فِعْلِ الوَعْدِ، ومَعْناها التَّعْلِيلُ فَيَكُونُ الرُّسُلُ هُمُ المَوْعُودُ عَلَيْهِمْ، ومَعْنى الوَعْدِ عَلى الرُّسُلِ أنَّهُ وعْدٌ عَلى تَصْدِيقِهِمْ فَتَعَيَّنَ تَقْدِيرُ مُضافٍ، وتَحْتَمِلُ أنْ تَكُونَ (عَلى) ظَرْفًا مُسْتَقِرًّا، أيْ وعْدًا كائِنًا عَلى رُسُلِكَ أيْ، مُنَزَّلًا عَلَيْهِمْ، ومُتَعَلِّقُ الجارِّ في مِثْلِهِ كَوْنٌ غَيْرُ عامٍّ بَلْ هو كَوْنٌ خاصٌّ، ولا ضَيْرَ في ذَلِكَ إذا قامَتِ القَرِينَةُ، ومَعْنى (عَلى) حِينَئِذٍ الِاسْتِعْلاءُ المَجازِيُّ، أوْ تُجْعَلُ (عَلى) ظَرْفًا مُسْتَقِرًّا حالًا مِن ﴿ما وعَدْتَنا﴾ أيْضًا، بِتَقْدِيرِ كَوْنٍ عامٍّ لَكِنْ مَعَ تَقْدِيرِ مُضافٍ إلى رُسُلِكَ، أيْ عَلى ألْسِنَةِ رُسُلِكَ.
:::

Abu Hayyan cites al-Zamakhshari who allows [على رسلك]{.ar} to be governed by a deleted محمول or منزل.
But Abu Hayyan does not like this permissibility because according to him the deleted 3aamil can only be general beingness.

Ibn 3aashoor, however, has no problem with it:

@https://tafsir.app/albahr-almuheet/3/194@

::: {.ar}
وقَوْلُهُ: ﴿عَلى رُسُلِكَ﴾ هو عَلى حَذْفِ مُضافٍ، فَقَدَّرَهُ الطَّبَرِيُّ وابْنُ عَطِيَّةَ: عَلى ألْسِنَةِ رُسُلِكَ. وقَدَّرَهُ الزَّمَخْشَرِيُّ: عَلى تَصْدِيقِ رُسُلِكَ. قالَ: فَـ(عَلى) هَذِهِ صِلَةٌ لِلْوَعْدِ في قَوْلِكَ: وعَدَ اللَّهُ الجَنَّةَ عَلى الطّاعَةِ. والمَعْنى: ما وعَدْتَنا عَلى تَصْدِيقِ رُسُلِكَ. ألا تَراهُ كَيْفَ أتْبَعَ ذِكْرَ المُنادِي لِلْإيمانِ وهو الرَّسُولُ، وقَوْلُهُ: (آمَنّا) وهو التَّصْدِيقُ. ويَجُوزُ أنْ يَكُونَ مُتَعَلِّقًا بِمَحْذُوفٍ، أيْ: ما وعَدْتَنا مُنْزِلًا عَلى رُسُلِكَ، أوْ مَحْمُولًا عَلى رُسُلِكَ؛ لِأنَّ الرُّسُلَ يَحْمِلُونَ ذَلِكَ، فَإنَّما عَلَيْهِ ما حُمِّلَ. انْتَهى. وهَذا الوَجْهُ الَّذِي ذَكَرَ آخِرًا أنَّهُ يَجُوزُ لَيْسَ بِجائِزٍ؛ لِأنَّ مِن قَواعِدِ النَّحْوِيِّينَ أنَّ الجارَّ والمَجْرُورَ والظَّرْفَ مَتى كانَ العامِلُ فِيهِما مُقَيَّدًا، فَلا بُدَّ مِن ذِكْرِ ذَلِكَ العامِلِ، ولا يَجُوزُ حَذْفُهُ، ولا يُحْذَفُ العامِلُ إلّا إذا كانَ كَوْنًا مُطْلَقًا. مِثالُ ذَلِكَ: زَيْدٌ ضاحِكٌ في الدّارِ، لا يَجُوزُ حَذْفُ ضاحِكٌ ألْبَتَّةَ. وإذا قُلْتَ: زِيدٌ في الدّارِ فالعامِلُ كَوْنٌ مُطْلَقٌ يُحْذَفُ. وكَذَلِكَ: زِيدٌ ناجٍ مِن بَنِي تَمِيمٍ، لا يَجُوزُ حَذْفُ ناجٍ. ولَوْ قُلْتَ: زِيدٌ مِن بَنِي تَمِيمٍ؛ جازَ عَلى تَقْدِيرِ: كائِنٌ مِن بَنِي تَمِيمٍ، والمَحْذُوفُ فِيما جَوَّزَهُ الزَّمَخْشَرِيُّ، وهو قَوْلُهُ: مُنْزَلًا أوْ مَحْمُولًا، لا يَجُوزُ حَذْفُهُ عَلى ما تَقَرَّرَ في عِلْمِ النَّحْوِ.
وإذا كانَ العامِلُ في الظَّرْفِ أوِ المَجْرُورِ مُقَيَّدًا صارَ ذَلِكَ الظَّرْفُ أوِ المَجْرُورُ ناقِصًا، فَلا يَجُوزُ أنْ يَقَعَ صِلَةً، ولا خَبَرًا لا في الحالِ، ولا في الأصْلِ، ولا صِفَةً، ولا حالًا.
:::

## The two 3umdah elements of a sentence

1. A grammatically complete sentence requires two ;3umdah; elements:

    i. The muxbar3
   ii. The muxbar

   The muxbar3 is main 3umdah element.
   It signifies whom sentence is about.
   The muxbar provides some information about the muxbar3.

   For example:

   zaydun rajulun
   zaydun qaa'imun
   qaama zaydun

## fadlah elements

In addition to the two 3umdah elements, a sentence may have additional fadlah elements

## The two types of sentences

2. There are two types of sentences:

    i. The doer sentence. 
       In this sentence, the muxbar3 is a doer. It is put in the ustate by a preceding verbal element.
   ii. The subject sentence.
       In this sentence, the muxbar3 is not a doer.


### Assigning the 3umdah elements

From the above description, there is an functional aspect in assigning the muxbar and the muxbar3.^[peled 111--112]
...

But we strictly define:
given/new
def/indef

Sometimes, it is not immediately clear from the functional aspect, who should be the muxbar3 and who should be the muxbar.

## Introduction

In this chapter, we will study the Arabic grammatical model for constructing sentences.
We will first define some linguistic terms.

### Truth-evaluability

Statements are classified into two types:

 i. a ;xabari; statement
ii. a ;inshai; statement

A _;xabari;_ statement is one that can be judged to be true or false.
In other words it is falsifiable.
For example, if we have a statement:

(@) zaydun qaaimun

The above statement may be judged to have a truth value.
If zayd is actually standing, then the statement is true.
And if zayd is not standing, then the statement is false.

A _;inshai;_ statement,
on the other hand,
does not have a truth value.
Here are some examples of ;inshai; statements:

(@) iDribh zaydan

(@) laa taf3al

(@) O zayd

(@) man huwa?


### Syntax, semantics, and pragmatics

#### Syntax {.unnumbered}

Syntax is the study of how words combine to form phrases and sentences.^[wiki]
It deals with the grammatical relationships between the words in a sentence.
For example, consider the adjectival noun kabIr.
When it is by itself, we cannot speak of any of its syntax.
But when it is in a linguistic environment, like a phrase or a sentence,
then its syntactical role is determined by the grammatical relationships it has with other words in the sentence.

Consider the following sentence:

(@) albaytu kabir

In the above sentence, kabIr is _syntactically_ a ;xabar;.

Now consider this example:

(@) daxala baytan kabIran

In example () kabIr is syntactically a ;na3t;.
In both examples, the meaning of kabIr is exactly the same.

#### Semantics {.unnumbered}

Semantics is the study of the meanings of words.
Consider the following sentence:

(@) taHaddatha fi al-bayt.

Here the semantic meaning of fi determines the meaning of the sentence.
If fi means "in" then the sentence means "He talked in the house."
And if fi means "regarding", then the sentence means "He talked about the house."

Semantics can affect the syntax of a sentence.

(@) al-af3Alu Hasanatun  
    "The acts are good."

(@) al-af3Alu HasanAtun  
    "The acts are good deeds."


#### Pragmatics {.unnumbered}

Pragmatics is the study of what sentences mean in context, and with regard to needs of the speaker and the listener.

<!--
#### Functional aspects {.unnumbered}

Semantics and pragmatics
-->


## The theory of government

A sentence in Arabic is constituted from elements.
An element is a noun, a verb, or a particle.
Of these elements, some have the quality of state.
These are called _stateful_ elements.
The stateful elements are nouns and ;mudarie; verbs.
A noun may be either in the ;ustate;, ;astate;, or ;istate;.
And a ;mudarie; verb may be either in the ;ustate;, ;astate;, or ;0state;.
The theory of government states that a stateful element is put in a particular state by a governor.
For example:

(@3amal_in_house) fii al-daari

In the above example,
<!--
the particle fii is the governor of the noun al-daari.
The noun al-daar is the governee of its governor fii.
-->
the governor fii governs its governee al-daar in the ;istate;.
We say that
the preposition fii is the governor of ;istate; noun al-daar because it is the reason or cause of the noun al-daar being in the ;istate;.

Here is another example:

(@3amal_zayd_beat_3amr) Daraba zaydun eamran.

In this example, the governor is the verb Daraba.
It has two governees:
the ;faa3il; zayd,
and the ;mafulb; eamr.
The governor Daraba governs the ;faa3il; zayd in the ;ustate;
and it governs the ;mafulb; in the ;astate;.

#### A governee can only have one governor  {.unnumbered}

From example (@3amal_zayd_beat_3amr),
you can see that one goveror may govern multiple governees.
However, one governee cannot be be governed by multiple governors.
In other words, there can be only one governor that causes a stateful element to be in a particular state.

#### The word-order of a governor and its governee(s)  {.unnumbered}

From the above examples,
you can see that a governor typically occurs before its governees in word-order.
For some governor-governee relationships, this word-order is obligatory,
like in example (@3amal_in_house).
For other governor-governee relationships, this word-order is more flexible.
For example, the ;maful; may occur before its governing verb, thus:

(@3amal_3amran_Daraba_zaydun) eamran Daraba zaydun

<!--
But the ;faa3il; must always follow its governing verb.
So that is another example of an obligatory word-order for the governor and the governee.
-->

#### Some elements are not governed {.unnumbered}

Not every element in a sentence is governed by a governor.
For example, the ;madi; verb has not state, and thus, no governor.

## Some common governees

prep-istate

mudaf-istate

verb-faa3il

verb-mafulb

na3t

## The two ;3umdah; elements of a sentence

In the Arabic grammatical model,
a sentence requires two ;3umdah; elements
in order to be grammatically complete.
These two ;3umdah; elements are:

 i. The ;muxbar3;
ii. The ;muxbar;

The ;muxbar3; represents whom the sentence is about, i.e. it's topic.
<!--
And the ;muxbar; is meant to provide some interesting comment about the ;muxbar3;.
-->
And the ;muxbar; expresses some property about the ;muxbar3; that completes the meaning of the sentence.
Here are some examples:

(@3amal_zayd_qaimun) zaydun qaaimun

DIAGRAM

In example (@3amal_zayd_qaaimun) zaydun qaaimun above,
zayd is the ;muxbar3;. It is the topic of the sentence.
And qaaimun is the ;muxbar;. It is a comment on the topic, giving us some information about zayd.

We have previously referred to this type of sentence as a ;j_ism;.
In this ;j_ism; the ;mubtada; is the ;muxbar3;,
and the ;xabar; is the ;muxbar;.

(@3amal_qaama_zaydun) qaama zaydun

DIAGRAM

In example (@3amal_zayd_qaaimun) zaydun qaaimun above,
zayd is the ;muxbar3;. It is the topic of the sentence.
And qaama is the ;muxbar;. It is a comment on the topic.

We have previously referred to this type of sentence as a ;j_f3l;.
In this ;j_f3l; the verb is the ;muxbar;,
and the ;faa3il; is the ;muxbar3;.
We will see later, ;ia; that 
in a ;j_f3l;
the ;muxbar; may sometimes be another element, instead of the verb that governs the ;faa3il;.


## Initial government

Besides the two ;3umdah; elements,
a sentence also needs an initial government.[Owens §2.3.6.1 54]
<!--
The initial governor governs the highest governing element(s) of the two ;3umdah; elements of the sentence.
-->
<!--
The initial governor is the source of all government in the sentence.
-->
Initial government is any and all government prior to, and until, the first governed ;3umdah; element.

#### One of the two ;3umdah; elements as the initial governor {.unnumbered}

In some sentences, the intitial governor may be one of the two ;3umdah; elements.
For example:

(@) pahaba zaydun

DIAGRAM

In the above example, the initial governor is the verb pahaba.
The madi verb has no state and needs no governor.
So it is itself, the initial governor.

#### An internal non-;3umdah; element as the initial governor {.unnumbered}

The intitial governor may be internal to the sentence but not one of the two ;3umdah; elements.
For example:

(@) lam yaDrib al-rajulu gulAma zaydin
    [owens §2.2.3 (16) 41]

DIAGRAM

(@) inna

(@) kaana



#### The abstract initial governor {.unnumbered}

Very commonly, the initial governor is not an actual word, but only an abstract concept.
When there is one or more stateful ;3umdah; elements in a sentence with no overt (i.e. observable) governor,
then this necessitates bringing in a _abstract_ initial governor.[ owens 55; peled 88 fn 7]
For example:

(@) zaydun muntaliqun

The abstract initial governor governs both the ;muxbar3; (the ;mubtada; zayd),
and the ;muxbar; (the ;xabar; muntaliqun) in the ;ustate;.

(@) yaphabu zaydun

The abstract initial governor governs both the ;muxbar; (the ;mudarie; verb yaphabu) in the ;ustate;.
And, as usual, the verb yaphabu governs its ;faa3il; zaydun (the ;muxbar3;) in the ;ustate;.

#### An external element as the initial governor {.unnumbered}

Sometimes, it is possible for an element that is external to the sentence under question, to be its initial governor.
We will learn moe about this case in sections\ (ref) and (ref) below.

<!--
(@) zaydun DAribun abUhu eamran

DIAGRAM

This is an example of a nested sentence.
We will study these types of sentences in more detail in later sections, ;ia;.
For now, we will give a brief overview specific to this example.

In the above example, the smaller sentence is
DAribun abUhu eamran
"His father is beating eamr."
The ;ism_fail; DAribun governs the its ;faa3il; abUhu,
and its ;mafulb; 3amr.
(Remember from section\ (ref) that an ;ism_fail; may have a ;faa3il; and a ;mafulb;.)
But DAribun is a stateful element that itself needs a governor.
It is put in the ;ustate; because it is the ;xabar; of the ;mubtada; zaydun.
by the conceptual governor that governs the larger sentence.

(@) inna zaydan DAribun eamran

DIAGRAM

This is an example of a nested sentence.
We will study these types of sentences in more detail in later sections, ;ia;.
For now, we will give a brief overview specific to this example.

In the above example,
the initial governor is the particle inna.
It governs its ;ism_of; zaydun in the ;astate;.
And it governs its ;xabar; DAribun in the ;ustate;.
However, its ;xabar; 
the smaller sentence is
DAribun eamran
"He is beating eamr."
The ;ism_fail; DAribun governs
and its ;mafulb; 3amr,
(and also its implied ;faa3il; "he").
(Remember from section\ (ref) that an ;ism_fail; may have a ;faa3il; and a ;mafulb;.)
But DAribun is a stateful element that itself needs a governor.
It is put in the ;ustate; because it is the ;xabar; of the initial governor inna.
-->

<!--
(@) kāna Zaydun munṭaliqan ʾabūhu
    [peled 207 citing zajjaji]{.citex}

DIAGRAM

This is an example of a nested sentence.
We will study these types of sentences in more detail in later sections, ;ia;.
For now, we will give a brief overview specific to this example.

In the above example,
the initial governor of the outer sentence is the verb kaana.
It governs its ;faa3il; zaydun in the ;ustate;.
And it governs its ;xabar; muntaliqan in the ;astate;.
However,
muntaliqan and its ;faa3il; abUhu
also constitute a sentence by themselves.
This is the inner sentence within the outer sentence.
This inner sentence 
muntaliqan abuhu
has two ;3umdah; elements: 
the ;ism_fail; muntaliq,
and its ;faa3il; abUhu.
(Remember from section\ (ref) that an ;ism_fail; can have a ;faa3il;)
muntaliq governs abUhu.
But muntaliq itself is also governed by an initial governor (the verb kaana) that is not in this inner sentence.
-->

#### More than one initial governor {.unnumbered}

Sometimes, there may be more than one initial governor in a chain, before one reaches the first governed ;3umdah; element.
For example:

(@) lam yakun 

## #;fadlah; elements

A ;fadlah; element is any stateful element in a sentence that is not either of the ;3umdah; elements,
but is governed,
directly or indirectly,
by any one of the ;3umdah; elements.
By the way,
when we say _;fadlah;_,
we mean that it is ;fadlah; in the sense that it is not required to complete the sentence _grammatically_.
We don't mean that it is superfluous in terms of its meaning.
In fact, a ;fadlah; element may be essential for the correct meaning of the sentence.
For example, consider the ;ayah;:

(@) [لاعبين]{.ar}
    [ cited by maani_nahw]{.citex}


[لاعبين]{.ar} is a ;hal; (see in chapter\ (ref)),
which is a ;fadlah; element.
If we remove it from the sentence,
then the sentence will be complete grammatically but it will have an incorrect meaning.

We will discuss some of the ;fadlah; elements below:

#### The ;astate; governees of a verb {.unnumbered}

The most prominent ;fadlah; elements are 
all ;astate; elements that a verb governs.
These include:

* the ;mafulb;
* the ;mmutlaq; (see chapter\ (ref))
* the ;dharf_zaman; and the ;dharf_makan; (see chapter\ (ref))
* the ;mafull; (see chapter\ (ref))
* the ;mafulm; (see chapter\ (ref))
* the ;hal; (see chapter\ (ref))
* the ;tamyiz; (see chapter\ (ref))

The ;mafulb; is usually a ;fadlah; element.
In most sentences, if we remove the ;mafulb; the sentence remains grammatically complete.
For example:

However, if a verb is semantically deficient,
like for kaana and its sisters (see chapter\ (ref)),
then its ;mafulb;(s) may become an ;3umdah; element.
For example:

(@) kaana zaydun  qaa'iman  
          doer    mafulb  
          muxbar3 muxbar  

DIAGRAM

We will discuss this in more detail in section\ (ref) below and also in chapter\ (ref), ;ia;.

#### The ;mudafil; in an ;idaafah; {.unnumbered}

Technically,
the ;mudafil; in an ;idaafah; is considered a ;fadlah; unit.
Consider the following example:

(@) abU zaydin axU eamrin

If we remove the ;mudafil; nouns from the sentence we get:

(@) al-abu al-axu

This is a complete sentence.
al-abu is the ;mubtada;.
And al-axu is the ;xabar; (the ;muxbar;).

However, for convenience, we will often (loosely) treat
the annexation as one unit.
So we may say that the ;mubtada; is
abu zaydin
and that the ;muxbar; is axu 3amr.

#### The ;tabi3;s {.unnumbered}

The ;tabi3;s are considered ;fadlah; elements.
These include:

* The ;na3t; (see chapter\ (ref))
* The ;badal; (see chapter\ (ref))
* The ;tawkeed; (see chapter\ (ref))
* The ;3atf_bayan; (see chapter\ (ref))


## The anchoring element

In addition to the ;3umdah; elements, and the initial governor,
some, but not all, sentences also require a _anchoring_ element [peled 140].
The anchoring element serves as an anchor to start the sentence and justify its structure.
It may either be a part of the sentence or external to it.
The anchoring element, when needed, cannot be either of the two ;3umdah; elements.
Rather, it must precede the two ;3umdah; elements in word-order.
Here are some examples:

(@) aqaaimun zaydun

In this example, the anchoring element is the question particle 'a'.
It allows us to order the sentence as 'qaaimun zaydun'.
Without it, the normal order would have been zaydun qaaimun.

(@) Zaydun munṭaliqun ʾabūhu
    [peled 207 citing zajjaji]{.citex}

In this example, the noun zaydun is the anchoring element to the inner sentence
muntaliqun abuhu.
By itself, the sentence muntaliqun abuhu, though grammatically correct, wouldn't typically be used.
The preceding noun Zayd is not part of the inner sentence muntaliqun abuhu.
Yet it serves as its anchoring element.

Not all sentences require an anchoring element.
Here are examples of sentences which do not require an anchoring element:

(@) zaydun qaaimun

(@) yantaliqu abUhu

## The two types of sentences

There are two types of sentences in the Arabic grammatical model:

 i. The ;j_ism;
ii. The ;j_f3l;

We have previously defined the two types of sentences thus:

A _;j_ism;_ typically begins with a noun. It has a ;mubtada; and a ;xabar;.
A _;j_f3l;_ begins with a verb.

These definitions lack some rigor.
We will attempt to refine these definitions below:

<!--
::: {#def-j_f3l}

In a ;j_f3l; the ;muxbar3; is a ;faa3il;.
It must be preceded and governed by the ;muxbar;.
The ;muxbar; may be either a verb, or a verb-like noun that is allowed to govern a ;faa3il;.

:::

::: {#def-j_ism}

In a ;j_ism; the ;muxbar3; is not a ;faa3il;. It is called the ;mubtada;.
The ;muxbar; is called the ;xabar;. It may be either a noun, or an inner sentence.

:::
-->

#### The ;j_f3l; {.unnumbered}

A _;j_f3l;_ has a ;faa3il; as its ;muxbar3;.
<!--
In a _;j_f3l;_,
the ;muxbar3; is a _;faa3il;_
-->
The ;faa3il; is preceded by its governor.
The ;faa3il;'s governor may either be a verb, or a verb-like noun that can govern a ;faa3il;.
<!--
the ;muxbar3; shall be a _;faa3il;_.
The ;faa3il;'s governor shall precede the ;faa3il; and be internal to the sentence.
The ;faa3il;'s governor shall be either a verb, or a verb-like noun that is allowed to govern a ;faa3il;.
-->

In a _;j_f3l;_,
the ;faa3il;'s governor will often, but not always, be the ;muxbar; of the sentence.
If the ;faa3il;'s governor is not meaningfully sufficient to be the ;muxbar;,
then it will, in its stead, also govern a
_;xabar;_ (as the ;muxbar;) in order to complete the sentence grammatically.
<!--
then a _;xabar;_ is required as the ;muxbar; to complete the sentence grammatically.
-->
<!--
sufficiently express a  the ;muxbar3;, then the sentence shall require a another element, the _;xabar;_, to be the ;muxbar;.
If the ;faa3il;'s governor is not the ;muxbar;, then the sentence shall require a another element, the _;xabar;_, to be the ;muxbar;.
-->

#### The ;j_ism; {.unnumbered}

The _;j_ism;_ does not have a ;faa3il; as its ;muxbar3;.
<!--
In a _;j_ism;_ the ;muxbar3; shall not be a ;faa3il;.
The ;muxbar3; shall not governed by a verb or a verb-like noun as a ;faa3il;.
The ;muxbar3; is called the _;mubtada;_ of its governor.
-->
The ;muxbar3; is a noun governed by an initial governor.
The ;muxbar3; will require a _;xabar;_ as the ;muxbar;.


We will also define the ;xabar;:

#### The ;xabar; {.unnumbered}

The _;xabar;_, when required, shall fulfil the role of the ;muxbar; of a sentence.
<!--
The ;xabar; may be either a noun, or an inner sentence.
-->
The ;xabar; is,
in principle,
a noun.
But an inner sentence may occur _in the place_^[Peled 91 citing ibn abi l-rabI3] of the ;xabar;.


<!--
From the above definitions we can infer the following:

::: {#cor-verb-sentence}

The verb can only occur, with its ;faa3il;, in a ;j_f3l; sentence.

:::
-->

Let's go through some examples and try to classify them according to the above definitions.

(@) lam yaphab zaydun

(@) kaana zaydun qaa'iman

(@) eamran daraba zaydun

## Determining the ;muxbar3; and the ;muxbar;


<!--
In a ;j_f3l;, determining the ;muxbar3; and the ;muxbar; is relatively straightforward.
The ;muxbar3; is the ;faa3il; and the ;muxbar; is the element which completes the sentence by expresses a property about the ;muxbar3;.
However, in a ;j_ism; determining the ;muxbar3; and the ;muxbar; can be a little complicated.
-->
The terms
;muxbar3;,
;muxbar;,
;faa3il;,
;3aamil;,
;xabar;,
etc.
are syntatical terms.
But they are determined using syntax, semantics, and pragmatics.

In terms of pragmatics, the ;muxbar3; and the ;muxbar; represent 'given' and 'new' information.
That is, the listener knows who the ;muxbar3; is and can identify him or it. So the ;muxbar3; is a 'given' to the listener.
And the speaker is providing 'new' information about the ;muxbar3; to the listener.

For example:

(@) ana tamimiyyun

In the above example, the listener already knows who the ;muxbar3; ("I") is.
And the speaker is providing new information (via the ;muxbar; "tamimiyyun") about the ;muxbar3; to the listener.
This new information is that the ;muxbar3; "is a Tamimi".

If we reverse the order of words in the sentence thus:

(@) tamimiyyun ana

then the ;muxbar3; and the ;muxbar; remain the same.
The ;muxbar3; is ana because that is 'given' information to the listener.
And the ;muxbar; is tamimiyyun becayse that represents 'new' information for the listener.

<!--
So much for the pragmatic perspective.

From the perspective of grammar, the ;muxbar3; and the ;muxbar; are determined 
first using syntactical rules, then with semantic considerations, and finally (only when needed) using pragmatics.

Usually the synactico-semantic perspective will align with the pragmatic perspective.
But sometimes they may mis-align.
-->

Sometimes, what is pragmatically the topic of sentence, may not align with the syntactic ;muxbar3;.
Consider for example, the following sentence:

(@) zaydan ra'aytu
    [peled 28]{.citex}

Pragmatically, it may seem that zayd is the topic of the sentence because it is whom the sentence is about.
But actually zayd is the ;mafulb; of a semantically complete verb ra'A.
So zayd is a ;fadlah; element.
Stripping the sentence of the ;fadlah; elements, we are left with ra'aytu.
This is a ;j_f3l;.
The ;muxbar3; is the ;faa3il; (the pronoun tu "I").
And the ;muxbar3; is the verb ra'A.

Determining the ;muxbar3; and the ;muxbar; in a ;j_f3l; is relatively straightforward, as in example () above.
In the case of a ;j_ism; this determination can be more complicated.
We will discuss it below:

### Determining the ;mubtada; and the ;xabar; in a ;j_ism;

If the ;j_ism; has a word as the initial governor, then determining the ;mubtada; and the ;xabar; is easy.
For example:

(@) fainna Hasbaka Allah
    [@https://quran.com/8/62]{.citex}

If the initial governor is abstract then the situation can be more tricky.
Regarding the definiteness of the two ;3umdah; elements,
there are three possibilities:

  i. One is definite and the other is indefinite.
 ii. Both are definite.
iii. Both are indefinite.

#### One ;3umdah; element is definite and the other is indefinite {.unnumbered}

The first case (where one ;3umdah; element is definite and the other is indefinite) is the basic and most common case.
The definite element is typically taken as the ;mubtada; and the indefinite element is taken as the ;xabar;.^[Peled 87]
This falls in line with the pragmatic perspective which we outlined above.
The definite element represents the 'given' information, which the listener already knows.
And the indefinite element represents 'new' information.

We already gave the example () ana tamimiyyun above.
ana is definite so it is the ;mubtada;.
And tamimiyyun is indefinite so it is the ;xabar;.
This assignment holds even if we change the order to () tamimiyyun ana.

In special cases, some grammarians hold that it is possible to have an indefinite ;mubtada; and a definite ;xabar;.
One special case is when a question noun is the ;mubtada;.
(Question nouns are considered indefinite.)
For example:

(@) [كَمْ مَالُكَ]{.ar}
    [sabban citing sibawayhi]{.citex}  

(@) [أَيُّ لَيْلَةٍ لَيْلَةُ الْقَدْرِ]{.ar}
    [@https://sunnah.com/tirmidhi:3513@]{.citex}  
    “Which night is the night of Decree”

Another special case is when the ;mubtada; is an indefinite ;af3al; in sentences like:

(@) xayrun minka zaydun
    [sabban citing sibawayhi]{.citex}  

In the above sentence, afDalu is considered the ;mubtada; of the sentence.
Typically, an indefinite comparative noun would be a ;xabar; instead of a ;mubtada;.
For example: zaydun xayrun minka.
But imagine a scenario where someone says:
3amrun xayrun minni.
In response to this, another person may reply
xayrun minka zaydun.
The given information is xayrun minka.
And the new information is zayd.

Besides these two special cases,
there are words like
Hasb, naHw, mivl, etc.
Remember from section\ (ref) that these words (exceptionally) remain indefinite when annexed to a definite noun.
So, for example, these words (as ;mudaf;s to definite ;mudafil;s) may be used as ;na3t;s to an indefinite noun.
For example:

(@) [مررت برجل حسبك من رجل]{.ar}
    [@ibn_hisham_awdah_almasaalik@ 3/139]{.ar}

There is some debate amongst the grammarians with regards to whether these indefinite noun may occur as a ;mubtada; to a definite ;xabar;.^[Sabban sharh ashmooni 1/277]
So if we have a sentence: 

(@) [حسبُك زَيْدٌ]{.ar}

then one may deem zayd as the ;mubtada; because it is more definite than hasbuka.

But see also the ;tafsir;s of the following ;ayah;s:

(@) faHasbuhu jahannamu

(@) Hasbuhum jahannamu yaSlawnahA

#### Both ;3umdah; elements are definite {.unnumbered}

When both ;3umdah; elements are definite, then typically the first is the ;mubtada; and the second is the ;xabar;.
For example:

(@) al-dInu al-naSIHatu

However, if it is known from context that one if the two elements is the 'given' information and the other is the 'new' information, then the given information will be the ;mubtada; and the new information will be the ;xabar;, regardless of word-order.^[ibn_aqil 1/233, maani_nahw 1/ta3reef al mutdada wal xabar]

For example, consider a situation where one wishes to say that Abu Yusuf is [like] Abu Hanifa.
(Imam Abu Yusuf was the foremost student of Imam Abu Hanifa.)
The normal way to express this sentence is:

(@) Abu Yusuf Abu Hanifa.

DIAGRAM

However, if the speaker and the listener know that Abu Yusuf is the topic of the conversation then Abu Yusuf is the given information.
And likening him to Abu Hanifa is the new information which then speaker is giving to the listener.
With the pragamatic knowledge that the listener would know what he means,
the speaker may choose, for stylistic reasons, to place the ;xabar; (Abu Hanifa) before the ;mubtada; (Abu Yusuf)

(@) Abu Hanifa Abu Yusuf 

DIAGRAM

#### Both ;3umdah; elements are indefinite {.unnumbered}

What we have said regarding both ;3umdah; elements being indefinite also holds for when both ;3umdah; elements are indefinite.
In this case, however, given that both elements are indefinite, it may be more difficult to establish that one is the 'given' information, and the other is the 'new' information.
So the ;mubtada; will likely precede the ;xabar;.
For example:

(@) [أفضل من زيد أفضل من عمرو]{.ar}
    [ibn_aqil 1/232]{.citex}  

Peled 87.

Sabban 1/277  
<https://shamela.ws/book/11539/274>

ibn_aqil 1/233

ibn uthaymeen sharh alfiyyah (search for ibn al-qayyin ibn taymiyyah)

[اإلخبار عن النكرة بالمعرفة في القرآن الكريم د. محمد دلوم]{.ar}
<https://asjp.cerist.dz/en/downArticle/312/6/1/100540>

## The compound sentence

<!--
In the definition of the ;xabar;
(section\ (ref) above)
we mentioned that the ;xabar; is,
in principle,
a noun.
But an inner sentence may occur _in the place_^[Peled 91 citing ibn abi l-rabI3] of the ;xabar;.
-->

Consider the sentence:

(@) yaqUmu zaydun

This is a simple ;j_f3l;.
zaydun is the ;faa3il; and
yaqUmu is its governor.

The word-order in () yaqoomu zaydun is the normal word-order that we would employ.
But we can also flip the word-order and say:

(@) zaydun yaqoomu

We will discuss the reasons for changing the normal word-order in more detail in chapter\ (Word-order).
For now, we will simply discuss the grammar of the new sentence.
The new sentence () zaydun yaqoom is actually no longer a simple ;j_f3l;.

Why? Because the word-order of a ;faa3il; and it's governor is strictly fixed in the Arabic grammatical model.
The ;faa3il;'s governor must precede it.
So zaydun cannot be a ;faa3il; of yaqoom.
But yaqoom is a verb, and a verb needs a ;faa3il;
The ;faa3il; of yaqoom is the ;mustatir; singular masculine pronoun (signifying "he") within the verb.
So yaqoom, by itself, is a complete ;j_f3l;.
So what, then, is Zayd?
Zayd is the ;mubtada; of a sentence, whose ;xabar; is the ;j_ism; yaqoom.

DIAGRAM

So we can see that we have
a _compound_ sentence,
consisting of
an outer sentence and an inner sentence.
A compound sentence is one that has a ;xabar; that is itself a sentence.
As opposed to compound sentences, a _simple_ sentence is one that does not contain another sentence within it.
<!--
The inner sentence is _nested_ in the outer sentence.
-->

::: {.callout-note}
Simply changing the word-order in a sentence (when permitted)
can result in a different grammar for the new sentence, compared to the original sentence.
This is a very important observation and we will make use of it later, ;ia;.
:::

### What is valid as an outer sentence

The outer sentence is often a ;j_ism; as in example () zaydun yaqoom.
But it is also possible for the outer sentence to be a ;j_f3l;.
For example:

(@) kaana zaydun yaktubu

DIAGRAM

We will study compound sentences that start with kaana in more detail in chapter\ (ref).

<!--
#### Composing a compound sentence {.unnumbered}

In example () zaydun yaqoom we created a compound sentence by flipping the word order of an original sentence.
But this is not the only way or reason to create compound sentences.
A compound sentence may be composed without being flipped from an original.
For example:
-->

### What is valid as an inner sentence

#### Both the ;j_ism; and the ;j_f3l; are valid {.unnumbered}

The ;xabar; of the outer sentence
may be either a ;j_f3l; (as in example () above),
or a ;j_ism;, as in the following example:

(@) [زيد أبوه قائم]{.ar}
    [@abu_hayyan_tadhyeel@ 4/26]{.citex}

#### A ;xabari; sentence is valid {.unnumbered}

The ;xabar; is always the ;muxbar; of a sentence.
And the ;muxbar; is defined as expressing some property about the ;muxbar3;.
This property that  the ;xabar; expresses is usually ;xabari;.
For example,
in the sentence
<!--
zaydun qaaim
qaaim is the ;xabar; (and thus ;muxbar;).
The property that the ;xabar; (qaaim) expresses about zayd that he is standing.
-->
zaydun yaqoom
the inner sentence yaqoom is ;xabari;.

<!--
But this rule of expressing a property about the ;muxbar3; is relaxed for a ;xabar;s that is an inner sentence.
-->
#### A ;inshai; sentence is valid {.unnumbered}

The property that the ;xabar; expresses about the ;muxbar3; need not always be ;xabari;
(although it usually is).
Consider, for example, the simple sentence:

(@3amal_where_is_3amr) [أين عمرو؟]{.ar}
    [@abu_hayyan_tadhyeel@ 4/27]{.citex}  
    "Where is [#eamr]{.trn2}?"

The ;xabar; [أَيْنَ]{.ar} of the simple sentence in example (@3amal_where_is_3amr) above is not ;xabari;.^[@abu_hayyan_tadhyeel@ 4/27]{.citex}  
Yet the sentence is perfectly valid.

<!--
Similarly, 
a simple sentence, as a whole, need not be ;xabari;.
Consider, for example, the simple sentence:

(@) [أَيُّ رَجُلٍ أَخُوكَ]{.ar}
    [ibn_3usfoor_sharh_jumal 1/347]{.citex}

The entire simple sentence in example () above is not ;xabari;.^[ibn_3usfoor_sharh_jumal 1/347;]
-->
Therefore, an inner sentence, which is the ;xabar; of a compound sentence, need not be ;xabari; either.^[ibn_3usfoor_sharh_jumal 1/347; @abu_hayyan_tadhyeel@ 4/27]
So we can say:

(@) zaydun iDribhu

(@) zaydun hal darabtahu

[Ibn Abi -r-RabI3, BasIT 706]{.citex}

In examples () and () above, the inner sentence ;xabar;s are ;inshai;.
But they are valid as a ;xabar; for their outer sentences,
and due to them,
the outer sentences are grammatically complete.

#### Invalid inner sentences {.unnumbered}

Some sentences, however, are not valid as inner sentences:

* A sentence beginning with lAkin, HattA, or bal is not valid.^[@abu_hayyan_tadhyeel@ 4/28]
* A vocative sentence is not valid.^[@abu_hayyan_tadhyeel@ 4/28]
  So. we cannot say, for example:

  (@) ;x; [زيد يا أخاه]{.ar}
      [@abu_hayyan_tadhyeel@ 4/28]{.citex}  
      "Zayd: O his brother."

### The ;rabt; between the inner and outer sentence

It is usually necessary for there to be a ;rabt; between the inner sentence, and the ;mubtada; of the outer sentence.
This ;rabt; is typically supplied by a pronoun.
Let's look at some examples:

(@) [زَيْدٌ قَامَ أَبُوهُ]{.ar}
    [jurjani_muqtasid 1/278]{.citex}  

DIAGRAM

In example () above, the ;rabt; is the pronoun [هُ]{.ar} in abuuhu.

(@) [زَيْدٌ قَامَ]{.ar}
    [jurjani_muqtasid 1/278]{.citex}  

DIAGRAM

In example () above, the ;rabt; is the implied singular masculine pronoun that is the ;faa3il; of qaama.

Generally, if there is no such ;rabt; between the inner sentence and the ;mubtada; of the outer sentence,
then the compound sentence is invalid.
So we cannot say, for example:

(@) ;x; Zaydun qāma ʿAmrun  
    [peled 94 citing ibn ya3eesh; jurjani_muqtasid 1/279]{.citex}

#### A ;ism_isharah; as the ;rabt; {.unnumbered}

Instead of a pronoun,
an ;ism_isharah; may serve as the ;rabt;.
For example:

(@) [وَلِبَاسُ التَّقْوَى ذَلِكَ خَيْرٌ]{.ar}
    [cited by ibn_uthaymeen_sharh 17/2, ibn_aqil 1/204]{.citex}  

#### A repeated ;mubtada; as the ;rabt; {.unnumbered}

The ;mubtada; of the outer sentence may be repeated in the inner sentence, and this is sufficient as the ;rabt;.
For example:

(@) [الْحَاقَّةُ * مَا الْحَاقَّةُ]{.ar}
    [cited by ibn_uthaymeen_sharh 17/2, ibn_aqil 1/204]{.citex}  

#### No need for the ;rabt; {.unnumbered}

In cases where the ;xabar; of the outer sentence is more general than its ;mubtada; a ;rabt; is not needed.
For example:

(@) zaydun ni3ma al-rajulu
    [@wright@ 2/256D, ibn_aqil 1/204]{.citex}

The ;rabt; is also not needed when the ;mubtada; of the outer sentence and its ;xabar; are perfectly identical in meaning.
For example:

(@) [نطقي الله حسبي]{.ar}
    [@wright@ 2/256D, ibn_aqil 1/204]{.citex}

(@) [قولي لا إله إلا الله]{.ar}
    [@wright@ 2/256D, ibn_aqil 1/204]{.citex}

#### An implied ;rabt; {.unnumbered}

The ;rabt;, even when technically required, is sometimes omitted.
But it remains implied.
This is in cases in which the sense is perfectly clear without it.^[@wright@ 2/256B]
For example:

(@) [ٱلسَّمْنُ مَنَوَانِ بِدِرْهَمٍ]{.ar}  
    [@wright@ 2/256C; jurjani_muqtasid 1/278; radiyy 1/238]{.citex}  
    (The sentence with the ;rabt; restored is [ٱلسَّمْنُ مَنَوَانِ مِنْهُ بِدِرْهَمٍ]{.ar} "two [manA]{.trn2}s _of it_ for a dirham.")

## The pronoun of the fact

<!--

(@) zaydun muntaliqun  
    Zayd is setting out.

The word muntaliqun is the ;xabar;.
We can replace the word muntaliqun with the ;j_f3l;
yantaliqu "he sets out."

(@) zaydun yantaliqu
    Zayd sets out.

Now we have _nested_ sentences which consists of two sentences:
 i. The inner sentence yantaliqu, which 
    is a ;j_f3l; sentence, consisting of the verb and the implied ;faa3il; "he".
ii. The outer sentence which is a ;j_ism;.
    The ;mubtada; of the outer sentence is the noun zaydun.
    And the ;xabar; of the outer sentence is the inner sentence.

The ;xabar; is,
in principle,
a noun.
But an inner sentence may occur,
as in the example above,
in its stead.

### Purpose of using a nested sentence

A sentence is used as a ;xabar; to contain more information than it would be to convey in a single word.


(@) ;x; Zaydun qāma ʿAmrun  
    [peled 94 citing ibn ya3eesh]{.citex}

;3aaid; can be substituted [peled 94]
-->

## [قَائِمٌ زَيْدٌ]{.ar}

In this section we will make extensive use of the example:

(@3amal_qaaimun_zaydun) [قَائِمٌ زَيْدٌ]{.ar}  
    "Standing is Zayd."

Example (@3amal_qaaimun_zaydun) above represents a much discussed structure in Arabic sentence theory.
It presented a serious challenge to the grammarians' theory of government and sentence types.^[Peled 122]

### [قَائِمٌ زَيْدٌ]{.ar} analyzed as a ;j_ism;

The normal word-order for expressing this sentence is:

(@3amal_zaydun_qaaimun) [زَيْدٌ قَائِمٌ]{.ar}  
    "Zayd is standing."

DIAGRAM

But the word-order of the sentence is flipped in example (@3amal_qaaimun_zaydun) [قَائِمٌ زَيْدٌ]{.ar}.
Again, we will discuss the stylistic reasons for changing the word-order in chapter\ (ref).
In this particular case, 
a speaker may choose to say (@3amal_qaaimun_zaydun) [قَائِمٌ زَيْدٌ]{.ar} 
instead of the more normal (@3amal_zaydun_qaaimun) [زَيْدٌ قَائِمٌ]{.ar}
when the listener is under an incorrect impression that Zayd is sitting.^[@maani_nahw@ 1/[المبتدأ الذي له مرفوع أغني عن الخبر]{.ar}]

Anyway, for now, let's focus on the grammar of the sentence, once the word-order has been changed.
Now, we know from section\ () above that changing the order of words in a sentence (when permitted)
can result in a different grammar for the new sentence, compared to the original sentence.

As a matter of fact, for this particular sentence,
the grammatical parsing of the flipped sentence can be the same as the original sentence:

DIAGRAM

So if we change the gender or number of the ;mubtada;,
then the gender and number of the ;xabar; will also be changed to match it.
For example:

(@) [قَائِمَةٌ هِنْدٌ]{.ar}  
    "Hind is standing."

<!--
(@) [قَائِمَانِ ٱلزَّيْدَانِ]{.ar}  
    "The (two) Zayds are standing."
-->

(@) [مَا قَائِمُونَ ٱلزَّيْدَونَ]{.ar}  
    "The Zayds are not standing."

(@) [أَقَائِمَتَانِ ٱلْهِنْدَانِ]{.ar}  
    "Are the (two) Hinds standing?"

So far so good.
Now let's get to the more problematic analysis:

### [قَائِمٌ زَيْدٌ]{.ar} analyzed as a ;j_f3l;

Sometimes a flipped sentence of this sort is anchored to a preceding anchoring element
(see section\ (ref) above).
For example,

(@) [أَقَائِمٌ زَيْدٌ]{.ar}  
    "Is Zayd standing?"
    (The question particle [أَ]{.ar} is the anchoring element.)

(@) [مَا قَائِمٌ زَيْدٌ]{.ar}  
    "Zayd is not standing."
    (The negative particle [مَا]{.ar} is the anchoring element.)

The anchoring element is usually a question particle 
or a negative particle^[Peled 143]
(as in examples () and () above).
But we will see in section\ (overlapping sentences) below, that it may even be an element of a previous sentence.

Now, with this anchoring element,
another grammatical parsing is possible.^[Peled 140]
The ;ism_fail;
[قَائِمٌ]{.ar}
is a verb-like noun.
In fact, it is the closest of the ;mushtaqq; nouns to the ;mudarie; verb [يَقُومُ]{.ar}.^[Peled 122]
This resemblance of the ;ism_fail; to the verb allows it to
serve as the governor of the ;muxbar3;
its ;faa3il;.
And the ;muxbar3;
[زَيْدٌ]{.ar}
can now parsed as a ;faa3il;.
And the sentence becomes a ;j_f3l;.

As for the governor of the (stateful) ;muxbar;
[قَائِمٌ]{.ar},
it is governed by an abstract governor,
just as if it had been the ;mudarie; verb [يَقُومُ]{.ar}.

DIAGRAM

The proof of this analysis is that when
<!--
the ;faa3il; ;muxbar3; is feminized,
its governor is feminized to match it.

And if the 
-->
the ;faa3il; ;muxbar3; is dualized or pluralized,
its governor remains in the singular,
just like for a verb:

(@) [أَقَائِمٌ ٱلزَّيْدَانِ]{.ar}  
    "Are the (two) Zayds standing?"

(@) [مَا قَائِمٌ ٱلزَّيْدُونَ]{.ar}  
    "The Zayds are not standing."

By the way, if
the ;faa3il; ;muxbar3; is feminized,
its governor would be feminized to match it.
This too would be done for actual verbs.
For example:

(@) [أَقَائِمَةٌ ٱلْهِنْدَانِ]{.ar}  
    "Are the (two) Hinds standing?"

<!--
So according to the ;j_f3l; analysis of (@3amal_qaaimun_zaydun) [قَائِمٌ زَيْدٌ]{.ar},
the ;muxbar3; 
[زَيْدٌ]{.ar}.
is a ;faa3il; governed by
[قَائِمٌ]{.ar}.
But the question remains:
[قَائِمٌ]{.ar}
is a stateful element in the ;ustate;;
so who is its governor?
The answer is:
[قَائِمٌ]{.ar}
is governed by an abstract governor, just as if it had been an actual verb like [يَقُومُ]{.ar}.

DIAGRAM
aqaaimun zaydun
ayaqoomu zaydun
-->

<!--
By the way, the flipped word-order sentence (@3amal_qaaimun_zaydun) [قَائِمٌ زَيْدٌ]{.ar}
is not 
would require a anchoring element
-->

### Traditional analysis of [قَائِمٌ ٱلزَّيْدَانِ]{.ar}

Traditionally, grammarians have analyzed this challenging sentence as a kind of hybrid sentence
that has aspects of both a ;j_ism; and a ;j_f3l;.
According to this mainstream view,
[قَائِمٌ]{.ar}
is a ;mubtada;,
and
[ٱلزَّيْدَانِ]{.ar}
is a ;faa3il;
"substituting for the ;xabar;."^[Peled 143 citing ibn_aqil 1/189 and Carter]
However, not all grammarians agreed with this mainstream view.^[Peled 143 citing astarabadi 1/225]

As for us, we have attempted to make this kind of sentence fit within the Arabic grammatical model
by defining the ;j_f3l; in a way that it may begin with a verb-like noun.

### TODO: Add ;ism_maful; + ;naib; ;faa3il;

## Overlapping sentences

Also at the edge of the Arabic grammatical model is what we will call
the case of overlapping sentences.
This is when last (stateful) element of one sentence serves as the first element of the next sentence.
In other words, the sentence has an external initial governor
(see section\ (ref) above).
It also utilizes the kind of analysis which we developed for the sentence
[قَائِمٌ زَيْدٌ]{.ar}.

Let's say we wish to express the meaning,
"Zayd's father were setting out."
The normal way to express this in Arabic would be:

(@) kaana abU zaydin munTaliqan

Now, for pragmatic, or stylistic reasons, we wish to make Zayd the topic of the sentence.
One way to do this could be to make
make Zayd the ;ism_of; of kaana.
The ;ism_fail; muntaliq is now assigned to be the ;xabar; of kaana thus:

(@) kaana zaydun muntaliqan

But wait!
Example () above is saying that Zayd was setting out, not his father.
And where is his father anyway?
What we'll do is consider the ;ism_fail;
muntaliqan
to be a verb-like noun that can govern a ;faa3il;.
And we'll add Zayd's father as the ;faa3il; of the ;ism_fail; thus:

(@) kaana zaydun muntaliqan abawaahu

DIAGRAM

Even though
the _overlapping element_
muntaliqan
is part of the first sentence
(as its ;xabar;),
its meaning applies to the second sentence.
So it is not Zayd who is setting out, but his father.

#### The ;rabt; between the overlapping sentences {.unnumbered}

Note that,
just like in the case of the compound sentence,
overlapping sentences also require a ;rabt; in the second sentence
that points back to the first sentence.
In example () above, the ;rabt; is the pronoun [ه]{.ar} in [أَبُوهُ]{.ar}, that points back to Zayd.
However,
But this ;rabt; does not necessarily point back to the ;muxbar3; of the first sentence.
It will point back to the _original_ referent of the overlapping element.
That is, the referent of the overlapping element, had the second sentence not been there.
It example () above,
if the second sentence had not been there,
the overlapping element
muntaliqan
would refer to
zayd.
So the ;rabt; points back to zayd.

In this sentence
the original referent
of the 
overlapping element
also happens to be the ;muxbar3; of the first sentence.
But in section\ (ref) below, we will see cases where it need not be so.

#### The anchoring element for the overlapping element {.unnumbered}

By the way, remember in section\ (ref) above,
we said that the verb-like noun can govern a ;faa3il; when anchored by an anchoring element.
For overlapping sentences, the overlapping element is the verb-like noun.
It is anchored by its being a syntactical part of the first sentence.
In our example,
muntaliqan
is anchored by bain a ;xabar; of the first sentence
kaana zaydun muntaliqan.^[But see also peled 208]

#### The effect of gender and number on the overlapping element {.unnumbered}

Just like in section\ (ref) above,
the verb-like noun that is the overlapping element will remain in the singular,
regardless of the number of its ;faa3il;,
or of the number of its original referent.
It will however modify for gender to match the gender of the ;faa3il;.

Here are examples of some possibilities:

(@) kāna l-Zaydāni munṭaliqan ʾabawāhumā
    [Peled 208]{.citex}

(@) kāna l-Zaydūna ḥisānan ʾābāʾuhum
    [Peled 208 fn]{.citex}

(@) kāna zaydun munṭaliqan ʾabawāhumā

(@) kāna l-Zaydāni munṭaliqan mu3allimuhuma

(@) kānat hindun munṭaliqan abUhu

(@) kānat hindun munṭaliqatan UmmuhA

(@) kānat alhindAni munṭaliqatan UmmAhumA

(@) kānat alhindAni munṭaliqan AbawAhu

#### A non-overlapping compound sentence to express the same meaning {.unnumbered}

Instead of using an overlapping sentence, we could also have used a compound sentence to express the same meaning:

(@) kaana zaydun muntaliqun abUhu
    [Peled 208]{.citex}

Here muntaliqun abUhu is an inner sentence with a fronted ;xabar;
And the inner sentence is the ;xabar; of the outer sentence.^[See Peled 209 fn 35]
DIAGRAM

If we were to change the number of the inner sentence's ;mubtada; then its ;xabar; would follow suit:

(@) kāna al-Zaydāni munṭaliqāni ʾabawāhumā
    [Peled 208]{.citex}

(@) kāna zaydun munṭaliqāni ʾabawāhumā

## The overlapping ;na3t;

Overlapping sentences are very common for one particular case,
called the _overlapping ;na3t;_.
Consider the following example:

(@) [رَأَيْتُ رَجُلًا حَسَنًا أَخُوهُ]{.ar}
    [@wright@ 2/283C]  
    "I saw a man [whose] brother is handsome."

This is a case of overlapping sentences.
The word
[حَسَنًا]{.ar}
is originally a ;na3t;
for the ;manut;
[رَجُلًا]{.ar}
in the first sentence.
But it is also the overlapping element that begins the second sentence
and serves as the governing verb-like noun for the ;faa3il;
[أَخُوهُ]{.ar}.

DIAGRAM

Note that,
as we mentioned above,
the ;rabt;,
which is the pronoun [ه]{.ar} in 
[أَخُوهُ]{.ar},
doesn't point to the ;muxbar3; of the first sentence
(which is the pronoun [تُ]{.ar} ("I") in
[رَأَيْتُ]{.ar}).
Rather, it points to the _original_ referent of the overlapping element,
i.e. whom the overlapping element
[حَسَنًا]{.ar}
would be referring to, if the second sentence were not there.
In this case it is the original ;manut;
[رَجُلًا]{.ar}.

We already know that a ;na3t; must match its ;manut; in four aspects:

  i. number
 ii. gender
iii. state
 iv. definiteness

As for number,
because the ;na3t; is acting as a verb and governing an expressed ;faa3il;
it will remain in the singular
regardless of the number of its ;faa3il;,
or of the number of its original referent.

And as for gender, the ;na3t; will match the ;faa3il;, not the original referent.
This is because, again, it is acting as a verb and a verb matches its ;faa3il; in gender.

But as for state,
then a (stateful i.e. ;mudarie;) verb's state is not governed by its ;faa3il;.
Since the overlapping member is part of the first sentence,
it will be governed (in its state) by whatever would govern it, if the second sentence were not there.
In the case of a ;na3t;,
we learned in section\ (ref) above,
that it is governed by the governor of its ;manut;.
So the overlapping member will match its original referent in state.

And as for definiteness,
then a real verb has no definiteness.
So here too it will match its original referent, i.e., the original ;manut;.

Here are some examples of overlapping ;na3t;s:

(@) [جَاءَنِي رَجُلٌ حَسَنٌ أَخُوهُ]{.ar}
    [@wright@ 2/283B]

...

[فاقع لونها]{.ar}

[القرية الظالم أهلها]{.ar}

[سَائِغٌ شَرَابُهُ]{.ar}

## Substituting nouns with sentences

The ;xabar; of a sentence is, in principle, a noun.
However, we saw in section\ (ref) above,
that a sentence may occur in place of it.
This formed a compound sentence.

This substitution of sentences in place a noun can be done for other syntactical elements as well.
We will discuss some of these cases here.

### A sentence as the ;na3t;

### A sentence as the ;mudafil; in an ;idaafah;

## Notes

### Word order

maani_nahw ([تعريف المبتدأ والخبر]{.ar}) vol. 1

ibn_aqil 1/233

ibn uthaymeen sharh alfiyyah (search for ibn al-qayyin ibn taymiyyah)



