# The ;participle; as a verb-like governor

## Introduction

The verb is the basic, and strongest, governor of a ;faa3il; or ;maful;.
#;mushtaqq; nouns, because they are derived from the verb, can also govern in a verb-like manner.
In this chapter
we will discuss the rules of how such nouns may act as verb-like governors.

## The ;ism_fail; as a verb-like governor

The ;ism_fail; is the closest of the ;mushtaqq; nouns to the verb,
and thus the strongest of the ;mushtaqq; nouns in its capacity to act as a verb-like governor.

Consider the following sentence:

(@3amal_mush_zaydun_yaqoomu) [زَيْدٌ يَقُومُ]{.ar}  
    [Zayd -- he stands]{.trans}

As we know from chapter\ (ref),
this is a compound sentence.
[زَيْدٌ]{.ar} is the ;mubtada; of an outer sentence.
The ;xabar; of the outer sentence is the inner sentence
[يَقُومُ]{.ar}.

Instead of using the ;mudarie; verb
[يَقُومُ]{.ar},
we can use its ;ism_fail;
[قَائِم]{.ar}, thus:

(@3amal_mush_zaydun_qaaimun) [زَيْدٌ قَائِمٌ]{.ar}  
    [Zayd is standing]{.trans}

As you can see,
we have translated the ;mudarie; verb
[يَقُومُ]{.ar} as [stands]{.trans}
and the ;ism_fail;
[قَائِم]{.ar} as [standing]{.trans}.
We will discuss the difference in meaning between the ;mudarie; verb and the ;ism_fail; in more detail in chapter\ (ref), ;ia;.
For now, we will focus on the grammar of the two sentences.

There is one notable similarity between the grammar of examples (@3amal_mush_zaydun_yaqoomu) and (@3amal_mush_zaydun_qaaimun),
and one notable difference:

##### The similarity {.unnumbered}

The
;mudarie; verb
[يَقُومُ]{.ar},
and the ;ism_fail;
[قَائِمٌ]{.ar}
both govern
a ;mustatir; ;faa3il; pronoun,
implicated as [[هُوَ]{.ar}].

##### The difference {.unnumbered}

The ;mudarie; verb
[يَقُومُ]{.ar}
and its ;mustatir; ;faa3il; pronoun 
[[هُوَ]{.ar}]
are complementary ;3umdah; elements that
constitute a complete sentence.
The 
;mustatir; ;faa3il; pronoun 
[[هُوَ]{.ar}]
is the ;muxbar3;
and
the ;mudarie; verb
[يَقُومُ]{.ar}
is the ;muxbar;.
The sentence formed by
the ;mudarie; verb
[يَقُومُ]{.ar}
and its ;mustatir; ;faa3il; pronoun 
[[هُوَ]{.ar}]
is in place of a ;ustate; noun as the ;xabar; of the ;mubtada;
([زَيْدٌ]{.ar})
of the outer sentence.

On the other hand,
and the ;ism_fail;
[قَائِمٌ]{.ar}
and its
;mustatir; ;faa3il; pronoun 
[[هُوَ]{.ar}]
are _not_ complementary ;3umdah; elements.
Rather,
[قَائِمٌ]{.ar} (as the ;muxbar;)
and
[زَيْدٌ]{.ar}
(as the ;muxbar3;)
are complementary ;3umdah; elements.
This is a simple sentence,
not a compound sentence.
The ;mustatir; ;faa3il; pronoun
[[هُوَ]{.ar}] is not the ;3umdah; element of any sentence.
But,
despite being
;fadlah; from the perspective of sentence completion,
the ;mustatir; ;faa3il; pronoun
is an essential governee of the ;ism_fail;.

Let's take a look at another example:

(@) [رَأَيْتُ رَجُلًا قَائِمًا]{.ar}  
    [I saw a standing man.]{.trans}

The ;3umdah; elements of this sentence are 
[رَأَيْتُ]{.ar}: the verb [رَأَى]{.ar} and its ;faa3il; pronoun [تُ]{.ar}.
The entire phrase
[رَجُلًا قَائِمًا]{.ar} has only ;fadlah; elements.
[قَائِمًا]{.ar} is a ;na3t; of [رَجُلًا]{.ar}, governed by the verb [رَأَى]{.ar}.
The ;ism_fail;
[قَائِمًا]{.ar} has a ;mustatir; ;faa3il; pronoun
[[هُوَ]{.ar}] that refers back to [رَجُلًا]{.ar}.
But because 
[قَائِمًا]{.ar} is a (;fadlah;) element of an existing sentence
(whose ;3umdah; elements are [رَأَيْتُ]{.ar}),
therefore it cannot be the ;3umdah; ;muxbar; of a new sentence with its ;mustatir; ;faa3il; pronoun 
[[هُوَ]{.ar}].

So, as you can see, whenever the ;ism_fail; has a ;mustatir; ;faa3il; pronoun,
that ;faa3il; pronoun is not the ;muxbar3; of any sentence.
This is because the ;ism_fail;, as a single element, is already a member of an existing sentence.

In contrast, a verb always forms a sentence (as the ;muxbar;) with its ;faa3il; (as the ;muxbar3;).
If we replace the ;ism_fail; [قَائِمًا]{.ar} with the verb [يَقُومُ]{.ar} thus:

(@) [رَأَيْتُ رَجُلًا **يَقُومُ**]{.ar}  

then [يَقُومُ]{.ar} is a complete sentence with the verb and its ;mustatir; ;faa3il; pronoun as ;3umdah; elements.
This complete sentence is the ;na3t; of [رَجُلًا]{.ar}.

## The ;ism_fail; as the governor of a ;mustatir; ;faa3il; pronoun

Let us look into the
;mustatir; ;faa3il; pronoun of the ;ism_fail; in more detail.
It makes sense for a verb to have a ;faa3il; but how can a noun have a ;faa3il;?
The reason is that the ;ism_fail;,
because of its closeness to the verb,
can act like one.
When acting with verbal force,
it can govern a ;faa3il;.
It can also, as we will see soon, ;ia;,
govern a ;mafulb;.

The ;faa3il; of the ;ism_fail; is,
by default,
a ;mustatir; pronoun.
And it refers back to a referent that occurs before it.
In example (@3amal_mush_zaydun_qaaimun) [زَيْدٌ قَائِمٌ]{.ar}
the ;faa3il; of the ;ism_fail;
[قَائِمٌ]{.ar}
is the ;mustatir; pronoun [[هُوَ]{.ar}].
And the referent of this ;faa3il; pronoun is the ;mubtada; [زَيْدٌ]{.ar}.

DIAGRAM

Let's see another example:

(@) [صَاحَ الرَّجُلُ الْقَائِمُ]{.ar}  
    [The standing man shouted.]{.trans}

then [الْقَائِمُ]{.ar} governs a ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}], that refers back to [الرَّجُلُ]{.ar}.

The fact that the ;ism_fail; has a ;mustatir; ;faa3il; pronoun
is,
in fact,
the reason why a ;ism_fail; in the ;xabar; will match the ;mubtada; in gender.^[[Non-agreement of Mubtada and Khabar](https://drvaniya.com/wp-content/uploads/2016/12/Q33-Non-agreement-of-Mubtada-and-Khabar.pdf)]

For example, if we say:

(@) [هِنْدٌ قَائِمَةٌ]{.ar}  
    [Hind is standing.]{.trans}

then the feminine marker [ة]{.ar} is added to the ;ism_fail; [قَائِم]{.ar} only because it has to match the feminine gender of the ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}] that occurs with, and is governed by, the ;ism_fail;.
(The ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}] refers back to [هِنْد]{.ar}.)

When the referent of the ;mustatir; ;faa3il; pronoun changes for number or gender,
then the ;mustatir; ;faa3il; pronoun will change to match it.
For example:

(@3amal_mush_zaydaan_qaaimaan) [الزَّيْدَانِ قَائِمَانِ]{.ar}
    [[@sabban@ 1/291](https://shamela.ws/book/11539/288#p1)]{.citex}  
    [The two Zayds are standing.]{.trans}

(@3amal_mush_zaydoon_qaaimoon) [الزَّيْدُونَ قَائِمُونَ]{.ar}
    [[@sabban@ 1/291](https://shamela.ws/book/11539/288#p1)]{.citex}  
    [The Zayds are standing.]{.trans}

In example (@3amal_mush_zaydaan_qaaimaan) above,
the ;mustatir; ;faa3il; pronoun of [قَائِمَانِ]{.ar} is implicated as [هُمَا]{.ar}.

And in example (@3amal_mush_zaydoon_qaaimoon) 
the ;mustatir; ;faa3il; pronoun of [قَائِمُونَ]{.ar} is implicated as [هُمْ]{.ar}.

As a point of technicality,
the alif in the dual suffix of [قَائِمَانِ]{.ar} and the [و]{.ar} in the plural suffix of [قَائِمُونَ]{.ar}, are not themselves the ;faa3il; pronouns.^[haazimi 30/5 <https://shamela.ws/book/36130/531>]
Rather, the ;faa3il; pronouns for the ;ism_fail;s above are ;mustatir;.

This is different than for verbs.
In the verbs
[يَقُومَانِ]{.ar} and [يَقُومُونَ]{.ar},
the alif in [انِ]{.ar} and the [و]{.ar} in [ونَ]{.ar} are, themselves, considered the ;faa3il; pronouns.
And these pronouns are _;zaahir;_, not ;mustatir;.

## The ;ism_fail; as the governor of a ;mafulb;

We have seen that the ;ism_fail;,
when acting with verbal force, governs a ;faa3il;.
In a similar manner,
the ;ism_fail; for transitive verbs can, optionally, govern a ;mafulb;.
In order to introduce this behavior,
we use again, as our starting point, the ;ustate; ;mudarie; verb.
Consider the following example:

(@3amal_mush_zaydun_yadribu_3amran) [زَيْدٌ يَضْرِبُ عَمْرًا]{.ar}  
    [Zayd beats [#amr]{.trn2}]{.trans}

Example (@3amal_mush_zaydun_yadribu_3amran) above is parsed as follows:

* [زَيْدٌ]{.ar} is a ;mubtada;.
* [يَضْرِبُ]{.ar} is a ;mudarie; verb in the ;ustate;.
  It governs a ;mustatir; pronoun (implicated as [هُوَ]{.ar}) in the ;ustate; as its ;faa3il;. 
  The ;mustatir; ;faa3il; pronoun [هُوَ]{.ar} refers back to its referent: the ;mubtada; [زَيْدٌ]{.ar}.
* [عَمْرًا]{.ar} is a ;mafulb;, governed in the ;astate; by  the verb [يَضْرِبُ]{.ar}.
* [يَضْرِبُ عَمْرًا]{.ar} is an inner sentence which is in place of a ;ustate; noun as the ;xabar; of the ;mubtada; [زَيْدٌ]{.ar}.

Instead of using the verb [يَضْرِبُ]{.ar} in example (@3amal_mush_zaydun_yadribu_3amran) above
we may instead use its ;ism_fail;
[ضَارِب]{.ar}, thus:

(@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}  
    [Zayd is beating [#amr]{.trn2}]{.trans}

Example (@3amal_mush_zaydun_daaribun_3amran) is parsed as follows:

* [زَيْدٌ]{.ar} is a ;mubtada;.
* [ضَارِبٌ]{.ar} is the ;xabar; of the ;mubtada; [زَيْدٌ]{.ar}.
  It governs a ;mustatir; pronoun (implicated as [هُوَ]{.ar}) in the ;ustate; as its ;faa3il;. 
  The ;mustatir; ;faa3il; pronoun [هُوَ]{.ar} refers back to the ;mubtada; [زَيْدٌ]{.ar}.
* [عَمْرًا]{.ar} is a ;mafulb;, governed in the ;astate; by the ;ism_fail; [ضَارِبٌ]{.ar}.

As you can see,
the ;ism_fail;
[ضَارِبٌ]{.ar} can govern a ;mafulb; just like 
the verb [يَضْرِبُ]{.ar}.

However, while a transitive verb can govern a ;mafulb; unconditionally,
a ;ism_fail; can only govern a ;mafulb; if certain conditions are satisfied.
We will discuss these conditions in section\ (ref) below.

By the way,
we again highlight the difference in
the ;faa3il; of
the verb [يَضْرِبُ]{.ar}
vs 
the ;faa3il; of the ;ism_fail;
[ضَارِبٌ]{.ar}:
The verb [يَضْرِبُ]{.ar} and its ;faa3il; are complementary ;3umdah; pairs that constitute a complete sentence.
Whereas,
the ;ism_fail;
[ضَارِبٌ]{.ar} does not form a new sentence with its ;faa3il;.

### A ;ism_fail; defined by [ٱل]{.ar} as the governor of a ;mafulb;

Example (@3amal_mush_zaydun_daaribun_3amran) shows the government of a ;mafulb; by an ;ism_fail; that is not defined by [ٱل]{.ar}.
In a similar manner,
an ;ism_fail; that _is_ defined by [ٱل]{.ar}, can also govern a ;mafulb;.
For example:

(@hadha_aldaaribu_zaydan) [هَذَا الضَّارِبُ زَيْدًا]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/84](https://shamela.ws/book/13301/1448)]{.citex}  
    [This [person] is the beater of Zayd.]{.trans}

By the way, you my be wondering what is the difference between the sentence in example (@hadha_aldaaribu_zaydan) [هَذَا الضَّارِبُ زَيْدًا]{.ar} above,
and if we had used an ;idaafah; thus:

(@hadha_aldaaribu_zaydan) [هَذَا ضَارِبُ زَيْدٍ]{.ar}
    [This [person] is the beater of Zayd.]{.trans}

This is touched upon in section\ (ma3aani_ism_faa3il).

### Word order of the ;mafulb; and its governing ;ism_fail;

As with verbs, the ;mafulb; usually follows its governing ;ism_fail;
(as in the examples above).
But the ;mafulb; is allowed to precede its governing ;ism_fail;.
So we can say:

(@) [هذا زيدا ضارب]{.ar}
    [[@sirafi_sibawayhi@ 1/259](https://shamela.ws/book/17726/257)]{.citex}  
    [This [person] is beating Zayd.]{.trans}

While the ;mafulb; is permitted 
to precede its governing ;ism_fail;
(as above),
it is very common,
in such a case,
for a ;laam_taqwiya; to be used with an ;indir_mafulb; instead, thus:

(@) [هذا لِزيدٍ ضارب]{.ar}  
    [This [person], to Zayd, is beating.]{.trans}

(@) [لِلضَّيْفِ مُكْرِمٌ]{.ar}
    [@fischer@ 113]{.citex}  
    [to the guest, is honoring]{.trans}  
    (i.e. [honoring the guest]{.trans})  

The ;laam_taqwiya; is discussed in more detail in section\ (later chapter).^[See also @wright@ 2/69CD, @fischer@ §203 Note\ 2 p.\ 113 (who consider this ;laam_taqwiya; obligatory), and @nahw_wafi@ 2/475--476 (who doesn't consider it obligatory).]

TODO: Fronting the ;mafulb; is not permitted for ;sifah_mush;. See link in example above. Add to section on ;sifah_mush;

### A dual or plural ;ism_fail; as the governor of a ;mafulb;

A dual or plural ;ism_fail; may govern a ;mafulb; just like the singular.
So we can say:

(@) [هذان ضاربان زيدًا]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]{.citex}  
    [These two [persons] are beating Zayd.]{.trans}

(@) [هم ضاربون زيدًا]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]{.citex}  
    [These [persons] are beating Zayd.]{.trans}

(@) [الهندات ضاربات عمرا]{.ar}
    [[@sirafi_sibawayhi@ 1/439](https://shamela.ws/book/17726/437)]{.citex}  
    [The Hinds are beating [#eamr]{.trn2}.]{.trans}

#;ism_fail;s defined by [ٱل]{.ar} are again also permitted:

(@) [هذان الضاربان زيدا]{.ar}
    [[@sirafi_sibawayhi@ 2/40](https://shamela.ws/book/17726/538)]{.citex}  
    [These two are the beaters of Zayd.]{.trans}

(@) [هؤلاء الضاربون الرجل]{.ar}
    [[@sirafi_sibawayhi@ 2/40](https://shamela.ws/book/17726/538)]{.citex}  
    [These are the beaters of the man.]{.trans}

(@) [وَٱلۡمُقِیمِینَ ٱلصَّلَوٰةَۚ وَٱلۡمُؤۡتُونَ ٱلزَّكَوٰةَ]{.quran}
    [@https://quran.com/4/162@ cited by [@sirafi_sibawayhi@ 2/40](https://shamela.ws/book/17726/538)]{.citex}  
    [And the establishers of prayer [especially] and the givers of zakāh]{.trans}

For plurals, the sound plurals are more worthy of being used as verb-like governors^[[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]
as in the examples above.
However, broken plurals are permitted as well.
So we can say:

(@) [الزيدون ضُرّابٌ عمرًا]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]{.citex}  
    [The Zayds are beating [#eamr]{.trn2}.]{.trans}

(@) [الهِنْداتُ ضواربُ عَمْرًا]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]{.citex}  
    [The Hinds are beating [#eamr]{.trn2}.]{.trans}

Flexible word order is again permitted for the dual and the plural as it was for the singular:

(@) [الزيدان عمرا ضاربان]{.ar}
    [[@sirafi_sibawayhi@ 1/439](https://shamela.ws/book/17726/437)]{.citex}  
    [The two Zayds are beating [#eamr]{.trn2}.]{.trans}

(@) [الزيدون عَمْرًا ضُرّابٌ]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]{.citex}  
    [The Zayds are beating [#eamr]{.trn2}.]{.trans}

(@) [الهندات عمرا ضاربات]{.ar}
    [[@sirafi_sibawayhi@ 1/439](https://shamela.ws/book/17726/437)]{.citex}  
    [The Hinds are beating [#eamr]{.trn2}.]{.trans}

(@) [الهِنْداتُ عَمْرًا ضواربُ]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/97](https://shamela.ws/book/13301/1461#p1)]{.citex}  
    [The Hinds are beating [#eamr]{.trn2}.]{.trans}


## #;lafzi; ;idaafah;

#### #;lafzi; ;idaafah; used to eliminate ;tanwin; {.unnumbered}

Consider again the sentence:

(@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}  
    [zaydun DAribun 3amran]{.trn}  
    [Zayd is beating [#amr]{.trn2}]{.trans}

The ;ism_fail; 
[ضَارِبٌ]{.ar}
has a ;tanwin; which is pronounced before pronouncing the ;mafulb;
[عَمْرًا]{.ar}.
In an effort to make the pronunciation easier, this ;tanwin; is often eliminated and replaced with an ;idaafah;.
The ;mafulb; is then made into a ;mudafil; in the ;istate;.
The meaning remains the same.
So the above sentence then becomes:

(@) [زَيْدٌ ضَارِبُ عَمْرٍو]{.ar}  
    [zaydun DAribu 3amrin]{.trn}  
    [Zayd is beating [#amr]{.trn2}]{.trans}

This is called a ;lafzi; ;idaafah;, 
as opposed to a ;ma3nawi; ;idaafah;,
which is what we have been studying so far.
This is because it is only an ;idaafah; for the purposes of easing the pronunciation,
not in meaning.

By the way, the sentence
[زَيْدٌ ضَارِبُ عَمْرٍو]{.ar}
can also be a ;ma3nawi; ;idaafah;.
In which case, the meaning will be:
[Zayd is the beater of [#eamr]{.trn2}]{.trans}.
So if we come across such a sentence, how can we tell if it is a ;ma3nawi; ;idaafah; or a ;lafzi; ;idaafah;?
The answer is, in this case, context should guide us.
We will see below that the ;lafzi; ;idaafah; is not always identical in form to the ;ma3nawi; ;idaafah;.
So in those cases, the form of the ;idaafah; will tell us whether 
it is a ;ma3nawi; ;idaafah; or a ;lafzi; ;idaafah;.

Here are some more examples of a ;lafzi; ;idaafah; used to eliminate a ;tanwin;:

(@) [ضارباتُ عمرٍو]{.ar}
    [[@azhari_sharh_tasreeh@ 1/682](https://shamela.ws/book/9985/694)]{.citex}  
    [beating~f,3+~ [#eamr]{.trn2}]{.trans}  
    (instead of [ضارباتٌ عمرًا]{.ar})

In the case where the ;ism_fail; is ;diptote;, it will not have a ;tanwin;.
But the ;lafzi; ;idaafah; may still be used in such a case because a ;tanwin; would have been present if the word were ;triptote;.^[[@azhari_sharh_tasreeh@ 1/682](https://shamela.ws/book/9985/694)]
For example:

(@) [ضواربُ زيدٍ]{.ar}
    [[@azhari_sharh_tasreeh@ 1/682](https://shamela.ws/book/9985/694)]{.citex}  
    [beating~f,3+~ [#eamr]{.trn2}]{.trans}  
    (instead of [ضواربُ زيدًا]{.ar})

#### #;lafzi; ;idaafah; used to eliminate the [ن]{.ar} of a dual or plural suffix {.unnumbered}

The ;lafzi; ;idaafah; is used in situations when the governing ;ism_fail; has ;tanwin; (as above),
and also in situations when it ends with a [ن]{.ar} arising from a dual or sound plural.
Examples:

(@) [ضاربا زَيْدٍ]{.ar}
    [[@azhari_sharh_tasreeh@ 1/682](https://shamela.ws/book/9985/694)]{.citex}  
    [[two] beating Zayd]{.trans}  
    (instead of [ضاربانِ زَيْدًا]{.ar})

#### Definiteness of the ;lafzi; ;idaafah; {.unnumbered}

Because this is a ;lafzi; and not a ;ma3nawi; ;idaafah;,
the ;mudaf; 
is not made definite  by a definite ;mudafil;.
In the examples so far, the ;mudafil;s have been proper nouns 
([زَيْد]{.ar}, [عَمْرو]{.ar})
which are definite.
But the ;ism_fail;s
([ضَارِب]{.ar},
[ضَارِبَا]{.ar},
etc.)
remain indefinite, because they did not originally have [ٱل]{.ar} when governing a ;mafulb;.
This example proves the above claim:

(@3amal_mush_hadyan_baaligha_lka3bati) [هَدۡیَۢا بَـٰلِغَ ٱلۡكَعۡبَةِ]{.quran}
    [@https://quran.com/5/95@ cited by [@ibn_ya3ish_mufassal@ 4/84](https://shamela.ws/book/13301/1448)]{.citex}  
    [as an offering [to Allāh] delivered to the Kaʿbah]{.trans}

In  example (@3amal_mush_hadyan_baaligha_lka3bati) above,
the ;ism_fail;
[بَالِغ]{.ar} is a ;mudaf; to the definite ;mudafil; [الْكَعْبَة]{.ar}.
But this is a ;lafzi; ;idaafah;. So
[بَالِغ]{.ar}
does not become definite.
Therefore 
[بَالِغ]{.ar}
can be a ;na3t; to the indefinite 
[هَدْيًا]{.ar}.

If the ;ism_fail; is to be made definite in a ;lafzi; ;idaafah; then a [ٱل]{.ar} is added to it.
For example:

(@) [هذان الضاربا زيدٍ]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/132](https://shamela.ws/book/13301/582#p1)]{.citex}  
    [These two are the beaters of Zayd.]{.trans}  
    (instead of [هذان الضاربان زيدًا]{.ar})

(@) [وَٱلۡمُقِیمِی ٱلصَّلَوٰةِ]{.quran}
    [@https://quran.com/22/35@ cited by [@ibn_ya3ish_mufassal@ 2/132](https://shamela.ws/book/13301/582#p1)]{.citex}  
    [and the establishers of prayer]{.trans}

Adding [ٱل]{.ar} to the ;mudaf; is particular to a ;lafzi; ;idaafah;.
As we know, it is not permitted in a ;ma3nawi; ;idaafah;.
So when we see
[ٱل]{.ar} with a ;mudaf;, then we will know that the ;idaafah; has to be a ;lafzi; one.

#### When the ;ism_fail; does not have ;tanwin; or a suffixed [ن]{.ar} {.unnumbered}

Consider the following case of a ;ism_fail; governing a ;mafulb;:

(@) [الضَّارِبُ زَيْدًا]{.ar}  
    [the beater of Zayd]{.trans}  

There is no ;tanwin; of suffixed [ن]{.ar} after the ;ism_fail;.
Therefore, a ;lafzi; ;idaafah; is not permitted, and we cannot say:

(@) ;x; [الضَّارِبُ زَيْدٍ]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/132](https://shamela.ws/book/13301/582#p1)]{.citex}  

The following are similarly not permitted:

(@) ;x; [الضارب رجلٍ]{.ar}
    [[@ibn_aqil_alfiyyah@ 3/47](https://shamela.ws/book/9904/726)]{.citex}  
    [the beater of the man]{.trans}  

(@) ;x; [الضَّارِبُ عَبْدِ زَيْدٍ]{.ar}
    [@wright@ 2/66B]{.citex}
    [the beater of the slave of Zayd]{.trans}  

(@) ;x; [الضَّارِبُ عَبْدِهِ]{.ar}
    [@wright@ 2/66B]{.citex}
    [the beater of his slave]{.trans}  

If, however, the ;mafulb; is defined by [ٱل]{.ar},
or is itself a ;mudaf; to a ;mudafil;
that is defined by [ٱل]{.ar},
then,
as an exception,
the ;lafzi; ;idaafah; is again permitted.^[@wright@ 2/66A]
For example:

(@) [الضَّارِبُ الْعَبْدِ]{.ar}
    [@wright@ 2/66A]{.citex}  
    [the beater of the slave]{.trans}  

(@) [الضَّارِبُ رَأْسِ الْعَبْدِ]{.ar}
    [@wright@ 2/66A]{.citex}  
    [the beater of the head of the slave]{.trans}  

<!--
We will also see in section\ (ref), ;ia;, that when the governor is used with a ;sifah; meaning,
then too such a ;lafzi; ;idaafah; is permitted.^[[@ibn_ya3ish_mufassal@ 2/132--133](https://shamela.ws/book/13301/582#p1)]
For example:
-->

(@) [الضَّارِبُ الرَّجُلِ]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/132](https://shamela.ws/book/13301/582#p1)]{.citex}  
    [the beater of the man]{.trans}

(@) [الضَّوَارِبُ/الضُّرَّابُ/الضَّارِبَاتُ الرَّجُلِ]{.ar}
    [[@ibn_aqil_alfiyyah@ 3/47](https://shamela.ws/book/9904/726)]{.citex}  
    [the beaters of the man]{.trans}

(@) [الضَّوَارِبُ/الضُّرَّابُ/الضَّارِبَاتُ غُلَامِ الرَّجُلِ]{.ar}
    [[@ibn_aqil_alfiyyah@ 3/47](https://shamela.ws/book/9904/726)]{.citex}  
    [the beaters of the slave-boy of the man]{.trans}

#### Two or more ;mafulb;s connected by [وَ]{.ar} or [أَوْ]{.ar} {.unnumbered}

When a ;ism_fail; governs two or more ;mafulb;s connected by [وَ]{.ar} or [أَوْ]{.ar}
then, if the first is in a ;lafzi; ;idaafah; then the second may either be in the ;istate; or the ;astate;.
For example

(@) [هذا ضاربُ زيدٍ وعمرٍو/وعمرًا]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/81](https://shamela.ws/book/13301/1445)]{.citex}  
    [This [person] is beating Zayd and [#eamr]{.trn2}]{.trans}  

By the way, if the first ;mafulb; is in the ;astate;, then it is not an ;idaafah; and the second ;mafulb; would follow in the ;astate;.

(@) [هذا ضاربٌ زيدًا وعمرًا]{.ar}  
    [This [person] is beating Zayd and [#eamr]{.trn2}]{.trans}  

## The ;ism_fail; with a pronoun as its ;mafulb;

When the ;ism_fail; governs a ;mafulb; that is a pronoun,
there is considerable variation seen

One possibility is is to separate the ;ism_fail; from its ;maful; pronoun using the prefix [إِيَّا]{.ar}, thus:

(@) [ضَارِبٌ إِيَّاكَ]{.ar}
    [@radiy_kafiyah@ 2/434]{.citex}  
    [beating you]{.trans}  

(@) [الضَارِبُ إِيَّاكَ]{.ar}
    [@radiy_kafiyah@ 2/434]{.citex}  
    [the beater of you]{.trans}  

(@) [الضَارِبُونَ إِيَّاهُ]{.ar}
    [@wright@ 2/67A]{.citex}  
    [the beaters of me]{.trans}  

The second possibility, and by far the more common usage, is to use a ;lafzi; ;idaafah;, thus:

(@) [ضَارِبُكَ]{.ar}
    [@radiy_kafiyah@ 2/434]{.citex}  
    [beating you]{.trans}  

(@) [الضَارِبُكَ]{.ar}
    [@radiy_kafiyah@ 2/434]{.citex}  
    [the beater of you]{.trans}  

(@) [الضارِبِي]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the beater of me]{.trans}

(@) [الضارباتِي]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the beaters~f~ of me]{.trans}

For the dual and sound [Un]{.trn} plural in a ;lafzi; ;idaafah;, the [ن]{.ar} of the suffix is regularly deleted.
So we will say:

(@) [هذان ضارباك]{.ar}
    [[@sirafi_sibawayhi@ 1/196](https://shamela.ws/book/17726/194)]{.citex}  
    [These two are beating you.]{.trans}  
    (from [ضاربان]{.ar})

(@) [هؤلاء ضاربوك]{.ar}
    [[@sirafi_sibawayhi@ 1/196](https://shamela.ws/book/17726/194)]{.citex}  
    [These [persons] are beating you.]{.trans}  
    (from [ضاربون]{.ar})

(@) [الضارِباك]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the two beaters of you]{.trans}  
    (from [الضاربان]{.ar})

(@) [الضارِبوك]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the beaters of you]{.trans}  
    (from [الضاربون]{.ar})

(@) [ضاربايَ]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the two beaters of me]{.trans}  
    (from [الضاربَان]{.ar})

(@) [الضارِبَيَّ]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the two beaters of me]{.trans}  
    (from [الضاربَيْن]{.ar})

(@) [الضارِبِيَّ]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/135](https://shamela.ws/book/13301/585#p1)]{.citex}  
    [the beaters of me]{.trans}  
    (from [الضاربِين]{.ar} and [الضاربون]{.ar})

Occasionally
a [ن]{.ar} is inserted
between the ;ism_fail; ;mudaf;
and the pronoun ;mudafil;.
This would permit words like:
[ضَارِبُنِي]{.ar},
[الضَّارِبُونِي]{.ar},
etc.
For example:

(@) [فَهَلْ أَنْتُمْ صَادِقُونِي فِيهِ]{.ar}
    ^[also narrated as [صَادِقِيَّ]{.ar} in @https://sunnah.com/bukhari:3169@]
    [<https://hadithunlocked.com/nasai-kubra:11291>]{.citex}  
    [So will you tell me the truth about it?]{.trans}  

It seems that this usage did not make its way to Standard Classical Arabic.
But some grammarians permit this usage
by poetic license,
or as a rare usage.^[See for more details [@sirafi_sibawayhi@ 2/44](https://shamela.ws/book/17726/542); [@nahw_wafi@ 1/285](https://shamela.ws/book/10641/284); [@ibn_ya3ish_mufassal@ 2/137](https://shamela.ws/book/13301/587#p1); @wright@ 2/67AB]

## Conditions for the ;ism_fail; to govern a ;mafulb;

As we mentioned above,
there are conditions that must be satisfied in order for an ;ism_fail; to be able to govern a ;mafulb; in this manner.
The conditions are different for when the ;ism_fail; is defined by [ٱلْ]{.ar},
and when it is not defined by [ٱلْ]{.ar}.
We will discuss each of these cases separately below:

### When the ;ism_fail; is not defined by [ٱلْ]{.ar}

When the ;ism_fail; is not defined by [ٱلْ]{.ar},
then two conditions must be satisfied:

1. The verbal aspect of the ;ism_fail; must be imperfect.
   That is, it must indicate an ongoing (whether present or past) or future action.
   Examples:

   * present ongoing:

     (@) [هذا ضارب زيدا الآن]{.ar}
         [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
         [This [person] is beating Zayd now.]{.trans}

   * past ongoing:

     (@) [كان زيد ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Zayd was beating [#eamr]{.trn2}.]{.trans}

     (@) [وَكَلْبُهُمْ بَاسِطٌ ذِرَاعَيْهِ بَٱلْوَصِيدِ]{.quran}
         [@https://quran.com/18/18@ cited by @ibn_aqil_alfiyyah@ 3/106]{.citex}  
         [while their dog stretched his forelegs at the entrance]{.trans}

   * future:

     (@) [هذا ضارب زيدا غَدًا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
         [This [person] will beat Zayd tomorrow.]{.trans}

   If the verbal aspect indicated by the ;ism_fail; is perfect,
   then the ;ism_fail; may not govern a ;mafulb;.
   So, for example, we cannot say:

   (@) ;x; [هذا ضارب **زيدا** أمس]{.ar}
       [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
       [This [person] beat Zayd yesterday.]{.trans}

   If we desire to use the ;ism_fail;, then it will not have verbal force.
   And [زَيْد]{.ar} will have to be a ;mudafil; in a  ;idaafah;.
   Furthermore, this ;idaafah; will be _;ma3nawi;_ (see chapter\ (ref)).

   (@3amal_mush_hadha_daaribu_zaydin_amsi) [هذا ضارب زيد أمس]{.ar}
       [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
       [This [person] was the beater of Zayd yesterday.]{.trans}

   An exception is made for
   for transitive verbs that take more than one ;mafulb;,
   like [جعل]{.ar}, [أَعطى]{.ar}, etc.
   When the ;ism_fail; of such a verb is annexed to what would have been the first ;mafulb;,
   then second ;mafulb; is permitted to be in the ;astate;, 
   even if the aspect is perfect.^[See also @https://tafsir.app/albahr-almuheet/35/1@ and @https://tafsir.app/aldur-almasoon/35/1@]
   For example:
   
   (@) [هذا معطي زيد أمس درهما]{.ar}
       [[@ibn_malik_sharh_tasheel@ 3/78](https://shamela.ws/book/13257/894#p1)]{.citex}  
       [This [person] was the giver of Zayd, yesterday, a dirham.]{.trans}  

   
   Even the first ;mafulb; may remain in the ;astate;, if separated from the ;ism_fail;.
   For example:
   
   (@) [هذا ظان أمس زيدا فاضلا]{.ar}
       [[@ibn_malik_sharh_tasheel@ 3/78](https://shamela.ws/book/13257/894#p1)]{.citex}  
       [This [person] was the believer, yesterday, of Zayd as an eminent person.]{.trans}  

2. The second condition that should be satisfied is that the ;ism_fail; must have _governing support_.
   This governing support can be provided by the following means:

   * The ;ism_fail; occurs after a ;adat_istifham;.
     Example:

     (@) [أضارب زيد عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Is Zayd beating [#eamr]{.trn2}?]{.trans}  

     (@) [هَلْ مُكْرِمٌ أَنْتَ زَيْدًا]{.ar}
         [@wright@ 2/65D]{.citex}  
         [Will you be treating Zayd with respect?]{.trans}  

   * The ;ism_fail; occurs after a ;nidaa; particle:
     Example:

     (@) [يا طالعا جبلا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [O scaler [of] a mountain!]{.trans}  

   * The ;ism_fail; occurs in a negation:
     Example:

     (@) [ما ضارب زيد عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Zayd is not beating [#eamr]{.trn2}.]{.trans}  

     (@) [مَا أَنْتَ بِتَابِعٍ قِبْلَتَهُمْ]{.quran}
         [@https://quran.com/2/145@ cited by @wright@ 2/65D]{.citex}  
         [Nor will you be a follower of their qiblah]{.trans}  

     (@) [مَا مُجِيرٌ أَحَدٌ عَدُوَّ أَحِبَّاءِهِ]{.ar}
         [@wright@ 2/65D]{.citex}  
         [No one gives protection to the enemy of his loved ones]{.trans}  

   * The ;ism_fail; occurs as a ;na3t;.
     Example:

     (@) [مررت برجل ضارب زيدا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [I passed by a man beating Zayd.]{.trans}  

     (@) [مَرَرْتُ بِفَارِسٍ طَالِبٍ ثَأْرَ أَبِيهِ]{.ar}
         [@wright@ 2/65C]{.citex}  
         [I passed by a horseman (who was) seeking vengeance for (the murder of) his father]{.trans}  

     An implied ;na3t; is also considered permissible.
     Example:

     (@) [كَمْ مَالِئٍ عَيْنَيْهِ مِنْ شَيْءِ غَيْرِهِ]{.ar}
         [@wright@ 2/65C; @ibn_aqil_alfiyyah@ 3/108]{.citex}  
         [How many a one fills his eyes with a thing of [someone] other than him]{.trans}    
         (i.e. [كَمْ شَخْصٍ مَالِئٍ]{.ar} [How many a person fills...]{.trans})

     (@) [كَنَاطِحٍ صَخْرَةً يَوْمًا لِيُوهِنَهَا]{.ar}
         [@wright@ 2/65C; @ibn_aqil_alfiyyah@ 3/109]{.citex}  
         [Like the gorer of a rock, one day, to try to weaken it]{.trans}    
         (i.e. [كَوَعِلٍ نَاطِحٍ]{.ar} [like a goring mountain goat...]{.trans})

   * The ;ism_fail; occurs as a ;hal;.
     Example:

     (@) [جاء زيد راكبا فرسا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Zayd came riding a horse.]{.trans}  

   * The ;ism_fail; occurs as a ;xabar;.
     Example:

     (@) [زيد ضارب عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Zayd is beating [#eamr]{.trn2}.]{.trans}  


     We will learn in later chapters, ;ia;, different forms of ;xabar;s.
     The following examples show these different forms, with references to the later chapters.

     (@) [كان زيد ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Zayd was beating [#eamr]{.trn2}.]{.trans}  
         (See chapter\ (kaana).)

     (@) [إن زيدا ضارب عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [Indeed Zayd is beating [#eamr]{.trn2}.]{.trans}  
         (See chapter\ (inna).)

     (@) [ظننت زيدا ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [I thought Zayd [was] beating [#eamr]{.trn2}.]{.trans}  
         (See chapter\ (zanna).)

     (@) [أعلمت زيدا عمرا ضاربا بكرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         [I let Zayd know [#eamr]{.trn2} is beating Bakr.]{.trans}  
         (See chapter\ (zanna).)

<!--
     (@) [زَيْدٌ ضَارِبٌ أَبُوهُ أَخًا لِي]{.ar}
         [@wright@ 2/65B]{.citex}  
         [Zayd, his father is beating a brother of mine.]{.trans}  
-->

### When the ;ism_fail; is defined by [ٱلْ]{.ar}

When the ;ism_fail; is defined by [ٱلْ]{.ar},
then it is permitted to govern a ;mafulb; for a perfect or imperfect aspect.
So we can say:

(@) [هذا الضارب زيدا الآن أو غدا أو أمس]{.ar}
    [@ibn_aqil_alfiyyah@ 3/110]{.citex}  
    [This [person] is the beater of Zayd now/tomorrow/yesterday.]{.trans}

Furthermore, no supporting element is required for it to be a governor,
(as was required for the ;ism_fail; without [ٱلْ]{.ar} in section\ (ref) above).


## The ;ism_fail; as the governor of an ;zaahir; ;faa3il; pronoun

The ;mustatir; ;faa3il; pronoun becomes ;zaahir; in some circumstances.
In this section,
we will discuss one such circumstance.
Consider the sentence:

(@) [الفارس الحصانُ مُتْعِبُه]{.ar}
    [@nahw_wafi@ 1/463]{.citex}  

This grammar is parsed as follows:

* [الْفَارِسُ]{.ar} is the ;mubtada; of the outer sentence.
* [الْحِصَانُ]{.ar} is a second ;mubtada;. It is the ;mubtada; of the inner sentence.
* [مُتْبِع]{.ar} is the ;xabar; of the inner sentence. It is also a ;mudaf;.
* The pronoun [هُ]{.ar} is a ;mudafil;.
* The inner sentence [الْحِصَانُ مُتْبِعُهُ]{.ar} is the ;xabar; of the ;mubtada; ([الْفَارِسُ]{.ar}) of outer sentence.

The ;xabar; of the inner sentence [مُتْبِع]{.ar} [one who makes tired]{.trans}
has a ;mustatir; ;faa3il; pronoun, implicated as [[هُوَ]{.ar}].
It is possible for this ;mustatir; ;faa3il; pronoun
to refer to either 
[الْفَارِسُ]{.ar}
or
[الْحِصَانُ]{.ar}.
Let's discuss both these meanings:

 i. If
    the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] in
    [مُتْبِع]{.ar} refers to
    [الْحِصَانُ]{.ar}
    then the meaning is that
    [the horse makes the horseman tired]{.trans}.
    In this case, 
    the pronoun [هُ]{.ar} in [مُتْبِعُهُ]{.ar} refers to 
    [الْفَارِسُ]{.ar}.
    
ii. And if 
    the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] in
    [مُتْبِع]{.ar} refers to
    [الْفَارِسُ]{.ar}
    then the meaning is that
    [the horseman makes the horse tired]{.trans}.
    In this case, 
    the pronoun [هُ]{.ar} in [مُتْبِعُهُ]{.ar} refers to 
    [الْحِصَانُ]{.ar}.

Both meanings are possible.

If only the second meaning is desired,
then the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] can be made ;zaahir; and added after the ;ism_fail; [مُتْبِع]{.ar}, thus:

(@) [الفارس الحصانُ مُتْعِبُه **هُوَ**]{.ar}
    [@nahw_wafi@ 1/464]{.citex}  
    [The horseman -- the horse -- [he] makes him tired.]{.trans}  
    (i.e. [The horseman makes the horse tired.]{.trans})

Now only the second meaning is possible.
If the first meaning is desired, the ;faa3il; pronoun of 
[مُتْبِع]{.ar}
must stay ;mustatir; and the ambiguity will remain.

By the way, the ambiguity arose in the original sentence
([الفارس الحصانُ مُتْعِبُه]{.ar})
only because both ;mubtada;s
([الْفَارِسُ]{.ar}
and
[الْحِصَانُ]{.ar})
are singular masculine nouns.
If the two ;mubtada;s are distinguishable in number or gender then there will be no ambiguity.
However, even in this case,
according to some grammarians,
if the ;xabar; is to refer to the ;mubtada; of the outer sentence,
then the ;faa3il; pronoun of the ;ism_fail; in the ;xabar; should be made ;zaahir;.
For example:

(@3amal_mush_zaydun_hindun_daaribuhaa_huwa) [زَيْدٌ هِنْدٌ ضَارِبُهَا **هُوَ**]{.ar}
    [[@ibn_aqil_alfiyyah@ 1/207](https://shamela.ws/book/9904/206#p1)]{.citex}  
    [Zayd -- Hind -- [he] is beating her.]{.trans}  
    (i.e. [Zayd is beating Hind.]{.trans})

But according to other grammarians, 
because [ضَارِب]{.ar} can refer only to Zayd and not to Hind,
the ;ism_fail;'s ;faa3il; pronoun can remain latent,^[[@ibn_aqil_alfiyyah@ 1/207](https://shamela.ws/book/9904/206#p1)] thus:

(@) [زَيْدٌ هِنْدٌ ضَارِبُهَا]{.ar}   
    [Zayd -- Hind -- [he] is beating her.]{.trans}  
    (i.e. [Zayd is beating Hind.]{.trans})

<!--
(@) [زَيْدٌ عَمْرٌو ضَارِبُهُ]{.ar}
    [@ibn_aqil_alfiyyah@ 1/208]{.citex}  

This sentence can have two different meanings:

 i. [Zayd -- [#eamr]{.trn2} beats him]{.trans}
ii. [Zayd -- [#eamr]{.trn2} beats him]{.trans}
-->

## The ;sababi; ;xabar;

<!--
[Zayd beats [#amr]{.trn2}]{.trans}
-->

Consider again example (@3amal_mush_zaydun_yadribu_3amran) [زَيْدٌ يَضْرِبُ عَمْرًا]{.ar}.
From this original sentence, we replaced the verb 
[يَضْرِبُ]{.ar}
with its ;ism_fail; and came up with
(@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}.

Now consider the following example:

(@3amal_mush_zaydun_yadribu_aboohu_3amran) [زَيْدٌ يَضْرِبُ أَبُوهُ عَمْرًا]{.ar}  
    [Zayd -- his father beats [#eamr]{.trn2}]{.trans}

In example (@3amal_mush_zaydun_yadribu_aboohu_3amran) above
the ;faa3il; of 
[يَضْرِبُ]{.ar}
is not Zayd but Zayd's father.
If we use this sentence as our starting point,
we can again replace the verb
[يَضْرِبُ]{.ar}
with its ;ism_fail; 
[ضَارِبٌ]{.ar}
and say:

(@3amal_mush_zaydun_daaribun_aboohu_3amran) [زَيْدٌ ضَارِبٌ أَبُوهُ عَمْرًا]{.ar}  
    [Zayd -- his father is beating [#eamr]{.trn2}]{.trans}

[أَبُوهُ]{.ar} is the (;zaahir;) ;faa3il; of the ;ism_fail;
[ضَارِبٌ]{.ar}.
And [عَمْرًا]{.ar} is its ;mafulb;.
So just like a verb can have an ;zaahir; noun as its ;faa3il; instead of a ;mustatir; pronoun,
so too can the ;ism_fail; have an ;zaahir; noun as its ;faa3il; instead of a ;mustatir; pronoun.

Again, there is one important difference between using the verb
[يَضْرِبُ]{.ar}
vs using its ;ism_fail; 
[ضَارِبٌ]{.ar}.
And that is that 
[يَضْرِبُ أَبُوهُ عَمْرًا]{.ar}
in example (@3amal_mush_zaydun_yadribu_aboohu_3amran)
is a complete sentence.
This inner sentence is the ;xabar; of the outer sentence.
Therefore, example (@3amal_mush_zaydun_yadribu_aboohu_3amran) is a compound sentence.

However,
[ضَارِبٌ أَبُوهُ عَمْرًا]{.ar}
in example (@3amal_mush_zaydun_daaribun_aboohu_3amran) 
is not a complete sentence.
[ضَارِبٌ]{.ar}
itself, as a single word, is the ;xabar; of the ;mubtada; [زَيْدٌ]{.ar}.^[[@taftazani_mukhtasar_maani@ 86](https://ketabonline.com/ar/books/16360/read?part=1&page=82&index=72272/72275)]
So example (@3amal_mush_zaydun_daaribun_aboohu_3amran) [زَيْدٌ ضَارِبٌ أَبُوهُ عَمْرًا]{.ar}
is not a compound sentence.

<!--
In example () it is an inner sentence as the ;xabar; of the outer sentence.
Therefore () zaydun yaDrib abuuhu 3amran is a compound sentence.
But DAribun abuuhu 3amran is not a complete sentence by itself.
Rather DAribun comprises the ;xabar; as a single word.^[subki, mukhtasar al-ma3aani lil-taftaazaani 86]
So () zaydun DAribun aBuuhu 3amran is not a compound sentence.
-->

This kind of a ;xabar;
<!--
where the ;faa3il; of the ;xabar; (abuhu) does not refer to the same person as the ;mubtada; (zaydun),
-->
([ضَارِبٌ]{.ar} in this example)
that is a ;mushtaqq; noun which has a ;faa3il; that is a ;zaahir; noun and not a ;mustatir; pronoun
<!--
that expresses a property,
not directly about the ;mubtada; (Zayd),
but about someone linked to the ;mubtada; (Zayd's father),
-->
is called a ;sababi; ;xabar;.^[[[الخبر السببي لوجيهة السطل]{.ar}](https://alababmisr.com/%D8%A7%D9%84%D8%AE%D8%A8%D8%B1-%D8%A7%D9%84%D8%B3%D8%A8%D8%A8%D9%8A-%D8%AF-%D9%88%D8%AC%D9%8A%D9%87%D8%A9-%D8%A7%D9%84%D8%B3%D8%B7%D9%84/)]

<!--
This can be made clear by looking at the following example:

(@) kaana zaydun muntaliqan

-->

### Varying the number or gender of the ;zaahir; ;faa3il; of the ;sababi; ;xabar;

Here is another example of a sentence with a ;sababi; ;xabar;:

(@3amal_mush_kaana_zaydun_muntaliqan_aboohu) [كَانَ زَيْدٌ مُنْطَلِقًا أَبُوهُ]{.ar}
    [@peled_sentence_types@ 208]{.citex}  
    [Zayd -- his father was setting out.]{.trans}

In example (@3amal_mush_kaana_zaydun_muntaliqan_aboohu) 
above,
[مُنْطَلِقًا]{.ar} is the ;sababi; ;xabar; of [كَانَ]{.ar}.
The ;zaahir; ;faa3il; of the [مُنْطَلِقًا]{.ar} is the singular masculine noun [أَبُوه]{.ar} [his father]{.trans}.

Let's see what happens when
we vary the number or gender of this ;zaahir; ;faa3il; of the ;sababi; ;xabar;.

(@3amal_mush_kaana_alzaydaani_muntaliqan_abawaahuma) [كَانَ الزَيْدَانِ **مُنْطَلِقًا** أَبَوَاهُمَا]{.ar}
    [@peled_sentence_types@ 208]{.citex}  
    [The two Zayds -- their fathers were setting out.]{.trans}

In example (@3amal_mush_kaana_alzaydaani_muntaliqan_abawaahuma) above,
the ;sababi; ;xabar; 
[مُنْطَلِقًا]{.ar}
remains in the singular, 
even though its ;faa3il; is the dual
[أَبَوَاهُمَا]{.ar}.

This is analagous to a verb, which remains in the singular for dual and plural ;faa3il;s.
For example
[كَانَ الزَيْدَانِ **يَنْطَلِقُ** أَبَوَاهُمَا]{.ar}, etc.

If the gender of the ;ism_fail;'s ;faa3il; is feminine,
then the ;ism_fail; remains in the singular but it is feminized.
For example:

(@) [زَيْدٌ **مُنْطَلِقَةٌ** أُمُّهُ]{.ar}  
    [Zayd -- his mother is setting out.]{.trans}

(@) [كَانَتْ هِنْدٌ **مُنْطَلِقَةً** خَالَتَاهَا]{.ar}  
    [Hind -- her two maternal aunts were setting out.]{.trans}

This again is analagous to the feminizing a verb that has a feminine ;faa3il;.

If the ;faa3il; of the ;ism_fail; is a plural, then we have an choice:

If the ;ism_fail; has a sound plural, then, again, it is not used and the ;ism_fail; remains in the singular.
For example:

(@) [كَانَ الزَيْدُونَ **مُنْطَلِقًا** آبَاؤُهُمْ]{.ar}  
    [The Zayds -- their fathers were setting out.]{.trans}

(@) [زَيْدٌ **مُنْطَلِقَةٌ** خَالَاتُهُ]{.ar}  
    [Zayd -- his maternal aunts are setting out.]{.trans}

But if
the ;ism_fail; has a broken plural, then it is allowed to be used, and is indeed preferred.^[@baseet_ibn_abi_rabee3@ 693--694 cited by @peled_sentence_types@ 208 (footnote)]
For example:

(@) [كَانَ الزَّيْدُونَ **قِيَامًا** آبَاؤُهُمْ]{.ar}  
    [The Zayds -- their fathers were standing]{.trans}

Here are some examples of ;sababi; ;xabar;s from the [#qurEAn]{.trn2}:

(@3amal_mush_aathimun_qalbuhu) [فَإِنَّهُۥۤ **ءَاثِمࣱ** قَلۡبُهُۥۗ]{.quran}
    [@https://quran.com/2/283@]{.citex}  
    [his heart is indeed sinful]{.trans}  
    (Other analyses besides a ;sababi; ;xabar; are also possible.^[@https://tafsir.app/aldur-almasoon/2/283@] One such differing analysis is discussed in section\ (ref) below.)

(@) [وَظَنُّوۤا۟ أَنَّهُم **مَّانِعَتُهُمۡ** حُصُونُهُم مِّنَ ٱللَّهِ]{.quran}
    [@https://quran.com/59/2@]{.citex}  
    [and they thought that their fortresses would protect them from Allāh]{.trans}  
    (Another analysis is also possible: [حُصُونُهُمْ]{.ar} can be a ;mubtada;, and [مَانِعَتُهُمْ]{.ar} is its fronted ;xabar;.^[@https://tafsir.app/aldur-almasoon/59/2@])

## The ;sababi; ;na3t;

(@) [يَتِيهُ قَوْمٌ قِبَلَ الْمَشْرِقِ مُحَلَّقَةٌ رُءُوسُهُمْ]{.ar}
    [@https://sunnah.com/muslim:1068c@]{.citex}  

Broken plural ok.^[@nahw_wafi@ 3/453--454]

::: {.ar}
مَرَرْت برجللين قَائِم أبواهما وبرجال قَائِم آباؤهم كَمَا تَقول قَامَ أبواهما وَقَامَ آباؤهم وَمن قَالَ قاما أبواهما وأكلوني البراغيث ثنى الْوَصْف وَجمعه جمع السَّلامَة فَقَالَ قَائِمين آبواهما قَائِمين آباؤهم وَأَجَازَ الْجَمِيع أَن تجمع الصّفة جمع التكسير إِذا كَانَ الِاسْم الْمَرْفُوع جمعا فَتَقول مَرَرْت بِرِجَال قيام آباؤهم وبرجل قعُود غلمانه
:::

[[[شرح قطر الندى]{.ar} 288](https://shamela.ws/book/6970/263)]{.citex}

## Conditions for the ;ism_fail; to govern a ;faa3il;

In section\ (ref) above,
we discussed the
conditions for the ;ism_fail; to govern a ;mafulb;.
Correspondingly, there exist
conditions for the ;ism_fail; to govern a ;faa3il;.

The ;ism_fail; can have either an ;zaahir; ;faa3il; (either as a noun or as a pronoun),
or a ;mustatir; ;faa3il; pronoun.
We will treat each of these separately below:

### Conditions for the ;ism_fail; to govern an ;zaahir; ;faa3il;

The grammarians differed with regard to the
conditions under which the ;ism_fail; is allowed to govern an ;zaahir; ;faa3il;.
According to some, the same conditions are applicable as for governing a ;mafulb;,
namely that the ;ism_fail; can only govern an ;zaahir; ;faa3il; when it has an imperfect aspect.
And it is not allowed to govern an ;zaahir; ;faa3il; for a perfect aspect.
The following example would then be disallowed:

(@) ;x; [زَيْدٌ قَائِمٌ أَبُوهُ أَمْسِ]{.ar}
    [@su3ood_dameer_mustatir@ 134]{.citex}  
    [Zayd -- his father stood yesterday.]{.trans}

Other grammarians, however, allowed such a sentence.^[@su3ood_dameer_mustatir@ 134]

### Conditions for the ;ism_fail; to govern a ;mustatir; ;faa3il; pronoun

As a default,
the ;ism_fail; requires
a ;mustatir; ;faa3il; pronoun.
So it governs
a ;mustatir; ;faa3il; pronoun unconditionally, except when it is prevented from doing so because of one of the following situations:

#### The ;ism_fail; is already governing an ;zaahir; ;faa3il; noun {.unnumbered}

If the ;ism_fail; is already governing an ;zaahir; ;faa3il;,
then it will not also have a ;mustatir; ;faa3il; pronoun.
This is because one ;ism_fail; cannot have two ;faa3il;s.^[@su3ood_dameer_mustatir@ 139]
Example:

(@) [زَيْدٌ قَائِمٌ أَبُوهُ]{.ar}
    [@su3ood_dameer_mustatir@ 139]{.citex}  
    [Zayd -- his father is standing]{.trans}

Beware though, that sometimes it may appear that an ;ism_fail; is governing an ;zaahir; ;faa3il;,
but actually another interpretation may also be possible.
Consider the following ;ayah; that we discussed in section\ (ref) above:

(@3amal_mush_aathimun_qalbuhu) [فَإِنَّهُۥۤ **ءَاثِمࣱ** قَلۡبُهُۥۗ]{.quran}
    [@https://quran.com/2/283@]{.citex}  
    [his heart is indeed sinful]{.trans}

We had discussed this as a case of a ;sababi; ;xabar;.
But another analysis is also possible:
The ;ism_fail; [آثِمٌ]{.ar} is governing a ;mustatir; ;faa3il; pronoun, and
[قَلْبُهُ]{.ar} is a ;badal; for the ;mustatir; ;faa3il; pronoun.^[@https://tafsir.app/aldur-almasoon/2/283@]

#### The ;ism_fail; is already governing an ;zaahir; ;faa3il; pronoun {.unnumbered}

We discussed in section\ (ref) above, a situation in which the originally ;mustatir; ;faa3il; pronoun of a ;ism_fail; becomes ;zaahir;.
Because the ;faa3il; is now ;zaahir; the ;ism_fail; will not govern an additional ;mustatir; ;faa3il;.^[@su3ood_dameer_mustatir@ 144]

(@3amal_mush_zaydun_hindun_daaribuhaa_huwa) [زَيْدٌ هِنْدٌ ضَارِبُهَا هُوَ]{.ar}
    [[@ibn_aqil_alfiyyah@ 1/207](https://shamela.ws/book/9904/206#p1)]{.citex}  
    [Zayd -- Hind -- [he] is beating her.]{.trans}  
    (i.e. [Zayd is beating Hind.]{.trans})

#### The ;ism_fail; is the ;mudaf; in a ;ma3nawi; ;idaafah; {.unnumbered}

When ;ism_fail; is the ;mudaf; in a ;ma3nawi; ;idaafah;,
then it will not govern a ;mustatir; ;faa3il; pronoun.^[@su3ood_dameer_mustatir@ 142]
This can happen when the ;ism_fail; indicates a perfective aspect.
We saw an example of this in the conditions for governing a ;mafulb; above:

@3amal_mush_hadha_daaribu_zaydin_amsi) [هذا ضارب زيد أمس]{.ar}
   [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
   [This [person] was the beater of Zayd yesterday.]{.trans}

By the way, this does not mean that the ;ism_fail; cannot govern a ;mustatir; ;faa3il; pronoun whenever it signifies a perfective aspect.
It only cannot do so in a ;ma3nawi; ;idaafah;.
So ;ism_fail; will govern a ;mustatir; ;faa3il; pronoun when it has a perfective aspect, but no ;idaafah;.
For example:

@) [هذا ضاربٌ أمس]{.ar}  
   [This [person] was a beater yesterday.]{.trans}

#### The ;ism_fail; does not have verbal force {.unnumbered}

When the ;ism_fail; does not verbal force, then it does not govern a ;mustatir; ;faa3il; pronoun.^[See citations in @su3ood_dameer_mustatir@ 154].
For example:

(@) [قَامَ **عَاقِلٌ** مِنْ بَنِي فُلَانٍ]{.ar}
    [@su3ood_dameer_mustatir@ 154]{.citex}  
    [An intelligent one from [such-and-such tribe] stood up.]{.trans}

#### Multiple ;ism_fail;s refer to the same referent {.unnumbered}

When there are multiple ;ism_fail;s that occur together and that refer to the same referent,
then only the first will have a ;mustatir; ;faa3il; pronoun and not the subsequent ones.
For example:

(@) [مَرَرْتُ بِرَجُلٍ قَائِمٍ لَا قَاعِدٍ]{.ar}
    [@su3ood_dameer_mustatir@ 156]{.citex}  
    [I passed by a standing, not a sitting, man.]{.trans}

## Chapter: The ;sifah_mush; as a verb-like governor

[[الأشباه والنظائز: ذكر ما افترق فيه الصفة المشبهة واسم الفاعل]{.ar}](https://archive.org/details/20220824_20220824_2014/page/n1377/mode/2up?q=%D8%A7%D9%84%D8%B3%D8%A8%D8%A8%D9%8A)

<https://shamela.ws/book/13301/1472>

<https://shamela.ws/book/13301/582#p1>

<https://shamela.ws/book/9985/799>

## Chapter: The ;masdar; as a verb-like governor

<https://shamela.ws/book/36130/1479#p1>

## FINI 

## Introduction

There are some nouns that are like verbs.
In that they may have the meaning of a verb (like the ;masdar;),
or they have be derived from a verb (like the ;mushtaqq;s: the ;ism_fail;, the ;ism_maful;, etc.).

In this chapter we will study their ability to govern a ;faa3il; or a ;maful;.

## The ;ism_fail; as a governor

Before we discuss
the ;ism_fail; as a verb-like governor,
we will discuss, as our starting point, the verb as a governor.
Consider the following example:

(@3amal_mush_zaydun_yadribu_3amran) [زَيْدٌ يَضْرِبُ عَمْرًا]{.ar}  
    [Zayd beats [#amr]{.trn2}]{.trans}

Example (@3amal_mush_zaydun_yadribu_3amran) is parsed as follows:

* [زَيْدٌ]{.ar} is a ;mubtada;.
* [يَضْرِبُ]{.ar} is a ;mudarie; verb in the ;ustate;.
  It governs a ;mustatir; pronoun (implicated as [هُوَ]{.ar}) in the ;ustate; as its ;faa3il;. 
  The ;mustatir; ;faa3il; pronoun [هُوَ]{.ar} refers back to its referent: the ;mubtada; [زَيْدٌ]{.ar}.
* [عَمْرًا]{.ar} is a ;mafulb;, governed in the ;astate; by  the verb [يَضْرِبُ]{.ar}.
* [يَضْرِبُ عَمْرًا]{.ar} is an inner sentence which is in place of a ;ustate; noun as the ;xabar; of the ;mubtada; [زَيْدٌ]{.ar}.

The figure below depicts the government of this sentence:

[DIAGRAM with dotted line for rabt/3aaid]

The inner sentence
[يَضْرِبُ عَمْرًا]{.ar}.
is a complete sentence consisting a two ;3umdah; elements:

 i. The ;muxbar3; is the ;mustatir; ;faa3il; pronoun (an implicated [هُوَ]{.ar}) of the verb [يَضْرِبُ]{.ar}.
ii. The ;muxbar; is the verb [يَضْرِبُ]{.ar}.

The ;mafulb; [عَمْرًا]{.ar} is a ;fadlah; element.

The above analysis is our starting point.
Now we come to our discussion regarding the ;ism_fail;.
The ;ism_fail; is technically a noun.
But because it is derived from a verb, it has some verbal qualities.
Instead of using the verb [يَضْرِبُ]{.ar} in example (@3amal_mush_zaydun_yadribu_3amran) above
we may instead use its ;ism_fail;
[ضَارِب]{.ar}, thus:

(@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}  
    [Zayd beats [#amr]{.trn2}]{.trans}

For now, we have translated examples (@3amal_mush_zaydun_yadribu_3amran) and (@3amal_mush_zaydun_daaribun_3amran)
identically:
[Zayd beats [#amr]{.trn2}]{.trans}.
But actually the ;ism_fail; can signify a somewhat different meaning from the ;mudarie; verb.
We wil study the meaning implications of using an ;ism_fail; instead of a verb in more detail in chapter\ (ref).
For now, let's focus on the grammar of the new sentence.
Example (@3amal_mush_zaydun_daaribun_3amran) is parsed as follows:

* [زَيْدٌ]{.ar} is a ;mubtada;.
* [ضَارِبٌ]{.ar} is the ;xabar; of the ;mubtada; [زَيْدٌ]{.ar}.
  It governs a ;mustatir; pronoun (implicated as [هُوَ]{.ar}) in the ;ustate; as its ;faa3il;. 
  The ;mustatir; ;faa3il; pronoun [هُوَ]{.ar} refers back to the ;mubtada; [زَيْدٌ]{.ar}.
* [عَمْرًا]{.ar} is a ;mafulb;, governed in the ;astate; by the ;ism_fail; [ضَارِبٌ]{.ar}.

DIAGRAM

Let's note some similarities and differences in the analyses of 
examples (@3amal_mush_zaydun_yadribu_3amran) and (@3amal_mush_zaydun_daaribun_3amran):

The similarities are:

* [زَيْدٌ]{.ar} is the ;mubtada; of a ;j_ism;.
* Both [يَضْرِبُ]{.ar} and [ضَارِبٌ]{.ar} govern a ;mustatir; ;faa3il; pronoun (implicated as [هُوَ]{.ar}).
* Both [يَضْرِبُ]{.ar} and [ضَارِبٌ]{.ar} govern the ;mafulb; [عَمْرًا]{.ar}.

The difference is that
in example (@3amal_mush_zaydun_yadribu_3amran),
the ;xabar; of [زَيْدٌ]{.ar} is the inner sentence [يَضْرِبُ عَمْرًا]{.ar}.

But in example (@3amal_mush_zaydun_daaribun_3amran):
the ;xabar; of [زَيْدٌ]{.ar} is the single noun [ضَارِبٌ]{.ar}.
Even though [ضَارِبٌ]{.ar} governs a ;faa3il; (an implicated [هُوَ]{.ar}).
it does not form a complete sentence with its ;faa3il; (unlike [يَضْرِبُ]{.ar}).
We will elaborate on this in the next section.

In examples (@3amal_mush_zaydun_yadribu_3amran) and (@3amal_mush_zaydun_daaribun_3amran)
we see that both the verb [يَضْرِبُ]{.ar}
and the ;ism_fail; [ضَارِب]{.ar}
have a ;mustatir; ;faa3il; pronoun.
Let's take a look at another example:

(@) [زَيْدٌ قَائِمٌ]{.ar}  
    [Zayd is standing.]{.trans}

The ;ism_fail; [قَائِمٌ]{.ar} has a ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] attached after it, just like if we had said
[زَيْدٌ يَقُومُ]{.ar}.
This ;faa3il; pronoun refers back to its referent: the ;mubtada; [زَيْدٌ]{.ar}.

DIAGRAM

Similarly, if we say:

(@) [صَاحَ الرَّجُلُ الْقَائِمُ]{.ar}  
    [The standing man shouted.]{.trans}

then [الْقَائِمُ]{.ar} has a ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] attached after it, that refers back to [الرَّجُلُ]{.ar}.

The fact that the ;ism_fail; has a ;mustatir; ;faa3il; pronoun
is,
in fact,
the reason why a ;ism_fail; in the ;xabar; will match the ;mubtada; in gender.^[[Non-agreement of Mubtada and Khabar](https://drvaniya.com/wp-content/uploads/2016/12/Q33-Non-agreement-of-Mubtada-and-Khabar.pdf)]

For example, if we say:

(@) [هِنْدٌ قَائِمَةٌ]{.ar}  
    [Hind is standing.]{.trans}

then the feminine marker [ة]{.ar} is added to the ;ism_fail; [قَائِم]{.ar} only because it has to match the feminine gender of the ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}] that is attached to the ;ism_fail;.
(The ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}] refers back to [هِنْد]{.ar}.)


<!--
This difference is important to note in order to understand in what manner the ;ism_fail; can act like a verb-like governor.
The ;ism_fail; with its ;faa3il;
([ضَارِبٌ]{.ar} and [[هُوَ]{.ar}]
in this example),
does not, in most circumstances, constitute a complete sentence.
We will elaborate on this in the next section.
-->

## Differences between the ;faa3il; of a verb and the ;faa3il; of a ;ism_fail;

In example (@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}
we stated that the ;ism_fail;
[ضَارِبٌ]{.ar}
has a ;mustatir; ;faa3il; pronoun
(implicated as [هُوَ]{.ar}).
In this respect, it is similar to a verb.
Because a verb is always followed by its ;faa3il;.

But there are some differences between
between the ;faa3il; of a verb and the ;faa3il; of a ;ism_fail;:

Firstly, the ;ism_fail; governs a ;faa3il; in most circumstances, but not in all circumstances.
In contrast, a verb always governs a ;faa3il;.
(We will discuss the conditions under which a ;ism_fail; governs a ;faa3il; in section (ref) below.)

Secondly,
the verb and its ;faa3il; are ;3umdah; elements and,
together,
always constitute a complete sentence.
For example,
if we say:

(@) [يَقُومُ]{.ar}  
    [He stands.]{.trans}

then
the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}]
is the ;muxbar3; and
[يَقُومُ]{.ar} is the ;muxbar;.

In contrast, the ;ism_fail; and its ;faa3il; do not,
in most circumstances, constitute a complete sentence.
This is because the ;ism_fail;
is always,
part of a existing sentence _as a single element_.
So it cannot be an ;3umdah; element of a new sentence (with its ;faa3il;).
The following examples should illustrate what we mean.
Let's begin with the previous example:

(@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}  
    [Zayd beats [#eamr]{.trn2}]{.trans}

In example (@3amal_mush_zaydun_daaribun_3amran) above,
[زَيْدٌ]{.ar} and
[ضَارِبٌ]{.ar} form a complete sentence as ;3umdah; elements.
[زَيْدٌ]{.ar} is the ;muxbar3; and
[ضَارِبٌ]{.ar} is the ;muxbar;.
The ;faa3il; of
[ضَارِبٌ]{.ar} (the pronoun [[هُوَ]{.ar}]) then cannot be a ;muxbar3; of new sentence with
[ضَارِبٌ]{.ar} as its ;muxbar; because
[ضَارِبٌ]{.ar}, as a single element, is already the ;muxbar; of the sentence
[زَيْدٌ ضَارِبٌ]{.ar}.

Here is another example:

(@) [مَرَرْتُ بٍرَجُلٍ قَائِمٍ]{.ar}  
    [I passed by a standing man.]{.trans}

The ;3umdah; elements of this sentence are 
[مَرَرْتُ]{.ar}: the verb [مَرَّ]{.ar} and its ;faa3il; pronoun [تُ]{.ar}.
The entire phrase
[بٍرَجُلٍ قَائِمٍ]{.ar} has only ;fadlah; elements.
[قَائِمٍ]{.ar} is a ;na3t; of [رَجُلٍ]{.ar}, governed by the verb [مَرَّ]{.ar}.
[قَائِمٍ]{.ar} has a ;mustatir; ;faa3il; pronoun
[[هُوَ]{.ar}] that refers back to [رَجُلٍ]{.ar}.
But because 
[قَائِمٍ]{.ar} is a (;fadlah;) element of an existing sentence ([مَرَرْتُ]{.ar}),
it cannot be the ;3umdah; ;muxbar; of a new sentence with its ;mustatir; ;faa3il; pronoun 
[[هُوَ]{.ar}].

So, as you can see, whenever the ;ism_fail; has a ;mustatir; ;faa3il; pronoun,
that ;faa3il; pronoun is not the ;muxbar3; of any sentence.
This is because the ;ism_fail;, as a single element, is already a member of an existing sentence.

In contrast, a verb always forms a sentence (as the ;muxbar;) with its ;faa3il; (as the ;muxbar3;).
We already saw how [يَضْرِبُ]{.ar}, as a complete sentence, is the ;xabar; in example (@3amal_mush_zaydun_yadribu_3amran) [زَيْدٌ يَضْرِبُ عَمْرًا]{.ar}.

And if we replace the ;ism_fail; [قَائِمٍ]{.ar} with the verb [يَقُومُ]{.ar} thus:

(@) [مَرَرْتُ بٍرَجُلٍ **يَقُومُ**]{.ar}

then [يَقُومُ]{.ar} is as a complete sentence with the verb and its ;mustatir; ;faa3il; pronoun as ;3umdah; elements.
This complete sentence is the ;na3t; of [رَجُلٍ]{.ar}.

<!--
## The ;mustatir; ;faa3il; pronoun of the ;ism_fail;

In example (@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}
we stated that the ;ism_fail;
[ضَارِبٌ]{.ar}
has a ;mustatir; ;faa3il; pronoun
(implicated as [هُوَ]{.ar}).
-->

<!--
The ;ism_fail; requires a ;faa3il; whenever it is acting in a verb-like capacity.
This includes when the ;ism_fail; is used as a ;sifah;,
like qaaim "standing".
This is because the ;sifah; meaning of an ;ism_fail; is derived from its verbal meaning
(qaama yaqoom "he stands").
-->
<!--
The ;ism_fail; will thus usually have
a ;mustatir; ;faa3il; pronoun with it.^[@su3ood_dameer_mustatir@ 136ff]
So, for example, if we say:

(@) [زَيْدٌ قَائِمٌ]{.ar}  
    [Zayd is standing.]{.trans}

then [قَائِمٌ]{.ar} has a ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] attached after it, just like if we had said
[زَيْدٌ يَقُومُ]{.ar}.
This ;faa3il; pronoun refers back to its referent: the ;mubtada; [زَيْدٌ]{.ar}.

DIAGRAM

Similarly, if we say:

(@) [صَاحَ الرَّجُلُ الْقَائِمُ]{.ar}  
    [The standing man shouted.]{.trans}

then [الْقَائِمُ]{.ar} has a ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] attached after it, that refers back to [الرَّجُلُ]{.ar}.

The fact that the ;ism_fail; requires a ;faa3il;
is,
in fact,
the reason why a ;ism_fail; in the ;xabar; will match the ;mubtada; in gender.^[[Non-agreement of Mubtada and Khabar](https://drvaniya.com/wp-content/uploads/2016/12/Q33-Non-agreement-of-Mubtada-and-Khabar.pdf)]

For example, if we say:

(@) [هِنْدٌ قَائِمَةٌ]{.ar}  
    [Hind is standing.]{.trans}

then the feminine marker [ة]{.ar} is added to the ;ism_fail; [قَائِم]{.ar} only because it has to match the feminine gender of the ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}] that is attached to the ;ism_fail;.
(The ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}] refers back to [هِنْد]{.ar}.)
-->
<!--
This is analagous to when a ;madi; verb has a feminine ;faa3il;. 
The [ت]{.ar} of femininity is appended to the verb in order to match the gender of the ;faa3il;.
For example:

(@) [هِنْدٌ قَامَتْ]{.ar}
-->

When the referent of the ;mustatir; ;faa3il; pronoun changes for number or gender,
then the ;mustatir; ;faa3il; pronoun will change to match it.
For example:

(@3amal_mush_zaydaan_qaaimaan) [الزَّيْدَانِ قَائِمَانِ]{.ar}
    [[@sabban@ 1/291](https://shamela.ws/book/11539/288#p1)]{.citex}  
    [The two Zayds are standing.]{.trans}

(@3amal_mush_zaydoon_qaaimoon) [الزَّيْدُونَ قَائِمُونَ]{.ar}
    [[@sabban@ 1/291](https://shamela.ws/book/11539/288#p1)]{.citex}  
    [The Zayds are standing.]{.trans}

In example (@3amal_mush_zaydaan_qaaimaan) above,
the ;mustatir; ;faa3il; pronoun of [قَائِمَانِ]{.ar} is implicated as [هُمَا]{.ar}.

And in example (@3amal_mush_zaydoon_qaaimoon) 
the ;mustatir; ;faa3il; pronoun of [قَائِمُونَ]{.ar} is implicated as [هُمْ]{.ar}.

But as a point of technicality,
the alif in the dual suffix of [قَائِمَانِ]{.ar} and the [و]{.ar} in the plural suffix of [قَائِمُونَ]{.ar}, are not themselves the ;faa3il; pronouns.^[haazimi 30/5 <https://shamela.ws/book/36130/531>]
<!--
This is because, 
[قَائِمَانِ]{.ar} and 
[قَائِمُونَ]{.ar},
even with their ;mustatir; ;faa3il; pronouns,
are not complete sentences.^[haazimi 30/5 <https://shamela.ws/book/36130/531>]
-->

This is different from verbs, where alif for the dual and [و]{.ar} for the plural are themselves the ;faa3il; pronouns.
So [يَقُومَانِ]{.ar} and [يَقُومُونَ]{.ar} are both complete sentences comprised of two ;3umdah; elements:
the verb and its ;faa3il;.

## A ;zaahir; ;faa3il; pronoun for the ;ism_fail;

The ;mustatir; ;faa3il; pronoun becomes ;zaahir; in some circumstances.
In this section,
we will discuss one such circumstance.
Consider the sentence:

(@) [الفارس الحصانُ مُتْعِبُه]{.ar}
    [@nahw_wafi@ 1/463]{.citex}  

This grammar is parsed as follows:

* [الْفَارِسُ]{.ar} is the ;mubtada; of the outer sentence.
* [الْحِصَانُ]{.ar} is a second ;mubtada;. It is the ;mubtada; of the inner sentence.
* [مُتْبِع]{.ar} is the ;xabar; of the inner sentence. It is also a ;mudaf;.
* The pronoun [هُ]{.ar} is a ;mudafil;.
* The inner sentence [الْحِصَانُ مُتْبِعُهُ]{.ar} is the ;xabar; of the ;mubtada; ([الْفَارِسُ]{.ar}) of outer sentence.

The ;xabar; of the inner sentence [مُتْبِع]{.ar} [one who makes tired]{.trans}
has a ;mustatir; ;faa3il; pronoun, implicated as [[هُوَ]{.ar}].
It is possible for this ;mustatir; ;faa3il; pronoun
to refer to either 
[الْفَارِسُ]{.ar}
or
[الْحِصَانُ]{.ar}.
Let's discuss both these meanings:

 i. If
    the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] in
    [مُتْبِع]{.ar} refers to
    [الْحِصَانُ]{.ar}
    then the meaning is that
    [the horse makes the horseman tired]{.trans}.
    In this case, 
    the pronoun [هُ]{.ar} in [مُتْبِعُهُ]{.ar} refers to 
    [الْفَارِسُ]{.ar}.
    
ii. And if 
    the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] in
    [مُتْبِع]{.ar} refers to
    [الْفَارِسُ]{.ar}
    then the meaning is that
    [the horseman makes the horse tired]{.trans}.
    In this case, 
    the pronoun [هُ]{.ar} in [مُتْبِعُهُ]{.ar} refers to 
    [الْحِصَانُ]{.ar}.

Both meanings are possible.

If only the second meaning is desired,
then the ;mustatir; ;faa3il; pronoun [[هُوَ]{.ar}] can be made ;zaahir; and added after the ;ism_fail; [مُتْبِع]{.ar}, thus:

(@) [الفارس الحصانُ مُتْعِبُه **هُوَ**]{.ar}
    [@nahw_wafi@ 1/464]{.citex}  
    [The horseman -- the horse -- [he] makes him tired.]{.trans}  
    (i.e. [The horseman makes the horse tired.]{.trans})

Now only the second meaning is possible.
If the first meaning is desired, the ;faa3il; pronoun of 
[مُتْبِع]{.ar}
must stay ;mustatir; and the ambiguity will remain.

By the way, the ambiguity arose in the original sentence
([الفارس الحصانُ مُتْعِبُه]{.ar})
only because both ;mubtada;s
([الْفَارِسُ]{.ar}
and
[الْحِصَانُ]{.ar})
are singular masculine nouns.
If the two ;mubtada;s are distinguishable in number or gender then there will be no ambiguity.
However, even in this case,
according to some grammarians,
if the ;xabar; is to refer to the ;mubtada; of the outer sentence,
then the ;faa3il; pronoun of the ;ism_fail; in the ;xabar; should be made ;zaahir;.
For example:

(@) [زَيْدٌ هِنْدٌ ضَارِبُهَا **هُوَ**]{.ar}
    [[@ibn_aqil_alfiyyah@ 1/207](https://shamela.ws/book/9904/206#p1)]{.citex}  
    [Zayd -- Hind -- [he] beats her.]{.trans}  
    (i.e. [Zayd beats Hind.]{.trans})

But according to other grammarians, 
because [ضَارِب]{.ar} can refer only to Zayd and not to Hind,
the ;ism_fail;'s ;faa3il; pronoun can remain latent,^[[@ibn_aqil_alfiyyah@ 1/207](https://shamela.ws/book/9904/206#p1)] thus:

(@) [زَيْدٌ هِنْدٌ ضَارِبُهَا]{.ar}   
    [Zayd -- Hind -- [he] beats her.]{.trans}  
    (i.e. [Zayd beats Hind.]{.trans})

<!--
(@) [زَيْدٌ عَمْرٌو ضَارِبُهُ]{.ar}
    [@ibn_aqil_alfiyyah@ 1/208]{.citex}  

This sentence can have two different meanings:

 i. [Zayd -- [#eamr]{.trn2} beats him]{.trans}
ii. [Zayd -- [#eamr]{.trn2} beats him]{.trans}
-->

## The ;sababi; ;xabar;

<!--
[Zayd beats [#amr]{.trn2}]{.trans}
-->

Consider again example (@3amal_mush_zaydun_yadribu_3amran) [زَيْدٌ يَضْرِبُ عَمْرًا]{.ar}.
From this original sentence, we replaced the verb 
[يَضْرِبُ]{.ar}
with its ;ism_fail; and came up with
(@3amal_mush_zaydun_daaribun_3amran) [زَيْدٌ ضَارِبٌ عَمْرًا]{.ar}.

Now consider the following example:

(@3amal_mush_zaydun_yadribu_aboohu_3amran) [زَيْدٌ يَضْرِبُ أَبُوهُ عَمْرًا]{.ar}  
    [Zayd -- his father beats [#eamr]{.trn2}]{.trans}

In example (@3amal_mush_zaydun_yadribu_aboohu_3amran) above
the ;faa3il; of 
[يَضْرِبُ]{.ar}
is not Zayd but Zayd's father.
If we use this sentence as our starting point,
we can again replace the verb
[يَضْرِبُ]{.ar}
with its ;ism_fail; 
[ضَارِبٌ]{.ar}
and say:

(@3amal_mush_zaydun_daaribun_aboohu_3amran) [زَيْدٌ ضَارِبٌ أَبُوهُ عَمْرًا]{.ar}  
    [Zayd -- his father beats [#eamr]{.trn2}]{.trans}

[أَبُوهُ]{.ar} is the (;zaahir;) ;faa3il; of the ;ism_fail;
[ضَارِبٌ]{.ar}.
And [عَمْرًا]{.ar} is its ;mafulb;.
So just like a verb can have an ;zaahir; noun as its ;faa3il; instead of a ;mustatir; pronoun,
so too can the ;ism_fail; have an ;zaahir; noun as its ;faa3il; instead of a ;mustatir; pronoun.

Again, there is one important difference between using the verb
[يَضْرِبُ]{.ar}
vs using its ;ism_fail; 
[ضَارِبٌ]{.ar}.
And that is that 
[يَضْرِبُ أَبُوهُ عَمْرًا]{.ar}
in example (@3amal_mush_zaydun_yadribu_aboohu_3amran)
is a complete sentence.
This inner sentence is the ;xabar; of the outer sentence.
Therefore, example (@3amal_mush_zaydun_yadribu_aboohu_3amran) is a compound sentence.

However,
[ضَارِبٌ أَبُوهُ عَمْرًا]{.ar}
in example (@3amal_mush_zaydun_daaribun_aboohu_3amran) 
is not a complete sentence.
[ضَارِبٌ]{.ar}
itself, as a single word, is the ;xabar; of the ;mubtada; [زَيْدٌ]{.ar}.^[[@taftazani_mukhtasar_maani@ 86](https://ketabonline.com/ar/books/16360/read?part=1&page=82&index=72272/72275)]
So example (@3amal_mush_zaydun_daaribun_aboohu_3amran) [زَيْدٌ ضَارِبٌ أَبُوهُ عَمْرًا]{.ar}
is not a compound sentence.

<!--
In example () it is an inner sentence as the ;xabar; of the outer sentence.
Therefore () zaydun yaDrib abuuhu 3amran is a compound sentence.
But DAribun abuuhu 3amran is not a complete sentence by itself.
Rather DAribun comprises the ;xabar; as a single word.^[subki, mukhtasar al-ma3aani lil-taftaazaani 86]
So () zaydun DAribun aBuuhu 3amran is not a compound sentence.
-->

This kind of a ;xabar;
<!--
where the ;faa3il; of the ;xabar; (abuhu) does not refer to the same person as the ;mubtada; (zaydun),
-->
([ضَارِبٌ]{.ar} in this example)
that expresses a property,
not directly about the ;mubtada; (Zayd),
but about someone linked to the ;mubtada; (Zayd's father),
is called a ;sababi; ;xabar;.^[[[الخبر السببي لوجيهة السطل]{.ar}](https://alababmisr.com/%D8%A7%D9%84%D8%AE%D8%A8%D8%B1-%D8%A7%D9%84%D8%B3%D8%A8%D8%A8%D9%8A-%D8%AF-%D9%88%D8%AC%D9%8A%D9%87%D8%A9-%D8%A7%D9%84%D8%B3%D8%B7%D9%84/), [@suyooti_ashbaah@ 4/287](https://lib.eshia.ir/71585/4/287)]

<!--
This can be made clear by looking at the following example:

(@) kaana zaydun muntaliqan

-->

### Varying the number or gender of the ;zaahir; ;faa3il; of the ;sababi; ;xabar;

Here is another example of a sentence with a ;sababi; ;xabar;:

(@3amal_mush_kaana_zaydun_muntaliqan_aboohu) [كَانَ زَيْدٌ مُنْطَلِقًا أَبُوهُ]{.ar}
    [@peled_sentence_types@ 208]{.citex}  
    [Zayd -- his father was setting out.]{.trans}

In example (@3amal_mush_kaana_zaydun_muntaliqan_aboohu) 
above,
[مُنْطَلِقًا]{.ar} is the ;sababi; ;xabar; of [كَانَ]{.ar}.
The ;zaahir; ;faa3il; of the [مُنْطَلِقًا]{.ar} is the singular masculine noun [أَبُوه]{.ar} [his father]{.trans}.

Let's see what happens when
we vary the number or gender of this ;zaahir; ;faa3il; of the ;sababi; ;xabar;.

(@3amal_mush_kaana_alzaydaani_muntaliqan_abawaahuma) [كَانَ الزَيْدَانِ **مُنْطَلِقًا** أَبَوَاهُمَا]{.ar}
    [@peled_sentence_types@ 208]{.citex}  
    [The two Zayds -- their fathers were setting out.]{.trans}

In example (@3amal_mush_kaana_alzaydaani_muntaliqan_abawaahuma) above,
the ;sababi; ;xabar; 
[مُنْطَلِقًا]{.ar}
remains in the singular, 
even though its ;faa3il; is the dual
[أَبَوَاهُمَا]{.ar}.

This is analagous to a verb, which remains in the singular for dual and plural ;faa3il;s.
For example
[كَانَ الزَيْدَانِ **يَنْطَلِقُ** أَبَوَاهُمَا]{.ar}, etc.

If the gender of the ;ism_fail;'s ;faa3il; is feminine,
then the ;ism_fail; remains in the singular but it is feminized.
For example:

(@) [زَيْدٌ **مُنْطَلِقَةٌ** أُمُّهُ]{.ar}  
    [Zayd -- his mother is setting out.]{.trans}

(@) [كَانَتْ هِنْدٌ **مُنْطَلِقَةً** خَالَتَاهَا]{.ar}  
    [Hind -- her two maternal aunts were setting out.]{.trans}

This again is analagous to the feminizing a verb that has a feminine ;faa3il;.

If the ;faa3il; of the ;ism_fail; is a plural, then we have an choice:

If the ;ism_fail; has a sound plural, then, again, it is not used and the ;ism_fail; remains in the singular.
For example:

(@) [كَانَ الزَيْدُونَ **مُنْطَلِقًا** آبَاؤُهُمْ]{.ar}  
    [The Zayds -- their fathers were setting out.]{.trans}

(@) [زَيْدٌ **مُنْطَلِقَةٌ** خَالَاتُهُ]{.ar}  
    [Zayd -- his maternal aunts are setting out.]{.trans}

But if
the ;ism_fail; has a broken plural, then it is allowed to be used, and is indeed preferred.^[@baseet_ibn_abi_rabee3@ 693--694 cited by @peled_sentence_types@ 208 (footnote)]
For example:

(@) [كَانَ الزَّيْدُونَ **قِيَامًا** آبَاؤُهُمْ]{.ar}  
    [The Zayds -- their fathers were standing]{.trans}

Here are some examples of ;sababi; ;xabar;s from the [#qurEAn]{.trn2}:

(@) [فَإِنَّهُۥۤ **ءَاثِمࣱ** قَلۡبُهُۥۗ]{.quran}
    [@https://quran.com/2/283@]{.citex}  
    [his heart is indeed sinful]{.trans}  
    (Other analyses besides a ;sababi; ;xabar; are also possible.^[@https://tafsir.app/aldur-almasoon/2/283@])

(@) [وَظَنُّوۤا۟ أَنَّهُم **مَّانِعَتُهُمۡ** حُصُونُهُم مِّنَ ٱللَّهِ]{.quran}
    [@https://quran.com/59/2@]{.citex}  
    [and they thought that their fortresses would protect them from Allāh]{.trans}  
    (Another analysis is also possible: [حُصُونُهُمْ]{.ar} can be a ;mubtada;, and [مَانِعَتُهُمْ]{.ar} is its fronted ;xabar;.^[@https://tafsir.app/aldur-almasoon/59/2@])

## The ;sababi; ;na3t;

(@) [يَتِيهُ قَوْمٌ قِبَلَ الْمَشْرِقِ مُحَلَّقَةٌ رُءُوسُهُمْ]{.ar}
    [@https://sunnah.com/muslim:1068c@]{.citex}  

Broken plural ok.^[@nahw_wafi@ 3/453--454]

::: {.ar}
مَرَرْت برجللين قَائِم أبواهما وبرجال قَائِم آباؤهم كَمَا تَقول قَامَ أبواهما وَقَامَ آباؤهم وَمن قَالَ قاما أبواهما وأكلوني البراغيث ثنى الْوَصْف وَجمعه جمع السَّلامَة فَقَالَ قَائِمين آبواهما قَائِمين آباؤهم وَأَجَازَ الْجَمِيع أَن تجمع الصّفة جمع التكسير إِذا كَانَ الِاسْم الْمَرْفُوع جمعا فَتَقول مَرَرْت بِرِجَال قيام آباؤهم وبرجل قعُود غلمانه
:::

[[[شرح قطر الندى]{.ar} 288](https://shamela.ws/book/6970/263)]{.citex}

<!--
## The ;sababi; ;hal;

Will discuss in chapter\ (ref) section\ (ref).
-->

<!--
## Circumstances in which the ;ism_fail; does not govern a ;mustatir; ;faa3il; pronoun
-->

## Conditions for the ;ism_fail; to govern a ;zaahir; ;faa3il; or a ;mafulb;

In order for a ;ism_fail; to govern an _;zaahir;_ ;faa3il; or a ;mafulb;
a certain set of conditions have to be satisfied.
In this section, we will discuss these conditions.

By the way, these conditions not required for an ;ism_fail; to govern a _;mustatir;_ ;faa3il; pronoun.
The ;ism_fail; typically always governs a ;mustatir; ;faa3il; pronoun,
(unless, of course, if it is governing an ;zaahir; ;faa3il;.^[See @su3ood_dameer_mustatir@ 139--156 for more exceptions.])

A foreign element must not come between the ;ism_fail; and its ;mafulb;

## The ;faa3il; that plugs the gap of the ;xabar;

We mentioned in sections\ (ref) above that an
;ism_fail; when governing a ;faa3il; does not constitute a complete sentence.

We gave the examples
DAriban 3amran
and
DAribun abuhu 3amran.
These don't consitute complete sentences until a ;mubtada; is added, like:
(@) zaydun DAriban 3amran
and
(@) zaydun DAribun abuhu 3amran.
Now the sentences are complete.

The ;mubtada; acts an supporting element for the ;ism_fail;.
(See section\ (ref) below.)


## Cases where the ;ism_fail; does not govern a ;faa3il;

From the discussion above,
we can see that the ;ism_fail; typically governs a ;faa3il; that occurs after it in sentence word-order.
This ;faa3il; is usually ;mustatir; but can be ;zaahir;, for example in ;sababi; sentences.
There are, however, some cases where the ;ism_fail; will not have a ;faa3il;.
These are:

#### When the ;ism_fail; is used with a ;substantive; meaning {.unnumbered}

As we know from chapter\ (ref), an ;ism_fail; can acquire a ;substantive; meaning.
For example,
jaami3ah univ
qaaimah leg.
When used with a ;substantive; meaning, the implication of the verb is now remote, and the ;ism_fail; behaves like any other ;substantive; in that it won't have a ;faa3il;.^[@nahw_wafi@ 1/232]
And this is the reason why,
when the ;ism_fail; is used as a ;substantive; in the ;xabar;,
then it does not need to match ;mubtada; in gender.
In other words, there is no ;mustatir; ;faa3il; pronoun,
which refers back to to the ;mubtada;
to cause the ;ism_fail; to get a mark of feminiity.

al-bina'u jaamiyah // gender matching not required.
hadhihi l-khashabu qaa'imatun lil-khiwaan.

#### When there is no referent for ;ism_fail; {.unnumbered}

For example:

(@) ra2aytun 3aaqilan min bani fulaan
    [phd su3ood al-Saa3idi 104]{.citex}  

Since there is no prior referent in the sentence for a ;faa3il; of the ;ism_fail; to refer to,
thus in this case the ;ism_fail; will have no ;faa3il;.

<!--
What about [والحافظين فروجهم]{.ar}??
maybe it has a doer pronoun referring to the ism_mawsool [الذين]{.ar} before it?
-->

## Necessary conditions in order for the ;ism_fail; to govern a ;mafulb;

In example () zaydun DAriban 3amran
we saw that the ;ism_fail; DAriban governs a ;mafulb; 3amran.
There are conditions that must be satisfied in order for an ;ism_fail; to be able to govern a ;mafulb; in this manner.
The conditions are different for when the ;ism_fail; has [ٱلْ]{.ar},
and when it is without [ٱلْ]{.ar}.
We will discuss each of these cases separately below:

### When the ;ism_fail; does not have [ٱلْ]{.ar}

When the ;ism_fail; is not defined by [ٱلْ]{.ar},
then two conditions must be satisfied:

1. The verbal action must have the meaning of the ;mudarie; verb.
   That is, its aspect should be continuous,
   (whether past or present) or future.
   Examples:

   * present continuous:

     (@) [هذا ضارب زيدا الآن]{.ar}
         [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
         "This [person] is beating Zayd now."

   * past continuous:

     (@) [كان زيد ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd was beating [#eamr]{.trn2}."

     (@) [وَكَلْبُهُمْ بَاسِطٌ ذِرَاعَيْهِ بَٱلْوَصِيدِ]{.ar}
         [@https://quran.com/18/18@ cited by @ibn_aqil_alfiyyah@ 3/106]{.citex}  
         "while their dog stretched his forelegs at the entrance"

   * future:

     (@) [هذا ضارب زيدا غَدًا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
         "This [person] will beat Zayd tomorrow."


2. The ;ism_fail; must be _supported_ by a preceding element.
   This can take the following forms:

   * The ;ism_fail; occurs after a ;adat_istifham;.
     Example:

     (@) [أضارب زيد عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Is Zayd beating [#eamr]{.trn2}?"

     (@) [هَلْ مُكْرِمٌ أَنْتَ زَيْدًا]{.ar}
         [@wright@ 2/65D]{.citex}  
         "Will you be treating Zayd with respect?"

   * The ;ism_fail; occurs after a ;nidaa; particle:
     Example:

     (@) [يا طالعا جبلا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "O scaler [of] a mountain!"

   * The ;ism_fail; occurs in a negation:
     Example:

     (@) [ما ضارب زيد عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd is not beating [#eamr]{.trn2}."

     (@) [مَا أَنْتَ بِتَابِعٍ قِبْلَتَهُمْ]{.ar}
         [@https://quran.com/2/145@ cited by @wright@ 2/65D]{.citex}  
         "Nor will you be a follower of their qiblah"

     (@) [مَا مُجِيرٌ أَحَدٌ عَدُوَّ أَحِبَّاءِهِ]{.ar}
         [@wright@ 2/65D]{.citex}  
         "No one gives protection to the enemy of his loved ones"

   * The ;ism_fail; occurs as a ;na3t;.
     Example:

     (@) [مررت برجل ضارب زيدا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "I passed by a man beating Zayd."

     (@) [مَرَرْتُ بِفَارِسٍ طَالِبٍ ثَأْرَ أَبِيهِ]{.ar}
         [@wright@ 2/65C]{.citex}  
         "I passed by a horseman (who was) seeking vengeance for (the murder of) his father"

     An implied ;na3t; is also considered permissible.
     Example:

     (@) [كَمْ مَالِئٍ عَيْنَيْهِ مِنْ شَيْءِ غَيْرِهِ]{.ar}
         [@wright@ 2/65C; @ibn_aqil_alfiyyah@ 3/108]{.citex}  
         "How many a one fills his eyes with a thing of [someone] other than him"  
         (i.e. [كَمْ شَخْصٍ مَالِئٍ]{.ar} "How many a person fills..."

     (@) [كَنَاطِحٍ صَخْرَةً يَوْمًا لِيُوهِنَهَا]{.ar}
         [@wright@ 2/65C; @ibn_aqil_alfiyyah@ 3/109]{.citex}  
         "Like the gorer of a rock, one day, to try to weaken it"  
         (i.e. [كَوَعِلٍ نَاطِحٍ]{.ar} "like a goring mountain goat...")

   * The ;ism_fail; occurs as a ;hal;.
     Example:

     (@) [جاء زيد راكبا فرسا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd came riding a horse."

   * The ;ism_fail; occurs as a ;xabar;, or 
     Examples:

     (@) [زيد ضارب عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd is beating [#eamr]{.trn2}."

     (@) [زَيْدٌ ضَارِبٌ أَبُوهُ أَخًا لِي]{.ar}
         [@wright@ 2/65B]{.citex}  
         "Zayd, his father is beating a brother of mine."

     (@) [كان زيد ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd was beating [#eamr]{.trn2}."

     (@) [إن زيدا ضارب عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Indeed Zayd is beating [#eamr]{.trn2}."

     Included in this definition of ;xabar; are the subsequent ;mafulb;s of the ;nasix; verbs.
     Examples:

     (@) [ظننت زيدا ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "I thought Zayd [was] beating [#eamr]{.trn2}."

     (@) [أعلمت زيدا عمرا ضاربا بكرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "I let Zayd know [#eamr]{.trn2} [was] beating Bakr."


<https://www.alukah.net/literature_language/0/108787/%D8%A7%D8%B3%D9%85-%D8%A7%D9%84%D9%81%D8%A7%D8%B9%D9%84-%D8%A8%D9%8A%D9%86-%D8%A7%D9%84%D8%AD%D8%A7%D9%84-%D9%88%D8%A7%D9%84%D8%A7%D8%B3%D8%AA%D9%82%D8%A8%D8%A7%D9%84-%D9%88%D8%A7%D9%84%D9%85%D8%B6%D9%8A/#014>

If the verbal action is not continuous,
and an ;ism_fail; is chosen to represent the action,
then the ;ism_fail; is, typically, not allowed to govern a ;mafulb;.
<!--
The ;ism_fail; will then is not used with the meaning of a verb.
Instead, it approaches more nearly to the nature of the noun that springs from the verb.^[@wright@ 2/64D]
-->

If the
semantic ;mafulb; is to be linked to the ;ism_fail;,
then they may be in a (_;ma3nawi;_) ;idaafah;.
(See section\ (ref) below for _;ma3nawi;_ vs _;lafzi;_ ;idaafah;s.)
For example,

(@) [هذا ضارب زيد أمس]{.ar}
    [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
    "This [person] was the beater of Zayd yesterday."

An exception is made for the case where the ;ism_fail; is prevented from being annexed to its semantic ;mafulb;.
This usually occurs
for transitive verbs that take more than one ;mafulb;,
like [جعل]{.ar}, [أَعطى]{.ar}, etc.
When the ;ism_fail; of such a verb is annexed to what would have been the first ;mafulb;,
then second ;mafulb; is permitted to be in the ;astate;.
For example

(@) [هذا معطي زيد أمس درهما]{.ar}

@https://tafsir.app/albahr-almuheet/35/1@

@https://tafsir.app/aldur-almasoon/35/1@

https://shamela.ws/book/13257/894#p1

Even the first ;mafulb; may remain in the ;astate;, if separated from the ;ism_fail;.
For example:

(@) [هذا ظان أمس زيدا فاضلا]{.ar}
    [https://shamela.ws/book/13257/894#p1]{.citex}

### When the ;ism_fail; has [ٱلْ]{.ar}

When the ;ism_fail; has [ٱلْ]{.ar},
then it is equivalent to a ;ism_mawsul; followed by a verb.
So, for example,
[ٱلضَّارِبُ]{.ar}
is equivalent to
[ٱلَّذِي ضَرَبَ],
[ٱلَّذِي يَضْرِبُ],
[ٱلَّذِي كَانَ يَضْرِبُ],
etc.
Because of this equivalence with an ;ism_mawsul; and a verb,
the ;ism_fail; that has [ٱلْ]{.ar}
is permitted to govern a ;faa3il; and a ;mafulb;
wherever the ;ism_fail; is used with the meaning of the doer of the verb.
No restriction is placed on whether the verbal action is in the past, present, or future.
Furthermore, no supporting element is required for it to be a governor,
(as was required for the ;ism_fail; without [ٱلْ]{.ar} in section\ (ref) above).

## The ;mushtaqq; noun governing a preposition

We have learned in section\ (ref) that prepositions can be governed by ;mushtaqq; nouns.
Even though they are in place of a ;mafulb;, they seem not to be restricted by the requirement to be in the imperfect.

[مبنية]{.ar}
[bukhari:4674]{.citex}

[أن صالجا مرسل من]{.ar}

## FINI


## The ;ism_fail; governing a preposition

The same preposition


## The difference in meaning when a governing ;ism_fail; is used instead of a verb

The primary meaning of the ;ism_fail; is that of the doer of a verb.
Here are some examples:

[قَاتِل]{.ar} | one who kills, i.e. a killer
[ضَارِب]{.ar} | one who laughs
[قَائِل]{.ar} | one who says, i.e a sayer
[مُتَكَلِّم]{.ar} | one who speaks, i.e. a speaker


---

## Conditions for using the ;ism_fail; as a verb-like governor

There are X conditions that need to be satisfied for using the ;ism_fail; as a governor:

wa kalbuhum baasiTun dhiraa3ayhi

## Implicating the ;mustatir; ;faa3il; pronoun

<!--
The adjectival meaning of the ;ism_fail; is in its capacity as a verb-like noun.
So qaaimun standing
-->
<!--
The ;mustatir; ;faa3il; pronoun accompanies its governing ;ism_fail; in most cases.
-->
The ;ism_fail; is requires a ;faa3il; whenever it is acting as a verb-like governor.
This includes when the ;ism_fail; is used as a ;sifah;.
This is because the ;sifah; meaning of an ;ism_fail; is derived from its verbal meaning.
And the use of the ;ism_fail; as a ;sifah; satsfies the conditions for the ;ism_fail; being a verb-like governor
because it signifies a description that is applicable in the present tense.

For example
qaa'imun
"standing"
gets this adjectival meaning from the verb
qaama yaqoomu.

Zaydun qaaimun.
Zayd is presently standing

kaana zaydun qaaiman
Zayd was (presently) standing.

The fact that the ;ism_fail; requires a ;faa3il; when acting as a verb-like governor is,
in fact,
<!--
It is in fact
-->
the reason why a ;ism_fail; (when used with its verbal meaning) in the ;xabar; will match the ;mubtada; in gender.

hindun qaaimatun

The mark of femininity [ة]{.ar} indicates the the ;faa3il; (the ;mustatir; pronoun which refers back the the ;mubtada; hindun) is feminine.
This is perfectly analagous to when a verb (that has the mark of femininity) is used in the ;xabar;

hindun qAmat

### Cases when the ;ism_fail; will not have a ;faa3il;

#### When the ;ism_fail; is used with a ;substantive; meaning {.unnumbered}

As we know from chapter\ (ref), an ;ism_fail; can acquire a ;substantive; meaning.
For example,
jaami3ah univ
qaaimah leg.
When used with a ;substantive; meaning, the implication of the verb is now remote, and the ;ism_fail; behaves like any other ;substantive; in that it won't have a ;faa3il;.
And this is the reason why,
when the ;ism_fail; is used as a ;substantive; in the ;xabar;,
then it does not need to match ;mubtada; in gender.
In other words, there is no ;mustatir; ;faa3il; pronoun,
which refers back to to the ;mubtada;
to cause the ;ism_fail; to get a mark of feminiity.

al-bina'u jaamiyah // gender matching not required.
hadhihi l-khashabu qaa'imatun lil-khiwaan.

#### When there is no referent for ;ism_fail;

For example:

(@) ra2aytun 3aaqilan min bani fulaan
    [phd su3ood al-Saa3idi 104]{.citex}  

Since there is no prior referent in the sentence for a ;faa3il; of the ;ism_fail; to refer to,
thus in this case the ;ism_fail; will have no ;faa3il;.


---

gender matching
number matching
drvaniya

When the ;ism_fail; is not a verb-like governor, then the ;mustatir; ;faa3il; pronoun is not implicated.
This is in the following cases:

When the ;ism_fail; is used as a common noun.


## Replacing the ;mustatir; ;faa3il; pronoun with an ;zaahir; noun

zaydun hindun DAribuhaa huwa

Abuuhu

ism_fail remains singular. Matches doer in gender

xabar is still mufrad, not a jumlah

## The ;sababi; ;na3t;

We mentioned in section\ (ref) above that the ism_fail requires a faa3il whenever it is acting as a verb-like gov.
And this includes when the ism_fail is a ;sifah;.
And we have examples of an ism_fail as a ;sifah; when it is a ;xabar;
But the ;sifah; is also used as a ;na3t;.
Here too, the ;faa3il; of the ;ism+fail; is implicated.
It refers back to ;manut;
And again it is the reason why the ;ism_fail; gets a mark of femininity to match the gender of the manut when the manut is feminine.

DIAGRAM use [hiya] as implicated faa3il.

Now, just like the ;mustatir; faa3il pronoun can replaced with an ;zaahir; noun when it is a xabar,
so too

** Important ** : Hidden pronoun requires gender matching of ism_fail to its mufassir


## Meaning implication of using the ;ism_fail; instead of the verb

## Improper annexation (maybe its own chapter)

yaqoom
qaa'im.
