# The noun as a verb-like governor

## Introduction

There are some nouns that are like verbs.
In that they may have the meaning of a verb (like the ;masdar;),
or they have be derived from a verb (like the ;mushtaqq;s: the ;ism_fail;, the ;ism_maful;, etc.).

In this chapter we will study their ability to govern a ;faa3il; or a ;maful;.

## The ;ism_fail; as a governor

Consider the verb
yaDribu.
For example:

(@) zaydun yaDribu 3amran

The sentence is parsed as follows:
* zaydun is a ;mubtada;
* The ;xabar; of zaydun is the inner sentence yaDribu 3amran
* yaDribu is a ;ustate; verb. It governs its a singular masculine ;mustatir; pronoun in the ;ustate; as its ;faa3il;.
  The ;mustatir; pronoun refers back to the mubtada.
* 3amran is a ;mafulb; governed in the ;astate; by yaDribu.


DIAGRAM with dotted line for rabt/3aaid

Let's consider the inner sentence
yaDribu 3amran
It is a complete sentence consisting a two ;3umdah; elements:

 i. The ;muxbar3;: the singular masculine ;faa3il; pronoun of the verb yaDribu
ii. The ;muxbar;: the verb yaDribu

The ;mafulb; is a ;fadlah; element, and the inner sentence will be grammatically complete without it.

The above analysis is our starting point.
Now we come to our discussion regarding the ;ism_fail;.
The ;ism_fail; is technically a noun.
But because of it derivation from the verb, it has some verbal qualities.

Instead of using the verb yaDribu in example () above
we may instead use its ;ism_fail;
DArib, thus:

(@) zaydun DAribun 3amran

Using the ;ism_fail; instead of the verb affects the meaning of the sentence.
Using DArib instead of yaDrib can be seen as asserting the fact that Zayd is beating 3amr.
We wil study the meaning implications of using an ;ism_fail; vs a verb in more detail in section\ (ref) below.
For now, let's focus on the grammar of the new sentence.
If we parse example () we get the following analysis:

* zaydun is a ;mubtada; in the ;ustate;.
* DAribun is the ;xabar; of the ;mubtada; in the ;ustate;.
  It governs its a singular masculine ;mustatir; pronoun in the ;ustate; as its ;faa3il;.
  The ;mustatir; pronoun refers back to the mubtada.
* 3amran is a ;mafulb; governed in the ;astate; by yaDribu.

DIAGRAM with dotted line for rabt/3aaid

Note that, just like the verb yaDribu,
DAribun now governs a ;faa3il; and the ;mafulb;.

Implicating the ;mustatir; ;faa3il; pronoun is essential for the grammar of the sentence.
And we will get to it in section\ (ref) below.
But before we do that, let's discuss an important difference of the new sentence () zaydun DAribun 3amran from the old sentence () zaydun yaDribu 3amran:

And that is that
Daribun 3amran
is not an inner sentence.
This is because it is not a complete sentence.
The single word DAribun itself is the ;xabar; of zaydun.
The two ;3umdah; elements are:
zayd (the ;muxbar3;), and DAribun (the ;muxbar;).
The ;mustatir; singular masculine ;faa3il; pronoun) does not make an inner sentence with its governor DAribun.
<!--
We can understanding this by seeing that we can say 
-->
So
yaDribu 3amran
as a complete sentence to mean "He beat 3amr."
But we cannot say
DAribun 3amran.
as a complete sentence.
DAribun 3amran
requires Zaydun as a ;mubtada; to form one complete sentence.

So, for example, if this was a sentence with kaana,
then DArib (alone) will be in the ;astate; as the ;xabar; of kaana.

(@) kaana zaydun DAriban 3amran

This is similar to:

(@) kaana zaydun muntaliqan

where muntaliqan, as a sinle noun, is the ;xabar; of kaana.^[But see also Peled 207]

<!--
Nevertheless,
the ;mustatir; ;faa3il; pronoun is an integral part of the ;ism_fail; DArib and is governed by it in the ;ustate;.
-->

## The ;mustatir; ;faa3il; pronoun of the ;ism_fail;

In example () zaydun DAribun 3amran above,
we stated that the ;ism_fail;
DAribun
has a (;mustatir;) ;faa3il; pronoun.

The ;ism_fail; requires a ;faa3il; whenever it is acting in a verb-like capacity.
This includes when the ;ism_fail; is used as a ;sifah;,
like qaaim "standing".
This is because the ;sifah; meaning of an ;ism_fail; is derived from its verbal meaning
(qaama yaqoom "he stands").

So, for example, if we say:

(@) zaydun qaaimun

then qaaimun has a ;mustatir; ;faa3il; pronoun attached after it, just like if we had said
zaydun yaqoom.
This ;faa3il; pronoun points back to the ;mubtada; zaydun.

DIAGRAM

The fact that the verbal/adjectival ;ism_fail; requires a ;faa3il;
is,
in fact,
the reason why a ;ism_fail; (when used with its verbal/adjectival meaning) in the ;xabar; will match the ;mubtada; in gender.^[drvaniya]

hindun qaaimatun

DIAGRAM

The mark of femininity [ة]{.ar} indicates the the ;faa3il; (the ;mustatir; pronoun which refers back the the ;mubtada; hindun) is feminine.
This is perfectly analagous to when a verb (that has the mark of femininity) is used in the ;xabar;

hindun qAmat

<!--
## The ;baariz; ;faa3il; pronoun

Consider sentence:

(@) zaydun 3amrun DAribuhu

In the above sentence
-->

If we dualize or pluralize the ;mubtada;,
then the ;xabar;, and its ;mustatir; ;faa3il; pronoun is also dualized or pluralized (repectively).
For example:

(@) al-zaydaani qaaimani
    (The ;mustatir; ;faa3il; of qaaimani is now theorized to be humaa, not huwa.)

Note, however, that the ;faa3il; remains a ;mustatir; pronoun.
That is, the alif in the dual ending Ani is not considered the ;faa3il; pronoun.
This is unlike the case of the verb where the alif in the dual (yaqoomaani) is considered the ;faa3il; pronoun.
The reason for this is that yaqoomAni is actually two (;3umdah;) elements:
the verb yaqoom and its doer.
Whereas qaaimAni is considered still one word, even with its (;mustatir;) ;faa3il; pronoun.^[sharh alfiyyah Haazimi 30/5]

<!--
The ;mustatir; ;faa3il; of the ;ism_fail; is not considered a word
(in terms of the sentence's ;3umdah; elements)
because it is a pronoun only within the confines of the sentence.
Its referent exists prior to it within the sentence
-->

Similarly, the waw in qaaimUna is simply an indicator of the plural and not the ;faa3il; pronoun.
The ;faa3il; pronoun remains ;mustatir;.

We have seen example, above, of the ;mustatir; ;faa3il; of an ;ism_fail; that is the ;xabar; of a sentence.
Similarly, an ;ism_fail; that is the ;na3t; also has a ;mustatir; ;faa3il; pronoun.
For example:

(@) ra2aytu rajulan qaaiman

DIAGRAM (pronoun points to rajulan)

The ;mustatir; ;faa3il; pronoun points back to its referent rajul.

<!--
## Substituting the ;mustatir; ;faa3il; pronoun with an apparent noun
-->

## The ;sababi; ;xabar;

Consider again example () zaydun yaDribu 3amran.
From this original sentence, we replaced the verb yaDribu with its ;ism_fail; and came up with example () zaydun DAribun 3amran.

Now consider the following example:

(@) zaydun yaDribu aBuuhu 3amran
    Zayd: his father is beating 3amr.

In example () the ;faa3il; of yaDribu is not Zayd but Zayd's father.
If we use this sentence as our starting point,
we can again replace the verb yaDrib with its ;ism_fail; DArib and say:

(@) zaydun DAribun aBuuhu 3amran
    Zayd: his father is beating 3amr.

So just like a verb can have an apparent noun as its ;faa3il; instead of a ;mustatir; pronoun,
so too can the ;ism_fail; have an apparent noun as its ;faa3il; instead of a ;mustatir; pronoun.

And again, there is one important difference between using the verb (yaDrib) vs using its ;ism_fail; (DArib).
And that is that 
yaDrib abuuhu 3amran
is a complete sentence.
In example () it is an inner sentence as the ;xabar; of the outer sentence.
Therefore () zaydun yaDrib abuuhu 3amran is a compound sentence.
But DAribun abuuhu 3amran is not a complete sentence by itself.
Rather DAribun comprises the ;xabar; as a single word.^[subki, mukhtasar al-ma3aani lil-taftaazaani 86]
So () zaydun DAribun aBuuhu 3amran is not a compound sentence.

This kind of a ;xabar;
<!--
where the ;faa3il; of the ;xabar; (abuhu) does not refer to the same person as the ;mubtada; (zaydun),
-->
where the ;xabar; (DAribun) expresses a property,
not directly about the ;mubtada; (Zayd) but someone linked to the ;mubtada; (Zayd's father),
is called a ;sababi; ;xabar;.^[<https://alababmisr.com/%D8%A7%D9%84%D8%AE%D8%A8%D8%B1-%D8%A7%D9%84%D8%B3%D8%A8%D8%A8%D9%8A-%D8%AF-%D9%88%D8%AC%D9%8A%D9%87%D8%A9-%D8%A7%D9%84%D8%B3%D8%B7%D9%84/>, see also 3uroos al-afraa7 lil-subki 1/314]

<!--
This can be made clear by looking at the following example:

(@) kaana zaydun muntaliqan

-->

Similarly, we can say:

(@) kāna Zaydun munṭaliqan ʾabūhu
    [Peled 208]

muntaliqan alone is the ;xabar; of a kaana.
Therefore it is in the ;astate;.
It is a single word and not a sentence.^[But see also Peled 207]

Just like in the case of a verb,
the gender of ;ism_fail; matches the gender of its ;faa3il;.
If the ;faa3il; of the ;ism_fail; is feminine,
then the ;ism_fail; is feminized to match it, just like a verb would be.
Examples:

(@) zaydun qaaimatun ummuhu  
    (compare to zaydun qaamat ummuhaa)

(@) kaanat hindun qaaimun Abuuhaa
    (Compare to kaanat hindun qaama Abuuhaa)

If the ;faa3il; is dualized or pluralized,
then the ;ism_fail; generally remains in the singular, just like a verb would be.
For example:

(@) kaana alzaydAni qaaiman abawaahuma

(@) inna zaydan qaaimatun akhawaatuhaa

(@) kaanat hindun qaaiman ikhwatahaa

However, as an exception, if a broken plural exists for the ;ism_fail;,
then it may be used, and even preferred to use it for the plural ;faa3il;.^[basIt ibn abi al-rabee3 693--694 cited by Peled 208 fn 33]
For example:

(@) kaana al-zaydUna qiyaaman aabaauhum

By the way, when the ;faa3il; of the ;ism_fail; is an apparent noun,
there is a non-;sababi; way to form the sentence.
And that is to consider the ;ism_fail; the fronted ;xabar; of an inner sentence, thus:

(@) kāna Zaydun munṭaliqun ʾabūhu
    [Peled 208]{.citex}  

In example () above 
munṭaliqun ʾabūhu
forms an inner sentence where muntaliqun is a fronted ;xabar; and abuhu is the ;mubtada;.
Now kaana does not cause muntaliq to take the ;astate; because the ;xabar; of kaana is the entire inner sentence.
And if we were to dualize or pluralize the the ;mubtada; of the inner sentence (abuhu),
its ;xabar; would match it, thus:

(@) kāna al-Zaydāni munṭaliqāni ʾabawāhumā
    [Peled 208]{.citex}  

Having said that, the ;sababi; formation
is preferred over the non-;sababi; formation.^[basIt ibn Abi al-rabee3 694]

Here is another example:

(@) fa'innahu aathimun qalbuhu

## The ;sababi; ;na3t;

## The ;sababi; ;hal;

Will discuss in chapter\ (ref) section\ (ref).

## Cases where the ;ism_fail; does not govern a ;faa3il;

From the discussion above,
we can see that the ;ism_fail; typically governs a ;faa3il; that occurs after it in sentence word-order.
This ;faa3il; is usually ;mustatir; but can be apparent, for example in ;sababi; sentences.
There are, however, some cases where the ;ism_fail; will not have a ;faa3il;.
These are:

#### When the ;ism_fail; is used with a substantive meaning {.unnumbered}

As we know from chapter\ (ref), an ;ism_fail; can acquire a substantive meaning.
For example,
jaami3ah univ
qaaimah leg.
When used with a substantive meaning, the implication of the verb is now remote, and the ;ism_fail; behaves like any other substantive in that it won't have a ;faa3il;.^[@nahw_wafi@ 1/232]
And this is the reason why,
when the ;ism_fail; is used as a substantive in the ;xabar;,
then it does not need to match ;mubtada; in gender.
In other words, there is no ;mustatir; ;faa3il; pronoun,
which refers back to to the ;mubtada;
to cause the ;ism_fail; to get a mark of feminiity.

al-bina'u jaamiyah // gender matching not required.
hadhihi l-khashabu qaa'imatun lil-khiwaan.

#### When there is no referent for ;ism_fail;

For example:

(@) ra2aytun 3aaqilan min bani fulaan
    [phd su3ood al-Saa3idi 104]{.citex}  

Since there is no prior referent in the sentence for a ;faa3il; of the ;ism_fail; to refer to,
thus in this case the ;ism_fail; will have no ;faa3il;.

What about [والحافظين فروجهم]{.ar}??
maybe it has a doer pronoun referring to the ism_mawsool [الذين]{.ar} before it?

## Necessary conditions in order for the ;ism_fail; to govern a ;mafulb;

In example () zaydun DAriban 3amran
we saw that the ;ism_fail; DAriban governs a ;mafulb; 3amran.
There are conditions that must be satisfied in order for an ;ism_fail; to be able to govern a ;mafulb; in this manner.
The conditions are different for when the ;ism_fail; is defined by [ٱلْ]{.ar},
and when it is without [ٱلْ]{.ar}.
We will discuss each of these cases separately below:

#### When the ;ism_fail; is not defined by [ٱلْ]{.ar} {.unnumbered}

When the ;ism_fail; is not defined by [ٱلْ]{.ar},
then two conditions must be satisfied:

1. The verbal action must be in a continuous or future tense.

   * present continuous:

     (@) [هذا ضارب زيدا الآن]{.ar}
         [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
         "This [person] is beating Zayd now."

   * past continuous:

     (@) [كان زيد ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd was beating [#eamr]{.trn2}."

     (@) [وَكَلْبُهُمْ بَاسِطٌ ذِرَاعَيْهِ بَٱلْوَصِيدِ]{.ar}
         [@https://quran.com/18/18@ cited by @ibn_aqil_alfiyyah@ 3/106]{.citex}  
         "while their dog stretched his forelegs at the entrance"

   * future:

     (@) [هذا ضارب زيدا الآن]{.ar}
         [@ibn_aqil_alfiyyah@ 3/106]{.citex}  
         "This [person] [will] beat Zayd tomorrow."

2. The ;ism_fail; must be _supported_ by a preceding element.
   This can take the following forms:

   * The ;ism_fail; occurs after a ;adat_istifham;.
     Example:

     (@) [أضارب زيد عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Is Zayd beating [#eamr]{.trn2}?"

   * The ;ism_fail; occurs after a ;nidaa; particle:
     Example:

     (@) [يا طالعا جبلا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "O scaler [of] a mountain!"

   * The ;ism_fail; occurs in a negation:
     Example:

     (@) [ما ضارب زيد عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd is not beating [#eamr]{.trn2}."

   * The ;ism_fail; occurs as a ;na3t;.
     Example:

     (@) [مررت برجل ضارب زيدا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "I passed by a man beating Zayd."

     An implied ;na3t; is also considered permissible.
     Example:

     (@) [كَنَاطِحٍ صَخْرَةً يَوْمًا لِيُوهِنَهَا فَلَمْ يَضُرَّهَا وَأَوْهَىٰ قَرْنَهُ ٱلْوَعِلُ]{.ar}
         [@ibn_aqil_alfiyyah@ 3/109]{.citex}  
         "Like the gorer of a rock, one day, to try to weaken it. But the mountain-goat does not harm it and he injures his horn."  
         ([نَاطِحٍ]{.ar} "gorer" can be considered to be a ;na3t; of an implied ;manut; [وَعِلٍ]{.ar} "a mountain goat".)



   * The ;ism_fail; occurs as a ;hal;.
     Example:

     (@) [جاء زيد راكبا فرسا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd came riding a horse."

   * The ;ism_fail; occurs as a ;xabar;, or 
     Examples:

     (@) [زيد ضارب عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd is beating [#eamr]{.trn2}."

     (@) [كان زيد ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Zayd was beating [#eamr]{.trn2}."

     (@) [إن زيدا ضارب عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "Indeed Zayd is beating [#eamr]{.trn2}."

     Included in this definition of ;xabar; are the subsequent ;mafulb;s of the ;nasix; verbs.
     Examples:

     (@) [ظننت زيدا ضاربا عمرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "I thought Zayd [was] beating [#eamr]{.trn2}."

     (@) [أعلمت زيدا عمرا ضاربا بكرا]{.ar}
         [@ibn_aqil_alfiyyah@ 3/107]{.citex}  
         "I let Zayd know [#eamr]{.trn2} [was] beating Bakr."


<https://www.alukah.net/literature_language/0/108787/%D8%A7%D8%B3%D9%85-%D8%A7%D9%84%D9%81%D8%A7%D8%B9%D9%84-%D8%A8%D9%8A%D9%86-%D8%A7%D9%84%D8%AD%D8%A7%D9%84-%D9%88%D8%A7%D9%84%D8%A7%D8%B3%D8%AA%D9%82%D8%A8%D8%A7%D9%84-%D9%88%D8%A7%D9%84%D9%85%D8%B6%D9%8A/#014>

If the verbal action is in the past but not continuous,
and an ;ism_fail; is chosen to represent the past action,
then the ;ism_fail; is, typically, not allowed to govern a ;mafulb;.
If the
semantic ;mafulb; is to be linked to the ;ism_fail;,
then they may be in a _;ma3nawi;_ ;idaafah;.
(See section\ (ref) below for _;ma3nawi;_ vs _;lafzi;_ ;idaafah;s.)
For example,

(@) [هذا ضارب زيد أمس]{.ar}
    "This [person] was the beater of Zayd yesterday."

In such cases, the ;ism_fail; will be annexed to its semantic ;mafulb;.
For example:

An exception is made for the case where the ;ism_fail; is prevented from being annexed to its semantic ;mafulb;.
This usually occurs
for transitive verbs that take more than one ;mafulb;,
like [جعل]{.ar}, [أَعطى]{.ar}, etc.
When the ;ism_fail; of such a verb is annexed to what would have been the first ;mafulb;,
then second ;mafulb; is permitted to be in the ;astate;.
For example

(@) [هذا معطي زيد أمس درهما]{.ar}

@https://tafsir.app/albahr-almuheet/35/1@

@https://tafsir.app/aldur-almasoon/35/1@

https://shamela.ws/book/13257/894#p1

Even the first ;mafulb; may remain in the ;astate;, if separated from the ;ism_fail;.
For example:

(@) [هذا ظان أمس زيدا فاضلا]{.ar}
    [https://shamela.ws/book/13257/894#p1]{.citex}



## The ;faa3il; that fulfils the role of the ;xabar;

We mentioned in sections\ (ref) above that an
;ism_fail; when governing a ;faa3il; does not constitute a complete sentence.

We gave the examples
DAriban 3amran
and
DAribun abuhu 3amran.
These don't consitute complete sentences until a ;mubtada; is added, like:
(@) zaydun DAriban 3amran
and
(@) zaydun DAribun abuhu 3amran.
Now the sentences are complete.

The ;mubtada; acts an anchoring element for the ;ism_fail;.

## The difference in meaning when a governing ;ism_fail; is used instead of a verb

The primary meaning of the ;ism_fail; is that of the doer of a verb.
Here are some examples:

[قَاتِل]{.ar} | one who kills, i.e. a killer
[ضَارِب]{.ar} | one who laughs
[قَائِل]{.ar} | one who says, i.e a sayer
[مُتَكَلِّم]{.ar} | one who speaks, i.e. a speaker


---

## Conditions for using the ;ism_fail; as a verb-like governor

There are X conditions that need to be satisfied for using the ;ism_fail; as a governor:

wa kalbuhum baasiTun dhiraa3ayhi

## Implicating the ;mustatir; ;faa3il; pronoun

<!--
The adjectival meaning of the ;ism_fail; is in its capacity as a verb-like noun.
So qaaimun standing
-->
<!--
The ;mustatir; ;faa3il; pronoun accompanies its governing ;ism_fail; in most cases.
-->
The ;ism_fail; is requires a ;faa3il; whenever it is acting as a verb-like governor.
This includes when the ;ism_fail; is used as a ;sifah;.
This is because the ;sifah; meaning of an ;ism_fail; is derived from its verbal meaning.
And the use of the ;ism_fail; as a ;sifah; satsfies the conditions for the ;ism_fail; being a verb-like governor
because it signifies a description that is applicable in the present tense.

For example
qaa'imun
"standing"
gets this adjectival meaning from the verb
qaama yaqoomu.

Zaydun qaaimun.
Zayd is presently standing

kaana zaydun qaaiman
Zayd was (presently) standing.

The fact that the ;ism_fail; requires a ;faa3il; when acting as a verb-like governor is,
in fact,
<!--
It is in fact
-->
the reason why a ;ism_fail; (when used with its verbal meaning) in the ;xabar; will match the ;mubtada; in gender.

hindun qaaimatun

The mark of femininity [ة]{.ar} indicates the the ;faa3il; (the ;mustatir; pronoun which refers back the the ;mubtada; hindun) is feminine.
This is perfectly analagous to when a verb (that has the mark of femininity) is used in the ;xabar;

hindun qAmat

### Cases when the ;ism_fail; will not have a ;faa3il;

#### When the ;ism_fail; is used with a substantive meaning {.unnumbered}

As we know from chapter\ (ref), an ;ism_fail; can acquire a substantive meaning.
For example,
jaami3ah univ
qaaimah leg.
When used with a substantive meaning, the implication of the verb is now remote, and the ;ism_fail; behaves like any other substantive in that it won't have a ;faa3il;.
And this is the reason why,
when the ;ism_fail; is used as a substantive in the ;xabar;,
then it does not need to match ;mubtada; in gender.
In other words, there is no ;mustatir; ;faa3il; pronoun,
which refers back to to the ;mubtada;
to cause the ;ism_fail; to get a mark of feminiity.

al-bina'u jaamiyah // gender matching not required.
hadhihi l-khashabu qaa'imatun lil-khiwaan.

#### When there is no referent for ;ism_fail;

For example:

(@) ra2aytun 3aaqilan min bani fulaan
    [phd su3ood al-Saa3idi 104]{.citex}  

Since there is no prior referent in the sentence for a ;faa3il; of the ;ism_fail; to refer to,
thus in this case the ;ism_fail; will have no ;faa3il;.


---

gender matching
number matching
drvaniya

When the ;ism_fail; is not a verb-like governor, then the ;mustatir; ;faa3il; pronoun is not implicated.
This is in the following cases:

When the ;ism_fail; is used as a common noun.


## Replacing the ;mustatir; ;faa3il; pronoun with an apparent noun

zaydun hindun DAribuhaa huwa

Abuuhu

ism_fail remains singular. Matches doer in gender

xabar is still mufrad, not a jumlah

## The ;sababi; ;na3t;

We mentioned in section\ (ref) above that the ism_fail requires a faa3il whenever it is acting as a verb-like gov.
And this includes when the ism_fail is a ;sifah;.
And we have examples of an ism_fail as a ;sifah; when it is a ;xabar;
But the ;sifah; is also used as a ;na3t;.
Here too, the ;faa3il; of the ;ism+fail; is implicated.
It refers back to ;manut;
And again it is the reason why the ;ism_fail; gets a mark of femininity to match the gender of the manut when the manut is feminine.

DIAGRAM use [hiya] as implicated faa3il.

Now, just like the ;mustatir; faa3il pronoun can replaced with an apparent noun when it is a xabar,
so too

** Important ** : Hidden pronoun requires gender matching of ism_fail to its mufassir


## Meaning implication of using the ;ism_fail; instead of the verb

## Improper annexation (maybe its own chapter)

yaqoom
qaa'im.
