# Additional forms of the verb

## Introduction

So far we have been studying the form 1 verb ([فَعَلَ يَفُعَلُ]{.ar}).
The form 1 verb is the basic form of the verb.
It consists of only the three root letters for the stateless verb.

In this chapter we will learn additional forms of the verb.
These forms add extra letters to three root letters.
There are about 15 or so additional forms of the verb.
But only 10 or so are in common usage.

Learning these additional forms may seem tedious but we advise you to persevere
because additional forms of the verb are used very commonly.

The form 1 verb has variability in the middle ([ع]{.ar}) letter, which can have either an [a]{.trn}, [i]{.trn}, or [u]{.trn} mark.
It also has variability in the pattern its verbal noun of doing.
The additional forms have almost no variability of this kind.
So, in one sense, the additional forms of the verb are easier than the form 1 verb.

### Topics to cover

+ usage of the masdar of one form for another form
+ [افتعل]{.ar} with the meaning of [تفاعل]{.ar} and nuances in the meaning
+ avoid using [مع] with form 6, unless as masdar. (Actually added it to Usage and Style chapter in appendix but reference it here.)

## The form 2 verb [فَعَّلَ يُفَعِّلُ]{.ar}

The form 2 verb doubles the middle [ع]{.ar} letter.
The vowel mark on the middle letter does not vary.
Here are some examples of form 2 verbs:

| Root | Verb | Meaning |
|:--|:----|:-------|
|[علم]{.ar}|[عَلَّمَ يُعَلِّمُ]{.ar}| to teach |
|[قتل]{.ar}|[قَتَّلَ يُقَتِّلُ]{.ar}| to massacre |
|[كبر]{.ar}|[كَبَّرَ يُكَبِّرُ]{.ar}| to magnify, say [ٱَللَّـٰهُ أَكْبَرُ]{.ar} |

### Meaning patterns

The form 2 verb can denote a strengthening of the meaning. For example, 

+ [كَسَرَ]{.ar} "to break ([هـ]{.ar} s.th.)"; [كَسَّرَ]{.ar} "to smash ([هـ]{.ar} s.th.)"
+ [قَتَلَ]{.ar} "to kill ([ه]{.ar} s.o.)"; [قَتَّلَ]{.ar} "to massacre ([ه]{.ar} s.o.)"

Often it denotes a causative meaning. For example,

+ [طَهُرَ]{.ar} "to be pure", [طَهَّرَ]{.ar} "to purify ([ه، هـ]{.ar} s.o., s.th.)"
+ [عَلِمَ]{.ar} "to know ([هـ]{.ar} s.th.)", [عَلَّمَ]{.ar} "to teach ([ه ب]{.ar} or [ه هـ]{.ar} s.o. s.th.)"

Note that in such cases, if the form 1 verb is intranstive (e.g. [طَهُرَ]{.ar}) then it becomes transitive in form 2 ([طَهَّرَ]{.ar}).
And if it is transitive in form 1 (e.g. [عَلِمَ]{.ar}), then it becomes doubly transitive in form 2 ([عَلَّمَ]{.ar}).

## The form 3 verb [فَاعَلَ يُفَاعِلُ]{.ar}

The basic meaning pattern for the form 3 verb is to express or emphasize the relation of the action to someone else.

Sometimes, as an extension of the basic meaning, it expresses vying with someone in the action of the verb. For example:

+ [قَتَلَ]{.ar} "to kill ([ه]{.ar} s.o.)", [قَاتَلَ]{.ar} "to fight ([ه]{.ar} s.o., with s.o., or against s.o.)", i.e., "to vie with another to kill him".
+ [سَبَقَ]{.ar} "to precede ([ه، هـ]{.ar} s.o., s.th.)", [سَابَقَ]{.ar} "to race ([ه]{.ar} s.o.)", i.e., "to vie with another to precede him".


