# Adjectival nouns and descriptive noun phrases

## Introduction

So far we have studied common nouns like [رَجُل]{.ar} [rajul]{.trn} "a man" and  [بَيْت]{.ar} [bayt]{.trn} "a house". 
<!--These are called designative nouns because the noun designates a specific object or entity.-->

In this chapter we will study *adjectival nouns*. Adjectival nouns are a class of nouns that don't denote objects. Rather they describe some quality of an object.

## Adjectives in English

In English we usually use adjectives to describe nouns. For example, the word "big" is an adjective. It can be used in a couple of different ways:

1. It can be used to describe a noun in an descriptive noun-phrase. For example:

   "a big car"

2. The adjective "big" can also be used as the ;xabar; of a sentence, describing the ;mubtada; noun. For example:

   "The car is big."

But the adjective "big" cannot be used by itself as a noun, for example, as the ;mubtada; of a sentence. So we can't say:

$\times$ "The big is fast."

We would have to say something like:

"The big car is fast."

instead.

## Terminology: the _describer_ and the _describee_

We take this opportunity to introduce some grammatical terminology. The descriptive noun-phrase "a big car" consists of two parts:

i. The adjective "big". It is describing the car. We will call it the _describer_ in the noun-phrase.
ii. The common noun "a car": It is being described by the describer. We will call it the _describee_.

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text=a big car,
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, below=0.5ex, left=0.2ex, rotate=90] {\scriptsize describer};

\draw [decoration={brace, mirror}, decorate] 
   (word-3.south west) -- (word-3.south east)
      node [midway, below=0.5ex, left=0.2ex, rotate=90] {\scriptsize describee};

\end{tikzpicture}
```

We will reserve this terminology of _describer_ and _describee_ only for the noun and adjective in an descriptive noun-phrase. So we won't use this terminology for the sentence: "The car is big."

Instead, here we will continue to use the existing terminology of _;mubtada;_ and _;xabar;_. The definite noun "the car" is the ;mubtada; of this sentence, and the adjective "big" is the ;xabar;.

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text={The car is big.},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-2.south east)
      node [midway, below=0.5ex] {\scriptsize subject};

\draw [decoration={brace, mirror}, decorate] 
   (word-4.south west) -- (word-4.south east)
      node [midway, below=0.5ex] {\scriptsize comment};

\end{tikzpicture}
```

## Adjectival nouns in English

Consider the English word "antique". It is what we will call a _adjectival noun_. 
<!--It describes some quality of the object it refers to.-->

It can be used just like an adjective to describe a noun as part of a noun-phrase. For example:

"The antique table is expensive."

In the above sentence the adjective "antique" is a describer and is describing the noun "table".

It can also be used as the ;xabar; of a sentence, just like an adjective. For example:

"The table is antique."

But what makes it different from an normal adjective is that it can also be used by itself as a noun. For example:

"The antique is expensive."

Here "the antique" could refer to any entity that can be described by the quality of being old and valuable. The adjectival noun does not require any other noun in this sentence and can stand on its own as the ;mubtada; of the sentence.

Adjectival nouns are rare in English. Instead, adjectives are usually used when we want to describe a noun.

## Adjectival nouns in Arabic and genderizability

<!--In Arabic, however, the situation is reversed. -->
Arabic does not have adjectives. It only has adjectival nouns.

The word [صَغِير]{.ar} [SagIr]{.trn} is an example of an indefinite adjectival noun in Arabic. It describes the quality of being "small" or "little". It can be used to denote any person, animal, or things that can be described as being small. Technically we could translate it as "a little one~m~" or "a small one~m~".

Being a noun [صَغِير]{.ar} [SagIr]{.trn}, like all other nouns in Arabic, will have a grammatical gender. Since it does not end with a feminine marker like [ة]{.ar}, we can state that 
[صَغِير]{.ar} [SagIr]{.trn} is a masculine noun.

Adjectival nouns, typically, are genderizable. This means that we can feminize 
[صَغِير]{.ar} [SagIr]{.trn} (masc.) to get the feminine noun.
We will feminize 
[صَغِير]{.ar} [SagIr]{.trn} (masc.) with the feminine marker [ة]{.ar} to get the feminine adjectival noun
[صَغِيرَة]{.ar} [SagIrah]{.trn} (fem.) "a little one~f~".

Generally, the dictionary will typically only supply the masculine adjectival noun.
And we are expected to know how to feminize it to get the feminine adjectival noun.

As opposed to adjectival nouns, common nouns are not genderizable. So, for example, if we know that the noun
[غُلَام]{.ar} [gulAm]{.trn} "a boy" exists, we cannot assume that we can feminize it, by using the feminine marker [ة]{.ar}, for example, getting: $\times$ [غُلَامَة]{.ar} [gulAmah]{.trn}. This would be a misguided attempt to obtain the meaning for "a girl" in Standard Arabic. Instead, we have to look up the Arabic word for "a girl" in the dictionary separately, and we find that it is [جَارِيَة]{.ar} [jAriyah]{.trn}.

Many times times, a masculine/feminine common noun pair will exist, that differ only by the feminine marker [ة]{.ar}. For example: 

+ [ٱِبْن]{.ar} [Eibn]{.trn} "a son" and [ٱِبْنَة]{.ar} [Eibnah]{.trn} "a daughter".
+ [مُعَلِّم]{.ar} [mueallim]{.trn} "a teacher~m~" and [مُعَلِّمَة]{.ar} [mueallimah]{.trn} "a teacher~f~"

This does not indicate that the common noun is genderizable. Rather, when the common noun masc./fem. pair has a meaning that is derived from a verb or an adjective (like
[مُعَلِّم]{.ar}/[مُعَلِّمَة]{.ar}),
then the masculine/feminine pair are co-derived as separate non-genderizable words. We will discuss this in more detail in later chapters, if [_allAh]{.trn2} wills.

And when the common noun masc./fem. pair has a primitive (non-verbal and non-adjectival) meaning, (like
[ٱِبْن]{.ar}/[ٱِبْنَة]{.ar}),
then this is only a coincidence. We alluded to this in section\ \@ref(related-nouns-for-male-and-female-animate-beings).

### Examples of Arabic adjectival nouns

Here are some examples of Arabic adjectival nouns that we will use in this chapter.

Arabic adjectival noun    | Meaning
:------------------|:------------
[كَبِير]{.ar}    [kabIr]{.trn}  | a big one
[صَغِير]{.ar}    [SagIr]{.trn}  | a small one
[طَيِّب]{.ar}     [Tayyib]{.trn} | a good one
[قَدِيم]{.ar}    [qadIm]{.trn}  | an old one
[جَدِيد]{.ar}    [jadId]{.trn}  | a new one
[طَوِيل]{.ar}    [TawIl]{.trn}  | a long/tall one
[وَاسِع]{.ar}    [wAsie]{.trn}  | a wide one
[عَرَبِيّ]{.ar}    [earabiyy]{.trn} | an Arab
[مَشْهُور]{.ar}   [machUr]{.trn} | a famous one

## The describer and the describee in descriptive noun-phrases

Let's learn how descriptive noun-phrases are formed in Arabic.

We learned in section\ \@ref(terminology-the-describer-and-the-describee)
above that descriptive noun-phrases consist of a describer and a describee. 

In English descriptive noun-phrases, like "the small house", the adjective describer ("small") comes before the describee ("house"). Also, only one definite article ("the") is used before the entire noun-phrase.

Here is the equivalent Arabic descriptive noun-phrase:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text= \txarb{ٱلصَّغِيرُ} \txarb{ٱَلْبَيْتُ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace}, decorate] 
   (word-1.north west) -- (word-1.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize describer};

\draw [decoration={brace}, decorate] 
   (word-2.north west) -- (word-2.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize describee};

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-2.south east)
      node [midway, below] {\scriptsize descriptive noun-phrase};

\path (0,0) node [midway, below=10ex, right=0ex, align=left] {``the small house''\\(literally: ``the small-one house'')};

\end{tikzpicture}
```

<!--
[ٱَلْبَيْتُ ٱلصَّغِيرُ]{.ar}  
[Ealbaytu -SSagIru]{.trn}  
"the small-one house" = "the small house"
-->

Note the following:

+ The adjectival noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" comes after the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house".
+ Both the adjectival noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" and the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" get the definite article [ٱَلْ]{.ar} "the".
+ The adjectival noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" is genderized to match the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" in gender.
+ The adjectival noun describer [ٱَلصَّغِير]{.ar} [EaSSagIr]{.trn} "the small one~m~" matches the describee [ٱَلْبَيْت]{.ar} [Ealbayt]{.trn} "the house" in state. In this example, they were both in the u-state but we will see examples in the other states as well.
+ The word-for-word equivalence of the above descriptive noun-phrase is "the small-one house" but we will usually give the more natural translation: "the small house"

Let's try another example: let's try to translate the sentence: "The little girl took a new book from the good mother."

Here is the sentence in Arabic:

[أَخَذَتِ ٱلْجَارِيَةُ ٱلصَّغِيرَةُ كِتَابًا جَدِيدًا مِنْ ٱلْأُمِّ ٱلطَّيِّبَةِ.]{.ar}  
[Eaxapati -ljAriyatu -SSagIratu kitaban jadIdan mina -lEummi -TTayyibah.]{.trn}  
"The little girl took a new book from the good mother."

This sentence has three descriptive noun-phrases. We will analyze each one individually:

i. [ٱَلْجَارِيَةُ ٱلصَّغِيرَةُ]{.ar}  
   [EaljAriyatu -SSagIratu]{.trn}  
   "the little girl"

   In this phrase the definite feminine noun [ٱلْجَارِيَةُ]{.ar} [EaljAriyatu]{.trn} is the ;fail; of the verb [أَخَذَ]{.ar} [Eaxapa]{.trn} "took". Therefore it is in the u-state. It is also the describee in the descriptive noun-phrase. Its describer [ٱَلصَّغِيرَةُ]{.ar} [EaSSagIratu]{.trn} follows the describee and is made to match the describee in state (u-state), gender (feminine), and definiteness (definite).

ii. [كِتَابًا جَدِيدًا]{.ar}  
    [kitAban jadIdan]{.trn}  
    "a new book"

    In this phrase the indefinite masculine noun [كِتَابًا]{.ar} [kitAban]{.trn} is the ;mafulb; of the verb [أَخَذَ]{.ar} [Eaxapa]{.trn} "took". Therefore it is in the a-state. It is also the describee in the descriptive noun-phrase. Its describer [جَدِيدًا]{.ar} [jadIdan]{.trn} follows the describee and is made to match the describee in state (a-state), gender (masculine), and definiteness (indefinite).

iii. [ٱَلْأُمِّ ٱلطَّيِّبَةِ]{.ar}  
     [EalEummi -TTayyibati]{.trn}  
     "the good mother"

      In this phrase the definite feminine noun [ٱلْأُمِّ]{.ar} [EalEummi]{.trn} is following the preposition [مِنْ]{.ar} [min]{.trn} "from". Therefore it is in the i-state. It is also the describee in the descriptive noun-phrase. Its describer [ٱَلطَيِّبَةِ]{.ar} [EaTTayyibati]{.trn} follows the describee and is made to match the describee in state (i-state), gender (feminine), and definiteness (definite). 

      Note carefully that the describer matches the describee in gender, not necessarily in having the same [ة]{.ar} ending. The feminine adjectival noun describer [ٱَلطَيِّبَة]{.ar} [EaTTayyibah]{.trn} is still formed using the feminine marker [ة]{.ar}, despite the feminine describee [ٱَلْأُمّ]{.ar} not having the [ة]{.ar} feminine marker.

<!--
[حَمَلَتِ ٱلْأُمُّ ٱلطَّيِّبُ جَارِيَةً صَغِيرَةً بِيَدٍ قَوِيَّةٍ.]{.ar}  

"The tall strong mother took an old and heavy book from the little girl."
-->

Sometimes, a common noun of one gender is used to refer to persons of either gender. For example:

+ the noun [شَخْص]{.ar} [caxS]{.trn} is itself a masculine noun but it may be used to refer to both male and female persons. 

If such a noun is a describee, then we will prefer to match the describer to the grammatical gender of the noun, not the physical gender of the person it is referring to. For example:

[ٱَلْجَارِيَةُ شَخْصٌ طَيِّبٌ.]{.ar}  
[EaljAriyatu caxSun Tayyib.]{.trn}  
"The girl is a good person."

See how we preferred to use the masculine adjectival noun [طَيِّب]{.ar} [Tayyib]{.trn} instead of using the feminine [طَيِّبَة]{.ar} [Tayyibah]{.trn}.

## Adjectival nouns as the ;xabar; of a sentence

### Indefinite adjectival noun

Let's see how to use Arabic adjectival nouns as the ;xabar; of a sentence.

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text= \txarb{صَغِيرٌ.} \txarb{ٱَلْبَيْتُ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace}, decorate] 
   (word-1.north west) -- (word-1.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize comment};

\draw [decoration={brace}, decorate] 
   (word-2.north west) -- (word-2.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize subject};

\path (0,0) node [midway, below=8ex, right=0ex, align=left] {``The house is small.''\\(literally: ``The house is a small-one.'')};

\end{tikzpicture}
```

<!--
[ٱَلْبَيْتُ صَغِيرٌ.]{.ar}  
[Ealbaytu SagIr.]{.trn}  
"The house is a small one." = "The house is small."
-->

In the above sentence, the indefinite adjectival noun 
[صَغِير]{.ar} [SagIr]{.trn} "a small one"
is used as the ;xabar; of a sentence. Its indefiniteness and u-state is indicated by the ;tanwin;ed ;umark; [◌ٌ]{.ar} on its end.

When an adjectival noun is the ;xabar; of a sentence, then it shall be genderized to match the gender of the ;mubtada; noun. The ;mubtada; noun in this case ([ٱَلْبَيْت]{.ar}) is masculine. Therefore, the masculine adjectival noun ([صَغِير]{.ar}) is chosen.

Technically, the translation of this sentence is "The house is a small one."
However, because Arabic has only adjectival nouns and not adjectives, it is how we can express the English sentence "The house is small." Therefore we can also translate it into English as such.

Now let's try a sentence with a feminine ;mubtada;:

[ٱَلْجَارِيَةُ صَغِيرَة.]{.ar}  
[EaljAriyatu SagIrah]{.trn}  
"The girl is a little one~f~." = "The girl is little."

In the above example the ;mubtada; ([ٱَلْجَارِيَة]{.ar} "the girl") was feminine. Therefore, we feminized the masculine adjectival noun [صَغِير]{.ar} [SagIr]{.trn} with the feminine marker [ة]{.ar} to get the feminine adjectival noun
[صَغِيرَة]{.ar} [SagIrah]{.trn} "a little one~f~"
and used the feminine adjectival noun in the sentence.

### Definite adjectival noun

Let's see if a definite adjectival noun can be used in the ;xabar;. For example, we would like to say "The old tree is the big one."

The ;mubtada; of the sentence is [ٱَلشَّجَرَةُ ٱلْقَدِيمَةُ]{.ar} [Eaccajaratu -lqadImuiatu]{.trn} "the old tree".
And the ;xabar; is [ٱلْكَبِيرَةُ]{.ar} [EalkabIratu]{.trn} "the big one". When we put the two together we get:

[ٱَلشَّجَرَةُ ٱلْقَدِيمَةُ ٱلْكَبِيرَةُ]{.ar}  
[Eaccajaratu -lqadImatu -lkabIratu]{.trn}

The problem is that the above could also be interpreted as one phrase "the big old tree", and not as the complete sentence "The old tree is the big one." This is the same problem that we highlighted in section\ \@ref(chap-smp-sent-sec-def-info).

The solution, too, is the same. We insert a detached pronoun, that matches the gender of the ;mubtada;, between the ;mubtada; and the ;xabar;. So in order to get our intended meaning, we will say:

[ٱَلشَّجَرَةُ ٱلْقَدِيمَةُ هِيَ ٱلْكَبِيرَةُ.]{.ar}  
[Eaccajaratu -lqadImatu hiya -lkabIratu.]{.trn}  
"The old tree is the big one."

## Adjectival nouns used without a described noun

We have mentioned that adjectival nouns are just like other nouns that we have learned so far, in that they have gender, state, and definiteness. Can we then use
an adjectival noun by itself and not when it is describing another noun?

The answer is yes, we can. So for example, you can say:

[شَرِبَ ٱلصَّغِيرُ حَلِيبًا.]{.ar}  
[cariba -SSagIru HalIbA.]{.trn}  
"The little one drank some milk."

The above is a correct sentence. But, by itself, it is not very clear. What do we mean by "the little one"? Is it a little boy, or a little cat, or something else? So, context would be needed to know what exactly is being denoted by the adjectival noun when it is used by itself independently.

Here is the same sentence again, but this time with some clarifying context.

[حَمَلَتِ ٱلْأُمُّ ٱلصَّغِيرَ. وَشَرِبَ ٱلصَّغِيرُ حَلِيبًا.]{.ar}  
[Hamalati -lEummu -SSagIra. wacariba -SSagIru HalIbA.]{.trn}  
"The mother carried the little one. And the little one drank some milk."

So now we can tell that what is meant by [ٱلصَّغِير]{.ar} [EaSSagIr]{.trn} "the little one" here is "the baby".

## Adjectival nouns re-used as common nouns

Sometimes, an adjectival noun, through much usage, acquires the meaning of a common noun. It then gets listed with this meaning in the dictionary. We actually just saw an example above. The adjectival noun 
[صَغِير]{.ar} [SagIr]{.trn} "a little one" is commonly used to mean "a baby". Of course, context would be needed to know whether, in a particular sentence, it has its common noun meaning: "a baby", or its general adjectival noun meaning: "a little one".

The opposite of 
[صَغِير]{.ar} [SagIr]{.trn} "a little one" 
is [كَبِير]{.ar} [kabIr]{.trn} "a big one". It too has acquired the common noun meaning of "an elder person". Here is an example of its usage:

[قَدِمَ ٱلْكَبِيرُ وَوَعَظَ ٱلْغُلَامَ.]{.ar}  
[qadima -lkabIru wawaeaPa -lgulAma.]{.trn}  
"The elder arrived and admonished the boy."

When an adjectival noun gets re-used as a common noun, it loses its genderizability.
For example, the feminine adjectival noun [حَسَنَة]{.ar} [Hasanah]{.trn} (fem.) "a good one" is re-used as a common noun meaning "a good deed". So we can use it in a sentence:

[ٱلصِّيَامُ حَسَنَةٌ.]{.ar}  
[EaSSiyAmu Hasanah.]{.trn}  
"Fasting is a good deed."

The ;mubtada; in this sentence is the masculine noun [ٱَلصِّيَام]{.ar} [EaSSiyAm]{.trn} "fasting". 
And the ;xabar; is the feminine noun [حَسَنَة]{.ar} [Hasanah]{.trn} "a good deed".
Note that the ;xabar; does not match the ;mubtada; in gender. This is because it lost its genderizability since it is no longer acting as an adjectival noun "a good one~f~", but rather as the common noun "a good deed".

What if we have the sentence:

[ٱَلصَّدَقَةُ حَسَنَةٌ.]{.ar}  
[EaSSadaqatu Hasanah.]{.trn}

The feminine gender of the ;mubtada; 
[ٱَلصَّدَقَة.]{.ar} 
[EaSSadaqah]{.trn} "charity" now matches the gender of the ;xabar;
[حَسَنَة]{.ar} [Hasanah]{.trn}.
So now, technically, the ;xabar; could be the adjectival noun, meaning "a good one~f~". So the sentence could mean:

"Charity is good."

Or the ;xabar; could be the common noun, meaning "a good deed". Then the sentence would mean:

"Charity is a good deed."

Context would be needed to tell us which meaning is intended.

## Common-nouns used as describers in a noun-phrase

Usually, adjectival nouns are used as the describer in an descriptive noun-phrase. However, we also often find a common noun used as a describer. For example,

[هُوَ رَجُلٌ مُعَلِّمٌ.]{.ar}  
[huwa rajulun mueallim.]{.trn}  
"He is a teacher~m~ man."  
= "He is a man who is a teacher~m~."

## Multiple adjectival nouns describing the same noun

In English we can have a noun described by multiple adjectives separated by commas and the word "and". For example, "The building is big, tall, and wide." In Arabic we will separate the multiple adjectival nouns with [وَ]{.ar} [wa-]{.trn} "and":

[ٱَلْبِنَاءُ كَبِيرٌ وَطَوِيلٌ وَوَاسِعٌ.]{.ar}  
[EalbinAEu kabIrun waTawIlun wawAsiEun]{.trn}  
"The building is big and tall and wide."

In an English descriptive noun-phrase, multiple describers may describe the same describee, without being separated by the word "and". For example, "The man is a famous Arab writer." In Arabic, we can do the same, except the describees will be in the reverse order:

[ٱَلرَّجُلُ كَاتِبٌ عَرَبِيٌّ مَشْهُورٌ.]{.ar}  
[Earrujulu kAtibun earabiyyun machUr.]{.trn}  
"The man is a famous Arab writer." 


## A prepositional phrase separating the describer from the describee

Consider the phrase:

[كِتَابٌ مِنَ ٱلْمَكْتَبَةِ]{.ar}  
[kitAbun mina -lmaktabati]{.trn}  
"a book from the library"

<!--The prepositional phrase [مِنَ ٱلْمَكْتَبَةِ]{.ar} [mina -lmaktabati]{.trn} "from the library" is not a adjectival noun. Yet it still acts as a describer for the noun [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book", in that it is describing a quality of the book.
-->
If we want to add a adjectival noun as to describe "the book", we may add it either before or after the prepositional phrase describer. Here are both examples as complete sentences:

[قَرَأَ كِتَابًا صَغِيرًا مِنَ ٱلْمَكْتَبَةِ.]{.ar}  
[qaraEa kitAban SagIran mina -lmaktabati.]{.trn}  
AND  
[قَرَأَ كِتَابًا مِنَ ٱلْمَكْتَبَةِ صَغِيرًا.]{.ar}  
[qaraEa kitAban mina -lmaktabati SagIran.]{.trn}  
"a small book from the library"

The first option is usually chosen as a matter of preference but the second option is legitimate too.

<!--
## A prepositional phrase as the describer

Consider the phrase:

[كِتَابٌ مِنَ ٱلْمَكْتَبَةِ]{.ar}  
[kitAbun mina -lmaktabati]{.trn}  
"a book from the library"

The prepositional phrase [مِنَ ٱلْمَكْتَبَةِ]{.ar} [mina -lmaktabati]{.trn} "from the library" is not a adjectival noun. Yet it still acts as a describer for the noun [كِتَابٌ]{.ar} [kitAbun]{.trn} "a book", in that it is describing a quality of the book.

If we want to add a adjectival noun as an additional describer, we may add it either before or after the prepositional phrase describer. Here are both examples as complete sentences:

[قَرَأَ كِتَابًا صَغِيرًا مِنَ ٱلْمَكْتَبَةِ.]{.ar}  
[qaraEa kitAban SagIran mina -lmaktabati.]{.trn}  
AND  
[قَرَأَ كِتَابًا مِنَ ٱلْمَكْتَبَةِ صَغِيرًا.]{.ar}  
[qaraEa kitAban mina -lmaktabati SagIran.]{.trn}  
"a small book from the library"

The first option is usually chosen as a matter of preference but the second option is legitimate too.
-->

