# ;dhanna; and its sisters

ta3leeq, ilghaa2: Peled <https://www.academia.edu/101820592/Amal_and_ibtid%C4%81_in_Medieval_Arabic_Grammatical_Tradition>

;wip_warn;

## Introduction

There are some verbs that,
in addition to a ;faa3il;,
also
generally require two ;mafulb;s.
;dhanna; is one of these verbs.
For example:

(@) [ظَنَنْتُ زَيْدًا أَخَاكَ]{.ar}
    [@peled_sentence_types@ 188]{.citex}  
    [I thought Zayd to be your brother.]{.trans}  

There are other verbs similar to ;dhanna;.
We will study them collectively as ";dhanna; and its sisters."

## The ;isnaad; of the ;dhanna; sentence

The basic ;j_ism; consists of a ;mubtada; and a ;xabar;.
For example:

(@) [زَيْدٌ أَخُوكَ]{.ar}  
    [Zayd is your brother.]{.trans}  

In example () above,
[زَيْدٌ]{.ar}
is the ;mubtada;
and
[أَخُوكَ]{.ar}
is its ;xabar;.
Both are in the ;ucase; because it is a basic ;j_ism;.
In terms of its ;isnaad;,
[زَيْدٌ]{.ar}
is the ;musnadi;
and
[أَخُوكَ]{.ar}
is the ;musnad;.
And the sentence is ;isnaad_comp;.

Now consider the following sentence:

(@) [ظَنَنْتُ زَيْدًا أَخَاكَ]{.ar}
    [@peled_sentence_types@ 188]{.citex}  
    [I thought Zayd to be your brother.]{.trans}  

In example () above,
the verb ;dhanna;
required a ;faa3il; (as usual),
which is the pronoun [تُ]{.ar} [I]{.trans}.
And it also requires two ;mafulb;s:
[زَيْدًا]{.ar}
is the first ;mafulb;
and
[أَخَاكَ]{.ar}
is the second ;mafulb;.

This sentence is peculiar in its ;isnaad;.
This is because the two ;mafulb;s are the ;3umdah; elements.
[زَيْدًا]{.ar}
is the ;musnadi;
and
[أَخَاكَ]{.ar}
is the ;musnad;.
The sentence is only ;isnaad_comp; when both ;mafulb;s are in place.
The verb ;dhanna; and its ;faa3il; are now not the ;3umdah; elements of the sentence.
Rather ;dhanna; is part of the ;pregov;.

If one or both of the ;mafulb;s are missing,
then the sentence is not (generally) sufficiently ;isnaad_comp;:

(@) ;x; [ظَنَنْتُ زَيْدًا]{.ar}  
    [I thought Zayd]{.trans}  

(@) ;x; [ظَنَنْتُ]{.ar}  
    [I thought]{.trans}  

In examples () and () above, the listener may be left wondering,
"You thought Zayd to be what?"
and
"You thought what?",
respectively.
(But see sections () below where we discuss the possibility of only one ;mafulb; or no ;mafulb;.)

Parallels of the ;isnaad; of the ;dhanna; sentence
may be found in the ;kaana; and ;inna; sentences:

(@) [كَانَ زَيْدٌ أَخَاكَ]{.ar}
    [@peled_sentence_types@ 188]{.citex}  
    [Zayd was your brother.]{.trans}  
    ([زَيْدٌ]{.ar}, the ;faa3il;/;ism_of;, is the ;musnadi;.
    [أَخَاكَ]{.ar}, the ;mafulb;/;xabar;, is the ;musnad;.
    ;kaana; is the ;pregov;.)


(@) [إِنَّ زَيْدًا أَخُوكَ]{.ar}
    [@peled_sentence_types@ 188]{.citex}  
    [Indeed Zayd is your brother.]{.trans}  
    ([زَيْدًا]{.ar}, the ;ism_of;, is the ;musnadi;.
    [أَخُوكَ]{.ar}, the ;xabar;, is the ;musnad;.
    ;inna; is the ;pregov;.)

## The sisters of ;dhanna;


## Second ;mafulb; can be a prepositional phrase or sentence

baseet 443

## one maful 

baseet 445ff

## No maful?

[إن هم إلا يظنون]{.ar}

[إن ظن خيرا]{.ar}

