# The adverb of time and and the adverb of place

## Introduction

Consider the sentence:

"Zayd went to the market one day."

The term "one day" here is an _adverb of time_.
It describes the verb "went" and tells us the time in which the action of going ocurred.

In this chapter, we will study two kinds of adverbs in Arabic:
the _adverb of time_ and the _adverb of place_.
These two adverbs are treated together because they both describe the space (of time and place, respectedly) in which the action of a verb ocurrs.
There are other kinds of adverbs as well, and we will study them in other chapters, if [#allAh]{.trn2} wills.

The adverb, in Arabic, is a noun that qualifies a verb.
It is put in the ;astate;.
Let's express the above sentence in Arabic:



(@) [ذَهَبَ زَيْدٌ إِلَى ٱلسُّوقِ يَوْمًا.]{.ar}  
    "Zayd went to the market one day."



The noun [يَوْم]{.ar} is functioning as an adverb of time.
When used thus, as an adverb, we can translate it idiomatically as "one day" instead of "a day".

## Determining when a noun is an adverb of time or place

The term _adverb_ in Arabic grammar technically does not refer to any specific class of nouns.
Generally, nouns can be used for different functions, including as adverbs.
For example, the noun
[يَوْم]{.ar}
doesn't necessarily need to be used as an adverb.
It may be used, for example, as the ;mubtada; of a sentence:



(@) [ٱَلْيَوْمُ طَوِيلٌ.]{.ar}  
    "The day is long."



Even when it is in the ;astate;, it is not necessarily an adverb. 
Here it is as a ;mafulb;:



(@) [أَنْتَظِرُ يَوْمًا سَهْلًا.]{.ar}  
    "I wait for an easy day."



The way that we can tell when a noun is an adevrb of time or place is if it satisfies the following conditions:

1. The noun is in the ;astate;.
2. The noun is extra, such that the sentence is complete, albeit more vague, without it.
3. The noun signifies the time or place in which the verb occurred.

In the sentence [أَنْتَظِرُ يَوْمًا سَهْلًا]{.ar}, the noun [يَوْم]{.ar} is not signify the time in which the verb [أَنْتَظِرُ]{.ar} is ocurring.
So it is not an adverb of time.

Having said that, there are nouns that are used exclusively or mostly as adverbs, like [قَبْل]{.ar} "before".
So, loosely speaking, such nouns, themselves, may be referred to as adverbs.

## The adverb or time

The adverb of time is more unrestricted than the adverb of place.
So we will deal with it first.
We have already seen an example of an adverb of time in the sentence:



(@) [ذَهَبَ زَيْدٌ إِلَى ٱلسُّوقِ يَوْمًا.]{.ar}  
    "Zayd went to the market one day."



In the above example, the adverb of time [يَوْم]{.ar} is singular and indefinite.
But an adverb of time can occur in other formations as well. For example:

As a definite common noun:



(@) [ذَهَبَ زَيْدٌ إِلَى ٱلسُّوقِ ٱلْيَوْمَ.]{.ar}  
    "Zayd went to the market today."  
    ([ٱلْيَوْم]{.ar} "the day" is also used to mean "today".)



With a ;na3t;:



(@) [قَتَلْتُهُ ٱلسَّنَةَ ٱلْمَاضِيَةَ.]{.ar}
    [Wright, vol.\ ii, §44, p.\ 110A]{.citex}  
    "I killed him last year."



As a proper noun:



(@) [صُمْتُ رَمَضَانَ.]{.ar}
    [Wright, vol.\ ii, §44, p.\ 110A]{.citex}  
    "I fasted (the month of) [#ramaDAn]{.trn2}."





As an ;mudaf; to a ;mudafil;:



(@) [جِئْتُ زَمَنَ ٱلشِّتَاءِ.]{.ar}
    [Wright, vol.\ ii, §44, p.\ 110A]{.citex}  
    "I came in the winter-time."



As an ;mudaf; to a sentence:



(@) [صَحَبْتُ صَدِيقِي يَوْمَ خَرَجْنَا مِنَ ٱلْمَدِينَةِ.]{.ar}  
    "I accompanied my friend the day we left the city."



As a dual or plural:



(@) [تَأَمَّلْ شَهْرَيْنِ فِي ٱخْتِيَارِ ٱلْأُسْتَاذِ.]{.ar}
    [Wright, vol.\ ii, §44, p.\ 109D]{.citex}  
    "Reflect two months upon the choice of a teacher."





(@) [سَكَنَ فِي بَعْضِ ٱلْقُرَىٰ أَيَّامًا.]{.ar}
    [Wright, vol.\ ii, §44, p.\ 109D]{.citex}  
    "He stayed in one of the villages (a few) days."



The adverb before its verb in sentence word order^[@nahw_wafi@ 2/245]:



(@) [ٱلْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ]{.ar}
    [<https://quran.com/5:3>]{.citex}  
    "This day I have perfected for you your religion"



## The adverb of place

The adverb of place is more restricted than the adverb of time.
Only some nouns are suitable to function as adverbs of place.
Such nouns fall under some categories that we will discuss in the next few subsections:

### Vague and unbounded nouns

Generally, only vague and unbounded nouns are permitted to be used as adverbs of place.
A noun that denotes a specific place are not permitted.
So, for example, we can't use the noun [بَيْت]{.ar} as an adverb of place to say [جَلَسْتُ بَيْتًا]{.ar}.
Instead we'll have to use the preposition [فِي]{.ar} and say [جَلَسْتُ فِي بَيْتٍ]{.ar}.

Directional nouns are considered vague enough to be used as adverbs of place.
Such nouns include:

+ [أَمَام]{.ar}, [قُدَّام]{.ar} "in front (of)"
+ [خَلْفَ]{.ar}, [وَرَاء]{.ar} "behind"
+ [فَوْق]{.ar} "above"
+ [تَحْت]{.ar} "under", [أَسْفَل]{.ar} "lower", [دُون]{.ar} "beneath"
+ [يَمِين]{.ar} "right"
+ [شِمَال]{.ar}, [يَسَار]{.ar} "left"

Permitted also are general spatial nouns like:

+ [وَسْط]{.ar} "in the middle (of)"
+ [حَوْل]{.ar} "around"
+ [عِنْد]{.ar}, [لَدُنْ]{.ar}, [لَدَىٰ]{.ar} "at, with, by"
+ [مَع]{.ar} "with"
+ [بَيْن]{.ar} "between"

Some of the nouns above we have introduced previously in section (ref) as _pseudo-prepositions_.
But they are actually nouns, that when used as adverbs give meanings similar to prepositions.

<!--
These nouns can be used when indefinite. 
-->
Here is an example of the use of these nouns as adverbs of place:



(@) [نَظَرَ يَمِينًا وَيَسَارًا (وَشِمَالًا)]{.ar}
    [Wright, vol.\ ii., §44,\ p.\ 111B]{.citex}  
    "He looked right and left."



<!--But they are more likely to be used as ;mudaf;s.-->
Most of
these nouns can be, and often are, ;mudaf;s.
When they are annexed to a definite noun then they too will be definite.
But this in no way restricts their vagueness and thus ability to be used as adverbs of place.^[[شرح الرضي على الكافية]{.ar} 1/488]
For example,

(@) [بَايَعْنَا النَّبِيَّ صلى الله عليه وسلم تَحْتَ الشَّجَرَةِ]{.ar}
    [<https://sunnah.com/bukhari:7208>]{.citex}  
    "We gave the oath of allegiance to the Prophet [ﷺ]{.aralt} under the tree"

<!--
Ocassionally, instead of being an ;mudaf;, the adverb occurs as an indefinite noun and is qualified by the preposition [مِنْ]{.ar} after it.
For example:

(@) [فَقَامَ أَسْفَلَ مِنْ ذَلِکَ عِنْدَ السَّرِیرِ]{.ar}
    [[[مصنف ابن أبي شيبة - ت الحوت]{.ar} :11544](https://shamela.ws/book/9944/12868)]{.citex}  
    "So he stood lower than that at the bed"  
    (Note how [أَسْفَل]{.ar} does not take [tanwIn]{.trn2} because it is a semi-flexible noun.
-->

There are some nouns whose meaning is associated with the word "side":

+ [جَانِب]{.ar}, [نَاحِيَة]{.ar}, [وَجْه]{.ar}, [جِهَة]{.ar} "side"
+ [دَاخِل]{.ar}, [جَوْف]{.ar} "inside"
+ [خَارِج]{.ar} "outside"

With these nouns, it is more common to use prepositions like [فِي]{.ar}, [إلَىٰ]{.ar}, or [مِنْ]{.ar} before them.
For example,



(@) [نِمْتُ فِي خَارِجِ ٱلدَّارِ]{.ar}
    [Wright, vol.\ ii., §44,\ p.\ 112A]{.citex}  
    "I slept outside the house."





(@) [زَيْدٌ فِي جَانِبِ عَمْرٍو.]{.ar}  
    or  
    [زَيْدٌ إِلَىٰ جَانِبِ عَمْرٍو.]{.ar}
    [[شرح الرضي على الكافية]{.ar} 1/489]{.citex}  
    "Zayd is beside [#eamr]{.trn2}"





(@) [زَيْدٌ مِنْ خَارِجِ ٱلدَّارِ.]{.ar}
    [[شرح الرضي على الكافية]{.ar} 1/489]{.citex}  
    "Zayd is outside the house."

But they may be used, less commonly, as adverbs of place as well.
For example,



(@) [أَتَشَوَّفُ دَاخِلًا وَخَارِجًا]{.ar}
    [[[مسند أحمد]{.ar} :6520](https://shamela.ws/book/25794/4962#p1)]{.citex}  
    "I (was) looking inside and outside."



(@) [فَهُوَ مُتَّكِئٌ عَلَيْهَا دَاخِلَ الْمَسْجِدِ]{.ar}
    [[[مسند أحمد]{.ar} :15837](https://shamela.ws/book/25794/12210)]{.citex}  
    "And he (was) relying on [our arms] inside the mosque"


<!--
Universal directions like
[شَرْق]{.ar} "east"
and
[غَرْب]{.ar} "west"
too are sometimes used as adverbs of place.
The nouns [بَرّ]{.ar} "land" and [بَحْر]{.ar} "sea" also seem to be used as adverbs of place.
For such nouns, it seems more correct that they only be used as such when indefinite.
For example,

:::{.ar}
وَتَقَرَّبُوا إِلَى اللَّهِ تَعَالَى بِاتِّبَاعِهِمْ سُنَنَ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ، وَطَلَبِهِمْ لِآثَارِهِ وَأَخْبَارِهِ، بَرًّا وَبَحْرًا وَشَرْقًا وَغَرْبًا
:::
[[تأويل مختلف الحديث لابن قتيبة]{.ar}, p.\ 127]{.aside}  
"And they sought to come close to [#allAh]{.trn2} by following the practices of the Messenger of [#allAh]{.trn2} [ﷺ]{.aralt} and by seeking reports and information of him, (by) land and (by) sea, and east and west."
-->

Some place nouns are vague in that they mean "place", like
[مَكَان]{.ar},
[مَوْضِع]{.ar},
and
[مَقَام]{.ar}.
These nouns are permitted to be used as adverbs of place when indefinite.
For example:

(@) [فَتُصَلِّيَ فِي بَيْتِي مَكَانًا]{.ar}
    [<https://sunnah.com/ibnmajah:754>]{.citex}  
    "that you may pray in my house (at) a place"

When definite then they may only be used as nouns of place when
construed with a verb conveying the idea of stopping or remaining.
For example,

(@) [جَلَسْتُ مَكَانَ زَيْدٍ]{.ar}
    [Wright, vol.\ ii, §44, p.\ 111D]{.citex}  
    "I sat down in Zayd's place."

(@) [امْكُثْ مَكَانَكَ]{.ar}
    [<https://sunnah.com/abudawud:940>]{.citex}  
    "Stay (at) your place."

The noun
[مَكَان]{.ar}
is also used in an ;idaafah; to mean "in place of". 
With this meaning, it may be used as an adverb of place unrestrictedly.
For example,

(@) [خُذْ هَـٰذَا مَكَانَ ذَ\ ٰلِكَ]{.ar}
    [@nahw_wafi@ 2/261]{.citex}  
    "Take this in place of that."

So too may the noun [بَدَل]{.ar} "replacement" be used in this way.

(@) [خُذْ هَـٰذَا بَدَلَ ذَ\ ٰلِكَ]{.ar}
    [@nahw_wafi@ 2/261]{.citex}  
    "Take this in replacement of that."

Excluded from this restriction of vagueness are nouns used with the verbs [دَخَلَ]{.ar} "to enter", [سَكَنَ]{.ar} "to dwell", and [نَزَلَ]{.ar} "to alight".^[@nahw_wafi@ 2/253]
So we can say
[دَخَلْتُ ٱلدَّارَ]{.ar}
"I entered the house,"
[سَكَنْتُ ٱلْبَيْتَ]{.ar}
"I dwelled (in) the house,"
and
[نَزَلْتُ ٱلْبَلَدَ]{.ar}
"I alighted (in) the country."
The ;astate; nouns with these verbs may be considered either ;mafulb;s or adverbs of place.
Excluded also, is the country name [ٱلشَّأْم]{.ar} "Syria" with the verb [ذَهَبَ]{.ar} "to go." So we can say [ذَهَبْتُ ٱلشَّأْمَ]{.ar} for "I went (to) Syria."

### Units of distance and space

Units of distance and space are permitted to be used as adverbs of place.
For example:

<!--
(@) [سَارُوا أَرْبَعَةَ أَمْيالٍ]{.ar}
    [Wright, vol.\ ii, §44, p.\ 111B]{.citex}  
    "They travelled four miles."
-->

(@) [سَارُوا مِيلًا]{.ar}  
    "They travelled a mile."

(@) [مَشَيْتُ فَرْسَخَيْنِ]{.ar}
    [Wright, vol.\ ii, §44, p.\ 111B]{.citex}  
    "I walked two parasangs."  
    (A [فَرْسَخْ]{.ar} is a unit of distance approximately equal to three miles.)

(@) [جَرَىٰ غَلْوَةً]{.ar}
    [Wright, vol.\ ii, §44, p.\ 111B]{.citex}  
    "He ran the distance of a bowshot."

### Nouns of place

In section\ (ref) we studied the _noun of place_, which is formed on the pattern [مَفْعِل]{.ar} or [مَفْعَل]{.ar}.
The noun of place is permitted to be used as an adverb of place, but only when construed with the verb from which it is derived.
For example,

(@) [قَعَدْتُ مَقْعَدَ زَيْدٍ]{.ar},  
    [جَلَسْتُ مَجْلِسَ زَيْدٍ]{.ar}
    [Wright, vol.\ ii, §44, p.\ 112A]{.citex}  
    I sat down in Zayd's seat.

(@) [رَأَى النَّبِيَّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ ذَهَبَ مَذْهَبًا مُوَاجِهًا لِلْقِبْلَةِ]{.ar}
    [[[مسند أحمد - ط الرسالة]{.ar} :5741](https://shamela.ws/book/25794/4432)]{.citex}  
    "He saw the Prophet [ﷺ]{.aralt} going a path facing towards the qiblah."

Also included in this category are the vague place nouns
(like
[مَكَان]{.ar},
[مَوْضِع]{.ar},
and
[مَقَام]{.ar})
annexed to the verb's ;masdar;.
They may occur as adverbs of place instead of the verb's actual noun of place.
For example,

(@) [قاتلت موضع القتال]{.ar}
    [[شرح الرضي على الكافية]{.ar} 1/490]{.citex}  
    "I fought (in) the place of fighting."

## The ;naib; adverb of time and place

The adverb of time or place may be substituted by another noun.
This other noun then becomes the adverb in the ;astate; as the ;naib; of the original adverb.
The meaning of the original (substituted) adverb is then implied.
The substitute may be from the following categories:

### A qualifier

When an adverb of time or place is qualified by another noun,
then the adverb may be dropped and the qualifier may take its place.^[@maani_nahw@ 2/191]

Such qualifiers include:

* A ;na3t;:

  (@) [جلست شرقي الدار]{.ar}
      [@maani_nahw@ 2/191]{.citex}  
      "I sat east of the house."  
      (for [جلست مَكَانًا شرقي الدار]{.ar})

  (@) [جَلَسْتُ عِنْدَهُ طَوِيلًا مِنَ ٱلدَّهْرِ]{.ar}
      [Wright, 2/110B]{.citex}  
      "I sat with him (for) a long (time)."
      (for [زَمَنًا طَوِيلًا]{.ar})

* A number:

  (@) [سَارُوا أَرْبَعَةَ أَمْيالٍ]{.ar}
      [Wright, 2/111B]{.citex}  
      "They travelled four miles."  
      (Technically the number [أَرْبَعَة]{.ar} is the adverb in the ;astate;.)

* A fraction or a whole:

  (@) [لَبِثْنَا يَوْمًا أَوْ بَعْضَ يَوْمٍ]{.ar}
      [<https://quran.com/23/113>]{.citex}  
      "We remained a day or part of a day"

* A ;ism_isharah;:

  (@) [جئت هذا الوقت]{.ar}
      [@maani_nahw@ 2/191]{.citex}  
      "I came (at) this time."

  (@) [خرج محمد هذه الساعة]{.ar}
      [@maani_nahw@ 2/191]{.citex}  
      "[#muHammad]{.trn2} left (at) this hour."

  (@) [سرت هذه المسافة]{.ar}
      [@maani_nahw@ 2/191]{.citex}  
      "I travelled this distance."

### A ;masdar;

A ;masdar; may substitute an adverb of time or place if:

* the meaning "at the time of" or "the amount of time of" is implied for adverb of time;
* and the meaning "at the place of" "the amount of space of" is implied for the adverb of place.

Examples:

(@) [جَاءَ طُلُوعَ ٱلشَّمْسِ]{.ar}
    [Wright 2/110C]{.citex}  
    "He came (at the time of) the rising of the sun."  
    (for [جَاءَ وَقْتَ طُلُوعِ ٱلشَّمْسِ]{.ar})

(@) [جِئْتُ صَلَاةَ ٱلْعَصْرِ]{.ar}
    [@maani_nahw@ 2/191]{.citex}  
    "I came (at the time of) the [eaSr]{.trn2} prayer."  
    (for [جِئْتُ وَقْتَ صَلَاةِ ٱلْعَصْرِ]{.ar}.)

(@) [ٱنْتَظَرْتُهُ حَلْبَ نَاقَةٍ]{.ar}
    [@maani_nahw@ 2/191]{.citex}  
    "I waited for him (the amount of time of) the milking of a she-camel."  
    (for [ٱنْتَظَرْتُهُ مِقْدَارَ حَلْبِ نَاقَةٍ]{.ar}

(@) [جَلَسْتُ قُرْبَ زَيْدٍ]{.ar}
    [[شرح ابن عقيل على ألفية ابن مالك]{.ar} 2/200]{.citex}  
    "I sat near Zayd."  
    (literally: "I sat (at the place of) the nearness of Zayd.")

This substitution by a ;masdar; is more common for the adverb of time than for the adverb of place.^[[شرح ابن عقيل على ألفية ابن مالك]{.ar} 2/200]
<!--And it is probably limited to verbal nouns of doing of proximity and distance like [قُرْب]{.ar}.-->

## Using prepositions instead of adverbs of time and place

Often we can replace a noun used as an adverb of time or place by a preposition followed by the same noun.
This preposition is usually [فِي]{.ar}.
For example, instead of saying:
[خَرَجْتُ يَوْمًا مَاطِرًا]{.ar}
"I left (on) a rainy day,"
we can say: 

(@) [خَرَجْتُ فِي يَوْمٍ مَاطِرٍ]{.ar}  
    "I left (on) a rainy day."  
    (literally "in a rainy day".)

The noun [يَوْم]{.ar} is technically no longer an adverb since it is not in the ;astate;.
The preposition [فِي]{.ar} signifies that the verb occurs _in_ the time or place denoted by the adverb.
So, in the example above, my act of leaving ocurred _in_ a time which is denoted by "a rainy day".
In cases like the example above, the choice of whether to use an adverb or preposition is a matter of style, and is up to the speaker.

Note, however, that this substitution with [فِي]{.ar} is not always literally correct.^[@maani_nahw@ 2/179]
For example, we can't say 
$\times$\ [طار الطائر في فوق الشجرة]{.ar}
for "The bird flew above the tree."
Instead we have to say
[طار الطائر فوق الشجرة]{.ar}.
Nevertheless, the idea of [فِي]{.ar} is still correct in that the bird flew _in_ the space which is above the tree.

And sometimes, if we substitute a noun used as an adverb with [فِي]{.ar} followed by the noun,
then the sentence may be grammatically correct, but with a different meaning from the original.
Consider the following examples:

(@dharf-without-fi) [فَعَلْتُ هَـٰذَا سَبْعَةَ أَيَّامٍ]{.ar}
    [@maani_nahw@ 2/179]{.citex}  
    "I did this (for) seven days."

(@dharf-with-fi) [فَعَلْتُ هَـٰذَا فِي سَبْعَةِ أَيَّامٍ]{.ar}
    [@maani_nahw@ 2/179]{.citex}  
    "I did this (in) seven days."

Example\ (@dharf-without-fi) indicates that I did an action repeatedly during seven days.
Whereas example\ (@dharf-with-fi) indicates that I did the action once, and it took seven days to complete the action.

Similarly, consider these two examples:

(@dharf-without-fi2) [أَدْرُسُ ٱللَّيْلَ وَٱلنَّهَارَ]{.ar}
    [@maani_nahw@ 2/181]{.citex}  
    "I study night and day."

(@dharf-with-fi2) [أَدْرُسُ فِي ٱللَّيْلِ وَٱلنَّهَارِ]{.ar}
    [@maani_nahw@ 2/181]{.citex}  
    "I study in the night and day."

Example\ (@dharf-without-fi2) is about the amount of time that I study.
This is the answer to "How much do you study?"
Whereas example\ (@dharf-with-fi2) is about the period of time during which I study.
This is the answer to "When do you study?"

### Using other prepositions besides [فِي]{.ar}

While [فِي]{.ar} is the most general preposition for substituting an adverb, other prepositions are also used.
This often depends on the adverb itself.
For example, instead of saying
[أَخْرُجُ غَدًا]{.ar}
for
"I will leave tomorrow,"
we can say:

(@) [أَخْرُجُ بِالْغَدِ]{.ar}  
    "I will leave tomorrow"

And instead of saying
[نَظَرَ يَمِينًا وَشِمَالًا]{.ar}
for 
"He looked right and left,"
we can say:

(@) [نَظَرَ عَنِ ٱلْيَمِينِ وَعَنِ ٱلشِّمَالِ]{.ar}  
    "He looked right and left."

One common preposition used before a class of adverbs is [مِنْ]{.ar}.
We will discuss it separately in the next section below.

## Using [مِنْ]{.ar} before some adverbs

There are some nouns that are used as adverbs, but are also used with the preposition [مِنْ]{.ar} to give the same adverbial meaning.
Some of these nouns are
[عِنْد]{.ar}, [لَدُن]{.ar} "by, with",
[قَبْل]{.ar} "before",
[بَعْد]{.ar} "after",
[فَوْق]{.ar} "above",
[تَحْت]{.ar} "under",^[@maani_nahw@ 2/193]
etc.

Often times, [مِنْ]{.ar} signifies its literal meaning "from", as usual.
For example:

(@) [مَكَثْتُ عِنْدَكَ سَاعَةً ثُمَّ خَرَجُتُ مِنْ عِنْدِكَ إِلَىٰ بَيْتِي]{.ar}
    [@nahw_wafi@ 2/262]{.citex}  
    "I stayed at your [place] an hour, then I left _from_ your place to my house."

Other times, the significance of this [مِنْ]{.ar} is less obvious.
Consider the following examples:

(@dharf-without-min) [قَرَأْتُ ٱلْقُرآنَ بَعْدَ صَلَاةَ ٱلْعَصْرِ]{.ar}  
    "I read the ;quran; after the [eaSr]{.trn2} prayer."

(@dharf-with-min) [قَرَأْتُ ٱلْقُرآنَ مِنْ بَعْدِ صَلَاةِ ٱلْعَصْرِ]{.ar}  
    "I read the ;quran; (during a time which starts) from after the [eaSr]{.trn2} prayer."

Example (@dharf-with-min) specifies the _beginning of the time period_ that is indicated by the adverb.
Technically, this is not necessarily when the action of the verb began.
But
this usage of [مِنْ]{.ar} could be used to signify that the action started very close to the beginning of the time period.
That is, it could indicate that I started to read the ;quran; right after the [eaSr]{.trn2} prayer.^[@maani_nahw@  2/193--201, and [من الفرق بين بعد ومن بعد في اللفظ القرآني لعلي هاني]{.ar}]

Often, when the meaning of [مِنْ]{.ar} is subtle, it is not translated as "from".
For example:

(@) [لِكَيْلَا يَعْلَمَ مِنْ بَعْدِ عِلْمٍ شَيْـًٔا]{.ar}
    [<https://quran.com/22/5>]{.citex}  
    "so that he knows, after [once having] knowledge, nothing"

(@) [لِكَيْ لَا يَعْلَمَ بَعْدَ عِلْمٍ شَيْـًٔا]{.ar}
    [<https://quran.com/16/70>]{.citex}  
    "so that he will not know, after [having had] knowledge, a thing"

Sometimes it may be left untranslated.

## [قَبْل]{.ar} and its sisters

There are a class of nouns,
which are usually adverbs of time and place,
that are sometimes flexible, and sometimes rigid.
These nouns are:

* [قَبْل]{.ar} "before"
* [بَعْد]{.ar} "after"
* [دُون]{.ar} "beneath", 
* [أَسْفَل]{.ar} "lower"
* [فَوْق]{.ar} "above"
* [تَحْت]{.ar} "under"
* [أَمَام]{.ar}, [قُدَّام]{.ar} "in front"
* [خَلْف]{.ar}, [وَرَاء]{.ar} "behind"
* [عَلُ]{.ar}, [عَلْو]{.ar}, "on top"
* [أَوَّل]{.ar} "first"

Also usually included with these are^[See @nahw_wafi@ 3/142, footnote\ 1 for references to the difference of opinion regarding them]:

* [يَمِين]{.ar} "right"
* [شِمَال]{.ar} "left"
* [آخِر]{.ar} "last"

Collectively, we will call them [قَبْل]{.ar} _and its sisters_.

We have already seen some of these being used used as adverbs of time or place.
The cases for determining when they are flexible and when rigid are as follows:

a. When used as ;mudaf;s with a mentioned ;mudafil;: When used as ;mudaf;s then 
   [قَبْل]{.ar} and its sisters
   are flexible.
   For example,

   (@) [قَامَ ٱلْأَمِيرُ أَمَامَ ٱلْجَيْشِ]{.ar}  
       "The commander stood in front of the army"

    As we've previously discussed, instead of using these nouns as adverbs, it is common to also precede them with a preposition, like [مِنْ]{.ar}.
    For example:

   (@) [قَامَ ٱلْأَمِيرُ مِنْ أَمَامِ ٱلْجَيْشِ]{.ar}  
       "The commander stood in front of the army"

   In this case, whether 
   [قَبْل]{.ar} or one of its sisters
   is an adverb in the ;astate;, or following a preposition in the ;istate;, then it is flexible.
   This is indicated in the examples above by the [fatHah]{.trn2} on its ending when in the ;astate;,
   and the [kasrah]{.trn2} when in the ;istate;.


b. When used as ;mudaf;s but the ;mudafil; is not mentioned:
   Rarely, for stylistic reasons, the ;mudafil; in sentences like the example above is dropped.
   But the presence of the ;mudafil; is intended by the speaker.
   In such cases, the ;mudaf; will be flexible and without [tanwIn]{.trn2}.
   For example:

   (@) a. [قَامَ ٱلْأَمِيرُ أَمَامَ]{.ar}  
       a. [قَامَ ٱلْأَمِيرُ مِنْ أَمَامِ]{.ar}  
       "The commander stood in front [of the army]"

c. More commonly, the ;mudafil; is deleted, both in expression and in intention,
   but the adverb is still understood to be bounded implicitly.
   In this case,
   [قَبْل]{.ar} and its sisters
   will be rigid.
   Their ending will have a [Dammah]{.trn2} regardless of whether they are in the ;astate; (as an adverb) or in the ;istate; (following [مِنْ]{.ar}).
   For example:

   (@) a. [قَدِمَ ٱلْجَيْشُ وَقَامَ ٱلْأَمِيرُ أَمَامُ]{.ar}  
       a. [قَدِمَ ٱلْجَيْشُ وَقَامَ ٱلْأَمِيرُ مِنْ أَمَامُ]{.ar}  
       "The army arrived, and the commander stood in front (of the army)"

   This usage is quite common. Much more so than case b. where the ;mudafil; is dropped only stylistically.

d. Lastly,
   [قَبْل]{.ar} and its sisters
   may occur as indefinite nouns
   without an implicit or explicit ;mudafil;.
   They then have an absolute and unbounded meaning.
   In this case, they
   are flexible. <!-- and will have [tanwIn]{.trn2}.-->
   For example,

   (@) a. [قَامَ ٱلْأَمِيرُ أَمَامًا]{.ar}  
       a. [قَامَ ٱلْأَمِيرُ مِنْ أَمَامٍ]{.ar}  
       "The commander stood in front"

   In the example above, we can see that [أَمًام]{.ar} is a flexible noun due to its [tanwIn]{.trn2}.
   <!--
   The rest of 
   [قَبْل]{.ar} and its sisters
   will be similar in behavior, except for
   [أَسْفَل]{.ar},
   which is a semi-flexible noun due to its pattern, and will therefore not take [tanwIn]{.trn2}.
   It will be [أَسْفَلَ]{.ar} both, when an adverb in the ;astate;, and in the ;istate; when preceded by [مِنْ]{.ar}.
   -->

The difference in meaning between some of these cases is quite subtle.
In practice, cases a. and c. are more common.
And case b. is rare.

Here are some more examples:

(@) [يُخْرِجُ غِلْمَانَهُ إِلَى الْحَجِّ فَلَا يُحْرِمُونَ مِنْ ذِي الْحُلَيْفَةِ، يُحْرِمُونَ مِنْ أَمَامِ ذَلِكَ]{.ar}
    [[[مصنف ابن أبي شيبة - ت الحوت]{.ar} :14178](https://shamela.ws/book/9944/15870)]{.citex}  
    "He would take his (slave) boys out for the [#Hajj]{.trn2}. But they would not enter [iHrAm]{.trn2} from [#pu l-#Hulayfah]{.trn2}; they would enter [iHrAm]{.trn2} from before that [location]."

The words [أَوَّل]{.ar} and [أَسْفَل]{.ar} also have some rules that are specific to them and we will treat them separately in section\ (ref).


## The use of an adverb without an obvious verb

The adverb of time and place is associated with the verb in a sentence.
It indicates the time or place in which the action of the verb occurs.
However, there are some sentences with adverbs that do not have an obvious verb

Sometimes, this is in partial sentences, like in the response to the question
"When did you arrive?"
one may answer:

(@) [يَومَ ٱلْجُمُعَةِ]{.ar}
    [@nahw_wafi@ 2/246]{.citex}  
    "The day of Friday."  
    [يَوْم]{.ar} is used as an adverb and the verb "I arrived" is implied.

Othertimes, it may be a complete sentence.
For example:

(@) [ٱلْأَزْهَارُ أَمَامَنَا]{.ar}
    [@nahw_wafi@ 2/247]{.citex}  
    "The flowers (are) in front of us."

(@) [مَاءٌ بَارِدٌ عِنْدَ يَوْمٍ حَارٍّ نِعْمَةٌ]{.ar}  
    "Some cold water (being) on a hot day, is a blessing."

In such sentences, the missing verb is "is" or its verbal noun "being". This verb is unexpressed in Arabic.

## Multiple adverbs of place with a single verb

### Multiple adverbs with conjunctions

It is possible for multiple adverbs to be used with a single verb.
This is regularly done with using particles like [وَ]{.ar} and [فَ]{.ar}.
For example:

(@) [ٱلْتَمَسْتُهُ لَيْلًا وَنَهَارًا]{.ar}  
    "I searched for it night and day"

(@) [لَقِيتُهُ صَبَاحًا فَمَسَاءً]{.ar}
    [@maani_nahw@ 2/202 (referencing [الرضي]{.ar})]{.citex}  
    "I met him evening after morning."  
    (i.e., every morning and evening.)

(@) [لَقِيتُهُ يَوْمًا فَيَوْمًا]{.ar}  
    "I met him day after day."

### Multiple adverbs without conjunctions

If particles like [وَ]{.ar} and [فَ]{.ar}
are not used then multiple adverbs may be used for one verb in one of the following cases^[@nahw_wafi@ 2/255]:

a. When one is an adverb of time and the other an adverb of place.
   For example:

   (@) [ٱجْلِسْ عِنْدِي سَاعَةً]{.ar}  
       "Sit with  me an hour."
       ([عِنْد]{.ar} is an adverb of place and [سَاعَة]{.ar} is a adverb of time.)

b. When both are adverbs of the same kind:
   
     i. When the second adverb is a replacement for the first.
        For example:

        (@) [أُقَابِلُكَ يَومَ ٱلْجُمُعَةِ ظُهْرًا]{.ar}
            [@nahw_wafi@ 2/255]{.citex}  
            "I will meet you Friday afternoon."  
            ([ظُهْر]{.ar} is a replacement for [يَوْم]{.ar} and specifies when on Friday.)

    ii. When the adverb is a comparative noun (see chapter (ref)).
        For example:
        
        (@) [ٱلْمَرِيضُ ٱلْيَوْمَ أَحْسَنُ مِنْهُ أَمْسِ]{.ar}
            [@nahw_wafi@ 2/256]{.citex}  
            "The patient today is better than he (was) yesterday."

### Compound adverbs

Instead of using 
particles like [وَ]{.ar} and [فَ]{.ar}
between adverbs, compound adverbs may be formed.
There are two ways to form a compound adverb:^[@nahw_wafi@ 2/271, @maani_nahw@ 2/202--204]

a. Both adverbs end with a [fatHah]{.trn2} without [tanwIn]{.trn2}.
   For example,

   (@) [لَقِيتُهُ يَوْمَ يَوْمَ]{.ar}  
       "I met him day after day."

b. The adverbs form an ;idaafah;.
   For example,

   (@) [تَزُورُنَا صَبَاحَ مَسَاءٍ]{.ar}
       [@nahw_wafi@ 2/271]{.citex}  
       "You visit us morning and night."

Both options can be used more or less interchangeably.
Unless there is a compound adverb with a set meaning.
For example:

(@) [دَرَجَةُ حَرَارَةِ ٱلْجَوِّ بَيْنَ بَيْنَ]{.ar}  
    "The degree of the temperature of the air is intermediate."

## Some commonly used adverbs of time and place

### [هُنَا]{.ar} and [هُنَاكَ]{.ar}

### [أَسْفَل]{.ar}

[أَسْفَل]{.ar} is actually a comparative noun, meaning "lower".
And even when it is used as an adverb of place, it is with this comparative meaning.^[[شرح قواعد الإعراب لشيخ زاده]{.ar} 79]

Most of the directional nouns, like
[أَمَام]{.ar},
[خَلْفَ]{.ar}, [وَرَاء]{.ar},
[فَوْق]{.ar},
and
[تَحْت]{.ar}
are used as ;mudaf;s.
For example,
[فَوْقَ ٱلْأَرْضِ]{.ar}
means "above the Earth."

We have learned that comparative nouns are used with the the preposition 
[مِنْ]{.ar}
to express their "-er" meaning. 
For example [أَكْبَرُ مِنْ ٱلْبَيْتِ]{.ar} "bigger than the house."
They may also be used as ;mudaf;s to express their "-est" meaning.
For example, [أَكْبَرُ بَيْتٍ]{.ar}, [أَكْبَرُ ٱلْبُيُوتِ]{.ar} "biggest house."

[أَسْفَل]{.ar}
too may be used in both these formations.
We will discuss them below:

#### [أَسْفَل]{.ar} used before [مِنْ]{.ar}

Usually
[أَسْفَل]{.ar}
is used with
[مِنْ]{.ar}
to express the adverb of place "lower (than)"
<!--
On the other hand hand,
[أَسْفَل]{.ar},
like comparative nouns in general,
is typically used with the preposition [مِنْ]{.ar} after it.
-->
Here are some examples of
[أَسْفَل]{.ar},
as an adverb of place:

(@) [وَٱلرَّكْبُ أَسْفَلَ مِنْكُمْ]{.ar}
    ^[<https://tafsir.app/albahr-almuheet/8/42> ([وقَرَأ زَيْدُ بْنُ عَلِيٍّ: أسْفَلُ]{.ar})]
    [<https://quran.com/8/42>]{.citex}  
    "and the caravan was lower [in position] than you"

(@) [زَيْدٌ أَسْفَلَ مِنْكَ]{.ar}
    [[[كتاب سيبويه]{.ar} 3/289](https://shamela.ws/book/23018/1140)]{.citex}  
    "Zayd is lower than you."

(@) [وَضَعَ رَاحَتَيْهِ عَلَى رُكْبَتَيْهِ وَجَعَلَ أَصَابِعَهُ أَسْفَلَ مِنْ ذَلِكَ]{.ar}
    [<https://sunnah.com/nasai:1036>]{.citex}  
    "He put his palms on his knees and put his fingers lower than that."

(@) [نَهَى رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَنْ يَقُومَ الْإِمَامُ فَوْقَ شَيْءٍ وَالنَّاسُ خَلْفَهُ يَعْنِي أَسْفَلَ مِنْهُ]{.ar}
    [<https://sunnah.com/mishkat:1692>]{.citex}  
    "The Messenger of [#allAh]{.trn2} [ﷺ]{.aralt} forbade that the [imAm]{.trn2} should stand on anything when the people are behind him, meaning lower than him."

<!--
Another difference from the rest of the directional nouns is that
[أَسْفَل]{.ar}
is a comparative noun on the pattern [أَفْعَل]{.ar}. So it is a semi-flexible noun and will therefore will not take [tanwIn]{.trn2}.
-->
Note, in the examples above, that [أَسْفَل]{.ar} does not have [tanwIn]{.trn2}.
This is because it is a semi-flexible noun.

Now, in the case of 
[قَبْل]{.ar} and its sisters 
we saw that their rigidity and flexibility is determined by
whether or not they are ;mudaf;s and if they have ;mudafil;s in an ;idaafah;.

But
[أَسْفَل]{.ar},
when used with before [مِنْ]{.ar} as an adverb of place,
is not an ;mudaf;.
<!--Instead, as we have just mentioned, it is used with the preposition [مِنْ]{.ar} after it.-->
So its rigidity and flexibility is determined by whether or not it is compared to a noun (with [مِنْ]{.ar}):

If 
the adverb of place
[أَسْفَل]{.ar}
is followed by [مِنْ]{.ar} and a compared noun, then it is flexible.
By the way, there may be another [مِنْ]{.ar} before
[أَسْفَل]{.ar}
as well, as we learned in section\ (ref).
Here is an example,

(@) [إِذْ جَاءُوكُمْ مِنْ فَوْقِكُمْ وَمِنْ أَسْفَلَ مِنْكُمْ]{.ar}
    [<https://quran.com/33:10>]{.citex}  
    "[Remember] when they came at you from above you and from below you"

And if
the adverb of place
[أَسْفَل]{.ar}
is not followed by [مِنْ]{.ar} and a compared noun,
but the adverb is still understood to be bounded implicitly,
then it will be rigid ending with a [Dammah]{.trn2}.
For example:

(@) [وَقَالَ بِأَصَابِعِهِ وَرَفَعَهَا إِلَى فَوْقُ وَطَأْطَأَ إِلَى أَسْفَلُ]{.ar}
    [<https://sunnah.com/bukhari:621>]{.citex}  
    "and he gestured with his fingers and raised them up upward and lowered [them] downward."

(@) [والطَّفْرُ وَثْبٌ مِنْ أسْفَلُ الى فَوْقُ]{.ar}
    [[فقه اللغة للثعالبي]{.ar} 137]{.citex}  
    "and [aTTafr]{.trn} is a leap from down to up."

#### [أَسْفَل]{.ar} as an ;mudaf;

Most of the time,
we will want to say that something is _below_ or _lower than_ another thing.
In this case,
we will use
[أَسْفَل مِنْ]{.ar}
as we have described above.

However, sometimes,
we may want to say that something is at the _lowest_ place.
In this case, we can use
[أَسْفَل]{.ar}
as an ;mudaf; to be an adverb of place.^[See <https://tafsir.app/ibn-aashoor/95/5> ([ثُمَّ رَدَدْناهُ أسْفَلَ سافِلِينَ]{.ar}) for one interpretation of [أسْفَلَ]{.ar} as a [ظرف]{.ar}]

For example,

(@) [نَعْلُكَ أَسْفَلُ رِجْلِكَ]{.ar}
    [@nahw_wafi@ 1/484]{.citex}  
    "Your sandal is (at) the lowest [part] of your foot."  
    (Note the partitive meaning of [أَسْفَل]{.ar} annexed to a singular ;mudafil;.)

#### Non-adverbial use of [أَسْفَل]{.ar}

By the way,
[أَسْفَل]{.ar}
need not always be an adverb of place.
It may be used like other common nouns.
In the following example,
it is the ;faa3il; of a verb and also an ;mudaf;.

(@) [لَمْ تَبْتَلَّ أَسْفَلُ نِعَالِهِمْ]{.ar}
    [<https://sunnah.com/abudawud:1059>]{.citex}  
    "The lower [part] of their sandals did not get wet."

### [أَوَّل]{.ar}

[أَوَّل]{.ar} 
is used as an adverb of time, meaning "first"

Much of what we have said about 
[أَسْفَل]{.ar}
applies also to 
the noun
[أَوَّل]{.ar}.

However there is some difference from [أَسْفَل]{.ar}:

a. The meaning of "first" is inherently superlative. In English we dont say that something is _more first than_ another thing. We can try to capture this meaning by translating it as "prior to".
b. [أَوَّل]{.ar}, despite being on the pattern [أَفْعَل]{.ar}, is irregular in that it can take [tanwIn]{.trn2} when used in an absolute and unbounded sense.

#### [أَوَّل]{.ar} used before [مِنْ]{.ar}

[أَوَّل]{.ar} is a semi-flexible noun when used with [مِنْ]{.ar}:

(@) [لاَ تَسْأَلْهُ عَنْ شَىْءٍ أَوَّلَ مِنْ حَدِيثِ الشَّفَاعَةِ]{.ar}
    [<https://sunnah.com/bukhari:7510>]{.citex}  
    "Don't ask him about anything prior to the [HadIv]{.trn2} of intercession"

(@) [لاَ تَبْتَدِئَانِ بِشَىْءٍ أَوَّلَ مِنَ الْبَيْتِ، تَطُوفَانِ بِهِ]{.ar}
    [<https://sunnah.com/bukhari:1641>]{.citex}  
    "They~2f~ would not begin with anything prior to the House, performing the [TawAf]{.trn2} around it."

When [مِنْ]{.ar} is not used but [أَوَّل]{.ar} is implicitly bounded then it is rigid with a [Dammah]{.trn2} on its ending:

(@) [أَىُّ الْقُرْآنِ أُنْزِلَ أَوَّلُ]{.ar}
    [<https://sunnah.com/bukhari:4924>]{.citex}  
    "Which [part] of the ;quran; was revealed first (of all the [sUrah]{.trn2}s)?"

(@) [أَىُّ مَسْجِدٍ وُضِعَ أَوَّلُ]{.ar}
    [<https://sunnah.com/ibnmajah:753>]{.citex}  
    "Which mosque was established first (of all the mosques)?"

When [أَوَّل]{.ar},
is used in an absolute and unbounded sense,
then it takes
[tanwIn]{.trn2}
despite being on the pattern [أَفْعَل]{.ar}:

(@) [يَبْتَدِرُونَهَا أَيُّهُمْ يَكْتُبُهَا أَوَّلًا]{.ar}
    [<https://sunnah.com/nasai:1062>]{.citex}  
    "They (were) rushing (to see) which of them would write it first"

(@) [وَأَمَّا الدَّارُ الَّتِي دَخَلْتَ أَوَّلًا فَدَارُ عَامَّةِ الْمُؤْمِنِينَ]{.ar}
    [[[مسند أحمد - ط الرسالة]{.ar} :20165](https://shamela.ws/book/25794/16641)]{.citex}  
    "And as for the house that you entered first, it was for the common people of the Muslims."

(@) [أَيُّهُمَا جَاءَ أَوَّلًا عَمِلَ عَمَلَهُ]{.ar}
    [<https://sunnah.com/mishkat:1700>]{.citex}  
    "Which of them came first [that] did his deed?"

#### [أَوَّل]{.ar} as an ;mudaf;

Like [أَسْفَل]{.ar},
when 
[أَوَّل]{.ar} can be used as an ;mudaf; as well, even when it is an adverb of time.
For example

(@) [كَانَ يَنَامُ أَوَّلَ اللَّيْلِ]{.ar}
    [<https://sunnah.com/muslim:739>]{.citex}  
    "He used to sleep the first [part] of the night"

The usage of 
[أَوَّل]{.ar}
as an ;mudaf; when it is an adverb of time
is probably not as uncommon as it is for
[أَسْفَل]{.ar}.

#### Non-adverbial use of [أَوَّل]{.ar}

Just like [أَسْفَل]{.ar},
[أَوَّل]{.ar} need not be used adverbially. 
Here it is as the comment of a sentence and an ;mudaf;:

(@) [وَأَنَا أَوَّلُ ٱلْمُسْلِمِینَ]{.ar}
    [<https://quran.com/6/163>]{.citex}  
    "and I am the first [among you] of the Muslims."

Even when used non-adverbially,
[أَوَّل]{.ar} may take [tanwIn]{.trn2}.
For example, here it is the ;mubtada; of [إنَّ]{.ar} in the ;astate;:

(@) [إِنَّ لِلصَّلَاةِ أَوَّلًا وَآخِرًا]{.ar}
    [<https://sunnah.com/tirmidhi:151>]{.citex}  
    "Indeed the prayer has a first [time] and a last [time]"

### [بَعْد]{.ar}

* used for time and place
* meaning "yet"

### [ذَات]{.ar}



