# The ;masdar;

## Introduction

Every verb has a set of _verbal-nouns_ derived from it that, despite being nouns, have a verbal meaning to them. One of these verbal-nouns is the _;masdar;_, that we shall study in this chapter.

Consider the following form\ 1 verb:

| Root | ;_madi; verb | ;_mudarie; verb (;ustate;)| ;_masdar;|
|:--|:----|:-----|:----|
|[ذهب]{.ar} | [ذَهَبَ]{.ar}  "he went" | [يَذْهَبُ]{.ar}  "he goes"|[ذَهَاب]{.ar} "going"|

The ;masdar; associated with this verb is [ذَهَاب]{.ar} [pahAb]{.trn}. It denotes "the action of going", or simply "going". In this section we shall learn how this and other verbal-nouns are used.

Before we proceed, we present a new method to present a verb and its meaning in this book. 
<!--Instead of giving the above table when presenting a verb, we will say:-->
We will often give a new verb in the format:

[ذَهَبَ يَذْهَبُ ذَهَابًا]{.ar} "to go"

The ;madi; verb for the singular masculine absentee participant "he", the corresponding ;mudarie; verb, and their ;masdar; are given together, in sequence. The ;masdar; is given in the ;astate;, because of a usage that we shall learn in a later chapter, if [_allAh]{.trn2} wills. This is how verb definitions are traditionally found in Arabic dictionaries. And the English meaning is given using the dictionary definition, in this case, the phrase: "to go". 

## Patterns of the ;masdar; for form\ 1 verbs

The patterns of the ;masdar; for form\ 1 verbs are very variable. It is best to learn the ;masdar; when you learn a new verb. Having said that, there are some general trends which may be useful to keep in mind:

1. If the verb takes a ;mafulb;, then the ;madi; verb must necessarily be of the pattern [فَعَلَ]{.ar} [faeala]{.trn} or [فَعِلَ]{.ar} [faeila]{.trn} (because ;madi; verbs of the pattern [فَعُلَ]{.ar} [faeula]{.trn} never take a ;mafulb;). In this case:
   a. The ;masdar; for many verbs, in general, tends to be [فَعْل]{.ar} [fael]{.trn}. Examples:
      + [فَتَحَ يَفْتَحُ فَتْحًا]{.ar}  "to open ([هـ]{.ar} s.th.)"
      + [أَخَذَ يَأْخُذُ أَخْذًا]{.ar}  "to take ([هـ]{.ar} s.th.)"
      + [حَمِدَ يَحْمَدُ حَمْدًا]{.ar}  "to praise ([ه]{.ar} s.o.)"
2. If the verb does not take a ;mafulb;, then:
   a. If the ;madi; verb is of the pattern [فَعِلَ]{.ar} [faeila]{.trn}, then:
      i. If the meaning of the verb does not fall under the cases ii., iii., and iv. (below), then the ;masdar; tends to be, in general, of the pattern [فَعَل]{.ar} [faeal]{.trn}. Examples:
         + [تَعِبَ يَتْعَبُ تَعَبًا]{.ar}  "to become tired"
         + [جَزِعَ يَجْزَعُ جَزَعًا]{.ar}  "to be impatient"
         + [أَسِفَ يَأْسَفُ أَسَفًا]{.ar}  "to be sorrowful"
      ii. If, instead, the meaning of the verb denotes being a color, then the ;masdar; is usually of the pattern [فُعْلَة]{.ar} [fuelah]{.trn}. Examples:
          + [خَضِرَ يَخْضَرُ خُضْرَةً]{.ar}  "to be green"
          + [سَمِرَ يَسْمَرُ سُمْرَةً]{.ar}  "to be brown"
      iii. If, instead, the meaning of the verb denotes some work or effort, then the ;masdar; tends to be of the pattern [فُعُول]{.ar} [fueUl]{.trn}. Example:
           + [قَدِمَ يَقْدَمُ قُدُومًا]{.ar}  "to arrive"
      iv. If, instead, the meaning of the verb denotes some static quality, then the ;masdar; tends to be of the pattern [فُعُولَة]{.ar} [fueUlah]{.trn}. Example:
          + [يَبِسَ يَيْبَسُ يُبُوسَة]{.ar}  "to be dry"
   a. If the ;madi; verb is of the pattern [فَعَلَ]{.ar} [faeala]{.trn}, then:
      i. If the meaning of the verb does not fall under the cases ii., iii., and iv. (below), then the ;masdar; tends to be, in general, of the pattern [فُعُول]{.ar} [fueUl]{.trn}. Examples:
         + [قَعَدَ يَقْعُدُ قُعُودًا]{.ar}  "to sit, stay back"
         + [سَجَدَ يَسْجُدُ سُجُودًا]{.ar}  "to prostrate down"
         + [خَضَعَ يَخْضَعُ خُضُوعًا]{.ar}  "to be humble"
      ii. If, instead, the meaning of the verb denotes an ailment, then the ;masdar; is usually of the pattern [فُعَال]{.ar} [fueAl]{.trn}. Examples:
          + [سَعَلَ يَسْعُلُ سُعَالً]{.ar}  "to cough"
      iii. If, instead, the meaning of the verb denotes travelling, then the ;masdar; is usually of the pattern [فَعِيل]{.ar} [faeIl]{.trn}. Examples:
           + [رَحَلَ يَرْحَلُ رَحِيلًا]{.ar}  "to depart"
      iv. If, instead, the meaning of the verb denotes a sound, then the ;masdar; is usually of the pattern [فَعِيل]{.ar} [faeIl]{.trn} or [فُعَال]{.ar} [fueAl]{.trn}, or both. Examples:
          + [صَرَخَ يَصْرُخُ صَرِيخًا وَصُرَاخًا]{.ar}  "to scream"
3. If the verb denotes a craft or a profession or a rank, then the ;masdar; is often of the pattern [فِعَالَة]{.ar} [fieAlah]{.trn}. Examples:
   + [تَجَرَ يَتْجُرُ تِجَارَةً]{.ar}  "to trade"
   + [أَمِرَ يَأْمَرُ إِمَارَةً]{.ar}  "to be a commander"
4. If the ;madi; verb is of the pattern [فَعُلَ]{.ar} [faeula]{.trn}, then the ;masdar; tends to be of the pattern [فُعُولَة]{.ar} [fueUlah]{.trn} or [فَعَالَة]{.ar} [faeAlah]{.trn}. Examples:
   + [صَعُبَ يَصْعُبُ صُعُوبَةً]{.ar}  "to be difficult"
   + [شَجُعَ يَشْجُعُ شَجَاعَةً]{.ar}  "to be brave"

As mentioned earlier, these are only general trends and there are many verbs that have ;masdar;s which don't fall under the above rules.

## Usage of the ;masdar;

### State and definiteness

The ;masdar; has properties of a noun, like state and definiteness. But it gives the meaning of a verb. For example, consider the verb [أَكَلَ يَأْكُلُ أَكْلًا]{.ar}  "to eat". We can use its ;masdar; in a sentence like this:

[فَرَغَ زَيْدٌ مِنَ ٱلْأَكْلِ.]{.ar}  
[faraga zaydun mina -lEakli.]{.trn}  
"Zayd got done with eating."

Note how the ;masdar; [ٱلْأَكْلِ]{.ar} [EalEakli]{.trn} gives the meaning of the action of the verb "eating". But since it is a noun, it obeys the rules for nouns, like being in the ;istate; when preceded by the preposition [مِنْ]{.ar} [min]{.trn}.

Another point worth noting is that we have made it definite by saying [ٱَلْأَكْلِ]{.ar} [EalEakli]{.trn} instead of saying [أَكْلٍ]{.ar} [Eaklin]{.trn} for the meaning of "eating". This is because, as we explained in section 
\@ref(usage-of-definite-and-indefinite-nouns),
the definite noun is usually used in Arabic to give a general meaning, where in English we would not use "the". This may be a good time to re-read that section.

Having said that, the indefnite ;masdar; may be used too, and this will give the meaning of "a certain", or "a specific". For example, with the verb [عَمِلَ يَعْمَلُ عَمَلًا]{.ar}  "to work", we can say:

[فَرَغَ مِنْ عَمَلٍ صَعْبٍ.]{.ar}  
[faraga min eamalin Saebin.]{.trn}  
"He got done with a [certain] difficult work."

### With a doer

A doer may be used with the ;masdar; to show who is doing the action. In this case, the ;masdar; and the doer are usually placed in an ;idafa;. The ;masdar; shall be the ;mudaf; and the doer shall be in the ;istate; as the ;mudafil; in the ;idafa;. For example, consider the verb [قَرَأَ يَقْرَأُ قِرَاءَةً]{.ar}  "to read". We can say:

[سَمِعْتُ قِرَاءَةَ زَيْدٍ.]{.ar}  
[samietu qirAEata zaydin.]{.trn}  
"I heard Zayd's reading."

The doer may similarly be a pronoun, in which case, as usual, attached pronouns are used. So we can say:

[سَمِعْتُ قِرَاءَتَهُ.]{.ar}  
[samietu qirAEatahu.]{.trn}  
"I heard his reading."

### With an ;indir_mafulb;

If a verb uses a particular preposition with ;indir_mafulb;s, and the ;masdar; of that verb is to be used with an ;indir_mafulb;, then that same preposition is used with the ;masdar;.

For example the verb [ذَهَبَ يَذْهَبُ ذَهَابًا]{.ar}  "to go" is used with the preposition [إِلَىٰ]{.ar} [EilA]{.trn} "to" with an ;indir_mafulb; to give the place to which the doer is going. This same preposition is then used with the ;masdar;, thus:

[تَعِبْتُ مِنَ ٱلذَّهَابِ إِلَىٰ ٱلْمَدِينَةِ  ٱلْبَعِيدَةِ.]{.ar}  
[taeibtu mina -ppahAbi Eila -lmadInati -lbaeIdati.]{.trn}  
"I became tired from going to the far city."

If a doer is used along with the ;indir_mafulb;, then the doer shall be placed in a noun chain with the ;ismfail;, as explained in the previous section. For example,

[حَزِنْتُ مِنْ ذَهَابِ زَيْدٌ إِلَىٰ مَدِينَةٍ بَعِيدَةٍ.]{.ar}  
[Hazintu min pahAbi zaydin EilA madInatin baeIdatin.]{.trn}  
"I became sad from Zayd's going to a far city."

### With a ;mafulb;

If a verb takes a ;mafulb;, and we wish to use the ;mafulb; with the verb's ;masdar;, then we may deal with it in one of three ways:

#### The ;mafulb; in the ;istate; in an ;idafa; with the ;masdar;

In the first method, the ;mafulb; is in the ;istate; as the ;mudafil; in an ;idafa; with the ;masdar;. This method is used when the doer of the verbal noun is not mentioned with the ;masdar;, or when there is no other phrase between the ;masdar; and the ;mafulb;. For example,

[فَرَغَ زَيْدٌ مِنْ قِرَاءَةِ ٱلْكِتَابِ.]{.ar}  
[faraga zaydun min qirAEati -lkitAbi.]{.trn}  
"Zayd got done with reading the book."

In this sentence, [ٱَلْكِتَابِ]{.ar} [EalkitAbi]{.trn} "the book" is the ;mafulb; of the ;masdar; [قِرَاءَةِ]{.ar} [qirAEati]{.trn} "reading". The doer [زَيْدٌ]{.ar} [zayd]{.trn} "Zayd" is only mentioned in the beginning of the sentence but not again with the ;masdar;. Therefore, the ;mafulb; [ٱَلْكِتَابِ]{.ar} [EalkitAbi]{.trn} "the book" is allowed to be put in an ;idafa; with the ;masdar; thus: [قِرَاءَةِ ٱلْكِتَابِ]{.ar}  [qirAEati -lkitAbi]{.trn}  "reading the book".

Instead of a noun, the ;mafulb; may be a pronoun instead. For example,

[قَرَأ زَيْدٌ ٱلْكِتَابَ فَفَرَغَ مِنْ قِرَاءَتِهِ.]{.ar}  
[qaraEa zayduni -lkitAba fafaraga min qirAEatihi]{.trn}  
"Zayd read the book, and then he got done with reading it."

Remember from the previous section, that a doer is handled in the same way with a ;masdar; by placing it in an ;idafa; with the ;masdar;. So how do we know whether the ;mudafil; in an ;idafa; with a ;masdar; is a doer or a doee? Well, for many verbs the meaning of the verbal-noun and the noun is sufficient. For example, in the phrase [قِرَاءَةِ ٱلْكِتَابِ]{.ar} [qirAEati -lkitAbi]{.trn} "reading the book", the meaning of "reading" makes it clear that [ٱَلْكِتَابِ]{.ar} [EalkitAbi]{.trn} can only be a doee, because a book can't be the one doing the reading.

But there are some verbs, however, where the meaning of the verbal-noun itself is not sufficient to tell us whether the noun following it in an ;idafa; is a doer or a doee. Consider the verb 
<!--[قَتَلَ يَقْتُلُ قَتْلًا]{.ar} [qatala yaqtulu qatlan]{.trn} "to kill ([ه]{.ar} s.o.)".-->
[ضَرَبَ يَضْرِبُ ضَرْبًا]{.ar}  "to beat ([ه]{.ar} s.o.)". If we form an ;idafa; using its ;masdar;, thus: [ضَرْبُ زَيْدٍ]{.ar} [Darbu zaydin]{.trn}, we cannot know whether Zayd is the doer (the one doing the beating), or the doee (the one getting beaten). In this case, we will need more context to help us determine whether Zayd is the doer or the doee. Here are a few sentences that may help illustrate this point:

[ضَرَبَ زَيْدٌ عَمْرًا. سَمِعَ ٱلْأَبُ **ضَرْبَ زَيْدٍ** فَغَضِبَ عَلَيْهِ. فَنَدِمَ زَيْدٌ مِنْ **ضَرْبِ عَمْرٍو**.]{.ar}  
[Daraba zaydun eamran. samiea -lEabu Darba zaydin fagaDiba ealayhi. fa nadima zaydun min Darbi eamrin.]{.trn}  
"Zayd beat [_eamr]{.trn2}. The father heard Zayd's beating so he became angry with him. So, Zayd became remorseful of beating [_eamr]{.trn2}."

We can see that the meaning of the sentences help us determine that in the phrase
[ضَرْبَ زَيْدٍ ]{.ar}
[Darba zaydin]{.trn}, Zayd is the doer, and in 
[ضَرْبِ عَمْرٍو]{.ar}
[Darbi eamrin]{.trn}, [_eamr]{.trn2} is the doee.

<!-- The masdar naSr may also be useful here:  نصر الله. نصر العبد-->

#### The ;mafulb; in ;astate; following the ;masdar;

The second way to deal with a ;mafulb; and a ;masdar; is to put it in the ;astate; after the ;masdar;. This is usually done when the doer is mentioned with the ;masdar; in an ;idafa; with it. The ;mafulb; is then placed after the doer in the ;astate;. For example, we can re-word the previous example:

<!--[سَمِعْتُ ضَرْبَ زَيْدٍ عَمْرًا.]{.ar}  
[samietu Darba zaydin eamran.]{.trn}  
"I heard Zayd's beating [_eamr]{.trn2}."-->

[ضَرَبَ زَيْدٌ عَمْرًا. سَمِعَ ٱلْأَبُ **ضَرْبَ زَيْدٍ عَمْرًا** فَغَضِبَ عَلَيْهِ. فَنَدِمَ زَيْدٌ مِنْ **ضَرْبِهِ عَمْرًا**.]{.ar}  
[Daraba zaydun eamran. samiea -lEabu Darba zaydin eamran fagaDiba ealayhi. fa nadima zaydun min Darbihi eamran.]{.trn}  
"Zayd beat [_eamr]{.trn2}. The father heard Zayd's beating [_eamr]{.trn2} so he became angry with him. So, Zayd became remorseful of his beating [_eamr]{.trn2}."

Notice that in [ضَرْبِهِ عَمْرًا]{.ar} [Darbihi eamran]{.trn} "his beating [_eamr]{.trn2}", the doer is a pronoun instead of a noun. This is permissible, and is in line with other usages we have learned so far.

The doee noun in the ;astate;, too, may be replaced with a pronoun, but just like when the attached doee pronoun is separated from its verb it has to instead be attached to the prefix [إِيَّا]{.ar} [EiyyA]{.trn}, here too this prefix is used. For example,

[أَلِمَ عَمْرٌو مِنْ ضَرْبِ زَيْدٍ إِيَّاهُ.]{.ar}  
[Ealima eamrun min Darbi zaydin EiyyAhu.]{.trn}  
"[_eamr]{.trn2} was in pain from Zayd's beating him."

This usage of putting the ;mafulb; in the ;astate; after the ;masdar; is not only done when the doer is mentioned with the ;masdar;. But it is also done when the ;mafulb; is separated from the ;masdar; by some other words, like a prepositional phrase. For example,

[فَرَغْتُ مِنَ ٱلْقِرَاءَةِ فِي ٱلْمَكْتَبَةِ كِتَابًا.]{.ar}  
[faragtu mina -lqirAEati fi -lmaktabati kitAban.]{.trn}  
"I got done with reading, in the library, a book."

The prepositional phrase [فِي ٱلْمَكْتَبَةِ]{.ar} [fi -lmaktabati]{.trn} in the above example is placed between the ;masdar; and the doee for effect. It could, of course, also have been placed after the doee, in a more normal fashion. In this case, it would be preferred for the ;masdar; and the doee to be placed in an ;idafa;, in the manner we have already learned.

[فَرَغْتُ مِنْ قِرَاءَةِ كِتَابٍ فِي ٱلْمَكْتَبَةِ .]{.ar}  
[faragtu min qirAEati kitAbin fi -lmaktabati.]{.trn}  
"I got done with reading a book in the library."

#### The ;mafulb; in ;istate; preceded by the preposition [لِ]{.ar} [li]{.trn}

The third way to deal with a ;mafulb; and a ;masdar; is to put it in the ;istate; preceded by the preposition [لِ]{.ar} [li]{.trn}. This is usually done in one of the following scenarios:

1. When the ;masdar; is indefinite and immediately precedes the ;mafulb;. Example:

   [فَرَغْتُ مِنْ قِرَاءَةٍ لِلْكُتُبِ.]{.ar}  
   [faragtu min qirAEatin lilkutubi.]{.trn}  
   "I got done with a reading of the books."

   This sentence can be used to indicate one particular instance of reading the books. As opposed to saying [قِرَاءَةِ ٱلْكُتُبِ]{.ar} [qirAEati -lkutubi]{.trn} which would indicate that the reading was general or complete.

2. When the doer comes between the ;masdar; and the doee. Example,

   [أَلِمَ عَمْرٌو مِنْ ضَرْبِ زَيْدٍ لَهُ.]{.ar}  
   [Ealima eamrun min Darbi zaydin lahu.]{.trn}  
   "[_eamr]{.trn2} was in pain from Zayd's beating him."

   This is as an optional alternative to putting the doee in the ;astate;, in the manner we have already learned in the previous section:

   [أَلِمَ عَمْرٌو مِنْ ضَرْبِ زَيْدٍ إِيَّاهُ.]{.ar}  
   [Ealima eamrun min Darbi zaydin EiyyAhu.]{.trn}  
   "[_eamr]{.trn2} was in pain from Zayd's beating him."

## Multiple ;masdar;s for the same verb

It is possible, and fairly common, for verbs to have more than one ;masdar;. Usually, each of the ;masdar;s has its own meaning, distinct from each other.

For example, the verb [حَمَلَ يَحْمِلُ حَمْلًا]{.ar}  means "to carry ([هـ]{.ar} s.th.)" Here is an example of its ;masdar; in a sentence:

[تَعِبَ زَيْدٌ مِنْ حَمْلِهِ لِلْكُتُبِ ٱلثَّقِيلَةِ.]{.ar}  
[taeiba zaydun min Hamlihi lilkutubi -vvaqIlati.]{.trn}  
"Zayd became tired from his carrying the heavy books."

There exists another meaning for this verb with its own ;masdar;: [حَمَلَ يَحْمِلُ حَمْلَةً]{.ar}  which means "to launch an attack ([عَلَىٰ]{.ar} on s.o.)" Here is an example of its ;masdar; in a sentence:

[دَهِشَ ٱلْقَوْمُ مِنْ حَمْلَةِ ٱلْعَدُوِّ عَلَيْهِمْ.]{.ar}  
[dahica -lqawmu min Hamlati -leaduwwi ealayhim.]{.trn}  
"The people were astonished at the attack launched by the enemy on them."

Sometimes the meaning between the multiple ;masdar;s is only slight. Consider, for example, the verb [جَهِلَ يَجْهَلُ]{.ar}  "to not know, or to be ignorant ([هـ]{.ar} of s.th.)"

It has two ;masdar;s: [جَهْلٌ]{.ar} [jahl]{.trn} and [جَهَالَة]{.ar} [jahAlah]{.trn} which have meanings that are close to each other.

[جَهْلٌ]{.ar} [jahl]{.trn} is the more simple ;masdar; used for not knowing something. For example,

[مَا فَعَلَ زَيْدٌ ٱلْوَاجِبَ لِجَهْلِهِ إِيَّاهُ.]{.ar}  
[mA faeala zayduni -lwAjiba lijahlihi EiyyAhu.]{.trn}  
"Zayd did not do the obligatory [work] because of his not knowing it."

[جَهَالَة]{.ar} [jahAlah]{.trn} has the more abstract meaning of "ignorance". For example,

[نَفَرَ ٱلْمُسْلِمُ مِنْ جَهَالَةِ ٱلْمُشْرِكِينَ.]{.ar}  
[nafara -lmuslimu min jahAlati -lmucrikIna.]{.trn}  
"The Muslim was repulsed by the ignorance of the pagans."

As a general rule of thumb, the fewer letters in a ;masdar;, the simpler its meaning. And ;masdar;s of the pattern [فَعَالَة]{.ar} [faeAlah]{.trn} tend to have an abstract meaning.

## ;_masdar;s re-used as common nouns

There are many ;masdar;s, that in addition to their verbal meaning, are also re-used as common nouns. Their common noun meaning is typically associated, in some manner, with their verbal meaning.

<!--For example, the verb [عَلِمَ يَعْلَمُ عِلْمًا]{.ar} [ealima yaelamu eilman]{.trn} means "to know". The ;masdar; [عِلْمٌ]{.ar} [eilmun]{.trn} can be used with its verbal meaning: "knowing". For example,-->

For example, the verb [سَأَلَ يَسْأَلُ سُؤَالًا]{.ar}  means "to question or ask ([ه عن]{.ar} s.o. about s.th.)". The ;masdar; [سُؤَالٌ]{.ar} [suEAlun]{.trn} can be used with its verbal meaning: "questioning". For example,

[سَئِمَ ٱلْأَبُ مِنْ كَثْرَةِ سُؤَالِ ٱبْنِهِ إِيَّاهُ.]{.ar}  
[saEima -lEabu min kavrati suEAli -bnihi EiyyAhu.]{.trn}  
"The father became weary from the excessiveness of his son's questioning him."

[سُؤَالٌ]{.ar} [suEAlun]{.trn}, in addition to being a ;masdar; "questioning" is re-used as a common noun with the meaning "a question" and the broken plural [أَسْئِلَة]{.ar} [EasEilah]{.trn} "questions". So, for example, we can say:

[كَتَبَ ٱلْأُسْتَاذُ سُؤَالًا عَلَى ٱلسَّبُّورَةِ.]{.ar}  
[kataba -lEustApu suEAlan eala -ssabbUrati.]{.trn}  
"The professor wrote a question on the board."

## Common nouns re-used as ;masdar;s

Just as some ;masdar;s are re-used as common nouns, there are some common nouns that may be re-used as ;masdar;s. For example, the verb [فَعَلَ يَفْعَلُ]{.ar}  "to do ([هـ]{.ar} an action)" has the ;masdar; [فَعْلٌ]{.ar} [faelun]{.trn}.

There is an associated common noun from this root: [فِعْلٌ]{.ar} [fielun]{.trn} "an act". This common noun is frequently used in place of the ;masdar; [فَعْلٌ]{.ar} [faelun]{.trn}. For example:

[طَلَبَ ٱلْأُسْتَاذُ مِنَ ٱلتَّلَامِيذِ فِعْلَ ٱلْوَاجِبِ.]{.ar}  
[Talaba -lEustApu mina -ttalAmIpa fiela -lwAjibi.]{.trn}  
"The professor wanted from his students the doing of the obligatory [work]."

## TODO

Add multiple doees with masdar

