# Glossary of terms

|Term used in this book | Term used in native Arabic grammar| Term used by Western grammars|
|:------|----:|:------|
|;mmutlaq; |[المَفْعُول المُطْلَق]{.ar} | absolute accusative |
|;0state; | [المَجْزُومُ]{.ar} / [حَالَةُ الجَزْمِ]{.ar}| jussive mood |
|;shart; | [الشَّرْط]{.ar} | protasis |
|;jawab; | [جَوَابُ الشَّرْط]{.ar} | apodosis |
|;sifah; |[الصِّفَةُ]{.ar} | epithet |
|adverb of time  |[ظَرْفُ الزَّمَانِ]{.ar} / [المَفْعُولُ فِيهِ]{.ar} | ?? |
|adverb of place |[ظَرْفُ المَكَانِ]{.ar} / [المَفْعُولُ فِيهِ]{.ar} | ?? |
|;idafa; |[الإِضَافَة]{.ar} | ?? |
|;mudaf; |[المُضَافُ]{.ar} | construct noun |
|;mudafil; |[المُضَافُ إِلَيْهِ]{.ar} | ?? |
|[verb of] command | [الأَمْرُ]{.ar} | imperative |
|;xabar; |[الخَبَر]{.ar} | predicate / comment |
|;ism_mawsul; |[الاسْمُ المَوْصُولُ]{.ar} | relative pronoun |
|;silah; |[الصِّلَة]{.ar} | ?? |
|;naib; -- |[نَائِبُ --]{.ar} / [نَائِبٌ عَنْ --]{.ar} | ?? |
|;mafulb; |[المَفْعُول بِهِ]{.ar} | object |
|;fail; |[الفَاعِلُ]{.ar} | subject |
|;istate; | [المَجْرُورُ]{.ar} / [حَالَةُ الجَرِّ]{.ar}| genitive case |
|particle|[الحَرْفُ]{.ar} | particle |
|;ism_ishara;|[اسْمُ الإِشَارَةِ]{.ar} | demonstrative pronoun |
|preposition|[حَرْفُ الجَرِّ]{.ar} | preposition |
|prohibition|[النَّهْيُ]{.ar} | ?? |
|pronoun|[الضَّمِيرُ]{.ar} | pronoun |
|proper noun|[العَلَمُ]{.ar} | ?? |
|;astate; | [المَنْصُوبُ]{.ar} / [حَالَةُ النَّصْبِ]{.ar}| accusative case (nouns) / subjunctive mood (verbs) |
|questioning|[الاسْتِفْهَامُ]{.ar} | interrogative |
|;ustate; | [المَرْفُوعُ]{.ar} / [حَالَةُ الرَّفْعِ]{.ar}| nominative case (nouns) / indicative mood (verbs) |
|;aaid; | [العَائِدُ]{.ar} / [الرَّابِطُ]{.ar} | ?? |
|;mabny;|[المَيْنِيُّ]{.ar} | ?? |
|;diptote;|[المَمْنُوعُ مِنَ الصَّرْفِ]{.ar} | diptote |
|state | [الإعْرَابُ]{.ar} | inflection / case (nouns) / mood (verbs) |
|;ism_of; (of [إِنَّ]{.ar}, [كَانَ]{.ar}, etc.) |[اسْمُ --]{.ar} | ?? |
|;mubtada; (of sentence) |[المُبْتَدَأُ بِهِ]{.ar}, [المُبْتَدَأُ]{.ar} | subject / topic |
|;tanwin; |[التَّنْوِين]{.ar} | nunation |

