# The ;hal;

;wip_warn;


## Introduction

The _;hal;_ 
([ٱلْحَال]{.ar})
is a kind of adverb,
governed typically by a verb,
that describes the state
of the _;sahib_hal;_ 
during the time that the ;hal;'s governing verb is taking place.
<!--
during the action of the ;hal;'s ;3aamil;.
-->
Here is an example of a ;hal;:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.25ex}]
\path [decoration={text effects along path, 
  text=.\txarb{رَاكِبًا} \txarb{زَيْدٌ} \txarb{جَاءَ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace}, decorate] 
   (word-1.north west) -- (word-1.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize ḥāl};

\draw [decoration={brace}, decorate] 
   (word-2.north west) -- (word-2.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize person of ḥāl};

\draw [decoration={brace}, decorate] 
   (word-3.north west) -- (word-3.north east)
      node [midway, rotate=90, anchor=south, right=0ex] {\scriptsize governor};

\path (0,0) node [midway, below=3ex, right=-1ex, align=left] {``Zayd came riding''};

\end{tikzpicture}
```

In the example above,
the usage of the ;hal; signifies that
Zayd, while he was coming, was in a riding state.

By the way,
we are not not using "state" here terminologically, as in ;ustate;, ;astate;, etc.  Rather we are using it to mean Zayd's condition or mode of being.
<!--
What we mean by
"temporal state of the ;sahib_hal;"
is that
It is a temporary state because Zayd is only described as angry while he is coming.
-->

<!--
Note that, like adverbs in general, the ;hal; is in the ;astate;.
Typically, the ;hal; is an ;sifah;, its ;3aamil; is a verb, and the ;hal; describes the ;sahib_hal;.
But, as we will see later in this chapter ;ia;, sometimes the ;hal; may have differing behavior.
-->

## Matching the ;hal; to the ;sahib_hal;

Consider again the example:

(@ex000001) [جَاءَ زَيْدٌ رَاكِبًا]{.ar}
    [@wright@ 2/112C]{.citex}  
    "Zayd came riding"

The ;hal;
[رَاكِبًا]{.ar}
is an adjectival noun matching the ;sahib_hal; [زَيْد]{.ar} in number (singular) and gender (masculine).

If the ;sahib_hal; is feminine in gender or more than one in number, then the ;hal; will match it accordingly.
For example:

(@ex000002) [قَامَتِ ٱبْنَتُهُ إِلَيْهِ بَاكِيَةً]{.ar}
    [@fischer@ 196D]{.citex}  
    "His daughter [went and] stood to him crying"

(@ex000003) [وَثَبَا مُسْرِعَيْنِ]{.ar}
    [@https://sunnah.com/bukhari:4794@]{.citex}  
    "they~2m~ got up hastening"

(@haal_two_sahibs_hal_dual_hal) [جَاءَ سَعِيدٌ وَخَالِدٌ رَاكِبَيْنِ]{.ar}
    [@nahw_arabi@ 2/38]{.citex}  
    "[#saeId]{.trn2} and [#xAlid]{.trn2} came riding."

For plurals, both sound and broken plurals may be used:

(@ex000004) [وَٱدْخُلُوا ٱلْبَابَ سُجَّدًا]{.ar}
    [@https://quran.com/2/58@]{.citex}  
    "and enter the gate bowing humbly"  
    (The ;sahib_hal; is the plural masculine ;faa3il; pronoun in [ٱدْخُلُوا]{.ar} and the ;hal; [سُجَّد]{.ar} is the plural of [سَاجِد]{.ar}.)

(@ex000005) [خَرَجْنَا مُتَوَجِّهِينَ إِلَىٰ ٱلْيَمَنِ]{.ar}
    [@fischer@ 196D]{.citex}  
    "We left heading towards Yemen"


As with ;na3t;s and ;xabar;s, when the ;sahib_hal; is a plural of
non-intelligent beings,
the singular feminine is typically used for the ;hal;.
For example:

(@ex000006) [صَالَتِ ٱلْأُسُودُ عَلَى ٱلْفَرِيسَةِ فَاتِكَةً]{.ar}  
    "The lions pounced on the prey slaying"

## The ;3aamil; of the ;hal;

The ;3aamil; of the ;hal; may be one of the following:

##### A verb {.unnumbered}

The verb is the typical ;3aamil; of the ;hal;.
For example:

(@ex000007) [جَاءَ زَيْدٌ رَاكِبًا]{.ar}
    [@wright@ 2/113D]{.citex}  
    "Zayd came riding"

##### A ;masdar; {.unnumbered}

(@ex000008) [رُكُوبُكَ ٱلسَّيَارَةَ مُسْرِعَةً خَطَرٌ عَلَيْكَ]{.ar}
    [@nahw_arabi@ 2/51]{.citex}  
    "Your riding the car speeding is a danger for you."

##### A ;shibh_fi3l; {.unnumbered}

A ;shibh_fi3l; is a ;mushtaqq; verbal noun like an ;ism_fail; or an ;ism_maful;, or an ;sifah;, etc.
For example:

(@ex000009) [زَيْدٌ ضَارِبٌ عَمْرًا قَائِمًا]{.ar}
    [@wright@ 2/113D]{.citex}  
    "Zayd is beating [#eamr]{.trn2} standing."

(@ex000010) [زَيْدٌ حَسَنٌ قَائِمًا]{.ar}
    [@wright@ 2/113D]{.citex}  
    "Zayd is handsome standing."

(@ex000011) [زَيْدٌ قَائِمًا أَحْسَنُ مِنْهُ قَاعِدًا]{.ar}
    [@wright@ 2/114A]{.citex}  
    "Zayd, standing, is more handsome than him sitting."

##### An expression that has verbal force  {.unnumbered}

An expression that has verbal force could be:

* a preposition or adverb of time or place with a following noun in the ;istate;
* a ;ism_isharah;
* a ;adat_istifham;
* a word like [لَيْتَ]{.ar}, [كَأَنَّ]{.ar}, [لَعَلَّ]{.ar}

In such cases there will typically be the implicit existential verb "is" providing the verbal force.

Examples:

(@ex000012) [زَيْدٌ فِي ٱلدَّارِ قَائِمًا]{.ar}
    [@wright@ 2/114A]{.citex}  
    "Zayd is in the house standing."
    (the existential verb "is" is implied)

(@ex000013) [هَـٰذَا عَمْرٌو مُنْطَلِقًا]{.ar}
    [@wright@ 2/114A]{.citex}  
    "This is [#eamr]{.trn2} (in the act of) setting out."

(@ex000014) [وَهَـٰذَا بَعْلِي شَيْخًا]{.ar}
    [@https://quran.com/11/72@ cited by @wright@ 2/114B]{.citex}  
    "and this, my husband, is an old man"

(@ex000015) [مَا شَأْنُكَ قَائِمًا]{.ar}
    [@wright@ 2/114B]{.citex}  
    "What is your matter, standing?"  
    (i.e. "Why are you standing?")

(@ex000016) [مَا لَكَ وَاقِفًا]{.ar}
    [@wright@ 2/114B]{.citex}  
    "What (happened) to you, standing?"  
    (i.e. "Why are you standing?")

<!--
(@ex000017) [خَالِدٌ مُسَافِرٌ رَاكِبًا]{.ar}
    [@nahw_arabi@ 2/52]{.citex}  
    "[#xAlid]{.trn2} is a traveller as he is riding."

(@ex000018) [زَيْدٌ مَضْرُوبٌ وَاقِفًا]{.ar}
    [@nahw_arabi@ 2/52]{.citex}  
    "Zayd is beaten standing."

##### The existential verb "is" as the ;3aamil; of the ;hal; {.unnumbered}

Arabic does not usually express the existential verb "is".
However, it is implicit and may be the govern the ;hal;.
For example,

(@ex000019) [هَـٰذَا كِتَابُكَ جَمِيلًا]{.ar}
    [@nahw_arabi@ 2/52]{.citex}  
    "This is your book (being) beautiful."

This is frequently the case in questions like:

(@ex000020) [مَا شَأْنُكَ وَاقِفًا]{.ar}
    [@nahw_arabi@ 2/52]{.citex}  
    "What is your matter, standing?"  
    (i.e. "Why are you standing?")

(@ex000021) [مَا لَكَ مُنْطَلِقًا]{.ar}
    [@nahw_arabi@ 2/52]{.citex}  
    "What (happened) to you, setting out?"  
    (i.e. "Why are you setting out?")
-->


## Valid ;sahibs_hal;

The ;sahib_hal; may be the ;faa3il; of the governing verb
but it may also be the ;mafulb;,
or even other nouns in a sentence.

Let's see some examples.

#### The ;sahib_hal; as a ;faa3il; {.unnumbered}

(@ex000022) [فَخَرَجَ مِنْهَا خَائِفًا]{.ar}
    [@https://quran.com/28/21@]{.citex}  
    "So he left it, fearful"

#### The ;sahib_hal; as a ;mafulb; {.unnumbered}

(@ex000023) [وَأَرْسَلْنَاكَ لِلنَّاسِ رَسُولًا]{.ar}
    [@https://quran.com/4/79@]{.citex}  
    "And We have sent you, [O Muḥammad], to the people as a messenger"

(@ex000024) [رَكِبْتُ ٱلْفَرَسَ مُسْرَجًا]{.ar}
    [@wright@ 2/113A]{.citex}  
    "I rode the horse saddled"

#### The ;sahib_hal; as a ;naib; ;faa3il; {.unnumbered}

(@ex000025) [تُؤْكَلُ ٱلْفَاكِهَةُ نَاضِجَةً]{.ar}
    [@nahw_arabi@ 2/28]{.citex}  
    "The fruit is eaten fresh"

#### The ;sahib_hal; as a ;mubtada; {.unnumbered}

(@ex000026) [ٱلْفَاكِهَةُ لَذِيذَةٌ نَاضِجَةً]{.ar}
    [@nahw_arabi@ 2/28]{.citex}  
    "The fruit is delicious (when it is) fresh."

<!--
(The ;3aamil; in the above (and also in the below) example is not apparent but is implied. See section\ (ref) later in this chapter.)
-->

#### The ;sahib_hal; as a ;xabar; {.unnumbered}

(@ex000027) [هَـٰذَا هُوَ ٱلْهِلَالُ طَالِعًا]{.ar}
    [@nahw_arabi@ 2/28]{.citex}  
    "This is the crescent (as it is) rising."

#### The ;sahib_hal; in the ;istate; following a preposition {.unnumbered}

(@ex000028) [مَرَرْتُ بِزَيْدٍ جَالِسًا]{.ar}
    [@wright@ 2/113A]{.citex}  
    "I passed by Zayd (as he was) sitting."

(@ex000029) [كُنْتُ فِي ٱلْبُسْتَانِ زَاهِرًا]{.ar}
    [@wright@ 2/113B]{.citex}  
    "I was in the garden (while it was) in bloom."

#### The ;sahib_hal; in the ;istate; in as the ;mudafil; in an ;idaafah; {.unnumbered}

The ;mudafil; in an ;idaafah; is permitted to be a ;sahib_hal; if it satisfies any one of the following conditions:

  i. When the ;mudaf; is naturally capable of being the ;3aamil; of the ;hal; (as a ;masdar; or ;ism_fail;, etc.).
     For example:

     (@) [أَعْجَبَنِي قِيَامُ زَيْدٍ مُسْرِعًا]{.ar}
         [@wright@ 2/119C]{.citex}  
         "Zayd's standing speedily pleased me."  
         (The ;3aamil; is the ;mudaf; [قِيَام]{.ar} which is a ;masdar;)

     (@) [إِلَى ٱللَّـٰهِ مَرْجِعُكمْ جَمِيعًا]{.ar}
         [@https://quran.com/5/105@]{.citex}  
         "To Allāh is your return all together"  
         (The ;3aamil; is the ;mudaf; [مَرْجِع]{.ar} which is a ;masdar;)

     (@) [أَنْتَ شَارِبُ ٱلْمَاءِ صَافِيًا]{.ar}
         [@nahw_arabi@ 2/50]{.citex}  
         "You are drinking the water clear."
         (The ;3aamil; is the ;mudaf; [شَارِب]{.ar} which is a ;ism_fail;)

 ii. When the ;mudaf; is a real part of the ;mudafil;.
     For example:

     (@) [وَنَزَعْنَا مَا فِي صُدُورِهِم مِّنْ غِلٍّ إِخْوَانًا]{.ar}
         [@https://quran.com/15/47@]{.citex}  
         "And We will remove whatever is in their breasts of resentment, [so they will be] brothers"  
         (The ;mudaf; [صُدُور]{.ar} is a real part of the ;mudafil; ;sahib_hal; [هِمْ]{.ar}.)

     (@) [أَيُحِبُّ أَحَدُكُمْ أَنْ يَأْكُلَ لَحْمَ أَخِيهِ مَيْتًا]{.ar}
         [@https://quran.com/49/12@]{.citex}  
         "Would one of you like to eat the flesh of his brother when dead?"  
         (The ;mudaf; [لَحْم]{.ar} is a real part of the ;mudafil; ;sahib_hal; [أَخ]{.ar}.)

iii. When the ;mudaf; is not really but is virtually a part of the ;mudafil;. 
     Such that the meaning would still be correct if the ;mudaf; was removed.
     For example:

     (@) [ثُمَّ أَوْحَيْنَا إِلَيْكَ أَنِ ٱتَّبِعْ مِلَّةَ إِبْرَاهِيمَ حَنِيفًا]{.ar}
         [@https://quran.com/16/123@]{.citex}  
         "Then We revealed to you, [O Muḥammad], to follow the religion of Abraham, inclining toward truth"  
         ([حَنِيفًا]{.ar} is a ;hal; of the ;sahib_hal; [إِبْرَاهِيم]{.ar}. [مِلَّة]{.ar} is virtually a part of [إِبْرَاهِيم]{.ar} such that the meaning is correct without it: [ٱتَّبِعْ إِبْرَاهِيمَ حَنِيفًا]{.ar}.)

When none of these conditions are satisfied then the ;mudafil; cannot be a ;sahib_hal;.
So we cannot say:

(@ex000030) ;x; [مَرَرْتُ بِغُلَامِ هِنْدٍ جَالِسَةً]{.ar}
    [@nahw_arabi@ 2/51]{.citex}  
    "I passed by Hind's slave boy (when she was) sitting."

#### Determining the ;sahib_hal; when there is more than one possibility {.unnumbered}

When the sentence has more than one noun as a possible ;sahib_hal;, 
usually the meaning, gender, or number is sufficient to determine whom the ;hal; is describing.
But sometimes context will be needed to determine who the ;sahib_hal; is.
For example:

<!--
(@ex000031) [لَقِيتُ ٱلسُّلْطَانَ عِنْدَهُ بَاكِيًا]{.ar}
    [@wright@ 2/113A]{.citex}  
    "I met the sultan in his house, crying."
-->

(@ex000032) [قَابَلْتُ ٱلْأَخَ رَاكِبًا]{.ar}
    [@nahw_wafi@ 2/386A]{.citex}  
    "I met the brother riding"

In the example above,
the ;hal;
[رَاكِبًا]{.ar}
may be applicable to either the speaker
(assuming he is male),
or to [ٱلْأَخ]{.ar} "the brother".
Context should tell us which is intended.
If context is not sufficient then is more suitable for the closer of the two to the ;hal; to be the ;sahib_hal;.
Or, to avoid ambiguity, it may be better that the expression not be used in this case.^[@nahw_wafi@ 2/386]


<!--
## Multiple ;hal;s or ;sahibs_hal;

There can be a
one-to-one,
many-to-one,
or
one-to-many
relationship between the 
;hal; and ;sahib_hal;.
So far,
we have seen the
one-to-one
;hal; and ;sahib_hal;,
where there is one ;hal; for one ;sahib_hal;
Now we will see that there can be
multiple ;hal;s for one ;sahib_hal;,
and also
one ;hal; for multiple ;sahibs_hal;.

### Multiple ;hal;s for one ;sahib_hal;
-->

## The ;hal; after verbs like [رَأَىٰ]{.ar} and [وَجَدَ]{.ar}

The verbs
[رَأَىٰ]{.ar} and [وَجَدَ]{.ar}
are what are known as
;af3aal_quloob;
(see chapter\ (ref)).
That is, they signify an act that takes place in the mind.
So they may take two ;mafulb;s.
For example:

(@ex000033) [إِنَّهُمْ يَرَوْنَهُ بَعِيدًا]{.ar}
    [@https://quran.com/70/6@]{.citex}  
    "Indeed, they see it [as] distant,"  
    ([بَعِيدًا]{.ar} has been analyzed as a second ;mafulb;^[@https://tafsir.app/iraab-aldarweesh/70/6@])

(@ex000034) [لَوَجَدُوا ٱللَّهَ تَوَّابًا رَحِيمًا]{.ar}
    [@https://quran.com/4/64@]{.citex}  
    "they would have found Allāh Accepting of Repentance and Merciful."  
    ([تَوَّابًا]{.ar} has been analyzed as a second ;mafulb;^[@https://tafsir.app/iraab-aldarweesh/4/64@])

However, if these verbs are mere verbs of sense,
i.e. they express nothing but acts of the external organs of sense,
then they may still have two ;ma3mul;s in the ;astate;
but the second ;ma3mul; will no longer be a ;mafulb;
but a ;hal;.^[@wright@ 2/50B]
For example:

(@ex000035) [رَأَيْتُكَ نَائِمًا]{.ar}
    [@wright@ 2/50C]{.citex}  
    "I saw you sleeping."

(@ex000036) [وَجَدْتُهُ مَرِيضًا]{.ar}
    [@wright@ 2/50C]{.citex}  
    "I found him sick."

## Multiple ;hal;s or ;sahibs_hal;

There may be one or multiple ;hal;s that correspond to one or multiple ;sahibs_hal;.
This occurs in the following cases:

### Multiple ;hal;s for one ;sahib_hal;

These are examples of 
multiple ;hal;s corresponding to one ;sahib_hal;:

(@ex000037) [وَلَمَّا رَجَعَ مُوسى إِلى قَوْمِهِ غَضْبانَ أَسِفًا]{.ar}
    [@https://quran.com/7/150@]{.citex}  
    "And when Moses returned to his people, angry and grieved"

(@ex000038) [ارْجِعِي إِلَى رَبِّكِ رَاضِيَةً مَرْضِيَّةً]{.ar}
    [@https://quran.com/89/28@]{.citex}  
    "Return to your Lord, well-pleased and pleasing [to Him]"

(@ex000039) [مَا لَكِ يَا عَائِشُ حَشْيَا رَابِيَةً]{.ar}
    [@https://sunnah.com/muslim:974b@]{.citex}  
    "Why are you, O [#eAEicah]{.trn2}, panting and short of breath?"  
    ([حَشْيَا]{.ar}, on the pattern [فَعْلَىٰ]{.ar}, is the feminine of [حَشْيَان]{.ar} meaning "short of breath". [رَابِيَة]{.ar} has a similar meaning.)

As you can see, there is no need for a ;3atf; like [و]{.ar} to connect the multiple ;hal;s
(though we may use the word "and" in the translation).
If such a [و]{.ar} is inserted, then the noun(s) following it is technically no longer a ;hal;.
Rather, it is now a ;ma3toof; to the preceding ;hal;.^[@nahw_wafi@ 2/386]
For example:

(@ex000040) [أَقْبَلَ ٱلْمُنْتَصِرُ فَرِحًا وَمُسْرِعًا وَمُصَافِحًا رِفَاقَهُ]{.ar}
    [@nahw_wafi@ 2/430]{.citex}  
    "The victor approached rejoicing, hastening, and shaking hands with his companions."

In the above example,
[فَرِحًا]{.ar}
is a ;hal;,
[مُسْرِعًا]{.ar}
and
[مُصَافِحًا]{.ar}
are ;ma3toof;s.

This distinction is technically correct.
However, loosely speaking, words like 
[مُسْرِعًا]{.ar}
and
[مُصَافِحًا]{.ar}
in the example above may be referred to as ;hal;s.^[See, for example, the analysis of [طَمَعًا]{.ar} in @https://tafsir.app/albahr-almuheet/32/16@ ([يَدْعُونَ رَبَّهم خَوْفًا وطَمَعًا]{.ar})]

See also section\ (ref) later in this chapter for multiple ;hal;s when one or more is a _sentence ;hal;_.

### One ;hal; for multiple ;sahibs_hal;

If there are multiple ;sahibs_hal; and the same ;hal; can be used to describe all of them,
then one ;hal;, appropriately dualized or pluralized, may be used.
We have already seen an example of this in example
(@haal_two_sahibs_hal_dual_hal) earlier in this chapter:

(@haal_two_sahibs_hal_dual_hal) [جَاءَ سَعِيدٌ وَخَالِدٌ رَاكِبَيْنِ]{.ar}
    [@nahw_arabi@ 2/38]{.citex}  
    "[#saeId]{.trn2} and [#xAlid]{.trn2} came riding."

Here is another example:

(@ex000041) [وَسَخَّرَ لَكُمُ ٱلشَّمْسَ وَٱلْقَمَرَ دَائِبَيْنِ]{.ar}
    [@https://quran.com/14/33@]{.citex}  
    "And He subjected for you the sun and the moon, continuous [in orbit]"

Sometimes the multiple ;sahibs_hal; may even occur in different functions in the sentence.
For example:

(@ex000042) [قَابَلَ عَلِيٌّ صَدِيقَهُ مَسْرُورَيْنِ]{.ar}
    [@nahw_arabi@ 2/28]{.citex}  
    "[#ealiyy]{.trn2} met his friend (while they both were) happy."

(@ex000043) [لَقِيتُهُ رَاكِبَيْنِ]{.ar}
    [@wright@ 2/113B]{.citex}  
    "I met him (while we both were) riding"

### Multiple ;hal;s for multiple ;sahibs_hal;

If there are multiple ;sahibs_hal;,
and each is to be described by different ;hal;s,
then the individual ;hal;s may occur in the sentence without any conjunction.
If context and meaning are not sufficient to determine which ;hal; applies to which ;sahib_hal;,
then the first ;hal; (in sentence word order) should apply to the second ;sahib_hal;,
and the second ;hal; should apply to the first ;sahib_hal;.^[@nahw_wafi@ 2/387, @nahw_arabi@ 2/38--39. But see also @wright@ 2/115CD]
For example:

(@ex000044) [لَقِيتُ خَالِدًا مُصْعِدًا مُنْحَدِرًا]{.ar}
    [@nahw_arabi@ 2/39]{.citex}  
    "I met [#xAlid]{.trn2} (while he was) going up (and I~m~ was) coming down."

But if meaning and context are sufficient to disambiguate, then the ;hal;s may occur in either order.
For example:

(@ex000045) [لَقِيتُ هِنْدًا مُصْعِدًا مُنْحَدِرَةً]{.ar}
    [@nahw_arabi@ 2/39]{.citex}  
    "I met Hind (while I~m~ was) going up (and she was) coming down."

<!--
(@ex000046) [حَدَّثَ ٱلْمُحَاضِرُ طُلَّابَهُ جَالِسِينَ وَاقِفًا]{.ar}
    [@nahw_arabi@ 2/38]{.citex}
    "The lecturer "
-->

## Definiteness of the ;hal;

The ;hal; is typically an indefinite noun,
as we have seen in all the examples so far.
Occasionally, however, it does occur as a definite noun.
The most common such ;hal; is the noun [وَحْد]{.ar} annexed to a pronoun, meaning "alone".
For example:

(@ex000047) [جَاءَ ٱلضَّيْفَ وَحْدَهُ]{.ar}
    [@nahw_wafi@ 2/375]{.citex}  
    "The guest came by himself."

Other definite nouns may also occur as ;hal;s.
For example:

(@ex000048) [ٱدْخُلُوا ٱلْأَوَّلَ فَٱلْأَوَّلَ]{.ar}  
    [@nahw_wafi@ 2/376]{.citex}  
    "Enter! the first then the first"  
    (i.e. "Enter in order")
     
(@ex000049) [كَلَّمْتُهُ فَاهُ إِلَىٰ فِيَّ]{.ar}
    [@nahw_arabi@ 2/34]{.citex}  
    "I spoke to him his mouth to my mouth."  
    (i.e. face to face)

The definite ;hal; may also occur in a comparative statement.
For example:

(@ex000050) [زَيْدٌ ٱلرَّاكِبَ أَحْسَنُ مِنْهُ ٱلْمَاشِي]{.ar}
    [@wright@ 2/116D]{.citex}  
    "Zayd as the rider is more handsome than he is (as) the walker."

Although, it is more usual to use the indefinite ;hal; in this case: 
[زَيْدٌ رَاكِبًا أَحْسَنُ مِنْهُ مَاشِيًا]{.ar}.

## Definiteness of the ;sahib_hal;

The ;sahib_hal; is typically a definite noun,
as we have seen in all the examples so far.
Sometimes, however, it does occur as an indefinite noun.
Usually, when the ;sahib_hal; is indefinite, it occurs in the following circumstances:

##### The ;hal; precedes the indefinite  ;sahib_hal; {.unnumbered}

(@ex000051) [فِيهَا قَائِمًا رَجُلًا]{.ar}
    [@wright@ 2/117B]{.citex}  
    "in it (i.e. the house) is a man standing"

The order of the ;hal; and the ;sahib_hal; is treated in more detail in section\ (ref).

##### The indefinite ;sahib_hal; is qualified by a ;na3t; or a ;mudafil; {.unnumbered}

(@ex000052) [عِنْدِي غُلَامُ رَجُلٍ قَائِمًا]{.ar}
    [@wright@ 2/117D]{.citex}  
    "in my house is a man's slave standing"

(@ex000053) [قَدِمَ طِفْلٌ صَغِيرٌ بَاكِيًا]{.ar}
    [@nahw_arabi@ 2/45]{.citex}  
    "a small child came crying"

(@ex000054) [وَبَارَكَ فِيهَا وَقَدَّرَ فِيهَا أَقْوَاتَهَا فِي أَرْبَعَةِ أَيَّامٍ سَوَاءً لِّلسَّائِلِينَ]{.ar}
    [@https://quran.com/41/10@ cited by @nahw_arabi@ 2/45]{.citex}  
    "and He blessed it and determined therein its [creatures'] sustenance in four days without distinction - for [the information of] those who ask."

##### The indefinite ;sahib_hal; is in a negative statement or a question {.unnumbered}

(@ex000055) [مَا خَابَ عَامِلٌ مُخْلِصًا]{.ar}
    [@nahw_wafi@ 2/403]{.citex}  
    "A worker, when sincere, does not fail."

(@ex000056) [لَا تَشْرَبْ فِي كُوبٍ مَكْسُورًا]{.ar}
    [@nahw_wafi@ 2/403]{.citex}  
    "Don't drink in a cup (when it is) broken."

(@ex000057) [أَجَاءَ أَحَدٌ رَاكِبًا]{.ar}
    [@nahw_arabi@ 2/44]{.citex}  
    "Did anyone come riding?"


##### The indefinite ;sahib_hal; without any special circumstance {.unnumbered}

Occasionally, 
the ;sahib_hal; may be indefinite without any special circumstance.^[@nahw_arabi@ 2/45--47]
For example:

(@ex000058) [وَصَلَّى وَرَاءَهُ قَوْمٌ قِيَامًا]{.ar}
    [@https://sunnah.com/bukhari:1113@]{.citex}  
    "and [some] people prayed behind him standing"

## The order of the ;hal;, the ;sahib_hal; and the ;3aamil;

The normal order is: first the ;3aamil;, then the ;sahib_hal;, then the ;hal;.
However, there is much variability permitted, subject to certain rules.

### The ;hal; preceding the ;3aamil;

The ;hal; may precede the ;3aamil; if
the ;3aamil; is an verb
or ;shibh_fi3l;
that flexes based on the doer.

So we can say:

(@ex000059) [رَاكِبًا جَاءَ زَيْدٌ]{.ar}
    [@wright@ 2/118B]{.citex}  
    "Zayd came riding."

(@ex000060) [مُسْرِعًا ذَا رَاحِلٌ]{.ar}
    [@wright@ 2/118B and @nahw_arabi@ 2/53]{.citex}  
    "In haste is this this (man) departing."  
    ([ذَا]{.ar} is a pointing noun like [هَـٰذَا]{.ar}. See section\ (ref).)

(@ex000061) [مُخْلِصًا زَيْدٌ دَعَا]{.ar}
    [add ref to alfiyyah ibn malik]  
    "Sincerely did Zayd supplicate."  
    (The ;hal; [مُخْلِصًا]{.ar} precedes not just its ;3aamil; in the ;xabar; [دَعَا]{.ar}, but also the ;mubtada; [زَيْدٌ]{.ar}.)

If the ;3aamil; is a verb or ;sifah; that is rigid (does not flex based on the doer),
then the ;hal; rarely^[ibn uthaymeen], if ever^[wright], precedes the ;3aamil;.
Examples of such ;3aamil;s are the verb of wonder and the ;af3al;.
For example:

(@ex000062) [مَا أَحْسَنَ زَيْدٌ ضَاحِكًا]{.ar}
    [@wright@ 2/118B]{.citex}  
    (not ;x; [ضَاحِكًا مَا أَحْسَنَ زَيْدٌ]{.ar})  
    "How handsome is Zayd (when) laughing!"

(@ex000063) [زَيْدٌ أَحْسَنُ مِنْ عَمْرٍو ضَاحِكًا]{.ar}
    [@wright@ 2/118B]{.citex}  
    (not ;x; [زَيْدٌ ضَاحِكًا أَحْسَنُ مِنْ عَمْرٍو]{.ar})  
    "Zayd is more handsome than [#eamr]{.trn2} (when) laughing."

An exception is permitted when a noun, in one ;hal;, is compared with itself or another noun in another ;hal;.
In this case, the ;hal; regularly precedes its ;af3al; ;3aamil;.
For example:

(@ex000064) [زَيْدٌ قَائِمًا أَحْسَنُ مِنْهُ قَاعِدًا]{.ar}
    [@wright@ 2/118C]{.citex}  
    "Zayd when standing is more handsome than [himself] when sitting."

(@ex000065) [زَيْدٌ مُفْرَدًا أَنْفَعُ مِنْ عَمْرٍو مُعَانًا]{.ar}
    [@wright@ 2/118C]{.citex}  
    "Zayd when alone is more useful than [#eamr]{.trn2} when assisted (by others)."

If the ;3aamil; is not a verb or a ;shibh_fi3l; but an expression that has verbal force,
then the ;hal; usually does not precede the ;3aamil;.^[See, however, @https://tafsir.app/albahr-almuheet/39/67@ for the recitation [والسماوات مطوياتٍ بيمينه]{.ar}. Also mentioned by @wright@ 2/118D]

(@ex000066) [كَأَنَّ زَيْدٌ رَاكِبًا أَسَدٌ]{.ar}
    [@wright@ 2/118D]{.citex}  
    (not ;x; [رَاكِبًا كَأَنَّ زَيْدٌ أَسَدٌ]{.ar})  
    "[It is] as if Zayd, when riding, is a lion."

(@ex000067) [زَيْدٌ فِي ٱلدَّارِ قَائِمًا]{.ar}
    [@wright@ 2/118D]{.citex}  
    (not ;x; [زَيْدٌ قَائِمًا فِي ٱلدَّارِ]{.ar})  
    "Zayd is in the house standing."

(@ex000068) [تِلْكَ هِنْدٌ بَاحِثَةً]{.ar}
    [@nahw_arabi@ 2/53]{.citex}  
    (not ;x; [بَاحِثَةً تِلْكَ هِنْدٌ]{.ar})  
    "That is Hind, searching."

### The ;hal; preceding the ;sahib_hal;

The ;hal; is generally allowed to precede the ;sahib_hal; when the ;sahib_hal; is in the ;ustate; or ;astate;.
For example:

(@ex000069) [جَاءَ ضَاحِكًا زَيْدٌ]{.ar}
    [@wright@ 2/119A]{.citex}  
    "Zayd came riding."

(@ex000070) [شَرِبْتُ ٱلْمَاءَ صَافِيًا]{.ar}
    [@nahw_arabi@ 2/48]{.citex}  
    "I drank the water clear."

Excepted from this general permissibility is if the ;sahib_hal; is restricted by [إِلَّا]{.ar}.
For example:

(@ex000071) [مَا جَاءَ أُسَامَةُ إِلَّا رَاكِبًا]{.ar}
    [@nahw_arabi@ 2/48]{.citex}  
    "[#usAmah]{.trn2} did not come except riding."

(@ex000072) [وَمَا نُرْسِلُ ٱلْمُرْسَلِينَ إِلَّا مُبَشِّرِينَ وَمُنْذِرِينَ]{.ar}
    [@https://quran.com/6/48@]{.citex}  
    "And We send not the messengers except as bringers of good tidings and warners."

When the ;sahib_hal; is in the ;istate; then:
if it is a ;mudafil; in an ;idaafah;, then the ;hal; should follow the ;sahib_hal; and not precede it.

For example:

(@ex000073) [أَعْجَبَنِي قِيَامُ زَيْدٍ مُسْرِعًا]{.ar}
    [@wright@ 2/119C]{.citex}  
    "Zayd's standing speedily pleased me."

If the ;sahib_hal; is in the ;istate; due to a preceding preposition, then
the ;hal; will usually follow it and not precede it.
For example:

(@ex000074) [مَرَرْتُ بِهِنْدٍ جَالِسَةً]{.ar}
    [@wright@ 2/119B]{.citex}  
    "I passed by Hind (when she was) sitting."

Occasionally, however, the ;hal; has been found to precede the ;istate; ;sahib_hal; preceded by a preposition.
For example:

(@ex000075) [وَمَا أَرْسَلْنَاكَ إِلَّا كَافَّةً لِلنَّاسِ]{.ar}
    [@https://quran.com/34/28@]{.citex}  
    "And We have not sent you except comprehensively to mankind"

### Reasons for varying the normal order

The natural order, as we have mentioned, is:
first the ;3aamil;, then the ;sahib_hal;, then the ;hal;.
So normally we would say:

(@ex000076) [حَضَرَ مُحَمَّدٌ مَاشِيًا]{.ar}
    [@nahw_arabi@ 2/55]{.citex}  
    "[#muHammad]{.trn2} came walking."

The speaker may choose to vary this normal order for a variety of reasons.
For example, if 
[#muHammad]{.trn2}
had been previously hampered from walking due to an illness or injury, then
in order to emphasize his being able to walk, the speaker may say:

(@ex000077) [حَضَرَ مَاشِيًا مُحَمَّدٌ]{.ar}
    [@nahw_arabi@ 2/55]{.citex}

Or if the listener was incorrectly assuming that
[#muHammad]{.trn2}
came riding and not walking, then the speaker may wish to disabuse him by saying

(@ex000078) [مَاشِيًا حَضَرَ مُحَمَّدٌ]{.ar}
    [@nahw_arabi@ 2/55]{.citex}

There may be other reasons as well.^[@maani_nahw@ 2/354]

## Transitory and permanent meanings for the ;hal;

Fundamentally, the ;hal; is transitory in its meaning;
i.e. it is not meant to be a permanent description of the ;sahib_hal;.
For example:

(@ex000079) [جَاءَ سَعِيدٌ غَاضِبًا]{.ar}
    [@nahw_arabi@ 2/28]{.citex}  
    "[#saeId]{.trn2} came angry"

(@ex000080) [أَقْبَلَ خَالِدٌ رَاكِبًا]{.ar}
    [@nahw_arabi@ 2/28]{.citex}  
    "[#xAlid]{.trn2} came riding."

In the above examples, the ;hal;s
[غَاضِبًا]{.ar} "angry"
and
[رَاكِبًا]{.ar} "riding"
are meant to be transitory descriptions,
such that it is conceivable that
[#saeId]{.trn2} may cease to be angry,
and that
[#xAlid]{.trn2} could come walking instead of riding.

<!--
However, there are circumstances in which the ;hal; may be a more permanent description of the ;sahib_hal;.
These circumstances are:

#### The ;hal; describes ;sahib_hal; coming in to existence {.unnumbered}

When the ;hal; describes ;sahib_hal; as it comes in to existence or relevance,
then it may have a permanent meaning.
-->

However, it is possible that the ;hal; have a more permanent meaning.
This is primarily when 
the ;hal; describes ;sahib_hal; as it comes in to existence or relevance.

For example:

(@ex000081) [وَخُلِقَ ٱلْإِنْسَانُ ضَعِيفًا]{.ar}
    [@https://quran.com/4/28@]{.citex}  
    "and mankind was created weak"

(@ex000082) [قَالَتْ رَبِّ إِنِّي وَضَعْتُهَا أُنْثَىٰ]{.ar}
    [@https://quran.com/3/36@]{.citex}  
    "she said, 'My Lord, I have delivered a female.'"

(@ex000083) [وَلَدَتْهُ أَزْرَقَ ٱلْعَيْنَينِ أَفْطَسَ ٱلْأَنْفِ]{.ar}
    [@nahw_arabi@ 2/29]{.citex}  
    "She gave birth to him blue-eyed (and) snub-nosed"

The ;hal; may also have a more permanent meaning in the sense that
while it describes the ;sahib_hal; linked in time to the ;3aamil;,
its meaning also applies more permanently to the ;sahib_hal;.
For example:

(@ex000084) [وَهَـٰذَا صِرَاطُ رَبِّكَ مُسْتَقِيمًا]{.ar}
    [@https://quran.com/6/126@ cited by @nahw_arabi@ 2/30]{.citex}  
    "And this is the path of your Lord, [leading] straight"  
    (The ;hal; [مُسْتَقِيمًا]{.ar} "straight" applies permanently to the ;sahib_hal; [صِرَاطُ رَبِّكَ]{.ar} "path of your Lord")

## Difference in meaning between the ;hal; and the ;na3t;

The ;hal; and the the ;na3t; are typically both sourced from ;sifah;s.
And generally when you use the ;sifah; as a ;hal; it will have a different meaning from when it is used as a ;sifah;.

Consider the following two examples:

(@ex000085) [هَـٰذَا ٱلْفَرَسُ ٱلسَّابِقُ]{.ar}
    [@maani_nahw@ 2/334]{.citex}  
    "This is the foremost horse."

(@ex000086) [هَـٰذَا ٱلْفَرَسُ سَابِقًا]{.ar}
    [@maani_nahw@ 2/334]{.citex}  
    "This is the horse (when it is) foremost"

The former sentence is describing the horse as being foremost,
but not necessarily at the time when the speaker is pointing to it.
So, at the moment of pointing to it, the horse may actually be tethered.
Whereas the latter sentence is describing the horse at the moment of pointing at it. 
It would likely be running and and being foremost at that time.

Similarly, consider:

(@ex000087) [أَقْبَلَ ٱلطَّالِبُ ٱلْمُقَصِّرُ]{.ar}
    [@maani_nahw@ 2/333]{.citex}  
    "The slacking student approached."

(@ex000088) [أَقْبَلَ ٱلطَّالِبُ مُقَصِّرًا]{.ar}
    [@maani_nahw@ 2/333]{.citex}  
    "The student approached (while) slacking."

The same distinction appiles to the above two examples.
The former sentence describes the student as a slacker generally.
But he may not be slacking at the moment when he is approaching.
Whereas the latter sentence describes the student as slacking when he is approaching.
He may not be a slacker in general.

<!--
Even when the ;sifah; used for the ;hal; has a more permanent meaning,
there can be a distinction from it being used as a ;na3t;.
-->

However, there can sometimes be some overlap in meaning.^[See also [شرح إبي سعيد بهامش كتاب سيبويه]{.ar} 1/272 cited by @maani_nahw@ 2/350]
For example, in the scenario when all the following conditions are satisfied:

* the ;hal; has a transitory meaning,
* the meaning of the ;hal; is a description of motion or posture (like "sitting", "standing", "sleeping", "running", etc.),
* the ;sahib_hal; is indefinite,
* the ;3aamil; is an expression that has verbal force (see section\ (ref)).

In such a case, the ;sifah; used as a ;na3t; may have a somewhat similar meaning to it being used a ;hal;.
For example:
<!--
(@ex000089) [فِي ٱلْبَيْتِ رَجُلٌ نَائمٌ]{.ar}  
    "In the house, is a sleeping man."  
    (;na3t;)

(@ex000090) [فِي ٱلْبَيْتِ رَجُلٌ نَائِمًا]{.ar}  
    "In the house, is a man sleeping."  
    (;hal;)
-->

(@ex000091) [فِيهَا رَجُلٌ قَائِمٌ]{.ar}  
    "In it (i.e. the house), is a standing man."  
    (;na3t;)

(@ex000092) [فِيهَا رَجُلٌ قَائِمًا]{.ar}  
    [[سيبويه]{.ar} 1/272 cited by @maani_nahw@ 2/352]{.citex}  
    "In the house, is a man standing."  
    (;hal;)

There may also be a case where the ;hal; is indistinguishable from the ;na3t; due to the ;sahib_hal; being indefinite and in the ;astate;.
For example:

(@ex000093) [رَأَيْتُ طَالِبًا مُقَصِّرًا]{.ar}
    [@maani_nahw@ 2/352]{.citex}  
    "I saw a student slacking."  
    or  
    "I saw a slacking student."  

## An ;jamid; noun as the ;hal;

Because the ;hal; is a description of the ;sahib_hal;,
and a description is likely to be a ;sifah;,
and ;sifah;s are typically ;mushtaqq; nouns,
it therefore follows that the ;hal; is likely to be a ;mushtaqq; noun.
Most of the examples we have seen so far have been of the ;hal; as a
;mushtaqq; noun.
For example:
[رَاكِبًا]{.ar},
[غَاضِبًا]{.ar}, etc.
However, it is possible for the
;hal; to be ;jamid; noun.
Here are some examples:

(@ex000094) [طَلَعَ ٱلْقَمَرُ بَدْرًا]{.ar}
    [@wright@ 2/115A]{.citex}  
    "The moon rose (as) a full moon."

(@ex000095) [كَرَّ زَيْدٌ أَسَدًا]{.ar}
    [@wright@ 2/115A]{.citex}  
    "Zayd charged (like) a lion." 

(@ex000096) [بِعْهُ مُدًّا بِدِرْهَمٍ]{.ar}
    [@wright@ 2/115A]{.citex}  
    "Sell it (at the rate of) a mudd for a dirham"  
    (a mudd is a measure of volume)

(@ex000097) [بِعْتُ ٱلشَّاءَ شَاةً وَدِرْهَمًا]{.ar}
    [@wright@ 2/115A]{.citex}  
    "I sold the sheep (at the rate of) a sheep [for] a dirham."

(@ex000098) [بَايَعْتُهُ يَدًا بِيَدٍ]{.ar}
    [@wright@ 2/115A]{.citex}  
    "I traded with him hand in hand"  
    (i.e. for ready money)

(@ex000099) [بَيَّنْتُ لَهُ حِسَابَهُ بَابًا بَابًا]{.ar}
    [@wright@ 2/115A]{.citex}  
    "I explained his account for him item by item."

(@ex000100) [دَخَلَ ٱلْقَوْمُ رَجُلًا رَجُلًا]{.ar}
    [@nahw_arabi@ 2/30]{.citex}  
    "The people entered, man by man."

(@ex000101) [كَلَّمْتُهُ فَاهُ إِلَىٰ فِيَّ]{.ar}
    [@wright@ 2/115B]{.citex}  
    "I spoke to him his mouth to my mouth."  
    (i.e. face to face)

(@ex000102) [هَـٰذَا عِنَبًا أَطْيَبُ مِنْهُ زَبِيبًا]{.ar}
    [@wright@ 2/115B]{.citex}  
    "This (fruit), as a grape, is better than it as a raisin."

(@ex000103) [وَكَذَ ٰلِكَ أَنْزَلْنَاهُ قُرْآنًا عَرَبِيًّا]{.ar}
    [@https://quran.com/20/113@ cited by @nahw_arabi@ 2/33]{.citex}  
    "And thus We have sent it down as an Arabic Qur’ān"

(@ex000104) [هَـٰذِهِ أَمْوَالُكَ ذَهَبًا]{.ar}
    [@nahw_arabi@ 2/34]{.citex}  
    "These are your wealths, as gold."

(@ex000105) [هَـٰذِهِ فِضَّتُكَ خَاتَمًا]{.ar}
    [@nahw_arabi@ 2/34]{.citex}  
    "This is your silver, as a ring."

(@ex000106) [هَـٰذَا خَاتَمُكَ فِضَّةً]{.ar}
    [@nahw_arabi@ 2/34]{.citex}  
    "This is your ring, in silver"

## A ;masdar; as the ;hal;

<!--
While the ;hal; is usually a ;sifah; it does frequently occur as an indefinite ;masdar;.
-->
The ;masdar; can sometimes _appear_ to be a ;hal;.
For example:

(@ex000107) [أَقْبَلَ عَلِيٌّ رَكْضًا]{.ar}
    [@maani_nahw@ 2/345]{.citex}  
    "[#ealiyy]{.trn2} approached (in the state of) running."

In the above example, the opinion of some scholars would be that
the ;masdar;
[رَكْضًا]{.ar}
is a ;hal;.
And this is a substitute for saying 
[أَقْبَلَ عَلِيٌّ رَاكِضًا]{.ar}.

When the ;masdar; is used thus it remains in the indefinite singular regardless of the number of the ;sahibs_hal;.
For example:

(@ex000108) [أَقْبَلَ ٱلْقَوْمُ رَكْضًا]{.ar}  
    "The people approached running."

The reasons for using a ;masdar;
[رَكْضًا]{.ar}
in this way instead of the ;sifah;
[رَاكِضًا]{.ar}
may be:

 i. Emphasis. The ;masdar; signifies purely the meaning of the verb "to run".
    Whereas the ;sifah; signifies the meaning of the verb along with person described by the ;sifah; (the runner).
    So using the ;masdar; as a ;hal; draws attention to the meaning of running rather than the person who is running.
    The ;masdar; used in this way can also be seen as a sort of metaphor,
    as if [#ealiyy]{.trn2}, while executing the action of running, _became_ the act of running.^[@maani_nahw@ 2/348]

ii. Expanding the sense of the adverb to incorporate other adverbs.
    The ;masdar; 
    [رَكْضًا]{.ar},
    in the above example, can also be analyzed as an ;mmutlaq; (being a ;naib; to the ;masdar; [إِقْبَال]{.ar}) meaning:

    (@) [أَقْبَلَ عَلِيٌّ إِقْبَالَ رَكْضٍ]{.ar}
        [@maani_nahw@ 2/348]{.citex}  
       "[#ealiyy]{.trn2} approached (in) the type of approaching (that is) running."

    The use of the ;masdar; in this way could then be used to intend both the ;hal; meaning and the ;mmutlaq; meaning together.
    That is [#ealiyy]{.trn2}'s type and state of approaching was running.

    Depending on the meaning of the ;masdar;, other types of adverbs, like the ;mafull;, may be included in this expanded sense as well.^[@maani_nahw@ 2/348]

Some scholars are conservative in analyzing a ;masdar; as a ;hal;, and instead prefer that it be analyzed as another adverb, like a (;naib;) ;mmutlaq; or an ;mafull;, etc.^[See @faysal_mansoor_articles@ 529--530]
And if the meaning of the ;masdar; does not allow it to be analyzed as another adverb, and only as a ;hal; then it is accepted as a permitted usage but one that is restricted to what has been recorded from Classical Arabic.

Here are some examples of ;masdar;s having being analyzed as ;hal;.
They may fit other adverbs instead or as well.

(@ex000109) [قَتَلْتُهُ صَبْرًا]{.ar}
    [@wright@ 2/114C]{.citex}  
    "I killed him in cold blood."

(@ex000110) [كَلَّمْتُهُ مُشَافَهَةً]{.ar}
    [@ibn_ya3ish_mufassal@ 2/12]{.citex}  
    "I spoke to him face to face."

(@ex000111) [يَدْعُونَ رَبَّهم خَوْفًا وطَمَعًا]{.ar}
    [@https://quran.com/32/16@]{.citex}  
    "they supplicate their Lord in fear and aspiration"  
    ([خَوْفًا]{.ar} (above) is analyzed as either a ;mafull; or a ;hal;.^[See @https://tafsir.app/albahr-almuheet/32/16@])


(@ex000112) [ٱلَّذِینَ یُنْفِقُونَ أَمْوَالَهُمْ بِٱلَّيْلِ وَٱلنَّهَارِ سِرًّا وَعَلَانِیَةً]{.ar}
    [@https://quran.com/2/274@]{.citex}  
    "Those who spend their wealth [in Allāh's way] by night and by day, secretly and publicly"  
    ([سِرًّا]{.ar} is analyzed as either a ;hal; or a ;na3t; to a deleted ;mmutlaq; [إِنْفَاقًا]{.ar}.^[@https://tafsir.app/albahr-almuheet/2/274@])


(@ex000113) [إنَّ الَّذِينَ يَأْكُلُونَ أمْوالَ اليَتامى ظُلْمًا]{.ar}
    [@https://quran.com/4/10@]{.citex}  
    "Indeed, those who devour the property of orphans unjustly"  
    ([ظُلْمًا]{.ar} (above) is analyzed as either a ;mafull; or a ;hal;.^[@https://tafsir.app/albahr-almuheet/4/10@])


(@ex000114) [حَتَّىٰ إِذَا جَاءَتْهُمُ ٱلسَّاعَةُ بَغْتَةً]{.ar}
    [@https://quran.com/6/31@]{.citex}  
    "until when the Hour [of resurrection] comes upon them unexpectedly"  
    ([بَغْتَةً]{.ar} (above) is analyzed as either a ;hal; or a ;mmutlaq;.^[@https://tafsir.app/albahr-almuheet/6/30@])

<!--
[خَوْفًا]{.ar} (above) is analyzed as either a ;mafull; or a ;hal;.^[See https://tafsir.app/albahr-almuheet/32/16]
[سِرًّا]{.ar} is analyzed as either a ;hal; or a ;na3t; to a deleted ;mmutlaq; [إِنْفَاقًا]{.ar}.^[https://tafsir.app/albahr-almuheet/2/274]
([ظُلْمًا]{.ar} (above) is analyzed as either a ;mafull; or a ;hal;.^[@https://tafsir.app/albahr-almuheet/4/10@])
([بَغْتَةً]{.ar} (above) is analyzed as either a ;hal; or a ;mmutlaq;.^[@https://tafsir.app/albahr-almuheet/6/30@])
-->

## A sentence as the ;hal;

In the examples so far,
the ;hal; has always been a single word,
usually an ;sifah;.
For example,
[جَاءَ زَيْدٌ ضَاحِكًا]{.ar} "Zayd came laughing".
Instead, of using the ;sifah;
[ضَاحِكًا]{.ar},
we can instead use the ;ustate; ;mudarie; verb
[يَضْحَكُ]{.ar}:

(@haal-sentence-mudarie-zayd-laughing) [جَاءَ زَيْدٌ يَضْحَكُ]{.ar}
    [@wright@, 2/331C]{.citex}  
    "Zayd came laughing."

Actually,
[يَضْحَكُ]{.ar}
is not just a verb.
Rather, it is a complete sentence
comprising of the verb itself and the ;faa3il;
which, in this case, is the hidden pronoun "he".
So the ;hal; here is a sentence.

As we know, the ;hal; describes the ;sahib_hal; during time of ;hal;'s governing verb.
The use of the ;mudarie; verb
[يَضْحَكُ]{.ar}
signifies that Zayd's action of laughing was ongoing during the time of the ;3aamil; [جَاءَ]{.ar}.
So [يَضْحَكُ]{.ar} has a past meaning because of the ;madi; verb [جَاءَ]{.ar}.
An additional verb like [كَانَ]{.ar} is not needed to transport the verb
[يَضْحَكُ]{.ar} to the past.
Similarly, if the ;3aamil; was in the present or the future, the ;mudarie; verb in the ;hal; would automatically be transported to the present or future as well.
For example:

(@ex000115) [سَيَأْتِي زَيْدٌ يَضْحَكُ]{.ar}  
    "Zayd will come laughing."

In fact, it is not permitted for the ;hal; sentence that begins with the ;mudarie; verb to itself be prefixed with [سَ]{.ar} or [سَوْفَ]{.ar}.^[@maani_nahw@ 2/354 citing @radiy_kafiyah@. But see @https://tafsir.app/ibn-aashoor/37/99@ for a dissenting opinion.]
So we cannot say (intending [سَيَضْحَكُ]{.ar} to be a ;hal;):

(@ex000116) ;x; [سَيَأْتِي زَيْدٌ سَيَضْحَكُ]{.ar} or  
    ;x; [يَأْتِي زَيْدٌ سَيَضْحَكُ]{.ar}

This restriction only applies to ;mudarie; verbs that begin a sentence ;hal;.
If a ;mudarie; verb begins a sentence that is not a ;hal; then it may begin with [سَ]{.ar} or [سَوْفَ]{.ar}.
For example:

(@ex000117) [وَقَالَ إِنِّى ذَاهِبٌ إِلَىٰ رَبِّى سَيَهْدِينِ]{.ar}
    [@https://quran.com/37/99@]{.citex}  
    "And [then] he said, 'Indeed, I will go to [where I am ordered by] my Lord; He will guide me."

Here are some more examples of sentence ;hal;s comprised of a ;mudarie; verb and a ;faa3il; (or ;naib; ;faa3il;) pronoun:

(@haal-quran-12-16) [وَجَاءُوا أَبَاهُمْ عِشَاءً يَبْكُونَ]{.ar}
    [@https://quran.com/12/16@]{.citex}  
    "And they came to their father at night, weeping."

### The link between the sentence ;hal; and the ;sahib_hal;

The sentence comprising of only the ;mudarie; verb and its doer is the simplest, and one of the most common, kind of ;hal; sentence.
However, more complex ;hal; sentences are also possible.
And the ;sahib_hal; need not always be the ;faa3il; of the verb in the sentence.

But the sentence ;hal; needs to have a link between it and the ;sahib_hal;.
This link is often a pronoun that refers back to the ;sahib_hal;.
In the examples above this link pronoun was the ;faa3il; pronoun of the ;mudarie; verb.
Here is an example of a more complex ;hal; sentence:

(@ex000118) [جَاءَ زَيْدٌ يَدُهُ عَلَىٰ رَأْسِهِ]{.ar}
    [@wright@, 2/331A]{.citex}  
    "Zayd came (with) his hand on his head."  

In the example above,
the sentence [يَدُهُ عَلَىٰ رَأْسِهِ]{.ar} is the ;hal;. 
Note that [يَد]{.ar} is in the ;ustate; because it is the ;mubtada; of the sentence.
It is not in the ;astate; because it is not, by itself, the ;hal;.
The entire sentence
[يَدُهُ عَلَىٰ رَأْسِهِ]{.ar} is considered to be in the ;astate; as the ;hal;.
The link is the pronoun [ه]{.ar} in [يَدُهُ]{.ar} and [رَأْسِهِ]{.ar}.

Here are some more examples:

(@ex000119) [ٱهْبِطُوا۟ بَعْضُكُمْ لِبَعْضٍ عَدُوٍّ]{.ar}
    [@https://quran.com/2/36@]{.citex}  
    "Go down, [all of you], as enemies to one another"  
    (The sentence [بَعْضُكُمْ لِبَعْضٍ عَدُوٍّ]{.ar} is the ;hal;. The link is the pronoun [كُمْ]{.ar} in [بَعْضُكُمْ]{.ar}.)

## The [و]{.ar} of ;hal; and its rules

Instead of, or in addition to, a pronoun as the link between the sentence ;hal; and the ;sahib_hal;,
a special [و]{.ar}, called the
[و]{.ar}\ _of ;hal;_,
may be used.
The [و]{.ar} of ;hal;
signifies that the sentence ;hal; occurred _while_ the governing verb took place.
Here are some examples of the
the [و]{.ar} of ;hal;:

(@haal-waw-haal-zayd-crying) [قَامَ زَيْدٌ وَهَوَ بَاكٍ]{.ar}
    [@wright@ 2/330C]{.citex}  
    "Zayd stood up while he was crying."

(@haal-waw-haal-wudoo) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم  مَرَّ بِسَعْدٍ وَهُوَ يَتَوَضَّأُ]{.ar}
    [@https://sunnah.com/ibnmajah:425@]{.citex}  
    "that the Messenger of [#allAh]{.trn2} ;pbuh; passed by [#saed]{.trn2} while he was performing ablution"

We have defined the ;hal; as an adverb that describes the ;sahib_hal;.
However,
sometimes, the ;hal; sentence that is linked with a
[و]{.ar} of ;hal;
won't apparently describe the ;sahib_hal;.
In fact, it may not even refer to the ;sahib_hal; at all.
For example:

(@haal-waw-haal-zayd-busy) [ذَهَبَ زَيْدٌ وَعَمْرٌو يَشْتَغِلُ]{.ar}
    [@wright@ 2/331A]{.citex}  
    "Zayd went while [#eamr]{.trn2} was busy."

In the example above,
the ;hal;'s
description of the ;sahib_hal; is only circumstantial,
in that it alludes to the time in which the action of the governing verb occurred.
In such cases
the meaning of the ;hal; approaches that of the adverb of time.
This is another of the cases where the lines between different types of adverbs get blurred.
We have seen similar cases in sections\ (ref).
Here are some more examples:

<!--
### Rules of the [و]{.ar} of ;hal;
-->

Depending on the sentence,
the [و]{.ar} of ;hal;
can be either mandatory, optional, or disallowed.

Let's go over the different types of ;hal; sentences, and discuss the ruling of
the [و]{.ar} of ;hal;
in each type of sentence.

<!--
Keep in mind that in the cases where
the [و]{.ar} of ;hal; is optional,
the sentence will often have a different meaning with
the [و]{.ar} of ;hal;
versus without it.
We will discuss these difference in meanings in section\ (ref).
-->


### The ;hal; sentence is a ;j_ism;

When the ;hal; sentence is a ;j_ism;,
then there are three possibilities:

  i. The ;hal; sentence is devoid of a pronoun referring back to the ;sahib_hal;.
     In this case,
     the [و]{.ar}\ of ;hal;
     is obligatory.
     For example:

     (@) [مَرَرْتُ بِزَيْدٍ وَعَمْرٌو فِي ٱلدَّارِ]{.ar}
         [@muqtadab@ 4/125 cited by @zidan_wujoob_waw@]{.citex}  
         "I passed by Zayd while [#eamr]{.trn2} (was) in the house."

     In the above example the ;sahib_hal; is [زَيْد]{.ar}
     and the ;hal; is the ;j_ism;
     [عَمْرٌو فِي ٱلدَّارِ]{.ar}.
     The sentence ;hal; does not have a pronoun that refers back to the ;sahib_hal;.
     Therefore the [و]{.ar} of ;hal; is necessary to link the sentence ;hal; to the ;sahib_hal;.

     We have also already seen this usage in example (@haal-waw-haal-zayd-busy) [ذَهَبَ زَيْدٌ وَعَمْرٌو يَشْتَغِلُ]{.ar}.
     Here are more examples:

     (@) [كَمَا أَخْرَجَكَ رَبُّكَ مِنْ بَيْتِكَ بِٱلْحَقِّ وَإِنَّ فَرِيقًا مِّنَ ٱلْمُؤْمِنِينَ لَكَارِهُونَ]{.ar}
         [@https://quran.com/8/5@ cited by @nahw_arabi@ 2/58]{.citex}  
         "[It is] just as when your Lord brought you out of your home [for the battle of Badr] in truth, while indeed, a party among the believers were unwilling,"

     (@) [قَالُوا لَئِنْ أَكَلَهُ ٱلذِّئْبُ وَنَحْنُ عُصْبَةٌ]{.ar}
         [@https://quran.com/12/14@ cited by @nahw_arabi@ 2/58]{.citex}  
         "They said, 'If a wolf should eat him while we are a [strong] clan,"

 ii. The sentence ;hal; begins with a pronoun that refers to ;sahib_hal;.
     In this case as well,
     the [و]{.ar}\ of ;hal;
     is obligatory.
     The link between the sentence ;hal; and the ;sahib_hal; is now both the pronoun and the [و]{.ar}\ of ;hal;.
     We saw this usage in examples (@haal-waw-haal-zayd-crying) [قَامَ زَيْدٌ وَهَوَ بَاكٍ]{.ar} and (@haal-waw-haal-wudoo) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم  مَرَّ بِسَعْدٍ وَهُوَ يَتَوَضَّأُ]{.ar}.

     Here are some more examples:

     (@) [لَا تَقْرَبُوا ٱلصَّلَاةَ وَأَنتُمْ سُكَارَىٰ]{.ar}
         [@https://quran.com/4/43@ cited by @nahw_arabi@ 2/58]{.citex}  
         "do not approach prayer while you are intoxicated"

     (@) [كَذَبْتُمْ وَأَنْتُمْ تَعْلَمُونَ]{.ar}
         [@wright@ 2/330D]{.citex}  
         "You lied, knowing (that you did so)."
    
     (@) [وَلَا يَأْتُونَ الصَّلَاةَ إِلَّا وَهُمْ كُسَالَى]{.ar}
         [@https://quran.com/9/54@]{.citex}  
         "and that they come not to prayer except while they are lazy"

     Some grammarians admitted optionally dropping the [و]{.ar}\ of ;hal; in this case to allow sentences like:

     (@) [جَاءَنِي زَيْدٌ هُوَ فَارِسٌ]{.ar}
         [@maani_zajjaj@ 2/317 cited by @zidan_wujoob_waw@]{.citex}  
         "Zayd came to me while he (was) on horseback."  
         (instead of the more normal usage with the [و]{.ar}\ of ;hal;: [جَاءَنِي زَيْدٌ وَهُوَ فَارِسٌ]{.ar})
        
     But this opinion is considered anomalous by the majority of the grammarians.^[@zidan_wujoob_waw@]

iii. The ;hal; sentence has a pronoun that refers to the ;sahib_hal; but it does not begin the ;hal; sentence.
     In this case,
     the [و]{.ar}\ of ;hal;
     is optional.
     But generally, it will be preferred to have
     the [و]{.ar}\ of ;hal;.
     For example:

     (@) [جَاءَ مُحَمَّدٌ وَيَدُهُ فِي جَيْبِهِ.]{.ar}
         [@nahw_arabi@ 2/61]{.citex} (more preferred)  
         [جَاءَ مُحَمَّدٌ يَدُهُ فِي جَيْبِهِ.]{.ar}
         [@nahw_arabi@ 2/61]{.citex} (less preferred)  
         [#muHammad]{.trn2} came (with) his hand in his pocket."

     If the ;hal; sentence's ;xabar; is a ;shibh_jumlah; (consisting of an prepositional or adverbial phrase),
     and the ;xabar; precedes the ;mubtada;,
     then dropping
     the [و]{.ar}\ of ;hal;
     is normal.^[@dalaail_jurjani@ 1/203]
     For example:

     (@) [جَاء زَيْدٌ فِي يَدِهِ سَوْطٌ]{.ar}  
         "Zayd came (with) a whip in his hand."  
         (The ;hal; sentence is [فِي يَدِهِ سَوْطٌ]{.ar}. Its ;xabar; [فِي يَدِهِ]{.ar} precedes its ;mubtada; [سَوْطٌ]{.ar}.)

### The ;hal; sentence is a verbal sentence that begins with a ;madi; verb

There are several possible cases here:

  i. The ;hal; sentence is devoid of a pronoun that refers back to the ;sahib_hal;.
     In this case
     the [و]{.ar}\ of ;hal;
     is mandatory.
     Furthermore, if the ;hal; sentence is affirmative, the ;madi; verb shall be preceded by the particle [قَدْ]{.ar}.
     And if the ;hal; sentence is negative, the ;madi; verb shall not be preceded by the particle [قَدْ]{.ar}.
     Examples:

     (@) [جِئْتُ وَقَدْ طَلَعَتِ ٱلشَّمْسُ]{.ar}
         [@nahw_arabi@ 2/58]{.citex}  
         "I came while the sun had already risen."

     (@) [جِئْتُ وَمَا طَلَعَتِ ٱلشَّمْسُ]{.ar}
         [@nahw_arabi@ 2/58]{.citex}  
         "I came while the sun had not risen."

 ii. The ;hal; sentence has a pronoun that refers back to the ;sahib_hal;.
     In this case
     the [و]{.ar}\ of ;hal;
     is optional.
     Furthermore, if the ;hal; sentence is affirmative, the ;madi; verb can optionally be preceded by the particle [قَدْ]{.ar}.
     And if the ;hal; sentence is negative, the ;madi; verb shall not be preceded by the particle [قَدْ]{.ar}.
     Here are some examples:

     Affirmative with [و]{.ar}\ of ;hal; and with [قَدْ]{.ar}. (This is the most common case.):

     (@) [وَمَا لَنَا أَلَّا نُقَاتِلَ فِى سَبِيلِ ٱللَّهِ وَقَدْ أُخْرِجْنَا مِنْ دِيَارِنَا وَأَبْنَائِنَا]{.ar}
         [@https://quran.com/2/246@ cited by @wright@ 2/332B]{.citex}  
         "And why should we not fight in the cause of Allāh when we have been driven out from our homes and from our children?"

     Affirmative with [و]{.ar}\ of ;hal; and without [قَدْ]{.ar}:

     (@) [قَالُوا۟ أَنُؤْمِنُ لَكَ وَٱتَّبَعَكَ ٱلْأَرْذَلُونَ]{.ar}
         [@https://quran.com/26/111@ cited by @nahw_arabi@ 2/62]{.citex}  
         "They said, 'Should we believe you while you are followed by the lowest [class of people]?'"

     Affirmative without [و]{.ar}\ of ;hal; and without [قَدْ]{.ar}:

     (@) [أَوْ جَاءُوكُمْ حَصِرَتْ صُدُورُهُمْ أَنْ يُقَاتِلُوكُمْ]{.ar}
         [@https://quran.com/4/90@ cited by @nahw_arabi@ 2/62 and @wright@ 2/332B]{.citex}  
         "or those who come to you, their hearts strained at [the prospect of] fighting you"

     Affirmative without [و]{.ar}\ of ;hal; and with [قَدْ]{.ar}:

     (@) [رَأَيْنَاهُ قَدْ تَغَيَّرَ لِزَيْدٍ وَكَانَ عَلَىٰ جُنْدِهِ]{.ar}
         [@wright@ 2/332C]{.citex}  
         "We saw him (when) he had changed [color due to being enraged] at Zayd who (was) [in command of] his army."

     Negative with [و]{.ar} of ;hal; (more common):

     (@) [جَاءَ زَيْدٌ وَمَا قَامَ أَبُوهُ]{.ar}
         [@wright@ 2/332D]{.citex}  
         "Zayd came without his father having stood up."

     Negative without [و]{.ar} of ;hal; (less common):

     (@) [جَاءَ زَيْدٌ مَا قَامَ أَبُوهُ]{.ar}
         [@wright@ 2/332D]{.citex}  
         "Zayd came without his father having stood up."

iii. The ;hal; sentence is an exception, preceded by [إِلَّا]{.ar}.
     In this case
     the [و]{.ar}\ of ;hal;
     is prohibited.
     For example:

     (@) [وَمَا يَأْتِيهِم مِّن رَّسُولٍ إِلَّا كَانُوا بِهِ يَسْتَهْزِءُونَ]{.ar}
         [@https://quran.com/15/11@ cited by @nahw_arabi@ 2/61]{.citex}  
         "And no messenger would come to them except that they ridiculed him."  
         (The sentence [كَانُوا بِهِ يَسْتَهْزِءُونَ]{.ar} is the ;hal; beginning with a ;madi; verb.)

     Some grammarians allowed 
     the [و]{.ar}\ of ;hal;
     in this case, but the examples they cite are considered irregular to normal usage.^[@zidan_haalaat_rabt_waw@]

 iv. The ;madi; verb is followed by the ;3atf; [أَوْ]{.ar}.
     In this case, the ;madi; verb is used with a conditional meaning.
     For example:

     (@) [أَحْفَظُ زَوْجِي غَابَ أَوْ حَضَرَ]{.ar}
         [@nahw_arabi@ 2/61]{.citex}  

     (@) [لأضربنَّه ذهب أو مكث]{.ar}
         [@zidan_haalaat_rabt_waw@ and @ibn_hisham_awdah_almasaalik@ 2/289]{.citex}  
         "I will certainly beat him [whether] he went or stayed."

### The ;hal; sentence is a verbal sentence that begins with a ;mudarie; verb

When a sentence ;hal; begins with a ;mudarie; verb,
then, if the ;mudarie; is used with a continuous meaning (i.e. not with [لَمْ]{.ar} or [لَمَّا]{.ar}),
then the ;hal; sentence will contain a pronoun that refers to the ;sahib_hal;.
If the ;mudarie; is used with a past meaning (i.e. with [لَمْ]{.ar} or [لَمَّا]{.ar}),
then the ;hal; sentence may or may not have a pronoun that refers to the ;sahib_hal;.^[Derived from sections [علةُ امتناع ربط المضارع المثبت بالواو]{.ar} and [علّة امتناع ربط المضارع المنفي بـ(لا) و(ما) بالواو]{.ar} in @zidan_haalaat_rabt_waw@]

There are again a number of possible cases.

  i. The sentence is affirmative and the ;mudarie; verb is preceded by the particle [قَدْ]{.ar}.
     In this case,
     the [و]{.ar}\ of ;hal;
     is obligatory.
     For example,

     (@) [لِمَ تُؤْذُونَنِى وَقَدْ تَعْلَمُونَ أَنِّى رَسُولُ ٱللَّهِ إِلَيْكُمْ]{.ar}
         [@https://quran.com/61/5@ cited by @wright@ 2/331C]{.citex}  
         "why do you harm me while you certainly know that I am the messenger of Allāh to you?"

 ii. The sentence is affirmative and the ;mudarie; verb is not preceded by the particle [قَدْ]{.ar}.
     We assume here that the sentence ;hal; contains a pronoun that refers to the ;sahib_hal;.

     In this case,
     the [و]{.ar}\ of ;hal;
     is usually not used.
     We have already seen examples of this case earlier, like (@haal-sentence-mudarie-zayd-laughing) [جَاءَ زَيْدٌ يَضْحَكُ]{.ar}
     and (@haal-quran-12-16) [وَجَاءُوا أَبَاهُمْ عِشَاءً يَبْكُونَ]{.ar}.

     Here are some more examples:

     (@) [جَاءَ ٱلْأَمِيرُ تُقَادُ ٱلْجَنَائِبُ بَيْنَ يَدَيْهِ]{.ar}
         [@wright@ 2/331C]{.citex}  
         "The commander came with the horses led in front of him."  
         ([جَنَائِب]{.ar} is the plural of [جَنِيب]{.ar} which is a word for a tractable horse that is led.)

     (@) [وَجَاءَ رَجُلٌ مِنْ أَقْصَى ٱلْمَدِينَةِ يَسْعَىٰ]{.ar}
         [@https://quran.com/28/20@]{.citex}  
         "And a man came from the farthest end of the city, running."

     What we have shown above constitutes the more common usage.
     However, we do sometimes see a ;hal; sentence beginning with a ;mudarie; verb with
     the [و]{.ar}\ of ;hal;
     and without [قَدْ]{.ar}.
     For example,

     (@) [قُمْتُ وَأَصُّكُ عَيْنَهُ]{.ar}
         [@nahw_arabi@ 2/59 and @zidan_haalaat_rabt_waw@]{.citex}  
         "I stood up, slapping his eye."

     More usually though,
     if
     a [و]{.ar}\ of ;hal;
     is to be used with a ;mudarie; verb,
     then a pronoun referring to the ;faa3il; is inserted before it, converting the ;hal; sentence to a ;j_ism;, thus:

     (@) [قُمْتُ وَأَنَا أَصُّكُ عَيْنَهُ]{.ar}  
         "I stood up, slapping his eye."

     We have already covered this type of ;hal; sentence in section\ (ref) above.

<!--
The و in ويكلم may be a واو عطف?
     In any case, here is an example from ;quran;
     where a sentence beginning with a ;mudarie; verb not preceded by [قَدْ]{.ar} has been interpreted as a ;hal;

     (@) [إِذْ قَالَتِ ٱلْمَلَاىِٕكَةُ يَا مَرْیَمُ إِنَّ ٱللَّهَ یُبَشِّرُكِ بِكَلِمَةٍ مِنْهُ ٱسْمُهُ ٱلْمَسِیحُ عِیسَى ٱبْنُ مَرْیَمَ وَجِیهًا فِی ٱلدُّنْيَا وَٱلْآخِرَةِ وَمِنَ ٱلْمُقَرَّبِینَ ۝ وَیُكَلِّمُ ٱلنَّاسَ فِی ٱلْمَهْدِ وَكَهْلًا وَمِنَ ٱلصَّالِحِینَ ۝]{.ar}  
         [@https://quran.com/3/45-46@ cited by @zidan_haalaat_rabt_waw@]{.citex}  
         [And mention] when the angels said, "O Mary, indeed Allāh gives you good tidings of a word from Him, whose name will be the Messiah, Jesus, the son of Mary - distinguished in this world and the Hereafter and among those brought near [to Allāh]. He will speak to the people in the cradle and in maturity and will be of the righteous."  
         (The sentence [وَيُكَلِّمُ]{.ar} has been analyzed as a ;hal;.^[@https://tafsir.app/albahr-almuheet/3/46@])
-->

iii. The sentence is negative and the ;mudarie; verb is negated with [لَا]{.ar} or [مَا]{.ar}.
     We again assume here that the sentence ;hal; contains a pronoun that refers to the ;sahib_hal;.
     In this case,
     the [و]{.ar}\ of ;hal;
     is prohibited.

     (@) [وَمَا لَنَا لَا نُؤْمِنُ بِٱللَّهِ]{.ar}
         [@https://quran.com/5/84@ cited by @nahw_arabi@ 2/59 and @ibn_hisham_awdah_almasaalik@ 2/289]{.citex}  
         "And why should we not believe in Allāh"

     (@) [عَهَدْتُكَ مَا تَصْبُو وَفِيكَ شَبِيبَةٌ]{.ar}
         [@nahw_arabi@ 2/60 and @ibn_hisham_awdah_almasaalik@ 2/290]{.citex}  
         "I knew you when you were not childish while [you had] in you youth."  
         ([مَا تَصْبُوا]{.ar} "You were not childish" is a sentence ;hal;)

 iv. The sentence is negative and the ;mudarie; verb is negated with [لَمْ]{.ar}.
     Here, the sentence ;hal; need not contain a pronoun that refers to the ;sahib_hal;.
     In this case,
     the [و]{.ar}\ of ;hal;
     is usually kept,
     although it is permissible to drop it.
     For example:

     (@) [أَوْ قَالَ أُوحِىَ إِلَىَّ وَلَمْ يُوحَ إِلَيْهِ شَىْءٌ]{.ar}
         [@https://quran.com/6/93@ cited by @nahw_arabi@ 2/60]{.citex}  
         "or says, 'It has been inspired to me,' while nothing has been inspired to him"

     (@) [فَٱنْقَلَبُوا بِنِعْمَةٍ مِنَ ٱللَّهِ وَفَضْلٍ لَمْ يَمْسَسْهُمْ سُوءٌ]{.ar}
         [@https://quran.com/6/93@ cited by @nahw_arabi@ 2/60]{.citex}  
         "So they returned with favor from Allāh and bounty, no harm having touched them."

     (@) [أَقْبَلَ مُحَمَّدٌ وَلَمْ يَحْمِلْ كُتُبَهُ]{.ar}
         [@nahw_arabi@ 2/60]{.citex}  
         [أَقْبَلَ سَعِيدٌ لَمْ يَحْمِلْ كُتُبَهُ]{.ar}
         [@nahw_arabi@ 2/60]{.citex}  
         "[#muHammad]{.trn2}/[#saeId]{.trn2} approached while he didn't carry his books."

     If the sentence ;hal; does not have a pronoun that links to the ;sahib_hal; then
     the [و]{.ar}\ of ;hal;
     is to be used.
     For example:

     (@) [أَقْبَلَ سَعِيدٌ وَلَمْ تَطْلُعِ ٱلشَّمْسُ]{.ar}
         [@nahw_arabi@ 2/60]{.citex}  
         "[#saeId]{.trn2} approached while the sun had not risen."

     (@) [وَلَقَدْ خَشِيتُ بِأَنْ أَمُوتَ وَلَمْ تَدُرْ لِلْحَرْبِ دَائِرَةٌ عَلَى ابْنَيْ ضَمْضَمِ]{.ar}
         [@nahw_arabi@ 2/60]{.citex}  
         "And indeed I feared that I would die, while a turn [of misfortune] had not [yet] turned, in battle, on the two sons of [#DamDam]{.trn2}"  
         ([وَلَمْ تَدُرْ لِلْحَرْبِ دَائِرَةٌ]{.ar} is the sentence ;hal;)


  v. The sentence is negative and the ;mudarie; verb is negated with [لَمَّا]{.ar}.
     Here again, the sentence ;hal; need not contain a pronoun that refers to the ;sahib_hal;.
     In this case,
     the [و]{.ar} of ;hal;
     is typically chosen to be used.^[From @https://tafsir.app/iraab-aldarweesh/7/4@: [وإن كانت منفية ب «لما» فالمختار ربطها بالواو]{.ar}]
     For example:

     (@) [أَمْ حَسِبْتُمْ أَن تَدْخُلُوا ٱلْجَنَّةَ وَلَمَّا يَعْلَمِ ٱللَّهُ ٱلَّذِينَ جَاهَدُوا مِنكُمْ وَيَعْلَمَ ٱلصَّابِرِينَ]{.ar}
         [@https://quran.com/3/142@]{.citex}  
         "Or do you think that you will enter Paradise while Allāh has not yet made evident those of you who fight in His cause and made evident those who are steadfast?"

### The sentence ;hal; strengthens the meaning of the preceding sentence as a whole

Sometimes the ;hal; describes, not just a single word as the ;sahib_hal; but the preceding sentence as a whole.
(See section\ (ref)).
If the ;hal; is itself a sentence, then
the [و]{.ar} of ;hal;
is not used.

For example:

(@ex000120) [ذَ ٰلِكَ ٱلْكِتَابُ لَا رَيْبَ فِيهِ]{.ar}
    [@https://quran.com/2/2@ cited by @ibn_hisham_awdah_almasaalik@ 2/289 and @zidan_haalaat_rabt_waw@]{.citex}  
    "This is the Book about which there is no doubt"  
    (The sentence [لَا رَيْبَ فِيهِ]{.ar}, in this interpretation, is analyzed as a ;hal; to the preceding sentence [ذَ ٰلِكَ ٱلْكِتَابُ]{.ar}.)

### The sentence ;hal; is a ;ma3toof;

If a sentence ;hal; is preceded by a ;3atf; (see section (multiple hals) above),
then an additional
[و]{.ar} of ;hal;
is not typically tacked on to the ;3atf;.

For example:

(@ex000121) [فَجَاءَهَا بَأْسُنَا بَيَاتًا أَوْ هُمْ قَائِلُونَ]{.ar}
    [@https://quran.com/7/4@]{.citex}  
    "and Our punishment came to them at night or while they were sleeping at noon."  
    (An additional [و]{.ar} of ;hal; is not tacked on to the ;3atf; [أَوْ]{.ar}.)

However, according to some grammarians, a
[و]{.ar} of ;hal;,
can be added to the ;3atf; and it would be acceptable.^[@zidan_haalaat_rabt_waw@ citing @farraa@]
For example:

(@ex000122) [أَتَيْتَنِى وَالِيًا أَوْ وَأَنَا مَعْزُولٌ]{.ar}
    [@https://tafsir.app/farraa/7/4@]{.citex}  
    "You came to me, while I was adjacent, or while I was remote."

## Purposes of the [و]{.ar} of ;hal;

The
[و]{.ar} of ;hal;
essentially distances the ;hal; from the influence of the governing verb.^[@dalaail_jurjani@ 1/213--214 cited by @maani_nahw@ 357--358]
For example, consider the expression:

(@ex000123) [جَاءَنِي زَيْدٌ يُسْرِعُ]{.ar}
    [@dalaail_jurjani@ 1/213]{.citex}  
    "Zayd came to me hastening."

The above example is almost equivalent to saying
[جَاءَنِي زَيْدٌ مُسْرِعًا]{.ar}.
The ;hal; [يُسْرِعُ]{.ar} is tightly bound to the ;3aamil; [جَاءَ]{.ar}.
So the expression asserts Zayd's coming and his hastening as one assertion.
<!--
Zayd's hastening is contained within his action of coming.
-->

Consider now the expression with the [و]{.ar} of ;hal;:

(@ex000124) [جَاءَنِي زَيْدٌ وَهُوَ يُسْرِعُ]{.ar}
    [@dalaail_jurjani@ 1/214]{.citex}  
    "Zayd came to me while he was hastening."

Here the ;hal; sentence
[وَهُوَ يُسْرِعُ]{.ar}
is a more independent assertion.
Now, the only link between the ;hal; and its governing verb is
that the ;hal; expresses the state of the ;sahib_hal; when the action of the governing verb took place.

<!--This distancing effect of the [و]{.ar} of ;hal; can be used for several purposes.-->
The [و]{.ar} of ;hal; can be used for a different purposes.
We will list them below.
In the following discussion, there will be three distinct expressions that we will refer to:

  i. The [و]{.ar} of ;hal;
 ii. The ;hal; sentence which follows the [و]{.ar} of ;hal;
iii. The _preceding statement_ which precedes the [و]{.ar} of ;hal;

Here are some purposes of the [و]{.ar} of ;hal;:

* The [و]{.ar} of ;hal; indicates that the event in the preceding statement took place at the time when the ;hal; occurred.
  For example:

  (@) [جَاءَ زَيْدٌ وٱلشَّمْسُ طَالِعَةٌ]{.ar}
      [@ibn_hisham_mughni@ 606 cited by @maani_nahw@ 2/361]{.citex}  
      "Zayd came when the sun was risen."

  (@) [سَأَزُورُكَ وٱلْقَمَرُ طَالِعٌ]{.ar}
      [@maani_nahw@ 2/367]{.citex}  
      "I will visit you when the moon is risen."

* The [و]{.ar} of ;hal; indicates that the ;sahib_hal; was already in the state described by the ;hal; before the event in the preceding statement occurred.
  For example:

  (@) [وَمَا لَنَا أَلَّا نُقَاتِلَ فِي سَبِيلِ ٱللَّهِ وَقَدْ أُخْرِجْنَا مِنْ دِيَارِنَا وَأَبْنَائِنَا]{.ar}
      [@https://quran.com/2/246@ cited by @maani_nahw@ 2/368]{.citex}  
      ""And why should we not fight in the cause of Allāh when we have been driven out from our homes and from our children?"


* The [و]{.ar} of ;hal; indicates that the ;hal; after it is something obvious and should be taken into account, when considering the preceding statement.
  For example:

  (@) [أَمْ حَسِبْتُمْ أَنْ تَدْخُلُوا ٱلْجَنَّةَ وَلَمَّا يَأْتِكُمْ مَثَلُ ٱلَّذِينَ خَلَوْا مِنْ قَبْلِكُمْ]{.ar}
      [@https://quran.com/2/214@ cited by @maani_nahw@ 2/367]{.citex}  
      "Or do you think that you will enter Paradise while such [trial] has not yet come to you as came to those who passed on before you?"

  (@) [أَرَأَيْتَ لَوْ مَضْمَضْتَ مِنَ الْمَاءِ وَأَنْتَ صَائِمٌ]{.ar}
      [@https://sunnah.com/abudawud:2385@]{.citex}  
      "What do you think if you rinse your mouth with water while you are fasting?"

* The [و]{.ar} of ;hal; indicates that the ;hal; sentence is is describing something extraordinary.
  For example:

  (@) [عَبَرَ ٱلنَّهْرَ وَلَمْ يُحَرِّكْ يَدَهُ]{.ar}
      [@maani_nahw@ 2/368]{.citex}  
      "He crossed the river while not (even) moving his hand!"

  (@) [دَخَلَ عَلَى ٱلْأَمِيرِ وَبِيَدِهِ سَيْفُهُ]{.ar}
      [@maani_nahw@ 2/368]{.citex}  
      "He entered upon the commander while in his hand was his sword!"

* To differentiate between a ;hal; and a ;na3t;.
  For example:

  (@) [رَأَيْتُ رَجُلًا عِنْدَهُ مَالٌ]{.ar}
      [@maani_nahw@ 2/368]{.citex}  
      "I saw a man (who) had wealth."  
      (The sentence [عِنْدَهُ مَالٌ]{.ar} can be analyzed as a ;na3t;.)

  (@) [رَأَيْتُ رَجُلًا وَعِنْدَهُ مَالٌ]{.ar}
      [@maani_nahw@ 2/368]{.citex}  
      "I saw a man while he had wealth."  
      (The sentence [عِنْدَهُ مَالٌ]{.ar} can only be analyzed as a ;hal;.)

There may be other purposes as well.^[@maani_nahw@ 2/368--369]
      
## A ;shibh_jumlah; as the ;hal;

(Compare this section to section\ (ref).)
A ;shibh_jumlah;, in this context, is a prepositional or adverbial phrase.
For example: 
[عَلَى ٱلْغُصْنِ]{.ar}
"on the branch"
and
[بَيْنَ ٱلسَّحَابِ]{.ar}
"between the clouds".

Just like a complete sentence,
a ;shibh_jumlah; too may occur as a ;hal;.
For example:

(@haal-shibh-jumlah-crescent) [رَأَيْتُ ٱلْهِلَالَ بَيْنَ ٱلسَّحَابِ]{.ar}
    [@ibn_hisham_awdah_almasaalik@ 2/285]{.citex}  
    "I saw the crescent between the clouds."  
    ([بَيْنَ ٱلسَّحَابِ]{.ar} is analyzed as a ;hal;.)

(@haal-shibh-jumlah-sparrow) [نَظَرْتُ ٱلْعُصْفُورَ عَلَى ٱلْغُصْنِ]{.ar}
    [@ghalayini_jaami3@ 3/101]{.citex}  
    "I looked at the sparrow on the branch."

(@haal-shibh-jumlah-wrote) [كتب عمر إلى أبي عبيدة بالشام]{.ar}
    [@sarraj_usool@ 2/52]{.citex}  
    "[#eumar]{.trn2} wrote to [#abI #eubaydah]{.trn2} in Syria."

(@ex000125) [فَخَرَجَ عَلَىٰ قَوْمِهِ فِى زِينَتِهِ]{.ar}
    [@https://quran.com/28/79@ cited by @ibn_hisham_awdah_almasaalik@ 2/285]{.citex}  
    "So he came out before his people in his adornment."  
    ([فِى زِينَتِهِ]{.ar} is analyzed as a ;hal;.^[See @https://tafsir.app/ibn-aashoor/28/79@])

(@ex000126) [وَيُكَلِّمُ ٱلنَّاسَ فِي ٱلْمَهْدِ]{.ar}
    [@https://quran.com/3/46@]{.citex}  
    "He will speak to the people in the cradle"  
    ([فِي ٱلْمَهْدِ]{.ar} has been analyzed as a ;hal;.^[@https://tafsir.app/albahr-almuheet/3/46@])


Now, you might be thinking: Didn't we learn
in chapter\ (ref) that [بَيْنَ]{.ar} is an ;dharf_makan;?
So why are we now saying that it is a ;hal;?

Well, first of all,
we are saying that the ;shibh_jumlah;
[بَيْنَ ٱلسَّحَابِ]{.ar}
is a ;hal;, not just 
[بَيْنَ]{.ar}.
Secondly, we say that the ;shibh_jumlah; is a ;hal; only loosely speaking.

Remember that an adverb of time or place is governed by a verb.
And the adverb of time or place indicates the time or place where the action of the verb occurred.
In a sentence like (@haal-shibh-jumlah-crescent) [رَأَيْتُ ٱلْهِلَالَ بَيْنَ ٱلسَّحَابِ]{.ar},
the crescent was between the clouds before the action of seeing took place.
So, in this case, we say that
[بَيْنَ]{.ar}
is an adverb of place, but it is governed,
not by the verb
[رَأَىٰ]{.ar},
but by an implied general beingness (see section\ (ref))
So it is as if we are saying:

"I saw the crescent (while it was) [being]^between\ the\ clouds^."

And it is this implied general beingness which is technically the ;hal;.^[@ghalayini_jaami3@ 3/101]
While
[بَيْنَ]{.ar}
remains (technically) an ;dharf_makan;.

Because the actual ;hal; "being" is (necessarily) unexpressed and only implied,
we can loosely say that the ;shibh_jumlah;
[بَيْنَ ٱلسَّحَابِ]{.ar}
is a ;hal;.

Similarly,
in example (@haal-shibh-jumlah-sparrow) [نَظَرْتُ ٱلْعُصْفُورَ عَلَى ٱلْغُصْنِ]{.ar},
the prepositional phrase
[عَلَى ٱلْغُصْنِ]{.ar}
is governed, not by the verb
[نَظَرَ]{.ar}
but by an implied verb "being" which is the true ;hal;.
But, loosely speaking, we may say that the ;shibh_jumlah;
[عَلَى ٱلْغُصْنِ]{.ar}
is the ;hal;.

Similarly,
in example (@haal-shibh-jumlah-wrote) [كتب عمر إلى أبي عبيدة بالشام]{.ar},
the act of writing was dony by [#eumar]{.trn2} in [al-#HijAz]{.trn2}, not in Syria.
So the prepositional phrase
[بالشام]{.ar}
is describing the state of
[#abU #eubaydah]{.trn2}
while he was in Syria.

This is yet another instance of where the lines between different types of adverbs get blurred.
In fact, some grammarians have classified the ;hal; to be of the same class of adverbs as the ;dharf_zaman; and the ;dharf_makan;.^[@muqtadab@ 4/166]



From the perspective of meaning,
the ;shibh_jumlah;
[بَيْنَ ٱلسَّحَابِ]{.ar}
"between the clouds"
describes the state of the ;sahib_hal;
[ٱلْهِلَالُ]{.ar}
during the occurrence of the verb [رَأَىٰ]{.ar}.
Similarly,
the ;shibh_jumlah;
[عَلَى ٱلْغُصْنِ]{.ar}
"on the branch"
describes the state of the ;sahib_hal;
[ٱلْعُصْفُور]{.ar}
during the occurrence of the verb [نَظَرَ]{.ar}.

<!--
So the ;shibh_jumlah; ;hal; must be uninfluenced, or pre-existing, before the action of any overt verb in the preceding statement.
-->

Here is an example of where the ;shibh_jumlah; does not work as a ;hal;:

(@ex000127) [وَقَعَ ٱلْحَجَرُ فِي ٱلْحُفْرَةِ]{.ar}  
    "The stone fell in the pit."

In the above example,
the stone went in the pit due to the action of the verb [وَقَعَ]{.ar}.
So the preposition [فِي]{.ar} is governed by the verb [وَقَعَ]{.ar}.
Because [فِي]{.ar} is not governed by an implied ;3aamil; meaning "being",
therefore, the ;shibh_jumlah;
[فِي ٱلْحُفْرَةِ]{.ar}
is not a ;hal;.

One indicator to test if the ;shibh_jumlah; is valid as ;hal; in any particular sentence,
is to insert a [و]{.ar} of ;hal; and a pronoun
(referring to the ;sahib_hal;)
before the ;shibh_jumlah;
(thus making it a complete sentence).
The purpose of the [و]{.ar} of ;hal;, here, is to make the ;hal; a pre-existing state.
If the resulting expression
(with the [و]{.ar} of ;hal; is interpreted as making the ;hal; a pre-existing state)
retains the same meaning as the original, then
the ;shibh_jumlah; could be valid as a ;hal;.
Let's use this test on some of the examples above.

(@ex000128) [وَقَعَ ٱلْحَجَرُ وَهُوَ فِي ٱلْحُفْرَةِ]{.ar}  
    "The stone fell while it had already been in the pit."  
    (This does not retain the same meaning as the original [وَقَعَ ٱلْحَجَرُ فِي ٱلْحُفْرَةِ]{.ar}. So the ;shibh_jumlah; in the original example is not a ;hal;.)

(@ex000129) [رَأَيْتُ ٱلْهِلَالَ وَهُوَ بَيْنَ ٱلسَّحَابِ]{.ar}  
    "I saw the crescent while it had already been between the clouds."  
    (This retains the meaning of the original [رَأَيْتُ ٱلْهِلَالَ بَيْنَ ٱلسَّحَابِ]{.ar}. So the ;shibh_jumlah; in the original example is valid as a ;hal;.)

(@ex000130) [نَظَرْتُ ٱلْعُصْفُورَ وَهُوَ عَلَى ٱلْغُصْنِ]{.ar}  
    "I looked at the sparrow while it had already been on the branch."  
    (This retains the meaning of the original [نَظَرْتُ ٱلْعُصْفُورَ عَلَى ٱلْغُصْنِ]{.ar}. So the ;shibh_jumlah; in the original example is valid as a ;hal;.)

There may be examples where a ;shibh_jumlah; could be validly interpreted either as a ;hal; 
(governed by an implied ;3aamil; meaning "being"),
or as governed by an overt verb.^[See also, for example, the [tafsIr]{.trn2} of [تَحْتَ ٱلشَّجَرَةِ]{.ar} in @https://tafsir.app/albahr-almuheet/48/18@]
For example:

(@ex000131) [رأيتُ زيدًا في الدار]{.ar}
    [@sarraj_usool@ 2/52]{.citex}  
    "I saw Zayd in the house."

Without context, the prepositional phrase
[في الدار]{.ar}
could either be governed by [رَأَىٰ]{.ar}, signifying that the act of seeing was done in the house.
Or it could be governed by the implication of general beingness, as a ;hal; for [زَيْد]{.ar}.^[@sarraj_usool@ 2/52]

A ;shibh_jumlah; can only be a ;hal; if it is governed by an implied (unexpressed) ;3aamil;.
This implicated ;3aamil; will typically be general beingness, as in the examples above.^[@ibn_hisham_awdah_almasaalik@ 2/285, @ibn_aqil_alfiyyah@ 1/213]
In fact, some grammarians insist that the implied governor can only be general beingness.^[@https://tafsir.app/albahr-almuheet/3/194@ ([مَا وَعَدْتَنَا عَلَىٰ رُسُلِكَ]{.ar})]
However, it is conceivable that the implied governor of the preposition be interpreted, if not formally then at least in meaning, as some other verb (or verbal noun).^[@nahw_wafi@ 2/447 footnote]
For example:

(@ex000132) [رَبَّنَا وَءَاتِنَا مَا وَعَدتَّنَا عَلَىٰ رُسُلِكَ]{.ar}
    [@https://quran.com/3/194@]{.citex}  
    "Our Lord, and grant us what You promised us through Your messengers"

In one interpretation of the above [Ayah]{.trn2},
the 
prepositional phrase
[عَلَىٰ رُسُلِكَ]{.ar}
"through Your messengers"
has been analyzed as ;hal; of
[مَا وَعَدتَّنَا]{.ar}
"what You promised us"
The meaning with the implicated governor has been explained as
[مُنَزَّلًا عَلَيْهِمْ]{.ar}
"_sent down_ on [Your messengers]."^[@https://tafsir.app/ibn-aashoor/3/194@]

## Interpreting a sentence as a ;hal; vs. a ;na3t;

We have just seen how a sentence
(or ;shibh_jumlah;)
can be intrepreted as a ;hal;.
And we already know that a sentence
(or ;shibh_jumlah;)
can be intrepreted as a ;na3t;.
So how can we tell when
a sentence
(or ;shibh_jumlah;)
is a ;hal; vs. when it is a ;na3t;?

We may use the following guidelines^[@ibn_hisham_mughni@ 560]:

* When
  a sentence
  (or ;shibh_jumlah;)
  occurs after a specific definite noun,
  then it will be a ;hal;.

* And when
  a sentence
  (or ;shibh_jumlah;)
  occurs after a unspecified indefinite noun,
  then it will be a ;na3t;.

* And when 
  a sentence
  (or ;shibh_jumlah;)
  occurs after a generic definite noun
  or an specified indefinite noun
  then it may be interpreted as either a ;hal; or a ;na3t;.

  However, in this case when both the ;na3t; and the ;hal; interpretations are possible,
  one may still be preferred over the other 
  depending on what the overall meaning and context demands.^[@nahw_wafi@ 3/477]

  This is because
  when a sentence is interpreted as a ;hal; then it will be describing the state of the ;sahib_hal;.
  And when a sentence is interpreted as a ;na3t; then it will be specifying or identifying the ;manut;.

What we mean by a _specific definite_ noun is one that refers to a specific entity.
Not one that refers to a generic type
(for which Arabic also uses the definite).

For example,
in the sentence
[زَيْدٌ فِي ٱلدَّارِ]{.ar} "Zayd is in the house,"
[زَيْدٌ]{.ar} is a specific definite noun
because it refers to a specific person.
On the other hand,
if we say
[ٱلْفِيلُ حَيَوانٌ]{.ar} "The elephant is an animal,"
then we may be using
[ٱلْفِيل]{.ar}
to refer to the species,
and not a specific elephant.
In this case,
[ٱلْفِيل]{.ar}
is a _generic definite_ noun.

And what we mean by an unspecified indefinite noun is one that is not restricted by a ;na3t; or other qualifier.
So it is applicable to any entity denoted by that noun.
For example, [رَجُل]{.ar} in
[فِي ٱلدَّارِ رَجُلٌ]{.ar}
is an unspecified indefinite noun.
But in 
[فِي ٱلدَّارِ رَجُلٌ كَبِيرٌ]{.ar}
and
[فِي ٱلدَّارِ رَجُلُ خَيْرٍ]{.ar}
it is a specified indefinite noun.

Here are some examples of sentences analyzed as ;na3t;s or ;hal;s:

(@ex000133) [حَتَّىٰ تُنَزِّلَ عَلَيْنَا كِتَابًا نَقْرَؤُهُ]{.ar}
    [@https://quran.com/17/93@ cited by @ibn_hisham_mughni@ 560]{.citex}  
    "until you bring down to us a book we may read"  
    ([نَقُرَؤُهُ]{.ar} is analyzed as a ;na3t; because [كِتَاب]{.ar} is an unspecified indefinite noun.)

(@ex000134) [فَلَقَدْ رَأَيْتُهُ يَقِيهَا مِنَ الْحِجَارَةِ بِنَفْسِهِ]{.ar}
    [@https://sunnah.com/muslim:1699a@]{.citex}  
    "for indeed I saw him protecting her from the stones with his [body]."  
    ([يَقِيهَا]{.ar} is analyzed as a ;hal; because the pronoun [ه]{.ar} in [رَأَيْتُهُ]{.ar} is a specific definite noun.)

(@ex000135) [وَقَالُوا لَوْلَا نُزِّلَ هَـٰذَا ٱلْقُرْءَانُ عَلَىٰ رَجُلٍ مِنَ ٱلْقَرْيَتَيْنِ عَظِيمٍ]{.ar}
    [@https://quran.com/43/31@]{.citex}  
    And they said, "Why was this Qur’ān not sent down upon a great man from [one of] the two cities?"  
    ([مِنَ ٱلْقَرْيَتَيْنِ]{.ar} is a ;na3t; to [رَجُل]{.ar}. [عَظِيم]{.ar} is a second ;na3t;.)

(@ex000136) [كَمَثَلِ ٱلْحِمَارِ يَحْمِلُ أَسْفَارًا]{.ar}
    [@https://quran.com/62/5@ cited by @ibn_hisham_mughni@ 561]{.citex}  
    "is like that of a donkey who carries volumes [of books]"  
    ([ٱلْحِمَارِ]{.ar} is a generic definite noun. So, the sentence [يَحْمِلُ أَسْفَارًا]{.ar} has been analyzed as either a ;hal; or a ;na3t;.^[@https://tafsir.app/kashaf/62/5@])

Consider now the following example:

(@ex000137) [وَقَالَ رَجُلٌ مُؤْمِنٌ مِنْ آلِ فِرْعَوْنَ يَكْتُمُ إِيمَانَهُ]{.ar}
    [@https://quran.com/40/28@]{.citex}  
    "And a believing man from the family of Pharaoh who concealed his faith said,"

In the above example, there are two (quasi-) sentences after the first ;na3t; [مُؤْمِن]{.ar}:

 i. [مِنْ آلِ فِرْعَوْنَ]{.ar}
ii. [يَكْتُمُ إِيمَانَهُ]{.ar}

There are now multiple possible interpretations:

Since [رَجُلٌ]{.ar} is now a specified indefinite noun
(having been described by the ;na3t; [مُؤْمِنٌ]{.ar})
it is permissible for both
[مِنْ آلِ فِرْعَوْنَ]{.ar}
and
[يَكْتُمُ إِيمَانَهُ]{.ar}
to be ;hal;s.
Or 
[مِنْ آلِ فِرْعَوْنَ]{.ar}
can be a ;na3t;
and
[يَكْتُمُ إِيمَانَهُ]{.ar}
can be a ;hal;.
Or both
[مِنْ آلِ فِرْعَوْنَ]{.ar}
and
[يَكْتُمُ إِيمَانَهُ]{.ar}
can be ;na3t;s.^[@https://tafsir.app/ibn-uthaymeen/40/28@]

## Multiple ;hal;s when one or more is a sentence or ;shibh_jumlah;

From section\ (ref) earlier in this chapter,
we learned that there may be more than one ;hal; for one ;sahib_hal;.
These multiple ;hal;s may consist of sentence and ;shibh_jumlah; ;hal;s.
For example:

(@ex000138) [فَنَادَتْهُ ٱلْمَلَائِكَةُ وَهُوَ قَائِمٌ يُصَلِّی فِی ٱلْمِحْرَابِ]{.ar}
    [@https://quran.com/3/39@]{.citex}  
    "So the angels called him while he was standing in prayer in the chamber,"  
    ([هُوَ قَائِمٌ]{.ar} and  [يُصَلِّی فِی ٱلْمِحْرَابِ]{.ar} have both been analyzed as ;hal;s as one interpretation.^[@https://tafsir.app/albahr-almuheet/3/39@])

When one or more of these multiple ;hal;s is a sentence
or ;shibh_jumlah;,
then it is usual,
though not imperative,
that the ;hal;s be in the following order^[@https://tafsir.app/albahr-almuheet/3/46@]:

1. First, any ;hal;s that are comprised of a single word
2. Then any ;shibh_jumlah; ;hal;s
3. Then any sentence ;hal;s

This is the same order that is usually followed for ;na3t;s as well.

Here is an example:

(@ex000139) [فَخَرَجَ مِنْهَا خَائِفًا يَتَرَقَّبُ]{.ar}
    [@https://quran.com/28/21@]{.citex}  
    "So he left it, fearful and anticipating [apprehension]."

## Suppressing the ;3aamil; of the ;hal;

The 
;3aamil; of the ;hal;
may be suppressed
(i.e. omitted)
in some cases optionally,
and in other cases necessarily.
We will discuss these cases below

### Optional suppressing of the ;3aamil; of the ;hal;

### Necessary suppressing of the ;3aamil; of the ;hal;

The ;3aamil; is also omitted when it is conceptual with the meaning "existing" or "being".
We have seen this in section\ (ref) above.

## TODO topics

* [حذف عامل الحال]{.ar}
* [الحال المؤكدة]{.ar}
* [الحال المقدرة]{.ar}/[الحال من حيث الزمن]{.ar}
* [الحال السببي]{.ar} [@nahw_wafi@ 2/400]

