# Rules for writing hamzah {#hamzarules}

## Seats of hamzah

Hamzah is written in four different ways:

1. Seated on an [alif]{.trn2}: [أ]{.aralt} or [إ]{.aralt}
2. Seated on an [wAw]{.trn2}: [ؤ]{.aralt}
3. Seated on an [yAE]{.trn2}: [ئ]{.aralt}
4. Unseated: [ء]{.aralt}

Here are some of notes about writing hamzah in the above four methods:

+ When unseated hamzah comes between two letters that are joined, then it is written above the line that joins them, for example: [خَطِيءَة]{.aralt} [xaTIEah]{.trn}. In this word, the [yAE]{.trn2} [ي]{.aralt} joins to the [tAE marbUTah]{.trn} [ة]{.aralt}.
  
  As a special case, when unseated hamza comes between joined [lAm]{.trn2} and [alif]{.trn2} ([لا]{.aralt}), then it is positioned between them thus: [لءا]{.aralt}. (In most cases, this is replaced with [لآ]{.aralt} as we will explain in the next point below.) And this is different from hamzah on the [alif]{.trn2} following the [lAm]{.trn2}: [لأ]{.aralt}.

+ When unseated hamzah is followed by an [alif]{.trn2}: [ءا]{.aralt},  the combination of hamzah and [alif]{.trn2} is usually written as [آ]{.aralt} as a convention. Examples: [آمَنَ]{.aralt} [EAmana]{.trn}, [ظَمْآن]{.aralt} [PamEAn]{.trn}, [شَنَآن]{.aralt} [canaEAn]{.trn}. However, when the [alif]{.trn2} is a suffix or part of a suffix, or the hamzah is doubled, or there is an [alif]{.trn2} before the hamzah then we will write [ءا]{.aralt}, not [آ]{.aralt}. Examples: [شَيْءَانِ]{.aralt} [cayEAni]{.trn}, [سَءَّال]{.aralt} [saEEAl]{.trn}, [قِرَاءَات]{.aralt} [qirAEAt]{.trn}. 

+ When hamzah is seated on [alif]{.trn2}, if it has an ;imark;, it is written below the [alif]{.trn2}: [إِ]{.aralt}. Otherwise, it is written above the [alif]{.trn2}: [أَ]{.aralt}, [أُ]{.aralt}, [أْ]{.aralt}.

+ When hamzah is seated on [yAE]{.trn2} [ئ]{.aralt} the dots of the [yAE]{.trn2} are no longer written. Here's how it will appear in different positions:

  Isolated | End | Middle | Beginnning
  :--------|:----|:-------|:----------
  [ئ]{.aralt}| [ـئ]{.aralt}| [ـئـ]{.aralt}| [ئـ]{.aralt}

  Note that hamzah is seated on [yAE]{.trn2} in the middle position [ـئـ]{.aralt} is different from unseated hamzah between two joining letters [ـءـ]{.aralt}.

So how do we know when to write hamzah unseated and when seated? And how do we choose between its three different seats? There are a set of rules that we need to follow in order to correctly write hamzah.

## Rules for determining the seat of hamzah

### Without prefixes and suffixes

We will first learn how to determine the seat of hamzah for a word
without any prefix or suffix.

Hamzah can occur in three positions in a word:

1. At the beginning of the word
1. In the middle of the word
1. At the end of the word

We will treat each of these positions below.

####  At the beginning of the word

When hamzah occurs in the beginning of a word, then:

a. If the hamzah carries a long-[A]{.trn} vowel, it is written unseated followed by an [alif]{.trn2} and written as [آ]{.aralt}, for example [آمَنَ]{.aralt} [EAmana]{.trn}.
b. If the hamzah carries any other vowel, it is written seated on an [alif]{.trn2}, and is marked with the appropriated vowel mark, for example [أَسْلَمَ]{.aralt} [Easlama]{.trn}, [أُرِيدُ]{.aralt} [EurIdu]{.trn}, [إِسْلَام]{.aralt} [EislAm]{.trn}, [إِيمَان]{.aralt} [EImAn]{.trn}, [أُوخِذَ]{.aralt} [EUxipa]{.trn}. 

#### In the middle of the word

<!--The most general case is when hamzah is in the middle of a word. -->

Arabic has three short vowels, three long vowels, two semi-vowels, and a zero-vowel indicated by a ;0mark; [◌ْ]{.aralt}. Each of these has an order of precedence and a hamzah seat, that we have shown in the table below:

Precedence | Vowel | Seated hamzah
:--|:------|:-----
1. | [I]{.trn}/[ay]{.trn} | [ء]{.aralt}
2. | [i]{.trn}            | [ئ]{.aralt}
3. | [U]{.trn}/[aw]{.trn} | [ء]{.aralt}
4. | [u]{.trn}            | [ؤ]{.aralt}
5. | [A]{.trn}            | [ء]{.aralt}
6. | [a]{.trn}            | [أ]{.aralt}
7. | [◌ْ]{.aralt}         | [ء]{.aralt}

**Main rule:** Disregard any ;shaddah; [◌ّ]{.aralt}. Consider the vowel on the consonant before the hamzah and the vowel on the hamzah itself. Determine which of the two vowels wins by being higher in precedence in the above table. The winning vowel's seat will be the seat of the hamzah.

**Exception:** If the vowel [A]{.trn} wins, but it is written not as an [alif]{.trn2} but as a [ىٰ]{.aralt}, then the hamzah will be seated on an [alif]{.trn2}.

<!--
**Sub-rule:** If the main rule determines that hamzah is to be seated on [alif]{.trn2}, and there is a long [A]{.trn} vowel on the hamzah using an [alif]{.trn2}, then hamzah shall be unseated. And the combination of [ءَا]{.aralt} will usually be written as [آ]{.aralt}.
-->

Examples:

| Word | Vowel before hamzah | Vowel on hamzah | Winning vowel | Seated hamzah |
|:-----|:-|:-|:-|:------|
|\vphantom{\huge J} [هَيْءَة]{.aralt} [hayEah]{.trn}     | [ay]{.trn} | [a]{.trn}  | [ay]{.trn} | [ء]{.aralt} |
|\vphantom{\huge J} [خَطِيءَة]{.aralt} [xaTIEah]{.trn}   | [I]{.trn}  | [a]{.trn}  | [I]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [اسْتِيءَاس]{.aralt} [EistIEAs]{.trn}| [I]{.trn}  | [a]{.trn}  | [I]{.trn}  | [ء]{.aralt} (Exception: [ءَا]{.aralt} is not written as [آ]{.aralt} when the preceding vowel is [I]{.trn}.)|
|\vphantom{\huge J} [تَوْءَم]{.aralt} [tawEam]{.trn}     | [aw]{.trn} | [a]{.trn}  | [aw]{.trn} | [ء]{.aralt} |
|\vphantom{\huge J} [سَوْءَة]{.aralt} [sawEah]{.trn}     | [aw]{.trn} | [a]{.trn}  | [aw]{.trn} | [ء]{.aralt} |
|\vphantom{\huge J} [مَوْئِل]{.aralt} [mawEil]{.trn}     | [aw]{.trn} | [i]{.trn}  | [i]{.trn} | [ئ]{.aralt} |
|\vphantom{\huge J} [سَائِل]{.aralt} [sAEil]{.trn}      | [A]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [تَسَاؤُل]{.aralt} [tasAEul]{.trn}   | [A]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.aralt} |
|\vphantom{\huge J} [تَسَاءَلَ]{.aralt} [tasAEala]{.trn}  | [A]{.trn}  | [a]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [قِرَاءَات]{.aralt} [qirAEAt]{.trn}  | [A]{.trn}  | [A]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [نُوآنٌ]{.aralt} [nUEAnun]{.trn}    | [U]{.trn}  | [A]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [مَسْءُول]{.aralt} [masEUl]{.trn}    | [◌ْ]{.aralt}   | [U]{.trn}  | [U]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [تَرْءِيس]{.aralt} [tarEIs]{.trn}    | [◌ْ]{.aralt}   | [I]{.trn}  | [I]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [مِرْآة]{.aralt} [mirEAh]{.trn}     | [◌ْ]{.aralt}   | [A]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [ظَمْآن]{.aralt} [PamEAn]{.trn}     | [◌ْ]{.aralt}   | [A]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [مَسْأَلَة]{.aralt} [masEalah]{.trn}  | [◌ْ]{.aralt}   | [a]{.trn}  | [a]{.trn}  | [أ]{.aralt} |
|\vphantom{\huge J} [الْمَرْأَة]{.aralt} [almarEah]{.trn} | [◌ْ]{.aralt}   | [a]{.trn}  | [a]{.trn}  | [أ]{.aralt} |
|\vphantom{\huge J} [أَسْئِلَة]{.aralt} [EasEilah]{.trn}  | [◌ْ]{.aralt}   | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [أَفْئِدَة]{.aralt} [EafEidah]{.trn}  | [◌ْ]{.aralt}   | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [بِئْسَ]{.aralt} [biEsa]{.trn}       | [i]{.trn}  | [◌ْ]{.aralt}   | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [سُؤْل]{.aralt} [suEl]{.trn}        | [u]{.trn}  | [◌ْ]{.aralt}   | [u]{.trn}  | [ؤ]{.aralt} |
|\vphantom{\huge J} [كَأْس]{.aralt} [kaEs]{.trn}        | [a]{.trn}  | [◌ْ]{.aralt}   | [a]{.trn}  | [أ]{.aralt} |
|\vphantom{\huge J} [سُئِلَ]{.aralt} [suEila]{.trn}      | [u]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [يَئِسَ]{.aralt} [yaEisa]{.trn}      | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [مُطْمَئِنّ]{.aralt} [muTmaEinn]{.trn} | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [سُؤَال]{.aralt} [suEAl]{.trn}      | [u]{.trn}  | [A]{.trn}  | [u]{.trn}  | [ؤ]{.aralt} |
|\vphantom{\huge J} [رَءِيس]{.aralt} [raEIs]{.trn}      | [a]{.trn}  | [I]{.trn}  | [I]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [رُءُوس]{.aralt} [ruEUs]{.trn}      | [u]{.trn}  | [U]{.trn}  | [U]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [شُءُون]{.aralt} [cuEUn]{.trn}      | [u]{.trn}  | [U]{.trn}  | [U]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [رَءُوف]{.aralt} [raEUf]{.trn}      | [a]{.trn}  | [U]{.trn}  | [U]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [لُؤَيّ]{.aralt} [luEayy]{.trn}      | [u]{.trn}  | [a]{.trn}  | [u]{.trn}  | [ؤ]{.aralt} |
|\vphantom{\huge J} [شَنَآن]{.aralt} [canaEAn]{.trn}    | [a]{.trn}  | [A]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [سَأَلَ]{.aralt} [saEala]{.trn}      | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.aralt} |
|\vphantom{\huge J} [رَأَّسَ]{.aralt} [raEEasa]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.aralt} |
|\vphantom{\huge J} [سَيِّئَة]{.aralt} [sayyiEah]{.trn}   | [i]{.trn}  | [a]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [يُرَئِّسُ]{.aralt} [yuraEEisu]{.trn}  | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [رُئِّسَ]{.aralt} [ruEEisa]{.trn}     | [u]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [تَفَؤُّل]{.aralt} [tafaEEul]{.trn}   | [a]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.aralt} |
|\vphantom{\huge J} [سَءَّال]{.aralt} [saEEAl]{.trn}     | [a]{.trn}  | [A]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [لَءَّال]{.aralt} [laEEAl]{.trn}     | [a]{.trn}  | [A]{.trn}  | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [رَأَىٰ]{.aralt} [raEA]{.trn}        | [a]{.trn}  | [A]{.trn}  | [A]{.trn}  | [أ]{.aralt} (using exception) |

#### At the end of the word

When hamzah occurs at the end of a word, disregard the vowel on hamzah itself, and consider only the vowel on preceding consonant.
Plug it into the precedence table as above to determine the seat of hamzah.

| Word | Vowel on consonant before hamzah | Seated hamzah |
|:-----|:-|:------|
|\vphantom{\huge J} [دُعَاءُ]{.aralt} [dueAEu]{.trn}     | [A]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [سُوءُ]{.aralt} [sUEu]{.trn}        | [U]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [جِيءَ]{.aralt} [jIEa]{.trn}        | [I]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [ضَوْءَ]{.aralt} [DawEa]{.trn}       | [aw]{.trn} | [ء]{.aralt} |
|\vphantom{\huge J} [شَيْءَ]{.aralt} [cayEa]{.trn}       | [ay]{.trn} | [ء]{.aralt} |
|\vphantom{\huge J} [بُطْءُ]{.aralt} [buTEu]{.trn}       | [◌ْ]{.aralt}   | [ء]{.aralt} |
|\vphantom{\huge J} [عِبْءُ]{.aralt} [eibEu]{.trn}       | [◌ْ]{.aralt}   | [ء]{.aralt} |
|\vphantom{\huge J} [شَطْءُ]{.aralt} [caTEu]{.trn}       | [◌ْ]{.aralt}   | [ء]{.aralt} |
|\vphantom{\huge J} [يُهَدِّئُ]{.aralt} [yuhaddiEu]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [مُتَّكِئَ]{.aralt} [muttakiEa]{.trn}  | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [سَيِّئُ]{.aralt} [sayyiEu]{.trn}     | [i]{.trn}  | [ئ]{.aralt} |
|\vphantom{\huge J} [بَطُؤَ]{.aralt} [baTuEa]{.trn}      | [u]{.trn}  | [ؤ]{.aralt} |
|\vphantom{\huge J} [يَهْدَأُ]{.aralt} [yahdaEu]{.trn}    | [a]{.trn}  | [أ]{.aralt} |
|\vphantom{\huge J} [مُبْتَدَإِ]{.aralt} [mubtadaEi]{.trn} | [a]{.trn}  | [إ]{.aralt} |

The exception to this rule is when the previous letter is a doubled [wAw]{.trn2} with an ;umark;.
In this case the hamzah will again be unseated. Example [تَبَوُّءُ]{.aralt} [tabawwuEu]{.trn}.

Note also that [مُبْتَدَإِ]{.aralt} [mubtadaEi]{.trn} can be written with the hamzah below the [alif]{.trn2} because of the ;imark; on the hamzah.
But it is also common to write it as [مُبْتَدَأ]{.aralt} [mubtadaE]{.trn}, especially when the hamzah is unvoweled.

### With prefixes and suffixes

#### Prefixes

If hamzah is in the beginning of a word, adding a prefix to the word will not alter the writing of the hamzah.
Hamzah will continue to be seated on an [alif]{.trn2}.
Here are some examples of words with beginning hamzahs and prefixes.

|Word without prefix | Prefix | Word with prefix
|:---|:-|:---
| \vphantom{\huge J} [أُسْتَاذِ]{.aralt} | [لِ]{.aralt}  | [لِأُسْتَاذِ]{.aralt}
| \vphantom{\huge J} [آخِرَة]{.aralt}  | [الْ]{.aralt} | [الْآخِرَة]{.aralt}

#### Suffixes

If hamzah is at the end of a word, adding a suffix to the word can, in general, alter the writing of the hamzah. 
Hamzah is now, generally, treated as if it is in the middle of the word, and the rules for hamzah in the middle of a word apply.
Examples:  

| Word | Vowel on consonant before hamzah | Shortened vowel on hamzah | Winning vowel | Seated hamzah |
|:-----|:-|:-|:-|:------|
|\vphantom{\huge J} [بَرِيءُونَ]{.aralt} [barIEUna]{.trn}     | [I]{.trn}  | [U]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [بَرِيءَانِ]{.aralt} [barIEAni]{.trn}     | [I]{.trn}  | [A]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [بَرِيءِينَ]{.aralt} [barIEIna]{.trn}     | [I]{.trn}  | [I]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [بَرِيءَيْنِ]{.aralt} [barIEayni]{.trn}    | [I]{.trn}  | [ay]{.trn}| [I/ay]{.trn}| [ء]{.aralt} |
|\vphantom{\huge J} [سِيءَتْ]{.aralt} [sIEat]{.trn}          | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [شَيْءُهُ]{.aralt} [cayEuhu]{.trn}        | [ay]{.trn} | [u]{.trn} | [ay]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [شَيْءَهُ]{.aralt} [cayEahu]{.trn}        | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [شَيْءِهِ]{.aralt} [cayEihi]{.trn}        | [ay]{.trn} | [i]{.trn} | [ay]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [شَيْءَانِ]{.aralt} [cayEAni]{.trn}       | [ay]{.trn} | [A]{.trn} | [ay]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [شَيْءَيْنِ]{.aralt} [cayEayni]{.trn}      | [ay]{.trn} | [ay]{.trn} | [ay]{.trn} | [ء]{.aralt} |
|\vphantom{\huge J} [مَجِيءُهُ]{.aralt} [majIEuhu]{.trn}      | [I]{.trn}  | [u]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [مَجِيءَهُ]{.aralt} [majIEahu]{.trn}      | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [مَجِيءِهِ]{.aralt} [majIEihi]{.trn}      | [I]{.trn}  | [i]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [سُوئِهِ]{.aralt} [sUEihi]{.trn}         | [U]{.trn}  | [i]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [ضَوْئِهِ]{.aralt} [DawEihi]{.trn}        | [aw]{.trn} | [i]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [يَسُوءُونَ]{.aralt} [yasUEUna]{.trn}     | [U]{.trn}  | [U]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [سُوءُهُ]{.aralt} [sUEuhu]{.trn}         | [U]{.trn}  | [u]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [سُوءَهُ]{.aralt} [sUEahu]{.trn}         | [U]{.trn}  | [a]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [سُوءَانِ]{.aralt} [sUEAni]{.trn}        | [U]{.trn}  | [A]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [ضَوْءَهُ]{.aralt} [DawEahu]{.trn}        | [aw]{.trn} | [a]{.trn} | [aw]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [ضَوْءَانِ]{.aralt} [DawEAni]{.trn}       | [aw]{.trn} | [A]{.trn} | [aw]{.trn}  | [ء]{.aralt} |
|\vphantom{\huge J} [مُرْجَءَات]{.aralt} [murjaEAt]{.trn}     | [a]{.trn}  | [A]{.trn} | [A]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [خَاطِءِين]{.aralt} [xATiEIn]{.trn}      | [i]{.trn}  | [I]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [خَاسِءِين]{.aralt} [xAsiEIn]{.trn}      | [i]{.trn}  | [I]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [مُتَّكِءِينَ]{.aralt} [muttakiEIna]{.trn}  | [i]{.trn}  | [I]{.trn} | [I]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [مُتَّكِئُونَ]{.aralt} [muttakiEUna]{.trn}  | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [يُبَرِّئُونَ]{.aralt} [yubarriEUna]{.trn}  | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [يُبَرَّءُونَ]{.aralt} [yubarraEUna]{.trn}  | [a]{.trn}  | [U]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [ٱقْرَءُوا]{.aralt} [iqraEU]{.trn}       | [a]{.trn}  | [U]{.trn} | [U]{.trn}   | [ء]{.aralt} |
|\vphantom{\huge J} [سَيِّئَات]{.aralt} [sayyiEAt]{.trn}      | [i]{.trn}  | [A]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [فِئَات]{.aralt} [fiEAt]{.trn}          | [i]{.trn}  | [A]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [فِئُون]{.aralt} [fiEUn]{.trn}          | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [مِئَات]{.aralt} [miEAt]{.trn}          | [i]{.trn}  | [A]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [مِئُون]{.aralt} [miEUn]{.trn}          | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [يُطْفِئُوا]{.aralt} [yuTfiEU]{.trn}      | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [مُسْتَهْزِئُون]{.aralt} [mustahziEUn]{.trn}| [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [مُنْشِئُون]{.aralt} [munciEUn]{.trn}     | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [يُضَاهِئُونَ]{.aralt} [yuDAhiEUna]{.trn}  | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |
|\vphantom{\huge J} [مُرْجِئُون]{.aralt} [murjiEUn]{.trn}     | [i]{.trn}  | [U]{.trn} | [i]{.trn}   | [ئ]{.aralt} |

There are some exceptions:

+ If the letter before the hamzah has a ;0mark; and is not [wAw]{.trn2} or [yAE]{.trn2},
then the hamzah will be written unseated. Examples:

  + \vphantom{\huge J}  [جُزْءَانِ]{.aralt} [juzEAni]{.trn}  
  + \vphantom{\huge J}  [عِبْءَانِ]{.aralt} [eibEAni]{.trn}  
  + \vphantom{\huge J}  [عِبْءَيْنِ]{.aralt} [eibEayni]{.trn}  
  + \vphantom{\huge J}  [بُطْءَهُ]{.aralt} [buTEahu]{.trn}  
  + \vphantom{\huge J}  [بُطْءُهُ]{.aralt} [buTEuhu]{.trn}  
  + \vphantom{\huge J}  [بُطْءِهِ]{.aralt} [buTEihi]{.trn}

<!--
+ If the hamzah is after a long-[U]{.trn} vowel or an [aw]{.trn} semi-vowel, and the hamzah does not have an ;imark;, then it is written unseated. Example:

  + \vphantom{\huge J} [يَسُوءُونَ]{.aralt} [yasUEUna]{.trn}

  This is actually an acceptable variant in the general case, as will discuss below in section\ \@ref(hamza-variants)
  -->

([انِ]{.aralt}, [يْنِ]{.aralt}, [هُ]{.aralt}, and [هِ]{.aralt} are suffixes.)
Note that the combination [ءا]{.ar} is not written as [آ]{.ar} when the [alif]{.trn2} is part of the suffix.

### [_nUn]{.trn2}ation on final hamzah

[_nUn]{.trn2}ation on final hamzah does not affect the writing of the hamzah except in the case of a [nUn]{.trn2}ated ;amark; [◌ً]{.ar}. When writing a [nUn]{.trn2}ated ;amark; [◌ً]{.ar} on a hamzah at the end of a word:

1. If there is an [alif]{.trn2} before a unseated hamzah [اء]{.aralt}, then we don't add a silent [alif]{.trn2} when writing the [nUn]{.trn2}ated ;amark; [◌ً]{.ar}. For example [دَاء]{.aralt} becomes [دَاءً]{.aralt} [dAEan]{.trn}, not [دَاءًا]{.aralt}.

2. Otherwise, we add the silent [alif]{.trn2} after the hamzah so that the hamzah is now in the middle of the word with a suffix [alif]{.trn2} after it. We now pretend that the hamzah has an ;amark; and that the [alif]{.trn2} after it is a long-[A]{.trn} vowel. Then we go through the rules for writing hamzah in the middle of a word (given above) to determine how hamzah will be written. We then write the [nUn]{.trn2}ated ;amark; [◌ً]{.ar} on the hamzah. Examples:

+ \vphantom{\huge J} [مُبْتَدَأ]{.aralt} becomes [مُبْتَدَأٌ، مُبْتَدَءًا، مُبْتَدَإٍ]{.aralt} 
+ \vphantom{\huge J} [مَلْجَأ]{.aralt} becomes [مَلْجَأٌ، مَلْجَءًا، مَلْجَإٍ]{.aralt}
+ \vphantom{\huge J} [جُزْء]{.aralt} becomes [جُزْءٌ، جُزْءًا، جُزْءٍ]{.aralt}
+ \vphantom{\huge J} [شَيْء]{.aralt} becomes [شَيْءٌ، شَيْءًا، شَيْءٍ]{.aralt}
+ \vphantom{\huge J} [سَيِّئ]{.aralt} becomes [سَيِّئٌ, سَيِّئًا, سَيِّئٍ]{.aralt}

### Variants {#hamza-variants}

There are some historical and regional variants to the above rules. The main one is when the letter before hamzah has a ;0mark;, the hamzah is generally written unseated. So with this variant, we write:

+ \vphantom{\huge J} [مَسْءَلَة]{.aralt} instead of [مَسْأَلَة]{.aralt}

However, this rule appears to be not consistently followed. For example, [nacEah]{.trn} is generally always written [نَشْأَة]{.aralt} never [نَشْءَة]{.aralt}.

<!--
A second variant is to avoid the repetition of vowel letters like [و]{.aralt} and [ي]{.aralt}. So they write:

+ \vphantom{\huge J} [رُءُوس]{.aralt} instead of [رُؤُوس]{.aralt}.
+ \vphantom{\huge J} [رَءِيس]{.aralt} instead of [رَئِيس]{.aralt}.
-->

Another variant is that when word final hamzah has an ;imark; and is followed by a suffix starting with [U]{.trn}, then the hamzah is written unseated instead of as [ئ]{.ar}. Examples:

+ \vphantom{\huge J} [مُتَّكِءُون]{.aralt} [muttakiEUn]{.trn}      instead of [مُتَّكِئُون]{.aralt} 
+ \vphantom{\huge J} [يُطْفِءُوا]{.aralt} [yuTfiEU]{.trn}      instead of [يُطْفِئُوا]{.aralt} 
+ \vphantom{\huge J} [مُسْتَهْزِءُون]{.aralt} [mustahziEUn]{.trn} instead of [مُسْتَهْزِئُون]{.aralt}
+ \vphantom{\huge J} [مُنْشِءُون]{.aralt} [munciEUn]{.trn}     instead of [مُنْشِئُون]{.aralt} 
+ \vphantom{\huge J} [يُضَاهِءُونَ]{.aralt} [yuDAhiEUna]{.trn}   instead of [يُضَاهِئُونَ]{.aralt} 
+ \vphantom{\huge J} [مُرْجِءُون]{.aralt} [murjiEUn]{.trn}   instead of [مُرْجِئُون]{.aralt} 
+ \vphantom{\huge J} [مُرْجِءُون]{.aralt} [murjiEUn]{.trn}   instead of [مُرْجِئُون]{.aralt} 
+ \vphantom{\huge J} [رَئِيس]{.aralt} [raEIs]{.trn}   instead of [رَءِيس]{.aralt} 

Excepted from this variant are deficient words like:

+ \vphantom{\huge J} [فِئُون]{.aralt} [fiEUn]{.trn}          
+ \vphantom{\huge J} [مِئُون]{.aralt} [miEUn]{.trn}          

Another, more modern, variant is to modify the precedence rule of vowels. According to this modern variant, the vowel before hamzah is compared with the _shortened_ vowel on the hamzah. This can result in some changes in the hamzah seat. For example:

+ \vphantom{\huge J} [مَسْؤُول]{.aralt}  [masEUl]{.trn} instead of [مَسْءُول]{.aralt}
+ \vphantom{\huge J} [رُؤُوس]{.aralt}   [ruEUs]{.trn}  instead of [رُءُوس]{.aralt}
+ \vphantom{\huge J} [ٱقْرَؤُوا]{.aralt} [iqraEU]{.trn} instead of [ٱقْرَءُوا]{.aralt}

Excepted from this variant is the combination [aEA]{.trn} which will continue to be written as [ـَءَا]{.aralt} or [ـَآ]{.aralt}. For example: [شَنَآن]{.aralt}, [مُرْجَءَات]{.aralt}.

## Why so complicated?

Hamzah was originally not pronounced everywhere in some Classical Arabic dialects. 
For speakers of these dialects, when hamzah would occur in the middle of a word, they would replace it with an [a]{.trn}, [u]{.trn}, or [i]{.trn} vowel.
So they would adjust their pronunciation as follows:

|Proununciation with hamzah | Proununciation without hamzah
|:--|:--
|\vphantom{\huge J}[هَيْءَة]{.aralt} [hayEah]{.trn}   | [هَيَّة]{.aralt} [hayyah]{.trn}     
|\vphantom{\huge J}[خَطِيءَة]{.aralt} [xaTIEah]{.trn} | [خَطِيَّة]{.aralt} [xaTiyyah]{.trn}   
|\vphantom{\huge J}[تَوْءَم]{.aralt} [tawEam]{.trn}   | [تَوَّم]{.aralt} [tawwam]{.trn}
|\vphantom{\huge J}[تَسَاؤُل]{.aralt} [tasAEul]{.trn} | [تَسَاوُل]{.aralt} [tasAwul]{.trn}
|\vphantom{\huge J}[بِئْسَ]{.aralt} [biEsa]{.trn}     | [بِيسَ]{.aralt} [bIsa]{.trn}
|\vphantom{\huge J}[سُؤْل]{.aralt} [suEl]{.trn}      | [سُول]{.aralt} [sUl]{.trn}
|\vphantom{\huge J}[كَأْس]{.aralt} [kaEs]{.trn}      | [كَاس]{.aralt} [kAs]{.trn}

When the Classical Standard Arabic variety emerged,
then, for reasons that are beyond the scope of this text,
the pronunciation _with_ hamzah 
and the consonantal spelling _without_ hamzah became standardized.
So [ء]{.aralt} is now added as a pronunciation mark on top of the various _seats_ that would instead have been dialectally pronounced without hamzah.

## Typographical limitations

Unfortunately, most digital fonts do not currently allow for correctly typing an unseated hamzah between two joined letters 
([ـءـ]{.aralt}), 
as in 
[خَطِيءَة]{.aralt} [xaTIEah]{.trn}.
In most fonts, the hamzah character (Unicode u+0621) will break the joining between the two letters surrounding it, and the output will be rendered incorrectly: 
[خَطِيءَة]{.ar} [xaTIEah]{.trn}.

Two typefaces which allow for the correct typesetting are 

+ Amiri from Alif Type ([amirifont.org](https://www.amirifont.org/))
+ Naskh™ from DecoType ([decotype.com](https://www.decotype.com/))

We have used the Amiri font for typesetting this appendix chapter.

For most other fonts, 
an unseated hamzah between two joined letters 
would have to be approximated
in one of two ways:

1. Hamzah superscript on a [taTwIl]{.trn2} character: [ـٔ]{.ar}. Example: [خَطِيـَٔة]{.ar}. The Unicode input sequence is:

   u+0640 [arabic tatweel]{.smallcaps}  
   u+0654 [arabic hamza above]{.smallcaps}

   This is a more accurate approximation, but some fonts may not position the hamzah correctly on the [taTwIl]{.trn2}, or position vowel marks on the superscript hamzah correctly.

2. Hamzah seated on [yAE]{.trn2}: [ئ]{.ar}. Example: [خَطِيئَة]{.ar}. This is a reprehensible, yet more prevalent, and better supported, approximation.

Beware, though, that neither of these approximations would allow for the correct rendering of a complex (but thankfully rare) word like 
[لَءَّال]{.aralt} [laEEAl]{.trn} "pearl seller", where the hamzah is not allowed to disturb the [lAm-alif]{.trn2} ligature [لا]{.aralt}.

