# ;inna; and its sisters

;wip_warn;

## Introduction

The ;arch; ;j_ism; is governed by an abstract ;pregov; that governs
a ;mubtada; and its ;xabar;, both in the ;ustate;.

For example:

(@inna_zaydun_qaaimun) [زَيْدٌ قَائِمٌ]{.ar}  
    [Zayd is standing.]{.trans} . 

;inna; and its sisters
are a set of six particles
that take an ;arch; ;j_ism; as their input and
change its ;pregov; such that
the ;mubtada; is put in the ;ustate; and the ;xabar; is put in the ;ustate;.
Furthermore, each particle has its own meaning that it imparts to the input sentence.

The set of
;inna; and its sisters
is:

  i. ;inna;
 ii. ;anna;
iii. ;ka_anna;
 iv. ;lakinna;
  v. ;layta;
 vi. ;la3alla;

We will them in the following sections.

## ;inna;

(@inna_zaydun_qaaimun) [زَيْدٌ قَائِمٌ]{.ar}  
    [Zayd is standing.]{.trans} . 

## ;anna;

;anna; may be translated as [that]{.trans}.
;anna; is unique amongst
;inna; and its sisters
that when it transforms an input ;j_ism;
the output is actually not a complete sentence anymore.
Here is its output after transforming example (@inna_zaydun_qaaimun):

(@anna_zaydan_qaaimun) [أَنَّ زَيْدًا قَائِمٌ]{.trans}  
    [that Zayd is standing]{.ar}

As you can see above, the output of ;anna; does not stand by itself as a complete sentence.
Terminologically,
the ;ism_of; of ;anna; is zayd
and its ;xabar; is qaaimun.
But the ;ism_of; and the ;xabar; no longer form the complementary ;musnad3; and ;musnad; of a sentence.
Rather, as will see shortly, ;ia;,
;anna; along with its ;ism_of; and its ;xabar;
structurally constitute a single element.
Let's explain this:

In order to make example () structutally complete
it has to be part of a larger sentence.
So for example, we could say:

(@anna_zaydan_qaaimun) [أَعْلَمُ أَنَّ زَيْدًا قَائِمٌ]{.ar}  
    [I know that Zayd is standing]{.trans}



## rest of sisters in turn

## complete sentence as the ;xabar;

## ;damir_shan; as the ;ism_of;
