# Introduction

;wip_warn;

All praises are due to [#allAh]{.trn2}. We praise Him, seek His help, and ask for His forgiveness. We seek refuge in [#allAh]{.trn2} from the evil in our souls and from our sinful deeds. Whomever [#allAh]{.trn2} guides, no one can mislead. Whomever [#allAh]{.trn2} leads astray, no one can guide. I bear witness that there is no one worthy of worship except [#allAh]{.trn2}. I also bear witness that [#muHammad]{.trn2} is His servant and messenger.

May the peace and blessings of [#allAh]{.trn2} be upon the Prophet [#muHammad]{.trn2}, his family, his companions, and those who followed them with good conduct.

## History of Arabic 

[#allAh]{.trn2}, may He be glorified and exalted, revealed the ;quran;, some fourteen and a half centuries ago, to the Prophet [#muHammad]{.trn2}, may [#allAh]{.trn2} grant peace and confer blessing upon him.
The language of the ;quran; is the Arabic language, as it was understood by the Arabs at that time.
The sayings and actions of the Prophet, may [#allAh]{.trn2} grant peace and confer blessing upon him, were recorded by his companions also in this Arabic language.
Also, composed in this Arabic language, was a vast body of poetry that the Arabs would consider eloquent and worth transmitting.
We will call the Arabic of this pre-[#islAm]{.trn2}ic and early [#islAm]{.trn2}ic era as Classical Arabic.^[Some researchers term the Arabic of this era as pre-classical Arabic. They use the term Classical Arabic to refer to the later use of what we call [sca]{.smallcaps}. Our choice is based on the contention that [sca]{.smallcaps} is but a variety of Classical Arabic (even if it was standardized later), and not a later development.]
The Classical Arabic language consisted of multiple dialects that were spoken by the different tribes and in the different regions of the Arabian peninsula.

All languages change naturally over time.
For example, English has changed to such a degree that the Old English language spoken 1400 years ago would be unintelligible to us today.
So too did the Classical Arabic dialects begin to change.
But when this began to happen,
scholars took on the responsibility of preserving the language of the 
revelation.^[[@mu3allimi@ 4/21--22](https://shamela.ws/book/328/56#p1)]
In the process of preserving Classical Arabic, one particular variety became standardized and gained prevalence as a literary language amongst the dialects of Classical Arabic.
We will call this variety _Standard Classical Arabic_ ([sca]{.smallcaps}).
<!--
This standard Arabic, in its early period after standardization, is called _Standard Classical Arabic_.
-->
<!--or simply Classical Arabic[^1].
-->
<!--
The pre-[#islAm]{.trn2}ic and early [#islAm]{.trn2}ic Arabic dialects (of which Standard Classical Arabic is but a standardized variety) are then referred to, collectively, as pre-Standard Classical Arabic.
-->

[sca]{.smallcaps} became the language of religious scholarship, science, and literature in the [#islAm]{.trn2}ic world.
As scholars developed new branches of religious and secular sciences, new terms and meanings were added (which are termed post-classical).
A few words were also borrowed from foreign languages and Arabicized, as needed by the different scientific disciplines.
Even Classical Arabic itself had a few Arabicized foreign borrowings from neighboring languages.


While [sca]{.smallcaps} was used for literary purposes, the vernacular language that was spoken by Arabs in their day-to-day lives continued to evolve naturally over time and in the different regions where Arabic was spoken.
And so, there began to exist two very distinct types of Arabic: the preserved [sca]{.smallcaps}
which is taught by formal education and which is primarily a written language,
and the vernacular Arabic dialects which Arabs learn as their mother tongue and which are primarily only spoken and not written.



<!--These additions were, by and large, deliberate, done by scholars who were experts in their fields and also well versed in Standard Classical Arabic, and validated by subsequent generations of scholarly discourse.
Besides these needed additions, the grammar and core language remained remarkably unchanged.
-->

In modern times, many new words and meanings were added to [sca]{.smallcaps}, often via translation from Western languages, to keep up with technological advancements and modern media. 
<!--However, it must be said that these additions have often been done by translators rather than scholars in the field, and have sometimes lacked the deliberation seen in the post-classical additions to Standard Arabic. -->
This modern development of [sca]{.smallcaps} is called Modern Standard Arabic ([msa]{.smallcaps}). 
<!--
There are also a small amount of words, meanings, and grammatical usages, which existed in [sca]{.smallcaps}, but which are deemed archaic, and are therefore largely unused, in [msa]{.smallcaps}.
-->


<!--
### What constitutes [sca]{.smallcaps}?

Because [sca]{.smallcaps} ceased to be a native language, any literary output in [sca]{.smallcaps} is
is only an attempt to conform to it.
That is, 
-->


<!--
[^1]: This definition of the term _Classical Arabic_ is not universally accepted, and other authors may use it to also include the Arabic of the late pre-[#islAm]{.trn2}ic and early [#islAm]{.trn2}ic period.
-->

<!--Ahmad Al-Jallad, Damascus Psalm Fragment, p.  69-->
<!--
While Standard Arabic was thus preserved from major change and was used for literary purposes, the language that was spoken by Arabs in their day-to-day lives continued to change over time from the pre-[#islAm]{.trn2}ic Arabic dialects into the modern colloquial Arabic dialects.
And so today, there exist two very distinct types of Arabic: the preserved Standard Arabic which is taught at schools and is primarily a written language, and the modern colloquial Arabic dialects which Arabs learn as their mother tongue and which are primarily only spoken and not written.
-->

The figure below presents a simplified view the historical development of the different varieties of Arabic.

```{.tikzarabic}

\usetikzlibrary{arrows.meta, decorations.text, decorations.pathreplacing}
\tikzstyle{arrow} = [thick,->,>=stealth]
%\tikzstyle{doublearr} = [line width=1pt, double distance=5pt, arrows = {-Classical TikZ Rightarrow[length=0pt 3 0]}]
\tikzstyle{doublearr} = [thick, double distance=7pt, arrows = {-Implies}]
%\tikzstyle{dottedcurved} = [line width=0.5pt, double distance=7pt, arrows = {-Implies}]
\tikzstyle{dashedarrow} = [dashed,->,>=stealth]
\tikzstyle{axes} = [->,>=stealth]

\begin{tikzpicture}[nodes={text depth=0.25ex,text height=2.0ex}]
\node (old) at (0,0) {Old Arabic};
\node (class) [right of=old, xshift=3cm] {Classical Arabic};
\node (sca) [above of=class, xshift=1.8cm, yshift=1cm] {};
\node (msa) [right of=sca, xshift=3.5cm] {MSA};
%\node (vern) [right of=class, xshift=7cm, align=center] {\small Modern\\\small Vernacular\\\small Arabic};
%\node (vern) at (class -| msa) [xshift=0.4cm] {\small Modern\\\small Vernacular\\\small Arabic};
\node (vern) at (class -| msa) [text centered,text width = 0.18\textwidth,text depth=0.5cm,align=left,xshift=0.7cm] {\small Modern Vernacular Arabic};


\draw [doublearr] (old) -- node [midway,yshift=1.5pt] {\footnotesize dialects} (class);
\draw [doublearr] (class) -- node [midway,yshift=1.5pt] {\footnotesize dialects} (vern);

\draw [arrow] (sca) -- (msa);

\draw [decoration={brace,raise=-0.2cm,amplitude=0.2cm,aspect=0.85}, decorate] 
   (class.north west) -- (class.north east);
      %node [midway, rotate=90, anchor=south, left=0ex] {\scriptsize SCA};

%\draw [->,>=stealth,thick,postaction={decorate,decoration={text along path,raise=3pt,text align=center,text={SCA}}}] (class) to [bend left=45] (sca);
%\draw [->,>=stealth,thick] ([xshift=-0.57cm]class.north east) to [bend left=30] (sca);
%\draw [->,>=stealth,thick,postaction={decorate,decoration={text along path,raise=1.5pt,text align=left,text={|\footnotesize|SCA}}}] ([xshift=-0.25cm]class.north east) to [bend left=25] (sca);
\draw [->,>=stealth,thick,postaction={decorate,decoration={text along path,raise=2.5pt,text align=center,text={SCA}}}] ([xshift=-0.4cm]class.north east) to [bend left=25] (sca);

\draw [dashedarrow] ([xshift=-1cm]msa.south west) -- (vern.north west);
\draw [dashedarrow] ([xshift=-1cm]vern.north west) -- (msa.south west);
\node (msavern) [below of=msa, xshift=-0.9cm, yshift=0.07cm] {\scriptsize cross-influence};

\node (native) [left of=old, xshift=-1.1cm, align=right] {\footnotesize native\\\footnotesize Arabic};
%\node (nonnative) [above of=native,align=right] {\footnotesize non-native\\\footnotesize SCA};
\node (nonnative) at (sca -| native) [xshift=-0.3cm,align=right] {\footnotesize non-native\\\footnotesize formal Arabic};

\node (classborrow) [above of=old,yshift=3cm,align=center] {\scriptsize Arabicized loanwords from\\\scriptsize Persian, Aramaic, etc.};
\draw [dashedarrow] (classborrow) -- (class.north west);

\node (scaborrow) [right of=classborrow,xshift=3cm,align=center] {\scriptsize Arabicized loanwords from\\\scriptsize Persian, Greek, etc.};
\draw [dashedarrow] (scaborrow) -- ([xshift=0.5cm]sca.north west);

\node (msaborrow) [right of=classborrow,xshift=7cm,align=center] {\scriptsize translated vocabulary, style and grammar\\\scriptsize from English, French, etc.};
\draw [dashedarrow] (msaborrow) -- (msa.north west);

\node (foreign) at (classborrow -| native) [xshift=-0.3cm,align=right] {\footnotesize foreign\\\footnotesize languages};

%\node (lang) [above of=foreign,yshift=1cm,xshift=1cm,align=right,rotate=90] {\scriptsize language/\\\scriptsize variety};

%\draw [axes] (-3,-0.5) -- node [below,xshift=7cm] {\footnotesize time axis} (13,-0.5);
\draw [axes] (-3,-0.5) --  (11,-0.5);
\draw [axes] (-1.5,-1) -- node [above, rotate=90, xshift=3.5cm,align=center] {\footnotesize language/\\\footnotesize variety} (-1.5,5);
%\draw [->,postaction={decorate,decoration={text along path,text align=right,text={|\scriptsize|time}}}] (-3,-0.5) to (13,-0.5);

\node (hijrah) [below of=class, yshift=0.2cm] {\footnotesize the Hijrah};
%\node (ah1400) [below of=vern, yshift=0.2cm,xshift=-1.75cm] {\footnotesize 1400\textsc{ah}};
\node (ah1400) at (hijrah -| msa)  {\footnotesize 1400\textsc{ah}};
\node (timelabel) [right of=ah1400,xshift=1cm]  {\footnotesize time axis};

\end{tikzpicture}
```

In the figure above, the extraction of
[sca]{.smallcaps}
towards the end of the Classical Arabic period does not imply that only later stages of Classical Arabic
contributed to
[sca]{.smallcaps}.
Rather, it only implies that that is when
[sca]{.smallcaps}
emerged as the standard literary language for non-native Classical Arabic users.
In fact,
the source material for
[sca]{.smallcaps}
includes
not only the speech of contemporary native Classical Arabic speakers,
but also transmitted texts from throughout the Classical Arabic period,
even texts from before the time of the Prophet ;pbuh;.

Nor does the diagram intend to imply that only
[sca]{.smallcaps}
was preserved
amongst all the dialects of Classical Arabic.
[sca]{.smallcaps}
is the variety of Classical Arabic which became a standard that continued to be used later.
But the scholars of the Arabic language made notes regarding the other dialects of Classical Arabic as well.

## What defines [sca]{.smallcaps}

<!--
In this context, 
-->
It may be appropriate to say a few words about what defines [sca]{.smallcaps} proper.
When the Arab grammarians first began recording and describing Classical Arabic,
the regular, day-to-day, speech of many people had already begun to deviate from Classical Arabic.
So the grammarians would seek out and record
samples of speech and texts from only authoritative sources.
And they had criteria for determining what constituted an authority in the language.
One such criterion was that the text sample be native Classical Arabic speech.
What we mean by 
"native Classical Arabic"
is the language produced by persons
immersed from early childhood in an
environment
where they would hear
(native) Classical Arabic
from people around them in their day-to-day lives,
such that they learned to speak it
naturally, without discernable change.^[See also [[علة رفض الاحتجاج بكبار الشعراء والكتاب الذين جاءوا بعد زمن الفصاحة]{.ar}](https://archive.org/details/riga2/page/n91/mode/2up) in @faysal_mansoor_articles@ 93--95]

By the time [sca]{.smallcaps} was emerging as a standard for literary output,
Classical Arabic was on the decline, as a native language.
Most literary output produced in
[sca]{.smallcaps}
was then a non-native attempt to conform to the standard.
So, even though proficiency in
[sca]{.smallcaps}
was generally pretty high,
books written in
[sca]{.smallcaps}
are not themselves, generally, definitive of
[sca]{.smallcaps}.

<!--
Versions of
[sca]{.smallcaps}
are used to this day as a literary language,
in formally produced news media and published literature.
-->

## [msa]{.smallcaps}

As we have mentioned earlier,
[sca]{.smallcaps}
when produced today will tend to have a lot of modern vocabulary, 
and will generally be referred to as
[msa]{.smallcaps}.
[msa]{.smallcaps}
is used today as the language of
published literature
and formally produced news media.

[msa]{.smallcaps},
in theory,
still attempts to conform to the grammar of
[sca]{.smallcaps}.
In practice,
however,
[msa]{.smallcaps}
is influenced
<!--
(mainly in its style,
but also occasionally in its grammar), 
-->
noticeably by
European languages.
This is because much 
written material, like books and news articles was, and is,
translated wholesale from European languages.
This translation, along with adding vocabulary, has also
influenced the style, and also in places, the grammar of
the [msa]{.smallcaps} which you are likely to find printed today.
<!--
In a sense,
this [msa]{.smallcaps}
has taken a life of its own.
This is because
when modern books and news media may form the brunt of a persons formative exposure to formal Arabic,
then that is the kind of Arabic that he will be likely to produce and in turn proliferate.
-->
That is not to say that all
[msa]{.smallcaps} produced today
has deviated from the grammar and style of
[sca]{.smallcaps}.
Persons who have been more exposed to
classical books are more likely to stay closer to
[sca]{.smallcaps}.
In any case, as we have mentioned earlier,
all Arabic that is produced
today that attempts to
conform to
[sca]{.smallcaps},
is merely that:
an attempt to
conform to
[sca]{.smallcaps},
and not definitive of
[sca]{.smallcaps}.


As a new learner, this exactitude is largely academic.
Excepting the ;quran;, which is inimitable,
you may feel free to emulate the writing of good writers of [sca]{.smallcaps}.

## Spoken [sca]{.smallcaps}

As we have mentioned above,
[sca]{.smallcaps}
is primarily a written language.
As a spoken language, [sca]{.smallcaps} is, today, heard almost only in religious and formal settings.

We will learn
in this book, ;ia;,
that there are very exact rules for properly pronouncing and pausing in 
[sca]{.smallcaps}.
Practically, however, most native Arabic speakers today rarely adhere to these rules exactly in extemporaneous speech.
Furthermore, depending on the situation,
speakers may sometimes casually mix in their vernacular dialect within their
[sca]{.smallcaps}
speech.
In terms of usage, Classical Arabic had many idiomatic expressions that were used in casual, day-to-day speech.
But because
spoken
[sca]{.smallcaps}
is relegated to formal settings today,
many of those expressions are now deemed archaic and are largely unused.
In fact,
a strict adherence to all [sca]{.smallcaps} grammar, usage, and pronunciation/pausing rules in informal spoken settings may,
today, come across as pretentious or overly formal.^[@hallberg_thesis@ 54--55. see also p.\ 86]

Our advice to the learner who wishes to speak his newly learned Arabic
is to learn to
be comfortable with the different spheres
and sociolinguistic norms
of Arabic.
Consider the following real-world setting:

A scholar may be giving a lecture,
in Arabic,
on one of the [#islAm]{.trn2}ic branches of knowledge.
It may even be a lecture on 
[sca]{.smallcaps} grammar.
In the beginning of the lecture,
the scholar will praise [#allAh]{.trn2}
and ask Allāh to confer blessing upon and grant peace to the Prophet ;pbuh;
This will be done using exact
[sca]{.smallcaps} grammar and pronunciation/pausing rules.

The scholar will then begin the instructional part of his lecture.
The language of this instruction will still typically be
[sca]{.smallcaps}.
But adherence to pronunciation and pausing rules may be considerably relaxed.
The scholar's speech may be closer to exact 
[sca]{.smallcaps}
rules
when giving formal instruction,
and then more relaxed when elaborating on some particular point.
When quoting an ;ayah; from the [#qurEAn]{.trn2},
strict
[sca]{.smallcaps}
would be employed,
even if not reciting the ;ayah;.
The scholar's fluency in spoken
[sca]{.smallcaps} is also a factor in how close his extemporaneous formal speech is to
[sca]{.smallcaps}.
Because, like anyone born after the classical era,
he is not a native speaker of 
[sca]{.smallcaps}.
And his proficiency in speaking exact
[sca]{.smallcaps} fluently does not detract, ;ia;,
from his eminence and
knowledge of his domain.
Within the lecture,
the scholar may even dip in and out of his vernacular dialect,
often when interacting with a questioner from the audience.

Once the lecture is concluded,
the scholar and his students may engage in an informal session.
The conversation in this session will almost entirely be in
vernacular dialect(s).

If you find yourself in such a society,
it is advisable to conform to its norms.
As a non-native Arabic speaker,
you won't be expected to speak a vernacular dialect.
So your speaking
[sca]{.smallcaps}
in an informal setting is excused.
But aim for a natural and easy flowing speech,
even at the cost of grammatical correctness.
Don't over articulate, and vary your pitch and tone.
<!--
^[Speaking formal
[sca]{.smallcaps}
in an informal setting is actually a trope in Arab culture,
and subject to some gentle humor.
See appendix\ (ref) for a collection of some jokes aimed at grammarians.]
-->
In fact, it may not be a bad idea to supplement your learning of
[sca]{.smallcaps}
with some knowledge of a vernacular dialect,
not least to understand the native speech of the Arabs today.
<!--
Even formal learning of a
vernacular dialect
is not required.
Often, it is sufficient for a non-Arab,
if he does not know a vernacular dialect,
to simply relax his Standard Arabic and use some commonly used substitutions for a few words and expressions.
-->


<!--
This exclusivity on our part is largely a matter of scope.
Practically speaking, it can be useful to have some breadth in your learning of Arabic.
As a spoken language, [sca]{.smallcaps} proper is, today, heard only in religious and very formal settings.
Even in religious lectures, the speaker often relaxes his conformance to [sca]{.smallcaps} rules.
Within the same speech, a speaker may dip in and out of [sca/msa]{.smallcaps} and a vernacular dialect.
This is a very natural process and is familiar to the audience.
A strict adherence to all [sca]{.smallcaps} grammar and enunciation rules in informal settings may, today, come across as turgid or pedantic.^[@hallberg_thesis@ 54--55, 86]
-->



## Scope of this book

In this book, we will study the grammar of [sca]{.smallcaps}. If [#allAh]{.trn2} wills, this will help you to begin to understand the language of the ;quran;, the [#HadIv]{.trn2}, and [#islAm]{.trn2}ic literature.

If your goal is to learn [msa]{.smallcaps}, then this book may still be of help because the core language and the grammar are essentially the same. However, you may prefer to study from a resource that focuses on the modern language.

This book does not touch at all upon the modern vernacular dialects that are spoken in the Arab world today.
<!--
## Current status

This book is currently a work in progress, and not yet ready for study.
There is a watermark on all online published pages indicating this status.
The preface and this introduction have been written prematurely as a reference for guiding principles that we can refer to during the writing process.
We publish updates online while the book is still a work in progress in the hope that it will help in correcting errors.
-->


## Organization of this book

We will start, if [#allAh]{.trn2} wills, with the Arabic script and present, in each chapter, a new concept of Arabic grammar, together with examples. 
Though there is none right now, we also plan to give, if [#allAh]{.trn2} wills, a vocabulary list and exercises for each chapter. 

We have generally tried to organize content coherently for convenient reference during learning.
Sometimes, this can mean that on encountering a new topic, we present it in more detail than is strictly necessary for learning at that stage.
Although identifying such material may not be easy for the learner, you may feel free to skim over such material and refer back to it later, as needed.

<!--
In order to organize content in a manageable and referrable way, 
we will give a reasonably full treatment of every topic upon its first encounter.
But in actuality, an exhaustive understanding of the topic may not be absolutely essential to the core understanding of grammar that a learner needs at that stage.
An example of such a topic is _semi-flexible nouns_ (_diptotes_ in Western grammars).
Although identifying such material may not be easy for the learner, you may feel free to skim over such material and refer back to it later, as needed.
-->

Some of the sentences we present, both as examples and as chapter exercises, because of their contrived nature, may seem of dubious usefulness to a learner wanting to learn practical usage.^[In this we are but following the tradition of the classical grammarians.
[ضَرَبَ]{.ar} [to beat]{.trans} was a favorite example verb of theirs. Consider (lightheartedly) these gems:
[اضرب أيهم أفضل]{.ar}
[[@sibawayhi@ 2/399](https://shamela.ws/book/23018/834)]{.citex}
[Beat whichever of them is most excellent!]{.trans}
and
[يعجبني أيهم ضربته في داره]{.ar}
[[@ibn_aqil_alfiyyah@ 1/168](https://shamela.ws/book/9904/167)]{.citex}
[I like the one amongst them whom I beat in his house]{.trans}.
Even the most excellent of people wasn't spared!
And a man was not safe from the grammarians even in his own house and even if he was someone they liked!]
Also, when translating examples, we usually steer toward a literal, word-for-word, translation rather than an idiomatic one. 
This is in order to illustrate the function of each word,
and to show a correspondence between the words in the Arabic sentence and the English translation.
The resulting English will then often sound awkward and, at times, even ungrammatical.
Our excuse is that our aim in this book is to teach Arabic,
not how to translate Arabic into English.

We request the reader's patience and indulgence in these and other matters.

<!--
## Indications of deviation from the norm

The rules of [sca]{.smallcaps} grammar were derived by the grammarians from recordings of authoritative Classical Arabic.
While many of the rules are generaly agreed upon,
some 

Vagueness:

* typically
* generally
* usually
* seems: We are not sure enough to assert definitively

No vagueness:

* archetypical
-->

## How to study from this book

Keep pen and paper in hand when studying.
Write some of the examples as you are studying and try to understand how the example is relevant to the topic.
In answering the exercises, we strongly recommend that you memorize the vocabulary in full and write down the answers with pen on paper.
We strongly recommend that you
avoid the tendency to
answer the exercises only orally or mentally without writing them down,
or look up the answers from the answer key before attempting to write the answer yourself,
or look up words in the vocabulary list without memorizing them,
or proceed to the next chapter before memorizing the vocabulary and going through the exercises.
You may also find yourself having to go back a few chapters every once in a while and revising the concepts therein. 
This is very normal and not a cause for any concern. It may also prove beneficial to re-do the exercises of that chapter when doing so.

Know that while Arabic grammar requires effort to master to a proficient degree, the real barrier to reading and understanding Arabic texts by oneself is vocabulary. 
Arabic is a very rich language and knowledge of a few thousand words is needed before the student can begin to read texts independently.
In fact, we would not be too far off to say that grammar, at this stage, is only a tool to help you make sense of the vocabulary that you are acquiring.
So strive to achieve a balance between learning grammar and acquiring vocabulary.
In appendix\ \@ref(vocabulary-and-reading), we suggest companion reading material, dictionaries, and techniques on acquiring and retaining vocabulary.
<!--
As companion reading material, we can recommend the book [عمدة التفسير لأحمد شاكر]{.ar} ([3umtdatu -ttafsIr]{.trn} by [#aHmad #cAkir]{.trn2}) which is an abridgement of the famous commentary of the [#qurEan]{.trn2} by [ابن كثير]{.ar} ([#ibn #kavIr]{.trn2}).
Start with [#surat al-#baqarah]{.trn2} because of its relatively easier content.
And try to start this early on, even before you have completed your grammar course.
In the beginning, trying to read a real book will seem difficult, especially when you haven't yet learned the complete Arabic grammar. 
But, keep at it, at intervals. If [#allAh]{.trn2} wills, it will become easier, and there will be a tipping point when you are able to understand many of the words and the gist of a sentence.
-->

## Interpreting the ;quran;

As you proceed in your Arabic studies,
you may begin to form an understanding of the meanings of some of the ;ayah;s of the ;quran;.
Pondering over the ;ayah;s of the ;quran;, to understand it, obtain guidance from it, and act upon it is one of the foremost goals of the ;quran;.^[@zarabozo_approach@ 96 citing [الفوزان]{.ar}]
Know, however, that forming this understanding should be done with a proper methodology: one that is based on sound and confirmed knowledge.^[@zarabozo_approach@ 187]
Interpreting the ;quran; is one of the branches of ;islam;ic knowledge known as ;tafsir;.
There are proper sources for ;tafsir;. They are:

1. The ;quran;.
   The ;quran; itself is a source of ;tafsir;. What is stated in a concise fashion in one place may be elaborated upon at another place.^[@zarabozo_approach@ 205 citing [الزركشي]{.ar}]
2. The Sunnah of the Prophet ;pbuh;.
   The Sunnah (via the [#HadIv]{.trn2}) is the second most important source of ;tafsir;.
   ;Allah; tasked the Prophet ;pbuh; with explaining the ;quran; and gave him ;pbuh; the necessary knowledge in order for him ;pbuh; to do so.^[@zarabozo_approach@ 212--213 citing [الألباني]{.ar}]
3. The understanding of the Companions of the Prophet ;pbuh;.
   The Companions had an excellent command of the Arabic language and lived through many of the events that the ;quran; refers to. Furthermore, if a meaning of an ;ayah; was not clear to them, they had access to the Prophet ;pbuh; and would ask him ;pbuh; about its meaning.^[@zarabozo_approach@ 224ff]
4. The Arabic language.^[@zarabozo_approach@ 235ff].
   One needs to have sound knowledge of the Arabic language of the time of the Prophet ;pbuh; to be able to interpret the ;quran; linguistically.
   However, one cannot rely solely on the Arabic language for ;tafsir;.^[@zarabozo_approach@ 241]
   There are many instances where the Companions, who possessed knowledge of the Arabic language, did not understand the intent of an ;ayah; and it was necessary for the Prophet ;pbuh; to explain the ;quran; to them.^[@zarabozo_approach@ 213ff]

The specialist in the science of ;tafsir; is able to use the above sources, and his educated reasoning,
to interpret and comment on the meaning of ;ayah;s.^[@zarabozo_approach@ 244--245]

There are grave dangers to speaking about the ;quran; without sound knowledge.
If one interprets and comments on the ;quran;,
then he is actually making a statement on behalf of ;Allah;.^[@zarabozo_approach@ 194]
So he better be sure that he is making that statement based on sound knowledge.
Because speaking about ;Allah; without knowledge is a most great sin.
This is because it involves and includes ascribing something falsely to ;Allah;.^[@zarabozo_approach@ 197 citing [ابن القيم]{.ar}]

Here is an example of an ;ayah; where it is conceivable that someone may make an incorrect interpretation,
if he did not interpret according to a proper methodology:

(@) [إِنَّ ٱلَّذِینَ ءَامَنُوا۟ وَٱلَّذِینَ هَادُوا۟ وَٱلنَّصَـٰرَىٰ وَٱلصَّـٰبِـِٔینَ مَنۡ ءَامَنَ بِٱللَّهِ وَٱلۡیَوۡمِ ٱلۡـَٔاخِرِ وَعَمِلَ صَـٰلِحࣰا فَلَهُمۡ أَجۡرُهُمۡ عِندَ رَبِّهِمۡ وَلَا خَوۡفٌ عَلَیۡهِمۡ وَلَا هُمۡ یَحۡزَنُونَ]{.quran}
    [@https://quran.com/2/62@]{.citex}  

Translation by [#SaH]{.trn2}ee[H]{.trn2} International™:

> [Indeed, those who believed and those who were Jews or Christians or Sabeans [before Prophet Muḥammad (;pbuh;)] - those [among them] who believed in Allāh and the Last Day and did righteousness - will have their reward with their Lord, and no fear will there be concerning them, nor will they grieve.]{.trans}

Footnote by the same translator:

> After the coming of Prophet Muḥammad (;pbuh;) no religion other than Islām is acceptable to Allāh, as stated in [3:85](https://quran.com/3/85).

The ;ayah; referred to in the footnote is:

(@) [وَمَن یَبۡتَغِ غَیۡرَ ٱلۡإِسۡلَـٰمِ دِینࣰا فَلَن یُقۡبَلَ مِنۡهُ وَهُوَ فِی ٱلۡـَٔاخِرَةِ مِنَ ٱلۡخَـٰسِرِینَ]{.quran}
    [@https://quran.com/3/85@]{.citex}  
    [And whoever desires other than Islām as religion - never will it be accepted from him, and he, in the Hereafter, will be among the losers.]{.trans}

Ibn [#kavIr]{.trn2}, in his ;tafsir; of this ;ayah;,
cites a report narrated from the the Companion of the Prophet ;pbuh;
[#ibn #eabbAs]{.trn2}
regarding ;ayah; @https://quran.com/2/62@, that ;Allah; revealed after it
@https://quran.com/3/85@.

Ibn [#kavIr]{.trn2} then says (paraphrasing):

> This statement by Ibn ʿAbbās indicates that ;Allah; does not accept any deed or work from anyone,
> unless it conforms to the Law of 
> [#muHammad]{.trn2} ;pbuh;
> that is, after ;Allah; sent
> [#muHammad]{.trn2} ;pbuh;.
> Before that, every person who followed the guidance of his own Prophet was on the correct path,
> following the correct guidance and was saved.^[@ibn_kathir_english@ 1/249]

From the ;tafsir; of this ;ayah;, we see how one ;ayah; is explained using another ;ayah;.
And we also see the role of the Companions in ;tafsir;.

The ;tafsir; of 
Ibn [#kavIr]{.trn2}
is available, abridged, in English translation:

* @ibn_kathir_english@

Arabic abridged editions also exist:

* [عمدة التفسير عن الحافظ ابن كثير لأحمد شاكر]{.ar}
* [المصباح المنير فى تهذيب تفسير ابن كثير للمباركفوري]{.ar}

These are beneficial, ;ia;,
not only for their ;tafsir;,
but also as
good companion reading material for the student of Arabic.

