# The Arabic grammatical tradition

;wip_warn;

## History of the Arabic grammatical tradition

<!--
By the end of the second century after the Hijrah,
we have the the first extant book on Arabic grammar titled _The Book_,
by a famous grammarian of the name [#sIbawayh]{.trn2}.

The earliest extant book on Arabic grammar
is titled
[الْكِتَاب]{.ar} [The Book]{.trans},
written
by the famous [#baSran]{.trans} grammarian [#sIbawayh]{.trn2} (died 185\ ;ah;).
[#sIbawayh]{.trn2}'s _Book_ is a remarkably comprehensive
-->


During the time of the Prophet ;pbuh;,
the Arabs spoke Classical Arabic natively.

After the time of the Prophet ;pbuh;,
<!--
when the borders of the [#islAm]{.trn2}ic state had expanded beyond the Arabian peninsula,
-->
<!--
there was an 
increased intermingling between Arab and non-Arab populations.
Because of this,
-->
<!--
the native speech of the Arabs began to
diverge from the Classical Arabic of the generation of the Companions of the Prophet ;pbuh;.
-->
during
the [#racidUn]{.trn2} caliphate (11--41\ ;ah;),
the borders of the [#islAm]{.trn2}ic state had expanded beyond the Arabian peninsula.
This brought upon an increased intermingling between Arab and non-Arab populations,
especially in the towns and urban centers.

There are
reports that,
during this time,
there was an increased occurrence of grammatical
and pronunciation errors in spoken Arabic,
especially by non-Arabs and the newer generation.
<!--
the older generation noticed that the kind of Arabic which was being spoken
on the street,
and by the newer generation,
had begun to diverge from the Classical Arabic of the generation of the Companions of the Prophet ;pbuh;.
Here are some examples of these reports:
-->

The reports also claim, that in order to safeguard the ;quran; from
being read incorrectly,
efforts began to preserve Classical Arabic.
This outline of events is traditionally credited as
the inception of the Arabic grammatical tradition,
and of the profession of the grammarian.

It is difficult to establish the authenticity of many of these reports.
So we are not certain
who would qualify to be the first grammarians,
nor are we certain of the extent of their grammatical discourse.
We do know that
the early grammarians 
of the first and early second centuries\ ;ah;,
were definitely able to distinguish between correct and incorrect language.^[@carter_thesis@ 5--6]
But their terminology and grammatical analysis
were presumably rudimentary.^[@baalbaki_intro@ xv; [@afghani@ 29--30, footnote\ 2](https://shamela.ws/book/9937/27#p1)]

However,
in the latter half of the second century\ ;ah;,
Arabic grammar had already developed,
from these primitive beginnings,
into a highly developed system of linguistic analysis.^[@baalbaki_intro@ xiii]

Initially,
grammatical activity flourished mainly
in two urban centers:
the cities of al-;Basr;ah
and al-;Kuf;ah
in Iraq.
These are often referred to as the
;Basr;an
and
;Kuf;an
grammatical schools respectively.
The 
;Basr;an
and
;Kuf;an
schools were mainly active,
in their eponymous cities,
into the third century\ ;ah;.
After that, grammarians would still often be ascribed academically
to one of the two schools,
but they were more geographically widespread.
Many famous later grammarians operated out of
[#bagdAd]{.trn2}, Egypt, Syria, Persia, and [al-#andalus]{.trn2} (;islam;ic Spain).

<!--
[al-#kisAEI]{.trn2}  
[#yUnus]{.trn2}  
[#sIbawayh]{.trn2}  
[al-#xalIl]{.trn2}  
[al-#farrAE]{.trn2}  
[#vaelab]{.trn2}  
[#sarrAj]{.trn2}  
[#zajjAjI]{.trn2}  
[#sIrAfI]{.trn2}  
[#jinnI]{.trn2}  
[#jurjAnI]{.trn2}  
[#zamaxcarI]{.trn2}  
[#abU al-#barakAt al-#anbArI]{.trn2}  
[al-#raDiyy al-#astarAbApI]{.trn2}  
[#yaeIc]{.trn2}  
[#mAlik]{.trn2}  
[#AjurrUm]{.trn2}  
[#euSfUr]{.trn2}  
[#maDAE]{.trn2}  
[#abU #HayyAn]{.trn2}  
[#eaqIl]{.trn2}  
[#hicAm]{.trn2}  
[#suyUTI]{.trn2}  
[#acmUnI]{.trn2}  
[al-#axfac al-#awsaT]{.trn2}  
[#abU #isHAq al-#cATibI]{.trn2}
[#abU #ealiyy al-#fArisI]{.trn2}
[Ibn #fAris]{.trn2}
-->

[@fig-gramtimeline]
depicts a (year of death) timeline and geographical distribution of some of the more well-known grammarians.

::: {#fig-gramtimeline .test-class}
```{.tikz}
% The following code is adapted from adapted from Andreas Hallberg’s https://andreasmhallberg.github.io/timeline-of-arab-grammarians
\usetikzlibrary{patterns}
\usetikzlibrary{calc, backgrounds}
\usetikzlibrary{arrows.meta, decorations.text}
\usetikzlibrary{shapes,positioning,intersections,quotes}

\newcommand\cetoah[1]{
  \fpeval{((#1) - 622) * (365.25/(29.5*12))}
}
\newcommand\ceaxis[1]{
    \draw (9, \cetoah{#1}) -- (9.2, \cetoah{#1}) node [anchor=west] {\footnotesize #1};
}

% Constants
\def\begah{0}
\def\endah{1000}
\def\beglong{0}
\def\endlong{9}
\def\regions{al-Andalus, North Africa, Egypt, Syria, al-Ḥijāz, Bag͡hdād, al-Kūfah, al-Baṣrah, Persia}
\def\mixcolor{gray}

\IfPackageLoadedTF{xcolor}{
\definecolor{GramNameColor}{RGB}{102, 0, 51}
}{}

\newcommand\condcolor[1]{
\IfPackageLoadedTF{xcolor}{\textcolor{GramNameColor}{#1}}{#1}
}


%\dynasty{<color>}{<begregion>}{<endregion>}{<begyear ah>}{<endyear ah>}{<name>}{<yshift>}
\newcommand\dynasty[7]{%
\begin{pgfonlayer}{background}
    % bar
    %\fill [color=#1!10!\mixcolor]
    %\fill [color=#1!20]
    \fill [pattern=#1,pattern color=black!18!white]
    ({#2-1},#4) rectangle (#3,#5);
    % label
    \node [black!25, #7, font=\bfseries\sffamily] 
    at ({#2-1+(#3-#2+1)/2},{#4+(#5-#4)/2}) {#6};
\end{pgfonlayer}
}
%x,y,xshift,yshift,label
\newcommand\person[7]{%
    \coordinate (pointnode)  at (#1,#2) {};
    \node [fill, draw, circle, minimum width=2pt, inner sep=0] at (#1,#2) {};
    \node (labelnode)  [inner sep=0, outer sep=0, #3 of=pointnode, xshift=#5, yshift=#6,anchor=#4] {\scriptsize \condcolor{#7}};
    \draw (pointnode)  -- (labelnode.#4);
}

% phases
% \phase{<name>}{<begin>}{<end>}
\newcommand{\phase}[3]{
    \draw [thin] (-0.8,#2+2) -- (-1,#2+2) -- (-1, #3-2) node [midway, above, rotate=90,align=center, font=\sffamily] {#1} -- (-0.8,#3-2);
}

\begin{tikzpicture}[y=0.1mm]

\draw [help lines] (\beglong,\begah) grid (\endlong,\endah);

% Axis
\draw [->, very thick] (\beglong,0) -- (\endlong+0.2,0);
\draw [->, very thick] (0,\begah) -- (0,\endah+20);

% Axis ticks
\foreach \y in {100,200,...,\endah} {
  \draw (0, \y) -- (-.2, \y) node [anchor=east] {\footnotesize \y};
}
\node  at (-0.5,0) {\footnotesize 1 AH};
\node  at (9.5,30) {\footnotesize CE};

\foreach \y in {600,700,...,1600} {
  \ceaxis{\y}
}


\foreach [count=\i] \x in \regions {
    %\node[label={\x}] (\i) at (\i-0.5, 0) {};
    \node[rotate=60,align=left,anchor=east] () at (\i-0.2, 0) {\footnotesize \x};
}

    % Baghdad
    \person{7.5}{170}{right}{west}{-16}{-12}{al-K͡halīl (\textsc{b})}
    \person{7.5}{182}{right}{west}{-16}{-8}{Yūnus b. Ḥabīb (\textsc{b})}
    \person{7.5}{180}{right}{west}{-16}{ 8}{Sībawayh (\textsc{b})}
    \person{7.5}{215}{above}{south}{20}{ -20}{al-Ak͡hfas͡h al-Awsaṭ (\textsc{b})}
    \person{7.5}{285}{above}{south}{20}{-20}{al-Mubarrad (\textsc{b})}

    % Kufah
    %\person{6.5}{150}{left} {east}{ 16}{0}{Abu Hanifah}
    \person{6.5}{189}{left} {east}{ 16}{-4}{al-Kisāʾī (\textsc{k})}
    \person{6.5}{207}{left} {east}{ 16}{0}{al-Farrāʾ (\textsc{k})}

    % Baghdad
    \person{5.5}{291}{left} {east}{ 16}{-1}{T͡haɛlab (\textsc{k})}
    \person{5.5}{316}{left} {east}{ 16}{-1}{Ibn al-Sarrāj (\textsc{b})}
    \person{5.5}{337}{left} {east}{ 16}{0}{al-Zajjājī}
    \person{5.5}{368}{left} {east}{ 16}{-1}{al-Sīrāfī (\textsc{b})}
    \person{5.5}{377}{left} {east}{ 16}{3}{Abū Ɛaliyy al-Fārisī (\textsc{b})}
    \person{5.5}{384}{left} {east}{ 16}{9}{al-Rummānī}
    \person{5.5}{392}{left} {east}{ 16}{13}{Ibn Jinnī}
    \person{5.5}{577}{right} {west}{-16}{6}{Abū al-Barakāt al-Anbārī}

    % Syria
    \person{3.5}{643}{right} {west}{-16}{3}{Ibn Yaɛīs͡h}
    \person{3.5}{672}{right} {west}{-16}{3}{Ibn Mālik}
    \draw [->, -{Latex}] (0.5,627) -- (3.5, 672);

    % Egypt
    %\person{2.5}{204}{right} {west}{-16}{0}{al-Shafiei}
    \person{2.5}{646}{left} {north}{ 10}{-10}{Ibn al-Ḥājib}
    \person{2.5}{745}{right} {west}{-16}{-2}{Abū Ḥayyān}
    \draw [->, -{Latex}] (0.5,674) -- (2.5, 745);
    \person{2.5}{761}{right} {west}{-16}{3}{Ibn His͡hām al-Anṣārī}
    \person{2.5}{769}{right} {west}{-16}{9}{Ibn Ɛaqīl}
    \person{2.5}{900}{right} {west}{-16}{0}{al-As͡hmūnī}
    \person{2.5}{911}{right} {west}{-16}{6}{al-Suyūṭī}

    % Persia
    \person{8.5}{471}{left} {east}{ 16}{0}{al-Jurjānī}
    \person{8.5}{538}{left} {east}{ 16}{6}{al-Zamak͡hs͡harī}
    \person{8.5}{684}{left} {east}{ 16}{-6}{al-Raḍiyy al-Astarābād͡hī}
    \person{8.5}{395}{left} {east}{ 20}{12}{Ibn Fāris}

    % Andalus
    \person{0.5}{592}{right}{west}{-16}{-10}{Ibn Maḍāʾ}
    \person{1}{669}{right}{west}{-16}{ 3}{Ibn Ɛuṣfūr}
    \person{0.5}{790}{right}{west}{-16}{22}{Abū Is·ḥāq al-S͡hāṭibī}

    % North Africa
    \person{1.5}{723}{above}{south}{-10}{-25}{Ibn Ājurrūm}

    \dynasty    {bricks}            {5}    {5}      {0}     {11}  {}{} % Prophet pbuh
    \dynasty    {bricks}            {2.5}  {8.5}    {11}    {41}  {RASHIDUN}{}
    \dynasty    {north east lines}  {2}    {9}      {41}    {132} {UMMAYADS}{}
    \dynasty    {north east lines}  {1}    {1}      {\cetoah{711}}    {\cetoah{1031}} {UMMAYADS}{rotate=90}
    \dynasty    {vertical lines}    {3}    {9}      {132}             {\cetoah{945}} {ABBASIDS}{yshift=6pt}
    \dynasty    {vertical lines}    {2}    {2}      {132}             {\cetoah{909}} {}{}% Abbasids % North Africa
    \dynasty    {vertical lines}    {5}    {5}      {\cetoah{945}}    {\cetoah{969}} {}{}% Abbasids
    \dynasty    {fivepointed stars} {3}    {4}      {\cetoah{969}}    {\cetoah{1171}} {FATIMIDS}{}
    \dynasty    {fivepointed stars} {5}    {5}      {\cetoah{969}}    {\cetoah{1171}} {}{} % Fatimids % Hijaz
    \dynasty    {fivepointed stars} {2}    {2}      {\cetoah{909}}    {\cetoah{1050}} {}{} % Fatimids % North Africa
    \dynasty    {crosshatch}        {3}    {5}      {\cetoah{1171}}   {\cetoah{1250}} {AYYUBIDS}{}
    %\dynasty    {crosshatch}        {5}    {5}      {600}             {\cetoah{1250}} {}{}
    \dynasty    {grid}              {6}    {9}      {\cetoah{1055}}   {\cetoah{1258}} {SELJUKS}{yshift=-10pt}
    \dynasty    {sixpointed stars}  {6}    {9}      {\cetoah{945}}    {\cetoah{1055}} {BUYIDS}{}
    \dynasty    {checkerboard}      {6}    {9}      {\cetoah{1258}}   {\cetoah{1335}} {MONGOLS}{}
    \dynasty    {horizontal lines}  {3}    {5}      {\cetoah{1250}}   {\cetoah{1517}} {MAMLUKS}{yshift=15pt}
    \dynasty    {crosshatch dots}   {1.5}  {1.5}    {\cetoah{1056}}   {\cetoah{1140}} {\scriptsize ALMORAVIDS}{rotate=60}
    \dynasty    {crosshatch dots}   {1.5}  {1.5}    {\cetoah{1140}}   {\cetoah{1269}} {\scriptsize ALMOHADS}{rotate=60}
    \dynasty    {dots}              {6}    {9}      {\cetoah{1335}}   {\cetoah{1508}} {\small TURKMEN DYNASTIES}{}
    \dynasty    {north west lines}  {2}    {8}      {\cetoah{1517}}   {1000} {OTTOMANS}{}

% Phases
% Data collection, formation, theroeticlaelaboration, consolidiation, degeneration
% \phase{Pre-theoretical\\grammar}{650}{780}
    \phase{\scriptsize Precursors}                           {\cetoah{660}} {\cetoah{770}}
    \phase{\scriptsize Early\\\scriptsize grammar}                        {\cetoah{770}} {\cetoah{920}}
    \phase{\scriptsize Codification\\\scriptsize and\\\scriptsize systematization}    {\cetoah{920}} {\cetoah{1100}}
    \phase{\scriptsize Elaboration of forms\\\scriptsize of presentation}{\cetoah{1100}}{\cetoah{1520}}


\end{tikzpicture}
```

A (year of death) timeline and geographical distribution of some of the more well-known grammarians.^[Adapted from Andreas Hallberg's blog post [[andreasmhallberg.github.io/timeline-of-arab-grammarians](https://andreasmhallberg.github.io/timeline-of-arab-grammarians)]{.citex}, and Ovamir Anjum's presentation at the Muslim Community Association, Santa Clara, Calif., 2013 [[youtu.be/cZ6RoRMF-kI](https://youtu.be/cZ6RoRMF-kI)]{.citex}.]
[(b)]{.smallcaps}
and
[(k)]{.smallcaps}
indicate an affiliation with the
;Basr;an
and
;Kuf;an schools, respectively.
:::


## #;samaa3; ([السَّماع]{.ar})


In order to develop a grammatical framework for Classical Arabic,
the grammarians first needed a collection of authentic Classical Arabic texts.
The grammarians 
used,
as their source material for this collection,
a corpus of Classical Arabic texts, which we will term _;samaa3;_.
The body of ;samaa3; can be categorized into^[from @suleiman_ta3leel@ 16]:

1. Transmitted texts. These include:
   a. Authorized readings of the ;quran;
   b. Poetry of the pre-;islam;ic and early ;islam;ic poets
   c. A collection of the sayings and proverbs of the Arabs
   d. the ;Hadith;
2. Elicited speech

We will discuss these categories below:

#### The ;quran; {.unnumbered}

The ;quran; was transmitted by the Prophet ;pbuh; to his Companions.
When the territories under the ;islam;ic caliphate expanded,
many of the Companions were sent or relocated to the different areas under Muslim rule,
and there, they began teaching the ;quran; to their students from the [#tAbieIn]{.trn2}.
Those students taught it to the next generation and so on and so forth.
The text of the ;quran; was thus available to the grammarians
and used by them as a primary linguistic source.^[@suleiman_ta3leel@ 18--19, [@qiyaas_amsha@ 7](https://ketabonline.com/ar/books/97698/read?part=1&page=7&index=5343316)]

#### Poetry {.unnumbered}

From pre-;islam;ic times into the ;islam;ic era,
Classical Arabic poetry was composed and transmitted orally,
from region to region, and from generation to generation.
The grammarians used this transmitted poetry as their second major source of transmitted data.^[@suleiman_ta3leel@ 19]
Some native Arabic dialects were beginning to diverge from Classical Arabic in the first and second century\ ;ah;.
Because of this,
the grammarians were more discerning in whether they would accept the poetry of a later poet.
Generally they would only accept the poetry of a later poet if his language was determined to be uninfluenced by the newer developments in the native dialects.
The grammarians generally have a cut-off date somewhere in the middle of the first century\ ;ah;.
Poetry composed after this cut-off date is typically not accepted as a valid source of Classical Arabic.^[[@qiyaas_amsha@ 8](https://ketabonline.com/ar/books/97698/read?part=1&page=8&index=5343317)]

#### Sayings and proverbs of the Arabs {.unnumbered}

A small portion of prose material,
consisting of sayings and proverbs of the Arabs,
is also generally accepted as a source of Classical Arabic data.^[@suleiman_ta3leel@ 16, [@qiyaas_amsha@ 7--8](https://ketabonline.com/ar/books/97698/read?part=1&page=7&index=5343316)]

#### The ;Hadith; {.unnumbered}

The ;Hadith; of the Prophet ;pbuh; were transmitted by his Companions
to their students from the [#tAbieIn]{.trn2},
who then transmitted them to their students from the next generation, and so on.
Theoretically, the ;Hadith; texts should be considered a valid source of Classical Arabic.
However, as a trend, the grammarians were reluctant to consider the transmitted ;Hadith; texts as part of ;samaa3;.
This is because they feared that some of the narrators in the chains of transmission of ;hadith; may have narrated their ;hadith; by meaning, rather than verbatim text.
And if the narrator was himself not a native Classical Arabic speaker,
than they could not be certain that the ;hadith; that reached them was correct Classical Arabic.
They did not have this view regarding the ;quran; and poetry
because the ;quran; and poetry required that they be transmitted verbatim.
This policy of the grammarians has received some criticism,
with some researchers deeming that they were unnecessarily exclusive,
and that if the transmitters of a ;hadith; are deemed competent, then the ;hadith; should be admitted into ;samaa3;.
In this sense, ;Hadith; texts
should be considered at least as acceptable as poetry,
since the possibility of variation in transmission is applicable to both.^[@suleiman_ta3leel@ 16--17, [@qiyaas_amsha@ 7--8](https://ketabonline.com/ar/books/97698/read?part=1&page=7&index=5343316)]
In any case, we note that if the grammarians erred then it was on the side of caution.

#### Elicited speech {.unnumbered}

In addition to the transmitted texts mentioned above,
the grammarians also used,
as part of their source data,
samples of speech that they obtained themselves by
meeting and talking to native Classical Arabic speaking _informants_.
Such informants continued to exist, in pockets,
into the second and third centuries\ ;ah;.
In general, the speech of the bedouin Arabs was considered purer and more free from errors
than that of the urban population.
The grammarians would seek out such informants,
listen to their ordinary speech in natural settings,
and also ask them questions,
the answers to which would betray insight into
the grammatical issues that they were investigating.^[@suleiman_ta3leel@ 22-24]

#### Exclusion of the grammarians' writings from ;samaa3; {.unnumbered}

The grammarians were scholars of Classical Arabic.
Yet, generally speaking, they were not native speakers of Classical Arabic.
So even though they were knowledgeable in analyzing Classical Arabic,
they had not learned it natively.
So their writings are not considered ;samaa3;.^[@qiyaas_husain@ 36--37]
Excepted are
examples that the grammarians made up and adduced to explain a particular grammatical issue.^[@suleiman_ta3leel@ 16]
Those are admitted into ;samaa3;, though subject to critique by other grammarians.^[Here is an example:  
[... ولم يذكره [سيبويه] إلا في نفس عبارته قال «وذلك عجبت من ضرب زيد عمرًا»، وليس في لفظه ما يدل على أنه محكي عن العرب، فيحتمل أن يكون ذلك رأيًا منه، بل هو ظاهر كلامه وقياس منه]{.ar}  
[[@abu_hayyan_tadhyeel@ 11/75](https://shamela.ws/book/17116/3610)]{.citex}]

## #;qiyaas; ([القِياس]{.ar}) and ;3illah; ([العِلّة]{.ar})

Once the source material from ;samaa3; was available to the grammarians,
they set about analyzing it
<!--
They did this by
observing patterns in ;samaa3;,
-->
in order to develop a grammatical framework
<!--
that accommodated those patterns.
-->
The process of developing a grammatical framework is based on
_;qiyaas;_ and _;3illah;_.

#;qiyaas; is the process of observing a pattern in ;samaa3;,
determining a ;3illah; for the pattern,
and expounding a grammatical rule that states that whenever the ;3illah; is to be found,
then the pattern is to be expected.^[@qiyaas_amsha@ 4--5]

Let's explain what we mean.

Let's say,
hypothetically,
the grammarian goes through the data in ;samaa3;, and comes across sentences like:

(@) [**جَاء الرَّجُلُ**]{.ar}  
    [The man came.]{.trans}  

(@) [**ضَرَبَ زَيْدٌ** عَمْرًا]{.ar}  
    [Zayd beat ;3amr;.]{.trans}  

(@) [**يَدْخُلُ** الْبَيْتَ **رَجُلٌ**]{.ar}  
    [A man enters the house.]{.trans}  

(@) [لَنْ **يَضِيعَ الْعَمَلُ** الصَّالِحُ]{.ar}  
    [The good deed shall not go waste.]{.trans}  

(@) [لَمْ **تَذْهَبْ هِنْدٌ**]{.ar}  
    [Hind did not go.]{.trans}  

<!--
(By the way, the above examples are made up and probably not actually found in ;samaa3;.)
-->
When the grammarian studies these sentences he notes that they are all ;j_f3l;s
consisting of (at least) a verb and its ;faa3il;.
He also observes a pattern.
And that is
that the ;faa3il; of the verb is always in the ;ustate;.
Now, he comes up with a grammatical rule that states that
whenever there is a ;j_f3l; (this is our ;3illah;),
then the ;faa3il; of the verb is be in the ;ustate;.

This rule is made for the benefit of the student
who has not gone through the data in ;samaa3;.
Let's say that a student is reading a text and comes across a sentence:

(@) [ضَرَبَ عَمْرًا زَيْدٌ]{.ar}  
    [Zayd beat ;3amr;.]{.trans}  

The student determines that this is a ;j_f3l;.
Being a ;j_f3l; is the ;3illah; that makes the above
;qiyaas;-based rule
applicable.
Now the student observes that [ضَرَبَ]{.ar} is the verb,
and following it are two nouns:
[عَمْرًا]{.ar} in the ;astate;,
and
[زَيْدٌ]{.ar} in the ;ustate;.
Applying the rule, he detrmines that the person who did the beating is Zayd, not ;3amr;.
This will give him a correct understanding of the text.

Furthermore, if the student wishes to construct his own ;j_f3l;,
attempting to conform to ;sca;,
then he knows that
he will have to put the verb's ;faa3il; in the ;ustate;.

## #;shaadh; ([الشَّاذّ]{.ar})

Sometimes a pattern occurs often enough in ;samaa3; that a rule is built upon it using
;qiyaas;.
However, occurrences contrary to the pattern are also found in ;samaa3;.
This usage which is contrary to ;qiyaas; is called _;shaadh;_.

As an example of ;shaadh;,
when the second letter of a root is [و]{.ar},
then its stem-10 ;madi; verb is regularly formed
by transforming the [و]{.ar} into an alif.
For example:

|Root| stem-10 ;madi; verb |
|:--|:------|
|[قوم]{.ar} | [اسْتَقَامَ]{.ar} [to be steadfast]{.trans}|
|[عوذ]{.ar} | [اسْتَعَاذَ]{.ar} [to seek refuge]{.trans} |
|[نور]{.ar} | [اسْتَنَارَ]{.ar} [to seek light]{.trans}  |

In ;shaadh;, a few roots whose middle letters are [و]{.ar},
usually form their stem-10 ;madi; verbs
by keeping the [و]{.ar}. For example:

|Root| stem-10 ;madi; verb |
|:--|:------|
|[حوذ]{.ar} | [اسْتَحْوَذَ]{.ar} [to gain mastery, overcome]{.trans}|
|[صوب]{.ar} | [اسْتَصْوَبَ]{.ar} [to consider ([هـ]{.ar} s.th) to be right]{.trans}|

By the way,
[اسْتَحَاذَ]{.ar} and [اسْتَصَابَ]{.ar}
are also found in ;samaa3;, albeit less frequently.

The general principle, when dealing with ;shaadh;,
is that it should
be limited to what is found in ;samaa3;,
and
not be extended by ;qiyaas;.

So the rule for forming stem-10 ;madi; verb for roots
that have [و]{.ar} as the middle letter,
is that
the verbs should be formed
generally by transforming the [و]{.ar} into an alif, like
[اسْتَقَامَ]{.ar}
and
[اسْتَعَاذَ]{.ar}.
But for the few verbs that fall into ;shaadh;,
we should prefer to keep the [و]{.ar}, thus:
[اسْتَحْوَذَ]{.ar}
and
[اسْتَصْوَبَ]{.ar}.
The forms
[اسْتَحَاذَ]{.ar} and [اسْتَصَابَ]{.ar}
are permissible but less preferred.^[@qiyaas_husain@ 40]

The grammarians have not always agreed over how to deal with different ;shaadh;s.
As an example,
when an ;sifah; is on the pattern
[أَفْعَل]{.ar},
like
[أَبْيَض]{.ar} [white]{.trans}
and
[أَسْوَد]{.ar} [black]{.trans},
then
a ;af3al; for it on the same pattern
[أَفْعَل]{.ar}
is regularly not found to be used in ;samaa3;.
So 
[أَبْيَض]{.ar}
is not usually found in ;samaa3; to mean [more white]{.trans}.
However, this meaning is found as ;shaadh;, as in the verse of poetry:

(@) [جَارِيَةٌ فِي دِرْعِهَا الفَضْفَاضِ ~ **أَبْيَضُ** مِنْ أُخْتِ بَنِي إِبَاضِ]{.ar}
    [@qiyaas_husain@ 42]{.citex}  
    [A girl in her full long shirt ~ **whiter** than a [woman of the tribe] of [#banU #ibAD]{.trn2}]{.trans}  

Some grammarians were of the opinion,
that because of the usage of
[أَبْيَض]{.ar} in the above verse to mean [whiter]{.trans},
this can be extended by analogy generally.
So whenever a ;sifah; is on the pattern
[أَفْعَل]{.ar},
a ;af3al; can also be formed for it on the same pattern.
Other grammarians were more conservative and did not extend this usage by ;qiyaas;.^[@qiyaas_husain@ 42]

## The balance between ;qiyaas; and ;samaa3;

The ultimate authority for what is correct Classical Arabic is ;samaa3;.
#;qiyaas;-based rules are a means to understand ;sca; correctly,
and a guide to form sentences that attempt to conform to ;sca;.

#;qiyaas;
is a speculative process on the part of the grammarians.^[@baalbaki_teaching_arabic@ 86]
As such, it is subjective, and
rules derived from ;qiyaas; may need to be revised and refined in order to sufficiently explain the language.
Natural language,
however,
is very complex and
;qiyaas;-based rules,
even if continually revised and refined,
can perhaps never capture its full complexity.

#;samaa3;, in general, cannot be rejected on the basis of ;qiyaas;.
And an ;qiyaas;, even if it were sound, should not be applied if it
leads to something that is contrary to ;samaa3;.^[[@intisaar_ibn_walaad@ 204](https://shamela.ws/book/29555/164#p1) cited by @baalbaki_book_agt@ 130]


## Classical Arabic dialects and ;sca;

Classical Arabic consisted of multiple dialects
that were spoken by the various tribes of the Arabs
in the different regions of the Arabian peninsula.
When the grammarians developed ;qiyaas;-based rules from ;samaa3;,
they would often grade the usages in the different dialects.
Even within a dialect, sometimes there are multiple permissible ways to construct an expression.
For forming ;qiyaas;-based rules,
the grammarians would often select,
out of the various usages,
a more normative one, or a more eloquent one,
or a more preferred one, or what they deemed a more original one.

Standard Classical Arabic (;sca;) is the _de facto_ standard variety
of Classical Arabic
that became dominant through,
amongst other factors,
the
widespread adoption of the grammarians' rules.

As an example,
the grammarians discuss a dialectal usage that pluralizes a verb even when the plural ;faa3il; is mentioned.
So speakers of this dialect would say:

(@) [ضَرَبُونِي قَوْمُكَ]{.ar}
    [[@sibawayhi@ 2/40](https://shamela.ws/book/23018/475)]{.citex}  
    [Your people beat me.]{.trans}  

instead of the more normative:

(@) [ضَرَبَنِي قَوْمُكَ]{.ar}

The dialectal usage of example ()
is graded as the lesser used.^[[@sibawayhi@ 2/40](https://shamela.ws/book/23018/475)]
It did not make its way into ;sca;.
Instead, the usage in example () became the standard.

## #;taqdiring; ([التَّقْدِير]{.ar})

In analyzing ;samaa3;,
the grammarians were
attempting to build a comprehensive and coherent grammar of Classical Arabic.
During this process, they saw that natural speech,
even when not ;shaadh;,
was often too complex to be codified
compactly.
However,
they also realized that
under the literally uttered speech
(termed _surface speech_),
there could be modeled a _virtual_ utterance
that was more amenable to being wrangled into 
organized rules.

The grammarians then considered it their role to theorize a _;taqdir;_,
when needed,
under the surface speech,
and to build their grammatical framework based on the ;taqdir;.

Let's explain what we mean by going through a hypothetical example.
Let's say that a grammarian goes through some data in ;samaa3;,
and he finds surface speech samples like the following:

(@) [قَرَأَ زَيْدٌ]{.ar}  
    [Zayd read.]{.trans}  

(@) [رَجَعَتْ هِنْدٌ]{.ar}  
    [Hind returned.]{.trans}  

(@) [يَذَهَبُ الرِّجَالُ]{.ar}  
    [The men go.]{.trans}  

The grammarian asks his native Classical Arabic speaking informant
what the informant understands by the above samples.
The informant tells the grammarian that he understands each one as having a complete meaning,
a meaning
that expresses
an action
(signified by the first word),
and the ;faa3il; of that action,
(signified by the second word).

Because each sample has a complete meaning,
the grammarian
determines that each sample is a complete sentence.
He
classifies the first word in each sentence as a verb,
and the second word as a noun.
Based on the abundance of sentences like the above,
the grammarian formulates a rule,
which is that a ;j_f3l; needs two parts to be a complete sentence:
a verb, followed by its ;faa3il; (noun).

The grammarian 
then continues going through ;samaa3;
and finds surface speech samples like the following:

(@) [تَصَدَّقْنَ]{.ar}  
    [They~f~ gave charity.]{.trans}  

(@) [عَمِلْتُ]{.ar}  
    [I worked.]{.trans}  

(@) [تَكْتُبَانِ]{.ar}  
    [You~2~ are writing.]{.trans}  

(@) [ذَهَبُوا]{.ar}  
    [They went.]{.trans}  

Checking with his informant, he
finds that these also are complete sentences in their meaning.
The informant tells him that the ;faa3il; of each action is now a person who is not named,
but who is known to the informant.
So the grammarian classifies the ;faa3il;s as _pronouns_.
<!--
But the ;faa3il;s of the verbs here are not expressed as common or proper nouns.
Rather, the  sentences' meanings signify that the ;faa3il;s are pronouns.
-->
The grammarian also notices that the end of each verb is modified and extra sounds
(expressed by letters in the script)
are added after it.
For example:
[عَمِلَ + تُ = عَمِلْتُ]{.ar} 

The grammarian then decides that these sentences can still be molded to fit into his above stated rule.
He does this
by analyzing
the extra sounds at the end of the verbs
(for example, [تُ]{.ar} in [عَمِلْتُ]{.ar})
to be the ;faa3il; pronouns.
Now
the sentences can be considered to have two parts: a verb followed by its ;faa3il;.
So far so good.

But now the grammarian comes across surface speech samples like the following:

(@) [ذَهَبَ]{.ar}  
    [He went.]{.trans}  

(@) [رَجَعَتْ]{.ar}  
    [She returned.]{.trans}  

(@) [أَعْمَلُ]{.ar}  
    [I work.]{.trans}  

(@) [نَتَصَدَّقُ]{.ar}  
    [We give charity.]{.trans}  

These samples pose a problem for our grammarian.
Because his informant tells him that he still understands these samples,
in context, to have a complete meaning.
The ;faa3il; of each action is again a person who is not named but who is known to the informant.

So, evidently, samples () through () are complete sentences with pronoun ;faa3il;s,
just like samples () through ().
But the problem is that there are no apparent extra sounds/letters after the verbs which can be considered the ;faa3il;.

Some of the verbs in these sentences,
like in examples () and (),
have extra sounds, but they are before the verb.
But some verbs,
like in example (),
don't even have that.
Example () [رَجَعَتْ]{.ar}
does have an extra [تْ]{.ar} after the verb,
but that letter is kept when there is an ;zaahir; ;faa3il; noun,
like in example () [رَجَعَتْ هِنْدٌ]{.ar}
above.
So the [تْ]{.ar} doesn't seem like it can be the ;faa3il;.
So what is the grammarian to do?

In order to keep the rule consistent,
the grammarian ;qaddars; _;mustatir;_ ;faa3il;s for these sentences.
For example () above, the ;mustatir; ;faa3il; is ;qaddared; as [[هُوَ]{.ar}], thus:

(@) [ذَهَبَ [هُوَ]]{.ar}  
    [He went.]{.trans}  

Now the sentence still has two parts:
the verb
[ذَهَبَ]{.ar}, followed by it's ;faa3il;, the ;qaddared; [[هُوَ]{.ar}].

This ;taqdir;ing on the part of the grammarian is definitely speculative and subjective.
But it is supported by the meaning which is in the mind of the native Classical Arabic speaker.
This is because the informant still understands each sample () through () to be a complete sentence with a pronoun ;faa3il;.

Here are the other examples with their ;qaddared; ;faa3il;s:

There are a couple of points to note about the ;qaddared; sentences
in examples () through () above.

One point is that these are not actually expressed sentences.
That is, we don't actually say, for example,
[ذَهَبَ هُوَ]{.ar}
when we want to say [He went]{.trans}.
Example () [ذَهَبَ]{.ar} is the only correct way to express this intended meaning.
The representation () [ذَهَبَ [هُوَ]]{.ar}
is only a _;taqdir;_ of example () [ذَهَبَ]{.ar}
that elucidates the grammar of the sentence.
By the way,
[ذَهَبَ هُوَ]{.ar}
is actually a correct sentence
in its own right,
but it has a different meaning than the intended
[ذَهَبَ]{.ar}
[He went]{.trans}.
It is a form of _;tawkeed;_ and we will study it in chapter\ (ref), ;ia;.

One point to note is that the ;qaddared; ;faa3il;s,
([[هُوَ]{.ar}],
[[هِيَ]{.ar}],
[[أَنَا]{.ar}],
and
[[نَحْنُ]{.ar}]
in examples () through () above)
are not "real" representations of the ;faa3il;s.



One option is to modify the rule,
and say that some ;j_f3l;s can consist of only a verb with no expressed ;faa3il;.
And he can specify which conjugations of a verb would fall under this sub-rule.

The other option is to keep the rule, as is.
That is, he states that a ;j_f3l; needs a verb followed by its ;faa3il;.
But not kkkkkkkkkkk
But now he lists the verb conjugations for which

But instead of there being a distinct noun after the verb,
the end of the verb has extra sounds
sentences also fit in with their above stated rule.
The sentences consist of a verb followed by its ;faa3il;.
The only difference is that the ;faa3il; is now a


* verb without ;faa3il; after it
* an + subjunctive



## The subjective and speculative nature of the ;taqdir;

## Difference of opinion between the grammarians

The grammarians sometimes differed with one another
regarding the extraction of ;qiyaas;-based rules from ;samaa3;.
We have seen a couple of examples of their differences in the sections above.
These differences often,
though not always,
occur along grammatical school lines,
with the
;Basr;ans having one opinion,
and the
;Kuf;ans another.^[See @baalbaki_intro@ §_The Basran/Kufan divide_ pp.\ xxxix--xlii] 
Sometimes, the difference is more in terminology than anything else.
For example,
the ;Basr;ans in their definition of the _;faa3il;_,
mandated that the ;faa3il; only occurs after the verb in word order.
The ;Kuf;ans on the other hand allowed the ;faa3il; to occur before the verb.
However, both schools allowed sentences like:

(@) [زَيْدٌ جَاءَ]{.ar}  
    [Zayd came.]{.trans}  

It's just that the ;Kuf;ans would analyze
[زَيْدٌ]{.ar} as a ;faa3il;,
whereas the ;Basr;ans would analyze it as a ;mubtada;.^[[@maani_nahw@ 2/45](https://shamela.ws/book/17801/428)]

Some more differences between the two schools are that
the ;Kuf;ans are considered to be more lax in extending ;qiyaas;
from ;shaadh;.
Whereas the ;Basr;ans would attempt to interpret ;shaadh; through ;taqdiring;
so that it aligned with their rules.
Both, however, as a general rule, accepted the ;shaadh; as valid ;samaa3;.
The ;Kuf;ans are also thought to be more grounded in that they tried to stay
closer to ;samaa3;^[[@abu_hayyan_tadhyeel@ 11/75](https://shamela.ws/book/17116/3610)]
rather than venturing into too much ;taqdiring;.

Generally speaking,
the ;Basr;ans formed their terminology and opinions
with a view to building a comprehensive and coherent grammatical framework.
And it is their terminology and opinions that became the standard among later grammarians.
Nevertheless,
the ;Kuf;an view is often brought in as a reality check against
what may sometimes be deemed to be excessive rule strictness and ;taqdiring;
on the part of the ;Basr;ans.

## FINI

<!--
This led to the founding of the discipline of Arabic grammar,
and the birth of a new profession:
that of the grammarian.
The motive of the early grammarians
for studying and analyzing the Arabic language
seems to have been
to preserve Classical Arabic,
and to safeguard the ;quran; from being incorrectly recited.^[@baalbaki_intro@ xv]

The level of grammatical analysis
in the first century after the Hijrah
appears to have been rudimentary.^[@baalbaki_intro@ xv; @afghani@ 27--30]
-->
<!--
Grammar at its inception was rudimentary.

In this very early stage,
it appears that the "grammar" developed by the early grammarians
was very rudimentary.^[@baalbaki_intro@ xv; @afghani@ 27--30]
-->
<!--
But by the end of the second century,
it had matured to a highly developed framework,
that utilized a set of
advanced analytic methods
to build a comprehensive and coherent grammatical framework.

fundamental tools to build a coherent and encompassing grammatical framework.
Some of these tools are:
-->

* ;samaa3;
* ;qiyaas;
* ;3illah;
* ;taqdir;

We will describe them in the next section, ;ia;.

## Description of the tool

## Taqdir

In order to preserve Classical Arabic,
a new profession took shape,
that of the grammarian.
Grammarians studied compilations of Classical Arabic texts
and derived a theoretical model of the grammar of Classical Arabic.
We will describe this model in the next few sections.

## 

The grammarians,
started with a body of authentic Classical Arabic texts.
They 
classified words in these texts
into different grammatical categories
(like nouns, verbs, particles).
They then derived the rules for connecting the words to form sentences.

But actually,
the grammarians went one step further.
They theorized that there were linguistic causes or reasons,
in the mind of the native speaker,
due to which he would choose a particular form or expression.^[https://shamela.ws/book/11321/2]

Sometimes these causes were apparent in the speech itself.
For example:


Other times, these causes were 

For example,
Consider the sentence:

(@) [أريد أن آكل طعاما]{.ar}

The grammarians theorized that
the particle [أن]{.ar}
causes 
the cause for the




Grammarians took compilations of authentic Classical Arabic texts


The grammarian acquired and had at his 
Over the new few generations,
grammarians compiled a _corpus_ of Classical Arabic texts.
So st
So they began to take steps to preserve Classical Arabic.
At its outset,
this effort seems to have centered around enhancing the Arabic script
to better distinguish the individual letters and vowels.
(which at the time did not have a standard way of
(which at the time seems to
Over the next few generations,
a new profession emerged and matured,
that of the grammarian.
The grammarian 

So much so, that some people were beginning to commit errors in their recitation of the ;quran;.

As we know, the endings of nouns and ;mudarie; verbs indicate their state.
There are reports
^[The soundness of these reports according to the criteria of the scholars of [#HadIv]{.trn2} is unknown to us.
We mention them as an indicator of a historical trend.]

In an attempt to preserve the correct

the borders of the caliphate expanded and incorporated countries where Arabic was not spoken.



### Sources of the corpus

Quran

Poetry

First hand samples of speech from informants

Hadith

## FINI

## History of the Arabic grammatical tradition

The exact details of the genesis of the Arabic grammatical tradition
are shrouded in the mists of history.
What we can say, summarily, is that
during the time of the revelation of the ;quran;,
the Arabs spoke Classical Arabic natively.
Then, after the time of the revelation,
when the caliphate extended beyond the Arabian peninsula,
an Arabic began to be spoken,
by the newer generation and non-native speakers,
that was diverging from Classical Arabic.

Around this time (c.\ 50\ [ah]{.smallcaps})


## Rule building

Consider the following scenario where
we want to teach a student Arabic.
Here is one approach:

We first teach the student the sentence:

(@) [أُرِيدُ أَنْ آكُلَ طَعَامًا]{.ar}
    [I want to eat some food.]{.trans}

We have the student memorize this sentence and its meaning.

And then we teach him the sentence:

(@) [أُرِيدُ أَنْ أَشْرَبَ مَاءً]{.ar}
    [I want to drink some water.]{.trans}

We again
have the student memorize this sentence and its meaning.

Similarly, we list all the sentences we can think of, and have him memorize them verbatim along with their meanings.

At some point, we may realize that instead of teaching all possible sentences and their meanings,
maybe we can start with some sentences.
break the sentences into words, classify the words into categories
(nouns, verbs, etc.),
and give him the rules for connecting the words together to form sentences.
Clearly, this is more efficient than listing all possible sentences,
and memorizing each one and its meaning individually.



## The underlying levels of speech

The grammarians,
thus started with a body of authentic Arabic speech.
They broke down that speech into sentences and words,
classified the words into different grammatical categories,
and derived the rules for connecting the words to form sentences.
This formed the basis of the science of grammar.

But actually, the grammarians went one step further.
They noticed that some sentences can superficially be different,
but they have a common behavior which can be attributed to the same cause.
For example,
let's look at the sentences:

(@) [جلست لأن أستريح]{.ar}
    [nawh waadih 1/135]{.citex}

(@) [جلست لأستريح]{.ar}
    [nawh waadih 1/135]{.citex}

In examples () and () above, we note that the verb
[أستريح]{.ar}
is in the ;astate;.
In example (),
the verb is preceded by [لِأَنْ]{.ar}
whereas in example ()
the verb is preceded only by [لِ]{.ar}.

Now, we know that a ;mudarie; verb is put in the ;astate; 
when it directly follows [أَنْ]{.ar}.
For example:

(@) [يسرني أن تزورَنا]{.ar}

Putting these (and other) factors together,
the grammarians theorize that
when an ;astate; ;mudarie; verb follows [لِ]{.ar}
(as in example ()) above),
then an implied [أَنْ]{.ar} is assumed after the [لِ]{.ar}.
And it is this implied
[أَنْ]{.ar} that causes the verb to be in ;astate;.

So, according to the grammarians,
when we hear the utterance
[جلست لأستريح]{.ar},
then there is an underlying form:
[جلست لأن أستريح]{.ar}
and this underlying form explains the syntax of the words in the speech that was actually uttered.
In this case, an
implied [أَنْ]{.ar} 
in the underlying form
caused the verb [أستريح] to be in ;astate;.

Conversely, some sentences can superficially be similar,
but they have different underlying causes for their superficial similarity.
For example,
consider the sentences:

(@) [جئت راكبا]{.ar}
    [kees 286 citing ibn jinni]{.citex}  
    [I came  riding.]{.trans}  

(@) [طبت به نفسا]{.ar}
    [kees 286 citing ibn jinni]{.citex}  
    [I [felt] good towards him in mind.]{.trans}  

Superficially, both nouns
[راكبا]{.ar}
and
[نفسا]{.ar}
are in the ;astate; and they both describe the verbs in the sentence.
So they are both adverbs.
But example () can have an underlying form which is reconstructed as:

(@) [طابت به نفسي]{.ar}
    [My mind [felt] good towards him]{.trans}  

In the reconstructed underlying form above, [نفس]{.ar} becomes the ;faa3il; of the verb.
Example () does not support a similar reconstructed underlying form.
That is,
we cannot say:

(@) ;x; [جَاء رَاكِبي]{.ar}  
    [My riding came]{.trans}

This tells us that
[راكبا]{.ar}
and
[نفسا]{.ar}
fall in different grammatical categories.
[راكبا]{.ar}
is a ;hal;,
whereas
[نفسا]{.ar}
is a ;tamyiz;.

Terminologically,
we will refer to the reconstruction of an underlying form of an utterance as its taqdir.
And we will refer to

So, in this way,
the grammarians formulated rules of grammar that explain the structure of 
the Arabic language,
by theorizing underlying forms.


Many times the surface of some speech cannot be directly explained by

The grammarians contended that a native speaker intuitively constructs the underlying forms 
in his mind
and the underlying forms contain the causes for the syntax in the speech that we hear uttered.
Now, obviously this underlying form is not something that is consciously known to the native speaker.
But the grammarian, with thorough study of a vast body of native texts,
can attempt to reconstruct the underlying forms which the native speaker knows by intuition.


some setences


The grammarians contended that the native speaker knows that the two sentences fall under the same grammatical category, and so he deals with them in a similar way.
So postulated a underlying form in which the similarity of both sentences becomes apparent.
In the case of the above example,
the underlying form is

In a similar manner, some sentences can appear to be similar in form of their utterance,
but actually are somewhat different at an underlying level.
And so there should actually

And so there is a hierarchy and levels of similarity and differences in the mind of the native speaker,
which necessitate coming up with a grammatical framework that mirrors this systemization in the mind of the speaker.

Arabic grammar then is
a grammarian-constructed model of the speech unit in the mind of the native Classical Arabic speaker.

Kees 286:

> The crucial point is that the underlying form is needed for the explanation of the syntactic relations in the surface sentence.


Native speaker's knowledge is unconscious.
Grammarian comes up with causes in the mind of the native speaker.

Quote by al-xaleel

##

Doesn't necessarily match, and often will not match,
with actual utterance

zaydan darabtuhu
[darabtu] zaydan darabtuhu

##

underlying form aims to be minimalist.^[kees 284 citing guilliame]

an mudmarah wujooban

hatta + marfoo3 = no an

an + mudaari3 = masdar

Sometimes underlying form, as costructed by the grammarians, does not explain authentic usage.

##

Underlying form is only a model.
Underlying form is unheard.
subjective.
subject to critique.
weaker than a grammarian's proof
Some grammarians were more reactionary. and rejected popular models.

## taqdir is not diachronic

kees 283--284

## taqdir can have different levels

zaydan darabtu

upper level: ma3mool preceded 3aamil

lower level: [darabtu] zaydan darabtu
because 3aamil has to precede ma3mool


one level: an mudarah
another level: an+verb = masdar

## Outline


Ultimate authority is the speech of the Arabs

Rules are deduced from analyzing corpus.

Rules are formulated in order:

* explain grammar analytically
* for qiyaas

Language is very complex.

Rules can keep on refining but

Rules can reach a limit where they are not suffient to capture the complexity.

Nevertheless, rules are useful not least to explain the normative usage

Within the grammatical tradition,
some grammarians were more practical.

as a school, their rep are the kufans,

they are strong on going back to ultimate authority: speech of arabs

but weak on coming up with a harmonious framework.

Basrans are more theoretical.

They are strong on coming up with harmonious model.

But you can't put cart before horse, when using their rules.

When we find authentic usage to be contrary to rules,
then either or both:

1. Rule is not sufficiently refined, and perhaps can never be.
2. It can be an anomalous usage that is correct but not normative.

Grammarians came up with 3ilal.

They may not be historically accurate.

They are only to provide a path to lead to a harmonious grammatical model.

[أضعف من حجة نحوي]{.ar}

## theory of taqdeer

kay has an mudmar

define rule an + subj = masdar

so now an is implicated when it is not there

## How to understand the grammarians' examples

Examples which they use,
especially contrived ones,
are to be understood within the scope of the discussion.
For example, the grammarians may say that the following is not a correct sentence:

(@) [زيد ضارب عمرا أمس]{.ar}

What they mean is that the ;ism_fail; cannot govern a ;mafulb; with a perfective meaning.
They use [أمس]{.ar} to show that the action occurred in the past and thus that the action was perfect.
But actually, the same sentence can be used if the ;ism_fail; has a past continuous meaning.
So we have to understand that when they use an example,
it may not necessarily be the wording of the example which is correct or incorrect.
They are using the example as a representation of
the concept which they are trying to explain.
In the scope of another concept, the same example may have a different ruling wrt to its correctness.

Continuing with the above example,
the grammarians will say that because the ;ism_fail; cannot have a ;mafulb;
therefore it has to be a ;ma3nawi; ;idaafah;.
And they give the following example:

(@) [زيد ضارب عمرو أمس]{.ar}

They again use [أمس]{.ar} to indicate the past.
But [أمس]{.ar}, as a ;dharf_zaman; needs a governor.
The ;ism_fail; can't govern it because it is not a governor.
The grammarians won't explainn this in the context of the governance of the ;ism_fail; because it is outside the scope of the current discussion.
Actually,
a verb is implicated, thus:

(@) [زيد ضارب عمرو [ضربه] أمس]{.ar}

Contrived examples are simplistic and not bulletproof outside of the concept which is being discussed.


## use of [HadIv]{.trn2} as a corpus

most grammarians did not consider authoritative because of narrators in chain who narrated by meaning and not necessarily wording.

[فيصل المنصور]{.ar} [cites works of [ياسر الطريقي]{.ar}](https://archive.org/details/riga2/page/n477/mode/2up?q=%D9%8A%D8%A7%D8%B3%D8%B1)

* [الشواهد الحديثية في الأبواب النحوية]{.ar}
* [الاستشهاد بالحديث في المسائل النحوية]{.ar}

We will use hadith in this book because easier for student to read than poetry.
And more practical.
But just to be safe, any deduction that you find us doing purely from hadith, without being backed by an authority should be taken with a grain of salt, until and unless you are able to substantiate it.

## TODO: 

find reference to develop above outline. Try works of Prof. Ramzi Baalbaki

<https://shamela.ws/book/11321/41>

## Further Reading

1. Shah, M., "Exploring the Genesis of Early Arabic Linguistic Thought: Qur'anic Readers and Grammarians of the Kufan Tradition (Part I)" <https://soas-repository.worktribe.com/output/421999/exploring-the-genesis-of-early-arabic-linguistic-thought-quranic-readers-and-grammarians-of-the-kufan-tradition-part-i>
2. Shah, M. "Exploring the Genesis of Early Arabic Linguistic Thought: Qur'anic Readers and Grammarians of the Baṣran Tradition (Part II)" <https://soas-repository.worktribe.com/output/434046/exploring-the-genesis-of-early-arabic-linguistic-thought-quranic-readers-and-grammarians-of-the-basran-tradition-part-ii>
3. Suleiman, Y. "Ideology, Grammar-Making and the Standardization of Arabic"
4. [الاحتجاج بالقراءات القرآنية وموقف النحاة منه , محمود حسن عمر]{.ar} <https://ketabonline.com/ar/books/97622>
5. KEES VERSTEEGH, THE NOTION OF 'UNDERLYING LEVELS' IN THE ARABIC GRAMMATICAL TRADITION
6. [من تأريخ النحو لسعيد الأفغاني]{.ar}
7. Almog Kasher, Two Types of Taqdīr?  A Study in Ibn Hišām’s Concept of ‘Speaker’s Intention’
8. <https://www.alukah.net/library/0/153594/%D8%A7%D9%84%D8%AA%D8%B9%D9%84%D9%8A%D9%84-%D8%A7%D9%84%D9%86%D8%AD%D9%88%D9%8A-%D8%B9%D9%86%D8%AF-%D8%A7%D9%84%D9%85%D8%A8%D8%B1%D8%AF-%D8%AA-285%D9%87%D9%80-%D9%81%D9%8A-%D9%83%D8%AA%D8%A7%D8%A8%D9%87-%D8%A7%D9%84%D9%85%D9%82%D8%AA%D8%B6%D8%A8/>
9. [الإيضاح في علل النحو أبو القاسم الزجاجي]{.ar} p.\ 64 <https://shamela.ws/book/143170/24>
10. <https://shamela.ws/book/11321/12#p1>

## Conclusion

The theory of government 
is a theory on which much of the Arabic grammatical tradition rests.
But it is worth reiterating that it is a theory which was built and refined to explain the motives behind the speech of the Arabs.
The ultimate authority in the Arabic language is the speech of the Arabs.
And it is a problem of any
grammatical theory that it has to fit the speech of the Arabs and not vice versa.

Frequently we will find rules that say:
X can not govern Y in Z circumstance.
And then we find usage which may seem to contradict this rule.
Underlying form is implicated to conform to rule.
Or theory needs to be modified.
