# Irregular nouns

## Introduction

There are some nouns in Arabic which are _irregular_ and behave a little differently than other _regular_ nouns. In this chapter we will study these irregular nouns.

## The five nouns

There are five nouns in Arabic which are irregular in the same basic way. Collectively, they are called "the five nouns".
They behave a little differently from regular nouns in how they display their state.
<!--
We have learned that regular nouns have three states: the u-state, a-state, and i-state. For singular nouns, the u-state is marked by the [u]{.trn}-mark [◌ُ]{.ar}, the a-state is marked by the [a]{.trn}-mark [◌َ]{.ar}, and the i-state is marked by the [i]{.trn}-mark [◌ِ]{.ar}. The [n]{.trn}-marks [◌ٌ]{.ar}, [◌ً]{.ar} and [◌ٍ]{.ar} are only but extensions of [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar} respectively.

We now present the five irregular nouns that behave differently.
-->


### [أَبٌ]{.ar} [Eab]{.trn}, [أَخٌ]{.ar} [Eax]{.trn}, and [حَمٌ]{.ar} [Ham]{.trn}

The first three nouns that we will talk about are:

i. [أَب]{.ar} [Eab]{.trn} "a father"        (root: [أبو]{.ar}) 
i. [أَخ]{.ar} [Eax]{.trn} "a brother"       (root: [أخو]{.ar}) 
i. [حَم]{.ar} [Ham]{.trn} "a father-in-law" (root: [حمو]{.ar}) 

The final root letter of all three of these nouns is [و]{.ar}. However, irregularly, it is omitted in most formations of the word. It does resurface in some cases as we will describe below.

Without the final root letter [و]{.ar}, these nouns display their state like regular nouns. Here are some examples:

[لِلْجَارِيَةِ أَبٌ كَبِيرٌ وَأَخٌ صَغِيرٌ.]{.ar}  
[liljAriyati Eabun kabIrun waEaxun SagIr]{.trn}  
"The girl has an old father and a young brother."

[ضَرَبَ ٱلْغُلَامُ أَخًا لَهُ.]{.ar}  
[Daraba -lgulAmu Eaxan lahu.]{.trn}  
"The boy beat a brother of his."

[ٱَلْحَمُ وَٱلْأَبُ فِي بَيْتِ ٱلْأَخِ.]{.ar}  
[EalHamu walEabu fI bayti -lEax.]{.trn}  
"The father-in-law and the father are in the brother's house."

Where the nouns behave irregularly is when they are an ;mudaf; in an ;idafa;. Then instead of displaying their state with [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar}, they display their state using the long vowels [و]{.ar} [U]{.trn}, [ا]{.ar} [A]{.trn}, and [ي]{.ar} [I]{.trn} instead. Here are some examples:

[هُوَ أَخُو ٱلْجَارِيَةِ.]{.ar}  
[huwa Eaxu -ljAriyah]{.trn}  
"He is the girl's brother."
<!--
[زَيدٌ أَخُو عَمْرٍو.]{.ar}  
[zaydun EaxU eamrin.]{.trn}  
"Zayd is [#eamr]{.trn2}'s brother."
-->

[سَأَلْتُ أَبَا صَدِيقِي عَنْ أَمْرٍ.]{.ar}  
[saEaltu EabA SadIqI ean Eamr.]{.trn}  
"I asked my friend's father about a matter."

<!--
[شَكَرْتُ لِحَمِي زَيْدٍ.]{.ar}  
[cakartu liHamI zaydin.]{.trn}  
"I thanked Zayd's father-in-law."
-->

[ذَهَبْتُ إِلَىٰ بَيْتِ حَمِي ٱلرَّجُلِ.]{.ar}  
[pahabtu EilA bayti Hami -rrajul.]{.trn}  
"I went to the man's father-in-law's house."

When these nouns are annexed to attached pronouns, then in most cases they will behave as above. So, for example,

[أَبُوهُ]{.ar}  
[EabUhu]{.trn}  
"his father" (u-state).

[أَخَانَا]{.ar}  
[EaxAnA]{.trn}  
"our brother" (a-state).

However, if the attached pronoun is [ي]{.ar} (for the singular speaker participant), then in that case, the attached pronoun [ي]{.ar} attaches to the ;mudaf; directly, without any intervening long vowel:

<!--
Even when the ;mudafil; in the noun-chain is an attached pronoun, these nouns behave in this irregular way, except if the attached pronoun is for the speaking person [ي]{.ar}. In that case, the attached pronoun [ي]{.ar} attaches to the ;mudaf; directly, without any intervening long vowel. Examples:
-->

[أَخِي]{.ar}  
[EaxI]{.trn}  
"my brother" (u-state, a-state, and i-state).

[أَبِي]{.ar}  
[EabI]{.trn}  
"my father" (u-state, a-state, and i-state).

[حَمِي]{.ar}  
[HamI]{.trn}  
"my father-in-law" (u-state, a-state, and i-state).

Here are some more examples in sentences:

[أَخُوهُ طَوِيلٌ وَأَخُوهَا قَصِيرٌ وَأَخِي كَبِيرٌ.]{.ar}  
[EaxUhu TawIlun waEaxUhA qaSIrun waEaxI kabIr.]{.trn}  
"His brother is tall and her brother is short and my brother is big."

[سَأَلَ أَخَاهُمْ وَأَخَانَا.]{.ar}  
[saEaltu EaxAhum waEaxAnA.]{.trn}  
"I asked their~m,3+~ brother and our brother."

[شَكَرَ أَخِي أَبِي.]{.ar}  
[cakara EaxI EabI.]{.trn}  
"My brother thanked my father."

[ذَهَبْتُ إِلَىٰ بَيْتِ أَخِيهِنَّ.]{.ar}  
[pahabtu EilA bayti EaxIhinn.]{.trn}  
"I went to their~f,3+~ brother's house."

The above irregular behavior of these three nouns is only when they are ;mudaf;s. When they happen to be ;mudafil;s in ;idafa;s, then they again they behave like regular nouns and their state is displayed by the short vowel marks [◌ُ]{.ar}, [◌َ]{.ar}, and [◌ِ]{.ar}, when definite, and by [nUn]{.trn2}ation 
[◌ٌ]{.ar}, 
[◌ً]{.ar}, and
[◌ٍ]{.ar}, when indefinite.
. Examples:

[بَيْتُ ٱلْأَخِ كَبِيرٌ.]{.ar}  
[baytu -lEaxi kabIr.]{.trn}  
"The brother's house is big."

[ذَهَبْتُ إِلَىٰ بَيْتِ أَخٍ.]{.ar}  
[pahabtu EilA bayti Eax.]{.trn}  
"I went to a brother's house."

When these nouns form their duals and plurals, then the final root letter [و]{.ar} is resurfaces.
In forming the broken plural, the final root letter [و]{.ar}, being a weak letter, sometimes converts to a [ء]{.ar}.
The following table shows their duals and plurals.

|Word | Dual (u-state) | Dual (a-state and i-state)|Plural|
|:-|:--|:---|:---|
|[أَب]{.ar} [Eab]{.trn}|[أَبَوَانِ]{.ar} [EabawAni]{.trn}|[أَبَوَيْنِ]{.ar} [Eabawayni]{.trn}|[آبَاء]{.ar} [EAbAE]{.trn}|
|[أَخ]{.ar} [Eax]{.trn}|[أَخَوَانِ]{.ar} [EaxawAni]{.trn}|[أَخَوَيْنِ]{.ar} [Eaxawayni]{.trn}|[إِخْوَة]{.ar} [Eixwah]{.trn}, [إِخْوَان]{.ar} [EixwAn]{.trn}|
|[حَم]{.ar} [Ham]{.trn}|[حَمَوَانِ]{.ar} [HamawAni]{.trn}|[حَمَوَيْنِ]{.ar} [Hamawayni]{.trn}|[أَحْمَاء]{.ar} [EaHmAE]{.trn}|

One special note regarding the dual [أَبَوَانِ]{.ar}/[أَبَوَيْنِ]{.ar}: in addition to meaning "two fathers", they can also mean "both parents", i.e., "a father and a mother". Here are examples of these words in sentences:

[ذَهَبَ ٱلْأَخَوَانِ إِلَى ٱلْمَسْجِدِ.]{.ar}  
[pahaba -lEaxawAni fi -lmasjidi.]{.trn}  
"The brothers~2~ went to the mosque."

[سَأَلْتُ أَخَوَيَّ عَنْ أَمْرٍ]{.ar}  
[saEaltu Eaxawayya ean Eamrin.]{.trn}  
"I asked my brothers~2~ about a matter."

[شَكَرْتُ لِأَبَوَيْهِ]{.ar}  
[cakartu liEabawayhi.]{.trn}  
"I thanked his parents."

### [ذُو]{.ar} [pU]{.trn} and [ذَات]{.ar} [pAt]{.trn} {#zu}

The fourth irregular noun from "the five nouns" is the masculine noun [ذُو]{.ar} [pU]{.trn} and its feminine counterpart [ذَات]{.ar} and [pAt]{.trn}. The words [ذُو]{.ar} [pU]{.trn} and [ذَات]{.ar} [pAt]{.trn} mean "owner of" or "possessor of". 

So, for example, [ذُو ٱلْمَالِ]{.ar} [pu -lmAli]{.trn} means "possessor~m~ of wealth" or "wealthy person~m~". The singular, dual, and plural of [ذُو]{.ar} [pU]{.trn} in all three states is shown in the table below:

|State|Singular|Dual|Plural|
|:--|:---|:---|:---|
|u-state|[ذُو]{.ar} [pU]{.trn} |[ذَوَا]{.ar} [pawA]{.trn}|[ذَوُو]{.ar} [pawU]{.trn}|
|a-state|[ذَا]{.ar} [pA]{.trn} |[ذَوَيْ]{.ar} [paway]{.trn}|[ذَوِي]{.ar} [pawI]{.trn}|
|i-state|[ذِي]{.ar} [pI]{.trn} |same as a-state|same as a-state|

The noun [ذُو]{.ar} [pU]{.trn} and its duals and plurals are only ever used as ;mudaf;s in ;idafa;s. Furthermore, they may not be annexed to pronouns. Here are some examples:

[ٱَلرَّجُلُ ذُو ٱلْمَالِ.]{.ar}  
[Earrujulu pu -lmAl.]{.trn}  
"The man is the possessor of wealth." = "This man is wealthy."

The word [ذَات]{.ar} is the feminine of [ذُو]{.ar}. When used as an ;mudaf;, its states, duals, and plurals are as in the table below:

|State|Singular|Dual|Plural|
|:--|:---|:---|:---|
|u-state|[ذَاتُ]{.ar} [pAtu]{.trn} |[ذَوَاتَا]{.ar} [pawAtA]{.trn} |[ذَوَاتُ]{.ar} [pawAtu]{.trn}|
|a-state|[ذَاتَ]{.ar} [pAta]{.trn} |[ذَوَاتَيْ]{.ar} [pawAtay]{.trn}|[ذَوَاتِ]{.ar} [pawAti]{.trn}|
|i-state|[ذَاتِ]{.ar} [pAti]{.trn} |same as a-state|same as a-state|

Examples:

[هَـٰذِهِ ٱلشَّجَرَةُ ذَاتُ ثَمَرٍ كَثِيرٍ.]{.ar}  
[hApihi -ccajaratu pAtu vamarin kavIrin.]{.trn}  
"This tree is the possessor of much fruit." = "This tree is very fruitful."

As opposed to [ذُو]{.ar} which is only an ;mudaf;, [ذَات]{.ar} may be used a noun in its own right. In this case it means "personality" or "essence". This usage is often found in theological or philosophical works. And, as such, unlike [ذُو]{.ar} which can't be annexed to attached pronouns, [ذَات]{.ar} can be annexed to attached pronouns. Examples:

### [فَم]{.ar} [fam]{.trn}

The fifth of "the five nouns" is [فَم]{.ar} [fam]{.trn} "a mouth". It is the most irregular of "the five nouns".

In some ways, the word [فَم]{.ar} [fam]{.trn} is regular. It is only irregular when it is a singular ;mudaf;. Let's first see its regular bahavior.

[عَلَى ٱلْوَجْهِ فَمٌ وَفِي ٱلْفَمِ لِسَانٌ.]{.ar}  
[eala -lwajhi famun wafi -lfami lisAn]{.trn}  
"On the face is a mouth, and in the mounth is a tongue."

It is a ;mudafil; in an ;idafa; regularly:

[نَطَقَ لِسَانُ ٱلْفَمِ.]{.ar}  
[naTaqa lisAnu -lfam.]{.trn}  
"The mouth's tongue articulated [speech]."

It forms duals regularly, which are used in ;idafa;s regularly

[فَمَا ٱلنَّهْرَيْنِ كَبِيرَانِ.]{.ar}  
[fama -nnahrayni kabIrAni.]{.trn}  
"The mouths~2~ of the rivers~2~ are big."

Let's now see its irregular behavior.

When [فَم]{.ar} is a singular ;mudaf;, then it is usual for it to follow the example of the rest of the five nouns.

<!--
In addition to the above regular behavior of [فَمٌ]{.ar} [famun]{.trn} "mouth", when the word is singular and is the first noun in a noun-chain, it is common to replace it with [فُو]{.ar} [fU]{.trn}. This is also done when the second noun in the noun-chain is a pronoun. 

The three states of the singular [فُو]{.ar} [fU]{.trn} are shown in the table below:
-->

Here is how it will appear as a singular ;mudaf; in the three states:

|u-state|a-state|i-state|
|:---|:---|:---|
|[فُو]{.ar} [fU]{.trn} |[فَا]{.ar} [fA]{.trn} |[فِي]{.ar} [fI]{.trn}|

Examples of usage:

[فُو ٱلنَّهْرِ كَبِيرٌ.]{.ar}  
[fu -nnahri kabIr.]{.trn}  
"The mouth of the river is big."

[فُوهَا جَمِيلٌ.]{.ar}  
[fUhA jamIl.]{.trn}  
"Her mouth is beautiful."

[فَتَحَ فَاهُ.]{.ar}  
[fataHa fAh.]{.trn}  
"He opened his mouth."

[جَعَلَتِ ٱلْأُمُّ لُقْمَةَ طَعَامٍ فِي فِي ٱبْنَتِهَا.]{.ar}  
[jaealati -lEummu luqmata TaeAmin fI fi -bnatihA.]{.trn}  
"The mother put a morsel of food in her daughter's mouth."

When the attached pronoun for the speaking person [ي]{.ar} is attached to [فُو]{.ar} [fU]{.trn}, [فَا]{.ar} [fA]{.trn}, or [فِي]{.ar} [fI]{.trn} the combination is always [فِيَّ]{.ar} [fiyya]{.trn} in all three states. Examples:

[فِيَّ مَفْتُوحٌ.]{.ar}  
[fiyya maftUh.]{.trn}  
"My mouth is open."

[فَتَحْتُ فِيَّ.]{.ar}  
[fataHtu fiyy.]{.trn}  
"I opened my mouth."

[أَكَلْتُ بِفِيَّ.]{.ar}  
[Eakaltu bifiyy.]{.trn}  
"I ate with my mouth."

In addition to the above irregular behavior, it is permissible, but less common, to treat [فَم]{.ar} regularly as an ;mudaf; in an ;idafa;. So it is permissible to also say:

[فَمُ ٱلنَّهْرِ كَبِيرٌ.]{.ar}  
[famu -nnahri kabIr.]{.trn}  
"The river's mouth is big."

[فَمِي مَفْتُوحٌ.]{.ar}  
[famI maftUhun.]{.trn}  
"My mouth is open."

[فَمُهَا جَمِيلٌ.]{.ar}  
[famuhA jamIlun.]{.trn}  
"Her mouth is beautiful."

[فَتَحَ فَمَهُ.]{.ar}  
[fataHa famahu.]{.trn}  
"He opened his mouth."

[جَعَلَتِ ٱلْأُمُّ لُقْمَةَ طَعَامٍ فِي فَمِ ٱبْنَتِهَا.]{.ar}  
[jaealati -lEummu luqmata TaeAmin fI fami -bnatihA.]{.trn}  
"The mother put a morsel of food in her daughter's mouth."

<!--
As mentioned above, [فُو]{.ar} [fU]{.trn} typically only replaces [فَمٌ]{.ar} [famun]{.trn} "mouth", when the word is singular and is the first noun in a noun-chain. Otherwise, [فَمٌ]{.ar} [famun]{.trn} continues to be used.
-->

The other irregularity of [فَم]{.ar} [fam]{.trn} "a mouth" is that its broken plural is 
[أَفْواه]{.ar} [EafwAh]{.trn}.

Note that the letter [م]{.ar} has not been used to form the broken plural, and instead a [و]{.ar}, and a [ه]{.ar} are used to form it.

## Other irregular nouns

There are more nouns that have irregularity in their own ways. We will discuss them below.

### [أُولُو]{.ar} [EulU]{.trn} and [أُولَات]{.ar} [EulAt]{.trn}

[أُولُو]{.ar} [EulU]{.trn} 
(first syllable has a short vowel with a silent [و]{.ar}) 
means "people~m~ of". It is only used as a masculine plural ;mudaf;, similar in meaning to
[ذَوُو]{.ar} [pawU]{.trn} which we discussed in section\ \@ref(zu) above.
There is no singular or dual of this noun.

Here is its form in the different states:

|u-state|a-and i-state|
|:---|:---|
|[أُولُو]{.ar} [EulU]{.trn}| [أُولِي]{.ar} [EulI]{.trn}|

Example:

[لِأُولِي ٱلْأَرْحَامِ حُقُوقٌ.]{.ar}  
[liEuli -lEarHAmi HuqUq.]{.trn}  
"The people of the wombs (i.e. blood relatives) have rights."

The feminine counterpart of
[أُولُو]{.ar} [EulU]{.trn} 
is
[أُولَات]{.ar} [EulAt]{.trn} "women of".
The first syllable again has a short vowel with a silent [و]{.ar}.

|u-state|a-and i-state|
|:---|:---|
|[أُولَاتُ]{.ar} [EulAtu]{.trn}| [أُولَاتِ]{.ar} [EulAti]{.trn}|

[لِأُولَاتِ ٱلْحَمْلِ حُقُوقٌ عَلَىٰ بُعُولَتِهِنَّ.]{.ar}  
[liEulAti -lHamli HuqUq ealA bueUlatihinn.]{.trn}  
"The women of pregnancy (i.e. pregnant women) have rights upon their husbands."

### [أُمّ]{.ar} [Eumm]{.trn}

The noun 
[أُمّ]{.ar} [Eumm]{.trn} "a mother"
forms two [At]{.trn} sound plural variants:

i. [أُمَّهَات]{.ar} [EummahAt]{.trn}
i. [أُمَّات]{.ar} [EummAt]{.trn}

The first variant
[أُمَّهَات]{.ar} [EummahAt]{.trn}
is more commonly used.
Example:

[أُمَّاهَاتُ ٱلْغِلْمَانِ طَيِّبَاتٌ.]{.ar}  
[EummahAtu -lgilmAni TayyibAt.]{.trn}  
"The boys' mothers are good."

### [سَنَة]{.ar} [sanah]{.trn}

The noun 
[سَنَة]{.ar} [sanah]{.trn} "a year"
forms both an [At]{.trn} sound plural
and an [Un]{.trn} sound plural.
(Remember from 
section\ \@ref(applicability-of-the-un-sound-plural)
that a few nouns that don't denote male intelligent beings have [Un]{.trn} sound plurals.)

In both plurals, the singular noun is modified irregularly.

|Singular |[At]{.trn} sound plural |[Un]{.trn} sound plural (u-state) |[Un]{.trn} sound plural (a- and i-states)|
|:--|:---|:---|:---|
|[سَنَة]{.ar} [sanah]{.trn} |[سَنَوَات]{.ar} [sanawAt]{.trn} |[سِنُونَ]{.ar} [sinUna]{.trn} |[سِنِينَ]{.ar} [sinIna]{.trn}|

Either of the two plurals may be used interchangeably.
Here are some examples:

### [مَاء]{.ar} [mAE]{.trn}

[مَاء]{.ar} [mAE]{.trn} "a water" forms its broken plural irregularly: [مِيَاه]{.ar} [miyAh]{.trn} "waters".

### [شَفَة]{.ar} [cafah]{.trn}

[شَفَة]{.ar} [cafah]{.trn} "a lip"
forms its broken plural irregularly: [شِفَاه]{.ar} [cifAh]{.trn} "lips".

Also, despite ending in the feminine marker [ة]{.ar}, it does not form an [At]{.trn} sound plural.

### [ٱِبْن]{.ar} [Eibn]{.trn}, [ٱِبْنَة]{.ar} [Eibnah]{.trn}, and [بِنْت]{.ar} [bint]{.trn}

The noun 
[ٱِبْن]{.ar} [Eibn]{.trn} "a son" is from the root [بنو]{.ar}.
It has two feminine counterparts:

i. [ٱِبْنَة]{.ar} [Eibnah]{.trn}
i. [بِنْت]{.ar} [bint]{.trn}

which mean "a daughter".

[ٱِبْن]{.ar} [Eibn]{.trn} "a son"
forms both a broken plural
and an [Un]{.trn} sound plural.

Its broken plural is [أَبْنَاء]{.ar} [EabnAE]{.trn} "sons". 

In forming the 
[Un]{.trn} sound plural,
the singular noun is modified irregularly:

|Singular |[Un]{.trn} sound plural (u-state) |[Un]{.trn} sound plural (a- and i-states)|
|:--|:---|:---|
|[ٱِبْن]{.ar} [Eibn]{.trn} |[بَنُونَ]{.ar} [banUna]{.trn} |[بَنِينَ]{.ar} [banIna]{.trn} |

The feminine
[ٱِبْنَة]{.ar}
and
[بِنْت]{.ar}
"a daughter"
form the irregular [At]{.trn} sound plural
[بَنَات]{.trn} [banAt]{.trn} "daughters".
Note that 
[بَنَات]{.ar} [banAt]{.trn}
is not a broken plural from the root [بنت]{.ar}. Therefore, it obeys the rules of [At]{.trn} sound plurals and does not end with [◌َ]{.ar} or [◌ً]{.ar} in the a-state.

Here are some examples using these nouns:


<!--
## Nouns that begin with connecting [hamzah]{.trn2}

When the definite article [ٱَلْ]{.ar} [Eal]{.trn} is prefixed to a noun which begins with a connecting [hamzah]{.trn2}, the [hamzah]{.trn2} is not pronounced. Instead the [lAm]{.trn} in [ٱَلْ]{.ar} will take an [i]{.trn}-mark. For example, [ٱِبْنٌ]{.ar} [Eibnun]{.trn} "a son" becomes [ٱَلِٱبْنُ]{.ar} [Ealibnu]{.trn} "the son".
-->
### [نَاس]{.ar} [nAs]{.trn}, and [أُنَاس]{.ar} [EunAs]{.trn}

[نَاس]{.ar} [nAs]{.trn}
and
[أُنَاس]{.ar} [EunAs]{.trn}
are from the root [أنس]{.ar}.
They both mean "a people".

When indefinite, only 
[أُنَاس]{.ar} [EunAs]{.trn}
tends to be used, and
[نَاس]{.ar} [nAs]{.trn}
tends to be unused.

When definite, only
[ٱَلنَّاس]{.ar} [EannAs]{.trn}
tends to be used, and
[ٱَلْأُنَاس]{.ar} [EalEunAs]{.trn}
is unused.

Here are some examples using these nouns:

### The nouns [ٱِمْرَأ]{.ar} and [ٱِمْرَأَة]{.ar}

The nouns 
[ٱِمْرَأ]{.ar} [EimraE]{.trn} (masc.) "a man, a person" and 
[ٱِمْرَأَة]{.ar} [EimraEah]{.trn} (fem.) "a woman" 
are quite irregular.

Firstly, 
[ٱِمْرَأَة]{.ar} [EimraEah]{.trn} "a woman" 
is, from the perspective, of its meaning, the feminine counterpart of
[رَجُل]{.ar} [rajul]{.trn} "a man (male human being)".

[ٱِمْرَأ]{.ar} [EimraE]{.trn}, on the other hand, only means "a man" in a general sense. For example, in the sentence "A man is only as good as his word." It can also be translated as "a person".

Secondly, 
[ٱِمْرَأ]{.ar} [EimraE]{.trn} "a man, a person" has no plural.
[نَاس]{.ar}/[أُنَاس]{.ar} "a people" and [قَوْم]{.ar} "a population" may be used when a plural is required.

[ٱِمْرَأَة]{.ar} [EimraEah]{.trn} "a woman" irregularly forms the broken plurals 
[نِسَاء]{.ar} [nisAE]{.trn} and [نِسْوَة]{.ar} [niswah]{.trn} "women". The former
([نِسَاء]{.ar} [nisAE]{.trn}) is more commonly used.

Like [شَفَة]{.ar} [cafah]{.trn}
it also, despite ending in the feminine marker [ة]{.ar}, does not form an [At]{.trn} sound plural.

Thirdly, both nouns are very irregular in how they become definite nouns with [ٱَلْ]{.ar}.
When [ٱَلْ]{.ar} is prefixed to these nouns to make them definite, they lose the initial connecting [hamzah]{.trn2} and change their internal vowels. This table shows what we mean:

State         | Definite of [ٱِمْرَأ]{.ar}     | Definite of [ٱِمْرَأَة]{.ar}
:-------------|:----------------------------|:----------------------------
u-state       |[ٱَلْمَرْءُ]{.ar} [EalmarEu]{.trn}|[ٱَلْمَرْأَةُ]{.ar} [EalmarEatu]{.trn}
a-state       |[ٱَلْمَرْءَ]{.ar} [EalmarEa]{.trn}|[ٱَلْمَرْأَةَ]{.ar} [EalmarEata]{.trn}
i-state       |[ٱَلْمَرْءِ]{.ar} [EalmarEi]{.trn}|[ٱَلْمَرْأَةِ]{.ar} [EalmarEati]{.trn}

The masculine noun
[ٱِمْرَأ]{.ar} [EimraE]{.trn}
has an additional irregularity.
When it is indefinite, it irregularly displays its state, not only on its final letter [ء]{.ar}, but also on the letter before it [ر]{.ar}. 

It is also permissible for it to behave regularly by displaying its state on its final letter only, but this is not as commonly used.

This table shows what we mean:

State         | Regular indefinite (less common) | Irregular indefinite (more common)
:-------------|:-----------------|:--------------
u-state       |[ٱِمْرَأٌ]{.ar} [EimraEun]{.trn} |[ٱِمْرُؤٌ]{.ar} [EimruEun]{.trn}
a-state       |[ٱِمْرَءًا]{.ar} [EimraEan]{.trn}|[ٱِمْرَءًا]{.ar} [EimraEan]{.trn}
i-state       |[ٱِمْرَأٍ]{.ar} [EimraEin]{.trn} |[ٱِمْرِئٍ]{.ar} [EimriEin]{.trn}

Here are some examples of these nouns:

