# Semantic aspects of the ;ism_fail;


## Ascribing the quality of being the ;faa3il; of a verb

(improper annexation should already have been discussed)

We have seen that, subject to certain conditions, the ;ism_fail; can behave like a verb. 
In that it can govern a ;faa3il; and a ;mafulb;.
In this section we will discuss
the shade of meaning that the ;ism_fail; conveys when it is used instead of a verb.

The primary meaning of the ;ism_fail; is that of the ;faa3il; of a verb. Here are some examples:

|;ism_fail;| meaning |
|--:|:----|
|[قَاتِل]{.ar} | one who kills/a killer |
|[ضَاحِك]{.ar} | one who laughs  |
|[قَائِل]{.ar} | one who says |
|[مُتَكَلِّم]{.ar} | one who speaks/a speaker |
|[كَاتِب]{.ar} | one who writes/a writer |

Using a verb primarily indicates the occurrence of an action.
For example:

(@) Jama3a zayd  
    Zayd gathered

(@) Yajma3u zaydun  
    Zayd gathers/ will gather.

In the examples above,
the verb jama3a signifies that the action of gathering occurred. 
And the verb yajma3u signifies that the action of gathering is occurring or will occur.

When we use the ism_fail jaami3 instead, its primary significance is to ascribe the quality of being a gatherer.
For example:

(@) al-Salatu jaami3atun likulli- al-naas [Lane]  
    "The prayer is a collector of all the people."

<!--
The ;ism_fail; jaami3 does not, by itself, imply the occurrence of a gathering event.
But such an occurrence may be understood from context.
For example:

al-Salaatu jaami3atun [bukhari:1045; muslim:901e]
"The prayer is gathering (imminently)."
-->

### Temporary vs permanent applicability of the ;ism_fail;

We have seen that the ism_fail’s primary significance is to ascribe the quality of being ;faa3il; of the verb,
rather than signifying the occurrence of the action of the verb.
In general, the permanence of this meaning (of one who does the action of the verb) can range from:

+ Temporary to only when the action of the verb occurs.
+ Permanent beyond the action of verb, such that the ism_fail indicates a permanent adjectival quality.

<!--
For example:
Zaydun SaaliHun
-->

Some ;ism_fail;s fall squarely into one or the other category.
For example, 
naa’im (from naama "to sleep") is an example of an ism_fail that is applicable to only when the action of the verb naama occurs. Someone won’t be described as naai’m after he has woken up.
On the other hand,
3aadil (from 3adala "to be just") is an example of an ism_fail with a more permanent meaning. Someone can be described as 3aadil even when he is not in the action of being just.

<!--
Sometimes, the same ism_fail can vary in how temporary or permanent this meaning is.
We saw an example of this with the ism_fail jaami3 in examples () and () above.
-->

The ;ism_fail; can also indicate a state so stable that it has acquired the status of a skill.^[marmor 127]
For example:

(@) Wa kaana 3umaru kaatiban.

When used as such, the ;ism_fail; loses some of its verbal force and becomes closer to a substantive.

We mentioned above that the primary significance of the ;ism_fail; is to ascribe the quality of being the one who does the action of the verb.
Because of this, the ;ism_fail; can be used to differentiate between one who truly does the action of a certain verb,
and someone who may have done the action but not sufficiently enough to earn the ism_fail as an epithet. [Surah al-kaafiroon, ibn al-qayyim]

On the flip side, one may have committed an act of disbelief or innovation, but may have done it out of ignorance or mistakenly. So, even if he is referred to as a kaafir or mubtadi3, then this will be only an incidental reference, i.e., limited to the incident of his action.
And it is possible that he won’t be referred to as such in general.

In a similar manner, someone who can generally be ascribed with an ism_fail, may lose that ascription due to the severity of another negating action. [hadith believer when he steals]

<!--
Stative vs dynamic verbs
When talking about the significance of the ism_fail we will talk about stative and dynamic verbs.
A stative verb is not associated with an event. It gives the meaning of being in a static state. For example, صلح to be honest عدل to be just

A dynamic verb is associated with an event. A dynamic event is one that is either momentary or one that implies a final goal or a point at which the event ends. 
-->

## Tenses of the ;ism_fail; not defined by [ٱل]{.ar}

In general, the u-state mudarie verb can be used in three situations:

  i. to indicate a future event. For example yaktubu zaydun ghadan. Zayd will write tomorrow. sa/sawfa can be used with with the mudarie for this meaning.
 ii. To express an on-going continuous action. Zaydun yaktubu l-aana, [kaana] zaydun yaktubu amsi. [sayakuunu] zaydun yaktubu ghadan. Zayd will be writing tomorrow.
iii. To express a habitual action. Yaktubu Zaydun kulla yawmin. Zayd writes every day.

In the examples above we used words like aana, ghadan to explicitly indicate the tense.
Without these words, all three meanings are still possible. So yaktubu zaydun can signify all three tenses. Context will be needed to tell us which meaning is meant.

When the ;ism_fail; (without al) is used instead of a mudarie verb, then it too, in general, can be used in the three positions above.
In all three situations,
the main difference in significance between using a mudarie verb and using its ism_fail is that the verb calls attention to the occurrence of an action,
whereas the ism_fail calls attention to the ;faa3il;’s being in a state that is brought about by the doing of the verb.

### The ;ism_fail; used to indicate a future event

Here are an example of the ;ism_fail; used to indicate a future event:

(@) [إني ذاهب إلى ربي سيهدين]{.ar}

(@) [فَهُوَ ذَاهِبٌ وَتَارِكُهُ لِلنَّاسِ]{.ar} muslim:2959a

(@) [إني ذاكر لك أمرا]{.ar} bukhari:1925

(@) [أنا فاعل]{.ar} tirmidhi:2433

(@) [جاعل في الأرض خليفة]{.ar}

(@) [زَعَمَ ابْنُ أُمِّي أَنَّهُ قَاتِلٌ رَجُلاً قَدْ أَجَرْتُهُ]{.ar}
    [@https://sunnah.com/bukhari:6158@]{.citex}  
    "My maternal brother claims that he will kill a man whom I have given protection to."

(@) [وَإِنِّي مُرْسِلَةٌ إِلَيْهِم بِهَدِيَّةٍ فَنَاظِرَةٌ بِمَ يَرْجِعُ ٱلْمُرْسَلُونَ]{.ar}
    [@https://quran.com/27/35@]{.citex}  
    "But indeed, I will send to them a gift and see with what [reply] the messengers will return."

If a ;mudarie; verb is used to indicate a future event,
then it merely signifies that the speaker thinks that the ;faa3il; will take an action.
For example, the mudarie verb in the utterance سأذهب merely signifies the speaker’s intention of going some time in the future.

In contrast, 
when the ;ism_fail; is used to indicate the future tense, then it signifies that,
in the estimation of the speaker, the event will definitely take place.
In other words, it signifies that the ;faa3il;’s action is so settled and resolved in the speaker’s mind that it is as if the ;faa3il; has already entered the state and can be described by the ism_fail.
So, for example, if the speaker says أنا ذاهب and the context tells us he is referring to a future action, then the use of the ism_fail ذاهب instead of the mudarie ver يذهب, signifies that the speaker is so sure that he will do this action that he can already be described by ذاهب "one who is in a state of going".

The use of the ism_fail instead of the mudarie verb to indicate a future event can also, depending on context, indicate that the event is imminent, i.e. that it is in the very near future.
In such cases it can be translated using "be going to".
For example:

(@) [فَقَالَ عُتْبَةُ:لَا شَيْءَ، أَنَا **خَارِجٌ**]{.ar} [marmor 171]

#### The ;ism_fail; used to express a hypothetical future event {.unnumbered}

The ;ism_fail; can also be used to express a hypothetical event.
Examples:

(@) [فَقَالَ عُمَرُ: ائْذَنْ لِي فِيهِ، قَالَ:" أَوَ كُنْتَ قَاتِلَهُ]{.ar} ahmad:5878

(@) [لو كنت قاتلا رسولا]{.ar}

(@) [لو كنت جاعلا لمشرك دية]{.ar}

#### The ;ism_fail; used to express entering into a future static state {.unnumbered}

The usage of the ;ism_fail; to indicate a future event is typically in the case of verbs that signify an event.
Some verbs are not associated with an event as much as they are associated with being in a (static) state. For example كان to be.
For such verbs the ;ism_fail; can express the entering into the state associated with the verb.
For example:

(@) [فإنه كائن لابن أخيك هذا شأن عظيم]{.ar} [kinberg 320 quoting youssef from ibn Hisham]  
    "Because there is going to be, for this son of your brother, a great importance"


### The ;ism_fail; used to indicate a concurrent state

In addition to expressing a future event, the ;ism_fail; is also used to express being in a static state that is concurrent to some past, present, or future reference point.
In contrast, the ;mudarie; verb indicates that the doer is doing a dynamic action.
Consider the following example:

(@) [كُنْتُ مُسَافِرًا فَأَتَيْتُ النَّبِيَّ صلى الله عليه وسلم وَهُوَ **يَأْكُلُ** وَأَنَا **صَائِمٌ**]{.ar}
    [@https://sunnah.com/nasai:2281@]{.citex}  
    "I was traveling and I came to the Prophet while he was eating and I was fasting."

The verb [يَأْكُلُ]{.ar} indicates a dynamic activity, where the ;faa3il; is actively eating.
Whereas the ;ism_fail; [صَائِم]{.ar} calls attention to the ;faa3il;'s being in a (static) state of fasting, and not to his actively doing the activity of fasting.

Here are some more examples of the the ;ism_fail; being used to indicate being in a static state:

(@) [مَنْ كَانَ مِنْكُمْ **مُلْتَمِسًا** لَيْلَةَ الْقَدْرِ فَلْيَلْتَمِسْهَا فِي الْعَشْرِ الْأَوَاخِرِ وِتْرًا]{.ar}
    [@https://sunnah.com/ahmad:298@]{.citex}  
    "Whoever amongst you is seeking the Night of Decree, then let him seek it in the last ten days of [#ramaDAn]{.trn2}, [in the] the odd [nights]."  
    (Note the the ;ism_fail; [مُلْتَمِسًا]{.ar} has a ;mafulb; [لَيْلَةَ الْقَدْرِ]{.ar}.)

(@) [لَمَّا كَانَ يَوْمَ أُحُدٍ انْهَزَمَ النَّاسُ عَنِ النَّبِيِّ صلى الله عليه وسلم وَأَبُو طَلْحَةَ بَيْنَ يَدَىِ النَّبِيِّ صلى الله عليه وسلم **مُجَوِّبٌ** عَلَيْهِ بِحَجَفَةٍ لَهُ]{.ar}
    [@https://sunnah.com/bukhari:4064@]{.citex}  
    "When it was the day of [#uHud]{.trn2}, the people left the Prophet ;pbuh; while [#abU #TalHah]{.trn2} was in front of the Prophet ;pbuh;, shielding him with a leather shield of his."

(@) [فَخَرَجَ النَّبِيُّ صلى الله عليه وسلم وَهُوَ **مُشْتَمِلٌ** عَلَى شَيْءٍ]{.ar}
    [@https://sunnah.com/tirmidhi:3769@]{.citex}  
    "So the Prophet ;pbuh; came out while he was wrapping over something [with his garment]."

(@) [وَإِذَا هُوَ **مُعْتَمِدٌ** عَلَى عَصًا فِي صَلاَتِهِ فَقُلْنَا بَعْدَ أَنْ سَلَّمْنَا . فَقَالَ حَدَّثَتْنِي أُمُّ قَيْسٍ بِنْتُ مِحْصَنٍ أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم لَمَّا أَسَنَّ وَحَمَلَ اللَّحْمَ اتَّخَذَ عَمُودًا فِي مُصَلاَّهُ **يَعْتَمِدُ** عَلَيْهِ]{.ar}
    [@https://sunnah.com/abudawud:948@]{.citex}  
    "And incidentally, he was resting on a staff in his prayer. We [asked] him (about resting on the staff) after we had given the salutation; He said: Umm Qays daughter of [#miHSan]{.trn2} said to me that when the Messenger of Allah ;pbuh; became aged and the flesh grew increasingly on him, he took a prop at his place of prayer and he would rest on it."  
    (Note how the ;ism_fail; [مُعْتَمِد]{.ar} indicates a state and the ;mudarie; verb [يَعْتَمِدُ]{.ar} indicates the activity."

(@) [اتَّبَعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم وَهُوَ **رَاكِبٌ**]{.ar}
    [@https://sunnah.com/nasai:953@]{.citex}  
    "I followed the Messenger of Allah ;pbuh; when he was riding"

(@) [إِنَّهُ كَانَ يُصَلِّي وَهُوَ **مُسْبِلٌ** إِزَارَهُ]{.ar}
    [@https://sunnah.com/abudawud:638@, graded weak by [al-E#albAni]{trn2}]{.citex}  
    "Indeed he was praying while trailing his lower garment."

(@) [وَوَقَفْتُ عِنْدَ بَابِ عَائِشَةَ فَإِذَا هُوَ **مُسْتَقْبِلٌ** الْمَغْرِبَ]{.ar}
    [@https://sunnah.com/adab:451@]{.citex}  
    "And I stopped at the door of [#eAEicah]{.trn2} and incidentally, it was facing the west."

Even when the ;ism_fail; is derived from a verb that is associated with a dynamic activity,
the ;ism_fail; is used (instead of the ;mudarie; verb) when the speaker (or writer) wishes to signify the ;faa3il;'s being in a state of doing the activity.
Instead, the ;mudarie; verb is used when the ;faa3il;'s actively doing the activity is highlighted.
For example:

(@) [فَلَبِثَ الْأَوْسُ وَالْخَزْرَجُ **مُتَحَارِبِينَ** عِشْرِينَ سَنَةً فِي أَمْرِ سُمَيْرٍ]{.ar}
    [marmor 134]{.citex}  
    "So [al-E#aws]{.trn2} and [al-#xazraj]{.trn2} kept fighting for twenty years because of the matter of Sumayr."

(@) [فَمَا الَّذِي أَنْتَ فِيهِ الْآنَ مُجْمِعٌ]{.ar}
    [marmor 99A]{.citex}  
    "So what is it that you are now decided about now?"

When the ;ism_fail;, is used to signify being in a state,
it will sometimes not take a ;mafulb;, even if the ;ism_fail; is derived from a transitive verb,
A ;mudarie; verb can then follow the ;ism_fail; with the ;mafulb; if needed.
For example:

(@) [فَخَرَجْنَا **خَائِفِينَ** **نَخَافُ** الرَّصَدَ]{.ar}
    [maghazi 28 in marmor 138]{.citex}  
    "So we set out afraid, fearing ambush."


(@3amal_ism_fail_3aamilun_ya3mal) [وَرُزَيْقٌ **عَامِلٌ** عَلَى أَرْضٍ **يَعْمَلُهَا**]{.ar}
    [@https://sunnah.com/bukhari:893@]{.citex}  
    "Ruzayq was (in a state of) working on the land, working (i.e. farming) it."  

<!--
Note how, in example\ (@3amal_ism_fail_3aamilun_ya3mal) above,
the ;ism_fail; [عَامِل]{.ar} is used without a ;mafulb;, indicating being in a state of working.
Whereas the ;mudarie; verb [يَعْمَلُ]{.ar} is used with the ;mafulb; to indicate doing the work.
-->

### The ;ism_fail; combined with [كَانَ]{.ar}

The ;ism_fail; can be combined with [كَانَ]{.ar}
to express a past-continuous or past-habitual action
just like the ;mudarie; verb
(see section\ (ref)).
The difference in meaning between using the ;mudarie; verb and using the ;ism_fail; is that,
as usual, the ;ism_fail; signifies a static state, whereas the ;mudarie; verb signifies the activity.
Here are some examples:

[marmor]

...

And similar to the ;mudarie; verb,
[كَانَ]{.ar}
can be ommitted if context indicates that the action occurred in the past.
For example:

(@) [**وَنُقَلِّبُهُمْ** ذَاتَ ٱلْيَمِينِ وَذَاتَ ٱلشِّمَالِ ۖ وَكَلْبُهُم **بَاسِطٌ** ذِرَاعَيْهِ بِٱلْوَصِيدِ]{.ar}
    [@https://quran.com/18:18@]{.citex}  
    "And We turned them to the right and to the left, while their dog stretched his forelegs at the entrance."

(@) [إِنِّي **لَجَالِسٌ** مَعَ عَبْدِ اللَّهِ وَأَبِي مُوسَى وَهُمَا يَتَحَدَّثَانِ]{.ar}
    [@https://sunnah.com/muslim:2672d@]{.citex}  
    "I [was] sitting with [#eabd #allAh]{.trn2} and [#abU #mUsA]{.trn2} while they were conversing."

### Motion and posture verbs

For some verbs only the ;ism_fail; is used to indicate a continuous on-going activity.
And the ;mudarie; verb is used to express a habitual activity.
This distinction is most prominent for verbs that have to do with motion and posture, like
[ذَهَبَ]{.ar} "to go",
[جَلَسَ]{.ar} "to sit",
[نَامَ]{.ar} "to sleep",
etc.

So, for example,
[يَنَامُ]{.ar} would be used to express "he sleeps".
And [هُوَ نَائِمٌ]{.ar} would be used to express "he is sleeping."
Here are examples contrasting the ;ism_fail; and the ;mudarie; verb:

(@) [ قُلْنَا لِعَمْرٍو إِنَّ نَاسًا يَقُولُونَ إِنَّ النَّبِيَّ صلى الله عليه وسلم **تَنَامُ** عَيْنُهُ وَلاَ **يَنَامُ** قَلْبُهُ]{.ar}
    [@https://sunnah.com/bukhari:859@]{.citex}  
    "We said to [#eamr]{.trn2}: 'Indeed some people say that the Prophet ;pbuh; his eye sleeps but his heart does not sleep.'"

(@) [جَاءَتْ مَلاَئِكَةٌ إِلَى النَّبِيِّ صلى الله عليه وسلم وَهْوَ **نَائِمٌ** فَقَالَ بَعْضُهُمْ إِنَّهُ **نَائِمٌ** وَقَالَ بَعْضُهُمْ إِنَّ الْعَيْنَ **نَائِمَةٌ** وَالْقَلْبَ يَقْظَانُ]{.ar}
    [@https://sunnah.com/bukhari:7281@]{.citex}  
    Some angels came to the Prophet ;pbuh; while he was sleeping. Some of them said, "He is sleeping." Some [others] of them said, "His eye[s] are sleeping but his heart is awake."

(@) [تِلْكَ صَلاَةُ الْمُنَافِقِ **يَجْلِسُ** يَرْقُبُ الشَّمْسَ حَتَّى إِذَا كَانَتْ بَيْنَ قَرْنَىِ الشَّيْطَانِ قَامَ فَنَقَرَ أَرْبَعًا لاَ يَذْكُرُ اللَّهَ فِيهَا إِلاَّ قَلِيلاً]{.ar}
    [@https://sunnah.com/tirmidhi:160@]{.citex}  
    That is the prayer of the hypocrite. He sits watching the sun, until when it is between the horns of the devil he stands and pecks out four (units of prayer), not remembering Allah in them but a little."

(@) [كُنْتُ جَالِسًا عِنْدَ مُعَاوِيَةَ، فَحَدَّثَ نَفْسَهُ ثُمَّ انْتَبَهَ]{.ar}
    [@https://sunnah.com/adab:564@]{.citex}  
    "I was sitting with [#mueAwiyah]{.trn2} when he [muttered to] himself, then he came to his senses."
<!--
(@) [كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم جَالِسًا وَرَجُلٌ يَأْكُلُ

(@) [عَنْ أَنَسٍ، أَنَّهُ كَانَ مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم جَالِسًا وَرَجُلٌ يُصَلِّي]{.ar}
Anas [narrated] that he was with 

(@) [شَهِدْنَا بِنْتَ رَسُولِ اللَّهِ صلى الله عليه وسلم وَرَسُولُ اللَّهِ صلى الله عليه وسلم **جَالِسٌ** عَلَى الْقَبْرِ، فَرَأَيْتُ عَيْنَيْهِ تَدْمَعَانِ]{.ar}
    [@https://sunnah.com/bukhari:1342@]{.citex}  
    We witnessed the [funeral] of the daughter of the Prophet ;pbuh; while the Propher ;pbuh; was sitting at the grave. I then saw his eyes tearful.
-->


Here are some more examples of ;ism_fail;s of verbs of motion and posture being used to indicate a continuous on-going action:

(@) [رَأَيْتُ النَّبِيَّ صلى الله عليه وسلم **مُقْعِيًا** يَأْكُلُ تَمْرًا]{.ar}
    [@https://sunnah.com/muslim:2044a@]{.citex}  
    "I saw the Prophet ;pbuh; squatting, eating dates."

(@) [وَقَدْ كُنْتُ مُسْنِدَتَهُ إِلَى صَدْرِي]{.ar}
    [@https://sunnah.com/bukhari:2741@]{.citex}  
    "I had been leaning him against my chest."

(@) [كُنْتُ مُسْنِدَةً النَّبِيَّ صلى الله عليه وسلم، إِلَى صَدْرِي]{.ar}
    [@https://sunnah.com/shamail:387@]{.citex}  
    "I was leaning the Prophet ;pbuh; against my chest."

(@) [قَالَ كُنْتُ مُتَّكِئًا عِنْدَ عَائِشَةَ]{.ar}
    [@https://sunnah.com/muslim:177a@]{.citex}  
    "I was resting at [the house of] [#eAEicah]{.trn2}"

(@) [لاَ أُلْفِيَنَّ أَحَدَكُمْ مُتَّكِئًا عَلَى أَرِيكَتِهِ ...]{.ar}
    [@https://sunnah.com/abudawud:4605@]{.citex}  
    "Let me not find one of you reclining on his couch ..."

(@) [أَنَّ أَبَا بَكْرٍ رَضِيَ اللَّهُ عَنْهُ اسْتَأْذَنَ عَلَى رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ لَابِسٌ مِرْطَ عَائِشَةَ]{.ar}
    [@https://sunnah.com/ahmad:514@]{.citex}  
    "that [#abU]{.trn2} Bakr asked for permission to enter upon the Messenger of Allah ;pbuh; when he was lying down on his bed, wearing the cover of [#eAEicah]{.trn2}."

This distinction between the habitual and continuous tense
is generally true for verbs of motion and posture.
But sometimes we can see the ;mudarie; verb used for a continuous meaning.
This can happen especially when the mudarie verb is limited to a specific time.
For example, the ;mudarie; verb is in a ;hal;:

(@) [عَنِ ابْنِ عُمَرَ، أَنَّهُ رَأَى رَجُلاً **يَتَّكِئُ** عَلَى يَدِهِ الْيُسْرَى]{.ar}
    [@https://sunnah.com/abudawud:994@]{.citex}  
    "[It was narrated] on the authority of Ibn [#umar]{.trn2} that he saw a man reclining on his left hand"

(@) [ رَأَيْتُ عُمَرَ بْنَ الْخَطَّابِ وَهُوَ **يَجْلِسُ** وَالنَّاسُ مَعَهُ]{.ar}
    [tarikh tabari 3/429]

Note, also that even though
the ;mudarie; and the ;ism_fail; of verbs of posture and motion are differentiated for habitual and continuous tenses,
they can both still be used to indicate a future event.
We have already seen an example of the ;ism_fail; [ذَاهِب]{.ar} used to indicate an future tense in example () above.

### Perfective

(@) [قَالَ جَابِرٌ فَبَيْنَا أَنَا نَازِلٌ تَحْتَ شَجَرَةٍ إِذَا رَسُولُ اللَّهِ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/malik/48/1@]{.citex}
    "While I was [resting] dismounted under a tree, the Messenger of Allah ;pbuh; [came]."

    ضائع
    طالق

### Not used for verbs of perception

### ;ism_fail; and ;mudarie; verb used equivalently

In the preceding discussion we have attempted to show the difference in meaning between
when a ;mudarie; verb is used and when its ;ism_fail; is used instead.
In closing,
we will also mention that the differences we have listed are often a general trend, and not a fixed rule.
Sometimes, we find ;mudarie; verbs and their ;ism_fail;s used equivalently.
Here are some examples:

### Negating the ;ism_fail;

## DELETE:

We said above that the ism_fail calls attention to the ;faa3il;’s being in a state that is brought about by doing the action of the verb.


The type of action of a verb can range from a _dynamic event_ to a static state.
//The ism_fail of a verb can refer to either a dynamic event or a static state.
A dynamic event is one that is either momentary or one that implies a final goal or a point at which the event ends. [kinberg: semi-imperfectives and imperfectives 320].
For example,
xalaqa refers to an event of creating.
ja3ala refers to an event of making
The verbs and ism_fails associated with a dynamic event are also called bounded because the dynamic event bounds or limits the beginning or end of state associated with the verbs ism_fail.

Like the mudarie verb, the ism_fail not defined by al, when used with verbal force, can have two main significations:

An imminent future action
A static state that is concurrent to some point of reference

We will discuss each of these in detail below.

Future:
An dyevent
A state
A
Mudarie can have modal nuances
Can’t say innii 3aadil for future because unbounded

Static state:
Mudarie is dynamic


## NOTES:

Add istimraar. See kinberg iterative and za3balawi https://shamela.ws/book/2120/482

When Ism_fail signifies being in an on-going state. (as opposed to imminent future):
Even when lexeme is dynamic, ism_fail forces a static meaning.
عامل in a state of working
If ism_fail on it’s own sufficiently signifies the state then it often does not to have a mafulb. A following mudari verb is commonly brought for the mafulb.

Bukhari 893 ورزيق عامل على الأرض يعملها
Marmor 137 فخرجنا خاءفين نخاف الرصد

But if the ism_fail requires an object to complete the meaning, then it may occur as a doee to the ism_fail:
Wa huwa muDTaji3un 3alaa firaashihi laabisun mirTa 3aaishata
Wa huwa muntaZirun wilaadahaa 



SECTION

The active participle can an imply action embarked upon, whose effects are still apparent [owens: The participle]
Punctual: jalasa, labisa, waqafa, ittafaqa
Durative; mashaa, qaama, tazaayada


قالوا إنا لضالون kinberg

With motion verbs, the ism_fail indicates the situation of being in a move, rather than actual kinesis or progression [marmor 127]
Marmor 7.4 qaaSidun naHwahu

The ism_fail can continue to signify being in a state even when the action was an event has been completed.

جيء بالنعمان شاربا



Active participle (with verbal force) not used commonly for some verbs:
Yuriidu, yarju

Objective pronoun is not used in accsative with ism_fail [van putten]

Improper accusation to the faa3il: https://shamela.ws/book/11825/868#p1 [footnote]

## Introduction

The primary meaning of the ;ism_fail; is that of the ;faa3il; of a verb. Here are some examples:

|;ism_fail;| meaning |
|--:|:----|
|[قَاتِل]{.ar} | one who kills/a killer |
|[ضَاحِك]{.ar} | one who laughs  |
|[قَائِل]{.ar} | one who says |
|[مُتَكَلِّم]{.ar} | one who speaks/a speaker |
|[كَاتِب]{.ar} | one who writes/a writer |

The ;ism_fail; can also be used in place of a verb.
What we mean by this is that the ;ism_fail; can be used in a sentence where we would expect a verb to occur.

For example, 
consider the following sentence:

(@) [زَيْدٌ يَسِيرُ إِلَىٰ مَكَّةَ]{.ar}  
    _[#zayd]{.trn2} travels to [#makkah]{.trn2}_

Instead of using the verb
[يَسِيرُ]{.ar}
we can use its ;ism_fail; 
[سَائِر]{.ar}
instead, and say:

(@) [زَيْدٌ سَائِرٌ إِلَىٰ مَكَّةَ]{.ar}

However, using the ;ism_fail; instead of the verb can, in many cases, affect the nuance or shade of meaning that the sentence would signify.
In this chapter we will study these semantic (aspects) of using a ;mushtaqq; noun in place of a verb.
We will start with and focus on the ;ism_fail;, ;ia;.
Using that as a basis, we will also discuss other ;mushtaqq; nouns like the ;ism_maful; and the ;sifah_mush;.

What will come into play as well is when the ;mushtaqq; noun can or cannot govern a ;mafulb;.
We discussed the conditions of this government in chapter\ (ref).

<!--
We would also like to make a distinction here.
In section\ (ref) of chapter\ (ref) we also discussed how the ;ism_fail;,
when it is defined by [ٱلْ]{.ar}, can govern a ;mafulb; unconditionally.
But this won't be the subject of our discussion in this chapter.
This is because when the ;ism_fail; is defined by [ٱلْ]{.ar},
and is used verbally,
then it desn't exactly replace a verb.
Rather it corresponds with an ;ism_mawsul; followed by a verb.
For example,
the definite ;ism_fail;
[الْقَاتِلُ]{.ar} 
won't be used directly in place the verb [قَتَلَ]{.ar} or [يَقْتُلُ]{.ar}.
Instead, it corresponds to [الَّذي قَتَلَ/يَقْتُلُ]{.ar}.
-->

## The verbal meanings of the ;ism_fail;

## Introduction

The verb essentially signifies the occurrence of an action.
Consider the following example:

(@) [يَتَّبِعُ زَيْدٌ عَمْرًا]{.ar}

The ;mudarie; verb 
[يَتَّبِعُ]{.ar}
signifies that,
depending on the tense indicated by the context:

  i. _Zayd is following [#eamr]{.trn2}_. (Present continuous tense)
 ii. _Zayd was following [#eamr]{.trn2}_. (Past continuous tense. Typically as [كَانَ يَتَّبِعُ]{.ar} but remember from section\ (ref) that [كَانَ]{.ar} can be omitted with the ;mudarie; verb if the context indicates a past tense.)
iii. _Zayd follows [#eamr]{.trn2}_. (Present habitual tense)
 iv. _Zayd used to follow [#eamr]{.trn2}_. (Past habitual tense. Again, typically as [كَانَ يَتَّبِعُ]{.ar}.)
  v. _Zayd will follow [#eamr]{.trn2}_. (Future tense)

Similarly if we say:

(@) [اتَّبَعَ زَيْدٌ عَمْرًا]{.ar}  
    _Zayd followed [#eamr]{.trn2}_.

then the ;madi; verb 
[اتَّبَعَ]{.ar}
signifies the past tense.

In contrast to the verb,
the ;ism_fail; 
[مُتَّبِع]{.ar}, 
essentially signifies that its ;faa3il; can be called a "follower".
For example, if we say:

(@meaning_ism_fail_zayd_follower_3amr_idafa) [زَيْدٌ مُتَّبِعُ عَمْرٍو]{.ar}

Then the ;ism_fail; 
[مُتَّبِع]{.ar}
signifies that
_Zayd is, was, or will be, [#eamr]{.trn2}'s follower_.

In example (@meaning_ism_fail_zayd_follower_3amr_idafa)
the ;ism_fail;
[مُتَّبِع]{.ar}
can be used with verbal force.
What we mean by _verbal force_ is that the ;ism_fail;,
while being a noun,
can also signify some aspects of meaning that are typically supplied by the verb.
These aspects are:

 i. the occurence of the action of verb,
ii. and its tense.

So the ;ism_fail;
[مُتَّبِع]{.ar},
while essentially meaning "follower",
can also supply the meaning of the occurrence of an action of "following".
As for the tense of when the following occurred,
the ;ism_fail; does not carry tense _per se_.
But the tense of its verbal meaning can be determined from context, the syntax of ;ism_fail;, and the lexical meaning of its root verb.

Depending on the tense,
the ;idaafah; 
[مُتَّبِعُ عَمْرٍو]{.ar}
in example (@meaning_ism_fail_zayd_follower_3amr_idafa) above may be either a ;ma3nawi; or ;lafzi; ;idaafah;.
(See section\ (ref).)
If the context indicates a past tense,
then it is a ;ma3nawi; ;idaafah;.

But if the context indicates that
the tense is future, continuous, or habitual,
then the ;idaafah; can be ;lafzi;, and
[عَمْرٍ]{.ar}
is then in the position of a ;mafulb;.
In this case,
the sentence can also be expressed as:

(@meaning_ism_fail_zayd_follower_3amr_mafulb) [زَيْدٌ مُتَّبِعٌ عَمْرًا]{.ar}

Here is an example from actual usage:

(@ism_fail_nasai_3498) [وَأَنَا **مُتَّبِعٌ** فِي ذَلِكَ قَضَاءَ رَسُولِ اللَّهِ صلى الله عليه وسلم فِي مَرْيَمَ الْمَغَالِيَّةِ]{.ar}
    [@https://sunnah.com/nasai:3498@]{.citex}  

In example (@ism_fail_nasai_3498) above,
context tells us that the tense of the verbal meaning in the ;ism_fail;
[مُتَّبِع]{.ar}
is the present tense.
When translating this sentence,
we have something  of a dilemma.
If we translate the ;ism_fail;
[مُتَّبِع]{.ar}
as "follower", then we will say:

(@) _I am **a follower**, in that [matter], **of** the ruling of the Messenger of [#allAh]{.trn2} ;pbuh; concerning Maryam al-[#magAliyyah]{.trn2}_.

But now we will lose the tense of the
verbal meaning included in
[مُتَّبِع]{.ar}.
If, on the other hand, we translate
[مُتَّبِع]{.ar}
with the verb "following", then we get:

(@) _I **am following**, in that [matter], the ruling of the Messenger of [#allAh]{.trn2} ;pbuh; concerning Maryam al-[#magAliyyah]{.trn2}_

Now we can lose the essential significance of the ;ism_fail; which is that of the noun "follower".

Many times, the verbal meaning is prioritized for the translation and so the ;ism_fail;,
when used with verbal force, is often translated as a verb.
But we should understand that this is a limitation of translation to English, and that the original Arabic, in general, has aspects of meaning of both a noun and a verb.

Also, the verbal force that an ;ism_fail; carries can vary on a sliding scale.
Sometimes, the ;ism_fail;'s essential ;faa3il; meaning is more dominant.
For example:

(@) [لَعَنَ اللَّهُ الْخَمْرَ **وَشَارِبَهَا وَسَاقِيَهَا وَبَائِعَهَا** وَمُبْتَاعَهَا **وَعَاصِرَهَا وَمُعْتَصِرَهَا وَحَامِلَهَا** وَالْمَحْمُولَةَ إِلَيْهِ]{.ar}
    [@https://sunnah.com/abudawud:3674@]{.ar}  
    Allah has cursed wine, **its drinker, its server, its seller**, its buyer, **its presser, the one for whom it is pressed, the one who conveys it**, and the one to whom it is conveyed.

And sometimes its verbal (tense) meaning is more dominant.
For example:

(@) [جَاءَتْ مَلاَئِكَةٌ إِلَى النَّبِيِّ صلى الله عليه وسلم وَهْوَ **نَائِمٌ** فَقَالَ بَعْضُهُمْ إِنَّهُ **نَائِمٌ** وَقَالَ بَعْضُهُمْ إِنَّ الْعَيْنَ **نَائِمَةٌ** وَالْقَلْبَ يَقْظَانُ]{.ar}
    [@https://sunnah.com/bukhari:7281@]{.citex}  
    [Some] angels came to the Prophet ;pbuh; while he **was sleeping**. Some of them said, "He is **sleeping.**" Some [others] of them said, "The eye **is sleeping** but the heart is awake."

In the next few sections we will look at more examples of ;ism_fail;s in real-world usage and examine the verbal meanings that the ;ism_fail; signifies.

## The ;ism_fail; used to indicate a static state

One of the more common usages of the ;ism_fail; is to indicate that the ;faa3il; is in a static state.
The term _static state_ here signifies the ;faa3il;'s remaining in a condition or position.

<!--
The word "static" here signifies that the state of the ;faa3il; 
is steady and relatively unchanging.
-->

The ;ism_fail; indicates being in a state from a semantic aspect.
And we have already studied that the ;hal; syntactically indicates being in a state.
These two (semantic and syntactic) aspects of indicating being in a state are often combined.
So, we will see from the examples in this section that
the ;ism_fail; is often (but not always) either a ;hal;, or part of a ;hal; sentence.

As we discuss the state indicated by an ;ism_fail; we will often deal with _stative_ verbs.
_Stative_ verbs are those which mean to be in a state.
For example:
[جَلَسَ]{.ar} to sit,
[قَامَ]{.ar} to stand,
[نَامَ]{.ar} to sleep,
[لَبِسَ]{.ar} to wear,
etc.
These verbs often mean both: to do an action of entering into a state, and also to remain in such a state.
For example,
[جَلَسَ]{.ar} can mean both: to enter into a seated state (from another position like standing, etc.), and also to remain in a seated state.
Similarly,
[لَبِسَ]{.ar} can mean both: to put on a garment, and also to be in a state of having put on the garment.

In contrast to the ;ism_fail;, the ;mudarie; verb indicates that the doer is doing a dynamic action.
Consider the following example:

(@) [كُنْتُ مُسَافِرًا فَأَتَيْتُ النَّبِيَّ صلى الله عليه وسلم وَهُوَ **يَأْكُلُ** وَأَنَا **صَائِمٌ**]{.ar}
    [@https://sunnah.com/nasai:2281@]{.citex}  
    "I was traveling and I came to the Prophet while he was **eating** and I was **fasting**."

The verb [يَأْكُلُ]{.ar} indicates a dynamic activity, where the ;faa3il; is actively eating.
Whereas the ;ism_fail; [صَائِم]{.ar} calls attention to the ;faa3il;'s being in a (static) state of fasting, and not to his actively doing the activity of fasting.

Even when a verb that is associated with a dynamic activity,
its ;ism_fail; can be used instead of the verb when the 
purpose is to indicate the ;faa3il;'s _being in a state_ of doing the activity,
rather than to indicate the dynamic activity of the verb.
For example:

(@) [فَلَبِثَ الْأَوْسُ وَالْخَزْرَجُ **مُتَحَارِبِينَ** عِشْرِينَ سَنَةً فِي أَمْرِ سُمَيْرٍ]{.ar}
    [marmor 134]{.citex}  
    "So [al-E#aws]{.trn2} and [al-#xazraj]{.trn2} stayed **(in a state of) fighting each other** for twenty years because of the matter of Sumayr."

(@) [فَمَا الَّذِي أَنْتَ فِيهِ الْآنَ **مُجْمِعٌ**]{.ar}
    [marmor 99A]{.citex}  
    "So what is it that you are now (in a state of being) **decided** about?

Here are some more examples of the the ;ism_fail; being used to indicate being in a static state:

(@) [لَمَّا كَانَ يَوْمَ أُحُدٍ انْهَزَمَ النَّاسُ عَنِ النَّبِيِّ صلى الله عليه وسلم وَأَبُو طَلْحَةَ بَيْنَ يَدَىِ النَّبِيِّ صلى الله عليه وسلم **مُجَوِّبٌ** عَلَيْهِ بِحَجَفَةٍ لَهُ]{.ar}
    [@https://sunnah.com/bukhari:4064@]{.citex}  
    "When it was the day of [#uHud]{.trn2}, the people left the Prophet ;pbuh; while [#abU #TalHah]{.trn2} was in front of the Prophet ;pbuh;, **shielding** him with a leather shield of his."

(@) [فَخَرَجَ النَّبِيُّ صلى الله عليه وسلم وَهُوَ **مُشْتَمِلٌ** عَلَى شَيْءٍ]{.ar}
    [@https://sunnah.com/tirmidhi:3769@]{.citex}  
    "So the Prophet ;pbuh; came out while he was **(in a state of) covering** something [with his garment]."

(@) [وَإِذَا هُوَ **مُعْتَمِدٌ** عَلَى عَصًا فِي صَلاَتِهِ فَقُلْنَا بَعْدَ أَنْ سَلَّمْنَا . فَقَالَ حَدَّثَتْنِي أُمُّ قَيْسٍ بِنْتُ مِحْصَنٍ أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم لَمَّا أَسَنَّ وَحَمَلَ اللَّحْمَ اتَّخَذَ عَمُودًا فِي مُصَلاَّهُ **يَعْتَمِدُ** عَلَيْهِ]{.ar}
    [@https://sunnah.com/abudawud:948@]{.citex}  
    "And incidentally, he was **resting** on a staff in his prayer. We [asked] him (about resting on the staff) after we had given the salutation; He said: Umm Qays daughter of [#miHSan]{.trn2} said to me that when the Messenger of Allah ;pbuh; became aged and the flesh grew increasingly on him, he took a prop at his place of prayer and he **would rest** on it."  
    (Note how the ;ism_fail; [مُعْتَمِد]{.ar} indicates a state and the ;mudarie; verb [يَعْتَمِدُ]{.ar} indicates the activity."

(@) [فَبَيْنَا أَنَا **نَازِلٌ** تَحْتَ شَجَرَةٍ إِذَا رَسُولُ اللَّهِ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/malik/48/1@]{.citex}  
    While I was **in a dismounted state** under a tree, the Messenger of Allah [came]

(@) [إِذَا مَرِضَ الْعَبْدُ أَوْ سَافَرَ، كُتِبَ لَهُ مِثْلُ مَا كَانَ يَعْمَلُ **مُقِيمًا** صَحِيحًا]{.ar}
    [@https://sunnah.com/bukhari/56@]{.citex}  
    When a slave journeys or falls ill, a [similar reward] is written for him as what he used to do while **staying** (i.e. not journeying) [and] healthy.

### The ;mafulb; of the ;ism_fail; when indicating a static state

When the ;ism_fail; is dervied from a transitive verb,
then the ;ism_fail;,
when indicating a static state,
may take a ;mafulb;
(as long as it satisifes the conditions specified in section\ (ref)).
For example:

(@) [مَنْ كَانَ مِنْكُمْ **مُلْتَمِسًا لَيْلَةَ** الْقَدْرِ فَلْيَلْتَمِسْهَا فِي الْعَشْرِ الْأَوَاخِرِ وِتْرًا]{.ar}
    [@https://sunnah.com/ahmad:298@]{.citex}  
    "Whoever amongst you is **seeking** the Night of Decree, then let him seek it in the last ten days of [#ramaDAn]{.trn2}, [in the] the odd [nights]."  
    (Note the the ;ism_fail; [مُلْتَمِسًا]{.ar} has a ;mafulb; [لَيْلَةَ الْقَدْرِ]{.ar}.)

(@) [إِنَّهُ كَانَ يُصَلِّي وَهُوَ **مُسْبِلٌ إِزَارَهُ**]{.ar}
    [@https://sunnah.com/abudawud:638@, graded weak by [al-E#albAni]{.trn2}]{.citex}  
    "Indeed he was praying while **trailing** his lower garment."

(@) [وَوَقَفْتُ عِنْدَ بَابِ عَائِشَةَ فَإِذَا هُوَ **مُسْتَقْبِلٌ الْمَغْرِبَ**]{.ar}
    [@https://sunnah.com/adab:451@]{.citex}  
    "And I stopped at the door of [#eAEicah]{.trn2} and incidentally, it was facing the west."

(@) [كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم **حَامِلَ الْحَسَنِ** بْنِ عَلِيٍّ عَلَى عَاتِقِهِ]{.ar}
    [@https://sunnah.com/tirmidhi:3784@]{.citex}  
    "The Messenger of Allah ;pbuh; was carrying [al-#Hasan ibn #ealiyy]{.trn2} on his shoulder"  
    ([حَامِلَ الْحَسَنِ]{.ar} is a ;lafzi; ;idaafah;.)

(@) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم كَانَ يُصَلِّي وَهُوَ **حَامِلٌ أُمَامَةَ**]{.ar}
    [@https://sunnah.com/nasai:1204@]{.citex}  
    "that the Messenger of Allah used to pray while he [was] **carrying** [#umAmah]{.trn2}"

(@ism_fail_wearing_bedsheet) [أَنَّ أَبَا بَكْرٍ اسْتَأْذَنَ عَلَى رَسُولِ اللَّهِ صلى الله عليه وسلم وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ **لاَبِسٌ مِرْطَ** عَائِشَةَ]{.ar}
    [@https://sunnah.com/muslim:2402a@]{.citex}  
    "that [#abU #bakr]{.trn2} sought permission from the Messenger of Allah ;pbuh; [for entrance in his apartment] while he was lying on his bed having on him [#eAEicah]{.trn2}'s bed-sheet."

However, when the main intent is to indicate the state of the ;faa3il;
independent of the action of the ;faa3il; upon any ;maful;,
then the ;ism_fail; can occur without a ;mafulb;.
For example:

(@) [قَالَ عُثْمَانُ أَجَلْ وَلَكِنَّا كُنَّا **خَائِفِينَ**]{.ar}
    [@https://sunnah.com/ahmad:431@]{.citex}  
    [#euvman]{.trn2} said, "Yes, but we were in a state of fear."

In such cases,
the ;ism_fail; can be followed with a verb (typically its own), specifying the ;mafulb;.
For example:

(@) [فَخَرَجْنَا **خَائِفِينَ** **نَخَافُ الرَّصَدَ**]{.ar}
    [maghazi 28 in marmor 138]{.citex}  
    "So we set out afraid, fearing ambush."


(@3amal_ism_fail_3aamilun_ya3mal) [وَرُزَيْقٌ **عَامِلٌ** عَلَى أَرْضٍ **يَعْمَلُهَا**]{.ar}
    [@https://sunnah.com/bukhari:893@]{.citex}  
    "Ruzayq was (in a state of) working on the land, working (i.e. farming) it."  

### The ;ism_fail; indicating a habitual state

The static state that is indicated by the ;ism_fail; often tends to be continuous rather than habitual.
But the ;ism_fail; can also indicate a habitual state.
For example:

(@) [عَنِ النَّبِيِّ ﷺ أَنَّهُ قَالَ لَا يَدْخُلُ الْجَنَّةَ مَنَّانٌ وَلَا **عَاقٌّ وَالِدَيْهِ** وَلَا مُدْمِنُ خَمْرٍ]{.ar}
    [https://hadithunlocked.com/ahmad:6882]{.citex}  
    [It was narrated] from the Prophet ;pbuh; that he said: "One who reminds people (of what he has given them) will not enter Paradise, nor will **one who disobeys** his parents, nor one addicted to wine."

### The ;ism_fail; for verbs of posture

Verbs of posture inlude:
[جَلَسَ]{.ar} to sit,
[قَامَ]{.ar} to stand,
[اضْطَجَعَ]{.ar} to lie down,
etc.

With such verbs,
the ;mudarie; verb tends to be used only for the habitual tense and not for the continuous tense.
So if we say
[يَجْلِسُ زَيْدٌ]{.ar}
then it will usually mean _Zayd sits_ and not _Zayd is sitting_.

For the continuous tense,
only
the ;ism_fail; tends to be used.
So, in order to say _Zayd is sitting_ we will usually say
[زَيْدٌ جَالِسٌ]{.ar}.

Here are some examples of the ;ism_fail; and ;mudarie; verb for verbs of posture:

#### The ;ism_fail; for verbs of posture indicating the continuous tense {.unnumbered}

(@) [رَأَيْتُ النَّبِيَّ صلى الله عليه وسلم **مُقْعِيًا** يَأْكُلُ تَمْرًا]{.ar}
    [@https://sunnah.com/muslim:2044a@]{.citex}  
    "I saw the Prophet ;pbuh; squatting, eating dates."

(@) [قَالَ كُنْتُ مُتَّكِئًا عِنْدَ عَائِشَةَ]{.ar}
    [@https://sunnah.com/muslim:177a@]{.citex}  
    "I was resting at [the house of] [#eAEicah]{.trn2}"

(@) [لاَ أُلْفِيَنَّ أَحَدَكُمْ مُتَّكِئًا عَلَى أَرِيكَتِهِ ...]{.ar}
    [@https://sunnah.com/abudawud:4605@]{.citex}  
    "Let me not find one of you reclining on his couch ..."

(@) [أَنَّ أَبَا بَكْرٍ رَضِيَ اللَّهُ عَنْهُ اسْتَأْذَنَ عَلَى رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَهُوَ **مُضْطَجِعٌ** عَلَى فِرَاشِهِ لَابِسٌ مِرْطَ عَائِشَةَ]{.ar}
    [@https://sunnah.com/ahmad:514@]{.citex}  
    "that [#abU #bakr]{.trn2} sought permission from the Messenger of Allah ;pbuh; [for entrance in his apartment] while he was **lying** on his bed having on him [#eAEicah]{.trn2}'s bed-sheet."

(@) [كُنْتُ جَالِسًا عِنْدَ مُعَاوِيَةَ، فَحَدَّثَ نَفْسَهُ ثُمَّ انْتَبَهَ]{.ar}
    [@https://sunnah.com/adab:564@]{.citex}  
    "I was sitting with [#mueAwiyah]{.trn2} when he [muttered to] himself, then he came to his senses."

#### The ;mudarie; verb for for verbs of posture indicating the habitual tense {.unnumbered}

(@) [تِلْكَ صَلاَةُ الْمُنَافِقِ **يَجْلِسُ** يَرْقُبُ الشَّمْسَ حَتَّى إِذَا كَانَتْ بَيْنَ قَرْنَىِ الشَّيْطَانِ قَامَ فَنَقَرَ أَرْبَعًا لاَ يَذْكُرُ اللَّهَ فِيهَا إِلاَّ قَلِيلاً]{.ar}
    [@https://sunnah.com/tirmidhi:160@]{.citex}  
    That is the prayer of the hypocrite. He sits watching the sun, until when it is between the horns of the devil he stands and pecks out four (units of prayer), not remembering Allah in them but a little."

(@) [كُنْتُ **أَقْعُدُ** مَعَ ابْنِ عَبَّاسٍ، يُجْلِسُنِي عَلَى سَرِيرِهِ]{.ar}
    [@https://sunnah.com/bukhari:53@]{.citex}  
    I used to sit with Ibn [#eabbAs]{.trn2} and he would seat me on his couch.

(@) [كَانَ جِذْعٌ يَقُومُ إِلَيْهِ النَّبِيُّ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/bukhari:918@]{.citex}  
    [There] was a stem (of a date palm) [which] the Prophet ;pbuh; would stand against.

(@) [وَيَرْكَعُ رَكْعَتَيْنِ قَبْلَ صَلاَةِ الْفَجْرِ ثُمَّ يَضْطَجِعُ عَلَى شِقِّهِ الأَيْمَنِ حَتَّى يَأْتِيَهُ الْمُؤَذِّنُ لِلصَّلاَةِ]{.ar}
    [@https://sunnah.com/bukhari:994@]{.citex}  
    And he would pray two units [of (sunnah) prayer] before the Fajr prayer, then he **would lie** on his right side until the [muEappin]{.trn2} would come to him for the (obligatory) prayer"

Rarely, the ;mudarie; verb has been found to be used to indicate a continuous tense.
But in such cases it will likely be in a ;hal; or with an adverb which will help indicate its continuous, rather than habitual, significance.
Examples:

(@) [عَنِ ابْنِ عُمَرَ، أَنَّهُ رَأَى رَجُلاً **يَتَّكِئُ** عَلَى يَدِهِ الْيُسْرَى]{.ar}
    [@https://sunnah.com/abudawud:994@]{.citex}  
    "[It was narrated] on the authority of Ibn [#umar]{.trn2} that he saw a man reclining on his left hand"

(@) [ رَأَيْتُ عُمَرَ بْنَ الْخَطَّابِ وَهُوَ **يَجْلِسُ** وَالنَّاسُ مَعَهُ]{.ar}
    [tarikh tabari 3/429]


#### Transitive verbs of posture {.unnumbered}

The verbs of posture are usually intransitive verbs,
as you can see in the examples so far.
But a transitive verb of posture can also be used.
For example:

(@) [كُنْتُ أُصَلِّي وَعَبْدُ اللَّهِ بْنُ عُمَرَ **مُسْنِدٌ** ظَهْرَهُ إِلَى جِدَارِ الْقِبْلَةِ]{.ar}
    [https://sunnah/malik]{.citex}  
    I was praying, while [#eabd #allAh ibn #eumar]{.trn2} was leaning his back on the wall of the qiblah

(@) [وَقَدْ كُنْتُ مُسْنِدَتَهُ إِلَى صَدْرِي]{.ar}
    [@https://sunnah.com/bukhari:2741@]{.citex}  
    "I had been leaning him against my chest."

#### Other verbs that have similar behavior to the verbs of posture {.unnumbered}

In addition to verbs of posture,
there are a few other verbs that indicate 
show the same distiction of the ;ism_fail; being used for the continous tense and the ;mudarie; verb for the habitual tense.
For example:
[نَامَ]{.ar} _to sleep_,
[صَامَ]{.ar} _to fast_.
The reason that these verbs show the same behavior as verbs of posture may be that the ;faa3il; is not actively _doing_ anything except remaining in a condition.
Here are some examples with these verbs:

(@) [ قُلْنَا لِعَمْرٍو إِنَّ نَاسًا يَقُولُونَ إِنَّ النَّبِيَّ صلى الله عليه وسلم **تَنَامُ** عَيْنُهُ وَلاَ **يَنَامُ** قَلْبُهُ]{.ar}
    [@https://sunnah.com/bukhari:859@]{.citex}  
    "We said to [#eamr]{.trn2}: 'Indeed some people say that the Prophet ;pbuh; his eye sleeps but his heart does not sleep.'"

(@) [جَاءَتْ مَلاَئِكَةٌ إِلَى النَّبِيِّ صلى الله عليه وسلم وَهْوَ **نَائِمٌ** فَقَالَ بَعْضُهُمْ إِنَّهُ **نَائِمٌ** وَقَالَ بَعْضُهُمْ إِنَّ الْعَيْنَ **نَائِمَةٌ** وَالْقَلْبَ يَقْظَانُ]{.ar}
    [@https://sunnah.com/bukhari:7281@]{.citex}  
    Some angels came to the Prophet ;pbuh; while he was sleeping. Some of them said, "He is sleeping." Some [others] of them said, "His eye[s] are sleeping but his heart is awake."

(@) [إِنِّي رَجُلٌ **أَصُومُ** أَفَأَصُومُ فِي السَّفَرِ]{.ar}
    [@https://sunnah.com/muslim:1121d@]{.citex}  
    "I am a man who [habitually] fasts, so should I fast in journeying?"

(@) [سِرْنَا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم وَهُوَ **صَائِمٌ**]{.ar}
    [@https://sunnah.com/muslim:1101c@]{.citex}  
    We travelled with the Messenger of Allah ;pbuh; while he [was] fasting.

### The ;ism_fail; for verbs of motion

The ;ism_fail; is very common with verbs of motion, like:
[ذَهَبَ]{.ar} to go,
[مَشَى]{.ar} to walk,
[رَجَعَ]{.ar} to return,
[سَارَ]{.ar} to travel,
etc.
The ;ism_fail; for these verbs again indicates the situation of being in a move rather than the actual dynamic movement.^[@marmor_tense@ 127]
For example:

(@) [وَذَلِكَ الْمَسْجِدُ عَلَى حَافَةِ الطَّرِيقِ الْيُمْنَى، وَأَنْتَ **ذَاهِبٌ** إِلَى مَكَّةَ]{.ar}
    [@https://sunnah.com/bukhari:485@]{.citex}  
    And that mosque is on the right edge of the path as you are **going** to Makkah

(@) [كَانَ النَّبِيُّ صلى الله عليه وسلم يَأْتِي قُبَاءً رَاكِبًا وَمَاشِيًا]{.ar}
    [@https://sunnah.com/bukhari:1194@]{.citex}  
    The Prophet ;pbuh; used to come to [#qubAE]{.trn2} while riding and while walking.

(@) [لَحِقَنِي عَبَايَةُ بْنُ رَافِعٍ وَأَنَا مَاشٍ، إِلَى الْجُمُعَةِ]{.ar}
    [@https://sunnah.com/nasai:3116@]{.citex}  
    [#eabAyah ibn #rAfie]{.trn2} joined me while I was **walking** to the [jumueah]{.trn2}

(@) [كُنْتُ **مُسَافِرًا** فَأَتَيْتُ النَّبِيَّ صلى الله عليه وسلم وَهُوَ يَأْكُلُ وَأَنَا صَائِمٌ]{.ar}
    [@https://sunnah.com/nasai:2281@]{.citex}  
    "I was journeying and I came to the Prophet ;pbuh; while he was eating and I was fasting."

(@) [بَيْنَا النَّبِيُّ ﷺ سَائِرٌ إِلَى تَبُوكَ نَزَلَ عَنْ رَاحِلَتِهِ]{.ar}
    [https://hadithunlocked.com/bayhaqi:16844]{.citex}  
    "While the Prophet ;pbuh; was **travelling** to [#tabUk]{.trn2}, he dismounted off his mount"

<!--
(@) [حَتَّى إِذَا كُنَّا بالْمُصَلَّى رَاجِعِينَ مِنْ بَدْرٍ بَرَكَ عَلَيْنَ]{.ar}
    "Until we were near [al-#muSallA]{.trn2}, returning from Badr, it (i.e. the camel) kneeled down to us"
-->

(@) [ثُمَّ أَرْدَفَنِي وَرَاءَهُ عَلَى الْعَضْبَاءِ رَاجِعِينَ إِلَى الْمَدِينَةِ]{.ar}
    [https://hadithunlocked.com/ahmad:16539]{.citex}  
    Then he seated me behind him on [al-#eaDbAE]{.trn} while we [were] returning to [al-#madInah]{.trn2}

(@) [اتَّبَعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم وَهُوَ **رَاكِبٌ**]{.ar}
    [@https://sunnah.com/nasai:953@]{.citex} [move to verbs of motion]  
    "I followed the Messenger of Allah ;pbuh; when he was **riding**"

<!--
But when the focus is on the actual dynamic movement rather than being in a state of moving,
then the ;mudarie; verb tends to be used.
As usual, the ;mudarie; verb can be used as well.
For example:

(@) [فَجَاءَتْهُ إِحْدَاهُمَا تَمْشِى عَلَى ٱسْتِحْيَاءٍ]{.ar}
    [@https://quran.com/28/25@]{.citex}  
    Then one of the two women came to him walking with shyness.
-->

Unlike verbs of posture and temporary state,
verbs of motion are frequently used for the continuous tense.
Here are some examples:

(@) [أَدْرَكَنِي أَبُو عَبْسٍ وَأَنَا **أَذْهَبُ** إِلَى الْجُمُعَةِ]{.ar}
    [@https://sunnah.com/bukhari:907@]{.citex}  
    [#abU #eabs]{.trn2} overtook me while I **[was] going** to the [jumueah]{.trn2}

(@) [بَيْنَا أَنَا **أَسِيرُ** مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم بَيْنَ الْجُحْفَةِ وَالأَبْوَاءِ إِذْ غَشِيَتْنَا رِيحٌ وَظُلْمَةٌ شَدِيدَةٌ]{.ar}
    [@https://sunnah.com/abudawud:1463@]{.ar}
    While I **was travelling** with the Messenger of Allah ;pbuh; between [al-#juHfah]{.trn2} and [al-E#abwAE]{.trn2}, suddenly a wind and intense darkness enveloped us

<!--
### The ;mudarie; verb used to indicate a static state

We would like to round off this discussion by mentioning that
the ;mudarie; verb too, can be used to indicate a static state.
Contrast example 
(@ism_fail_wearing_bedsheet) ([وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ **لاَبِسٌ مِرْطَ** عَائِشَةَ]{.ar})
with example (@ism_fail_wearing_sandals) below:

(@ism_fail_wearing_sandals) [فِإِنِّي رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم **يَلْبَسُ** النِّعَالَ الَّتِي لَيْسَ فِيهَا شَعْرٌ]{.ar}
    [@https://sunnah.com/abudawud:1772@]{.citex}  
    "I have seen the Messenger of Allah ;pbuh; **wearing** the sandals which don't have hair on them (i.e. tanned)."

Sometimes, the ;ism_fail;,
when indicating a static state,
is interchangeable with the ;mudarie; verb.
See the following pair of examples:

(@) [... وَلاَ آخَرُ قَدِ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهُوَ **مُنْتَظِرٌ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/muslim:1747@]{.citex}  
    "... nor another who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"

(@) [... وَلاَ أَحَدٌ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهْوَ **يَنْتَظِرُ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/bukhari:3124@]{.citex}  
    "... nor one who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"
-->

## The ;ism_fail; used to indicate a future event

In addition to indicating a static state,
another verbal meaning of the ;ism_fail;
is to indicate the future tense.

Here too, the ;ism_fail; is used instead of the ;mudarie; verb.
When a ;mudarie; verb is used to indicate a future event,
then it merely signifies that the speaker thinks that the ;faa3il; will take an action.
For example, the ;mudarie; verb
[أَذْهَبُ]{.ar}
(when used to indicate the future tense)
merely signifies the speaker’s intention of going some time in the future.

In contrast, 
when the ;ism_fail; is used to indicate the future tense, then it signifies that,
in the estimation of the speaker, the event will definitely take place.
In other words, the ;faa3il;’s future action is so settled and resolved in the speaker’s mind that
;faa3il; can already be described by the ;ism_fail;.
So, for example, if the speaker says 
[أَنَا ذَاهِبٌ]{.ar}
and the context tells us he is referring to a future action, then the use of the ;ism_fail;
[ذَاهِب]{.ar}
instead of the ;mudarie; verb [يَذْهَبُ]{.ar}, 
signifies that the speaker is so sure that he will do this action that he can already be described as a "goer".

Here are some examples of the ;ism_fail; being used to indicate the future tense:

(@) [إني ذاهب إلى ربي سيهدين]{.ar}

(@) [فَهُوَ ذَاهِبٌ وَتَارِكُهُ لِلنَّاسِ]{.ar} muslim:2959a

(@) [إني ذاكر لك أمرا]{.ar} bukhari:1925

(@) [أنا فاعل]{.ar} tirmidhi:2433

(@) [جاعل في الأرض خليفة]{.ar}

(@) [زَعَمَ ابْنُ أُمِّي أَنَّهُ قَاتِلٌ رَجُلاً قَدْ أَجَرْتُهُ]{.ar}
    [@https://sunnah.com/bukhari:6158@]{.citex}  
    "My maternal brother claims that he will kill a man whom I have given protection to."

(@) [وَإِنِّي مُرْسِلَةٌ إِلَيْهِم بِهَدِيَّةٍ فَنَاظِرَةٌ بِمَ يَرْجِعُ ٱلْمُرْسَلُونَ]{.ar}
    [@https://quran.com/27/35@]{.citex}  
    "But indeed, I will send to them a gift and see with what [reply] the messengers will return."

The use of the ism_fail instead of the mudarie verb to indicate a future event can also, depending on context, indicate that the event is imminent, i.e. that it is in the very near future.
In such cases it can be translated using "be going to".
For example:

(@) [فَقَالَ عُتْبَةُ:لَا شَيْءَ، أَنَا **خَارِجٌ**]{.ar} [marmor 171]


### The ;ism_fail; used for a hypothetical event

<!--
### The ;mudarie; verb used to indicate a future event

We would like to round off this discussion by mentioning that
the ;mudarie; verb too can be used to indicate a future event.
We have already discussed the possible difference in meaning between a ;mudarie; verb is used to indicate a future event,
and when an ;ism_fail; is used to do so.

Contrast example (@ism_fail_going_to_my_lord) with example (@ism_fail_anas_going) below:

(@ism_fail_anas_going) [فَقَالَ يَا أُنَيْسُ أَذَهَبْتَ حَيْثُ أَمَرْتُكَ  قَالَ قُلْتُ نَعَمْ أَنَا أَذْهَبُ يَا رَسُولَ اللَّهِ]{.ar}
    [@https://sunnah.com/muslim:2310a@]{.citex}  
    He said "O Unays, did you go where I commanded you [to go]?" I said, "Yes I am going, O Messenger of Allah"

Sometimes, the ;ism_fail;,
when indicating a future event
is interchangeable with the ;mudarie; verb.
See the following pair of examples:

(@) [أَرَأَيْتَكُمْ لَوْ أَخْبَرْتُكُمْ أَنَّ خَيْلاً تَخْرُجُ بِسَفْحِ هَذَا الْجَبَلِ أَكُنْتُمْ **مُصَدِّقِيَّ**]{.ar}
    [@https://sunnah.com/muslim:208a@]{.citex}  
    "Do you think if I were to inform you that there were horsemen emerging out of the foot of this mountain, would you **believe** me?"

(@) [أَرَأَيْتُمْ إِنْ حَدَّثْتُكُمْ أَنَّ الْعَدُوَّ مُصَبِّحُكُمْ أَوْ مُمَسِّيكُمْ، أَكُنْتُمْ **تُصَدِّقُونِي**]{.ar}
    [@https://sunnah.com/bukhari:4972@]{.citex}  
    "Do you think if I told you that an enemy is going to attack you in the morning or in the evening, will you **believe** me?"
-->

## Interchangeability of the ;mudarie; verb and the ;ism_fail;

We have described above,
the circumstances when the ;ism_fail; instead of the ;mudarie; verb,.
We would like to state that these are more like trends rather than hard and fast rules.
We sometimes find a ;mudarie; verb where an ;ism_fail; could have worked, and vice versa.

For the indication of a static state,
consider, for instance, example (@ism_fail_wearing_bedsheet)
([وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ **لاَبِسٌ مِرْطَ** عَائِشَةَ]{.ar}) above
and compare it with with example (@ism_fail_wearing_sandals) below:

(@ism_fail_wearing_sandals) [فِإِنِّي رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم **يَلْبَسُ النِّعَالَ** الَّتِي لَيْسَ فِيهَا شَعْرٌ]{.ar}
    [@https://sunnah.com/abudawud:1772@]{.citex}  
    "I have seen the Messenger of Allah ;pbuh; **wearing** the sandals which don't have hair on them (i.e. tanned)."

Consider also the following two narrations:

(@) [... وَلاَ آخَرُ قَدِ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهُوَ **مُنْتَظِرٌ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/muslim:1747@]{.citex}  
    "... nor another who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"

(@) [... وَلاَ أَحَدٌ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهْوَ **يَنْتَظِرُ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/bukhari:3124@]{.citex}  
    "... nor one who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"

Similarly, for the indication of the future tense,
contrast example (@ism_fail_going_to_my_lord) with example (@ism_fail_anas_going) below:

(@ism_fail_anas_going) [فَقَالَ يَا أُنَيْسُ أَذَهَبْتَ حَيْثُ أَمَرْتُكَ  قَالَ قُلْتُ نَعَمْ أَنَا أَذْهَبُ يَا رَسُولَ اللَّهِ]{.ar}
    [@https://sunnah.com/muslim:2310a@]{.citex}  
    He said "O Unays, did you go where I commanded you [to go]?" I said, "Yes I am going, O Messenger of Allah"

Consider also the following two narrations:

(@) [أَرَأَيْتَكُمْ لَوْ أَخْبَرْتُكُمْ أَنَّ خَيْلاً تَخْرُجُ بِسَفْحِ هَذَا الْجَبَلِ أَكُنْتُمْ **مُصَدِّقِيَّ**]{.ar}
    [@https://sunnah.com/muslim:208a@]{.citex}  
    "Do you think if I were to inform you that there were horsemen emerging out of the foot of this mountain, would you **believe** me?"

(@) [أَرَأَيْتُمْ إِنْ حَدَّثْتُكُمْ أَنَّ الْعَدُوَّ مُصَبِّحُكُمْ أَوْ مُمَسِّيكُمْ، أَكُنْتُمْ **تُصَدِّقُونِي**]{.ar}
    [@https://sunnah.com/bukhari:4972@]{.citex}  
    "Do you think if I told you that an enemy is going to attack you in the morning or in the evening, will you **believe** me?"


## The ;ism_fail; defined by [ٱل]{.ar}

When the ;ism_fail; is defined by 
[ٱل]{.ar}
and has verbal force,
then the
[ٱل]{.ar}
serves an identifying purpose,
corresponding to the ;ism_mawsul;s
([ٱلَّذِي]{.ar},
[ٱلَّتِي]{.ar},
etc.).
And the ;ism_fail; itself has a strong correspondence with the verb.
So for example,
the ;ism_fail;
[القَاتِل]{.ar}
corresponds to the structure
[الَّذِي قَتَلَ/يَقْتُلُ]{.ar}.
The meaning of the verb is included in the meaning of the ;ism_fail;.
So much so, that an actual verb may be conjuncted to the _meaning of the verb_ that is included in the ;ism_fail;^[@https://tafsir.app/albahr-almuheet/57/18@]:
[ٱل]{.ar}.
For example:

(@) [إِنَّ **ٱلْمُصَّدِّقِينَ وَٱلْمُصَّدِّقَاتِ وَأَقْرَضُوا** ٱللَّهَ قَرْضًا حَسَنًا يُضَاعَفُ لَهُمْ وَلَهُمْ أَجْرٌ كَرِيمٌ]{.ar}
    [@https://quran.com/57/18@]{.citex}  
    "Indeed, the men who practice charity and the women who practice charity and [they who] have loaned Allāh a goodly loan - it will be multiplied for them, and they will have a noble reward."


## Applicability of the ;ism_fail; to the ;faa3il;

In this section, we will discuss at what point the ;faa3il; of a verb may be ascribed by the ;ism_fail;.
For example, if a person reads or recites only one word, can he be described as a [قَارِئ]{.ar}?
Or does the person need to read/recite a large amount of text to qualify being called a [قَارِئ]{.ar}?
The answer is: it depends on what is intended to be meant by the ;ism_fail; [قَارِئ]{.ar}.

Technically, any person who has performed, is performing, or will perform an action of the verb [قَرَأَ]{.ar}, even once, can be called a
[قَارِئ]{.ar}.
This is a situational applicability.
And from context it will be understood that the person is being called a [قَارِئ]{.ar} within the situation of a certain reading or recitation.
For example:

<!--
(@) [إِنَّ رَجُلاً أَسْلَمَ فِي حَدِيقَةِ نَخْلٍ فِي عَهْدِ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ قَبْلَ أَنْ يُطْلِعَ النَّخْلُ فَلَمْ يُطْلِعِ النَّخْلُ شَيْئًا ذَلِكَ الْعَامَ فَقَالَ الْمُشْتَرِي هُوَ لِي حَتَّى يُطْلِعَ . وَقَالَ الْبَائِعُ إِنَّمَا بِعْتُكَ النَّخْلَ هَذِهِ السَّنَةَ .]{.ar}
    [@https://sunnah.com/ibnmajah:2284@]{.ar}  
    _A man paid in advance for a grove of trees during the time of the Messenger of Allah ;pbuh;, before they had produced any fruit, and they did not bear anything that year. The purchaser said: "They belong to me until they produce." But the **seller** said: "I only sold the trees to you for this year!"_
-->

(@) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم صَلَّى الظُّهْرَ فَجَعَلَ رَجُلٌ يَقْرَأُ خَلْفَهُ بِسَبِّحِ اسْمَ رَبِّكَ الأَعْلَى فَلَمَّا انْصَرَفَ قَالَ  أَيُّكُمْ قَرَأَ  أَوْ  أَيُّكُمُ **الْقَارِئُ**]{.ar}
    [@https://sunnah.com/muslim:398b@]{.citex}  
    _that the Messenger of Allah ;pbuh; prayed the [Puhr]{.trn2} prayer, and a man began to recite behind him [[sUrat al-#aelA]{.trn2}]. When [the Prophet ;pbuh; concluded the prayer and] turned around, he said: "Which of you recited?" or "Which of you [was] **the reciter**?"_

(@) [سَمِعَ النَّبِيُّ صلى الله عليه وسلم **قَارِئًا** يَقْرَأُ مِنَ اللَّيْلِ فِي الْمَسْجِدِ]{.ar}
    [@https://sunnah.com/bukhari:5042@]{.citex}  
    _The Prophet ;pbuh; heard **a reciter** reciting the [#qurEAn]{.trn2} in the mosque at night._

However, sometimes, a person may have done the action of the verb many times, or is skilful in it, or does the action as his profession. In these cases he can be described by the ;ism_fail; generally.
For example:

(@) [وَقَرَأْتَ الْقُرْآنَ لِيُقَالَ هُوَ **قَارِئٌ**]{.ar}
    [@https://sunnah.com/muslim:1905a@]{.citex}  
    _And you recited the [#qurEAn]{.trn2} in order that it be said: "He is **a reciter**."_

(@) [عَنْ سَعِيدِ بْنِ عُبَيْدٍ وَكَانَ يُدْعَى فِي زَمَنِ النَّبِيِّ صلى الله عليه وسلم **الْقَارِئَ**]{.ar}
    [https://hadithunlocked.com/tabarani:5540]{.citex}  
    _[It was narrated] from [#saeId ibn #eubayd]{.trn2}, and he was called in the time of the Prophet ;pbuh; **the reciter**..._

The ;ism_fail;,
with its meaning of general applicability,
can also be contrasted with the verb to indicate a more stative and descriptive meaning for the ;ism_fail; and an active meaning for the ;faa3il; of the verb.
Consider [سورة الكافرون]{.ar}:

(@) [قُلْ يا أيُّها الكافِرُونَ ۝ لا أعْبُدُ ما تَعْبُدُونَ ۝ ولا أنْتُمْ عابِدُونَ ما أعْبُدُ ۝ ولا أنا عابِدٌ ما عَبَدْتُمْ ۝ ولا أنْتُمْ عابِدُونَ ما أعْبُدُ ۝ لَكم دِينُكم ولِيَ دِينِ ۝]{.ar}  
    [@https://quran.com/109@]{.citex}  
    _Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you worship. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."_

Ibn\ al-Qayyim says, in the [tafsIr]{.trn2} of this [sUrah]{.trn2}, that 
the Prophet ;pbuh; is negated from worshipping the disbelievers' gods using once the verb 
[أَعْبُدُ]{.ar}
and once using the ;ism_fail; 
[عَابِد]{.ar}.
So the Prophet ;pbuh; is disassociated from their false gods from every perspective and at every time.
For the negated verb 
[لَا أَعْبُدُ]{.ar}
negates the occurence of the action of worshipping and its continuation from the Prophet ;pbuh;.
And the negated ;ism_fail; 
[وَ لَا أَنَا عَابِدٌ]{.ar}
states that the Prophet ;pbuh; cannot be described as a worshipper of their false gods, or as being in a state of worshipping their false gods.

Whereas 
the disbelievers are negated from worshipping [#allAh]{.trn2} both times using the negated ;ism_fail; [ولا أنْتُمْ عَابِدُون]{.ar}.
This is because, even if they had sometimes worshipped [#allAh]{.trn2} along with their false gods, they do not qualify being described as "worshippers of [#allAh]{.trn2}".
This epithet is only applicable to one who worships [#allAh]{.trn2} without associating any partners with him.^[@https://tafsir.app/ibn-alqayyim/109/6@]

In the following [HadIv]{.trn2}, the Prophet ;pbuh; describes how a person cannot be described as "a believer" when committing certain negating actions:

(@) [عَنْ أَبِي هُرَيْرَةَ، قَالَ قَالَ النَّبِيُّ صلى الله عليه وسلم  لاَ يَزْنِي الزَّانِي حِينَ يَزْنِي وَهْوَ مُؤْمِنٌ، وَلاَ يَسْرِقُ حِينَ يَسْرِقُ وَهْوَ مُؤْمِنٌ، وَلاَ يَشْرَبُ حِينَ يَشْرَبُهَا وَهْوَ مُؤْمِنٌ، وَالتَّوْبَةُ مَعْرُوضَةٌ بَعْدُ]{.ar}


## The difference in meaning between the ;ism_fail; and the ;sifah_mush;

Usually more temporary.
some ism_fail can be more permanent
Daaiq, Dayyiq: see maani_nahw
Some ism_fails not used


