# The connected nouns

## Introduction

Consider the sentence:

[رَأَيْتُ ٱلرَّجُلَ.]{.ar}  
"I saw the man."

If the listener (or reader) can identify 
the individual referred to by the noun "the man"
(maybe from a pre-existing mutual understanding with the speaker),
then there is no problem with this sentence.
But often, further clarification is needed for the listener to correctly identify the individual to whom the speaker is referring.
This further clarification can be provided in a number of ways.

One way is to use an adjectival noun to describe the noun. For example:

[رَأَيْتُ ٱلرَّجُلَ ٱلطَّوِيلَ.]{.ar}  
"I saw the _tall_ man."

Another way is to use a pointing noun, thus:

[رَأَيْتُ ذَ ٰلِكَ ٱلرَّجُلَ.]{.ar}  
"I saw _that_ man."

But sometimes, a whole sentence is needed to provide the needed identification. 
In this case, Arabic uses what is called a _connected noun_ and a _connecting sentence_. 
<!--A connected noun is itself a vague noun, which is then connected to by a qualifying sentence directly following it called the _connecting sentence_. 
The connecting sentence contains sufficient information to identify the individual intended by the speaker. -->
This example should help you understand what we mean:


```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=2.0ex}]
\path [decoration={text effects along path, 
  text=.\txarb{لَقِيتُهُ بِٱلْأَمْسِ} \txarb{ٱلَّذِي} \txarb{رَأَيْتُ ٱَلرَّجُلَ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, rotate=90, anchor=south, left=0ex, align=left] {\scriptsize connecting sentence};

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, rotate=90, anchor=south, left=0ex, align=left] {\scriptsize connected noun};

\path (0,0) node [midway, below=15.5ex, right=0ex, align=left] {``I saw the [specific] man whom I met yesterday.''};

\end{tikzpicture}
```

In the above sentence, the connected noun is [ٱَلَّذِي]{.ar} [EallapI]{.trn}.
It is applied to singular masculine nouns, like [ٱلرَّجُل]{.ar}.
<!--It signifies a specific individual denoted by a singular masculine noun.-->
By itself it may be translated as "the one~1m~ that/which/who/whom".
<!--Sometimes in sentences it is left untranslated (as above) and an implied "who", "whom", "that", or "which" is used to aid the translation.-->
It is called a connected noun because it is directly followed by, i.e. _connected_ to, a connecting sentence.
The connecting sentence contains necessary information for the listener to correctly identify the individual that the connected noun refers to.
The connecting sentence in the above example is the sentence [لَقِيتُهُ بِٱلْأَمْسِ]{.ar} "I met him yesterday."

Note by the way, that we did not translate the pronoun "him" in our original translation (above). 
This is because it would sound unnatural in English to say: "I saw the [specific] man (whom) I met _him_ yesterday."
But this pronoun is an essential part of the Arabic connecting sentence and is called the _refer-back pronoun_. 
We will deal with it in section\ \@ref(refer-back-pronoun) later in this chapter.

There are two types of connected nouns:

 1. The specific connected nouns
 2. The general connected nouns

We will study both these types separately within this chapter.

## The specific connected nouns

The specific connected nouns have a significance which is restricted to a specific individual or category of individuals, 
and its connecting sentence should contain sufficient information to identify that specific individual.

The specific connected nouns is a group of nouns where each noun is applied to a gender and number of individuals. They are:

|Connected noun|Description|
|:--|:----------------|
|[ٱَلَّذِي]{.ar} [EallapI]{.trn}|Singular masculine. For both intelligent and non-intelligent beings. Rigid. Only one [ل]{.ar} in its spelling.|
|[ٱَلَّتِي]{.ar} [EallatI]{.trn}|Singular feminine. For both intelligent and non-intelligent beings. Also used for plural non-intelligent beings of both genders. Rigid. Only one [ل]{.ar} in its spelling.|
|[ٱَللَّذَانِ]{.ar} [EallapAnI]{.trn}|Dual masculine. For both intelligent and non-intelligent beings. Flexible: [ٱَللَّذَيْنِ]{.ar} [Eallapayni]{.trn} in the a- and i-states. Two [ل]{.ar}'s in its spelling.|
|[ٱَللَّتَانِ]{.ar} [EallatAnI]{.trn}|Dual feminine. For both intelligent and non-intelligent beings. Flexible: [ٱَللَّتَيْنِ]{.ar} [Eallatayni]{.trn} in the a- and i-states. Two [ل]{.ar}'s in its spelling.|
|[ٱَلَّذِينَ]{.ar} [EallapIna]{.trn}|Plural masculine. For both intelligent beings. Rigid. Only one [ل]{.ar} in its spelling.|
|[ٱَللَّاتِي]{.ar} [EallAtI]{.trn} |For plural feminine intelligent beings. Also used for non-intelligent beings of both genders but [ٱَلَّتِي]{.ar} is more common there. Rigid. Two [ل]{.ar}'s in its spelling. Has the following variants: [ٱَللَّاتِ]{.ar} [EallAti]{.trn}, [ٱَللَّائِي]{.ar} [EallAEI]{.trn}, [ٱَللَّوَاتِي]{.ar} [EallawAtI]{.trn}|

### Grammatical position of the specific connected noun

Consider again the same example:

[رَأَيْتُ ٱلرَّجُلَ ٱلَّذِي لَقِيتُهُ بِٱلْأَمْسِ.]{.ar}  
"I saw the [specific] man whom I met yesterday."

In this example, the connected noun
[ٱَلَّذِي]{.ar} [EallapI]{.trn}
is a describer (in the a-state) to the described noun
<!--
[ٱلرَّجُل]{.ar}.
[ٱَلَّذِي]{.ar} 
is in the a-state to match the described noun
-->
[ٱلرَّجُلَ]{.ar}.
Because 
[ٱَلَّذِي]{.ar} 
is a rigid noun, it will appear the same in all states without any change to its ending.

As a describer, the connected noun may also come as the last in a series of describers, and can also be combined with a pointing noun. 
For example:

[رَأَيْتُ ذَ ٰلِكَ ٱلرَّجُلَ ٱلطَّوِيلَ ٱلَّذِي لَقِيتُهُ بِٱلْأَمْسِ.]{.ar}  
"I saw that [specific] tall man whom I met yesterday."

But connected nouns need not only occur as describers.
<!--They may occur as a subject, an information, a doer, a doee, following a preposition, and as a base noun in an annexation.-->
They may occur in various grammatical positions. 
Here are some examples:
<!--
As a subject:

[ٱَلَّذِي رَزَقَنَا بِٱلْأَمْسِ سَيَرْزُقُنَا بِالْغَدِ.]{.ar}  
"The [specific] one (who) provided for us yesterday will provide for us tomorrow."

As an information:

[هَـٰذَا هُوَ ٱلَّذِي لَقِيتُهُ.]{.ar}  
"This is the [specific] one (whom) I met."

As a doer:

[قَدْ بَلَغَنَا ٱلَّذِي قُلْتُمُوهُ.]{.ar}  
"The [specific] one (thing that) you said has reached us."

As a doee:

[نَهَيْتُ ٱلَّذِي أَسَاءَ.]{.ar}  
"I forbade the [specific] one (who) did evil."

Following a preposition:

[أَرَادَ أَنْ يَبْطِشَ بِٱلَّذِي هُوَ عَدُوٌّ لَهُمَا]{.ar}  
"he wanted to strike the one who was an enemy to both of them"  
(28:19)

As a base noun in an annexation:

[هَـٰذَا بَيْتُ ٱلَّذِي لَقِيتُهُ.]{.ar}  
"This is the house of the [specific] one (whom) I met."
-->

As a subject:

[وَالَّذِينَ يَكْنِزُونَ ٱلذَّهَبَ وَٱلْفِضَّةَ وَلَا يُنْفِقُونَهَا فِي سَبِيلِ ٱللَّـٰهِ فَبَشِّرْهُمْ بِعَذَابٍ أَلِيمٍ]{.ar}  
"And those who hoard gold and silver and spend it not in the way of Allāh - give them tidings of a painful punishment."  
9:34

As an information:

[خِيَارُ أَئِمَّتِكُمُ الَّذِينَ تُحِبُّونَهُمْ وَيُحِبُّونَكُمْ]{.ar}  
"The best of your rulers are the ones whom you love and who love you"
[[#SaHIH #muslim]{.trn2}:1855]

[هُنَّ اللَّوَاتِي عَلَى الْمِنْبَرِ]{.ar}  
"They are the ones which (are) on the pulpit."  
[[#sunan al-#dArimI]{.trn2}:36]

As a doer:

[قَدْ بَلَغَنَا ٱلَّذِي قُلْتُمُوهُ.]{.ar}  
"The [specific] one (thing) that you said has reached us."

As a doee:

[رَبَّنَا أَرِنَا ٱللَّذَيْنِ أَضَلَّانَا مِنَ ٱلْجِنِّ وَٱلْإِنْسِ]{.ar}  
"Our Lord, show us those who misled us of the jinn and men"  
41:29

Following a preposition:

[أَوْ كَٱلَّذِي مَرَّ عَلَىٰ قَرْيَةٍ]{.ar}  
"Or [consider such an example] as the one who passed by a township"  
2:259

As a base noun in an annexation:

[قَدْ سَمِعَ ٱللَّـٰهُ قَوْلَ ٱلَّتِي تُجَادِلُكَ فِي زَوْجِهَا]{.ar}  
"Certainly has Allāh heard the speech of the one who argues [i.e., pleads] with you, [O Muḥammad]"  
58:1

## The refer-back pronoun {#refer-back-pronoun}

The connecting sentence is directly follows the connected noun. 
As we mentioned in the introduction,
the connecting sentence provides clarifying information for the listener (or reader) to identify the individual referred to by the connected noun.

<!--
### An incomplete sentence as the connecting sentence

The connecting sentence is, by default, a complete sentence. 
It is, however, allowed to be an incomplete sentence if it is one of the following:

 i. A prepositional phrase. For example:

    [نَامَ ٱلَّذِي فِي ٱلْغُرْفَةِ.]{.ar}  
    "The one (who is) in the room has slept."

    The connecting sentence is the incomplete sentence [فِي ٱلْغُرْفَةِ]{.ar} "(is) in the room".

ii. An adverbial phrase. For example:

    [تَكَلَّمَ ٱلَّذِي عِنْدَكَ.]{.ar}  
    "The one (who is) with you spoke."

    (Remember that [عِنْدَ]{.ar} is technically a noun used adverbially, not a preposition.)
    The connecting sentence is the incomplete sentence [عِنْدَكَ]{.ar} "(is) with you". 

In such cases, the incomplete sentence connecting sentence implcitly includes the meaning of a verb which is usually the verb "being", like "is", "are", "am", etc.

### The refer-back pronoun {#refer-back-pronoun}
-->

In the connecting sentence is a pronoun that refers back to the connected noun.
This pronoun is called the _refer-back pronoun_.
and it is an essential (though not always apparent) part of the connecting sentence.

Let us identify some of the refer-back pronouns in the examples we have given.


[وَالَّذِينَ يَكْنِزُونَ ٱلذَّهَبَ وَٱلْفِضَّةَ]{.ar}  
"And those who hoard gold and silver"  
refer-back pronoun: the plural masculine doer pronoun [و]{.ar} in [يَكْنِزُونَ]{.ar}

[خِيَارُ أَئِمَّتِكُمُ الَّذِينَ تُحِبُّونَهُمْ]{.ar}  
"The best of your rulers are the ones whom you love and who love you"  
refer-back pronoun: the plural masculine doee attached pronoun [هُمْ]{.ar} in [تُحِبُّونَهُمْ]{.ar}

[قَدْ بَلَغَنَا ٱلَّذِي قُلْتُمُوهُ.]{.ar}  
"The [specific] one (thing) that you said has reached us."  
refer-back pronoun: the singular masculine doee attached pronoun [هُ]{.ar} in [قُلْتُمُوهُ]{.ar}

[رَبَّنَا أَرِنَا ٱللَّذَيْنِ أَضَلَّانَا مِنَ ٱلْجِنِّ وَٱلْإِنْسِ]{.ar}  
"Our Lord, show us those who misled us of the jinn and men"  
refer-back pronoun: the dual masculine doer pronoun [ا]{.ar} in [أَضَلَّانَا]{.ar}

[أَوْ كَٱلَّذِي مَرَّ عَلَىٰ قَرْيَةٍ]{.ar}  
"Or [consider such an example] as the one who passed by a township"  
refer-back pronoun: the implied singular masculine doer pronoun "he" in [مَرَّ]{.ar}

[قَدْ سَمِعَ ٱللَّـٰهُ قَوْلَ ٱلَّتِي تُجَادِلُكَ فِي زَوْجِهَا]{.ar}  
"Certainly has Allāh heard the speech of the one who argues [i.e., pleads] with you, [O Muḥammad]"  
refer-back pronoun: the implied singular feminine doer pronoun "she" in [تُجَادِلُكَ]{.ar}

### Matching the refer-back pronoun with the connected noun

The refer-back pronoun matches the specific connected noun in gender and number.
And the refer-back pronoun is generally an absent-person pronoun ([هُ]{.ar}, [هَا]{.ar}, [هُوَ]{.ar}, [هُمْ]{.ar}, etc.).
For example, in the sentence,
[وَالَّذِينَ يَكْنِزُونَ ٱلذَّهَبَ وَٱلْفِضَّةَ]{.ar}
"And those who hoard gold and silver,"
the refer-back pronoun is the plural masculine absent-person doer pronoun [و]{.ar} "they" in [يَكْنِزُونَ]{.ar} "they hoard".
And it matches the plural masculine connected noun [ٱلَّذِينَ]{.ar}.

However, there is an exception to the refer-back pronoun being an absent-person pronoun.
And that is when the connected noun refers to the speaker or the addressed person, like 
[أَنَا ٱلَّذِي]{.ar}, or [أَنْتُمُ ٱلَّذِينَ]{.ar}, etc.
In these cases, the refer-back pronoun may optionally:

 i. either be an absent-person pronoun to match the connected noun (as usual),
ii. or match the pronoun for the speaker or addressed person (as the case may be)

The latter is generally more common but both options are permissible.
For example:

[أَنَا ٱلَّذِي حَضَرْتُ.]{.ar}  
refer-back pronoun: the singular masculine doer pronoun for the speaker [تُ]{.ar} in [حَضَرْتُ]{.ar}  
or  
[أَنَا ٱلَّذِي حَضَرَ.]{.ar}  
refer-back pronoun: the implied singular masculine doer pronoun for the absent person "he" in [حَضَرَ]{.ar}  
"I am the one (who) was present."

Here are some examples from Classical Arabic:

[أَنَا ٱلَّذِي سَمَّتْنِ أُمِّي حَيْدَرَهْ]{.ar}  
"I am the one whom my mother named [#Haydarah]{.trn2}"  
(The refer-back pronoun is the speaker person's doee pronoun in [سَمَّتْنِ]{.ar}, which is an abbreviation of [سَمَّتْنِي]{.ar} "she named me".)

[فَقَالَ مُوسَى يَا آدَمُ أَنْتَ الَّذِي خَلَقَكَ اللَّهُ بِيَدِهِ]{.ar}  
"[#mUsA]{.trn2} said: O [#Adam]{.trn2}, you are the one whom [#allAh]{.trn2} created with His Hand"  
tirmidhi:2134  
(The refer-back pronoun is the addressed person's doee pronoun [كَ]{.ar} in [خَلَقَكَ]{.ar}.)

There is one circumstance where matching the refer-back pronoun to the (absent person) connected-noun is mandated.
And that is when the connected noun is the called-out person using the particle [أَيُّهَا]{.ar} or [أَيَّتُهَا]{.ar}.
For example,

[يَاأَيُّهَا ٱلَّذِينَ  آمَنُوا]{.ar}  
"O you who have believed"  
not  
$\times$ [يَاأَيُّهَا ٱلَّذِينَ آمَنْتُمْ]{.ar}  

Similarly,

[يَاأَيُّهَا الَّذِي نُزِّلَ عَلَيْهِ الذِّكْرُ]{.ar}  
"O you upon whom the message has been sent down"  
15:6

<!--
If 
the connected noun is called-out to using the another particle, then again, both options are permissible.
For example,

[يَا هَـٰذَا ٱلَّذِي قَامَ]{.ar}  
or    
[يَاأَيُّهَا هَـٰذَا ٱلَّذِي قُمْتَ]{.ar}  
"O the one (who) stood up"  
-->

## The general connected nouns [مَنْ]{.ar} and [مَا]{.ar}

The general connected nouns are unrestricted in significance, and may be applied to any individual who fits the criteria given in the connecting sentence.
The most commonly general connected nouns are:

+ [مَنْ]{.ar} [man]{.trn}. Typically used for intelligent beings and translated as "who".
+ [مَا]{.ar} [mA]{.trn}. Typically used for non-intelligent beings and translated as "what".
+ [أَيّ]{.ar} [Eayy]{.trn}. Used for both intelligent and non-intelligent beings. Translated as "which", "whichever" or "any".

There are also a couple of rarely or dialectally used general connected nouns that we will not cover. 
These are 
<!--[أَيّ]{.ar} [Eayy]{.trn},--> 
[ذُو]{.ar} [pU]{.trn}, and [ذَا]{.ar} [pA]{.trn}.[^connected-noun-other-interrogatives]

[^connected-noun-other-interrogatives]: Fischer claims (§427):

    > Other interrogatives (§289) are also used as relatives:
    > [عَرَفَ ٱلْمَكِيدَةَ وَكَيْفَ كَانَ ٱلْمَلِكُ أَوْقَعَهَا]{.ar}
    > 'He knew the trick and how the king employed it.'
    > [وَٱللّٰهِ مَا نُبَالِي أَيْنَ ذَهَبَ]{.ar}
    > 'By God, we do not care where he went'; cf.\ also §419b.

    However, we have not been able to find the classical grammarians including [كيف]{.ar}, [أين]{.ar}, etc. among [الأسماء الموصولة]{.ar}.
    To understand how these interrogatives are to be analyzed in such sentences,
    it may help to look up the [إعراب]{.ar} of the verses :
    [هُوَ الَّذِي يُصَوِّرُكُمْ فِي الْأَرْحَامِ كَيْفَ يَشَاءُ]{.ar} [3:6], and
    [لِيُرِيَهُ كَيْفَ يُوَارِي سَوْءَةَ أَخِيهِ]{.ar} [5:31]
    in linguisitic [tafsIrs]{.trn2} like
    [البحر المحيط لأبي حيان]{.ar} and
    [التحرير والتنوير لابن عاشور]{.ar}.

    The article [ٱل]{.ar} is also generally included among [الأسماء الموصولة المشتركة]{.ar}.
    However, we have deemed it too complicated to cover (and too confusing to even mention in main text).
    See [النحو الوافي لعباس حسن]{.ar} vol.\ 1, pp.\ 356--357 for its treatment.

In this section we will deal with [مَنْ]{.ar} and [مَا]{.ar}.
We will deal with [أَيّ]{.ar} separately in section\ (give ref) later in this chapter.

Unlike the specific connected nouns ([ٱَلَّذِي]{.ar}, etc.),
the general connected nouns do not vary for number and gender.

For example:

[أُحِبُّّ مَنْ يَعْدِلُ]{.ar}  
"I love [him] who is just."

[أُحِبُّّ مَنْ يَعْدِلُونَ]{.ar}  
"I love [them] who are just."

[ٱِصْنَعْ مَا بَدَا لَكَ.]{.ar}  
"Do what seems (good) to you."

[مَرَرْتُ بِمَا يُعْجِبُكَ.]{.ar}  
"I passed by what will please you."

### [مَنْ]{.ar} and [مَا]{.ar} after prepositions

When [مَنْ]{.ar} and [مَا]{.ar} are directly preceded by the prepositions [مِنْ]{.ar} and [عَنْ]{.ar}, these prepositions lose their [ن]{.ar} and are joined to the following noun with the noun's [م]{.ar} doubled.
For example: 
[مَمَّنْ]{.ar} [mimman]{.trn},
[مَمَّا]{.ar} [mimmA]{.trn},
[عَمَّنْ]{.ar} [eamman]{.trn},
[عَمَّا]{.ar} [eammA]{.trn}.

The preposition [فِي]{.ar} is also often (though not always) optionally attached to these connected nouns, thus: [فِيمَنْ]{.ar} [fIman]{.trn}, [فِيمَا]{.ar} [fImA]{.trn}.

The remaining prepositions follow the normal rules: [عَلَى مَا]{.ar}, [كَمَنْ]{.ar}, etc.
But we will see, if [#allAh]{.trn2} wills, in chapter\ \@ref(questions), that [مَا]{.ar} and [مَنْ]{.ar} are also used as question nouns, in which case the rules of joining prepositions to them will differ.

### The refer-back pronoun for the general connected nouns

The general connected nouns
[مَنْ]{.ar}
and
[مَا]{.ar}
are themselves singular masculine in number and gender.
However, they can be used to signify persons or things of any number and gender.

Their refer-back pronouns can then, optionally:

 i. Either match the gender and number of the persons or things meant by the connected noun. For example:

    [وَمِنْهُمْ مَنْ يَسْتَمِعُونَ إِلَيْكَ]{.ar}  
    "And among them are those who listen to you"  
    10:42

    [قَدْ خَابَتْ مَنْ فَعَلَتْ ذَلِكَ مِنْهُنَّ وَخَسِرَتْ]{.ar}  
    "She has thwarted herself, whoever did that from them~3f~, and lost."  
    [[#jAmie al-#tirmipI]{.trn2}:3318]

    Note also how, in this example how, in addition to the feminine refer-back doer pronouns in [فَعَلَتْ]{.ar} and [خَسِرَتْ]{.ar},
    the feminine gender of the person signified by [مَنْ]{.ar} has also caused the [تْ]{.ar} of femininity to be added to the verb [خَابَ]{.ar} (of which [مَنْ]{.ar} is the doer noun).

    [جَمَعْتُ مِنَ ٱلْوَرَقِ مَا سَقَطْنَ.]{.ar}
    "I gathered what fell from the leaves."

    [صَلِّ مِنَ ٱلرَّكَعَاتِ مَا يَتَيَسَّرْنَ.]{.ar}  
    or  
    [صَلِّ مِنَ ٱلرَّكَعَاتِ مَا تَتَيَسَّرُ.]{.ar}  
    "Pray from the units (of prayer) what is easy."

ii. Or be singular masculine to match the connected noun itself. This is generally more common for [مَا]{.ar}. For example:

    [وَمِنْهُم مَّن يُؤْمِنُ بِهِۦ وَمِنْهُم مَّن لَّا يُؤْمِنُ بِهِۦ ۚ]{.ar}  
    "And of them are those who believe in it, and of them are those who do not believe in it."  
    10:40

    [جَمَعْتُ مِنَ ٱلْوَرَقِ مَا سَقَطَ.]{.ar}
    "I gathered what fell from the leaves."

    [صَلِّ مِنَ ٱلرَّكَعَاتِ مَا يَتَيَسَّرُ.]{.ar}  
    "Pray from the units (of prayer) what is easy."

    [لَمْ أَجِدْ مَا أَعْتَذِرُ بِهِ]{.ar}  
    "I did not find what I (could) make an excuse for with".

Both options can be utilized together as well. For example:

[بَلَىٰ مَنْ أَسْلَمَ وَجْهَهُۥ لِلَّهِ وَهُوَ مُحْسِنٌۭ فَلَهُۥٓ أَجْرُهُۥ عِندَ رَبِّهِۦ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ]{.ar}  
"Yes, [on the contrary], whoever submits his face [i.e., self] in Islām to Allāh while being a doer of good will have his reward with his Lord. And no fear will there be concerning them, nor will they grieve."  
2:112

[فَمَن تَبِعَ هُدَايَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ]{.ar}  
"whoever follows My guidance - there will be no fear concerning them, nor will they grieve."  
2:38

<!--
[ٱُشْكُرْ مَنْ أَحْسَنَ إِلَيْكَ.]{.ar} (refer-back pronoun is the implied sing. masc. doer pronoun of the verb [أَحْسَنَ]{.ar}.)  
or  
[ٱُشْكُرْ مَنْ أَحْسَنُوا إِلَيْكَ.]{.ar} (refer-back pronoun is the implied pl. masc. doer pronoun of the verb [أَحْسَنُوا]{.ar}.)  
"Thank who did good to you."
-->

### Applicability of [مَا]{.ar} and [مَنْ]{.ar} to intelligent and non-intelligent beings {#man-and-maa-for-intelligent}

As we mentioned earlier, [مَنْ]{.ar} is typically used to refer to intelligent beings.
And [مَا]{.ar} is typically used to refer to non-intelligent beings.
However, there are some circumstances in which these roles can differ.

[مَنْ]{.ar}
may be used for non-intelligent beings when a non-intelligent being is compared with an intelligent being.
For example,
 
::: {.otherlanguage data-latex="{arabic}" lang="ar"}
وَاللَّهُ خَلَقَ كُلَّ دَابَّةٍ مِّن مَّاءٍ ۖ
فَمِنْهُم مَّن يَمْشِي عَلَىٰ بَطْنِهِ
وَمِنْهُم مَّن يَمْشِي عَلَىٰ رِجْلَيْنِ
وَمِنْهُم مَّن يَمْشِي عَلَىٰ أَرْبَعٍ ۚ
:::

<!--
[وَاللَّهُ خَلَقَ كُلَّ دَابَّةٍ مِّن مَّاءٍ ۖ ]{.ar}  
[فَمِنْهُم مَّن يَمْشِي عَلَىٰ بَطْنِهِ ]{.ar}  
[وَمِنْهُم مَّن يَمْشِي عَلَىٰ رِجْلَيْنِ ]{.ar}  
[وَمِنْهُم مَّن يَمْشِي عَلَىٰ أَرْبَعٍ ۚ]{.ar}  
-->
"Allāh has created every [living] creature from water. And of them are those that move on their bellies, and of them are those that walk on two legs, and of them are those that walk on four."

[مَنْ]{.ar}
may also be used for non-intelligent beings when 
attributes usually applicable to intelligent beings are applied to a non-intelligent being.
For example:

[أَسِرْبَ الْقَطَا، هَلْ مَنْ يُعِيرُ جَنَاحَه * لَعَلِّي إِلَىٰ مَنْ قَدْ هَوِيتُ أَطِيرُ]{.ar}  
O flock of birds, is there who will lend his wing  
that perhaps I may fly to whom I love  
[أَ]{.ar}: "O",
[سِرْب]{.ar}: "flock",
[قَطَا]{.ar}: a species of bird,
[هَلْ]{.ar}: "is there?",
[يُعِيرُ]{.ar}: "lend",
[جَنَاح]{.ar}: "wing",
[لَعَلِّي]{.ar}: "Perhaps I",
[هَوِيتُ]{.ar}: "I love",
[أَطِيرُ]{.ar}: "I fly".

[مَنْ]{.ar}
may also be used for non-intelligent beings when 
there is a mixed group including both intelligent and non-intelligent beings,
and the intelligent beings are given preference.
For example:

[وَلِلَّهِ يَسْجُدُ مَن فِى ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ]{.ar}  
"And to Allāh prostrates whoever is within the heavens and the earth"  
13:15

Similarly, [مَا]{.ar} may, in some circumstances, be used for intelligent beings. 
This may be when
there is a mixed group including both intelligent and non-intelligent beings,
and the non-intelligent beings are given preference because of their larger number.
For example:

[يُسَبِّحُ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ]{.ar}  
"Whatever is in the heavens and whatever is on the earth is exalting Allāh"  
62:1

[مَا]{.ar} may also be used for intelligent beings when
the person being referred to is vague to the speaker.
For example:

[رَبِّ إِنِّي نَذَرْتُ لَكَ مَا فِي بَطْنِي مُحَرَّرًا]{.ar}  
"My Lord, indeed I have pledged to You what is in my womb, consecrated [for Your service]"  
3:35

[مَا]{.ar} may also be used for intelligent beings when
the characteristics of an intelligent being are highlighted when referring to them. For example:

[فَانكِحُوا مَا طَابَ لَكُم مِّنَ النِّسَاءِ]{.ar}  
"then marry those that please you of [other] women"  
4:3

<!--
http://shiaonlinelibrary.com/%D8%A7%D9%84%D9%83%D8%AA%D8%A8/3954_%D8%B4%D8%B1%D8%AD-%D8%A7%D8%A8%D9%86-%D8%B9%D9%82%D9%8A%D9%84-%D8%A7%D8%A8%D9%86-%D8%B9%D9%82%D9%8A%D9%84-%D8%A7%D9%84%D9%87%D9%85%D8%AF%D8%A7%D9%86%D9%8A-%D8%AC-%D9%A1/%D8%A7%D9%84%D8%B5%D9%81%D8%AD%D8%A9_140#top
footnotes on شرح ابن عقيل ١/١٤٠
-->

### Grammatical position of the general connected nouns

The general connected noun may occur in various grammatical positions. 
Here are some examples:

As a subject:

[ما عِنْدَكُمْ يَنْفَدُ]{.ar}  
"Whatever you have will end"  
16:96

As an information:

[مَالُكَ مَا قَدَّمْتَ، وَمَالُ وَارِثِكَ مَا أَخَّرْتَ]{.ar}  
"Your wealth is what you have sent forward, and the wealth of your inheritors is what you have left behind."  
adab:153

As a doer:

[فَعَلَهُ مَنْ هُوَ خَيْرٌ مِنِّي]{.ar}  
"it was done by one who was better than I"  
bukhari:668

As a doee:

[اعْمَلُوا مَا شِئْتُمْ]{.ar}  
"Do whatever you will"  
41:40

Following a preposition:

[وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ]{.ar}  
"and make me independent from (all) who are besides You"  
tirmidhi:3563

As a base noun in an annexation:

[هُمْ شَرُّ مَنْ خَلَقَ ٱللَّـٰهُ.]{.ar}  
"They are the most evil of whom Allah has created."

[مَا تَرَىٰ رَأْيَ مَا نَرَىٰ.]{.ar}  
"You do not think what we think."  
(literally: "You do not opine the opinion of what we opine.")

[أَمْرَ مَا تَحْذَرُ]{.ar}  
"the matter of which you are wary"

Unlike the specific connected nouns 
([ٱَلَّذِي]{.ar}, etc),
the general connected nouns do not occur as describers.[^connected-noun-describers]

[^connected-noun-describers]: See  [كتاب المقتصد في شرح الإيضاح للجرجاني]{.ar}, vol.\ 1, p.\ 319:

    > [ومَن لا يوصف به، ألا ترى لا تقول: مررت بالرجل مَن أخوه منطلق. فتجعله صفةً للرجل، كما تقول: بالرجل الذي أخوه منطلق]{.ar}

    Also [شرح الرضي على الكافية لابن الحاجب]{.ar} vol.\ 2, p.\ 314:

    > [ولا يقع من الموصولات وصفا إلا ما في أوله اللام، نحو الذي والتي، واللاتي، وبابها، لمشابهته لفظا للصفة المشبهة في كونه على ثلاثة أحرف فصاعدا، بخلاف من وما، وأما (أي) الموصول فلم يقع وصفا، لأن الأغلب فيه: الشرط والاستفهام ووقوعه موصولا قليل فروعي ذلك الأكثر، وإنما يوصف بذو، الطائية وإن كانت على حرفين كما في قوله:]{.ar}
    >
    > [٣٢٧ - فقولا لهذا المرء ذو جاء ساعيا ... هلم فان المشرفي الفرائض]{.ar}

    Basically, of [الأسماء الموصولة المشتركة]{.ar} (which comprise [ما, مَن, أي, أل, ذو, ذا]{.ar}) only the dialectal [ذو]{.ar} appears as a [صفة]{.ar}.

So while we can say:

[مَرَرْتُ بِٱلرَّجُلِ ٱلَّذِي أَحْسَنَ إِلَيّ.]{.ar}  
"I passed by the man who was good to me."

we cannot say:

$\times$ [مَرَرْتُ بِٱلرَّجُلِ مَنْ أَحْسَنَ إِلَيّ.]{.ar}  

We will have to say instead:

[مَرَرْتُ بِمَنْ أَحْسَنَ إِلَيّ.]{.ar}  

The general connected noun can, however, occur as a replacement.^[Fischer §421.2. The example too is taken from there. Originally, it is from [السيرة النبوية لابن هشام]{.ar}.]
For example,

[والمسلمون مَن تبع رسول الله صلى الله عليه وسلم كثير]{.ar}  
"And the Muslims, who follow the Messenger of [#allAh]{.trn2}, are many"

### Use with the preposition [مِنْ]{.ar}

The preposition [مِنْ]{.ar} is frequently used with the general connected nouns to restrict the applicability of the connected noun to a group or type. 
This [مِنْ]{.ar} may come either before the connected noun, or after its connecting sentence.
For example:

<!--[سَأُعْطِيهِ مَا عِنْدِي مِنْ خُبْزٍ.]{.ar}  
"I will give him what I have of bread."-->

[فَأَعْطَانِي مَا كَانَ عِنْدَهُ مِنْ خُبْزٍ.]{.ar}  
"Then he gave me what he had of bread."

[مَنْ دَخَلَ ٱلشَّأْمَ مِنَ ٱلْعَرَبِ]{.ar}  
"Those Arabs who entered Syria"  
(literally: "Who entered Syria from the Arabs")

[فَانكِحُوا مَا طَابَ لَكُم مِّنَ النِّسَاءِ]{.ar}  
"then marry those that please you of [other] women"  
4:3

[اللَّهُمَّ اقْسِمْ لَنَا مِنْ خَشْيَتِكَ مَا يَحُولُ بَيْنَنَا وَبَيْنَ مَعَاصِيكَ]{.ar}  
O [#allAh]{.trn2}, apportion for us, from the fear of You, (that) what shall come between us and disobedience of You  
tirmidhi:3502  
(The connected noun [مَا]{.ar} is the direct doee of the verb of command [اقْسِمْ]{.ar}.)

### Use with a repeated word to express vagueness or uncertainty

The general connected nouns
[مَنْ]{.ar} and [مَا]{.ar}
are used with a word that is repeated to express a vague or uncertain quantity or quality.
For example:

[هُمْ مَا هُمْ]{.ar}  
"They are what they are."

[نَزَلَ مَنْ نَزَلَ مِنْهُمْ]{.ar}  
"Some of them came down."  
(literally: Came down who came down from them.")

[جَمَعْتُ مَا جَمَعْتُ]{.ar}  
"I gathered what I gathered."

## Deleting the refer-back pronoun

The refer-back pronoun may be deleted (and its meaning is then implicit) if some conditions are satisfied.
Some conditions are specific to the state of the refer-back pronoun. These are:

(a) When the refer-back pronoun is the subject of a subject-information sentence, then it may be deleted, and its meaning will be implied.
    When deleting the refer-back pronoun in this case, it is preferred that the connecting sentence not be too short.
    <!--In such cases, the incomplete sentence connecting sentence implcitly includes the meaning of a verb which is usually the verb "being", like "is", "are", "am", etc.-->

    For example:

    [انْظُرُوا إِلَى مَنْ أَسْفَلَ مِنْكُمْ]{.ar}  
    "Look at who is beneath you."  
    [muslim:2963c]  
    (instead of [انْظُرُوا إِلَى مَنْ هُوَ أَسْفَلَ مِنْكُمْ]{.ar})

    [وَلَهُ مَن فِي السَّمَاوَاتِ وَالْأَرْضِ]{.ar}  
    "To Him belongs whoever is in the heavens and the earth."  
    [quran:21/19]  
    (instead of [مَنْ هُوَ فِي ٱلسَّمَوَاتِ وَٱلْأَرْضِ]{.ar})

    [مَا أَنَا بِٱلَّذِي قَائِلٌ لَكَ شَيْـًٔا]{.ar}  
    I am not the one who says anything to you.  
    [Wright vol. ii, §175, p. 322D]  
    (instead of [مَا أَنَا بِٱلَّذِي هُوَ قَائِلٌ لَكَ شَيْـًٔا]{.ar})

    If the connecting sentence is very short, the deleting the refer-back pronoun subject is permissible, though rare. For example:

    [جاء الذي ذَكِيٌّ]{.ar}  
    The one who is smart came.  
    [[شرح ألفية ابن مالك للعثيمين]{.ar}]  
    (instead of [جاء الذي هو ذكي]{.ar})

(b) When the refer-back pronoun is an attached pronoun for the direct doee it is permissible to delete it. For example:

    [هَـٰذَا مَا كَنَزْتُمْ لِأَنْفُسِكُمْ]{.ar}  
    "This is what you hoarded for yourselves"  
    [9:35]  
    (instead of [مَا كَنَزْتُمُوهُ]{.ar})

(c) When the refer-back pronoun is in the i-state, it is permissible to delete it:

    (i) When the refer-back pronoun is the base noun in an annexation whose annex noun is a verbal noun of the doer or the doee implying a present or future meaning. For example:

        [فَاقْضِ مَا أَنتَ قَاضٍ]{.ar}  
        "So decree whatever you are to decree."  
	[quran:20/72]  
        (instead of [فَاقْضِ مَا أَنتَ قَاضِيهِ]{.ar})

	<!--
        [أَخَافُ مِنْهُ ٱلظُّلْمَ ٱلَّذِي هُوَ فَاعِلٌ.]{.ar}  
        "I fear from him the wrong that he will do."

        With the refer-back pronoun restored, the sentence is  
        [أَخَافُ مِنْهُ ٱلظُّلْمَ ٱلَّذِي هُوَ فَاعِلُهُ.]{.ar}  
	-->

    (ii) When the refer-back pronoun is attached to a preposition or adverb, and the same preposition or adverb has already been used (with the same meaning) with the connecting noun or its described noun. The preposition/adverb is deleted along with its attached pronoun. For example:

         <!--
         [سِرْتُ فِي ٱلْحَدِيقَةِ ٱلَّتِي سِرْتَ.]{.ar}  
         "I walked in the (same) garden [in] which you walked."

         With the refer-back pronoun restored, the sentence is  
         [سِرْتُ فِي ٱلْحَدِيقَةِ ٱلَّتِي سِرْتَ فِيهَا.]{.ar}  
         -->

         [أَنَا عِنْدَ مَنْ أَنْتَ.]{.ar}  
         "I am at his [house] at whose you (are)."  
         [Wright vol. ii, §175, p. 323C]  
         (instead of [مَنْ أَنْتَ عِنْدَهُ]{.ar})

         [مَرَرْتُ بِٱلَّذِي مَرَّ سُلَيْمَانُ.]{.ar}  
         "I passed by the (same) one that [#sulaymAn]{.trn2} did."  
         [Wright vol. ii, §175, p. 323D]  
         (instead of [مَرَرْتُ بِٱلَّذِي مَرَّ بِهِ سُلَيْمَانُ.]{.ar})

In addition to the above conditions that are specific to the state of the refer-back pronoun,
a further, general, condition should be satisfied, which is:
that the omission of the refer-back pronoun be obvious to the listener, and the listener can re-construct the original meaning by restoring the refer-back pronoun to get the intended meaning.

If the refer-back pronoun is deleted, and the remaining connecting sentence (with the refer-back pronoun deleted) is valid as a connecting sentence on its own right, then it will give a different meaning (even if slightly) from the original. 
And the listener will not know that the refer-back pronoun has been deleted. 
In this case, it is not permitted to delete the refer-back pronoun. Here is an example that should explain what we mean:

Consider the sentence:

[جاء الذي كَلَّمْتُهُ في داره.]{.ar}  
"The one whom I spoke to (him) in his house, came.  
[modified from example in [شرح ابن عقيل على ألفية ابن مالك]{.ar}]

The connecting sentence is 
[كَلَّمْتُهُ في داره.]{.ar} "I spoke to him in his house."
and the refer-back pronoun is the a-state direct doee pronoun [ه]{.ar} "him".
If we delete this pronoun, the sentence becomes

[جاء الذي كَلَّمْتُ في داره.]{.ar}  
"The one who I spoke in his house, came.

Now the meaning of the sentence is markedly different. The connecting sentence [كَلَّمْتُ فِي دَارِهِ]{.ar} is valid on its own right but it gives a different meaning from the original.
It does not specify that I spoke to _him_ in his house, just that I spoke in his house, possibly to others.
Because the omission of the refer-back pronoun is not obvious, the sentence now does not siginify the original intent. And so deleting the refer-back pronoun in this case is not permitted.

## The general connected noun [أَيّ]{.ar}

TODO.

## Separating the connecting sentence from the connected noun

Generally, the connecting sentence directly follows the connected noun, as in all the examples we have given so far.
However, the connecting sentence may be separated from the connected noun by one of the following:

  i. An oath. For example:

     [جَاءَ ٱلَّذِي وَٱللَّـٰه قَهَرَ ٱلْأَعْدَاءَ.]{.ar}  
     "The one who - by [#allAh]{.trn2} - overpowered the enemies has come."

 ii. A sentence calling out to someone. For example,

     [أَنْتَ ٱلَّذِي يَا زَيْدُ فَتَحْتَ ٱلْبَابَ.]{.ar}  
     "You are the one - O Zayd - who opened the door."

iii. A parenthetical clause, which is a sentence within the main sentence that adds information to it, but which can be deleted without affecting the completeness of the main sentence. For example:

     [قَدِمَ ٱلَّذِي أَطَالَ ٱللَّـٰهُ عُمْرَهُ أَحْسَنَ إِلَيَّ.]{.ar}  
     "The one who - may Allah lengthen his age - was good to me has arrived."

     [قَدِمَ ٱلَّذِي وَهُوَ مُبْتَسِمٌ أَحْسَنَ إِلَيَّ.]{.ar}  
     "The one who - and he is smiling - was good to me has arrived."


## Deleting the connected noun and/or the connecting sentence

TODO. See النحو الوافي

## Sentences without connected nouns

There are some sentences where we might expect a connected noun but which are always, or often (as the case may be), expressed in Arabic without a connected noun. These sentences are of different types:

### Sentences with indefinite nouns needing a qualifying sentence

When an indefinite noun needs a qualifying sentence, it is natural in English to insert "that", "which", "who", etc. between the noun and the following sentence. For example, "I passed by a man _who_ was sleeping."

In Arabic, however, we will not use any connected noun in such sentences. 
This is because the connected nouns are considered definite nouns.
And therefore they may not be a describer to an indefinite noun.
So while we can say:

[مَرَرْتُ بِٱلرَّجُلِ ٱلَّذِي يَنَامُ.]{.ar}  
"I passed by the man who is sleeping."

we cannot say

$\times$ [مَرَرْتُ بِرَجُلٍ ٱلَّذِي يَنَامُ.]{.ar}  

Instead, we put the qualifying sentence directly after the indefinite noun. The qualifying sentence will then not be a connecting sentence, but will itself be the describer to the described noun:

[مَرَرْتُ بِرَجُلٍ يَنَامُ.]{.ar}  
"I passed by a man (who) is sleeping."

Here is another example:

<!--
[أَكَلْتُ طَعَامًا قَدْ بِٱلْمِلْحِ.]{.ar}  
"I ate a food (that) had been seasoned with salt."
-->

[جَلَسْتُ فِي مَجْلِسٍ قَدْ رُشَّ بِمَاءِ ٱلْوَرْدِ.]{.ar}  
"I sat in a sitting (that) had been sprinkled with rose-water."

A connected noun can, however, follow an indefinite noun, if we intend to start a separate sentence with it, or if it is a _replacement_ (see chapter\ \@ref(the-replacement)). For example.

[وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ]{.ar}  
"Resurrect him to a praiseworthy station, the one that you promised him"  
bukhari:614

[وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ]{.ar}  
[الَّذِي جَمَعَ مَالًا وَعَدَّدَهُ]{.ar}  
"Woe to every scorner and mocker  
Who collects wealth and [continuously] counts it."  
104:1-2

### Sentences containing a noun with generic definiteness

Sometimes the definite article [ٱَلْ]{.ar} 
does not determine a particular individual, but
makes a noun definite only in a generic way.
In this case a qualifying sentence may directly follow it without any intermediate connected noun used as a describer.^[Fischer §428.1, Wright vol.\ 2, §172, p.\ 318B.]
Because there is no connected noun, the qualifying sentence is, again, not analyzed as a connecting sentence.
For example:

[كَمَثَلِ الْحِمَارِ يَحْمِلُ أَسْفَارًا]{.ar}  
"like that of a donkey who carries volumes [of books]"  
62:5  
(Note how the translator has actually translated [ٱلْحِمَار]{.ar} as "a donkey" because in English an indefinite noun is often used to indicate a generic type.)


[أَنْتَ ٱلْوَزِيرُ لَا يُعْصَىٰ]{.ar}  
"You are the (sort of) vizier (who) is not disobeyed."

[هُمُ ٱلْفَوَارِسُ يَحْمُونَ ٱلنِّسَاءَ.]{.ar}  
"They are the (kind of) horsemen (who) protect the women."

### Sentences with prepositional or adverbial phrases

If a sentence has a definite noun which is to be qualified by a prepositional or adverbial phrase, then in many cases, that phrase may directly follow the definite noun without any intermediate connected noun used a describer.
But using a connected noun is also permissible if one wishes to emphasize that the specificity of the noun.
When there is no connected noun, the prepositional or adverbial phrase is not analyzed as a connecting sentence, but is considered attached to an implied verb that has the idea of "being", like "is", "are", etc.
When there is a connected noun, then it is analyzed as a connecting sentence, as usual.
For example:

[سِرْتُ فِي ٱلْحَدِيقَةِ عِنْدَ ٱلْمَسْجِدِ.]{.ar}  
"I walked in the garden next to the mosque."  
or  
[سِرْتُ فِي ٱلْحَدِيقَةِ ٱلَّتِي عِنْدَ ٱلْمَسْجِدِ.]{.ar}  
or  
[سِرْتُ فِي ٱلْحَدِيقَةِ ٱلَّتِي هِيَ عِنْدَ ٱلْمَسْجِدِ.]{.ar}  
"I walked in the [specific] garden that [is] next to the mosque."  

## Notes and references

Wright:

   + vol.\ ii, §172, p.\ 317--319: 

From [شرح ابن عقيل على ألفية ابن مالك]{.ar}:

:::{.ar}
وأشار بقوله وأبوا أن يختزل إن صلح الباقي لوصل مكمل إلى أن شرط حذف صدر الصلة أن لا يكون ما بعده صالحا لأن يكون صلة كما إذا وقع بعده جملة نحو جاء الذي هو أبوه منطلق أو هو ينطلق أو ظرف أو جار ومجرور تامان نحو جاء الذي هو عندك أو هو في الدار فإنه لا يجوز في هذه المواضع حذف صدر الصلة فلا تقول جاء الذي أبوه منطلق تعني الذي هو أبوه منطلق لأن الكلام يتم دونه فلا يدرى أحذف منه شيء أم لا؟ وكذا بقية الأمثلة المذكورة ولا فرق في ذلك بين أي وغيرها فلا تقول في يعجبني أيهم هو يقوم يعجبني أيهم يقوم لأنه لا يعلم الحذف ولا يختص هذا الحكم بالضمير إذا كان مبتدأ بل الضابط أنه متى احتمل الكلام الحذف وعدمه لم يجز حذف العائد وذلك كما إذا كان في الصلة ضمير غير ذلك الضمير المحذوف صالح لعوده على الموصول نحو جاء الذي ضربته في داره فلا يجوز حذف الهاء من ضربته فلا تقول جاء الذي ضربت في داره لأنه لا يعلم المحذوف.

وبهذا يظهر لك ما في كلام المصنف من الإبهام فإنه لم يبين أنه متى صلح ما بعد الضمير لأن يكون صلة لا يحذف سواء أكان الضمير مرفوعا أو منصوبا أو مجرورا وسواء أكان الموصول أيا أم غيرها بل ربما يشعر ظاهر كلامه بأن الحكم مخصوص بالضمير المرفوع وبغير أي من الموصولات لأن كلامه في ذلك والأمر ليس كذلك بل لا يحذف مع أي ولا مع غيرها متى صلح ما بعدها لأن يكون صلة كما تقدم نحو جاء الذي هو أبوه منطلق ويعجبني أيهم هو أبوه منطلق وكذلك المنصوب والمجرور نحو جاءني الذي ضربته في داره ومررت بالذي مررت به في داره ويعجبني أيهم ضربته في داره ومررت بأيهم مررت به في داره.
:::

From [تفسير القرطبي]{.ar}:

:::{.ar}
قوله تعالى : ثم آتينا موسى الكتاب مفعولان . تماما مفعول من أجله أو مصدر . على الذي أحسن قرئ بالنصب والرفع . فمن رفع - وهي قراءة يحيى بن يعمر وابن أبي إسحاق - فعلى تقدير : تماما على الذي هو أحسن . قال المهدوي : وفيه بعد من أجل حذف المبتدأ العائد على الذي . وحكى سيبويه عن الخليل أنه سمع " ما أنا بالذي قائل لك شيئا " . ومن نصب فعلى أنه فعل ماض داخل في الصلة ; هذا قول البصريين . وأجاز الكسائي والفراء أن يكون اسما نعتا ل " الذي " وأجازا " مررت بالذي أخيك " ينعتان " الذي " بالمعرفة وما قاربها . قال النحاس : وهذا محال عند البصريين ; لأنه نعت للاسم قبل أن يتم ، والمعنى عندهم : على المحسن .

شرح ابن عقيل:
ذهب الكوفيون إلى أنه يجوز حذف العائد المرفوع بالابتداء مطلقا، أي سواء أكان الموصول أيا أم غيره، وسواء أطالت الصلة أم لم تطل، وذهب البصريون إلى جواز حذف هذا العائد إذا كان الموصول أيا مطلقا، فإن كان الموصول غير أي لم يجيزوا الحذف إلا بشرط طول الصلة، فالخلاف بين الفريقين منحصر فيما إذا لم تطل الصلة وكان الموصول غير أي، فأما الكوفيون فاستدلوا بالسماع، فمن ذلك قراءة يحيى بن يعمر:
(تماما على الذي أحسن) قالوا: التقدير على الذي هو أحسن، ومن ذلك قراءة مالك ابن دينار وابن السماك: (إن الله لا يستحيي أن يضرب مثلا ما بعوضة فما فوقها) قالوا:
التقدير: مثلا الذي هو بعوضة فما فوقها، ومن ذلك قول الشاعر:
لا تنو إلا الذي خير، فما شقيت * إلا نفوس الألى للشر ناوونا قالوا: التقدير لا تنو إلا الذي هو خير، ومن ذلك قول الآخر:
من يعن بالحمد لم ينطق بما سفه ولا يحد عن سبيل المجد والكرم قالوا: تقدير هذا البيت: من يعن بالحمد لم ينطق بالذي هو سفه، ومن ذلك قول عدي بن زيد العبادي:
لم أر مثل الفتيان في غبن * الأيام يدرون ما عواقبها قالوا: ما موصولة، والتقدير: يدرون الذي هو عواقبها.
وبعض هذه الشواهد يحتمل وجوها من الاعراب غير الذي ذكروه، فمن ذلك أن " ما " في الآية الثانية يجوز أن تكون زائدة، وبعوضة خبر مبتدأ محذوف، ومن ذلك أن " ما " في بيت عدي بن زيد يحتمل أن تكون استفهامية مبتدأ، وما بعدها خبر، والجملة في محل نصب مفعول به ليدرون، وقد علق عنها لأنها مصدرة بالاستفهام، والكلام يطول إذا نحن تعرضنا لكل واحد من هذه الشواهد، فلنجتزئ لك بالإشارة.
:::



