# Significance of the ;ism_fail;

;wip_warn;


## Introduction

The ;ism_fail;
is technically a noun.
But because of its derivation,
and close association with the verb,
it can have some verbal qualities.
We have already seen in chapter\ (ref) how the ;ism_fail; can, like a verb,
govern a ;faa3il; and a ;mafulb;

In this chapter,
we will study the meanings that the ;ism_fail; can signify,
especially when it behaves as a verb-like governor.

## The essential significance of the ;ism_fail;

The ;ism_fail; is derived from a verb.
For example,
the ;ism_fail;
[منطلق]{.ar}
is derived from the verb
[انطلق ينطلق]{.ar}
[to set out]{.trans}.
The essential significance of the ;ism_fail; is
that its referent can be described as the doer of the action of its verb.
Consider the example:

(@ma3aami_mush_zaydun_muntaliqun) [زيد منطلق]{.ar}
    [@za3balawi_dirasat@ 486 citing [الجرجاني]{.ar}]{.citex}
    [Zayd is a setter out.]{.trans}

In example () above
[منطلق]{.ar}
essentially signifies that its referent
[زيد]{.ar}
can be described as one who sets out.
As opposed to the ;ism_fail;,
the essential significance of the ;mudarie; verb is the dynamic execution of the action of the verb.
For example:

(@ma3aami_mush_zaydun_yantaliqu) [زيد ينطلق]{.ar}
    [@za3balawi_dirasat@ 486 citing [الجرجاني]{.ar}]{.citex}
    [Zayd is setting out.]{.trans}  
    or [Zayd sets out.]{.trans}  
    or [Zayd will set out.]{.trans} 

In example () above,
the ;mudarie; verb
[ينطلق]{.ar} indicates the dynamic action of setting out.

Here is another example of a ;ism_fail; used to signify the doer of a verb.
This time the ;ism_fail; is from a transitive noun and is governing a ;mafulb;.

(@ism_fail_nasai_3498) [وَأَنَا **مُتَّبِعٌ** فِي ذَلِكَ قَضَاءَ رَسُولِ اللَّهِ صلى الله عليه وسلم فِي مَرْيَمَ الْمَغَالِيَّةِ]{.ar}
    [@https://sunnah.com/nasai:3498@]{.citex}  
    [I am **a follower**, in that [matter], **of** the ruling of the Messenger of [#allAh]{.trn2} ;pbuh; concerning Maryam al-[#magAliyyah]{.trn2}.]{.trans}

<!--
The difference between the essential significance of the ;ism_fail;
and the essential significance of the verb is highlighted in 
 [سورة الكافرون]{.ar}:

::: {.quran}
قُلۡ یَـٰۤأَیُّهَا ٱلۡكَـٰفِرُونَ۝
لَاۤ أَعۡبُدُ مَا تَعۡبُدُونَ۝
وَلَاۤ أَنتُمۡ عَـٰبِدُونَ مَاۤ أَعۡبُدُ۝
وَلَاۤ أَنَا۠ عَابِدࣱ مَّا عَبَدتُّمۡ۝
وَلَاۤ أَنتُمۡ عَـٰبِدُونَ مَاۤ أَعۡبُدُ۝
لَكُمۡ دِینُكُمۡ وَلِیَ دِینِ۝
:::



[@https://quran.com/109@]{.citex}  
_Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you worship. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."_

[#ibn al-#qayyim]{.trn2} says,
in the [tafsIr]{.trn2} of this ;surah;:

> Negation isn't employed for [the disbelievers] except by the ;ism_fail;. And for [the Prophet ;pbuh;], [negation] is employed once using the verb, and once using the ;ism_fail;.
>
> And this is -- and [#allAh]{.trn2} knows best -- due to a marvelous wisdom, which is that the greater objective is [the Prophet's ;pbuh;] disassociation from their gods from every perspective and in every [instance of] time.
> So [the Prophet ;pbuh;, in speaking to the disbelievers with the words of the revealed ;surah;], used first the verb [[أَعْبُدُ]{.ar}],
> which signifies dynamic occurrence,
> and then used for this same negation the ;ism_fail; [[عَابِد]{.ar}] in the second instance,
> i.e. "This [worshipping of what you worship] is not my description nor my state of affairs."
> [This is] as if he had said: "Worshipping other than [#allAh]{.trn2} will not be an verbal action of mine, nor a descrption of mine."
> Thus he used two negations for two negated items [a verbal action, and a description], that are intended by the negation.
>
> As for [the negation used for the disbelievers], he used only the ;ism_fail; [عَابِدُونَ]{.ar},
> which signifies the description [of its referent by the ;ism_fail;] and the stability [of this description],
> i.e. "The stable, requisite, description [of being a worshipper] of [#allah]{.trn2} is negated from you.
> For this description cannot be established for you.
> It is only established for the one who singles out [#allAh]{.trn2} exclusively for worship,
> and then does not associate anyone with Him.
> But you, because you have worshipped other than Him, are not from His worshippers."
> Even if they may have worshipped [#allAh]{.trn2} some of the time.
> For the polytheist worships [#allAh]{.trn2} and worships, with Him, others besides Him.
> Just like the People of the Cave said:
> [And when you have withdrawn from them and that which they worship other than Allāh]{.trans} [@https://quran.com/18/16@]{.citex}
> i.e., "you have withdrawn from their gods, except [#allAh]{.trn2}, for you have not withdrawn from Him."
> And similarly did the polytheists say regarding their gods:
> ["We only worship them that they may bring us nearer to Allāh in position."]{.trans} [@https://quran.com/39/3@]{.citex}.
> Thus they used to worship, with Him, others besides Him.
> So the verb [[عَبَدَ يَعْبُدُ]{.ar}] is not negated from them because of its occurrence from them.
> But the description [[عَابِد]{.ar}] is negated because whoever worshipped other than [#allAh]{.trn2}
> is not established on the worship of [#allAh]{.trn2}, and is not described by [being a worshipper of [#allAh]{.trn2}].^[@https://tafsir.app/ibn-alqayyim/109/6@]

-->

In
the following sections, 
we will see that the ;ism_fail;,
while retaining its essential significance of describing its referent as the doer of a verb,
can also signify the meaning of the verb from which it is described.
So it can signify the occurrence of the action of the verb and its tense.

For example,
(@ma3aami_mush_zaydun_muntaliqun) [زيد منطلق]{.ar} can be used 
in place of (@ma3aami_mush_zaydun_yantaliqu) [زيد ينطلق]{.ar}
to mean
[Zayd is setting out]{.trans}, or
[Zayd sets out]{.trans}, or
[Zayd will sets out]{.trans}.

<!--
But it does this while (typically)
retaining its essential significance of describing its referent as the doer of a verb,
We will describe this usage of the ;ism_fail; in place of a verb in the next few sections, ;ia;.
-->

## The ;ism_fail; without [ٱلْ]{.ar} used to indicate a imperfect static state

When we consider a verbal action,
it can,
in general,
have a static and a dynamic perspective
The dynamic perspective of looking at a verbal action focuses on the dynamic activity of the doer as he undertakes the verbal action.
So, for example, if someone is eating, then the dynamic perspective of looking at this activity is considering the doer's action of lifting his hand from his plate to his mouth,
chewing, swallowing, etc.

The static perspective of looking at a verbal action focuses
more on fact that the person can be described as being in a state of doing the action.
And not so much on the actual activity involved.
So, the static perspective of considering someone eating is simply that the person was in a state where he can be described as eating.

Some verbs,
just from their meaning,
tend to be more dynamic than others.
For example:
[جَرَى]{.ar} [to run]{.trans},
[أَكَلَ]{.ar} [to eat]{.trans},
etc.

Other verbs are inherently more static.
For example:
[جَلَسَ]{.ar} [to sit]{.trans},
[نَامَ]{.ar} [to sleep]{.trans},
etc.

Some verbs have, inherently, both a dynamic and a static meaning.
For example,
[لَبِسَ]{.ar} can mean both: to put on a garment, and also to remain clothed in the garment..
Even static verbs can have a dynamic component.
For example,
[جَلَسَ]{.ar} can mean both: to enter into a seated state (from another position like standing, etc.), and also to remain in a seated state.

<!--
When we discuss the significance of the ;ism_fail;,
we will talk about how _static_ or _dynamic_ a lexeme is.
A dynamic lexeme is one which indicates continual activity or change, e.g.
[جَرَى]{.ar} [to run]{.trans},
[أَكَلَ]{.ar} [to eat]{.trans},
etc.
A static lexeme
on the other hand,
indicates remaining in an steady and relatively unchanging state, e.g.
[نَامَ]{.ar} [to sleep]{.trans},
[قَامَ]{.ar} [to stand]{.trans},
[طَهُرَ]{.ar} [to be pure]{.trans},
etc.

Even within these verbs, there is considerable variation in staticity.
For example,
[طَهُرَ]{.ar} [to be pure]{.trans}
involves virtually no dynamicity.
Other verbs can have both a static and a dynamic aspect.
For example:
[جَلَسَ]{.ar} to sit,
[قَامَ]{.ar} to stand,
[نَامَ]{.ar} to sleep,
[لَبِسَ]{.ar} to wear,
etc.
These verbs often mean both: to do an action of entering into a state, and also to remain in such a state.
For example,
[جَلَسَ]{.ar} can mean both: to enter into a seated state (from another position like standing, etc.), and also to remain in a seated state.
Similarly,
[لَبِسَ]{.ar} can mean both: to put on a garment, and also to be in a state of having put on the garment.
-->


<!--
One of the more common usages of the ;ism_fail; is to indicate that the ;faa3il; is in an imperfect static state.
The term _static state_ here means remaining in a stationary condition or position as opposed to a dynamic action.
-->
<!--
The word "static" here signifies that the state of the ;faa3il; 
is steady and relatively unchanging.
-->

<!--
As we discuss the state indicated by an ;ism_fail; we will often deal with _stative_ verbs.
_Stative_ verbs are those which mean to be in a state.
For example:
[جَلَسَ]{.ar} to sit,
[قَامَ]{.ar} to stand,
[نَامَ]{.ar} to sleep,
[لَبِسَ]{.ar} to wear,
etc.
These verbs often mean both: to do an action of entering into a state, and also to remain in such a state.
For example,
[جَلَسَ]{.ar} can mean both: to enter into a seated state (from another position like standing, etc.), and also to remain in a seated state.
Similarly,
[لَبِسَ]{.ar} can mean both: to put on a garment, and also to be in a state of having put on the garment.
-->

As a general trend,
the ;ism_fail; is used to indicate a static state.
In contrast to the ;ism_fail;, the ;mudarie; verb indicates that the doer is doing a dynamic action.

By the way,
when we say "static state" we mean it semantically.
The state or condition of an entity can also be indicated syntactically using the ;hal; (see chapter\ (ref)).
These two (semantic and syntactic) aspects of indicating being in a state are often combined.
So, we will see from the examples in this section that
the ;ism_fail; is often (but not always) either a ;hal;, or part of a ;hal; sentence.

Consider the following example:

(@ex000416) [كُنْتُ مُسَافِرًا فَأَتَيْتُ النَّبِيَّ صلى الله عليه وسلم وَهُوَ **يَأْكُلُ** وَأَنَا **صَائِمٌ**]{.ar}
    [@https://sunnah.com/nasai:2281@]{.citex}  
    "I was traveling and I came to the Prophet while he was **eating** and I was **fasting**."

The verb [يَأْكُلُ]{.ar} indicates a dynamic activity, where the ;faa3il; is actively eating.
Whereas the ;ism_fail; [صَائِم]{.ar} calls attention to the ;faa3il;'s being in a (static) state of fasting, and not to his actively doing the activity of fasting.

Even when a verb that is associated with a dynamic activity,
its ;ism_fail; can be used instead of the verb when the 
purpose is to indicate the ;faa3il;'s _being in a state_ of doing the activity,
rather than to indicate the dynamic activity of the verb.
For example:

(@ex000417) [فَلَبِثَ الْأَوْسُ وَالْخَزْرَجُ **مُتَحَارِبِينَ** عِشْرِينَ سَنَةً فِي أَمْرِ سُمَيْرٍ]{.ar}
    [marmor 134]{.citex}  
    "So [al-E#aws]{.trn2} and [al-#xazraj]{.trn2} stayed **(in a state of) fighting each other** for twenty years because of the matter of Sumayr."

(@ex000418) [فَمَا الَّذِي أَنْتَ فِيهِ الْآنَ **مُجْمِعٌ**]{.ar}
    [marmor 99A]{.citex}  
    "So what is it that you are now (in a state of being) **decided** about?

Here are some more examples of the the ;ism_fail; being used to indicate being in a static state:

(@ex000419) [لَمَّا كَانَ يَوْمَ أُحُدٍ انْهَزَمَ النَّاسُ عَنِ النَّبِيِّ صلى الله عليه وسلم وَأَبُو طَلْحَةَ بَيْنَ يَدَىِ النَّبِيِّ صلى الله عليه وسلم **مُجَوِّبٌ** عَلَيْهِ بِحَجَفَةٍ لَهُ]{.ar}
    [@https://sunnah.com/bukhari:4064@]{.citex}  
    "When it was the day of [#uHud]{.trn2}, the people left the Prophet ;pbuh; while [#abU #TalHah]{.trn2} was in front of the Prophet ;pbuh;, **shielding** him with a leather shield of his."

(@ex000420) [فَخَرَجَ النَّبِيُّ صلى الله عليه وسلم وَهُوَ **مُشْتَمِلٌ** عَلَى شَيْءٍ]{.ar}
    [@https://sunnah.com/tirmidhi:3769@]{.citex}  
    "So the Prophet ;pbuh; came out while he was **(in a state of) covering** something [with his garment]."

(@ex000421) [وَإِذَا هُوَ **مُعْتَمِدٌ** عَلَى عَصًا فِي صَلاَتِهِ فَقُلْنَا بَعْدَ أَنْ سَلَّمْنَا . فَقَالَ حَدَّثَتْنِي أُمُّ قَيْسٍ بِنْتُ مِحْصَنٍ أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم لَمَّا أَسَنَّ وَحَمَلَ اللَّحْمَ اتَّخَذَ عَمُودًا فِي مُصَلاَّهُ **يَعْتَمِدُ** عَلَيْهِ]{.ar}
    [@https://sunnah.com/abudawud:948@]{.citex}  
    "And incidentally, he was **resting** on a staff in his prayer. We [asked] him (about resting on the staff) after we had given the salutation; He said: Umm Qays daughter of [#miHSan]{.trn2} said to me that when the Messenger of Allah ;pbuh; became aged and the flesh grew increasingly on him, he took a prop at his place of prayer and he **would rest** on it."  
    (Note how the ;ism_fail; [مُعْتَمِد]{.ar} indicates a state and the ;mudarie; verb [يَعْتَمِدُ]{.ar} indicates the activity."

(@ex000422) [فَبَيْنَا أَنَا **نَازِلٌ** تَحْتَ شَجَرَةٍ إِذَا رَسُولُ اللَّهِ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/malik/48/1@]{.citex}  
    While I was **in a dismounted state** under a tree, the Messenger of Allah [came]

(@ex000423) [إِذَا مَرِضَ الْعَبْدُ أَوْ سَافَرَ، كُتِبَ لَهُ مِثْلُ مَا كَانَ يَعْمَلُ **مُقِيمًا** صَحِيحًا]{.ar}
    [@https://sunnah.com/bukhari/56@]{.citex}  
    When a slave journeys or falls ill, a [similar reward] is written for him as what he used to do while **staying** (i.e. not journeying) [and] healthy.

(@ex000424) [إِنَّ أُمِّي قَدِمَتْ وَهْىَ **رَاغِبَةٌ**]{.ar}
    [@https://sunnah.com/bukhari:5979@]{.citex}  
    My mother has arrived and she is desirous (of my favor).

### The ;mafulb; of the ;ism_fail; when indicating a static state

When the ;ism_fail; is dervied from a transitive verb,
then the ;ism_fail;,
when indicating a static state,
may take a ;mafulb;
(as long as it satisifes the conditions specified in section\ (ref)).
For example:

(@ex000425) [مَنْ كَانَ مِنْكُمْ **مُلْتَمِسًا لَيْلَةَ** الْقَدْرِ فَلْيَلْتَمِسْهَا فِي الْعَشْرِ الْأَوَاخِرِ وِتْرًا]{.ar}
    [@https://sunnah.com/ahmad:298@]{.citex}  
    "Whoever amongst you is **seeking** the Night of Decree, then let him seek it in the last ten days of [#ramaDAn]{.trn2}, [in the] the odd [nights]."  
    (Note the the ;ism_fail; [مُلْتَمِسًا]{.ar} has a ;mafulb; [لَيْلَةَ الْقَدْرِ]{.ar}.)

(@ex000426) [إِنَّهُ كَانَ يُصَلِّي وَهُوَ **مُسْبِلٌ إِزَارَهُ**]{.ar}
    [@https://sunnah.com/abudawud:638@, graded weak by [al-E#albAni]{.trn2}]{.citex}  
    "Indeed he was praying while **trailing** his lower garment."

(@ex000427) [وَوَقَفْتُ عِنْدَ بَابِ عَائِشَةَ فَإِذَا هُوَ **مُسْتَقْبِلٌ الْمَغْرِبَ**]{.ar}
    [@https://sunnah.com/adab:451@]{.citex}  
    "And I stopped at the door of [#eAEicah]{.trn2} and incidentally, it was facing the west."

(@ex000428) [كَانَ رَسُولُ اللَّهِ صلى الله عليه وسلم **حَامِلَ الْحَسَنِ** بْنِ عَلِيٍّ عَلَى عَاتِقِهِ]{.ar}
    [@https://sunnah.com/tirmidhi:3784@]{.citex}  
    "The Messenger of Allah ;pbuh; was carrying [al-#Hasan ibn #ealiyy]{.trn2} on his shoulder"  
    ([حَامِلَ الْحَسَنِ]{.ar} is a ;lafzi; ;idaafah;.)

(@ex000429) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم كَانَ يُصَلِّي وَهُوَ **حَامِلٌ أُمَامَةَ**]{.ar}
    [@https://sunnah.com/nasai:1204@]{.citex}  
    "that the Messenger of Allah used to pray while he [was] **carrying** [#umAmah]{.trn2}"

(@ism_fail_wearing_bedsheet) [أَنَّ أَبَا بَكْرٍ اسْتَأْذَنَ عَلَى رَسُولِ اللَّهِ صلى الله عليه وسلم وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ **لاَبِسٌ مِرْطَ** عَائِشَةَ]{.ar}
    [@https://sunnah.com/muslim:2402a@]{.citex}  
    "that [#abU #bakr]{.trn2} sought permission from the Messenger of Allah ;pbuh; [for entrance in his apartment] while he was lying on his bed having on him [#eAEicah]{.trn2}'s bed-sheet."

However, when the main intent is to indicate the state of the ;faa3il;
independent of the action of the ;faa3il; upon any ;maful;,
then the ;ism_fail; can occur without a ;mafulb;.
For example:

(@ex000430) [قَالَ عُثْمَانُ أَجَلْ وَلَكِنَّا كُنَّا **خَائِفِينَ**]{.ar}
    [@https://sunnah.com/ahmad:431@]{.citex}  
    [#euvman]{.trn2} said, "Yes, but we were in a state of fear."

In such cases,
the ;ism_fail; can be followed with a verb (typically its own), specifying the ;mafulb;.
For example:

(@ex000431) [فَخَرَجْنَا **خَائِفِينَ** **نَخَافُ الرَّصَدَ**]{.ar}
    [maghazi 28 cited by @marmor_tense@ 138]{.citex}  
    "So we set out afraid, fearing ambush."


(@3amal_ism_fail_3aamilun_ya3mal) [وَرُزَيْقٌ **عَامِلٌ** عَلَى أَرْضٍ **يَعْمَلُهَا**]{.ar}
    [@https://sunnah.com/bukhari:893@]{.citex}  
    "Ruzayq was (in a state of) working on the land, working (i.e. farming) it."  

<!--
### The ;ism_fail; indicating a habitual state

The static state that is indicated by the ;ism_fail; often tends to be continuous rather than habitual.
But the ;ism_fail; can also indicate a habitual state.
For example:

(@ex000432) [عَنِ النَّبِيِّ ﷺ أَنَّهُ قَالَ لَا يَدْخُلُ الْجَنَّةَ مَنَّانٌ وَلَا **عَاقٌّ وَالِدَيْهِ** وَلَا مُدْمِنُ خَمْرٍ]{.ar}
    [https://hadithunlocked.com/ahmad:6882]{.citex}  
    [It was narrated] from the Prophet ;pbuh; that he said: "One who reminds people (of what he has given them) will not enter Paradise, nor will **one who disobeys** his parents, nor one addicted to wine."


(@ex000433) [زَيْدٌ مُكْرِمٌ ضِيفَانِهِ]{.ar}
    [[@za3balawi_dirasat@ 482](https://shamela.ws/book/2120/482)]{.citex}  
    [[Zayd is hospitable to his guests]{.trans}  
-->

### The ;ism_fail; for verbs of posture

Verbs of posture inlude:
[جَلَسَ]{.ar} to sit,
[قَامَ]{.ar} to stand,
[اضْطَجَعَ]{.ar} to lie down,
etc.

With such verbs,
the ;mudarie; verb,
when used for the present or past,
tends to be used only for the habitual tense and not for the continuous tense.
So if we say
[يَجْلِسُ زَيْدٌ]{.ar}
then it will usually mean _Zayd sits_ and not _Zayd is sitting_.

For the continuous tense,
only
the ;ism_fail; tends to be used.
So, in order to say _Zayd is sitting_ we will usually say
[زَيْدٌ جَالِسٌ]{.ar}.

Here are some examples of the ;ism_fail; and ;mudarie; verb for verbs of posture:

#### The ;ism_fail; for verbs of posture indicating the continuous tense {.unnumbered}

(@ex000434) [رَأَيْتُ النَّبِيَّ صلى الله عليه وسلم **مُقْعِيًا** يَأْكُلُ تَمْرًا]{.ar}
    [@https://sunnah.com/muslim:2044a@]{.citex}  
    "I saw the Prophet ;pbuh; squatting, eating dates."

(@ex000435) [قَالَ كُنْتُ مُتَّكِئًا عِنْدَ عَائِشَةَ]{.ar}
    [@https://sunnah.com/muslim:177a@]{.citex}  
    "I was resting at [the house of] [#eAEicah]{.trn2}"

(@ex000436) [لاَ أُلْفِيَنَّ أَحَدَكُمْ مُتَّكِئًا عَلَى أَرِيكَتِهِ ...]{.ar}
    [@https://sunnah.com/abudawud:4605@]{.citex}  
    "Let me not find one of you reclining on his couch ..."

(@ex000437) [أَنَّ أَبَا بَكْرٍ رَضِيَ اللَّهُ عَنْهُ اسْتَأْذَنَ عَلَى رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَهُوَ **مُضْطَجِعٌ** عَلَى فِرَاشِهِ لَابِسٌ مِرْطَ عَائِشَةَ]{.ar}
    [@https://sunnah.com/ahmad:514@]{.citex}  
    "that [#abU #bakr]{.trn2} sought permission from the Messenger of Allah ;pbuh; [for entrance in his apartment] while he was **lying** on his bed having on him [#eAEicah]{.trn2}'s bed-sheet."

(@ex000438) [كُنْتُ **جَالِسًا** عِنْدَ مُعَاوِيَةَ، فَحَدَّثَ نَفْسَهُ ثُمَّ انْتَبَهَ]{.ar}
    [@https://sunnah.com/adab:564@]{.citex}  
    "I was **sitting** with [#mueAwiyah]{.trn2} when he [muttered to] himself, then he came to his senses."

(@ex000439) [إِنِّي لَجَالِسٌ مَعَ عَبْدِ اللَّهِ وَأَبِي مُوسَى وَهُمَا يَتَحَدَّثَانِ]{.ar}
    [@https://sunnah.com/muslim:2672d@]{.citex}  
    I was sitting with [#eabd #allAh]{.trn2} and [#abU #mUsA]{.trn2} while they were talking to each other.

(@ex000440) [سَقَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم مِنْ زَمْزَمَ فَشَرِبَ وَهُوَ **قَائِمٌ**]{.ar}
    [@https://sunnah.com/muslim:2027a@]{.citex}  
    I served the Messenger of Allah some Zamzam and he drank (it) while he was **standing**.

(@ex000441) [هَلْ كَانَ النَّبِيُّ صلى الله عليه وسلم يُصَلِّي وَهُوَ **قَاعِدٌ**]{.ar}
    [@https://sunnah.com/muslim:732a@]{.citex}  
    Did the Prophet ;pbuh; pray while he was **sitting**?

#### The ;mudarie; verb for for verbs of posture indicating the habitual tense {.unnumbered}

(@ex000442) [تِلْكَ صَلاَةُ الْمُنَافِقِ **يَجْلِسُ** يَرْقُبُ الشَّمْسَ حَتَّى إِذَا كَانَتْ بَيْنَ قَرْنَىِ الشَّيْطَانِ قَامَ فَنَقَرَ أَرْبَعًا لاَ يَذْكُرُ اللَّهَ فِيهَا إِلاَّ قَلِيلاً]{.ar}
    [@https://sunnah.com/tirmidhi:160@]{.citex}  
    That is the prayer of the hypocrite. He sits watching the sun, until when it is between the horns of the devil he stands and pecks out four (units of prayer), not remembering Allah in them but a little."

(@ex000443) [كُنْتُ **أَقْعُدُ** مَعَ ابْنِ عَبَّاسٍ، يُجْلِسُنِي عَلَى سَرِيرِهِ]{.ar}
    [@https://sunnah.com/bukhari:53@]{.citex}  
    I used to sit with Ibn [#eabbAs]{.trn2} and he would seat me on his couch.

(@ex000444) [كَانَ جِذْعٌ يَقُومُ إِلَيْهِ النَّبِيُّ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/bukhari:918@]{.citex}  
    [There] was a stem (of a date palm) [which] the Prophet ;pbuh; would stand against.

(@ex000445) [وَيَرْكَعُ رَكْعَتَيْنِ قَبْلَ صَلاَةِ الْفَجْرِ ثُمَّ يَضْطَجِعُ عَلَى شِقِّهِ الأَيْمَنِ حَتَّى يَأْتِيَهُ الْمُؤَذِّنُ لِلصَّلاَةِ]{.ar}
    [@https://sunnah.com/bukhari:994@]{.citex}  
    And he would pray two units [of (sunnah) prayer] before the Fajr prayer, then he **would lie** on his right side until the [muEappin]{.trn2} would come to him for the (obligatory) prayer"

Rarely, the ;mudarie; verb has been found to be used to indicate a continuous tense.
But in such cases it will likely be in a ;hal; or with an adverb which will help indicate its continuous, rather than habitual, significance.
Examples:

(@ex000446) [أَنَّهُ رَأَى رَجُلاً **يَتَّكِئُ** عَلَى يَدِهِ الْيُسْرَى]{.ar}
    [@https://sunnah.com/abudawud:994@]{.citex}  
    that he saw a man **reclining** on his left hand

(@ex000447) [ رَأَيْتُ عُمَرَ بْنَ الْخَطَّابِ وَهُوَ **يَجْلِسُ** وَالنَّاسُ مَعَهُ]{.ar}
    [tarikh tabari 3/429]{.citex}  
    I saw [#eumar ibn al-#xaTTAb]{.trn2} while he [was] **sitting** while the people [were] with him


#### Transitive verbs of posture {.unnumbered}

The verbs of posture are usually intransitive verbs,
as you can see in the examples so far.
But a transitive verb of posture can also be used.
For example:

(@ex000448) [سَأَلْتُ ابْنَ عَبَّاسٍ وَهُوَ **مُسْنِدٌ ظَهْرَهُ** إِلَى الْكَعْبَةِ عَنِ الْبَاذَقِ]{.ar}
    [@https://sunnah.com/nasai:5687@]{.citex}  
    I asked Ibn [#eabbAs]{.trn2}, while he was leaning his back against the [#kaebah]{.trn2}, about (a drink called) [al-#bApaq]{.trn2}

(@ex000449) [وَقَدْ كُنْتُ **مُسْنِدَتَهُ** إِلَى صَدْرِي]{.ar}
    [@https://sunnah.com/bukhari:2741@]{.citex}  
    "I had been leaning him against my chest."

(@ex000450) [فَبَيْنَا أَنَا قَاعِدٌ وَرَسُولُ اللَّهِ صلى الله عليه وسلم **مُتَوَسِّدٌ فَخِذِي**]{.ar}
    [@https://sunnah.com/tirmidhi:2861@]{.citex}  
    So while I was sitting and the Prophet ;pbuh; [was] using my thigh as a headrest

#### Other verbs that have similar behavior to the verbs of posture {.unnumbered}

In addition to verbs of posture,
there are a few other verbs that indicate 
show the same distiction of the ;ism_fail; being used for the continous tense and the ;mudarie; verb for the habitual tense.
For example:
[نَامَ]{.ar} _to sleep_,
[صَامَ]{.ar} _to fast_.
The reason that these verbs show the same behavior as verbs of posture may be that the ;faa3il; is not actively _doing_ anything except remaining in a condition.
Here are some examples with these verbs:

(@ex000451) [ قُلْنَا لِعَمْرٍو إِنَّ نَاسًا يَقُولُونَ إِنَّ النَّبِيَّ صلى الله عليه وسلم **تَنَامُ** عَيْنُهُ وَلاَ **يَنَامُ** قَلْبُهُ]{.ar}
    [@https://sunnah.com/bukhari:859@]{.citex}  
    "We said to [#eamr]{.trn2}: 'Indeed some people say that the Prophet ;pbuh; his eye sleeps but his heart does not sleep.'"

(@ex000452) [جَاءَتْ مَلاَئِكَةٌ إِلَى النَّبِيِّ صلى الله عليه وسلم وَهْوَ **نَائِمٌ** فَقَالَ بَعْضُهُمْ إِنَّهُ **نَائِمٌ** وَقَالَ بَعْضُهُمْ إِنَّ الْعَيْنَ **نَائِمَةٌ** وَالْقَلْبَ يَقْظَانُ]{.ar}
    [@https://sunnah.com/bukhari:7281@]{.citex}  
    Some angels came to the Prophet ;pbuh; while he was sleeping. Some of them said, "He is sleeping." Some [others] of them said, "His eye[s] are sleeping but his heart is awake."

(@ex000453) [إِنِّي رَجُلٌ **أَصُومُ** أَفَأَصُومُ فِي السَّفَرِ]{.ar}
    [@https://sunnah.com/muslim:1121d@]{.citex}  
    "I am a man who [habitually] fasts, so should I fast in journeying?"

(@ex000454) [سِرْنَا مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم وَهُوَ **صَائِمٌ**]{.ar}
    [@https://sunnah.com/muslim:1101c@]{.citex}  
    We travelled with the Messenger of Allah ;pbuh; while he [was] fasting.

### The ;ism_fail; for verbs of motion

The ;ism_fail; is very common with verbs of motion, like:
[ذَهَبَ]{.ar} to go,
[مَشَى]{.ar} to walk,
[رَجَعَ]{.ar} to return,
[سَارَ]{.ar} to travel,
etc.
The ;ism_fail; for these verbs again indicates the situation of being in a move rather than the actual dynamic movement.^[@marmor_tense@ 127]
For example:

(@ex000455) [وَذَلِكَ الْمَسْجِدُ عَلَى حَافَةِ الطَّرِيقِ الْيُمْنَى، وَأَنْتَ **ذَاهِبٌ** إِلَى مَكَّةَ]{.ar}
    [@https://sunnah.com/bukhari:485@]{.citex}  
    And that mosque is on the right edge of the path as you are **going** to Makkah

(@ex000456) [كَانَ النَّبِيُّ صلى الله عليه وسلم يَأْتِي قُبَاءً رَاكِبًا وَمَاشِيًا]{.ar}
    [@https://sunnah.com/bukhari:1194@]{.citex}  
    The Prophet ;pbuh; used to come to [#qubAE]{.trn2} while riding and while walking.

(@ex000457) [لَحِقَنِي عَبَايَةُ بْنُ رَافِعٍ وَأَنَا مَاشٍ، إِلَى الْجُمُعَةِ]{.ar}
    [@https://sunnah.com/nasai:3116@]{.citex}  
    [#eabAyah ibn #rAfie]{.trn2} joined me while I was **walking** to the [jumueah]{.trn2}

(@ex000458) [كُنْتُ **مُسَافِرًا** فَأَتَيْتُ النَّبِيَّ صلى الله عليه وسلم وَهُوَ يَأْكُلُ وَأَنَا صَائِمٌ]{.ar}
    [@https://sunnah.com/nasai:2281@]{.citex}  
    "I was journeying and I came to the Prophet ;pbuh; while he was eating and I was fasting."

(@ex000459) [بَيْنَا النَّبِيُّ ﷺ سَائِرٌ إِلَى تَبُوكَ نَزَلَ عَنْ رَاحِلَتِهِ]{.ar}
    [https://hadithunlocked.com/bayhaqi:16844]{.citex}  
    "While the Prophet ;pbuh; was **travelling** to [#tabUk]{.trn2}, he dismounted off his mount"

<!--
(@ex000460) [حَتَّى إِذَا كُنَّا بالْمُصَلَّى رَاجِعِينَ مِنْ بَدْرٍ بَرَكَ عَلَيْنَ]{.ar}
    "Until we were near [al-#muSallA]{.trn2}, returning from Badr, it (i.e. the camel) kneeled down to us"
-->

(@ex000461) [ثُمَّ أَرْدَفَنِي وَرَاءَهُ عَلَى الْعَضْبَاءِ رَاجِعِينَ إِلَى الْمَدِينَةِ]{.ar}
    [https://hadithunlocked.com/ahmad:16539]{.citex}  
    Then he seated me behind him on (his camel) [al-#eaDbAE]{.trn2} while we [were] returning to [al-#madInah]{.trn2}

(@ex000462) [اتَّبَعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم وَهُوَ **رَاكِبٌ**]{.ar}
    [@https://sunnah.com/nasai:953@]{.citex} [move to verbs of motion]  
    "I followed the Messenger of Allah ;pbuh; when he was **riding**"

<!--
But when the focus is on the actual dynamic movement rather than being in a state of moving,
then the ;mudarie; verb tends to be used.
As usual, the ;mudarie; verb can be used as well.
For example:

(@ex000463) [فَجَاءَتْهُ إِحْدَاهُمَا تَمْشِى عَلَى ٱسْتِحْيَاءٍ]{.ar}
    [@https://quran.com/28/25@]{.citex}  
    Then one of the two women came to him walking with shyness.
-->

Unlike verbs of posture and temporary state,
verbs of motion are frequently used for the continuous tense.
Here are some examples:

(@ex000464) [أَدْرَكَنِي أَبُو عَبْسٍ وَأَنَا **أَذْهَبُ** إِلَى الْجُمُعَةِ]{.ar}
    [@https://sunnah.com/bukhari:907@]{.citex}  
    [#abU #eabs]{.trn2} overtook me while I **[was] going** to the [jumueah]{.trn2}

(@ex000465) [بَيْنَا أَنَا **أَسِيرُ** مَعَ رَسُولِ اللَّهِ صلى الله عليه وسلم بَيْنَ الْجُحْفَةِ وَالأَبْوَاءِ إِذْ غَشِيَتْنَا رِيحٌ وَظُلْمَةٌ شَدِيدَةٌ]{.ar}
    [@https://sunnah.com/abudawud:1463@]{.citex}
    While I **was travelling** with the Messenger of Allah ;pbuh; between [al-#juHfah]{.trn2} and [al-E#abwAE]{.trn2}, suddenly a wind and intense darkness enveloped us

<!--
### The ;mudarie; verb used to indicate a static state

We would like to round off this discussion by mentioning that
the ;mudarie; verb too, can be used to indicate a static state.
Contrast example 
(@ism_fail_wearing_bedsheet) ([وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ **لاَبِسٌ مِرْطَ** عَائِشَةَ]{.ar})
with example (@ism_fail_wearing_sandals) below:

(@ism_fail_wearing_sandals) [فِإِنِّي رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم **يَلْبَسُ** النِّعَالَ الَّتِي لَيْسَ فِيهَا شَعْرٌ]{.ar}
    [@https://sunnah.com/abudawud:1772@]{.citex}  
    "I have seen the Messenger of Allah ;pbuh; **wearing** the sandals which don't have hair on them (i.e. tanned)."

Sometimes, the ;ism_fail;,
when indicating a static state,
is interchangeable with the ;mudarie; verb.
See the following pair of examples:

(@ex000466) [... وَلاَ آخَرُ قَدِ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهُوَ **مُنْتَظِرٌ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/muslim:1747@]{.citex}  
    "... nor another who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"

(@ex000467) [... وَلاَ أَحَدٌ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهْوَ **يَنْتَظِرُ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/bukhari:3124@]{.citex}  
    "... nor one who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"
-->

## The ;ism_fail; without [ٱلْ]{.ar} used to indicate a future event

In addition to indicating a static state,
another verbal meaning of the ;ism_fail;
is to indicate the future tense.

Here too, the ;ism_fail; is used instead of the ;mudarie; verb.
When a ;mudarie; verb is used to indicate a future event,
then it merely signifies that the speaker thinks that the ;faa3il; will take an action.
For example, the ;mudarie; verb
[أَذْهَبُ]{.ar}
(when used to indicate the future tense)
merely signifies the speaker’s intention of going some time in the future.

In contrast, 
when the ;ism_fail; is used to indicate the future tense, then it signifies that,
in the estimation of the speaker, the event will definitely take place.
In other words, the ;faa3il;’s future action is so settled and resolved in the speaker’s mind that
;faa3il; can already be described by the ;ism_fail;.
So, for example, if the speaker says 
[أَنَا ذَاهِبٌ]{.ar}
and the context tells us he is referring to a future action, then the use of the ;ism_fail;
[ذَاهِب]{.ar}
instead of the ;mudarie; verb [يَذْهَبُ]{.ar}, 
signifies that the speaker is so sure that he will do this action that he can already be described as a "goer".

Here are some examples of the ;ism_fail; being used to indicate the future tense:

(@ex000468) [وَقَالَ إِنِّى **ذَاهِبٌ** إِلَىٰ رَبِّى سَيَهْدِينِ]{.ar}  
    [@https://quran.com/37/99@]{.citex}  
    And [then] he said, "Indeed, I will go to [where I am ordered by] my Lord; He will guide me.

(@ex000469) [فَهُوَ **ذَاهِبٌ وَتَارِكُهُ** لِلنَّاسِ]{.ar}
    [@https://sunnah.com/muslim:2959a@]{.citex}  
    For he is going to go and leave it for the people.

(@ex000470) [إِنِّي **ذَاكِرٌ** لَكَ أَمْرًا]{.ar}
    [@https://sunnah.com/bukhari:1925@]{.citex}  
    I am going to mention to you a matter.

(@ex000471) [سَأَلْتُ النَّبِيَّ صلى الله عليه وسلم أَنْ يَشْفَعَ لِي يَوْمَ الْقِيَامَةِ فَقَالَ أَنَا **فَاعِلٌ**]{.ar}
    [@https://sunnah.com/tirmidhi:2433@]{.citex}  
    I asked the Propher ;pbuh; that he intercede for me on the Day of Resurrection. So he said, "I will do [it]."

(@ex000472) [وَإِذْ قَالَ رَبُّكَ لِلْمَلَائِكَةِ إِنِّى **جَاعِلٌ** فِي ٱلْأَرْضِ خَلِيفَةً]{.ar}
    [@https://quran.com/2/30@]{.citex}  
    And [mention, O Muḥammad], when your Lord said to the angels, "Indeed, I will make upon the earth a successive authority."

(@ex000473) [أَلاَ وَإِنِّي **تَارِكٌ** فِيكُمْ ثَقَلَيْنِ]{.ar}
    [@https://sunnah.com/muslim:2408d@]{.citex}  
    Unquestionably, I am leaving amongst you two weighty [things]  
    (In English, "I am leaving s.th." can indicate the future tense.)

(@ex000474) [زَعَمَ ابْنُ أُمِّي أَنَّهُ **قَاتِلٌ** رَجُلاً قَدْ أَجَرْتُهُ]{.ar}
    [@https://sunnah.com/bukhari:6158@]{.citex}  
    "My maternal brother claims that he will kill a man whom I have given protection to."

(@ex000475) [وَإِنِّي **مُرْسِلَةٌ** إِلَيْهِم بِهَدِيَّةٍ **فَنَاظِرَةٌ** بِمَ يَرْجِعُ ٱلْمُرْسَلُونَ]{.ar}
    [@https://quran.com/27/35@]{.citex}  
    "But indeed, I will send to them a gift and see with what [reply] the messengers will return."

(@ex000476) [إِنِّي **سَائِلٌ** هَذَا عَنْ هَذَا الرَّجُلِ الَّذِي يَزْعُمُ أَنَّهُ نَبِيٌّ]{.ar}
    [@https://sunnah.com/bukhari:4553@]{.citex}  
    I **am going to ask** this [person] about this man who claims that he is a prophet.

(@ex000477) [وَيْحَكَ يَا فُلَانُ تَرَى هَذَا **كَائِنًا**]{.ar}
    [https://hadithunlocked.com/ahmad:15841]{.citex}  
    A mercy on you O so-and-so! Do you think this **will be**?

The use of the ;ism_fail; instead of the ;mudarie; verb to indicate a future event can also, depending on context, indicate that the event is imminent, i.e. that it is in the very near future.
In such cases it can be translated using "be going to".
For example:

(@ex000478) [وَقَالَ أَبُو جَهْلٍ فَمَا تُرِيدُ هَذَا سَيّدُ كِنَانَةَ وَهُوَ لَنَا جَارٍ عَلَى مَنْ تَخَلّفَ فَقَالَ عُتْبَةُ لَا شَيْءَ أَنَا **خَارِجٌ**]{.ar}
    [[@maghazi_waqidi@ 1/38](https://shamela.ws/book/23680/79) cited by @marmor_tense@ 171]{.citex}  
    [[#abU #jahl]{.trn2} said, "So what do you want? This is the chief of [#kinAnah]{.trn2} and he is for us a protector over who remains behind." So [#eutbah]{.trn2} said, "[I want] nothing. I am going out."]{.trans}

By the way, it is not just the ;ism_fail; which is used to indicate an imminent future event.
The ;mudarie; verb can also be used with this meaning. For example,

(@ex000479) [قَالَتْ أَيْنَ قَالَ **أُصَلِّي** قَالَتِ اجْلِسْ قَالَ إِنِّي **أُصَلِّي**]{.ar}
    [@https://sunnah.com/muslim:560a@]{.citex}  
    She said, "Where [are you going]?" He said, "I **am going to pray**." She said, "Sit!" He said, "Indeed I **am going to pray**."

The ;ism_fail; of verbs of posture and verbs of motion
don't have any special behavior when used with a future tense meaning.
Examples:

(@ex000480) [إِنِّي إِنْ شَاءَ اللَّهُ **لَقَائِمٌ** الْعَشِيَّةَ فِي النَّاسِ، **فَمُحَذِّرُهُمْ** هَؤُلاَءِ الَّذِينَ يُرِيدُونَ أَنْ يَغْصِبُوهُمْ أُمُورَهُمْ]{.ar}
    [@https://sunnah.com/bukhari:6830@]{.citex}  
    I, ;ia;, **will stand** tonight amongst the peope and **warn** them [about] these [people] who want to forcibly seize their affairs.

## The ;ism_fail; without [ٱلْ]{.ar} used to indicate a hypothetical event

The ;ism_fail;,
is used very commonly in conditional hypothetical clauses with [كَانَ]{.ar}.
<!--
It seems to derive its usage, in most hypothetical clauses, from its future tense meaning.
-->
Here are some examples:

(@ex000481) [وَلَوْ كُنْتُ **مُتَّخِذًا** مِنَ النَّاسِ خَلِيلاً لاَتَّخَذْتُ أَبَا بَكْرٍ خَلِيلاً]{.ar}
    [@https://sunnah.com/bukhari:467@]{.citex}  
    If I were to take [anyone] from the people as a friend, I would have taken [#abU #bakr]{.trn2} as a friend.

(@ex000482) [لَوْ كُنْتُ **مُصَلِّيًا** قَبْلَهَا أَوْ بَعْدَهَا لَأَتْمَمْتُهَا]{.ar}
    [https://hadithunlocked.com/ahmad:5185]{.citex}  
    If I were to pray before it or after it, I would have completed them.

(@ex000483) [وَلَوْ كَانَ مُحَمَّدٌ صلى الله عليه وسلم **كَاتِمًا** شَيْئًا مِمَّا أُنْزِلَ عَلَيْهِ لَكَتَمَ هَذِهِ الآيَةَ]{.ar}
    [@https://sunnah.com/muslim:177b@]{.citex}  
    And if [#muHammad]{.trn2} were to conceal anything from what was revealed to him, he would have concealed this ;ayah;.

(@ex000484) [لَوْ كُنْتُ **قَاتِلًا** رَسُولًا لَضَرَبْتُ أَعْنَاقَكُمَا]{.ar}
    [https://hadithunlocked.com/ahmad:3708]{.citex}  
    If I were a killer of a messenger I would have struck your necks.

(@ex000485) [لَوْ كُنْتُ **آمِرًا** أَحَدًا أَنْ يَسْجُدَ لأَحَدٍ لأَمَرْتُ الْمَرْأَةَ أَنْ تَسْجُدَ لِزَوْجِهَا]{.ar}
    [@https://sunnah.com/tirmidhi:1159@]{.citex}  
    If I were to order anyone that he prostrate to anyone, I would have ordered the woman to prostrate to her spouse

(@ex000486) [لَوْ كَانَ لَكَ مَا عَلَى الْأَرْضِ مِنْ شَيْءٍ أَكُنْتَ **مُفْتَدِيًا** بِهِ]{.ar}
    [https://hadithunlocked.com/ahmad:12289]{.citex}  
    If you had everything that is on the earth would you ransom yourself with it?

(@ex000487) [إِنْ كُنْتَ لاَ بُدَّ **فَاعِلاً** فَوَاحِدَةً]{.ar}
    [@https://sunnah.com/muslim:546@]{.citex}  
    If you must do it then (only) once.

The ;mudarie; verb is also used in such clauses, but it tends
to indicate a hypothetical _current_ situation.
For example:

(@ex000488) [لَوْ كُنْتُ **أَقْرَبُهَا أَوْ أَدْخُلُ** عَلَيْهَا لأَتَيْتُهَا حَتَّى تُشَافِهَنِي بِهِ]{.ar}
    [@https://sunnah.com/muslim:746a@]{.citex}  
    If (the current situtation were such that) I were nearing her or entering upon her, I would have come to her so that she would [tell] it to me face-to-face.

(@ex000489) [قُل لَّوْ كَانَ فِي ٱلْأَرْضِ مَلَائِكَةٌ **يَمْشُونَ** مُطْمَئِنِّينَ لَنَزَّلْنَا عَلَيْهِم مِّنَ ٱلسَّمَآءِ مَلَكًا رَّسُولًا]{.ar}
    [@https://quran.com/17/95@]{.citex}  
    Say, "If there were upon the earth angels walking securely, We would have sent down to them from the heaven an angel [as a] messenger."

(@ex000490) [إِنَّ عَبْدَ اللَّهِ رَجُلٌ صَالِحٌ لَوْ كَانَ **يُكْثِرُ** الصَّلاَةَ مِنَ اللَّيْلِ]{.ar}
    [@https://sunnah.com/ibnmajah:3919@]{.citex}  
    Indeed [#eabd #allAh]{.trn2} is a righteous man, if only he would pray much in the night.

The ;ism_fail; can also be used in non-conditional hypothetical sentences (see section\ (kaana)).
For example:

(@ex000491) [يَا سَلَمَةُ أَتُرَاكَ كُنْتَ **فَاعِلاً**]{.ar}
    [@https://sunnah.com/muslim:1807a@]{.citex}  
    O Salamah, do you think you could do [it]?

(@ex000492) [أَوَكُنْتَ **فَاعِلًا** ذَاكَ]{.ar}
    [@https://sunnah.com/ahmad:61@]{.citex}  
    Would you have done that?

The ;mudarie; verb is also used in such sentences.
For example:

(@ex000493) [أَنْتَ كُنْتَ **تَفْعَلُ** ذَلِكَ]{.ar}
    [@https://sunnah.com/muslim:1788@]{.citex}  
    You would/may have done that

<!--
### The ;mudarie; verb used to indicate a future event

We would like to round off this discussion by mentioning that
the ;mudarie; verb too can be used to indicate a future event.
We have already discussed the possible difference in meaning between a ;mudarie; verb is used to indicate a future event,
and when an ;ism_fail; is used to do so.

Contrast example (@ism_fail_going_to_my_lord) with example (@ism_fail_anas_going) below:

(@ism_fail_anas_going) [فَقَالَ يَا أُنَيْسُ أَذَهَبْتَ حَيْثُ أَمَرْتُكَ  قَالَ قُلْتُ نَعَمْ أَنَا أَذْهَبُ يَا رَسُولَ اللَّهِ]{.ar}
    [@https://sunnah.com/muslim:2310a@]{.citex}  
    He said "O Unays, did you go where I commanded you [to go]?" I said, "Yes I am going, O Messenger of Allah"

Sometimes, the ;ism_fail;,
when indicating a future event
is interchangeable with the ;mudarie; verb.
See the following pair of examples:

(@ex000494) [أَرَأَيْتَكُمْ لَوْ أَخْبَرْتُكُمْ أَنَّ خَيْلاً تَخْرُجُ بِسَفْحِ هَذَا الْجَبَلِ أَكُنْتُمْ **مُصَدِّقِيَّ**]{.ar}
    [@https://sunnah.com/muslim:208a@]{.citex}  
    "Do you think if I were to inform you that there were horsemen emerging out of the foot of this mountain, would you **believe** me?"

(@ex000495) [أَرَأَيْتُمْ إِنْ حَدَّثْتُكُمْ أَنَّ الْعَدُوَّ مُصَبِّحُكُمْ أَوْ مُمَسِّيكُمْ، أَكُنْتُمْ **تُصَدِّقُونِي**]{.ar}
    [@https://sunnah.com/bukhari:4972@]{.citex}  
    "Do you think if I told you that an enemy is going to attack you in the morning or in the evening, will you **believe** me?"
-->

## Interchangeability of the ;mudarie; verb and the ;ism_fail; without [ٱلْ]{.ar} 

We have described above,
the circumstances when the ;ism_fail; instead of the ;mudarie; verb,.
We would like to state that these are more like trends rather than hard and fast rules.
We sometimes find a ;mudarie; verb where an ;ism_fail; could have worked, and vice versa.

For the indication of a static state,
consider, for instance, example (@ism_fail_wearing_bedsheet)
([وَهُوَ مُضْطَجِعٌ عَلَى فِرَاشِهِ **لاَبِسٌ مِرْطَ** عَائِشَةَ]{.ar}) above
and compare it with with example (@ism_fail_wearing_sandals) below:

(@ism_fail_wearing_sandals) [فِإِنِّي رَأَيْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم **يَلْبَسُ النِّعَالَ** الَّتِي لَيْسَ فِيهَا شَعْرٌ]{.ar}
    [@https://sunnah.com/abudawud:1772@]{.citex}  
    "I have seen the Messenger of Allah ;pbuh; **wearing** the sandals which don't have hair on them (i.e. tanned)."

Consider also the following two narrations:

(@ex000496) [... وَلاَ آخَرُ قَدِ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهُوَ **مُنْتَظِرٌ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/muslim:1747@]{.citex}  
    "... nor another who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"

(@ex000497) [... وَلاَ أَحَدٌ اشْتَرَى غَنَمًا أَوْ خَلِفَاتٍ وَهْوَ **يَنْتَظِرُ** وِلاَدَهَا]{.ar}
    [@https://sunnah.com/bukhari:3124@]{.citex}  
    "... nor one who has bought sheep or pregnant she-camels and he is **waiting** for their giving birth"

Similarly, for the indication of the future tense,
contrast example (@ism_fail_going_to_my_lord) with example (@ism_fail_anas_going) below:

(@ism_fail_anas_going) [فَقَالَ يَا أُنَيْسُ أَذَهَبْتَ حَيْثُ أَمَرْتُكَ  قَالَ قُلْتُ نَعَمْ أَنَا أَذْهَبُ يَا رَسُولَ اللَّهِ]{.ar}
    [@https://sunnah.com/muslim:2310a@]{.citex}  
    He said "O Unays, did you go where I commanded you [to go]?" I said, "Yes I am going, O Messenger of Allah"

Consider also the following two narrations:

(@ex000498) [أَرَأَيْتَكُمْ لَوْ أَخْبَرْتُكُمْ أَنَّ خَيْلاً تَخْرُجُ بِسَفْحِ هَذَا الْجَبَلِ أَكُنْتُمْ **مُصَدِّقِيَّ**]{.ar}
    [@https://sunnah.com/muslim:208a@]{.citex}  
    "Do you think if I were to inform you that there were horsemen emerging out of the foot of this mountain, would you **believe** me?"

(@ex000499) [أَرَأَيْتُمْ إِنْ حَدَّثْتُكُمْ أَنَّ الْعَدُوَّ مُصَبِّحُكُمْ أَوْ مُمَسِّيكُمْ، أَكُنْتُمْ **تُصَدِّقُونِي**]{.ar}
    [@https://sunnah.com/bukhari:4972@]{.citex}  
    "Do you think if I told you that an enemy is going to attack you in the morning or in the evening, will you **believe** me?"

## The ;ism_fail; without [ٱلْ]{.ar} used with a ;madi; significance

We have seen,
in the sections above, that
the ;ism_fail; without [ٱلْ]{.ar} has a strong correlation with the ;ustate; ;mudarie; verb, giving an imperfect meaning.
But,
the ;ism_fail; without [ٱلْ]{.ar}
can also carry the significance of the ;madi; verb.
Such that it can indicate that the ;faa3il; has completed the action of the verb.
As when the ;ism_fail; was used in an imperfect sense,
here too it can indicate being in a static state.
Examples:
<!--
But
when
the ;ism_fail; without [ٱلْ]{.ar}
is used with a ;madi; significance,
it isn't used _in place of_ the ;madi; verb.
Instead, it's essential ;faa3il; meaning remains uppermost.
-->

(@ex000500) [لَا آتِيكَ مُجْرِمًا]{.ar}
    [@fischer@ 112]{.citex}  
    I shall not come to you as one who has committed a crime.  
    ([مُجْرِمًا]{.ar} is here in place of the ;madi; verb [وَقَدْ أَجْرَمْتُ]{.ar}.)

(@ex000501) [جِيءَ بِالنُّعَيْمَانِ أَوِ ابْنِ النُّعَيْمَانِ شَارِبًا]{.ar}
    [@https://sunnah.com/bukhari:2316@]{.citex}  
    [al-#nueaymAn]{.trn2} or [al-#nueaymAn]{.trn2}'s son was brought (in a state of) of having drunk (wine).

(@ex000502) [قَالَ جَابِرٌ فَبَيْنَا أَنَا **نَازِلٌ** تَحْتَ شَجَرَةٍ إِذَا رَسُولُ اللَّهِ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/malik/48/1@]{.citex}  
    "While I was (resting) dismounted under a tree, the Messenger of Allah ;pbuh; [came]."

(@ex000503) [لَوْ كُنْتُ **مُتَوَضِّئًا** أَكَلْتُهُ]{.ar}
    [https://hadithunlocked.com/ahmad:15147, graded weak by [al-E#arnaEUT]{.trn2}]{.citex}  
    If I were in a state of having done [wuDUE]{.trn2}, I would have eaten it.
    
When used with a ;madi; significance,
then, according to most authorities,
the ;ism_fail; cannot usually have a ;mafulb;.
(See section\ (ref).)

## The ;ism_fail; prefixed with [ٱل]{.ar}

Consider the sentence:

(@ex000504) [رَأَيْتُ الرَّجُلَ]{.ar}  
    [I saw the man.]{.trans}

The
definite article
[ٱل]{.ar}
indicates that the listener
would know identity of the person who was seen because of his being referred to as
a definite entity:
[الرَّجُلَ]{.ar}
_the_ man.

Consider now the sentence:

(@ex000505) [رَأَيْتُ الضَّارِبَ]{.ar}  
    [I saw the beater~m~.]{.trans}

Now the person who was seen is identified, 
not by his virtue of being an entity,
but because of his being the doer of the verb
[ضَرَبَ يَضْرِبُ]{.ar}.
In this sense,
the noun
[الضَّارِب]{.ar}
is similar in meaning to
[الَّذِي ضَرَبَ/يَضْرِبُ]{.ar}
[the one who beat/beats]{.trans}.

Similarly, if we say:

(@ex000506) [جَاءَتِ الضَّارِبَةُ]{.ar}  
    [The beater~f~ came.]{.trans}

then this is similar to
saying
[جَاءَتِ الَّتِي ضَرَبَتْ/تَضْرِبُ]{.ar}
[The one~f~ who beat/beats came.]{.trans}

Because of the equivalence of this
[ٱل]{.ar}
to the ;ism_mawsul;s
([ٱلَّذِي]{.ar},
[ٱلَّتِي]{.ar},
etc.),
this
[ٱل]{.ar},
that is prefixed to ;ism_fail;s
(and to ;mushtaqq; nouns in general)
is called the
_;ism_mawsul;_ [ٱل]{.ar}.
We will learn more about 
the _;ism_mawsul;_ [ٱل]{.ar}
in section\ (ref).

For now, we note that when
the ;ism_mawsul; [ٱل]{.ar},
is prefixed to a ;mushtaqq; noun
then the ;mushtaqq; noun retains its capability to govern a ;faa3il; and a ;astate; governee.

So in example (@) [جَاءَتِ الضَّارِبَةُ]{.ar},
the ;ism_fail;
[الضَّارِبَة]{.ar}
is governing a ;mustatir; ;faa3il; pronoun [[هِيَ]{.ar}].
And in the following example,
the ;ism_fail; is also governing a ;mafulb;:

<!--
(@ex000507) [مَرَرْتُ بالضَّارِبِ الْعَبْدَ]{.ar}  
    [I passed by the beater of the slave.]{.trans}
-->

(@3amal_mush_muslim_601) [فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم مَنِ الْقَائِلُ كَلِمَةَ كَذَا وَكَذَا]{.ar}
    [@https://sunnah.com/muslim:601@]{.citex}  
    [The Messenger of Allah ;pbuh; said: "Who is the one who said such and such speech?"]{.trans}


(@ex000508) [عَاتَبْتُ الْمُخْلِفَ الْوَعْدَ]{.ar}  
    [I reproved the promise-breaker.]{.trans}

The construction
[الْمُخْلِفَ الْوَعْدَ]{.ar}
<!--
[الضَّارِبِ الْعَبْدَ]{.ar}
-->
can also be converted to a ;lafzi; ;idaafah;, thus:

<!--
(@ex000509) [مَرَرْتُ بالضَّارِبِ الْعَبْدِ]{.ar}  
    [I passed by the beater of the slave.]{.trans}
-->

(@ex000510) [عَاتَبْتُ الْمُخْلِفَ الْوَعْدِ]{.ar}  
    [I reproved the promise-breaker.]{.trans}

When
the _;ism_mawsul;_ [ٱل]{.ar}
is used with an ;ism_fail;,
then the ;ism_fail; includes the meaning of the verb.
So much so,
that an actual verb may be conjuncted to the _meaning of the verb_ that is included in the ;ism_fail;.^[@https://tafsir.app/albahr-almuheet/57/18@]
For example:

(@ex000511) [إِنَّ **ٱلْمُصَّدِّقِينَ وَٱلْمُصَّدِّقَاتِ وَأَقْرَضُوا** ٱللَّهَ قَرْضًا حَسَنًا يُضَاعَفُ لَهُمْ وَلَهُمْ أَجْرٌ كَرِيمٌ]{.ar}
    [@https://quran.com/57/18@]{.citex}  
    "Indeed, the men who practice charity and the women who practice charity and [they who] have loaned Allāh a goodly loan - it will be multiplied for them, and they will have a noble reward."

## The ;ism_fail; that crosses over to the ;subst;


Sometimes, the ;ism_fail; is re-used as a ;subst;.
When this happens, it loses its purely verbal meaning of the doer of a verb,
and signifies only an entity, just like a ;subst;.
There are two categories of ;ism_fail;-crossover ;subst;s:

<!--
 i. The ;ism_fail;-crossover-to-;subst; that has a distinct or more permanent meaning from the original ;ism_fail;
ii. The ;ism_fail;-crossover-to-;subst; that has the same meaning as the original ;ism_fail;
-->

 i. The lexical ;ism_fail;-crossover-to-;subst;
ii. The ad hoc ;ism_fail;-crossover-to-;subst;

In reality, these are not completely distinct categories.
They more represent a spectrum of meanings.
And it can be a judgement call as to which category a particluar noun may belong.
We will discuss each of these categories in the following sub-sections:

### The lexical ;ism_fail;-crossover-to-;subst;

The ;ism_fail; is from the class of ;sifah;s, not ;subst;s.
And in terms of its meaning, it
has a relatively temporary and incidental meaning when compared to a ;subst;.
For example the
the ;ism_fail; [ضَارِب]{.ar} [beater]{.trans}
would only be applicable to someone when he is associated with the act of beating.
Otherwise he would not be referred to as a
[ضَارِب]{.ar}.
On the other hand, a
;subst; like
[رَجُل]{.ar} [man]{.trans}
has a more permanent meaning, that is not associated with any action from him.

Some ;ism_fail;'s can take on this more permanent meaning of a ;subst;.
Usually, their meaning will be somewhat distinct from the original ;ism_fail; or the verb from which it is derived.
Such a ;ism_fail; is termed
a lexical ;ism_fail;-crossover-to-;subst;
because its new meaning often deserves a new lexical definition in the dictionary.

For example,
the ;ism_fail;
[صَاحِب]{.ar}
(from the verb [صَحِبَ يَصْحَبُ]{.ar} [to accompany]{.trans})
is predominantly used as a ;subst; to mean [companion]{.trans}.
With this meaning, it can no longer act as a verb-like governor.
So it will not have a ;mustatir; ;faa3il; pronoun,
and 
it will not govern a ;mafulb;.
So we cannot say:

(@ex000512) ;x; [حَسَّامٌ صَاحِبٌ يَاسِرًا]{.ar}
    [@za3balawi_dirasat@ 487 citing [العدناني]{.ar}]{.citex}  
    [[#HassAm]{.trn2} is a companion of [#yAsir]{.trn2}.]{.trans}


Additionally any
[ٱل]{.ar}
that is prefixed to a
;ism_fail;-crossover-to-;subst;
cannot be
the 
;ism_mawsul; [ٱل]{.ar}.
It will be the regular
[ٱل]{.ar}
that is prefixed to ;subst;s.^[[@za3balawi_dirasat@ 484](https://shamela.ws/book/2120/484)]
So when it is the ;mudaf; in an ;idaafah; then it must be a ;ma3nawi; ;idaafah;,
and the
[ٱل]{.ar}
is dropped.

So we will say:

(@ex000513) [صَحِبَ حَسَّامٌ يَاسِرًا فَهُوَ **صَاحِبُهُ**]{.ar}
    [@za3balawi_dirasat@ 487 citing [العدناني]{.ar}]{.citex}  
    [[#HassAm]{.trn2} accompanied [#yAsir]{.trn2} so he is **his companion**.]{.trans}

With regard to their plurals,
the default behavior for the ;ism_fail;, especially when used with a verbal meaning, is to have a sound plural.
But when the ;ism_fail; crosses-over to a ;subst; then it is more likely to have a broken plural.^[[@za3balawi_dirasat@ 503](https://shamela.ws/book/2120/503) citing [السيوطي]{.ar}]

Here are some examples of ;subst;s from cross-over ;ism_fail;s:

|;subst; | meaning | plural | verb |
|:---|:----|:---|:---------|
|[صَاحِب]{.ar}   | a companion              |[أَصْحَاب]{.ar}   | [صَحِبَ يَصْحَبُ]{.ar}  to accompany|
|[سَائِل]{.ar}   | a beggar                 |[سَأَلَة]{.ar}, [سُؤَّال]{.ar}   | [سَأَلَ يَسْأَلُ]{.ar}  to ask|
|[عَالِم]{.ar}   | a scholar                |[عُلَمَاء]{.ar}   | [عَلِمَ يَعْلَمُ]{.ar}  to know     |
|[قَاضٍ]{.ar}    | a judge                  |[قُضَاة]{.ar}    | [قَضَى يَقْضِي]{.ar}  to decree   |
|[كَاتِب]{.ar}   | a scribe                 |[كَتَبَة]{.ar}    | [كَتَبَ يَكْتُبُ]{.ar}  to write    |
|[شَاعِر]{.ar}   | a poet                   |[شُعَرَاء]{.ar}   | [شَعَرَ يَشْعُرُ]{.ar}  to be aware |
|[بَالِغ]{.ar}   | a legally mature person  |[بَالِغُونَ]{.ar}  | [بَلَغَ يَبْلُغُ]{.ar}  to reach    |
|[مُصِيبَة]{.ar}  | a calamity               |[مَصَائِب]{.ar}   | [أَصَابَ يُصِيبُ]{.ar} to strike   |
|[جَارِيَة]{.ar}  | a girl                   |[جَوَارٍ]{.ar}    | [جَرَى يَجْرِي]{.ar}  to run      |
|[طَالِب]{.ar}   | a student                |[طَلَبَة]{.ar}, [طُلَّاب]{.ar}    | [طَلَبَ يَطْلُبُ]{.ar}  to seek     |
|[شَارِب]{.ar}   | a moustache              |[شَوَارِب]{.ar}   | [شَرِبَ يَشْرَبُ]{.ar}  to drink    |
|[سَاحِل]{.ar}   | a shore                  |[سَوَاحِل]{.ar}   | [سَحَلَ يَسْحَلُ]{.ar}  to abrade   |
|[جَامِع]{.ar}   | a large mosque           |[جَوَامِع]{.ar}   | [جَمَعَ يَجْمَعُ]{.ar}  to gather   |
|[جَامِعَة]{.ar}  | a university             |[جَامِعَات]{.ar}  | [جَمَعَ يَجْمَعُ]{.ar}  to gather   |
|[قَائِمَة]{.ar}  | a leg (of a beast, furniture)             |[قَوَائِم]{.ar}  | [قَامَ يَقُومُ]{.ar}  to stand   |
|[وَارِث]{.ar}   | an heir                  |[وَرَثَة]{.ar}, [وُرَّاث]{.ar}  | [وَرَثَ يَرِثُ]{.ar}  to inherit   |
|[وَالِدٌ]{.ar}   | a parent                 |[وَالِدُونَ]{.ar}             | [وَلَدَ يَلِدُ]{.ar}  to beget (offspring)   |
|[حَامِل]{.ar}   | a carrier                |[حَمَلَة]{.ar}               | [حَمَلَ يَحْمِلُ]{.ar} to carry |
|[قَارِئ]{.ar}   | a reciter                |[قُرَّاء]{.ar}               | [قَرَأَ يَقٌرَأُ]{.ar} to read, recite |
|[مُعَلِّم]{.ar}   | a teacher                |[مُعَلِّمُونَ]{.ar}             | [عَلَّمَ يُعَلِّمُ]{.ar} to teach |


When the ;ism_fail; that has crossed over to a ;subst; refers to human beings,
then often, but not always, a feminine version of the crossed over ;subst; will also exist, with a [ة]{.ar}.
So [صَاحِبَة]{.ar} is a female companion,
[وَالِدَة]{.ar} is a female parent, etc.
Sometimes, however, the ;subst; exists for only one gender and not for the other,
e.g. [جَارِيَة]{.ar} [a girl]{.trans}.
Also sometimes, the same ;subst; is used for both genders,
e.g.
[بَالِغ]{.ar}   [a legally mature person]{.trans}.
So we will say:

(@ex000514) [رجل بالغٌ، وامرأة بالغ]{.ar}
    [[@ibn_alanbaari_mudhakkar@ 1/136](https://shamela.ws/book/17819/87#p1)]{.citex}  
    [A legally mature man and a legally mature woman]{.trans}

There is often some flexibility in these cases, so 
[بَالِغَة]{.ar} can also be used for a female legally mature person.
The dictionary is the best guide in these matters.

Recall from section\ (ref) that the [ة]{.ar} that exists in a
feminine ;ism_fail; is
because of its
;mustatir; ;faa3il; pronoun.
So when we say
[هِنْدٌ قَائِمَةٌ]{.ar}
[Hind is standing]{.trans}
then the
[ة]{.ar}
in
[قَائِمَةٌ]{.ar}
is to match its
;mustatir; ;faa3il; pronoun
[[هِيَ]{.ar}]
that refers to
[هِنْدٌ]{.ar}.
But
the [ة]{.ar} that exists in a
;ism_fail;-crossover-to-;subst;
is no longer because of a ;mustatir; ;faa3il; pronoun.
This is because,
as mentioned previously,
the
;ism_fail;-crossover-to-;subst;
is not a verb-like governor, so it will not govern
a ;mustatir; ;faa3il; pronoun.
So the
[ة]{.ar}
in the
;ism_fail;-crossover-to-;subst;s
[صَاحِبَة]{.ar} [female companion]{.trans}
and
[وَالِدَة]{.ar} [female parent]{.trans}
is a fixed feminine marker, just like the
[ة]{.ar}
in any other feminine ;subst;, e.g.
[شَجَرَة]{.ar} [tree]{.trans},
[امْرَأَة]{.ar} [woman]{.trans},
etc.

Additionally,
once a ;ism_fail; has crossed over to a ;subst;,
then like all ;subst;s, it loses its genderizability.
So we cannot add or remove a feminine marker (like [ة]{.ar}) at will.
For example, if we wish to say
[The building is a university]{.trans},
then we will say

(@ex000515) [الْبِنَاءُ جَامِعَةٌ]{.ar}  
    [The building is a university.]{.trans}

We cannot remove [ة]{.ar} from 
[جَامِعَةٌ]{.ar}
in order to match the gender of
[الْبِنَاءُ]{.ar}.
If we do so then the meaning will be:

(@ex000516) [الْبِنَاءُ جَامِعٌ]{.ar}  
    [The building is a large mosque.]{.trans}

In this case,
[جَامِع]{.ar}
happens to exist as another ;ism_fail;-crossover-to-;subst;.
So example () is a valid sentence, but with a different meaning than intended.

Sometimes it can be difficult to tell whether a noun from this category is an ;ism_fail; with its original meaning,
or one that has crossed over to a ;subst;.
If you find that it is used independently (in meaning) without referring to an (implicit or explicit) referent,
then it is likely that it is a
;ism_fail;-crossover-to-;subst;.
Another clue is that it is used with a broken plural.^[[@za3balawi_dirasat@ 503](https://shamela.ws/book/2120/503)]
But broken plurals may be used for governing ;ism_fail;s as well
(as we saw in section\ (ref))
so this isn't a definitive indicator.
A more reliable indicator is whether it is made definite by being annexed to a definite ;mudafil; in a ;ma3nawi; ;idaafah;.
Here are some examples:

(@ex000517) [هؤلاء حملة الأقلام]{.ar}
    [[@za3balawi_dirasat@ 503](https://shamela.ws/book/2120/503)]{.citex}  
    [These are **the** carriers of the pens.]{.trans}

(@ex000518) [وَمَنْ تَرَكَ مَالاً **فَلِوَرَثَتِهِ** وَأَنَا **وَارِثُ** مَنْ لاَ وَارِثَ لَهُ أَعْقِلُ لَهُ وَأَرِثُهُ وَالْخَالُ وَارِثُ مَنْ لاَ وَارِثَ لَهُ يَعْقِلُ عَنْهُ وَيَرِثُهُ]{.ar}
    [@https://sunnah.com/abudawud:2899@]{.citex}  
    [Whoever leaves wealth then [it is] for his heirs. And I am **the heir** of he who has no heir, paying blood-wit for him and inheriting from him. And the maternal uncle is the heir of he who has no heir, paying blood-wit for him and inheriting from him.]{.trans}

Another possible indicator is whether
the ;ism_fail; as an ;xabar; mismatches in gender with the ;mubtada;.
For example:

(@ex000519) [الْعُودُ قَائِمَةٌ]{.ar}  
    [The stick is a leg (of some furniture or other structure).]{.trans}  
    (If the ;ism_fail; was intended, then we would say [الْعُودُ قَائِمٌ]{.ar} [The stick is standing]{.trans}.)

But this isn't always reliable because the ;mubtada; may match in gender with the ;ism_fail;-crossover-to-;subst; anyway.
For example:

(@ex000520) [الْعَصَا قَائِمَةٌ]{.ar}  
    [The stick is a leg.]{.trans}  
    or [The stick is standing.]{.trans}  
    ([عَصًا]{.ar} is a feminine noun.)

Another indicator also whether
the singular feminine of the ;ism_fail; is used as a ;xabar; or ;na3t; for ;g_3aaqil;s.
For example:

(@ex000521) [الْأَعْوَادُ قَائِمَةٌ]{.ar}  
    [The sticks are standing.]{.trans}

In the above example
[قَائِمَةٌ]{.ar}
is likely to be an ;ism_fail;.
(By the way, a ;subst; reading is also possible:
[the sticks (collectively) are a leg]{.trans}.)
But if we say:

(@ex000522) [الْأَعْوَادُ قَوَائِمُ]{.ar}  
    [The sticks are legs.]{.trans}

then
[قَوَائِمُ]{.ar}
is more likely to be a ;subst;.
Context is a useful guide here.

<!--

### The ;ism_fail;-crossover-to-;subst; that has a similar (but more permanent) meaning to the original ;ism_fail;


In this second category,
the
;ism_fail;-crossover-to-;subst;
can keep the original meaning of the verb-doer
but it will now be a 
more permanent description of the referent,
rather than the relatively incidental and temporary meaning that the ;ism_fail; has.
Here are some examples:


|;subst; | meaning | plural | verb |
|:---|:----|:---|:---------|
|[وَارِث]{.ar}    | an heir             |[وَرَثَة]{.ar}, [وُرَّاث]{.ar}  | [وَرَثَ يَرِثُ]{.ar}  to inherit   |
|[وَالِدٌ]{.ar}    | a parent            |[وَالِدُونَ]{.ar}             | [وَلَدَ يَلِدُ]{.ar}  to beget (offspring)   |
|[حَامِل]{.ar}    | a carrier           |[حَمَلَة]{.ar}               | [حَمَلَ يَحْمِلُ]{.ar} to carry |
|[قَارِئ]{.ar}    | a reciter           |[قُرَّاء]{.ar}               | [قَرَأَ يَقٌرَأُ]{.ar} to read, recite |

Remove. Look more like sifah_mush:
|[آثِم]{.ar}     | a sinner            |[أُثَمَاء]{.ar}              | [أَثِمَ يَأْثَمُ]{.ar} to fall into sin |
|[عَاشِق]{.ar}    | a passionate lover  |[عُشَّاق]{.ar}               | [عَشِقَ يَعْشَقُ]{.ar} to love passionately |

Even for such cases, where the ;subst; has the same (but more stable) meaning as the ;ism_fail;,
the ;subst; can (generally) now no longer govern in a verb-like manner.
So it will not govern a ;mustatir; ;faa3il; pronoun, or a ;mafulb;.
Therefore, when this
;ism_fail;-crossover-to-;subst;
is the ;mudaf; in an ;idaafah; then it must be a ;ma3nawi; ;idaafah;.
For example:

(@ex000523) [وَمَنْ تَرَكَ مَالاً فَلِوَرَثَتِهِ وَأَنَا **وَارِثُ** مَنْ لاَ وَارِثَ لَهُ أَعْقِلُ لَهُ وَأَرِثُهُ وَالْخَالُ وَارِثُ مَنْ لاَ وَارِثَ لَهُ يَعْقِلُ عَنْهُ وَيَرِثُهُ]{.ar}
    [@https://sunnah.com/abudawud:2899@]{.citex}  
    [Whoever leaves wealth then [it is] for his heirs. And I am **the heir** of he who has no heir, paying blood-wit for him and inheriting from him. And the maternal uncle is the heir of he who has no heir, paying blood-wit for him and inheriting from him.]{.trans}

In this second category as well,
when the ;ism_fail; that has crossed over to a ;subst; refers to human beings,
then often, but not always, a feminine version of the crossed over ;subst; will also exist, with a [ة]{.ar}.
So [وَالِدَة]{.ar} is a female parent.

e.g.
[عَاشِق]{.ar} [a passionate lover]{.trans},
[آثِم]{.ar} [a sinner]{.trans}.

So we will say:

(@ex000524) [ورجُلٌ عاشقٌ وامرأةٌ عاشقٌ]{.ar}
    [[@ibn_alanbaari_mudhakkar@ 1/137](https://shamela.ws/book/17819/88#p1)]{.citex}  
    [A passionate lover man and a passionate lover woman]{.trans}

Again, there is often some flexibility, so 
[عَاشِقَة]{.ar} can be used for  a female passionate lover.

Sometimes it can be difficult to tell whether a noun from this category is an ;ism_fail; with its original meaning,
or one that has crossed over to a ;subst;.
If you find that it is used independently (in meaning) without referring to an (implicit or explicit) referent,
then it is likely that it is a
;ism_fail;-crossover-to-;subst;.
Another clue is that it is used with a broken plural.^[[@za3balawi_dirasat@ 503](https://shamela.ws/book/2120/503)]
A more reliable indicator is if it is made definite by being annexed to a definite ;mudafil; in a ;ma3nawi; ;idaafah;.
Here is an example that uses a broken plural, and also a ;ma3nawi; ;idaafah;.

(@ex000525) [هؤلاء حملة الأقلام]{.ar}
    [[@za3balawi_dirasat@ 503](https://shamela.ws/book/2120/503)]{.citex}  
    [These are **the** carriers of the pens.]{.trans}
-->

### The ad\ hoc ;ism_fail;-crossover-to-;subst;

This second category consists of ;ism_fail;s that are made ;subst;s on an ad\ hoc basis.
That is, the dictionary will typically not list the ;ism_fail; (for this category of meaning) separately for any distinct meaning.

Th ad\ hoc
;ism_fail;-crossover-to-;subst;
is routinely formed for ;ism_fail;s that signify the action of a perfect verb.
This is especially done when the ;ism_fail; of the perfect action is to be the ;mudaf; in a (now ;ma3nawi;) ;idaafah;.

So for example,
if someone has done the action of beating,
then he can be described as a [ضَارِب]{.ar}.
Now,
if we wish to refer to this specific person, we have a choice:
Either we can use the
;ism_mawsul;
[ٱل]{.ar}
or we can use the regular
[ٱل]{.ar}.
Either way,
the word will look the same: 
[الضَّارِب]{.ar}.
But its meaning will be slightly different.

In the case of the
;ism_mawsul;
[ٱل]{.ar},
we are defining the person based on an action of beating that he did.
[الضَّارِب]{.ar},
in this case, remains a ;ism_fail;.

And in the case of
the regular
[ٱل]{.ar},
we are defining him by virtue  of his entity.
Just like we would say [الرَّجُل]{.ar} [the man]{.trans}, [الْمَرْأَة]{.ar} [the woman]{.trans}, etc.
[الضَّارِب]{.ar},
in this case, becomes a ;subst;.

Either of these can generally be used when describing the definite ;faa3il; of a perfect verb.
When the semantic ;mafulb; of the verb is mentioned,
then the ;ism_fail;
[الضَّارِب]{.ar}
retains its
[ٱل]{.ar} and governs the semantic ;mafulb; in the ;astate;.
For example:

(@3amal_mush_hadha_aldaaribu_zaydan) [هَذَا الضَّارِبُ زَيْدًا أَمْسِ]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/100](https://shamela.ws/book/13301/1464); [@sarraj_usool@ 2/265](https://shamela.ws/book/7365/775)]{.citex}  
    [This [person] [was] the one who beat Zayd yesterday]{.trans}  
    ([الضَّارِب]{.ar} is a ;ism_fail; governing a ;mustatir; ;faa3il; pronoun and a ;mafulb;.)

But the ;subst;
[الضَّارِب]{.ar}
cannot govern a ;mafulb; and so it has to be annexed to the semantic ;mafulb; in a ;ma3nawi; ;idaafah;
So we will say:

(@3amal_mush_hadha_daaribu_zaydin) [هَذَا ضَارِبُ زَيْدٍ أَمْسِ]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/32](https://shamela.ws/book/13301/1396); [@maani_nahw@ 3/171](https://shamela.ws/book/17801/896) citing [الزجاجي]{.ar}]{.citex}  
    [This [person] [was] the beater of Zayd yesterday]{.trans}  
    ([ضَارِب]{.ar} is a ;subst; in a ;ma3nawi; ;idaafah;.)


In theory,
if the speaker intends to define the person by his being the doer of the verb [ضَرَبَ]{.ar},
then he would use example (@3amal_mush_hadha_aldaaribu_zaydan).
^[[@sarraj_usool@ 2/265](https://shamela.ws/book/7365/775)]
And if the speaker intends to define the person by virtue of his entity then he would use example (@3amal_mush_hadha_daaribu_zaydin).

But in practice, they are often (but not always) close enough in meaning that they can be used interchangeably.
Here is another example:

(@ex000526) [فَقَالَ رَسُولُ اللهِ  ﷺ مَنْ **قَائِلُهَا**]{.ar}
    [https://hadithunlocked.com/ahmad:7060]{.citex}  
    [The Messenger of Allah ;pbuh; said: "Who is the sayer of it?"]{.trans}  
    Compare with example (@3amal_mush_muslim_601) [مَنِ **الْقَائِلُ** كَلِمَةَ كَذَا وَكَذَا]{.ar} above.

### The ;ism_fail;-crossover-to-;subst; as a ;na3t;

Once an ;ism_fail; has crossed over to a ;subst;,
it can still be used as a ;na3t;.
This is because the the
;ism_fail;-crossover-to-;subst;
still
signifies its verbal meaning to some degree.
So, for example,
[ضَارِب]{.ar}, even once it has crossed over to a ;subst; still signifies its verbal meaning of being a one who beats.
But because it is now a ;subst;, it will lose its [ال]{.ar} when is a ;mudaf;.
Consider the following example:

(@ex000527) [مررت بزيد ضارب عمر]{.ar}
    [[@muqtadab@ 4/149](https://shamela.ws/book/6965/1163)]{.citex}  
    [I passed by the beater-of-[#eamr]{.trn2} Zayd]{.trans}

See also the ;tafsir;s of:

(@ex000528) [مَـٰلِكِ یَوۡمِ ٱلدِّینِ]{.quran}
    [@https://quran.com/1/4@]{.citex}  
    [Sovereign of the Day of Recompense.]{.trans}

(@ex000529) [ٱلۡحَمۡدُ لِلَّهِ فَاطِرِ ٱلسَّمَـٰوَ ٰ⁠تِ وَٱلۡأَرۡضِ جَاعِلِ ٱلۡمَلَـٰۤىِٕكَةِ رُسُلًا أُو۟لِیۤ أَجۡنِحَةࣲ مَّثۡنَىٰ وَثُلَـٰثَ وَرُبَـٰعَۚ]{.quran}
    [@https://quran.com/35/1@]{.citex}  
    [[All] praise is [due] to Allāh, Creator of the heavens and the earth, [who] made the angels messengers having wings, two or three or four.]{.trans}

### The ;ism_fail;-crossover-to-;subst; of doubly transitive verb

As we have mentioned, when an ;ism_fail; crosses over to a ;subst;,
then it cannot govern a ;faa3il; or an ;astate; governee like a ;mafulb;.
But
an exception is made for the ;ism_fail; of transitive verb that has two ;mafulb;s.
When an ;ism_fail; of such a verb is used with a perfect meaning (as a ;subst;)
in a ;ma3nawi; ;idaafah;,
then it's first semantic ;mafulb; is made into the ;mudafil;
but it's second ;mafulb; remains in the ;astate;.
We mentioned this already in section\ (ref) and gave the following example:

(@ex000530) [هذا معطي زيد أمس درهما]{.ar}
    [[@ibn_malik_sharh_tasheel@ 3/78](https://shamela.ws/book/13257/894#p1)]{.citex}  
    [This [person] was the giver of Zayd, yesterday, a dirham.]{.trans}  

<!--

When the ;ism_fail; that has crossed over to a ;subst; refers to human beings,
then often, but not always, a feminine version of the crossed over ;subst; will also exist, with a [ة]{.ar}.
So [صَاحِبَة]{.ar} is a female companion,
[وَالِدَة]{.ar} is a female parent, etc.
Sometimes, however, the ;subst; exists for only one gender and not for the other,
e.g. [جَارِيَة]{.ar} [a girl]{.trans}.
Also sometimes, the same ;subst; is used for both genders,
e.g.
[بَالِغ]{.ar}   [a legally mature person]{.trans},
[آثِم]{.ar} [a sinner]{.trans}.
There is often some flexibility in these cases, so 
[بَالِغَة]{.ar} can be used for  a female legally mature person.
The dictionary is the best guide in these matters.
-->

### An ;ism_fail; can co-exist  with its ;ism_fail;-crossover-to-;subst;s

When a cross-over ;subst; exists, it does not mean that the original ;ism_fail; meaning has ceased to exist.
Both can continue to exist and context will clue us in as to which meaning is intended.
For example, [بَالِغ]{.ar} is used as an ;ism_fail; here:

(@3amal_mush_hadyan_baaligha_lka3bati) [هَدۡیَۢا بَـٰلِغَ ٱلۡكَعۡبَةِ]{.quran}
    [@https://quran.com/5/95@]{.citex}  
    [as an offering [to Allāh] delivered to the Kaʿbah]{.trans}

For some cross-over ;subst;s, however, the ;subst; usage is predominant and the original ;ism_fail; meaning is virtually non-existent.
Such is the case for [صَاحِب]{.ar} [a companion]{.trans} and [وَالِد]{.ar} [a parent]{.trans}.^[@za3balawi_dirasat@ 488 citing [سيبويه]{.ar} and others]

<!--
Also, by the way,
the same
;ism_fail;-crossover-to-;subst;
can exist in multiple categories.

So, for example,
[حَامِل]{.ar}
can be used 
-->

## Eligibility to be described with the ;ism_fail;

Theoretically,
anyone who is the ;faa3il; of a verb can be described with its ;ism_fail;.
So, for example,
any person who is the ;faa3il; of the verb [قَرَأَ]{.ar}, even once, can be called a
[قَارِئ]{.ar}.
And from context it will be understood that the person is being called a [قَارِئ]{.ar} within the situation of a certain reading or recitation.
Here are some examples:

(@ex000531) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم صَلَّى الظُّهْرَ فَجَعَلَ رَجُلٌ يَقْرَأُ خَلْفَهُ بِسَبِّحِ اسْمَ رَبِّكَ الأَعْلَى فَلَمَّا انْصَرَفَ قَالَ  أَيُّكُمْ قَرَأَ  أَوْ  أَيُّكُمُ **الْقَارِئُ**]{.ar}
    [@https://sunnah.com/muslim:398b@]{.citex}  
    _that the Messenger of Allah ;pbuh; prayed the [Puhr]{.trn2} prayer, and a man began to recite behind him [[sUrat al-#aelA]{.trn2}]. When [the Prophet ;pbuh; concluded the prayer and] turned around, he said: "Which of you recited?" or "Which of you [was] **the reciter**?"_

(@ex000532) [سَمِعَ النَّبِيُّ صلى الله عليه وسلم **قَارِئًا** يَقْرَأُ مِنَ اللَّيْلِ فِي الْمَسْجِدِ]{.ar}
    [@https://sunnah.com/bukhari:5042@]{.citex}  
    _The Prophet ;pbuh; heard **a reciter** reciting the [#qurEAn]{.trn2} in the mosque at night._

Having said that,
the ;ism_fail; is a noun.
And a noun, by its very nature, signifies a more permanence and constancy in its meaning than a verb.
So there can be scenarios where being described by an ;ism_fail; 
can have a higher bar of eligibility than simply being the ;faa3il; of a verb.
Consider for example
 [سورة الكافرون]{.ar}:

::: {.quran}
قُلۡ یَـٰۤأَیُّهَا ٱلۡكَـٰفِرُونَ۝
لَاۤ أَعۡبُدُ مَا تَعۡبُدُونَ۝
وَلَاۤ أَنتُمۡ عَـٰبِدُونَ مَاۤ أَعۡبُدُ۝
وَلَاۤ أَنَا۠ عَابِدࣱ مَّا عَبَدتُّمۡ۝
وَلَاۤ أَنتُمۡ عَـٰبِدُونَ مَاۤ أَعۡبُدُ۝
لَكُمۡ دِینُكُمۡ وَلِیَ دِینِ۝
:::



[@https://quran.com/109@]{.citex}  
_Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you worship. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."_

[#ibn al-#qayyim]{.trn2} says,
in the [tafsIr]{.trn2} of this ;surah;:

> Negation isn't employed for [the disbelievers] except by the ;ism_fail;. And for [the Prophet ;pbuh;], [negation] is employed once using the verb, and once using the ;ism_fail;.
>
> And this is -- and [#allAh]{.trn2} knows best -- due to a marvelous wisdom, which is that the greater objective is [the Prophet's ;pbuh;] disassociation from their gods from every perspective and in every [instance of] time.
> So [the Prophet ;pbuh;, in speaking to the disbelievers with the words of the revealed ;surah;], used first the verb [[أَعْبُدُ]{.ar}],
> which signifies dynamic occurrence,
> and then used for this same negation the ;ism_fail; [[عَابِد]{.ar}] in the second instance,
> i.e. "This [worshipping of what you worship] is not my description nor my state of affairs."
> [This is] as if he had said: "Worshipping other than [#allAh]{.trn2} will not be an verbal action of mine, nor a descrption of mine."
> Thus he used two negations for two negated items [a verbal action, and a description], that are intended by the negation.
>
> As for [the negation used for the disbelievers], he used only the ;ism_fail; [[عَابِدُونَ]]{.ar},
> which signifies the description [of its referent by the ;ism_fail;] and the stability [of this description],
> i.e. "The stable, requisite, description [of being a worshipper] of [#allah]{.trn2} is negated from you.
> For this description cannot be established for you.
> It is only established for the one who singles out [#allAh]{.trn2} exclusively for worship,
> and then does not associate anyone with Him.
> But you, because you have worshipped other than Him, are not from His worshippers."
> Even if they may have worshipped [#allAh]{.trn2} some of the time.
> For the polytheist worships [#allAh]{.trn2} and worships, with Him, others besides Him.
> Just like the People of the Cave said:
> [And when you have withdrawn from them and that which they worship other than Allāh]{.trans} [@https://quran.com/18/16@]{.citex}
> i.e., "you have withdrawn from their gods excluding [#allAh]{.trn2}, for you have not withdrawn from Him."
> And similarly did the polytheists say regarding their gods:
> ["We only worship them that they may bring us nearer to Allāh in position."]{.trans} [@https://quran.com/39/3@]{.citex}.
> Thus they used to worship, with Him, others besides Him.
> So the verb [[عَبَدَ يَعْبُدُ]{.ar}] is not negated from them because of its occurrence from them.
> But the description [[عَابِد]{.ar}] is negated because whoever worshipped other than [#allAh]{.trn2}
> is not established on the worship of [#allAh]{.trn2}, and is not described by [being a worshipper of [#allAh]{.trn2}].^[@https://tafsir.app/ibn-alqayyim/109/6@]




<!--
## Temporariness or permanence of the meaning of ;ism_fail;
-->

<!--
In this section, we will discuss at what point the ;faa3il; of a verb may be ascribed by the ;ism_fail;.
For example, if a person reads or recites only one word, can he be described as a [قَارِئ]{.ar}?
Or does the person need to read/recite a large amount of text to qualify being called a [قَارِئ]{.ar}?
-->
<!--
The answer is: it depends on what is intended to be meant by the ;ism_fail; [قَارِئ]{.ar}.
-->

<!--
In theory, the ;ism_fail; has a temporary and incidental applicability that is tied to the occurence of a verb.
For example,
theoretically, any person who is, was, or will be, the ;faa3il; of the verb [قَرَأَ]{.ar}, even once, can be called a
[قَارِئ]{.ar}.
And from context it will be understood that the person is being called a [قَارِئ]{.ar} within the situation of a certain reading or recitation.
For example:
-->

<!--
(@ex000533) [إِنَّ رَجُلاً أَسْلَمَ فِي حَدِيقَةِ نَخْلٍ فِي عَهْدِ رَسُولِ اللَّهِ ـ صلى الله عليه وسلم ـ قَبْلَ أَنْ يُطْلِعَ النَّخْلُ فَلَمْ يُطْلِعِ النَّخْلُ شَيْئًا ذَلِكَ الْعَامَ فَقَالَ الْمُشْتَرِي هُوَ لِي حَتَّى يُطْلِعَ . وَقَالَ الْبَائِعُ إِنَّمَا بِعْتُكَ النَّخْلَ هَذِهِ السَّنَةَ .]{.ar}
    [@https://sunnah.com/ibnmajah:2284@]{.ar}  
    _A man paid in advance for a grove of trees during the time of the Messenger of Allah ;pbuh;, before they had produced any fruit, and they did not bear anything that year. The purchaser said: "They belong to me until they produce." But the **seller** said: "I only sold the trees to you for this year!"_
-->

<!--
(@ex000534) [أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم صَلَّى الظُّهْرَ فَجَعَلَ رَجُلٌ يَقْرَأُ خَلْفَهُ بِسَبِّحِ اسْمَ رَبِّكَ الأَعْلَى فَلَمَّا انْصَرَفَ قَالَ  أَيُّكُمْ قَرَأَ  أَوْ  أَيُّكُمُ **الْقَارِئُ**]{.ar}
    [@https://sunnah.com/muslim:398b@]{.citex}  
    _that the Messenger of Allah ;pbuh; prayed the [Puhr]{.trn2} prayer, and a man began to recite behind him [[sUrat al-#aelA]{.trn2}]. When [the Prophet ;pbuh; concluded the prayer and] turned around, he said: "Which of you recited?" or "Which of you [was] **the reciter**?"_

(@ex000535) [سَمِعَ النَّبِيُّ صلى الله عليه وسلم **قَارِئًا** يَقْرَأُ مِنَ اللَّيْلِ فِي الْمَسْجِدِ]{.ar}
    [@https://sunnah.com/bukhari:5042@]{.citex}  
    _The Prophet ;pbuh; heard **a reciter** reciting the [#qurEAn]{.trn2} in the mosque at night._

If a person has done the action of the verb many times, or is skilful in it, or does the action as his profession,
then the ;ism_fail; crosses over to the meaning of the ;subst;.
In these cases he can be described by the ;ism_fail;-crossover-to-;subst; generally.
For example:

(@ex000536) [وَقَرَأْتَ الْقُرْآنَ لِيُقَالَ هُوَ **قَارِئٌ**]{.ar}
    [@https://sunnah.com/muslim:1905a@]{.citex}  
    _And you recited the [#qurEAn]{.trn2} in order that it be said: "He is **a reciter**."_

(@ex000537) [عَنْ سَعِيدِ بْنِ عُبَيْدٍ وَكَانَ يُدْعَى فِي زَمَنِ النَّبِيِّ صلى الله عليه وسلم **الْقَارِئَ**]{.ar}
    [https://hadithunlocked.com/tabarani:5540]{.citex}  
    _[It was narrated] from [#saeId ibn #eubayd]{.trn2}, and he was called in the time of the Prophet ;pbuh; **the reciter**..._
-->

### The ;ism_fail; indicating a habitual doer

In addition to the default incidental meaning,
the meaning of the doer that is indicated by the ;ism_fail; can be a habitual meaning.
For example:

<!--
Can be sure of tashkeel.
(@ex000538) [عَنِ النَّبِيِّ ﷺ أَنَّهُ قَالَ لَا يَدْخُلُ الْجَنَّةَ مَنَّانٌ وَلَا **عَاقٌّ وَالِدَيْهِ** وَلَا مُدْمِنُ خَمْرٍ]{.ar}
    [https://hadithunlocked.com/ahmad:6882]{.citex}  
    [It was narrated] from the Prophet ;pbuh; that he said: "One who reminds people (of what he has given them) will not enter Paradise, nor **a disobeyer** to his parents, nor one addicted to wine."
-->

(@ex000539) [زَيْدٌ مُكْرِمٌ ضِيفَانِهِ]{.ar}
    [[@za3balawi_dirasat@ 482](https://shamela.ws/book/2120/482)]{.citex}  
    [Zayd is an honorer to his guests]{.trans}  

## Verbs for which the ;ism_fail; is rarely used

### The ;ism_fail; for stative verbs

Technically, an ;ism_fail; can be formed from any verb.^[@nahw_wafi@ 3/242]
For form\ 1 verbs, it will always be on the pattern [فَاعِل]{.ar}.
However, there are some verbs for which their ;ism_fail;s are rarely used.

These are verbs which indicate only being in a static state,
with virtually no dynamic action.
The meaning signified is usually (but not exclusively) an innate permanent quality.
For such verb, the their ;sifah_mush;s
(see chapter\ (ref))
are generally used instead of their ;ism_fail;s.
The following table lists some such verbs,
along with their rarely used ;ism_fail;s,
and their commonly used ;sifah_mush;s.

|verb|meaning|;ism_fail;|;sifah_mush;|
|:--|:-----|:--|:-----|
|[كَرُمَ]{.ar} |[to be noble, generous]{.trans}  |[كَارِم]{.ar}|[كَرِيم]{.ar} [noble, generous]{.trans}|
|[بَخِلَ]{.ar} |[to be stingy]{.trans}           |[بَاخِل]{.ar}|[بَخِيل]{.ar} [stingy]{.trans}|
|[فَرِحَ]{.ar} |[to by joyous]{.trans}           |[فَارِح]{.ar}|[فَرِح]{.ar}  [joyous]{.trans}|
|[ضَاقَ]{.ar} |[to be narrow]{.trans}           |[ضَائِق]{.ar}|[ضَيِّق]{.ar}  [narrow]{.trans}|
|[حَسُنَ]{.ar} |[to be handsome]{.trans}         |[حَاسِن]{.ar}|[حَسَن]{.ar}  [handsome]{.trans}|


Nevertheless,
the ;ism_fail;s for such verbs can be used,
on occasion,
to indicate a incidental state that has only temporary occurred.
As opposed to the more permanent state that the ;sifah_mush; would signify.^[@nahw_wafi@ 3/240 footnote 3; @nahw_wafi@ 3/292]
For example:

(@ex000540) [فَلَعَلَّكَ تَارِكُۢ بَعۡضَ مَا یُوحَىٰۤ إِلَیۡكَ **وَضَاۤىِٕقُۢ** بِهِۦ صَدۡرُكَ أَن یَقُولُوا۟ لَوۡلَاۤ أُنزِلَ عَلَیۡهِ كَنزٌ أَوۡ جَاۤءَ مَعَهُۥ مَلَكٌۚ]{.quran}
    [@https://quran.com/11/12@ cited by @nahw_wafi@ 3/240 footnote 3]{.citex}  
    [Then would you possibly leave [out] some of what is revealed to you, or is your breast constrained by it because they say, "Why has there not been sent down to him a treasure or come with him an angel?"]{.trans}

According to the commentary on this ;ayah;,
[ضَائِق]{.ar} is used in place of he more commonly used [ضَيِّق]{.ar} to indicate a temporary constrictness.^[@nahw_wafi@ 3/240 footnote 3 citing @ibn_ya3ish_mufassal@ and others; @https://tafsir.app/kashaf/11/12@]

<!--
Here is another example:

(@ex000541) [وَمَا أَنَا مِنْ رُزْءٍ وَإِنْ جَلَّ جَازِعٌ وَلَا بِسُرُورٍ بَعْدَ مَوْتِكَ فَارِحُ]{.ar}
    [And I am not, because of a calamity, even if be great, impatient. Nor [am I] in happiness after your death, [and] joyous]{.trans}
-->

### The ;ism_fail;-crossover-to-;sifah_mush;

Sometimes, 
for stative verbs like the above
what would appear to be an ;ism_fail; is very commonly used.
But actually, these usages are from the class of ;ism_fail;-crossover-to-;sifah_mush;s.
Here are some examples:

|verb|meaning|;ism_fail;-crossover-to-;sifah_mush;|
|:--|:-----|:-----|
|[عَدَلَ]{.ar} |[to be just]{.trans}           |[عَادِل]{.ar} [just]{.trans}|
|[بَسُلَ]{.ar} |[to be courageous]{.trans}     |[بَاسِل]{.ar} [courageous]{.trans}|
|[صَلُحَ]{.ar} |[to be righteous]{.trans}      |[صَالِح]{.ar} [righteous]{.trans}|
|[رَبِحَ]{.ar} |[to be profitable]{.trans}     |[رَابِح]{.ar} [profitable]{.trans}|
|[نَعُمَ]{.ar} |[to be soft]{.trans}           |[نَاعِم]{.ar} [soft]{.trans}|

We will study this category in more detail in section\ (ref), ;ia;.

### Verbs for which the ;ism_fail; is rarely used in place of the ;mudarie; verb

The ;ism_fail; is also
not found used in place of a ;mudarie; verb for various other classes of verbs,
including verbs  that indicate mental states, perception, or action.^[See @marmor_tense@ 124]
Such verbs include
[رَأَى]{.ar} to see,
[رَجَا]{.ar} to hope,
[أَرَادَ]{.ar} to want,
and others.
For such verbs, only the verb is typically used when the meaning of the verb is needed.
Nevertheless, the ;ism_fail; for such verbs has been found to be used on occasion.
Examples:

(@ex000542) [أَنَّ رَسُولَ اللَّهِ ص لَمَّا انْصَرَفَ مِنَ الطَّائِفِ **مُرِيدًا** مَكَّةَ مَرَّ بِهِ بَعْضُ أَهْلِ مَكَّةَ]{.ar}
    [[@tarikh_tabari@ 2/347](https://shamela.ws/book/9783/972) cited by @waltisberg_satzkomplex@ 293]{.citex}  
    that the Messenger of Allah, when he departed from [al-#TAEif]{.trn2} intending (as his destination) Makkah, one of the people of Makkah passed by him.

(@ex000543) [أُرَانِي اللَّيْلَةَ عِنْدَ الْكَعْبَةِ فَرَأَيْتُ رَجُلاً آدَمَ كَأَحْسَنِ مَا أَنْتَ **رَاءٍ** مِنْ أُدْمِ الرِّجَالِ]{.ar}
    [@https://sunnah.com/bukhari:6999@]{.citex}  
    I saw myself (in a dream) near the [#kaebah]{.trn2} last night, and I saw a man with whitish red complexion, the best you may see amongst men of that complexion.


The ;ism_fail; of such verbs may also freely be used when its essential "doer" meaning is intended.
For example:

(@ex000544) [وَكَمْ مِنْ **مُرِيدٍ** لِلْخَيْرِ لَنْ يُصِيبَهُ]{.ar}
    [https://hadithunlocked.com/darimi:210]{.citex}  
    [How many of an intender of goodness shall not achieve it.]{.trans}

## Further reading

1. @fischer@ §201--§204, pp.\ 111--113.
1. @kinberg_participal@
1. @marmor_tense@
1. @odilavadze_participle@
1. @owens_participle@
1. @putten_participles@
1. @waltisberg_satzkomplex@
1. @wright@, vol.\ ii, §30--§31 pp.\ 63--69, §72--§74 pp\. 194--198.
1. @youssef_partizip@
1. @za3balawi_dirasat@ pp.\ 480--525.
1. @maani_nahw@ [3/170ff.](https://shamela.ws/book/17801/895)
1. @nahw_wafi@ 3/240 footnote 3, 3/241, 3/292ff.
1. @shadi_ism_faa3il@
1. @hamid_ism_faa3il@

