# The ;mmutlaq;

## Introduction

The ;mmutlaq; is, fundamentally, the verb taking it's own
;masdar;
as a ;maful; in the ;astate;.
For example,

(@) [ضَرَبَ زَيْدٌ عَمْرًا ضَرْبًا]{.ar}  
    "Zayd beat [#eamr]{.trn2} a beating"

In the above example
[ضَرْبًا]{.ar}
is the 
;masdar;
of the verb
[ضَرَبَ]{.ar}
and is governed by it in the ;astate; as its ;mmutlaq;.

This sort of sentence is unfamiliar in English,
as evinced by its awkward translation,
"Zayd beat [#eamr]{.trn2} a beating."
Nevertheless, we can find some parallels so you can get a feel for it:

(@) 1. "He died an honorable death."
    2. "He slept the sleep of the just."
    3. "He lived two lives."

The ;mmutlaq; is somewhat different from the direct ;maful; in that the ;mafulb; only occurs for ;mutaddi; verbs.
Whereas, the ;mmutlaq; can occur for any verb, whether ;mutaddi; or ;lazim;
Also, the ;mmutlaq; is effectively an adverb because it qualifies the meaning of the verb as we will learn in this chapter,
if [#allAh]{.trn2} wills.

The ;mmutlaq; is used for the following purposes:

1. To reinforce or emphasize the meaning of the governing verb.
2. To qualify the meaning of the governing verb.
3. To act as a ;naib; for the governing verb, substituting it and fulfilling it's role.

## The reinforcing ;mmutlaq;

Reinforcing and emphasizing the meaning of the governing verb is the basic function of the ;mmutlaq;.
Consider again our earlier example:

(@) [ضَرَبَ زَيْدٌ عَمْرًا ضَرْبًا]{.ar}  
    "Zayd beat [#eamr]{.trn2} a beating"

The ;mmutlaq; [ضَرْبًا]{.ar} signifies that beating actually ocurred,
as if to
counter any possible suspicion that it didn't.
If the usage of the governing verb can support both a literal and a metaphorical meaning, then
the ;mmutlaq; can also signify that the meaning of the verb is literal, and not metaphorical.^[See [معاني النحو]{.ar} 2/194--195. But see also <https://tafsir.app/ibn-alqayyim/4/164> ([وكلم الله موسى تكليما]{.ar}) and <https://tafsir.app/ibn-uthaymeen/27/50> ([ومكروا مكرًا ومكرنا مكرًا]{.ar})]

For greater emphasis, the ;masdar; may be repeated.^[Wright, 2/55B]
For example,

<!--
(@) [إِذَا دُكَّتِ ٱلْأَرْضُ دَكًّا دَكَّا]{.ar}
is passive...
-->

The reinforcing ;mmutlaq;, when used purely for emphasis and not also for other purposes, cannot be dualized or pluralized.
So we cannot say $\times$\ [وَعَدْتُكَ وُعُودًا]{.ar} ("I promised you promises").^[@nahw_wafi@ 2/211]
Though, this sentence is correct for the other purposes of the ;mmutlaq;, which we will learn in subsequent sections,
if [#allAh]{.trn2} wills.

## The qualifying ;mmutlaq;

With regard to the meaning of the governing verb, the qualifying ;mmutlaq; indicates either what kind was intended, or its quantity, or both.

The kind of the ;masdar; is frequently used with a ;na3t; or in an ;idaafah;.
For example,

(@) [ضَرَبْتُهُ ضَرْبًا شَدِيدًا]{.ar}
    [Wright, 2/54A]{.citex}  
    "I beat him (with) a severe beating."

(@) [ضَرَبَهُ ضَرْبَ ٱلظَّالِمِ]{.ar}
    [Wright, 2/54B]{.citex}  
    "He beat him (with) the beating of an oppressor."

Such a qualifying ;mmutlaq; may also be signified simply with the definite article [ٱل]{.ar}.^[@nahw_wafi@ 2/207 (footnote 4)]. For example, if a specific kind of beating is known before-hand to both the speaker and addressee, then the speaker may simply say:

(@) [أَضْرِبُهُ ٱلضَّرْبَ]{.ar}  
    "I will beat him (with) _the_ beating."

The qualifying ;masdar; may also be annexed to a pronoun referring to the ;faa3il; of the verb.
For example,

(@) [ضَرَبَ ضَرْبَهُ]{.ar}  
    "He beat him (with) his beating"

The quantity of the ;masdar; often uses the _;ism_marrah;_.
It may be dualized or pluralized.
For example,

(@) [ضَرَبْتُهُ ضَرَبْةً وَضَرَبَنِي ضَرْبَتَيْنِ أَوْ ضَرَبَاتٍ]{.ar}
    [Wright, 2/53D]{.citex}  
    "I beat him one blow and he beat me two blows or (three or more) blows."

Some ;masdar;s themselves end with a [ة]{.ar}, like [تِلَاوَة]{.ar},
so they are readily dualized or pluralized^[[[الكليات لأبي البقاء الكفوي]{.ar} 817](https://shamela.ws/book/7037/803)]
(to the sound [At]{.trn} plural)
without resorting to the ;ism_marrah;.
For example,

(@) [تَلَا ٱلْقَارِئُ تِلَاوَاتٍ]{.ar}  
    "The reader recited recitations."

But in reality, when a ;masdar; is dualized or pluralized in this manner,
it seems to leave its ;masdar; meaning,
which is purely a verbal meaning,
and begins to denote a concrete or abstract noun.^[[[دراسات في النحو لصلاح الدين الزعبلاوي]{.ar} 137](https://shamela.ws/book/2120/137#p1)]
So [تِلَاوَات]{.ar} will denote, not so much the actions of reciting but kinds of recitations.

The same goes for ;masdar;s that don't end with a [ة]{.ar} but for whom a broken plural has been recorded from Classical Arabic,
like
[عُلُوم]{.ar}, which is the plural of [عِلْم]{.ar} "knowledge",
and [وُعُود]{.ar} which is the plural of [وَعْد]{.ar} "promise".

So we can say:

(@) [وَعَدْتُكَ وُعُودًا]{.ar}  
    "I promised you promises."

[وُعُود]{.ar} here refers to different kinds or occasions of promises, rather than the purely verbal actions of promising.^[See also <https://tafsir.app/ibn-aashoor/33/10> ([وتظنون بالله الظنونا]{.ar})]

Plurals have not been recorded for all ;masdar;s.
For example, [ضَرْب]{.ar} does not have a recorded plural for its ;masdar; meaning of "beating".

So can we pluralize it if we wish to say "I beat him (many) kinds of beatings"?
Some authorities allow us to form a new broken plural if there is a need.^[[[دراسات في النحو لصلاح الدين الزعبلاوي]{.ar} 139](https://shamela.ws/book/2120/139#p1)]
So according to them we should be able to 
coin a new plural
[ضُرُوب]{.ar}^[this plural already exists for [ضَرْب]{.ar} but for its other meaning "example"] "beatings"
and say,

(@) [ضَرَبْتُهُ ضُرُوبًا]{.ar}  
    "I beat him (many kinds of) beatings"

Other authorities are more conservative and would only allow using broken plurals for existing meanings of words if one has been recorded for them. Following this opinion, we might then say:

(@) [ضَرَبْتُهُ أَنْوَاعًا مِنَ ٱلضَّرْبِ]{.ar}  
    "I beat him (many) kinds of beatings"

In any case, any ;masdar; may at least be dualized to indicate the kinds of its action.^[@nahw_wafi@ 2/212]
So we can say:

(@) [ضَرَبَنِي ضَرْبَيْنِ]{.ar}
    [Wright 2/55D]{.citex}  
    "He beat me two (kinds of) beatings."  
    or  
    "He beat me (on) two (occasions of) beatings."

By the way, you should be able to see that saying
[ضَرَبَنِي ضَرْبَيْنِ]{.ar}
is different from if we had said

(@) [ضَرَبَنِي ضَرْبَتَيْنِ]{.ar}  
    "He beat me (with) two blows."

The former signifies the kinds or occasions of beating
whereas the latter indicates the number of individual acts of beating.

By the way, for ;masdar;s that themselves end with [ة]{.ar},
if we wish to specify that the action ocurred only once,
we cannot, of course, form a ;ism_marrah; by appending another [ة]{.ar} to it.
In such a case, we may qualify the ;masdar; with the ;na3t; [وَاحِدَة]{.ar} "once".
For example:

(@) [رَحِمَهُ رَحْمَةً وَاحِدَةً]{.ar}
    [Wright 1/123C]{.citex}  
    "He took one mercy upon him."

It is also important to mention that the qualifying ;mmutlaq; includes the reinforcing meaning.^[@nahw_wafi@ 2/207--209]
We cannot use the qualifying ;mmutlaq; without also emphasizing the meaning of the verb.
For example,

(@) [فَٱصْبِرْ صَبْرًا جَمِيلًا]{.ar}
    [<https://quran.com/70/5>]{.citex}  
    "So be patient with gracious patience"

In section (ref), we will see that in order to only qualify the verb without emphasizing it, we can substitute the verb with the ;mmutlaq; which then becomes a _;naib; to the verb_.^[[معاني النحو]{.ar} 2/203]

Finally, the qualifying ;mmutlaq; may qualify both the kinds and quantity of the meaning of the verb.
For example:

(@) [قَرَأْتُ ٱلْكِتَابَ قِرَاءَتَيْنِ نَافِعَتَيْنِ]{.ar}
    [@nahw_wafi@ 2/209]{.citex}  
    "I read the book two useful readings."

## The ;naib; to the ;masdar; as an ;mmutlaq;

Frequently, instead of using the ;masdar; as the ;mmutlaq; directly,
it is substituted by another word.
This word is then called the ;naib; to the ;masdar; as an ;mmutlaq; because it fulfils the ;mmutlaq;'s role.
The ;masdar; may still figure in the expression.
It will just not technically be the ;mmutlaq;, because the first ;astate; ;maful; in that position is now its ;naib;.

The ;naib; to the ;masdar; can be one of several categories:

#### A ;na3t; to a deleted ;masdar; {.unnumbered}

For example:

(@) [ضَرَبْتُهُ شَدِيدًا]{.ar}
    [Wright, 2/54A]{.citex}  
    "I beat him severely."  
    (for [ضَرَبْتُهُ ضَرْبًا شَدِيدًا]{.ar} "I beat him a severe beating.")

(@) [سِرْتُ أَحْسَنَ ٱلسَّيْرِ]{.ar}
    [[[أوضح المسالك إلى ألفية ابن مالك لابن هشام]{.ar} 2/184](https://shamela.ws/book/11825/551)]{.citex}  
    "I travelled the best (kind) of travelling."  
    (for [سِرْتُ ٱلسَّيْرِ أَحْسَنَ ٱلسَّيْرِ]{.ar})

When the ;masdar; is thus substituted with its ;na3t;, then the masculine ;sifah; is typically used for the ;na3t;,
even if the ;masdar; was a feminine noun.
For example:

(@) [كَتَبُوا سَرِيعًا]{.ar}  
    "They wrote quickly."  
    (for [كَتَبُوا كِتَابَةً سَرِيعَةً]{.ar})

This is because even when
;masdar;s
end with a feminine marker,
they are abstract enough in their meaning that when they are absent,
only the idea of them retains influence, not their actual wording.
And because that abstract idea is not feminine in its meaning,
it doesn't cause the ;na3t; to match the feminine wording of the ;masdar; in gender.
So, by default, the masculine ;sifah; is used for the ;na3t;.

Also, the ;astate; ;sifah; in such phrases as 
[ضَرَبْتُهُ شَدِيدًا]{.ar}
may, where the sense allows or requires it, be a ;naib; to the ;dharf_zaman;
instead of a ;naib; to the ;mmutlaq;.^[Wright 2/54D]
For example: [سَارُوا طَوِيلًا]{.ar} "They travelled a long time,"
(for [سَارُوا زَمَنًا طَوِيلًا]{.ar}. See section\ (ref).)

In fact, according to some authorities,
when the ;astate; noun in such phrases could be applied to both
a deleted ;mmutlaq;
or a deleted ;dharf_zaman;
(or, for that matter, other ;astate; functions like a ;mafulb;),
then it is possible that both meanings could be intended.^[[معاني النحو]{.ar} 2/196--199]
For example,

(@mmutlaq_mmutlaq_dharf) [ضَرَبْتُهُ كَثِيرًا]{.ar}  
    "I beat him a lot."

This sentence could mean, at the same time, both 
[ضَرَبْتُهُ ضَرْبًا كَثِيرًا]{.ar}
"I beat him a lot [of beatings]," and
[ضَرَبْتُهُ زَمَنًا كَثِيرًا]{.ar}
"I beat him (for) a lot [of time]."

#### An ;ism_masdar; {.unnumbered}

The ;ism_masdar; may be a regular common noun that is used in place of a verb's ;masdar;
(see (ref)).

For example:

(@) [فَرَجَعَ إِلَى قَوْمِهِ فَقَالَ يَا قَوْمِ أَسْلِمُوا فَإِنَّ مُحَمَّدًا يُعْطِي عَطَاءً لاَ يَخْشَى الْفَاقَةَ]{.ar}
    [<https://sunnah.com/muslim:2312a>]{.citex}  
    "So he returned to his people and said, 'O my people, embrace [#islAm]{.trn2} for indeed [#muHammad]{.trn2} gives a gift not fearing want.'"  
    ([عَطَاء]{.ar} "gift" is a ;ism_masdar; for the actual ;masdar; [إِعْطَاء]{.ar}.)

(@) [ٱنْهَزَمُوا هَزِيمَةً شَنِيعَةً]{.ar}  
    [Wright 2/56B]{.citex}  
    "They were defeated an atrocious defeat"  
    (The ;masdar; of [ٱنْهَزَمَ]{.ar} is properly [ٱنْهِزَام]{.ar})

Also falling under the category of ;ism_masdar; is the ;masdar; of another form of the verb from the same root.^[@nahw_wafi@ 2/215].
For example:

(@) [ٱقْتَتَلُوا قِتَالًا شَدِيدًا]{.ar}
    [Wright 2/56B]{.citex}  
    "They fought with one another a hard fight"  
    ([قِتَال]{.ar} is properly the ;masdar; of the form\ 3 verb [قَاتَلَ]{.ar})

(@) [وَتَبَتَّلْ إِلَيْهِ تَبْتِيلًا]{.ar}
    [<https://quran.com/73/8>]{.citex}  
    "and devote yourself to Him with [complete] devotion"  
    ([تَبْتِيل]{.ar} is properly the ;masdar; of the form\ 2 verb [بَتَّلَ]{.ar})

#### A synonymous ;masdar; from a different root {.unnumbered}

For example:

(@) [جَلَسَ قُعُودًا]{.ar}
    [Wright, 2/56C]{.citex}  
    "I sat (with) a sitting"

#### A noun that indicates the type of ;masdar; {.unnumbered}

For example:

(@) [رَجَعَ ٱاْقَهْقَرَىٰ]{.ar}
    [Wright 2/56C]{.citex}  
    "He returned walking backwards."  
    [قَهْقَرَىٰ]{.ar} is a noun which means "backward walk".

#### A ;ism_hay2ah; of the pattern [فِعْلَة]{.ar} {.unnumbered}

For example:

(@) [مشى القط مشية الأسد]{.ar}
    [@nahw_wafi@ 2/218]{.citex}  
    "The cat walked (with) the gait of a lion"

#### The number of the ;masdar; {.unnumbered}

For example:

(@) [ضَرَبْتُ ثَلَاثَ ضَرَبَاتٍ]{.ar}  
    "I beat him three blows"

The ;masdar; may also be omitted from the base noun such that only the number remains.
For example:

(@) [ضَرَبْتُ ثَلَاثًا]{.ar}  
    "I beat him three (blows)"  
    (Note the feminine number [ثَلَاث]{.ar} instead of the masculine [ثَلَاثَة]{.ar} because the deleted base noun will be feminine in such circumstances.)

#### A partial or whole fraction {.unnumbered}

Words like
[كُلّ]{.ar}, [جَمِيع]{.ar} "all";
[بَعْض]{.ar} "some";
[نِصْف]{.ar}, [شَطْر]{.ar} "half", etc.
can be used to indicate how much of an action is done.

For example:

(@) [فَلَا تَيِيلُوا كُلَّ ٱلْمَيْلِ]{.ar}
    [<https://quran.com/4/129>]{.citex}  
    "So do not incline completely [toward one]"

(@) [أَهْمَلَ ٱلطَّالِبُ بَعْضَ ٱلْإِهْمَالِ]{.ar}
    [[النحو العربي للسامرائي]{.ar} 1/452]{.citex}  
    "The student was negligent somewhat"

Included in this category is the word [شَيْء]{.ar} "thing".
When used in the ;astate; governed by a verb it can signify the meaning "a bit" or "somewhat", etc.^[See, for example, <https://tafsir.app/ibn-aashoor/17/74> ([كِدتَّ تَرْكَنُ إِلَيْهِمْ شَيْـًٔا قَلِیلًا]{.ar})]
For example:

(@) [فَسَارَ عَلِيٌّ شَيْـًٔا ثُمَّ وَقَفَ]{.ar}
    [<https://sunnah.com/muslim:2405>]{.citex}  
    "So [#ealiyy]{.trn2} went a bit, then he stopped"

The ;astate; noun [شَيْـًٔا]{.ar} isn't always a ;mmutlaq; after a verb.
It may be, depending on the meaning of the sentence, a ;mafulb;.
For example, in the [وَجَدْتُ شَيْـًٔا]{.ar} "I found something."
However, in some circumstances,
[شَيْـًٔا]{.ar}
may make sense both as an ;mmutlaq; and as a ;mafulb;.^[[معاني النحو]{.ar} 2/199]
For example:

(@mmutlaq_shirk_mafulb_mmutlaq) [وَلَا تُشْرِكُوا بِهِ شَيْـًٔا]{.ar}
    [<https://quran.com/4/36>]{.citex}  
    "and associate nothing with Him"

Regarding this [Ayah]{.trn2},
the mufassir [#ibn #eAcUr]{.trn2} says:

> [شَيْـًٔا]{.ar} is in the ;astate; due to its being a [direct] ;maful; for [تُشْرِكُوا]{.ar}, i.e. "Don't make a partner anything from what is worshipped", similar to His saying, [ولَنْ نُشْرِكَ بِرَبِّنا أحَدًا]{.ar} [<https://quran.com/72/2>]{.citex} ("And we will never associate with our Lord anyone"). 
> 
> And it is permissible that [شَيْـًٔا]{.ar} is in the ;astate; due to its being [a ;naib; to] the ;masdar;, i.e. "a bit of associating even if it is slight", similar to His saying, [فَلَنْ يَضُرُّوكَ شَيْـًٔا]{.ar} [<https://quran.com/5/42>]{.citex} ("never will they harm you at all.").^[See <https://tafsir.app/ibn-aashoor/4/36>]

<!--
Also included in this category are nouns like
[عَامَّة]{.ar} "generally",
and
[خَاصَّة]{.ar} "specially, specifically".

(@) [فَقَالَ أَصْحَابُهُ يَا رَسُولَ اللَّهِ أَلِهَذَا خَاصَّةً أَمْ لِلنَّاسِ عَامَّةً]{.ar}
    [<https://sunnah.com/tirmidhi:3115>]{.citex}  
    "So his companions said, 'O Messenger of [#allAh]{.trn}, is [it] for this [person] specifically, or for the people generally?"

^ probably wrong. should be Haal.See tafsirs for خاصة and كافة.
-->

#### The instrument or implement used in the action {.unnumbered}

The type of action may be indicated with the
the instrument or implement used in the action.
For example:

(@) [ضَرَبْتُهُ سَوْطًا]{.ar}
    [Wright 2/56D]{.citex}  
    "I beat him (with) a whip."  
    (for [ضَرْبَ سَوْطٍ]{.ar})

#### A pronoun {.unnumbered}

A ;mmutlaq; can be substituted by a pronoun that refers to it.^[See also <https://tafsir.app/ibn-aashoor/5/115> ([فَإنِّي أُعَذِّبُهُ عَذابًا لا أُعَذِّبُهُ أحَدًا مِنَ العالَمِينَ]{.ar})]
For example:

(@) [أَحْسَنَ ٱلْإِكْرَامَ وَأَكْرَمَهُ ضَيْفَهُ]{.ar}  
    "He perfected generosity and was generous (with it) [to] his guest."  
    (i.e., he was generous with the generosity)

#### A ;ism_isharah; {.unnumbered}

Similar to the pronoun as a ;naib; ;masdar; ;mmutlaq;, a ;ism_isharah; may be used in the same vein.
For example

(@) [ٱلرَّجُلُ ٱلْمُهَذَّبُ لاَ يُعَامِلُ ٱلنَّاسَ هَـٰذِهِ ٱلْمُعَامَلَةَ]{.ar}
    [[[النحو الواضح لعلي الجارم]{.ar} 2/159](https://shamela.ws/book/10018/571#p1)]{.citex}  
    "The refined man does not deal with the people (with) this dealing."

(@) [يَحْفَظُونَ أَسْرَارَهُمْ هَـٰذَا ٱلْحِفْظَ]{.ar}
    [Wright 2/54A]{.citex}  
    "They keep their secrets (with) this keeping"  
    (i.e. so carefully)

## The ;mmutlaq; with a deleted governing verb

The governing verb of the specifying ;mmutlaq; may be deleted
if there is sufficient context or circumstance to supply its meaning.
For example, in response to the question,

[هَلْ جَلَسَ ٱلزَّائِرُ عِنْدَكَ؟]{.ar}  
"Did the visitor sit with you?"

one may reply:

(@) [جُلُوسًا طَوِيلًا]{.ar}
    [@nahw_wafi@ 2/219]{.citex}  
    "A long sitting"  
    (for [جَلَسَ جُلُوسًا طَوِيلًا]{.ar} "He sat a long sitting.")

Similarly, if one sees a hunter striking his quarry with an arrow succesfully, he might say:

(@) [إِصَابَةً سَرِيعَةً]{.ar}
    [@nahw_wafi@ 2/219]{.citex}  
    "A quick striking"  
    (for [أَصَابَ إِصَابَةً سَرِيعَةً]{.ar} "He struck a quick striking.")

In both the above scenarios, the deleted governing verb is implied.
So the complete sentence includes both the implied governing verb, and the ;mmutlaq;

## The ;mmutlaq; as a ;naib; of the deleted governing verb

In some cases, the deleted governing verb is replaced by the ;mmutlaq;.
The ;mmutlaq; is then a ;naib; of the deleted verb.
This can be done in the following circumstances:

### The ;mmutlaq; as a ;naib; of the verb in a command or supplication

For example, instead of using the verb of command [ٱصْبِرُوا]{.ar} "Be patient," one may say:

(@) [صَبْرًا]{.ar}  
    "Patience"

In terms of governance, the complete sentence is
[ٱصْبِرُوا صَبْرًا]{.ar}.
<!--
In this case, the complete sentence is not
[ٱصْبِرُوا صَبْرًا]{.ar}.
-->
The sentence
[ٱصْبِرُوا صَبْرًا]{.ar}
is valid on its own right as a use of the reinforcing ;mmutlaq;.
But that is not exactly what the utterance 
[صَبْرًا]{.ar}, by itself,
signifies.
Rather the governing verb 
[ٱصْبِرُوا]{.ar}.
is substituted with the ;mmutlaq;,
such that the verb is no longer present in meaning,
and the ;mmutlaq; is now its ;naib;,
fulfilling its role.

<!--
But it gives a different meaning from 
[صَبْرًا]{.ar},
where the ;mmutlaq; is a ;naib; of the governing verb.
-->

Why then would one choose to use a ;mmutlaq; instead of a verb?^[[معاني النحو]{.ar} 2/203]
The ;masdar; signifies only a meaning of the action of the verb.
The verb signifies both the meaning of its ;masdar; and is also linked to a time in which the action originates, continues, or renews. So the verb is more temporary than its ;masdar;.
Therefore, if we use a ;mmutlaq; instead of a verb, then it is not explicitly linked to any time, nor does it explicitly imply a renewal of the action.
So the ;mmutlaq; as a ;naib; for the verb signifies a constancy and inseperableness of the action.
Whereas the verb is a direct application of the action.

Secondly, the verb is necessarily tied to its ;faa3il;.
So, also in circumstances where the objective is the action itself, and not who does it, the ;mmutlaq; may be used as a ;naib; to the verb.

Here are some more examples of a
;mmutlaq; as a ;naib; for the verb:

(@) [قَالَ أَبُو لَهَبٍ تَبًّا لَكَ أَلِهَذَا جَمَعْتَنَا فَنَزَلَتْ تَبَّتْ يَدَا أَبِي لَهَبٍ]{.ar}
    [<https://sunnah.com/bukhari:4973>]{.citex}  
    "[#abU #lahab]{.trn2} said: 'A perishing for you! Is it for this (that) you have gathered us?' So there was revealed: 'May the hands of Abū Lahab be ruined'" [<https://quran.com/111/1>]{.citex}  
    ([تَبًّا]{.ar} is a ;mmutlaq; of the verb [تَبَّ]{.ar} "to perish".)

(@) [شُكْرًا لَكُمْ]{.ar}  
    "A thanking for you"  
    (for [أَشْكُرُكَ]{.ar} "I thank you.")

(@) [سُبْحَانَ ٱللَّـٰهِ]{.ar}
    "The glorification of [#allAh]{.trn2}!"  
    ([سُبْحَانَ]{.ar} is a ;ism_masdar; for the verb [سَبَّحَ]{.ar} "to glorify".)

In the above example,
the sentence with the verb could be, e.g.,
[أُسَبِّحُ سُبْحَانَ ٱللَّـٰهِ]{.ar}
"I glorify the glorification of [#allAh]{.trn2}."
But again, though this may be a valid sentence on its own right,
it is not exactly what
the utterance
[سُبْحَانَ ٱللَّـٰهِ]{.ar},
by itself, signifies.
The ;ism_masdar; [سُبْحَان]{.ar}, as a ;naib; to the verb
does not explicitly specify the verb or its doer.
Rather, the ;ism_masdar; [سُبْحَان]{.ar}
replaces its governing verb.
The purpose is to mention the glorification of [#allAh]{.trn2} without being limited by a time limit for the action of the verb, or a need to mention the ;faa3il; of the verb.^[[معاني النحو]{.ar} 2/206]

Similarly,

(@) [مَعَاذَ ٱللَّـٰهِ]{.ar}  
    "The refuge of [#allAh]{.trn2}"  
    ([مَعَاذ]{.ar} is a ;masdar; of [عَاذَ يَعُوذُ]{.ar} "to seek refuge".)

#### Using the ;ustate; ;masdar; instead of the ;mmutlaq; {.unnumbered}

In situations that call for a course of action,
the ;ustate; ;masdar; may optionally be used
instead of using the (;astate;) ;mmutlaq;.

For example, in a situation that calls for patience, one might say

(@) [صَبْرٌ جَمِيلٌ]{.ar}
    [[معاني النحو]{.ar} 2/206]{.citex}  
    "A beautiful patience"

instead of saying 
[صَبْرًا جَمِيلًا]{.ar}.
Here, the implied meaning is [ٱلْأَمْرُ فِيهِ صَبْرٌ جَمِيلٌ]{.ar} "The thing to be done in the matter is a beautiful patience."^[See also <https://tafsir.app/albahr-almuheet/12/18> ([فَصَبْرٌ جَمِيلٌ]{.ar})]

The ;ustate; ;masdar; (instead of the ;astate; ;mmutlaq;) has the force of more constancy and generality.
Additionally, it can imply that the action called for has, in the speaker's estimation, already begun and become established.
Here are some more examples:

(@) [رَحْمَةُ ٱللَّـٰهِ عَلَيْهِ]{.ar}
    [[معاني النحو]{.ar} 2/206]{.citex}  
    "The mercy of [#allAh]{.trn2} on him"

(@) [وَيْحٌ لِزَيْدٍ]{.ar}
    [Lane's Lexicon, root [ويح]{.ar}]{.citex}  
    "A mercy on Zayd"

In the above example,
the following alternative (using the ;mmutlaq;) is also possible:

(@) (1) [وَيْحًا لِزَيْدٍ]{.ar} [Lane's Lexicon, root [ويح]{.ar}]{.citex}
    (2) [وَيْحَ زَيْدٍ]{.ar} [Lane's Lexicon, root [ويح]{.ar}]{.citex}  
    "A mercy on Zayd"  
    (as though one were to say: [أَلْزَمَهُ ٱللَّـٰهُ وَيْحًا]{.ar} "May [#allAh]{.trn} may mercy to attend him constantly!")

The words 
[وَيْل]{.ar},
[وَيْب]{.ar},
and
[وَيْس]{.ar}
are used in a similar manner to [وَيْح]{.ar} above.
These are all ;masdar;s of disused verbs.
[وَيْح]{.ar}
and 
[وَيْس]{.ar}
typically signify compassion and a mild chiding.
Whereas 
[وَيْل]{.ar}
and
[وَيْب]{.ar}
typically signify a severe chiding, calling for misfortune and destruction.

### The ;mmutlaq; as a ;naib; of a verb that is a ;xabar;

There is a set of circumstances where
the governing verb can deleted, and its place is taken by the ;mmutlaq; as its ;naib;.
This is when the verb is the ;xabar; of a ;mubtada;-;xabar; sentence,
and the verb's ;masdar; wouldn't ordinarily be a ;xabar; in the ;ustate; for the ;mubtada;.^[[معاني النحو]{.ar} 2/209]

Here are some examples that should illustrate what we mean:

Consider the sentence
[أَنْتَ تَأْكُلُ وَتَشْرَبُ]{.ar}
"You are eating and drinking."
The verbs in this sentence may be deleted and each is substituted with its ;astate; ;mmutlaq;s as a ;naib;.
So we can say:

(@) [أَنْتَ أَكْلًا وَشُرْبًا]{.ar}
    [[معاني النحو]{.ar} 2/208]{.citex}  
    "You are eating and drinking."  
    (for [أَنْتَ تَأْكُلُ وَتَشْرَبُ]{.ar})

What allows this is that
the ;masdar;s
[أَكْل]{.ar}
[شُرْب]{.ar}
wouldn't oridinarily work as ;ustate; ;xabar;s for this ;mubtada;.
That is, we can't say $\times$\ [أَنْتَ أَكْلٌ وَشُرْبٌ]{.ar}.
So when we use the ;masdar;s in the ;astate; as ;mmutlaq;s
([أَنْتَ أَكْلًا وَشُرْبًا]{.ar}),
it is understood that they are acting as a ;naib; for their respected deleted verbs.

Here are some more examples:

(@) [ٱلْمَطَرُ سَحًّا سَحًّا]{.ar}
    [@nahw_wafi@ 2/225]{.citex}  
    "The rain (is) pouring (and) pouring."  
    ([سَحّ]{.ar} is the ;masdar; of the verb [سَحَّ يَسُحُّ]{.ar} "to pour down abundantly (of rain)")

<!--
(@) [مَا ٱلنّمِرُ عِنْدَ لِقَاءِ ٱلْفِيلِ إِلَّ غَدْرًا]{.ar}
    [@nahw_wafi@ 2/226]  
    "The leopard is, at meeting the elephant, nothing but cowardly."  
    ([غَدْرًا]{.ar} is the ;masdar; of [غَدَرَ يَغْدِرُ]{.ar} "to act perfidiously")
-->

(@) [مَا ٱلْأَسَدُ مَعَ فَرِيسَتِهِ إِلَّا فَتْكًا]{.ar}
    [@nahw_wafi@ 2/226]{.citex}  
    "The lion is not, with his prey, [anything] but slaying"  
    ([فَتْك]{.ar} is the ;masdar; of [فَتَكَ يَفْتُكُ]{.ar} "to assault and slay")

(@) [أَسَفَاهَةً وَأَنْتَ مُثَقَّفٌ؟]{.ar}
    [@nahw_wafi@ 2/222]{.citex}  
    "[Do you act] foolishly while you are an educated [person]?"  
    ([سَفَاهَة]{.ar} is the ;masdar; of [سَفِهَ يَسْفَهُ]{.ar} "to be foolish")

As you can see from the examples above, these circumstances are usually limited to one of the following kind of sentences:

* a repeated ;masdar;
* multiple ;masdar;s joined with conjunctive particles
* a restricted ;masdar;
* a ;masdar; that is asked about in a question

### The ;mmutlaq; as a ;naib; for a verb in detailing a vague consequential action

This is a very specific circumstance where the ;mmutlaq; may occur as a ;naib; to a verb.
Consider an action that is done as a consequence of some matter.
If this consequential action is expressed only vaguely,
then the following sentence can add detail to this vague action using ;mmutlaq;s.^[[النحو العربي للسمرائي]{.ar} 1/459]
Here is an example:

(@) [إِنْ أَسَاءَ إِلَيْكَ ٱلصَّدِيقُ فَٱسْلُكْ مَسْلَكَ ٱلْعُقَلَاءِ. فَإٍمَّا عِتَابًا كَرِيمًا وَإِمَّا صَفْحًا جَمِيلًا]{.ar}
    [@nahw_wafi@ 2/224]{.citex}  
    If a friend does you wrong then take the path of the intelligent: So either an honorable reproving or a gracious pardoning"

In the example above, the consequential vague action is
[فَٱسْلُكْ مَسْلَكَ ٱلْعُقَلَاءِ]{.ar} "take the path of the intelligent".
The ;masdar;s
[عِتَاب]{.ar} "reproving" and [صَفْح]{.ar} "pardoning"
are then used as ;mmutlaq;s
to detail this vague action,
[فَإٍمَّا عِتَابًا كَرِيمًا وَإِمَّا صَفْحًا جَمِيلًا]{.ar}
"So either an honorable reproving or a gracious pardoning."^[See also <https://quran.com/47/4> ([فَإِمَّا مَنًّا بَعْدُ وَإِمَّا فِدَاءً]{.ar})]

### The ;mmutlaq; as a ;naib; for a verb in emphasizing the meaning of an entire sentence

One usage of the
;mmutlaq; as a ;naib; for a verb is in emphasizing the meaning of an entire sentence.
The ;mmutlaq; in such cases are ;masdar;s (or ;ism_masdar;s) like:

* [حَقًّا]{.ar} "truly" for [أُحِقُّ حَقًّا]{.ar} "I assert a truth"
* [يَقِينًا]{.ar} "certainly" for [أُوقِنُ يَقِينًا]{.ar} "I ascertain a certainty"

For example,

(@) [تَبَدَّى لَهُ جِبْرِيلُ فَقَالَ يَا مُحَمَّدُ إِنَّكَ رَسُولُ اللَّهِ حَقًّا]{.ar}
    [<https://sunnah.com/bukhari:6982>]{.citex}  
    "Gabriel would appear before him and say, 'O [#muHammad]{.trn2}! Indeed you are [#allAh]{.trn2}'s Messenger [ﷺ]{.aralt} truly'"

(@) [وَمَا قَتَلُوهُ يَقِينًا]{.ar}
    [<https://quran.com/4/157>]{.citex}  
    "And they did not kill him, for certain."

### The dualized ;mmutlaq; as a ;naib; of the verb

There are some ;mmutlaq;s that are dualized and annexed to a pronoun in set phrases.
The dual indicates a recurringness of the action.
These include:

* [لَبَّيْكَ]{.ar} -- [لَبّ]{.ar} is the ;ism_masdar; of the verb [أَلَبّ يُلِبُّ]{.ar} "to remain." The ;astate; dualized ;masdar; annexed to the addressee pronoun, [لَبَّيْكَ]{.ar}, signifies "I remain for you (i.e. at your service] time after time." A verb [لَبَّىٰ يُلَبِّي تَلْبِيَةً]{.ar} "to utter [لَبَّيْكَ]{.ar}" is derived from this phrase.
* [سَعْدَيْكَ]{.ar} -- [سَعْد]{.ar} is the ;ism_masdar; of the verb [أَسْعَدَ يُسْعِدُ]{.ar} "to help" The ;astate; dualized ;masdar; annexed to the addressee pronoun, [سَعْدَيْكَ]{.ar}, signifies "I am at your aid time after time." 
* [حَنَانَيْكَ]{.ar} -- from [حَنَان]{.ar} "mercy". [حَنَانَيْكَ]{.ar} signifies "Let your mercy be continuous to me."
* [دَوَالَيْكَ]{.ar} -- from [دَوَال]{.ar} which is equivalent to [مُدَاوَلَة]{.ar} and [تَدَاوُل]{.ar} "taking by turns".
[دَوَالَيْكَ]{.ar} signifies "Make (you) the action to be done by turns."
* [حَذَارَيْكَ]{.ar} -- from [حَذَار]{.ar} "Beware". [حَذَارَيْكَ]{.ar} signifies "Twice beware!"

## Differentiating the ;mmutlaq; from the other ;astate; ;maful;s

The ;mmutlaq; is a kind of ;maful;.
Other kinds of ;maful;s include the ;mafulb;,
the ;dharf_zaman; and the ;dharf_makan;,
and
the ;mafull;.
Generally, all adverbs can be considered to be in the category of ;maful;s.
All ;maful;s are governed by verbs and occur in the ;astate;.

Sometimes it is not easy to disambiguate the exact function of an ;astate; noun occurring as a ;maful;.
We have already seen some instances of this. For example, we mentioned that in example\ (@mmutlaq_mmutlaq_dharf)
[ضَرَبْتُهُ كَثِيرًا]{.ar},
that the ;astate; ;maful; 
[كَثِيرًا]{.ar}
could be analyzed as either a ;mmutlaq; or a ;dharf_zaman;, depending on context.

Similarly,
in example\ (@mmutlaq_shirk_mafulb_mmutlaq)
[وَلَا تُشْرِكُوا بِهِ شَيْـًٔا]{.ar}
[<https://quran.com/4/36>]{.citex}
"and associate nothing with Him",
[شَيْـًٔا]{.ar}
has been analyzed to support both a ;mmutlaq; meaning and a ;mafulb; meaning.

For some verbs, their ;masdar;s are re-used as common nouns. For example:

* [أَكَلَ يَأْكُلُ أَكْلًا]{.ar}  --  [أَكْل]{.ar} is re-used to mean "a food"
* [صَادَ يَصِيدُ صَيْدًا]{.ar}  --  [صَيْد]{.ar} is re-used to mean "a prey"
* [قَالَ يَقُولُ قَوْلًا]{.ar}  --  [قَوْل]{.ar} is re-used to mean "a saying" or "a speech"
* [سَأَلَ يَسْأَلُ سُؤَالًا]{.ar} --  [سُؤَال]{.ar} is re-used to mean "a question"

When these nouns are in the ;astate; governed by their verb, then how do we tell whether they are a ;mmutlaq; or a ;mafulb;?
For example:

(@) [أَكَلَ زَيْدٌ أَكْلًا]{.ar}  
    "Zayd ate an eating."  
    or  
    "Zayd ate a food."

By itself, [أَكْلًا]{.ar} supports both functions of the ;mafulb; and the ;mmutlaq;.
And we have to look at context to see which of the two meanings the speaker intended.

Sometimes, if the ;astate; ;maful; is qualified, then that can help us distinguish between the two functions.
For example,

(@) [أَكَلَ زَيْدٌ أَكْلًا سَرِيعًا]{.ar}  
    "Zayd ate a fast eating"  
    (i.e. "Zayd ate quickly.")

<!--In the above example, the ;na3t; [سَرِيع]{.ar} "fast" can only be meaningfully applied to the ;masdar; "eating" and not to the common noun "food."-->
In the above example, the ;na3t; [سَرِيع]{.ar} "fast" is applied to the ;manut; [أَكْلًا]{.ar}.
Now, unless Zayd was eating "fast food" (unlikely in classical times),
the ;na3t; 
applies to the manner in which Zayd was eating.
Hence [أَكْلًا]{.ar} is a ;mmutlaq; and not a ;mafulb;.

Sometimes, the qualifier may be applicable to both the ;mmutlaq; and the ;maful;.
Yet each meaning will be distinct.
For example,

(@) [صَادَ زَيْدٌ صَيْدَ ٱلْأَسَدِ]{.ar}  
    "Zayd hunted (in the manner of) the hunting of a lion."  
    or  
    "Zayd hunted the lion's prey."

In the above example, the ;maful; [صَيْد]{.ar} is qualified in an annexation with the ;mudafil; [ٱلْأَسَد]{.ar} "the lion".
But the qualifier is applicable to both
meanings of
[صَيْد]{.ar}:
the ;mmutlaq; meaning: "hunting",
and
the ;mafulb; meaning: "prey".
When applied to the ;mmutlaq; meaning then the sentence means that Zayd hunted in a ferocious and daring manner, like a lion does.
And when applied to the ;mafulb; meaning then the sentence means that Zayd hunted a prey which was (previously) the prey of a lion.
However, both of these meanings are distinct from each other.
In this sort of case, context should help in figuring out the intended meaning.

In the case of ;masdar;s like
[أَكْل]{.ar}
and
[صَيْد]{.ar},
when they are re-used as common nouns,
then their existence is not tied to the action of the verb.
For example,
[أَكْل]{.ar}, meaning "food", exists prior to the action of eating.
And 
[صَيْد]{.ar}, meaning "prey" exists prior to the action of hunting.

But in the case of ;masdar;s like
[قَوْل]{.ar}
and
[سُؤَال]{.ar},
even when they are a ;mafulb;,
they only come into existence with the action of their verb.
So there is no [قَوْل]{.ar},
either as a ;mmutlaq; or as a ;mafulb;, before the action of "saying"
And there is no [سُؤَال]{.ar},
either as a ;mmutlaq; or as a ;mafulb;, before the action of "asking".

In such cases, even when a qualifier is applied, the line between the ;mmutlaq; and the ;mafulb; can remain blurry.
And that is not really a big deal because both meanings will be similar.
For example,

(@) [سَأَلَ زَيْدٌ عَمْرًا سُؤَالًا صَعْبًا]{.ar}  
    "He asked a difficult questioning."  
    (i.e. the questioning was difficult upon [#eamr]{.trn2})  
    or  
    "He asked a difficult question."

This sort of ambiguity can sometimes be found in the other adverb ;maful;s as well.

## Candidates for governing the ;mmutlaq;

The verb is the fundamental governor of the ;faa3il; and the ;maful;.
But we have seen (in sections\ (ref)), that nouns that have a verbal quality to them,
like the ;masdar;,
the ;ism_fail;, etc., can also govern a ;faa3il; and a ;maful;.

So a ;mmutlaq; may occur, governed by either a verb (as we have seen),
or a ;ism_fail;,
or a ;ism_maful;,
or a ;sifah_mush;,
or even another ;masdar;.

Here are some examples:

(@) [فَرَحْتُ بِٱجْتِهَادِكَ ٱجْتِهَادًا حَسَنًا]{.ar}  
    [[النحو العربي للسامرائي]{.ar} 1/449]{.citex}  
    "I rejoiced at your striving a good striving"  
    (the ;mmutlaq; [ٱجْتِهَادًا]{.ar} is governed by the preceding ;masdar; [ٱجْتِهَاد]{.ar})

(@) [أَنَا مُكْرِمٌ خَالِدًا إِكْرَامًا عَظِيمًا]{.ar}  
    [[النحو العربي للسامرائي]{.ar} 1/449]{.citex}  
    "I will honor [#xAlid]{.trn2} a great honoring."  
    (the ;mmutlaq; [إِكْرَامًا]{.ar} is governed by the ;ism_fail; [مُكْرِم]{.ar})

