# The ;astate; ;mudarie; verb

## Introduction

In 
chapter\ \@ref(;ustate;-;mudarie;-verbs)
we mentioned that ;mudarie; verbs have three states (like nouns). 
These states are called:

i. The ;ustate;
i. The ;astate;
i. The ;0state;

We introduced the ;ustate; ;mudarie; verb in
chapter\ \@ref(;ustate;-;mudarie;-verbs).
In this chapter we will study the 
;astate;
;mudarie; verb.

The ;ustate; ;mudarie; verb makes a plain statement.
The ;astate; ;mudarie; verb implies a wish or purpose.
The ;astate; ;mudarie; verb is used after the following articles:

+ [أَنْ]{.ar} [Ean]{.trn}
+ [لَنْ]{.ar} [lan]{.trn}
+ [لِ]{.ar} [li]{.trn}
+ [كَيْ]{.ar} [kay]{.trn}
+ [حَتَّىٰ]{.ar} [HattA]{.trn}
+ [إِذَنْ]{.ar} [Eipan]{.trn}

We will go over these cases in this chapter.

## Forming the ;astate; ;mudarie; verb

Here is the ;ustate; ;mudarie; verb for the singular masculine absentee participant ;fail; "he":

[يَفْعَلُ]{.ar}  
[yafealu]{.trn}  
"he does"

Note that, because it is in the ;ustate;, the its final letter ends with a ;umark; [◌ُ]{.ar}.
In order to form the 
;astate;
;mudarie; verb,
we change the ;umark; into a
;amark; [◌َ]{.ar}, thus:

[يَفْعَلَ]{.ar}  
[yafeala]{.trn}  

This is done for all participants whose ;fail; pronoun is invisible and ;ustate; verb ends with a ;umark; [◌ُ]{.ar}.

For participants whose ;fail; pronoun is followed by an extra [ن]{.ar} in the ;ustate; verb, this final [ن]{.ar} is dropped in order to form the 
;astate;
;mudarie; verb.
So, for example, the ;ustate;
;mudarie; verb:

[يَفْعَلَانِ]{.ar}  
[yafealAni]{.trn}  
"they~2,m~ do"

becomes, for the 
;astate;:

[يَفْعَلَا]{.ar}  
[yafealA]{.trn}  

Here is the complete table of the 
;astate;
;mudarie; verb
for all ;fail; participants.

|Participant|;#mudarie; verb ;fail; pronoun|;ustate; ;mudarie; verb | ;astate; ;mudarie; verb|
|:---|:--|:---|:---|
| he        |_invisible_         |[يَفْعَلُ]{.ar}    |[يَفْعَلَ]{.ar}    |
| she       |_invisible_         |[تَفْعَلُ]{.ar}    |[تَفْعَلَ]{.ar}    |
| you~1m~   |_invisible_         |[تَفْعَلُ]{.ar}    |[تَفْعَلَ]{.ar}    |
| you~1f~   |[ي]{.ar}            |[تَفْعَلِينَ]{.ar}  |[تَفْعَلِي]{.ar}   |
| I         |_invisible_         |[أَفْعَلُ]{.ar}    |[أَفْعَلَ]{.ar}    |
| they~2m~  |[ا]{.ar}            |[يَفْعَلَانِ]{.ar}  |[يَفْعَلَا]{.ar}   |
| they~2f~  |[ا]{.ar}            |[تَفْعَلَانِ]{.ar}  |[تَفْعَلَا]{.ar}   |
| you~2~    |[ا]{.ar}            |[تَفْعَلَانِ]{.ar}  |[تَفْعَلَا]{.ar}   |
| they~3m~  |[و]{.ar}            |[يَفْعَلُونَ]{.ar}  |[يَفْعَلُوا]{.ar}  |
| they~3f~  |[نَ]{.ar}            |[يَفْعَلْنَ]{.ar}   |[يَفْعَلْنَ]{.ar} (same)   |
| you~3m~   |[و]{.ar}            |[تَفْعَلُونَ]{.ar}  |[تَفْعَلُوا]{.ar}  |
| you~3f~   |[نَ]{.ar}            |[تَفْعَلْنَ]{.ar}   |[تَفْعَلْنَ]{.ar} (same)  |
| we        |_invisible_         |[نَفْعَلُ]{.ar}    |[نَفْعَلَ]{.ar}    |

Take note the following:

+ The ;ustate; and ;astate; verbs are the same for the feminine plural absentee and addressee participants: 
  + [يَفْعَلْنَ]{.ar} (they~3f~)
  + [تَفْعَلْنَ]{.ar} (you~3f~)
+ The ;astate; verbs for the masculine plural absentee and addressee participants have a final silent [alif]{.trn2}: 
  + [يَفْعَلُوا]{.ar} (they~3m~) 
  + [تَفْعَلُوا]{.ar} (you~3m~)

<!--
### Doubled and weak roots

The following table lists the ;astate; ;mudarie; verb for some roots with a weak final letter. These are the only roots that have any complications in forming the ;astate;. The rest of the doubled and weak root verbs are straightforward. For a complete listing, including the higher forms, see Appendix\ \@ref(chapter-verb-tables).

Root: [سعي]{.ar}

|Participant|;ustate; verb | ;astate; verb
|:---|:--|:---|:---|
| he        |_invisible_         |[يَفْعَلُ]{.ar}    |[يَفْعَلَ]{.ar}    |
| she       |_invisible_         |[تَفْعَلُ]{.ar}    |[تَفْعَلَ]{.ar}    |
| you~1m~   |_invisible_         |[تَفْعَلُ]{.ar}    |[تَفْعَلَ]{.ar}    |
| you~1f~   |[ي]{.ar}            |[تَفْعَلِينَ]{.ar}  |[تَفْعَلِي]{.ar}   |
| I         |_invisible_         |[أَفْعَلُ]{.ar}    |[أَفْعَلَ]{.ar}    |
| they~2m~  |[ا]{.ar}            |[يَفْعَلَانِ]{.ar}  |[يَفْعَلَا]{.ar}   |
| they~2f~  |[ا]{.ar}            |[تَفْعَلَانِ]{.ar}  |[تَفْعَلَا]{.ar}   |
| you~2~    |[ا]{.ar}            |[تَفْعَلَانِ]{.ar}  |[تَفْعَلَا]{.ar}   |
| they~3m~  |[و]{.ar}            |[يَفْعَلُونَ]{.ar}  |[يَفْعَلُوا]{.ar}  |
| they~3f~  |[نَ]{.ar}            |[يَفْعَلْنَ]{.ar}   |[يَفْعَلْنَ]{.ar} (same)   |
| you~3m~   |[و]{.ar}            |[تَفْعَلُونَ]{.ar}  |[تَفْعَلُوا]{.ar}  |
| you~3f~   |[نَ]{.ar}            |[تَفْعَلْنَ]{.ar}   |[تَفْعَلْنَ]{.ar} (same)  |
| we        |_invisible_         |[نَفْعَلُ]{.ar}    |[نَفْعَلَ]{.ar}    |
-->

## After [أَنْ]{.ar} [Ean]{.trn}

[أَنْ]{.ar} [Ean]{.trn} "that" is the main article which causes the following
;mudarie; verb to be in the ;astate;.
The other articles that we listed in the introduction are all either derived from 
[أَنْ]{.ar} 
or include its meaning implicitly without expressing it.

### Basic usage of [أَنْ]{.ar} [Ean]{.trn} with the ;astate; ;mudarie; verb

[أَنْ]{.ar} often follows verbs that have a meaning of wishing or hoping. For example,

[أَمَلَ ٱلطَّالِبُ أَنْ يَنْجَحَ.]{.ar}  
[Eamala -TTAlibu Ean yanjaH.]{.trn}  
"The student hoped that he succeed."

[لَا]{.ar} can be used to negate the following ;astate; ;mudarie; verb.
[لَا]{.ar} combines with [أَنْ]{.ar} and assimilates with it to form [أَلَّا]{.ar} [EallA]{.trn} "that not".
For example,

[أَمَرَ ٱلْأَبُ ٱلِٱبْنَ أَلَّا يَكْسَلَ.]{.ar}  
[Eamara -lEabu li-bna EallA yaksal.]{.trn}  
"The father ordered the son that he not be lazy."

Other than this [لَا]{.ar},
[أَنْ]{.ar} must directly precede the following ;astate; ;mudarie; verb and must not be separated from it.

### Grammatical equivalence of [أَنْ]{.ar} clause with a ;masdar;

In grammatical theory,
[أَنْ]{.ar} 
and the following verb form a clause that is equivalent in meaning to the ;masdar; of the verb. So in the example,
[أَمَلَ ٱلطَّالِبُ أَنْ يَنْجَحَ.]{.ar}, the 
[أَنْ]{.ar} clause is
[أَنْ يَنْجَحَ]{.ar}.
It is equivalent to the ;masdar; [ٱلنَّجَاح]{.ar}.
So the sentence is grammatically equivalent to

[أَمَلَ ٱلطَّالِبُ ٱلنَّجَاحَ.]{.ar}  
[Eamala -TTAlibu -nnajAH.]{.trn}  
"The student hoped [for] success."

This grammatical equivalence of the 
[أَنْ]{.ar} clause
with a noun aloows the 
[أَنْ]{.ar} clause to take the place of a noun in various positions in a sentence.
So, in the above example, the 
[أَنْ]{.ar} clause
is in place of the ;mafulb; of the verb [أَمَلَ]{.ar}:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.45ex}]
\path [decoration={text effects along path, 
  text=.\txarb{أَنْ يَنْجَحَ} \txarb{أَمَلَ ٱلطَّالِبُ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, below] {\scriptsize ;mafulb;};

\path (0,0) node [midway, below=6ex, right=-2ex, align=left] {``The student hoped that he suceed.''};

\end{tikzpicture}
```

We show other examples below where the
[أَنْ]{.ar} clause
occurs in place of other noun positions.

As the ;mubtada;:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.45ex}]
\path [decoration={text effects along path, 
  text=.\txarb{هُوَ ٱلْمَقْصِدُ} \txarb{أَنْ تَنْجَحَ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, below] {\scriptsize subject};

\path (0,0) node [midway, below=6ex, right=-2ex, align=left] {``That you succeed is the purpose.''};

\end{tikzpicture}
```

which is grammatically equivalent to: [نَجَاحَكَ هُوَ ٱلْمَقْصِدُ.]{.ar}.


As the ;xabar;:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.45ex}]
\path [decoration={text effects along path, 
  text=.\txarb{أَنْ تَنْجَحَ} \txarb{ٱَلْمَقْصِدُ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, below] {\scriptsize comment};

\path (0,0) node [midway, below=6ex, right=-2ex, align=left] {``The purpose is that you succeed.''};

\end{tikzpicture}
```

which is grammatically equivalent to: [ٱَلْمَقْصِدُ نَجَاحَكَ.]{.ar}.

As a ;fail; noun:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.45ex}]
\path [decoration={text effects along path, 
  text=.\txarb{أَنْ يَذْهَبَ} \txarb{يَحْزُنُنِي},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-1.south west) -- (word-1.south east)
      node [midway, below] {\scriptsize doer};

\path (0,0) node [midway, below=6ex, right=-2ex, align=left] {``That he [should] go saddens me.''};

\end{tikzpicture}
```

which is grammatically equivalent to: [يَحْزُنُنِي ذَهَابُهُ.]{.ar}.

In the ;istate; as the ;mudafil; in an ;idafa;:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.45ex}]
\path [decoration={text effects along path, 
  text=.\txarb{عَلَيْهَا} \txarb{أَنْ يَغْضَبَ} \txarb{سَكَتَتْ مِنْ خَشْيَةِ},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, below] {\scriptsize ;istate; ;mudafil;};

\path (0,0) node [midway, below=6ex, right=-2ex, align=left] {``She stayed quiet from fear of that he be angry at her.''};

\end{tikzpicture}
```

which is grammatically equivalent to: [سَكَتَتْ مِنْ خَشْيَةِ غَضَبِهِ عَلَيْهَا.]{.ar}.

In the ;istate; after a preposition:

```{.tikzarabic}
\usetikzlibrary{decorations.text, decorations.pathreplacing}
\begin{tikzpicture}[nodes={text depth=0.25ex,text height=1.45ex}]
\path [decoration={text effects along path, 
  text=.\txarb{أَنْ يَأْكُلَ ٱلطَّعَامَ} \txarb{رَغِبَ ٱلْغُلَامُ فِي},
  text effects/.cd, 
    path from text, text along path,
    group letters, word count=\w,
    every word/.style={name=word-\w, execute at begin node=\strut}},
  decorate] (0,0);

\draw [decoration={brace, mirror}, decorate] 
   (word-2.south west) -- (word-2.south east)
      node [midway, below] {\scriptsize ;istate; after preposition};

\path (0,0) node [midway, below=6ex, right=-2ex, align=left] {``The boy desired that he eat the food.''};

\end{tikzpicture}
```

which is grammatically equivalent to: [رَغِبَ ٱلْغُلَامُ فِي أَكْلِ ٱلطَّعَامِ.]{.ar}.

### Option to drop the preposition before [أَنْ]{.ar}

In the above example the verb [رَغِبَ يَرْغَبُ]{.ar} takes an ;indir_mafulb; after the preposition [فِي]{.ar}.
In such cases, where the 
[أَنْ]{.ar} clause
occurs after a preposition, it is common to drop the preposition as long as there is not resulting confusion in meaning.
So, we can also say (without the preposition [فِي]{.ar}) for the same meaning:

[رَغِبَ ٱلْغُلَامُ أَنْ يَأْكُلَ ٱلطَّعَامَ.]{.ar}  
"The boy desired that he eat the food."

### [أَنْ]{.ar} meaning "lest"

Ocassionally, [أَنْ]{.ar} is used with the meaning "lest". For example:

[قَتَلْتُ ٱلثُّعْبَانَ أَنْ يَقْتُلَنِي.]{.ar}  
"I killed the serpent lest it kill me."

### [أَنْ]{.ar} with the ;madi; verb

[أَنْ]{.ar} may also occur before a ;madi; verb. Example:

[بَلَغَنِي أَنْ رَجَعْتَ.]{.ar}  
"That you have returned has reached me."

### Other types of [أَنْ]{.ar}

There are other types of [أَنْ]{.ar} in the Arabic language. They all have the basic meaning "that". But they are used in different grammatical ways.

The [أَنْ]{.ar} we have learned here is called the _;masdar;i [أَنْ]{.ar}_ because of the equivalence of its clause with a ;masdar;.

There is also another type of [أَنْ]{.ar} called the _lightened [أَنْ]{.ar}_ that we will learn in section\ \@ref(lightened-an).

There is also the _explanatory [أَنْ]{.ar}_ and the _extra [أَنْ]{.ar}_ that we will cover in chapter\ \@ref(types-of-an).

## After [لِ]{.ar} [li]{.trn}

### The [لِ]{.ar} of purpose

The article [أَنْ]{.ar} may be attached to the preposition [لِ]{.ar} [li]{.trn} thus: [لِأَنْ]{.ar} [liEan]{.trn} to give the purpose of the following verb. This [لِ]{.ar} may be translated as "so that". For example:

[أَكَلَ لِأَنْ يَشْبَعَ.]{.ar}  
"He ate so that he be sated."

When [لِ]{.ar} is thus used, [أَنْ]{.ar} is optionally allowed to be dropped while its meaning is retained.
[لِ]{.ar} is then attached to the verb.
So we can say, for the same meaning:

[أَكَلَ لِيَشْبَعَ.]{.ar}  
"He ate so that he be sated."

But when using [لَا]{.ar} to negate the verb, then [أَنْ]{.ar} must be expressed, and the combination of [لِ]{.ar}, [أَنْ]{.ar}, and [لَا]{.ar} is written as [لِئَلَّا]{.ar} [liEallA]{.trn}. For example,

[شَرِبَ ٱلْمَاءَ لِئَلَّا يَعْطَشَ.]{.ar}  
"He drank the water so that he not be thirsty."

<!--
By the way, this [لِ]{.ar}, which is used with ;astate; ;mudarie; verbs, is different from 
the [لِ]{.ar} we learned in section\ \@ref(indirect-commands), which is used with the ;0state; ;mudarie; verbs for indirect commands.
-->

By the way, the grammatical equivalence of [أَنْ]{.ar} and a following ;astate; ;mudarie; verb with a ;masdar; applies also to when [لِ]{.ar} is used before (either an expressed or an implied) [أَنْ]{.ar}. So, for example, if we have a sentence:

[قَرَأَ ٱلْكِتَابَ لِيَعْلَمَ مَفْهُومَهُ.]{.ar}  
or  
[قَرَأَ ٱلْكِتَابَ لِأَنْ يَعْلَمَ مَفْهُومَهُ.]{.ar}  
"He read the book so that he know its meaning."

Then, grammatically, [أَنْ]{.ar} and what follows it may be expressed with the ;masdar; [عِلْم]{.ar} thus:

[قَرَأَ ٱلْكِتَابَ لِعِلْمِ مَفْهُومِهِ.]{.ar}  
"He read the book for the knowledge of its meaning."

### The [لِ]{.ar} of denial

There is a specific [لِ]{.ar}, called the [لِ]{.ar} of denial,  which is used with ;astate; ;mudarie; verbs and the verb [كَانَ]{.ar} that we will discuss in section (TODO in [كَانَ]{.ar} chapter).

## After [كَيْ]{.ar} [kay]{.trn}

[كَيْ]{.ar} [kay]{.trn}
is a preposition similar to [لِ]{.ar} in meaning. It may be translated as "in order that", or also as "so that".
It is also used before the ;astate; ;mudarie; verb.
The difference from [لِ]{.ar} is that, when [لِ]{.ar} is used with the ;astate; ;mudarie; verb, expressing or dropping the [أَنْ]{.ar} was optional.
But with [كَيْ]{.ar}, dropping the [أَنْ]{.ar} is mandatory, while its meaning is retained. For example:

[أَكَلَ كَيْ يَشْبَعَ.]{.ar}  
"He ate in order that he be sated."

[لَا]{.ar} is used, as usual, to negate the verb and is attached to [كَيْ]{.ar} thus: [كَيْلَا]{.ar} [kaylA]{.trn}. Example:

[شَرِبَ ٱلْمَاءَ كَيْلَا يَعْطَشَ.]{.ar}  
"He drank the water in order that he not be thirsty."

The preposition [لِ]{.ar} may be combined with [كَيْ]{.ar} thus: [لِكَيْ]{.ar} [likay]{.trn}, for more or less the same meaning. For example:

[أَكَلَ لِكَيْ يَشْبَعَ.]{.ar}  
"He ate in order that he be sated."

With [لَا]{.ar} the whole combination is written as [لِكَيْلَا]{.ar} [likaylA]{.trn}. [أَنْ]{.ar} must again be not be expressed.

Example:

[شَرِبَ ٱلْمَاءَ لِكَيْلَا يَعْطَشَ.]{.ar}  
"He drank the water in order that he not be thirsty."

By the way, 
[كَيْ]{.ar} and a following ;astate; ;mudarie; verb are not _directly_ replaced by
a ;masdar;.
So, for example, if we have a sentence:

[قَرَأَ ٱلْكِتَابَ كَيْ يَعْلَمَ مَفْهُومَهُ.]{.ar}  
"He read the book in order that he know its meaning."

Then [لِ]{.ar} is to be used in place of [كَيْ]{.ar} if we wish to replace it and what follows with the ;masdar; [عِلْم]{.ar} thus:

[قَرَأَ ٱلْكِتَابَ لِعِلْمِ مَفْهُومِهِ.]{.ar}  
"He read the book for the knowledge of its meaning."

## After [حَتَّىٰ]{.ar} [HattA]{.trn}

[حَتَّىٰ]{.ar} [HattA]{.trn}
is a particle that can be used in multiple ways.
Its basic meaning is "until" or "to the point of" or "even" where it indicates an extreme limit.

Before we discuss its use with a verb following it, we will take a short digression to discuss its use with a following noun.

### [حَتَّىٰ]{.ar} [HattA]{.trn} with a following noun

Consider the following sentence:

[أَكَلْتُ ٱلسَّمَكَةَ حَتَّىٰ رَأْسِهَا.]{.ar}  
"I ate the fish until its head."

[حَتَّىٰ]{.ar} "until",
here, is used as a preposition.
Therefore,
[رَأْس]{.ar}
is in the ;istate;, as the noun following a preposition.
The meaning of the sentence is that the fish was eaten all the way to its head. 
(Whether the head itself was eaten or not is ambiguous. The sentence itself admits both meanings.)

Consider now a variant of this sentence:

[أَكَلْتُ ٱلسَّمَكَةَ حَتَّىٰ رَأْسَهَا.]{.ar}  
"I ate the fish, even its head."

[رَأْس]{.ar},
here, is in the ;astate; because it is a ;mafulb; of the verb [أَكَلَ]{.ar} "ate".
The particle
[حَتَّىٰ]{.ar} "even",
here, is only a connector between the ;mafulb;s in much the same way as [وَ]{.ar} "and". 
([أَكَلْتُ ٱلسَّمَكَةَ وَرَأْسَهَا.]{.ar}
"I ate the fish and its head.")

Consider now yet another variant of this sentence:

[أَكَلْتُ ٱلسَّمَكَةَ. حَتَّىٰ رَأْسُهَا [أَكَلْتُهَا].]{.ar}  
"I ate the fish. Even its head [I ate]."

Now
[رَأْس]{.ar}
is in the ;ustate; because it is actually the ;mubtada; of a new sentence, whose ;xabar; is (an either expressed or implied) [أَكَلْتُهَا]{.ar} "I ate it".
[حَتَّىٰ]{.ar},
here, serves as an introductory particle to the second ;mubtada; and does not affect the state of the following noun.

### [حَتَّىٰ]{.ar} [HattA]{.trn} with a following verb

<!-- See
Wright vol. ii. Section 15, p. 29C,D

Arik Sadan, "The Mood of The Verb following Ḥattā, according To Medieval arab grammarians"
in
The foundations of Arabic linguistics : Sibawayhi and early Arabic grammatical theory / edited by Amal
Elesha Marogy
-->

Just as
[حَتَّىٰ]{.ar}
is used for different purposes with a following noun,
so too is it used with different purposes with a verb following it.

#### [حَتَّىٰ]{.ar} with a following ;astate; ;mudarie; verb

When
[حَتَّىٰ]{.ar}
is used with an expectation or purpose of a future action of the verb following it, then 
the verb following it is an ;astate; ;mudarie; verb. 
<!--
When the verb following
[حَتَّىٰ]{.ar}
signifies the expectation or purpose of a future action, then the verb used is an ;astate; ;mudarie; verb. 
-->
This is done in the following two scenarios:

1. When [حَتَّىٰ]{.ar} is used to indicate an extreme point at which the action of the following verb would occur, or is meant to occur. Here, 
   [حَتَّىٰ]{.ar}
   may be translated as "to the point of" and the verb following it is translated using "-ing".
   For example,

   [قَرَأْتُ ٱلْقُرْآنَ حَتَّىٰ أَخْتِمَهُ.]{.ar}  
   "I read the ;quran; to the point of finishing it."

   [يَغْضَبُ حَتَّىٰ يَهْرَبُوا مِنْهُ.]{.ar}  
   "He becomes angry to the point of their fleeing from him."

   [غَضِبَ حَتَّىٰ لَا يَمْلِكَ نَفْسَهُ.]{.ar}  
   "He became angry to the point of not controlling himself."

   It is noteworthy that the use of [حَتَّىٰ]{.ar}, here, implies only that the following action is meant to occur, or is at the point of being expected to occur. It doesn't actually state that the action will actually occur, for something may prevent it from occurring in reality.^[Sadan, Arik, _The subjunctive mood in Arabic grammatical thought_, 2012, p.\ 201]

   Note, also, that [لَا]{.ar} is not attached to [حَتَّىٰ]{.ar} in [حَتَّىٰ لَا]{.ar}.

   Also, similar to the case of [كَيْ]{.ar}, there is an assumed (but mandatorily unexpressed) [أَنْ]{.ar} which is the real cause of the following ;mudarie; verb being in the ;astate;.
   In fact, 
   [حَتَّىٰ]{.ar},
   here, can be considered synonymous to [إِلَىٰ أَنْ]{.ar} "to [the point] that". So the above examples can be considered similar in meaning to:

   [قَرَأْتُ ٱلْقُرْآنَ إِلَىٰ أَنْ أَخْتِمَهُ.]{.ar}  

   [يَغْضَبُ إِلَىٰ أَنْ يَهْرَبُوا مِنْهُ.]{.ar}  

   [غَضِبَ إِلَىٰ أَلَّا يَمْلِكَ نَفْسَهُ.]{.ar}  

2. When [حَتَّىٰ]{.ar} is used with the meaning "to such a purpose that". This is a similar meaning to [كَيْ]{.ar} "in order that".
   For example,

   [أَذْهَبُ إِلَيْهِ حَتَّىٰ يَأْمُرَنِي بِشَيْءٍ.]{.ar}  
   "I go to him to such a purpose that he order me [to do] something."

   [وَعَظَ ٱلْأَبُ ٱبْنَهُ حَتَّىٰ يَصْلُحَ.]{.ar}  
   "The father admonished his son to such a purpose that he be righteous."

   Again, there is an assumed (but mandatorily unexpressed) [أَنْ]{.ar} which is the real cause of the following ;mudarie; verb being in the ;astate;.

Sometimes, the sentence itself may admit both of the above meanings. For example:

[يَأْكُلُ حَتَّىٰ يَشْبَعَ.]{.ar}  
"He eats to the point of being full."  
and/or  
"He eats to the purpose that he be full."

Context would be needed to determine which meaning or whether both meanings are intended.

#### [حَتَّىٰ]{.ar} with no effect on the following verb

If
[حَتَّىٰ]{.ar}
is not used with any expectation or purpose of a future action of the verb following it, then it has no effect on this verb.
(It goes without saying that an implicit [أَنْ]{.ar} is not assumed with [حَتَّىٰ]{.ar} in this case.)

The verb following 
[حَتَّىٰ]{.ar}
in this case
may even be a ;madi; verb. For example:

[أَكَلْتُ ٱلطَّعَامَ حَتَّىٰ شَبِعْتُ.]{.ar}  
"I ate the food until I became full."

When used with a following ;mudarie; verb, the verb is put in the ;ustate; and the meaning is that the action of the verb _before_
[حَتَّىٰ]{.ar}
was done to such an extent that it caused
the action of the verb _following_
[حَتَّىٰ]{.ar}
to definitely occur.
The action before
[حَتَّىٰ]{.ar}
must necessarily be a past action, and the action following
[حَتَّىٰ]{.ar}
must necessarily be a present (not a future) action.
For example,

[أَكَلْتُ ٱلطَّعَامَ حَتَّىٰ أَشْبَعُ.]{.ar}  
"I ate the food to such an extent that I am (being) full."

[غَضِبَ حَتَّىٰ يَهْرَبُونَ مِنْهُ.]{.ar}  
"He became so angry that they are fleeing from him."

[غَضِبَ حَتَّىٰ لَا يَمْلِكُ نَفْسَهُ.]{.ar}  
"He became so angry that he is not controlling himself."

Compare these examples with the corresponding ones in the previous sub-section that have an ;astate; ;mudarie; verb.


<!--The preposition 
[حَتَّىٰ]{.ar} [HattA]{.trn}
is unusual in that the ;mudarie; verb following it may either be in the ;astate; or the ;ustate;, with slightly different meanings.
When the ;mudarie; verb following it is in the ;ustate; then
[حَتَّىٰ]{.ar} gives the meaning "until".
And when the ;mudarie; verb following it is in the ;astate; then
[حَتَّىٰ]{.ar} gives the meaning "for the result that".
A mandatorily unexpressed [أَنْ]{.ar} is assumed with
[حَتَّىٰ]{.ar} 
when the verb following it is in the ;astate;.
Examples:

[يَأْكُلُ حَتَّىٰ يَشْبَعَ.]{.ar} (;astate;, unexpressed [أَنْ]{.ar} assumed)  
"He eats for the result that he be sated."

[يَأْكُلُ حَتَّىٰ يَشْبَعُ.]{.ar} (;ustate;, no [أَنْ]{.ar})  
"He eats until he is sated."

[حَتَّىٰ]{.ar} 
is also used with ;madi; verbs. Example:

[أَكَلَ حَتَّىٰ شَبِعَ.]{.ar} (;madi;, no [أَنْ]{.ar})  
"He ate until he was sated."
-->

## After [لَنْ]{.ar} [lan]{.trn}

[لَا]{.ar} and [أَنْ]{.ar} are combined to form [لَنْ]{.ar} [lan]{.trn} with the meaning "shall not". [لَنْ]{.ar} is used with the ;astate; ;mudarie; verb to emphatically negate the future.

[لَنْ تَذْهَبَ.]{.ar}  
"You~1m~ shall not go."

## After [إِذَنْ]{.ar} [Eipan]{.trn}

TODO

## After [وَ]{.ar}, [فَ]{.ar}, [أَوْ]{.ar}, and [ثُمَّ]{.ar}

### As connectors

If the connectors
[وَ]{.ar}, [فَ]{.ar}, [أَوْ]{.ar}, and [ثُمَّ]{.ar}
occur after an ;astate; ;mudarie; verb, then 
a second ;astate; ;mudarie; verb
(that doesn't have its own [أَنْ]{.ar}, etc.)
may be either in the ;astate; or the ;ustate;.
For example,

[أَرْغَبُ أَنْ أَحْضُرَ ٱلْمَجْلِسَ وَأَسْمَعَ.]{.ar} ([أَسْمَعَ]{.ar} in ;astate;)  
"I desire that I attend the session and [that] I listen."

or

[أَرْغَبُ أَنْ أَحْضُرَ ٱلْمَجْلِسَ وَأَسْمَعُ.]{.ar} ([أَسْمَعَ]{.ar} in ;ustate;)  
"I desire that I attend the session and I will listen."

<!--
 كتاب شرح المفصل لابن يعيش
 vol. 4, p. 259
 https://shamela.ws/book/13301/1623
-->

### With special meanings

[وَ]{.ar}, [فَ]{.ar}, [أَوْ]{.ar}, and [ثُمَّ]{.ar} also cause the following ;mudarie; verb to be in the ;astate; in their own right, not simply as connectors. This is discussed in more detail in chapter TODO.

