# Notes

## The connected noun

###

Wright:

   + vol.\ ii, §172, p.\ 317--319: 

###

Fischer claims (§427):

> Other interrogatives (§289) are also used as relatives:
> [عَرَفَ ٱلْمَكِيدَةَ وَكَيْفَ كَانَ ٱلْمَلِكُ أَوْقَعَهَا]{.ar}
> 'He knew the trick and how the king employed it.'
> [وَٱللّٰهِ مَا نُبَالِي أَيْنَ ذَهَبَ]{.ar}
> 'By God, we do not care where he went'; cf.\ also §419b.

However, we have not been able to find the classical grammarians including [كيف]{.ar}, [أين]{.ar}, etc. among [الأسماء الموصولة]{.ar}.
To understand how these interrogatives are to be analyzed in such sentences,
it may help to look up the [إعراب]{.ar} of the verses :
[هُوَ الَّذِي يُصَوِّرُكُمْ فِي الْأَرْحَامِ كَيْفَ يَشَاءُ]{.ar} [3:6], and
[لِيُرِيَهُ كَيْفَ يُوَارِي سَوْءَةَ أَخِيهِ]{.ar} [5:31]
in linguisitic [tafsIrs]{.trn2} like
[البحر المحيط لأبي حيان]{.ar} and
[التحرير والتنوير لابن عاشور]{.ar}.

The article [ٱل]{.ar} is also generally included among [الأسماء الموصولة المشتركة]{.ar}.
However, we have deemed it too complicated to cover (and too confusing to even mention in main text).
See [النحو الوافي لعباس حسن]{.ar} vol.\ 1, pp.\ 356--357 for its treatment.

###

From  [كتاب المقتصد في شرح الإيضاح للجرجاني]{.ar}, vol.\ 1, p.\ 319:

:::{.ar}
ومَن لا يوصف به، ألا ترى لا تقول: مررت بالرجل مَن أخوه منطلق. فتجعله صفةً للرجل، كما تقول: بالرجل الذي أخوه منطلق
:::

Also [شرح الرضي على الكافية لابن الحاجب]{.ar} vol.\ 2, p.\ 314:

:::{.ar}
ولا يقع من الموصولات وصفا إلا ما في أوله اللام، نحو الذي والتي، واللاتي، وبابها، لمشابهته لفظا للصفة المشبهة في كونه على ثلاثة أحرف فصاعدا، بخلاف من وما، وأما (أي) الموصول فلم يقع وصفا، لأن الأغلب فيه: الشرط والاستفهام ووقوعه موصولا قليل فروعي ذلك الأكثر، وإنما يوصف بذو، الطائية وإن كانت على حرفين كما في قوله:

٣٢٧ - فقولا لهذا المرء ذو جاء ساعيا ... هلم فان المشرفي الفرائض
:::

Basically, of [الأسماء الموصولة المشتركة]{.ar} (which comprise [ما, مَن, أي, أل, ذو, ذا]{.ar}) only the dialectal [ذو]{.ar} appears as a [صفة]{.ar}.

###

From [شرح ابن عقيل على ألفية ابن مالك]{.ar}:

:::{.ar}
وأشار بقوله وأبوا أن يختزل إن صلح الباقي لوصل مكمل إلى أن شرط حذف صدر الصلة أن لا يكون ما بعده صالحا لأن يكون صلة كما إذا وقع بعده جملة نحو جاء الذي هو أبوه منطلق أو هو ينطلق أو ظرف أو جار ومجرور تامان نحو جاء الذي هو عندك أو هو في الدار فإنه لا يجوز في هذه المواضع حذف صدر الصلة فلا تقول جاء الذي أبوه منطلق تعني الذي هو أبوه منطلق لأن الكلام يتم دونه فلا يدرى أحذف منه شيء أم لا؟ وكذا بقية الأمثلة المذكورة ولا فرق في ذلك بين أي وغيرها فلا تقول في يعجبني أيهم هو يقوم يعجبني أيهم يقوم لأنه لا يعلم الحذف ولا يختص هذا الحكم بالضمير إذا كان مبتدأ بل الضابط أنه متى احتمل الكلام الحذف وعدمه لم يجز حذف العائد وذلك كما إذا كان في الصلة ضمير غير ذلك الضمير المحذوف صالح لعوده على الموصول نحو جاء الذي ضربته في داره فلا يجوز حذف الهاء من ضربته فلا تقول جاء الذي ضربت في داره لأنه لا يعلم المحذوف.

وبهذا يظهر لك ما في كلام المصنف من الإبهام فإنه لم يبين أنه متى صلح ما بعد الضمير لأن يكون صلة لا يحذف سواء أكان الضمير مرفوعا أو منصوبا أو مجرورا وسواء أكان الموصول أيا أم غيرها بل ربما يشعر ظاهر كلامه بأن الحكم مخصوص بالضمير المرفوع وبغير أي من الموصولات لأن كلامه في ذلك والأمر ليس كذلك بل لا يحذف مع أي ولا مع غيرها متى صلح ما بعدها لأن يكون صلة كما تقدم نحو جاء الذي هو أبوه منطلق ويعجبني أيهم هو أبوه منطلق وكذلك المنصوب والمجرور نحو جاءني الذي ضربته في داره ومررت بالذي مررت به في داره ويعجبني أيهم ضربته في داره ومررت بأيهم مررت به في داره.
:::

###

From [تفسير القرطبي]{.ar}:

:::{.ar}
قوله تعالى : ثم آتينا موسى الكتاب مفعولان . تماما مفعول من أجله أو مصدر . على الذي أحسن قرئ بالنصب والرفع . فمن رفع - وهي قراءة يحيى بن يعمر وابن أبي إسحاق - فعلى تقدير : تماما على الذي هو أحسن . قال المهدوي : وفيه بعد من أجل حذف المبتدأ العائد على الذي . وحكى سيبويه عن الخليل أنه سمع " ما أنا بالذي قائل لك شيئا " . ومن نصب فعلى أنه فعل ماض داخل في الصلة ; هذا قول البصريين . وأجاز الكسائي والفراء أن يكون اسما نعتا ل " الذي " وأجازا " مررت بالذي أخيك " ينعتان " الذي " بالمعرفة وما قاربها . قال النحاس : وهذا محال عند البصريين ; لأنه نعت للاسم قبل أن يتم ، والمعنى عندهم : على المحسن .

شرح ابن عقيل:
ذهب الكوفيون إلى أنه يجوز حذف العائد المرفوع بالابتداء مطلقا، أي سواء أكان الموصول أيا أم غيره، وسواء أطالت الصلة أم لم تطل، وذهب البصريون إلى جواز حذف هذا العائد إذا كان الموصول أيا مطلقا، فإن كان الموصول غير أي لم يجيزوا الحذف إلا بشرط طول الصلة، فالخلاف بين الفريقين منحصر فيما إذا لم تطل الصلة وكان الموصول غير أي، فأما الكوفيون فاستدلوا بالسماع، فمن ذلك قراءة يحيى بن يعمر:
(تماما على الذي أحسن) قالوا: التقدير على الذي هو أحسن، ومن ذلك قراءة مالك ابن دينار وابن السماك: (إن الله لا يستحيي أن يضرب مثلا ما بعوضة فما فوقها) قالوا:
التقدير: مثلا الذي هو بعوضة فما فوقها، ومن ذلك قول الشاعر:
لا تنو إلا الذي خير، فما شقيت * إلا نفوس الألى للشر ناوونا قالوا: التقدير لا تنو إلا الذي هو خير، ومن ذلك قول الآخر:
من يعن بالحمد لم ينطق بما سفه ولا يحد عن سبيل المجد والكرم قالوا: تقدير هذا البيت: من يعن بالحمد لم ينطق بالذي هو سفه، ومن ذلك قول عدي بن زيد العبادي:
لم أر مثل الفتيان في غبن * الأيام يدرون ما عواقبها قالوا: ما موصولة، والتقدير: يدرون الذي هو عواقبها.
وبعض هذه الشواهد يحتمل وجوها من الاعراب غير الذي ذكروه، فمن ذلك أن " ما " في الآية الثانية يجوز أن تكون زائدة، وبعوضة خبر مبتدأ محذوف، ومن ذلك أن " ما " في بيت عدي بن زيد يحتمل أن تكون استفهامية مبتدأ، وما بعدها خبر، والجملة في محل نصب مفعول به ليدرون، وقد علق عنها لأنها مصدرة بالاستفهام، والكلام يطول إذا نحن تعرضنا لكل واحد من هذه الشواهد، فلنجتزئ لك بالإشارة.
:::

### Use of [ما]{.ar} for intelligent beings and [من]{.ar} for non-intelligent beings

From [[شرح ابن عقيل على ألفية ابن مالك ت: محمد محيي الدين عبد الحميد]{.ar} 1/147, footnotes](https://shamela.ws/book/9904/146#p1)

:::{.ar}
(١) تستعمل " ما " في العاقل في ثلاثة مواضع، الاول: أن يختلط العاقل مع غير العاقل نحو قوله تعالى: (يسبح لله ما في السموات وما في الارض) فإن ما يتناول ما فيهما من إنس وملك وجن وحيوان وجماد، بدليل قوله: (وإن من شئ إلا يسبح بحمده) والموضع الثاني: أن يكون أمره مبهما على المتكلم، كقولك - وقد رأيت شبحا من بعيد -: انظر ما ظهر لي، وليس منه قوله تعالى: (إذ قالت امرأة عمران رب إني نذرت لك ما في بطني محررا) لان إبهام ذكورته وأنوثته لا يخرجه عن العقل، بل استعمال " ما " هنا في ما لا يعقل لان الحمل ملحق بالجماد، والموضع الثالث: أن يكون المراد صفات من يعقل، كقوله تعالى (فانكحوا ما طاب لكم) وهذا الموضع هو الذي ذكره الشارح بالمثال الاول من غير بيان.

(٢) تستعمل " من " في غير العاقل في ثلاثة مواضع، الاول: أن يقترن
غير العاقل مع من يعقل في عموم فصل بمن الجارة، نحو قوله تعالى: (فمنهم من يمشي على بطنه، ومنهم من يمشي على رجلين، ومنهم من يمشي على أربع) ومن المستعملة فيما لا يعقل مجاز مرسل علاقته المجاورة في هذا الموضع، والموضع الثاني: أن يشبه غير العاقل بالعاقل فيستعار له لفظه، نحو قوله تعالى: (من لا يستجيب له تعالى) وقول الشاعر أسرب القطا هل من يعير جناحه وهو الذي استشهد به المؤلف
فيما يلي، وسنذكر معه نظائره، واستعمال من فيما لا يعقل حينئذ استعارة، لان العلاقة المشابهة، والموضع الثالث: أن يختلط من يعقل بما لا يعقل نحو قول الله تعالى: (ولله يسجد من في السموات ومن في الارض) واستعمال من فيما لا يعقل - في هذا الموضع - من باب التغليب، واعلم أن الاصل تغليب من يعقل على ما لا يعقل، وقد يغلب ما لا يعقل على من يعقل، لنكتة، وهذه النكت تختلف باختلاف الاحوال والمقامات.
:::

### [أيّ]{.ar} followed by [شاء]{.ar}

I have found some narrations where 
[أيّ]{.ar} is followed by the verb [شاء]{.ar}. For example,

[فَلْتَدْخُلْ مِنْ أَيِّ أَبْوَابِ الْجَنَّةِ شَاءَتْ]{.ar}  
https://sunnah.com/mishkat:3254

[فُتِحَتْ لَهُ أَبْوَابُ الْجَنَّةِ الثَّمَانِيَةُ يَدْخُلُ مِنْ أَيِّهَا شَاءَ]{.ar}  
https://sunnah.com/muslim:234a

[فَخُذْ بِيَدِ أَيِّهِمَا شِئْتَ]{.ar}  
https://sunnah.com/abudawud:2277

The question is whether
[أيّ]{.ar}
in these examples is [موصولة]{.ar}

[حنين محمد عبد]{.ar} has a thesis entitled
[(أيٌّ) في اللغة العربية - دراسة نحوية]{.ar}
under which some similar examples are filed under a category [أي التعميمية]{.ar}.

I'm not convinced...

I find a similarity between these examples and the [Ayah]{.trn2}s:

[من كان يريد العاجلة عجلنا له فيها ما نشاء لمن نريد]{.ar}  
https://quran.com/17/18

and

[نَرْفَعُ دَرَجَـٰتٍۢ مَّن نَّشَآءُ]{.ar}  
https://quran.com/12/76  
In one reading [درجات]{.ar} is a [مضاف]{.ar}.

As far as I can see, [مَنْ]{.ar} has been analyzed as [موصولة]{.ar} in these verses.
As to their [صلة]{.ar} and [عائد]{.ar}
it has been generally menioned that the [مفعول به]{.ar} for verbs like [شاء]{.ar} is often deleted.
But usually this is in a conditional context:

From [معاني النحو]{.ar}:

:::{.ar}
ويكثر ذلك في فعل المشيئة أو الإرادة أو نحوهما إذا وقع فعل شرط فإن الجواب يدل عليه ويبينه، نحو قوله تعالى: وَلَوْ شاءَ اللَّهُ مَا اقْتَتَلُوا، أي: ولو شاء الله ألا يقتتلوا أو عدم اقتتالهم ما اقتتلوا. فإنه لما قيل: «ولو شاء» علم السامع أن هناك شيئا تعلقت المشيئة الإلهية به لكنه خفيّ مبهم، فلما جيء بجواب الشرط صار بينا واضحا يقع في النفس.

ومثله قوله تعالى: وَلَوْ شاءَ لَهَداكُمْ أَجْمَعِينَ، أي: لو شاء هدايتكم لهداكم أجمعين. وقوله تعالى: وَلَوْ شِئْنا لَآتَيْنا كُلَّ نَفْسٍ هُداها، أي: ولو شئنا هداية النفوس لآتينا كل نفس هداها.
:::

From [دلائل الإعجاز للجرجاني]{.ar}:

:::{.ar}
لَوْ شِئْتَ لَمْ تُفْسِدْ سَمَاحَةَ حَاتِمٍ     كَرَمًا وَلَمْ تَهْدِمْ مَآثِرَ خَالِدِ


الْأَصْلُ لَا مَحَالَةَ: لَوْ شِئْتَ أَنْ لَا تُفْسِدَ سَمَاحَةَ حَاتِمٍ لَمْ تُفْسِدْهَا ، ثُمَّ حَذَفَ ذَلِكَ مَنِ الْأَوَّلِ اسْتِغْنَاءً بِدَلَالَتِهِ فِي الثَّانِي عَلَيْهِ . ثُمَّ هُوَ عَلَى مَا تَرَاهُ وَتَعْلَمُهُ مِنَ الْحُسْنِ وَالْغَرَابَةِ وَهُوَ عَلَى مَا ذَكَرْتُ لَكَ مِنْ أَنَّ الْوَاجِبَ فِي حُكْمِ الْبَلَاغَةِ أَنْ لَا يُنْطَقَ بِالْمَحْذُوفِ وَلَا يَظْهَرُ إِلَى اللَّفْظِ . فَلَيْسَ يَخْفَى أَنَّكَ لَوْ رَجَعْتَ فِيهِ إِلَى مَا هُوَ أَصْلُهُ فَقُلْتَ : " لَوْ شِئْتَ أَنْ لَا تُفْسِدَ سَمَاحَةَ حَاتِمٍ لَمْ تُفْسِدْهَا " صِرْتَ إِلَى كَلَامٍ غَثٍّ، وَإِلَى شَيْءٍ يَمُجُّهُ السَّمْعُ وَتَعَافُهُ النَّفْسُ . وَذَلِكَ أَنَّ فِي الْبَيَانِ، [ ص: 164 ] إِذَا وَرَدَ بَعْدَ الْإِبْهَامِ وَبَعْدَ التَّحْرِيكِ لَهُ أَبَدًا لُطْفًا وَنُبْلًا لَا يَكُونُ إِذَا لَمْ يَتَقَدَّمْ مَا يُحَرِّكُ.

وَأَنْتَ إِذَا قُلْتَ : " لَوْ شِئْتَ " عَلِمَ السَّامِعُ أَنَّكَ قَدْ عَلَّقْتَ هَذِهِ الْمَشِيئَةَ فِي الْمَعْنَى بِشَيْءٍ، فَهُوَ يَضَعُ فِي نَفْسِهِ أَنَّ هَهُنَا شَيْئًا تَقْتَضِي مَشِيئَتُهُ لَهُ أَنْ يَكُونَ أَوْ أَنْ لَا يَكُونَ . فَإِذَا قُلْتَ : " لَمْ تُفْسِدْ سَمَاحَةَ حَاتِمٍ " عَرَفَ ذَلِكَ الشَّيْءَ.

وَمَجِيءُ " الْمَشِيئَةِ " بَعْدَ " لَوْ " وَبَعْدَ حُرُوفِ الْجَزَاءِ هَكَذَا مَوْقُوفَةً غَيْرَ مُعَدَّاةٍ إِلَى شَيْءٍ، كَثِيرٌ شَائِعٌ كَقَوْلِهِ تَعَالَى : « وَلَوْ شَاءَ اللَّهُ لَجَمَعَهُمْ عَلَى الْهُدَى » [ سُورَةِ الْأَنْعَامِ :35 ] « وَلَوْ شَاءَ لَهَدَاكُمْ أَجْمَعِينَ » [ سُورَةِ النَّحْلِ :9 ] . وَالتَّقْدِيرُ فِي ذَلِكَ كُلِّهِ عَلَى مَا ذَكَرْتُ، فَالْأَصْلُ : لَوْ شَاءَ اللَّهُ أَنْ يَجْمَعَهُمْ عَلَى الْهُدَى لَجَمَعَهُمْ - وَلَوْ شَاءَ أَنْ يَهْدِيَكُمْ أَجْمَعِينَ لَهَدَاكُمْ - إِلَّا أَنَّ الْبَلَاغَةَ فِي أَنْ يُجَاءَ بِهِ كَذَلِكَ مَحْذُوفًا .
:::

My examples are not in a conditional context but could they be analyzed as [أي الموصولة]{.ar} with its [صلة]{.ar} in the deleted [مفعول به]{.ar} of [شاء]{.ar}?

For example:

[فَلْتَدْخُلْ مِنْ أَيِّ أَبْوَابِ الْجَنَّةِ شَاءَتْ _أن تدخل منه_]{.ar}  

### The violence of the grammarians

I wish I could directly use examples from the classical grammarians.
But consider this gem from [كتاب سيبويه]{.ar}:

[وزعم الخليل أن أيهم إنما وقع في قولهم: اضرب أيهم أفضل على أنه حكاية]{.ar}

Even the most excellent of them they would beat!

and how about this from [ابن عقيل]{.ar}:

[يعجبني أيهم ضربته في داره]{.ar}

A man was not safe from the grammarians even in his own house, and even when he was someone they liked!

And when tired from all the beatings they were dishing out, 
they would suffice with [يعجبني]{.ar} and [مررت بـ]{.ar} sentences 
which grow repetitious.

I'm just complaining...


