# The question nouns [مَا]{.ar}, [مَنْ]{.ar}, and [أَيّ]{.ar}

## Introduction

In chapter (connected nouns) we studied the use of
[مَا]{.ar} "what",
[مَنْ]{.ar} "who",
and
[أَيّ]{.ar} "which"
as the general connected nouns.
In this chapter, we will study the use of these same nouns as _question nouns_.

There are other question nouns besides the ones above, like
[كَيْفَ]{.ar} "how",
[أَيْنَ]{.ar} "where"
[مَتَىٰ]{.ar} "when".
There are also question words which are particles, not nouns, like
[أَ]{.ar}
and
[هَلْ]{.ar}.
We will study all these elsewhere, if [#allAh]{.trn2} wishes.

## [مَا]{.ar} and [مَنْ]{.ar}

All question words typically occur in the beginning of the question sentence.
(Particles like [وَ]{.ar}, [فَ]{.ar}, etc. are allowed to precede them.)
For example,

[مَنْ أَنْتَ؟]{.ar}
^[Wright vol. ii, §170, p. 311D]  
"Who are you?"

[وَمَا تِلْكَ بِيَمِينِكَ؟]{.ar}
^[[[طه]{.ar}:17](https://quran.com/20:17)]  
"What is that in your right hand?"

In both the above examples, the question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
are in the u-state as the topic of their respective question sentences.

When the question is asking about the direct doee of a verb, then too
is the question noun placed in the beginning of the sentence. For example,

[مَا تَقُولُ؟]{.ar}
^[Wright vol. ii, §170, p. 312A]  
"What do you say?"

[مَنْ قَتَلْتَ؟]{.ar}
^[Wright vol. ii, §170, p. 311D]  
"Whom did you kill?"

[مَا فَرَضَ رَبُّكَ عَلَىٰ أُمَّتِكَ؟]{.ar}
^[[[مسلم]{.ar}:162a](https://sunnah.com/muslim:162a)]  
"What has your Lord enjoined upon your [#ummah]{.trn2}?"

In the above three examples, the question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
are analyzed as the a-state direct doee of the verb following it.

The question nouns are exempted from being placed in the beginning of the question noun when they are in the i-state:
either following a preposition, or as the base noun in an annexation. For example,

[لِمَنْ هَـٰذَا ٱلْقَصْرُ؟]{.ar}
^[[[الترمذي]{.ar}:3688](https://sunnah.com/tirmidhi:3688)]  
"Whose is this palace?"

[بِنْتُ مَنْ أَنْتِ؟]{.ar}
^[Wright vol. ii, §170, p. 311D]  
"Whose daughter are you?"

When the question noun [مَا]{.ar} [mA]{.trn} is in the i-state it is typically shortened to [مَ]{.ar} [ma]{.trn}.
Example:

[بِمَ يَرْجِعُ؟]{.ar}
^[[[سنن ابن ماجه]{.ar}:4108](https://sunnah.com/ibnmajah:4108)]  
"With what does he return?"

This shortened [مَ]{.ar} is also usually joined to the preposition before it,
even for prepositions constituting more than one letter (which don't typically join to the word directly following it).
So we get:

+ [بِمَ]{.ar} for [بِمَا]{.ar}
+ [لِمَ]{.ar} for [لِمَا]{.ar}
+ [فِيمَ]{.ar} for [فِي مَا]{.ar}
+ [إِلَامَ]{.ar} for [إِلَىٰ مَا]{.ar}
+ [عَلَامَ]{.ar} for [عَلَىٰ مَا]{.ar}
+ [حَتَّامَ]{.ar} for [حَتَّىٰ مَا]{.ar}
+ [مِمَّ]{.ar} for [مِمَّا]{.ar} ([مِنْ مَا]{.ar})
+ [عَمَّ]{.ar} for [عَمَّا]{.ar} ([عَنْ مَا]{.ar})

When pausing on this shortened [مَ]{.ar}, a [هْ]{.ar} is appended to it to preserve the sound of the [a]{.trn}-mark.
For example:

[لِمَهْ؟]{.ar}  
[limah?]{.trn}  
"For what?"

The shortened [مَ]{.ar} is also used when it is the base noun in an annexation. 
However, in this case it won't be joined to the previous word.
For example:

[مِثْلُ مَ أَنْتَ؟]{.ar}
^[Wright vol. i, §351, p. 275A]  
"What are you like?"

As an alternative to placing the question noun
[مَا]{.ar}
or
[مَنْ]{.ar}
after the preposition or annex noun,
the question noun may be placed in the beginning of the sentence
and it is referred back to by a pronoun. For example,

[قُلْ مَنْ بِيَدِهِ مَلَكُوتُ كُلِّ شَيْءٍ]{.ar}
^[[[المؤمنون]{.ar}:88](https://quran.com/23:88)]  
Say, "In whose hand is the realm of all things"

The question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
are themselves masculine singular nouns.
But they can be used to ask abount nouns of any gender or number.
For example,

[مَا تِلْكَ بِيَمِينِكَ؟]{.ar}
^[[[طه]{.ar}:17](https://quran.com/20:17)]  
"What is that in your right hand?"

[مَنْ هَـٰؤُلَاءِ ٱلرِّجَالُ؟]{.ar}  
"Who are these men?"

When asking the identity of the doer of a verb, then the verb is usually construed with a masculine singular doer to match the question noun. For example:

[مَنْ جَاءَ؟]{.ar}  
"Who has come?"

[مَا يُبْكِيكَ؟]{.ar}
^[[[الترمذي]{.ar}:3894](https://sunnah.com/tirmidhi:3894)]  
"What makes you cry?"

Ocassionally, the feminine verb may be used if asking about a feminine doer. For example:

[مَنْ كَانَتْ أُمَّكَ؟]{.ar}
^[Wright vol. ii, §170, p. 313C. Also [تفسير البحر المحيط لأبي حيان]{.ar} for [[«فإن كانتا اثنتين» [النساء:١٧٦]]{.ar}](https://tafsir.app/albahr-almuheet/4/176) and [[«ثم لم تكن فتنتهم» [الأنعام:٢٣]]{.ar}](https://tafsir.app/albahr-almuheet/6/23)]
"Who was your mother?"

<!--Note how [كَانَتْ]{.ar} has a feminine doer pronoun to match the gender of [أُمَّكَ]{.ar}.-->

If the question is regarding a specific number and gender, then we are more likely to insert the corresponding specific connected noun
([ٱلَّذِي]{.ar}, etc.)
between the question noun [مَن]{.ar} and the verb. 
For example:

[مَنِ اللَّتَانِ تَظَاهَرَتَا عَلَى النَّبِيِّ صلى الله عليه وسلم مِنْ أَزْوَاجِهِ]{.ar}
^[[[صحيح البخاري]{.ar}:4913](https://sunnah.com/bukhari:4913)]  
"Who are the ones~2f~, from his wives, who aided one another against the Prophet [ﷺ ]{.ar}?  

Note that now the dual feminine doer pronoun [ا]{.ar} in [تَظَاهَرَتَا]{.ar} is the refer-back pronoun that refers back to the connected noun [ٱللَّتَانِ]{.ar}.

## Differentiating question words from their other functions

Many of the question words 
([أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.)
also have other functions.
For example,
in chapter\ \@ref(the-connected-nouns) we learned that [مَنْ]{.ar}, [مَا]{.ar}, and [أَيّ]{.ar} are also connected nouns.
Many of the question nouns can also be used as _conditional nouns_ that we will study in chapter\ \@ref(...), if [#allAh]{.trn2} wills.

In this section, we will discuss briefly how to determine when words like
[أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.
are question words, and when they could have one of their other functions.

The basic principle regarding a question sentence is that it is to be treated as one unit. 
A word from within a question sentence is not, individually, affected by anything outside the question.
Let's try to understand this using an example.

Consider the following sentence:

[ٱِسْأَلْ أَيُّهُمْ قَامَ]{.ar}  
[EisEal Eayyuhum qAm]{.trn}  
"Ask: 'Which of them stood?'"

The speaker is commanding the addressed person to ask a group of people the question: 
"Which of them stood".

The question sentence is
[أَيُّهُمْ قَامَ]{.ar}
[Eayyuhum qAm]{.trn}
"Which of them stood".
This entire sentence is considered the direct doee of the verb of command [ٱسْأَلْ]{.ar} "ask!".
The question noun [أَيُّ]{.ar} [Eayyu]{.trn} is in the u-state because it is the subject of the question sentence.
It does not become [أَيَّ]{.ar} [Eayya]{.trn} in the a-state because it is not, by itself, the direct doee of 
[ٱسْأَلْ]{.ar}.
Rather, as we have just stated, the entire question sentence is the direct doee.
But because the direct doee is a sentence, and not an individual word, it does not indicate its state using, for example, an a-mark [◌َ]{.ar}.

Now, let's modify the example. Consider now this sentence:

[ٱِسْأَلْ أَيَّهُمْ قَامَ]{.ar}  
[EisEal Eayyahum qAm]{.trn}  
Ask the one of them who stood!

Now, the noun [أَيَّ]{.ar} is in the a-state because it (individually) is the direct doee of the verb of command 
[ٱسْأَلْ]{.ar}.
The speaker is now commanding the addressed person to ask (something) of only the person who stood, out of a group of people. The rest of the people are not to be asked.
Because the noun 
[أَيَّ]{.ar}
is individually affected by the preceding verb
[ٱسْأَلْ]{.ar}
it is now not a question noun, and must be one of the other functions that the word
[أَيّ]{.ar} can have.
As a matter of fact, it is here a connected noun, and the sentence following it:
[قَامَ]{.ar} "he stood" is its connector.

The other noteworthy point regarding questions
(besides their being considered one unit)
is that they may only be preceded 
either by a verb of knowledge, (like [عَلِمَ]{.ar}, [دَرىٰ]{.ar}, etc.)
or by an expression indicating that the question is being quoted.
We have already seen an example of the question being quoted in the example:

[ٱِسْأَلْ أَيُّهُمْ قَامَ]{.ar}  
"Ask: 'Which of them stood?'"

An example of a question being preceded by a verb of knowledge is:

[مَا عَلِمْتُ أَذَهَبَ أَمْ مَكَثَ]{.ar}  
I don't know whether he went or stayed.

Here the question sentence is: 
[أَذَهَبَ أَمْ مَكَثَ]{.ar}
"Did he go or did he stay?"

By the way, a question sentence may be part of a bigger question as well. For example:

[أَتَدْرِي أَيُّهُمْ فِي ٱلدَّارِ؟]{.ar}  
[EatadrI Eayyuhum fi -ddAr]{.trn}  
Do you know: which of them is in the house?

Note now the subtle difference in meaning if we change the state of [أَيّ]{.ar} in the above example from the u-state to the a-state:

[أَتَدْرِي أَيَّهُمْ فِي ٱلدَّارِ؟]{.ar}  
[EatadrI Eayyahum fi -ddAr]{.trn}  
Do you know the one of them who is in the house?

When [أَيّ]{.ar} was in the u-state it was a question noun. And the speaker was asking the addressed person if he could figure out who, from among the group of people, was in the house.

When [أَيّ]{.ar} is in the a-state it is now a connected noun.
The connector's link-back pronoun is omitted (as is permissible in this case, see section\ \@ref(...)). With the link-back pronoun restored, the sentence is
[أَتَدْرِي أَيَّهُمْ هُوَ فِي ٱلدَّارِ؟]{.ar}
And the speaker is asking the addressed person if he is familiar with the person who is in the house.
Now he is not asking the addressed person to identify him, but rather if knows him as a person.

This difference is apparent with 
[أَيّ]{.ar} 
because it is a flexible noun whose state is indicated by the vowel mark at its end.
The same occurs in the other question nouns that are also connected nouns:
[مَا]{.ar}, and [مَنْ]{.ar}
but it won't often be as apparent because they are rigid nouns.

As a final note, sometimes, one of the words like 
[أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.
may be preceded by parts of a sentence that are neither quoting, nor a verb of knowledge.
Here we can be sure that the word is not a question word
and
must be one of its other functions. However,
it still may not be easy to figure out what that other function is.
Nevertheless, the meaning of the sentence can still usually be gleaned.
For example:

[فَلْتَدْخُلْ مِنْ أَيِّ أَبْوَابِ الْجَنَّةِ شَاءَتْ]{.ar}  
"then let her enter from whichever of the doors of paradise she wishes."[^question-vs-other-functions]

