# The question nouns [مَا]{.ar}, [مَنْ]{.ar}, and [أَيّ]{.ar}

## Introduction

In chapter (connected nouns) we studied the use of
[مَا]{.ar} "what",
[مَنْ]{.ar} "who",
and
[أَيّ]{.ar} "which"
as the general connected nouns.
In this chapter, we will study the use of these same nouns as _question nouns_.

There are other question nouns besides the ones above, like
[كَيْفَ]{.ar} "how",
[أَيْنَ]{.ar} "where"
[مَتَىٰ]{.ar} "when".
There are also question words which are particles, not nouns, like
[أَ]{.ar}
and
[هَلْ]{.ar}.
We will study all these elsewhere, if [_allAh]{.trn2} wishes.

## [مَا]{.ar} and [مَنْ]{.ar}

### Position of question words in the beginning of the sentence

All question words typically occur in the beginning of the question sentence.
(Particles like [وَ]{.ar}, [فَ]{.ar}, etc. are allowed to precede them.)
For example,

[مَنْ أَنْتَ؟]{.ar}
[Wright vol.\ ii, §170, p.\ 311D]{.aside}  
"Who are you?"

[وَمَا تِلْكَ بِيَمِينِكَ؟]{.ar}
[<https://quran.com/20:17>]{.aside}  
"And what is that in your right hand?"

In both the above examples, the question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
are in the u-state as the topic of their respective question sentences.

When the question is asking about the ;mafulb; of a verb, then too
is the question noun placed in the beginning of the sentence. For example,

[مَا تَقُولُ؟]{.ar}
[Wright vol.\ ii, §170, p.\ 312A]{.aside}  
"What do you say?"

[مَنْ قَتَلْتَ؟]{.ar}
[Wright vol.\ ii, §170, p.\ 311D]{.aside}  
"Whom did you kill?"

[مَا فَرَضَ رَبُّكَ عَلَىٰ أُمَّتِكَ؟]{.ar}
[<https://sunnah.com/muslim:162a>]{.aside}  
"What has your Lord enjoined upon your [_ummah]{.trn2}?"

In the above three examples, the question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
are analyzed as the a-state ;mafulb; of the verb following it.

The question nouns are exempted from being placed in the beginning of the question noun when they are in the i-state:
either following a preposition, or as the ;mudafil; in an ;idafa;. For example,

[لِمَنْ هَـٰذَا ٱلْقَصْرُ؟]{.ar}
[<https://sunnah.com/tirmidhi:3688>]{.aside}  
"Whose is this palace?"

[بِنْتُ مَنْ أَنْتِ؟]{.ar}
[Wright vol.\ ii, §170, p.\ 311D]{.aside}  
"Whose daughter are you?"

### [مَا]{.ar} shortened to [مَ]{.ar} in the i-state

When the question noun [مَا]{.ar} [mA]{.trn} is in the i-state it is typically shortened to [مَ]{.ar} [ma]{.trn}.
Example:

[بِمَ يَرْجِعُ؟]{.ar}
[<https://sunnah.com/ibnmajah:4108>]{.aside}  
"With what does he return?"

This shortened [مَ]{.ar} is also usually joined to the preposition before it,
even for prepositions constituting more than one letter (which don't typically join to the word directly following it).
So we get:

+ [بِمَ]{.ar} for [بِمَا]{.ar}
+ [لِمَ]{.ar} for [لِمَا]{.ar}
+ [فِيمَ]{.ar} for [فِي مَا]{.ar}
+ [إِلَامَ]{.ar} for [إِلَىٰ مَا]{.ar}
+ [عَلَامَ]{.ar} for [عَلَىٰ مَا]{.ar}
+ [حَتَّامَ]{.ar} for [حَتَّىٰ مَا]{.ar}
+ [مِمَّ]{.ar} for [مِمَّا]{.ar} ([مِنْ مَا]{.ar})
+ [عَمَّ]{.ar} for [عَمَّا]{.ar} ([عَنْ مَا]{.ar})

When pausing on this shortened [مَ]{.ar}, a [هْ]{.ar} is appended to it to preserve the sound of the ;amark;.
For example:

[لِمَهْ؟]{.ar}  
[limah?]{.trn}  
"For what?"

The shortened [مَ]{.ar} is also used when it is the ;mudafil; in an ;idafa;. 
However, in this case it won't be joined to the previous word.
For example:

[مِثْلُ مَ أَنْتَ؟]{.ar}
[Wright vol.\ i, §351, p.\ 275A]{.aside}  
"What are you like?"

### [مَا]{.ar} and [مَنْ]{.ar} referred back to with an i-state pronoun

As an alternative to placing the question noun
[مَا]{.ar}
or
[مَنْ]{.ar}
after the preposition or ;mudaf;,
the question noun may be placed in the beginning of the sentence
and it is referred back to by a pronoun. For example,

[قُلْ مَنْ بِيَدِهِ مَلَكُوتُ كُلِّ شَيْءٍ]{.ar}
[<https://quran.com/23:88>]{.aside}  
Say, "In whose hand is the realm of all things"

[مَاذَا يَسْتَعْجِلُ مِنْهُ الْمُجْرِمُونَ]{.ar}
[<https://quran.com/10:50>]{.aside}  
"for which [aspect] of it would the criminals be impatient?"

### Verb gender when inquiring about the ;fail; of a verb

The question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
are themselves masculine singular nouns.
But they can be used to ask abount nouns of any gender or number.
For example,

[وَمَا تِلْكَ بِيَمِينِكَ؟]{.ar}
[<https://quran.com/20:17>]{.aside}  
"And what is that in your right hand?"

[مَنْ هَـٰؤُلَاءِ ٱلرِّجَالُ؟]{.ar}  
"Who are these men?"

When inquiring about the ;fail; of a verb, then the verb is usually construed with a masculine singular ;fail; to match the question noun. For example:

[مَنْ جَاءَ؟]{.ar}  
"Who has come?"

[مَا يُبْكِيكَ؟]{.ar}
[<https://sunnah.com/tirmidhi:3894>]{.aside}  
"What makes you cry?"

Ocassionally, the feminine verb may be used if asking about a feminine ;fail;. For example:

[مَنْ كَانَتْ أُمَّكَ؟]{.ar}
^[See also [تفسير البحر المحيط لأبي حيان]{.ar} for [[«فإن كانتا اثنتين» [النساء:١٧٦]]{.ar}](https://tafsir.app/albahr-almuheet/4/176) and [[«ثم لم تكن فتنتهم» [الأنعام:٢٣]]{.ar}](https://tafsir.app/albahr-almuheet/6/23)]
[Wright vol.\ ii, §170, p.\ 313C]{.aside}  
"Who was your mother?"

<!--Note how [كَانَتْ]{.ar} has a feminine ;fail; pronoun to match the gender of [أُمَّكَ]{.ar}.-->

If the question is regarding a specific number and gender, then we are more likely to insert the corresponding specific connected noun
([ٱلَّذِي]{.ar}, etc.)
between the question noun [مَن]{.ar} and the verb. 
For example:

[مَنِ اللَّتَانِ تَظَاهَرَتَا عَلَى النَّبِيِّ صلى الله عليه وسلم مِنْ أَزْوَاجِهِ]{.ar}
[<https://sunnah.com/bukhari:4913>]{.aside}  
"Who are the ones~2f~, from his wives, who aided one another against the Prophet [ﷺ ]{.ar}?  

Note that now the dual feminine ;fail; pronoun [ا]{.ar} in [تَظَاهَرَتَا]{.ar} is the refer-back pronoun that refers back to the connected noun [ٱللَّتَانِ]{.ar}.

### An indefinite noun after [مَا]{.ar} and [مَنْ]{.ar}

The question nouns [مَا]{.ar} and [مَنْ]{.ar}
cannot occur as ;mudaf;s.
Nor can either of them be a replacee.
So any indefinite noun after them must necessarily be the comment of the question sentence.
For example,
[مَنْ فَارِسٌ؟]{.ar} 
[Wright, vol.\ ii, §170, p.\ 312C]{.aside}
can only mean, "Who is a horseman?" not "Who horseman?" or "Which horseman?"

### [مَاذَا]{.ar} and [مَنْ ذَا]{.ar}

To lend more force to the question or to make it more lively, [ذَا]{.ar} may be appended to the question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}.
For example,

[مَاذَا قَالَ رَبُّكُمْ]{.ar}
[<https://sunnah.com/bukhari:4800>]{.aside}  
"What did your lord say?"

With [مَنْ ذَا]{.ar} especially, but also with [مَا]{.ar}, the specific connected noun [ٱلَّذِي]{.ar} is often appended as well.
For example:

[مَنْ ذَا الَّذِي قَالَ هَذَا]{.ar}
[<https://sunnah.com/ibnmajah:3802>]{.aside}  
"Who is the one that said this?"

[مَاذَا ٱلَّذِي تَقُولُ؟]{.ar}
[Wright, vol.\ ii, §170, p.\ 312B]{.aside}  
"What is it that you say?"

Note that [ذَا]{.ar} is also a variant pointing noun meaning "this" or "that". 
In which case, it can be the comment of the question sentence by itself.
For example:

<!--[مَنْ ذَا؟]{.ar}
"Who is that?"-->

[فَدَقَقْتُ الْبَابَ، فَقَالَ: مَنْ ذَا؟ فَقُلْتُ: أَنَا، قَالَ: أَنَا، أَنَا؟، كَأَنَّهُ كَرِهَهُ.]{.ar}
[<https://sunnah.com/adab:1086>]{.aside}  
"So I knocked at the door. He said, 'Who is that?' I said, 'I.' He said 'I? I?' as if he disliked it."

### Why

Arabic has no distinct question word for "why".
Instead, the question noun [مَا]{.ar} is used with a preposition, typically [لِ]{.ar}
to give the meaning "For what?".
For example,

[لِمَ فَعَلَ ذَلِكَ]{.ar}
[<https://sunnah.com/muslim:705b>]{.aside}  
"Why did he do that?"

[لِمَاذَا وَلَّيْتَ بَعْدَ مَجِيِّكَ إِلَىٰ هَـٰهُنَا؟]{.ar}
[Wright, vol.\ ii, §170, p.\ 312B]{.aside}  
"Why did you turn back after your coming here?"

Sometimes, other prepositions like [عَلَىٰ]{.ar} and [بِ]{.ar} may be used. But this is dependent on the verb in the sentence.
For example,

[عَلَامَ يَقْتُلُ أَحَدُكُمْ أَخَاهُ]{.ar}
[<https://sunnah.com/mishkat:4562>]{.aside}  
"Why does one of you kill his brother?"  
i.e. "on what [basis]"

[بِمَ يَأْخُذ أحدكُم مَال أَخِيه؟]{.ar}
[<https://sunnah.com/mishkat:2840>]{.aside}  
"Why should any of you take his brother’s property?"  
i.e. "by what [justification]"

And often times, the meaning "why" is conveyed using [مَا]{.ar} when a suitable verb exists. For example:

[مَا يُبْكِيكَ؟]{.ar}
[<https://sunnah.com/tirmidhi:3894>]{.aside}  
"What makes you cry?"  
i.e. "Why are you crying?"

### Applicability of [مَا]{.ar} and [مَنْ]{.ar} to intelligent and non-intelligent beings {#man-and-maa-for-intelligent}

In (give ref) we discussed how, sometimes, the connected noun [مَا]{.ar} may be used for intelligent beings
and [مَنْ]{.ar} for non-intelligent beings.
Those same guidelines apply for [مَا]{.ar} and [مَنْ]{.ar} when they are question nouns.
For example,
when inquiring about the nature or qualities of a person [مَا]{.ar} may be used. Examples:

[فَقُلْتُ لَهُ مَا أَنْتَ قَالَ أَنَا نَبِيٌّ. فَقُلْتُ وَمَا نَبِيٌّ قَالَ أَرْسَلَنِي اللَّهُ]{.ar}
[<https://sunnah.com/muslim:832>]{.aside}  
"I said, 'Who are you?' He said, 'I am a prophet.' So I said, 'And who is a prophet?' He said '[_allAh]{.trn2} has sent me.'"

## [أَيّ]{.ar}

In section .. we studied [أَيّ]{.ar} as a general connected noun.
Just like
[مَا]{.ar}
and
[مَنْ]{.ar},
[أَيّ]{.ar}
too can be a question noun for "which" questions.
Many of the rules that apply the question nouns
[مَا]{.ar}
and
[مَنْ]{.ar}
also apply to 
[أَيّ]{.ar}.
For example,
the default position of 
[أَيّ]{.ar}
is in the beginning of the question sentence.

However,
[أَيّ]{.ar}
is also different from 
[مَا]{.ar}
and
[مَنْ]{.ar}
in some respects.
For example,
consistent with what we learned in its use as a connected noun,
the question noun
[أَيّ]{.ar}
is a fully-flexible noun
and can be used indiscriminately for both intelligent and non-intelligent beings.

Also, 
[أَيّ]{.ar}
is typically the ;mudaf; in an ;idafa;.
When
[أَيّ]{.ar}
is a connected noun, then its ;mudafil; is usually definite.
But when
[أَيّ]{.ar}
is a question noun, then its ;mudafil; may be either definite or indefinite.

### [أَيّ]{.ar} with a definite ;mudafil;

When the ;mudafil; of 
[أَيّ]{.ar}
is a definite noun, the ;idafa; has the meaning "which [one] of".
For example,

[فَأَيَّ آيَاتِ ٱللَّهِ تُنكِرُونَ]{.ar}
[<https://quran.com/40:81>]{.aside}  
"So which of the signs of Allāh do you deny?"

[أَيُّ الأَعْمَالِ أَفْضَلُ]{.ar}
[<https://sunnah.com/abudawud:1449>]{.aside}  
"Which of the deeds is best?"

[فَأَيُّ الْفَرِيقَيْنِ أَحَقُّ بِالْأَمْنِ]{.ar}
[<https://quran.com/6/81>]{.aside}  
"So which of the two parties has more right to security"

[مِنْ أَيِّ أَيَّامِ الشَّهْرِ كَانَ يَصُومُ]{.ar}
[<https://sunnah.com/muslim:1160>]{.aside}  
"From which of the days of the month would he fast?"

As in the examples above, the ;mudafil; in such a case is typically a plural or a dual.
If the ;mudafil; is a definite singular noun, then there is an implied partitive meaning,
i.e. "which part of".^[Wright, vol.\ ii, §87, p.\ 220A]
For example,

<!--
[أَيُّ ٱلرَّجُلِ أَحْسَنُ؟]{.ar}
"Which (aspect or feature) of the man is most handsome?"
-->

[فِي أَيِّ طَعَامِهِ يُبَارَكُ لَهُ]{.ar}
[<https://sunnah.com/abudawud:3845>]{.aside}  
"in which (part) of his food is the blessing"

[مِنْ أَيِّ الْمَالِ]{.ar}
[<https://sunnah.com/abudawud:4063>]{.aside}  
"From which (category) of wealth?"

However, if the noun is of generic definiteness then the partitive aspect indicates one out of the set that constitutes the generic type. In English the plural is often used to signify the generic type.
For example the generic type [ٱلْعَمَل]{.ar} "the deed" can be translated in English as "deeds".
So [أَيُّ ٱلْعَمَلِ]{.ar} means "which one from the generic type 'deeds'" or simply "which deed".
Examples:

[أَيُّ الْعَمَلِ أَحَبُّ إِلَى اللهِ عَزَّ وَجَلَّ؟]{.ar}
[<https://sunnah.com/adab:1>]{.aside}  
"Which deed is most beloved to [_allAh]{.trn2}?"

[أَيُّ الدُّعَاءِ أَفْضَلُ]{.ar}
[<https://sunnah.com/adab:637>]{.aside}  
"Which supplication is best?"

[أَيُّ الذَّنْبِ أَعْظَمُ عِنْدَ اللَّهِ]{.ar}
[<https://sunnah.com/bukhari:4477>]{.aside}  
"Which deed is most enormous in the sight of [_allAh]{.trn2}?"

### [أَيّ]{.ar} with a indefinite ;mudafil;

When the ;mudafil; of 
[أَيّ]{.ar}
is a indefinite noun, the ;idafa; has the meaning "which" without "of".
For example,

[أَيَّ شَىْءٍ كُنْتَ تَصْنَعُ]{.ar}
[<https://sunnah.com/ibnmajah:2606>]{.aside}  
"Which thing would you do?"

[أَيَّ شَىْءٍ نَشْتَهِي]{.ar}
[<https://sunnah.com/muslim:1887>]{.aside}  
"What thing shall we desire?"

[أَيُّ لَيْلَةٍ لَيْلَةُ الْقَدْرِ]{.ar}
[<https://sunnah.com/tirmidhi:3513>]{.aside}  
"Which night is the night of Decree"

If the ;mudafil; is a dual or plural indefinite then then inquiry is about the complete number, not just one of them.
For example:

[أَيُّ رِجَالٍ؟]{.ar}
[Wright, vol.\ ii, §87, p.\ 220A]{.aside}  
"Which men?"

[أَيُّ رَجُلَيْنِ؟]{.ar}
[Wright, vol.\ ii, §87, p.\ 220A]{.aside}  
"Which two men?"

### Matching the rest of the question sentence with [أَيّ]{.ar}

[أَيّ]{.ar}
itself, like
[مَا]{.ar}
and
[مَنْ]{.ar},
is singular masculine.
For the purpose of
matching the rest of the question sentence with [أَيّ]{.ar},
either it can match the singular masculine to match with the word
[أَيّ]{.ar},
or 
it can match the gender and number of what
[أَيّ]{.ar}
refers to.
For example,

[أَيُّ أَزْوَاجِ النَّبِيِّ صلى الله عليه وسلم اسْتَعَاذَتْ مِنْهُ]{.ar}
[<https://sunnah.com/bukhari:5254>]{.aside}  
Which of the wives of the Prophet sought refuge (fwith [_allAh]{.trn2}) from him?  
([اسْتَعَاذَتْ]{.ar} is a feminine verb to match the feminine "wife".)

[فَأَيُّ نِسَاءِ رَسُولِ اللَّهِ صلى الله عليه وسلم كَانَ أَحْظَى عِنْدَهُ مِنِّي]{.ar}
[<https://sunnah.com/muslim:1423>]{.aside}  
"So which of the women of the Prophet was dearer to him than I?"  
([كَانَ]{.ar} is a masculine verb to match masculine [أَيّ]{.ar}.)

### [أَيّ]{.ar} standalone without a ;mudafil;

Occasionally, [أَيّ]{.ar} is used without a ;mudafil;.
It is then, technically, indefininte.
However, the meaning of an ;idafa; is still implicit.
This may be when [أَيّ]{.ar} has already been used once with an an ;idafa;,
and subsequent uses of [أَيّ]{.ar} are restricted to the previously mentioned ;idafa;.
For example,

[أَيُّ الْعَمَلِ أَحَبُّ إِلَى اللهِ عَزَّ وَجَلَّ؟ قَالَ الصَّلاَةُ عَلَى وَقْتِهَا، قُلْتُ ثُمَّ أَيٌّ؟]{.ar}
[<https://sunnah.com/adab:1>]{.aside}  
"'Which deed is most beloved to [_allAh]{.trn2}?' He replied, 'Prayer at its proper time.' I said, 'Then which?'"

See also section\ ... below, where [أَيّ]{.ar} is used standalone in a response.

### [أَيّ]{.ar} annexed to multiple ;mudafil;s

One [أَيّ]{.ar} may be annexed to multiple ;mudafil;s separated by [وَ]{.ar} "and".
For example,

[أَيُّ زِرَاعَةِ ٱلْفَاكِهَةِ وَزِرَاعَةِ ٱلْقُطْنِ أَرْبَحُ؟]{.ar}
[[النحو الوافي]{.ar} 3/107]{.aside}  
"Which one of the agriculture of fruit, and the agriculture of cotton is more profitable?"

In such a case, it is optional to have one
[أَيّ]{.ar}
or to repeat it.
So we could also say, for the same meaning:

[أَيُّ زِرَاعَةِ ٱلْفَاكِهَةِ وَأَيُّ زِرَاعَةِ ٱلْقُطْنِ أَرْبَحُ؟]{.ar}

However, if one of the ;mudafil;s is an attached pronoun 
<!--for the speaker [ي]{.ar},-->
then repeating
[أَيّ]{.ar}
is mandatory.^[Wright, vol.\ ii §87, p.\ 220B]
Example:

[أَيِّي وَأَيُّكَ أَعْلَمُ؟]{.ar}  
"Which one of you and me is more knowledgeable?"

[أَيِّي وَأَيُّكَ]{.ar} is equivalent to [أَيُّنَا]{.ar} but it spells out the two options to choose from.

## The question sentence within another sentence^[[التعليق]{.ar}. See [[معاني النحو (ظن وأخواتها) ٢/٣٧]{.ar}](https://shamela.ws/book/17801/420#p1); [[النحو الوافي ٢/٢٧]{.ar}](https://shamela.ws/book/10641/758#p1); Howell, part\ II, book\ 5, §444, pp.\ 155--165.]

TODO

## Usage of question nouns in quoting and standalone^[[الحكاية]{.ar}. See Wright, vol.\ i., §352--353, pp.\ 275B--276B, vol.\ ii, §170, p.\ 313]

TODO

## Differentiating question words from their other functions

Many of the question words 
([أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.)
also have other functions.
For example,
in chapter\ \@ref(the-connected-nouns) we learned that [مَنْ]{.ar}, [مَا]{.ar}, and [أَيّ]{.ar} are also connected nouns.
Many of the question nouns can also be used as _conditional nouns_ that we will study in chapter\ \@ref(...), if [_allAh]{.trn2} wills.

In this section, we will discuss briefly how to determine when words like
[أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.
are question words, and when they could have one of their other functions.

The basic principle regarding a question sentence is that it is to be treated as one unit. 
A word from within a question sentence is not, individually, affected by anything outside the question.
Let's try to understand this using an example.

Consider the following sentence:

[ٱِسْأَلْ أَيُّهُمْ قَامَ]{.ar}  
[EisEal Eayyuhum qAm]{.trn}  
"Ask: 'Which of them stood?'"

The speaker is commanding the addressed person to ask a group of people the question: 
"Which of them stood".

The question sentence is
[أَيُّهُمْ قَامَ]{.ar}
[Eayyuhum qAm]{.trn}
"Which of them stood".
This entire sentence is considered the ;mafulb; of the verb of command [ٱسْأَلْ]{.ar} "ask!".
The question noun [أَيُّ]{.ar} [Eayyu]{.trn} is in the u-state because it is the ;mubtada; of the question sentence.
It does not become [أَيَّ]{.ar} [Eayya]{.trn} in the a-state because it is not, by itself, the ;mafulb; of 
[ٱسْأَلْ]{.ar}.
Rather, as we have just stated, the entire question sentence is the ;mafulb;.
But because the ;mafulb; is a sentence, and not an individual word, it does not indicate its state using, for example, an ;amark; [◌َ]{.ar}.

Now, let's modify the example. Consider now this sentence:

[ٱِسْأَلْ أَيَّهُمْ قَامَ]{.ar}  
[EisEal Eayyahum qAm]{.trn}  
Ask the one of them who stood!

Now, the noun [أَيَّ]{.ar} is in the a-state because it (individually) is the ;mafulb; of the verb of command 
[ٱسْأَلْ]{.ar}.
The speaker is now commanding the addressed person to ask (something) of only the person who stood, out of a group of people. The rest of the people are not to be asked.
Because the noun 
[أَيَّ]{.ar}
is individually affected by the preceding verb
[ٱسْأَلْ]{.ar}
it is now not a question noun, and must be one of the other functions that the word
[أَيّ]{.ar} can have.
As a matter of fact, it is here a connected noun, and the sentence following it:
[قَامَ]{.ar} "he stood" is its connector.

The other noteworthy point regarding questions
(besides their being considered one unit)
is that they may only be preceded 
either by a verb of knowledge, (like [عَلِمَ]{.ar}, [دَرىٰ]{.ar}, etc.)
or by an expression indicating that the question is being quoted.
We have already seen an example of the question being quoted in the example:

[ٱِسْأَلْ أَيُّهُمْ قَامَ]{.ar}  
"Ask: 'Which of them stood?'"

An example of a question being preceded by a verb of knowledge is:

[مَا عَلِمْتُ أَذَهَبَ أَمْ مَكَثَ]{.ar}  
I don't know whether he went or stayed.

Here the question sentence is: 
[أَذَهَبَ أَمْ مَكَثَ]{.ar}
"Did he go or did he stay?"

By the way, a question sentence may be part of a bigger question as well. For example:

[أَتَدْرِي أَيُّهُمْ فِي ٱلدَّارِ؟]{.ar}  
[EatadrI Eayyuhum fi -ddAr]{.trn}  
Do you know: which of them is in the house?

Note now the subtle difference in meaning if we change the state of [أَيّ]{.ar} in the above example from the u-state to the a-state:

[أَتَدْرِي أَيَّهُمْ فِي ٱلدَّارِ؟]{.ar}  
[EatadrI Eayyahum fi -ddAr]{.trn}  
Do you know the one of them who is in the house?

When [أَيّ]{.ar} was in the u-state it was a question noun. And the speaker was asking the addressed person if he could figure out who, from among the group of people, was in the house.

When [أَيّ]{.ar} is in the a-state it is now a connected noun.
The connector's link-back pronoun is omitted (as is permissible in this case, see section\ \@ref(...)). With the link-back pronoun restored, the sentence is
[أَتَدْرِي أَيَّهُمْ هُوَ فِي ٱلدَّارِ؟]{.ar}
And the speaker is asking the addressed person if he is familiar with the person who is in the house.
Now he is not asking the addressed person to identify him, but rather if knows him as a person.

This difference is apparent with 
[أَيّ]{.ar} 
because it is a flexible noun whose state is indicated by the vowel mark at its end.
The same occurs in the other question nouns that are also connected nouns:
[مَا]{.ar}, and [مَنْ]{.ar}
but it won't often be as apparent because they are rigid nouns.

As a final note, sometimes, one of the words like 
[أَ]{.ar}, [مَنْ]{.ar}, [مَا]{.ar}, [كَيْفَ]{.ar}, etc.
may be preceded by parts of a sentence that are neither quoting, nor a verb of knowledge.
Here we can be sure that the word is not a question word
and
must be one of its other functions. However,
it still may not be easy to figure out what that other function is.
Nevertheless, the meaning of the sentence can still usually be gleaned.
For example:

[فَلْتَدْخُلْ مِنْ أَيِّ أَبْوَابِ الْجَنَّةِ شَاءَتْ]{.ar}  
"then let her enter from whichever of the doors of paradise she wishes."[^question-vs-other-functions]

