# Narrations, quotes and humor

## Narrations

::: {.aralt}
عَنْ عَبْدِ الرَّحْمَنِ بْنِ عَوْفٍ، قَالَ سَمِعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ قَالَ اللَّهُ أَنَا الرَّحْمَنُ وَهِيَ الرَّحِمُ شَقَقْتُ لَهَا اسْمًا مِنَ اسْمِي مَنْ وَصَلَهَا وَصَلْتُهُ وَمَنْ قَطَعَهَا بَتَتُّهُ
:::

[@https://sunnah.com/abudawud:1694@]{.citex}

---

::: {.aralt}
عَنْ عَدِيِّ بْنِ حَاتِمٍ أَنَّ رَجُلاً خَطَبَ عِنْدَ النَّبِيِّ صلى الله عليه وسلم فَقَالَ مَنْ يُطِعِ اللَّهَ وَرَسُولَهُ فَقَدْ رَشِدَ وَمَنْ يَعْصِهِمَا فَقَدْ غَوَى  فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم بِئْسَ الْخَطِيبُ أَنْتَ قُلْ وَمَنْ يَعْصِ اللَّهَ وَرَسُولَهُ قَالَ ابْنُ نُمَيْرٍ فَقَدْ غَوِيَ
:::

[@https://sunnah.com/muslim:870@]{.citex}

---

::: {.aralt}
حَدَّثَنَا يَحْيَى عَنْ أَجْلَحَ قَالَ حَدَّثَنَا يَزِيدُ بْنُ الْأَصَمِّ عَنِ ابْنِ عَبَّاسٍ قَالَ
جَاءَ رَجُلٌ إِلَى النَّبِيِّ ﷺ يُرَاجِعُهُ الْكَلَامَ فَقَالَ مَا شَاءَ اللهُ وَشِئْتَ فَقَالَ جَعَلْتَنِي لِلَّهِ عَدْلًا مَا شَاءَ اللهُ وَحْدَهُ
:::

[<https://hadithunlocked.com/ahmad:3247>]{.citex}

---

::: {.aralt}
عَنِ ابْنِ شِهَابٍ أَنَّ أَنَسَ بْنَ مَالِكٍ رَضِيَ اللَّهُ عَنْهُ أَخْبَرَهُ أَنَّهُ سَمِعَ عُمَرَ بْنَ الْخَطَّابِ رَضِيَ اللَّهُ عَنْهُ يَقُولُ {فَأَنْبَتْنَا فِيهَا حَبًّا وَعِنَبًا وَقَضْبًا وَزَيْتُونًا وَنَخْلًا وَحَدَائِقَ غُلْبًا وَفَاكِهَةً وَأَبًّا} [عبس: ٢٨] قَالَ فَكُلُّ هَذَا قَدْ عَرَفْنَاهُ فَمَا الْأَبُّ ثُمَّ نَقَضَ عَصًا كَانَتْ فِي يَدِهِ فَقَالَ هَذَا لَعَمْرُ اللَّهَ التَّكَلُّفُ اتَّبِعُوا مَا تَبَيَّنَ لَكُمْ مِنْ هَذَا الْكِتَابِ هَذَا حَدِيثٌ صَحِيحٌ عَلَى شَرْطِ الشَّيْخَيْنِ وَلَمْ يُخَرِّجَاهُ

[التعليق - من تلخيص الذهبي]٣٨٩٧ - على شرط البخاري ومسلم
:::

[[[مستدرك الحاكم]{.ar} :3897](https://shamela.ws/book/2266/4092)]{.citex}

---

::: {.aralt}
عن سعيد بن جُبير عن ابن عباس قال بعث ربُّ العزة مَلكَ الموت فأخذ من أديم الأرض من عذْبها ومالحها فخلق منه آدم ومن ثَمَّ سُمي آدم لأنه خُلق من أديم الأرض
:::

[@https://tafsir.app/tabari/2/31@]{.citex}

---

::: {.aralt}
وعن أبي عبيد حدثني يحيى بن سعيد عن سفيان عن إبراهيم بن المهاجر عن مجاهد عن ابن عباس قال كنت لا أدري ما «فاطر السموات» (١) حتى أتاني أعرابيان يختصمان في بئر فقال أحدهما: أنا فطرتها أي ابتدأتها
:::

[[[شعب الإيمان للبيهقي (ط الرشد)]{.ar} 3/212](https://shamela.ws/book/10660/1369)]{.citex}

(١) [ٱلۡحَمۡدُ لِلَّهِ فَاطِرِ ٱلسَّمَـٰوَ ٰ⁠تِ وَٱلۡأَرۡضِ جَاعِلِ ٱلۡمَلَـٰۤىِٕكَةِ رُسُلًا أُو۟لِیۤ أَجۡنِحَةࣲ مَّثۡنَىٰ وَثُلَـٰثَ وَرُبَـٰعَۚ یَزِیدُ فِی ٱلۡخَلۡقِ مَا یَشَاۤءُۚ إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَیۡءࣲ قَدِیرࣱ]{.quran}
[@https://quran.com/35/1@]{.citex}

---

::: {.aralt}
قال الأصمعي: قرأت هذه الآية (١)، وإِلى جنبي أعرابيٌ، فقلت: والله غفور رحيم، سهواً، فقال الأعرابي: كلام مَن هذا؟ قلت: كلام الله. قال: أعد فأعدت: والله غفور رحيم، فقال: ليس هذا كلام الله، فتنبهت، فقلت: وَاللَّهُ عَزِيزٌ حَكِيمٌ. فقال:

أصبت، هذا كلام الله. فقلت له: أتقرأ القرآن؟ قال: لا. قلت: فمن أين علمت أني أخطأت؟ فقال: يا هذا عزَّ فحكم فقطع، ولو غفر ورحم لما قطع.
:::

[[[زاد المسير في علم التفسير لابن الجوزي]{.ar} 1/546](https://shamela.ws/book/23619/539)]{.citex}

(١) [وَٱلسَّارِقُ وَٱلسَّارِقَةُ فَٱقۡطَعُوۤا۟ أَیۡدِیَهُمَا جَزَاۤءَۢ بِمَا كَسَبَا نَكَـٰلࣰا مِّنَ ٱللَّهِۗ وَٱللَّهُ عَزِیزٌ حَكِیمࣱ]{.quran}
[@https://quran.com/5/38@]{.citex}


---

::: {.aralt}
فقال أبو حاتم: لا تعجبون من هذا، أخبرني الأصمعي أن معتوها جاء إلى أبي عمرو بن العلاء فقال: يا أبا عمرو، لم سميت الخيل خيلا؟ فبقى أبو عمرو ليس عنده فيه جواب. فقال: لا أدري. فقال: لكني أدري. فقال: علمنا نعلم. قال: لاختيالها في المشي. فقال أبو عمرو لأصحابه بعد ما ولى المجنون: اكتبوا الحكمة وارووها ولو عن معتوه.
:::

[[[مجالس العلماء للزجاجي]{.ar} 187](https://shamela.ws/book/26676/186)]{.citex}

---

::: {.aralt}
وَأخْبرنَا أَبُو حَاتِم عَن الْأَصْمَعِي قَالَ: قَالَ أَبُو عَمْرو بن الْعَلَاء: سَمِعت أَعْرَابِيًا يَمَانِيا يَقُول: فلَان لغوب جَاءَتْهُ كتابي فاحتقرها. فَقلت: يَقُول: جَاءَتْهُ كتابي فَقَالَ: أَلَيْسَ بِصَحِيفَة؟
:::

[[[جمهرة اللغة لابن دريد]{.ar} 1/370](https://shamela.ws/book/7032/331)]{.citex}

---

## Quotes

::: {.aralt}
وكان المازني يقول:

من أراد أن يعمل كبيرًا في النحو بعد كتاب سيبويه فليستحي.
:::

[[[أخبار النحويين البصريين للسيرافي]{.aralt} 40](https://shamela.ws/book/26338/31)]{.citex}

---

::: {.aralt}
وذكر بعض شيوخنا أن الخليل بن أحمد رحمه الله، سئل عن العلل التي يعتل بها في النحو، فقيل له: عن العرب أخذتها أم اخترعتها من نفسك؟ فقال:

إن العرب نطقت على سجيتها وطباعها. وعرفت مواقع كلامها، وقام في عقولها علله، وإن لم يُنقل ذلك عنها، واعتللت أنا بما عندي أنه علة لما عللته منه. فإن أكن أصبت العلة فهو الذي التمست. وإن تكن هناك علة له فمثلي في ذلك مثل رجل حكيم دخل داراً محكمة البناء؛ عجيبة النظم والأقسام؛ وقد صحت عنده حكمة بانيها، بالخبر الصادق أو بالبراهين الواضحة والحجج اللائحة، فكلما وقف هذا الرجل في الدار على شيء منها قال: إنما فعل هذا هكذا لعلة كذا وكذا، ولسبب كذا وكذا. سنحت له وخطرت بباله محتملة لذلك، فجائز أن يكون الحكيم الباني للدار فعل ذلك للعلة التي ذكرها هذا الذي دخل الدار، وجائز أن يكون فعله لغير تلك العلة، إلا أن ذلك مما ذكره هذا الرجل محتمل أن يكون علة لذلك. فإن سنح لغيري علة لما عللته من النحو هو أليق مما ذكرته بالمعاول فليأت بها.
:::

[[[الإيضاح في علل النحو للزجاجي]{.aralt} 65](https://shamela.ws/book/143170/25#p1)]{.citex}

---

::: {.aralt}
وقال الفراء أموت وفي نفسي شيء من حتى
:::

[[[وفيات الأعيان لابن خلكان]{.aralt} 6/180](https://shamela.ws/book/1000/2600)]{.citex}

---

::: {.aralt}
ويقال ما زال النحو مجنونا حتى عقله ابن السراج بأصوله
:::

[[[معجم الأدباء للحمودي]{.aralt} 6/2535](https://shamela.ws/book/9788/2532)]{.citex}

---


<!--
::: {.aralt}
> النحو العربي كله حاشية على كتاب سيبويه.
:::

[Attributed to Kees Versteegh in [Dr. Ramzi Baalbaki - Foundations of the Arabic grammatical theory](https://www.youtube.com/watch?v=YJeYKqKr1_Y)]{.citex}
-->

> Without exaggeration one could say that the entire linguistic tradition in Arabic is nothing but a huge commentary on the _[#kitAb #sIbawayhi]{.trn2}_.

[Kees Versteegh, _Landmarks in linguistic thought III: The Arabic linguistic tradition_ 39]{.citex}

---

::: {.aralt}
النحو والله جاف، لكن هذا «التقدير» والله روح النحو، وقلبه النابض.
:::

[[[محاضرة “التّقدير النَّحْويّ بين الواقع والتّقعيد” لـ أ.د. رياض الخوّام]{.ar}](https://www.youtube.com/watch?v=4ypfXSOZaDU)]{.citex}

---

## Humor

::: {.aralt}
لِمَ ضرب زيد عمرًا؟  
لأنه سرق واو داود.
:::

---

::: {.aralt}
ترنو بِطرف فاتر فاتن ... أَضْعَف من حجَّة نحوي
:::

[[[يتيمة الدهر للثعالبي]{.aralt} 3/469](https://shamela.ws/book/6743/1462)]{.citex}

---

::: {.aralt}
اضرب أيهم أفضل
:::

[[@sibawayhi@ 2/399](https://shamela.ws/book/23018/834)]{.citex}

---

::: {.aralt}
يعجبني أيهم ضربته في داره
:::

[[@ibn_aqil_alfiyyah@ 1/168](https://shamela.ws/book/9904/167)]{.citex}

---

::: {.aralt}
ومثله ما حكي أن بعض الفقراء
وقف على باب نحوي فقرعه فقال النحوي من بالباب فقال سائل فقال ينصرف فقال اسمي أحمد فقال النحوي لغلامه أعط سيبويه كسرة.
:::

[[[ثمرات الأوراق في المحاضرات لابن حجة الحموي]{.aralt} 1/40](https://shamela.ws/book/11056/39#p1)]{.citex}

---

::: {.aralt}
وكان لبعضهم ولد نحوي يتقعر في كلامه، فاعتل أبوه علة شديدة أشرف منها على الموت، فاجتمع عليه أولاده، وقالوا له: ندعو لك فلانا أخانا، قال: لا إن جاءني قتلني، فقالوا: نحن نوصيه أن لا يتكلم، فدعوه، فلما دخل عليه قال له يا أبت: قل لا إله إلا الله تدخل بها الجنة وتفوز من النار، يا أبت: والله ما أشغلني عنك إلا فلان، فإنه دعاني بالأمس، فأهرس وأعدس واستبذج وسكبج وطهبج وأفرج ودجج وأبصل وأمضر ولوزج وافلوزج فصاح أبوه غمضوني، فقد سبق [أخوكم] ملك الموت إلى قبض روحي.
:::

[[[المستطرف في كل فن مستظرف للأبشيهي]{.ar} 475](https://shamela.ws/book/23802/470)]{.citex}

---

::: {.aralt}
ووقع نحوي في كنيف، فجاء كناس ليخرجه، فصاح به الكناس ليعلم أهو حي أم لا، فقال له النحوي: أطلب لي حبلا دقيقا وشدني شدا وثيقا واجذبني جذبا رفيقا، فقال الكناس: [امرأتي] طالق إن أخرجتك منه، ثم تركه وانصرف.
:::

[[[المستطرف في كل فن مستظرف للأبشيهي]{.ar} 475](https://shamela.ws/book/23802/470)]{.citex}

---


::: {.aralt}
حدثنا أبو طاهر، قال: حدثنا وكيع، قال: حدثني محمد بن خلّاد، قال: ثنا الوليد بن هشام القَحْذَمِيُّ، قال:

دخل خالدُ بنُ صَفْوَانَ الحَمَّامَ وفيه رَجُلٌ مَعَ ابْنِهِ، فأرَادَ أنْ يُعَرِّفَ خالدًا ما عِنْدَهُ من البَيَان فقال: يا بُنَيّ، ابْدَأْ بيداك ورجلاك، ثم التفت إلى خَالِدٍ فقال: يا أبا  صَفْوَانَ، هذا كَلامٌ قَدْ ذَهَبَ أَهْلُهُ. قال: هذا كلامٌ ما خَلَقَ اللَهُ له أهْلًا قَطُّ.
:::

[[[أخبار في النحو لأبي طاهر بن أبي هاشم]{.ar} 49](https://shamela.ws/book/857/65)]{.citex}

---

::: {.aralt}
ركب نحويّ سفينة فقال للملّاح: أتعرف النحو؟ قال: لا، قال: ذهب نصف عمرك. فهاجت الريح واضطربت السفينة فقال له الملاح: أتعرف السباحة؟ قال لا، قال: ذهب كل عمرك.
:::

[[[روض الأخيار المنتخب من ربيع الأبرار للأماسي]{.ar} 392](https://shamela.ws/book/10512/388)]{.citex}

---

