# The ;sifah_mush;

## Introduction

The ;sifah_mush; is a ;mushtaqq; noun.
It is the quintessential ;sifah; signifying a relatively stable and unchanging meaning.
[حَسَن]{.ar} [handsome, good]{.trans} is an example of a ;sifah_mush;.

The ;sifah_mush; is called such because it shares some characteristics with the ;ism_fail;.
The ;ism_fail; is the closest of the ;mushtaqq; nouns to the verb.
We saw in chapter\ (ref) that it can govern in a verb-like manner and even be used in place of a verb.

The ;sifah_mush;, although not as close to the verb as the ;ism_fail;,
can also govern in a manner which is similar (but not quite exactly the same) as the governing of the ;ism_fail;.
In this chapter, we will explore its significance and its ability to govern in a verb-like manner.

## The forms of the ;sifah_mush;

The ;sifah_mush; comes in various forms.
We will list the most common of them^[The following list is taken mostly from @nahw_wafi@ 3/285ff]:

<!--
#### The ;sifah_mush; from [فَعِلَ]{.ar} verbs {.unnumbered}
-->

<!--
When the ;madi; verb, from which the ;sifah_mush; is derived,
is on the pattern
[فَعِلَ]{.ar},
and the meaning signified by the ;ism_fail; is one that changes relatively quickly,
but is frequently reoccurring,
like
happiness or sadness,
then the ;sifah_mush; is often on the pattern [فَعِل]{.ar} for the masculine and [فَعِلَة]{.ar} for the feminine.
Examples:
-->

#### #;sifah_mush;'s on the pattern [فَعِل]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[فَرِحَ]{.ar} |[to be joyous]{.trans}                |[فَرِح]{.ar}|[joyous]{.trans} |
|[حَزِنَ]{.ar} |[to be sad]{.trans}                   |[حَزِن]{.ar}|[sad]{.trans} |
|[حَذِرَ]{.ar} |[to be precautious]{.trans}           |[حَذِر]{.ar}|[precautious]{.trans} |
|[تَعِبَ]{.ar} |[to be tired]{.trans}                 |[تَعِب]{.ar}|[tired]{.trans} |


#### #;sifah_mush;'s on the pattern [فَعْلَان]{.ar} {.unnumbered}

Feminine: usually [فَعْلَى]{.ar}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[عَطِشَ]{.ar} |[to be thirsty]{.trans}               |[عَطْشَان]{.ar}|[thirsty]{.trans} |
|[ظَمِئَ]{.ar} |[to be thirsty]{.trans}               |[ظَمْآن]{.ar} |[thirsty]{.trans} |
|[شَبِعِ]{.ar} |[to be sated]{.trans}                 |[شَبْعَان]{.ar}|[sated]{.trans} |
|[يَقِظَ]{.ar} |[to be awake]{.trans}                 |[يَقْظَان]{.ar}|[awake]{.trans} |

#### #;sifah_mush;'s on the pattern [أَفْعَل]{.ar} {.unnumbered}

Feminine: [فَعْلَاء]{.ar}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[حَمِرَ]{.ar}|[to be red]{.trans}       |[أَحْمَر]{.ar} |[red]{.trans}      |
|[خَضِرَ]{.ar}|[to be green]{.trans}     |[أَخْضَر]{.ar} |[green]{.trans}    |
|[عَرِجَ]{.ar}|[to be lame]{.trans}      |[أَعْرَج]{.ar} |[lame]{.trans}     |
|[حَوِرَ]{.ar}|[to be big-eyed]{.trans}  |[أَحْوَر]{.ar} |[big-eyed]{.trans} |

#### #;sifah_mush;'s on the pattern [فَعِيل]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[شَرُفَ]{.ar} |[to be noble]{.trans} |[شَرِيف]{.ar}|[noble]{.trans} |
|[قَبُحَ]{.ar} |[to be ugly]{.trans}  |[قَبِيح]{.ar}|[ugly]{.trans} |
|[بَخِلَ]{.ar} |[to be stingy]{.trans}|[بَخِيل]{.ar}|[stingy]{.trans} |

#### #;sifah_mush;'s on the pattern [فَعْل]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[صَعُبَ]{.ar} |[to be difficult]{.trans} |[صَعْب]{.ar}|[difficult]{.trans} |
|[ضَخْمَ]{.ar} |[to be large]{.trans}     |[ضَخْم]{.ar}|[large]{.trans} |

#### #;sifah_mush;'s on the pattern [فَعَال]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[جَبُنَ]{.ar} |[to be cowardly]{.trans} |[جَبَان]{.ar}|[cowardly]{.trans} |
|[حَصُنَ]{.ar} |[to be chaste]{.trans}   |[حَصَان]{.ar}|[chaste]{.trans} |

#### #;sifah_mush;'s on the pattern [فُعَال]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[شَجُعَ]{.ar} |[to be brave]{.trans} |[شُجَاع]{.ar}|[brave]{.trans} |
|[فَرُتَ]{.ar} |[to be sweet]{.trans} |[فُرَات]{.ar}|[sweet]{.trans} |

#### #;sifah_mush;'s on the pattern [فُعْل]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[صَلُبَ]{.ar} |[to be hard (rigid)]{.trans} |[صُلْب]{.ar}|[hard (rigid)]{.trans} |

#### #;sifah_mush;'s on the pattern [فِعْل]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[مَلُحَ]{.ar} |[to be salty]{.trans} |[مِلْح]{.ar}|[salty]{.trans} |

#### #;sifah_mush;'s on the pattern [فَيْعِل]{.ar} {.unnumbered}

| verb | meaning | ;sifah_mush; | meaning |
|:--|:----|:--|:----|
|[مَاتَ]{.ar} |[to die]{.trans} |[مَيِّت]{.ar}|[dead, dying]{.trans} |


<!--
### FINI

TODO: rework from @nahw_wafi@ 3/281

The ;ism_fail; has an incidental meaning (as the ;faa3il; of its verb).
For example, if we say

(@) [زَيْدٌ ضَارِبٌ]{.ar}  
    [Zayd is a beater]{.trans}

then the ;ism_fail; [ضَارِب]{.ar} [beater]{.trans} is applicable to a [زَيْدٌ]{.ar} only when he is associated with the action of beating.

On the other hand,
the ;sifah_mush;,
in general,
has a more stable and innate meaning.^[@su3ood_dameer_mustatir@ 160]

So if we say:

(@) [زَيْدٌ حَسَنٌ]{.ar}  
    [Zayd is handsome.]{.trans}

then the ;sifah_mush; [حَسَن]{.ar} [handsome]{.trans} is a constant quality that will (generally) always be applicable to a [زَيْدٌ]{.ar}.
-->

## The ;sifah_mush; as the governor of a ;mustatir; ;faa3il; pronoun

Just like the ;ism_fail;, the ;sifah_mush; will,
by default,
govern a ;mustatir; ;faa3il; pronoun.^[@su3ood_dameer_mustatir@ 161]
Consider the following examples:

(@) [مررت بامرأة حسنة]{.ar}
    [@su3ood_dameer_mustatir@ 161]{.citex}  
    [I passed by a handsome woman.]{.trans}  
    ([حسنة]{.ar} has a ;mustatir; ;faa3il; pronoun implicated as [هي]{.ar}.)

(@) [مررت برجلين حسنين]{.ar}
    [@su3ood_dameer_mustatir@ 161]{.citex}  
    [I passed by two handsome men.]{.trans}  
    ([حسنين]{.ar} has a ;mustatir; ;faa3il; pronoun [هما]{.ar}.)

## The ;sifah_mush; as the governor of a ;sababi; ;zaahir; ;faa3il;

TODO:
sifah should be valid for both genders if mismatch.
Also for ism_fail like murDi3.
Add forward reference to ism_fail chapter.
[[@nahw_wafi@ 3/303--304](https://shamela.ws/book/10641/1529#p1)]

Similar to the ;ism_fail;
the ;sifah_mush; can govern a ;zaahir; ;faa3il;.
So we can say:

(@) [مررت برجل حسن وجهه]{.ar}
    [@baseet_ibn_abi_rabee3@ 1077]{.citex}  

(@) [مررت برجلين حسن أبواهما]{.ar}
    [@baseet_ibn_abi_rabee3@ 1077]{.citex}  

(@) [مررت برجال حسن آباؤهم]{.ar}
    [@baseet_ibn_abi_rabee3@ 1077]{.citex}  

(@) [الرجال كريمة أمهاتهم]{.ar}

(@) [رأيت الرجالَ الكريمةَ أمهاتهم]{.ar}


Also similar to the ;ism_fail;,
when ;sifah_mush;'s ;faa3il; is a broken plural
(as in example () above [آباؤهم]{.ar}),
then the ;sifah_mush; is permitted, and preferred, to also be a broken plural.^[[@nahw_wafi@ 3/453–454](https://shamela.ws/book/10641/1679#p1); [fawzan_sharh_qatr 248](https://shamela.ws/book/2135/248#p1); [@sharh_qatr_alnada@ 288](https://shamela.ws/book/6970/263)]

So we can say:

(@) [مررت برجال حسانٍ آباؤهم]{.ar}
    [@baseet_ibn_abi_rabee3@ 1077]{.citex}  

(@) [هؤلاءِ زملاءُ كرامٌ آباؤهم]{.ar}
    [[@nahw_wafi@ 3/453](https://shamela.ws/book/10641/1679#p1)]{.citex}

But if the ;faa3il; of the ;sifah_mush; is a sound plural,
then it is preferred that the ;sifah_mush; remain singular.
Examples:

(@) [هؤلاء زملاءُ كريم والدوهم]{.ar}
    [[@nahw_wafi@ 3/454](https://shamela.ws/book/10641/1680#p1)]{.citex}

(@) [هؤلاء زميلات كريمة والداتهن]{.ar}
    [[@nahw_wafi@ 3/454](https://shamela.ws/book/10641/1680#p1)]{.citex}


By the way, when the ;sifah_mush; is a ;na3t;,
then instead of using a ;sababi; na3t
(as in examples () above),
we can use a sentence ;na3t;.
So instead of saying
[مررت برجل حسنٍ وجهه]{.ar},
we can say:

(@) [مررت برجل حسنٌ وجهه]{.ar}
    [@baseet_ibn_abi_rabee3@ 1076]{.citex}  

Now the ;na3t; is the sentence
[حسنٌ وجهُه]{.ar}
[handsome, his face is]{.trans}.
[حسن]{.ar} in this sentence is a fronted ;xabar;.

#### The ;sifah_mush; cannot govern a non-;sababi; ;zaahir; ;faa3il; {.unnumbered}

In section\ (ref) above,
we saw that an ;ism_fail; can govern a
non-;sababi; ;zaahir; ;faa3il;.
Unlike the ;ism_fail;
the ;sifah_mush; can only govern a ;sababi; ;zaahir; ;faa3il;.
So we cannot say:

(@) ;x; [مررت برجل حَسَنٍ عمرٌو في داره]{.ar}
    [@baseet_ibn_abi_rabee3@ 1075]{.citex}  
    [I passed a man [whom] [#eamr]{.trn2} was handsome in his house.]{.trans}  

## The ;sifah_mush; in a ;lafzi; ;idaafah;

Like the ;ism_fail;,
the ;sifah_mush; forms a ;lafzi; ;idaafah; with its governee.
In section\ (ref),
we learned that
the ;ism_fail; forms a ;lafzi; ;idaafah; between the ;ism_fail; and its semantic ;mafulb;.
The ;sifah_mush; is typically from an intransitive verb.
so it will not have a ;mafulb;.
Instead, it
forms a ;lafzi; ;idaafah; in two ways:

 i. A ;lafzi; ;idaafah; between the ;sifah_mush; and its semantic _;faa3il;_.
ii. A ;lafzi; ;idaafah; between the ;sifah_mush; and its ;tamyiz;.

### #;lafzi; ;idaafah; between the ;sifah_mush; and its semantic ;faa3il;

The ;sifah_mush; can form a
;lafzi; ;idaafah; between the ;sifah_mush; and its semantic ;faa3il;.
It does this by first transforming its ;faa3il; into a _;mafulb;-like_ governee.
Wil will explaing this process below:

Consider the sentence:

(@) [مررت برجل حسنٍ وجهُه]{.ar}
    [@baseet_ibn_abi_rabee3@ 1077]{.citex}

In this sentence,
the ;sifah_mush; has a definite ;sababi; ;faa3il;
[وجهه]{.ar}.
This sentence is transformed in the following manner^[@baseet_ibn_abi_rabee3@ 1080]:

#### First step of the transformation {.unnumbered}

Firstly, the base noun pronoun
[ه]{.ar}
in
[وجهه]{.ar}
is transferred to being a ;mustatir; ;faa3il; pronoun of the ;sifah_mush;
[حسن]{.ar}.

#### Second step of the transformation {.unnumbered}

Secondly,
[وجه]{.ar},
with its base noun pronoun
[ه]{.ar}
eliminated, is made into
[الوجه]{.ar}
to keep it definite
(to match [وجهه]{.ar} which was also definite).

Now that
the ;sifah_mush;
[حسن]{.ar}
already has a ;faa3il;
(its ;mustatir; ;faa3il; pronoun [هو]{.ar}),
the noun
[الوجه]{.ar}
cannot be its ;faa3il;.
So it is made into what we will call a
_;mafulb;-like_ governee.
So it is put into the ;astate; thus:
[الْوَجْهَ]{.ar}.

We call [الْوَجْهَ]{.ar} a ;mafulb;-like governee, and not a true ;mafulb; because, in meaning, it is still the ;faa3il; of the ;sifah_mush;
[حسن]{.ar}.
The ;sifah_mush;
[حسن]{.ar}
is derived from an intransitive verb
[حَسُنَ]{.ar}
which does not take a ;mafulb;.

With this transformation,
the sentence becomes:

(@) [مررت برجل حسنٍ الوجهَ]{.ar}
    [@baseet_ibn_abi_rabee3@ 1080]{.citex}

It is important to note that this transformation affects only the syntax of the sentence, but not its meaning.
The ;sifah_mush;
[حسن]{.ar}
is still describing a quality of [الوجه]{.ar},
not [رجل]{.ar}.

But now that [الوجه]{.ar} is not syntactically the ;faa3il; of the ;sifah_mush;,
the ;sifah_mush; match its syntactic referent [رجل]{.ar}
in gender and number,
not its semantic ;faa3il;
[الوجه]{.ar}.
So we will say:

(@) [مررت برجلين حسنين الوجهين]{.ar}

(@) [مررت برجالٍ حسانٍ الوجوهَ]{.ar}

(@) [مررت بمرأة حسنة الوجهَ]{.ar}

(@) [مررت بمرأتين حسنتين الوجهين]{.ar}

Remember, that it
[الوجه]{.ar}
were syntactically the ;faa3il;,
then we would have said instead:

(@) [مررت برجلين حسنين وجهاهما]{.ar}

(@) [مررت بمرأة حَسَنٍ وجهُهَا]{.ar}

etc.

The transformation that we have described above works exactly the same for definite ;sifah_mush;s.
So we will say:

(@) [مررت بالرجل الحسن الوجهَ]{.ar}

(@) [جاءت المرأتان الحسنتان الوجهين]{.ar}

etc.

#### Final step of the transformation {.unnumbered}

A sentence with a ;mafulb;-like governee,
like in example ()
[مررت برجل حسنٍ الوجهَ]{.ar}
above,
while grammatically correct, is rarely used in practice.^[@su3ood_dameer_mustatir@ 166]
The main purpose of the ;mafulb;-like governee is that it is used as a intermediate step for the final step of the transformation:
and that is into a ;lafzi; ;idaafah;^[@su3ood_dameer_mustatir@ 167]
This is done by converting the ;mafulb;-like governee into a syntactic ;mudafil;.

<!--
#### Transformation of ;faa3il; which is an ;mudaf; {.unnumbered}

As a sub-case of the above transformation, consider the example:

(@) [مررت برجل حسنٍ وجهُ أبيه]{.ar}

We can transform this sentence to:

(@) [مررت برجل حسنٍ وجهَ الأب]{.ar}
Similarly the sentence:

(@) [مررت بالمرأة الحسن وجهُ أمها]{.ar}

can be transformed to:

(@) [مررت بالمرأة الحسنة وجهَ الأم]{.ar}

We will revisit this sort of sentence when we discuss ;lafzi; ;idaafah; in section\ (ref) below.
–->

### With an indefinite ;astate; governee

Remember from section\ (ref),
that the ;tamyiz; is a ;astate; governee that specifies the scope of its governor.
So we can say, for example:

(@) [مررت برجل حسن وجهًا]{.ar}
    [@baseet_ibn_abi_rabee3@ 1080]{.citex}

(@) [جاءت المرأة الحسنة وجهًا]{.ar}

(@) [الزيدون حسنون وجوها]{.ar}
    [@abu_hayyan_tadhyeel@ 9/241]{.citex}  

The ;tamyiz; is thus very commonly used with the ;sifah_mush;.^[@su3ood_dameer_mustatir@ 167 citing @radiy_kafiyah@ 3/439]

### The word order of the ;sifah_mush; and its ;astate; ;governee;

Recall from section\ (ref) above that the ;astate; governee of a ;ism_fail; is permitted to precede its governing ;ism_fail; in word order.
So we can say:

(@) [زيد عمرا ضارب]{.ar}
    [@ibn_aqil_alfiyyah@ 3/143]{.citex}

But this is not permitted for the ;sifah_mush;.^ [@sirafi_sibawayhi@ 1/259; @ibn_aqil_alfiyyah@ 3/143]
So we cannot say:

(@) [زَيْدٌ الْوَجْهَ حَسَنٌ]{.ar}
    [@ibn_aqil_alfiyyah@ 3/143]{.citex}

## #;lazfi; ;idaafah; with the ;sifah_mush;

Remember from section\ (ref) that a ;lafzi; ;idaafah; is formed between a governing noun and its ;astate; governee.
<!--
It cannot be formed between a governing noun and its ;faa3il;.
So the following constructions,
which have a ;zaahir; ;sababi; ;faa3il;,
do not form a ;lafzi; ;idaafah;:

* Indefinite ;sifah_mush;: [حَسَنٌ وَجْهُهُ]{.ar}
* Definite ;sifah_mush;: [الْحَسَنُ وَجْهُهُ]{.ar}
-->
<!--
We have discussed the following constructions of a ;sifah_mush; with a ;astate; governee:
 
1. The ;sifah_mush; with a (definite) ;mafulb;-like governee 

   a. Indefinite ;sifah_mush;: [حَسَنٌ الْوَجْهَ]{.ar}
   b. Definite ;sifah_mush;: [الْحَسَنُ الْوَجْهَ]{.ar}

2. The ;sifah_mush; with an (indefinite) ;tamyiz; governee:

   a. Indefinite ;sifah_mush;: [حَسَنٌ وَجْهًا]{.ar}
   b. Definite ;sifah_mush;: [الْحَسَنُ وَجْهًا]{.ar}

Constructions 1a and 1b are both form a ;lafzi; ;idaafah;.^[@su3ood_dameer_mustatir@ 171]
In fact, the ;lafzi; ;idaafah; is the dominant form of usage for such constructions.
-->

Lets start with ;sifah_mush;s with their ;mafulb;-like governees:

* Indefinite ;sifah_mush;: [حَسَنٌ الْوَجْهَ]{.ar}
* Definite ;sifah_mush;: [الْحَسَنُ الْوَجْهَ]{.ar}

The
;astate; ;mafulb;-like governees
are converted into ;mudafil;s in the ;istate;:

* Indefinite ;sifah_mush;: [حَسَنُ الْوَجْهِ]{.ar}
* Definite ;sifah_mush;: [الْحَسَنُ الْوَجْهِ]{.ar}


Here are some examples using this ;lafzi; ;idaafah;:

(@sifah_mush_marartu_birajulin_hasanil_wajhi) [مررت برجل حسنِ الوجهِ]{.ar}
    [@baseet_ibn_abi_rabee3@ 1078, 1081]{.citex}

(@) [جاء الرجل الحسنُ الوجهِ]{.ar}

Note that, because [الوجه]{.ar} is a ;astate; governee, and not the ;faa3il;,
of the ;sifah_mush;, therefore, the ;sifah_mush; is feminized, dualized, or pluralized to match its referent, not [الوجه]{.ar}.
Examples:

(@) [هند حسنة الوجه]{.ar}
    [@radiy_kafiyah@ 3/439]{.citex}

(@) [الزيدان حسنا الوجهين]{.ar}
    [@radiy_kafiyah@ 3/439]{.citex}

(@) [الزيدون حسنو الوجوه]{.ar}
    [@radiy_kafiyah@ 3/439]{.citex}

## The ;sifah_mush; with a ;tamyiz;

Remember from section\ (ref),
that the ;tamyiz; is a ;astate; governee that specifies the scope of its governor.
As a verb-like noun,
the ;sifah_mush;
can govern a ;tamyiz;.
So we can say, for example:

(@) [مررت برجل حسن وجهًا]{.ar}
    [@baseet_ibn_abi_rabee3@ 1080]{.citex}

(@) [جاءت المرأة الحسنة وجهًا]{.ar}

(@) [الزيدون حسنون وجوها]{.ar}
    [@abu_hayyan_tadhyeel@ 9/241]{.citex}  

### #;lafzi; ;idaafah; of the ;sifah_mush; with a ;tamyiz;

As with the ;sifah_mush; that has a ;mafulb;-like governee,
the ;sifah_mush; with a ;tamyiz;
also can also form a
;lafzi; ;idaafah;.

So
[حَسَنٌ وَجْهًا]{.ar} will become:

(@) [حسنُ وجهٍ]{.ar}
    [@su3ood_dameer_mustatir@ 171]{.citex}

Again, the ;sifah_mush; will match its referent in gender and number.
So, for example, we will say:

(@) [هم حسنو وجوه]{.ar}
    [[@abu_hayyan_tadhyeel@ 9/227](https://shamela.ws/book/17116/3012)]{.citex}  

Unlike, the ;sifah_mush; with a ;mafulb;-like governee,
a ;sifah_mush; prefixed by [ال]{.ar} with a ;tamyiz; does not form a ;lafzi; ;idaafah;
This is because a definite ;mudaf; 
with an indefinite ;mudafil; is fundamentally inconsistent with an ;idaafah; construction.^[@su3ood_dameer_mustatir@ 169]{.citex}
So
[الْحَسَنُ وَجْهًا]{.ar}, 
however, does not
form a ;lafzi; ;idaafah;
to become:

(@) ;x; [الحسنةُ وجهٍ]{.ar}
    [@su3ood_dameer_mustatir@ 169]{.citex}

Finally,
whereas the ;sifah_mush; with its ;mafulb;-like governee
(e.g. [حَسَنُ الْوَجْهَ]{.ar})
is pretty much only used as an intermediate step to form a ;lafzi; ;idaafah;,
such is not the case for 
the
;sifah_mush; with a ;tamyiz;.
The
;sifah_mush; with a ;tamyiz;
can be used, as is, without converting it into a
;lafzi; ;idaafah;.^[@su3ood_dameer_mustatir@ 167 citing @radiy_kafiyah@ 3/439]


<!--
Construction 2a
[حَسَنٌ وَجْهًا]{.ar}
can also form a ;lafzi; ;idaafah;.^[@su3ood_dameer_mustatir@ 171]
So we can say:

(@) [زيد حسنُ وجهٍ]{.ar}

Construction 2b
[الْحَسَنُ وَجْهًا]{.ar}, 
however, does not
form a ;lafzi; ;idaafah;.^[@su3ood_dameer_mustatir@ 169]
So we cannot say:

(@) ;x; [جاءت المرأة الحسنةُ وجهٍ]{.ar}
-->

## The word order of the ;sifah_mush; and its ;astate; governee

Recall from section\ (ref) above that the ;astate; governee of a ;ism_fail; is permitted to precede its governing ;ism_fail; in word order.
So we can say:

(@) [زيد عمرا ضارب]{.ar}
    [@ibn_aqil_alfiyyah@ 3/143]{.citex}

But this is not permitted for the ;sifah_mush;.^ [@sirafi_sibawayhi@ 1/259; @ibn_aqil_alfiyyah@ 3/143]
So we cannot say:

(@) ;x; [زَيْدٌ الْوَجْهَ حَسَنٌ]{.ar}
    [@ibn_aqil_alfiyyah@ 3/143]{.citex}

Nor is the ;tamyiz; allowed to precede its governing ;sifah_mush;
(see section\ (ref)).
So we cannot say:

(@) ;x; [زيد وَجها حسن]{.ar}
    [[@muqtadab@ 4/164](https://shamela.ws/book/6965/1178)]{.citex}  


## Uncommon constructions of the ;sifah_mush;

There are some constructions of the ;sifah_mush;,
that are uncommonly found.
Some are disagreed upon with regard to their grammatical correctness.
Some grammarians allow some of them unconditionally, others by poetic license only, while others would disallow them.^[@su3ood_dameer_mustatir@ 162--170]{.citex}

We list these constructions here for compleness:

#### Governing a ;faa3il; {.unnumbered}

(@) [حَسَنٌ الْوَجْهُ]{.ar} [@su3ood_dameer_mustatir@ 162]{.citex}

(@) [الْحَسَنُ الْوَجْهُ]{.ar} [@su3ood_dameer_mustatir@ 162]{.citex}

(@) [حَسَنٌ وَجْهٌ]{.ar} [@su3ood_dameer_mustatir@ 163]{.citex}

(@) [الْحَسَنُ وَجْهٌ]{.ar} [@su3ood_dameer_mustatir@ 163]{.citex}

#### Governing a ;astate; governee {.unnumbered}

(@) [حَسَنٌ وَجْهَهُ]{.ar} [@su3ood_dameer_mustatir@ 166]{.citex}

(@) [الْحَسَنُ وَجْهَهُ]{.ar} [@su3ood_dameer_mustatir@ 166]{.citex}

#### In a ;lafzi; ;idaafah; {.unnumbered}

(@) [حَسَنُ وَجْهِهِ]{.ar} [@su3ood_dameer_mustatir@ 169]{.citex}

When the ;sifah_mush; is defined by [أل]{.ar}
and the semantic ;faa3il; is not defined by [أل]{.ar},
then a ;lafzi; ;idaafah;
is disallowed.^[@su3ood_dameer_mustatir@ 166]{.citex}
For example:

(@) ;x; [الْحَسَنُ وَجْهِهِ]{.ar} [@su3ood_dameer_mustatir@ 169]{.citex}

## #;lafzi; ;idaafah; to an ;idaafah;

It is possible for the ;faa3il; of a ;sifah_mush; to itself be in an ;idaafah;.
For example:

(@) [زَيْدٌ حَسَنٌ وَجْهُ أَبِيهِ]{.ar}

(@) [رَأَيْتُ الرَّجُلَ الطَّوِيلَةَ لِحْيَةُ أَبِيهِ]{.ar}

#;lafzi; ;idaafah;s can, in general, be formed from such constructions
after, of course, first transforming the ;faa3il;s into ;astate; governees.

But
when the ;sifah_mush; is defined by [أل]{.ar},
then a ;lafzi; ;idaafah; is only permitted,
if the ;mudafil; of semantic ;faa3il; also is defined by [أل]{.ar}.^[@ibn_aqil_alfiyyah@ 3/145--146]
Compare this with section\ (ref) for the ;ism_fail;.
Examples:

(@) ;v; [زَيْدٌ حَسَنُ وَجْهِ الْأَبِ]{.ar}

(@) ;v; [زَيْدٌ حَسَنُ وَجْهِ أَبٍ]{.ar}

(@) ;v; [زَيْدٌ حَسَنُ وَجْهِ أَبِيهِ]{.ar}

(@) ;v; [رَأَيْتُ الرَّجُلَ الطَّوِيلَ لِحْيَةِ الْأَبِ]{.ar}

(@) ;x; [رَأَيْتُ الرَّجُلَ الطَّوِيلَ لِحْيَةِ أَبٍ]{.ar}

(@) ;x; [رَأَيْتُ الرَّجُلَ الطَّوِيلَ لِحْيَةِ أَبِيهِ]{.ar}

<!--
## The ;sifah_mush; in the form of the ;ism_fail;

utheymeen

Form1: rare

Form 2+: always
e.g. muntaliq -al-lisaan

ism_fail is tied to an an event of the verb
sifah_mush is tied to an innate constant quality

sifah_mush can have meaning of ism_fail if there is a daleel that it is tied to an event:
- أرشيف منتدى الفصيح - سؤال لأهل العلم عاجل - المكتبة الشاملة الحديثة
-->

## Significance of the ;sifah_mush;

The ;sifah_mush; is typically derived from a stative verb.
A stative verb is one which,
rather than describing any process or action,
signifies that its ;faa3il; is in a particular state.
Futhermore, its ;faa3il; does not do any actual work or action that causes him to be in the state described by the ;sifah_mush;.


### Permanence of the meaning of the ;sifah_mush;

Some ;sifah_mush;s have a very permanent meaning. For example:

|;sifah_mush; | meaning |
|:---|:-----|
|[أَخْضَر]{.ar}  |[green]{.trans} |
|[أَعْرَج]{.ar}  |[lame]{.trans} |
|[شَرِيف]{.ar}  |[noble, highborn]{.trans} |
|[زَنِيم]{.ar}  |[ignoble, baseborn]{.trans} |

Others are fairly permanent but can change gradually.
For example:

|;sifah_mush; | meaning |
|:---|:-----|
|[جَمِيل]{.ar}|[beautiful]{.trans}|
|[قَبِيح]{.ar}|[ugly]{.trans}|

Others can change fairly quickly.
For example

|;sifah_mush; | meaning |
|:---|:-----|
|[جَوْعَان]{.ar} |[hungry]{.trans} |
|[فَرِح]{.ar}   |[joyous]{.trans} |
|[تَعِب]{.ar}   |[tired]{.trans} |

### Transitivity of the verb from which the ;ism_fail; is derived

The ;sifah_mush; is typically derived from intransitive verbs.
Rarely, we find a ;sifah_mush; which is derived from a transitive verb.
For example:

|;sifah_mush; | meaning |
|:---|:-----|
|[ثَكْلَان]{.ar}|[bereft (of child)|


### #;sifah_mush;s whose meaning aligns with the ;maful;

Most of the time, the ;sifah_mush; aligns in meaning with the ;faa3il; of the verb from which it is derived.
For example,
[حَسَن]{.ar} [handsome]{.trans} aligns in meaning with the ;faa3il; of the verb [حَسُنَ]{.ar} [to be handsome]{.trans}.
Occasionally, however,
the ;sifah_mush; aligns in meaning with the ;maful; of its verb.
Examples:

|;sifah_mush;|meaning | verb |
|:--|:----|:----|
|[حَمِيد]{.ar}| [praiseworthy]{.trans}             | [حَمِدَ]{.ar} [to praise (s.o.)]{.trans}|
|[ذَمِيم]{.ar}| [blameworthy]{.trans}              | [ذَمَّ]{.ar}  [to blame (s.o.)]{.trans}|
|[مَنِيع]{.ar}| [inaccessible, impregnable]{.trans}| [مَنَعَ]{.ar} [to prevent (s.o., s.th.)]{.trans}|

## The ;ism_fail;-crossover-to-;sifah_mush;

Whereas ;sifah_mush; are typically derived from stative verbs,
;ism_fail;s are derived from both intransitive verbs
(like [قَائِم]{.ar} from [قَامَ]{.ar} [to stand]{.trans}),
and transitive verbs
(like [ضَارِب]{.ar} from [ضَرَبَ]{.ar} [to beat]{.trans}).
Furthermore, when a verb has a stative meaning,
then,
as we learned in section\ (ref)
its ;ism_fail; is often not in common usage.
Instead, a ;sifah_mush; will often exist for the stative verb and the ;sifah_mush; will be generally used instead.
For example,
the ;ism_fail; 
[كَارِم]{.ar}
of the stative verb
[كَرُمَ]{.ar} [to be noble, generous]{.trans}
is rarely used.
Instead, the ;sifah_mush;
[كَرِيم]{.ar} [noble, generous]{.trans}
will generally be used instead.
But, as we also learned,
[كَارِم]{.ar}
could be used when temporary meaning is intended.

The above is the general rule for ;ism_fail;s of stative verbs.
However, there are some stative verbs, for which the ;ism_fail; is commonly used,
but only after it crosses over to become a ;sifah_mush;.
As with
the ;ism_fail;-crossover-to-;substantive;
there are two categories of ;ism_fail;-crossover-to-;sifah_mush;s:

 i. The lexical ;ism_fail;-crossover-to-;sifah_mush;
ii. The ad\ hoc ;ism_fail;-crossover-to-;sifah_mush;

### The lexical ;ism_fail;-crossover-to-;sifah_mush;

The lexical ;ism_fail;-crossover-to-;sifah_mush;
is one which is commonly used with its ;sifah_mush; meaning.
It will typically have its own entry in a dictionary.
Examples are:

|verb|meaning|;ism_fail;-crossover-to-;sifah_mush;|
|:--|:-----|:-----|
|[طَهُرَ]{.ar} |[to be clean]{.trans}          |[طَاهِر]{.ar} [clean]{.trans}|
|[ضَمَرَ]{.ar} |[to be lean]{.trans}           |[ضَامِر]{.ar} [lean]{.trans}|
|[صَلُحَ]{.ar} |[to be righteous]{.trans}      |[صَالِح]{.ar} [righteous]{.trans}|
|[نَعُمَ]{.ar} |[to be soft]{.trans}           |[نَاعِم]{.ar} [soft]{.trans}|
|[بَسُلَ]{.ar} |[to be courageous]{.trans}     |[بَاسِل]{.ar} [courageous]{.trans}|

Sometimes, a true ;sifah_mush;
with a similar meaning,
can co-exist with
the lexical ;ism_fail;-crossover-to-;sifah_mush;,
For example
[طَهِير]{.ar} [clean]{.trans}.

Sometimes,
lexical ;ism_fail;-crossover-to-;sifah_mush;
occurs for verbs which are not purely stative.
In fact, it can even occur for transitive verbs.
Here are some examples:

|verb|meaning|;ism_fail;-crossover-to-;sifah_mush;|
|:--|:-----|:-----|
|[عَدَلَ]{.ar} |[to act justly]{.trans}           |[عَادِل]{.ar} [just]{.trans}|
|[رَبِحَ]{.ar} |[to gain a profit]{.trans}        |[رَابِح]{.ar} [profitable]{.trans}|
|[ظَلَمَ]{.ar} |[to wrong (s.o.)]{.trans}         |[ظَالِم]{.ar} [unjust, tyrannical]{.trans}|
|[رَحِمَ]{.ar} |[to have mercy (on s.o.)]{.trans} |[رَاحِم]{.ar} [merciful]{.trans}|
|[قَطَعَ]{.ar} |[to cut (s.th.)]{.trans}          |[قَاطِع]{.ar} [sharp, incisive]{.trans}|

Occasionally, the meaning of the ;ism_fail; can change considerably when it crosses over to a ;sifah_mush;.
For example:

|verb|meaning|;ism_fail;-crossover-to-;sifah_mush;|
|:--|:-----|:-----|
|[كَتَمَ]{.ar} |[to conceal (s.th)]{.trans}  |[كَاتِم]{.ar} [concealed]{.trans}|
|[دَفَقَ]{.ar} |[to pour (s.th.)]{.trans}    |[دَافِق]{.ar} [poured forth]{.trans}|

In the above examples, we can see that the
lexical ;ism_fail;-crossover-to-;sifah_mush;s
actually have the meaning of the ;ism_maful;s.
So [سِرٌّ كَاتِمٌ]{.ar} 
[@lane@ [»دفق«]{.ar}]{.citex}
is [a concealed secret]{.trans},
and [مَاءٌ دَافِقٌ]{.ar}
[@lane@ [»دفق«]{.ar}]{.citex}
is [water that is poured forth]{.trans}.^[See also @https://tafsir.app/albahr-almuheet/69/21@ [فَهُوَ فِی عِیشَةٍ رَّاضِیَةٍ]{.ar}]
But the ;ism_fail; can still be used with its original meaning.
For example:

(@) [وَلَوْ كَانَ مُحَمَّدٌ صلى الله عليه وسلم **كَاتِمًا** شَيْئًا مِمَّا أُنْزِلَ عَلَيْهِ لَكَتَمَ هَذِهِ الآيَةَ]{.ar}
    [@https://sunnah.com/muslim:177b@]{.citex}  
    And if [#muHammad]{.trn2} were to conceal anything from what was revealed to him, he would have concealed this ;ayah;.

When an ;ism_fail; crosses over to a ;sifah_mush;,
then it will govern in the manner of a ;sifah_mush;.
So, it can govern a ;faa3il;,
and the ;faa3il; is transformed into a ;mafulb;-like governee,
which is then used in a ;lafzi; ;idaafah;.
For example:

(@) [طَاهِرُ الْقَلْبِ]{.ar}
    [@azhari_sharh_tasreeh@ 2/41]{.citex}  
    [clean of heart]{.trans}  
    (The transformation is [طَاهِرٌ قَلْبُهُ]{.ar} ;rarr; [طَاهِرٌ الْقَلْبَ]{.ar} ;rarr; [طَاهِرُ الْقَلْبِ]{.ar}.)

(@) [ضَامِرُ الْكَشْحِ]{.ar}
    [@abu_hayyan_tadhyeel@ 10/298]{.citex}  
    [lean of flank]{.trans}  
    (The transformation is
    [ضَامِرٌ كَشْحُهُ]{.ar}
    ;rarr;
    [ضَامِرٌ الْكَشْحَ]{.ar}
    ;rarr;
    [ضَامِرُ الْكَشْحِ]{.ar}.)

The process above is normal and straightforward when it comes to
;ism_fail;-crossover-to-;sifah_mush;s
that are derived from intransitive verbs.
But if a
;ism_fail;-crossover-to-;sifah_mush;
is derived from a transitive verb, then there is more care required when using it in a ;lafzi; ;idaafah;.
For example, consider the following two
;ism_fail;-crossover-to-;sifah_mush;s
that are derived from transitive verbs:

|verb|meaning|;ism_fail;-crossover-to-;sifah_mush;|
|:--|:-----|:-----|
|[ظَلَمَ]{.ar} |[to wrong (s.o.)]{.trans}         |[ظَالِم]{.ar} [unjust, tyrannical]{.trans}|
|[رَحِمَ]{.ar} |[to have mercy (on s.o.)]{.trans} |[رَاحِم]{.ar} [merciful]{.trans}|

Now let's say that we wish to use the
;ism_fail;-crossover-to-;sifah_mush;
[رَاحِم]{.ar}
in a ;lafzi; ;idaafah;.
Then, it is preferred that the actual ;mafulb; of the ;ism_fail; not be mentioned.
So, for example, we can say

(@) [زَيْدٌ رَاحِمُ الْقَلْبِ]{.ar}  
    [Zayd is merciful of heart.]{.trans}

But we shouldn't say:

(@) ;x; [زَيْدٌ رَاحِمُ الْقَلْبِ النَّاسَ]{.ar}  
    [Zayd is merciful of heart to the people.]{.trans}

Sometimes, the meaning of the syntactic ;mudafil; can cause ambiguity.
For example if we say:

(@) [زَيْدٌ رَاحِمُ الْأَبْنَاءِ]{.ar}
    [modified from [@ibn_malik_sharh_tasheel@ 3/104](https://shamela.ws/book/13257/920#p1)]{.citex}  

then there are two routes to end up with this construction:

 i. [رَاحِم]{.ar} is a ;ism_fail; and [الأَبْنَاء]{.ar} is its ;mafulb;.
    The original sentence is:

    (@) [زَيْدٌ رَاحِمٌ الْأَبْنَاءَ]{.ar}  
        [Zayd is/will be having mercy on the sons.]{.trans}

ii. [رَاحِم]{.ar} is a
    ;ism_fail;-crossover-to-;sifah_mush;
    and [الأَبْنَاء]{.ar} is its semantic ;faa3il;.
    The original sentence is:

    (@) [زَيْدٌ رَاحِمٌ أَبْنَاؤُهُ]{.ar}  
        [Zayd is merciful of sons.]{.trans}  
        i.e. [Zayd has merciful sons.]{.trans}  

    This sentence gets transformed according to the transformation of ;sifah_mush;s.
    Even though [رَاحِم]{.ar} is derived from a transitive verb,
    its governee [أَبْنَاء]{.ar} is treated as a ;mafulb;-like governee,
    not as a ;mafulb;.^[[@ibn_malik_sharh_tasheel@ 3/104](https://shamela.ws/book/13257/920#p1)]
    So the transformation is
    [زَيْدٌ رَاحِمٌ أَبْنَاؤُهُ]{.ar}
    ;rarr;
    [زَيْدٌ رَاحِمٌ الْأَبْنَاءَ]{.ar}
    ;rarr;
    [زَيْدٌ رَاحِمُ الْأَبْنَاءِ]{.ar}.


There is actually a third route as well, where [رَاحِم]{.ar} is an
ad\ hoc ;ism_fail;-crossover-to-;substantive;.
In this case the meaning would be
[Zayd is the merciful-one of the sons]{.trans}.
However, this meaning is a little less likely and not very relevant to our discussion here.

Coming back to the sentence
[زَيْدٌ رَاحِمُ الْأَبْنَاءِ]{.ar},
there is no problem with using
[رَاحِمُ الْقَلْبِ]{.ar} as a
;ism_fail;-crossover-to-;sifah_mush;
to mean
[merciful of sons]{.trans}.
But only if context makes it clear that Zayd has merciful sons, not that he is having mercy on the sons.

Similarly,
one can say

(@) [زَيْدٌ ظَالِمُ الْعَبِيدِ]{.ar}
    [modified from [@ibn_malik_sharh_tasheel@ 3/104](https://shamela.ws/book/13257/920#p1)]{.citex}  
    [Zayd is unjust of slaves.]{.trans}  

when it is known that
Zayd has unjust slaves.^[[@ibn_aqil_musaa3id@ 2/222](https://shamela.ws/book/133358/818); see also @https://tafsir.app/aldur-almasoon/14/39@]



The lexical ;ism_fail;-crossover-to-;sifah_mush; is not as common for form\ 1 verbs as the true ;sifah_mush;.
But for form\ 2+ verbs,
the
;ism_fail; crossing over to a ;sifah_mush;
is the default mechanism to derive a ;sifah_mush; from the verb.
Examples:

|verb|meaning|;ism_fail;-crossover-to-;sifah_mush;|
|:--|:-----|:-----|
|[انْطَلَقَ]{.ar}  |[to be let loose]{.trans} |[مْنْطَلِقُ اللِّسَانِ]{.ar} [fluent of tongue]{.trans} [@abu_hayyan_tadhyeel@ 3/308]{.citex}  |
|[اطْمَأَنَّ]{.ar}  |[to be tranquil]{.trans}  |[مُطْمَئِنُّ الْقَلْبِ]{.ar}  [tranquil of heart]{.trans} [@abu_hayyan_tadhyeel@ 3/308]{.citex}  |
|[اسْتَقَامَ]{.ar} |[to be upright]{.trans}   |[مُسْتَقِيم]{.ar}       [straight]{.trans}         |
|[اعْتَدَلَ]{.ar}  |[to be moderate]{.trans}  |[مُعْتَدِل]{.ar}        [moderate]{.trans}         |

### The ad\ hoc ;ism_fail;-crossover-to-;sifah_mush;

The ad\ hoc ;ism_fail;-crossover-to-;sifah_mush;
can be created from any ;ism_fail;, on the fly,
when what is intended by the ;ism_fail; is a more permanent quality.
So, for example,
the ;ism_fail;
[قَائِم]{.ar}
can cross over to a ;sifah_mush; 
if its referent is standing more constantly than the ;ism_fail; would signify.
Now it can follow the same transformation of
governing a ;mafulb;-like governee and then into a ;lafzi; ;idaafah;.^[[@ibn_aqil_musaa3id@ 2/222](https://shamela.ws/book/133358/818); [@sharh_ashmooni@ 2/230](https://shamela.ws/book/11742/757)]
So we can say:

(@) [زَيْدٌ قَائِمُ الْأَبِ]{.ar}
    [[@ibn_aqil_musaa3id@ 2/222](https://shamela.ws/book/133358/818)]{.citex}  
    [Zayd's father is a stander.]{.trans}  
    (The process of transformation is
    [زَيْدٌ قَائِمٌ أَبُوهُ]{.ar}
    ;rarr;
    [زَيْدٌ قَائِمٌ الْأَبَ]{.ar} 
    ;rarr;
    [زَيْدٌ قَائِمُ الْأَبِ]{.ar}.)

But we should not use the ;lafzi; ;idaafah;
[زَيْدٌ قَائِمُ الْأَبِ]{.ar}
with the temporary meaning of the ;ism_fail;
[Zayd's father is standing]{.trans}.
This is because then
[قَائِم]{.ar}
is not a ;sifah_mush; and thus cannot govern a ;mafulb;-like governee.^[[@ibn_aqil_alfiyyah@ 3/140](https://shamela.ws/book/9904/818); [@shatibi_sharf_alfiyyah@ 4/393](https://shamela.ws/book/20562/2382)]
And it is derived from a transitive verb,
so it cannot govern a true ;mafulb; either.
So we can't say
(with a temporary meaning):

(@) ;x; [زَيْدٌ قَائِمُ الْأَبِ غَدًا]{.ar}
    [[@ibn_aqil_alfiyyah@ 3/140](https://shamela.ws/book/9904/818)]{.citex}
    [Zayd's father will stand tomorrow.]{.trans}
    
We should only say, in this case:

(@) [زَيْدٌ قَائِمٌ أَبُوهُ غَدًا]{.ar}
    [[@ibn_aqil_alfiyyah@ 3/140](https://shamela.ws/book/9904/818)]{.citex}
    [Zayd's father will stand tomorrow.]{.trans}

An
ad\ hoc ;ism_fail;-crossover-to-;sifah_mush;
can be formed from a transitive ;ism_fail; using the same reasoning.
So we can say:

(@) [زَيْدٌ ضَارِبُ الْأَبِ]{.ar}
    [[@ibn_aqil_musaa3id@ 2/222--223](https://shamela.ws/book/133358/818)]{.citex}  
    [Zayd's father is a beater.]{.trans}

But one should only use such a construction when context makes it clear that Zayd's father is the beater.
Otherwise the apparent meaning, out of context, is [Zayd is the beater of the father]{.trans}.
By the way, 
we have already learned in section\ (ref) above that
when a 
;ism_fail;-crossover-to-;sifah_mush;
is derived from a transitive verb,
then the true ;mafulb; of the verb should not be used.
So we shouldn't say:

(@) ;x; [زَيْدٌ ضَارِبُ الْأَبِ عَمْرًا]{.ar}
    [[@ibn_aqil_musaa3id@ 2/223](https://shamela.ws/book/133358/819#p1)]{.citex}  
    [Zayd's father is a beater of [#eamr]{.trn2}.]{.trans}

## The ;substantive; that crosses over to a ;sifah;

It is possible for a
;substantive; to cross over to a ;sifah;.
Sometimes this crossing over is metaphorical,
such that the ;substantive; is used with an ;sifah; meaning.
For example:

(@) [مررت برجل أسد]{.ar}  
    [I passed by a lion man]{.trans}  
    ([lion]{.trans} is used metaphorical to mean courageous.)

Othertimes, the ;substantive; is simply used descriptively.
For example:

(@) [مررت برجل عبد]{.ar}
    [I passed by a slave man]{.trans}

When a ;substantive; crosses over to a ;sifah;,
then it will govern a ;mustatir; ;faa3il; pronoun.
This ;faa3il; can also be an ;zaahir; ;sababi; ;faa3il;.
For example:

(@) [مررت برجل عبد أبوه]{.ar}
    [@https://tafsir.app/kashaf/4/172@]{.citex}

## The lexical ;sifah_mush;-crossover-to-;substantive;

Very often,
a ;sifah_mush; can cross over to a ;substantive;.

Here are some examples:

|;sifah_mush;-crossover-to-substantive | meaning |
|:----|:-----|
|[صَغِير]{.ar}  |[a baby]{.trans} |
|[كَبِير]{.ar}  |[a elder person]{.trans} |
|[صَغِيرَة]{.ar} |[a minor sin]{.trans} |
|[كَبِيرَة]{.ar} |[a major sin]{.trans} |
|[نَصِيحَة]{.ar} |[an advice]{.trans} |
|[حَسَنَة]{.ar}  |[a good deed]{.trans} |

As with 
;ism_fail;-crossover-to-;substantive;s
when an ;sifah; crosses over to a ;substantive;, it loses its genderizability.
For example, the feminine ;sifah_mush; [حَسَنَة]{.ar}  [good]{.trans}
crosses over to a ;substantive; to mean [a good deed]{.trans}.
Let's use it in a sentence:

(@) [ٱلصِّيَامُ حَسَنَةٌ.]{.ar}  
    [Fasting is a good deed.]{.trans}

The ;mubtada; in this sentence is the masculine noun [ٱَلصِّيَام]{.ar} [fasting]{.trans}.
And the ;xabar; is the feminine noun [حَسَنَة]{.ar} [a good deed]{.trans}.
Note that the ;xabar; does not match the ;mubtada; in gender.
This is because it lost its genderizability since it is no longer acting as an ;sifah_mush; 
[good]{.trans}, but rather as the ;substantive; [a good deed]{.trans}.

What if we have the sentence:

(@) [ٱَلصَّدَقَةُ حَسَنَةٌ.]{.ar}  

The feminine gender of the ;mubtada; 
[ٱَلصَّدَقَة.]{.ar} 
[charity]{.trans}
now matches the gender of the ;xabar;
[حَسَنَة]{.ar}.
So now, technically, the ;xabar; could be the ;sifah_mush;, meaning [good]{.trans}.
So the sentence could mean
[Charity is good.]{.trans}

Or the ;xabar; could be the ;substantive; meaning [a good deed]{.trans}.
Then the sentence would mean
[Charity is a good deed.]{.trans}.

Context would be needed to tell us which meaning is intended.


Frequently,
when
a ;sifah_mush; can cross over to a ;substantive;,
then it uses a different plural from the original ;sifah_mush;.
For example,
[كَبِيرَة]{.ar}
as a ;sifah_mush; can use the broken plural [كِبَار]{.ar}.
So we can say:

(@) [الْجَوَارِي كِبَارٌ]{.ar}
    [The girls are big.]{.trans}  
    ([كَبِيرات]{.ar} could also have been used.)


But when
[كَبِيرَة]{.ar}
crosses over to a ;substantive;,
then it will use the plural [كَبَائِر]{.ar}.
For example:

(@) [هَذِهِ الْأَفْعَالُ كَبَائِرُ]{.ar}  
    [These acts are major sins.]{.trans}

#### The ;ism_fail;-crossover-to-;substantive; on the pattern [فَعِيل]{.ar} {.unnumbered}

There is a special category of
lexical ;ism_fail;-crossover-to-;substantive;s
and that is on the pattern [فَعِيل]{.ar},
when it has the meaning of the ;ism_maful;.
Examples are:

|;sifah_mush;-crossover-to-substantive | meaning | verb | definition |
|:----|:-----|:--|:----|
|[قَتِيل]{.ar}  |[a killed person]{.trans}  |[قَتَلَ]{.ar} | [to kill (s.o.)]{.trans} |
|[جَرِيح]{.ar}  |[a wounded person]{.trans} |[جَرَحَ]{.ar} | [to wound (s.o.)]{.trans} |
|[أَجِير]{.ar}  |[a hired person]{.trans}   |[أَجَرَ]{.ar} | [to hire (s.o.)]{.trans} |

These 
;ism_fail;-crossover-to-;substantive;s are used under the following general guidelines:

* They can be used as a ;na3t; (by crossing back over to a ;sifah; as in section\ (ref) above)).

* When with an (explicit or implicit) noun as its referent has been previously mentioned, then only the masculine noun is used, even for feminine referents.

* When used without an (explicit or implicit)  noun as its referent, then the feminine noun (with [ة]{.ar}) may be used for a feminine referent.

Here are some examples:

(@) [مررت بامرأة جريح]{.ar}
    [[@ibn_aqil_alfiyyah@ 4/94](https://shamela.ws/book/9904/1101#p1)]{.citex}  
    [I passed by a wounded-person woman.]{.trans}  

(@) [مررت برجل جريح أبوه]{.ar}
    [[@ibn_aqil_musaa3id@ 2/209](https://shamela.ws/book/133358/805#p1)]{.citex}  
    [I passed by a man whose father was a wounded-person.]{.trans}  

(@) [رَأَيْتُ قَتِيلًا وَقَتِيلَةً]{.ar}  
    [I saw a male killed person and a female killed person.]{.trans}  

Not all ;sifah_mush;s with the meaning of the ;ism_maful; cross over (lexically) to ;substantive;s.
Some remain as ;sifah_mush;s and then are feminized as usual.
For example:

(@) [رَجُلٌ حَمِيدٌ وَامْرأَةٌ حَمِيدَةٌ]{.ar}  
    [a praiseworthy man and a praiseworthy woman]{.trans}

(@) [رَجُلٌ ذَمِيمٌ وَامْرأَةٌ ذَمِيمَةٌ]{.ar}  
    [a blameworthy man and a blameworthy woman]{.trans}

(@) [حِصْنٌ مَنِيعٌ وَقَلْعَةٌ مَنِيعَةٌ]{.ar}  
    [an impregnable fort and an impregnable citadel]{.trans}

Another example od
lexical ;ism_fail;-crossover-to-;substantive;s
that is on the pattern [فَعِيل]{.ar} is:

|;sifah_mush;-crossover-to-substantive | meaning | verb | definition |
|:----|:-----|:--|:----|
|[رَهِينَة]{.ar} |[a pledged-item]{.trans}   |[رَهَنَ]{.ar} | [to pledge (s.th.)]{.trans} |

In this case, the ;substantive; has a [ة]{.ar} and can be used for both masculine and feminine referents.
For example:

(@) [كُلُّ غُلاَمٍ رَهِينَةٌ بِعَقِيقَتِهِ]{.ar}
    [@https://sunnah.com/abudawud:2837@]{.citex}  
    [Every boy is a pledge by his [#eaqIqah]{.trn2}]{.trans}

The masculine [رَهِين]{.ar} can also be used but it will generally retain its ;sifah; sense.^[@lane@ entry [رَهْن]{.ar}]

## Definiteness of a ;sifah_mush; in a ;lafzi; ;idaafah; 

We learned in section\ (ref)
that the ;mudaf; in a
;lafzi; ;idaafah; is not made definite by a definite ;mudafil;.
We saw this in example (@sifah_mush_marartu_birajulin_hasanil_wajhi) [مررت برجل حسنِ الوجهِ]{.ar},
where
[حَسَن]{.ar}
in the ;lafzi; ;idaafah; remains indefinite
even though it is a ;mudaf; to a definite ;mudafil;
[الْوَجْهِ]{.ar}.
Therefore,
the indefinite
[حَسَن]{.ar}
is a ;na3t; to the indefinite ;manut;
[رَجُل]{.ar}.

If the ;manut; is definite,
then the ;sifah_mush; ;mudaf; is prefixed by [ال]{.ar}.

(@) [مررت بالرجل الحسنِ الوجهِ]{.ar}
    [[@ibn_ya3ish_mufassal@ 4/116](https://shamela.ws/book/13301/1480)]{.citex}

(@) [مررتُ بزيدٍ الحسنِ الوجهِ، وهندٍ الجائلةِ الوِشاح]{.ar}
    [[@ibn_ya3ish_mufassal@ 2/132](https://shamela.ws/book/13301/582)]{.citex}

This rule of a ;sifah_mush; not becoming definite because of a definite ;mudafil;
is followed more strictly than for the ;ism_fail;.^[[@za3balawi_dirasat@ 495](https://shamela.ws/book/2120/495)]
In the case of an ;ism_fail;,
we saw in section\ (ref) that it can cross over to a ;substantive; in an ad\ hoc manner.
When this happens, then it it becomes definite when it is a ;mudaf; to a definite ;mudafil;
(section\ (ref)).

But the ;sifah_mush;, when it is a ;mudaf; to its semantic ;faa3il;,
cannot be understood as a ;ma3nawi; ;idaafah;.
That is 
[حَسَنُ الْوَجْهِ]{.ar}
[handsome of face]{.trans}
can only be understood to mean that the face is handsome,
never [the face's handsome-one]{.trans}.
So we cannot, in general, say:

(@) ;x; [مررت بزيد حسن الوجه]{.ar}
    [[@za3balawi_dirasat@ 496](https://shamela.ws/book/2120/496) citing [الجامي]{.ar}]{.citex}  

We would have to say [مررتُ بزيدٍ الحسنِ الوجهِ]{.ar} instead, as in example () above.

All this notwithstanding,
some grammarians allow,
on occasion,
a ;sifah_mush;,
when a ;mudaf; to its semantic ;faa3il;,
to become definite by a definite ;mudafil;.
This is by reason of aligning to form of a ;ma3nawi; ;idaafah;.
For more discussion on this, see
@https://tafsir.app/ibn-uthaymeen/40/3@:

(@) [غَافِرِ ٱلذَّنۢبِ وَقَابِلِ ٱلتَّوۡبِ **شَدِیدِ ٱلۡعِقَابِ** ذِی ٱلطَّوۡلِۖ لَاۤ إِلَـٰهَ إِلَّا هُوَۖ إِلَیۡهِ ٱلۡمَصِیرُ]{.quran}
    [@https://quran.com/40/3@]{.citex}  
    [The forgiver of sin, acceptor of repentance, severe in punishment, owner of abundance. There is no deity except Him; to Him is the destination.]{.trans}



## Further reading

1. [الصفة المشبهة (قراءة جديدة في البنية الشكلية والدلالية لبعض الأوصاف المشتقة) د. فيصل إبراهيم صفا]{.ar}

