# Usage and style

;wip_warn;

;msa; today is considerably influenced by poor translations from English into Arabic.
This has resulted in a usage and style that is often far removed from ;sca;.
This appendix aims to highlight some poor usages and styles that the learner would be advised to guard against.
For more detailed works on this topic see the list of works in @sec-usage_further_reading below.

## Existential sentences

In English the plain existence of an indefinite ;mubtada; is expressed using the word [there]{.trans}. For example:

+ [There is a gloom in the house.]{.trans}
+ [There is a type of jealousy which is liked and [there is] a type of jealousy which is disliked.]{.trans}
+ [There are reasons.]{.trans}
+ [There is a god.]{.trans}
+ [Is there food?]{.trans}

The word [there]{.trans} in these examples does not indicate a specific place. Rather it signifies the existence of the ;mubtada; of the sentence. 
This use of [there]{.trans} is called the _existential_ [there]{.trans}.^[See also [@hapselmath_existential@](https://doi.org/10.58079/nswb)]

<!--As if to say:

i.   [A gloom exists in the house.]{.trans}
ii.  "A type of confidence exists which is good and a type of confidence exists which is bad.
iii. [Reasons exist]{.trans}
iv.  [A god exists.]{.trans}
-->

Expressing such sentences in Arabic can sometimes be tricky.
There is a modern tendency to use the ;dharf_makan; [هُنَاكَ]{.ar} and the passive verb [يُوجَدُ]{.ar}. <!-- as direct equivalents of the English [there]{.trans} and [exists]{.trans}.-->
So one might find:

(@ex001060) [هُنَاكَ حَزَنٌ فِي ٱلْبَيتِ.]{.ar} or  
    [يُوجَدُ حَزَنٌ فِي ٱلْبَيتِ.]{.ar}  
    [There is a gloom in the house.]{.trans}  

(@ex001061) [هناك غيرة يستحب وهناك غيرة يكره.]{.ar}  or  
    [توجد غيرة تستحب وتوجد غيرة تكره.]{.ar}  
    [There is a type of jealousy which is liked and there is a type of jealousy which is disliked.]{.trans}  

(@ex001062) [هُناك أسباب.]{.ar} or  
    [تُوجَدُ أسباب.]{.ar}  
    [There are reasons.]{.trans}  

(@ex001063) [هناك إله.]{.ar} or  
    [يوجد إله.]{.ar}  
    [There is a god.]{.trans}  

(@ex001064) [هَل هناك طعام؟]{.ar} or  
    [هل يوجد طعام؟]{.ar}  
    [Is there food?]{.trans}  

Sometimes in place of [هُنَاكَ]{.ar}, its synonyms [ثَمَّ]{.ar} or [ثَمَّةَ]{.ar} is used.

[هُنَاكَ]{.ar}, [ثَمَّ]{.ar}/[ثَمَّةَ]{.ar}, and [يُوجَدُ]{.ar} are not generally (see @sec-usage_legit_hunaaka below) used in ;sca; to express the existential.
<!--
These usages of [هُنَاكَ]{.ar}, [ثَمَّ]{.ar}/[ثَمَّةَ]{.ar}, and [يُوجَدُ]{.ar} are foreign to Arabic and should generally be avoided.

In Classical Arabic, expressing such sentences falls under the category of sentences with indefinite ;mubtada;s.
We have discussed this topic in chapter\ \@ref(chap-indef-subjects).
-->
There are various strategies for expressing such sentences:

### Using or manufacturing scope

If, for example, there is a [jArr wa-majrUr]{.trn2}, or other [cibh jumlah]{.trn2} then it can readily be used as a ;xabar; that precedes the ;mubtada;. For example:

(@ex001065) [فِي ٱلْبَيتِ حَزَنٌ.]{.ar}  
    [In the house is gloom.]{.trans}

Sometimes, a [jArr wa-majrUr]{.trn2}, or other [cibh jumlah]{.trn2} is not original, but can readily be manufactured. 
For example, in the sentence, [There are reasons]{.trans} the reasons must be for something, and that something can be used as a ;xabar;:

(@ex001066) [لِلْأَمْرِ أَسْبَابٌ.]{.ar}  
    [There are reasons for the situation.]{.trans}

### Using or manufacturing an introductory sentence

Similarly, a introductory sentence or [cibh jumlah]{.trn2} can be manufactured to pave the way for the main sentence. For example:

<!--
[الغَضَبُ غَضَبَانِ: غَضَبٌ مُسْتَحَبٌّ وَغَضَبٌ مَكْرُوهٌ.]{.ar}  
[Anger is (actually) two angers: an anger that is liked, and an anger that is disliked.]{.trans}

[مَنَ ٱلْغَضَبِ مَا يٌسْتَحَبُّ وَمَا يٌكْرَهُ.]{.ar}  
[From anger is that which is liked, that which is disliked.]{.trans}
-->

(@ex000140) [مِنَ الْغَيْرَةِ مَا يُحِبُّ اللَّهُ وَمِنْهَا مَا يَكْرَهُ اللَّهُ]{.ar}
    [@https://sunnah.com/ibnmajah:1996@]{.citex}  
    [**There is** a kind of jealousy what ;Allah; loves, and a kind that ;Allah; dislikes.]{.trans}

(@ex001067) [الْفَجْرُ فَجْرَانِ فَجْرٌ يَحْرُمُ فِيهِ الطَّعَامُ وَتَحِلُّ فِيهِ الصَّلَاةُ وَفَجْرٌ تَحْرُمُ فِيهِ الصَّلَاةُ وَيَحِلُّ فِيهِ الطَّعَامُ]{.ar}
    [@https://hadithunlocked.com/hakim:687@]{.citex}  
    [**There are** two dawns: a dawn in which food is forbidden while prayer becomes permissible, and a dawn in which prayer is forbidden while food becomes permissible.]{.trans}

### Using a ;ism_isharah;

A ;ism_isharah;,
like [هَذَا]{.ar},
can sometimes be used when English would use
[there is]{.trans}
to offer an option.
For example:

(@) [فقال: ارى أن تنزل القرية، قَالَ: أكرهها، قَالَ: **فهذا الهزيم**.  قَالَ: أكره اسمه، قَالَ: فهذا البخراء، قصر النعمان بْن بشير]{.ar}
    [[@tarikh_tabari@ 7/244](https://shamela.ws/book/9783/3940) accessed via @rasaif@]{.citex}  
    [So he said, "I think that you should stop at a settlement." He said, "I dislike [doing so]." He said, "**Then there is [al-#hazIm]{.trn2}**." He said, "I dislike its name." He said, "Then there is [al-#baxrAE]{.trn2}, the palace of [al-#nuemAn ibn #bacIr]{.trn2}.]{.trans}

### Using a suitable verbal expression

For example:

(@) [**وَاخْتُلِفَ** فِيمَنْ حَجَّ بِالنَّاسِ فِي هَذِهِ السَّنَةِ]{.ar}
    [[@tarikh_tabari@ 4/249](https://shamela.ws/book/9783/2140) accessed via @rasaif@]{.citex}  
    [**There is a disagreement** regarding who led the [#Hajj]{.trn2} in this year.]{.trans}

(@) [فإن **فضلَ فضلٌ** نقلته إلى البلد الذي يليه، ممن هو أحوج إليه]{.ar}
    [[@tarikh_tabari@ 7/269](https://shamela.ws/book/9783/3965) accessed via @rasaif@]{.citex}  
    [If **there is any surplus**, I will transfer it to the country next to it that is in more need of it.]{.trans}  

### Using an interjection

Sometimes it hard to come up with any of the above solutions, as in the sentence: [There is a god.]{.trans}
Such sentences, if they are able to be converted to an interjection, may be expressed with the ;mubtada; itself as a one word sentence^[@cantarino_smap@ 1/5 citing @brock_grund@ 2/35]:

(@ex001068) [إِلَـٰهٌ]{.ar}  
    [**[There is]** a god!]{.trans}

(@ex001069) [**أَمِيرَانِ** هَلَكَ الْقَوْمُ]{.ar}
    [cited by @brock_grund@ 2/6]{.citex}  
    [**[There are]** two commanders?! The people are destroyed!]{.trans}

Consider also this example:

(@ex000141) [سَأَلْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم هَلْ رَأَيْتَ رَبَّكَ قَالَ **نُورٌ** أَنَّى أَرَاهُ]{.ar}
    [@https://sunnah.com/muslim:178@]{.citex}  

The statement
[نُورٌ أَنَّى أَرَاهُ]{.ar}
has been explained by Ibn Taymiyyah with the following wording^[[@ibn_qayyim_juyoosh@ 21](https://shamela.ws/book/18632/80)]:

> [**كَانَ ثَمَّ** نُورٌ ، أَوْ حَالَ دُونَ رُؤْيَتِهِ نُورٌ فَأَنَّىٰ أَرَاهُ.]{.ar}  
> [**There was** light, or light came between [my] seeing Him, so how could I see Him?]{.trans}

This solution should only be considered if the sentence makes sense as an interjection, and can not be used as a blanket solution. For example, the question:

[Is there food?]{.trans}  

can be expressed in Arabic, not as an interjection, but as:

(@ex001070) [**هَلْ مِنْ** غَدَاءٍ]{.ar}
    [@https://sunnah.com/muslim:2052d@]{.citex}  
    [**Is there** any food?]{.trans}  

Similarly:

(@ex001071) [**هَلْ مِنْ** مُسْتَغْفِرٍ **هَلْ مِنْ** تَائِبٍ **هَلْ مِنْ** سَائِلٍ **هَلْ مِنْ** دَاعٍ]{.ar}
    [@https://sunnah.com/muslim:758e@]{.citex}  
    [**Is there** one seeking forgiveness? **Is there** a penitent? **Is there** an asker? **Is there** a caller?]{.trans}


### Negative existential sentences

For a negative existential sentence,
we can conveniently use ;laa;, ;maa; and ;laysa;.
For example:

(@ex001073) [**لَا** أَمَلَ]{.ar}  
    [**There is no** hope.]{.trans}  

(@) [**ما** في المحفظة ريال]{.ar}
    [@earanjiyyah@ 171]{.citex}  
    [**There are no** [riyAl]{.trn2}s in the wallet.]{.trans}  

(@) [فلان **ما** بقلبه رحمة]{.ar}
    [@earanjiyyah@ 171]{.citex}  
    [**There is no** mercy in so-and-so's heart.]{.trans}  

(@) [يَا أُمَّ سَلَمَةَ إِنَّهُ **لَيْسَ آدَمِيٌّ** إِلاَّ وَقَلْبُهُ بَيْنَ أُصْبُعَيْنِ مِنْ أَصَابِعِ اللَّهِ فَمَنْ شَاءَ أَقَامَ وَمَنْ شَاءَ أَزَاغَ]{.ar}  
    [@https://sunnah.com/tirmidhi:3522@]{.citex}  
    [O Umm Salamah, indeed **there is no human** except that his heart is between two fingers from the fingers of ;Allah;. Whomsoever He wills He makes steadfast. And whomsoever he wills, he causes to deviate.]{.trans}  

### Using ;kaana; to express the existential

As we know,
[يَكُونُ]{.ar}
is not normally used as the equivalent of the English [is]{.trans}.
But ;kaana; is used for [was]{.trans} with no problem.
This helps us solve the problem of expressing the existential for the past tense.
For example:

(@ex001072) [**كَانَ** مَلِكٌ]{.ar}  
    [**There was** a king.]{.trans}  
    This uses the ;taamm; ;kaana;. (See @sec-kaana_taammah).

;kaana; and ;yakun; can also be used to express the existential in ;j_sh;s and similar sentences,
where the tense is determined from context.
For example:

(@) [وإن **كَانَ** ملك فالملك ملككم]{.ar}
    [[@tarikh_tabari@ 3/269](https://shamela.ws/book/9783/1542) accessed via @rasaif@]{.citex}  
    [And if **there is** [to be] any sovereignty it shall be yours.]{.trans}

(@) [دَعُوهُ، فَإِنْ **يَكُ** فِيهِ خَيْرٌ فَسَيُلْحِقُهُ اللَّهُ بِكُمْ]{.ar}
    [[@tarikh_tabari@ 3/107](https://shamela.ws/book/9783/1381) accessed via @rasaif@]{.citex}  
    [Leave him be, for if **there is** any good in him, then ;Allah; will join him to you.]{.trans}

(@) [فَوَاللَّهِ لَقَلَّمَا **كَانَتِ** امْرَأَةٌ قَطُّ وَضِيئَةٌ عِنْدَ رَجُلٍ يُحِبُّهَا وَلَهَا ضَرَائِرُ إِلاَّ كَثَّرْنَ عَلَيْهَا]{.ar}
    [@https://sunnah.com/muslim:2770a@]{.citex}  
    [Rarely **is there** a woman at all, fair to a man who loves her, and she has co-wives, except that they say much against her.]{.trans}


### Legitimate use of [هُنَاكَ]{.ar}, ;thamma; and [يُوجَدُ]{.ar}

If, of course, a place is intended by [there]{.trans} then there is no problem using [هُنَاكَ]{.ar} or its synonyms.
We show below some examples that use ;hunaaka; and ;thamma;.
It would appear that they are still locatives, though there may sometimes be a suggestion of the existential.

One technique you can use to determine whether ;hunaaka; or ;thamma; are appropriate,
is to substitute
[فِي هَذَا/ذَلِكَ الْمَكَانِ]{.ar} in place of it and see if the sentence is still valid.

Here are the examples:

(@ex001074) [كُنَّا نَادِينَ بِالصَّبَاحِ **وَهُنَاكَ** عَبْدُ اللَّهِ بْنُ عَمْرٍو **وَكَانَ هُنَاكَ** امْرَأَةٌ مِنْ بَنِي الْمُغِيرَةِ يُقَالُ لَهَا فَاطِمَةُ فَسَمِعْتُ عَبْدَ اللَّهِ بْنَ عَمْرٍو يَقُولُ «ذَاكَ يَزِيدُ بْنُ مُعَاوِيَةَ»]{.ar}
    [@https://hadithunlocked.com/hakim:8461@]{.citex}  
    [We used to meet socially in the morning and [#eabd]{.trn2} ;Allah; ibn [#eamr]{.trn2} **would be there**. And **there was** a woman there from [#banU al-#mugIrah]{.trn2} called [#fATimah]{.trn2}. And she heard [#eabd]{.trn2} ;Allah; ibn [#eamr]{.trn2} saying, "That is [#yazId ibn #mueAwiyah]{.trn2}."]{.trans}  

(@ex001075) [خَرَجَ النَّبِيُّ صلى الله عليه وسلم فِي طَائِفَةِ النَّهَارِ لاَ يُكَلِّمُنِي وَلاَ أُكَلِّمُهُ حَتَّى أَتَى سُوقَ بَنِي قَيْنُقَاعَ، فَجَلَسَ بِفِنَاءِ بَيْتِ فَاطِمَةَ فَقَالَ **أَثَمَّ لُكَعُ أَثَمَّ لُكَعُ**]{.ar}
    [@https://sunnah.com/bukhari:2122@]{.citex}  
    [The Prophet ;pbuh; went out during the day, neither he talking to me nor I talking to him, until he reached the market of [#banI #qaynuqAe]{.trn2}. He then sat in the courtyard of [#faTimah]{.trn2}'s house and said, "**Is the little chap there? Is the little chap there**?"]{.trans}

(@ex001076) [جَلَبْتُ أَنَا وَمَخْرَمَةُ الْعَبْدِيُّ بَزًّا مِنْ هَجَرَ فَأَتَيْنَا بِهِ مَكَّةَ فَجَاءَنَا رَسُولُ اللَّهِ ﷺ يَمْشِي فَسَاوَمَنَا بِسَرَاوِيلَ فَبِعْنَاهُ **وَثَمَّ** رَجُلٌ يَزِنُ بِالأَجْرِ فَقَالَ لَهُ رَسُولُ اللَّهِ ﷺ زِنْ وَأَرْجِحْ]{.ar}
    [@https://sunnah.com/abudawud:3336@]{.citex}  
    [I and Makhrafah al-Abdi imported some garments from Hajar, and brought them to Mecca. The Messenger of ;Allah; ;pbuh; came to us walking, and after he had bargained with us for some trousers, we sold them to him. **There was** a man who was weighing for payment. The Messenger of ;Allah; ;pbuh; said to him: Weigh out and give overweight.]{.trans}

(@ex001077) [كَانَ رَسُولُ اللهِ ﷺ إِذَا سَجَدَ **وَثَمَّ** بَهْمَةٌ أَرَادَتْ أَنْ تَمُرَّ بَيْنَ يَدَيْهِ تَجَافَى]{.ar}
    [@https://hadithunlocked.com/ahmad:26809@]{.citex}  
    [When the Messenger of ;Allah; ;pbuh; used to prostrate, and **there was** a lamb that wanted to pass infront of him, he would have his arms to the side.]{.trans}  

(@ex001078) [رَأَيْتُ رَسُولَ اللَّهِ ﷺ يَرْمِي الْجِمَارَ عَلَى نَاقَةٍ صَهْبَاءَ **لَيْسَ ثَمَّ** ضَرْبٌ وَلَا طَرْدٌ وَلَا إِلَيْكَ إِلَيْكَ]{.ar}
    [@https://hadithunlocked.com/darimi:1942@]{.citex}  
    [I saw the Prophet ;pbuh; stone the Pillar, on the Day of Sacrifice, from atop a reddish-brown camel of his; and **there wasn't** any beating or driving them off or [telling them to] go away.]{.trans}

(@ex001079) [أَنَّ رَكْبًا وَقَفُوا عَلَى عُثْمَانَ بْنِ عَفَّانَ فَمَدَحُوهُ وَأَثْنَوْا عَلَيْهِ **وَثَمَّ** الْمِقْدَادُ بْنُ الْأَسْوَدِ فَأَخَذَ قَبْضَةً مِنَ الْأَرْضِ فَحَثَاهَا فِي وُجُوهِ الرَّكْبِ]{.ar}
    [@https://hadithunlocked.com/ahmad:23826@]{.citex}  
    [... that a group of riders stopped by [#euvmAn ibn #eaffAn]{.trn2} and praised him. And [al-#miqdAd ibn al-E#aswad]{.trn2} **was there**. So he took a handful [of dirt] from the ground and threw it in the faces of the riders.]{.trans}


Similarly, [يُوجَدُ]{.ar} may be used with no problem if the meaning [is (to be) found]{.trans} is intended. For example:

(@ex001080) [مَنْ قَتَلَ مُعَاهَدًا لَمْ يَرَحْ رَائِحَةَ الْجَنَّةِ، وَإِنَّ رِيحَهَا **تُوجَدُ** مِنْ مَسِيرَةِ أَرْبَعِينَ عَامًا]{.ar}
    [@https://sunnah.com/bukhari:3166@]{.citex}  
    [Whoever killed a person having a treaty with the Muslims, shall not smell the smell of Paradise though its smell **is perceived** from a distance of forty years.]{.trans}  

### Use of existential ;hunaaka; {#sec-usage_legit_hunaaka}

Some researchers have found ;hunaaka; rarely being used existentially in older works not influenced by European languages.
For example:

(@) [وَقَالَ الْكُوفِيُّونَ مِنْ أَصْحَابِ الرَّأْيِ الْوُضُوءُ وَالْغُسْلُ جَائِزَانِ وَإِنْ  لَمْ يَكُنْ **هُنَاكَ** نِيَّةٌ]{.ar}  
    [[[الطهور (ت مشهور) لأبي عبيد القاسم بن سلام]{.ar} 200](https://shamela.ws/book/262/147) cited by @earanjiyyah@ 170]{.citex}  

(@) [**وهناك** خيانات في صلب الملك، أو في بعض الحرم، فلا يستطيع الملك أن يكشف للعامة موضع العورة في الملك]{.ar}  
    [[[البيان والتبيين للجاحظ]{.ar} 3/246](https://shamela.ws/book/10614/797) cited by @earanjiyyah@ 170]{.citex}  

Further research would be required to establish whether this usage is original,
or a later addition by a copyist.

### Technical and scientific use of [يوجَد]{.ar}

Our above directive to avoid the use of [يوجد]{.ar} to mean [there is]{.trans} holds for normal sentences.
Sometimes, however, a more technical meaning of [exists]{.trans} is intended, especially in the language of science.
<!--
However, scholars, in developing branches of science, need to define terminology and use it in the precise manner which their science demands.
Historically, scholars have added on scientific meanings to existing words. There is no problem with this if done carefully and discriminately.
-->
In this case, [يوجد]{.ar} and its ;ism_maful; [موجود]{.ar} may be used when needing to discuss the existence of something in a scientific text.
But such usage should be restricted to its domain, and should not, ideally, spill over to normal sentences, where a simple [there is]{.trans} is intended.

By the way, the disused verb [أَيْسَ]{.ar} [to be]{.trans},
(theorized, along with [لَا]{.ar}, to be the origin of the verb [لَيْسَ]{.ar}^[@wilmsen_croft@ 329--331; @wright@ 1/96C])
is also used to express the existence of an object in philosophical works.

<!--
While this concession can be granted to [يوجد]{.ar}, we find no such justifying circumstance for using [هناك]{.ar} existentially.
-->

<!--## [#DamIr al-faSl]{.trn2} after [ism al-istifhAm]{.trn2}-->

## Pronoun of separation after question nouns

In later writing we find the following forms:

(@) [مَنْ هِيَ زَيْنَب؟]{.ar}  
    [Who is Zaynab?]{.trans}

(@) [مَا هُوَ ٱلْإِسْلَامُ؟]{.ar}  
    [What is [#islAm]{.trn2}?]{.trans}

(@) [لِمَاذَا هُوَ حَزِينٌ؟]{.ar}  
    [Why is he sad?]{.trans}

The insertion of the pronoun of separation ([هُوَ]{.ar}, [هِيَ]{.ar}, etc.) after question nouns is best avoided.
So it is better to say:

(@) [مَنْ زَيْنَب؟]{.ar}  
    [Who is Zaynab?]{.trans}

(@) [مَا ٱلْإِسْلَامُ؟]{.ar}  
    [What is [#islAm]{.trn2}?]{.trans}

As for [why]{.trans} sentences, Arabic has a native expression using [مَا لِ]{.ar} followed by a noun or pronoun in the ;icase; and then an adjective in the ;acase;.
For example:

(@) [مَا لَهُ حَزِينًا؟]{.ar}  
    [Why is he sad?]{.trans}

Another option,
that is sometimes possible,
is to convert the [why]{.trans} question into a [what]{.trans} question, thus:

(@) [مَا أَحْزَنَهُ]{.ar}  
    [Why is he sad?]{.trans}
    (literally: What has made him sad?)

## [What happened to ...]{.trans}

When asking the question, [What happened to a person/thing?]{.trans} the verbs [فَعَلَ]{.ar} and [صَنَعَ]{.ar} are used and the person or thing asked about is made the ;faa3il;.
For example:

(@) [يَا أَبَا عُمَيْرٍ مَا فَعَلَ النُّغَيْرُ]{.ar}  
    [@https://sunnah.com/bukhari:6129@]{.citex}  
    [What happened to the sparrow?]{.trans}

(@) [ما فعل أصحابك]{.ar}  
    [@https://sunnah.com/riyadussalihin:30@]{.citex}  
    [What happened to your companions?]{.trans}

(@) [مَا فَعَلَتِ الرَّيْطَةُ]{.ar}  
    [@https://sunnah.com/ibnmajah:3603@]{.citex}  
    [What happened to the thin cloak?]{.trans}

(@) [فَيَسْأَلُونَهُ مَاذَا فَعَلَ فُلاَنٌ مَاذَا فَعَلَ فُلاَنٌ]{.ar}  
    [@https://sunnah.com/nasai:1833@]{.citex}  
    [So they ask him: What happened to so-and-so? What happened to so-and-so?  ]{.trans}

## [About]{.trans}

The word [about]{.trans} is often indiscriminately translated as [عَنْ]{.ar}.
[عَنْ]{.ar} can be used as such. But more care is required.

;ean; is normally with  the verb [سَأَلَ]{.ar}.
For example:

(@) [سَأَلَهُ عَنْ أَمْرٍ.]{.ar}  
    [He asked him about a matter.]{.trans}

[عَنْ]{.ar} can also sometimes be used generically.
For example:

(@) [مَا هَذَا الَّذِي يَذْكُرُونَ **عَنِ** الْحَسَنِ]{.ar}  
    [@https://sunnah.com/abudawud:4621@]{.citex}  
    [What is this that they are mentioning **about** [al-#Hasan]{.trn2}?]{.trans}

(@) [فأخبره **عنهم**]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [So he informed him **about them**.]{.trans}

(@) [بلغني أشياء **عن** الحرشي]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [Certain things have reached me **about** [al-#HaracI]{.trn2}.]{.trans}

Usually, though, the preposition depends on the verb used.
For example:

(@) [فسأله **عن** دينه فأخبره **به**]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [He asked him **about** his religion and he told him **about it**.]{.trans}

(@) [وَكَانَ عالما بأمر طليحة]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [He was knowledgable about the affairs of [#TulayHah]{.trn2}.]{.trans}

(@) [فاكتب إلي **بالأمر** على وجهه لأخبر **به** أمير المؤمنين]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [So write to me **about the matter** properly, so that I may inform the Commander of the Faithful **about it**.]{.trans}

(@) [قد قيل **في** ذلك أقوال]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [[Sundry] statements have been given **about** that.]{.trans}

(@) [واختلفوا **فِي** أمره]{.ar}
    [@tarikh_tabari@  accessed via @rasaif@]{.citex}  
    [[Authorities] have differed **about** his affair.]{.trans}

## [What about ...]{.trans}

Avoid 
[مَاذَا عَنْ]{.ar}
when asking [What about someone/something?]{.trans}

Instead use 
[مَا بَالُ]{.ar}.

For example:

(@) [حَتَّى إِذَا فَرَغَ مَشَيْتُ، فَقُلْتُ **مَا بَالُ** الْعَظْمِ وَالرَّوْثَةِ ]{.ar}  
    [@https://sunnah.com/bukhari:3860@]{.citex}  

(@) [إِذَا تَوَاجَهَ الْمُسْلِمَانِ بِسَيْفَيْهِمَا فَكِلاَهُمَا مِنْ أَهْلِ النَّارِ ". قِيلَ فَهَذَا الْقَاتِلُ، **فَمَا بَالُ** الْمَقْتُولِ]{.ar}  
    [@https://sunnah.com/bukhari:7083@]{.citex}  

(@) [عَنْ عَائِشَةَ، أَنَّهَا قَالَتْ يَا رَسُولَ اللَّهِ مَا الشَّىْءُ الَّذِي لاَ يَحِلُّ مَنْعُهُ قَالَ الْمَاءُ وَالْمِلْحُ وَالنَّارُ " . قَالَتْ قُلْتُ يَا رَسُولَ اللَّهِ هَذَا الْمَاءُ قَدْ عَرَفْنَاهُ **فَمَا بَالُ** الْمِلْحِ وَالنَّارِ]{.ar}  
    [@https://sunnah.com/ibnmajah:2474@]{.citex}  

When the question [What about ...?]{.trans} is asked as a follow-up to a previous statement then the asked about person/thing can be asked by itself in a single word.
For example:

(@) [عَنِ النَّبِيِّ صلى الله عليه وسلم أَنَّهُ نَهَى أَنْ يَشْرَبَ الرَّجُلُ قَائِمًا . قَتَادَةُ فَقُلْنَا **فَالأَكْلُ** فَقَالَ ذَاكَ أَشَرُّ أَوْ أَخْبَثُة]{.ar}
    [@https://sunnah.com/muslim:2024b@]{.citex}  
    ["What about eating?"]{.trans}

(@) [قَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم لِلْمُتَلاَعِنَيْنِ حِسَابُكُمَا عَلَى اللَّهِ أَحَدُكُمَا كَاذِبٌ لاَ سَبِيلَ لَكَ عَلَيْهَا قَالَ يَا رَسُولَ اللَّهِ **مَالِي**]{.ar}  
    [@https://sunnah.com/abudawud:2257@]{.citex}  
    ["What about my wealth?"]{.trans}

## To make someone do something

In order to express the meaning: to make someone do something, we have a few options:

1. To use a causative verb, like form\ 4, if one is available with this meaning^[@earanjiyyah@ 65].
   For example:

   (@) [أَدْخَلْتُهُ ٱلدَّارَ]{.ar}
       [@muqtadab@ 2/104]{.citex}  


2. To use the expression [حَمَلَهُ عَلَى أَنْ يَفْعَلَ]{.ar} or [حَمَلَهُ عَلَى الفعل]{.ar}.
   For example

   (@) [وَقَالُوا شَيَّأْتُهُ ; أَيْ حَمَلْتُهُ عَلَى أَنْ يَشَاءَ]{.ar}
       [@3akbari_tibyan@ 1/37]{.citex}  

   (@) [وَأَعْجَلْتُهُ بِالْأَلِفِ حَمَلْتُهُ عَلَى أَنْ يَعْجَلَ]{.ar}
       [[المصباح المنير للفيومي]{.ar} root [عجل]{.ar}]{.citex}  

   This expressions is especially common in questions like [What made you ...?]{.trans}
   For example:

   (@) [مَا حَمَلَكَ عَلَى مَا صَنَعْتَ]{.ar}
       [@https://sunnah.com/abudawud:2221@]{.citex}  

3. To use the verb [جَعَلَ]{.ar}. This isn't as preferred as the other options above.
   For example:

   (@) [جَعَلْتُهُ يَدْخُلَهَا]{.ar}
       [@muqtadab@ 2/104]{.citex}  

## To leave a place

In English, the verb [to leave]{.trans}
is used to mean [to depart]{.trans}.
In Arabic, the verb
[تَرَكَ]{.ar} should not be used with this meaning unless
the intended meaning is to abandon the place.
Nor should the verb [غَادَر]{.ar} be used with this meaning,
because it means [to leave (s.th.) out]{.trans}.
Instead Arabic has a variety or verbs that can be used,
sometimes interchangeably and sometimes
depending on the exact meaning required.
Some (out of many) of these verbs are:

+ [خَرَجَ]{.ar} [to exit]{.trans}

  (@) [كَانَ إِذَا **خَرَجَ مِنْ بَيْتِهِ** قَالَ بِسْمِ اللهِ، التُّكْلاَنُ عَلَى اللهِ، لا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ]{.ar}
      [@https://sunnah.com/adab:1197@]{.citex}  
      [When he would **leave his house**, he would say, "In the name of ;Allah;. Reliance is on ;Allah;. There is no power or strength except by ;Allah;."]{.trans}  

+ [انْصَرَفَ]{.ar} [to turn around]{.trans}

  (@) [ثُمَّ انْصَرَفَ]{.ar}
      [@https://sunnah.com/bukhari:1462@]{.citex}  
      [Then he left.]{.trans}  

+ [بَرِحَ]{.ar} [to depart]{.trans}

  (@) [فَقَالَ يَا رَسُولَ اللَّهِ فَكَيْفَ فِيَّ وَأَنَا أَعْمَى قَالَ **فَمَا بَرِحَ** حَتَّى نَزَلَتْ غَيْرُ أُولِي الضَّرَرِ]{.ar}
      [@https://sunnah.com/nasai:3102@]{.citex}  
      [He said, "O Messenger of ;Allah;, how about me whereas I am blind?" And **so he did not leave** until [the ;ayah;] "other than the disabled" [@https://quran.com/4/95@]{.citex} was revealed.]{.trans}  

+ [انْحَرَفَ]{.ar} [to turn away]{.trans}

  (@) [ثُمَّ انْحَرَفَ فَانْحَرَفْتُ]{.ar}
      [@https://sunnah.com/nasai:3964@]{.citex}  
      [Then he left and I left.]{.trans}

<!--
+ [مَضَى]{.ar} [to pass]{.trans}

  (@) [قَالَ الْحَقْ وَمَضَى فَتَبِعْتُهُ]{.ar}
      [@https://sunnah.com/bukhari:6452@]{.citex}  
      [He said, "Join me." And he left. So I followed him.]{.trans}

+ [أَدْبَرَ]{.ar} [to turn back]{.ar}
+ [تَوَلَّى]{.ar} [to turn back]{.ar}
-->

## To bring something

Arabic has no commonly used verb which is the direct equivalent of [to bring]{.trans}.
Avoid using verbs [أَحْضَرَ]{.ar} and [جَلَبَ]{.ar}
as common equivalents of the simple verb [to bring]{.trans}.
These are legitimate verbs but they have their own specific meanings
and are nowhere near as common as 
[أَتَى ب]{.ar}
and
[جَاءَ ب]{.ar}
when the simple meaning of [to bring]{.trans} is intended.


Instead, one may use the verbs
[أَتَى]{.ar}
and
[جَاءَ]{.ar}
[to come]{.trans}
with the preposition [بِ]{.ar}.
For example:

<!--
When using these verbs, the ;faa3il; need not actually be coming to any place himself.
For example:
-->

(@) [أُتِيَ النَّبِيُّ صلى الله عليه وسلم بِصَبِيٍّ]{.ar}
    [@https://sunnah.com/bukhari:5468@]{.citex}  
    [A baby was brought to the Prophet ;pbuh;.]{.trans}

(@) [ثُمَّ دَعَا بِمَاءٍ، فَجِئْتُهُ بِمَاءٍ فَتَوَضَّأَ]{.ar}
    [@https://sunnah.com/bukhari:224@]{.citex}  
    [Then he called for water. So I brought him some water and he performed ablution.]{.trans}  

When bringing something in a particular direction,
other, more specific, verbs may be used similarly.
For example:

(@) [ثُمَّ مَسَحَ رَأْسَهُ بِيَدَيْهِ، **فَأَقْبَلَ بِهِمَا وَأَدْبَرَ**، بَدَأَ بِمُقَدَّمِ رَأْسِهِ، حَتَّى ذَهَبَ بِهِمَا إِلَى قَفَاهُ، ثُمَّ **رَدَّهُمَا** إِلَى الْمَكَانِ الَّذِي بَدَأَ مِنْهُ]{.ar}
    [@https://sunnah.com/bukhari:185@]{.citex}  
    [Then he wiped his head with his hands, **so he brought them forwards and backwards**. He started with the front part of he head until he took them to the nape of his neck, then **he brought them back** to the place that he had started from.]{.trans}  

When bringing something out, the verb [أَخْرَجَ]{.ar} or [خَرَجَ ب]{.ar} are used.
For example:

(@) [أَتَى رَسُولُ اللَّهِ صلى الله عليه وسلم **فَأَخْرَجْنَا** لَهُ مَاءً فِي تَوْرٍ مِنْ صُفْرٍ فَتَوَضَّأَ]{.ar}
    [@https://sunnah.com/bukhari:197@]{.citex}  
    [Once ;Allah;'s Messenger ;pbuh; came to us and we brought out water for him in a brass pot. He performed ablution.]{.trans}

(@) [**خَرَجَ** إِلَيْنَا أَنَسُ بْنُ مَالِكٍ بِنَعْلَيْنِ لَهُمَا قِبَالاَنِ]{.ar}
    [@https://sunnah.com/bukhari:5858@]{.citex}  
    [Anas ibn [#mAlik]{.trn2} brought out for us, two sandals having two straps.]{.trans}  

## To take someone/something somewhere

Arabic has the verb [أَخَذَ]{.ar}
which means [to take]{.trans}.
But this verb is not typically used when the meaning of
[to take someone/something somewhere]{.trans}
is intended.
Instead,
the verb/preposition combination
[ذَهَبَ بِ]{.ar} is used.
For example:

(@) [ذَهَبَتْ بِي خَالَتِي إِلَى رَسُولِ اللَّهِ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/bukhari:3541@]{.citex}  
    [My aunt took me to Messenger of ;Allah; ;pbuh;.]{.trans}  

Other verbs besides [ذَهَبَ]{.ar} may similarly be used.
For example:

(@) [أَخَذَ أَبُو طَلْحَةَ بِيَدِي **فَانْطَلَقَ بِي إِلَى** رَسُولِ اللَّهِ صلى الله عليه وسلم]{.ar}
    [@https://sunnah.com/bukhari:6911@]{.citex}  
    [[#abU #TalHah]{.trn2} took my hand **and took me to** the Messenger of ;Allah; ;pbuh;.]{.trans}


The ;faa3il; need not actually be _going_ anywhere
when using this verb.
For example:

(@) [ثُمَّ مَسَحَ رَأْسَهُ بِيَدَيْهِ، فَأَقْبَلَ بِهِمَا وَأَدْبَرَ، بَدَأَ بِمُقَدَّمِ رَأْسِهِ، حَتَّى **ذَهَبَ بِهِمَا إِلَى قَفَاهُ**، ثُمَّ رَدَّهُمَا إِلَى الْمَكَانِ الَّذِي بَدَأَ مِنْهُ]{.ar}
    [@https://sunnah.com/bukhari:185@]{.citex}  
    [Then he wiped his head with his hands, so he brought them forwards and backwards. He started with the front part of he head until **he took them to the nape of his neck**, then he brought them back to the place that he had started from.]{.trans}  

## Further reading {#sec-usage_further_reading}

1. @earanjiyyah@
2. [معجم أخطاء الكتاب لصلاح الدين الزعبلاوي]{.ar}
3. [معجم الأخطاء الشائعة لمحمد العدناني]{.ar}
4. [معجم الأغلاط اللغوية المعاصرة لمحمد العدناني]{.ar}
5. [أخطاء لغوية شائعة لخالد بن هلال بن ناصر العبري]{.ar}

