# Modifying ;sca; to sound like a vernacular dialect {#sec-vern}

;wip_warn;

;sca; is not typically used in informal settings.
Rather Arabs use their native modern vernacular dialects in everyday settings.
For the student of Arabic,
in order to fit in,
and not seem overly formal in these settings,
it's not a bad idea to learn a vernacular dialect.
Which vernacular dialect you should learn can depend on
where you think you would be using your spoken Arabic.
The Egyptian, Levantine, and Urban [#hijAzi]{.trn2} dialects cover a wide strata of the Arab population
and,
in our opinion,
learning any one of these would be useful.

But if you don't find yourself having enough time to learn both ;sca; and a dialect,
you can water down your spoken ;sca; to sound more like a vernacular.
Here are some tips to do this:

1. Soften the semi-vowels. Examples:

   |Word | pronunciation in exact ;sca; | pronunciation in watered down ;sca; |
   |:----|:----|:----|
   |[بَيْت]{.ar} | [bayt]{.trn} | _beyt_

2. Replace middle and end hamzahs by their seat letters. Examples:



3. Drop the case endings. Example:


   The [ن]{.ar} of the ;ustate; plural masculine ;mudarie; verb is also a case ending so it too is dropped.

   Drop also the final fathah of the singular masculine ;madi; verb.

4. Use only [ين]{.ar} [In]{.trn} instead of [Una]{.trn}/[Ina]{.trn} for the sound masculine plural.

5. For ;mudarie; verbs where the second letter has a sukoon, convert yaf3al to yif3al and taf3al to tif3al.

5. Use only [ما]{.ar} and [لا]{.ar} for negation, never [لم]{.ar} or [ليس]{.ar}.

5. Use the plural masculine verb instead of the dual verbs and the feminine plural verb.

6. Drop ;an; before the ;astate; ;mudarie; verb.


7. Learn the vernacular words for:

   * The verb [to go]{.trans}
   * The verb [to want]{.trans}
   * The verb [to bring]{.trans}
   * The question nouns:

TODO: add examples

